### ISSUE TITLE
Spinning forts (Geting items only on the first fort)

### ISSUE THREAD

**Issue by fsimchen** [PokemonGoF/PokemonGo-Bot#100]
Geting items only on the first fort, nothing found on the others,

Found fort 43b00bd26bec49edb42cc250e7f7525b.16 at distance 786.551530419m
Need to move closer to Pokestop
Arrived at Pokestop
Now at a Pokestop: Spinning...
- Loot:
- 50 xp
- 1x Pokeball
- 1x Razz Berry
- 1x Greatball

Found fort 40141160e54546a4af673f61cd5ea6aa.16 at distance 47.8673628317m
Need to move closer to Pokestop
Arrived at Pokestop
Now at a Pokestop: Spinning...
- Loot:
- 0 xp
- Nothing found.

may search too often, lets have a rest
need a rest

**Comment by douglascamata** [comment]
Please, update your code from upstream for a new possible softban detection  and try again. It looks like you got softbanned.

**Comment by fsimchen** [comment]
I can catch pokemons on the phone.

Download all again and same problem.

looping: step 1 of 100
steplimit: 100 x: 0 y: 0 pos: 1 dx: 0 dy -1
(45.0303262, -93.319313, 0)
Found fort 43b00bd26bec49edb42cc250e7f7525b.16 at distance 786.551530419m
Need to move closer to Pokestop
Arrived at Pokestop
Now at Pokestop: Thomas Hollingsworth Park - Spinning...
- Loot:
-  xp
- 1x Pokeball
- 1x Pokeball
- 1x Super Potion
- 1x Razz Berry
PokeStop on cooldown. Time left: 1469146393
Something rustles nearby!
Found fort 40141160e54546a4af673f61cd5ea6aa.16 at distance 47.8673628317m
Need to move closer to Pokestop
Arrived at Pokestop
Now at Pokestop: George Carols Henson Memorial - Spinning...
- Loot:
- Nothing found.
Oops, Exception, have a rest then.
looping: step 1 of 100
steplimit: 100 x: 1 y: 0 pos: 1 dx: 1 dy 0
(45.032826199999995, -93.319313, 0)
Found fort 40141160e54546a4af673f61cd5ea6aa.16 at distance 47.8673628317m
Need to move closer to Pokestop
Arrived at Pokestop
Now at Pokestop: George Carols Henson Memorial - Spinning...
- Loot:
- Nothing found.
Oops, Exception, have a rest then.
looping: step 1 of 100
steplimit: 100 x: 1 y: 1 pos: 1 dx: 0 dy 1
(45.032826199999995, -93.316813, 0)
Oops, Exception, have a rest then.

**Comment by douglascamata** [comment]
Ok, let me do one thing. Just a minute.

**Comment by douglascamata** [comment]
@fsimchen run a `git pull origin master` inside your PokemonGo-Bot folder to update the code, try again and look the error message.

**Comment by fsimchen** [comment]
Seem to work now, thanks for the help!

**Comment by fsimchen** [comment]
Again, I pasted the log on pastebin.

http://pastebin.com/076u02x3

**Comment by Lenovotro** [comment]
This is the same issue I get. Though it doesn't appear I really am soft-banned. Same log. Works for about 10 seconds, then shuts down.

**Comment by surfaace** [comment]
please confirm if this issue persists in latest DEV branch

**Comment by dmateusp** [comment]
issue persisting, using latest dev branch.

As described, it spins only the first fort

![may search too often](https://cloud.githubusercontent.com/assets/8832050/17095482/959366e4-524c-11e6-85e4-771cf5fcc754.PNG)

**Comment by dmateusp** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/pull/775 might fix it hopefully !

**Comment by surfaace** [comment]
bugfix for #775 in fb2cca3b1f701653d58424f49a2ba7fae5cd97e9

please clarify if issue is resolved

**Comment by dmateusp** [comment]
Tests done, teleporting might have been the cause of soft bans that would cause this behavior.

Spinning is working for me
