### ISSUE TITLE
Bot catch one or two pokemons and go to farm

### ISSUE THREAD

**Issue by crusardri** [PokemonGoF/PokemonGo-Bot#1003]
### Expected Behavior

Farm while catch pokemons

### Actual Behavior

catch one or two pokemons and go to farm (bot mode still in all)

### Other Information
OS: Windws 10
Git Commit:  8964c0a

Older commits catch pokemons correctly

**Comment by hero16** [comment]
same observation here. i'll try a non "all" mode and see

**Comment by hklcf** [comment]
#949

**Comment by AndyBean** [comment]
#821

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
