### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by rui-ribeiro** [PokemonGoF/PokemonGo-Bot#1005]
### Expected Behavior

Delete unnecessary items. Like revives or initial potions.

### Actual Behavior

Infinite loop

### Steps to Reproduce

If you don´t have pokeballs or great balls the bot will go with farm mode but if you have the inventory is full the bot swithc to poke mode. Infinite loop

### Other Information
OS:  Linux
Git Commit: 3aca6d798f8a3e173dce0beb7b13c9505cc5b251

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
