### ISSUE TITLE
Cannot Start Script

### ISSUE THREAD

**Issue by Drambuie** [PokemonGoF/PokemonGo-Bot#1007]
Have following the installation instructions, and created the config.json

But when i got to run the script I get the following error

[07:59:15] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 250, in <module>
    main()
  File "pokecli.py", line 229, in main
    config = init_config()
  File "pokecli.py", line 57, in init_config
    load.update(json.load(data))
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 22 column 7 (char 586)

The config file i am using is as follows (I have blanked my username password and google api key but they are configured)

Any sugguestions would be appriciated

{
    "auth_service": "ptc",
    "username": "#########",
    "password": "#########",
    "location": "51.527562, -0.124647",
    "gmapkey": "#########",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "",
    "evolve_all": "NONE",
    "cp_min": 300,
    "use_lucky_egg": false,
    "evolve_captured": false,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      // "Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      // "Rattata": { "always_release" : true }
    }
}

**Comment by yaosichao0915** [comment]
try the command like this : python pokecli.py -cf configs/config.json

**Comment by thehawkes** [comment]
comments aren't allowed in json files

> {
"auth_service": "ptc",
"username": "#########",
"password": "#########",
"location": "51.527562, -0.124647",
"gmapkey": "#########",
"max_steps": 5,
"mode": "all",
"walk": 4.16,
"debug": false,
"test": false,
"initial_transfer": 0,
"location_cache": true,
"distance_unit": "km",
"item_filter": "",
"evolve_all": "NONE",
"cp_min": 300,
"use_lucky_egg": false,
"evolve_captured": false,
"catch": {
"any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"}
},
"release": {
"any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"}
}
}

should work

**Comment by TCB13** [comment]
Yes, I've been over this "issue" before at #966. Most people forget that JSON does not support comments and we should be careful with colons...

**Comment by Drambuie** [comment]
thanks for the advice, it seems in the config.json.example // exists in the catch and release section

Removed this and it is working

**Comment by mehdi-S** [comment]
readme or config.json.exemple needs to be updated to avoid other "issue" like this

**Comment by AndyBean** [comment]
This error even occurs with the latest pull and the updated sample config (now with no comments).

```
(PokemonGo-Bot) ab-mac:PokemonGo-Bot andybean$ python pokecli.py -cf config.json
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 197, in main
    config = init_config()
  File "pokecli.py", line 61, in init_config
    load.update(json.load(data))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
Barebones config:
```
{
    "auth_service": “ptc”,
    "username": “xxx”,
    "password": “xxx”,
    "location": “xxx”,
    "gmapkey": "xxx",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104",
    "evolve_all": "NONE"
}
```

**Comment by VictorChen** [comment]
@AndyBean you need to fix your double quotes, see http://jsonlint.com/ to validate your json

**Comment by AndyBean** [comment]
stupid text editor changing my quotes. Good catch.
