### ISSUE TITLE
Dev Build: Empty/Unkown Pokestops Spin

### ISSUE THREAD

**Issue by TheGoGlider** [PokemonGoF/PokemonGo-Bot#1013]
### Expected Behavior
Collect from pokestop and continue to walk.

### Actual Behavior
Goes to few pokestops, works fine, after a while shows [this](http://imgur.com/a/kEECB) and continues doing that until I restart.

### Steps to Reproduce
One way to fix is to keep restarting the bot every five minutes  which can be super annoying or just wait for a fix.

### Other Information
OS: Windows 10 B4-bit
Git Commit: 8462fb2a699b1c46e166d7917b0d59cc244264ec

**Comment by LasseSkogland** [comment]
The login token has expired, in newer commits this should be addressed, try `git pull` or redownload from github.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
