### ISSUE TITLE
Bot unnecessarily walks to center of Pokestops

### ISSUE THREAD

**Issue by bstpierr** [PokemonGoF/PokemonGo-Bot#1018]
This issue may also increase detectability since it's unlikely that users would walk to the exact center of every stop they visit.

Also, most stops are spinnable from the road or other more accessible place. Once we start following roads, this will need fixed.

### Expected Behavior

Bot should walk to anywhere within the range of the stop.

### Actual Behavior

Bot walks to exactly the center of a stop.

### Steps to Reproduce

Run the bot and observe its path.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
