### ISSUE TITLE
Crash spinning stops

### ISSUE THREAD

**Issue by bgrimm** [PokemonGoF/PokemonGo-Bot#1024]
### Expected Behavior
Not crashing

### Actual Behavior
crashes
  File "C:\Temp\dev\pokemongo_bot\cell_workers\seen_fort
_worker.py", line 76, in work
    id_filter = self.config.item_filter.get(str(item_id), 0)
AttributeError: 'list' object has no attribute 'get'

### Steps to Reproduce
start bot, captures pokes ok, then crashes after spinning while processing loot

### Other Information
OS:  windows 7
0ebdfc0fe6d23898f47db0674cf892b060a0e06b

**Comment by asaf050** [comment]
Same here

**Comment by ayiire** [comment]
Did you update the config to include the new item filter changes?

    "item_filter": {
      "1": { "keep" : 100 },
      "101": { "keep" : 10 },
      "102": { "keep" : 30 },
      "103": { "keep" : 30 },
      "201": { "keep" : 30 },
      "701": { "keep" : 100 }
},

**Comment by bgrimm** [comment]
I am not using any filtering, so using old blank or new change makes no difference.
(tried with updated item filter line and my blank:      "item_filter": "",

**Comment by Nurvx** [comment]
Experiencing the same symptom. Also on the dev branch.

**Comment by ayiire** [comment]
Does the filter need the two { } then when not using it? The previous configs did not have that.

**Comment by Nurvx** [comment]
I copied over the new item_filter into my config.bot1.json and set values that I wanted to each item and it works. There needs to be code that determines if there are no items to filter that it ignores the recycling feature (i.e. "item_filter": {})

**Comment by ayiire** [comment]
Did you include all the other items (Other balls, potions) in your filter? I copied over the example and it eventually still crashed

**Comment by Nurvx** [comment]
@ayiire I opened up the config.json.example and pasted what was in there for "item_filter" into my own config and left the items as is, didn't remove or add any extra. I only changed the default "keep" values.

**Comment by bgrimm** [comment]
I still crash, tried the example config.json just plugging in my login info only and it still goes to first stop and crashes.

**Comment by Nurvx** [comment]
@bgrimm The bot is still running for me with no crashes since my last post. I have not pulled anything in the last hour. When you crash, are you receiving the same output log as OP?

**Comment by bgrimm** [comment]
@Nurvx : I tried again, (example json file with my creds and example item_filter) and now it did work, so has to be something in (my) config. 
It has successfully spun 2 stops and recycled items to filter value without crash. 

So likely my issue, not code, if it now stable for everyone else stating they had similar problem.

**Comment by Nurvx** [comment]
@bgrimm I'm glad it is working for you now. Once the recycle items feature is **optional** and not mandatory, then I would deem it as stable. I wish I knew git well enough to help out. I know that sounds terrible, but I've never made a commit/push or however it's done properly.

**Comment by surfaace** [comment]
added missing load code in 07e028292881677c06e1ded51e021d1a8cc9e68f
