### ISSUE TITLE
Progress Bar Not Completing & Output Formatting Issue

### ISSUE THREAD

**Issue by Nurvx** [PokemonGoF/PokemonGo-Bot#1028]
### Expected Behavior
Expected progress bar to be 100% when arriving at PokeStop. Also expected the next logged item to have a carriage return after the progress bar.

### Actual Behavior
Progress bar does not complete. No carriage return for following logged entry.

### Steps to Reproduce
Run bot and let it arrive at a PokeStop. See screenshot.

### Other Information
OS: Mac

<img width="554" alt="screen shot 2016-07-26 at 2 18 00 pm" src="https://cloud.githubusercontent.com/assets/6528118/17150140/4cd71d24-533c-11e6-89d2-2cf75503beb0.png">

**Comment by VictorChen** [comment]
hmm maybe related to this change where it doesn't walk to the center anymore? https://github.com/PokemonGoF/PokemonGo-Bot/pull/1025

**Comment by Nurvx** [comment]
@VictorChen A progress bar would not make sense if the bot will not be stopping exactly at final destinations (where it seems to be caring about). I actually preferred the approx. time the bot used to have. Using the approx. time, I could visually/mentally figure where it is based on log time stamp.
