### ISSUE TITLE
Bot shouldn't stop if it detects soft ban

### ISSUE THREAD

**Issue by aconite33** [PokemonGoF/PokemonGo-Bot#103]
I noticed in the latest update that the bot stops all together. I've plugged in a 15 second sleep in between pokestop swipes and it's consistently stopped me from getting softbanned. Can we add a interval timer so avoid softban instead of just quitting all together?

**Comment by tstumm** [comment]
Well increasing the sleep is a good solution (and was also proposed in serveral other issues). Stopping when a softban is detected is a good solution. I don't see any advantages in keeping it running.

**Comment by surfaace** [comment]
its better for bot to close instead of running with an open session just because if something is tracked
