### ISSUE TITLE
Weird path

### ISSUE THREAD

**Issue by BartKoppelmans** [PokemonGoF/PokemonGo-Bot#1030]
### Expected Behavior
The bot should walk in a way that explores a radius or block around the starting location.

### Actual Behavior
It walks across the following, weird path:
![Imgur](http://i.imgur.com/0ooNqJ1.png)

I'm afraid that the bot is trying to summon some kind of demon...
### Steps to Reproduce
Start the bot in 'poke' mode with `max_step: 5`

### Other Information
OS: `Windows 10, 64bit`
Git Commit: 9d52654c2491c92374374877cd75de7a292fb65e

**Comment by jaerak** [comment]
Same exact shaped formed for me as well, using "poke" mode

**Comment by BartKoppelmans** [comment]
They're communicating... @jaerak 😨

**Comment by Arderos** [comment]
Same shape here

**Comment by BartKoppelmans** [comment]
Problem is not yet fixed on the dev channel. I couldn't find anything too weird in the code. Somebody else found anything odd?

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
