### ISSUE TITLE
Farming can attempt to recycle '0' items.

### ISSUE THREAD

**Issue by twaffle** [PokemonGoF/PokemonGo-Bot#1036]
### Expected Behavior
  Recycle anything over your specified maximums

### Actual Behavior
  Recycle can try to trigger the deletion of 0 items, if the number you have is exactly what is specified

###
  Fix:

--- a/pokemongo_bot/cell_workers/seen_fort_worker.py
+++ b/pokemongo_bot/cell_workers/seen_fort_worker.py
@@ -77,7 +77,7 @@ class SeenFortWorker(object):
                         if id_filter is not 0:
                             id_filter_keep = id_filter.get('keep',20)
                         new_bag_count = self.bot.item_inventory_count(item_id)
-                        if str(item_id) in self.config.item_filter and new_bag_count >= id_filter_keep:
+                        if str(item_id) in self.config.item_filter and new_bag_count > id_filter_keep:
                             #RECYCLE_INVENTORY_ITEM
                             items_recycle_count = new_bag_count - id_filter_keep
                             logger.log("-- Recycling " + str(items_recycle_count) + "x " + item_name + " to match filter "+ str(id_filter_ke

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
