### ISSUE TITLE
Several attempts needed to switch modes because of full inventory

### ISSUE THREAD

**Issue by kennycoc** [PokemonGoF/PokemonGo-Bot#1044]
### Expected Behavior
As soon as the inventory is full, the bot switches to catch mode

### Actual Behavior
The bot says it is switching to catch mode, and then finds another fort to farm.
This happens several times before eventually switching successfully. (between three and six times)

### Steps to Reproduce
attempt to farm pokestop with full inventory

### Other Information
OS: 
3aca6d798f8a3e173dce0beb7b13c9505cc5b251

![image](https://cloud.githubusercontent.com/assets/4149002/17153718/84160870-5343-11e6-9061-de8cf44392d2.png)

**Comment by TheGoldenXY** [comment]
@kennycoc Please try updating to the latest `master` branch.

**Comment by kennycoc** [comment]
This issue is still occurring after pulling down the latest commits

On Version:
9ea015e1fd9c5d269276de8a8e822ee8eb0afa0f

**Comment by kennycoc** [comment]
Also, I just realized my initial message is not clear. It does eventually successfully switch to catch mode properly, it just takes several attempts.

It takes somewhere between four and six attempts to switch modes.

I've updated the initial comment to make this more clear.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
