### ISSUE TITLE
Logging in debug mode defect 

### ISSUE THREAD

**Issue by koppa** [PokemonGoF/PokemonGo-Bot#1050]
### Expected Behavior
See log.debug(...) calls

### Actual Behavior
setLevel of logging library not correctly set

### Fix

The code in __init__.py must be:

            logging.getLogger("pgoapi.pgoapi").setLevel(logging.DEBUG)
            logging.getLogger("pgoapi.rpc_api").setLevel(logging.DEBUG)

Insead of

            logging.getLogger("pgoapi.pgoapi").setLevel(logging.DEBUG)
            logging.getLogger("pgoapi.rpc_api").setLevel(logging.DEBUG)

**Comment by TheGoldenXY** [comment]
@koppa The code snippets above is both identical. If you really are experiencing any issues, please open a new issue with more specific information.

/closed
