### ISSUE TITLE
Bot does not work TabError

### ISSUE THREAD

**Issue by srknkrn** [PokemonGoF/PokemonGo-Bot#1052]
`Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/Users/Serkan/PokemonGo-Bot/pokemongo_bot/__init__.py", line 85
    gyms = [gym for gym in cell['forts'] if 'gym_points' in gym]
                                                              
TabError: inconsistent use of tabs and spaces in indentation`

I can't run bot with "python pokecli.py" on OS X, when I try I did get error message on above. I tried many things (I tried run even with no-change configs file for some encoding problems etc.) but still can't solve problem

### Other Information
OS: OsX El Capitan
Python Version: 3.5.1
I use master version 9ea015e1fd9c5d269276de8a8e822ee8eb0afa0f

**Comment by TheGoldenXY** [comment]
@srknkrn Please run this command: `git log -n 1 --pretty=format:"%H"` and tell me your result.

**Comment by srknkrn** [comment]
Thank your for your interest @TheGoldenXY . 
The result is 3aca6d798f8a3e173dce0beb7b13c9505cc5b251

**Comment by srknkrn** [comment]
I solved the problem via downgrade of Python version to 2.7
