### ISSUE TITLE
--Steps does not work

### ISSUE THREAD

**Issue by iDervy** [PokemonGoF/PokemonGo-Bot#106]
I see you've just added a --Steps function. Decided to try it out for Pokestops, it does not work. Here's the long/lats for you to check out. 

```
looping: step 1 of 4
steplimit: 4 x: 0 y: 0 pos: 1 dx: 0 dy -1
Walking from (51.4807245, -0.1532149) to (51.4807245, -0.1532149) for approx. 0.0 seconds
Finished walking
(51.4807245, -0.1532149, 0)
Found fort af137249c1644cd3b8c0f0cad3fd1578.12 at distance 1253.93940158m
Need to move closer to Pokestop
Walking from (51.4807245, -0.1532149) to (51.491205, -0.159886) for approx. 627.0 seconds
```

However, it seems to work if I'm not using the -s function, to spin PokeStops.

**Comment by PokemonGoF** [comment]
oh, need fix, I'll commit soon.

**Comment by PokemonGoF** [comment]
Should be fixed:
https://github.com/PokemonGoF/PokemonGo-Bot/commit/0db3b82529f427aa188eb3ed92649aa7ad41729a
