### ISSUE TITLE
[Crash] randomly every 30 minutes around

### ISSUE THREAD

**Issue by rednka** [PokemonGoF/PokemonGo-Bot#1060]
Hi , first I apologize for spelling , I use Google Translate for talking. Specifically I have an issue with PokemonGoBot when I run the script everything works , it captures me the Pokemon / pokéstop , walking & other .

But to get to a certain stage ( known to date) the script crash , forced to restart it's pretty annoying knowing that I would like it to work at night while I sleep for example.

I'm not really able to tell you what time it crash, being given that there is no record log.txt on my computer , it looks to be truly random .. Thanks in advance good job !

**Comment by buettner123** [comment]
@MeGaPk posted a good workaround for this: https://github.com/PokemonGoF/PokemonGo-Bot/issues/948#issuecomment-235229012

**Comment by rednka** [comment]
Hello, thanks for the return, i have creating a start.bat with this content :+1: `@echo off
:begin
python pokecli.py
goto begin`

i appreciate your help, thanks !

**Comment by TheGoldenXY** [comment]
@rednka That should work. If not, please use @MeGaPk's batch script:

`@echo off
:begin
python2 pokecli.py
goto begin`

**Comment by rednka** [comment]
The script wasn't crash this night, thanks, but i have rename "python2" by "python" in this start.bat to work, thanks have a nice day !
