### ISSUE TITLE
The speed to Evolve is too fast! Not like a human play!

### ISSUE THREAD

**Issue by xc-mezcal** [PokemonGoF/PokemonGo-Bot#1066]
### Expected Behavior
To Evolve a pokemon, it should use like 15-20 sec for animation, and then other stuffs. Let's say 23-30 sec, in total. 

This is not a human behaviour, need an option to slow down the evolve speed. Thanks!

### Actual Behavior
But the Bots just do it like instantly!

### Steps to Reproduce
Have lots of zubat and weedle in stock to evolve. Suppose to do them all for 30 mins, but finished them all in 5 min?

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by RiberoD07** [comment]
it sleeps for 3.7 seconds inbetween api call to evolve. you can change it manually. it's in .\cell_workers\evolve_all_worker.py
line 129
you can change it to whatever you want

**Comment by xc-mezcal** [comment]
Thanks!
