### ISSUE TITLE
Can't use a street address as Location

### ISSUE THREAD

**Issue by chadsaun** [PokemonGoF/PokemonGo-Bot#1070]
Because of [this line](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/__init__.py#L448) and stripping out spaces I can't use a street address with spaces.  It won't find the address.

It turns `123 East 123 North, City, State` to `123E123N,City,State`

**Comment by TheGoldenXY** [comment]
@chadsaun Please use the coordinates of that street address.

**Comment by chadsaun** [comment]
Well, yah, that would be the workaround.  But it sure would be nice to be able to use a street address, or anything else that Google Maps can search and find.

**Comment by linanqiu** [comment]
http://stackoverflow.com/questions/3652951/google-maps-api-get-coordinates-of-address

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
