### ISSUE TITLE
[Error] After PokeStore visiting AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by Zgrkaralar** [PokemonGoF/PokemonGo-Bot#1073]
Hello, 

After visiting poke store showing this error.

` id_filter = self.config.item_filter.get(str(item_id), 0)
AttributeError: 'list' object has no attribute 'get'`

<img width="730" alt="screen shot 2016-07-27 at 1 53 22 am" src="https://cloud.githubusercontent.com/assets/879674/17158163/f17513c6-539c-11e6-9228-d07760583994.png">

### Other Information
OS: Ubuntu 14
Git Commit: 14e4d03e367d12ee601d9553253d254e78829dd7

**Comment by Zgrkaralar** [comment]
That is fix it on dev

**Comment by Zgrkaralar** [comment]
closed

**Comment by TheGoldenXY** [comment]
This issue has already been fixed in latest version.

Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
