### ISSUE TITLE
No module named geopy.geocoders

### ISSUE THREAD

**Issue by Caperous** [PokemonGoF/PokemonGo-Bot#1077]
I tried running this on Mac 10.9.5

After running the line `python pokecli.py` I run into the same issue and can't find a fix.

`Traceback (most recent call last):
  File "pokecli.py", line 37, in <module>
    from pokemongo_bot import PokemonGoBot
  File "/Users/Pikachu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 12, in <module>
    from geopy.geocoders import GoogleV3
ImportError: No module named geopy.geocoders`

I have checked and all files are there, `pip install -r requirements.txt` has been done.
Any help would be great.

EDIT: `pip install -r requirements.txt`

I am using dev

**Comment by ltsampros** [comment]
You mean `pip install -r requirements.txt`, right?

**Comment by Caperous** [comment]
That's what I meant, yes. 
I have tried an --upgrade to no prevail. Changed my API key.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
