### ISSUE TITLE
[Request] Display Pokemon inventory statistics in web viewer

### ISSUE THREAD

**Issue by lollan** [PokemonGoF/PokemonGo-Bot#1079]
### Expected Behavior

It would be nice to be able to see what Pokemon the bot has kept without having to use a phone.  Since I will often set the bot to roam in locations that are nowhere near my actual GPS location, this would avoid any softban issues by opening my phone to check on the status.

### Actual Behavior

Currently, the Web Viewer displays Trainer Pokemon and Pokedex statistics.  There is not a way (that I know of) to list all of the Pokemon in my current inventory, along with basic statistics like CP/IV/HP/Attacks

### Steps to Reproduce

Use the Web Viewer included with PokemonGo-Bot and select 'Trainer' on the right hand side.

**Comment by Orrielel** [comment]
Maybe tag the pokemon with a timestamp, with list stored locally in a JSON file?

**Comment by CadeBrown** [comment]
This is a feature in the dev branch. Switch to it for more features

**Comment by lollan** [comment]
Just pulled the latest dev branch.. you guys did a bang up job with these additions!!!
