### ISSUE TITLE
Random Shit chars in Dev branch when walking.

### ISSUE THREAD

**Issue by xc-mezcal** [PokemonGoF/PokemonGo-Bot#1081]
### Expected Behavior
I don't know. Should not be those char.

### Actual Behavior
[19:42:00] Pokemon Bag has been cleaned up!
[19:42:00]
[19:42:01] Starting PokemonGo Bot....
[19:42:01] Scanning area for objects....
[19:42:01] Walking from (37.787933, -122.4096922) to [37.787933, -122.4096922] 0.00km
[鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚
枅] 100%

### Steps to Reproduce
ALways appear in my setting.

### Other Information
OS: Windows Powershell

**Comment by TheGoldenXY** [comment]
Please run this command: `git log -n 1 --pretty=format:"%H"` and tell me your result.

**Comment by xc-mezcal** [comment]
@TheGoldenXY  
it returns:
9c99cc0de7e5b0c35762cae9b657c495d32e3ade

**Comment by TheGoldenXY** [comment]
@xc-mezcal Please update to the latest `dev` branch

**Comment by xc-mezcal** [comment]
@TheGoldenXY  Yup!

By the way, to update the least dev branch, I used git pull.  (cause git checkout dev didn't add new things to me, keep saying it's up to date)

But how to update the least master branch with git pull?
