### ISSUE TITLE
Need help. Hi guys im a beginner and have no idea on how to run the bot ( im using mac OS X El capitan ) 

### ISSUE THREAD

**Issue by divinesamuel** [PokemonGoF/PokemonGo-Bot#1086]
So i did the installation part and i think i did it successfully. Now im about to use the bot but have no idea on what am i suppose to do.. 
"1/ copy `config.json.example` to `config.json` and `release_config.json.example` to `release_config.json`.
2/ Edit `config.json` and replace `auth_service`, `username`, `password`, `location` and `gmapkey` with your parameters (other keys are optional, check `Advance Configuration` below)"

i dont understand that part and i attached a screenshot below
<img width="1280" alt="screen shot 2016-07-26 at 5 05 39 pm" src="https://cloud.githubusercontent.com/assets/20632355/17159675/e29a9ff4-5353-11e6-9976-5b9bd530a105.png">

**Comment by dontrebootme** [comment]
I would take the part in red as your issue.
```Login Error, server busy```

Try again later?

**Comment by TheGoldenXY** [comment]
@divinesamuel If you are logging in through PTC (Pokemon Trainer Club), there might be a chance that the servers is down. 

According to https://twitter.com/PoGoServer there are some issues with PTC in the Netherlands.

**Comment by divinesamuel** [comment]
i see.. but i didnt do this part yet "Edit config.json and replace auth_service, username, password, location and gmapkey with your parameters (other keys are optional, check Advance Configuration below)"" 

I literally don't know what it means by "Edit". what to edit and where? what does auth_service means? lol sorry im so noob XD

**Comment by TheGoldenXY** [comment]
@divinesamuel 
1. Please navigate to `configs/` and rename the configuration file from `config.json.example` to `config.json`.
2. Open the configuration file `config.json` and type in your username/gmail address, password and location. Leave the other parameters as default. Example shown below:
    
    If you are logging in with gmail address, use this example:
    `"auth_service": "google",
    "username": "yourGmailHere@gmail.com",
    "password": "password123",
    "location": "37.787994, -122.407440",`

    If you are logging in with a PTC (Pokemon Trainer Club) account, use this example:
    `"auth_service": "ptc",
    "username": "username",
    "password": "password123",
    "location": "37.787994, -122.407440",`

Remember to replace the parameters with your own values.

**Comment by divinesamuel** [comment]
ah i see.. okay i did that but it still gave me the same problem like "The location given using -l could not be parsed. Checking for a cached location." 
and then "Login Error, server busy" 

maybe i should try again later? 
Thanks btw!

**Comment by mrwbsn** [comment]
i think you have master branch version and your coordinate is have "-" in front of the numbers when try to run in your terminal, try to use -l parameter with name like `-l  British+Museum`, hope it will help.

**Comment by divinesamuel** [comment]
Hmm i think i did the instruction "change master to dev" and also i dont have "-" in front of the numbers.

Also, it is written on the instruction as below: 
__________________________________________________
Google login issues (Login Error, Server busy)?

Try to generate an app password and set is as

-p "<your-app-password>"
_________________________________________________

where should i type and put that ? sorry for keep asking stupid questions lol...
