### ISSUE TITLE
Possible bug with candy egg

### ISSUE THREAD

**Issue by TheGoldenXY** [PokemonGoF/PokemonGo-Bot#1087]
### Expected Behavior
Self explanatory.

### Actual Behavior
For some reason the bot evolved my pokemons without using a lucky egg. As you can see in the screenshot below, I did set the `use_lucky_egg` parameter to true. Any logical explanation to why the bot never used a lucky egg?
http://prntscr.com/bxy9k9

### Steps to Reproduce
Run the bot using my configuration settings above.

### Other Information
OS: Ubuntu, 14.04
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
3aca6d798f8a3e173dce0beb7b13c9505cc5b251

**Comment by codybaldwin** [comment]
This issue was caused by PR #1159 by the following addition to evolve_all_worker: 'skip_evolves = False

        if self.config.evolve_all:
            return skip_evolves'
this logic will return false every time the use_lucky_egg config is true. Causing the evolve to be skipped when a lucky egg is used.
