### ISSUE TITLE
Show coordinates

### ISSUE THREAD

**Issue by ayiire** [PokemonGoF/PokemonGo-Bot#1095]
Is it possible to still show the coordinates from the current to the next location?

[2016-07-26 16:36:28] [#] Walking from (40.7037, -74.012929) to (40.709641, -74.010338) for approx. 4.15 minutes

**Comment by TheGoldenXY** [comment]
@ayiire Can you please be more specific? Do you want to know the location of your bot in real-time? If so, then you can just use the map here https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#how-do-i-use-the-map

**Comment by ayiire** [comment]
Yeah, I also use the map. Still trying to figure out how to get the new map to work so I'm using a older map release. It seems like they restructured it. I can't get my API key to work as it loads a white page even though I filled in everything in the userdata.json. (I'm just opening up the html, not trying to serve it)

It's just weird that the coordinates and ETA time were removed from the console screen, guess it was too cluttered?

**Comment by TheGoldenXY** [comment]
Please try using the latest version. Lots of tests were conducted. It should be really improved.

Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
