### ISSUE TITLE
All i get is fleeing?

### ISSUE THREAD

**Issue by IAmTipsy** [PokemonGoF/PokemonGo-Bot#11]
Once i stopped the first run, then all i get now is:
{"responses": { "CATCH_POKEMON": { "status": 3 } } 

I know it means flee, though it's the only response i get.. 

`2016-07-21 10:38:15,938 [    pgoapi] [ INFO] Create new request...
2016-07-21 10:38:15,938 [    pgoapi] [ INFO] Adding 'CATCH_POKEMON' to RPC request including arguments
2016-07-21 10:38:15,939 [    pgoapi] [ INFO] Execution of RPC
2016-07-21 10:38:16,266 [    pgoapi] [ INFO] Cleanup of request!
Response dictionary: 
{
  "unknown2": 8145806132888207460, 
  "direction": 1, 
  "auth_ticket": {
    "expire_timestamp_ms": 1469092097186, 
    "start": "eDgMNcKL0UfQYKMgEnJ+2Yc79f1LDlaMprhis528FM8uhgDa9dO1+PlHpN9HLjgwZHsiEOOysPX/\n+NAm6G7c+Encp0cRqg1X5umhT7+bhLo=\n", 
    "end": "V5J3qbUWRy8AwL8XoSzCZA==\n"
  }, 
  "responses": {
    "CATCH_POKEMON": {
      "status": 3
    }
  }
`

**Comment by MtDubious** [comment]
Probably a 30 min soft ban for teleporting too far. Make sure the location you set isn't too far away from it's last known position. The game doesn't like people teleporting around too far.
