### ISSUE TITLE
line not found

### ISSUE THREAD

**Issue by Tom-Neverwinter** [PokemonGoF/PokemonGo-Bot#1103]
Documentation is incorrect

"Comment out following line: root /var/www/html; and change it to the web folder of your PokemonGo-Bot: eg:

/home/user/dev/PokemonGo-Bot/web;"

actually looks like; http://pastebin.com/sjQXHPFX on Ubuntu 14.04 LTS
(root /var/www/html; is not in this file)

**Comment by banksymate** [comment]
Depends on your nginx config, just change the line that says:
        root /usr/share/nginx/html;

**Comment by Tom-Neverwinter** [comment]
added commit covering both. https://github.com/PokemonGoF/PokemonGo-Bot/pull/1107
