### ISSUE TITLE
-h doesn't work in the command line -> little bit confusing

### ISSUE THREAD

**Issue by AlexHartveld** [PokemonGoF/PokemonGo-Bot#1104]
### Expected Behavior
pokecli.py -h should give a list of the commands

### Actual Behavior
pokecli.py -h crashes but 
pokecli.py by itself gives the help needed. 

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by banksymate** [comment]
You didn't provide OS or the commit, or any steps to reproduce.
I was able to run those same commands perfectly fine on my server.

**Comment by TheGoldenXY** [comment]
@AlexHartveld Please run `git log -n 1 --pretty=format:"%H"` and show me your output.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
