### ISSUE TITLE
Make `print` output to a text file as well  

### ISSUE THREAD

**Issue by TopOneOfTopOne** [PokemonGoF/PokemonGo-Bot#1111]
It would be nice if we get a log file with all the text that was printed to terminal/command prompt.

Thank you for all your hard work :)

**Comment by kriswong** [comment]
If you want to just add a `>log1.out` at the end of your command.  Better yet use this...

`nohup python pokecli.py -cf xxx.json&>log1.ou&`

That will right output to a file for review...

**Comment by TheGoldenXY** [comment]
Solution above. Closing this.

/closed
