### ISSUE TITLE
Bugs in pokemon_catch_worker?

### ISSUE THREAD

**Issue by xc-mezcal** [PokemonGoF/PokemonGo-Bot#1121]
### Expected Behavior
    def _get_catch_config_for(self, pokemon):
        catch_config = self.config.catch.get(pokemon)
        if not catch_config:
            catch_config = self.config.catch.get('any')
        return catch_config

### Actual Behavior

    def _get_catch_config_for(self, pokemon):
        catch_config = self.config.catch.get(pokemon)
        if not catch_config:
            catch_config = self.config.catch.get('any')
        if not catch_config:
            catch_config = {}
        return catch_config

### Other Information

It should return the setting given by "any" instead of return {} for a "unspecified" pokemon.

BTW, I don't know how to do pull request or commit things, any one can help me out? Many thanks!

**Comment by hklcf** [comment]
fork -> edit -> submit PR (pull request)

**Comment by xc-mezcal** [comment]
Thanks for helping!
