### ISSUE TITLE
[Request]Release unwanted pokemons when pokemon bag is full

### ISSUE THREAD

**Issue by RenKelvin** [PokemonGoF/PokemonGo-Bot#1128]
### Expected Behavior
Release low cp or low iv pokemons when bag is full

### Actual Behavior
Stop catching

### Steps to Reproduce
Catch when bag is full

### Other Information
OS: macOS
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by karanjthakkar** [comment]
@RenKelvin This is something thats already available. What is your `config.json` and `release_config.json`?

**Comment by alexFab** [comment]
the "initial release" of pokes doesn't work at the moment 8f0bacebcd172727f7e6ccd8e8861d4d47c7937c

running the dev with default config. one day ago it works fine.
