### ISSUE TITLE
Always struct.error: integer out of range for 'Q' format code

### ISSUE THREAD

**Issue by adesuluh** [PokemonGoF/PokemonGo-Bot#1129]
i've update to v1.1, and seems in stepper.py cause this, anyone can help ?
http://imgur.com/a/KEtAF

update : location "-7.xxx, 122,xxxx"
then i erase - sign it succes but it takes 3000098 seconds to evolve pokemon
i know its not my position but is it about the sign - ?

**Comment by adesuluh** [comment]
@dorklord it fixed but then there's traceback http://imgur.com/a/rD6Bs

**Comment by dorklord** [comment]
yep this one 
https://github.com/PokemonGoF/PokemonGo-Bot/pull/1130/commits/01ca304cc137ec96ef6aa91fe45cad49221a944b
took care of that error

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```
