### ISSUE TITLE
[REQUEST] Add maximum capacity for item

### ISSUE THREAD

**Issue by dionalfa** [PokemonGoF/PokemonGo-Bot#1131]
### Expected Behavior
After get certain amount of item, the next item will be discarded.
Example:
Razberry - 100 in bag
Treshold 100 
Then If trainer spin the poke stop, and get the razberry again, it will be discard rather then being keep.

### Actual Behavior
Current condition is always keep not filtered item. 

### Steps to Reproduce
-

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by TJSoler** [comment]
I guess you are using master?

Dev's item filter works like this:

```
 "item_filter": {
      "1": { "keep" : 100 },
      "101": { "keep" : 10 },
      "102": { "keep" : 30 },
      "103": { "keep" : 30 },
      "201": { "keep" : 30 },
      "701": { "keep" : 100 }
    },
```
I'll keep whatever you want to keep. Don't know what are the plans to merge that into master though.

**Comment by dionalfa** [comment]
Yep, I am using master.
Thanks for the answer, I will close this issue
