### ISSUE TITLE
[REQUEST] Pop a lucky egg whenever it runs out.

### ISSUE THREAD

**Issue by AndreAbdel27** [PokemonGoF/PokemonGo-Bot#1132]
### Expected Behavior
As the title say. Right now i don't know a way of doing this rather than manually. 

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by RolfKoenders** [comment]
The same functionality could be used for 'incense'.

**Comment by Whosdaman** [comment]
Agree, would also like to see an "use_incense" command too, similar to how the "use_lucky_egg" one currently works
