### ISSUE TITLE
[SUGGESTION] Changing Location (Lat/Long) On the fly

### ISSUE THREAD

**Issue by JohnnyOmm** [PokemonGoF/PokemonGo-Bot#1133]
Just a cool suggestion. would be cool if you can type in a lat long combo ex.(35.739448091800757,-70.34589676194207) while the bot is running rather than have to close it and edit it in the config.json to go along well with my pokemon radar.

If not it's fine, thanks guys!

**Comment by hmate9** [comment]
I would discourage this. This teleporting behaviour will only lead to more bans.

**Comment by diabl0** [comment]
And how about not teleporting but just walking from one district/neighborhood to another.

**Comment by Laith** [comment]
also speed up or slow down
