### ISSUE TITLE
Pokemons with high ??? CP become very low-level (<100) when found/caught by bot

### ISSUE THREAD

**Issue by kenshin007** [PokemonGoF/PokemonGo-Bot#1139]
### Expected Behavior
Pokemon CP should be the same as if the user caught it through the official app.

### Actual Behavior
Noticed this many times now, whenever I use the pokemap to hunt for rare pokemons, I use the bot to catch it by using the coordinates as the starting point. It seems that if the pokemon's CP is high enough to have the ??? value when in-game, the bot catches it with a very low cp instead (less than 100). I was able to test this on 3 occasions already, caught a rare pokemon (e.g. dragonite) with account 1 using the bot which resulted to a very low cp. When I use another account (same level) to catch it (through the app), the CP is correct (which is usually 1k+).

Hopefully someone can figure out why this happens.

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by ironbishop** [comment]
I find low CP pokemons with the official app, too. There's a bit of randomness. Sometimes I catch a pidgey CP240, and minutes after, a CP10.

Can you go there both with official app and bot, at the same time, using same level accounts?

**Comment by kenshin007** [comment]
I thought that was the case too, but it happened enough times to me already to suspect that it's something to do with how the bot interacts with pokemons with very high CP. I got rare pokemons with suspiciously low CP (46 dragonite, 50+ arcanine and there were other rares that were immediately exchanged for candy!).

**Comment by fdelia** [comment]
I couldn't observe that. The CP are similar in my case.

**Comment by kenshin007** [comment]
@fdelia were you running the bot normally or were you starting your run from the coordinates of the pokemon? I wonder if it's an anti-cheat implementation that's causing it.

**Comment by fdelia** [comment]
I usually try to spot an area with rare pokemons with pokevision.com, then I run the bot normally from there. Rare pokemons don't have as high levels as others...

**Comment by MR-ScottH** [comment]
There is an anti-cheat mechanism that causes this, your previous location is stored on the phone when using the app, if you suddenly teleport from USA to Japan for example it does check to see if X -> Y is possible based on the last logged time and now.
