### ISSUE TITLE
[REQUEST] A WanderNavigator to wander within a specific radius

### ISSUE THREAD

**Issue by furrycoat21** [PokemonGoF/PokemonGo-Bot#1140]
### Expected Behavior
Bot Wanders in a certain radius with being able to use the --mode all

### Actual Behavior
I think the Max_Steps is supposed to do this, however when I set Max_Steps to 0, the bot stays at startup "Starting PokemonGo Bot...."  
If set to 1 the bot Returns to the starting location by teleporting (results in Soft Ban/App Crashing)

If Max_Steps is set to 1, and Walk is set to 0, bot teleports (results in Soft Ban)
If Max_Steps and Walk is set to 1, the bot stays at startup "Starting PokemonGo Bot...."  

### Other Information
It'd be nice to be able to specify a Radius in whatever the Distance Unit is, and the bot wanders within that radius collecting both PokeStops and Catching Pokemon. 

Using recent pull of Master Branch. Configs are default except for the changes made in Max_Steps/Walk (and obviously Login/API info)

**Comment by tstumm** [comment]
Setting walk to zero is like disabling walking at all. That is intentional.
Setting max_steps to zero is pointless, 1 would only spread across your current cell.

max_steps is like telling a maximum radius. The radius is max_steps * cell_width / 2 where the cell_width is approx. 0.0025 * 111000 = 277,... m

**Comment by furrycoat21** [comment]
Sounds correct. 
Thank you for the info on max_steps. I didn't clearly understand what it was. 

I do think that a WanderNavigator would be handy to have. It would allow you to farm in a specific area for certain pokemon that spawn there.
