### ISSUE TITLE
Keep getting "Login Error, server busy"

### ISSUE THREAD

**Issue by sarandafl** [PokemonGoF/PokemonGo-Bot#1144]
### Expected Behavior
Login an run bot.

### Actual Behavior
Can't login. Message provided: `Login Error, server bus`

### Steps to Reproduce
Latest master branch using a google account.

**Comment by topazas** [comment]
Same here

**Comment by tb87** [comment]
Have you setup a google app password and used that to authenticate with your google account?

**Comment by sarandafl** [comment]
No, but it was working fine up until yesterday.

**Comment by tloesch** [comment]
Same here.

Temp. Solution:
Restarting the bot until it works.

**Comment by ngkogkos** [comment]
Guys this is because of the servers having issues with PTC accounts probably.

**Comment by TheGoldenXY** [comment]
The PTC (Pokemon Trainer Club) servers might be offline. Please try to login later or use a gmail account instead.

/closed

**Comment by sarandafl** [comment]
@TheGoldenXY Please read, this is with a gmail account, not a PTC account.

**Comment by sarandafl** [comment]
What I find strange is, I only get this error on some google accounts. I have multiple config files and I start the bot using the config file for the account I want to use.

**Comment by yayat** [comment]
guys i have any problem, i use my vm ubuntu on digital ocean when i try to login and i have reponse  "Login Error, server busy" any body help??
