### ISSUE TITLE
Bot walks a very long distance and does nothing

### ISSUE THREAD

**Issue by MilkyPL** [PokemonGoF/PokemonGo-Bot#1155]
### Expected Behavior
Bot Should just work

### Actual Behavior
It walks from an unknown location (2.6e-322, 1e-322) to my specified location, which takes him approx. 1506154.00 seconds (418 hours).
`jakub@jakub-arch ~/PokemonGo-Bot> python2 '/home/jakub/PokemonGo-Bot/pokecli.py'`
`[2016-07-27 09:50:49] [x] PokemonGO Bot v1.0`
`[2016-07-27 09:50:49] [x] Configuration initialized`
`[2016-07-27 09:50:49] [x] Coordinates found in passed in location, not geocoding.`
`[2016-07-27 09:50:49] `
`[2016-07-27 09:50:49] [x] Address found: 53.7759291,20.3256168`
`[2016-07-27 09:50:49] [x] Position in-game set as: (53.7759291, 20.3256168, 0.0)`
`[2016-07-27 09:50:49] `
`[2016-07-27 09:50:52] [#] Username: hidden`
`[2016-07-27 09:50:52] [#] Acccount Creation: 2016-07-26 22:16:35.640000`
`[2016-07-27 09:50:52] [#] Bag Storage: 54/350`
`[2016-07-27 09:50:53] [#] Pokemon Storage: 1/250`
`[2016-07-27 09:50:53] [#] Stardust: 100`
`[2016-07-27 09:50:53] [#] Pokecoins: 0`
`[2016-07-27 09:50:53] [#] PokeBalls: 50`
`[2016-07-27 09:50:53] [#] GreatBalls: 0`
`[2016-07-27 09:50:53] [#] UltraBalls: 0`
`[2016-07-27 09:50:53] [#] -- Level: 1`
`[2016-07-27 09:50:53] [#] -- Experience: 600`
`[2016-07-27 09:50:53] [#] -- Experience until next level: 400`
`[2016-07-27 09:50:53] [#] -- Pokemon Captured: 1`
`[2016-07-27 09:50:53] [#]`
`[2016-07-27 09:50:53] [x] Starting PokemonGo Bot....`
`[2016-07-27 09:50:53] [#] Scanning area for objects (1 / 25)`
`[2016-07-27 09:50:53] [#] Walking from (2.6e-322, 1e-322) to (53.7759291, 20.3256168) for approx. 1506154.00 seconds`

### Steps to Reproduce
Start the bot with my config:
`{`
`    "auth_service": "ptc",`
`    "username": "hidden",`
`    "password": "hidden",`
`    "location": "53.7759291,20.3256168",`
`    "gmapkey": "hidden",`
`    "max_steps": 5,`
`    "mode": "all",`
`    "walk": 4.16,`
`    "debug": false,`
`    "test": false,`
`    "initial_transfer": 0,`
`    "location_cache": true,`
`    "distance_unit": "km",`
`    "item_filter": "101,102,103,104",`
`    "evolve_all": ""`
`}`

### Other Information
OS: Arch Linux
Git Commit: 3aca6d798f8a3e173dce0beb7b13c9505cc5b251

**Comment by VietAnhh** [comment]
Could it be this?

the negative sign in the longitude

"location": "53.7759291, -20.3256168",

**Comment by MilkyPL** [comment]
Nope, that way my bot would be somewhere on Atlantic Ocean. I want it to be in Olsztyn City in Poland.

**Comment by GithubSTC** [comment]
Same issue here. Bot worked on first Windows system with minimum requirements installed (Python 2.7.x, pip, git, protobuf 3). Tried it out on second Windows machine with same requirements, and gave similar error as denoted above:
"Walking from (2.57e-322, 5e-323) to (hidden, hidden) for approx. 1416793.00 seconds"
Again, tried it on first Windows system, and error still appears.

**Comment by CtrlAltDefeat94** [comment]
Same here on Ubuntu

**Comment by afro001** [comment]
jovobe comment here:
https://github.com/PokemonGoF/PokemonGo-Bot/issues/1039

This is a problem caused by an update in the pgoapi from tejado. It can easily be fixed by pinning the pgoapi pip to the "v1.1.0" tag. Change the first line in the requirements.txt in this way:
-e git+https://github.com/tejado/pgoapi.git@v1.1.0#egg=pgoapi
and update your pip with
pip install -r requirements.txt

**Comment by lepiscopien** [comment]
Fix for me Thx

**Comment by GithubSTC** [comment]
Work around works for me too. Thanks! :+1:

**Comment by MilkyPL** [comment]
Fixed, thank you. Closing
