### ISSUE TITLE
Login Error, anybody? 

### ISSUE THREAD

**Issue by divinesamuel** [PokemonGoF/PokemonGo-Bot#1162]
(PokemonGo-Bot) Divines-MacBook-Pro:PokemonGo-Bot divinesamuel$ python pokecli.py
[2016-07-27 02:35:31] [x] PokemonGO Bot v1.0
[2016-07-27 02:35:31] [x] Configuration initialized
[2016-07-27 02:35:31] [x] The location given using -l could not be parsed. Checking for a cached location.
[2016-07-27 02:35:32] Login Error, server busy

Any solution guys? Thanks 👍 
Also, i dont understand what's happening "location given using -l could not be parsed." 
What should i do??

**Comment by RolfKoenders** [comment]
I think the logging issue is due to the PokemonGO servers are at capacity. Retry couple of times?

**Comment by Zgrkaralar** [comment]
Please try to give location using config.json

P.S: Now my 15 bots are working perfectly :) i'm re login all not any problem

**Comment by divinesamuel** [comment]
@RolfKoenders I dont think so bro.. cuz ive been trying whole day and actually i havent run the bot yet so this is gonna be my first time. I think the problem is with the location but i have no idea.

@Zgrkaralar Wow! thats impressive! I did edit my config.json and put my location there but still showing that message i really dont know why..

Actually if you guys look at the "instructions" on this website it is written below: 
_______________________________________________
Google login issues (Login Error, Server busy)?

Try to generate an app password and set is as

-p "<your-app-password>"
This error mostly occurs for those who are using 2 factor authentication, but either way, for the purpose of security it would be nice to have a separate password for the bot app.
____________________________________________________________________________________

Do you guys know what does "generate an app password" and how do you set it? BIG THANKS!

**Comment by BoGnY** [comment]
Use this link to set application password: [https://security.google.com/settings/security/apppasswords?utm_source=OGB](url)
then use the application password in your config.json

;)

**Comment by ksawerykarwacki** [comment]
It says that this setting is not available on my account :(

**Comment by tanpaulus0605** [comment]
https://productforums.google.com/forum/#!topic/gmail/mqc2rVUZuWE

**Comment by TheGoldenXY** [comment]
If you receive a `Login Error, server busy` notification upon login, then the Pokemon Go servers seems to be offline or unstable. Please try again in an hour. If issue persists, open a new issue.

/closed
