### ISSUE TITLE
Initial transfer

### ISSUE THREAD

**Issue by DokterPhill** [PokemonGoF/PokemonGo-Bot#1174]
### Expected Behavior
Documentation says 'set to 1 if you want to transfer pokemon'

### Actual Behavior
Setting to '1' will make it transfer anything below 1.

Also, a suggestion: it would be pretty neat to exclude your top 6 from transferring, while the rest will be transferred.

EDIT: it does work though, setting it to 800 will transfer anything under 800 cp, but readme is misleading.
### Other Information
OS: w10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Drambuie** [comment]
Have you tried "initial_transfer": true,

**Comment by ironbishop** [comment]
@Drambuie , he's right, that's an integer, not a boolean, but the README is misleading

**Comment by IHOPETHISONEISNOTTAKEN** [comment]
He is indeed correct, it works using the configuration file but not through command-line.

**Comment by VictorChen** [comment]
The README is for master, this is the updated wiki: https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files

**Comment by ironbishop** [comment]
@VictorChen that page is wrong :) for exaple says "kilometers per hour" while it's "meters per second"

**Comment by TheGoldenXY** [comment]
The README file is currently outdated. It will soon be up-to-date. Looks like this issue has been resolved.

/closed
