### ISSUE TITLE
Idear for new initial transfer filter

### ISSUE THREAD

**Issue by Witzbold** [PokemonGoF/PokemonGo-Bot#1183]
Short Description:
It would be nice to have a filter for the initial transfer function. Up to now one can only go down to 1 pokemon that is kept. It would be nice to be able to change this value to 2 which will keep 2.
Furthermore it would be nice to be able to use the feature on specific pokemon. For example one wants to keep his Weedles with 10-300 CP but also wants to release his Pigeys with 300-500 CP

**Comment by VictorChen** [comment]
are you on master branch? this should be possible on dev through the release config

**Comment by TheGoldenXY** [comment]
This feature has alreaady been implemented in the latest `dev` branch.

/closed
