### ISSUE TITLE
[REQUEST] Softban lift

### ISSUE THREAD

**Issue by kotecekk** [PokemonGoF/PokemonGo-Bot#1187]
So, as some of us know, there is an easy way to lift softban:

walk to a pokestop, spin it and close it. You won’t be getting any rewards from it, however, doing so up to 40 times (or until you finally receive the rewards) will remove your soft ban.

This feature should be implemented.

**Comment by svista** [comment]
Great

**Comment by DimaVIII** [comment]
This is not true! It the soft ban is depending on your "jump" distance and can remain from 5 min to 4 hours. (Experts in bans, got a lot this and learn how to jump without getting a softban, but I will not post it public.)
The solution for the bot will be better like this:
If you don't get a rewards from pokestops (at least 2 pokestops need to be checked) logout for 5 min and try again.

**Comment by weknin** [comment]
I implemented what @svista said. Yet, didn't test if it works.

**Comment by PP19** [comment]
Dont implement that feature, it wont remove your softban, spinning 40 times just takes long enough to let it expire.

**Comment by kotecekk** [comment]
Spinnig 40 times will remove your soft ban.

**Comment by Whosdaman** [comment]
I just tested this myself and it is 100% accurate. Softban was completely lifted and activity returned to normal after spinning and exiting a Pokestop around 40 times.

**Comment by PP19** [comment]
This "feature" sounds like "Autoban"

**Comment by IQNeoXen** [comment]
Works perfectly well for me. Should be implemented imo.

**Comment by Whosdaman** [comment]
It is exactly 40 spins on the same pokestop. On the 40th spin, the pokestop will give you the items. We need to have this implemented asap in my opinion.

**Comment by VictorChen** [comment]
You know what else removes the soft ban? Just waiting a few minutes and restarting the bot...

**Comment by wandering7man** [comment]
Dont work if u across 5000km in 1 sec.

**Comment by MikeDX** [comment]
Is this legit? I feel like I need to test it. Would be great for when I want to teleport to the states to catch that elusive pokemon that's just appeared...

**Comment by IQNeoXen** [comment]
@wandering7man it actually does... just try it out ^^

**Comment by solderzzc** [comment]
Wow, is that real?  CC to @douglascamata @TheSavior

**Comment by MikeDX** [comment]
There is definitely something to this.

I had a bot running in new york, and decided to move it to australia after I caught two Tauro so that I could capture something new and try this out.

Upon restarting the bot, it did all the evolutions, then removed all dupes except the best two of each. - Well over 40 commands, but cannot remember the exact figure.

Once the bot started farming, it had no issues. Pokemon are being caught and stops are being spun.

So is it just 40 commands? 

Needs more testing, but interesting none the less.
