### ISSUE TITLE
No lure modules in inventory

### ISSUE THREAD

**Issue by silelmot** [PokemonGoF/PokemonGo-Bot#1189]
I wondered  why there are No lure modules in the inventory of the bot. 
Is this an error or wanted?

**Comment by vicch** [comment]
One possibility: it is called "Troy Disk". http://101pokemongo.com/wiki/Troy_Disk

**Comment by silelmot** [comment]
ok... 
 where to add this, that this must be fixed?

**Comment by maestroi** [comment]
you can add it inside ur config.json under items
@douglascamata please close this
