### ISSUE TITLE
[DEV] Evolve Captured

### ISSUE THREAD

**Issue by Foulwerp** [PokemonGoF/PokemonGo-Bot#1195]
### Expected Behavior
Catch a Pokémon
Check if it can be evolved, if so evolve it
Check release parameters and see if there are Pokémon, especially the evolved form, to release

### Actual Behavior
Catches Pokémon
Checks if it can be evolved, if so evolves it
Tries to release the unevolved form leave the evolved Pokémon in bag to take up space.

### Steps to Reproduce
Turn the setting to evolve when caught

### Other Information
OS:  Windows 10
Git Commit: 70e8d50d8ad3ed59dbf7b718d4cc98b168e957d6

**Comment by TheGoldenXY** [comment]
@Foulwerp Can you please be more specific?

**Comment by Calcyfer** [comment]
I think this sentence is more accurate as a title : 

> Tries to release the unevolved form leave the evolved Pokémon in bag to take up space.

**Comment by Foulwerp** [comment]
Okay. Bot catches a Pokémon, for example Pidgey, if it can evolve it does so right away. Then instantly tries to exchange Pidgey for candy not Pidgeotto . Pidgeotto then stays in your inventory taking up space. 

I would think that it would attempt to exchange the evolved form not the unevolved form after evolving, or at run through the Pokémon to see if any can be released based on configs.
