### ISSUE TITLE
i cant run it help me please

### ISSUE THREAD

**Issue by shrunkenolive** [PokemonGoF/PokemonGo-Bot#1196]
### Expected Behavior
i run pokecli.py but where i can see whats happening ?

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Ph4i1ur3** [comment]
I would recommend by filling this issue out more thoroughly.
Maybe include a screenshot. At the moment I have no idea what the problem your having even is

**Comment by shrunkenolive** [comment]
@Ph4i1ur3 i run pokecli.py how can i see whats happening

**Comment by shrunkenolive** [comment]
![ekran alintisi](https://cloud.githubusercontent.com/assets/20683441/17176943/a4dac666-5417-11e6-8e48-32092aa53531.PNG)

**Comment by shrunkenolive** [comment]
is it right ?

**Comment by Ph4i1ur3** [comment]
That looks like a developer end issue, If you downloaded one of the dev branches I would recommend downloading from the master branch

**Comment by shrunkenolive** [comment]
@Ph4i1ur3 ty for answer but im new and i didnt get it

**Comment by shrunkenolive** [comment]
do i need to change anything in release_config.json

**Comment by proesd** [comment]
did you pull from master ? i would recommend to clone dev instead. it works done for me.

**Comment by shrunkenolive** [comment]
i pulled from master but still same

**Comment by mehdi-S** [comment]
do you have edit config.json.exemple and rename it config.json before trying to launch ?

**Comment by shrunkenolive** [comment]
@mehdi-S yes i did

**Comment by shrunkenolive** [comment]
@mehdi-S i gave ss u can see it loggin in but doesnt work

**Comment by shrunkenolive** [comment]
fixed it by #1042

**Comment by mehdi-S** [comment]
solved by :

> change the first line of requirements.txt to this:
> `-e git+https://github.com/tejado/pgoapi.git@v1.1.0#egg=pgoapi`
> 
> and run pip install -r requirements.txt again
?

because another comment said that is not a fix a cause other crash
