### ISSUE TITLE
1+ Hour till Bot Dies

### ISSUE THREAD

**Issue by kriswong** [PokemonGoF/PokemonGo-Bot#1197]
### Expected Behavior
Bot continues to run

### Actual Behavior
Bot has a strange set of repeated commands and moves from 1 pokestop to another never ever actually spinning them or catching pokemon...

### Steps to Reproduce
Run Bot for more than 2 hour.

### Other Information
OS: 
Git Commit: (9ea015e1fd9c5d269276de8a8e822ee8eb0afa0f)

**Comment by tstumm** [comment]
Fixed in current `dev`
