### ISSUE TITLE
Simple Map error ?

### ISSUE THREAD

**Issue by rednka** [PokemonGoF/PokemonGo-Bot#1199]
Hi , sorry for the spelling I use google translation to you speak, so I used the PokemonGo -Bot and it works very well , thank you for that! But I saw that it was possible to follow live the movements of his trainer via the extension " single map" , I install the file in PokemonGo -Bot / web / and I change the userdata file. js ( aPI key , username .. ) then I created a .bat file with:
`python -m SimpleHTTPServer
`
When I go to localhost : 8000 is what I have an error with the google map :
http://image.noelshack.com/fichiers/2016/30/1469625792-simplemap.jpg

and cmd return :
http://image.noelshack.com/fichiers/2016/30/1469625794-erreur.jpg

But I think having good install , objects / catch Pokémon are clearly visible and updated, but the map really does not want to show my google API key and well valid ..

Thank you in advance and good job !

EDIT : It's work, my API Key was expired/not actived, thanks !
### Other Information
OS: Windows XP SP1
Chrome
Python 2.7.X
Git

**Comment by Ph4i1ur3** [comment]
Create blank files in the web folder named location-inreap@gmail.com.json and catchable-inreap@gmail.com.json

**Comment by rednka** [comment]
Thanks, i have no more error on the SimpleMap.cmd

But, the map is again blank. (during the loading web page it's work, and a few seconde after it's broken ! :()
