### ISSUE TITLE
[Suggestion] Pokeball Farm if no pokeball.

### ISSUE THREAD

**Issue by necrozis** [PokemonGoF/PokemonGo-Bot#12]
```
	if pokeballs = 0:
		farm pokestops until pokeballs >= [some number] then continue hunting
```

**Comment by eggins** [comment]
I've come in to go through and remove all massive JSON dumps - this is still a WIP and no where near ready.

I'm slowly going through and doing what I can. More than welcome to help out! I can merge updates in if you have done anything :)

**Comment by necrozis** [comment]
Add Pokemon Names code to Pull.
Edit this to "[Suggestion] Pokeball Farm if no pokeball."

**Comment by eggins** [comment]
@necrozis  just merged the pokemon name pulling.

Currently working on company website. Will come back to pokemon shortly.

**Comment by necrozis** [comment]
@eggins, this code print how many balls of each type in your inventory.
```
    api.get_player().get_inventory()
    response_dict = api.call()
    for item in response_dict['responses']['GET_INVENTORY']['inventory_delta']['inventory_items']:
        try:
            if item['inventory_item_data']['item']['item'] == 1:
                print('Poke Ball count: ' + str(item['inventory_item_data']['item']['count']))
            if item['inventory_item_data']['item']['item'] == 2:
                print('Great Ball count: ' + str(item['inventory_item_data']['item']['count']))
            if item['inventory_item_data']['item']['item'] == 3:
                print('Ultra Ball count: ' + str(item['inventory_item_data']['item']['count']))
        except:
            continue
```

**Comment by CharlesVu** [comment]
There will be the need to discard potions/revives/berries as well as the inventory might fill with these.
