### ISSUE TITLE
[Dev] Step_walker Error

### ISSUE THREAD

**Issue by Zgrkaralar** [PokemonGoF/PokemonGo-Bot#1204]
###  Step_walker Error
When starting bot directly show error

<img width="671" alt="screen shot 2016-07-27 at 5 14 40 pm" src="https://cloud.githubusercontent.com/assets/879674/17178356/d87dc45e-541d-11e6-8755-57ed0177c8c8.png">

### Other Information
OS: Ubuntu 14
Git Commit: 3a18aa57dfb67e2e09c207087cad6e5aa1867112

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest branch. You can do it by running this command:
```
git reset --hard
git pull -f
```

**Comment by Zgrkaralar** [comment]
@TheGoldenXY Not working

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
