### ISSUE TITLE
HowTo? Syntax config.json for multiple PoGo-Accounts

### ISSUE THREAD

**Issue by msm2k11** [PokemonGoF/PokemonGo-Bot#1207]
### Expected Behavior
How is the syntax to work with multiple PokemonGo-Accounts?

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by matrix14** [comment]
start 2 instances. First with --config ./configs/config_x.json and second same with config_y.json (where x and y are your name, and you have config files)

**Comment by mehdi-S** [comment]
by using multiple window with screen or tmux

**Comment by zenety** [comment]
@matrix14 Thanks, but only 1 bot shows up on the website. What do I need to do to fix that?

**Comment by msm2k11** [comment]
Yes i have now written a little bash-script like this and run it in a screen session

```
users="user1 user2 user3"
for line in ${users}; do
./cli.py --config config/config.json.${line} &
done
```

thanks guys

**Comment by TheGoldenXY** [comment]
Looks like this issue has been solved, closing this now.

/closed
