### ISSUE TITLE
Continuously detecting the same fort and never reaches it

### ISSUE THREAD

**Issue by Ozitiho** [PokemonGoF/PokemonGo-Bot#1209]
### Expected Behavior
When booted the bot will detect the nearest fort (pokestop) and walk towards it

### Actual Behavior
Every couple seconds the bot prints "Found fort" and appears to walk significantly slower

### Steps to Reproduce
No changes to config other than my login

### Other Information
OS: Linux Mint Rosa
Git Branch: Dev branch

![image](https://cloud.githubusercontent.com/assets/3775556/17179688/5fe644d8-541a-11e6-8b01-b4120ce9084f.png)

**Comment by zenety** [comment]
#1168 mentions this.

unequaled86 posted the fix.

**Comment by urbels** [comment]
About speed - Yes, it seems much slower than stable for me too even if it have the same speed as stable in config.

**Comment by Ozitiho** [comment]
Oh, #1168 fixed it for me too. Thanks.
