### ISSUE TITLE
walking hook

### ISSUE THREAD

**Issue by TSM-EVO** [PokemonGoF/PokemonGo-Bot#121]
walking hook
walking hook
walking hook
walking hook
walking hook
walking hook
walking hook
walking hook
walking hook
walking hook
walking hook
walking hook
walking hook
walking hook
walking hook
walking hook..

walking hook

logs are spamming 'walking hook' repeatedly. Is there a way to toggle this? It seems like a debug view that's not necessarily needed in master

**Comment by TheGoldenXY** [comment]
Please don't create unnecessary issues.

**Comment by CtrlAltDefeat94** [comment]
The 'issue' is real, the report however lacks some information..

I think he dislikes the spamming of "walking hook" throughout the log/output(which I agree with)

**Comment by TheGoldenXY** [comment]
Comment out this line https://github.com/PokemonGoF/PokemonGo-Bot/blob/429d114638c59e2b58d15e6eb6300ae49dcdf686/stepper.py#L26

**Comment by TSM-EVO** [comment]
That works, it has to be replaced with something though otherwise you get the error 'expected an indented block'

**Comment by CtrlAltDefeat94** [comment]
@TSM-EVO replace the print for "pass" (without quotes)

**Comment by dragonalvaro** [comment]
maybe we can add a dot '.' on every step instead a new line.

"walking hook.................................................."

**Comment by jtdroste** [comment]
This hook is removed in the dev branch.  If you want to fix it against master, comment out the line in stepper.py
