### ISSUE TITLE
Error when Scanning Area for objects

### ISSUE THREAD

**Issue by supershanesta** [PokemonGoF/PokemonGo-Bot#1210]
### Expected Behavior
Scan Area

### Actual Behavior
![untitled](https://cloud.githubusercontent.com/assets/20649126/17180351/fde3ea40-53d0-11e6-800d-a0288e3a6cf9.png)

### Steps to Reproduce
start the pokecli.py
Have proper config

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by TheGoldenXY** [comment]
What version are you using? Please run this command: `git log -n 1 --pretty=format:"%H"` and show me your output.

**Comment by davericher** [comment]
Getting the same

**Comment by supershanesta** [comment]
![pokemongo](https://cloud.githubusercontent.com/assets/20649126/17192992/d7d2190a-5405-11e6-891f-15ec8bb0918a.png)

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
