### ISSUE TITLE
[feature] Logging to file

### ISSUE THREAD

**Issue by matrix14** [PokemonGoF/PokemonGo-Bot#1211]
### Expected Behavior
In config, you can set logging on or off. And then it's logging to folder "logs", with filename "logs-$NAME-YYYY-MM-DD-HH-MM-SS".

### Actual Behavior
Bot isn't logging.

### Steps to Reproduce
...

### Other Information
OS: all
Git Commit: all

**Comment by alexanderrock** [comment]
Would be a great feature, because you don't need to use screen and you are able to review what happened.

**Comment by matrix14** [comment]
When I use screen and it crashed I don't know what happend because only what I see is "screen is terminating"... And I don't have idea how to have screen output to file and posibility to attach to screen.

**Comment by VictorChen** [comment]
pretty simple to do this with bash:

```
# run bot, output to console AND log.txt file
python pokecli.py | tee log.txt
```

**Comment by matrix14** [comment]
> pretty simple to do this with bash:

# run bot, output to console AND log.txt file
python pokecli.py | tee log.txt

Of course, but you also need run it in screen. If you run it normally it won't work. But now I have method to do that, but I think bot should have this feature.

**Comment by ph3l1x** [comment]
A logging option would be really nice! any plans to do this?
