### ISSUE TITLE
Where is config.json?

### ISSUE THREAD

**Issue by ankerbachryhl** [PokemonGoF/PokemonGo-Bot#1214]

**Comment by BartKoppelmans** [comment]
You should look into the root folder when you are on `master`, or in the configs folder when you are on `dev`.

**Comment by ankerbachryhl** [comment]
I am on dev, and in my configs folder are there only the files: config.json.example and config.json.pokemons.example :( @BartKoppelmans

**Comment by BartKoppelmans** [comment]
You should rename the file `config.json.example` (if you want just the configuration) or the file `config.json.pokemons.example` (if you also want the release configuration) to `config.json`.

**Comment by ankerbachryhl** [comment]
Ahhh thanks @BartKoppelmans

**Comment by LasseSkogland** [comment]
Please close this issue as it is resolved.

**Comment by TheGoldenXY** [comment]
Issue has been resolved.

/closed
