### ISSUE TITLE
Error on : from pokemongo_bot import logger line 39 and gyms = [gym for gym in cell['forts'] if 'gym_points' in gym] line 85

### ISSUE THREAD

**Issue by WilliyPW** [PokemonGoF/PokemonGo-Bot#1222]
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/home/choukr_w/PokemonGo-Bot/pokemongo_bot/__init__.py", line 85
    gyms = [gym for gym in cell['forts'] if 'gym_points' in gym]
                                                               ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by TheGoldenXY** [comment]
Version check. Please run this command: `git log -n 1 --pretty=format:"%H"` and show me your output.

**Comment by juriw** [comment]
@TheGoldenXY I get this: 9ea015e1fd9c5d269276de8a8e822ee8eb0afa0f

**Comment by TheGoldenXY** [comment]
@juriw Please upgrade to the latest version. You can do it by running this command:
```
git reset --hard
git pull -f
```

**Comment by juriw** [comment]
@TheGoldenXY 
$ git pull -f
Already up-to-date.

**Comment by TheGoldenXY** [comment]
@juriw Has the issue been resolved now? Please try running the bot again.

**Comment by juriw** [comment]
@TheGoldenXY Nope, still gives
```
$ python pokecli.py -cf config.json
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/Users/username/PokemonGo-Bot/pokemongo_bot/__init__.py", line 85
    gyms = [gym for gym in cell['forts'] if 'gym_points' in gym]
                                                               ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by juriw** [comment]
@TheGoldenXY Should I do these steps after the pull -f?
```
$ git clone -b master https://github.com/PokemonGoF/PokemonGo-Bot  
$ cd PokemonGo-Bot  
$ virtualenv .  
$ source bin/activate  
$ pip install -r requirements.txt
$ git submodule init
$ git submodule update
```

**Comment by WilliyPW** [comment]
same result :/

**Comment by chiefdfo** [comment]
```
$ python pokecli.py -cf ./configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "C:\Users\Daniel\Documents\GitHub\PokemonGo-Bot\pokemongo_bot\__init__.py", line 85
    gyms = [gym for gym in cell['forts'] if 'gym_points' in gym]
                                                               ^
TabError: inconsistent use of tabs and spaces in indentation
$ git log -n 1 --pretty=format:"%H"
9ea015e1fd9c5d269276de8a8e822ee8eb0afa0f
$ git reset --hard
HEAD is now at 9ea015e Fix pgoapi package repository hash (#1117)
$ git pull -f
Already up-to-date.
$ python pokecli.py -cf ./configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "C:\Users\Daniel\Documents\GitHub\PokemonGo-Bot\pokemongo_bot\__init__.py", line 85
    gyms = [gym for gym in cell['forts'] if 'gym_points' in gym]
                                                               ^
TabError: inconsistent use of tabs and spaces in indentation
```

same Problem here.

**Comment by chiefdfo** [comment]
Fix No.1: i replaced all Tabs with spaces before the gym in Line 85.

then it got further. 

New Error:  

```
File "C:\Users\Daniel\Documents\GitHub\PokemonGo-Bot\pokemongo_bot\__init__.py", line 358
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

Fix No. 2: `except Exception as e:` 

Next Error: 

```
  File "C:\Users\Daniel\Documents\GitHub\PokemonGo-Bot\pokemongo_bot\__init__.py", line 11, in <module>
    import logger
ImportError: No module named 'logger'
```

no Idea how to fix that kind of an error.

I'm curious... i think there's something elementary wrong, which causes one error by another... I'm using W10 64bit. 

@TheGoldenXY @WilliyPW @juriw - any ideas?

**Comment by juriw** [comment]
@chiefdfo no I have also tried to hack the errors away, but I can't understand why module "logger" is not imported. Note that Im not a Python programmer, only coded a couple of hours in it :)

**Comment by juriw** [comment]
@chiefdfo @TheGoldenXY I just solved the problem by running python 2.7 instead of 3.5 (had not seen the requirements was 2.7).

**Comment by srknkrn** [comment]
We have a problem with 3.5 , I cant understand but I solved same problem by same way

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
