### ISSUE TITLE
Bot go away from pokestop instead of walking toward them

### ISSUE THREAD

**Issue by mehdi-S** [PokemonGoF/PokemonGo-Bot#1223]
### Expected Behavior
walk to pokestop, spin it then reach the next one

### Actual Behavior
<img src="http://i.imgur.com/GXFUQ5h.png" width="400" height="80" />
<img src="http://i.imgur.com/hL8iw2F.png" width="167" height="157" />

### Steps to Reproduce
launch the bot normally with configuration done
setting that can help
```
location : "48.892407,2.389109"
step : 4
walk speed : default (4.16)
```

### Other Information
OS: Debian x86_64
Git Commit: 18f232bffb8df487654e6c52ff3eea859a120925

**Comment by tstumm** [comment]
Use latest dev.
