### ISSUE TITLE
Location Problem

### ISSUE THREAD

**Issue by h8rry** [PokemonGoF/PokemonGo-Bot#1228]
I have been seeing the location to be wrong on aws linux and heroku

```
Walking from (1.1e-322, 5.63e-322) to (22.2867584, 114.1487753)
```

Any reasons?

**Comment by carminaburana123** [comment]
same problem I didn't change versions

**Comment by LasseSkogland** [comment]
Update the repository, pgoapi had a big change and broke the bot.

**Comment by TheGoldenXY** [comment]
Solution above, closing this.

/closed
