### ISSUE TITLE
not catching any pokemon just walkin

### ISSUE THREAD

**Issue by shrunkenolive** [PokemonGoF/PokemonGo-Bot#1235]
### Expected Behavior
![ekran alintisi](https://cloud.githubusercontent.com/assets/20683441/17185681/a4e70188-543a-11e6-9248-af2accca4109.PNG)

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by TheGoldenXY** [comment]
What version are you using? Please run this command: `git log -n 1 --pretty=format:"%H"` and show me your output.

**Comment by shrunkenolive** [comment]
@TheGoldenXY  fatal:not a git repository

**Comment by shrunkenolive** [comment]
@TheGoldenXY could it be about my level should i chance release configs ?

**Comment by VictorChen** [comment]
are you running that command inside the directory?

**Comment by shrunkenolive** [comment]
@VictorChen  what u mean running in cmd.exe

**Comment by xushWT** [comment]
I got that issue too.
