### ISSUE TITLE
Item IDs

### ISSUE THREAD

**Issue by ayozebarrera** [PokemonGoF/PokemonGo-Bot#1236]
Hi

In both example files of config, we have the following:

```js
"item_filter": {
      "1": { "keep" : 100 },
      "101": { "keep" : 0 },
      "102": { "keep" : 0 },
      "103": { "keep" : 20 },
      "201": { "keep" : 20 },
      "701": { "keep" : 50 }
    }
```

But I dont know the id of items so.. I don't know what I'm configuring... so It would be nice to have with comments which item is each line, like this:

```js
"item_filter": {
      "1": { "keep" : 100 },  //Item
      "101": { "keep" : 0 },  //Potion
      "102": { "keep" : 0 },  //Super Potion
      "103": { "keep" : 20 }, //Hyper Potion
      "201": { "keep" : 20 }, //Revive
      "701": { "keep" : 50 }  //Another item
    }
```

I tried to find them on google but couldn't..

good work guys

**Comment by LasseSkogland** [comment]
[Item-ID's](https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Item-ID's)

**Comment by ayozebarrera** [comment]
Ok great, thanks.. 

..so what is the reason of not commenting which item are you configuring? It's a bad idea?

**Comment by TheGoldenXY** [comment]
Please use this article as your reference: https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Item-ID's

/closed
