### ISSUE TITLE
Walking in a loop in "catch" mode

### ISSUE THREAD

**Issue by vicch** [PokemonGoF/PokemonGo-Bot#1238]
### Expected Behavior
Walking in "catch" mode should more efficient (towards lures, for example), or at least more unpredictable.

### Actual Behavior
Walking repeatedly in a path shaped like a "9", which is inefficient and unnatural. See screenshot:

![1](https://cloud.githubusercontent.com/assets/1412595/17186710/b84af6cc-540c-11e6-8c08-80c992369329.PNG)

### Steps to Reproduce
Just run and wait for the "catch" mode to start.
I have tried in different locations, so should have no relation to the starting point.

### Other Information
OS: Windows 7
Git Commit: 74e37dedd950d341eae7c6c0efa8682bd71dcbd8

**Comment by smith-and-web** [comment]
I run the bot in Halifax sometimes and haven't noticed that behaviour.

**Comment by vicch** [comment]
@smith-and-web OK, you found me :) But have you tried the latest `dev` ? I don't remember seeing this behavior before either.

**Comment by koppa** [comment]
In ```dev``` this behavior is still there. I'm running the latest version.

**Comment by vicch** [comment]
A simple solution is to keep your bag far from full, so that it stays in "all" mode.

**Comment by smith-and-web** [comment]
I take it back, I got stuck around pizza corner.

**Comment by vicch** [comment]
Not seen since yesterday, maybe fixed.
