### ISSUE TITLE
[Suggestion] Restrict Movement and Claim Level Up Rewards

### ISSUE THREAD

**Issue by Whosdaman** [PokemonGoF/PokemonGo-Bot#1242]
### Expected Behavior
1. Set a perimeter for how far you want your trainer to walk, this is to limit the area that the trainer wanders.

2. Each time Trainer levels up, allow bot to collect the level up reward items or, if necessary, have the bot restart each time trainer levels in order to collect reward items.

### Actual Behavior
1. Wanders aimlessly wherever the closest available pokestop is

2. Bot does not collect level up reward items at all. Only way to currently do this is by logging in yourself, which will cause a softban.

### Steps to Reproduce
1. Use the bot

2. Use the bot

### Other Information
OS: Windows 10 and MacOS

**Comment by koppa** [comment]
I think the egg rewards are also not colleted.

**Comment by davericher** [comment]
the egg rewards are collected, they are just not reported

**Comment by kingvibs** [comment]
Level up rewards are causing the inventory bag to have more items than allowed
