### ISSUE TITLE
Walk in circle

### ISSUE THREAD

**Issue by DavidTai1** [PokemonGoF/PokemonGo-Bot#1245]
### Expected Behavior
walk around

### Actual Behavior
walk in circle

### Steps to Reproduce
starting position: -35.289139, 149.132514

I have kept a file for recording the pokstops that it visited(in pic).
![1](https://cloud.githubusercontent.com/assets/12397480/17188143/e21ee92a-5409-11e6-8bc6-58cc59b478c5.png)
![b8de7a5a-9674-4273-bbae-2c55e5e18cf3](https://cloud.githubusercontent.com/assets/12397480/17188150/e766ce5c-5409-11e6-814a-37f8c614cbac.png)

### Other Information
OS: MAC OS X 10.11.5
Git Commit: I download zip file to replace the old files and remove old pyc. The file downloaded is from commit 3a18aa57dfb67e2e09c207087cad6e5aa1867112

**Comment by DavidTai1** [comment]
Time was: [14:30:04][14:31:30][14:34:05][14:37:24]  / [14:39:49][14:41:06] ect....

**Comment by DavidTai1** [comment]
I think it is because the 5min has past after spin the first stop, and at that time the first stop is also the closest stop to spin. I modified spin cooldown to 10min and it walks to other stops. 
Suggestions: Maybe keep a routing table for pokstops within a limited area?

**Comment by binarydepartment** [comment]
Can confirm:
![circle](http://pix.toile-libre.org/upload/original/1469647181.png)

**Comment by DavidTai1** [comment]
@binarydepartment You can try to change cooldown time for spinning. Mine is about 10min ([14:39:49] - [14:30:04])and it works pretty well now but this is not a good solution might fail in your case.

**Comment by DavidTai1** [comment]
@Philipp59  dev 3a18aa57dfb67e2e09c207087cad6e5aa1867112
max_steps: 5
mode:all

**Comment by T3hKonijn** [comment]
same bug for me
http://i.imgur.com/KbqFkJz.png
mode: all
walk 4.16
max_steps 5
branch dev
commit 15a034427d805e0bacb79fc0a1f3c96a6c93f0e3

**Comment by javiercravioto** [comment]
Where do you modify spin cooldown?

**Comment by DavidTai1** [comment]
@javiercravioto .../pokemongo_bot/cell_workers/seen_fort_worker.py    line 120, change 300s to the seconds you want. remember to remove file seen_fort_worker.pyc

**Comment by javiercravioto** [comment]
Thanks! I feel we should add this to the wiki. Do you agree?

**Comment by javiercravioto** [comment]
Or, maybe if farm is not set, increase this value to enable the bot to walk farther?

**Comment by DavidTai1** [comment]
@javiercravioto I think they might come up a better solution very soon but for now this is the only way. It needs a update in algorithm, there can be different circles on the map, increase the cooldown value probably just solve the problem temporally. It will fail at some point eg. suddenly walk into a very large circle on the map.
