### ISSUE TITLE
Map not functioning

### ISSUE THREAD

**Issue by Jasperrr91** [PokemonGoF/PokemonGo-Bot#1246]
### Expected Behavior
The bot should properly output the catchable, inventory and location json's into the web folder. It does so for the first two but the location json isn't made and therefor the map is just showing as an empty google maps.

### Actual Behavior
127.0.0.1 - - [27/Jul/2016 21:02:14] "GET /web/catchable-anon@gmail.com.json HTTP/1.1" 200 -
127.0.0.1 - - [27/Jul/2016 21:02:15] code 404, message File not found
127.0.0.1 - - [27/Jul/2016 21:02:15] "GET /web/location-anon@gmail.com.json HTTP/1.1" 404 -

### Steps to Reproduce
1. Run SimpleHTTPServer
2. Run Bot

### Other Information
OS: Mac OSX 10.11.5
Git Commit: 9ea015e1fd9c5d269276de8a8e822ee8eb0afa0f

**Comment by vicch** [comment]
Manually create an empty file `location-anon@gmail.com.json` in the web directory should be able to solve it. Had the same problem myself.

**Comment by Jasperrr91** [comment]
Superb, that did the trick. Thanks Vicch!
