### ISSUE TITLE
[Suggestion] Separate configs for login, catch and release, and, might be, location. 

### ISSUE THREAD

**Issue by jahkuba** [PokemonGoF/PokemonGo-Bot#1250]
I think need to separate configuration for login, catch and release behaviour in three different files, for more usability. I have a bulk of configuration files, and if i need a tune "pokemon management" that's look like a hell. 

I think we need more keys, not only one -cf. 
--user-configuration -uc — login and gmap key information (not to often edited)
--catch-configuration -cc — catch logic here
--release-configuration -rc — release logic here
--evolve-configuration -ec — some evolve logic
--location-configuration -lc — location behaviour (polygon or list of waypoints) or just key for coords, if not file.

### Actual Behavior
python2 pokecly.py -cf /config/poke/loc.json

**Comment by Whosdaman** [comment]
They actually removed the release configuration file. It is still in the master build

**Comment by SteffanLong** [comment]
We just merged two configuration files into one, why separate them into 5? For simplicity when running the bot on multiple accounts, one config file per account is best.

**Comment by jahkuba** [comment]
I have a bulk of configs for different locations and behaviour, if i want tune release pokemon logic for one account i need to edit a  lot of json. Maybe just implement "import" functionality so we can use  different logic for different account just typing something like: 

python2 pokecli.py -uc andy.json -cc catch-only-squirtle.json -rc release-all-birds-and-rats.json -ec evolve-strong.json -lc farm-loc.json

So if i want change only release configs for all account with different behaviour on different places i need to edit all files for account, not just one release-config.json

**Comment by TheSavior** [comment]
I could imagine a world different behaviors take an argument that points to another file for configuration. I believe the core bot itself will only have one config file though. @jahkuba, we are making a bunch of changes to configuration, give it a couple days and see if you are happy with the results.

**Comment by jahkuba** [comment]
Thanks for answer, and sorry for my "foggy" explanations, English is not my native, but i'm trying hard)  

This have more sense with Pokemon-Go-Map database integration #1043 for more complex and automation.
