### ISSUE TITLE
Where did the catch above CP/IV disappeared? 

### ISSUE THREAD

**Issue by boriss579** [PokemonGoF/PokemonGo-Bot#1254]
Now that there are a config.json and release_config.json, where do I config the bot the 'catch' parameter?
AKA
"catch": {
"any": {"catch_above_cp": XX, "catch_above_iv": X.X, "logic": "XX"},

I try to put it in the config.json file, but bot doesn't follow it.

The WIKI is not clear about it.

### Other Information
OS: 
Git Commit: 9ea015e1fd9c5d269276de8a8e822ee8eb0afa0f

**Comment by bstpierr** [comment]
Is this on master or dev?

**Comment by boriss579** [comment]
dev, sorry.
