### ISSUE TITLE
Improve log messages while walking to forts

### ISSUE THREAD

**Issue by HeIix** [PokemonGoF/PokemonGo-Bot#1259]
### Expected Behavior
After starting the bot, move to next pokestop while catching pokemon.

### Actual Behavior
Does not catch pokemon and outputs the following:

_I removed PokeStop name and lat/lon to maintain anonymity._

> [20:39:53] Starting PokemonGo Bot....
> [20:39:54] [x] Found fort a3186fabf81d47f69e1433f4928b273c.16 at distance 0.02km
> [20:39:54] [x] Need to move closer to Pokestop
> [20:39:57] [x] Found fort a3186fabf81d47f69e1433f4928b273c.16 at distance 0.02km
> [20:39:57] [x] Need to move closer to Pokestop
> [20:40:01] [x] Found fort a3186fabf81d47f69e1433f4928b273c.16 at distance 0.01km
> [20:40:01] [x] Need to move closer to Pokestop
> [20:40:04] [x] Found fort a3186fabf81d47f69e1433f4928b273c.16 at distance 0.01km
> [20:40:04] [o] Arrived at Pokestop
> [20:40:05] Now at Pokestop: 
> [20:40:05] Spinning ...
> [20:40:05] Possibly searching too often - taking a short rest :)
> [20:40:05] Scanning area for objects....
> [20:40:05] Walking from () to [] 0.01km
> [20:40:12] [x] Found fort 78618cf46d344592a76869b8d14d2dc0.16 at distance 0.09km
> [20:40:12] [x] Need to move closer to Pokestop

### Steps to Reproduce
Starting the bot on "all" mode.

### Other Information
OS:  Debian
Git Commit: f9468efb454c0e32d87fa7bfc1d398d4c1d65fcf

**Comment by endeavor7** [comment]
Same problem.

git log
f9468efb454c0e32d87fa7bfc1d398d4c1d65fcf

**Comment by Nurvx** [comment]
I don't believe this is an issue. Prior to this, the bot used to have a progress bar showing distance to Pokestop. Now it just shows the distance logged out line by line. I believe the repeat may have to deal with the update and steps.

**Comment by LostDGod** [comment]
Its an issue. I was using the map to check and the bot was randomly sending me on zig zags and ups and downs until it finally reached the pokestop that was only 0.01km away after over 10min.

**Comment by TheSavior** [comment]
Yeah, I believe this is intended behavior. There are probably ways we can improve the log messages though.

**Comment by endeavor7** [comment]
Is the movement speed appearing ridiculously low for a reason? I even went so far as to change the config file speed to 50.0 and it still took almost 5 minutes to move 0.1km.

**Comment by Simage** [comment]
modification of the format_dist function to use an appropriate unit seems to clean it up

`def format_dist(distance, unit='m'):
    # Assumes that distance is in meters and converts it to the given unit, then a formatted string is returned
    # Ex: format_dist(1500, 'km') returns the string "1.5km"

    metric = ('mm', 'cm', 'm', 'km')
    imperial = ('ft', 'yd', 'mi')
    system = reversed(metric)
    if unit in imperial:
        system = reversed(imperial)
    for unit in system:
        d = convert(distance, 'm', unit)
        if d >= 1:
            return dist_to_str(d, unit)
    return dist_to_str(convert(distance, 'm', unit), unit)`

output like
`[17:15:24] [x] Found fort 6c135167e4634d459efcd1db451b9f93.16 at distance 85.68m
[17:15:24] [x] Need to move closer to Pokestop
[17:15:28] [x] Found fort 6c135167e4634d459efcd1db451b9f93.16 at distance 83.65m
[17:15:28] [x] Need to move closer to Pokestop
[17:15:31] [x] Found fort 6c135167e4634d459efcd1db451b9f93.16 at distance 79.72m
[17:15:31] [x] Need to move closer to Pokestop
[17:15:35] [x] Found fort 6c135167e4634d459efcd1db451b9f93.16 at distance 78.16m`

**Comment by klingan** [comment]
Found fort 4968a19d699d40549694c095e7fe3e74.16 at distance 0.04km (initial distance 0.05km) progress [|||||||||                        ] 27%

would this be an improvement?
