### ISSUE TITLE
Pokemon seen but ignored and continue to pop up

### ISSUE THREAD

**Issue by theebanka** [PokemonGoF/PokemonGo-Bot#1260]
### Expected Behavior
Pokeball thrown or attempt to catch Pokemon occurs

### Actual Behavior
Seems to ignore certain Pokemon but will spin stops or catch others in the meantime

![screen shot 2016-07-27 at 1 51 02 pm](https://cloud.githubusercontent.com/assets/10566478/17191928/3a07fdd8-5401-11e6-8c18-251865d5bca4.png)

**Comment by ayiire** [comment]
Sounds like the issue I had. Magikarp appears three times in the config file.

Remove the catch above like and one catch below line for magikarp.
