### ISSUE TITLE
Proper catching of the pgoapi.exceptions.NotLoggedInException

### ISSUE THREAD

**Issue by skartoffel** [PokemonGoF/PokemonGo-Bot#1261]
### Expected Behavior
If this error occures, attempt a reconnect (ideally with the last known coords)

### Actual Behavior
Bot crashes (smart as I was I forgot to copy the stack trace...) will try to deliver

### Steps to Reproduce
Unsure.. I just noticed that I've been disconnected after a while

### Other Information
OS: Mac 10.11.5
Git Commit: 9ea015e1fd9c5d269276de8a8e822ee8eb0afa0f

**Comment by TheGoldenXY** [comment]
@skartoffel Please update to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
