### ISSUE TITLE
[Dev] [Bug] Coords are not getting passed correctly

### ISSUE THREAD

**Issue by IQNeoXen** [PokemonGoF/PokemonGo-Bot#1263]
### Expected Behavior
On startup, bot is scanning the area and then starts walking.

### Actual Behavior
Bot does "Scanning Area for Objects" on repeat and doesn't stop because the coordinates are not being passed correctly (look at the start)

### Steps to Reproduce
Pull latest git and run "sh run.sh"

### Other Information
OS: Debian 8
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

ommit 15e0161d32c7a78c230c6e75cfd6867663c985d1
Author: xc-mezcal <xiwenc.cn@gmail.com>
Date:   Wed Jul 27 17:01:40 2016 -0400

    Update the location & location_cache logic (#1217)
    
    Previously, the location_cache can't be used, even people set location_cache to TRUE. Everytime, it starts from the initial position.
    
    Now the bot check the initial position first.
    Then check if people set location_cache. If so, read it and update it, otherwise use the initial location.
    If there is no initial location and no location cache, print msg and exit.
![bildschirmfoto vom 2016-07-27 23-14-14](https://cloud.githubusercontent.com/assets/20561093/17192756/2a1fe486-5450-11e6-9ad6-4eb54a77db40.png)

**Comment by GRB** [comment]
Exact same issue here, the geocoordinates are not beeing passed correctly.

Look at the starting point of the image.

**Comment by IQNeoXen** [comment]
@GRB What did you do to fix it?

**Comment by GRB** [comment]
i did revert to last version before the bug.

heres the code

git reset --hard 18f232b

:)

**Comment by IQNeoXen** [comment]
@GRB Tyvm, works :) hope this will be fixed soon

**Comment by GRB** [comment]
updated last code, so you can understand how it worked :)

**Comment by GRB** [comment]
Do:

c:\python27\scripts\pip.exe install -r requirements.txt --upgrade

and it will work again.

**Comment by parifuture** [comment]
when I got a git reflog I get something different

 git reflog
f0a77f9 HEAD@{0}: pull: Fast-forward
15e0161 HEAD@{1}: clone: from https://github.com/PokemonGoF/PokemonGo-Bot
<img width="930" alt="screen shot 2016-07-27 at 4 27 43 pm" src="https://cloud.githubusercontent.com/assets/455828/17196117/1a4c55b4-5417-11e6-8df3-a4e4882ce8ef.png">

**Comment by Calcyfer** [comment]
Check @GRB 's previous comment for the fix.

**Comment by eggins** [comment]
Latest updates fixes this aswell.
