### ISSUE TITLE
It crashes with pgoapi.exceptions.NotLoggedInException

### ISSUE THREAD

**Issue by jcaballero4** [PokemonGoF/PokemonGo-Bot#1264]
### Expected Behavior
Not crashing, it should stop when i Ctrl+C it

### Actual Behavior
After an hour / hour and a half of correct behavior it crashes a throws me that error

### Other Information
I updated the directory and i installed the updated pip requeriments too.
OS: Ubuntu 16,04
Git Commit: 9ea015e1fd9c5d269276de8a8e822ee8eb0afa0f

**Comment by TheGoldenXY** [comment]
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1261

/closed
