### ISSUE TITLE
[Help wanted] Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by Henji96** [PokemonGoF/PokemonGo-Bot#1265]
When running "pip install -r requirements.txt" i get
"Command "python setup.py egg_info" failed with error code 1 in c:\users\magnus\appdata\local\temp\pip-build-06gz2k\pyproj\"

The folder pip-build-06gz2k\pyproj\ doesn't exist. 
I have obviously installed pip as well as SetupTools. 

When going a step further, ignoring the error, i get
"Traceback (most recent call last):
  File "pokebot.py", line 15, in <module>
    from pgoapi import PGoApi
  File "C:\Users\Magnus\Desktop\POGO\pgoapi\__init__.py", line 16, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3"
when typing "python pokebot.py -i 0"

And the same when i add --cache, afterwards.
Any help is much appreciated! I obviously know very little about Python so this might just be a noob mistake.

**Comment by TheGoldenXY** [comment]
Please upgrade to latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command to upgrade your deps:
`pip install --upgrade -r requirements.txt`

Please tell me if that solved your issue.

**Comment by Henji96** [comment]
Seems like it worked, thanks! Now i'll just have to figure out how to make this thing run :D

**Comment by TheGoldenXY** [comment]
Issue has been resolved.

/closed
