### ISSUE TITLE
The bot is releasing pokemons that shouldn't be released.

### ISSUE THREAD

**Issue by TheGoldenXY** [PokemonGoF/PokemonGo-Bot#1267]
### Expected Behavior
The bot shouldn't release duplicate pokemons when **CP/IV** is set to **0**. 

### Actual Behavior
If **CP/IV** is set to **0**, the bot still releases the pokemons.

Recently the bot released all my Vaporeons, Flareons and Jolteons, even though I configured it not to.
http://prntscr.com/bycq14

### Steps to Reproduce
Navigate to `configs/` and modify the `config.json` file. Add this to your configuration file:
```
          "Vaporeon": { "release_below_cp": 0, "release_below_iv": 0, "logic": "and" },
          "Jolteon": { "release_below_cp": 0, "release_below_iv": 0, "logic": "and" },
          "Flareon": { "release_below_cp": 0, "release_below_iv": 0, "logic": "and" },
```

### Other Information
OS: **Ubuntu, 14.04**
Git Commit: **15a034427d805e0bacb79fc0a1f3c96a6c93f0e3**

**Comment by fierysolid** [comment]
Interesting. This works with `"logic": "or"` for me, so I never noticed the `and` not working.

**Comment by TheGoldenXY** [comment]
@fierysolid Can you confirm that the bot won't transfer duplicate pokemons if the `"logic"` parameter is set to `or`?
```
          "Vaporeon": { "release_below_cp": 0, "release_below_iv": 0, "logic": "or" },
          "Jolteon": { "release_below_cp": 0, "release_below_iv": 0, "logic": "or" },
          "Flareon": { "release_below_cp": 0, "release_below_iv": 0, "logic": "or" },
```

**Comment by LostDGod** [comment]
#1169

**Comment by douglascamata** [comment]
#1169 is only about misunderstanding boolean math.

**Comment by douglascamata** [comment]
@TheGoldenXY I'm investigating this.

**Comment by douglascamata** [comment]
@TheGoldenXY are you sure you don't have any duplicate entry?

**Comment by TheGoldenXY** [comment]
@douglascamata I'm pretty sure.

http://prntscr.com/bydogj

**Comment by douglascamata** [comment]
@TheGoldenXY can provide logs, please?

**Comment by TheGoldenXY** [comment]
@douglascamata Unfortunately I didn't log it. I was asleep when this incident happened. When I woke up and checked my account, I noticed that the bot had transfered all my vaporeons, flareons and jolteons, even though I configured it not to...

However, some people are claiming that the bot doesn't transfer pokemons if the `"logic"` parameter is set to `or`. I set mine to `and` and the bot transfered all my pokemons. If the `or` value works, perhaps the problem lays with the `and` value?

**Comment by douglascamata** [comment]
There's no problem with the logical operations, they are straightforward and clear:

```
logic_to_function = {
            'or': lambda x, y: x or y,
            'and': lambda x, y: x and y
        }
```

**Comment by douglascamata** [comment]
The whole code is clear:

```python
release_results = {
            'cp': False,
            'iv': False,
        }

        if release_config.get('never_release', False):
            return False

        if release_config.get('always_release', False):
            return True

        release_cp = release_config.get('release_below_cp', 0)
        if cp < release_cp:
            release_results['cp'] = True

        release_iv = release_config.get('release_below_iv', 0)
        if iv < release_iv:
            release_results['iv'] = True

        logic_to_function = {
            'or': lambda x, y: x or y,
            'and': lambda x, y: x and y
        }

        return logic_to_function[cp_iv_logic](*release_results.values())
```

**Comment by TheGoldenXY** [comment]
@douglascamata So you're basically stating that it should work theoretically, right? Can you please test it and check if it works, because I'm very positive that it doesn't work. That explains why the bot transfered all my pokemons

**Comment by douglascamata** [comment]
@TheGoldenXY yes, I'm very confident it is working, need a dummy account to test. BTW, the recommended you of never releasing a pokemon is using the key `never_release: true`

**Comment by TheGoldenXY** [comment]
@douglascamata Have this never been tested working in real time? Then I'll test it for you. 

Did I configure it properly?
http://prntscr.com/bydwlt

**Comment by douglascamata** [comment]
@TheGoldenXY yes. Please duplicate the second duplicates. Also I'm testing with Caterpie in my main acc now.

**Comment by douglascamata** [comment]
`"Caterpie": {"release_below_cp": 0, "release_below_iv": 0, "logic": "and" }`

this should reproduce your problem, right?

**Comment by TheGoldenXY** [comment]
@douglascamata Which duplicates are we talking about? 

Do you want me to add this
```
      "Vaporeon": { "release_below_cp": 0, "release_below_iv": 0, "logic": "or" },
      "Jolteon": { "release_below_cp": 0, "release_below_iv": 0, "logic": "or" },
      "Flareon": { "release_below_cp": 0, "release_below_iv": 0, "logic": "or" },
```
below
```
      "Vaporeon": { "release_below_cp": 0, "release_below_iv": 0, "logic": "and" },
      "Jolteon": { "release_below_cp": 0, "release_below_iv": 0, "logic": "and" },
      "Flareon": { "release_below_cp": 0, "release_below_iv": 0, "logic": "and" },
```
?

**Comment by TheGoldenXY** [comment]
@douglascamata That should reproduce the problem

**Comment by douglascamata** [comment]
@TheGoldenXY I want you to only keep lines for these pokemon with `never_release: true` and delete others.

**Comment by TheGoldenXY** [comment]
@douglascamata Alright, I'll do so

**Comment by douglascamata** [comment]
```
[01:13:03] Login to Pokemon Go successful.
[01:13:04]
[01:13:04] --- PokeGother ---
[01:13:04] Level: 23 (Next Level: 11370 XP) (Total: 548630 XP)
[01:13:04] Pokemon Captured: 2111 | Pokestops Visited: 1197
[01:13:04] Pokemon Bag: 217/250
[01:13:04] Items: 313/350
[01:13:04] Stardust: 164167 | Pokecoins: 0
[01:13:04] PokeBalls: 96 | GreatBalls: 79 | UltraBalls: 11
[01:13:04] RazzBerries: 7 | BlukBerries: 0 | NanabBerries: 0
[01:13:04] LuckyEgg: 5 | Incubator: 5 | TroyDisk: 5
[01:13:04] Potion: 5 | SuperPotion: 30 | HyperPotion: 30
[01:13:04] Incense: 8 | IncenseSpicy: 0 | IncenseCool: 0
[01:13:04] Revive: 30 | MaxRevive: 0
[01:13:04]
[01:13:04]
[01:13:08] Starting PokemonGo Bot....
[01:13:10] Something rustles nearby!
[01:13:10] A Wild Tangela appeared! [CP 314] [Potential 0.51]
[01:13:10] IV [Stamina/Attack/Defense] = [10/13/0]
[01:13:14] Catch Rate with normal Pokeball is low (45.82%). Throwing Razz Berry... (6 left!)
[01:13:14] Catch Rate with normal Pokeball has increased to 68.73%
[01:13:14] Using Pokeball (chance: 68.73%)... (95 left!)
[01:13:16] Captured Tangela! [CP 314] [10/13/0]
[01:13:16] Tangela has been exchanged for candy!
[01:13:18] Scanning area for objects....
[01:13:18] Walking from (41.915286318001144, 12.496777884177504) to [41.915286318001144, 12.496777884177504] 0.00km

[01:13:19] Scanning area for objects....
[01:13:19] Walking from (41.915286318001144, 12.496777884177504) to [41.91708631800115, 12.496777884177504] 0.20km

[01:13:25] Scanning area for objects....
[01:13:25] Walking from (41.91708631800115, 12.496777884177504) to [41.91708631800115, 12.498577884177504] 0.15km

[01:13:26] Scanning area for objects....
[01:13:26] Walking from (41.91708631800115, 12.498577884177504) to [41.915286318001144, 12.498577884177504] 0.20km
[01:13:30] Something rustles nearby!
[01:13:31] A Wild Exeggcute appeared! [CP 203] [Potential 0.76]
[01:13:31] IV [Stamina/Attack/Defense] = [13/12/9]
[01:13:34] Using Pokeball (chance: 57.27%)... (94 left!)
[01:13:36] Captured Exeggcute! [CP 203] [13/12/9]
```

It didn't release any Caterpie I got.

**Comment by TheGoldenXY** [comment]
@douglascamata That's very weird. For me it did the opposite. How does your configuration file look like?

**Comment by douglascamata** [comment]
```
    "release": {
      "any": {"release_below_cp": 400, "release_below_iv": 0.6, "logic": "and" },
      "Pinsir": {"release_below_cp": 900, "release_below_iv": 0.6, "logic": "or" },
      "Caterpie": {"release_below_cp": 0, "release_below_iv": 0, "logic": "and" },
      "Doduo": {"release_below_cp": 900, "release_below_iv": 0.7, "logic": "or" },
      "Dodrio": {"release_below_cp": 900, "release_below_iv": 0.6, "logic": "or" }
    }
}
```

**Comment by douglascamata** [comment]
you running last dev revision?

**Comment by TheGoldenXY** [comment]
@douglascamata Yes, that is correct

**Comment by douglascamata** [comment]
It works correctly for me again, I tried with `Ponyta` now and I put a debugger right before `return logic_to_function[cp_iv_logic](*release_results.values())` (where the final decision is calculated), manually checked the final decision and it was always `False`.

My config:

```
"Ponyta": {"release_below_cp": 0, "release_below_iv": 0, "logic": "and" },
```

Logs + debugger: 

```
[01:24:25] Starting PokemonGo Bot....
> /Users/douglascamata/code/pokemongo-bot-dirty/pokemongo_bot/cell_workers/initial_transfer_worker.py(115)should_release_pokemon()
-> return logic_to_function[cp_iv_logic](*release_results.values())
(Pdb) print release_results
{'cp': False, 'iv': False}
(Pdb) logic_to_function[cp_iv_logic](*release_results.values())
False
(Pdb) c
> /Users/douglascamata/code/pokemongo-bot-dirty/pokemongo_bot/cell_workers/initial_transfer_worker.py(115)should_release_pokemon()
-> return logic_to_function[cp_iv_logic](*release_results.values())
(Pdb) logic_to_function[cp_iv_logic](*release_results.values())
False
(Pdb) c
[01:25:32] Scanning area for objects....
[01:25:32] Walking from (41.916205104104215, 12.49496682865102) to [41.916205104104215, 12.49496682865102] 0.00km

> /Users/douglascamata/code/pokemongo-bot-dirty/pokemongo_bot/cell_workers/initial_transfer_worker.py(115)should_release_pokemon()
-> return logic_to_function[cp_iv_logic](*release_results.values())
(Pdb) logic_to_function[cp_iv_logic](*release_results.values())
False
(Pdb) c
> /Users/douglascamata/code/pokemongo-bot-dirty/pokemongo_bot/cell_workers/initial_transfer_worker.py(115)should_release_pokemon()
-> return logic_to_function[cp_iv_logic](*release_results.values())
(Pdb) logic_to_function[cp_iv_logic](*release_results.values())
False
(Pdb)
```

**Comment by TheGoldenXY** [comment]
@douglascamata So it works, great. I think most of the people are confused on how to do it, including me.

Would it be okay to set `"release_below_cp"` and `"release_below_iv"` parameters to 0 and use both `and` `or` values in `"logic"` parameter, such as this?
```
"Caterpie": {"release_below_cp": 0, "release_below_iv": 0, "logic": "and" },
"Caterpie": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or" },
```

Or should we ONLY only do it this way?
```
"Caterpie": { "never_release": true },
```

And would it be OK to use duplicates, without affecting the process?

**Comment by douglascamata** [comment]
Both ways should work. Using the smaller form is more clear and intuitive tho. It's also safer because if `never_release` is `true` we don't even do any math, just skip it and don't release.

**Comment by TheGoldenXY** [comment]
@douglascamata More specifically, in order to configure the bot to **NOT** transfer pokemons, we should remove duplicates and **ONLY** use this line?
```
"Caterpie": { "never_release": true },
```

**Comment by douglascamata** [comment]
@TheGoldenXY a short cut to not release any pokemon is using the `any` entry instead of repeating this for every one of the 151 pokemons.

**Comment by douglascamata** [comment]
`"any": {never_release: true}`

**Comment by TheGoldenXY** [comment]
@douglascamata Would it be possible for you to add a new feature to the bot, so that it doesn't transfer **ANY** pokemons above x CP? This would certainly help a lot of people.

For instance: You have 150/250 pokemons. 50/250 pokemons has CP above 1000. It would be nice to have a configuration so that the bot won't transfer those pokemons with CP above 1000

**Comment by douglascamata** [comment]
@TheGoldenXY `"any": {release_below_cp: 1000}`

**Comment by TheGoldenXY** [comment]
@douglascamata I don't want the bot to release all my pokemons below 1000 CP. I simply want the bot to not release pokemons with CP > 1000

**Comment by Antairez** [comment]
@TheGoldenXY "any": {release_below_cp: 200}

**Comment by Antairez** [comment]
@TheGoldenXY You need to better understand how boolean logic work. If the condition is to release all pokemons whose cp is below 200, then all pokemons whose cp above 200 won't get released. Your statement of above 1000 don't release and below 200 do release is misleading, what do you do when something is between 200~1000?

**Comment by TheGoldenXY** [comment]
This issue has been resolved, closing this for now.

/closed
