### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'get'

### ISSUE THREAD

**Issue by jcaballero4** [PokemonGoF/PokemonGo-Bot#1269]
### Expected Behavior
Not crashing
### Actual Behavior
id_filter = self.config.item_filter.get(str(item_id), 0) 
### Other Information
I come from https://github.com/PokemonGoF/PokemonGo-Bot/issues/1264 i did the thing in the other ticket.
Then i created a new environment for the dev version (i was using master), and i installed it updated. I cant even start the script now

OS: Ubuntu 16,04
Git Commit: 15e0161d32c7a78c230c6e75cfd6867663c985d1

**Comment by anziclone** [comment]
Same Issue here!

**Comment by jcaballero4** [comment]
Solved, I used the same config.json i was using on master, i checked the new and it was diferent
