### ISSUE TITLE
Release lower duplicate pokemon

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [PokemonGoF/PokemonGo-Bot#127]
I've got tonnes of duplicate Pokemon with high CP. I'd like to be able to release all but the highest I've got (instead of setting a minimum CP to keep)

similar to #15

**Comment by jtdroste** [comment]
Related: #142

**Comment by jtdroste** [comment]
Closing for tracking on #142

**Comment by CtrlAltDefeat94** [comment]
#127 #142 #15 
i just wish people would check if something is reported already..
