### ISSUE TITLE
Want to create a log when i catched pokemon

### ISSUE THREAD

**Issue by rednka** [PokemonGoF/PokemonGo-Bot#1271]
Hello, sorry for my bad language, i'm not english, i want to create a log.txt file when i catched a pokemon (write pokemon name and iv value in the text file)

i'm a newbie to python, but i have search the script for catched pokemon, it's pokemongo_bot/cell_workers/pokemon_catch_worker.py right ?

After the line 136 i have added : 
`fichier = open("log.txt", "a")
fichier.write("\nNom: ".pokemon_name." %: ".pokemon_potential."")
fichier.close()`

And i have this error : 
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "D:\Documents and Settings\flo\Bureau\PokemonGo-B
    from cell_workers import PokemonCatchWorker, SeenFor
  File "D:\Documents and Settings\flo\Bureau\PokemonGo-B
    from pokemon_catch_worker import PokemonCatchWorker
  File "D:\Documents and Settings\flo\Bureau\PokemonGo-B
    fichier.write("\nNom: ".pokemon_name." %: ".cp."")
                                              ^

i don't understand why it's bugged, can you help me ?

thanks for the job ! have a nice day

**Comment by DavidTai1** [comment]
with open('cap_pok.txt','a') as cap_pok:
                                    cap_pok.write('A Wild {} appeared! [CP {}] [Potential {}]\n'.format(
                                    pokemon_name, cp, pokemon_potential));

This is what I use

**Comment by rednka** [comment]
Hello, were are you put this code ?

Me, after the line 136 (cell_workers/pokemon_catch_workers.py=
`open('cap_pok.txt','a') as cap_pok:
									cap_pok.write('{} a etait capture ! [CP {}] [Potential {}]\n'.format(
									pokemon_name, cp, pokemon_potential));`

**Comment by DavidTai1** [comment]
pokemon_catch_worker.py  line 87 right under the log. It works for me

**Comment by rednka** [comment]
Sorry but isn't work for me ..

i need to put your code before this comment ?
`# @TODO, use the best ball in stock to catch VIP (Very Important Pokemon: Configurable)`

i have all time the same error ..

**Comment by DavidTai1** [comment]
![image](https://cloud.githubusercontent.com/assets/12397480/17197871/708a233a-543e-11e6-9b02-af6ff470b0af.png)
![image](https://cloud.githubusercontent.com/assets/12397480/17197875/78fc7d38-543e-11e6-9b57-cea7b9e73b86.png)
I made some change to it.

**Comment by rednka** [comment]
Thanks, but why i don't have the same script ?

I'm really a newbie to github/python ... master version can't be modified ?

i have python 2.7, PokemonGo-Bot 1.0, Windows XP, git ...


And this is my pokemon_catch_worker.py (whitout your script because crashing the bot)

**Comment by DavidTai1** [comment]
3a18aa57dfb67e2e09c207087cad6e5aa1867112
This is the version i use

**Comment by rednka** [comment]
Hello again .. i have "update" to your version, i haven't touch to anything and it's doesn't work !

it's crazy..

Script to image:
![bug](https://cloud.githubusercontent.com/assets/20670732/17206364/a1b2dfd0-54af-11e6-98f0-83d6c61a07ec.png)

Error to image:
![bug](https://cloud.githubusercontent.com/assets/20670732/17206399/cbbc9b36-54af-11e6-90af-19f89984475b.png)

**Comment by DavidTai1** [comment]
what is your python version?

**Comment by rednka** [comment]
2.7.X

**Comment by DavidTai1** [comment]
Same here, no idea why you have that error. Maybe try put tab before 
![image](https://cloud.githubusercontent.com/assets/12397480/17228470/1cc08336-54e1-11e6-8d5e-76a78a8471d7.png)
just like the form I did.

**Comment by rednka** [comment]
no work again .. i don't understand why doesn't work, i have just use for test: 
`cap_pok.write('test');` and same error..

**Comment by DavidTai1** [comment]
no idea.. maybe google for another way

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
