### ISSUE TITLE
Wrong walking behavior

### ISSUE THREAD

**Issue by LostDGod** [PokemonGoF/PokemonGo-Bot#1275]
### Expected Behavior
Walking in a straight line from pokestop to pokestop?

### Actual Behavior

![drunk_bot](https://cloud.githubusercontent.com/assets/13785053/17194745/92a24fe8-5451-11e6-8552-b11997dbee32.png)

### Other Information
OS: Windows
Git Commit: 15e0161d32c7a78c230c6e75cfd6867663c985d1

**Comment by CadeBrown** [comment]
It adds some amount of randomness, to emulate human behaviour. If you don't want this, you can change pokemongo_bot/human_behaviour.py

**Comment by LostDGod** [comment]
Thats some over the top PR! It might have took into consideration the starting point was a bar too so it added the behavior of a drunk person over the randomness you spoke about.

**Comment by douglascamata** [comment]
@LostDGod you don't provide any information to help us diagnose, dude...

**Comment by LostDGod** [comment]
Sorry I had forgotten I added a comment with some coords below the location on config. Let me test it out now that its cleaned, I will report back in a few mins.

**Comment by LostDGod** [comment]
Its working fine now. A bit of randomness but thats perfect.
This is how my config was:

>     "location": "-33.85921726653056,151.21314346790314",
> 	"// S: -33.85921726653056,151.21314346790314": {},
>     "gmapkey": "XXX",
>     "max_steps": 1,
>     "mode": "all",
>     "walk": 0.01,

Reverted back to normal and everything is fine. I believe the problem was the extreme low speed in conjugation witht he human behavior factor. 
Problem was on my end so I'm sorry for your time : |
