### ISSUE TITLE
Bot stuck when too much items

### ISSUE THREAD

**Issue by Cygnus-X3** [PokemonGoF/PokemonGo-Bot#1277]
### Expected Behavior
Bot needs to remove items to stay below 350 items limit

### Actual Behavior
The bot seems to remove items from time to time, but it overflows and reach 400+ items in a regular manner (exceeding the actual limit on the game) thus showing this line multiple times and not doing anything else unless a pokemon appears nearby where it catches the pokemon and then goes back to being stuck
[2016-07-28 00:32:00] [#] Scanning area for objects (1 / 1)

### Steps to Reproduce
let the bot work, it will eventually reach the limit and get stuck by itself

### Other Information
OS: Win10
Git Commit: 3aca6d798f8a3e173dce0beb7b13c9505cc5b251

**Comment by Kassius509** [comment]
Expected Behavior should be modified to detect and accommodate higher item limits for players with expanded inventories.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
