### ISSUE TITLE
Never_capture does not work (dev)

### ISSUE THREAD

**Issue by KiraEnishi** [PokemonGoF/PokemonGo-Bot#1278]
### Expected Behavior
"Caterpie": {"never_capture": true}, does not stop me from capturing Caterpies
Doesn't work with other pokemons as well.

### Actual Behavior
I still capture them and then release them

### Other Information
OS: OSX
On dev package

**Comment by SteffanLong** [comment]
The flag is `never_capture`.

**Comment by KiraEnishi** [comment]
Oppse typo.
