### ISSUE TITLE
Map doesn't show anything

### ISSUE THREAD

**Issue by ayiire** [PokemonGoF/PokemonGo-Bot#1279]
### Expected Behavior
Map should appear when opening up index.html after renaming userdata.js and editing it. I am opening it directly and do not have a web server running.

The map from master branch works fine for me when using this method. API key is working fine

### Actual Behavior
Map shows a white screen
http://i.imgur.com/nPf4mg1.png

userdata.js
http://i.imgur.com/hlmOI7N.png

### Steps to Reproduce
git clone -b dev https://github.com/PokemonGoF/PokemonGo-Bot c:\devtest
pip install -r requirements.txt
git module init
git module update

Fill in parameters into userdata.js.example and rename it to userdata.js

Open index.html

### Other Information
OS: Win10
Git Commit: 01de69fa9d889207c1501afbf605db10414e65f0

**Comment by eggins** [comment]
You need to open another cmd/terminal

and run the following

`python -m SimpleHTTPServer`

Then navigate to `http://localhost:8000`
