### ISSUE TITLE
No candy info in browser

### ISSUE THREAD

**Issue by CadeBrown** [PokemonGoF/PokemonGo-Bot#1283]
### Expected Behavior

The "Pokemon" tab should show how many candies I have for that type of pokemon

### Actual Behavior

Shows undefined:
![Picture](https://cloud.githubusercontent.com/assets/10441207/17196226/0b490476-5431-11e6-9a0c-3090c7c12477.png)

### Steps to Reproduce

Just run "python -m SimpleHTTPServer $port", navigate, and select pokemon submenu

### Other Information
OS: Ubuntu
Git Commit: f0a77f92c20ba057ea8baace0952b4f82dae2b01

**Comment by Viper896** [comment]
It's not pretty.... but here is my main.js to use as a work around.
https://github.com/Viper896/Patch/blob/master/main.js

Contains the fix from but modified for the current Dev version
https://github.com/fierysolid/OpenPoGoWeb/commit/bad725ea996356e1b5d7fae8964873b341bcc018#diff-77ab163850ef0fa98d6a9ee9fb6bbcaf

**Comment by knobunc** [comment]
This fixed it for me!  thanks
(dev branch)
