### ISSUE TITLE
[Help] Try to add throw berry feature in Master branch, called api, but get status code 52 back.

### ISSUE THREAD

**Issue by xc-mezcal** [PokemonGoF/PokemonGo-Bot#1292]
To be simple, let's only put simple things there.

### Expected Behavior

[2016-07-27 19:06:04] [#] Catch Rate with Pokeball has increased to xxxx%

### Actual Behavior

[2016-07-27 19:06:04] Fail to use berry. Status Code: 52

### Steps to Reproduce

```
berrry_id = 701
self.api.use_item_capture(
                                    item_id=berry_id,
                                    encoutner_id=encounter_id,
                                    spawn_point_guid =spawnpoint_id
)
response_dict = self.api.call()
if response_dict['status_code'] is 1:
            //TODO
else:
            logger.log('Fail to use berry. Status Code: {}'.format(response_dict['status_code']),'red')
```

### Other Information
Succeed in dev branch,
but get status code 52 when use it in master branch.

Any help, suggestions?
"status code 52"
"api.call()"
"api.use_item_capture()" (where are those defined?)

**Comment by Calcyfer** [comment]
I'll point you in the right direction : You can find the message arguments [here](https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Networking/Requests/Messages/UseItemCaptureMessage.proto).

Make sure to check the history of that file and view the commit that is being used in our master branch.

**Comment by xc-mezcal** [comment]
@Calcyfer Yes I already followed the message format. And the right values, I believe. (Since the only new value are berry_id, which is simple to verify)

The problem now for me is what should I do with that ""status code 52.""

**Comment by Calcyfer** [comment]
I'm afraid I can't help you with that - status codes aren't documented anywhere. =/
Are you sure you have the right version of the API? 

`spawn_point_guid` is `spawn_point_id` in the new version.

**Comment by xc-mezcal** [comment]
@Calcyfer Oh, Thanks for pointing it out!

The protos API  in my branch is 
`spawn_point_guid`

But what you pointed (master) is `spawn_point_id`

Should I somehow download the newest API? (and is there any command I need to type, or just download it)

Appreciate it!

**Comment by Calcyfer** [comment]
Well, if you're on PokemonGo-Bot/master you should have the PgoAPI v1.1.0, which actually has `spawn_point_guid`.

It seems you had the correct code, using `spawn_point_guid`, but a newer PgoAPI.
Delete the `src` folder and run `pip install --upgrade -r requirements.txt` to get the right one instead.

**Comment by xc-mezcal** [comment]
@Calcyfer 
Thanks buddy!

My last questions is if I have a `spawn_point_guid` version installed, and called api in such an old way.
Will it function well? 

Or we have to use the newer API to a successfully call?

**Comment by Calcyfer** [comment]
If you're on master, use the old api that has `spawn_point_guid`, if you're on dev, use the new API that has `spawn_point_id`.

Anytime. :)

**Comment by xc-mezcal** [comment]
Will the issue is not fixed yet. 
Tried some weird solution, get status code 3.

But thanks! :)

**Comment by TheGoldenXY** [comment]
Closing this for now. Please upgrade to the latest `dev` branch. If issue persists, open new issue.

/closed
