### ISSUE TITLE
TabError when starting Pokecli.py

### ISSUE THREAD

**Issue by hagridaaron** [PokemonGoF/PokemonGo-Bot#1294]
### Expected Behavior
Normal Startup of Pokecli.py

### Actual Behavior
~~~~
$ python pokecli.py -l    
~~~~

Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/home/atracy/sysadmin/projects/PokemonGo-Bot/pokemongo_bot/__init__.py", line 85
    gyms = [gym for gym in cell['forts'] if 'gym_points' in gym]
                                                               ^
TabError: inconsistent use of tabs and spaces in indentation

### Steps to Reproduce
$ python pokecli.py

### Other Information
OS: Arch Linux
Git Commit: 9ea015e1fd9c5d269276de8a8e822ee8eb0afa0f

**Comment by pokemule** [comment]
Are you executing the command "source bin/activate" in terminal before executing "python pokecli.py"?

**Comment by kennycoc** [comment]
@hagridaaron I found a syntax error on that line. Once the PR gets accepted just run `git pull` and you should be good.
