### ISSUE TITLE
Latest Dev Branch Update 35min Ago just scans for objects

### ISSUE THREAD

**Issue by inet-pwnZ** [PokemonGoF/PokemonGo-Bot#1295]
### Expected Behavior
Catching pokemon, using pokestops

### Actual Behavior
Just scaning for objects

### Steps to Reproduce
Starting the bot 
i went back to master branch
### Other Information
OS: Win7
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by longlhgithub** [comment]
I got the same issue when getting latest from dev branch. Hopes Developers can realize this soon.

**Comment by Kujawadl** [comment]
I had this issue as well. Running `pip install -r requirements.txt update` and then deleting `./data/last-location*` and `./data/cells*` fixed the issue for me.

**Comment by eggins** [comment]
Always clear configs and old data on every new update.
@Kujawadl provided the fix.
