### ISSUE TITLE
Is this a bug or I did something wrong? (new to Python)

### ISSUE THREAD

**Issue by DrunkAgain** [PokemonGoF/PokemonGo-Bot#1296]
### Actual Behavior
![bug 2](https://cloud.githubusercontent.com/assets/20692601/17197078/160d0d24-549c-11e6-99e6-9b39e7963d79.jpg)
![bug](https://cloud.githubusercontent.com/assets/20692601/17197079/16321b78-549c-11e6-8238-c1838d4d0ac9.jpg)

### Other Information
OS: win7 32bit
PokemonGo-Bot dev
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by kennycoc** [comment]
Are you on dev? It looks like there's a known issue right now. #1291 
Delete the catch_above_cp lines from the config.json and you should be good.

**Comment by DrunkAgain** [comment]
yes sir, I'm on dev.

is this the right way to delete it

    "use_lucky_egg": false,
    "evolve_captured": false,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or" },

      "// Pokemons with example": { "always_catch": true },
      "// Gets filtered with release parameters": {},

to

    "use_lucky_egg": false,
    "evolve_captured": false,
    "catch": {
      "any": { },

      "// Pokemons with example": { "always_catch": true },
      "// Gets filtered with release parameters": {},

**Comment by ayiire** [comment]
I deleted line 61 and 132 completely and I'm catching magikarp fine. Before I deleted them, I had issues. Eevee also has the same issue.

```
	Line 60:       "// Magikarp evolves to Gyarados": {},
	Line 61:       "Magikarp": { "catch_above_cp": 91, "catch_above_iv": 0.9, "logic": "and" },
	Line 131:       "// Magikarp evolves to Gyarados": {},
	Line 132:       "Magikarp": { "release_below_cp": 91, "release_below_iv": 0.8, "logic": "and" },
	Line 177:       "Magikarp": { "release_below_cp": 91, "release_below_iv": 0.8, "logic": "and" },
```

**Comment by DrunkAgain** [comment]
Will try your fix sir ayiire.

**Comment by DrunkAgain** [comment]
I think that did the trick. It doesn't happen anymore, 6 Magikarps caught and transferred already. Thank you.

But what about the 2nd picture sir?
It only happened 1 time, and 1 hour of using it after, it still doesn't produce the same error.
![bug](https://cloud.githubusercontent.com/assets/20692601/17197945/a9e08d44-54a3-11e6-84a1-7cf17fa642ed.jpg)

**Comment by eggins** [comment]
`pip install -r requirements.txt`

**Comment by carminaburana123** [comment]
doesn't work
