### ISSUE TITLE
Can't install the requirements

### ISSUE THREAD

**Issue by Vardex** [PokemonGoF/PokemonGo-Bot#1298]
### Expected Behavior

Should install all the requirements

### Actual Behavior

Don't install the requirements

:~/PokemonGo-Bot# pip install -r requirements.txt
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8                                                                                                                                                             fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi (from -r requirements.txt (line 1))
  Cloning https://github.com/tejado/pgoapi.git (to 81e786cabf027a1c8fbd1e9a07e1c                                                                                                                                                             11aa3d8ee8b) to ./src/pgoapi
  Could not find a tag or branch '81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b', ass                                                                                                                                                             uming commit.
  Running setup.py egg_info for package pgoapi
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/root/PokemonGo-Bot/src/pgoapi/setup.py", line 9, in <module>
        install_reqs = parse_requirements(path_req, session=False)
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/root/PokemonGo-Bot/src/pgoapi/setup.py", line 9, in <module>

    install_reqs = parse_requirements(path_req, session=False)

TypeError: parse_requirements() got an unexpected keyword argument 'session'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /root/PokemonGo-Bot                                                                                                                                                             /src/pgoapi

### Steps to Reproduce

Follow the "Installation Linux", should happen at the step with "pip install -r requirements.txt"

### Other Information
OS: Debian 7.11
Latest dev version

**Comment by friparia** [comment]
which is ur pip version, i've met a install error, and after i upgrade pip it worked. The upgrade command `pip install -U pip`
