### ISSUE TITLE
Documentation uses "never_capture" flag - should use "never_catch"

### ISSUE THREAD

**Issue by iPression** [PokemonGoF/PokemonGo-Bot#1301]
Don't know if this is an issue, but "never_capture" is not defined in the catch worker. Documentation should say "never_catch" : true instead.

Dev Branch.

**Comment by eggins** [comment]
The Wiki currently supports the `dev` branch - are you referring to the dev branch?

**Comment by iPression** [comment]
Yep, I'm sorry I didn't point this out.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
