### ISSUE TITLE
The bot doesn't transfer pokemons anymore when the bag is full

### ISSUE THREAD

**Issue by TheGoldenXY** [PokemonGoF/PokemonGo-Bot#1303]
### Expected Behavior
If the pokemon bag is full, the bot should transfer pokemons at the beginning of the run.

### Actual Behavior
When my pokemon bag is full, it doesn't transfer any pokemons at the beginning of the run. Everything is configured properly. It's weird, because it was working before. Perhaps someone overwrote something in a PR?

Here is the message I'm receiving:
http://prntscr.com/byezd6

Here is my configuration file:
http://prntscr.com/byf058

### Steps to Reproduce
Use the latest `dev` branch and run the bot when your pokemon bag is full

### Other Information
OS: **Ubuntu, 14.04**
Git Commit: 6022dfbdc2cc1ed804cd66a8616102a31603941d

**Comment by surfaace** [comment]
#1286

**Comment by TheGoldenXY** [comment]
@surfaace I am using the latest `dev` branch. This is not fixed

**Comment by TheGoldenXY** [comment]
@surfaace Thanks. I'll get someone to merge your PR

**Comment by TheGoldenXY** [comment]
Bug has been fixed https://github.com/PokemonGoF/PokemonGo-Bot/commit/63b43878c72bfaacdfef0d7443f5ee019a16f585 

Closing this.

/closed
