### ISSUE TITLE
Catch/Farm mode

### ISSUE THREAD

**Issue by enajork** [PokemonGoF/PokemonGo-Bot#1305]
### Issue
When the bot runs out of item space and no longer can carry anymore Pokeballs and then it visits a Pokestop, it cannot pick anything up so it switch into catch mode. However, once in catch mode, when a Pokemon appears, the bot realizes it doesn't have any Pokeballs to catch the Pokemon, so it reverts back to farm mode. And then the cycle repeats. One way to address this problem is to have the item recycling function actually work (this feature appears to be broken at the moment) and have that function run on bot startup.

### Steps to Reproduce
Run the bot

### Other Information
OS: El Capitan
Git Commit: (1815d03ea011532ba44218ce624f4033b9c88677)

**Comment by eggins** [comment]
Not broken. THis is still being implemented to clear the inventory before running.

Will be up soon.
Manually delete some items for now.

**Comment by enajork** [comment]
Thanks
