### ISSUE TITLE
Map does not update

### ISSUE THREAD

**Issue by artgenos** [PokemonGoF/PokemonGo-Bot#1306]
### Expected Behavior
Expect map to show where I am at and where i am moving to

### Actual Behavior
Starts me in Germany, location is not set in Europe, and never moves.

### Steps to Reproduce
Fresh install followed instructions for installation

### Other Information
OS: Debian, Raspbian
Git Commit: dc742c598a2636337bd358dae8a558ef02159e8e

**Comment by Viper896** [comment]
Dev or Master branch?

**Comment by iPression** [comment]
i believe he's using the master branch. did you enter your google api and your username in the master/config.json and master/web/userdata.js?

**Comment by artgenos** [comment]
master branch and yes, google api in both places. removed original catchable/inventory files and retyped in name. restarted SimpleHTTPServer and working now. maybe a typo in the name.
