### ISSUE TITLE
pokemon (never_capture) not work

### ISSUE THREAD

**Issue by akbaribnu** [PokemonGoF/PokemonGo-Bot#1308]
hello dev, 
i try for never catch zubat and pidgey but not work, my bot always catch pidgey and zubat.. please give me solution..

this is my config.

    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "Pidgey": {"never_capture": true},
      "Zubat": {"never_capture": true},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 500, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": { "always_release" : true }
    }
}

**Comment by iPression** [comment]
#1301

**Comment by akbaribnu** [comment]
hai thnks for reply, but on wiki use never_capture for never catch

**Comment by akbaribnu** [comment]
btw parameter  never_catch  work for me, thank you

**Comment by iPression** [comment]
Yeah, but in pokemon_catch_worker.py it says:

        if catch_config.get('never_catch', False):
            return False

I already figured out, that the wiki is not correct, that's why I linked you my Issue #1301 
So use never_catch instead of never_capture
