### ISSUE TITLE
Problems running pokecli.py

### ISSUE THREAD

**Issue by mattlehning** [PokemonGoF/PokemonGo-Bot#1311]
### Expected Behavior
For it to run

### Actual Behavior
`usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USER
                  [-p PASSWORD] [-l LOCATION] [-lc LOCATION_
                  [-w WALK] [-k GMAPKEY] [-ms MAX_STEPS]
                  [-it INITIAL_TRANSFER] [-d DEBUG] [-t TEST
                  [-du DISTANCE_UNIT] [-if ITEM_FILTER] [-ev
                  [-ec EVOLVE_CAPTURED]
pokecli.py: error: argument -a/--auth_service is required`

### Steps to Reproduce
./pokecli.py

### Other Information
Yes I changed config.json with my configuration info.
OS: windows
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by anziclone** [comment]
Where is your config file located?

**Comment by mattlehning** [comment]
...\GitHub\PokemonGo-Bot

**Comment by eggins** [comment]
put the config.json in the configs/ folder.
