### ISSUE TITLE
Bot crashes on startup after login

### ISSUE THREAD

**Issue by tauntonian** [PokemonGoF/PokemonGo-Bot#1317]
### Expected Behavior
Bot should start working at determined location

### Actual Behavior
Bot crashes due to an error: 

> \PokemonGo\PokemonGo-Bot\pokemongo_bot\cell_workers\recycle_items_worker.py", line 18, in work
>     id_filter = self.config.item_filter.get(str(item_id), 0)
> AttributeError: 'str' object has no attribute 'get'

### Other Information
OS: Win10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
63b43878c72bfaacdfef0d7443f5ee019a16f585

**Comment by vicch** [comment]
Check your `configs/config.json` and look for `item_filter`, it should look like this:
```
"item_filter": {
    "1": { "keep" : 100 },
    "101": { "keep" : 10 },
    "102": { "keep" : 20 },
    "103": { "keep" : 50 },
    "201": { "keep" : 50 },
    "701": { "keep" : 80 }
},
```

**Comment by tauntonian** [comment]
That was it. Thank you.  I had copied the config from a previous version and it was missing this.
