### ISSUE TITLE
[Suggestion] If you do this can release from soft ban

### ISSUE THREAD

**Issue by yidongw** [PokemonGoF/PokemonGo-Bot#1321]
If you spin the pokestop for 40 times, you are good to go.

I already confirmed. It will be a great feature to add.

Also a friend told me if you throw 40 pokeballs, you get released too. I haven't tested yet. I'm not sure its throw and missing pokemon for 40 times or I have to hit pokemon 40 times.

**Comment by yidongw** [comment]
Even for the same pokestop

**Comment by aitzol** [comment]
I have tested and it works. Dirty patch attached
[patch.diff.txt](https://github.com/PokemonGoF/PokemonGo-Bot/files/388225/patch.diff.txt)
