### ISSUE TITLE
No such file or directory / No JSON object could be decoded

### ISSUE THREAD

**Issue by Messingaroung2323** [PokemonGoF/PokemonGo-Bot#1322]
### Expected Behavior
The bot will commence running.

### Actual Behavior
![image](https://cloud.githubusercontent.com/assets/20694819/17200226/5472bd98-5438-11e6-9241-bab1e7f6471e.png)

### Steps to Reproduce
Entering any of" ./run.sh or ./pokecli.py or python pokecli.py -cf ./configs/config.json".

### Other Information
OS: Mac Yosemite El Capitan
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
0ce208e8f7976ea0bfcdf6f34978d9411a5e7138

Any help?

**Comment by williamliu168** [comment]
In your config file, check to see if you had any ” instead of "

**Comment by kellyplitz** [comment]
I have the same problem :-(

**Comment by bjurn** [comment]
I have the same issue, any help on this? Running OS: Mac Yosemite El Capitan

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
