### ISSUE TITLE
auth_service

### ISSUE THREAD

**Issue by gregtampa** [PokemonGoF/PokemonGo-Bot#1324]
please update wiki to reflect correct values to use in config file for auth_service

**Comment by jcleigh** [comment]
"ptc" or "google" are valid values.

**Comment by gregtampa** [comment]
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException
ImportError: No module named pgoapi.exceptions
