### ISSUE TITLE
ask no catch no farm after update

### ISSUE THREAD

**Issue by nadarehime** [PokemonGoF/PokemonGo-Bot#1327]
> [23:42:58] Scanning area for objects....
> [23:42:58] Walking from (4.886674144978916e+18, 4.886674138550722e+18) to [4.886674144978916e+18, 4.886674138550722e+18] 0.00km

still like this

**Comment by fuzha** [comment]
```
git reset --hard
git pull -f
pip install -r requirements.txt --upgrade
rm ./data/last-location*
rm ./data/cells*
```

**Comment by nadarehime** [comment]
thx solve
