### ISSUE TITLE
[regression] pokemon capture adds only curve, previously it was excellent catch

### ISSUE THREAD

**Issue by livinstun** [PokemonGoF/PokemonGo-Bot#1329]
### Expected Behavior
catching pokemon should result in excellent like before
used to get 210 xp
### Actual Behavior
catching pokemon only results in curve capture
getting only 110 xp 
### Steps to Reproduce
check the xp during capture

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
63b43878c72bfaacdfef0d7443f5ee019a16f585

**Comment by livinstun** [comment]
15a034427d805e0bacb79fc0a1f3c96a6c93f0e3
(API update fixes (i2f etc) and lured pokemon catching (#1163))
regression caused by the above check in. it was working fine before.

**Comment by vicch** [comment]
So pokemon catch was always "excellent + curve" before? Isn't that behavior easily detectable?

**Comment by livinstun** [comment]
yes it was.
ya i think it was kind of easily detectable, may be random change will help

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
