### ISSUE TITLE
install help

### ISSUE THREAD

**Issue by roryhduffy** [PokemonGoF/PokemonGo-Bot#1330]
im on mac and im trying to install but as soon as i reach the command "virtualenv ." i hit a wall, have i missed something along the way?
x:~ xxxx$ git clone -b dev https://github.com/PokemonGoF/PokemonGo-Bot  
fatal: destination path 'PokemonGo-Bot' already exists and is not an empty directory.
x:~ xxxx$ cd PokemonGo-Bot  
x:PokemonGo-Bot xxxx$ virtualenv .
-bash: virtualenv: command not found
x:PokemonGo-Bot xxxx$

**Comment by roryhduffy** [comment]
rorys-mbp:~ roryhellwig$ $ git clone -b master https://github.com/PokemonGoF/PokemonGo-Bot  
-bash: $: command not found
rorys-mbp:~ roryhellwig$ $ cd PokemonGo-Bot  
-bash: $: command not found
rorys-mbp:~ roryhellwig$ $ virtualenv .  
-bash: $: command not found
rorys-mbp:~ roryhellwig$ $ source bin/activate  
-bash: $: command not found
rorys-mbp:~ roryhellwig$ $ pip install -r requirements.txt
-bash: $: command not found
rorys-mbp:~ roryhellwig$ 
rorys-mbp:~ roryhellwig$ brew update && brew install --devel protobuf
Updated Homebrew from c4deed6 to 97b6a30.
Updated 1 tap (homebrew/core).
==> Updated Formulae
exiftool                                 redpen                                 
Warning: protobuf-3.0.0-beta-4 already installed
rorys-mbp:~ roryhellwig$ $ git clone -b master https://github.com/PokemonGoF/PokemonGo-Bot  
-bash: $: command not found
rorys-mbp:~ roryhellwig$ $ cd PokemonGo-Bot  
-bash: $: command not found
rorys-mbp:~ roryhellwig$ $ virtualenv .  
-bash: $: command not found
rorys-mbp:~ roryhellwig$ $ source bin/activate  
-bash: $: command not found
rorys-mbp:~ roryhellwig$ $ pip install -r requirements.txt
-bash: $: command not found
rorys-mbp:~ roryhellwig$ git clone -b master https://github.com/PokemonGoF/PokemonGo-Bot  
fatal: destination path 'PokemonGo-Bot' already exists and is not an empty directory.
rorys-mbp:~ roryhellwig$ cd PokemonGo-Bot  
rorys-mbp:PokemonGo-Bot roryhellwig$ virtualenv .  
-bash: virtualenv: command not found
rorys-mbp:PokemonGo-Bot roryhellwig$ virtualenv
-bash: virtualenv: command not found
rorys-mbp:PokemonGo-Bot roryhellwig$ source bin/activate  
-bash: bin/activate: No such file or directory
rorys-mbp:PokemonGo-Bot roryhellwig$ pip install -r requirements.txt
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@3787ffbe2e80ebce8a02d48eebceb9edf40179c1#egg=pgoapi (from -r requirements.txt (line 1))
  Skipping because already up-to-date.
Collecting geopy==1.11.0 (from -r requirements.txt (line 2))
  Could not fetch URL https://pypi.python.org/simple/geopy/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement geopy==1.11.0 (from -r requirements.txt (line 2)) (from versions: )
No matching distribution found for geopy==1.11.0 (from -r requirements.txt (line 2))
rorys-mbp:PokemonGo-Bot roryhellwig$

**Comment by hklcf** [comment]
remove the existing "PokemonGO-Bot" folder

**Comment by hklcf** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation#requirements-click-each-one-for-install-guide

**Comment by surfaace** [comment]
please see installation guide
