### ISSUE TITLE
Please Implement proxy, like pokecli.py --proxy="http://PROXY_URL:PORT/"	

### ISSUE THREAD

**Issue by chauhan-rahul** [PokemonGoF/PokemonGo-Bot#1333]
### Expected Behavior
while executing the pokecli.py we can define the proxy url to use or something similar.
I am behind a proxy, direct connections to pokemon sites or other stuff are blocked here and unable to use the bot in any way.
all the dependencies like python virtualenv etc have the proxy functionality, would be nice if you could implement for this also.
or provide an option to define it in the config file..

**pokecli.py --proxy="http://PROXY_URL:PORT/"**
OR
in config file:
**"proxy": "http://PROXY_URL:PORT/",**

**Comment by Surceis** [comment]
First it must be implemented in pgoapi and gpsoauth.

**Comment by ferbeb** [comment]
You could try supernetworktunnel or a similar solution to tunnel all traffic through http as a workaround.
