### ISSUE TITLE
Is this a Niantic way to Identify bots ?

### ISSUE THREAD

**Issue by leovarmak** [PokemonGoF/PokemonGo-Bot#1336]
Hey !

As usually I was running the bot and suddenly I found this on my screen. The PokeStop appears in some Unicode stuff.
This is the location the bot was running - `40.7570099984601, -73.97768497467041`
OS- `Windows 10`
Branch- `Master`

![screenshot 21](https://cloud.githubusercontent.com/assets/14135553/17202443/d8a7885e-54b6-11e6-8574-b922e63d67e1.png)

**Comment by klvs** [comment]
Probably python unicode stuff. Not Niantic bot detetion imo.

**Comment by BobbyWibowo** [comment]
Probably the PokeStop name was written with some unicode characters or something. Such as characters from other languages?

**Comment by leovarmak** [comment]
@BobbyWibowo I don't think that PokeStop name would be non-english thing. Its because the pokestop is somewhere near Central Park, NY

**Comment by klvs** [comment]
@leovarmak What's the name of it? out of curiosity...

**Comment by leovarmak** [comment]
@klvs I have no Idea man.

**Comment by klvs** [comment]
@elanini scope it, plz?

**Comment by Surceis** [comment]
i think it was this pokestop [http://www.mapapokemongo.com/stops/b263de3aa9434bc99ac3a7ec17b81af8.12](url)

**Comment by klvs** [comment]
I rest my case

**Comment by leovarmak** [comment]
@Surceis @klvs I just been a PokeStop indeed. Closing the issue for now. Will reopen if necessary
