### ISSUE TITLE
Windows Keep Popping Up

### ISSUE THREAD

**Issue by fl3tching101** [PokemonGoF/PokemonGo-Bot#1337]
### Expected Behavior
Bot runs and give output on python shell

### Actual Behavior
Bot runs and gives output on python shell, but there is a constant flashing of what looks like command prompt windows opening and closing instantly. It makes it hard to use the computer for just about anything else while the bot is running.

### Other Information
OS: Windows 10
Computer: MSI GE62 Apache pro

**Comment by BobbyWibowo** [comment]
Oh, hi. I'm using MSI GE62 Apache Pro with Windows 10 (Enterprise) as well, but I have no such issue.
Is it possible for you to provide some kind animated GIF of the actual behavior?

**Comment by fl3tching101** [comment]
I believe my issue was I was using the Python IDLE to run the bot instead of using command prompt to run it, I went into command prompt and used that to run it, runs fine now without the annoying windows

**Comment by razer86** [comment]
The Google Protoc file runs as a seperate program to help decode some of the api responses, so when its called, it will run, receive the info from python, and then pass back the decoded response.

**Comment by TheGoldenXY** [comment]
Issue has been resolved, closing this.

/closed
