### ISSUE TITLE
Not evolving at start

### ISSUE THREAD

**Issue by Steefj3** [PokemonGoF/PokemonGo-Bot#1339]
### Expected Behavior
Bot should evolve pokemon at start

### Actual Behavior
It used to do this, but doesnt anymore. Only (not at start) one if evolve_captured is set. I have set evolve_all with specific pokemon.

### Other Information
Latest dev branch
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by JulioMansilla** [comment]
Please refer to Issue #1335 .

**Comment by TheGoldenXY** [comment]
This issue has already been fixed.

Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
