### ISSUE TITLE
Is there any way to keep the app from logging out?

### ISSUE THREAD

**Issue by Messingaroung2323** [PokemonGoF/PokemonGo-Bot#1343]
The first time I got this running it played for one hour and then logged out. Is there any way to keep it going for longer than that? (For example while I'm sleeping tonight)

**Comment by hklcf** [comment]
Which OS do you use?

**Comment by Messingaroung2323** [comment]
@hklcf Mac!

**Comment by liudayu** [comment]
Duplicated of #948 
Check temp solution in that page please 
/close
