### ISSUE TITLE
catchable-[username].jason not updating

### ISSUE THREAD

**Issue by mouendless** [PokemonGoF/PokemonGo-Bot#1345]
### Expected Behavior
For my understanding, the web/catchable-[username].json would be updated once I encountered some poke, and then the web would show. 
submodule has also been updated

### Actual Behavior
Previously it works but after I update (dev branch) today it became not showing. Other feature like moving or user info works well. I check the folder and the catchable-[username].json is always "{}" now. Anyway to fix this problem?

### Other Information
OS: CentOS

**Comment by krypttr** [comment]
Confirmed.

**Comment by luoy2** [comment]
same issue here.
