### ISSUE TITLE
Invalid cached location accepted and used

### ISSUE THREAD

**Issue by s7726** [PokemonGoF/PokemonGo-Bot#1346]
### Initial Conditions
Developmental inconsistencies lead to invalid location information ie (3.7e+18, 4.8e+18).
This information gets cached as the last user location

### Expected Behavior
pokecli should recognize invalid coordinates and either error out or restart from the location specified in the config.json

### Actual Behavior
pokecli appears to try and use the invalid coordinates and never ends up getting anywhere (rightfully)

### Steps to Reproduce
Fill in invalid lat and lon in the location cache and watch it walk no-where

### Other Information
OS: linux

I believe I ended up in this situation because the geo api had been updated and I had failed to `pip install -r requirements.txt` after doing a `git pull`. But this could also happen from a clumsy or malicious user. Any user supply-able data should always be validated.

**Comment by elsidoi** [comment]
Same issue on two of my machines. Update goi api and get this error.

**Comment by mackoj** [comment]
Same issue here

**Comment by s7726** [comment]
interim fix for the symptoms of this is to run `pip install -r requirements.txt` and then clear out your location cache in the data directory. But this bug is for making that process not necessary in the future.

**Comment by mackoj** [comment]
thanks it worked

**Comment by TheGoldenXY** [comment]
Looks like issue has been resolved.

/closed
