### ISSUE TITLE
config.json.pokemons.example missing Mr. Mime

### ISSUE THREAD

**Issue by Kassius509** [PokemonGoF/PokemonGo-Bot#1347]
### Expected Behavior
Listing all pokemon including Mr Mime.

### Actual Behavior
Mr Mime not there.

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
b7e133c09a6828f40cc535afbd95b1e3d1a4525a

**Comment by JulioMansilla** [comment]
@Kassius509 thank you for the heads up, the issue has been fixed in  the following dev commit: #5e6b8ae

**Comment by mizhgan** [comment]
Well, it`s also missed both genders of Nidoran =)

**Comment by TheGoldenXY** [comment]
This issue has been resolved.

/closed
