### ISSUE TITLE
code 404, message File not found

### ISSUE THREAD

**Issue by gregtampa** [PokemonGoF/PokemonGo-Bot#1353]
on the web
If you change the config file to a new username
after running the webserver for another username
you get a bunch of errors... I assume its caching something someplace..
whats the deal... i'm on slack if anyone wants to help debug.

**Comment by gregtampa** [comment]
Found a fix.. however it due to caching.. need to find out where it caching to...but here
to fix please do the following steps:

Navigate to the OpenPoGoBot folder.
Open a file and put in {}.
Save the file as catchable-abc123@gmail.com.json.
Restart webservice.
Repeat steps for location.json:

Navigate to the OpenPoGoBot folder.
Open a file and put in {}.
Save the file as location-abc123@gmail.com.json.
Restart webservice.

**Comment by ironbishop** [comment]
duplicate of #691, fixed in dev

**Comment by TheGoldenXY** [comment]
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/691

Also fixed in latest `dev` branch.

/closed
