### ISSUE TITLE
Bot Attempts To Evolve When Mode is 'spin'

### ISSUE THREAD

**Issue by EvilSupahFly** [PokemonGoF/PokemonGo-Bot#1354]
### Expected Behavior
When `"mode": "spin"` and `"evolve_all": "NONE"` are set in `config.json` - Walk from stop to stop and spin each one

### Actual Behavior
Attempts to evolve all pokemon on startup before walking form stop to stop

### Steps to Reproduce
Run the bot with the above settings in `config.json`

### Other Information
OS: Linix x64, Ubuntu 15.10, kernel 4.5.3-040503-generic #201605041831
Git Commit: c7ab5b03cb93b5393bebbc383545a50e8519e57a

**Comment by tstumm** [comment]
Set `"evolve_all": false` and please always test using newest builds when opening an issue.

**Comment by EvilSupahFly** [comment]
The Readme says "3. Not setting evolve_all or having any other string would
not evolve any pokemon on startup" so the "NONE" setting from the
config.json.example is wrong and the Readme is wrong.

On Jul 28, 2016 03:55, "tstumm" <notifications@github.com> wrote:

Set "evolve_all": false and please always test using newest builds when
opening an issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PokemonGoF/PokemonGo-Bot/issues/1354#issuecomment-235825539>,
or mute the thread

**Comment by buettner123** [comment]
If you set evolve_all to "NONE" it will only display the log message but wont evolve any pokemon. This seems to be just a logging issue

**Comment by EvilSupahFly** [comment]
OK. Cool.

**Comment by TheGoldenXY** [comment]
Looks like issue has been resolved. Closing this for now.

/closed
