### ISSUE TITLE
Release pokemon condition

### ISSUE THREAD

**Issue by KarimEA** [PokemonGoF/PokemonGo-Bot#1357]
### Expected Behavior
Release pokemon below CP OR  below IV

### Actual Behavior

Release Pokemon below CP AND below IV

![rundll32_2016-07-28_09-36-56](https://cloud.githubusercontent.com/assets/16318133/17204753/9450aab4-54a7-11e6-9f1d-90d6861adfef.png)

### Steps to Reproduce

Put in the config "any": {"release_below_cp": 800, "release_below_iv": 0.85, "logic": "or"} and start the bot

### Other Information
OS: WIN 10
Git Commit: 6dd0fade877a4e5281156381e8d1eff4d17316b8

**Comment by Surceis** [comment]
It's all work correct on screenshot (and config set to "logic" : "or"):
800>787 or 0.85>0.84 => true => exchange
800>974 or 0.85>0.56 => true => exchange
800>42 or 0.85>0.91 => true => exchange
800>302 or 0.85>0.38 => true => exchange

**Comment by KarimEA** [comment]
Oh damn i'm an idiot...
thanks to remind me that

**Comment by Bramzor** [comment]
No it does not work:

    "Hypno":        { "release_under_cp": 763, "release_under_iv": 0.8, "cp_iv_logic": "and" },

[x] Transferring Hypno with CP 1414

-> This sucks, really!

**Comment by KarimEA** [comment]
See the last config file
it changes

**Comment by Bramzor** [comment]
That config only works in the dev repository I assume? And that one does not work here.

Traceback (most recent call last):
  File "pokecli.py", line 291, in <module>
    main()
  File "pokecli.py", line 241, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 40 column 64 (char 1218)

**Comment by KarimEA** [comment]
that's right it works only on dev

**Comment by Bramzor** [comment]
Tried the dev but there is still  a bug there. And if someone else creates an issue for this, it just gets closed as invalid? #1372

**Comment by LostDGod** [comment]
With "OR" only 1 condition needs to be met to return true (release). For instance if you set up to release with this config: CP<800 IV<0.85 OR , it will release all pokes with CP<800 (regardless of IV) and all pokes with IV<0.85 (regardless of CP).
With "AND" both conditions need to be met to return true. So with your values: CP<800 IV<0.85 AND , the bot would only keep pokes with CP>800 AND IV>0.85.

**Comment by mrseeker** [comment]
I have this issue sometimes when a pokemon gets caught and for some unknown reason the bot crashes before it could dispose of the unwanted pokemon. When I restart the bot and check my list of pokemon, I have doubles in there that I am pretty sure don't belong there and should be released. Might be config issue or simply the fact that the bot only checks when a pokemon is caught, not when its updating its list of pokemon.

**Comment by tonz134** [comment]
I'm pretty sure the bot still reads the `OR` as `AND`(vice versa).

Latest Dev.
[08:40:51] Release config for Drowzee: Conf, CP 374 or IV 0.5 - Poke, CP 310 IV 0.56
[08:40:51] Exchanging Drowzee for candy!
```

**Comment by gillray1314** [comment]
here have the problem too , my setting are

"Dratini":      { "release_under_cp": 343, "release_under_iv": 0.9, "cp_iv_logic": "and" },

but my bot still keep the dratini , even the iv not meet 0.9 this value

[2016-07-28 20:35:02] [#] A Wild Dratini appeared! [CP 462] [Potential 0.49]
[2016-07-28 20:35:02] [#] IV [Stamina/Attack/Defense] = [9/2/11]
[2016-07-28 20:35:04] [x] Using Greatball (chance: 38.24%)... (0 left!)
[2016-07-28 20:35:05] [x] Captured Dratini! [CP 462] [IV 0.49]
[2016-07-28 20:35:06] [x] Captured Dratini! [CP 462]
[2016-07-28 20:35:43] [#] Something rustles nearby!
[2016-07-28 20:35:44] [#] A Wild Mankey appeared! [CP 170] [Potential 0.4]

any way to solve ? want a high iv and cp only

**Comment by mrseeker** [comment]
Thats the issue where the Dratini has a high CP but a low IV. The AND function checks if both are correct, and it appears only one of them does, so it goes "nope". I think OR would work better there.

**Comment by gillray1314** [comment]
ok thanks , maybe at this moment i try to set ridiculous cp to leep IV 0.9 pokemon

**Comment by LostDGod** [comment]
Re-read my previous comment, it explains how the OR and AND logic works. Check #1169 for more details.

**Comment by TheGoldenXY** [comment]
There is nothing wrong with the release config. You need to understand how boolean math works.

/closed
