### ISSUE TITLE
pokemon farming walking logic wrong

### ISSUE THREAD

**Issue by w1sht0l1v3** [PokemonGoF/PokemonGo-Bot#1358]
### Expected Behavior
the bot should walk in a pattern like a snail shell...just with corners and straight lines that are longer each turn...least this is how it was some time ago
![old_walk](https://cloud.githubusercontent.com/assets/1199041/17205042/9a0693ba-54b1-11e6-8e9b-070a688f4fa0.png)

### Actual Behavior
at this moment it moves only like this:
![poke_movement](https://cloud.githubusercontent.com/assets/1199041/17204892/b7031764-54b0-11e6-9244-5b2a818d77e4.png)

### Steps to Reproduce
use dev branch

### Other Information
OS: win7/debian8
Git Commit: 6dd0fade877a4e5281156381e8d1eff4d17316b8

**Comment by tstumm** [comment]
Increase `max_steps`

**Comment by sayasemut** [comment]
increase max_steps into ?

**Comment by longlhgithub** [comment]
...bigger one

**Comment by tstumm** [comment]
Well how big do you want that spiral to be? The one you wanted should equal 25 steps

**Comment by tstumm** [comment]
But currently we are working on that, so 5 should be enough

**Comment by w1sht0l1v3** [comment]
i always used the default "max_steps": 5

**Comment by tstumm** [comment]
Then wait for the PR to fix this.

**Comment by w1sht0l1v3** [comment]
that's why i opened the issue.so whoever knows how to fix it sees this :)

**Comment by tstumm** [comment]
The team decided that we wont change that parameter. Currently max_steps describe the length of the spiral in cell widths.
