### ISSUE TITLE
unicodeDEcodeError

### ISSUE THREAD

**Issue by data2700** [PokemonGoF/PokemonGo-Bot#136]
This error showed up with the latest release.   It seems to be an issue with certain european alphabet characters öäå

File "/usr/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 33: ordinal not in range(128)

**Comment by pseudoheld** [comment]
Same here

**Comment by s1x** [comment]
```
data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 43: ordinal not in range(128)


same here.

```
