### ISSUE TITLE
importError: cannot import name format_time

### ISSUE THREAD

**Issue by Scerchy** [PokemonGoF/PokemonGo-Bot#1362]
### Expected Behavior
The bot should launch when installing all prerequisites

### Actual Behavior
A manual installs of the 'utils' package is required.

### Steps to Reproduce
Get a fresh installation of both Python 2.7.x and clone this repository. When running the install.sh and then the run.sh you will encounter the error that there is no module named Utils (ImportError: No module named utils)

### Other Information
OS: Windows 7
I'm on the dev branch with latest commit 8d65cdc

###Screenshots
![image](https://cloud.githubusercontent.com/assets/17570109/17206018/efac5b82-54ad-11e6-826a-228dec64b25b.png)
ImportError for Utils module.

After installing Utils module using Pip: (in my case >C:\Python27\python.exe -m pip install utils)
![image](https://cloud.githubusercontent.com/assets/17570109/17206054/2dd8bf72-54ae-11e6-93ae-5d84ad69633c.png)
The format_time error arises
![image](https://cloud.githubusercontent.com/assets/17570109/17206066/3d3ef83c-54ae-11e6-8f9f-2d93106e7649.png)

**Comment by Scerchy** [comment]
Well it seems that the utils.py from the master branch just disappeared in this dev version.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
