### ISSUE TITLE
"spin_forts": false has no effect

### ISSUE THREAD

**Issue by wcrwcr** [PokemonGoF/PokemonGo-Bot#1363]
### Expected Behavior
not spin any forts

### Actual Behavior
[10:33:30] Spinning ...
[10:33:30] Loot:
[10:33:30] 50 xp
[10:33:31] - 1x Pokeball (Total: 169)
[10:33:31] - 1x Greatball (Total: 34)
[10:33:31] - 1x Super Potion (Total: 31)
[10:33:31] PokeStop on cooldown. Time left: 5.13 minutes

### Steps to Reproduce
config 
    "catch_pokemon": true,
    "spin_forts": false,

run

### Other Information
OS: win7
Git Commit: 8d65cdc23035a1d823f471db5f566c3ea5fb8238

**Comment by TheSavior** [comment]
Are you running the latest commit on dev? That configuration is for dev

**Comment by wcrwcr** [comment]
yes. 8f77214ee409ae05c18887f771f84fb01b09bbee acts the same way

**Comment by elfenars** [comment]
+1

**Comment by tonz134** [comment]
+1

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
