### ISSUE TITLE
Just walking around finding nothing?

### ISSUE THREAD

**Issue by coachgibbo** [PokemonGoF/PokemonGo-Bot#1366]
I found a pokemon the first time I ran it and the game said "no pokeballs switching to farming mode" or something like that, and nothing has happened since then. It just's been saying this for the last 10 minutes.
https://gyazo.com/b5a48bad6db6b89ebdf311ce278c618a
Is there anything I need to change to get it to work? I can give more info if necessary

**Comment by surfaace** [comment]
check that you max_step is above like 10 in config, it can fail and go into a loop if max_step is to low
