### ISSUE TITLE
pokemon remove protection

### ISSUE THREAD

**Issue by Bramzor** [PokemonGoF/PokemonGo-Bot#1367]
I'm using the master branch and got a few important pokemon being released because of some strange bug. Is there a way to protect them from being released?
For example by adding them to the favorites, changing their names or...?

**Comment by Philipp59** [comment]
check release config and your initial_transfer in config.

release config e.g
add your fav to always capture

{
    "any": {
        "release_under_cp": 9,
        "release_under_iv": 0.93,
        "cp_iv_logic": "or"
    },
    "My Pokemon": {
        "release_under_cp": 0,
        "release_under_iv": 0,
        "cp_iv_logic": "or"
    },
    "exceptions": {
        "always_capture": [
            "Pidgey",
            "Caterpie",
            "Weedle",
            "Venusaur",
            "Charizard",
            "Blastoise",
            "Onix",
            "Hitmonlee",
            "Hitmonchan",
            "Chansey",
            "Kangaskhan",
            "Mr. Mime",
            "Gyarados",
            "Lapras",
            "Ditto",
            "Snorlax",
            "Dragonite",
            "Mew",
            "Aerodactyl",
            "Kabutops",
            "Gengar",
            "Alakazam",
            "Raichu",
            "Omastar"
        ]
    }
}

**Comment by Bramzor** [comment]
Always_capture will overwrite the release part? Because always_capture =/= do not release.

**Comment by Philipp59** [comment]
yes thats the logic behind 
but keep in mind that initial_transfer in config overwrites all so set this to 0

**Comment by surfaace** [comment]
function is more clear and better in dev branch, but solution pasted is for master branch
