### ISSUE TITLE
unexpected server error

### ISSUE THREAD

**Issue by fajar125** [PokemonGoF/PokemonGo-Bot#1368]
is it just me or bot not working anymore?
or should i update it.
i download the bot on Monday this week.

**Comment by rednka** [comment]
i have the same problem, i have update the bot & other no match.

RIP PokemonGo-Bot ?

**Comment by hklcf** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/1365#issuecomment-235838166

**Comment by adpit** [comment]
yes, same here 
perhaps , server maintenance

**Comment by leonso** [comment]
same here

**Comment by rednka** [comment]
Why i have no problem to connect in my smartphone ? ... (EU)

**Comment by gagas3113** [comment]
all bot error confirmed.. ban wave incoming in 3..2..1..

**Comment by rednka** [comment]
He can't ..

A lot of people cheat because he don't live in city .. if he ban definitly all cheater it's a team kill haha

**Comment by thehawkes** [comment]
According to http://ispokemongodownornot.com/, all login servers (google and ptc) are down since ~20mins.
so let's wait.

**Comment by adpit** [comment]
maybe they start blocking login without a smartphone or with API

**Comment by zenety** [comment]
But logging in through the app works fine. Through the API fails. Maybe they disabled the API?

**Comment by antoineweytens** [comment]
http://ispokemongodownornot.com/ is probably using pgoapi as well.

**Comment by Raudaschl** [comment]
Back up now (EU)

**Comment by rihago** [comment]
Looks like they changed the api

https://pgorelease.nianticlabs.com/plfe/rpc

HTTP ERROR: 405

Problem accessing /plfe/rpc. Reason:

    HTTP method GET is not supported by this URL
Powered by Jetty://

**Comment by surfaace** [comment]
servers are down

**Comment by rihago** [comment]
servers are not down.

on my mobile everything works, they changed the API access.

**Comment by YuxuanChen** [comment]
Do a `git pull`, everything should be working again.

**Comment by rihago** [comment]
11:16:55] The API didn't return player info, servers are unstable - retrying.

**Comment by rednka** [comment]
git pull worked thanks !

**Comment by bmays** [comment]
Everything working again for me!

**Comment by hklcf** [comment]
my mobile cant login too(google acc)

Send from my Galaxy Note 3

2016/7/28 5:16 下午 於 "Yuxuan Chen" <notifications@github.com> 寫道：

**Comment by adpit** [comment]
Legend, git pull

**Comment by zenety** [comment]
Login successful

**Comment by akatasonov** [comment]
![image](https://cloud.githubusercontent.com/assets/6917547/17207491/8a983d5a-54bd-11e6-8c4e-b13e8bf83bc4.png)

`git pull` didn't work for me

**Comment by adpit** [comment]
maybe dev version,

root@localhost:~/PokemonGo-Bot# git pull
remote: Counting objects: 13, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 13 (delta 5), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (13/13), done.
From https://github.com/PokemonGoF/PokemonGo-Bot
 * [new branch]      catch-transfer_worker-error -> origin/catch-transfer_worker-error
   8f77214..7e608c2  dev        -> origin/dev
Already up-to-date.

**Comment by Sterkoel** [comment]
@akatasonov At least it solved the login issue :)

**Comment by fajar125** [comment]
i didnt git pull things, but now i already logged in.
but really slow response

**Comment by Philipp59** [comment]
servers are down.... just relaxe and wait app also don't work 
check status: [http://allestörungen.de/stoerung/pokemon-go](http://allestörungen.de/stoerung/pokemon-go)  (german site)

**Comment by caudrelierm** [comment]
`git pull` worked for me as well
![selection_095](https://cloud.githubusercontent.com/assets/7402764/17207718/200b96b4-54b6-11e6-96b0-2018d5b5c6e9.png)

**Comment by akatasonov** [comment]
Got the dev branch working!! Thank you! @mickaelftw how did you get such a nice bash prompt? :)

**Comment by sayasemut** [comment]
i still cannot login .. :(

when i tried to pull this notif show up

$ git pull
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/PokemonGoF/PokemonGo-Bot
   5f0781c..e5c0c8f  catch-transfer_worker-error -> origin/catch-transfer_worker-error
Already up-to-date.

**Comment by hklcf** [comment]
@sayasemut run `git checkout dev`

Send from my Galaxy Note 3

**Comment by sayasemut** [comment]
already using branch dev...

and already up to date

and still can't login ...

**Comment by tstumm** [comment]
This is a server issue and we can't fix that.
