### ISSUE TITLE
Need help about installation. "fatal: Not a git repository (or any of the parent directories): .git"

### ISSUE THREAD

**Issue by hsizadam** [PokemonGoF/PokemonGo-Bot#1370]
I'm trying to use it on windows. i am new at python and got some issues. i did everything, set up git and others

i did this steps
$ git clone -b master https://github.com/PokemonGoF/PokemonGo-Bot  
$ cd PokemonGo-Bot  
$ pip2 install -r requirements.txt

when im trying to "$ git submodule init" its give me this error 
fatal: Not a git repository (or any of the parent directories): .git

thanks for your help already guys.

**Comment by surfaace** [comment]
no issues with latest dev7e608c2ff5367be0e22cdf55228056aad5a0d718
