### ISSUE TITLE
requirements.txt error?

### ISSUE THREAD

**Issue by roryhduffy** [PokemonGoF/PokemonGo-Bot#1371]
(PokemonGo-Bot) Rorys-MBP:PokemonGo-Bot roryhellwig$ pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

ive done everything before this and now im stuck

**Comment by surfaace** [comment]
check that file is there.. it cannot find it at the moment

**Comment by roryhduffy** [comment]
the file isnt there

**Comment by roryhduffy** [comment]
excuse me what do i do

(PokemonGo-Bot) Rorys-MBP:PokemonGo-Bot roryhellwig$ brew update && brew install --devel protobuf
Updated 1 tap (homebrew/core).
==> Updated Formulae
etcd                          gource                        libphonenumber                offlineimap                   purescript                    utf8proc                    
Warning: protobuf-3.0.0-beta-4 already installed
(PokemonGo-Bot) Rorys-MBP:PokemonGo-Bot roryhellwig$ git clone --recursive -b master https://github.com/PokemonGoF/PokemonGo-Bot 
fatal: destination path 'PokemonGo-Bot' already exists and is not an empty directory.
(PokemonGo-Bot) Rorys-MBP:PokemonGo-Bot roryhellwig$ cd PokemonGo-Bot  
(PokemonGo-Bot) Rorys-MBP:PokemonGo-Bot roryhellwig$ virtualenv .
New python executable in /Users/roryhellwig/PokemonGo-Bot/PokemonGo-Bot/bin/python2.7
Also creating executable in /Users/roryhellwig/PokemonGo-Bot/PokemonGo-Bot/bin/python
Installing setuptools, pip, wheel...done.
(PokemonGo-Bot) Rorys-MBP:PokemonGo-Bot roryhellwig$ source bin/activate  
(PokemonGo-Bot) Rorys-MBP:PokemonGo-Bot roryhellwig$ pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
(PokemonGo-Bot) Rorys-MBP:PokemonGo-Bot roryhellwig$
