### ISSUE TITLE
[DEV] Bot does not start parsing Config does not work?

### ISSUE THREAD

**Issue by maestroi** [PokemonGoF/PokemonGo-Bot#1372]
### Expected Behavior

Bot starting, parsing the config file

### Actual Behavior
`maestro@sd-93980:~/dev/PokemonGo-Bot$ python pokecli.py  
[11:09:43] PokemonGO Bot v1.0  
[11:09:43] No config argument specified, checking for /configs/config.json 
Traceback (most recent call last):
  File "pokecli.py", line 291, in <module>
    main()
  File "pokecli.py", line 241, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 3 column 35 (char 66)
`

### Steps to Reproduce
New Dev Downloaded on 28-7 10:00 GMT
Using Default Config file with only my credentials 

### Other Information
OS: Ubuntu server 16.04

**Comment by Bramzor** [comment]
Same issue here on Mac. Already checked the config a few times but it's not an error in the json.

**Comment by surfaace** [comment]
no problem parsing config.json.example in either dev or master. check your config please

**Comment by maestroi** [comment]
@surfaace i use the default one?

**Comment by Bramzor** [comment]
Same here. this is my config:

{
    "auth_service": "google",
    "username": "xxx@gmail.com",
    "password": "xxx",
    "location": "xxx",
    "gmapkey": "xxx",
    "max_steps": 5,
    "catch_pokemon": true,
    "spin_forts": true,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "1": { "keep" : 100 },
      "101": { "keep" : 10 },
      "102": { "keep" : 30 },
      "103": { "keep" : 30 },
      "201": { "keep" : 30 },
      "701": { "keep" : 100 }
    },
    "evolve_all": "Pidgey,Weedle",
    "evolve_speed": 20,
    "cp_min": 300,
    "use_lucky_egg": false,
    "evolve_captured": false,
    "release_pokemon": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"}
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "Pidgey": {"release_below_cp": 0, "release_below_iv": 0.8", "logic": "or"},
      "Rattata": {"always_release": true},
      "Zubat": {"release_below_cp": 200, "release_below_iv": 0.8", "logic": "or"}
    }
}

**Comment by Bramzor** [comment]
@maestroi , Tried with a new copy of the config and not copy pasting anything from a previous one but just filling in. And it did work. So seems indeed invalid.
