### ISSUE TITLE
New bot modes don't work properly.

### ISSUE THREAD

**Issue by JulioMansilla** [PokemonGoF/PokemonGo-Bot#1374]
### Expected Behavior
"catch_pokemon": false, => Bot will not catch pokemons
"spin_forts": false, => Bot will not spin Pokestops

### Actual Behavior
"catch_pokemon": false, => Bot will catch pokemons
"spin_forts": false, => Bot will spin Pokestops
This means the Bot is not running in "mode": all, once again. 
### Steps to Reproduce
set either "catch_pokemon" or "spin_forts" to false

### Other Information
OS: Mac
Git Commit: 7e608c2ff5367be0e22cdf55228056aad5a0d718

### Source of the change
f6755971c39b61b6204c6bfcad6dbad32a6f621e

**Comment by tonz134** [comment]
+1

**Comment by w1sht0l1v3** [comment]
confirm for branch dev on hash e25a7091f5f26eef17bc38f6f90df26ad199ffbc
i set spin_forts to false and it still goes for them

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
