### ISSUE TITLE
When Inventory is full and there is no PokeBalls it's an endless loop

### ISSUE THREAD

**Issue by d3dx9de** [PokemonGoF/PokemonGo-Bot#1376]
### Expected Behavior
Automaticlly remove items from bag

### Actual Behavior
Does nothing except of a endless loop
http://puu.sh/qhh4d/c7e81d90d4.png

### Steps to Reproduce
Get a full inventory without pokeballs

### Other Information
OS: Debian 8 Jessie (Docker)
Git Commit: 893483778366075aa9f3b80e090b448088439b93

**Comment by VictorChen** [comment]
How would it know which items to remove? You should specify the items you want to keep.

Ex: 

```
"item_filter": {
  "1": { "keep" : 50 },
  "2": { "keep" : 100 },
  "3": { "keep" : 200 },
  "101": { "keep" : 0 },
  "102": { "keep" : 0 },
  "103": { "keep" : 0 },
  "201": { "keep" : 0 },
  "701": { "keep" : 10 }
}
```

The above tells the bot to keep at most 50 pokeballs, 100 great balls, 200 ultra balls, 10 razz berries and throw away all potions/revives. See https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Item-ID's for item codes

**Comment by d3dx9de** [comment]
Oh okay. Sorry, I didn't read it. :D

Thanks :)

**Comment by sangwon04** [comment]
@VictorChen didn't know you could do this! However, doing this results in errors...something with splitting by the comma delimiter (can't remember off the top of my head).

**Comment by VictorChen** [comment]
@sangwon04 are you on the master branch? this only works on dev

**Comment by sangwon04** [comment]
@VictorChen that explains it then.
