### ISSUE TITLE
Pgoapi import problem

### ISSUE THREAD

**Issue by ka1nsha** [PokemonGoF/PokemonGo-Bot#1381]
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/home/user/Poke/pokemongo_bot/__init__.py", line 13, in <module>
    from pgoapi import PGoApi
ImportError: cannot import name PGoApi

### Other Information
OS: Linux 64-Bit Debian Based
6e99169d963bd8637dfb55426650f2fe15e694bd

**Comment by thehawkes** [comment]
`pip install -r requirements.txt`

please check the output of 
`pip freeze | grep -i pgoapi`

**Comment by ka1nsha** [comment]
I do installed one week ago

**Comment by thehawkes** [comment]
`pip install -r requirements.txt --force-reinstall -U`

the version changed since last week ;)

**Comment by ka1nsha** [comment]
Okey I try and write here response

**Comment by ka1nsha** [comment]
Same error after force-reinstall 
![error](http://i.hizliresim.com/6nOW1l.png)
