### ISSUE TITLE
A legend to all the config options please? 

### ISSUE THREAD

**Issue by ssm34** [PokemonGoF/PokemonGo-Bot#1387]
Like, where is the documentation about, say, all the different modes for the "mode" parameter? 

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by ayiire** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files

**Comment by ironbishop** [comment]
i think the "mode" parameter is deprecated, see the link provided by ayiire

the master and dev branches have different configuration parameters, and that can be misleading at first

**Comment by xavor92** [comment]
Maybe a Link in the ReadMe to the wiki (or at least a hint) could be helpful?

**Comment by regzzz** [comment]
Mode : all, poke, farm

**Comment by ssm34** [comment]
The most recommended commit to be on right now, please? Thanks for the help.

**Comment by ironbishop** [comment]
the master branch is working perfectly, just it stops after 59 minutes.
fine for me.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
