### ISSUE TITLE
Release isnt working

### ISSUE THREAD

**Issue by prometheus247** [PokemonGoF/PokemonGo-Bot#1393]
### Expected Behavior
Pokemons should be released, following the config. 

### Actual Behavior
They are actually not. Config is getting ignored.

### Steps to Reproduce
**Log:**
[14:05:54] Using Pokeball (chance: 64.82%)... (75 left!)
[14:05:56] Captured Pidgey! [CP 197] [Potential 0.58] [13/0/13]
[14:06:02] Scanning area for objects....
[...]
[14:07:38] Using Pokeball (chance: 62.29%)... (74 left!)
[14:07:40] Captured Spearow! [CP 98] [Potential 0.49] [1/11/10]
[14:08:27] Something rustles nearby!

**Config:**
http://pastebin.com/N51SSJ8Z

I did follow the instructions here: https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files
Tried alot of stuff with the syntax, but in the end - i have no clue whats going on.

### Other Information
OS: debian 7.11
Git Commit: 7e608c2ff5367be0e22cdf55228056aad5a0d718

**Comment by cyberflow** [comment]
+1

**Comment by tonz134** [comment]
I don't see this thought "release_pokemon": true,

**Comment by skorokithakis** [comment]
@tonz134 Can confirm that fixed it. Can you guys stop adding config options that are forwards-incompatible? This issue would have been prevented if `release_pokemon` were `True` by default, same as in the previous version.

**Comment by prometheus247** [comment]
Yeah I guess I was on a wrong example config with this argument. Thanks @tonz134  for the good eyes.

One question though: Wouldnt it be great if the bot does the checkup for releaseable Pokemons at the start? Im just thinking - when building up your config there will be flaws you never will be able to resolve - only via logging in to your Bot manually and kicking out your pre-config release Pokemons. Even little changes to it when it comes to releases are a pain in the ass when only checked for after a pokemons has been caught.

**Comment by tonz134** [comment]
I'm pretty sure the release_pokemon will read bags.
just make sure yo use OR if you have a specific pokemon you want to keep like. 
_Dragonite with 500cp IV 0.96_
`OR` means (AND) and `AND` means (OR), that's how bot reads it for some reason.

`"Dragonite": { "release_below_cp": 1221, "release_below_iv": 0.9, "logic": "or" },`

**Comment by prometheus247** [comment]
Thanks, I wanted to focus on realising the 4 types of crap before I head to new configs.
I did change my config in the way you mentioned it, @tonz134 

Still: 

[...]
```
[15:06:25] A Wild Spearow appeared! [CP 162] [Potential 0.73]
[15:06:25] IV [Stamina/Attack/Defense] = [13/12/8]
[15:06:28] Using Pokeball (chance: 50.05%)... (49 left!)
[15:06:31] Captured Spearow! [CP 162] [Potential 0.73] [13/12/8]
```
[...]

**Updates Config Part**
[...]
```
"release": {
      "Rattata": {"release_pokemon": true},
      "Pidgey": {"release_pokemon": true},
      "Spearow": {"release_pokemon": true},
      "Weedle": {"release_pokemon": true}
    }
}
```

I dont get it :(

**Comment by tonz134** [comment]
works fine on my end.
can you post your config?

**Comment by prometheus247** [comment]
Fu*k me...

I confused the always_release with release_pokemon option.
I was  missing the release_pokemon general option completely.

So cut things short, you need a general option "release_pokemon" true AND you need to configure your undesired Pokemons below via "always_release" or "release_below_cp" or "release_below_iv" ...

Its finally working:

```
[15:33:53] Starting PokemonGo Bot....
[15:33:54] Exchanging Weedle for candy!
[15:33:58] Exchanging Weedle for candy!
[15:34:01] Exchanging Weedle for candy!
[15:34:05] Exchanging Weedle for candy!
[15:34:09] Exchanging Weedle for candy!
```

Thanks for your endurance @tonz134 

Here is my config if any1 else has been in the same struggle. Its working with the recent Bot :)
http://pastebin.com/eJNGtgeN
