### ISSUE TITLE
item filter

### ISSUE THREAD

**Issue by yehan77** [PokemonGoF/PokemonGo-Bot#1394]
### Expected Behavior
i just want the varies of pokeballs. not revives 
what are the item numbers?
### Actual Behavior
 "item_filter": "101,102,103,104",

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by arnogues** [comment]
Please RTFM : 
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files
And then https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Item-ID's

**Comment by xorinzor** [comment]
@yehan77 Read the manual first before asking a question. @arnogues has linked them.

Close this issue please.

**Comment by TheGoldenXY** [comment]
Please read the wiki.

/closed
