### ISSUE TITLE
Logging Error

### ISSUE THREAD

**Issue by ragnaroksg** [PokemonGoF/PokemonGo-Bot#1396]
[2016-07-28 14:30:28] [x] PokemonGO Bot v1.0
[2016-07-28 14:30:28] [x] Configuration initialized
[2016-07-28 14:30:28]
[2016-07-28 14:30:28] [x] Address found: New York, Central Park
[2016-07-28 14:30:28] [x] Position in-game set as: (40.7711329, -73.97418739999999, 0.0)
[2016-07-28 14:30:28]
[2016-07-28 14:30:28] Login Error, server busy

I've tried the previous solutions but it still can't work. Somebody can help me please?

**Comment by buettner123** [comment]
As the message is pointing out the server is busy. This has nothing to do with the bot but with the niantic servers. 
If you want to see the serverstatus take a look at: http://ispokemongodownornot.com/
Servers are unstable at the moment.

**Comment by ragnaroksg** [comment]
But even the serverstatus is critical, I can still login from the application in my phone

**Comment by arnogues** [comment]
It's not a bot bug...

**Comment by buettner123** [comment]
There is more than one login/game server. Seems like you where lucky and your phone picked a good one while the bot got a one that couldn't handle the request.
Fact is, that the servers are unstable atm and you should just try again once in a while..

**Comment by BoGnY** [comment]
Did you try login with google account?? Did you have 2 factor authentication in your google account??

If yes, you have to generate an app password [here](https://security.google.com/settings/security/apppasswords?utm_source=OGB), after that, add the application password just create in your config.json in "password" setting

;)

**Comment by TheGoldenXY** [comment]
The Pokemon Trainer Club (PTC) servers might be down. Please try again later.

/closed
