### ISSUE TITLE
Takes over 10 tries to walk 0.0X away

### ISSUE THREAD

**Issue by weknin** [PokemonGoF/PokemonGo-Bot#1397]
### Expected Behavior
Bot should arrive to fort at first/second try

### Actual Behavior
![image](https://cloud.githubusercontent.com/assets/9269939/17212666/3e63a566-54d9-11e6-84bb-ddc9073317e2.png)

Takes so many tries to walk 0.0X away

### Steps to Reproduce
Default config :
"max_steps": 5
"walk": 4.16,

### Other Information
OS: Windows
Git Commit: 7e608c2ff5367be0e22cdf55228056aad5a0d718

I saw this issue once, yet couldn't find a proper solution for this.

**Comment by BScreen** [comment]
As far as I can tell it's because your bot walks quite slowly. Since it takes so long to walk from A to B there are multiple log entries for the same location.
If you increase the walk speed you wouldn't see the same log entry more than once.

BTW I'd rather see a progress bar than have my log flooded with the current coordinates.

**Comment by vicch** [comment]
Are you running `dev` ?
Check the manual: https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files
Walk speed is now in km/h.

**Comment by weknin** [comment]
Raising the walk speed fixed it :)

**Comment by ayiire** [comment]
@BScreen 

I brought this up but they removed the progress bar for log population which I think line by line updates causes more population?

The old geolocation updates were better IMO. I'd look at the map to see where I was, as long as I know where point A was and point B was
`[2016-07-28 09:34:07] [#] Walking from (40.710519, -74.009057) to (40.710122, -74.00735) for approx. 1.02 minutes`

This was my post
https://github.com/PokemonGoF/PokemonGo-Bot/issues/1212

**Comment by BScreen** [comment]
@ayiire 
Both the log updates and the progress bar aren't really necessary imo, but I really liked the time estimates. Shame it's been removed in the dev.

**Comment by TheGoldenXY** [comment]
This feature has been removed in the dev branch. Please upgrade to the latest `dev` branch and consider rising the walk speed. Closing this for now.

/closed
