### ISSUE TITLE
[Suggestion] Add an argument for more precise prints

### ISSUE THREAD

**Issue by Gugu42** [PokemonGoF/PokemonGo-Bot#14]
I'm going to try to make it by myself, but I don't know if I can succeed so I'll still leave it here:

Basically, instead of having everything printed out, add an argument to shorten it (Only shows "Captured %POKEMON% [CP XXX]" or "Pokestop %NAME% visited, found %ITEMS%")

**Comment by harsh1412** [comment]
Need this +1

**Comment by Reaver01** [comment]
Implemented for Pokemon.  Will look into Pokestops/Items later.

**Comment by Gugu42** [comment]
Oh I see, then I'll close this, thanks for your help !
