### ISSUE TITLE
Server seems to be busy or offline - try again!

### ISSUE THREAD

**Issue by crack00r** [PokemonGoF/PokemonGo-Bot#140]
[#] Scanning area for objects (1 / 25)
[#] Walking from (53.1381631, 8.216335599999999) to (53.1381631, 8.216335599999999) for approx. 0.0 seconds
[#] Finished walking to (53.1381631, 8.216335599999999)
(53.1381631, 8.216335599999999, 0)
[#] Something rustles nearby!
[#] A Wild Drowzee appeared! [CP129]
[x] Using Greatball...
[x] Captured Drowzee! [CP129] - exchanging for candy
[x] Exchanged successfuly!
2016-07-22 09:42:48,247 [    pgoapi] [ INFO] Server seems to be busy or offline - try again!
[x] Exchanged successfuly!
2016-07-22 09:43:07,391 [    pgoapi] [ INFO] Server seems to be busy or offline - try again!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
[x] Exchanged successfuly!
Traceback (most recent call last):
  File "C:\Users\Manuel\Desktop\PokemonGo-Bot-master\pokecli.py", line 120, in <module>
    main()
  File "C:\Users\Manuel\Desktop\PokemonGo-Bot-master\pokecli.py", line 117, in main
    bot.take_step()
  File "C:\Users\Manuel\Desktop\PokemonGo-Bot-master\bot.py", line 29, in take_step
    self.stepper.take_step()
  File "C:\Users\Manuel\Desktop\PokemonGo-Bot-master\stepper.py", line 63, in take_step
    self.bot.work_on_cell(cell,position)
  File "C:\Users\Manuel\Desktop\PokemonGo-Bot-master\bot.py", line 36, in work_on_cell
    worker.work()
  File "C:\Users\Manuel\Desktop\PokemonGo-Bot-master\cell_workers\pokemon_catch_worker.py", line 81, in work
    self.transfer_pokemon(list(Set(id_list2) - Set(id_list1))[0])
IndexError: list index out of range

C:\Users\Manuel\Desktop\PokemonGo-Bot-master>

**Comment by s1x** [comment]
Servers are offline. Check status. http://ispokemongodownornot.com/

**Comment by jtdroste** [comment]
Correct, servers are down.  Nothing we can do about this.
