### ISSUE TITLE
Do not transfer on startup

### ISSUE THREAD

**Issue by ayiire** [PokemonGoF/PokemonGo-Bot#1400]
Running dev, commit - 7e608c2ff5367be0e22cdf55228056aad5a0d718

It seems like the config file for initial transfer is gone now. When "release_pokemon": is set to false, transferring pokemon will not occur at all when capturing pokemon.

Setting it true will allow Pokemon to be transferred after capture but also will transfer any other pokemon on startup that is behold the thresholds set on the config file.

How do I get pokemon to only be transferred after capture, like the previous commits (Not sure when this changed). I have pokemon in my bag that's below the threshold but have perfect IV.

**Comment by tonz134** [comment]
just use `OR` instead of `AND`, It seems the bot reads `OR` as `AND`.
`"Dragonite": { "release_below_cp": 1246, "release_below_iv": 0.9, "logic": "or" },`

**Comment by ayiire** [comment]
I know of that but the previous behavior was more friendly with existing pokemon.

**Comment by tonz134** [comment]
That's what im wondering too.

**Comment by ayiire** [comment]
It's just the and/or logic isn't working properly and the config files tend to change every night.

With the previous behavior, I would run the bot near my area for X amount of time then log in my phone to clean up any pokemon that wasn't released after auditing them and their movesets. Remember movesets > IV > CP for battling

**Comment by TheGoldenXY** [comment]
The and/or logic is working perfectly fine. You don't understand boolean math, that's the issue here.

Please read more here: https://en.wikipedia.org/wiki/Truth_table#Logical_conjunction_.28AND.29
Conjunction = AND
Disjunction = OR

/closed
