### ISSUE TITLE
Install fail on linux

### ISSUE THREAD

**Issue by LoloLaurentiu** [PokemonGoF/PokemonGo-Bot#1401]
OS: Ubuntu 14.04
pip install -r requirements.txt
gets me to this error: 
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/protobuf-to-dict
Storing debug log for failure in /root/.pip/pip.log
what should I do? thanls

**Comment by arnogues** [comment]
Someone in the internet said : 
Fixed it with `apt-get install libcap-dev`

**Comment by LoloLaurentiu** [comment]
@arnogues didn't fixed for me...I get the same error

**Comment by greynaert** [comment]
Check your python version, this app is for python 2.7 if you launched you virtualenv in python3 it will fail on the dependency.

To select 2.7 as the python version of your env do `virtualenv --python=/usr/bin/python2.7 .` instead of `virtualenv .`

**Comment by LoloLaurentiu** [comment]
@greynaert 
python --version
Python 2.7.6

**Comment by Calcyfer** [comment]
Try using the setup.py file to install the requirements.

**Comment by LoloLaurentiu** [comment]
@Calcyfer 
python setup.py
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by Calcyfer** [comment]
Looks like that got broken.. =/
Do you also have Python 3 installed?

**Comment by LoloLaurentiu** [comment]
@Calcyfer yes do I have to delete it ? 

python3 --version
Python 3.4.3

**Comment by Calcyfer** [comment]
It might help - I'm guessing pip is configured for python 3, not 2.7, hence the egg_info not working correctly.
Try removing both python 3 and pip, then reinstalling pip.

**Comment by friederschueler** [comment]
or just use pip2 instead of pip executable (should be available)

**Comment by LoloLaurentiu** [comment]
after I deleted python 3 I get this error even with pip2
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-XbLvLB/protobuf-to-dict/

**Comment by friederschueler** [comment]
You did install protobuf?

apt-get install python-protobuf (python2-protobuf?)

**Comment by LoloLaurentiu** [comment]
ok I reinstalled everything 
and now after pip install -r requirements.txt I didn't recived any erros.. I think now I just have to setup my bot and ./pokecli.py

**Comment by Calcyfer** [comment]
Indeed, should work fine now.

**Comment by LoloLaurentiu** [comment]
@Calcyfer 1 more question. is it working with PTC login or only with google ?

**Comment by Calcyfer** [comment]
Google is generally more stable than the PTC login servers.
Check here for a good server status website : http://ispokemongodownornot.com/

**Comment by TheGoldenXY** [comment]
This issue has been resolved.

/closed
