### ISSUE TITLE
Issue closed due to misunderstanding,

### ISSUE THREAD

**Issue by sarandafl** [PokemonGoF/PokemonGo-Bot#1405]
#1144 was closed due to a misunderstanding. 

For some google accounts the bot is giving a "Login server busy" error.

**Comment by ayiire** [comment]
There was login problems with google yesterday.

**Comment by Calcyfer** [comment]
I'm afraid there's not much we can do about that, Servers have been unstable for a while.
I currently have issues with both Google and PTC logins.

**Comment by katanakiwi** [comment]
Perhaps you are using 2-step authentication? See the FAQ at https://github.com/PokemonGoF/PokemonGo-Bot/wiki/FAQ
