### ISSUE TITLE
(REQUEST) Bot Should Proceed To Nearest Unvisited Pokestop

### ISSUE THREAD

**Issue by ThunderVamp9** [PokemonGoF/PokemonGo-Bot#1407]
### Expected Behavior
The bot should proceed to the nearest unvisited pokestop, keeping a sense of following a legitimate path as a human would go from one to the next and so on.

### Actual Behavior
Bot seems to jump back and forth randomly across town, skipping stops in between to get to a stop 3 blocks away, then heading off in another random direction, skipping even more stops.

### Steps to Reproduce
Start bot and Simple Map and watch progress.

### Other Information
OS: Ubuntu Linux 14.04 LTS
Git Commit: 32cefeed4760d6b52db3eb76d783d0f13d068e83

**Comment by arnogues** [comment]
It's the goal of the boat to walk around all pokestop from the start location.
Increase the value of max_steps if you want more distance

**Comment by ThunderVamp9** [comment]
But this doesn't have anything to do with more distance or walking around them all from start to finish.

It's about starting from point A, and the bot skipping point B, C and D to get to point E which is much farther away, then going to point Z, skipping everything in between, then going back to point C, again skipping everything, etc. Eventually it does get all of the stops, but it isn't efficient OR in a manner a human would do it.

It walks in random directions, skipping multiple stops along the way. A human would start at point A, look for the next closest one (B) and go to it, then look for the NEXT closest one (C) and go there, along a path from one to the next. They wouldn't jump around skipping stops.
