### ISSUE TITLE
1 main config, n login configs

### ISSUE THREAD

**Issue by prometheus247** [PokemonGoF/PokemonGo-Bot#1409]
Is there a way to refer in one config to another?

Lets say we change this part in different configs:

```
    "auth_service": "google",
    "username": "YOUR_USERNAME",
    "password": "YOUR_PASSWORD",
    "location": "SOME_LOCATION",
    "gmapkey": "GOOGLE_MAPS_API_KEY",
```

But keep this config in only one file:

```
 "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": false,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": {
      "1": { "keep" : 100 },
      "101": { "keep" : 10 },
      "102": { "keep" : 30 },
      "103": { "keep" : 30 },
      "201": { "keep" : 30 },
      "701": { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "evolve_speed": 20,
    "use_lucky_egg": false,
    "evolve_captured": false,
```
[...]

My bot is running in 6 instances right now and I would like to add more to it.
But without an intelligent config organisation I am struggling.

Ideas?

dev branch, 8f0bace

**Comment by arnogues** [comment]
The bot is not maid to cheat like dumb

**Comment by elfenars** [comment]
struggling, really?
I'm running 10 and it's as simple as copy-pasting from the 5th line onwards. 

I wouldn't consider this an issue.

**Comment by prometheus247** [comment]
I agree, @elfenars that it isnt an issue. Let it mark it as question via changing the subject.

Now that we have this sorted out, lets get back to the solution.
I have no clue of the syntax of python config files, but if one is not willing to share it, i will find out myself.

**Comment by dosin** [comment]
I have an idea but I don't have an extra account to test if it works
Environment is **Ubuntu** OS and **master** branch
Let's say you have 10 google accounts
you create **config1.json** to **config10.json**
```
vi runalot.sh
```
In **runalot.sh**, you have
```
cd PokemonGo-Bot && virtualenv . && source bin/activate
python pokecli.py -cf config1.json
...
python pokecli.py -cf configN.json
```
then
```
chmod +x runalot.sh
```
finally
```
./runalot.sh
```
I don't know if this would work

**Comment by prometheus247** [comment]
Thanks for your contribution to this idea of mine, @dosin 

I have laid my hands on a multi config maintainer already, a kind of what you described. 
I just created a git rep to start sharing it: https://github.com/prometheus247/mbm

My point is, that I want to have kind of 2 configs merging into one. 
While 1 config is static (basic stuff like the pokemon you wanto release, etc), and alot more configs are differing from each other (logins of the different bots).

I dont think its hard to get this straight. I will try some things myself just now.

**Comment by cronyp** [comment]
I like what you are doing with your development @prometheus247 
I also am interested in an easier way to manage multiple accounts
I have to thank @dosin as i did a spin off his idea here: [https://github.com/cronyp/botbash](https://github.com/cronyp/botbash)
