### ISSUE TITLE
Pokestops sorting

### ISSUE THREAD

**Issue by ChronoAS** [PokemonGoF/PokemonGo-Bot#141]
They're being sorted from the furthest distance to the closest, so bot will visit furthest pokestops at first.

**Comment by tstumm** [comment]
Actually you need to resort every time you visit a pokestop. You are describing a greedy approach, something like travelling salesman should be a better way (and way more complex).

**Comment by jtdroste** [comment]
They're currently being sorted based on what the API returns.  We'll be figuring out better sorting (it's on the todo list)
