### ISSUE TITLE
Bot stucks at initial location

### ISSUE THREAD

**Issue by longlhgithub** [PokemonGoF/PokemonGo-Bot#1410]
### Expected Behavior

Bot must go to further spots to catch pokemons & spin ports.

### Actual Behavior
Just happens right after starting bot...

the second walk just move from initial location to itself. 

[14:03:31] Starting PokemonGo Bot....
[14:03:33] Scanning area for objects....
[14:03:33] Walking from (22.28224, 114.1477566) to [22.28224, 114.1477566] 0.00km
[14:03:35] Scanning area for objects....
[14:03:35] Walking from (22.28224, 114.1477566) to [22.28404, 114.1477566] 0.20km

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by friederschueler** [comment]
try to increase max_steps value to something higher than the default 5?
like
"max_steps": 12

**Comment by friederschueler** [comment]
You did install protobuf?

apt-get install python-protobuf (python2-protobuf?)

**Comment by longlhgithub** [comment]
I did not install protobuf yet. You think I need to install it?. the bot has just worked fine for hours. just got this after restarting it

**Comment by friederschueler** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation

Linux: apt-get install python-protobuf

So I assume you have to install it, maybe it wasn't needed before

**Comment by Witzbold** [comment]
I have still the same problem and I already installed python-protobuf...

**Comment by mrseeker** [comment]
Do you have the flag "test" in your configuration set to true?

**Comment by Calcyfer** [comment]
The walking logic has been changed a lot and there are still PRs open to fix certain things. Wait a bit and make sure you have max_steps higher than 1.
