### ISSUE TITLE
[DEV] Bot does go to pokestops

### ISSUE THREAD

**Issue by gaz492** [PokemonGoF/PokemonGo-Bot#1412]
### Expected Behavior
Bot 'walks' to nearby pokestops

### Actual Behavior
Bot seems to walk around in a rectangle according to the webmap

[Image](http://ss.wolf.ski/firefox_2016-07-28_15-25-38.png)

### Steps to Reproduce
Just run the bot

### Other Information
OS: Ubuntu 16.04 LTS
Git Commit: e568e352da98d4ba983fb9e1d50d66a9efbdaf17

**Comment by mrseeker** [comment]
Well, the question is: Where are the pokestops located, and are they all in a 5 minute distance from each other? If so, then the bot will walk back to the nearest pokestop which he can swipe (and therefore cause a loop).
