### ISSUE TITLE
Bool has no attribute 'get item'

### ISSUE THREAD

**Issue by Messingaroung2323** [PokemonGoF/PokemonGo-Bot#1413]
### Expected Behavior
Bot commences working.

### Actual Behavior
![image](https://cloud.githubusercontent.com/assets/20694819/17215893/5a9abf26-5493-11e6-80f4-0b5e4c31fc03.png)
It was working perfectly last night, but is now reading this.

### Steps to Reproduce
Entering the ./pokecli.py command.

### Other Information
OS: Mac
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
0ce208e8f7976ea0bfcdf6f34978d9411a5e7138

I tried adding a restart shell file to the folder to keep the game from crashing every hour but could not get it to work so I deleted it and now the bot wont run.

**Comment by sangwon04** [comment]
Literally just opened an issue for this exact same issue.
