### ISSUE TITLE
Source is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by RaziHaj** [PokemonGoF/PokemonGo-Bot#1415]
Hi guys, I feel exhausted. this was one difficult installation to do.
I made sure to follow the instructions, researched as much as I could to avoid stupid questions (as this is the first time I'm working with Python). 
I have successfully did all the steps up until <source bin/activate>. ($ sign is not working with windows 10 apparently). I chose the master version.
after printing the line I got that message, and I have no idea what I'm doing wrong.

OS: 
Windows 10 x64 bit.

**Comment by bimahp** [comment]
you can just skip that 'source bin/activate' step on windows and proceed with the next one
work many times for me

**Comment by RaziHaj** [comment]
Yeah, that's what I did, but I encountered some problems going forward, so I figured it might be the source of it.

**Comment by Afzalbinaziz** [comment]
hey razi,im facing the same problem,did you find a solution?

**Comment by Jcolomar** [comment]
try manual installation

**Comment by karansamra** [comment]
On Windows use Git Bash

**Comment by vinayaposa** [comment]
on windows use 'venv\scripts\activate'

**Comment by tayustayus** [comment]
@vinayaposa Thank you so much

**Comment by john2912** [comment]
virtualenv env
ls -la env
#For Unix/Linux
source env/bin/activate
#For Windows
env\scripts\activate

**Comment by basavdotio** [comment]
> on windows use 'venv\scripts\activate'

This worked on my windows.  since I was already in my_env folder, I just typed scripts\activate.

Thank you.

**Comment by grimmie38** [comment]
```
PS E:\Django\myproject> 'venv\scripts\activate'
venv\scripts\activate
```

It worked

**Comment by karthikkunala** [comment]
Thanks for the help :)

**Comment by tootiefrutie9999** [comment]
Can anyone help me??
I used 'venv/Scripts/activate' in windows 7 but still cannot activate my virtualenv. 
I already have python 3.8 installed, when I tried to activate my venv it said "venv" is not recognized as internal or external command, or operable batch file.I also tried 'venv/Scripts/activate.bat' but NO LUCK...

**Comment by tootiefrutie9999** [comment]
I already successfully installed virtualenv package and venv packages and libraries. What do you think I should do???!

**Comment by tootiefrutie9999** [comment]
My venv name is "django"

**Comment by tootiefrutie9999** [comment]
My venv is actually a folder so I tried to activate the folder.

**Comment by tootiefrutie9999** [comment]
Consisting of my venv libraries and packages

**Comment by shrikantpardhi** [comment]
navigate to env/Scripts/ 
`cd env/Scripts`
then run the command 
`activate`

![image](https://user-images.githubusercontent.com/26996069/93178949-a2448580-f752-11ea-8f96-c3d2fc8506b7.png)

It will activate your virtual environment

then go back  to the project directory using
```
cd..
cd..
```
![image](https://user-images.githubusercontent.com/26996069/93178829-6a3d4280-f752-11ea-8ded-1e0d559e61b8.png)

to deactivate the virtual environment again navigate to 
`cd env/Scripts` and run
`deactivate`

![image](https://user-images.githubusercontent.com/26996069/93178899-89d46b00-f752-11ea-9410-42fcae32b6b1.png)

**Comment by largalaga** [comment]
> navigate to env/Scripts/
> `cd env/Scripts`
> then run the command
> `activate`
> 
> ![image](https://user-images.githubusercontent.com/26996069/93178949-a2448580-f752-11ea-8f96-c3d2fc8506b7.png)
> 
> It will activate your virtual environment
> 
> then go back to the project directory using
> 
> ```
> cd..
> cd..
> ```
> 
> ![image](https://user-images.githubusercontent.com/26996069/93178829-6a3d4280-f752-11ea-8ded-1e0d559e61b8.png)
> 
> to deactivate the virtual environment again navigate to
> `cd env/Scripts` and run
> `deactivate`
> 
> ![image](https://user-images.githubusercontent.com/26996069/93178899-89d46b00-f752-11ea-9410-42fcae32b6b1.png)

this is the only solution that worked for me for Windows 10.  Thanks a lot.

**Comment by Khosiyat** [comment]
largalaga , thanks for the solution

**Comment by sowrovsec** [comment]
> On Windows use Git Bash

On Gitbash It is working fine

**Comment by NKVDL** [comment]
I created a .venv folder in my C:\path. Windows 10. 

The above suggestions didn't work out, so in CP:

_Navigate to `C:\path`_

`cd .venv`
`cd scripts`
`activate`

**Output in CP**
`(.venv) C:\Users\Administrator\Desktop\Code\Practice\.venv\Scripts>`

`cd..`
`cd..`

**Output in CP**
`(.venv) C:\Users\Administrator\Desktop\\Code\Practice>`

**Comment by mercymtae** [comment]
> on windows use 'venv\scripts\activate'

**Comment by Akbarjon03** [comment]
> 

hi i use this command but i take this "The system cannot find the path specified."

**Comment by vrammohan** [comment]
Yes on Windows, "source env/bin/activate" doesn't work, we need to change the directory and **manually run the "activate.bat" file**  (as per my experience).

**Comment by Notetaker234** [comment]
cd env/Scripts 
then 
./activate 

this worked for me on windows. Hope it helps someone.
