### ISSUE TITLE
[dev] Error while install requirements on OpenShift

### ISSUE THREAD

**Issue by pararang** [PokemonGoF/PokemonGo-Bot#1416]
### Actual Behavior
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi (from -r requirements.txt (line 1))
  Updating ./src/pgoapi clone (to 81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b)
  Could not find a tag or branch '81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b', assuming commit.
  Running setup.py egg_info for package pgoapi
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/var/lib/openshift/579a11ed2d527124a600013d/app-deployments/2016-07-28_10-10-25.478/repo/src/pgoapi/setup.py", line 9, in <module>
        install_reqs = parse_requirements(path_req, session=False)
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/var/lib/openshift/579a11ed2d527124a600013d/app-deployments/2016-07-28_10-10-25.478/repo/src/pgoapi/setup.py", line 9, in <module>

    install_reqs = parse_requirements(path_req, session=False)

TypeError: parse_requirements() got an unexpected keyword argument 'session'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /var/lib/openshift/579a11ed2d527124a600013d/app-deployments/2016-07-28_10-10-25.478/repo/src/pgoapi

### Steps to Reproduce
`pip install -r requirements.txt`

### Other Information
OS: OpenShift

**Comment by kriwil** [comment]
`pip --version`?

probably old pip version, try `pip install --upgrade pip` first.

**Comment by pararang** [comment]
@kriwil yes, its works sir..... terima kasih.
upgraded `pip` 7 to 8
