### ISSUE TITLE
error: argument -a/--auth_service is required

### ISSUE THREAD

**Issue by PraeceptorXS** [PokemonGoF/PokemonGo-Bot#1422]
### Expected Behavior
Bot to launch after entering python pokecli.py in terminal

### Actual Behavior
Terminal returns error message 
(PokemonGo-Bot) Bens-MBP-2:PokemonGo-Bot BenSun$  python pokecli.py -cf configs/config.json
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-p PASSWORD] [-l LOCATION] [-lc LOCATION_CACHE] [-m MODE]
                  [-w WALK] [-k GMAPKEY] [-ms MAX_STEPS]
                  [-it INITIAL_TRANSFER] [-d DEBUG] [-t TEST]
                  [-du DISTANCE_UNIT] [-if ITEM_FILTER] [-ev EVOLVE_ALL]
                  [-ec EVOLVE_CAPTURED]
pokecli.py: error: argument -a/--auth_service is required

### Steps to Reproduce
<img width="1680" alt="screen shot 2016-07-28 at 10 17 45 am" src="https://cloud.githubusercontent.com/assets/20705111/17218206/9d3306f4-54ac-11e6-98d9-757862925633.png">

### Other Information
OS: OSX Sierra Beta

**Comment by Vvkmnn** [comment]
Does your `config.json` have the `"auth_service"` value filled in?

**Comment by PraeceptorXS** [comment]
Yeah. Here is a pic of it
<img width="1680" alt="screen shot 2016-07-28 at 10 28 25 am" src="https://cloud.githubusercontent.com/assets/20705111/17218678/3fe14d74-54ae-11e6-9572-a9187ed9197b.png">

**Comment by Vvkmnn** [comment]
Hmm.

Sorry, but I can't tell from the screencap; is there a comma after `auth_service"` (and every other JSON entry)?

Like the following:
```
    "auth_service": "google",
    "username": "someemail@gmail.com",
    "password": "somepassword",
    "location": "43.639557, -79.375932",
    "gmapkey": "somekey",
```

**Comment by sangwon04** [comment]
You're missing the comma lol.

**Comment by PraeceptorXS** [comment]
I went back and added it and it still returned the error.

**Comment by Vvkmnn** [comment]
What happens with

`python pokecli.py -cf configs/config.json -a "google"`

**Comment by sangwon04** [comment]
@PraeceptorXS I'd make sure your config.json is properly saved then start a new shell and try running the script. Running the script explicitly with the '-a' param should also be interesting to see how it returns.

**Comment by PraeceptorXS** [comment]
(PokemonGo-Bot) Bens-MBP-2:PokemonGo-Bot BenSun$ python pokecli.py -cf configs/config.json -a "google"
usage: pokecli.py [-h] [-cf CONFIG]
pokecli.py: error: unrecognized arguments: -a google

**Comment by PraeceptorXS** [comment]
Ok.

**Comment by sangwon04** [comment]
No, leave out the 'cf configs/config.json' if you're going to explicitly authenticate from the shell.

**Comment by sangwon04** [comment]
You're also pulling from the dev branch, which includes the latest version but can be unstable (IIRC). Have you tried pulling from the master branch to see if you saw this same issue?

**Comment by PraeceptorXS** [comment]
Yeah. I've used both branches and it always returns the same error.

**Comment by sangwon04** [comment]
Authenticating is very straightforward. Try running 'python pokecli.py -a google -u -p

**Comment by PraeceptorXS** [comment]
It says unrecognized argument. I put my username and password after the -u and -p

**Comment by kscheung1228** [comment]
I have the same issues when using docker

**Comment by RaziHaj** [comment]
Same here

**Comment by PraeceptorXS** [comment]
Well, I tried running the bot on a different computer. Now I'm getting this error.
PokemonGo-Bot) Graces-iMac-216:PokemonGo-Bot GraceXu$ python pokecli.py
[11:19:51] PokemonGO Bot v1.0
[11:19:51] No config argument specified, checking for /configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 294, in <module>
    main()
  File "pokecli.py", line 244, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by PraeceptorXS** [comment]
Ok I think I figured it out. First, make sure the config.json in your PokemonGo-Bot is named correctly and formatted correctly. Autocorrect messed up some quotes and that was what was messing stuff up. Also, make sure that the config.json is a valid json.

**Comment by sangwon04** [comment]
Glad to caught it. Seems like the issue was very trivial.
