### ISSUE TITLE
Pokefast 2.0. Googlerefreshtoken question 

### ISSUE THREAD

**Issue by Mrbeyond13** [PokemonGoF/PokemonGo-Bot#1424]
Hi guys, can someone tell me, where is googlerefreshtoken situated in Pokefast 2.0? i have my old token, but i don't know where i have to past it. with which name,and in which format i have to past it?

**Comment by vicch** [comment]
I don't think this is the right place for Pokefast questions.

**Comment by Mrbeyond13** [comment]
Sorry, but i didn't know where i can give that question , i just need to know where is it situated and in which file format
