### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by hsizadam** [PokemonGoF/PokemonGo-Bot#1425]
Guys sorry about my ignorance but i am new at this things.
i did this all steps (using windows 10)

$ git clone -b master https://github.com/PokemonGoF/PokemonGo-Bot  
$ cd PokemonGo-Bot 
$ virtualenv .  
$ source bin/activate
$ pip install -r requirements.txt
$ git submodule init
$ git submodule update

and what should i do now? i think i should change configs and then what? need some help.

**Comment by 3DDario** [comment]
./pokecli.py

**Comment by dosin** [comment]
Then you should read this https://github.com/PokemonGoF/PokemonGo-Bot#usage-up-to-date
Then just run **pokecli.py**

**Comment by Kassius509** [comment]
Added start instructions to the FAQ's
