### ISSUE TITLE
push request issue

### ISSUE THREAD

**Issue by Wheaties466** [PokemonGoF/PokemonGo-Bot#1428]
### Expected Behavior
for it to push the changes to the dev branch

### Actual Behavior
git push origin dev
remote: Permission to PokemonGoF/PokemonGo-Bot.git denied to Wheaties466.
fatal: unable to access 'https://github.com/PokemonGoF/PokemonGo-Bot.git/': The requested URL returned error: 403

### Steps to Reproduce
git push origin dev

(confirmed that the username and password are correct.)

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by elfenars** [comment]
Man, this is not even an issue for the project.
Read: https://help.github.com/articles/fork-a-repo/

**Comment by Wheaties466** [comment]
I apologize

**Comment by xorinzor** [comment]
You need to fork the project, commit the changes to the forked repository then create a pull-request.

Also, you can close the issue yourself.
