### ISSUE TITLE
Runtime error on Line 118 Cell Worker "seen_fort_wroker.py"

### ISSUE THREAD

**Issue by inet-pwnZ** [PokemonGoF/PokemonGo-Bot#1430]
### Expected Behavior
Working Properly

### Actual Behavior
![Image of Issue](http://image.prntscr.com/image/f896f6ef0edc466a9a186d029df21112.png)
Account is not softbanned

### Steps to Reproduce
Let the bot run for a couple of min like 20min

edit : since the account isn't softbanned its probably caused by not finding any itmes

### Other Information
OS: Win7
Git Commit: e25a7091f5f26eef17bc38f6f90df26ad199ffbc

**Comment by xorinzor** [comment]
Please do a `git pull` to update to the latest version and report if the issue still happens

**Comment by inet-pwnZ** [comment]
Google Servers had some login issues
i got some stable bots running now i report back when i got an issue

**Comment by inet-pwnZ** [comment]
Ok it happend again
![issue](http://image.prntscr.com/image/d5c5c58dc1944c1eac4eae27fd1d8c37.png)

**Comment by inet-pwnZ** [comment]
Problem is resolved
