### ISSUE TITLE
Fail on launch (Servers to busy?); 'bool' object has no attribute '__getitem__' 

### ISSUE THREAD

**Issue by RolfKoenders** [PokemonGoF/PokemonGo-Bot#1432]
### Expected Behavior
Start being a bot.

### Actual Behavior
Crashing

### Steps to Reproduce
Just launch the bot.

### Other Information
OS: Linux, Ubuntu
Git Commit: c7ab5b03cb93b5393bebbc383545a50e8519e57a

#### Stacktrace
```
ubuntu@hostname:~/PokemonGo-Bot$ python pokecli.py
[2016-07-28 16:06:25] [x] PokemonGO Bot v1.0
[2016-07-28 16:06:25] [x] Configuration initialized
[2016-07-28 16:06:25] [x] Coordinates found in passed in location, not geocoding.
[2016-07-28 16:06:25]
[2016-07-28 16:06:25] [x] Address found: 52.257067, 5.224954
[2016-07-28 16:06:25] [x] Position in-game set as: (52.257067, 5.224954, 0.0)
[2016-07-28 16:06:25]
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/home/ubuntu/PokemonGo-Bot/pokemongo_bot/__init__.py", line 151, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
TypeError: 'bool' object has no attribute '__getitem__'
```

**Comment by Roydeking52** [comment]
It's a server problem. Servers off Pokemon Go are unstable at the moment. Im waiting as well.

**Comment by kscheung1228** [comment]
same here

**Comment by RolfKoenders** [comment]
@Roydeking52 Ah oke. Would be nice if we can make some sort of checking. If its a timeout to go check at a service which checks if its down or not? So we can provide a better error message?

**Comment by Roydeking52** [comment]
yes that would be great.

**Comment by sangwon04** [comment]
Dealt with this earlier this morning. Make sure you don't have any rogue/zombie shell sessions that might have any remnants of the script running. I had to kill all shell sessions and restarting the bot got me up and running again.

**Comment by Roydeking52** [comment]
I know but the server are unstable a lot of ppl are reporting that, im using CentOS

**Comment by RolfKoenders** [comment]
A few moment ago i got this message: 
`[2016-07-28 16:40:25] Login Error, server busy`

**Comment by Roydeking52** [comment]
try again.

**Comment by sangwon04** [comment]
@Roydeking52 then build a quick bash script to run the script, timeout for x minutes, then run the script again. Then you don't have to ever worry about running the script manually each time it fails due to server related issues.

**Comment by dneern** [comment]
@sangwon04 That's a really good idea. Unfortunately for me, I have 0 experience with coding bash scripts. Could you maybe help me to figure out what I have to do to get something like that working, or at least point me in the right direction?

**Comment by RolfKoenders** [comment]
It will start again from where it initially started. Isn't it strange it will immediately jump back to that position? Would be cool to save last position walked to or last in game position and start again from there. That will also help preventing detection?

**Comment by dneern** [comment]
@RolfKoenders it says here: https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files that when the location_cache is set to true "Bot will start at last known location if you do not have location set in the config"
