### ISSUE TITLE
Perfect thrown raise 110 xp only

### ISSUE THREAD

**Issue by Anakin5** [PokemonGoF/PokemonGo-Bot#1436]
### Expected Behavior
It seems that we intend to get a perfect throw and the 210 xp that goes with it. It was the case few commits ago.

### Actual Behavior
It is only 110 now, most of the time. But I noticed some rare 210 xp.

### Steps to Reproduce
Just catch pokemon and print following line when catch succeed:
`logger.log("{}".format(response_dict['responses']['CATCH_POKEMON']['capture_award']))`

### Other Information
OS: Windows
Git Commit: 8f0bacebcd172727f7e6ccd8e8861d4d47c7937c

**Comment by DayBr3ak** [comment]
Can confirm 
OS: Windows
Commit: 522e35f541a82fcb0542f0be35aaf6dda28a7008
