### ISSUE TITLE
Egg incubator not starting

### ISSUE THREAD

**Issue by Marco208** [PokemonGoF/PokemonGo-Bot#1437]
### Expected Behavior
Egg incubation to start

### Actual Behavior
No eggs start to incubate

### Steps to Reproduce
Have an egg in your bag, start the bot

### Other Information
OS: CentOS 6
Git Commit: 522e35f541a82fcb0542f0be35aaf6dda28a7008

**Comment by xorinzor** [comment]
If you would have read the TODO list you'd know that nothing regarding eggs has been implemented yet.

You can close this issue.

**Comment by aTadTasty** [comment]
@xorinzor i thought this was added in the latest of the dev. but it has an error  `    incubators.append({"id":incubator.get("id", -1), "used":False})
AttributeError: 'str' object has no attribute 'get'`

**Comment by Marco208** [comment]
@xorinzor #1404 If you would check the commits that are pushed.

**Comment by xorinzor** [comment]
My bad.

**Comment by reddivision** [comment]
hey guys, feel free to pull and test #1526
