### ISSUE TITLE
Stuck in an impossible location

### ISSUE THREAD

**Issue by ArkBriar** [PokemonGoF/PokemonGo-Bot#1438]
### Expected Behavior

Walking around.

### Actual Behavior

[12:47:37] Scanning area for objects....
[12:47:37] Walking from (4.886674138783273e+18, 4.886674138783273e+18) to [4.886674138783273e+18, 4.886674138783273e+18] 0.00km

Logging this over and over.

### Steps to Reproduce

I don't know... I remove the last location file and everything's ok the 2nd time I ran the program. Seems it calculated the incredible location and didn't know how to get out.

### Other Information
OS: Ubuntu 14.04
Git Commit: 522e35f541a82fcb0542f0be35aaf6dda28a7008

**Comment by buettner123** [comment]
have you tried these steps: https://github.com/PokemonGoF/PokemonGo-Bot/issues/1349#issuecomment-235818135 ?

**Comment by ArkBriar** [comment]
@buettner123 yes, I have to update the python requirements to run the script on dev branch. Now the bot has worked for about 10 minutes and nothing strange happend. I will update the issue when I run into the same problem next time. Maybe I can try to find this out.

**Comment by johntyyk3** [comment]
Just did the update, perfectly working now :)  Thanks
