### ISSUE TITLE
[Question] It is possible a permanent ban?

### ISSUE THREAD

**Issue by H4xXx0r** [PokemonGoF/PokemonGo-Bot#1440]
I ran dev branch many hours until server turns down. Now (after 6 hours) I try to login from the smartphone and when i push login button it returns to the main screen (to register a new account). Tried many times, and it do the same: nothing. No warning messages, no error messages, only returns to the main screen. Tried with a google account and it works ok, just with PTC. It is possible a permanent ban or another limitation from the game?

**Comment by leadboots5** [comment]
Login is likely just down.
http://ispokemongodownornot.com/

**Comment by xorinzor** [comment]
Please don't create these issues here, this has nothing to do with the workings of the bot.

**Comment by wsmigielski** [comment]
So far they have only issued soft bans from what I know. Next time google it, you'll find everything you need to know.
