### ISSUE TITLE
Crash After successful login, caused by egg incubator. 

### ISSUE THREAD

**Issue by phant0mg33k** [PokemonGoF/PokemonGo-Bot#1444]
### Expected Behavior
To be able to run the bot

### Actual Behavior
Hard crash every time the  bot, has a good login, it begins the inventory search and crashes with eggs. 

### Steps to Reproduce
_restarting the bot with configuration, even with directly editing the example, will result in the same issue.

### Other Information
OS: Mac OS Sierria
Git Commit: (8852f62)

[11:57:45] Starting PokemonGo Bot....
Traceback (most recent call last):
  File "pokecli.py", line 294, in <module>
    main()
  File "pokecli.py", line 260, in main
    bot.tick()
  File "/Users/G33K/PokemonGo-Bot/pokemongo_bot/__init__.py", line 63, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/Users/G33K/PokemonGo-Bot/pokemongo_bot/cell_workers/incubate_eggs_worker.py", line 34, in work
    incubators.append({"id":incubator.get("id", -1), "used":False})
AttributeError: 'str' object has no attribute 'get'

**Comment by hklcf** [comment]
server problem

**Comment by phant0mg33k** [comment]
Ah

**Comment by aTadTasty** [comment]
after the server is stablized, i'd recommend you do a new requirements installation through `sudo pip install -r requirements.txt`maybe that will update the new variables and make it work

**Comment by phant0mg33k** [comment]
Yup that did it thank you
