### ISSUE TITLE
location json never gets created

### ISSUE THREAD

**Issue by IanCass** [PokemonGoF/PokemonGo-Bot#1445]
### Expected Behavior
Map should update with current location

### Actual Behavior
Map does not update with current location 

### Steps to Reproduce
Do fresh install. Follow instructions.

### Other Information
The cause is this this line in stepper.py

if os.path.isfile(user_web_location):

The user location file in the web directory never gets created. If you create an empty file byhand, then everything springs into life.

**Comment by sangwon04** [comment]
This is a known issue. Simple workaround is to manually touch the file as you stated.

**Comment by shangguokan** [comment]
Thanks, I'm exactly searching for this answer :+1:

**Comment by retraut** [comment]
What dir need to create?

**Comment by retraut** [comment]
Need to create 
'web/location-%s.json'
'data/last-location-%s.json'

Where %s - username of trainer

**Comment by Gregwar** [comment]
Indeed, it seems that here:
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/stepper.py#L110

The file is only opened if it already exists (isfile test)
