### ISSUE TITLE
How to visualize cells for max_steps?

### ISSUE THREAD

**Issue by sangwon04** [PokemonGoF/PokemonGo-Bot#1446]
Sorry for posting this in issue but I cannot find any information on this. 

max_steps is defined to determine how many cells around your initial location you walk. Is there any way to visualize this in an actual map? I've been testing different values to see if I can 'eye' out how far/close I walk from my starting point but that is proving to be more difficult. 

Any info on cells would also be appreciated. Thank you all.

**Comment by sgitkene** [comment]
https://github.com/AHAAAAAAA/PokemonGo-Map

the circles shown on the map when turning "scanned locations" on and having configured the same step number.

roughly a circle of radius 150m * number of steps if I am not mistaken.

hope I helped
