### ISSUE TITLE
[Master] Initial transfer is releasing duplicated pokemon, ignoring config

### ISSUE THREAD

**Issue by bimahp** [PokemonGoF/PokemonGo-Bot#1448]
### Expected Behavior
Even when pokemon bag is full, bot won't release any pokemon if not configured to do so

### Actual Behavior
Initial transfer is triggered and most duplicated pokemon got transfered and only keep the ones with highest CP

> [2016-07-27 03:39:49] [x] Captured Staryu! [CP 512] [IV 0.82]
[2016-07-27 03:39:50] [x] Captured Staryu! [CP 512]
[2016-07-27 03:40:04] [#] Something rustles nearby!
[2016-07-27 03:40:05] [x] Pokemon Bag is full!
[2016-07-27 03:40:05] [x] Initial Transfer.
[2016-07-27 03:40:05] [x] Preparing to transfer all duplicate Pokemon, keeping the highest CP of each type.
[2016-07-27 03:40:05] [x] Will NOT transfer anything above CP 0
[x] Transferring Magikarp with CP 143
[x] Transferring Magikarp with CP 121
[x] Transferring Magikarp with CP 119
[x] Transferring Magikarp with CP 105
[x] Transferring Magikarp with CP 92
[x] Transferring Magikarp with CP 86
[x] Transferring Magikarp with CP 81
[x] Transferring Magikarp with CP 64
[x] Transferring Metapod with CP 207
[x] Transferring Metapod with CP 205
[x] Transferring Metapod with CP 191
[x] Transferring Metapod with CP 169
[x] Transferring Metapod with CP 168
[x] Transferring Metapod with CP 120
[x] Transferring Metapod with CP 110
[x] Transferring Metapod with CP 79
[x] Transferring Weedle with CP 99
[x] Transferring Weedle with CP 97
[x] Transferring Weedle with CP 95
[x] Transferring Weedle with CP 88
[x] Transferring Weedle with CP 68
[x] Transferring Kakuna with CP 177
[x] Transferring Kakuna with CP 168
[x] Transferring Kakuna with CP 154
[x] Transferring Kakuna with CP 146
[x] Transferring Kakuna with CP 119
[x] Transferring Kakuna with CP 116
[x] Transferring Pidgey with CP 128
[x] Transferring Pidgey with CP 90
[x] Transferring Pidgey with CP 89
[x] Transferring Pidgeotto with CP 570
[x] Transferring Pidgeotto with CP 534
[x] Transferring Pidgeotto with CP 491
[x] Transferring Pidgeotto with CP 476
[x] Transferring Pidgeotto with CP 336
[x] Transferring Pidgeotto with CP 269
[x] Transferring Pidgeotto with CP 268
[x] Transferring Pidgeotto with CP 267
[x] Transferring Pidgeotto with CP 262
[x] Transferring Pidgeotto with CP 238
[x] Transferring Dratini with CP 13
[x] Transferring Raticate with CP 683
[x] Transferring Raticate with CP 682
[x] Transferring Raticate with CP 672
[x] Transferring Raticate with CP 648
[x] Transferring Fearow with CP 761
[x] Transferring Sandshrew with CP 354
[x] Transferring Nidoran M with CP 298
[x] Transferring Clefairy with CP 432
[x] Transferring Vulpix with CP 131
[x] Transferring Zubat with CP 305
[x] Transferring Zubat with CP 292
[x] Transferring Zubat with CP 234
[x] Transferring Zubat with CP 224
[x] Transferring Zubat with CP 215
[x] Transferring Zubat with CP 211
[x] Transferring Zubat with CP 210
[x] Transferring Zubat with CP 194
[x] Transferring Zubat with CP 187
[x] Transferring Zubat with CP 160
[x] Transferring Zubat with CP 145
[x] Transferring Zubat with CP 128
[x] Transferring Zubat with CP 88
[x] Transferring Golbat with CP 729
[x] Transferring Oddish with CP 482
[x] Transferring Oddish with CP 464
[x] Transferring Venonat with CP 498
[x] Transferring Venonat with CP 472
[x] Transferring Venonat with CP 367
[x] Transferring Venonat with CP 190
[x] Transferring Meowth with CP 290
[x] Transferring Psyduck with CP 548
[x] Transferring Growlithe with CP 521
[x] Transferring Growlithe with CP 292
[x] Transferring Poliwag with CP 300
[x] Transferring Poliwag with CP 299
[x] Transferring Poliwag with CP 297
[x] Transferring Poliwag with CP 124
[x] Transferring Bellsprout with CP 417
[x] Transferring Bellsprout with CP 408
[x] Transferring Bellsprout with CP 204
[x] Transferring Tentacruel with CP 990
[x] Transferring Geodude with CP 338
[x] Transferring Geodude with CP 183
[x] Transferring Geodude with CP 158
[x] Transferring Ponyta with CP 416
[x] Transferring Ponyta with CP 238
[x] Transferring Slowpoke with CP 631
[x] Transferring Slowpoke with CP 629
[x] Transferring Slowpoke with CP 467
[x] Transferring Slowpoke with CP 331
[x] Transferring Magnemite with CP 443
[x] Transferring Magnemite with CP 361
[x] Transferring Magnemite with CP 349
[x] Transferring Magnemite with CP 324
[x] Transferring Magnemite with CP 321
[x] Transferring Magnemite with CP 113
[x] Transferring Doduo with CP 412
[x] Transferring Doduo with CP 390
[x] Transferring Doduo with CP 380
[x] Transferring Doduo with CP 338
[x] Transferring Doduo with CP 302
[x] Transferring Doduo with CP 300
[x] Transferring Seel with CP 403
[x] Transferring Shellder with CP 127
[x] Transferring Gastly with CP 357
[x] Transferring Drowzee with CP 563
[x] Transferring Krabby with CP 368
[x] Transferring Krabby with CP 359
[x] Transferring Krabby with CP 126
[x] Transferring Krabby with CP 115
[x] Transferring Voltorb with CP 435
[x] Transferring Voltorb with CP 381
[x] Transferring Voltorb with CP 342
[x] Transferring Voltorb with CP 326
[x] Transferring Voltorb with CP 182
[x] Transferring Voltorb with CP 156
[x] Transferring Voltorb with CP 35
[x] Transferring Exeggcute with CP 174
[x] Transferring Cubone with CP 42
[x] Transferring Rhyhorn with CP 539
[x] Transferring Rhyhorn with CP 530
[x] Transferring Rhyhorn with CP 527
[x] Transferring Rhyhorn with CP 524
[x] Transferring Rhyhorn with CP 451
[x] Transferring Kabuto with CP 480
[x] Transferring Horsea with CP 358
[x] Transferring Horsea with CP 353
[x] Transferring Horsea with CP 352
[x] Transferring Horsea with CP 330
[x] Transferring Goldeen with CP 439
[x] Transferring Goldeen with CP 419
[x] Transferring Goldeen with CP 410
[x] Transferring Goldeen with CP 407
[x] Transferring Goldeen with CP 404
[x] Transferring Goldeen with CP 400
[x] Transferring Goldeen with CP 398
[x] Transferring Goldeen with CP 367
[x] Transferring Goldeen with CP 351
[x] Transferring Goldeen with CP 340
[x] Transferring Goldeen with CP 319
[x] Transferring Goldeen with CP 311
[x] Transferring Seaking with CP 972
[x] Transferring Staryu with CP 512
[x] Transferring Staryu with CP 442
[x] Transferring Staryu with CP 426
[x] Transferring Staryu with CP 392
[x] Transferring Staryu with CP 384
[x] Transferring Staryu with CP 376
[x] Transferring Staryu with CP 348
[x] Transferring Staryu with CP 329
[x] Transferring Staryu with CP 148
[x] Transferring Staryu with CP 40
[x] Transferring Caterpie with CP 173
[x] Transferring Caterpie with CP 62
[x] Transferring Pinsir with CP 1027
[x] Transferring Pinsir with CP 967
[x] Transferring Pinsir with CP 94
[2016-07-27 03:46:54] [x] Transferring Done.

### Steps to Reproduce
On master branch, set `"initial_transfer": 0` and fill your pokemon bag
I lost my 1.00 IV Dragonair and left with the one with highest CP but poor IV lol

### Other Information
OS: Windows 10
Git Commit: 9ea015e1fd9c5d269276de8a8e822ee8eb0afa0f

**Comment by VictorChen** [comment]
looks like a bug in Master, needs to check for `initial_transfer` config before transferring

```
if return_value == PokemonCatchWorker.BAG_FULL:
    worker = InitialTransferWorker(self)
    worker.work()
```

**Comment by VictorChen** [comment]
should check for `initial_transfer` before transferring here

https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/__init__.py#L192

**Comment by bimahp** [comment]
is this a known bug and already fixed on dev?

**Comment by VictorChen** [comment]
this doesn't happen in dev because it transfers based on the release config instead of removing duplicates

**Comment by bimahp** [comment]
so when `release_pokemon` set to true and my bag is full its just gonna stop the bot right away right?

https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/pokemon_catch_worker.py#L37

**Comment by VictorChen** [comment]
yeah that's correct
