### ISSUE TITLE
"No /configs/config.json or specified config" when launching

### ISSUE THREAD

**Issue by RaziHaj** [PokemonGoF/PokemonGo-Bot#1454]
I have installed the Dev version of the bot.
I didn't know how to change the file type from Example to _json_. So, in order to follow the steps in the "Usage (up-to-date)" section, I went to _PokemonGo-Bot/configs_ and added a **different** _json_ file type, opened it with notepad, and pasted the following content of "config.json.pokemons":

> {
>     "auth_service": "google",
>     "username": "XX@XXXX.com",
>     "password": "XXX",
>     "location": "40.7554, -73.9815",
>     "gmapkey": "XXX",
>     "max_steps": 5,
>     "catch_pokemon": true,
>     "spin_forts": true,
>     "walk": 4.16,
>     "action_wait_min": 1,
>     "action_wait_max": 4,
>     "debug": false,
>     "test": false,
>     "health_record": true,
>     "location_cache": true,
>     "distance_unit": "km",
>     "item_filter": {
>       "1": { "keep" : 50 },
>       "2": { "keep" : 50 },
>       "3": { "keep" : 50 },
>       "101": { "keep" : 10 },
>       "102": { "keep" : 25 },
>       "103": { "keep" : 25 },
>       "201": { "keep" : 25 },
>       "701": { "keep" : 100 }
>     },
>     "evolve_all": "NONE",
>     "evolve_speed": 20,
>     "use_lucky_egg": false,
>     "hatch_eggs": true,
>     "longer_eggs_first": true,
>     "evolve_captured": false,
>     "release_pokemon": true,
>     "catch": {
>       "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or" },
> 
>       "// Pokemons with example": { "always_catch": true },
>       "// Gets filtered with release parameters": {},
> 
>       "// Legendary pokemons (Goes under S-Tier)": {},
>       "Lapras": { "always_catch": true },
>       "Moltres": { "always_catch": true },
>       "Zapdos": { "always_catch": true },
>       "Articuno": { "always_catch": true },
> 
>       "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
>       "Mewtwo": { "always_catch": true },
>       "Dragonite": { "always_catch": true },
>       "Snorlax": { "always_catch": true },
>       "// Mew evolves to Mewtwo": {},
>       "Mew": { "always_catch": true },
>       "Arcanine": { "always_catch": true },
>       "Vaporeon": { "always_catch": true },
>       "Gyarados": { "always_catch": true },
>       "Exeggutor": { "always_catch": true },
>       "Muk": { "always_catch": true },
>       "Weezing": { "always_catch": true },
>       "Flareon": { "always_catch": true },
> 
>       "// Growlithe evolves to Arcanine": {},
>       "Growlithe": { "always_catch": true },
>       "// Dragonair evolves to Dragonite": {},
>       "Dragonair": { "always_catch": true },
>       "// Grimer evolves to Muk": {},
>       "Grimer": { "always_catch": true },
> 
>       "// Magikarp evolves to Gyarados": {},
>       "Magikarp": { "always_catch": true },
>       "// Exeggcute evolves to Exeggutor": {},
>       "Exeggcute": { "always_catch": true },
>       "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
>       "Eevee": { "always_catch": true },
> 
>       "// A-Tier pokemons": {},
>       "Slowbro": { "always_catch": true },
>       "Victreebel": { "always_catch": true },
>       "Machamp": { "always_catch": true },
>       "Poliwrath": { "always_catch": true },
>       "Clefable": { "always_catch": true },
>       "Nidoking": { "always_catch": true },
>       "Venusaur": { "always_catch": true },
>       "Charizard": { "always_catch": true },
>       "Golduck": { "always_catch": true },
>       "Nidoqueen": { "always_catch": true },
>       "Vileplume": { "always_catch": true },
>       "Blastoise": { "always_catch": true },
>       "Omastar":  { "always_catch": true },
>       "Aerodactyl": { "always_catch": true },
>       "Golem": { "always_catch": true },
>       "Wigglytuff": { "always_catch": true },
>       "Dewgong": { "always_catch": true },
>       "Ninetales": { "always_catch": true },
>       "Magmar": { "always_catch": true },
>       "Kabutops": { "always_catch": true },
>       "Electabuzz": { "always_catch": true },
>       "Starmie": { "always_catch": true },
>       "Jolteon": { "always_catch": true },
>       "Rapidash": { "always_catch": true },
>       "Pinsir": { "always_catch": true },
>       "Scyther": { "always_catch": true },
>       "Tentacruel": { "always_catch": true },
>       "Gengar": { "always_catch": true },
>       "Hypno": { "always_catch": true },
>       "Pidgeot": { "always_catch": true },
>       "Rhydon": { "always_catch": true },
>       "Seaking": { "always_catch": true },
>       "Kangaskhan": { "always_catch": true }
>     },
>     "release": {
>       "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or" },
> 
>       "// Legendary pokemons (Goes under S-Tier)": {},
>       "Lapras": { "release_below_cp": 1041, "release_below_iv": 0.8, "logic": "and" },
>       "Moltres": { "release_below_cp": 1132, "release_below_iv": 0.8, "logic": "and" },
>       "Zapdos": { "release_below_cp": 1087, "release_below_iv": 0.8, "logic": "and" },
>       "Articuno": { "release_below_cp": 1039, "release_below_iv": 0.8, "logic": "and" },
> 
>       "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
>       "Mewtwo": { "release_below_cp": 1447, "release_below_iv": 0.8, "logic": "and"},
>       "Dragonite": { "release_below_cp": 1221, "release_below_iv": 0.8, "logic": "and" },
>       "Snorlax": { "release_below_cp": 1087, "release_below_iv": 0.8, "logic": "and" },
>       "// Mew evolves to Mewtwo": {},
>       "Mew": { "release_below_cp": 1152, "release_below_iv": 0.8, "logic": "and" },
>       "Arcanine": { "release_below_cp": 1041, "release_below_iv": 0.8, "logic": "and" },
>       "Vaporeon": { "release_below_cp": 984, "release_below_iv": 0.8, "logic": "and" },
>       "Gyarados": { "release_below_cp": 938, "release_below_iv": 0.8, "logic": "and" },
>       "Exeggutor": { "release_below_cp": 1032, "release_below_iv": 0.8, "logic": "and" },
>       "Muk": { "release_below_cp": 909, "release_below_iv": 0.8, "logic": "and" },
>       "Weezing": { "release_below_cp": 784, "release_below_iv": 0.8, "logic": "and" },
>       "Flareon": { "release_below_cp": 924, "release_below_iv": 0.8, "logic": "and" },
> 
>       "// Growlithe evolves to Arcanine": {},
>       "Growlithe": { "release_below_cp": 465, "release_below_iv": 0.8, "logic": "and" },
>       "// Dragonair evolves to Dragonite": {},
>       "Dragonair": { "release_below_cp": 609, "release_below_iv": 0.8, "logic": "and" },
>       "// Grimer evolves to Muk": {},
>       "Grimer": { "release_below_cp": 448, "release_below_iv": 0.8, "logic": "and" },
>       "// Magikarp evolves to Gyarados": {},
>       "Magikarp": { "release_below_cp": 91, "release_below_iv": 0.8, "logic": "and" },
>       "// Exeggcute evolves to Exeggutor": {},
>       "Exeggcute": { "release_below_cp": 384, "release_below_iv": 0.8, "logic": "and" },
>       "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
>       "Eevee": { "release_below_cp": 376, "release_below_iv": 0.8, "logic": "and" },
> 
>       "// A-Tier pokemons": {},
>       "Slowbro": { "release_below_cp": 907, "release_below_iv": 0.8, "logic": "and" },
>       "Victreebel": { "release_below_cp": 883, "release_below_iv": 0.8, "logic": "and" },
>       "Machamp": { "release_below_cp": 907, "release_below_iv": 0.8, "logic": "and" },
>       "Poliwrath": { "release_below_cp": 876, "release_below_iv": 0.8, "logic": "and" },
>       "Clefable": { "release_below_cp": 837, "release_below_iv": 0.8, "logic": "and" },
>       "Nidoking": { "release_below_cp": 864, "release_below_iv": 0.8, "logic": "and" },
>       "Venusaur": { "release_below_cp": 902, "release_below_iv": 0.8, "logic": "and" },
>       "Charizard": { "release_below_cp": 909, "release_below_iv": 0.8, "logic": "and" },
>       "Golduck": { "release_below_cp": 832, "release_below_iv": 0.8, "logic": "and" },
>       "Nidoqueen": { "release_below_cp": 868, "release_below_iv": 0.8, "logic": "and" },
>       "Vileplume": { "release_below_cp": 871, "release_below_iv": 0.8, "logic": "and" },
>       "Blastoise": { "release_below_cp": 888, "release_below_iv": 0.8, "logic": "and" },
>       "Omastar":  { "release_below_cp": 780, "release_below_iv": 0.8, "logic": "and" },
>       "Aerodactyl": { "release_below_cp": 756, "release_below_iv": 0.8, "logic": "and" },
>       "Golem": { "release_below_cp": 804, "release_below_iv": 0.8, "logic": "and" },
>       "Wigglytuff": { "release_below_cp": 760, "release_below_iv": 0.8, "logic": "and" },
>       "Dewgong": { "release_below_cp": 748, "release_below_iv": 0.8, "logic": "and" },
>       "Ninetales": { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
>       "Magmar": { "release_below_cp": 792, "release_below_iv": 0.8, "logic": "and" },
>       "Kabutops": { "release_below_cp": 744, "release_below_iv": 0.8, "logic": "and" },
>       "Electabuzz": { "release_below_cp": 739, "release_below_iv": 0.8, "logic": "and" },
>       "Starmie": { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
>       "Jolteon": { "release_below_cp": 746, "release_below_iv": 0.8, "logic": "and" },
>       "Rapidash": { "release_below_cp": 768, "release_below_iv": 0.8, "logic": "and" },
>       "Pinsir": { "release_below_cp": 741, "release_below_iv": 0.8, "logic": "and" },
>       "Scyther": { "release_below_cp": 724, "release_below_iv": 0.8, "logic": "and" },
>       "Tentacruel": { "release_below_cp": 775, "release_below_iv": 0.8, "logic": "and" },
>       "Gengar": { "release_below_cp": 724, "release_below_iv": 0.8, "logic": "and" },
>       "Hypno": { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
>       "Pidgeot": { "release_below_cp": 729, "release_below_iv": 0.8, "logic": "and" },
>       "Rhydon": { "release_below_cp": 782, "release_below_iv": 0.8, "logic": "and" },
>       "Seaking": { "release_below_cp": 712, "release_below_iv": 0.8, "logic": "and" },
>       "Kangaskhan": { "release_below_cp": 712, "release_below_iv": 0.8, "logic": "and" },
> 
>       "// Koffing evolves to Weezing (A-Tier)": {},
>       "Koffing": { "release_below_cp": 403, "release_below_iv": 0.8, "logic": "and" },
> 
>       "// Below is B-tier and lower pokemons": {},
>       "Magikarp": { "release_below_cp": 91, "release_below_iv": 0.8, "logic": "and" },
>       "Caterpie": { "release_below_cp": 156, "release_below_iv": 0.8, "logic": "and" },
>       "Weedle": { "release_below_cp": 156, "release_below_iv": 0.8, "logic": "and" },
>       "Diglett": { "release_below_cp": 158, "release_below_iv": 0.8, "logic": "and" },
>       "Metapod": { "release_below_cp": 168, "release_below_iv": 0.8, "logic": "and" },
>       "Kakuna": { "release_below_cp": 170, "release_below_iv": 0.8, "logic": "and" },
>       "Rattata": { "release_below_cp": 204, "release_below_iv": 0.8, "logic": "and" },
>       "Abra": { "release_below_cp": 208, "release_below_iv": 0.8, "logic": "and" },
>       "Zubat": { "release_below_cp": 225, "release_below_iv": 0.8, "logic": "and" },
>       "Chansey": { "release_below_cp": 235, "release_below_iv": 0.8, "logic": "and" },
>       "Pidgey": { "release_below_cp": 237, "release_below_iv": 0.8, "logic": "and" },
>       "Spearow": { "release_below_cp": 240, "release_below_iv": 0.8, "logic": "and" },
>       "Meowth": { "release_below_cp": 264, "release_below_iv": 0.8, "logic": "and" },
>       "Krabby": { "release_below_cp": 276, "release_below_iv": 0.8, "logic": "and" },
>       "Sandshrew": { "release_below_cp": 278, "release_below_iv": 0.8, "logic": "and" },
>       "Poliwag": { "release_below_cp": 278, "release_below_iv": 0.8, "logic": "and" },
>       "Horsea": { "release_below_cp": 278, "release_below_iv": 0.8, "logic": "and" },
>       "Gastly": { "release_below_cp": 280, "release_below_iv": 0.8, "logic": "and" },
>       "Ekans": { "release_below_cp": 288, "release_below_iv": 0.8, "logic": "and" },
>       "Shellder": { "release_below_cp": 288, "release_below_iv": 0.8, "logic": "and" },
>       "Vulpix": { "release_below_cp": 290, "release_below_iv": 0.8, "logic": "and" },
>       "Voltorb": { "release_below_cp": 292, "release_below_iv": 0.8, "logic": "and" },
>       "Geodude": { "release_below_cp": 297, "release_below_iv": 0.8, "logic": "and" },
>       "Doduo": { "release_below_cp": 297, "release_below_iv": 0.8, "logic": "and" },
>       "Onix": { "release_below_cp": 300, "release_below_iv": 0.8, "logic": "and" },
>       "Mankey": { "release_below_cp": 307, "release_below_iv": 0.8, "logic": "and" },
>       "Pikachu": { "release_below_cp": 309, "release_below_iv": 0.8, "logic": "and" },
>       "Magnemite": { "release_below_cp": 312, "release_below_iv": 0.8, "logic": "and" },
>       "Tentacool": { "release_below_cp": 316, "release_below_iv": 0.8, "logic": "and" },
>       "Paras": { "release_below_cp": 319, "release_below_iv": 0.8, "logic": "and" },
>       "Jigglypuff": { "release_below_cp": 321, "release_below_iv": 0.8, "logic": "and" },
>       "Ditto": { "release_below_cp": 321, "release_below_iv": 0.8, "logic": "and" },
>       "Staryu": { "release_below_cp": 326, "release_below_iv": 0.8, "logic": "and" },
>       "Charmander": { "release_below_cp": 333, "release_below_iv": 0.8, "logic": "and" },
>       "Goldeen": { "release_below_cp": 336, "release_below_iv": 0.8, "logic": "and" },
>       "Squirtle": { "release_below_cp": 352, "release_below_iv": 0.8, "logic": "and" },
>       "Cubone": { "release_below_cp": 352, "release_below_iv": 0.8, "logic": "and" },
>       "Venonat": { "release_below_cp": 360, "release_below_iv": 0.8, "logic": "and" },
>       "Bulbasaur": { "release_below_cp": 374, "release_below_iv": 0.8, "logic": "and" },
>       "Drowzee": { "release_below_cp": 374, "release_below_iv": 0.8, "logic": "and" },
>       "Machop": { "release_below_cp": 381, "release_below_iv": 0.8, "logic": "and" },
>       "Psyduck": { "release_below_cp": 386, "release_below_iv": 0.8, "logic": "and" },
>       "Seel": { "release_below_cp": 386, "release_below_iv": 0.8, "logic": "and" },
>       "Kabuto": { "release_below_cp": 386, "release_below_iv": 0.8, "logic": "and" },
>       "Bellsprout": { "release_below_cp": 391, "release_below_iv": 0.8, "logic": "and" },
>       "Omanyte": { "release_below_cp": 391, "release_below_iv": 0.8, "logic": "and" },
>       "Kadabra": { "release_below_cp": 396, "release_below_iv": 0.8, "logic": "and" },
>       "Oddish": { "release_below_cp": 400, "release_below_iv": 0.8, "logic": "and" },
>       "Dugtrio": { "release_below_cp": 408, "release_below_iv": 0.8, "logic": "and" },
>       "Rhyhorn": { "release_below_cp": 412, "release_below_iv": 0.8, "logic": "and" },
>       "Clefairy": { "release_below_cp": 420, "release_below_iv": 0.8, "logic": "and" },
>       "Slowpoke": { "release_below_cp": 424, "release_below_iv": 0.8, "logic": "and" },
>       "Pidgeotto": { "release_below_cp": 427, "release_below_iv": 0.8, "logic": "and" },
>       "Farfetch'd": { "release_below_cp": 441, "release_below_iv": 0.8, "logic": "and" },
>       "Poliwhirl": { "release_below_cp": 468, "release_below_iv": 0.8, "logic": "and" },
>       "Nidorino": { "release_below_cp": 480, "release_below_iv": 0.8, "logic": "and" },
>       "Haunter": { "release_below_cp": 482, "release_below_iv": 0.8, "logic": "and" },
>       "Nidorina": { "release_below_cp": 489, "release_below_iv": 0.8, "logic": "and" },
>       "Graveler": { "release_below_cp": 501, "release_below_iv": 0.8, "logic": "and" },
>       "Beedrill": { "release_below_cp": 504, "release_below_iv": 0.8, "logic": "and" },
>       "Raticate": { "release_below_cp": 504, "release_below_iv": 0.8, "logic": "and" },
>       "Butterfree": { "release_below_cp": 508, "release_below_iv": 0.8, "logic": "and" },
>       "Hitmonlee": { "release_below_cp": 520, "release_below_iv": 0.8, "logic": "and" },
>       "Ponyta": { "release_below_cp": 530, "release_below_iv": 0.8, "logic": "and" },
>       "Hitmonchan": { "release_below_cp": 530, "release_below_iv": 0.8, "logic": "and" },
>       "Charmeleon": { "release_below_cp": 544, "release_below_iv": 0.8, "logic": "and" },
>       "Wartortle": { "release_below_cp": 552, "release_below_iv": 0.8, "logic": "and" },
>       "Persian": { "release_below_cp": 568, "release_below_iv": 0.8, "logic": "and" },
>       "Lickitung": { "release_below_cp": 568, "release_below_iv": 0.8, "logic": "and" },
>       "Ivysaur": { "release_below_cp": 571, "release_below_iv": 0.8, "logic": "and" },
>       "Electrode": { "release_below_cp": 576, "release_below_iv": 0.8, "logic": "and" },
>       "Marowak": { "release_below_cp": 578, "release_below_iv": 0.8, "logic": "and" },
>       "Gloom": { "release_below_cp": 590, "release_below_iv": 0.8, "logic": "and" },
>       "Porygon": { "release_below_cp": 590, "release_below_iv": 0.8, "logic": "and" },
>       "Seadra": { "release_below_cp": 597, "release_below_iv": 0.8, "logic": "and" },
>       "Jynx": { "release_below_cp": 600, "release_below_iv": 0.8, "logic": "and" },
>       "Weepinbell": { "release_below_cp": 602, "release_below_iv": 0.8, "logic": "and" },
>       "Tangela": { "release_below_cp": 607, "release_below_iv": 0.8, "logic": "and" },
>       "Fearow": { "release_below_cp": 609, "release_below_iv": 0.8, "logic": "and" },
>       "Parasect": { "release_below_cp": 609, "release_below_iv": 0.8, "logic": "and" },
>       "Machoke": { "release_below_cp": 614, "release_below_iv": 0.8, "logic": "and" },
>       "Arbok": { "release_below_cp": 616, "release_below_iv": 0.8, "logic": "and" },
>       "Sandslash": { "release_below_cp": 631, "release_below_iv": 0.8, "logic": "and" },
>       "Alakazam": { "release_below_cp": 633, "release_below_iv": 0.8, "logic": "and" },
>       "Kingler": { "release_below_cp": 636, "release_below_iv": 0.8, "logic": "and" },
>       "Dodrio": { "release_below_cp": 640, "release_below_iv": 0.8, "logic": "and" },
>       "Tauros": { "release_below_cp": 643, "release_below_iv": 0.8, "logic": "and" },
>       "Primeape": { "release_below_cp": 650, "release_below_iv": 0.8, "logic": "and" },
>       "Magneton": { "release_below_cp": 657, "release_below_iv": 0.8, "logic": "and" },
>       "Venomoth": { "release_below_cp": 660, "release_below_iv": 0.8, "logic": "and" },
>       "Golbat": { "release_below_cp": 672, "release_below_iv": 0.8, "logic": "and" },
>       "Raichu": { "release_below_cp": 708, "release_below_iv": 0.8, "logic": "and" },
>       "Cloyster": { "release_below_cp": 717, "release_below_iv": 0.8, "logic": "and"},
>       "Mr. Mime": { "release_below_cp": 650, "release_below_iv": 0.8, "logic": "and" }
>     }
> }
> 

OS: 
Windows 10, 64 bit
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

Now I get the following problem:
![problem2](https://cloud.githubusercontent.com/assets/20704106/17222770/938b1992-5502-11e6-8901-e1a1204f06df.jpg)

**Comment by Jumbt** [comment]
Rename that file to config.json and you'll not get that error.

**Comment by bradleykins** [comment]
Dude you need to research before logging a problem, this is an issue with your understanding and NOT an issue in the  app.

You need to pass the config.json file in as a parameter, you will likely (if you did a pull on the dev project) have a run.sh file kicking about in the main folder. If you edit this in notepad you see the script someone wrote, and it gives you the format you need to pass for the app to work:

python pokecli.py --config ./configs/config.json

where ./configs/config.json is the subfolder configs and the file config.json

YOu can try running that with your json file, I personally havent touched the example pokemon one, but just the plain bog standard, as i want to control it for me, not someone elses account, but if you know what your doing in the json then fire on.

**Comment by RaziHaj** [comment]
@Jumbt The file name is already config.json, it was the first thing I checked :(
![illu](https://cloud.githubusercontent.com/assets/20704106/17223428/2d28b76a-5505-11e6-8913-36f5db83b215.jpg)

@bradleykins Thank you for the in-depth reply.
Believe me I had done as much research as I could, I've been trying to get it to work since noon. I have the utmost respect towards everybody's time and I'm trying as hard as I can not to waste it.

I should have stated before that I have no experience with Python (but do with java!).  Anyway, I followed the instruction up until the Usage part. I couldn't find the original "config.json", and "release_config.json", so I downloaded the dev version. I followed some instructions from other  questions posted here, where people have been told to change either "config.json.pokemons" or "config.json". I opened the pokemons' one with a notepad, added the my own parameters, and then transferred the whole code into a new json file, and named it "config.json".
		
Did it help clear the problem I have?

**Comment by Jumbt** [comment]
what's in config.json? because you need pretty much what you put in pokemon.json in there. The current error is effectively saying you don't have log in information in there.

**Comment by RaziHaj** [comment]
@Jumbt You can see the content in the quote section of my first message

**Comment by aTadTasty** [comment]
@RaziHaj did you place the config file into the root folder? if so, then you have to create a new folder in root called configs and then put config.json into the configs folder that you just made.

**Comment by RaziHaj** [comment]
@aTadTasty The config file is already in the configs folder. Jeez... what could cause that problem?

**Comment by Jumbt** [comment]
I see the problem now - @bradleykins has pointed it out already - you need to run the command so it loads with the json as parameter. 

python pokecli.py --config ./configs/config.json

At the moment you're not passing it the path the config file.

**Comment by RaziHaj** [comment]
@Jumbt I tried running the command he gave me (without the "python" part), but the problem remained.

**Comment by momonjo** [comment]
idiots... idiots everywhere..

**Comment by RaziHaj** [comment]
@momonjo I don't know what I've done to deserve such a response. I said before, I have never used Python, and I struggle finding answers to questions you probably find obvious. it doesn't make me an idiot. As long as I'm researching and looking for answers by myself before I ask for help, I think I fulfill my part in the deal. Try to be more considerate next time.

**Comment by momonjo** [comment]
go install python then.. save to C: or anywhere you like...

open folder that contain the bot, 
press shift + right click on white, choose "open command window here"

type : `C:\Python27\python.exe pokecli.py --config configs/config.json`

**) That `C:\Python27` is my instalation folder, you may change to another folder... example : `D:\Program Files\Python27\python.exe` followed by  `pokecli.py --config configs/config.json`

**Comment by RaziHaj** [comment]
@momonjo I appreciate the reply.
I have python on my pc, and I also followed the instruction for the whole installation.
I get the same problem: this time,
C:\Python27\python.exe: can't open file 'pokecli.py': [eeno 2] No such file or direcory.

I think I should make this clearer, **I have the config.json file, in the configs directory. Still, Python doesn't recongnize it.**

cheers

**Comment by momonjo** [comment]
weird,

first, are you sure you install that in `C:\Python27`
second, make sure you run the command in the right folder (that contain bot).

**Comment by RaziHaj** [comment]
@momonjo 
Yes, Python was installed in the default C:\Python27.
and I ran the command in PokemonGo-Bot folder.

**Comment by d0t1q** [comment]
@RaziHaj 

Provide an entire excerpt from your command prompt(press and hold shift then highlight the entire window then press ENTER > contents will go to your clipboard) because you are most definitely not running this correctly 

try running 
C:\Python27\python.exe C:\path\to\bot\pokecli.py --config configs/config.json

**Comment by RaziHaj** [comment]
@d0t1q  I'm definitely doing something wrong, that's for sure.

here is the excerpt from the line you asked me to run (I ran it in the PokemonGo directory):

C:\Users\user\PokemonGo Dev\PokemonGo-Bot>C:\Users\user\PokemonGo Dev\PokemonGo-Bot\pokecli.py --config configs/config.json
'C:\Users\user\PokemonGo' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\user\PokemonGo Dev\PokemonGo-Bot>pokecli.py --config configs/config.json
[00:32:10] PokemonGO Bot v1.0
[00:32:10] Error: No /configs/config.json or specified config
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-p PASSWORD] [-l LOCATION] [-lc LOCATION_CACHE]
                  [--catch_pokemon CATCH_POKEMON] [--spin_forts SPIN_FORTS]
                  [-w WALK] [-k GMAPKEY] [-ms MAX_STEPS] [-rp RELEASE_POKEMON]
                  [-d DEBUG] [-t TEST] [-du DISTANCE_UNIT] [-ev EVOLVE_ALL]
                  [-cm CP_MIN] [-ec EVOLVE_CAPTURED] [-le USE_LUCKY_EGG]
                  [-rt RECONNECTING_TIMEOUT] [-hr HEALTH_RECORD]
pokecli.py: error: argument -a/--auth_service is required

As you can see, I couldn't get the line to work properly, but I figured this is what you asked for?

**Comment by d0t1q** [comment]
can you try moving the config.json file to the same directory as the pokecli.py file 

move it here: C:\Users\user\PokemonGo Dev\PokemonGo-Bot\

so that way when you run the script you would do -cf config.json 
and as long as the command prompt is in the same directory it should work

**Comment by RaziHaj** [comment]
@d0t1q It seems to me like something in the file I created was not properly set, the system can't find it.
I moved the file to the ROOT folder as you asked, and ran the command again, but same results:

C:\Users\user\PokemonGo Dev\PokemonGo-Bot>pokecli.py -cf config.json
[00:53:12] PokemonGO Bot v1.0
[00:53:12] Error: No /configs/config.json or specified config
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-p PASSWORD] [-l LOCATION] [-lc LOCATION_CACHE]
                  [--catch_pokemon CATCH_POKEMON] [--spin_forts SPIN_FORTS]
                  [-w WALK] [-k GMAPKEY] [-ms MAX_STEPS] [-rp RELEASE_POKEMON]
                  [-d DEBUG] [-t TEST] [-du DISTANCE_UNIT] [-ev EVOLVE_ALL]
                  [-cm CP_MIN] [-ec EVOLVE_CAPTURED] [-le USE_LUCKY_EGG]
                  [-rt RECONNECTING_TIMEOUT] [-hr HEALTH_RECORD]
pokecli.py: error: argument -a/--auth_service is required

**Comment by bradleykins** [comment]
I don't believe its an issue with your content the system is showing a problem with finding the folder.

Can you run the following command:

tree c:\folder 

Where c:\folder is the location of your pokemonbot folder.

i.e.

c:\RaziHaj\PokemonGo-Bot

This will print the file structure you have, one you pop this up here we can see whats happening in terms of folders.

Also what is the full path for your config.json file?

is it like c:\RaziHaj\PokemonGo-Bot\configs\config.json?

We will get this sorted, sounds like an setup issue mainly.

**Comment by bradleykins** [comment]
Also do you have hide known file extensions off? I am assuming so, and looking at your screenshot im not 100% sure, so if you have a peek that could be the issue.

I assume you know how to change that, if not google show file extensions for your version of windows.

Let me know

**Comment by gregtampa** [comment]
come to slack chat #help and someone can help you
NOT A BUG

**Comment by LemonGraham** [comment]
It seems your file is named config.json.json
Make sure you can see file extensions. In a file window, press "View" then "Show file Extension"
