### ISSUE TITLE
Evolving not working

### ISSUE THREAD

**Issue by vicch** [PokemonGoF/PokemonGo-Bot#1456]
### Expected Behavior
Evolve pokemons on startup as configured.

### Actual Behavior
Not evolving at all. Wasted a lucky egg.

### Steps to Reproduce
```
"evolve_all": "Caterpie,Weedle,Pidgey,Rattata,Zubat,Eevee",
"evolve_cp_min": 10,
"evolve_speed": 15,
```

### Other Information
OS: Windows 7
Git Commit: 0a9444bd0da806e2a765af43b4de874146d5faf2

**Comment by aTadTasty** [comment]
it's prob because of server lagging right now. can't even log in for me.

http://downdetector.com/status/pokemon-go

**Comment by vicch** [comment]
@aTadTasty Login is fine for me. The bot just completely omits evolving step and goes on spinning and catching.

**Comment by sangwon04** [comment]
@vicch honestly, if you're going to risk losing an egg you might as well do the evolving yourself.

**Comment by aTadTasty** [comment]
@vicch have you tried updating the requirements after the pull? `sudo pip install -r requirements.txt`

**Comment by vicch** [comment]
@aTadTasty Yes, `git pull` and reinstalled the requirements several times, no luck.

**Comment by aTadTasty** [comment]
duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/1335 and https://github.com/PokemonGoF/PokemonGo-Bot/issues/1339 i guess we just gotta wait for a new resolve

**Comment by vicch** [comment]
@sangwon04 NSFW

**Comment by vicch** [comment]
Closed as duplicate of #1335 and #1339.

**Comment by Vvkmnn** [comment]
Hey, random question. How did you close your own issue?

I can't get it to work for some reason.

**Comment by sangwon04** [comment]
@vicch very understandable. Perhaps hold off on using the egg/evolve till after work then hah.

**Comment by vicch** [comment]
@Vvkmnn There's a button on the left of "Comment".

**Comment by Vvkmnn** [comment]
@vicch ...Wow, I'm having a slow day.

Thanks.
