### ISSUE TITLE
[DEV] invalid <lambda> value:

### ISSUE THREAD

**Issue by anovosiolov** [PokemonGoF/PokemonGo-Bot#1466]
./run.sh
[21:28:46] PokemonGO Bot v1.0
usage: pokecli.py [-h] [-cf CONFIG] [-a AUTH_SERVICE] [-u USERNAME]
                  [-p PASSWORD] [-l LOCATION] [-lc LOCATION_CACHE]
                  [--catch_pokemon CATCH_POKEMON] [--spin_forts SPIN_FORTS]
                  [-w WALK] [-k GMAPKEY] [-ms MAX_STEPS] [-rp RELEASE_POKEMON]
                  [-d DEBUG] [-t TEST] [-du DISTANCE_UNIT] [-ev EVOLVE_ALL]
                  [-ecm EVOLVE_CP_MIN] [-ec EVOLVE_CAPTURED]
                  [-le USE_LUCKY_EGG] [-rt RECONNECTING_TIMEOUT]
                  [-hr HEALTH_RECORD]

> `pokecli.py: error: argument -l/--location: invalid <lambda> value: u'\u05d0\u05e7\u05e1\u05d5\u05d3\u05d5\u05e1 \u05d0\u05e9\u05d3\u05d5\u05d3'
`

### Steps to Reproduce
Unicode location in config:
like:  
"location": "אקסודוס אשדוד",

Worked in commit: 4c46ad7e6b41f4d66400aee82be469cdbbb26f80
### Other Information
OS: Ubuntu 14.04
Git Commit: 34caa002a464b7665cdcfb531ea3d302632898ac

**Comment by th3w4y** [comment]
try below workaround



"location": "\\u05d0\\u05e7\\u05e1\\u05d5\\u05d3\\u05d5\\u05e1 \\u05d0\\u05e9\\u05d3\\u05d5\\u05d3"


In [1]: import json

In [2]: json.dumps({'location':"אקסודוס אשדוד"})
Out[2]: '{"location": **"\\u05d0\\u05e7\\u05e1\\u05d5\\u05d3\\u05d5\\u05e1 \\u05d0\\u05e9\\u05d3\\u05d5\\u05d3"**}'

In [3]:

**Comment by anovosiolov** [comment]
So to put "location": "\u05d0\u05e7\u05e1\u05d5\u05d3\u05d5\u05e1 \u05d0\u05e9\u05d3\u05d5\u05d3" in config file ? 
Gives me the same result:
`pokecli.py: error: argument -l/--location: invalid <lambda> value: u'\u05d0\u05e7\u05e1\u05d5\u05d3\u05d5\u05e1 \u05d0\u05e9\u05d3\u05d5\u05d3'`

**Comment by vieira** [comment]
PR #1503 should fix this.
