### ISSUE TITLE
[feature request] set item qty targets

### ISSUE THREAD

**Issue by slatspie** [PokemonGoF/PokemonGo-Bot#1468]
Would be great to be able set target quantities for items to keep a target number; collect below and recycle above.

eg. want have 20 pokeballs available want to have available slots for great balls, etc. Set item 1 (pokeballs) to 20 and, say, potions to zero (something like "item_filter": "1:20,101:0" or whatever)
So if I drop below 20 pokeballs, they will be collected from spins until the target of 20 is reached. If there are 20 or more in the item inventory then recycle any new ones.

It's a nice-to-have.

**Comment by aTadTasty** [comment]
@slatspie i thought it already did that 
this is what i have in mine.
`      "1": { "keep" : 50 },
      "2": { "keep" : 60 },
      "3": { "keep" : 70 },        
      "4": { "keep" : 100 },          
      "101": { "keep" : 0 },
      "102": { "keep" : 0 },
      "103": { "keep" : 0 },
      "201": { "keep" : 0 },
      "701": { "keep" : 30 }`

**Comment by Calcyfer** [comment]
Indeed, already works on dev.

**Comment by slatspie** [comment]
Excellent, thanks! I read through a bunch of the issues and pulls before posting this. I should have dug a little deeper.

**Comment by Evanito** [comment]
You should close this issue

**Comment by TheGoldenXY** [comment]
This issue has been resolved, closing this.

/closed
