### ISSUE TITLE
KeyError: 'GET_INVENTORY'

### ISSUE THREAD

**Issue by data2700** [PokemonGoF/PokemonGo-Bot#147]
getting this message after logging in.   

inventory_dict = inventory_req['responses']['GET_INVENTORY']['inventory_delta']['inventory_items']
KeyError: 'GET_INVENTORY'

**Comment by s1x** [comment]
Servers are at the moment under heavy load / offline. http://ispokemongodownornot.com/

**Comment by data2700** [comment]
Thanks!

**Comment by s7726** [comment]
If we've failed to get the data we expected because the server is busy (or other issue) we should report that rather than just trying to access data that doesn't exist and dumping.

**Comment by thellimist** [comment]
That shouldn't crash the app.
