### ISSUE TITLE
Error: No /configs/config.json or specified config

### ISSUE THREAD

**Issue by yweitkemper** [PokemonGoF/PokemonGo-Bot#1470]
### Expected Behavior
Authenticate

### Actual Behavior

Cant seem to find config files 
### Steps to Reproduce
This is the error I'm **getting**
![screenshot 2016-07-28 11 42 45](https://cloud.githubusercontent.com/assets/20580515/17225114/70a9b3ba-54b8-11e6-80e3-b3e8b2d79dcb.png)

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by friederschueler** [comment]
Did you create the file? You have to copy the example file and rename it. Is this too hard?

Please close the issue and rtfm: https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files

**Comment by yweitkemper** [comment]
I did create the file and it is renamed

**Comment by vicch** [comment]
Try to run `python pokecli.py --config configs/config.json` .

**Comment by yweitkemper** [comment]
Still the same error this is my file minus the username/pass anything else I'm missing?
![screenshot 2016-07-28 11 59 12](https://cloud.githubusercontent.com/assets/20580515/17225670/c1e07794-54ba-11e6-9de2-e92bc8f5d9c7.png)

**Comment by vicch** [comment]
Are you running `dev` or `master` ? This config file is for `master`.

**Comment by yweitkemper** [comment]
Ah ok, where would i find the Dev one?

**Comment by momonjo** [comment]
try open ur eyes wider mate..

**Comment by yweitkemper** [comment]
you see an error?

**Comment by boriss579** [comment]
Download a new copy of the config file and try not to delete any on the ["] in the details fields when you enter your info. I think this will fix your problem.

**Comment by surfaace** [comment]
read manual on how to config
