### ISSUE TITLE
AttributeError: 'PokemonGoBot' object has no attribute 'position'

### ISSUE THREAD

**Issue by surewhynotmon** [PokemonGoF/PokemonGo-Bot#1474]
### Expected Behavior
Running as bot on a simulated location

### Actual Behavior
AttributeErrror raised, program exit.

More error details running in debug mode
2016-07-28 18:59:16,963 [   rpc_api] [DEBUG] Parsing class: POGOProtos.Networking.Responses_pb2.GetInventoryResponse
2016-07-28 18:59:16,965 [    pgoapi] [ INFO] Cleanup of request!
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/home/vagrant/dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 32, in start
    self.stepper = Stepper(self)
  File "/home/vagrant/dev/PokemonGo-Bot/pokemongo_bot/stepper.py", line 32, in __init__
    self.origin_lat = self.bot.position[0]
AttributeError: 'PokemonGoBot' object has no attribute 'position'

### Steps to Reproduce
Run it with following json, location set to `New York, Central Park`
````
{
    "auth_service": "google",
    "username": "USER@gmail.com",
    "password": "PASSWORD",
    "location": "New York, Central Park",
    "gmapkey": "API-KEY",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.36,
    "debug": true,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104",
    "evolve_all": "NONE"
}

````

### Other Information
OS:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise 
Git Commit: ec2b7add95da6bc580035d8d4c472c1d41e439a6

**Comment by friederschueler** [comment]
Try `40.781346, -73.966578` and close this issue. You can get coordinates with google maps for example.

**Comment by oswaldocfr** [comment]
@friederschueler, I solved for my, Thanks!
