### ISSUE TITLE
Changing Location in Config.json won't teleport me there

### ISSUE THREAD

**Issue by JohnnyOmm** [PokemonGoF/PokemonGo-Bot#1480]
I updated to Dev version of this program and usually when i want to teleport to a pokemon spot that I view on my scanner, i type it in on config.json under
`"location": "25.765268149325763,-80.39148170432131",`
and it would take me there, but with dev version it is starting off from 

```
Last location flag used. Overriding passed in location
Last in-game location was set as: (xxxxxx,-yyyy, 0)
```
Instead of the location I want it to go, is there an easier way to a specific lat/long or at least walk towards that direction so I can capture a specific pokemon?

**Comment by vicch** [comment]
Did you try this `"location_cache": false,` in the config ?

**Comment by ArkBriar** [comment]
You can try remove the cache file under data folder (usually named last-location-mail@xxx.gmail.com.json if you log in with google). 
Plus, location changes may cause soft ban and the time depends on the distance.

**Comment by beedy01** [comment]
try change this config "location_cache": false

or go to folder \data and 
delete those file 

cells-xxxx.json and last-location-xxxx.json

**Comment by darkstardxm** [comment]
Try a shorter lat/long 
25.765267, -80.391482
