### ISSUE TITLE
Is this something we can use?

### ISSUE THREAD

**Issue by Roydeking52** [PokemonGoF/PokemonGo-Bot#1482]
I found a site where you can see if the server are up or if theye have any problems.
Theye have made a API: https://github.com/rubenvereecken/pokemongo-api

Maybe we can use it for some kind of monitoring?

**Comment by Bramzor** [comment]
This system uses the same API to detect this...

**Comment by xorinzor** [comment]
I don't see why the bot would need this, if you want to monitor if the service is up check https://pgorelease.nianticlabs.com/plfe/ (if you see text, it's up).

Please close this issue.

**Comment by TheGoldenXY** [comment]
Answer above, closing this for now.

/closed
