### ISSUE TITLE
Using high-tier balls and razz berries on low-tier pokemons with low CP

### ISSUE THREAD

**Issue by LostDGod** [PokemonGoF/PokemonGo-Bot#1487]
### Expected Behavior

Save the high-tier balls and razz berries for pokemons you actually want to keep according to the release config.

### Actual Behavior

>  A Wild Pidgeotto appeared! [CP 452] [Potential 0.42]
>  IV [Stamina/Attack/Defense] = [8/1/10]
>  Using Ultraball (chance: 34.92%)... (0 left!)

>  A Wild Dragonite appeared! [CP 1599] [Potential 0.51]
>  IV [Stamina/Attack/Defense] = [15/8/0]
>  Using Greatball (chance: 5.40%)... (2 left!)
>  [-] Attempted to capture Dragonite - failed.. trying again!
>  Using Greatball (chance: 5.40%)... (1 left!)
>  [-] Attempted to capture Dragonite - failed.. trying again!
>  Using Greatball (chance: 5.40%)... (0 left!)
>  [-] Attempted to capture Dragonite - failed.. trying again!
>  Using Pokeball (chance: 3.63%)... (84 left!)
>  [-] Attempted to capture Dragonite - failed.. trying again!
>  Using Pokeball (chance: 3.63%)... (83 left!)
>  [-] Attempted to capture Dragonite - failed.. trying again!
>  Using Pokeball (chance: 3.63%)... (82 left!)
>  [-] Attempted to capture Dragonite - failed.. trying again!
>  Using Pokeball (chance: 3.63%)... (81 left!)
>  [-] Attempted to capture Dragonite - failed.. trying again!
>  Using Pokeball (chance: 3.63%)... (80 left!)
>  [-] Attempted to capture Dragonite - failed.. trying again!
>  Using Pokeball (chance: 3.63%)... (79 left!)
>  [-] Attempted to capture Dragonite - failed.. trying again!
>  Using Pokeball (chance: 3.63%)... (78 left!)
>  [-] Attempted to capture Dragonite - failed.. trying again!
>  Using Pokeball (chance: 3.63%)... (77 left!)
>  [-] Attempted to capture Dragonite - failed.. trying again!
>  Using Pokeball (chance: 3.63%)... (76 left!)
>  [-] Attempted to capture Dragonite - failed.. trying again!
>  Using Pokeball (chance: 3.63%)... (75 left!)
>  [-] Attempted to capture Dragonite - failed.. trying again!
>  Using Pokeball (chance: 3.63%)... (74 left!)
>  Oh no! Dragonite vanished! :(

**Comment by achretien** [comment]
👍

**Comment by vicch** [comment]
Related to #1406 , however the opposite. A ball control feature will be really helpful.

**Comment by LostDGod** [comment]
@vicch Yap, I saw your post when searching for duplicates before posting this one. I absolutely agree, in fact I was about to request it in this issue. We really need to be able to configure ball usage.
