### ISSUE TITLE
Docker build not copying configs

### ISSUE THREAD

**Issue by Lunik** [PokemonGoF/PokemonGo-Bot#1488]
### Expected Behavior
After a `docker build`, the `configs/config.json` should by into the  docker image.

### Actual Behavior
`configs/config.json` is not in the docker image

### Steps to Reproduce
```
$ nano configs/config.json
$ docker build -t pkmgo .
```
### Other Information
OS: MacOS
Git Commit: c11af09b64df4be77257207dfd147649489c776e

**Comment by ColeFortson** [comment]
Getting the same issue here

**Comment by 4rthurRousseau** [comment]
To get around this problem, I used a "VOLUME" instruction in my Dockerfile so my docker image is built without any configuration in.

Here is my dockerfile :
```
FROM alpine

RUN apk update
RUN apk add --no-cache python
RUN apk add --no-cache python-dev
RUN apk add --no-cache py-pip
RUN apk add --no-cache perl
RUN apk add --no-cache git
RUN apk add --no-cache build-base

RUN git clone -b dev https://github.com/PokemonGoF/PokemonGo-Bot /opt/PokemonGo-Bot

WORKDIR /opt/PokemonGo-Bot
RUN pip install -r requirements.txt
RUN git submodule init
RUN git submodule update

VOLUME ["/opt/PokemonGo-Bot/configs"]

ENTRYPOINT ["python", "pokecli.py"]
```

After building the image, run it with the following command to mount your host directory (/`path/to/your/config/folder`) to your docker container.
```
docker run --rm -it -v /path/to/your/config/folder:/opt/PokemonGo-Bot/configs --name running-name image-name
```

**Comment by Lunik** [comment]
@4rthurRousseau your dockerfile is useless, the Dockerfile provided into this repo do exactly the same as you do. 
The `python onbuild` do it for you. 
And you aren't solving the problem of being obligated to add volume to the container.

# What we want:
 `$ docker build .` and all the configs are into the container.

**Comment by zenety** [comment]
@4rthurRousseau thank you very much for the docker file and run command. But how do I specify a config.json for the bot to run? I would love to run multiple bots in different docker containers.
