### ISSUE TITLE
Multiple bot account on PokemonGo-Bot (with .bat launcher) ?

### ISSUE THREAD

**Issue by rednka** [PokemonGoF/PokemonGo-Bot#1489]
Hi, it's possible to "read" 2 differents account's log on SimpleMap ?

i want to see my account & brother's account on SimpleMap without editing userdata.js

thanks and good job !

**Comment by buettner123** [comment]
you can add the usernames like this:
`var users = ["...@gmail.com", "...@gmail.com"];`

**Comment by thehawkes** [comment]
It depends ;)

my setup:

- 2 accounts (dev and main)
- 2 git bot directories (dev and master)
- the userdata.js in the master directory contains both accounts
- the 3 account specific json files are symlinked from the dev/web directory to the master/web directory

 ```
 ~/PokemonGo-Bot-dev/web/catchable-dev.json ~/PokemonGo-Bot-master/web/catchable-dev.json
  ~/PokemonGo-Bot-dev/web/inventory-dev.json ~/PokemonGo-Bot-master/web/catchable-dev.json
  ~/PokemonGo-Bot-dev/web/location-dev.json ~/PokemonGo-Bot-master/web/catchable-dev.json
```

- the master web directory is served by the python simplehttpserver
`python -m SimpleHTTPServer 8000`

**Comment by rednka** [comment]
@buettner123 thanks ! i have before create the issue test this : ["an_user"], ["an_other_user"]; and didn't work, your syntexe is correct i think, i go test this, thank you !

**Comment by inet-pwnZ** [comment]
im running 10 test Bots without issues

**Comment by TheGoldenXY** [comment]
This issue has been resolved, closing this.

/closed
