### ISSUE TITLE
[Feature Request] Farm around piles of lured pokestop only, instead of wondering around

### ISSUE THREAD

**Issue by Antairez** [PokemonGoF/PokemonGo-Bot#1498]
I hope the bot is able to farm around lured pokestops, there are tons of them in parks. Is it possible via configuration or we need a new feature just for this? Thanks

**Comment by LostDGod** [comment]
I will take this chance to speak about a few things that have been bothering me since yesterday.

So I know this exact spot that in-game is able to reach 4 pokestops at the same time (these ones are basically lured 24/7). Yet when I place the bot in there (not exactly there cause of geo positioning but pretty close) it still forces the player to go to the exact location of the pokestop to spin it instead of being able to spin all of them without moving. The range of picking up  normal pokemon seems fine but there's almost no range for pokestops.
As for lured pokemon, the bot is only trying to catch 1 upon reaching a lured spot instead of scanning like it does for regular pokemon so its pretty much pointless as a lured pokestop farmer atm. 
It also has no option to stay in a fixed place, it forces the player to move around and works weird when you set up the walking speed too low.

So yeah, I bump this request and if someone picks it up, please remember the issues I just spoke of.

**Comment by rihago** [comment]
think i like to see that too

@LostDGod Den Helder is the place? ;)

**Comment by LostDGod** [comment]
@rihago bars near the opera house, sydney

**Comment by Antairez** [comment]
@LostDGod I could not have said that better myself. It is really driving me crazy that I have to restart the bot every 3 minutes just to get it back to the coordinates I set for it (middle of 4 lured pokestops).

**Comment by MFizz** [comment]
Can you specify the wanted behaviour? Should it farm the nearest (lured) forts? Or just forts in a set radius from start? What should it do when there are no spinnable spots in the radius?

**Comment by Antairez** [comment]
@MFizz Let me try to throw in some ideas, I don't know if they are practical or not because I don't really understand what information the bot has and how it works with those information.

1. When the bot enters the "catch" mode, it scans for all lured pokestops within its scope, and find all clustered lured stops that are within x unit from each other, where x unit should be a small number that doesn't require the bot to travel too long without the effect of lured stops. (for example, x should not be more than 20 meters)
2. It then chooses the largest cluster and proceeds to loop within the chosen cluster.
3. If a lured stop lost its effect, it is removed from the loop list. If the loop list is smaller than x (maybe 3 or 4), the cluster is considered invalid. The bot then proceed to find the next available cluster.
4. If no valid cluster is found within scope, the bot goes back to wondering around mode, until one is found.

**Comment by LostDGod** [comment]
My idea is kind of similar to @Antairez and I'm a bit stonned so it might not make sense but here it goes:

> upon reaching a lured pokestop
> scans for nearby lured pokestops
> if more lured pokestops are found
> 	calculates central position to reach as many lured pokestops as possible
> 	determines how many within-reach lured pokestops there are (from the central position) (near_lured_stops)
> 	if "lured_stops": X, and near_lured_stops >=X
> 		sends player to central position
> 	LOOP
> 		if spin_forts = true
> 			spin pokestops every 5min
> 		scans for regular pokemon every 5sec
> 		if pokemon found 
> 			enter battle
> 		scans for lured pokemon every 3sec
> 		if lured pokemon found 
> 			enter battle
> 		scan for lured pokestops every 10sec
> 		if 0 within-reach lured pokestops are found
> 			resume 'normal/walking' mode
> 		every 
> 	LOOP END

**Comment by slatspie** [comment]
+1

Having the ability to walk to lure clusters and loiter around for a bit would be gold. I think it would likely also better replicate real user game play, reducing bot telltales

I have a cluster right near me.. 5 spots. I tried setting walk to 0, thinking it would hold me at the latlong but that removed any limitations at all and I essentially teleported around. My next attempt worked better. I set walk to a very low number, around 1. It would still walk to each spot (slowly) and catch some pokemon on the way, then spin. By the time it did that, the next spot had finished the cool down and was open. They all have lures on them all day and it just walked in circles.

**Comment by rihago** [comment]
the latest dev build totally killed farming lured spots.

i have got a spot with 4 lure forts around me, but it just moves away.

**Comment by rihago** [comment]
i think it should prioritize the lured stops, if it sees lured stops it should move there (even when its walking to another stop) and check does first and when a lured stop finished its cool down it should check it out again. when the lure is over it should move on. if a lure is back on the same stop it should move back to that lure.
