### ISSUE TITLE
Keep best CP and best IV

### ISSUE THREAD

**Issue by Floriferous** [PokemonGoF/PokemonGo-Bot#1507]
### Expected Behaviour
release: {
"any": {"keep_best_cp": x, "keep_best_iv": y}
}

Lets you keep your x best CP pokemon as well as your y best iv pokemon.

for example: 
release: {
"any": {"keep_best_cp": 1, "keep_best_iv": 1}
}

will keep 2 magikarps:

120cp, 0.54iv
10cp, 0.96iv

### Actual Behaviour
Currently, setting both appears to only consider the last rule, in this case it will only keep your y best IV pokemon:
release: {
"any": {"keep_best_cp": x, "keep_best_iv": y}
}

### Other Information
OS: Mac OS X
Git Commit: 47cf9db53d986f78cf0cce8a2c6aa5863c29a7c8

**Comment by simonsmh** [comment]
It's a good suggestion.

**Comment by achretien** [comment]
PR #1472

**Comment by TheGoldenXY** [comment]
PR has already been made. Closing this for now.

/closed
