### ISSUE TITLE
Cant seem to load config file

### ISSUE THREAD

**Issue by yweitkemper** [PokemonGoF/PokemonGo-Bot#1511]
### Expected Behavior
Load config file

### Actual Behavior
[16:01:25] PokemonGO Bot v1.0
[16:01:25] Error: No /configs/config.json or specified config
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-p PASSWORD] [-l LOCATION] [-lc LOCATION_CACHE]
                  [--catch_pokemon CATCH_POKEMON] [--spin_forts SPIN_FORTS]
                  [-w WALK] [-k GMAPKEY] [-ms MAX_STEPS] [-rp RELEASE_POKEMON]
                  [-d DEBUG] [-t TEST] [-du DISTANCE_UNIT] [-ev EVOLVE_ALL]
                  [-ecm EVOLVE_CP_MIN] [-ec EVOLVE_CAPTURED]
                  [-le USE_LUCKY_EGG] [-rt RECONNECTING_TIMEOUT]
                  [-hr HEALTH_RECORD]
Here is the error i get. 

This is my directory and my code 
![screenshot 2016-07-28 11 59 12](https://cloud.githubusercontent.com/assets/20580515/17232480/28b6238e-54dd-11e6-8701-f0f0098483d0.png)
![screenshot 2016-07-28 15 13 48](https://cloud.githubusercontent.com/assets/20580515/17232471/182e7714-54dd-11e6-8e1a-2099a84dc644.png)

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by rarshonsky** [comment]
It's not in the config folder.

**Comment by yweitkemper** [comment]
Which folder is that the data one?

**Comment by rarshonsky** [comment]
"[16:01:25] Error: No /configs/config.json or specified config"
It's by default looking for a config.json in the config folder. Which you don't appear to have.

**Comment by yweitkemper** [comment]
ah ok thank you so much

**Comment by yweitkemper** [comment]
Did this still doesn't seem to work, is there something I'm missing?

Thanks in advance. 
![screenshot 2016-07-28 16 18 47](https://cloud.githubusercontent.com/assets/20580515/17232732/0454520c-54df-11e6-8895-b5484b84384f.png)

**Comment by pokemule** [comment]
If it's the same error, try making the folder lowercase "configs" rather than uppercase "Configs". Folders are case-sensitive.

**Comment by yweitkemper** [comment]
That didn't help, still getting the same error.
