### ISSUE TITLE
dev resource usage / hanging issue

### ISSUE THREAD

**Issue by Bramzor** [PokemonGoF/PokemonGo-Bot#1520]
### Expected Behavior

Low resource usage as it is just a python script.

### Actual Behavior

A lot of the time, I see the busy mouse cursor while system is actually idle. Rebooted to a clean system and still having the same issue. Sometimes the system just stops doing anything and blocks the console.

### Steps to Reproduce

DEV branch on a Macbook Pro. 

### Other Information
OS: Mac OSX
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by banksymate** [comment]
`Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)`
Please add that to your issue.

As for the resource usage, my server is barely even affected by the process, it doesn't even show up in top.
(16gb ram \ Xeon E31230)

**Comment by Bramzor** [comment]
git log -n 1 --pretty=format:"%H"
ee9e32cd6c413a1e04b1286a1df37e4f27d9b871

Pulling it frequently from the git to get all the updates.
Yes resource show nothing, it's just that the console is hanging all the time :-(

**Comment by banksymate** [comment]
Causes no lag at all with my system, could possibly be your specs.
You should consider getting a server to run it on or running it on a spare computer if you have one if this problem keeps reoccurring, don't know what to tell you otherwise.

**Comment by Bramzor** [comment]
I think it's somewhere in one of the modules or in the implementation that it has issues. Not resource wise/specs because those are plenty. Also nothing running on that client so my guess is some kind of module. Anyone who is running it on Mac OSX without an issue?
I know the problem started with this specific bot. Before I was using another version (also based on the same pgoapi) but no issue there.
We'll see if someone else compains about the same issue.

BTW it is not that your server isn't showing the issue, that it isn't there. If it's running externally, you might just not notice it.

**Comment by banksymate** [comment]
I'd notice if something was hanging since I host a pretty large website on the same box. Maybe it's a thread hanging from a loop or something? What are the logs right before you notice it starts to hang, might help track it down.
