### ISSUE TITLE
Google Maps API (web page) Candy: undefined

### ISSUE THREAD

**Issue by DimaVIII** [PokemonGoF/PokemonGo-Bot#1521]
### Expected Behavior
Show amount of candy's.

### Actual Behavior
The Map is showing "Candy: undefined" under pokémon tab.

http://imgur.com/a/9cHgM

It was working with the releases 3a18aa57dfb67e2e09c207087cad6e5aa1867112

### Steps to Reproduce

Current Dev repo

### Other Information
Git Commit: ee9e32cd6c413a1e04b1286a1df37e4f27d9b871

**Comment by bnt44** [comment]
https://github.com/OpenPoGo/OpenPoGoWeb/pull/98

**Comment by tstumm** [comment]
Since its not a bot issue...
