### ISSUE TITLE
[Request] Configure on which pokemon to use razzberries

### ISSUE THREAD

**Issue by DanielVolz** [PokemonGoF/PokemonGo-Bot#1524]
I have the experience that I am always out of razzberries. The bot uses them on every harder to catch pokemon. It would be great if we could decide which pokemon is worth a razzberry.

Keep up the wonderful work! 👍 😃

**Comment by Bramzor** [comment]
+1 Only on the S and A class pokemon!

**Comment by banksymate** [comment]
Don't quote me on this, but I think it does it based off the chance of Pokemon being caught.

**Comment by Bramzor** [comment]
Correct, so it will use it to catch Rattatas etc that have a high CP. (Not worth anything though)

**Comment by banksymate** [comment]
Duplicate of #1487
