### ISSUE TITLE
[Feature Request] Keep X amount of Z,Y,A pokemon. When X amount is reached use lucky egg  and evolve Z, Y, A.

### ISSUE THREAD

**Issue by Henji96** [PokemonGoF/PokemonGo-Bot#1528]
This would be very useful for power leveling.

**Comment by slatspie** [comment]
I like this. 
Even just the first part would help. Keep x amount pokemon based on the candies needed for evolution would keep enough of each specific pokemon to use all candies for leveling in batch .. eg. have 9 Pidgey candies: keep 1 Pidgey, have 15 candies: keep 2, have 110 candies, keep 10 (candies-on-hand div candies-to-evolve +1). As you said, It would be for power leveling so keeping specific pokemon based on iv or cp would not really matter

**Comment by RedViper9** [comment]
You might be able to do part of this now by setting the keep_best_iv or keep_best_cp parameter. eg:
```
"release": {
    "Pidgey": { "release_below_cp": 237, "release_below_iv": 0.9, "logic": "and", "keep_best_iv": 70 },
```
That should let you keep your top 70 Pidgeys.

You could then modify config for Egg/Evolve cycle and reload the bot.

**Comment by slatspie** [comment]
I did have it set up like that. I finished doing a whack of evolves just now. I had more pidgey candies than I thought so didn't save enough pidgeys (my map shows undefined for candy counts and the fixes here didn't work for me so I lost count). Anyway, it was all good. I'll set it higher as you suggest.

**Comment by Henji96** [comment]
Slatspie, how do you go about evolving? I can't seem to get it to work on master or dev.

**Comment by slatspie** [comment]
@Henji96 sorry for the delay, was out of town. I evolved manually at that time. I think the evolve code is working now but I have not fully caught up on everything
