### ISSUE TITLE
The dev map didn't who Candy now.

### ISSUE THREAD

**Issue by xc-mezcal** [PokemonGoF/PokemonGo-Bot#1534]
### Expected Behavior

Candy for each type of pokemon.

### Actual Behavior

Candy: Undifined

### Steps to Reproduce
I have also tried to use some old but well functioned map submodule to replace the current one, But the issue is still there.

Run it and see :D

### Other Information
OS: Win 10
Git Commit: 83463c2bcd5c4360adbc41c61e6572406fec54ce

**Comment by vicch** [comment]
Have you tried
```
git submodule init
git submodule update
```

**Comment by xc-mezcal** [comment]
https://github.com/OpenPoGo/OpenPoGoWeb/pull/98
