### ISSUE TITLE
[   rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 500

### ISSUE THREAD

**Issue by Electrofenster** [PokemonGoF/PokemonGo-Bot#154]
When I start the Bot I only get this:
[   rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 500

**Comment by pawelkolanowski** [comment]
500 - Server error. Developer should know

**Comment by Electrofenster** [comment]
It's a internal server error I know, but i don't understand why it work sometimes and sometimes not. On my smartphone the servers work correctly..

**Comment by pawelkolanowski** [comment]
http://ispokemongodownornot.com
