### ISSUE TITLE
During softban it errors, rather than removing ban by spinning pokestop many times

### ISSUE THREAD

**Issue by MatthewARoy** [PokemonGoF/PokemonGo-Bot#1540]
### Expected Behavior
You can remove a softban by spinning a single pokestop every second or so for around 50 times, until you get items and xp from it.

### Actual Behavior
When banned, you can't spin pokestops because the app gives the softban error
https://unbanster.com/how-to-remove-soft-ban-pokemon-go/

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by MikeDX** [comment]
Fixed in pull request #1522 - awaiting approval
