### ISSUE TITLE
Flag `spin_forts` doesn't work

### ISSUE THREAD

**Issue by jasonliu119** [PokemonGoF/PokemonGo-Bot#1544]
I tried to debug it and print `str(config.spin_forts)` in `pokecli.py`, it says `{u'avoid_circles': False, u'max_circle_size': 10}`. What is wrong?

### Expected Behavior
when I config spin_forts to false, it should not spin the forts.

### Actual Behavior

when I config spin_forts to false, it still spins the forts.

### Steps to Reproduce
just try set spin_forts to false

### Other Information
OS: Ubuntu 14.04
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
6c6fc59de9ea02a2079cb7548f80937f65894088

**Comment by banksymate** [comment]
Please specify the OS and Git Commit
