### ISSUE TITLE
[Dev] "Release" function clarification.

### ISSUE THREAD

**Issue by DrunkAgain** [PokemonGoF/PokemonGo-Bot#1545]
### Expected Behavior
Keep 600CP above or .8 IV above

### Actual Behavior
In this case, this Aerodactyl has met the IV requirements for it to be kept, but the bot still released it.
![bug3](https://cloud.githubusercontent.com/assets/20692601/17237255/7fca8d2c-5582-11e6-8977-a5f4f493f36b.jpg)

here is my config.json,

    "evolve_all": "NONE",
    "evolve_speed": 20,
    "cp_min": 300,
    "use_lucky_egg": false,
    "hatch_eggs": true,
    "longer_eggs_first": true,
    "evolve_captured": false,
    "release_pokemon": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 600, "release_below_iv": 0.8, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3}

How can I keep 600CP+ or 0.8IV+ .

### Other Information
OS:  win7 32bit , python 2.7, dev
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by DennyHoang** [comment]
Your release logic is "or". Since the Aerodactyl has CP 93, it was true, so it released it

**Comment by banksymate** [comment]
Change the logic to "and", that way if it is under 80% IV AND under 600 CP it will release, how you have it right now is if it is below 600 cp or if it is below 80% IV it will release.

**Comment by DrunkAgain** [comment]
I see. Thank you very much guys.
