### ISSUE TITLE
NotLoggedInException

### ISSUE THREAD

**Issue by Lentron** [PokemonGoF/PokemonGo-Bot#1556]
I'm having troubles with logging in. 
On startup i keep getting a NotLoggedInException, even though i filled all the config files in both the config folder and the src folder

**Comment by tillheden** [comment]
I'm having the same issue, I'm using the dev branch

Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException
ImportError: No module named pgoapi.exceptions

**Comment by sfai05** [comment]
you need to run `source bin/activate` before `run.sh`

**Comment by Lentron** [comment]
even running source bin/activate and the run.sh i get exactly the same error
i've also tried a clean install incase something went wrong but no difference

**Comment by Lentron** [comment]
i've been looking into the error, here's what i found: 

pokecli.py gives the following error: 
    import error: No Module names pgoapi.exceptions 

then if i open the pgoapi.py line 38 reads:
    from pgoapi.exceptions import NotLoggedInexception

then opening exceptions.py it has a class names NotLoggedInException, and the def just passes it. 

so all in all i see no reason why it couldn't find this import

**Comment by luispereira** [comment]
Having the same problem starting the bot with npm start after:
 - checking out the project
 - npm install
 - pip install --upgrade -r requirements.rxt
