### ISSUE TITLE
Walker always starts at 0,0

### ISSUE THREAD

**Issue by jurjen2000** [PokemonGoF/PokemonGo-Bot#1557]
### Expected Behavior
Walk around the location set in the config.json

### Actual Behavior
The walker always starts at 0,0
I can not figure out how to make sure i2f(self.api._position_lng) returns another value then 0. (probably a very simple solution but I am a noob)

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by arnogues** [comment]
Post your `config.json` file please

**Comment by jurjen2000** [comment]
{
    "auth_service": "google",
    "username": "*******",
    "password": "********",
    "location": "52.1400000, 06.1200000",
    "gmapkey": "*********",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 50,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104",
    "evolve_all": "ALL"
}

The walker will walk towards the set location but starts at 0,0 so it will have to walk for days before arriving...

**Comment by jurjen2000** [comment]
![pgo](https://cloud.githubusercontent.com/assets/20708988/17239543/29bd8abe-5565-11e6-8a84-02d9fdaa2819.png)

**Comment by arnogues** [comment]
remove the space in the comma, and delete cache location json file.

You should stop using master branch and use dev branch, it's better and more fixed.

**Comment by jurjen2000** [comment]
Thanks so much, that solved the problem. :)

**Comment by w1sht0l1v3** [comment]
close ticket
