### ISSUE TITLE
Erorr "Walking from"

### ISSUE THREAD

**Issue by Chudopoke** [PokemonGoF/PokemonGo-Bot#1563]
How to fix it:

`[2016-07-29 10:32:40] [#] Walking from (2.27e-322, 1.6e-322) to (46.635417, 32.616867) for approx. 405234.00 seconds`

**Comment by knobunc** [comment]
Re-run the pip requirements step from setup.

**Comment by Chudopoke** [comment]
@knobunc did not help

**Comment by Jojo1910** [comment]
delete your lastlocation-*.jason in data

**Comment by Chudopoke** [comment]
@Jojo1910 did not help

`[2016-07-29 10:53:46] [x] Starting PokemonGo Bot....
[2016-07-29 10:53:46] [#] Scanning area for objects (1 / 400)
[2016-07-29 10:53:46] [#] Walking from (2.27e-322, 1.6e-322) to (46.635417, 32.616867) for approx. 405234.00 seconds`

**Comment by Jojo1910** [comment]
did you update the Projekt?

Command: git pull

**Comment by Chudopoke** [comment]
@Jojo1910 yes

**Comment by Chudopoke** [comment]
Delete the file "pokemon_spawn_locations.json" in the main folder , it helped . Thanks to all.
