### ISSUE TITLE
Bot walking slow

### ISSUE THREAD

**Issue by Bashin** [PokemonGoF/PokemonGo-Bot#1570]
### Expected Behavior
Setting in config "walk": 4.16 (m/s)
Should take about 50 - 60 seconds to get to a pokestop at a distance of 0.2 km

### Actual Behavior
Moving to pokestop at a speed of ~0.9 (m/s) - took 220 seconds for 0.2 km!
Pathing looks great though! :-)

### Steps to Reproduce
Just run the bot and compare times and distances traveled

### Other Information
OS: Win10
Git Commit: annoying bug (#1559) - installed from scratch one hour ago

**Comment by BartKoppelmans** [comment]
The speed was changed to be km/h. So you are walking at 4.16km/h. Set it to 15 to have some more speed!

**Comment by Bashin** [comment]
Great i'm an idiot :-D
Maybe the default value should be changed to a higher value
