### ISSUE TITLE
Item filter only uses default values

### ISSUE THREAD

**Issue by Erody** [PokemonGoF/PokemonGo-Bot#1572]
### Expected Behavior
The bot should recycle all items listed in the item filter. This is how mine looks:      
    
`"item_filter": "101,102,103,104,201,202,701",`
   
As you can see I added revives and razz berries, so those should also get recycled.
### Actual Behavior
However, that doesn't happen. Only what was originally listed in the item_filter (just potions) is being recycled. My bag is pretty much full with revives and razz berries because of this.

### Steps to Reproduce
Start bot with edited item_filter, watch it only recycle potions.

### Other Information
OS:  Ubuntu 14.04
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Jojo1910** [comment]
Are you running dev or master branch?

And pls run " git log -n 1 --pretty=format:"%H" " and paste the output here

**Comment by Erody** [comment]
Output: c7ab5b03cb93b5393bebbc383545a50e8519e57a   
Running on master branch
