### ISSUE TITLE
[Suggestion] Users should give the git branch when creating an issue

### ISSUE THREAD

**Issue by arnogues** [PokemonGoF/PokemonGo-Bot#1575]
### Expected Behavior
A lot of issues are created every day but sometimes they come from branch `master` or branch `dev` we should add a `### Branch name` title in the issue template.

**Comment by cwild** [comment]
Doesn't the template already mention to do a ```git log```?

https://github.com/PokemonGoF/PokemonGo-Bot/blob/a1433f235c0afc00a15d79ff99711c0cd520dc7f/.github/ISSUE_TEMPLATE.md

**Comment by arnogues** [comment]
Yes, this can be closed...
