### ISSUE TITLE
cant proceed with installation step : "$ source bin/activate"

### ISSUE THREAD

**Issue by leroyv13** [PokemonGoF/PokemonGo-Bot#1580]
### Expected Behavior
Succesfull installation

### Actual Behavior
cant complete installation

### Steps to Reproduce
latest steps in installation: 

$ cd download-directory
$ pip install PyYAML-3.11-cp27-cp27m-win32.whl
// if you needed to download the 64-bit version)
// (replace PyYAML-3.11-cp27-cp27m-win32.whl with PyYAML-3.11-cp27-cp27m-win_amd64.whl
After this, just do:

$ git clone -b master https://github.com/PokemonGoF/PokemonGo-Bot
$ cd PokemonGo-Bot
$ virtualenv .
$ source bin/activate

i`m in the folder where the pokemon go bot is installed but when i enter "source bin/activate" it says source is not recognized as an command. what am i doing wrong? 

thanks in advance!

### Other Information
OS: windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by arnogues** [comment]
You are under windows 10, follow the steps for windows
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation#installation-windows

**Comment by leroyv13** [comment]
thank you!!

**Comment by NamPNQ** [comment]
In window use `$ Scripts\activate.bat` instead of `$ source bin/activate`

**Comment by LasseSkogland** [comment]
Close this issue. Issue resolved.
