### ISSUE TITLE
socketio error

### ISSUE THREAD

**Issue by simonsmh** [PokemonGoF/PokemonGo-Bot#1581]
### Expected Behavior
run

### Actual Behavior
File "pokecli.py", line 40, in 
from pokemongo_bot import PokemonGoBot
File "/root/PokemonGo-Bot/pokemongo_bot/init.py", line
24, in 
from pokemongo_bot.socketio_server.runner import SocketI
oRunner
File "/root/PokemonGo-Bot/pokemongo_bot/socketio_server/ru
nner.py", line 6, in 
from app import app, sio
File "/root/PokemonGo-Bot/pokemongo_bot/socketio_server/ap
p.py", line 8, in 
sio = socketio.Server(async_mode='eventlet', logging=log
ging.NullHandler)
AttributeError: 'module' object has no attribute 'Server'

### Other Information
OS: Debian 8
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
a1433f235c0afc00a15d79ff99711c0cd520dc7f

**Comment by simonsmh** [comment]
sorry,fixed it.

**Comment by JVenberg** [comment]
How did you fix it? I'm still having that issue
