### ISSUE TITLE
[DEV] PIP failed (different installation instructions)

### ISSUE THREAD

**Issue by nivong** [PokemonGoF/PokemonGo-Bot#1582]
### Expected Behavior
it does not fail

### Actual Behavior
sudo pip install -r requirements.txt gives:
error code: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ZBnVwb/protobuf-to-dict/
'
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 7))
  Downloading protobuf-to-dict-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:

    Installed /usr/local/lib/python2.7/site-packages/nosexcover-1.0.10-py2.7.egg
    Searching for protobuf>=2.3.0
    Reading http://pypi.python.org/simple/protobuf/
    Best match: protobuf 3.0.0b4
    Downloading https://pypi.python.org/packages/8b/fa/2a4f48c3579a5d88bfe4e8408227cb12731efcb30da4ba423cf115a1d320/protobuf-3.0.0b4-py2.7.egg#md5=e29a69cb89fff0bc39f099e705e4e93e
    Processing protobuf-3.0.0b4-py2.7.egg
    creating /usr/local/lib/python2.7/site-packages/protobuf-3.0.0b4-py2.7.egg
    Extracting protobuf-3.0.0b4-py2.7.egg to /usr/local/lib/python2.7/site-packages

    Installed /usr/local/lib/python2.7/site-packages/protobuf-3.0.0b4-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ZBnVwb/protobuf-to-dict/setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 588, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (six 1.7.3 (/usr/local/lib/python2.7/site-packages), Requirement.parse('six>=1.9'))

### Steps to Reproduce
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation#installation-linux

### Other Information
OS: Synology DSM 6.x - Linux
Git Commit: latest dev update
Possible fix run the installation like described in the main read.me file.

**Comment by Jojo1910** [comment]
Try to remove the python-sixt package

**Comment by nivong** [comment]
@Jojo1910 and how would I do that (It's a synology linux version)
