### ISSUE TITLE
Bot crashes after spinning the Pokestop

### ISSUE THREAD

**Issue by MilkyPL** [PokemonGoF/PokemonGo-Bot#1592]
### Expected Behavior
Spin the Pokestop and move on

### Actual Behavior
Crash
`[2016-07-29 11:51:24] [#] Now at Pokestop: Trzy Zlote Baby - Spinning...`
`Traceback (most recent call last):`
`  File "/home/jakub/PokemonGo-Bot/pokecli.py", line 220, in <module>`
`    main()`
`  File "/home/jakub/PokemonGo-Bot/pokecli.py", line 211, in main`
`    bot.take_step()`
`  File "/home/jakub/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step`
`    self.stepper.take_step()`
`  File "/home/jakub/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step`
`    self._work_at_position(position[0], position[1], position[2], True)`
`  File "/home/jakub/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position`
`    self.bot.work_on_cell(cell, position, pokemon_only)`
`  File "/home/jakub/PokemonGo-Bot/pokemongo_bot/__init__.py", line 96, in work_on_cell`
`    hack_chain = worker.work()
`  `File "/home/jakub/PokemonGo-Bot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 47, in work`
`    if 'responses' in response_dict and \`
`TypeError: argument of type 'NoneType' is not iterable`

### Steps to Reproduce
Arrive near Pokestop

### Other Information
OS: Arch Linux
Git Commit: 3aca6d798f8a3e173dce0beb7b13c9505cc5b251

**Comment by arnogues** [comment]
Use dev branch, it's up to date (and tap  `git pull` too)
