### ISSUE TITLE
[Suggestion] Config generator

### ISSUE THREAD

**Issue by karasube** [PokemonGoF/PokemonGo-Bot#1594]
### Expected Behavior
Config generator (CLI/GUI). Might be based on yeoman or whatever suits.

### Actual Behavior
$ head -5 configs/config.json | xclip
$ cp configs/config.example.json configs/config.json
$ vim configs/config.json

modify auth, location, gmap key, etc etc ...
modify catch config
modify release config
setup eggs, etc ...

I might throw something later if nobody do this.

**Comment by yehan77** [comment]
+1 Would make it a lot easier on us. I've been stumbling with some problems editing the release configs. A GUI would probably help 40% of the problems that occur

**Comment by jrlambs** [comment]
Is anyone working on something like this? I was thinking something web-based, maybe it could be built as an option in the web project?   I'm at best an intermediate at javascript but I'd be willing to start throwing something together.  I'm not positive how inter-related the web project and this one are and I'm afraid if I do a pull-request with this functionality in that project that It wouldn't be seen as the right place and I'd have to do a bunch of re-work to get it to the right place? thoughts on this? where would be the "right" place for something like this?
