### ISSUE TITLE
[DEV] python-dev dependency / greenlet error

### ISSUE THREAD

**Issue by ferbeb** [PokemonGoF/PokemonGo-Bot#1597]
2805cb7 introduced eventlet==0.19.0 in requirements.txt.
This depends on greenlet which cannot be installed when the python-dev package is not installed.

Can be fixed by `apt-get install python-dev`, but took me a few minutes to figure out.

**Comment by hklcf** [comment]
There's a quick solution for this.

`
pip uninstall greenlet
easy_install greenlet
`
