### ISSUE TITLE
Duplicate configuration variable 'spin forts' in example files

### ISSUE THREAD

**Issue by mrthrowaway** [PokemonGoF/PokemonGo-Bot#1598]
### Expected Behavior
Remove the one that is not used

### Actual Behavior
One is an object/array and the other is bool.

### Other Information
OS:  Ubuntu 16.04
Git Commit: a1433f235c0afc00a15d79ff99711c0cd520dc7f

**Comment by tstumm** [comment]
Both configuration options are valid, so whats the problem?
Use the bool if you just want to control if its on or off. Use the dict if you want to configure it more precisely.

**Comment by mrthrowaway** [comment]
Well, the second one isn't documented. I have no idea what 'circle' means in that context
