### ISSUE TITLE
[Login] Support Google 2-Factor

### ISSUE THREAD

**Issue by tstumm** [PokemonGoF/PokemonGo-Bot#16]
Some Google accounts use 2-factor authorization. Login for 2-factor currently fails.

**Comment by tstumm** [comment]
Workaround should be app passwords:
https://security.google.com/settings/security/apppasswords

**Comment by Saturate** [comment]
Seeing as most accounts may get banned, it's not really good to use ones real google account with 2-Factor.

**Comment by tstumm** [comment]
Well using better techniques than teleporting should avoid getting banned

**Comment by s1x** [comment]
Till that you can use an app password: https://support.google.com/accounts/answer/185833?hl=en

**Comment by tstumm** [comment]
I already proposed that as a fallback solution
