### ISSUE TITLE
Slack, Gitchat , dev , Master 

### ISSUE THREAD

**Issue by crack00r** [PokemonGoF/PokemonGo-Bot#160]
wich one is the right One to use? ! 
This Project becomes bigger and bigger

**Comment by eggins** [comment]
Slack is our current messenger.
Master is our main branch
Anything currently being developed (beta) will be in the dev branch.

Once its confirmed working - we will merge it to the main branch!

**Comment by harsh1412** [comment]
@eggins Someone changed the main branch to DEV please fix it -.-'

**Comment by douglascamata** [comment]
@harsh1412 main branch is `dev` because we use it to develop, receive pull requests, etc.

**Comment by harsh1412** [comment]
@douglascamata Normal people will not able to run the project if they download Dev branch.

**Comment by douglascamata** [comment]
@harsh1412 I fixed the instruction to clone the repository in the `dev` branch. It always instruct users to clone the `master` branch.

**Comment by harsh1412** [comment]
@douglascamata thats helpful,
Dude but can i download the master branch and dev branch and merge the dev branch into master branch and it will run?

**Comment by jtdroste** [comment]
You can just download the dev branch and run it @harsh1412 .  Be warned, there are constant changes.

Closing the issue.

**Comment by harsh1412** [comment]
@jtdroste but pgoapi is missing in dev 
Should i take it from master?
