### ISSUE TITLE
run as daemon or docker

### ISSUE THREAD

**Issue by sayasemut** [PokemonGoF/PokemonGo-Bot#1602]
please anyone help me on this.. 
i have followed many tutorial and spent much time to this but still cannot 

anyone has succeed setup this as a daemon or service ?

OS: ubuntu 14.04
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by tastypear** [comment]
use `screen`

**Comment by zenety** [comment]
Or create an upstart script in /etc/init

**Comment by tstumm** [comment]
Or use the given Dockerfile.
This is actually no issue so I'm closing this.
