### ISSUE TITLE
[Suggestion] Adding Ability to Set Predefined Path in Config

### ISSUE THREAD

**Issue by Whosdaman** [PokemonGoF/PokemonGo-Bot#1604]
### Expected Behavior
Travel from point A to B to C to D...

### Actual Behavior
Following pokestops or standing still

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Pyrofer** [comment]
I would like the ability to set these waypoints on the web interface by clicking the map, then the bot walks to where you clicked. Used in conjunction with the Pokevision site you could easily pick specific pokemon to walk to and capture rather than randomly wandering.

**Comment by glumpje** [comment]
This would make life so much easier, maybe add support for the wtracks format used by Necrobot

https://github.com/NecronomiconCoding/NecroBot/wiki/Locations-&-GPX-Route-Files

Integration with Pokemon Go Map would be awsome too. :)
