### ISSUE TITLE
warning: no support for Intel AESNI instructions unable to execute

### ISSUE THREAD

**Issue by nivong** [PokemonGoF/PokemonGo-Bot#1612]
### Expected Behavior
Install requirments

### Actual Behavior
trows error:
```
warning: no support for Intel AESNI instructions
unable to execute '/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ccache-gcc': No such file or directory
error: Setup script exited with error: command '/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ccache-gcc' failed with exit status 1

### Steps to Reproduce
I have a synology NAS and I have tried the following commands to get it working:
```
sudo pip install -r ./requirements.txt
also tried:
while read line; do sudo easy_install $line; done < requirements.txt

It looks like an build error for the linux kernel. 

### Other Information
OS: Synology Linux DSM 6.x
Git Commit: latest release

### Similair issues:
https://github.com/AHAAAAAAA/PokemonGo-Map/issues/945
https://github.com/Legrandin/pycryptodome/issues/27
Related to:
https://github.com/Legrandin/pycryptodome/issues

**Comment by mrseeker** [comment]
Looks like gcc is not installed. You need to install that one first.

**Comment by nivong** [comment]
Could you give me a hand in the right direction @mrseeker?

**Comment by mrseeker** [comment]
Run this command on your Synology server and tell me if you still get errors:
`ipkg install optware-devel`

**Comment by arnogues** [comment]
install docker on your synology and try to install the bot into docker, you will keep your synology clean

**Comment by nivong** [comment]
@mrseeker my nas isn't bootstrapped, ipkg can't be used
@arnogues, good tip! Tried it but failed, have no idea how docker works lol I used this docker:
https://hub.docker.com/r/babfrag/docker-pokemongobot/
but it failed to install....
Any good tutorial out there?

**Comment by mrseeker** [comment]
https://blog.pavelsklenar.com/how-to-install-and-use-docker-on-synology/ <- this one?

**Comment by nivong** [comment]
omg @mrseeker thanks I had NO idea that images meant the "basic/OS" i always just searched and thought it was some sort of github lol
When downloading the image "python" and creating a new container called "pokemon go" It worked! 
Now I just need to reinstall my nas to get rid of all the dirty python stuff i installed manually lol...
