### ISSUE TITLE
Bot seems to wander aimlessly

### ISSUE THREAD

**Issue by xorinzor** [PokemonGoF/PokemonGo-Bot#1619]
### Expected Behavior
To walk towards pokestops and catch pokemon in the meanwhile

### Actual Behavior
Very, very slowly it just walks north, but isn't actually going to a pokestop

### Steps to Reproduce
Just run the latest dev build

### Other Information
OS: Win 10 x64
Git Commit: c5483349e02fc0b1c8c8ed31411ae8ca71ec4177

**Comment by mrseeker** [comment]
Do you have evolve_all set to "all"? If so, might be related to #1586

**Comment by xorinzor** [comment]
@mrseeker I do not, I have had these defined as `Pidgey,Rattata,Weedle,Caterpie,Zubat`

This is happening to me since I updated just now to the latest `dev` commit

**Comment by vicch** [comment]
What's your config?

**Comment by xorinzor** [comment]
@vicch

```
{
    "auth_service": "google",
    "username": "my@email.com",
    "password": "ibetyouwannaknowdontya",
    "location": "somewhere",
    "gmapkey": "mygmapskey",
    "max_steps": 4,
    "catch_pokemon": true,
    "spin_forts": true,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
	  "1": { "keep" : 100 },
	  "2": { "keep" : 999 },
	  "3": { "keep" : 999 },
	  "4": { "keep" : 999 },
      "101": { "keep" : 30 },
      "102": { "keep" : 50 },
      "103": { "keep" : 100 },
      "104": { "keep" : 999 },
      "201": { "keep" : 100 },
      "202": { "keep" : 999 },
      "701": { "keep" : 40 }
    },
    "evolve_all": "Pidgey,Rattata,Weedle,Caterpie,Zubat",
    "evolve_speed": 20,
    "cp_min": 10,
    "use_lucky_egg": false,
    "hatch_eggs": true,
    "longer_eggs_first": true,
    "evolve_captured": false,
    "release_pokemon": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "Rattata": { "always_release" : true },
      "Pidgey": { "always_release" : true },
      "Zubat": { "always_release" : true },
      "Weedle": { "always_release" : true },
      "Caterpie": { "always_release" : true },
      "Magikarp": { "keep_best_cp" : true },
      "// Example of keeping stronger (based on IV) Zubat:": {},
      "// Zubat": { "keep_best_iv" : true }
    }
}
```

**Comment by Philipp59** [comment]
`   "walk": 4.16,`

its km/h not m/s maybe thats the reason ?

**Comment by mrseeker** [comment]
Correction: It is related to #1586, posted a possible fix there.

**Comment by xorinzor** [comment]
@philipp59 I haven't changed that value since the beginning (also I'm from the netherlands so I work with km/h too) 4.16km/h seems like walking speed to me?

**Comment by Philipp59** [comment]
you are right i set the speed up to 40 km/h and resulting to this:
13:49:14] Arrived at Pokestop
[13:49:33] A Wild Pikachu appeared! [CP 219] [Potential 0.53]
[13:49:33] IV [Stamina/Attack/Defense] = [5/4/15]
[13:49:35] Using Greatball (chance: 27.01%)... (0 left!)
[13:49:36] Captured Pikachu! [CP 219] [Potential 0.53] [5/4/15]
[13:49:41] Moving towards fort 03d55664e8824ca69f8fa64c5af9dacc.16, 0.05km left

[13:49:41] Arrived at Pokestop
[13:50:02] Moving towards fort 03d55664e8824ca69f8fa64c5af9dacc.16, 0.05km left

[13:50:02] Arrived at Pokestop
[13:50:23] Moving towards fort 03d55664e8824ca69f8fa64c5af9dacc.16, 0.05km left

[13:50:23] Arrived at Pokestop
[13:50:44] Moving towards fort 03d55664e8824ca69f8fa64c5af9dacc.16, 0.05km left

[13:50:44] Arrived at Pokestop
[13:51:04] Moving towards fort 03d55664e8824ca69f8fa64c5af9dacc.16, 0.05km left

[13:51:04] Arrived at Pokestop
[13:51:27] Moving towards fort 03d55664e8824ca69f8fa64c5af9dacc.16, 0.05km left

[13:51:27] Arrived at Pokestop
[13:51:52] Moving towards fort 03d55664e8824ca69f8fa64c5af9dacc.16, 0.05km left

[13:51:52] Arrived at Pokestop
[13:52:16] Moving towards fort 03d55664e8824ca69f8fa64c5af9dacc.16, 0.05km left

[13:52:16] Arrived at Pokestop

so its ignoring move settings ?

**Comment by xorinzor** [comment]
@mrseeker yours is actually walking to a fort though, mine isn't (I know the pattern of how the bot should be walking, plus I'm kinda in the middle of nowhere so there arent a lot of pokestops nearby either).

It's just walking.. to nothing

**Comment by mrseeker** [comment]
Guys, please check #1586, I am calling this a duplicate...

**Comment by mrseeker** [comment]
@xorinzor And if you turn evolve_all off, will that change behavior? For me it had the same issue when it booted up... It started going north in a very slow pace due to the evolve_all being constantly triggered.

**Comment by xorinzor** [comment]
@mrseeker again, it's not related since yours is moving to a fort, mine isn't. it seems to not even detect any objects in my area.

Also I set `evolve_all` to `false` and the same thing happens, so that's not the issue either.

**Comment by kubiq** [comment]
i have same problem, `evolve_all` = `false` and still walking aimlessly

**Comment by xorinzor** [comment]
I let it run for a while, and it took 4 minutes for the bot to detect objects in the area, now it walks back towards them and seems to function as intended again.

Not sure what is going on in the meanwhile during those 4 minutes, but it doesn't seem to be good.

**Comment by shaldev** [comment]
Mine walks to one pokestop, then starts moving to another and suddenly decides to switch to the previously visited pokestop...


> [14:03:05] Moving towards fort 45d9643285cd40fb8c75cfa4654cd996.11, 0.14km left
> [14:03:15] Moving towards fort 45d9643285cd40fb8c75cfa4654cd996.11, 0.14km left
> [14:03:26] Moving towards fort 45d9643285cd40fb8c75cfa4654cd996.11, 0.13km left
> [14:03:36] Moving towards fort 148b9d06b56d4e979ad645016e507bd5.12, 0.11km left
> [14:03:47] Moving towards fort 148b9d06b56d4e979ad645016e507bd5.12, 0.11km left
> [14:03:57] Moving towards fort 148b9d06b56d4e979ad645016e507bd5.12, 0.10km left
> [14:04:08] Moving towards fort 148b9d06b56d4e979ad645016e507bd5.12, 0.10km left
> [14:04:19] Moving towards fort 148b9d06b56d4e979ad645016e507bd5.12, 0.09km left

**Comment by mrseeker** [comment]
Okay, just let me get facts straight here:
- You start the bot
- It starts wandering around in an area near a pokestop
- After 4 minutes it suddenly sees the pokestop

If thats the case, then its Niantic having network issues. If not, then it might be that your location is too far from a pokestop (I don't know the maximum range for a pokestop to be visible).

**Comment by xorinzor** [comment]
@mrseeker no, it wasnt in range of a pokestop, the pokestop was south of the bot and it just started walking north, then after 4 minutes it detected the fort and started walking back towards it.

Right now it seems to be working though, so it may indeed have been some external factor causing it to wander aimlessly.
