### ISSUE TITLE
Exception on Non-Ascii locations

### ISSUE THREAD

**Issue by Balauue** [PokemonGoF/PokemonGo-Bot#162]
The latest version throws an UnicodeEncodeError on non-ascii location strings, e.g. "Köpenicker Str., Berlin, Germany" with umlauts.

what fixes it for me: pokecli.py line ``28``

```
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

and deleting the ``import sys`` a litte below.

**Comment by jtdroste** [comment]
This should be fixed now on the dev branch.
