### ISSUE TITLE
[Dev] catchable-<username>.json not updating

### ISSUE THREAD

**Issue by also1412** [PokemonGoF/PokemonGo-Bot#1622]
### Expected Behavior
web/catchable-<username>.json gets updated when bot catches pokemon and map gets updated

### Actual Behavior
web/catchable-<username>.json reads: {}

### Steps to Reproduce
Run bot

### Other Information
OS: OS X
Git Commit: c5483349e02fc0b1c8c8ed31411ae8ca71ec4177

**Comment by xushWT** [comment]
confirmed

**Comment by matejvelikonja** [comment]
and then on the map nothing is shown.

not sure if its related, but also alerts are not displayed on web gui

**Comment by mizhgan** [comment]
catchable-.json is updated and then moment later it`s updated again with {}, so webmap does not have much time to read it.
I think it`s reasonable to wait until devs release websocket version of the bot with same webmap - it`s so much better then use AJAX to load jsons once a second.

**Comment by also1412** [comment]
@mizhgan agreed.

**Comment by Jojo1910** [comment]
@mizhgan you are right. I'm watching the map a lot and only 1 time the map loaded a Pokemon for 1 Sec so its working good but the bot is too fast. Maybe it shouldn't show Pokemon he can catch maybe it should show Pokemon he did catch and which flee

**Comment by mushi8** [comment]
if you change the order it works fine.

like so :   
with open(user_web_catchable, 'w') as outfile:
                    json.dump(pokemon, outfile)

                return_value = self.catch_pokemon(self.cell['catchable_pokemons'][0])

                with open(user_web_catchable, 'w') as outfile:
                   json.dump({}, outfile)

                return return_value

its working fine with the web

**Comment by also1412** [comment]
tested, magic! thanks

also i just saw be9e7bb79de33a7d177014184c510b2c60513be8 changed it. issue can be closed.
