### ISSUE TITLE
Can someone please point me in the right direction.

### ISSUE THREAD

**Issue by Rlewisrlou666** [PokemonGoF/PokemonGo-Bot#1623]
Hi i'm just looking to set up the map GUI how do I go about doing that?

**Comment by vicch** [comment]
Have you read this? https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Google-Maps-API-(web-page)

**Comment by Rlewisrlou666** [comment]
I got it to display in the web browser but its not tracking my movement or anything.
I might give it a bash later Thanks for the help.

**Comment by ironbishop** [comment]
known issue, currently the web doesnt work in the master branch

workaround is manually creating an empty  "location-USER.json" file

duplicate #691

**Comment by TheGoldenXY** [comment]
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/691

/closed
