### ISSUE TITLE
Uncaught exception when exiting.

### ISSUE THREAD

**Issue by priestoferis** [PokemonGoF/PokemonGo-Bot#1628]
### Expected Behavior
Graceful exit on keyboard interrupt (ctrl-c).

### Actual Behavior
Got a TypeError.

```
^CTraceback (most recent call last):
  File "pokecli.py", line 389, in <module>
    main()
  File "pokecli.py", line 68, in main
    bot.tick()
  File "/home/fbence/Codes/PokemonGo-Bot/pokemongo_bot/__init__.py", line 89, in tick
    if worker(self).work() == WorkerResult.RUNNING:
  File "/home/fbence/Codes/PokemonGo-Bot/pokemongo_bot/cell_workers/recycle_items_worker.py", line 14, in work
    item_count_dict = self.bot.item_inventory_count('all')
  File "/home/fbence/Codes/PokemonGo-Bot/pokemongo_bot/__init__.py", line 396, in item_inventory_count
    'GET_INVENTORY']['inventory_delta']['inventory_items']
TypeError: string indices must be integers, not str
```

### Steps to Reproduce
Only got it once so far.

### Other Information
OS: Ubuntu 16.04
Git Commit: 3e6edf6ddc003b898b652a7a7a30abc08d73b75d

**Comment by pavel-trubitsyn-clearscale** [comment]
Got the same
> root@ip-172-31-59-94:/opt/PokemonGo-Bot# git pull
> Already up-to-date.

> root@ip-172-31-59-94:/opt/PokemonGo-Bot# pip install -r requirements.txt --upgrade
> Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@3787ffbe2e80ebce8a02d48eebceb9edf40179c1#egg=pgoapi (from -r requirements.txt (line 1))
>   Skipping because already up-to-date.
> Requirement already up-to-date: geopy==1.11.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
> Requirement already up-to-date: protobuf==3.0.0b4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
> Requirement already up-to-date: requests==2.10.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
> Requirement already up-to-date: s2sphere==0.2.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
> Requirement already up-to-date: gpsoauth==0.3.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
> Requirement already up-to-date: protobuf-to-dict==0.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
> Requirement already up-to-date: googlemaps==2.4.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
> Requirement already up-to-date: colorama==0.3.7 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
> Requirement already up-to-date: enum34==1.1.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
> Requirement already up-to-date: pyyaml==3.11 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
> Requirement already up-to-date: haversine==0.4.5 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
> Requirement already up-to-date: polyline==1.3.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
> Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from pgoapi->-r requirements.txt (line 1))
> Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages (from protobuf==3.0.0b4->-r requirements.txt (line 3))
> Requirement already up-to-date: future in /usr/local/lib/python2.7/dist-packages (from s2sphere==0.2.4->-r requirements.txt (line 5))
> Requirement already up-to-date: pycryptodomex>=3.0 in /usr/local/lib/python2.7/dist-packages (from gpsoauth==0.3.0->-r requirements.txt (line 6))
> Installing collected packages: pgoapi
>   Running setup.py develop for pgoapi
> Successfully installed pgoapi-1.1.0

> [2016-07-29 20:43:27] [x] PokemonGO Bot v1.0
> [2016-07-29 20:43:27] [x] Configuration initialized
> [2016-07-29 20:43:27] [x] Coordinates found in passed in location, not geocoding.
> [2016-07-29 20:43:27]
> [2016-07-29 20:43:27] [x] Address found: 54.983033,82.895887
> [2016-07-29 20:43:27] [x] Position in-game set as: (54.983033, 82.895887, 0.0)
> [2016-07-29 20:43:27]
> Traceback (most recent call last):
>   File "./pokecli.py", line 220, in <module>
>     main()
>   File "./pokecli.py", line 206, in main
>     bot.start()
>   File "/opt/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
>     self._setup_api()
>   File "/opt/PokemonGo-Bot/pokemongo_bot/__init__.py", line 159, in _setup_api
>     balls_stock = self.pokeball_inventory()
>   File "/opt/PokemonGo-Bot/pokemongo_bot/__init__.py", line 234, in pokeball_inventory
>     inventory_dict = inventory_req['responses']['GET_INVENTORY'][
> KeyError: 'GET_INVENTORY'`
