### ISSUE TITLE
New config.json fileds - what are they doing?

### ISSUE THREAD

**Issue by boriss579** [PokemonGoF/PokemonGo-Bot#1629]
So I have downloaded the new dev branch and there are some new fields in the config file that I can find on the wiki.
Can anyone give me a quick guide what the purpose of:
    "forts": {
      "spin": true,
      "avoid_circles": true,   **-->this one**
      "max_circle_size": 50  **-->this one**

"health_record": true        **-->this one**

**Comment by mrseeker** [comment]
its the dev branch, so to prevent people from spamming that their stuff does not work its not documented yet.

avoid_circles & max_circle_size: Prevent bot from walking in a loop by keeping track of the last 50 spots visited.

health_record: Prevent google login from functioning when Google Fit functionality is turned on.

**Comment by boriss579** [comment]
Cool man, thanks!
