### ISSUE TITLE
wrong triger IV for pokemon release

### ISSUE THREAD

**Issue by akbaribnu** [PokemonGoF/PokemonGo-Bot#1630]
hello dev, i have a problem with script, i set IV 0.9 for release pokemon, and my snorlax woth IV 0.69 release too, and i have only one snorlax before.
why my snorlax release too.? and i dont have duplicate snorlax

**Comment by Raiven66** [comment]
since your IV setting is 0.9, and your newly acquired snorlax is 0.69, it is released. What is the problem?

**Comment by akbaribnu** [comment]
my other pokemon with iv under 0.9 not release too and dont have duplicate,
i think release only for duplicate pokemon, because my snorlax not have duplicate before

**Comment by Raiven66** [comment]
I might be wrong but I think only just newly captured ones are compared to the values and eventually released
(new to the code, might have overlooked something)

**Comment by asnelzin** [comment]
It seems like they changed this logic. Now pokemons will be released even if you haven't duplicate.   Lost some good ones because of it.

Need to find commit to clarify this.
