### ISSUE TITLE
Log in error

### ISSUE THREAD

**Issue by numinam** [PokemonGoF/PokemonGo-Bot#1638]
### Expected Behavior
Log in using Google account

### Actual Behavior
Server busy, log in error trying again in 10 seconds

### Steps to Reproduce
Not using any 2 step verification, tried on multiple accounts and also tried generating app password on 1 account that I had 2 step verification on.
Any guide how to make this work?

### Other Information
OS: Windows 10

**Comment by PokemonFinder727** [comment]
I've got the issue where it asks me for the code to connect devices, when i try to get the code off the console it just closes before i can even see it. I haven't got 2 step verification on either.

**Comment by BarryReid** [comment]
I'm getting the same as OP

**Comment by mrseeker** [comment]
Exactly what it says: Niantic server cannot handle your request (server too busy).

**Comment by numinam** [comment]
The google servers are up so thats not the problem

**Comment by mrseeker** [comment]
@numinam Its not the google server but the Niantic/Pokemongo server which is unstable. Sometimes that one lags out, and the bot will give exactly this error.

**Comment by numinam** [comment]
http://ispokemongodownornot.com/ Im really sure its not server related, 
![screenshot_11](https://cloud.githubusercontent.com/assets/20701909/17253157/d09a5e30-55af-11e6-9935-f0412fc27cf4.png)

**Comment by mrseeker** [comment]
One other option: Is this the first time you are logging in? If so, check if your password & auth is correct.

**Comment by numinam** [comment]
@mrseeker  Just checked it and had missed one letter, thanks working without one problem now :)
