### ISSUE TITLE
[Suggestion] Alpine Dockerfile

### ISSUE THREAD

**Issue by arckosfr** [PokemonGoF/PokemonGo-Bot#1640]
Hello,

I use docker whenever it possible, and i found the actual a bit weight (700Mb+) and not really user-friendly.
So i have created a new one (150Mb) based on python:2-alpine
It support : 
+ webview
+ external conf
+ AutoRestart

You can see at https://github.com/arckosfr/dockerfiles/tree/master/PokemonGo-Bot
If you want you can use it to replace the original.

**Comment by Lunik** [comment]
+1
How could you have 700mb ? [Mine](https://hub.docker.com/r/lunik/pkmgobot/) is only 310Mb

**Comment by arckosfr** [comment]
yes without python:2.7-onbuild (the size of the tag is not realistic because it exclude the based image weight)

**Comment by Lunik** [comment]
Oh yes ! My mistake ;)

**Comment by Wonderfall** [comment]
Why did you close it? More and more official images are migrating to Alpine Linux, this shows how image size is a concern to many of us.
