### ISSUE TITLE
web - multiple problems when userdata.js contains multiple usernames

### ISSUE THREAD

**Issue by Erody** [PokemonGoF/PokemonGo-Bot#1642]
### Expected Behavior
Clicking on Info - shows user info about user currently in focus
Clicking on Items - shows items of user currently in focus
..
same for Pokemon and Pokedex

### Actual Behavior
Clicking on Info - always shows the first username, shows info of a random user
Clicking on Items - always shows the first username, shows items of a random user
..
same for Pokemon and Pokedex

All item names are undefined, some item counts are undefined

### Steps to Reproduce
Start SimpleHTTPServer and go to localhost:8000

### Other Information
OS: Ubuntu 14.04
Git Commit: c7ab5b03cb93b5393bebbc383545a50e8519e57a

**Comment by Lunik** [comment]
See [here](https://github.com/OpenPoGo/OpenPoGoWeb/issues) for Web issues.
