### ISSUE TITLE
[dev] unnecessary log output every tick

### ISSUE THREAD

**Issue by 1cu** [PokemonGoF/PokemonGo-Bot#1644]
### Expected Behavior
No clutter in the log output

### Actual Behavior
Blank log line every tick

### Steps to Reproduce
Start bot, wait till it starts walking.

### Other Information
OS: Debian 7.11
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
e936135da0d98e7d9d27a8d98c0c2f3571d27b1f

Change  pokemongo_bot/__init__.py
`    def tick(self):
        logger.log('')
        self.cell = self.get_meta_cell()`
changed to
`    def tick(self):
        self.cell = self.get_meta_cell()`

This line has been introduced with PR #1627

**Comment by djdiart** [comment]
+1
not working

**Comment by douglascamata** [comment]
@1cu this log was added to separate each tick's logs and will stay there.

**Comment by 1cu** [comment]
Shouldn't it then be a debug or test option?

**Comment by xorinzor** [comment]
agreed @douglascamata that should be a debug option feature

**Comment by leadboots5** [comment]
This is changed in the latest dev. Those of us that like the change will have to hope it remains. /crossfingers
