### ISSUE TITLE
[Suggestion] Safe Exit to stop soft ban -home (location)

### ISSUE THREAD

**Issue by infamousmax** [PokemonGoF/PokemonGo-Bot#165]
Perhaps a safe exit function could be added? I imagine a good reason for a soft ban is somebody putting in a location 5+ miles from their real (home) location. A GUI to manage inventory and bots would solve this or a unmanged bot but until that happens perhaps a -home function could be added which will either take you back to your gps in real time or even something as simple as saying "You're 30 minutes from home, please do not login on your mobile device until that has elapsed".

**Comment by ironbishop** [comment]
If the bot knows where your home is, it could deny you to teleport too far.

But if the operator is fool enough to specify a obiously weird destination, probably he won't specify his home location in the first place.

**Comment by jtdroste** [comment]
I'm going to close this for tracking in #138.
