### ISSUE TITLE
dev-fix version gives: "Error: No /configs/config.json or specified config"

### ISSUE THREAD

**Issue by leroyv13** [PokemonGoF/PokemonGo-Bot#1650]
### Expected Behavior
start pokecli.py

### Actual Behavior
Error: No /configs/config.json or specified config

### Steps to Reproduce
After succesfully using the master version i want to use dev version, so:

$ git clone -b dev-fix https://github.com/PokemonGoF/PokemonGo-Bot  
$ cd PokemonGo-Bot  
$ pip2 install -r requirements.txt
$ git submodule init
$ git submodule update

i have 1 config file with the same login parameters as i used for the master version. 

config.json contains: 

{
    "auth_service": "google",
    "username": "####",
    "password": "####",
    "location": "#######",
    "gmapkey": "###",
    "max_steps": 5,
    "catch_pokemon": true,
    "forts": {
      "spin": true,
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "1": { "keep" : 100 },
      "101": { "keep" : 10 },
      "102": { "keep" : 30 },
      "103": { "keep" : 30 },
      "201": { "keep" : 30 },
      "701": { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "evolve_speed": 20,
    "evolve_cp_min": 300,
    "use_lucky_egg": false,
    "hatch_eggs": true,
    "longer_eggs_first": true,
    "evolve_captured": false,
    "release_pokemon": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 1000, "release_below_iv": 0.9, "logic": "and"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    }
}

when i run "python pokecli.py" i am getting the error:  "No /configs/config.json or specified config"

### Other Information
OS: windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by ayiire** [comment]
You have to specific the config file.

python pokecli.py --config configs/fullfilenamehere

**Comment by leroyv13** [comment]
C:\PokemonGo-Bot>python pokecli.py --config configs/config.json 

this gives the same error sadly, or am i still doing something wrong?

**Comment by ayiire** [comment]
Are you sure the file is config.json?

**Comment by leroyv13** [comment]
yes i`m sure, see:

![image](https://cloud.githubusercontent.com/assets/17337672/17254568/994a0376-55b5-11e6-89df-ff5f14806cfc.png)

**Comment by ayiire** [comment]
configs\config.json

You have the slash the wrong way.

**Comment by leroyv13** [comment]
Thanks for noticing my mistake there!, But it still doesnt run. To my understanding it has to run when entering the line below, but it still doesnt start the bot.. instead get this:

C:\PokemonGo-Bot>python pokecli.py --config configs\config.json
[18:04:14] PokemonGO Bot v1.0
> c:\pokemongo-bot\pokecli.py(363)init_config()
-> return config
(Pdb)

**Comment by mirkorobocop** [comment]
@leroyv13 same here, any one know how to fix it? 
on debian wheezy:
`[12:13:04] PokemonGO Bot v1.0
> /root/PokemonGo-Bot/pokecli.py(363)init_config()
-> return config
(Pdb)
`

**Comment by ayiire** [comment]
Run the following command to show which commit version you're on

git log -n 1 --pretty=format:"%H

**Comment by mirkorobocop** [comment]
```
~/PokemonGo-Bot# git log -n 1 --pretty=format:"%H"
18d3b2df2f5fbadc396271b03c47bb19d8258212

```

**Comment by leroyv13** [comment]
C:\Users\Leroy\PokemonGo-Bot>git log -n 1 --pretty=format:"%H
18d3b2df2f5fbadc396271b03c47bb19d8258212

**Comment by xorinzor** [comment]
just a stupid question, but is your `config.json` file actually in the `config` directory?

If not, you should just pass `-cf config.json`

**Comment by mirkorobocop** [comment]
i have config.json in configs directory, also tried with -cf parameter, nothing works

**Comment by X1xMadex1X** [comment]
I believe I know the issue. I solved it on my pc.
Check the type file. On windows, it never changed my file to a json file, it stayed as a .example file. Easy fix.
New text document, copy everything over, save as .json
Worked for me

**Comment by xorinzor** [comment]
@X1xMadex1X then it wouldn't show in the screenshot he took as `JSON-bestand`, would've been a good idea though otherwise.

**Comment by X1xMadex1X** [comment]
@xorinzor Ahh I passed over the screenshot. It has to be a path error since the auth is the first thing it would try to read from the file. Should have a catch to catch no file for opening. 

I had the exact same error but thats how i fixed it.

Btw, love the bot.  Hoping to contribute soon!
