### ISSUE TITLE
[dev] bot crashes on startup

### ISSUE THREAD

**Issue by Mooseymax** [PokemonGoF/PokemonGo-Bot#1653]
### Expected Behavior
Bot to run

### Actual Behavior
Crashing on startup (after latest sync)

The following error happens when doing "pip install -r requirements.txt"
```
building 'markupsafe._speedups' extension
error: [Error 2] The system cannot find the file specified
```

And the following error happens when trying to actually run the bot
`ImportError: No module named socketIO_client`

### Steps to Reproduce
Whenever I run the dev bot following recent sync.

### Other Information
OS: Windows
Git Commit: be9e7bb79de33a7d177014184c510b2c60513be8

**Comment by zjr8** [comment]
Requirements seem to have changed on one of the releases overnight -  try `pip install -r requirements.txt --upgrade `

**Comment by Mooseymax** [comment]
I had already tried pulling a fresh release from git, so all files are up to date as at the last revision.

Doing `pip install -r requirements.txt --upgrade` results in the second error listed above.
```
building 'markupsafe._speedups' extension
error: [Error 2] The system cannot find the file specified
```

Thanks anyway :)

**Comment by zjr8** [comment]
No Worries - at least in my virtual environment the same error was fixed by a dependency update / reinstall

**Comment by iggut** [comment]
Same here: fresh clone of the dev git and then:
pip install -r requirements.txt 

    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\markupsafe
    copying markupsafe\tests.py -> build\lib.win-amd64-2.7\markupsafe
    copying markupsafe\_compat.py -> build\lib.win-amd64-2.7\markupsafe
    copying markupsafe\_constants.py -> build\lib.win-amd64-2.7\markupsafe
    copying markupsafe\_native.py -> build\lib.win-amd64-2.7\markupsafe
    copying markupsafe\__init__.py -> build\lib.win-amd64-2.7\markupsafe
    running egg_info
    writing MarkupSafe.egg-info\PKG-INFO
    writing top-level names to MarkupSafe.egg-info\top_level.txt
    writing dependency_links to MarkupSafe.egg-info\dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'MarkupSafe.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'MarkupSafe.egg-info\SOURCES.txt'
    copying markupsafe\_speedups.c -> build\lib.win-amd64-2.7\markupsafe
    running build_ext
    building 'markupsafe._speedups' extension
    error: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\XXXX\\appdata\\local\\temp\\pip-build-wbfv04\\MarkupSafe\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\XXXX\appdata\local\temp\pip-g5apo2-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\XXXX\appdata\local\temp\pip-build-wbfv04\MarkupSafe\

**Comment by iggut** [comment]
Just tried the master git and that one runs perfectly.....I am unsure what I am going wrong then.

**Comment by Mooseymax** [comment]
My only issue is that the config.json is much better in the dev version along with a few other features.

**Comment by clavat** [comment]
Same here...

**Comment by Mooseymax** [comment]
Thanks @clavat I've tried installing `pip install setuptools==21.2.1` but still getting the error below
`from socketIO_client import SocketIO
ImportError: No module named socketIO_client`

Any further help?

**Comment by justinbeatz** [comment]
pip install socketIO_client will fix it.

**Comment by Mooseymax** [comment]
@justinbeatz Thank you for the reply!
Fixed the error which resulted in the following error - `ImportError: No module named eventlet`
Fixed error with same style install - `pip install eventlet`

I'm now coming up to `ImportError: No module named flask` & have tried `pip install flask`
This comes up with the first error I was getting: 
```
    building 'markupsafe._speedups' extension
    error: [Error 2] The system cannot find the file specified
```

**Comment by asnelzin** [comment]
Try to completely rebuild you virtual environment:
`pip install -r requirements.txt -I`

**Comment by Whosdaman** [comment]
I am getting the exact same error, running Windows 10, and I've tried running everything specified here and nothing has resolved this issue

**Comment by vamirineni87** [comment]
pip install setuptools==21.2.1

**Comment by Whosdaman** [comment]
I don't know where @vamirineni87 post is, but his suggestion worked

Run pip install setuptools==21.2.1
Then run pip install -r requirements.txt -I

**Comment by iggut** [comment]
yep so I ran the above two commands and now my error has changed:

    checking if libyaml is compilable
    error: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\\\appdata\\local\\temp\\pip-build-z3dqmi\\pyyaml\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\\appdata\local\temp\pip-_opdo9-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\\appdata\local\temp\pip-build-z3dqmi\pyyaml\


Then seeing as how libyaml was missing for some reason I did:

C:\PokemonGo-Bot1>pip install libyaml
Collecting libyaml
  Could not find a version that satisfies the requirement libyaml (from versions: )
No matching distribution found for libyaml

**Comment by Viper896** [comment]
FYI workaround to install markupsafe on windows can be found here:

https://github.com/pallets/markupsafe/issues/60

**Comment by Mooseymax** [comment]
^Workaround works fine and can now use the dev bot again

Happy with this at the moment but would be nice to have it fixed in the repo so that people don't have to workaround.

For clarification, to fix the problem, do the following:
`pip install setuptools==23.2.1`
`pip install --no-cache-dir markupsafe==0.23`

And @iggut you need to download `PyYAML-3.11-cp27-cp27m-win32.whl` from http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyyaml, put it in your PokemonGo-bot folder and do `pip install PyYAML-3.11-cp27-cp27m-win32.whl`.

Should fix your problem before you use the fix from @Viper896 :)

**Comment by iggut** [comment]
Nope, same thing and I did have that step done @Mooseymax but did it again to make sure

warning: manifest_maker: standard file '-c' not found

    reading manifest file 'MarkupSafe.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'MarkupSafe.egg-info\SOURCES.txt'
    copying markupsafe\_speedups.c -> build\lib.win-amd64-2.7\markupsafe
    running build_ext
    building 'markupsafe._speedups' extension
    error: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\x\\appdata\\local\\temp\\pip-build-atrk7_\\markupsafe\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\x\appdata\local\temp\pip-rgblop-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\x\appdata\local\temp\pip-build-atrk7_\markupsafe\

**Comment by iggut** [comment]
Cleaned everything up and did everything all over and this time it worked....I copy pasted the same lines so not sure whats up......but hey it works
