### ISSUE TITLE
moving away from 4 lured stops

### ISSUE THREAD

**Issue by rihago** [PokemonGoF/PokemonGo-Bot#1655]
my trainer is moving away from 4 lured stops.

i spawn next to 4 lured stops. it only spins one, and then moves away.

i tried the following config without result.

    "max_steps": 1,
    "catch_pokemon": true,
    "forts": {
      "spin": true,
      "avoid_circles": false,
      "max_circle_size": 1
    },
    "walk": 1,

**Comment by leadboots5** [comment]
You didn't post your version

**Comment by rihago** [comment]
latest dev.

**Comment by z4ppy** [comment]
Same here, bot moved away from lures with latest dev version (ae5184fed) :(

**Comment by douglascamata** [comment]
`latest dev` is not a valid version. Latest dev now is (much) different than 4 hours ago.

**Comment by douglascamata** [comment]
And bot doesn't stay in lure forever. It checks is there is Pokemon, catch is it's there and leave.

**Comment by rihago** [comment]
it's 9a29c0f at the moment.

you i saw him go, but we have a place in our town, with 4 stops in a range of 10 meters, with 24/7 Lure modules on it.

The bot only goes to 1, turns around, walks away and never coming back.

i want it to stay there, or, prioritize lure stops over normal stops. if it sees one where the cooldown of the spin is gone, go to it, get the lure pokemon and spin it.

or that my bot isn't moving at all and just stays at those 4 stops.

**Comment by kylearmington** [comment]
is it possible to do like... walk: 0.01?

**Comment by LostDGod** [comment]
@kylearmington yes but the bot only scans for lured pokes upon reaching a lured pokestop and only reaches it when its actually on it.

**Comment by gregtampa** [comment]
use a better config to change these settings. this is not a bug.
