### ISSUE TITLE
[BUG] Lots of empty lines in console

### ISSUE THREAD

**Issue by xorinzor** [PokemonGoF/PokemonGo-Bot#1657]
Don't know why this is happening, but it is.

![untitled](https://cloud.githubusercontent.com/assets/4212335/17254158/dc73217a-55b3-11e6-9dc1-32e5ed349256.png)

### Other Information
OS: Win 10 x64
Git Commit: be9e7bb79de33a7d177014184c510b2c60513be8

**Comment by wsmigielski** [comment]
Also seeing this on Linux Ubuntu 16.04

**Comment by 1cu** [comment]
See #1644 

Seems to be intended :-1: 

Edit line line 87 in file "pokemongo_bot/__init__.py" and remove the complete line `logger.log('')` and the empty lines are gone.

**Comment by xorinzor** [comment]
That should be implemented as a debug option, not by default

**Comment by xorinzor** [comment]
It seems to be fixed in the dev branch now, so I'm closing this.
