### ISSUE TITLE
IndexError: list index out of range. 

### ISSUE THREAD

**Issue by Keizel** [PokemonGoF/PokemonGo-Bot#1665]
### Expected Behavior
There aren't bugs.

### Actual Behavior
The Bot is stopped randomly.

### Steps to Reproduce
I only execute the bot and this happen.
![the bug](https://cloud.githubusercontent.com/assets/15636441/17256504/b6502748-55b5-11e6-9951-14ca8ceb2793.png)

### Other Information
OS: windows 8
Git Commit: the lastest dev commit.

**Comment by xSidewinderx** [comment]
Same issue here.
OS. Ubuntu server && Ubuntu 14.04
Dev build

**Comment by nmanpkr** [comment]
Same here after like an hour and a half runtime. On Ubuntu. I think it happens when the bot tries to index a pokemon spawned by a lure. Im not positive though. Possibly adding a lured pokemon pushes the index without considering its dimensions?

**Comment by nmanpkr** [comment]
Possible solution for now?

try:
  Line 53
except:
  pass

**Comment by xSidewinderx** [comment]
@nmanpkr which file?

**Comment by Keizel** [comment]
The bug seems have relation with the location; when I changed that, the problem looks be fixed.

**Comment by nmanpkr** [comment]
Your gps location in config? I think it happens when there is a lure around. Is this resolved in the latest dev?

**Comment by nmanpkr** [comment]
if len(forts) == 0:
            return False

        fort = forts[0]

This in the latest dev fixes this.
