### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by toryxxxx** [PokemonGoF/PokemonGo-Bot#1668]
Traceback (most recent call last):
  File "pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot
  File "/Users/Tory/Pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 14, in <module>
    from pgoapi.utilities import f2i, get_cell_ids
ImportError: cannot import name get_cell_ids

**Comment by samjack** [comment]
did you try `pip install -r requirements.txt`

**Comment by toryxxxx** [comment]
Yes,of couse

**Comment by samjack** [comment]
try `pip uninstall pgoapi` after it `pip install -r requirements.txt`

**Comment by toryxxxx** [comment]
success ,thx
