### ISSUE TITLE
Show Pokestop names again or add an option to do so please

### ISSUE THREAD

**Issue by sgitkene** [PokemonGoF/PokemonGo-Bot#1675]
### Expected Behavior
When arriving at a pokestop, display its name.

### Actual Behavior
Does only say "arrived at pokestop. Spinning..."

### Steps to Reproduce
Have bot set to spin forts, walk in location where there are forts.

### Other Information
OS: Archlinux
Git Commit: b91ec50de8996942ffd901c0c135ea5734ba5920

**Comment by Adastras** [comment]
Looks like PR #1671 is addressing this.
