### ISSUE TITLE
[Suggestion] use a maximum distance radius instead of cells

### ISSUE THREAD

**Issue by A7F** [PokemonGoF/PokemonGo-Bot#1676]
Just because it's way more intuitive (in my opinion) than using map cells; starting from your position you can set a maximum radius (in meters) and the pg doesn't explore outside the circle.
Don't know wether is this possible to do or not... i would help but I don't know how to python.
It could also be useful for a kind of "lucky egg burst", if you know there are a lot of pokestops somewhere, you can set a radius to farm inside that circle

**Comment by vkamathb** [comment]
+1 for this. 

If say I need to stay within a certain area that are farms, I dont want the bot to go outside of that boundary. Keep capturing all the required ones inside the boundary (just like what we do if we go to a Charmander farm or a Dratini Farm... stay inside the farm boundary)

**Comment by douglascamata** [comment]
The `max_steps` key is there to configure the radius of the farm. Just change its value and check the size of the spiral.
