### ISSUE TITLE
[suggestion] Rename pokémon with IV-value

### ISSUE THREAD

**Issue by groveld** [PokemonGoF/PokemonGo-Bot#1679]
Is it possible to auto rename Pokémon to contain their IV values in their name?
Like Rattata_15-7-13 or something like that?
It would give you some nice feedback if you pick the game back up to see which Pokémon to evolve after a night of candy farming ;)

**Comment by asnelzin** [comment]
Like it.

Can make a PR.

**Comment by vkamathb** [comment]
+1 for this. 
Makes sense and easy to recognize.

**Comment by groveld** [comment]
I've seen that NecroBot uses this too, but has it notated as a percentage (0-100).
I don't know if this is the better notation, but merely an example.

**Comment by douglascamata** [comment]
Big names are not allowed.

**Comment by asnelzin** [comment]
@douglascamata you are correct. There is a max limit of 12 characters in a nickname, but you can use something like: `45, 12/12/12`

**Comment by VictorChen** [comment]
could we keep the original name but just append the IV next to it? eg: `Zubat (85)`

**Comment by asnelzin** [comment]
@VictorChen with some names (e.g. «Hitmonchan») it will be more than 12 characters.

**Comment by VictorChen** [comment]
could we truncate the name (if it's too long) and then append the IV?

eg: `Hitmonc (85)`

**Comment by TianCNCA** [comment]
We don't need to keep the original name as they're useless information.

**Comment by asnelzin** [comment]
We can make "renaming_format" setting in config to manually set this.

**Comment by groveld** [comment]
@TianCNCA True... But is still looks nice :)
we can even drop the special chars, so it looks like "Hitmoncha 85"

**Comment by BobbyWibowo** [comment]
Please make this optional (changeable from config file, probably). I'd like to monitor the IV from OpenPoGoWeb and keep the Pokemon's original name instead.

**Comment by VictorChen** [comment]
keeping the original name will allow sorting by name to work and make it easier to go back to the original name (by removing the iv)

**Comment by MatthewARoy** [comment]
Ah thanks Bobby. Is there currently a way to view the IV's after they've been caught, as per your comment?

**Comment by MatthewARoy** [comment]
Or, as a side option, automatically star any pokemon with IV's over X. Easy to sort through then.

**Comment by BobbyWibowo** [comment]
I monitor the bots with the web client. In the Pokemon listing, you can already see each Pokemon's IV there. If I want to evolve some Pokemon manually, I will just keep the web client open, temporarily turn off the bot, then open the app from my phone. After that, it's just as simple as finding the same Pokemon with the same CP and/or HP (highly unlikely to find duplicate anyway).
And if I don't feel like evolving manually, well, I had already set my bots to always evolve all Pokemon with CP above 500.

**Comment by johnw424** [comment]
There is already a sort by Pokemon name option in the app.
+1 for the simplest solution: rename Pokemon to IV - Str,Def,Stam (i.e. 100-15,15,15)

**Comment by asnelzin** [comment]
@johnw424 +1. There is a sort by id too, so it's safe to use the simplest solution.

Do we need to rename all existing pokemons on the start or only captured ones?

**Comment by VictorChen** [comment]
Sort by pokemon name isn't going to work if you rename it to like 100-15,15,15. If I want to search for the highest iv psyduck for example, I could sort my pokemons by name, and then look for psyduck, much easier.

**Comment by groveld** [comment]
Just make it 2 variables, one for the name of the Pokémon and one for the IV value and make a config option. if you tell the code to keep it to a max of 12 chars, then you can do everything you want. ex. `{0}` would be `Hitmonchan` and `{1}` would be `85`, so you could do something like `{0}_{1}` which would look something like `Hitmoncha_85`.
This way you keep the config at `{0}` so it doesn't get renamed, or `{1}` for the simplists ;)

**Comment by TianCNCA** [comment]
I have been playing with the api's nickname_pokemon call but has no success, anyone know why?

**Comment by johnw424** [comment]
@VictorChen What I mean is the sort by Pokemon ID. Even if you change the name of your Pokemon's to something like "100-15,15,15", you can still see all of your Psyducks together by using sort by Pokemon ID. That way, you can compare all of your Psyducks and avoid having a name string that is too long.

**Comment by VictorChen** [comment]
@johnw424 Yes you can sort by ID, but it's still hard to find `Psyducks` for example (how far to scroll?) If it was sorted by name, you can easily determine whether or not you've scrolled too far

**Comment by reddivision** [comment]
implemented in #1850

**Comment by reddivision** [comment]
See the [Configuration Files wiki page](https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files) (specifically [the Pokemon Nicknaming section](https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files#pokemon-nicknaming)) for usage information
