### ISSUE TITLE
[Suggestion] Better Walking Dynamics

### ISSUE THREAD

**Issue by infamousmax** [PokemonGoF/PokemonGo-Bot#168]
Ninatic are clearly aware of the API abuse and will start putting in precautions, I suggest a more human walking algorithm for a more realistic log server side to ensure any trawler they have will not pick up obvious bots.

Additions:
Variable-Speed = Simulate walking and running, we all do it, especially when a popular pokemon has been spotted. Perhaps a default walking speed of 2 then a run frequency of X, so during the walk it will make the player run X times during the duration.

Natural Movement = Using pokestops as the bases for walking construct a route based on the amount of pokestops near location. Then map a route which efficiently walks to all those, then during the walk search for pokemon every X steps if there is a pokemon then have the player move to that location capture then move back to the route.
*If the player can use google walk navigation then perfect.

Stationary Time = If area has >= X pokemon then stay in area and catch pokemon for Y then move to next location on route.

I think it is important to note that some functions should be locked, when walking is fully implemented and a proven anti-softban method then teleportation only risks the bot requiring better walking algorithms to prevent this. It's great to many features, but is the goal a complete bot application or a stable reliable one?

**Comment by fsegouin** [comment]
There is a problem here, since the bot is scanning an area first and then walking. It can takes up to XX mins and the bot can't catch he pokemon because its reset counter will be 0 by the time you get there.

**Comment by ironbishop** [comment]
You could just compute how much time you need to slowly walk there (you already know speed and distance), if walk time is less than reset counter... gotcha!

**Comment by daemonfire300** [comment]
Just to add this as a suggestion, I might contribute a seperate Class that simulates this: Humans dont always walk straight, this might be possible in park areas where there is grass, but usually you follow a concrete path or road, I mean GPS is not very accurate, but when you look at the pattern the bot is currently using, it's basically all straight lines with no noise. You basically have to compute the route, (linear function in interval [a,b]) and then distort it with noise so that the server cant simply check if your route is a straight line.

**Comment by tvb** [comment]
I agree with this suggestion. The current walking pattern is going to get us banned 😞 

<img width="504" alt="screen shot 2016-07-29 at 09 47 03" src="https://cloud.githubusercontent.com/assets/1263414/17241362/79c1bde4-5571-11e6-8b5a-dcd673792e38.png">

**Comment by CapCap** [comment]
This is actively being worked on
