### ISSUE TITLE
Bot crosses rivers

### ISSUE THREAD

**Issue by cth90** [PokemonGoF/PokemonGo-Bot#1681]
### Expected Behavior
Stick to viable walking paths (such as bridges, etc).

### Actual Behavior
Bot crosses rivers.

### Steps to Reproduce
Put bot near a river with a pokestop on the other side.

### Other Information
OS: Ubuntu
Git Commit: dev

**Comment by josephmcox** [comment]
People swim...

**Comment by cth90** [comment]
Sure, but the bot ignored available bridges near where it crossed. With all the effort going into making the bot walk in a non-suspicious manner, I think it would be smart to make it not randomly cross rivers (especially at walking speeds).

**Comment by vkamathb** [comment]
I think this would break the logic where there is a park. Inside a park, anyone can walk anywhere on the grass and not strictly to the pathway defined. So I would not want to change the existing logic to walk anywhere. (to add to this, if walking over building seems odd, then it can be thought as walking through the building). 
My opinion is no need to fix the current logic.

**Comment by Adastras** [comment]
This would require intelligent routing of some sort. Currently I believe it just picks a nearby stop and moves to it, so if the nearest one happens to be across a river it's going to walk on water. If it tied into Google Maps for pathing between a start and end point and followed the points in the path, it would look like normal walking around.

**Comment by MZorzy** [comment]
it will be usefull to add a N "random" shift to path.
so with N=0 bot will walk  regular, but with N>0 every step will be different (long,short,bit left or right)

**Comment by d0t1q** [comment]
The Fact that pokemon can be caught in the water/parks/buildings means that niantic is not confirming that the player is following paths, making this pointless.

**Comment by mrseeker** [comment]
Niantic does not confirm that players actually walk on water (ingress bots do violate this frequently) but only verifies that the route the player takes looks legitimate and is not straight from A to B. So, to quote milk inc:
>Split the ocean, cross the sea
>Walk on water if you believe

**Comment by leadboots5** [comment]
sounds like a request for google maps pathing integration

**Comment by demgod** [comment]
Besides you starting to walk across the ocean, they won't be able to tell if you crossed a river or you crossed a bridge that google maps just doesn't have on it yet. Since Google Maps doesn't have perfect information it would be stupid for them to start enforcing bans only you crossing bodies of water.

**Comment by MrCarlosJr** [comment]
If Selectabe maximum radius walk?

**Comment by larssy1** [comment]
Also, does the bot not use Google Maps? I know for a fact that my hometown is outdated by years on Google Maps, there aren't any rivers where they used to be :)
