### ISSUE TITLE
Wrong GeoLocation on master after installing dev

### ISSUE THREAD

**Issue by alfonzo1** [PokemonGoF/PokemonGo-Bot#1684]
I've download dev to different folder and get it running. When started master geo location is wrong. Config file seems to be fine:
cat config.json | grep "location"
    "location": "52.233207, 21.004425",
    "location_cache": true,

### Actual Behavior
[2016-07-29 12:57:56] [x] Starting PokemonGo Bot....
[2016-07-29 12:57:56] [#] Scanning area for objects (1 / 49)
[2016-07-29 12:57:56] [#] Walking from (2.57e-322, 1.04e-322) to (52.233207, 21.004425) for approx. 1459498.00 seconds

### Steps to Reproduce
Install dev in different directory.
Run master script (in diff directory).

### Other Information
OS: Debian 8
Git Commit: c7ab5b03cb93b5393bebbc383545a50e8519e57a

**Comment by Philipp59** [comment]
"location_cache": true,

**Comment by alfonzo1** [comment]
Changed to false in config. I don't have any location files i data folder.

ls -aF data/
./  ../  items.json  pokemon.json

Didn't help. :(

**Comment by Philipp59** [comment]
maybe its related to the gmapkey ? did u use the same key on dev ? 
Did you run the web module on both maybe it comes from that ?

**Comment by alfonzo1** [comment]
I used diffrent accounts for master and dev so it shouldn't be the problem.

**Comment by demgod** [comment]
Different game accounts or different Google Map API keys?

**Comment by alfonzo1** [comment]
Both :) Different account and different Gmap API.

**Comment by DayBr3ak** [comment]
if you didn't use a virtualenv and ran pip install -r requirements.txt it is probably why it doesn't work. Your master bot is using new python modules from dev bot

**Comment by alfonzo1** [comment]
Got it! Is it sefe tu use one Gmap API for few accounts?

**Comment by demgod** [comment]
Yes, the Google Map API is just used on your end, it isn't sent to the server.

**Comment by alfonzo1** [comment]
Philipp & Demgod - thank you for your time and help!
