### ISSUE TITLE
Not catching lured pokemon

### ISSUE THREAD

**Issue by OVO647** [PokemonGoF/PokemonGo-Bot#1685]
Latest dev version. Does the bot differentiate between lured pokemon and wild pokemon? It tells me that the fort is lured but doesn't say which pokemon are a result of the lure.

**Comment by martijnvandijke** [comment]
Why would you need this information ? I don't think the bot can distinguish between them

**Comment by douglascamata** [comment]
@OVO647 the pokemon it finds and capture right after that is the lured one.
