### ISSUE TITLE
what am I doing wrong?

### ISSUE THREAD

**Issue by 13werwolf13** [PokemonGoF/PokemonGo-Bot#1689]
everything according to instructions, but
![screenshot_20160730_004828](https://cloud.githubusercontent.com/assets/3271641/17259919/7a68776e-55ef-11e6-8627-ae3d6493cd4e.png)
what am I doing wrong?

**Comment by Kafkamorph** [comment]
source bin/activate

**Comment by 13werwolf13** [comment]
@Kafkamorph 
repeated from scratch was the sad result of the new
![screenshot_20160730_010134](https://cloud.githubusercontent.com/assets/3271641/17260259/3a82dba6-55f1-11e6-8241-608db3c16f38.png)

**Comment by Kafkamorph** [comment]
That output really tells a lot:
- you need to upgrade pip - follow what is shown
- python libraries seem to not be in the right place or not installed - did you do a pip install -r requirements.txt?

**Comment by 13werwolf13** [comment]
@Kafkamorph

**Comment by 13werwolf13** [comment]
@Kafkamorph An error appeared on this

**Comment by 13werwolf13** [comment]
@Kafkamorph I tried to python3 instead python2. as a result of all the assembled correctly but does not start
![screenshot_20160730_105255](https://cloud.githubusercontent.com/assets/3271641/17268167/c1ab26b8-5643-11e6-971b-91bccd84831a.png)

**Comment by 13werwolf13** [comment]
![screenshot_20160730_151547](https://cloud.githubusercontent.com/assets/3271641/17269383/7dbdfbea-5668-11e6-81f7-7aa691f614bb.png)
![screenshot_20160730_151551](https://cloud.githubusercontent.com/assets/3271641/17269382/7db7d3b4-5668-11e6-9b6e-3dda72252d19.png)

**Comment by 13werwolf13** [comment]
just install python-dev
