### ISSUE TITLE
Bot keeps looping on the same path

### ISSUE THREAD

**Issue by Floriferous** [PokemonGoF/PokemonGo-Bot#1690]
### Expected Behaviour
Bot walks along a seemingly random path to avoid getting caught and also go to more diverse areas from its starting location.

### Actual Behaviour
Currently the bot often finds itself stuck in a loop between 4-6 pokestops and repeats it over and over again.
Should mention that I have walk speed set to 14 in these trials:
http://imgur.com/a/mRZEV

### Steps to Reproduce
Put bot in a dense area with a lot of pokestops.

### Other Information
OS: OS X
Git Commit: aff8e76fdeef738707af23c9fe0fb33336597c12

**Comment by vanrzuf** [comment]
![screenshot_20160729-205412](https://cloud.githubusercontent.com/assets/18649425/17260115/e5b7d3b4-55ce-11e6-9d29-d8473b2733a3.png)

**Comment by wilsonyqm** [comment]
I have met the same problem, but it seems like some people would like to have the Bot go in a loop

**Comment by wilsonyqm** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/pull/1590 Fixed here
