### ISSUE TITLE
Can't just stay at one place

### ISSUE THREAD

**Issue by m0r0n** [PokemonGoF/PokemonGo-Bot#1691]
### Expected Behavior
When changing walk speed to 0 I expected to stay at the same pokestop and just collect everything, that spawns there. As currently eggs are not supported I would like to stay at one place, where many lock modules are active.

### Actual Behavior
It lures all pokestops and then ends the tool with this message:
RuntimeError: Stopped at Pokestop and did not find experience, items or information about the stop cooldown. You are probably softbanned. Try to play on your phone, if pokemons always ran away and you find nothing in PokeStops you are indeed softbanned. Please try again in a few hours.

### Steps to Reproduce
This config:
{
    "auth_service": "google",
    "username": "user@gmail.com",
    "password": "pass",
    "location": "someloc",
    "gmapkey": "key",
    "mode": "all",
    "debug": false,
    "walk": 0,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104",
    "evolve_all": "all"
}

### Other Information
OS: Debian 8.5 
Linux de 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux

Git Commit: ec2b7add95da6bc580035d8d4c472c1d41e439a6

**Comment by TheRealJoeSmoe** [comment]
Try adding 

`"max_steps": 0`

**Comment by m0r0n** [comment]
In that case it is just stuck at

`[2016-07-29 21:13:23] [x] Starting PokemonGo Bot....`

**Comment by larssy1** [comment]
Aside that it might be a bug, I'd like to make you aware that egging is supported on the 'dev' branch :)

**Comment by douglascamata** [comment]
This is possible now with the custom task list feature.

**Comment by CoderFX** [comment]
@douglascamata please elaborate or give examples

**Comment by douglascamata** [comment]
@CoderFX I'm very busy, sorry. But read the wiki and you will understand by looking how we manage configurations right now.
