### ISSUE TITLE
Keep at least one of each type regardless of release config

### ISSUE THREAD

**Issue by chris-tipton** [PokemonGoF/PokemonGo-Bot#1694]
Until recently, the bot would default to keep at least one of each type of pokemon (highest CP), even if it otherwise would have been released based on your config.

Is there a way I can still set up my release config to do this? I'd like to keep the highest CP pokemon of each type only if I have no pokemon of that type which meet my other conditions.

**Comment by leadboots5** [comment]
You should read the wiki:
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files

**Comment by chris-tipton** [comment]
Thanks.

I have read through the wiki and I don't believe the configuration I am asking about is addressed.

**Comment by leadboots5** [comment]
Keep the strongest pokemon configuration (dev branch)

You can set "release": {"Pidgey": {"keep_best_cp": 1}} or "release": {"any": {"keep_best_iv": 1}}.

In that case after each capture bot will check that do you have a new Pokémon or not.

If you don't have it, it will keep it (no matter was it strong or weak Pokémon).

If you already have it, it will keep a stronger version and will transfer the a weaker one.

"release": {"any": {"keep_best_cp": 2}}, "release": {"any": {"keep_best_cp": 10}} - can be any number.

You'll have to provide some additional information about what this doesn't accomplish for you.

**Comment by chris-tipton** [comment]
Sure!

I have my bot set to farm for all pokemon above a certain IV level (0.85). This works just fine.

Until recently, the bot would ALSO keep at least 1 pokemon of each type, even if they were not above 0.85 IV.

For example, if it catches a Blastoise with IV 0.5, the bot keeps it if you do not have another Blastoise. 

I would like to restore that functionality. I want to continue farming for pokemon with high IV, but I don't want to throw away a pokemon I don't have yet because of that condition.

Does that make sense?

**Comment by leadboots5** [comment]
Does this not work?

"release": {"any": {"keep_best_iv": 1}}

**Comment by leadboots5** [comment]
You could try these, they may or may not work. Sorry I can't be of my help.
"any": {"keep_best_iv": 1, "release_below_iv": .85 }
"any": {"keep_best_iv": 1, "release_below_iv": .85, "logic": "and" }

**Comment by BlackPornActor** [comment]
I just created an account to say that none of those lines work for our purpose.  I want to keep 1 Pokemon of each type AND everything else with CP > 1000.

**Comment by Mooseymax** [comment]
http://pastebin.com/gxSTmRcF

This is mine, I hope it helps.

It isn't exactly the highest 1 of each (because of pidgy and weedle) but mostly.
