### ISSUE TITLE
New to this and cant workout what's wrong?

### ISSUE THREAD

**Issue by PeteZilla** [PokemonGoF/PokemonGo-Bot#1695]
I goto start pokecli.py and this comes up, **** represents my name, i am working on a mac

Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/Users/********/Desktop/PokemonGo-Bot-master/pokemongo_bot/__init__.py", line 4, in <module>
    import googlemaps
ImportError: No module named googlemaps

**Comment by sgitkene** [comment]
A step in the instructions might have been skipped.

try "pip install -r requirements.txt"

**Comment by PeteZilla** [comment]
thanks man! got it working, im very new to this but getting the hang of it, any idea how to stop it exchanging all my pokemon for candy?

**Comment by sgitkene** [comment]
ctrl c
I sure hope you are not using your main account to try out a bot.
This might get you banned, or as you see now, you might get unexpected behaviour.

**Comment by PeteZilla** [comment]
perfect thankyou dude and no, using a secondary test account, thank you for the help!
