### ISSUE TITLE
[suggestion] Use great balls when encounter higher CP pokemons

### ISSUE THREAD

**Issue by harsh1412** [PokemonGoF/PokemonGo-Bot#17]
Hey so i just had an idea, Why don't you make a code that uses great balls when bot encounter higher set amount of CP of a pokemon lets say bot saw a pokemon of CP 1000 let the bot through a normal ball first. if fails then try a great ball if it again fails then through a raspberry and a greatball until its captured. :)

**Comment by tstumm** [comment]
The Pokemon Go app itself shows the "hardness" of a pokemon by a pokeball as colors. Maybe we can adapt this somehow?

**Comment by tstumm** [comment]
Actually encouters contain the following information:

e.g.
"capture_probability": {
        "capture_probability": [
          0.320090651512146,
          0.43936973810195923,
          0.5377233028411865
        ],
        "pokeball_type": [
          1,
          2,
          3
        ]
      }

So we actually have a probability for pokeballs, superballs and hyperballs
If the capture_probability is very low we should switch to better balls if we have any.

**Comment by tstumm** [comment]
Basic algorithm:
Look at pokeball probability. Check if higher than THRESHOLD.
If it is and has enough pokeballs: Use pokeball
If not: Repeat for great ball, hyperball, etc.

**Comment by tstumm** [comment]
Will work on that tomorrow

**Comment by surfaace** [comment]
merged in #618
