### ISSUE TITLE
I am not sure what the problem is!

### ISSUE THREAD

**Issue by JellyFishes** [PokemonGoF/PokemonGo-Bot#1701]
I type in source bin/activate and it says source is not an internal or external command!! :(

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by vanrzuf** [comment]
Probably you don't have virtualenv. its not very important

**Comment by leadboots5** [comment]
Windows 10 doesn't recognize the source command so it won't work on Windows.

What I've had to do the couple times I have ran it on windows is go into the lib/scripts or scripts/lib folder(can't remember which it is) and just type in 'activate' to run it

**Comment by larssy1** [comment]
There isn't a lib folder, what you have to do:

Open a console window from within your PokemonGo root folder.
Type: Scripts\activate.bat
