### ISSUE TITLE
Keep best IV/PC

### ISSUE THREAD

**Issue by TLuigi003** [PokemonGoF/PokemonGo-Bot#1708]
I'm trying to use that feature but I'm not sure how to make it work.
My current release_config.json
`{
   "release": {
	"any": {"keep_best_cp": 1, "keep_best_iv": 1}
	},
	
    "exceptions": {
        "always_capture": [
            "Arcanine",
            "Lapras",
            "Dragonite",
            "Snorlax",
            "Blastoise",
            "Moltres",
            "Articuno",
            "Zapdos",
            "Mew",
            "Mewtwo"
        ]
    }
}
`

However It throws me this error(Traceback snipped):
`  File "C:\Users\Usuario\GoBot\test\PokemonGo-Bot\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 280, in _get_release_config_for
    release_config = self.config.release_config['any']
KeyError: 'any'
`

I hope you can help me
Thanks in advance.

**Comment by larssy1** [comment]
I'm not familiar with the feature myself, but my best bet would be this:

```
{
    "any": {
        "keep_best_cp": 1,
        "keep_best_iv": 1
    },

    "exceptions": {
        "always_capture": [
            "Arcanine",
            "Lapras",
            "Dragonite",
            "Snorlax",
            "Blastoise",
            "Moltres",
            "Articuno",
            "Zapdos",
            "Mew",
            "Mewtwo"
        ]
    }
}
```

**Comment by TLuigi003** [comment]
@larssy1 It could be, however, It seems to catch ALL the Pokemon:
`[2016-07-29 22:58:50] [x] Captured Rattata! [CP 111] [IV 0.56]
[2016-07-29 22:58:50] [x] Captured Rattata! [CP 111]
[2016-07-29 22:59:25] [#] Something rustles nearby!
[2016-07-29 22:59:25] [#] A Wild Rattata appeared! [CP 81] [Potential 0.51]
[2016-07-29 22:59:25] [#] IV [Stamina/Attack/Defense] = [13/4/6]
[2016-07-29 22:59:28] [x] Using Pokeball (chance: 62.29%)... (94 left!)
[2016-07-29 22:59:28] [x] Captured Rattata! [CP 81] [IV 0.51]
[2016-07-29 22:59:29] [x] Captured Rattata! [CP 81]
`
It should have discarded the second Rattata since It has lower IV and lower CP than the first one
Thanks~

**Comment by leadboots5** [comment]
I think you need logic in for it to handle 2 parameters in a single statement like that. That may not work in case next I would try having a statement for each.

**Comment by Foulwerp** [comment]
```
[14:18:16] Something rustles nearby!
[14:18:16] A Wild Ponyta appeared! [CP 325] [Potential 0.71]
[14:18:16] IV [Stamina/Attack/Defense] = [11/15/6]
[14:18:19] Using Pokeball (chance: 42.64%)... (51 left!)
[14:18:20] Captured Ponyta! [CP 325] [Potential 0.71] [11/15/6]
[14:18:25] Moving towards Empty Space, 0.06km left
[14:18:30] Keep 2 best Ponyta, based on cp and iv
[14:18:30] Ponyta [CP 843] [Potential 0.84]
[14:18:30] Ponyta [CP 962] [Potential 0.78]
[14:18:30] Transferring 1 pokemon
[14:18:30] Exchanging Ponyta [CP 325] [Potential 0.71] for candy!
```

Works for me. Caught Ponyta that was not higher than highest CP or IV and then released it.

**Comment by TLuigi003** [comment]
@Foulwerp I don't know why It isn't working for me, I used "git pull" to update the bot and I used exactly the same release config as you:
`{
"catch":{
      "any":{
         "always_catch":true
      }
   },
   "release":{
      "any":{
         "keep_best_cp":1,
         "keep_best_iv":1
      }
   }
}`

But It throw me this error:
`File "C:\Users\Usuario\GoBot\test\PokemonGo-Bot\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 280, in _get_release_config_for
    release_config = self.config.release_config['any']
KeyError: 'any'
`
Regards~

**Comment by leadboots5** [comment]
@TLuigi003 I'm guessing you're on the master branch?

**Comment by TLuigi003** [comment]
@leadboots5 Yes I am.
Does This feature work only on the dev branch? Or any other branch?
Thanks~

**Comment by leadboots5** [comment]
I believe the keep_best is only in dev

**Comment by TLuigi003** [comment]
@leadboots5 After switching to dev brach the feature works perfectly
Thanks to all of you~

**Comment by ftykazaf** [comment]
May i know how to switch from master branch to dev branch??
Because I am suffering from this now.
Exactly what you experienced

**Comment by TLuigi003** [comment]
If I remember properly "git checkout -b dev" allows you to switch between branches
Then perform a "git pull" so you can update the bot and "pip install -r requirements.txt" to update the dependencies

I hope that works
Regards~
