### ISSUE TITLE
Launch a bot with crontab or without SSH on a headless server

### ISSUE THREAD

**Issue by Cholaloula** [PokemonGoF/PokemonGo-Bot#1712]
### Expected Behavior

When I try to launch @reboot the bot with crontab or if I launch it with SSH and close the session the bot stops working.
Is there any way to make it work this way?
The idea would be to make it work an a headless raspberry pi server.

### Steps to Reproduce
SSHing into the server, launching the bort and close the session,
or put in crontab something like :
@reboot source path/to/thebot/bin/activate && cd  path/to/thebot && python pokecli.py

(I'm not a dev, so it may not be the best way to do it...)

### Other Information
OS: Debian_Jessie (Raspbian)
Git Commit: 3f1f8e321da1ee256659ef623730ee1efeb442d0

**Comment by asnelzin** [comment]
What exactly are you doing, when trying to run it?

Seems like it should be running in background when you restart your raspberry.
Additionally I would recommend you using something like supervisor for such purposes.

**Comment by DisasteR** [comment]
simple way is to launch it on a screen or tmux multiplexer

**Comment by Cholaloula** [comment]
Thank you both!!!
I'm using screen that I just discovered and...it's wonderful! 
And for supervisor I see it could be right the perfect tool so this issue can be closed!
Thank you!!!
