### ISSUE TITLE
Map not working

### ISSUE THREAD

**Issue by SimoneCattozzi** [PokemonGoF/PokemonGo-Bot#1713]
### Expected Behavior
Maps pan to position or showing gym icon or pokemon images

### Actual Behavior
Maps shows up notification of pokecli bot but doesn't shows any information on map

### Steps to Reproduce
start pokecli in folder OpenPoGoBot with "python pokecli.py -j config.json"
start web sever in folder OpenPoGoBot\web with "python -m SimpleHTTPServer"

### Other Information
OS:  Windows
Git Commit: f7bfffaaee76afeb2811a32ebd3eef6f4d034451

**Comment by BobbyWibowo** [comment]
Check the browser's console while viewing the map. That way you can monitor what went wrong with the map.

**Comment by LostDGod** [comment]
Have you placed your ID + google api key on the web\userdata.js.example file and renamed it for userdata.js ? I belive the console does not warn you if you are missing credencials.

**Comment by BobbyWibowo** [comment]
@LostDGod It should actually log an error message from Google Maps JS API regarding invalid API key.

**Comment by larssy1** [comment]
Tried myself, appears there is a 3 step installation in order here.

1. Rename userdata.js.example to userdata.js
2. Replace the keyword 'username' with the loginname of your account (can be identified with the file 'location-[SOMEUSERNAMEHERE].json'
3. Replace the googlemaps api key (I tried, and I couldn't use the same one i use for the bot itself, I had to create a new one with the link provided within that userdata.js file)

**Comment by BobbyWibowo** [comment]
@larssy1 You couldn't use the same API key as the bot used? That's strange. I could use the same one just fine here.

**Comment by larssy1** [comment]
Hmm, it said for me the api key wasn't activated, although it works fine for the bot.. but I fixed it, so not rlly a problem.. ^^ Only thing im wondering right now is.. 

The website supports more then one usernames, yet the bot itself does not and so does not register multiple locations, which is something i find weird :)

**Comment by BobbyWibowo** [comment]
I'm using 2 bots here (I actually didn't want to bother with another bot, but I was working on fixing a couple of things with the web viewer). I simply ran 2 instances of the bot. I made 2 batch files, each one using their own config file. No issue so far :hushed:

**Comment by larssy1** [comment]
Let's continue here @BobbyWibowo  https://github.com/PokemonGoF/PokemonGo-Bot/issues/1731

**Comment by SimoneCattozzi** [comment]
Hi, thanks for the troubleshooting hints.
I've placed the ID+Api key in userdata.js. In fact the maps shows up and it pops messages from pokecli process (ex. "+50XP", "A wild Rattata Appears"..) but it doesn't pans on location or visualize pokestops images..

chrome console give me error messages like
main.js:680 Uncaught TypeError: Cannot read property 'length' of undefined
main.js:680 Uncaught TypeError: Cannot read property 'length' of undefinedtrainerFunc @ main.js:680(anonymous function) @ main.js:804i @ jquery.min.js:2fireWith @ jquery.min.js:2y @ jquery.min.js:4c @ jquery.min.js:4
main.js:426 Uncaught TypeError: Cannot read property 'pokemon_family' of undefinedfilter @ main.js:426invSuccess @ main.js:456(anonymous function) @ main.js:804i @ jquery.min.js:2fireWith @ jquery.min.js:2y @ jquery.min.js:4c @ jquery.min.js:4
4main.js:680 Uncaught TypeError: Cannot read property 'length' of undefinedtrainerFunc @ main.js:680(anonymous function) @ main.js:804i @ jquery.min.js:2fireWith @ jquery.min.js:2y @ jquery.min.js:4c @ jquery.min.js:4
main.js:426 Uncaught TypeError: Cannot read property 'pokemon_family' of undefinedfilter @ main.js:426invSuccess @ main.js:456(anonymous function) @ main.js:804i @ jquery.min.js:2fireWith @ jquery.min.js:2y @ jquery.min.js:4c @ jquery.min.js:4
4main.js:680 Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by SimoneCattozzi** [comment]
![cattura](https://cloud.githubusercontent.com/assets/19191117/17268587/866f732a-562e-11e6-9116-5c840c419f73.PNG)

**Comment by SimoneCattozzi** [comment]
Today i've moved all on debian OS (Raspberry) and works perfectly!
Thanks

**Comment by Rlewisrlou666** [comment]
I have both PokemonBot and the map working but the map isn't following me.
Its showing pokemon in the area and pokestops/gyms but the pin is stuck on my actual location.
I must be missing something.
