### ISSUE TITLE
Print evolved stats

### ISSUE THREAD

**Issue by mjmadsen** [PokemonGoF/PokemonGo-Bot#1717]
### Expected Behavior
Print evolved stats after evolving a pokemon.

### Actual Behavior
Simply states it was evolved.

### Steps to Reproduce
Set to evolve pokemon after capture. 

Related to this, I would love to see all current items when we capture more of them, current EXP after EXP change, EXP gain from captures (including separate bonuses), current candies when transferring or after hatch (and add totals behind hatch info). Hatch count after hatch and distance to hatch. Distance walked to fort distance and distance travelled since last "moving towards fort..." line.

**Comment by groveld** [comment]
+1
I like to see some more feedback for distance, XP, eggs etc. also. not just after the script closes.
Maybe log all Pokémon with IV values, just like the "Captured <pokemon>!" message.
