### ISSUE TITLE
Refactor dev branch Evolve Logic

### ISSUE THREAD

**Issue by nburn42** [PokemonGoF/PokemonGo-Bot#1719]
As per discussion on #1649.

Current dev branch evolve worker should be refactored.

**Comment by accident12123** [comment]
Is this needed?   isn't https://github.com/klingan/PokemonGo-Bot/commit/ac3bd71d7f08b05c3a0914f3ebc5553b17b0f9c5 the fix for why it's walking slow?   I manually put in the change and it's going great.
