### ISSUE TITLE
[Dev Branch] Bot is not starting, no module socketIO-client, invalid command 'egg_info'

### ISSUE THREAD

**Issue by Agentos** [PokemonGoF/PokemonGo-Bot#1723]
### Expected Behavior

Bot should start working.

### Actual Behavior

Bot fails with error message:

  File "pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot
  File "/home/pi/Documents/Github/pokebotdev/pokemongo_bot/__init__.py", line 22, in <module>
    from pokemongo_bot.event_handlers import LoggingHandler
  File "/home/pi/Documents/Github/pokebotdev/pokemongo_bot/event_handlers/__init__.py", line 2, in <module>
    from socketio_handler import SocketIoHandler
  File "/home/pi/Documents/Github/pokebotdev/pokemongo_bot/event_handlers/socketio_handler.py", line 2, in <module>
    from socketIO_client import SocketIO
ImportError: No module named socketIO_client

When I try to install/update requirements with pip, the following error is coming up:

    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
      warnings.warn(msg)
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: invalid command 'egg_info'

### Steps to Reproduce

Update to latest commit (dev branch), run pip install / upgrade and/or try to start the bot.

### Other Information
OS: Linux (Debian, Raspberry Pi)
Git Commit: 100830618d192ad7d8c15d790a3d1a243ec66362

**Comment by mjmadsen** [comment]
Try "pip install -r requirements.txt --upgrade"

**Comment by Agentos** [comment]
I tried both ways, just the install and the upgrade... same error:

Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi (from -r requirements.txt (line 1))
  Skipping because already up-to-date.
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
      warnings.warn(msg)
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: invalid command 'egg_info'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/pi/Documents/Github/pokebotdev/src/pgoapi/

**Comment by Agentos** [comment]
Tried a clean install and this solved the issue. Strange...
