### ISSUE TITLE
protobuf 3

### ISSUE THREAD

**Issue by frossaren** [PokemonGoF/PokemonGo-Bot#1727]
### Expected Behavior
Bot would start working

### Actual Behavior
```
pi@serverpi:~/PokemonGo-Bot $ python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/__init__.py", line 13, in <module>
    from pgoapi import PGoApi
  File "/home/pi/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 17, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3
```

### Steps to Reproduce
install as guide says and run with python pokecli.py

### Other Information
OS: raspbian jessie

**Comment by xorinzor** [comment]
you did actually run `pip install -r requirements.txt` ?

**Comment by frossaren** [comment]
yes and i even tried doing it again but still same problem

**Comment by xorinzor** [comment]
hmm, in that case I'm guessing the package that's attempting to be installed is not available for the architecture that the raspberry pi uses.

But I have no knowledge about the packages that python (or this app for that matter) uses so I wouldn't be able to tell you what to do next.

My guess is you'll have to manually build and install the package.

**Comment by yehan77** [comment]
Okay, i had the same problem. What i did was type " pip install -r "
then i dragged the txt after -r and it installed perfectly

**Comment by frossaren** [comment]
how did you drag the txt? mine just pops back to the folder

**Comment by frossaren** [comment]
I reinstalled everything and got some other problems but they are not related to protobuf so i will make another thread for that

**Comment by qwer4790** [comment]
hi, I have the same issue and they tried to uninstall everything(include python itself), re-install, and everything fine now
