### ISSUE TITLE
Web supports multiple usernames, bot does not

### ISSUE THREAD

**Issue by larssy1** [PokemonGoF/PokemonGo-Bot#1731]
### Expected Behavior
Allow the bot to have 'multiple' instances with multiple 'usernames', after which the locations of the bots get writtin into the 'web' folder.

### Actual Behavior
Web appears to be supporting multiple bots, the bot itself does not.

### Steps to Reproduce
Inside the web folder only one location-username.json is written, however, the userdata.js has an array format for the usernames.

### Other Information
OS: Windows
Git Commit: dev

**Comment by BobbyWibowo** [comment]
You simply have to run 2 instances of the both. Each using their own config file.

**Comment by larssy1** [comment]
So, how did you accomplish that? What I did was pretty old school.. I copied the entire folder 4 times

**Comment by BobbyWibowo** [comment]
Just like you. I actually had made my own batch file which automatically restart the bot:
```
@echo off

:start
pokecli.py --config ./configs/config.1.json

echo Program was terminated at %Date% %Time% with error %ErrorLevel% >> run-self-managed.1.log
echo Press Ctrl-C if you don't want to restart automatically
ping -n 3 localhost

goto start
```
See the config name? I made 2 config files named config.1.json and config.2.json (both has different credentials). The batch files which contain codes that are roughly the same as the one I posted there were named run-self-managed.1.bat and run-self-managed.2.bat. Then I simply executed both. So yeah, I have 2 consoles running, each with their own config.

**Comment by larssy1** [comment]
Ya, that's exactly what I meant ^^ Thanks

**Comment by BobbyWibowo** [comment]
@larssy1 Your edit with the multiple config files thingy wasn't visible while I was posting that long ass reply, lmao

**Comment by larssy1** [comment]
Haha no worries, I fixed it, and tested it on the webserver, works perfectly ^__^
