### ISSUE TITLE
Add config option to append Pokemon IV onto Pokemon name

### ISSUE THREAD

**Issue by MatthewARoy** [PokemonGoF/PokemonGo-Bot#1734]
### Expected Behavior
After pokemon is caught, hatched, or evolved, if set to add IV (Either compact ".89" or full "15/13/12") it will append to the name of the pokemon. If there is not enough characters, delete characters from the pokemon name.

I feel lik this will be beneficial for sorting through your collections.
Alternatively, it could be a command to run that would label all of the pokemon you currently own.
### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by BobbyWibowo** [comment]
#1679 Duplicate
