### ISSUE TITLE
Not using great or excellent throw

### ISSUE THREAD

**Issue by pisuth** [PokemonGoF/PokemonGo-Bot#1737]
### Expected Behavior
Get 160xp - 210xp

### Actual Behavior
Only getting 110xp

### Steps to Reproduce
Run the bot using the lastest dev branch and did run pip upgrade the requirements

### Other Information
OS: Ubuntu 16
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Alino** [comment]
just a note: I think it should not ALWAYS throw excellent throws because it would become one of the indicators that you are using a bot, it should simuluate human behavior so the throws should be random.
