### ISSUE TITLE
Failed building Wheel for MarkupSafe (probably problem at my end)

### ISSUE THREAD

**Issue by inet-pwnZ** [PokemonGoF/PokemonGo-Bot#1738]
while pip2 install
it says 
building "markupsafe._speedups' extension
error: ERROR 2 couldn't find file

edit : i downloaded it manually and install it
setup.py install
gets me the same error even though it contains a file called 
_speedups.c

edit : i installed a older version of setuptools and flask
works now

### Other Information
OS: Win7
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Kassius509** [comment]
@inet-pwnZ how did you install the older version of setup tools
