### ISSUE TITLE
Error with requirements.txt

### ISSUE THREAD

**Issue by gartia** [PokemonGoF/PokemonGo-Bot#1740]
### Expected Behavior
So i was using the dev build fine just yesterday did a update and then it broke so i reinstalled completely and i'm getting this error now. Not sure what happened if its something i did or what

### Actual Behavior
http://pastebin.com/raw/bgRcG5QY
the debug: http://pastebin.com/raw/KNAnk6Ze
ends up erroring with greenlet

### Steps to Reproduce
git clone --recursive -b dev https://github.com/PokemonGoF/PokemonGo-Bot
cd PokemonGo-Bot
virtualenv .
source bin/activate
pip install -r requirements.txt

### Other Information
OS: Debian wheezy
Git Commit: 872dfa5eb948021b083bb19fa85749e8040cbf97

**Comment by larssy1** [comment]
what happens if you run the install.sh from the dev branch?

**Comment by gartia** [comment]
It said it was installed successfully, but when i tried to run.sh i get this

(PokemonGo-Bot)gartia@strife:~/pokemon/PokemonGo-Bot$ ./run.sh 
Traceback (most recent call last):
  File "pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot
  File "/home/gartia/pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 25, in <module>
    from pokemongo_bot.socketio_server.runner import SocketIoRunner
  File "/home/gartia/pokemon/PokemonGo-Bot/pokemongo_bot/socketio_server/runner.py", line 5, in <module>
    from eventlet import patcher, wsgi
  File "/home/gartia/pokemon/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/patcher.py", line 4, in <module>
    from eventlet.support import six
  File "/home/gartia/pokemon/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/support/__init__.py", line 4, in <module>
    from eventlet.support import greenlets, six
  File "/home/gartia/pokemon/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/support/greenlets.py", line 3, in <module>
    import greenlet
ImportError: No module named greenlet

**Comment by xSidewinderx** [comment]
pip install greenlet? Or try  
sudo apt-get install python-dev

**Comment by AndreAbdel27** [comment]
Am getting very similar results. It was working perfectly until yesterday afternoon EST. 

Already did:
-Git pull on both folders (dev/master)
-pip upgrade
-configure config.json and and release.json 
![untitled](https://cloud.githubusercontent.com/assets/13223242/17266844/4910a8f4-55b2-11e6-8678-9e2866ffaf65.png)

**Comment by LostDGod** [comment]
I'm not sure if you still need to use pip install _--upgrade_ requirements.txt but if you are not doing it you should try it out

**Comment by theebanka** [comment]
> sudo apt-get install python-dev

Worked for me! Then I just re-ran the "pip install requirements.txt" and I was all set

**Comment by AndreAbdel27** [comment]
@gitter-badger How do I install for windows 10?

**Comment by gartia** [comment]
Okay a fresh install of dev branch with python-dev and using ./install.sh fixxed it

**Comment by AndreAbdel27** [comment]
@gartia by doing that it help me login successfully. But, the bot gets stuck just after "Starting PokemonGo Bot" Servers are busy, failed to login

**Comment by gartia** [comment]
Well i think thats just exactly what it says @AndreAbdel27 they are busy maybe? I havn't had any issues with this anymore.

**Comment by AndreAbdel27** [comment]
@gartia I own a macbook and a Desktop PC and the weird thing is that on the PC doesnt work, but in Mac runs smoothly.
