### ISSUE TITLE
Unexpected 

### ISSUE THREAD

**Issue by MPNull** [PokemonGoF/PokemonGo-Bot#1742]
**Linux**
I've Cloned a dev branch to my Linux. I ran ./install.sh and after that I copied the config.json.example to same configs folder, but with a new name (config.json) then I started the bot by ./run.sh, but I get the error: "TypeError: __init__() got an unexpected keyword argument 'syntax'"

With master branch I got it ONCE to show some green console text, but it was first and probably last time. That's why I changed to dev. Is the guide missing something or am I missing something? I also tried installation as manually like the "Wiki > Installation" page says.

https://i.gyazo.com/84d3315622d39df58590078e568c8e45.png

**Comment by gregtampa** [comment]
come to slack chat #help and someone can help you
NOT A BUG
