### ISSUE TITLE
Release Pokemon Problem

### ISSUE THREAD

**Issue by ZgrK** [PokemonGoF/PokemonGo-Bot#1743]
My config is 

> "max_steps": 150,
    "catch_pokemon": true,
    "forts": {
      "spin": true,
      "avoid_circles": true,
      "max_circle_size": 50,
      "show_name": true
    },
    "websocket_server": false,
    "walk": 40,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
       "1": { "keep" : 50 },
     "2": { "keep" : 50 },
     "3": { "keep" : 50 },
     "101": { "keep" : 10 },
     "102": { "keep" : 25 },
     "103": { "keep" : 25 },
     "201": { "keep" : 25 },
     "701": { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "evolve_speed": 20,
    "evolve_cp_min": 300,
    "use_lucky_egg": false,
    "hatch_eggs": true,
    "longer_eggs_first": true,
    "evolve_captured": "NONE",
    "release_pokemon": true,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0.6, "logic": "or" },

      "// Legendary pokemons (Goes under S-Tier)": {},
      "Lapras": { "release_below_cp": 1041, "release_below_iv": 0.8, "logic": "and" },
      "Moltres": { "release_below_cp": 1132, "release_below_iv": 0.8, "logic": "and" },
      "Zapdos": { "release_below_cp": 1087, "release_below_iv": 0.8, "logic": "and" },
      "Articuno": { "release_below_cp": 1039, "release_below_iv": 0.8, "logic": "and" },

      "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
      "Mewtwo": { "release_below_cp": 1447, "release_below_iv": 0.8, "logic": "and"},
      "Dragonite": { "release_below_cp": 1221, "release_below_iv": 0.8, "logic": "and" },
      "Snorlax": { "release_below_cp": 1087, "release_below_iv": 0.8, "logic": "and" },
      "// Mew evolves to Mewtwo": {},
      "Mew": { "release_below_cp": 1152, "release_below_iv": 0.8, "logic": "and" },
      "Arcanine": { "release_below_cp": 1041, "release_below_iv": 0.8, "logic": "and" },
      "Vaporeon": { "release_below_cp": 984, "release_below_iv": 0.8, "logic": "and" },
      "Gyarados": { "release_below_cp": 938, "release_below_iv": 0.8, "logic": "and" },
      "Exeggutor": { "release_below_cp": 1032, "release_below_iv": 0.8, "logic": "and" },
      "Muk": { "release_below_cp": 909, "release_below_iv": 0.8, "logic": "and" },
      "Weezing": { "release_below_cp": 784, "release_below_iv": 0.8, "logic": "and" },
      "Flareon": { "release_below_cp": 924, "release_below_iv": 0.8, "logic": "and" },

      "// Growlithe evolves to Arcanine": {},
      "Growlithe": { "release_below_cp": 465, "release_below_iv": 0.8, "logic": "and" },
      "// Dragonair evolves to Dragonite": {},
      "Dragonair": { "release_below_cp": 609, "release_below_iv": 0.8, "logic": "and" },
      "// Grimer evolves to Muk": {},
      "Grimer": { "release_below_cp": 448, "release_below_iv": 0.8, "logic": "and" },
      "// Magikarp evolves to Gyarados": {},
      "Magikarp": { "release_below_cp": 91, "release_below_iv": 0.8, "logic": "and" },
      "// Exeggcute evolves to Exeggutor": {},
      "Exeggcute": { "release_below_cp": 384, "release_below_iv": 0.8, "logic": "and" },
      "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
      "Eevee": { "release_below_cp": 376, "release_below_iv": 0.8, "logic": "and" },

      "// A-Tier pokemons": {},
      "Slowbro": { "release_below_cp": 907, "release_below_iv": 0.8, "logic": "and" },
      "Victreebel": { "release_below_cp": 883, "release_below_iv": 0.8, "logic": "and" },
      "Machamp": { "release_below_cp": 907, "release_below_iv": 0.8, "logic": "and" },
      "Poliwrath": { "release_below_cp": 876, "release_below_iv": 0.8, "logic": "and" },
      "Clefable": { "release_below_cp": 837, "release_below_iv": 0.8, "logic": "and" },
      "Nidoking": { "release_below_cp": 864, "release_below_iv": 0.8, "logic": "and" },
      "Venusaur": { "release_below_cp": 902, "release_below_iv": 0.8, "logic": "and" },
      "Charizard": { "release_below_cp": 909, "release_below_iv": 0.8, "logic": "and" },
      "Golduck": { "release_below_cp": 832, "release_below_iv": 0.8, "logic": "and" },
      "Nidoqueen": { "release_below_cp": 868, "release_below_iv": 0.8, "logic": "and" },
      "Vileplume": { "release_below_cp": 871, "release_below_iv": 0.8, "logic": "and" },
      "Blastoise": { "release_below_cp": 888, "release_below_iv": 0.8, "logic": "and" },
      "Omastar":  { "release_below_cp": 780, "release_below_iv": 0.8, "logic": "and" },
      "Aerodactyl": { "release_below_cp": 756, "release_below_iv": 0.8, "logic": "and" },
      "Golem": { "release_below_cp": 804, "release_below_iv": 0.8, "logic": "and" },
      "Wigglytuff": { "release_below_cp": 760, "release_below_iv": 0.8, "logic": "and" },
      "Dewgong": { "release_below_cp": 748, "release_below_iv": 0.8, "logic": "and" },
      "Ninetales": { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
      "Magmar": { "release_below_cp": 792, "release_below_iv": 0.8, "logic": "and" },
      "Kabutops": { "release_below_cp": 744, "release_below_iv": 0.8, "logic": "and" },
      "Electabuzz": { "release_below_cp": 739, "release_below_iv": 0.8, "logic": "and" },
      "Starmie": { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
      "Jolteon": { "release_below_cp": 746, "release_below_iv": 0.8, "logic": "and" },
      "Rapidash": { "release_below_cp": 768, "release_below_iv": 0.8, "logic": "and" },
      "Pinsir": { "release_below_cp": 741, "release_below_iv": 0.8, "logic": "and" },
      "Scyther": { "release_below_cp": 724, "release_below_iv": 0.8, "logic": "and" },
      "Tentacruel": { "release_below_cp": 775, "release_below_iv": 0.8, "logic": "and" },
      "Gengar": { "release_below_cp": 724, "release_below_iv": 0.8, "logic": "and" },
      "Hypno": { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
      "Pidgeot": { "release_below_cp": 729, "release_below_iv": 0.8, "logic": "and" },
      "Rhydon": { "release_below_cp": 782, "release_below_iv": 0.8, "logic": "and" },
      "Seaking": { "release_below_cp": 712, "release_below_iv": 0.8, "logic": "and" },
      "Kangaskhan": { "release_below_cp": 712, "release_below_iv": 0.8, "logic": "and" },

      "// Koffing evolves to Weezing (A-Tier)": {},
      "Koffing": { "release_below_cp": 403, "release_below_iv": 0.8, "logic": "and" },

      "// Below is B-tier and lower pokemons": {},
      "Caterpie": { "release_below_cp": 156, "release_below_iv": 0.8, "logic": "and" },
      "Weedle": { "release_below_cp": 156, "release_below_iv": 0.8, "logic": "and" },
      "Diglett": { "release_below_cp": 158, "release_below_iv": 0.8, "logic": "and" },
      "Metapod": { "release_below_cp": 168, "release_below_iv": 0.8, "logic": "and" },
      "Kakuna": { "release_below_cp": 170, "release_below_iv": 0.8, "logic": "and" },
      "Rattata": { "release_below_cp": 204, "release_below_iv": 0.8, "logic": "and" },
      "Abra": { "release_below_cp": 208, "release_below_iv": 0.8, "logic": "and" },
      "Zubat": { "release_below_cp": 225, "release_below_iv": 0.8, "logic": "and" },
      "Chansey": { "release_below_cp": 235, "release_below_iv": 0.8, "logic": "and" },
      "Pidgey": { "release_below_cp": 237, "release_below_iv": 0.8, "logic": "and" },
      "Spearow": { "release_below_cp": 240, "release_below_iv": 0.8, "logic": "and" },
      "Meowth": { "release_below_cp": 264, "release_below_iv": 0.8, "logic": "and" },
      "Krabby": { "release_below_cp": 276, "release_below_iv": 0.8, "logic": "and" },
      "Sandshrew": { "release_below_cp": 278, "release_below_iv": 0.8, "logic": "and" },
      "Poliwag": { "release_below_cp": 278, "release_below_iv": 0.8, "logic": "and" },
      "Horsea": { "release_below_cp": 278, "release_below_iv": 0.8, "logic": "and" },
      "Gastly": { "release_below_cp": 280, "release_below_iv": 0.8, "logic": "and" },
      "Ekans": { "release_below_cp": 288, "release_below_iv": 0.8, "logic": "and" },
      "Shellder": { "release_below_cp": 288, "release_below_iv": 0.8, "logic": "and" },
      "Vulpix": { "release_below_cp": 290, "release_below_iv": 0.8, "logic": "and" },
      "Voltorb": { "release_below_cp": 292, "release_below_iv": 0.8, "logic": "and" },
      "Geodude": { "release_below_cp": 297, "release_below_iv": 0.8, "logic": "and" },
      "Doduo": { "release_below_cp": 297, "release_below_iv": 0.8, "logic": "and" },
      "Onix": { "release_below_cp": 300, "release_below_iv": 0.8, "logic": "and" },
      "Mankey": { "release_below_cp": 307, "release_below_iv": 0.8, "logic": "and" },
      "Pikachu": { "release_below_cp": 309, "release_below_iv": 0.8, "logic": "and" },
      "Magnemite": { "release_below_cp": 312, "release_below_iv": 0.8, "logic": "and" },
      "Tentacool": { "release_below_cp": 316, "release_below_iv": 0.8, "logic": "and" },
      "Paras": { "release_below_cp": 319, "release_below_iv": 0.8, "logic": "and" },
      "Jigglypuff": { "release_below_cp": 321, "release_below_iv": 0.8, "logic": "and" },
      "Ditto": { "release_below_cp": 321, "release_below_iv": 0.8, "logic": "and" },
      "Staryu": { "release_below_cp": 326, "release_below_iv": 0.8, "logic": "and" },
      "Charmander": { "release_below_cp": 333, "release_below_iv": 0.8, "logic": "and" },
      "Goldeen": { "release_below_cp": 336, "release_below_iv": 0.8, "logic": "and" },
      "Squirtle": { "release_below_cp": 352, "release_below_iv": 0.8, "logic": "and" },
      "Cubone": { "release_below_cp": 352, "release_below_iv": 0.8, "logic": "and" },
      "Venonat": { "release_below_cp": 360, "release_below_iv": 0.8, "logic": "and" },
      "Bulbasaur": { "release_below_cp": 374, "release_below_iv": 0.8, "logic": "and" },
      "Drowzee": { "release_below_cp": 374, "release_below_iv": 0.8, "logic": "and" },
      "Machop": { "release_below_cp": 381, "release_below_iv": 0.8, "logic": "and" },
      "Psyduck": { "release_below_cp": 386, "release_below_iv": 0.8, "logic": "and" },
      "Seel": { "release_below_cp": 386, "release_below_iv": 0.8, "logic": "and" },
      "Kabuto": { "release_below_cp": 386, "release_below_iv": 0.8, "logic": "and" },
      "Bellsprout": { "release_below_cp": 391, "release_below_iv": 0.8, "logic": "and" },
      "Omanyte": { "release_below_cp": 391, "release_below_iv": 0.8, "logic": "and" },
      "Kadabra": { "release_below_cp": 396, "release_below_iv": 0.8, "logic": "and" },
      "Oddish": { "release_below_cp": 400, "release_below_iv": 0.8, "logic": "and" },
      "Dugtrio": { "release_below_cp": 408, "release_below_iv": 0.8, "logic": "and" },
      "Rhyhorn": { "release_below_cp": 412, "release_below_iv": 0.8, "logic": "and" },
      "Clefairy": { "release_below_cp": 420, "release_below_iv": 0.8, "logic": "and" },
      "Slowpoke": { "release_below_cp": 424, "release_below_iv": 0.8, "logic": "and" },
      "Pidgeotto": { "release_below_cp": 427, "release_below_iv": 0.8, "logic": "and" },
      "Farfetch'd": { "release_below_cp": 441, "release_below_iv": 0.8, "logic": "and" },
      "Poliwhirl": { "release_below_cp": 468, "release_below_iv": 0.8, "logic": "and" },
      "Nidorino": { "release_below_cp": 480, "release_below_iv": 0.8, "logic": "and" },
      "Haunter": { "release_below_cp": 482, "release_below_iv": 0.8, "logic": "and" },
      "Nidorina": { "release_below_cp": 489, "release_below_iv": 0.8, "logic": "and" },
      "Graveler": { "release_below_cp": 501, "release_below_iv": 0.8, "logic": "and" },
      "Beedrill": { "release_below_cp": 504, "release_below_iv": 0.8, "logic": "and" },
      "Raticate": { "release_below_cp": 504, "release_below_iv": 0.8, "logic": "and" },
      "Butterfree": { "release_below_cp": 508, "release_below_iv": 0.8, "logic": "and" },
      "Hitmonlee": { "release_below_cp": 520, "release_below_iv": 0.8, "logic": "and" },
      "Ponyta": { "release_below_cp": 530, "release_below_iv": 0.8, "logic": "and" },
      "Hitmonchan": { "release_below_cp": 530, "release_below_iv": 0.8, "logic": "and" },
      "Charmeleon": { "release_below_cp": 544, "release_below_iv": 0.8, "logic": "and" },
      "Wartortle": { "release_below_cp": 552, "release_below_iv": 0.8, "logic": "and" },
      "Persian": { "release_below_cp": 568, "release_below_iv": 0.8, "logic": "and" },
      "Lickitung": { "release_below_cp": 568, "release_below_iv": 0.8, "logic": "and" },
      "Ivysaur": { "release_below_cp": 571, "release_below_iv": 0.8, "logic": "and" },
      "Electrode": { "release_below_cp": 576, "release_below_iv": 0.8, "logic": "and" },
      "Marowak": { "release_below_cp": 578, "release_below_iv": 0.8, "logic": "and" },
      "Gloom": { "release_below_cp": 590, "release_below_iv": 0.8, "logic": "and" },
      "Porygon": { "release_below_cp": 590, "release_below_iv": 0.8, "logic": "and" },
      "Seadra": { "release_below_cp": 597, "release_below_iv": 0.8, "logic": "and" },
      "Jynx": { "release_below_cp": 600, "release_below_iv": 0.8, "logic": "and" },
      "Weepinbell": { "release_below_cp": 602, "release_below_iv": 0.8, "logic": "and" },
      "Tangela": { "release_below_cp": 607, "release_below_iv": 0.8, "logic": "and" },
      "Fearow": { "release_below_cp": 609, "release_below_iv": 0.8, "logic": "and" },
      "Parasect": { "release_below_cp": 609, "release_below_iv": 0.8, "logic": "and" },
      "Machoke": { "release_below_cp": 614, "release_below_iv": 0.8, "logic": "and" },
      "Arbok": { "release_below_cp": 616, "release_below_iv": 0.8, "logic": "and" },
      "Sandslash": { "release_below_cp": 631, "release_below_iv": 0.8, "logic": "and" },
      "Alakazam": { "release_below_cp": 633, "release_below_iv": 0.8, "logic": "and" },
      "Kingler": { "release_below_cp": 636, "release_below_iv": 0.8, "logic": "and" },
      "Dodrio": { "release_below_cp": 640, "release_below_iv": 0.8, "logic": "and" },
      "Tauros": { "release_below_cp": 643, "release_below_iv": 0.8, "logic": "and" },
      "Primeape": { "release_below_cp": 650, "release_below_iv": 0.8, "logic": "and" },
      "Magneton": { "release_below_cp": 657, "release_below_iv": 0.8, "logic": "and" },
      "Venomoth": { "release_below_cp": 660, "release_below_iv": 0.8, "logic": "and" },
      "Golbat": { "release_below_cp": 672, "release_below_iv": 0.8, "logic": "and" },
      "Raichu": { "release_below_cp": 708, "release_below_iv": 0.8, "logic": "and" },
      "Cloyster": { "release_below_cp": 717, "release_below_iv": 0.8, "logic": "and"},
      "Mr. Mime": { "release_below_cp": 650, "release_below_iv": 0.8, "logic": "and" }
    }
}

Showing me my pokebag is full error

![screen shot 2016-07-30 at 4 04 43 am](https://cloud.githubusercontent.com/assets/879674/17267114/c58c4228-560a-11e6-971c-08079796a2f6.png)

My pokebag is

<img width="861" alt="screen shot 2016-07-30 at 4 05 10 am" src="https://cloud.githubusercontent.com/assets/879674/17267130/fc253ab0-560a-11e6-9da5-77e9ba2ba167.png">
<img width="844" alt="screen shot 2016-07-30 at 4 05 18 am" src="https://cloud.githubusercontent.com/assets/879674/17267135/fc28f2ae-560a-11e6-862a-2a8a535f957b.png">
<img width="829" alt="screen shot 2016-07-30 at 4 05 24 am" src="https://cloud.githubusercontent.com/assets/879674/17267132/fc265d6e-560a-11e6-955f-c4ef2f5de6f6.png">
<img width="856" alt="screen shot 2016-07-30 at 4 05 31 am" src="https://cloud.githubusercontent.com/assets/879674/17267134/fc26faa8-560a-11e6-8f70-e9c5c51899a3.png">
<img width="853" alt="screen shot 2016-07-30 at 4 05 36 am" src="https://cloud.githubusercontent.com/assets/879674/17267131/fc25ac52-560a-11e6-9b71-6aa3bcaebd8c.png">
<img width="831" alt="screen shot 2016-07-30 at 4 05 42 am" src="https://cloud.githubusercontent.com/assets/879674/17267133/fc26ab8e-560a-11e6-9fbc-8b68e20a8d7f.png">
<img width="862" alt="screen shot 2016-07-30 at 4 05 47 am" src="https://cloud.githubusercontent.com/assets/879674/17267137/fc40c85c-560a-11e6-8b77-cb9747c7b24d.png">
<img width="843" alt="screen shot 2016-07-30 at 4 05 55 am" src="https://cloud.githubusercontent.com/assets/879674/17267136/fc3ff436-560a-11e6-8f18-938adc8eefe9.png">
<img width="836" alt="screen shot 2016-07-30 at 4 06 00 am" src="https://cloud.githubusercontent.com/assets/879674/17267138/fc414728-560a-11e6-9fcd-2a712e8a281e.png">
<img width="844" alt="screen shot 2016-07-30 at 4 06 10 am" src="https://cloud.githubusercontent.com/assets/879674/17267139/fc42e0b0-560a-11e6-8900-2c9bf2294cd0.png">
<img width="848" alt="screen shot 2016-07-30 at 4 06 13 am" src="https://cloud.githubusercontent.com/assets/879674/17267140/fc42faa0-560a-11e6-8215-77e376bd664e.png">

### Other Information
OS: UBUNTU
Git Commit: bbcaec20d206867e113ee0b3050a93ad35731a1a

**Comment by Flowzor** [comment]
Did you manage to fix this?

**Comment by ltsampros** [comment]
I'm on 2f277fd7d08ff9a7ad45cf46e102a00db7ba9fdf and I can see the issue with a similar config. 

```

Also a log message when releasing/transfering a pokemon would be nice.
```

**Comment by ThadeuBrito** [comment]
@ZgrK which app do you se to manager your pokemons like the screenshot above?
