### ISSUE TITLE
new paramater on pokemon go server, fact or not.?

### ISSUE THREAD

**Issue by akbaribnu** [PokemonGoF/PokemonGo-Bot#1749]
hai dev, this morning i have warning from redit about new parameter on pokemongo api
this true or not.? please info.

this capture from redit

https://postimg.org/image/jlpztxmt3/

https://m.reddit.com/r/pokemongo/comments/4u8efx/first_ban_wave_coming_soon/

**Comment by Bramzor** [comment]
They have been logging that from the start.
