### ISSUE TITLE
Popping a lucky egg before evolving all

### ISSUE THREAD

**Issue by Donwulff** [PokemonGoF/PokemonGo-Bot#1752]
### Expected Behavior
Bot pops lucky egg before starting to evolve pokemon.

### Actual Behavior
Bot doesn't pop lucky egg before starting to evolve pokemon.

### Steps to Reproduce
Set...
"evolve_all": "NONE",
"use_lucky_egg": false,
Run bot

### Other Information
dev branch

### Fix:
evolve_all_worker.py:
```python
# Evolve all is used - Don't run after the first tick or if the config flag is false
        if self.bot.tick_count is not 1 or not self.bot.config.use_lucky_egg:
            return True
```
tick_count is increased by 1 before running each worker, therefore the first tick is 1, not 0.

**Comment by codybaldwin** [comment]
Thank you, a recent change to when the tick count is incremented broke this code as you pointed out. I'll submit a PR for the fix.
