### ISSUE TITLE
Web-UI doesn't show available candy on dev branch

### ISSUE THREAD

**Issue by Donwulff** [PokemonGoF/PokemonGo-Bot#1760]
The JSON key for candy in bagss was changed at some point from pokemon_family to candy. While this makes sense, it breaks compatibility with the shared bot web-UI that still (on latest pull from origin) expects pokemon_family key. Either source tree needs to change to support the other.

I *think* this key name comes straight from the pgoapi Inventory_pb2.py so fixing this in bot would mean changing the key on fly... little tricky.

**Comment by w1sht0l1v3** [comment]
this is not a bot issue.go to https://github.com/OpenPoGo/OpenPoGoWeb and complain there.
also it's a known thing that will be fixed soon.
you can close this ticket.
