### ISSUE TITLE
Not sure if I am an idiot, or if there is an error.  Pip install problem

### ISSUE THREAD

**Issue by rkowalk** [PokemonGoF/PokemonGo-Bot#1763]
Error:  Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-LlO1YQ/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_gNSH4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-LlO1YQ/greenlet/

I am getting this error when I attempt to use the following code:

- sudo pip install -r requirements.txt

Is this an issue?

**Comment by leadboots5** [comment]
are you doing 'virtualenv .' and 'source bin/activate' before doing that?

I had a hard time getting it to run outside of virtualenv and once you're in it you dont need sudo

**Comment by rkowalk** [comment]
Up until I pulled a few more commits everything was running correctly.

Sent from a mobile device. Erroneous words are a feature, not a typo




On Fri, Jul 29, 2016 at 10:28 PM -0600, "leadboots5" <notifications@github.com> wrote:












are you doing 'virtualenv .' and 'source bin/activate' before doing that?



I had a hard time getting it to run outside of virtualenv and once you're in it you dont need sudo

**Comment by gregtampa** [comment]
please come to the slack chat #help and ask someone to help you
this isn't a bug
