### ISSUE TITLE
How to change items to be Recycled and which not to Recycle?

### ISSUE THREAD

**Issue by xicedogzx** [PokemonGoF/PokemonGo-Bot#1765]
Keep having the issue in which the bot will keep high amounts of pokeballs and yet gets rid of other items I need. Someone know where I can find the location to modify these values? Thanks and sorry for the newb questions..

**Comment by pokemule** [comment]
Edit your item filter in config.json (e.g.):
"item_filter": {
      "1":   { "keep" : 100},
      "2":   { "keep" : 100},
      "3":   { "keep" : 100},
      "101": { "keep" : 0 },
      "102": { "keep" : 0 },
      "103": { "keep" : 80 },
      "104": { "keep" : 30 },
      "201": { "keep" : 80 },
      "701": { "keep" : 100 }
    },

The numbers to the left of the brackets (such as "1":, "2":,"3":, etc.) denote the item IDs. These item IDs are in your /PokemonGo-Bot/data/items.json:
{
    "0": "Unknown",

    "1": "Pokeball",
    "2": "Greatball",
    "3": "Ultraball",.... etc.

**Comment by xicedogzx** [comment]
Thanks Mate =)

**Comment by xicedogzx** [comment]
I tried it and having a issue launching, can you look at this picture and tell me what is wrong and possibly correct it for me? Sorry again =\ [http://imageshack.com/a/img921/3108/EeGyQi.png](url)

**Comment by arnogues** [comment]
JSON error, use http://jsonlint.com/ to check your JSON

**Comment by xicedogzx** [comment]
said it was valid =\

**Comment by zachd** [comment]
remove } just before `item_filter`

**Comment by xicedogzx** [comment]
still not working...
