### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by AwesomeGalS2** [PokemonGoF/PokemonGo-Bot#1778]
Friend's problem
http://imgur.com/a/o7raS

Issue: Can't run the bot.

**Comment by izzyleung** [comment]
I guess this is because your friend modified the two config files: `config.json` and `release_config.json`, but there are some JSON syntax error in those files.

**Comment by AwesomeGalS2** [comment]
Okay, I will tell him to check these files
