### ISSUE TITLE
Failed to run on VM after copying directly from own PC.

### ISSUE THREAD

**Issue by DrunkAgain** [PokemonGoF/PokemonGo-Bot#1780]
### Expected Behavior
To function properly.

### Actual Behavior
![bug5](https://cloud.githubusercontent.com/assets/20692601/17268223/494de1ec-5657-11e6-94c1-c60cf3cc33c6.png)

I just copied my folder into the exact same place in a VM instance.
ran everything
$ cd PokemonGo-Bot
$ virtualenv .
$ source bin/activate
$ pip install -r requirements.txt
$ git submodule init
$ git submodule update

except $ git clone -b master https://github.com/PokemonGoF/PokemonGo-Bot
because I provided the one I use in my pc, I just copied it to the VM.

### Other Information
OS:  WinServer2012 Google Cloud Platform
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Lunik** [comment]
Windows server ?! Really ?! Is you are familliar with Linux, USE Linux ! 😉

**Comment by DrunkAgain** [comment]
No sir. Just free trial from google. T_T

**Comment by DrunkAgain** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20692601/17268323/a8c5bf6c-5659-11e6-8fb1-4f61bd5dc4a7.jpg)
I mean this, I only use it as normal pc, so bot can run 24/7 .

**Comment by DrunkAgain** [comment]
problem is, bot have problems that doesn't appear here in my pc even though I copied the same folders. help.

**Comment by DrunkAgain** [comment]
probably the python plugins are not working properly due to the version of the system, will try Oracle VM + win7 x86 thru this VM. Closing thread.
