### ISSUE TITLE
[DEV] Can't find many Pokemon and Pokestops.

### ISSUE THREAD

**Issue by markkvdb** [PokemonGoF/PokemonGo-Bot#1786]
### Expected Behavior
Find more Pokemons and stop by more Pokestops. Yesterday I find a lot more Pokemon and Pokestops on the exact same spot.

### Actual Behavior
The bot just walks past a lot of nearby Pokestops and I don't find many Pokemon. I live in a dense city and I find around 5 pokemons in 0.5 hour. Could it have something to do with new range of detecting Pokemons of 70 meters instead of 100?

### Steps to Reproduce
config.json file:
"auth_service": "google",
    "username": "realusername",
    "password": "realpassword",
    "location": "reallocation",
    "gmapkey": "realkey",
    "max_steps": 10,
    "catch_pokemon": true,
    "forts": {
      "spin": true,
      "avoid_circles":true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 7.6,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "1": { "keep" : 100 },
      "101": { "keep" : 0 },
      "102": { "keep" : 0 },
      "103": { "keep" : 60 },
      "201": { "keep" : 0 },
      "701": { "keep" : 40 }
    },
    "evolve_all": "NONE",
    "evolve_speed": 20,
    "cp_min": 300,
    "use_lucky_egg": false,
    "hatch_eggs": true,
    "longer_eggs_first": true,
    "evolve_captured": false,
    "release_pokemon": true,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"}
    },

### Other Information
OS: OS X El Capitan
Git Commit: 79152bc65f8194ee9eb591fa657b99423771409e

**Comment by balpoint** [comment]
I'm expiriencing the same issue

**Comment by Viper896** [comment]
Can you try lowering you max circle size to something like 15 and tell me if you experience the same issue?

**Comment by Erody** [comment]
Same here. Bot is in central park and only caught 2 Pokemon in the last 30 mins. Used to be at least 1 per minute.

**Comment by markkvdb** [comment]
@Viper896 I have `avoid_circles:true` so it should not matter which `max_circle_size` I have. I tried it nonetheless and nothing changed. I don't know what explains that the bot doesn't go by the Pokestops, but I think the lack of Pokemon has to do something with the change in radius from 100m to 70m that happened overnight.

**Comment by gregtampa** [comment]
please come to the slack chat #help and ask someone to review your config files.
use dev version its much better
