### ISSUE TITLE
install requirements throws unsupported operand

### ISSUE THREAD

**Issue by tino-michael** [PokemonGoF/PokemonGo-Bot#1787]
when I run pip install -r requirements.txt
I get somewhere down the line the following error
Collecting universal-analytics-python==0.2.4 (from -r requirements.txt (line 18))
  Using cached universal-analytics-python-0.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-opf_acib/universal-analytics-python/setup.py", line 5, in <module>
        print >>sys.stderr, "Preparing version {0}\n".format(VERSION or "NOTFOUND")
    TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-opf_acib/universal-analytics-python/

### Other Information
OS: Arch Linux
Git Commit: 79152bc65f8194ee9eb591fa657b99423771409e
(current dev commit)

**Comment by gregtampa** [comment]
please come to the slack chat #help and ask someone to help you
this isn't a bug
