### ISSUE TITLE
How to increase the CP level of greatball?

### ISSUE THREAD

**Issue by harsh1412** [PokemonGoF/PokemonGo-Bot#179]
So i saw in the bot that its using the greatballs even on low level CP pokemons.
How do i increase the amount of CP which a greatball triggers?

**Comment by eggins** [comment]
I missed this section of the implementation. @douglascamata could you help on this one?

**Comment by millejosh** [comment]
@brantje @eggins 
isn't this set at line 65 of pokemon_catch_worker.py??

**Comment by brantje** [comment]
Nope,  see (this)[https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/cell_workers/pokemon_catch_worker.py#L65].
On line [42-51](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/cell_workers/pokemon_catch_worker.py#L42-L51] it looks for the strongest ball.
Already working on a fix

**Comment by millejosh** [comment]
@brantje weird, mine seems to be working.

[#] A Wild Rattata appeared! [CP68]
[x] Using Pokeball...
[x] Captured Rattata! [CP68] - exchanging for candy
[x] Exchanged successfully!
[x] Found pokemon at distance 329.249950733m
[#] Walking from (30.511562712141007, -97.67613412729037) to (30.511319456121722, -97.6757101444806) for approx. 3.0 seconds
[#] Finished walking to (30.511319456121722, -97.6757101444806)
[x] Walked to Pokemon
[#] A Wild Pidgey appeared! [CP266]
[x] Using Greatball...
[x] Captured Pidgey! [CP266]

**Comment by brantje** [comment]
@millejosh dev branch?

**Comment by millejosh** [comment]
@brantje nope its off the master

I think  42-51 is if your out of balls it switches

**Comment by jasonleeraert** [comment]
Can you also add a check to see if the pokemon has already been caught before? I'd only like to use great balls on new pokemons above a certain level.

**Comment by fsegouin** [comment]
```

**Comment by surfaace** [comment]
good function added with probability in PR #618
