### ISSUE TITLE
Please what's item code

### ISSUE THREAD

**Issue by MrCarlosJr** [PokemonGoF/PokemonGo-Bot#1791]
"item_filter": {
      "1": { "keep" : 50 },
      "2": { "keep" : 50 },
      "3": { "keep" : 50 },
      "101": { "keep" : 10 },
      "102": { "keep" : 25 },
      "103": { "keep" : 25 },
      "201": { "keep" : 25 },
      "701": { "keep" : 100 }
    },

**Comment by hklcf** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Item-ID's

**Comment by MrCarlosJr** [comment]
Thanks @hklcf
