### ISSUE TITLE
no lucky egg...skip evolve fail

### ISSUE THREAD

**Issue by hklcf** [PokemonGoF/PokemonGo-Bot#1792]
![image](https://cloud.githubusercontent.com/assets/410302/17268736/5ca8e854-5666-11e6-9369-5779e057c4b2.png)

79152bc65f8194ee9eb591fa657b99423771409e

**Comment by WillM88** [comment]
Is use_lucky_egg false in config.json?

**Comment by hklcf** [comment]
@WillM88 I want to evolve all pkm with lucky egg so `"evolve_all": "all"` and `"use_lucky_egg": true`

but it return no lucky egg there and skipping evolve so i think the bot should not evolve any pkm.

**Comment by WillM88** [comment]
Have you done a git pull recently? There was a fix uploaded a little while ago.

**Comment by gregtampa** [comment]
we aware use_lucky_egg dont work. thanks
