### ISSUE TITLE
Level up items aren't being claimed. Why?

### ISSUE THREAD

**Issue by sgitkene** [PokemonGoF/PokemonGo-Bot#1793]
### Expected Behavior
claims level up items

### Actual Behavior
Never claims level up items

### Steps to Reproduce
Run the bot until level up occurs

### Other Information
OS: Arch Linux
Git Commit: 83463c2bcd5c4360adbc41c61e6572406fec54ce

**Comment by wsmigielski** [comment]
When you login on a mobile device you receive them.

**Comment by eggins** [comment]
👍 @wsmigielski
