### ISSUE TITLE
[DEV] Keep looping at the same routes

### ISSUE THREAD

**Issue by lshaf** [PokemonGoF/PokemonGo-Bot#1796]
### Expected Behavior
It should be go to near pokestop when it's near

### Actual Behavior
It doesn't go to pokestop but bot just keep wandering at the same routes from the start and to the end.

### Steps to Reproduce
I don't know how but I just set my position to -7.940486, 112.664315
and here is screenshot map for more than a hour
![image](https://cloud.githubusercontent.com/assets/4636265/17268935/74148450-5664-11e6-97b8-3fd7b3ce3881.png)

### Other Information
OS: Windows
Git Commit: 79152bc65f8194ee9eb591fa657b99423771409e

**Comment by WebberTakkn** [comment]
I have exactly the same thing. The pattern seems to be random enough except it keeps repeating on some of the straight lines

**Comment by lshaf** [comment]
yeah, it's getting worse
![image](https://cloud.githubusercontent.com/assets/4636265/17270473/9a26ccec-568d-11e6-97da-b4135ecdf20a.png)
![image](https://cloud.githubusercontent.com/assets/4636265/17270477/a746f41a-568d-11e6-98bb-f0a8ef62d7f1.png)

**Comment by balpoint** [comment]
I'm also having these issue's, anyone have a fix yet, i'm on:

`DEV: 9b2450a`
