### ISSUE TITLE
[DEV] Failing to release pokemon on init. Exits with runtime error "Pokemon Bag is full!"

### ISSUE THREAD

**Issue by LaurynasGerbutavicius** [PokemonGoF/PokemonGo-Bot#1797]
### Expected Behavior
Start to release pokemons by config.

### Actual Behavior
Starting to catch pokemon having bag full and getting an error.

### Steps to Reproduce
Have full pokemon bag initialise bot on top of pokemon.

### Other Information
OS: win 10
![image](https://cloud.githubusercontent.com/assets/16867829/17268955/98236f76-5643-11e6-8ce6-09ca885d5546.png)

**Comment by gregtampa** [comment]
please open your config file and tweak it with better settings to release pokemon that you dont care to keep.
