### ISSUE TITLE
[DEV] bot crash (UnboundLocalError:)

### ISSUE THREAD

**Issue by StarForser** [PokemonGoF/PokemonGo-Bot#1798]
![crash](https://cloud.githubusercontent.com/assets/17098307/17268996/dd4d72da-5644-11e6-930c-4b38115e7b6c.JPG)

Use last commit

**Comment by JaisDK** [comment]
Just got this as well

git commit cb98498

**Comment by gregtampa** [comment]
come to slack chat #help and someone can help you
NOT A BUG
most likey you installed something wrong.. try dev version or update please.
