### ISSUE TITLE
For nubs.

### ISSUE THREAD

**Issue by DaniQQ** [PokemonGoF/PokemonGo-Bot#18]
Hello There smarter ppl than me.

I'm dumb for programming,can anyone write a guide how to make this work for nuubs like me?

I'm at the part where i installed python,and wanted to start pokecli but it just popps and doesn't stay to let me write stuff in it. 

Halp pls.
Thanks for it in forward.

**Comment by dankmemes** [comment]
Do you have a skype or a method of contact I can help you get it working I am pretty sure I know what your issue is someone else had this issue with another bot I could help you just hard to explain here.

**Comment by DaniQQ** [comment]
Thanks dankmemes, my skype is needmorecake, gonna be up on it in like half an hour if it's okay for you.

**Comment by dankmemes** [comment]
@DaniQQ  Sounds good.

**Comment by comfortedbasher** [comment]
i need halp too

**Comment by dankmemes** [comment]
@comfortedbasher Skype etc?

**Comment by TheGoldenXY** [comment]
Help me please. My skype is: REFHOST

**Comment by dankmemes** [comment]
@TheGoldenXY Added.

**Comment by jtdroste** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation
