### ISSUE TITLE
Bot is walking to pokestops instead of teleporting

### ISSUE THREAD

**Issue by sarandafl** [PokemonGoF/PokemonGo-Bot#181]
I do not have the `-w` argument enabled, yet the bot is still walking in realtime to pokestops.

**Comment by YourATowel** [comment]
This became the default.
-w 0 to teleport now I believe.

**Comment by douglascamata** [comment]
@sarandafl you will get softban is something like 5 though.

**Comment by sarandafl** [comment]
@douglascamata What do you mean?
Before this functionality was added I was still teleporting and never go a softban (Yesterday).

**Comment by dominikue** [comment]
@sarandafl I never got a softban too yesterday, but now i got one after only 3 Pokestops while tp 760 meters.

```
Found fort 56c31ab57c9a48718127d2c620e43780.16 at distance 759.932864462m
Need to move closer to Pokestop
Arrived at Pokestop
Now at Pokestop: Screaming Stone Lion - Spinning...
- Loot:
- Nothing found.
Traceback (most recent call last):
  File "pokecli.py", line 120, in <module>
```

**Comment by jtdroste** [comment]
Can you try using the latest version in the dev branch?
