### ISSUE TITLE
Do not release uniq pokemon

### ISSUE THREAD

**Issue by nyroDev** [PokemonGoF/PokemonGo-Bot#1811]
### Expected Behavior
When catching a pokemon that we don't own, and even if it has a bad IV or doesn't reach the configuration, don't release it.
It kinds of annoying to see it in the log, but not in our phone

### Actual Behavior
Pokemon are released even if we won't have it anymore

### Steps to Reproduce
1. Walk
2. Catch a pokemon that you don't have that have a relatively bad IV
3. It is released

**Comment by xorinzor** [comment]
Please read the documentation before opening an issue.

```
"Zubat": { "keep_best_iv" : true }

or

"Zubat": { "keep_best_cp" : true }
```

**Comment by nyroDev** [comment]
Ok sorry, I didn't check on dev branch, my bad.
