### ISSUE TITLE
pgoapi.exceptions.PleaseInstallProtobufVersion3

### ISSUE THREAD

**Issue by Cephis** [PokemonGoF/PokemonGo-Bot#1815]
### Expected Behavior
start pokemonGo-bot

### Actual Behavior
python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException
  File "/home/cephis/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 17, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3

### Steps to Reproduce
I install the last releases, made installs as described in the walkthrough and start with python pokecli.py in a prompt. I tried to install protobuf 3 especially but I don't know how to do it.

### Other Information
OS: linux mint rosa
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by rguedes** [comment]
run: `pip install -r requirements.txt`

**Comment by Cephis** [comment]
already done

**Comment by samjack** [comment]
`pip uninstall pgoapi` & `pip install -r requirements.txt`

**Comment by Cephis** [comment]
sudo pip uninstall pgoapi & pip install -r requirements.txt
[1] 4520
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi (from -r requirements.txt (line 1))
  Updating ./src/pgoapi clone (to 81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b)
Can't uninstall 'pgoapi'. No files were found to uninstall.
error: impossible d'ouvrir .git/FETCH_HEAD : Permission non accordée

  Complete output from command /usr/bin/git fetch -q:
  
----------------------------------------
Cleaning up...
Command /usr/bin/git fetch -q failed with error code 255 in /home/cephis/PokemonGo-Bot/src/pgoapi
Storing debug log for failure in /home/cephis/.pip/pip.log
[1]+  Fini                    sudo pip uninstall pgoapi

**Comment by samjack** [comment]
did you try `./install.sh`

**Comment by Cephis** [comment]
yes, i do it, it worked

**Comment by sgitkene** [comment]
maybe you mix python3 with python2?

try
`pip2 install -r requirements.txt`
and change python in run.sh to python2

**Comment by Cephis** [comment]
same thing with "sudo pip2 install -r requirements.txt"

Then I change in run.sh:
./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException
  File "/home/cephis/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 17, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3

**Comment by zachd** [comment]
edit run.sh file, change `python` to `python2`

**Comment by Cephis** [comment]
already done

**Comment by mercuriete** [comment]
you need some libraries
https://community.linuxmint.com/software/view/python-protobuf

python-protobuf is needed....
this package is in debian and ubuntu. but in linux mint it seems is provided by the community.
This is why you should use a better distribution or at least with a better package manager.

**Comment by Cephis** [comment]
packages available in linux mint rosa are protobuf 2.5.0-9ubuntu1. Is there any way to install version 3 by a ppa or else?

**Comment by mercuriete** [comment]
I have a friend that have the same exception than you in his raspberry pi but he coudn't fix it.

I am running the app inside a container and it is really weird because this is the version of the packages ->

root@e590f6264c87:/usr/src/app# dpkg -s python-protobuf
Package: python-protobuf
...........
Version: 2.6.1-1
Depends: libc6 (>= 2.4), libgcc1 (>= 1:4.1.1), libprotobuf9, libstdc++6 (>= 4.1.1), python-pkg-resources, python (<< 2.8), python (>= 2.7~), python:any (>= 2.7.5-5~)
....... .
root@e590f6264c87:/usr/src/app# dpkg -s libprotobuf9   
Package: libprotobuf9
..........
Version: 2.6.1-1
Depends: libc6 (>= 2.14), libgcc1 (>= 1:4.1.1), libstdc++6 (>= 4.9), zlib1g (>= 1:1.1.4)


Sorry for not beeing helpful. :(

**Comment by Cephis** [comment]
don't worry, that's alright, thx for your help anyway. I'll wait for more help of the community or an update that could resolve my problem.

**Comment by kendertas** [comment]
I resolved protobuf3 problem with this

[https://pypi.python.org/pypi/protobuf/3.0.0b4](url)

download the ".egg" file, and then install it with:
easy_install protobuf-3.0.0a3-py2.7.egg
(maybe you need sudo)

**Comment by open-abbott** [comment]
I had this exact same issue on Debian.  Flushed my ~/.local directory and reran pip and everything worked fine afterward.

**Comment by WojteKris** [comment]
just simple enter: 
pip install protobuf --upgrade

**Comment by hirudy** [comment]
@WojteKris  you are right
