### ISSUE TITLE
Require concise commit messages and PR titles, along with a PR review system

### ISSUE THREAD

**Issue by MaxLeiter** [PokemonGoF/PokemonGo-Bot#182]
The commit log is currently a mess, and every commit should be concise and say what it changes. I also recommend requiring PRs to be squashed into one commit for readability.

**Comment by jtdroste** [comment]
Agreed.  We're working on cleaning up commit messages and PRs.  I'm going to be adding an issue / pr template shortly, also

I'll close this, but it's ack'd
