### ISSUE TITLE
config.json entry "websocket_server"

### ISSUE THREAD

**Issue by groveld** [PokemonGoF/PokemonGo-Bot#1827]
what does the "websocket_server" variable in config.json do exactly? i've searched trough the code but could'nt find anything. is it something from a time long lost or is it to enable the SimpleHTTPServer from the main app later on?

**Comment by mrthrowaway** [comment]
Seems to have something to do with logging. Possibly a feature yet to be added

Added in commit 2805cb75be3d30de272095675316f1bf9138b639

**Comment by micdawg12** [comment]
I dunno, the fact that they added flask to the requirements.txt plus added the host/port config the same commit probably means they may be doing away with the extra web service for monitoring and have it built into the bot, much like the python poke maps.
