### ISSUE TITLE
Multi Bot

### ISSUE THREAD

**Issue by jimysb** [PokemonGoF/PokemonGo-Bot#1828]
Is there an easier way to do multi bots?
I did `screen` and `python pokecli.py --config ./configs/config1.json` then i start another terminal and did the same thing but with `config2.json`. This method works but it's kinder confusing because when i'm back from afking i won't know which is which. 

### Other Information
OS: Ubuntu 14.04 LTS

**Comment by vanrzuf** [comment]
maybe set name for each screen? screen -S name

**Comment by avallete** [comment]
I use docker to do that. Much more scalable.

**Comment by Hansimausi1984** [comment]
My current solution:

screen -S bots -c screenscript

screenscript
----------------
layout save default
screen bot1.sh
split -v            
focus            
screen bot2.sh 
split             
focus             
screen bot3.sh
----------------
each bot.sh executes "python pokecli.py -cf configs/config.json -u ... -p ... " 
i use a global config and overwrite it iside the bot.sh with bot specific settings.
-----------------
later you can detach ctrl+a d, and retatch always using screen -r bots

**Comment by jimysb** [comment]
Can someone please explain the docker part?
