### ISSUE TITLE
Bot Not Running since last pull :(

### ISSUE THREAD

**Issue by phoenix98787** [PokemonGoF/PokemonGo-Bot#1829]
### Expected Behavior
Bot to start running

### Actual Behavior
PS C:\Users\Phoenix\Documents\GitHub\PokemonGo-Bot> python pokecli.py -cf ./configs/config7.json
>>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\eventlet\__init__.py", line 5, in <module>
    from eventlet import greenthread
  File "C:\Python27\lib\site-packages\eventlet\greenthread.py", line 4, in <module>
    from eventlet import event
  File "C:\Python27\lib\site-packages\eventlet\event.py", line 3, in <module>
    from eventlet import hubs
  File "C:\Python27\lib\site-packages\eventlet\hubs\__init__.py", line 3, in <module>
    from eventlet import patcher
  File "C:\Python27\lib\site-packages\eventlet\patcher.py", line 4, in <module>
    from eventlet.support import six
  File "C:\Python27\lib\site-packages\eventlet\support\__init__.py", line 4, in <module>
    from eventlet.support import greenlets, six
  File "C:\Python27\lib\site-packages\eventlet\support\greenlets.py", line 3, in <module>
    import greenlet
ImportError: DLL load failed: The specified procedure could not be found.
Traceback (most recent call last):
  File "pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot
  File "C:\Users\Phoenix\Documents\GitHub\PokemonGo-Bot\pokemongo_bot\__init__.py", line 25, in
    from pokemongo_bot.socketio_server.runner import SocketIoRunner
  File "C:\Users\Phoenix\Documents\GitHub\PokemonGo-Bot\pokemongo_bot\socketio_server\runner.py"
    from eventlet import patcher, wsgi
  File "C:\Python27\lib\site-packages\eventlet\patcher.py", line 4, in <module>
    from eventlet.support import six
  File "C:\Python27\lib\site-packages\eventlet\support\__init__.py", line 4, in <module>
    from eventlet.support import greenlets, six
  File "C:\Python27\lib\site-packages\eventlet\support\greenlets.py", line 3, in <module>
    import greenlet
ImportError: DLL load failed: The specified procedure could not be found.

### Steps to Reproduce
python pokecli.py -cf ./configs/config7.json

### Other Information
OS: Windows 10
Git Commit: 2f277fd7d08ff9a7ad45cf46e102a00db7ba9fdf

**Comment by micdawg12** [comment]
Did you install/upgrade all the pip requirements?

**Comment by hklcf** [comment]
There's a quick solution for this.

`pip uninstall greenlet`
`easy_install greenlet`

**Comment by phoenix98787** [comment]
@micdawg12 I have done a  pip install -r requirements.txt and it seems everything did install correctly

@hklcf I have Run both too results look like it worked :-1: 
C:\Users\Phoenix\Documents\GitHub\PokemonGo-Bot [dev ≡ +0 ~2 -0 !]> pip uninstall greenlet
Uninstalling greenlet-0.4.10:
  c:\python27\lib\site-packages\greenlet-0.4.10-py2.7-win-amd64.egg
Proceed (y/n)? y
  Successfully uninstalled greenlet-0.4.10
C:\Users\Phoenix\Documents\GitHub\PokemonGo-Bot [dev ≡ +0 ~2 -0 !]> easy_install greenlet
Searching for greenlet
Reading https://pypi.python.org/simple/greenlet/
Best match: greenlet 0.4.10
Downloading https://pypi.python.org/packages/a7/d7/c10e63637a81f8a706325ef83700edbe516a1b7aa9b77fdf5d025925b84a/greenlet-0.4.10-py2.7-win-amd64.egg#md5=b04aab0bd673e8fac5260933edc834cf
Processing greenlet-0.4.10-py2.7-win-amd64.egg
creating c:\python27\lib\site-packages\greenlet-0.4.10-py2.7-win-amd64.egg
Extracting greenlet-0.4.10-py2.7-win-amd64.egg to c:\python27\lib\site-packages
Adding greenlet 0.4.10 to easy-install.pth file

Installed c:\python27\lib\site-packages\greenlet-0.4.10-py2.7-win-amd64.egg
Processing dependencies for greenlet
Finished processing dependencies for greenlet
C:\Users\Phoenix\Documents\GitHub\PokemonGo-Bot [dev ≡ +0 ~2 -0 !]> easy_install greenlet

**Comment by umutafacan** [comment]
same here, also pip uninstall greenlet not working
`Cannot uninstall requirement greenlet, not installed
Storing debug log for failure in /tmp/tmpL9nukI`

`pip install greenlet
Downloading/unpacking greenlet
  Downloading greenlet-0.4.10.zip (82kB): 82kB downloaded
  Running setup.py (path:/home/umut/PokemonGo-Bot/build/greenlet/setup.py) egg_info for package greenlet
    
Installing collected packages: greenlet
  Running setup.py install for greenlet
    building 'greenlet' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c greenlet.c -o build/temp.linux-x86_64-2.7/greenlet.o
    In file included from greenlet.c:5:0:
    greenlet.h:8:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /home/umut/PokemonGo-Bot/bin/python -c "import setuptools, tokenize;__file__='/home/umut/PokemonGo-Bot/build/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mXNNyC-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/umut/PokemonGo-Bot/include/site/python2.7:
    running install

running build

running build_ext

building 'greenlet' extension

creating build

creating build/temp.linux-x86_64-2.7

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c greenlet.c -o build/temp.linux-x86_64-2.7/greenlet.o

In file included from greenlet.c:5:0:

greenlet.h:8:20: fatal error: Python.h: No such file or directory

 #include <Python.h>

                    ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /home/umut/PokemonGo-Bot/bin/python -c "import setuptools, tokenize;__file__='/home/umut/PokemonGo-Bot/build/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mXNNyC-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/umut/PokemonGo-Bot/include/site/python2.7 failed with error code 1 in /home/umut/PokemonGo-Bot/build/greenlet
Storing debug log for failure in /tmp/tmp49srDc
`

**Comment by rlking** [comment]
same here

**Comment by rlking** [comment]
you can fix it with:
sudo apt-get install python-dev

there is the missing python.h

**Comment by umutafacan** [comment]
no use :( 
Traceback (most recent call last):
  File "pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot
  File "/home/umut/PokemonGo-Bot/pokemongo_bot/__init__.py", line 25, in <module>
    from pokemongo_bot.socketio_server.runner import SocketIoRunner
  File "/home/umut/PokemonGo-Bot/pokemongo_bot/socketio_server/runner.py", line 5, in <module>
    from eventlet import patcher, wsgi
  File "/home/umut/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/patcher.py", line 4, in <module>
    from eventlet.support import six
  File "/home/umut/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/support/__init__.py", line 4, in <module>
    from eventlet.support import greenlets, six
  File "/home/umut/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/support/greenlets.py", line 3, in <module>
    import greenlet
ImportError: No module named greenlet

**Comment by rlking** [comment]
try also this again
`sudo pip install --upgrade -r requirements.txt`
this has to complete without error

**Comment by jessecordeiro** [comment]
@phoenix98787 @umutafacan Update to Python 2.7.4 and this should resolve the issue.

**Comment by phoenix98787** [comment]
@jessecordeiro Dude you sir are awesome ....
That has resolved the issue lol
thank you so much, Marking as resolved
