### ISSUE TITLE
Getting stuck in a loop.

### ISSUE THREAD

**Issue by 2spook5me** [PokemonGoF/PokemonGo-Bot#183]
The bot seems to get stuck in a loop getting requests and then cleaning them up, to then start requesting them again.

Doesn't seem to matter what args you use in the batchfile to run the bot, gets stuck on the same thing no matter what the args are.

EDIT: It showed my stardust, xp and pokestops visited etc, but it said 0/250 pokemon, logged onto the account and they were all still there though.

http://i.imgur.com/fQE1cTP.png

**Comment by salihozd** [comment]
Same here. What is the expected output?

**Comment by Klohto** [comment]
Same problem. Is it because of the servers?

**Comment by 2spook5me** [comment]
It shouldn't be because of the servers, I just went out to see if it could be either that or a softban, but I could easily get onto the servers + use a pokéstop.
