### ISSUE TITLE
utf-8 logger.py

### ISSUE THREAD

**Issue by karasube** [PokemonGoF/PokemonGo-Bot#1833]
```UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 31: ordinal not in range(128)```

logger.py:21
```python
print('[' + time.strftime("%H:%M:%S") + '] ' + string)
```

should be
```python
print('[' + time.strftime("%H:%M:%S") + '] ' + string.decode('utf-8')
```

So we can bot in eg. Japan :)

```
[13:52:40] [x] Next egg incubates in 0.46 km
[13:52:41] Now at Pokestop: 古家石
[13:52:41] Spinning ...
[13:52:41] Possibly searching too often - taking a short rest :)
[13:52:42] Moving towards fort キノコ, 0.04km left
[13:52:46] Now at Pokestop: キノコ
[13:52:46] Spinning ...
```

**Comment by karasube** [comment]
Duplicate of  #1814 imho.

**Comment by marksweb** [comment]
I should have a fix for this in what I've done here;
https://github.com/marksweb/PokemonGo-Bot/commit/9fdc0b82bae08885f12dd54093e2a711b6fdc18f

**Comment by beranPro** [comment]
Problem still there. Latest commit on dev

**Comment by marksweb** [comment]
@beranPro in my latest commit from my fork?

**Comment by michi0987** [comment]
@karasube not 

`print('[' + time.strftime("%H:%M:%S") + '] ' + string.decode('utf-8')` 
But
`print('[' + time.strftime("%H:%M:%S") + '] ' + string.decode('utf-8'))`

**Comment by beranPro** [comment]
No, Dev on this project
