### ISSUE TITLE
Unknown spin result: -1

### ISSUE THREAD

**Issue by Erody** [PokemonGoF/PokemonGo-Bot#1836]
### Expected Behavior
Bot spins pokestop and gets items

### Actual Behavior
[13:53:46] Now at Pokestop: Unknown
[13:53:46] Spinning ...
[13:53:47] Unknown spin result: -1
[13:53:47] Possibly searching too often - taking a short rest :)

This is sometimes happening in all of my instances, but in one bot instance it's constantly happening. I have since run out of pokeballs, and am unable to get any new ones. Restarting the bot didn't help.

### Other Information
OS: Ubuntu 14.04
Git Commit: 79152bc65f8194ee9eb591fa657b99423771409e

**Comment by Hansimausi1984** [comment]
@Erody Try to change your location around 5km (wait some minutes regarding softban)
Same happend to my bots this morning. After changing the location everything works perfect again

**Comment by Erody** [comment]
Changed the location multiple times already, to no avail. Also, I remember there being a farm mode on the master branch. Is that not on the dev branch? Bot keeps trying to catch Pokemon with no pokeballs.

**Comment by Hansimausi1984** [comment]
hmm, for me it works perfect after changing the location - had the same problem on 4 users.

you can try:
    "catch_pokemon": false,

in your config.json. Never tested it myself

**Comment by Erody** [comment]
Tried that just now. It doesn't catch any Pokemon anymore, so that's good, but the pokestop error is still happening. It's now happening in all instances but one. They are all in different places too.

**Comment by Hansimausi1984** [comment]
hmm, just checked on my bots.
"walk": 14
checking the logs it took one of them around 30sec for 120m -> ~14km/h
looks okay for me if the distance is correct in the logs

requirements are updated also?

**Comment by Hansimausi1984** [comment]
@Erody 
Please check if  "Unknown spin result: -1" happens when the bags are full.
Happens now again on one of my guys with 341 Items in the bag (+9 eggs) with 350max

Think thats the problem for the Unknown spin result

**Comment by leadboots5** [comment]
I'm having this issue as well. bag is not full, I'm at Items: 193/350

**Comment by Erody** [comment]
Bags aren't full. All have less than 200 items in them
