### ISSUE TITLE
How to upgrade web part

### ISSUE THREAD

**Issue by MrCarlosJr** [PokemonGoF/PokemonGo-Bot#1840]
### Question
How to update de web page, in the original project have changes..
https://github.com/OpenPoGo/OpenPoGoWeb
### Steps to Reproduce
python pokecli.py

### Other Information
OS: Fedora 24
Git Commit: ec2b7add95da6bc580035d8d4c472c1d41e439a6

**Comment by Hansimausi1984** [comment]
inside your PokemonGo-Bot folder:
cd web/
git checkout master
git pull
should update to the lastest master of OpenPoGoWeb

also you can download the zip from https://github.com/OpenPoGo/OpenPoGoWeb/archive/master.zip and replace your web folder.

Take care after the update - userdata.js sturcture changed

**Comment by bchynds** [comment]
Don't just copy paste the zip into the git repo.  Use:
``git submodule foreach git pull origin master``

**Comment by MrCarlosJr** [comment]
Please Help me
http://i.imgur.com/NJMFHdW.png

**Comment by Hansimausi1984** [comment]
I think the websockets wont work on the current dev of the bot (at least never tested) so this error wont be a problem.

did you edit the userdata.js ?
What do you see when you access the website?

**Comment by MrCarlosJr** [comment]
Site works but don't asynchronous.
