### ISSUE TITLE
"catch_randomize_reticle_factor" seems not working

### ISSUE THREAD

**Issue by vicch** [PokemonGoF/PokemonGo-Bot#1843]
### Expected Behavior
Do "nice" and "great" throws occasionally.

### Actual Behavior
Barely do "nice" throws, never do "great" throws.

### Steps to Reproduce
```
"catch_randomize_reticle_factor" : 1,
"catch_randomize_spin_factor"    : 0.3,
```

### Other Information
OS: Windows 7
Git Commit: 2f277fd7d08ff9a7ad45cf46e102a00db7ba9fdf

**Comment by vicch** [comment]
Or maybe the "+110 exp" was from curve balls, the nice/great/excellent throws were not working at all.

**Comment by chauhan-rahul** [comment]
any sort of documentation on "catch_randomize_reticle_factor" and "catch_randomize_spin_factor", would be really welcome.. and i have the same issue!!

**Comment by vicch** [comment]
Some explaination in the code:
```
long_flag="--catch_randomize_reticle_factor",
help="Randomize factor for pokeball throwing accuracy (DEFAULT 1.0 means no randomize: always 'Excellent' throw. 0.0 randomizes between normal and 'Excellent' throw)",
...
long_flag="--catch_randomize_spin_factor",
help="Randomize factor for pokeball curve throwing (DEFAULT 1.0 means no randomize: always perfect 'Super Spin' curve ball. 0.0 randomizes between normal and 'Super Spin' curve ball)",
```
However I doubt it really does what it says.

**Comment by chauhan-rahul** [comment]
I found this in code... currently testing it..

API:

```
# Humanized `normalized_reticle_size` parameter for `catch_pokemon` API.
# 1.0 => normal, 1.950 => excellent
def normalized_reticle_size(factor):
    minimum = 1.0
    maximum = 1.950
    return uniform( minimum + (maximum - minimum) * factor, maximum)
```

Our code:
`    if config.catch_randomize_reticle_factor < 0 or 1 < config.catch_randomize_reticle_factor:
        parser.error("--catch_randomize_reticle_factor is out of range! (should be 0 <= catch_randomize_reticle_factor <= 1)")
        return None
`

No sure what to make of it... currently testing withe max api values, but 1.950 doesnt seem to catch anything.. whereas 1 just does a normal throw!

**Comment by antoineneff** [comment]
I looked into the code but it seems 1.0 should make excellent throws only ... I don't know why it does not.
Maybe pokemongo recent update change it ?

**Comment by xc-mezcal** [comment]
@vicch @antoineneff @douglascamata  It only do curve ball, no nice/great/excellent throw

This behaviour hugely affects the capture rates :(

**Comment by douglascamata** [comment]
#2095 states this is problem in `pgoapi`.

**Comment by Likael** [comment]
Actually, the (too simple) problem was in our code. Fixed with #2130.

**Comment by DayBr3ak** [comment]
With #2130 throws are only 210xp ? I have 
`"catch_randomize_reticle_factor": 1.0,
 "catch_randomize_spin_factor": 1.0,`

**Comment by vicch** [comment]
Happy to see it fixed in latest dev, closed.
