### ISSUE TITLE
[dev] Stuck in loop when Pokemon is not caught | catch/release config settings

### ISSUE THREAD

**Issue by toremielck** [PokemonGoF/PokemonGo-Bot#1846]
## The same Pokemon appears again and again as long as it's not caught
[15:02:12] Something rustles nearby!
**[15:02:13] A Wild Magikarp appeared! [CP 89] [Potential 0.8]**
[15:02:13] IV [Stamina/Attack/Defense] = [8/14/14]
[15:02:16] Moving towards fort Rathaus Speicherstadt, 0.07km left
[15:02:22] Moving towards fort Madame Monsieur, 0.11km left
[15:02:28] Something rustles nearby!
**[15:02:28] A Wild Magikarp appeared! [CP 89] [Potential 0.8]**
[15:02:28] IV [Stamina/Attack/Defense] = [8/14/14]
[15:02:32] Moving towards fort Rathaus Speicherstadt, 0.07km left
[15:02:38] Moving towards fort Madame Monsieur, 0.11km left
[15:02:45] Moving towards fort Madame Monsieur, 0.10km left
[15:02:50] Moving towards fort Rathaus Speicherstadt, 0.08km left
[15:02:57] Moving towards fort Madame Monsieur, 0.10km left
[15:03:03] Something rustles nearby!
**[15:03:04] A Wild Magikarp appeared! [CP 89] [Potential 0.8]**
[15:03:04] IV [Stamina/Attack/Defense] = [8/14/14]
[15:03:07] Moving towards fort Rathaus Speicherstadt, 0.08km left
[15:03:13] Something rustles nearby!
**[15:03:14] A Wild Magikarp appeared! [CP 89] [Potential 0.8]**
[15:03:14] IV [Stamina/Attack/Defense] = [8/14/14]
[15:03:18] Moving towards fort Rathaus Speicherstadt, 0.07km left
[15:03:24] Moving towards fort Madame Monsieur, 0.11km left
[15:03:30] Moving towards fort Madame Monsieur, 0.10km left
[15:03:36] Something rustles nearby!
**[15:03:36] A Wild Magikarp appeared! [CP 89] [Potential 0.8]**
[15:03:36] IV [Stamina/Attack/Defense] = [8/14/14]
[15:03:39] Moving towards fort Rathaus Speicherstadt, 0.08km left

## this is caused by the following settings in the config.json :

"auth_service": "google",
    "username": "EMAIL",
    "password": "PASSWORD",
    "location": "77.54430488172143, 10.997672625778575",
    "gmapkey": "GMAP_KEY",
    "max_steps": 10,
    "catch_pokemon": true,
    "forts": {
      "spin": true,
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 9,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "1": { "keep" : 100 },
      "101": { "keep" : 10 },
      "102": { "keep" : 30 },
      "103": { "keep" : 30 },
      "201": { "keep" : 30 },
      "701": { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "evolve_speed": 20,
    "evolve_cp_min": 300,
    "use_lucky_egg": false,
    "hatch_eggs": true,
    "longer_eggs_first": true,
    "evolve_captured": "NONE",
    "release_pokemon": true,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"**catch_above_cp": 150**, "catch_above_iv": 0, "logic": "and"},
      "// Example of always catching Rattata:": {},
      "Dratini": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "Rattata": {"always_release": true},
      "Zubat": {"always_release": true},
      "Pidgey": {"always_release": true},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    }
}

## As soon as i change the catch_above_cp to 0 and the Pokemon is caught the game continues.

Ideas anyone?

**Comment by fari-99** [comment]
i got the same problem, i'm just config to always catch anything (because they will disappear after you catch them) and release any below 400 cp.

so i think your config should be like this.
```
"catch": {
"any": {"catch_above_cp": **0**, "catch_above_iv": 0, "logic": "and"},
"// Example of always catching Rattata:": {},
"Dratini": { "always_catch" : true }
},
"release": {
"any": {"release_below_cp": **150**, "release_below_iv": 0, "logic": "or"},
"Rattata": {"always_release": true},
"Zubat": {"always_release": true},
"Pidgey": {"always_release": true},
"// Example of always releasing Rattata:": {},
"// Rattata": {"always_release": true},
"// Example of keeping 3 stronger (based on CP) Pidgey:": {},
"// Pidgey": {"keep_best_cp": 3},
"// Example of keeping 2 stronger (based on IV) Zubat:": {},
"// Zubat": {"keep_best_iv": 2},
"// Also, it is working with any": {},
"// any": {"keep_best_iv": 3},
"// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
"// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
}
```
