### ISSUE TITLE
ImportError: No module named pgoapi

### ISSUE THREAD

**Issue by YourATowel** [PokemonGoF/PokemonGo-Bot#185]
Traceback (most recent call last):
  File "C:\Users\User\PokemonGo-Bot\pokecli.py", line 41, in <module>
    from bot import PokemonGoBot
  File "C:\Users\User\PokemonGo-Bot\bot.py", line 8, in <module>
    from pgoapi import PGoApi
ImportError: No module named pgoapi

**Comment by HT395925N** [comment]
"pgoapi To install the pgoapi use pip install -e git://github.com/tejado/pgoapi.git#egg=pgoapi"

**Comment by aditardy** [comment]
#171

**Comment by tranhuanltv** [comment]
You can run: pip install -r ./requirements.txt 

again to checkout pgoapi
