### ISSUE TITLE
[Suggestion] Implement checking nearest pokestop first

### ISSUE THREAD

**Issue by harsh1412** [PokemonGoF/PokemonGo-Bot#186]
Hey so i was thinking as you guys implemented walking now it became much slower to gather pokemon/pokestops so i was thinking you could could implement something like this:

Lets stay steps =25
Okay so start the loop with 1
scan the whole 1 step area and note the number of pokestops/pokemons.
Farm them one by one 
now increment the loop by 1
and remove the previous step 1 data.
now scan the step 2 and farm them
repeat..

So this method looks more legit and gives more profit
because right now the bot goes in a line or choose the first  pokemon/pokestop it get while scanning and it doesn't care if the pokemon/pokestop is 1 meter away or 1000 meter away and start walking there.. which is time taking..

Thankyou.

**Comment by douglascamata** [comment]
Closing to avoid duplication spam.
