### ISSUE TITLE
[DEV] Fixing logger encoding

### ISSUE THREAD

**Issue by Gregwar** [PokemonGoF/PokemonGo-Bot#1860]
There is a little encoding mistake in `logger.py`, line 21 should be:

```python
        print('[' + time.strftime("%H:%M:%S") + '] ' + string.decode('utf-8'))
```

(see #1859)

**Comment by leadboots5** [comment]
already a pull request for it:
https://github.com/PokemonGoF/PokemonGo-Bot/pull/1839

**Comment by Gregwar** [comment]
Ok, great
