### ISSUE TITLE
Map isn't working can anyone help.

### ISSUE THREAD

**Issue by Rlewisrlou666** [PokemonGoF/PokemonGo-Bot#1863]
### Running terminal from PokemonGo-Bot folder with python pokecli.py
        Running terminal from web/ with python -m SimpleHTTPServer
        Opening http://localhost:8000/ in browser and nothing happens.

![snip20160730_1](https://cloud.githubusercontent.com/assets/20677921/17271126/b9dad3de-566b-11e6-9940-53f61ff71d8e.png)

**Comment by pierrecholhot** [comment]
Have you tried http://0.0.0.0:8000/ ? Any logs in the browser console ?

**Comment by glitchsnob** [comment]
what happens when you go to http://127.0.0.1:8000 in your browser?

**Comment by Rlewisrlou666** [comment]
Its working now thank you.
Is there supposed to be a player sprite?

**Comment by glitchsnob** [comment]
![What Mine Looks Like](https://cloud.githubusercontent.com/assets/19580093/17271235/63bfef1a-562b-11e6-852b-83486de5774d.PNG)

**Comment by Rlewisrlou666** [comment]
I was starting SimpleServer in the /web folder i was just using localhost.
I'm not getting pokestops/gyms showing up now and mine looks like this.
![snip20160730_2](https://cloud.githubusercontent.com/assets/20677921/17271263/d3e47d0e-566e-11e6-832e-a5a350d68847.png)

**Comment by glitchsnob** [comment]
make sure the extracted contents of the -master OpenPoGoWeb are in \web\css..js..images..etc...

**Comment by Rlewisrlou666** [comment]
do I have to move the images folder?

**Comment by Rlewisrlou666** [comment]
![snip20160730_4](https://cloud.githubusercontent.com/assets/20677921/17271599/04b3e772-5678-11e6-829d-407d6ecb8614.png)

**Comment by fari-99** [comment]
got the same problem with @Rlewisrlou666 , i think documentation for using the web is not good enough. @glitchsnob , can you tell what you are doing?

**Comment by Rlewisrlou666** [comment]
I think its a problem with OpenPoGo itself and they are working on a fix at the min.
https://github.com/OpenPoGo/OpenPoGoWeb/issues/132

**Comment by Rlewisrlou666** [comment]
@glitchsnob thanks for all your help I think I just have to wait for a fix my Bot is still working at least. :)

**Comment by WillM88** [comment]
@glitchsnob what interface is that? And is that "bot path" random?

**Comment by lelbo** [comment]
Hello

Possible to guide for Maps-api

Bot work perfect.

**Comment by glitchsnob** [comment]
Mine is running with out issue. Using Dev for BOT, Master for OpenPoGoWeb

Your web folder of your bot should look like this. (The contents of the OpenPogoWeb should be the only in \web

![web contents](https://cloud.githubusercontent.com/assets/19580093/17278236/1c8842a4-570d-11e6-8fa7-176c42dab190.PNG)

**Comment by gilegue** [comment]
Only catchable and inventory will populate automatically. You just have to create an empty location file manually.
