### ISSUE TITLE
No JSON object could be decoded?

### ISSUE THREAD

**Issue by lifeofbolo** [PokemonGoF/PokemonGo-Bot#1864]
<img width="818" alt="skaermbillede 2016-07-30 kl 16 52 38" src="https://cloud.githubusercontent.com/assets/20727032/17271296/c5e354e2-5677-11e6-9555-3a43a5d005a1.png">
<img width="605" alt="skaermbillede 2016-07-30 kl 16 55 41" src="https://cloud.githubusercontent.com/assets/20727032/17271300/ce6e71fa-5677-11e6-87b7-229974566c12.png">

**Comment by mrthrowaway** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/No-JSON-object-could-be-decoded-or-decoder.py-error

**Comment by lifeofbolo** [comment]
im getting this...
<img width="951" alt="skaermbillede 2016-07-30 kl 17 24 37" src="https://cloud.githubusercontent.com/assets/20727032/17271396/9029ca18-567a-11e6-8bd8-bb43286426b9.png">

**Comment by mrthrowaway** [comment]
Yes, you seem to be getting the double quotes wrong. Probably something your text editor does. Try copying the example file, and editing only the text inside the quotes

**Comment by lifeofbolo** [comment]
@mrthrowaway whats the next step? :-D

<img width="1178" alt="skaermbillede 2016-07-30 kl 18 47 29" src="https://cloud.githubusercontent.com/assets/20727032/17271804/21aef4d0-5686-11e6-9870-66cbcedff338.png">

**Comment by mrthrowaway** [comment]
`python pokecli.py`

**Comment by lifeofbolo** [comment]
@mrthrowaway but what does this mean? 
<img width="707" alt="skaermbillede 2016-07-30 kl 20 41 06" src="https://cloud.githubusercontent.com/assets/20727032/17272428/1a8cfe62-5696-11e6-95df-15db4c894d55.png">

**Comment by mrthrowaway** [comment]
Where is your config.json file? If its in a different location other than the default or if you've renamed it
do `python pokecli.py -cf path/to/config.json`

**Comment by lifeofbolo** [comment]
@mrthrowaway getting this now :-) whats next?

(PokemonGo-Bot) Kenneths-MacBook-Pro:PokemonGo-Bot kennethbolo$ python pokecli.py
[2016-07-30 21:04:11] [x] PokemonGO Bot v1.0
[2016-07-30 21:04:11] [x] Configuration initialized
[2016-07-30 21:04:11] [#] IMPORTANT: Rename and configure release_config.json.example for your Pokemon release logic first!

**Comment by mrthrowaway** [comment]
`IMPORTANT: Rename and configure release_config.json.example for your Pokemon release logic first!`

That :P

**Comment by lifeofbolo** [comment]
change it back to config.json.example?

**Comment by mrthrowaway** [comment]
nope. you'll find a file named `release_config.json.example`, change it to `release_config.json`

**Comment by lifeofbolo** [comment]
I'm getting this now.
[2016-07-30 22:33:51] [x] PokemonGO Bot v1.0
[2016-07-30 22:33:51] [x] Configuration initialized
[2016-07-30 22:33:51] [x] The location given using -l could not be parsed. Checking for a cached location.
[2016-07-30 22:33:53] Login Error, server busy

**Comment by mrthrowaway** [comment]
Login error happens when the pokemon go servers are busy. If you location isn't recognized, you could try entering the latitude and longitude manually

**Comment by lifeofbolo** [comment]
@mrthrowaway I managed to run it. By cloning and adding the Google generated password. But how do i set it up with the web ui?

**Comment by mrthrowaway** [comment]
```
git submodule init
git submodule update
cd web
<edit userdata.js or config/userdata.js depending on what version you're on>
python -m SimpleHTTPServer
```

And browse to http://localhost:8000

**Comment by lifeofbolo** [comment]
should i run it in a new terminal window? or in the same terminal as pokecli.py?

**Comment by mrthrowaway** [comment]
run it separately

**Comment by lifeofbolo** [comment]
do i need to download openpogoweb-master first?

**Comment by mrthrowaway** [comment]
`git submodule` command should be run inside PokemonGo-Bot

**Comment by lifeofbolo** [comment]
@mrthrowaway 
So what order should i put git submodule in? 

cd pokemongo-bot
virtualenv .
source bin/activate
- git submodule?
pip install -r requirements.txt
python pokecli.py

**Comment by mrthrowaway** [comment]
> cd path/to/PokemonGo-Bot
> git submodule init
> git submodule update
> cd web
<edit userdata.js or config/userdata.js depending on what version you're on>
The above bit only needs to be done the first time
To start the web interface,
> cd path/to/PokemonGo-Bot/web
> python -m SimpleHTTPServer

This is run separately from your bot, presumably in another terminal window/tab

**Comment by lifeofbolo** [comment]
is this correct? i'm getting a blank screen on my localhost.
<img width="764" alt="skaermbillede 2016-07-31 kl 16 11 21" src="https://cloud.githubusercontent.com/assets/20727032/17277029/85b866ce-5739-11e6-9cb3-44f5e6e92789.png">

**Comment by mrthrowaway** [comment]
you need to run the server from inside the web directory

**Comment by lifeofbolo** [comment]
@mrthrowaway  u mean the OpenPoGoWeb-master

**Comment by mrthrowaway** [comment]
If you followed the installation instructions, you end up with the `PokemonGo-Bot/` directory with the `web/` directory inside it.

If your OpenPoGoWeb directory is named something other than `web` or located elsewhere, you'll have to rename it to `web` and move it inside the bot directory

**Comment by lifeofbolo** [comment]
@mrthrowaway now its running a blank screen
<img width="766" alt="skaermbillede 2016-07-31 kl 17 24 20" src="https://cloud.githubusercontent.com/assets/20727032/17277461/a9e34b4a-5743-11e6-814d-b9a00646d547.png">

**Comment by mrthrowaway** [comment]
Umm. Did you install the bot using git like the installation instructions said or did you download a zip file?

**Comment by lifeofbolo** [comment]
@mrthrowaway now i am getting this? 
<img width="767" alt="skaermbillede 2016-07-31 kl 17 46 21" src="https://cloud.githubusercontent.com/assets/20727032/17277585/c440dc0c-5746-11e6-94d1-14c3dd65a74d.png">

**Comment by mrthrowaway** [comment]
At this point, I'd just start over and go through the installation instructions step by step

https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation

At the end, you will have the directory named `PokemonGo-Bot` from where you run the bot, and a `web` directory inside that from where you run the web interface.

If you still have issues, join the Slack chanel at https://pokemongo-bot.herokuapp.com/
Someone with more experience with MacOS may be able to help you there

**Comment by mrthrowaway** [comment]
Regarding the error you last posted https://github.com/PokemonGoF/PokemonGo-Bot/issues/2082

**Comment by lifeofbolo** [comment]
thank you very much 👍
