### ISSUE TITLE
When losing internet connection

### ISSUE THREAD

**Issue by pierrecholhot** [PokemonGoF/PokemonGo-Bot#1867]
### Expected Behavior
It would be nice to have the bot automatically re-connect and resume. Well because it's a bot after all =)

### Actual Behavior
Nothing happens, no logs or retries.

### Steps to Reproduce
Lose internet connection while the bot is walking.

### Output

> [16:55:53] Spinning ...
> [16:55:53] Loot:
> [16:55:53] 50 xp
> [16:55:54] - 3x Pokeball (Total: 54)
> [16:55:54] - 1x Greatball (Total: 177)
> [16:55:54] PokeStop on cooldown. Time left: 4 minutes, 59 seconds
> [16:56:15] Walking from (X, Y) to [X, Y] 0.20km
> [16:57:26] Walking from (X, Y) to [X, Y] 0.20km
> [16:57:47] Something rustles nearby!
> [16:57:48] A Wild Pidgey appeared! [CP 263] [Potential 0.29]
> [16:57:48] IV [Stamina/Attack/Defense] = [1/3/9]
> [16:57:51] Catch Rate with normal Pokeball is low (36.31%). Throwing Razz Berry... (8 left!)
> [16:57:51] Catch Rate with normal Pokeball has increased to 54.47%
> [16:57:51] Using Pokeball (chance: 54.47%)... (53 left!)
> [16:57:52] Captured Pidgey! [CP 263] [Potential 0.29] [1/3/9] [+110 exp]
> [16:58:42] [x] Next egg incubates in Y.11 km
> [16:58:42] Walking from (X, Y) to [X, Y] 0.20km
> [16:59:46] Walking from (X, Y) to [X, Y] 0.13km
> 
> //- then nothing happens, no warnings nor retries.

### Other Information
OS: El Capitan, latest
Git Commit: (2f277fd7d08ff9a7ad45cf46e102a00db7ba9fdf)

**Comment by MMurarasu** [comment]
You can make a .bat for this.... run it, and it will keep spawning the bot  or you can increase the number of retries and the time for this.
:loop

echo "Retrying...."
cd "C:\Path\To\Bot\PokemonGo-Bot\"
python pokecli.py %* 
timeout /t 30

goto loop

**Comment by tstumm** [comment]
@MMurarasu I think the bot just pauses and does not exit, so your script won't help.

**Comment by MMurarasu** [comment]
No it doesn't.  pausing, Waiting with these couple of command line's it's the same. I've been using exactly this stuf to farm for the last 4 nights. :)  Try first

**Comment by fari-99** [comment]
i think @tstumm  is right, because the robot in pause, the script won't help, it will work if the robot is crash.

**Comment by MMurarasu** [comment]
Guys, seriously.. TEST FIRST, PLEASE.   Something happens with servers/connections. You'll see in the logs a red message with retry number ( you can set there number of retries and interval). IN THIS CASE, BOT IS PAUSING AND RETRYING BY HIMSELF. --> server up or internet is back online --> script resume. Otherwise. IT STOPS.  In this case... the bat will  call it again and again every 30 secs.  This is mainly better than  just setting 999 retries at 30 mons interval because you will have uptime in case of other crashes too.
To test: RUN BAT - DISCONNECT FROM INTERNET - SEE THE MAGIC. Please post stuff with "  i think " afterwards

**Comment by NickUstimenko** [comment]
how to make bot auto restart on Linux?
this code
`until (python pokecli.py); do
    echo "Process crashed with exit code $?.  Respawning.." >&2
    sleep 3600
done`

**Comment by NickUstimenko** [comment]
@MMurarasu help me pls

**Comment by MMurarasu** [comment]
#!/bin/bash
echo "I'm running...."
while true do
 /path/to/script/python pokecli.py $@
 exitcode = $? 
 echo -e "Script crashed - Exit: ${exitcode}  ... will initialize under a short break"
 sleep 3600


I think this should be it. No way to test it until tomorrow though...

**Comment by NickUstimenko** [comment]
@MMurarasu and where to write it?
