### ISSUE TITLE
--maxstep still not working when -s is used

### ISSUE THREAD

**Issue by iDervy** [PokemonGoF/PokemonGo-Bot#187]
`pokecli.py -a ptc -u xxxxxx -p xxxx --location "kyoto garden, london" -w 3 -c 10 --maxstep 2 -s`

This spot has 10 pokestops within 2 steps, yet its first Pokestop is 5 steps away approx. 

```
looping: step 1 of 4
steplimit: 4 x: 0 y: 0 pos: 1 dx: 0 dy -1
Walking from (51.50299219999999, -0.2046902) to (51.50299219999999, -0.2046902) for approx. 0.0 seconds
Finished walking
(51.50299219999999, -0.2046902, 0)
Found fort 7e24276df4a04425b73f118454b725f6.16 at distance 1103.0083532m
Need to move closer to Pokestop
Walking from (51.50299219999999, -0.2046902) to (51.496808, -0.192237) for approx. 368.0 seconds
```

**Comment by jtdroste** [comment]
Please try using the version located in the `dev` branch.

**Comment by hero16** [comment]
just to understand a bit better,

how big exactly is a cell since say maxstep 5 = 25 cells. thank you!

**Comment by eggins** [comment]
This is now being revamped with the walk&grab.
Please wait for updates - and use the dev branch for now whilst testing.
