### ISSUE TITLE
The bot repeat the same route when "move_to_spin" is false

### ISSUE THREAD

**Issue by crusardri** [PokemonGoF/PokemonGo-Bot#1876]
### Expected Behavior

Go to explore an search pokemon

### Actual Behavior
![image](https://cloud.githubusercontent.com/assets/4596106/17271736/3e3f6a32-5684-11e6-9d89-9802508fe04e.png)
purple route
### Steps to Reproduce

"move_to_spin": False

### Other Information
OS: Win 10
Git Commit: 190640f

**Comment by douglascamata** [comment]
Increase max steps dramatically.
