### ISSUE TITLE
[DEV] ImportError: cannot import name get_cell_ids

### ISSUE THREAD

**Issue by razithekillers** [PokemonGoF/PokemonGo-Bot#1877]
Just pull code and I get this error
![image](https://cloud.githubusercontent.com/assets/20743071/17271791/3a611968-56b8-11e6-9eb8-4005547e9588.png)

Any idea?

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by razithekillers** [comment]
never mind, forgot to upgrade requirements. sorry guys

**Comment by vamirineni87** [comment]
how did u get this to work. even after 

pip2 install -r requirements.txt 

it doesnt work

**Comment by razithekillers** [comment]
I just follow update guide, run pip:

1. git pull
2. pip install --upgrade -r requirements.txt

that all

**Comment by kaoztheory** [comment]
does not fix.
