### ISSUE TITLE
[Feature request] Pokémon Sniping

### ISSUE THREAD

**Issue by betrisey** [PokemonGoF/PokemonGo-Bot#1880]
NecroBot has a feature to snipe Pokémons, it would be nice to have it too.
It scans others locations using pokevision.com and once in a while, it teleports and catches it.

Implementation in C#
https://github.com/NecronomiconCoding/NecroBot/blob/16a18c7beee973ed4b97862c9c316c8202cf301c/PoGo.NecroBot.Logic/Tasks/SnipePokemonTask.cs
https://github.com/NecronomiconCoding/NecroBot/pull/1274

**Comment by DayBr3ak** [comment]
I thought PokemonGo-Bot was aiming for human behavior ? Is this ok ?

**Comment by ddrght12345** [comment]
Might be useful, as long as it isnt TOO frequent and within a short distance.

**Comment by Lunik** [comment]
Added in 21254bc0f21ca7bd7612eab0ac480d080ccea9f9
But the bot snipe every pokemon... sometimes 1,5km away :sob:.
Maybe add a snipe filter ? `snipe_min: 100`
