### ISSUE TITLE
Bot Stops Working Properly after ServerBusyOrOfflineException

### ISSUE THREAD

**Issue by inet-pwnZ** [PokemonGoF/PokemonGo-Bot#1881]
### Expected Behavior
catching pokemon going to forts

### Actual Behavior
Server Busy
![issue](http://image.prntscr.com/image/49c163fbf9b54b0785c5e3ac04a7c52d.png)
then after the bot restarts it's just walking around doing nothing
![issue2](http://image.prntscr.com/image/1d3cdf9e1cc74529b421f5132bd107bf.png)

### Steps to Reproduce
after the bot loses connection like in the first picture
it stops working properly after restarting the programm
im running a loop
`
@echo off
title inet
:loop
python pokecli.py
timeout /t 60 >null
GOTO loop
`

### Other Information
OS: Win7
Git Commit: 190640f06fc623f804c554ce1ac9264c9fa8b22d

**Comment by AshKetchum07302016** [comment]
Got the same problem

**Comment by xc-mezcal** [comment]
Got the same problem 

Win 10
