### ISSUE TITLE
Constantly "walking from xxxxx to xxx"

### ISSUE THREAD

**Issue by ayiire** [PokemonGoF/PokemonGo-Bot#1885]
What is the solution to this problem where the bot is constantly just walking with no updates on the bot? Or not even provide and update. I asked on slack and nobody seems to know. Did something change with the walking speed?

Reference issue where it was closed - https://github.com/PokemonGoF/PokemonGo-Bot/issues/1692

I already did the following:

-fresh pull of dev by deleting the whole folder and doing a pull. 
Running commit - c6652f228ad9543be7907f66f731d988a26676d0

-Reinstall of requirements.txt doing the following:
pip install --upgrade -r requirements.txt

Snippet of config
```
    "max_steps": 5,
    "catch_pokemon": true,
    "forts": {
      "spin": true,
      "move_to_spin": false,
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "101": { "keep" : 10 },
      "102": { "keep" : 30 },
      "103": { "keep" : 30 },
      "201": { "keep" : 30 },
      "701": { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "evolve_speed": 20,
    "evolve_cp_min": 300,
    "use_lucky_egg": false,
    "hatch_eggs": false,
    "longer_eggs_first": true,
    "evolve_captured": "NONE",
    "release_pokemon": true,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,

```
Here is a console output
```
[13:07:49]  Starting PokemonGo Bot....
[13:07:51] Walking from (40.761734, -73.974306) to [40.761734, -73.974306] 0.00km
[13:07:53] Walking from (40.761734, -73.974306) to [40.763534, -73.974306] 0.20km
[13:11:24] Walking from (40.763534, -73.974306) to [40.763534, -73.972506] 0.15km
[13:13:34]  Exiting PokemonGo Bot
```

**Comment by accident12123** [comment]
There is a bug where it seems to walk back and forth for what appears to be a human movement feature but it never makes it before heading back to the next fort..

But in the last day https://github.com/PokemonGoF/PokemonGo-Bot/commit/cb984984ab482a8bf3f65686fec988ef6ee3fc78 with a default setting of true.     It seems to never try walk to any pokestop.    I think the intention was to not walk far just to spin a fort but if you switch it to false it'll behave like it did before it was added.

**Comment by ayiire** [comment]
I have move to spin set to false and it still seems to be stuck. If I have the hatch egg parameter set to true, the distance to hatch does increase so it is sort of walking really slowly.

**Comment by mercuriete** [comment]
I hit the same issue.

**Comment by Simbe90** [comment]
Got this issue as well after updating from commit earlier today 93dbca6. I'm going to revert back to it for now.

**Comment by accident12123** [comment]
There is a patch waitng to be applied by some but change

https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/evolve_all_worker.py#L58

to be return False instead of return True.    It's trying to evolve pokemon on every step is the sort answer.

**Comment by ayiire** [comment]
So even though evolve is set to NONE, it's still trying to evolve something? 

Now that's an answer rather than closing a issue without a resolution.

**Comment by ayiire** [comment]
Setting that line to false and running it again doesn't seem to resolve the issue with walking or updates. I'll just wait for the patch.

**Comment by mako-taco** [comment]
This patch fixes the walking speed issue without hampering egg hatching or evolving #1769 . It also happens to fix this issue of walking past a fort.

**Comment by DimaVIII** [comment]
@ayiire just get the newest dev commit... it will fix your bug

**Comment by xterraforcex** [comment]
I just tried the newest dev comment and it is still having the same issue

**Comment by DimaVIII** [comment]
May try to install a fresh bot in a new directory.
