### ISSUE TITLE
help me pelase

### ISSUE THREAD

**Issue by T7pokemon** [PokemonGoF/PokemonGo-Bot#1889]
Hi, when i type npm start. it starts like how it should, but when it doesn't do anything when i click on apply. it says this in the cmd: looks like googlemaps module is missing? i'm using debian.

npm start

> PokemonGoBot@0.0.1-alpha start /root/PokemonGo-Bot-Desktop
> electron main.js

Starting Python process...
Got open port: 8000
Bot path: /root/PokemonGo-Bot-Desktop/gofbot
python ./pokecli.py
Bot path: /root/PokemonGo-Bot-Desktop/gofbot/web
python serveit.py 8000
server started!
Python: Traceback (most recent call last):
  File "./pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/root/PokemonGo-Bot-Desktop/gofbot/pokemongo_bot/__init__.py", line 4, in <module>
    import googlemaps
ImportError: No module named googlemaps

**Comment by mrthrowaway** [comment]
You're looking for https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
