### ISSUE TITLE
same posistion

### ISSUE THREAD

**Issue by drew93** [PokemonGoF/PokemonGo-Bot#1890]
every time I start the bot returns the coordinates of the first time I started , even if I put the new coordinates

**Comment by mrthrowaway** [comment]
You'll have to set location_cache to false in your config if you want it to always start at the coordinates from the config.

If its a one time thing, stop the bot, delete data/last-location-<account>.json and start the bot

**Comment by fari-99** [comment]
in config set `"location_cache": false`. hope it helps.

**Comment by drew93** [comment]
thanks i try, and in config.json there is this 
    "mode": "all",
what are the other commands ?

**Comment by fari-99** [comment]
please see the configuration file [here](https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files).

**Comment by drew93** [comment]
@mrthrowaway in data/  i have only item,json and pokemon.json

**Comment by fari-99** [comment]
well, after you start the bot, you will get more than that.
like cells-[your_email_here].json etc.

**Comment by drew93** [comment]
@fari-99 i started and same 2 files

**Comment by mrthrowaway** [comment]
Wait. Are you saying that the command line argument of location is not overriding the location in the config file?

**Comment by fari-99** [comment]
for @mrthrowaway i don't know, i never used the command line. just ordinary using. haha.

**Comment by mrthrowaway** [comment]
So how are you passing the location to the bot?

**Comment by fari-99** [comment]
using config.json files.

**Comment by drew93** [comment]
@mrthrowaway  i put in config.json coordinate like this "location": "2.61319687920969,6.247913360595703",
