### ISSUE TITLE
[Feature Request] Farm a popular spot Mode

### ISSUE THREAD

**Issue by leckeia** [PokemonGoF/PokemonGo-Bot#1895]
First off, great bot, good job!

A Feature which shouldnt need much of code is the following:
Farming a popular spot like famous spots with 4 pokestops.
These spots often spawn a great amount of pokemon and also some rare and high CP ones.

So setting the Bot to these coordinates, all thats left is making it stand still, catch all the pokemon and repeatitly farm the pokestops. There should be a little GPS movement since the GPS on a phone also is always slightly moving around a little. 

With this we'd be able to farm specific spots for specific pokemon or just whatever spawns on these crazy crowded popular spots.

greetings, leckeia

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by mrthrowaway** [comment]
Guess you can use the 'Path Navigator' feature that was just added to the dev branch 

9062f9a539881323c386500d16581ec9dd062c0a

**Comment by leckeia** [comment]
Hehe had the same thought, already testing the new feature, looks good but it's too early to tell if the spots i set have been visited
