### ISSUE TITLE
Bot fell to Sleep

### ISSUE THREAD

**Issue by Stayhomeforever** [PokemonGoF/PokemonGo-Bot#1896]
The Bot fell to sleep after the logger shows walk from (XXX) to (XXX), and does not wake up any more.

### Other Information
OS: Win 10 also Ubuntu
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by ayiire** [comment]
Same as my issue here. Seems like there is a bug somewhere.

https://github.com/PokemonGoF/PokemonGo-Bot/issues/1885

**Comment by inet-pwnZ** [comment]
got something similar #1881

**Comment by AshKetchum07302016** [comment]
same as my issue here
