### ISSUE TITLE
Logger error data with non asccii character

### ISSUE THREAD

**Issue by tuccy** [PokemonGoF/PokemonGo-Bot#1897]
### Expected Behavior
porperly display of correct name

### Actual Behavior
Raise an exception on python lib decode

### Steps to Reproduce
Bot in spain near pokestop with ñ character

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

Fix

pokemongo_bot/logger.py       at line 20

  if color not in color_hex:
###REPLACE START
##DEL        print('[' + time.strftime("%H:%M:%S") + '] ' + string)
##ADD        print('[' + time.strftime("%H:%M:%S") + '] ' + string.decode('utf-8'))
###END RELACE
    else:
        print('[' + time.strftime("%H:%M:%S") + '] ' + u'\033[' + color_hex[color] + string.decode('utf-8') + '\033[0m')
    if lcd:
        if string:
            lcd.message(string)

**Comment by sgitkene** [comment]
#1817 duplicate issue, fix already underway.
