### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by nanoymaster** [PokemonGoF/PokemonGo-Bot#190]
Hi I am getting the following:

Traceback (most recent call last):
  File "./pokecli.py", line 120, in <module>
    main()
  File "./pokecli.py", line 117, in main
    bot.take_step()
  File "/opt/PokemonGo-Bot/bot.py", line 29, in take_step
    self.stepper.take_step()
  File "/opt/PokemonGo-Bot/stepper.py", line 41, in take_step
    self._walk_to(self.config.walk, *position)
  File "/opt/PokemonGo-Bot/stepper.py", line 72, in _walk_to
    dist = self.distance(i2f(self.api._position_lat), i2f(self.api._position_lng), lat, lng)
AttributeError: 'Stepper' object has no attribute 'distance'

any ideas?

**Comment by 2spook5me** [comment]
Looks like they are updating a lot atm, just keep a look out here for updates.
https://github.com/PokemonGoF/PokemonGo-Bot/commits/dev

**Comment by jtdroste** [comment]
What version of the bot are you running? Which branch (Dev or Master)?

**Comment by Calcyfer** [comment]
This should be closed, getting a current copy of stepper.py resolves this error.
`dist = self.distance` should be `dist = distance`, it was fixed in a recent commit.
