### ISSUE TITLE
Python2/3 issues

### ISSUE THREAD

**Issue by sgitkene** [PokemonGoF/PokemonGo-Bot#1902]
### Expected Behavior
Always use python 2.7 for ppl that have python 2 and 3 installed.

### Actual Behavior
whenever run.sh is changed back to python instead of python2, I get an error because it accidentally defaults to python3.

### Steps to Reproduce
Install both python2 and python3, usually then python will mean python3 and python2 will get the right python. Buy a snake.

### Other Information
OS: Arch Linux
Git Commit: 32c611fe2b43d212aa8a46e56f0c6c2f2722b6ec

### Proposed adjustment
In run.sh write python2 instead of python. This will not break anything for users with only python 2 installed, but will help me (and a few others) who have both versions installed, and also may reduce confusion among less experienced users and/or ppl that only have python3 yet.

**Comment by CapCap** [comment]
I'm actively working on supporting py3 as well, but this is a good short term solution.

Can you submit a pull request?
