### ISSUE TITLE
cant get web to work

### ISSUE THREAD

**Issue by captainmustard** [PokemonGoF/PokemonGo-Bot#1903]
I have my gmaps api key and I set my username to my gmail login in the config. Not sure what I'm doing wrong

ian@wintermute ~/PokemonGo-Bot/web $ python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
127.0.0.1 - - [30/Jul/2016 13:56:54] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2016 13:56:54] "GET /main.css HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2016 13:56:54] "GET /main.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2016 13:56:54] "GET /userdata.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2016 13:59:41] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2016 13:59:41] "GET /main.css HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2016 13:59:41] "GET /userdata.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2016 13:59:41] "GET /main.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2016 13:59:42] code 404, message File not found
127.0.0.1 - - [30/Jul/2016 13:59:42] "GET /favicon.ico HTTP/1.1" 404 -

![screenshot from 2016-07-30 14 00 51](https://cloud.githubusercontent.com/assets/4436461/17272529/5fa18e60-565e-11e6-9666-bca1e18eadda.png)

**Comment by mako-taco** [comment]
Can you paste the output of the dev console in the browser (ctrl + shift + j / cmd + opt + j, then refresh the page)? 

Also, make sure you're up to date by running `git submodule sync && git submodule update --init` in the root directory of PokemonGo-Bot.

**Comment by captainmustard** [comment]
![screenshot from 2016-07-30 15 20 02](https://cloud.githubusercontent.com/assets/4436461/17272911/313a0b14-5669-11e6-8a55-065a2110cea3.png)

**Comment by antoineneff** [comment]
You need to enter your Google Maps API key in userdata.js file in web folder.

**Comment by captainmustard** [comment]
It's already entered in there

**Comment by antoineneff** [comment]
If you did, should be defined then ... The console says not.
Can we see your userdata.js file ? Without your key of course.

**Comment by captainmustard** [comment]
![screenshot from 2016-07-30 15 22 20](https://cloud.githubusercontent.com/assets/4436461/17272986/58e562b0-566b-11e6-92f4-612d7e2a8591.png)

**Comment by MartinTerp** [comment]
It should be:
var users = ["USER1"];
var userZoom = true;
var userFollow = true;
var imageExt = ".png";
var gMapsAPIKey = "KEY";

**Comment by ddrght12345** [comment]
Correct. The the format in your screenshot is for the newer version of the map.
Either put it in the format of 
```js
var users = ["USER1"];
var userZoom = true;
var userFollow = true;
var imageExt = ".png";
var gMapsAPIKey = "KEY";
```
or download the most recent master version of the site
