### ISSUE TITLE
Go where I tell you to go!

### ISSUE THREAD

**Issue by skellyton5** [PokemonGoF/PokemonGo-Bot#1907]
I enter a location in the config, but the bot jumps to the last location. I turned it off for hours, so making the jump should be no issue, but now it starts up right where it left off. WTF.  And, its not even heading in the right direction. 

This kind of "oh im going to do whatever the fuck i want to do" behavior is NOT OK.

http://prntscr.com/bzk735

**Comment by sgitkene** [comment]
yo
you need to set location cache in config.json off, otherwise it uses last known location and not the one you entered.

**Comment by skellyton5** [comment]
ok, ty.

/closed
