### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by Parth6182** [PokemonGoF/PokemonGo-Bot#1909]
The app does not open

I changed the config file etc. and started it up it loaded said Pokemongo bot 1.0 and then after a few lines it said No JSON object could be decoded and stopped

OS: El captain 10.11

**Comment by sgitkene** [comment]
Please post the exact errormessage and maybe your configuration.

Try these steps:
Make sure you are using Python2

`sudo pip2 install -r requirements.txt`

in run.sh change python to python2

hope I could help

**Comment by mrthrowaway** [comment]
Also, https://github.com/PokemonGoF/PokemonGo-Bot/wiki/No-JSON-object-could-be-decoded-or-decoder.py-error

**Comment by Parth6182** [comment]
> Also, https://github.com/PokemonGoF/PokemonGo-Bot/wiki/No-JSON-object-could-be-decoded-or-decoder.py-error

I tried to validate my JSON files but it says that my gmail id and password and location are being accepted as undefined terms whereas it expects a string or numbers from me

**Comment by mrthrowaway** [comment]
then you'll have to show us config, minus the username/password/gmaps key

**Comment by Parth6182** [comment]
{
    "auth_service": "google",
    "username": “exampleemail@gmail.com”,
    "password": “examplepassword”,
    "location": “37.791786, -122.391327”,
    "gmapkey": "examplegmapkey",
    "max_steps": 10,
    "catch_pokemon": true,
    "forts": {
      "spin": true,
      "move_to_spin": true,
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "1": { "keep" : 100 },
      "101": { "keep" : 10 },
      "102": { "keep" : 30 },
      "103": { "keep" : 30 },
      "201": { "keep" : 30 },
      "701": { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "evolve_speed": 20,
    "evolve_cp_min": 300,
    "use_lucky_egg": false,
    "hatch_eggs": true,
    "longer_eggs_first": false,
    "evolve_captured": "NONE",
    "release_pokemon": true,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },    
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
        
    } 
}

**Comment by Parth6182** [comment]
^litteraly not changed anything, The json checking website stops showing errors if i remove the username and password and location lines so the problem lies there. My map key works fine

**Comment by mrthrowaway** [comment]
Could you try removing the space between your location coordinates?

**Comment by Parth6182** [comment]
ill try that out

**Comment by Parth6182** [comment]
Nope the username and password, location area is yet invalid ( using a mac )

**Comment by antoineneff** [comment]
The quotes seems to be different, you are using backward quotes, I don't really know the name in english but might be the problem.

**Comment by Parth6182** [comment]
> Yes that might be the case ill check it out my mac defaulted to those quotes automatically

**Comment by Parth6182** [comment]
TY guys its working :D
