### ISSUE TITLE
I'm not able to find any eggs? Does the script pick up eggs?

### ISSUE THREAD

**Issue by IAmTipsy** [PokemonGoF/PokemonGo-Bot#191]
I have been running with you for the last couple of days and so far none of my two accounts have been getting any eggs. Through looking at the outputs from the terminal it does not seem to find any? Does anyone know about this?

**Comment by Klohto** [comment]
Same problem actually

**Comment by harsh1412** [comment]
A script cannot ignore a item which it receives -.-'
All the items we receive goes directly to server's database 
We can't modify it

**Comment by Klohto** [comment]
It's just weird I have 60 pokestops visited and not even one egg

**Comment by harsh1412** [comment]
Well i am getting eggs :D

**Comment by CtrlAltDefeat94** [comment]
I've got 9/9 eggs. 
Try logging in on the account with BlueStacks or your phone and check the journal for items you got from Pokestops. If there are none there, you got none(so just bad luck)
