### ISSUE TITLE
[Feature Request] Implement release logic keep_best_cp OR release_below_cp

### ISSUE THREAD

**Issue by dapearce** [PokemonGoF/PokemonGo-Bot#1919]
Config: `"Ponyta": { "keep_best_cp": 3, "release_below_cp": 600, "logic": "or" }`

### Requested Behavior
Keep a minimum of 3 Ponyta but don't release any over 600cp. 

### Actual Behavior
Keeps only the best 3 CP, will release pokemon over `release_below_cp` if they are 4+ in CP ranking.

**Comment by Parth6182** [comment]
The actual behaviour you have listed is the expected behaviour. The command to keep only the top 3 comes first so the second command of not releasing over 600cp becomes irrelevant. It will only keep the amount of top cp pokemon you choose.

**Comment by dapearce** [comment]
@Parth6182 correct, this is a feature request the default subtitle was misleading, I edited to "Requested Behavior".
