### ISSUE TITLE
Dev branch only walks and release

### ISSUE THREAD

**Issue by surewhynotmon** [PokemonGoF/PokemonGo-Bot#1921]
### Expected Behavior
Capture stops and pokemons

### Actual Behavior
Only saw the initial evolve_all's release routine
Log is full of Server seems to be busy or offline - try again - 1/5   
Walking from 
But when I stop the script, it shows encountered and threw Pokeballs...is it a log level issue so some stop/capture events are ignored?

### Steps to Reproduce
Using included .run.sh to run.

### Other Information
OS: Ubuntu
Git Commit: fc2668a13cdcdb2b9b4b3bcd4105d5632d99ae9f

**Comment by surewhynotmon** [comment]
This might have something to do with Python and OS version....working much better with 2.7.11 on Ubuntu

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
