### ISSUE TITLE
Location override

### ISSUE THREAD

**Issue by cmorbaab** [PokemonGoF/PokemonGo-Bot#1927]
### Expected Behavior
I edited my son file location to a new location and I expected my location to be sent there.
However, I get this message:
`[13:49:44] [x] Parsing cached location...
[13:49:44] 
[13:49:44] [x] Last location flag used. Overriding passed in location
[13:49:44] [x] Last in-game location was set as: (37.76695739625344, -122.42211926362825, 0)
[13:49:44] 
`
To fix this i set my location cache variable to false and I just got soft-banned. Is this the right way to prevent the override is there a better method?

**Comment by ddrght12345** [comment]
1. You need to give it time if you are jumping around locations. The larger the distance, the longer you need to wait.
2. In the data folder is a file called `last-location-username.json`. Delete that file and it will place you at your config's location

**Comment by CapCap** [comment]
Behavior is correct, albeit confusing and maybe could use a y/n confirmation.

Expected behavior:
Location in CLI > Cache in config > location in config

**Comment by skorokithakis** [comment]
Agree with @CapCap, although I'm seeing the cached location take precedence over the CLI. The CLI should always have precedence.
