### ISSUE TITLE
Protobuf not installing: missing zlib

### ISSUE THREAD

**Issue by djycraigslist** [PokemonGoF/PokemonGo-Bot#1929]
I'm trying to install protobuf on my mac and I end up getting this error:

==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/protobuf/3.0.0-beta-4 --with-zlib
Last 15 lines from /Users/danielyoo/Library/Logs/Homebrew/protobuf/02.configure:
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for working memcmp... yes
checking for working strtod... yes
checking for ftruncate... yes
checking for memset... yes
checking for mkdir... yes
checking for strchr... yes
checking for strerror... yes
checking for strtol... yes
checking zlib version... ok (1.2.0.4 or later)
checking for library containing zlibVersion... no
configure: error: in `/private/tmp/protobuf-20160730-37067-1f0ezcb/protobuf-3.0.0-beta-4':
configure: error: --with-zlib was given, but no working zlib library was found
See `config.log' for more details

Any details on how to go around this?

Thanks

**Comment by xorinzor** [comment]
You should ask this question at https://github.com/google/protobuf

These are issues meant for the pokemon bot, not Protobuf

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
