### ISSUE TITLE
pokemon capture adds only curve, previously it was excellent catch with curve

### ISSUE THREAD

**Issue by chauhan-rahul** [PokemonGoF/PokemonGo-Bot#1931]
### Expected Behavior
We should get a perfect throw and the 210 xp that goes with it. 

### Actual Behavior
![image](https://cloud.githubusercontent.com/assets/19290089/17273285/2d1d23a4-56cd-11e6-9fe8-b9345777d1b5.png)

It is only 110 now, all the time.

### Steps to Reproduce
Latesh dev.

### Other Information
OS: WIN7
Git Commit: 83463c2bcd5c4360adbc41c61e6572406fec54ce

**Comment by xc-mezcal** [comment]
I notice that as well. May be related to the randomized_xxx_ factor in the config file.

**Comment by vicch** [comment]
Duplicate of #1843

**Comment by chauhan-rahul** [comment]
closing and using #1843.... tried searchin but didnt find any related bugs!!
