### ISSUE TITLE
[DEV] Evolve_all does not sleep between each evolution

### ISSUE THREAD

**Issue by makistsantekidis** [PokemonGoF/PokemonGo-Bot#1935]
### Expected Behavior

Sleep 20 seconds between each evolution

### Actual Behavior
```
[01:07:20]  Exchanging Shellder [CP 367] [Potential 0.56] for candy!
[01:07:25] Using lucky egg ... you have 5
[01:07:25]  Successfully used lucky egg... (4 left!)
[#] Successfully evolved Krabby with 431 CP and 0.84 IV!
[#] Successfully evolved Magnemite with 390 CP and 0.84 IV!
[#] Successfully evolved Paras with 502 CP and 0.82 IV!
[#] Successfully evolved Magnemite with 265 CP and 0.82 IV!
[#] Successfully evolved Zubat with 295 CP and 0.78 IV!
[#] Successfully evolved Magnemite with 261 CP and 0.78 IV!
[#] Successfully evolved Spearow with 301 CP and 0.69 IV!
[#] Successfully evolved Spearow with 350 CP and 0.64 IV!
[#] Successfully evolved Rattata with 294 CP and 0.56 IV!
[#] Successfully evolved Zubat with 289 CP and 0.47 IV!
[#] Successfully evolved Pidgey with 253 CP and 0.44 IV!
[#] Successfully evolved Zubat with 215 CP and 0.44 IV!
[#] Successfully evolved Poliwag with 282 CP and 0.33 IV!
[#] Successfully evolved Rattata with 182 CP and 0.56 IV!
[#] Successfully evolved Caterpie with 171 CP and 0.22 IV!
[#] Successfully evolved Pidgey with 165 CP and 0.6 IV!
[#] Successfully evolved Poliwag with 154 CP and 0.51 IV!
[#] Successfully evolved Pidgey with 126 CP and 0.44 IV!
[#] Successfully evolved Weedle with 118 CP and 0.13 IV!
[#] Successfully evolved Weedle with 99 CP and 0.44 IV!
[#] Successfully evolved Caterpie with 91 CP and 0.29 IV!
[#] Successfully evolved Caterpie with 71 CP and 0.27 IV!
[#] Successfully evolved Weedle with 68 CP and 0.49 IV!
[#] Successfully evolved Rattata with 67 CP and 0.62 IV!
[#] Successfully evolved Spearow with 66 CP and 0.76 IV!
[01:07:44]  Now at Pokestop: <redacted>
[01:07:44]  Spinning ...
[01:07:44]  Possibly searching too often - taking a short rest :)
```

### Steps to Reproduce
part of config:
```
    "use_lucky_egg": true,
    "evolve_speed": 20,
    "evolve_all": "Pidgey,Rattata,Weedle,Zubat,Caterpie,Paras,Krabby,Spearow,Magnemite,Poliwag",
```
### Other Information
OS: OS X
Git Commit: 8b887a13e162371f3ea057b2c3a3576c90cb11b1
Python 2.7.12

**Comment by xc-mezcal** [comment]
There is a configuration in config file you can set to reduce the speed.

"evolve_speed "  = 20 somehow

check the example json file

**Comment by makistsantekidis** [comment]
`"evolve_speed " = 20` means ~20 seconds between each evolution and it is the configuration I have set for my config file.

As you can see from the timestamps before and after the batch of ~30 evolutions happens in 20 seconds total, whereas they should have taken 20*30 = 600 seconds or more.

**Comment by lucasfevi** [comment]
@makistsantekidis You may have a typo on your JSON: `"evolve_speed" = 20` should be `"evolve_speed" : 20`, notice how I removed space and changed `=` to `:`

**Comment by xc-mezcal** [comment]
Wait definitely it's a :

used = for simple meaning. Sorry if makes trouble

**Comment by Di9** [comment]
I have ":" and still get same result:
[03:42:59]  Ran for 0:00:38
[03:42:59]  Total XP Earned: 58000  Average: 5497168.47/h
[03:42:59]  58 evolved

**Comment by makistsantekidis** [comment]
@lucasfevi Sorry for the typo in the issue, as @xc-mezcal said it is just to convey the value I used, I checked my config file and it is correct. I fixed the issue text to have the actual copy-pasted line of my `evolve_speed` config.

**Comment by makistsantekidis** [comment]
@Di9 Do you mean you have the same problem? Evolution happening too quickly one after the other?

**Comment by xc-mezcal** [comment]
@makistsantekidis  @Di9  Guys, sorry that I can confirm this problem in my old dev, not tested for the new dev. The speed is super fast!

**Comment by makistsantekidis** [comment]
I have not tested it with the new dev, so it's probably best to close this issue and reopen it, if it happens again.

**Comment by TheSavior** [comment]
I haven't heard of this being a problem with the current dev, please re open if still an issue.
