### ISSUE TITLE
[DEV] Path navigation

### ISSUE THREAD

**Issue by kendertas** [PokemonGoF/PokemonGo-Bot#1938]
I think I don't understand how path navigation works.

this is my config.json

> "navigator.type": "path",
	"navigator.path_mode":"loop",
	"navigator.path_file":"pok.json",

and `pok.json` has many coords written like in the `path.example.json`

but it seems not following the waypoints.

Am I missing something?

Thanks.

### Other Information
OS: Windows 10 Home
Git Commit: 7b3f70f4e8e9a58d90d8367e4a75348503e98597

**Comment by sevket** [comment]
Same...
Config:
> "navigator": {
>       "type": "path",
>       "path_mode": "loop",
>       "path_file": "configs/path_test.json"
>     }

Path Config :
> [
>     {"location": "41.0052693,28.9743862"},
>     {"location": "41.0054960,28.9745954"},
>     {"location": "41.0058805,28.9751158"},
>     {"location": "41.0063420,28.9755396"},
>     {"location": "41.0067307,28.9759419"},
>     {"location": "41.0070383,28.9763013"},
>     {"location": "41.0072569,28.9761887"},
>     {"location": "41.0073986,28.9759956"},
>     {"location": "41.0074755,28.9759151"},
>     {"location": "41.0075039,28.9758132"},
>     {"location": "41.0077306,28.9757810"},
>     {"location": "41.0078399,28.9756039"},
>     {"location": "41.0078722,28.9754484"},
>     {"location": "41.0079168,28.9749817"},
>     {"location": "41.0081354,28.9749924"},
>     {"location": "41.0080908,28.9754752"},
>     {"location": "41.0080382,28.9759205"},
>     {"location": "41.0080180,28.9762262"},
>     {"location": "41.0079775,28.9764676"},
>     {"location": "41.0079208,28.9769075"},
>     {"location": "41.0078641,28.9772616"},
>     {"location": "41.0078156,28.9775566"},
>     {"location": "41.0079856,28.9776049"},
>     {"location": "41.0081192,28.9777604"},
>     {"location": "41.0081030,28.9780501"},
>     {"location": "41.0081961,28.9786992"},
>     {"location": "41.0082649,28.9787797"},
>     {"location": "41.0081839,28.9790050"},
>     {"location": "41.0082366,28.9791927"},
>     {"location": "41.0081637,28.9793215"},
>     {"location": "41.0081070,28.9794985"},
>     {"location": "41.0081030,28.9796702"},
>     {"location": "41.0080463,28.9798365"},
>     {"location": "41.0080018,28.9799974"},
>     {"location": "41.0079734,28.9799438"},
>     {"location": "41.0080423,28.9796165"},
>     {"location": "41.0079977,28.9794824"},
>     {"location": "41.0079046,28.9792732"},
>     {"location": "41.0077670,28.9790050"},
>     {"location": "41.0073865,28.9787099"},
>     {"location": "41.0072164,28.9786027"},
>     {"location": "41.0071071,28.9784900"},
>     {"location": "41.0067550,28.9781735"},
>     {"location": "41.0066618,28.9781145"},
>     {"location": "41.0069412,28.9775083"},
>     {"location": "41.0071355,28.9772240"},
>     {"location": "41.0072286,28.9770148"},
>     {"location": "41.0069978,28.9766822"},
>     {"location": "41.0067226,28.9764140"},
>     {"location": "41.0063785,28.9760385"},
>     {"location": "41.0060141,28.9756576"},
>     {"location": "41.0054231,28.9749978"},
>     {"location": "41.0052369,28.9747832"},
>     {"location": "41.0051559,28.9745847"},
>     {"location": "41.0052693,28.9743862"}
> ]

Output :
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.
> [02:12:53] [x] Coordinates found in passed in location, not geocoding.

**Comment by kendertas** [comment]
ok... that's what I understood.
config written in this way

>"navigator.type": "path",
"navigator.path_mode":"loop",
"navigator.path_file":"pok.json",

doesn't work (it's a json, after all)

written in @sevket's way it loads the coords from the file.
That's why all the
`Coordinates found in passed in location, not geocoding.`

I tested the path via OpenPoGoBot, and (even if  it's not accurated) the path was correct.
It spins pokestop found, and catches pokemon.

I'll test more in the next days.

**Comment by DimaVIII** [comment]
If you want him to follow the path you need to set "move_to_spin": false
But anyway the path navigator is with the current commit broken.
