### ISSUE TITLE
Request: Hunter Mode

### ISSUE THREAD

**Issue by RedViper9** [PokemonGoF/PokemonGo-Bot#1940]
It would be great to have the ability to walk directly toward known pokemon locations, similar to how the bot will currently walk directly toward poke-stops.

This would require:
1) Look up pokemon locations at your Lat, Long
Maybe with something like PokeVision [https://pokevision.com/](url)
or the PokemonGO-MAP? [https://github.com/AHAAAAAAA/PokemonGo-Map](url)

2) Set the pathwalker to go in that direction.

3) Update pokemon locations every X seconds.

**Comment by KiraEnishi** [comment]
I thought that was the purpose of catch mode? When you turn going to forts off and leave catch mode on isn't that what the bot is suppose to do? I know that some people are experiencing the bot walking in a set path that resembles an upside down L. If I'm wrong what does catch mode do when going to forts is turned off?

**Comment by Orrielel** [comment]
It only walks around looking for pokemon, in what I assume is a random pattern.
I'd also like this feature, which I guess could be a sub-module that reads the database from PokemonGo-Map and goes directly for those Pokemon and adds them on the BotMap.
