### ISSUE TITLE
No Module named pgoapi.exceptions

### ISSUE THREAD

**Issue by EpicProXD** [PokemonGoF/PokemonGo-Bot#1941]
### Expected Behavior

The bot starts up and runs
### Actual Behavior

Gives Me this Williams-MacBook-Air:~ Mac_OS$ cd '/Users/Mac_OS/PokemonGo-Bot/' && '/usr/local/bin/pythonw' -S -t  '/Users/Mac_OS/PokemonGo-Bot/pokecli.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/Mac_OS/PokemonGo-Bot/pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException
ImportError: No module named pgoapi.exceptions
Williams-MacBook-Air:PokemonGo-Bot Mac_OS$ 

### Steps to Reproduce
Before it said missing inventory blablabla so i reinstalled and it started happening

### Other Information
OS: El capitan

**Comment by pokemule** [comment]
Did you run 'pip install -r requirements.txt'?

**Comment by EpicProXD** [comment]
Yes I have, done multiple reinstalls im using dev

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
