### ISSUE TITLE
[DEV] Bot doesn't catch pokemon anymore, only informs about rustling nearby

### ISSUE THREAD

**Issue by Orrielel** [PokemonGoF/PokemonGo-Bot#1942]
### Expected Behavior
Catching Pokemons after something rustles nearby

### Actual Behavior
Nothing, just repeating rustling, but no error messages.
Pokemon appears on the map, but the bot doesn't engage catch mode.

### Steps to Reproduce
Updated from 2f277fd to 637b7e6
Happens with both path navigator and spiral navigator

### Other Information
OS: Win 7
Git Commit: 637b7e6

Snipped of config:
```
    "max_steps": 5,
    "catch_pokemon": true,
    "forts": {
      "spin": true,
      "move_to_spin": true,
      "avoid_circles": true,
      "max_circle_size": 10
    },
    "navigator": {
      "type": "path",
      "path_mode": "loop",
      "path_file": "configs/path.json"
    },
    "websocket_server": true,
    "walk": 8.32,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "1": { "keep" : 150 },
      "101": { "keep" : 0 },
      "102": { "keep" : 25 },
      "103": { "keep" : 100 },
      "201": { "keep" : 30 },
      "701": { "keep" : 50 }
    },
    "evolve_all": "NONE",
    "evolve_speed": 20,
    "evolve_cp_min": 300,
    "use_lucky_egg": false,
    "hatch_eggs": true,
    "longer_eggs_first": true,
    "evolve_captured": "NONE",
    "release_pokemon": false,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,

```

**Comment by Orrielel** [comment]
Disregard that, I just noticed my Pokemon Bag was full..... Not expected at all :^)

**Comment by DimaVIII** [comment]
I can confirm this issue.
Quick fix: Just restart the bot and wait for 5 -10 min if he doesn't start repeat the restart.
Also set: "move_to_spin": false, otherwise he want move the path...

**Comment by Orrielel** [comment]
Most likely not the same problem as me, but maybe the bot should report if the PokeBag is full when `"catch_pokemon": true`.

**Comment by DimaVIII** [comment]
This issue is not appears from full bags, it also appears sometimes without a reason, the bot is just walking a bit and doing nothing.

**Comment by Orrielel** [comment]
I got mine working now after releasing some of my pokemon, I'll report if I get same or similar issue.
Will just keep this open since you're actually having this issue.

**Comment by Orrielel** [comment]
It does look like that the path navigator isn't following the coordinates in the path_file

**Comment by DimaVIII** [comment]
Set "move_to_spin": false, otherwise he want move the path...
