### ISSUE TITLE
Dev Bot wont login

### ISSUE THREAD

**Issue by pickett2k** [PokemonGoF/PokemonGo-Bot#1943]
Im running this on Windows 7 64-bit

i get multiple errors when i try to run, alot of them seem to relate to greenlet but even easy installing doesn't fix this and i get a DLL error unable to run on win32

i have installed the 64 bit version of python but it just wont login, however the Master version would log in if it wasnt for the Inventory bug

anyone got any ideas? thanks

**Comment by phoenix98787** [comment]
yeap upgrade your Python to 2.7.4 that resolved it for me had this issue all day :+1:

**Comment by pickett2k** [comment]
thanks that helped me move forward, now im getting a cryptodome error and something about OSErro cannot load native model

**Comment by phoenix98787** [comment]
try another Git Pull then 
pip install -r requirements.txt

**Comment by pickett2k** [comment]
no damnit, just tried a full refresh and it still didnt make any difference, still getting a Cryptodome error OSError cannot load native model

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
