### ISSUE TITLE
[Python error] UnicodeDecodeError

### ISSUE THREAD

**Issue by leomont84** [PokemonGoF/PokemonGo-Bot#1947]
Hey, i've got an error when i run the bot : 

UnicodeDecodeError : "ascii" codec can't decode byte 0xc3 in position 44 : ordinal not in range (128).

Sometimes when i run my bot, it works for 1 pokemon or 1 pokestop, then i've got this error. 
So have you any idea to fix this problem ?

There is a picture of all error message
![error](https://cloud.githubusercontent.com/assets/6116422/17273802/da454926-56c3-11e6-87fa-7b4f757b7a0f.png)

**Comment by tuccy** [comment]
solved by me in issue #1897 please commit solution
