### ISSUE TITLE
protoc not found?

### ISSUE THREAD

**Issue by raxxon** [PokemonGoF/PokemonGo-Bot#1954]
### Expected Behavior

Extracted binary into path - Verified it's in path via manual execution

### Actual Behavior

bot runs but debug claims protoc not in path or "other issue"

### Steps to Reproduce

2016-07-30 19:37:26,506 [pgoapi.rpc_api] [DEBUG] Decode raw over protoc (protoc has to be in your PATH):
Couldn't find protoc in your environment OR other issue...
2016-07-30 19:37:26,506 [pgoapi.rpc_api] [DEBUG] Parsing sub RPC responses...

Hazer@Breakpoint MINGW64 /c/pokebot/PokemonGo-Bot (dev)
$ protoc
Missing input file.

### Other Information
OS: Windows10
Git Commit: 
$ git log -n 1 --pretty=format:"%H"
a761db475f22f9db54ba867322c2813277c7a806

**Comment by gregtampa** [comment]
not a bug
please come to slack chat and join #help ask for assistance.
