### ISSUE TITLE
dev version eventlet install

### ISSUE THREAD

**Issue by drew93** [PokemonGoF/PokemonGo-Bot#1955]
why ?????

(PokemonGo-Bot-dev) andrea@ubunturemoto:~/PokemonGo-Bot-dev$ pip install -r requirements.txt
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi (from -r requirements.txt (line 1))
  Skipping because already up-to-date.
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in ./lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): protobuf==3.0.0b4 in ./lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in ./lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in ./lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in ./lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): protobuf-to-dict==0.1.0 in ./lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): googlemaps==2.4.4 in ./lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): colorama==0.3.7 in ./lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): enum34==1.1.6 in ./lib/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): pyyaml==3.11 in ./lib/python2.7/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): haversine==0.4.5 in ./lib/python2.7/site-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): polyline==1.3.1 in ./lib/python2.7/site-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): python-socketio==1.4.2 in ./lib/python2.7/site-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): flask==0.11.1 in ./lib/python2.7/site-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): socketIO_client==0.7.0 in ./lib/python2.7/site-packages (from -r requirements.txt (line 16))
Collecting eventlet==0.19.0 (from -r requirements.txt (line 17))
  Using cached eventlet-0.19.0-py2.py3-none-any.whl
Collecting universal-analytics-python==0.2.4 (from -r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): gpxpy==1.1.1 in ./lib/python2.7/site-packages (from -r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): six in ./lib/python2.7/site-packages (from pgoapi->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./lib/python2.7/site-packages (from protobuf==3.0.0b4->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): future in ./lib/python2.7/site-packages (from s2sphere==0.2.4->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in ./lib/python2.7/site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): python-engineio>=0.8.0 in ./lib/python2.7/site-packages (from python-socketio==1.4.2->-r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in ./lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in ./lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): click>=2.0 in ./lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in ./lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): websocket-client in ./lib/python2.7/site-packages (from socketIO_client==0.7.0->-r requirements.txt (line 16))
Collecting greenlet>=0.3 (from eventlet==0.19.0->-r requirements.txt (line 17))
  Using cached greenlet-0.4.10.zip
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in ./lib/python2.7/site-packages (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in ./lib/python2.7/site-packages (from websocket-client->socketIO_client==0.7.0->-r requirements.txt (line 16))
Building wheels for collected packages: greenlet
  Running setup.py bdist_wheel for greenlet ... error
  Complete output from command /home/andrea/PokemonGo-Bot-dev/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-XKe4bo/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpgB0Nz2pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'greenlet' extension
  creating build
  creating build/temp.linux-i686-2.7
  i686-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c greenlet.c -o build/temp.linux-i686-2.7/greenlet.o
  In file included from greenlet.c:5:0:
  greenlet.h:8:20: fatal error: Python.h: File o directory non esistente
   #include <Python.h>
                      ^
  compilation terminated.
  error: command 'i686-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for greenlet
  Running setup.py clean for greenlet
Failed to build greenlet
Installing collected packages: pgoapi, greenlet, eventlet, universal-analytics-python
  Running setup.py develop for pgoapi
  Running setup.py install for greenlet ... error
    Complete output from command /home/andrea/PokemonGo-Bot-dev/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-XKe4bo/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-3oT3hX-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/andrea/PokemonGo-Bot-dev/include/site/python2.7/greenlet:
    running install
    running build
    running build_ext
    building 'greenlet' extension
    creating build
    creating build/temp.linux-i686-2.7
    i686-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c greenlet.c -o build/temp.linux-i686-2.7/greenlet.o
    In file included from greenlet.c:5:0:
    greenlet.h:8:20: fatal error: Python.h: File o directory non esistente
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'i686-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/andrea/PokemonGo-Bot-dev/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-XKe4bo/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-3oT3hX-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/andrea/PokemonGo-Bot-dev/include/site/python2.7/greenlet" failed with error code 1 in /tmp/pip-build-XKe4bo/greenlet/

**Comment by gregtampa** [comment]
not a bug
please come to slack chat and join #help ask for assistance.
