### ISSUE TITLE
pgoapi problem with python

### ISSUE THREAD

**Issue by crusadox** [PokemonGoF/PokemonGo-Bot#196]
Windows [Versione 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tutti i diritti riservati.

C:\Users\FcInter>C:\Python27\Scripts\pip install -e git://github.com/tejado/pgoa
pi.git#egg=pgoapi
Obtaining pgoapi from git+git://github.com/tejado/pgoapi.git#egg=pgoapi
  Cloning git://github.com/tejado/pgoapi.git to c:\users\fcinter\src\pgoapi
  Error [Error 2] Impossibile trovare il file specificato while executing comman
d git clone -q git://github.com/tejado/pgoapi.git C:\Users\FcInter\src\pgoapi
Cannot find command 'git'

Someone that could help me?

**Comment by 2spook5me** [comment]
http://lmgtfy.com/?q=How+to+install+pip

**Comment by crusadox** [comment]
i installed the others but for this don't work . 
![immagi987690670ne](https://cloud.githubusercontent.com/assets/20598252/17058885/bd33eaf6-5022-11e6-8192-3ae53d816438.png)

**Comment by 2spook5me** [comment]
You still need to install the command git. It is available with a simple googlesearch.

**Comment by crusadox** [comment]
ok thx
