### ISSUE TITLE
Constant updates stopped

### ISSUE THREAD

**Issue by skellyton5** [PokemonGoF/PokemonGo-Bot#1961]
Last night when I was running it, I would get constant updates as to what was happening, and how far it was away from it's goal. Now it doesn't. 

what gives?

**Comment by chauhan-rahul** [comment]
same issue with me.. i need to hit enter in the window, for it to start displaying them agay... but it seems like everything just stops if there is no updates as nothing is being done..

**Comment by gregtampa** [comment]
provide more like your OS and version of bot pull...
get latest if anything

**Comment by skellyton5** [comment]
kk, will do. but its late now. Ill do tomottow
