### ISSUE TITLE
Need help, please.

### ISSUE THREAD

**Issue by Contradriver** [PokemonGoF/PokemonGo-Bot#1962]
When I try to install "PyYAML-3.11-cp27-cp27m-win_amd64.whl" with git bash it shows me this error: "pip2 install PyYAML-3.11-cp27-cp27m-win_amd64.whl". I upgraded pip before, and I don't know what to do.

**Comment by tuccy** [comment]
is not an issue but please first check your python versión pip2 working on python 2.7 and instructions proyect said not supoert on x64 your PyYAML ios x64 ¿match with your python instalation arch?.

Regards

**Comment by Contradriver** [comment]
Do you mean if I upgraded pip? if i try it with x32 it happens the same. I didn't write it correctly. 
It shows me this thing: bash: pip2: command not found

**Comment by leadboots5** [comment]
try doing just pip instead of pip2

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
