### ISSUE TITLE
Pokemon go client update influence catches?

### ISSUE THREAD

**Issue by Bramzor** [PokemonGoF/PokemonGo-Bot#1965]
### Expected Behavior

Normal catching result like a few days ago.

### Actual Behavior

Low amount of catches.

### Steps to Reproduce

Is this related to the upgrade of the client? https://www.reddit.com/r/pokemongo/comments/4vcyra/pokémon_go_0310_update_changelog/
I assume they removed special or most pokemon that before, the server was sending to the client? This will also impact the number of pokemon on the pokemon go maps.
For some reason, the amount of pokemon that the bot detects is a lot lower than in game?

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by gregtampa** [comment]
has to do with steps and stuff...
come over to chat someone can help you
