### ISSUE TITLE
Path Bot is running out of Pokeballs

### ISSUE THREAD

**Issue by DimaVIII** [PokemonGoF/PokemonGo-Bot#1966]
### Expected Behavior
Running on path an spinning all nearby forts.

### Actual Behavior
If the bot is running on path mode he isn't spinning all nearby forts and running so out of pokeballs.
If I set move_to_spin=true he actually want follow the path anymore. 

### Steps to Reproduce
Run on
"navigator": {
      "type": "path",
      "path_mode": "loop",
      "path_file": "configs/path.json"
    },

"forts": {
      "spin": true,
      "move_to_spin": false,
      "avoid_circles": true,
      "max_circle_size": 1
    },

**Comment by gregtampa** [comment]
Reason it is invalid is this is how it should be.
If you put in the fort addresses it will spin them if you set move to spin true
you missing forts in your path...
of course you will run out of balls if your not collecting more.

seems like you shouldnt use path and use default config if you want to have balls and spin.
spiral nav is best*
