### ISSUE TITLE
step by step using install and use web

### ISSUE THREAD

**Issue by fari-99** [PokemonGoF/PokemonGo-Bot#1971]
because there is much people still doesn't know how to install and use it, i think it's time to update the documentation for web. here's my documentation using python simplehtttpserver.

1. after you `pip install -r requirement.txt` run this command to install web

> git submodule init
git submodule update

2. copy userdata.js.example, [copy in the same folder!!] and rename it to userdata.js
3. set your username [your email bot!! not username in-game!!] and set your google map api
4. after that you just run `python -m SimpleHTTPServer [port]`.
5. open browser (in chrome use incognito mode, or just clear chache and history to avoid error), and type `localhost:port ` example: 

> python -m SimpleHTTPServer 8080
 localhost:8080

note for getting google map api (your bot must login!)
1. go to [this](https://developers.google.com/maps/documentation/javascript/get-api-key) url.
2. klik `GET A KEY`
3. create project
4. dont forget to enabling your api.
5. On the Credentials page, get a Browser key (and set the API Credentials). 
Note: If you have an existing Browser key, you may use that key.

**Comment by Mooseymax** [comment]
Wrong area - this is covered on the wiki.
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Google-Maps-API-(web-page)

If you think you can add to that, you should be able to edit the page :)

**Comment by fari-99** [comment]
ah i see, thanks.
