### ISSUE TITLE
No JSON Object Could Be Decoded

### ISSUE THREAD

**Issue by SaipanDamashii** [PokemonGoF/PokemonGo-Bot#1975]
### Expected Behavior
I entered the pokecli.py and hit enter, and this is what happened.  I read up in the Wiki about what to do, but it doesn't quite specify/isn't really clear which json I'm supposed to check, or how I'm supposed to fix it if I find something wrong.  I checked the config.json file, using that website, and this is what happened:

> Error: Parse error on line 2:
> {	"auth_service": “ptc”,	"username": 
> ------------------^
> Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

### Actual Behavior

> (PokemonGo-Bot) Kelvins-MBP-2:PokemonGo-Bot kelvin$ python pokecli.py
> Traceback (most recent call last):
>   File "pokecli.py", line 220, in <module>
>     main()
>   File "pokecli.py", line 197, in main
>     config = init_config()
>   File "pokecli.py", line 64, in init_config
>     load.update(json.load(data))
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
>     **kw)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
>     raise ValueError("No JSON object could be decoded")
> ValueError: No JSON object could be decoded

### Steps to Reproduce
Type pokecli.py and hit enter.

### Other Information
OS: OS X El Capitan
Git Commit: 78c5f2bc8c5aeafb902309583cfab621179bed4e

**Comment by leadboots5** [comment]
Looking at what you copy pasted it looks like you quotes are slanted. Textedit does this by default. Either use something else like text wrangler or this may work...

Under System Preferences > Keyboard, you can change the quotation marks.

Go to the 'Text' sub-menu. On the right-hand side of the box, uncheck the "Use smart quotes and dashes" checkbox.

**Comment by SaipanDamashii** [comment]
Thank you!  I just copy and pasted over with the "normal" quotation marks haha
