### ISSUE TITLE
ImportError: No module named gpxpy

### ISSUE THREAD

**Issue by astr010** [PokemonGoF/PokemonGo-Bot#1976]
### Expected Behavior
./install.sh should install dependencies

### Actual Behavior
the package gpxpy requires sudo for install

### Steps to Reproduce
clone dev branch 
cd PokemonGo-Bot
./install.sh
./run.sh
Error:
ImportError: No module named gpxpy

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Darkmet98** [comment]
https://pypi.python.org/packages/59/88/3dba16d7fd7b1308e1e22c57bc7c593da2cfc8bc827776d8b7380e69dbfb/gpxpy-1.1.1.tar.gz

setup.py install

**Comment by vzaritovsky** [comment]
Did you do `pip install -r requirements.txt` ?

**Comment by astr010** [comment]
I used the install.sh script and received the fail. then I just sudo pip installed it and it works fine.

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
