### ISSUE TITLE
Question about cp_iv_logic

### ISSUE THREAD

**Issue by havenofear** [PokemonGoF/PokemonGo-Bot#1977]
When cp_iv_logic set to "and" for example Pidgey cp>300 iv>80. Should it catch Pidgey with both parameters? If it should be so - it doesn't work. It's catching or iv>80 or cp>300, or i'm doing something wrong? (sry for my english ^:) )

**Comment by leadboots5** [comment]
it would only catch a pidgey if it has both 300+ cp and .8+ IV.

80 IV is not a thing so if thats what you have then that would also be a problem

**Comment by gregtampa** [comment]
wiki

**Comment by themouette** [comment]
Hi, I think it comes from [here](https://github.com/PokemonGoF/PokemonGo-Bot/blob/c5a7109fd82ea4644d4f8a598f5a83bab4361f63/pokemongo_bot/cell_workers/pokemon_catch_worker.py#L234)

It applies logic on the release conditions, so it will release 

`if cp<300 AND iv<.8`

this mean 

`if cp>=300 OR iv>=.8`
