### ISSUE TITLE
item "1" does not exits. check data/items.json error after task supporting level commit.

### ISSUE THREAD

**Issue by AndreAbdel27** [PokemonGoF/PokemonGo-Bot#1981]
### Actual Behavior
pokecli.py: error: item "1" does not exist, spelling mistake? (check for valid item names in data/items.json)

### Steps to Reproduce
after:
git pull
pip install --upgrade -r -requirements.txt

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by pokemule** [comment]
The way you choose which items to keep has changed. Now we use names instead of IDs. So you must edit your config.json and use item names instead of the IDs like so:
"item_filter": {
      "Pokeball":     { "keep" : 100},
      "Greatball":    { "keep" : 100},
      "Ultraball":    { "keep" : 100},
      "Potion":       { "keep" : 0 },
      "Super Potion": { "keep" : 0 },
      "Hyper Potion": { "keep" : 80 },
      "Max Potion":   { "keep" : 30 },
      "Revive":       { "keep" : 80 },
      "Razz Berry":   { "keep" : 100 }
    },

**Comment by AndreAbdel27** [comment]
@pokemule Thanks. it worked.
Although, it's been 2 days getting

**Comment by DayBr3ak** [comment]
@AndreAbdel27  unless you have the 5 tries done and an error crash your bot, that's not a problem

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
