### ISSUE TITLE
Map is no longer tracking users.

### ISSUE THREAD

**Issue by KiraEnishi** [PokemonGoF/PokemonGo-Bot#1982]
Just open the map my bot remains in the same place even though the log is saying I'm going to different pokestops.

commit https://github.com/PokemonGoF/PokemonGo-Bot/commit/dc2fa60b14cd7be1ed689de509e1d32ba63aa4fe

**Comment by srknkrn** [comment]
You should delete latest location file in data folder after giving a new location to bot

**Comment by gregtampa** [comment]
clear your cache files
