### ISSUE TITLE
Bot attempts to throw Pokeballs when there are none

### ISSUE THREAD

**Issue by hobbes3** [PokemonGoF/PokemonGo-Bot#1985]
### Expected Behavior
Throws the next available ball (Ultraball) when there are no Pokeballs and Greatballs.

### Actual Behavior
Attempts to throw a Pokeball anyway and doesn't catch the Pokemon:

<img width="503" alt="screen shot 2016-07-30 at 8 30 12 pm" src="https://cloud.githubusercontent.com/assets/1494403/17274412/7f8da0ac-5694-11e6-86bb-5004bfea1805.png">

### Steps to Reproduce
Have 0 Pokeballs and Greatballs.

I use this config (since I have over 300+ Ultraballs):

    "item_filter": {
      "Pokeball":     { "keep" : 0 },
      "Greatball":    { "keep" : 0 },
      "Potion":       { "keep" : 0 },
      "Super Potion": { "keep" : 0 },
      "Hyper Potion": { "keep" : 0 },
      "Max Potion":   { "keep" : 10 },
      "Revive":       { "keep" : 10 },
      "Razz Berry":   { "keep" : 100 }
    },

### Other Information
OS: Mac OS 10.11.6
Git Commit: 48e0f5b8e14f8490972893def5b16f7fe9883f76

**Comment by xc-mezcal** [comment]
Check PR
https://github.com/PokemonGoF/PokemonGo-Bot/pull/2113
