### ISSUE TITLE
Item 201 does not exist 

### ISSUE THREAD

**Issue by brainz11203** [PokemonGoF/PokemonGo-Bot#1987]
### Expected Behavior
on startup

### Actual Behavior
$ python pokecli.py
[23:41:39]  PokemonGO Bot v1.0
[23:41:39]  No config argument specified, checking for /configs/config.json
usage: pokecli.py [-h] [-cf CONFIG] [-a AUTH_SERVICE] [-u USERNAME]
                  [-ws WEBSOCKET_SERVER] [-p PASSWORD] [-l LOCATION]
                  [-lc LOCATION_CACHE] [--forts.spin FORTS.SPIN] [-w WALK]
                  [-k GMAPKEY] [-ms MAX_STEPS] [-n NAVIGATOR.TYPE]
                  [-pm NAVIGATOR.PATH_MODE] [-pf NAVIGATOR.PATH_FILE]
                  [-d DEBUG] [-t TEST] [-du DISTANCE_UNIT] [-ev EVOLVE_ALL]
                  [-ecm EVOLVE_CP_MIN] [-ec EVOLVE_CAPTURED]
                  [-le USE_LUCKY_EGG] [-rt RECONNECTING_TIMEOUT]
                  [-hr HEALTH_RECORD] [-ac FORTS.AVOID_CIRCLES]
                  [-mcs FORTS.MAX_CIRCLE_SIZE]
                  [--catch_randomize_reticle_factor CATCH_RANDOMIZE_RETICLE_FACT                     OR]
                  [--catch_randomize_spin_factor CATCH_RANDOMIZE_SPIN_FACTOR]
pokecli.py: error: item "201" does not exist, spelling mistake? (check for valid                      item names in data/items.json)

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by berong91** [comment]
Just change all item number to their name. Like this:
````
"item_filter": {
      "Pokeball": { "keep" : 75 },
      "Greatball": { "keep" : 50 },
      "Super Potion": { "keep" : 75 },
      "Super Potion": { "keep" : 20 },
      "Razz Berry": { "keep" : 100 }
    },
````

**Comment by BAMitUp** [comment]
Either do the above, or save the new config example and save that over the old config.json.

**Comment by gregtampa** [comment]
python pokecli.py  <-----reason your not passing config --config ./configs/config.json
[23:41:39] PokemonGO Bot v1.0
[23:41:39] No config argument specified, checking for /configs/config.json
