### ISSUE TITLE
Location Bug: If location have more than 6 decimal numbers bot crash

### ISSUE THREAD

**Issue by DimaVIII** [PokemonGoF/PokemonGo-Bot#1988]
If location have more than 6 decimal numbers bot crash.
### Other Information
Git Commit: dc2fa60b14cd7be1ed689de509e1d32ba63aa4fe

**Comment by DayBr3ak** [comment]
Provide your error log please

**Comment by DimaVIII** [comment]
Bot is doing nothing and google maps api don't work

[05:51:52]  Starting PokemonGo Bot.... 
[05:51:53]  [x] Next egg incubates in 1.00 km 
[05:52:04] Walking from (-73.97305377126574, 40.76756843041008) to [-73.97305377126574, 40.76756843041008] 0.00km
[05:52:16] Walking from (-73.97305377126574, 40.76756843041008) to [-73.97125377126574, 40.76756843041008] 0.20km

**Comment by DimaVIII** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/commit/8b887a13e162371f3ea057b2c3a3576c90cb11b1#commitcomment-18461936

**Comment by ayiire** [comment]
You're getting something similar to what I'm getting here.

https://github.com/PokemonGoF/PokemonGo-Bot/issues/1885

**Comment by DimaVIII** [comment]
@ayiire no, this issue is not related.

**Comment by DimaVIII** [comment]
@ayiire Please read the title: If location have more than 6 decimal numbers bot crash

**Comment by raxxon** [comment]
on the dev branch earlier tonight I was having issues where greater than 6 digits after the decimal was somehow "corrupting" the location values but not crashing the bot. It would work fine until the first time it tried to move and then I'd teleport several hundred kilometers away (long only, lat unaffected). After truncating to 6 sigfig the issue went away. I was in the 32's for lat, -93's for long for startup values
