### ISSUE TITLE
EVOLVE_POKEMON request sent for every Pokémon at every tick

### ISSUE THREAD

**Issue by Moonlight-Angel** [PokemonGoF/PokemonGo-Bot#1990]
Since I'm using it, I noticed the bot was really slow but blamed this on his "human" behavior.
Out of curiosity, I thought running it in debug would be fun and noticed something really strange. Looks like the bot is sending an `EVOLVE_POKEMON` request for every Pokémon at every tick (when using tasks, maybe this was the case even before using tasks).
I tried to disable the `EvolveAll` task and now the bot is running way faster.

### Expected Behavior
I don't think trying to evolve Pokémon involves sending an `EVOLVE_POKEMON` request for each and every Pokémon.
Maybe there is another way of knowing if a particular Pokémon can be evolved ?

### Actual Behavior
There's an `EVOLVE_POKEMON` request sent for every Pokémon at every tick. That's time consuming and probably explains why the bot is so slow.

### Steps to Reproduce
- Enable the `EvolveAll` task in the configuration file.
- Enable debug mode.
- Notice all the `EVOLVE_POKEMON` requests made at each bot tick.

### Other Information
OS: Arch Linux x86_64 (kernel 4.6.4-1)
Git Commit: b0a7b7cc4ffb5d23d671640965bad7b5446b2409

**Comment by mrthrowaway** [comment]
I guess evolve should trigger at start if opted in and only when candies are received (when pokemon is caught/transfered) and only for the evolution chain the candy is for
