### ISSUE TITLE
Update WEB page

### ISSUE THREAD

**Issue by MrCarlosJr** [PokemonGoF/PokemonGo-Bot#1996]
### Web page
Web page in the master have more options. Update here.
http://imgur.com/a/zBnXp

**Comment by SaipanDamashii** [comment]
How did you get it to work?  Every time I try it, my webpage is just blank/white, with the two buttons in the upper right hand corner...

**Comment by CattDamon** [comment]
Just copy the contents of into web, edit the userdata.js and then python -m HTTPSimpleServer.

It should populate.

**Comment by And0r-** [comment]
The new version of the web project, uses a new format in userdata.js and is moved to a /web/config/ folder.
When this File not exist, you see this blank page.

The new web version is very cool. I hope this will be updated soon

**Comment by zx900930** [comment]
read the openpokegoweb readme.md and make a batch file to update this:

example 

update.bat(dev channel)

```
@echo off
git fetch --all
git reset --hard origin/dev
git pull
pip install -r requirements.txt
IF EXIST ".\web\index.html" (
git submodule foreach git pull origin master
) ELSE (
git submodule init
git submodule update
)
pause
```

**Comment by SaipanDamashii** [comment]
@CattDamon yes, I did that stuff.  It didn't populate lol the screen was still blank and very white.
@zx900930 I feel like an idiot for even asking this, but how do I make a batch file to update that?  Could you possibly walk me through that process?

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
