### ISSUE TITLE
[Suggestion] Only use infinite incubator based on config

### ISSUE THREAD

**Issue by Sayujya** [PokemonGoF/PokemonGo-Bot#1997]
### Expected Behavior

Load only the infinite incubator. Output name, CP, IV of hatched pokemon and candy received.

### Actual Behavior

Loads all incubators

### Steps to Reproduce

Run the program
### Expected Behavior

Load only the infinite incubator. Output name, CP, IV of hatched pokemon and candy received.

### Actual Behavior

Loads all incubators

### Steps to Reproduce

Run the program with hatch eggs flag set to true

**Comment by gregtampa** [comment]
This is how it was made to use all incubators.. why wouldn't you?
you could request a feature to specify in config though.
