### ISSUE TITLE
Softban remedy issues

### ISSUE THREAD

**Issue by SaipanDamashii** [PokemonGoF/PokemonGo-Bot#1998]
### Expected Behavior
I followed the instructions in the Softban section of the Wiki, but instead of running, I got an error and the process terminated.  Other than changing the json file mode from all to poke, and adding the use lucky egg true, I have not changed anything.  After getting this error, I tried to edit the file to remove the lucky egg true part, since I thought that might be the problem.  Then I got the other error (the second block below)

### Actual Behavior

> [2016-07-30 22:32:47] [x] PokemonGO Bot v1.0
> [2016-07-30 22:32:47] [x] Configuration initialized
> [2016-07-30 22:32:47] [x] Coordinates found in passed in location, not geocoding.
> [2016-07-30 22:32:47] 
> [2016-07-30 22:32:47] [x] Address found: 34.009848,-118.496463
> [2016-07-30 22:32:47] [x] Position in-game set as: (34.009848, -118.496463, 0.0)
> [2016-07-30 22:32:47] 
> Traceback (most recent call last):
>   File "pokecli.py", line 220, in <module>
>     main()
>   File "pokecli.py", line 206, in main
>     bot.start()
>   File "/Users/kelvin/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
>     self._setup_api()
>   File "/Users/kelvin/PokemonGo-Bot/pokemongo_bot/__init__.py", line 151, in _setup_api
>     player = response_dict['responses']['GET_PLAYER']['player_data']
> TypeError: 'bool' object has no attribute '__getitem__'
> 

After removing the lucky egg true
> Traceback (most recent call last):
>   File "pokecli.py", line 220, in <module>
>     main()
>   File "pokecli.py", line 197, in main
>     config = init_config()
>   File "pokecli.py", line 64, in init_config
>     load.update(json.load(data))
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
>     **kw)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
>     obj, end = self.scan_once(s, idx)
> ValueError: Expecting property name: line 17 column 1 (char 433)

### Steps to Reproduce
Change mode in json file from all to poke.
Add use lucky egg true.
type python pokecli.py, hit enter.
Remove lucky egg true from json file.
Type python pokecli.py, hit enter.

### Other Information
OS: OS X El Capitan
Git Commit: 78c5f2bc8c5aeafb902309583cfab621179bed4e

**Comment by SaipanDamashii** [comment]
Ok so I tried it again, this time I deleted an extra comma I had at the end of the last line of the json (from when I tried to add use lucky egg true), then I closed the file this time and tried to run the code again.  I was able to go through the initial configuration messages this time, but then after the position in game part I got another error:

> Traceback (most recent call last):
>   File "pokecli.py", line 220, in <module>
>     main()
>   File "pokecli.py", line 206, in main
>     bot.start()
>   File "/Users/kelvin/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
>     self._setup_api()
>   File "/Users/kelvin/PokemonGo-Bot/pokemongo_bot/__init__.py", line 159, in _setup_api
>     balls_stock = self.pokeball_inventory()
>   File "/Users/kelvin/PokemonGo-Bot/pokemongo_bot/__init__.py", line 234, in pokeball_inventory
>     inventory_dict = inventory_req['responses']['GET_INVENTORY'][
> KeyError: 'GET_INVENTORY'
> 

What's going on??  Why do I keep getting errors now?

**Comment by Philipp59** [comment]
what branch are you using ?
Can you post your config?

**Comment by douglascamata** [comment]
bad server responses

**Comment by SaipanDamashii** [comment]
ok so I got the thing to run, finally....I set it to poke, and then after the 36th capture attempt, I went a while without seeing any pokemon (it just kept on walking and searching and walking and searching for a while, before it finally caught another pokemon.  I guess this method of brute force softban remedy is legit.

> [2016-07-30 23:10:30] [#] Finished walking
> [#] (34.004847999999996, -118.49396300000001, 0)
> [2016-07-30 23:10:37] [#] Scanning area for objects (19 / 100)
> [2016-07-30 23:10:37] [#] Walking from (34.004847999999996, -118.49396300000001) to (34.004847999999996, -118.496463) for approx. 6.00 seconds
> [2016-07-30 23:10:45] [#] Finished walking
> [#] (34.004847999999996, -118.496463, 0)
> [2016-07-30 23:10:55] [#] Scanning area for objects (20 / 100)
> [2016-07-30 23:10:55] [#] Walking from (34.004847999999996, -118.496463) to (34.004847999999996, -118.498963) for approx. 6.00 seconds
> [2016-07-30 23:11:06] [#] Finished walking
> [#] (34.004847999999996, -118.498963, 0)
> [2016-07-30 23:11:17] [#] Scanning area for objects (21 / 100)
> [2016-07-30 23:11:17] [#] Walking from (34.004847999999996, -118.498963) to (34.004847999999996, -118.501463) for approx. 6.00 seconds
> [2016-07-30 23:11:26] [#] Finished walking
> [#] (34.004847999999996, -118.501463, 0)
> [2016-07-30 23:11:38] [#] Scanning area for objects (22 / 100)
> [2016-07-30 23:11:38] [#] Walking from (34.004847999999996, -118.501463) to (34.007348, -118.501463) for approx. 7.00 seconds
> [2016-07-30 23:11:46] [#] Finished walking
> [#] (34.007348, -118.501463, 0)
> [2016-07-30 23:11:59] [#] Scanning area for objects (23 / 100)
> [2016-07-30 23:11:59] [#] Walking from (34.007348, -118.501463) to (34.009848, -118.501463) for approx. 7.00 seconds
> [2016-07-30 23:12:12] [#] Finished walking
> [#] (34.009848, -118.501463, 0)
> [2016-07-30 23:12:26] [#] Scanning area for objects (24 / 100)
> [2016-07-30 23:12:26] [#] Walking from (34.009848, -118.501463) to (34.012347999999996, -118.501463) for approx. 7.00 seconds
> [2016-07-30 23:12:37] [#] Finished walking
> [#] (34.012347999999996, -118.501463, 0)
> [2016-07-30 23:12:50] [#] Scanning area for objects (25 / 100)
> [2016-07-30 23:12:50] [#] Walking from (34.012347999999996, -118.501463) to (34.014848, -118.501463) for approx. 7.00 seconds
> [2016-07-30 23:12:58] [#] Finished walking
> [#] (34.014848, -118.501463, 0)
> [2016-07-30 23:13:07] [#] Scanning area for objects (26 / 100)
> [2016-07-30 23:13:07] [#] Walking from (34.014848, -118.501463) to (34.017348, -118.501463) for approx. 7.00 seconds
> [2016-07-30 23:13:16] [#] Finished walking
> [#] (34.017348, -118.501463, 0)
> [2016-07-30 23:13:28] [#] Scanning area for objects (27 / 100)
> [2016-07-30 23:13:28] [#] Walking from (34.017348, -118.501463) to (34.017348, -118.498963) for approx. 6.00 seconds
> [2016-07-30 23:13:30] [#] Something rustles nearby!
> [2016-07-30 23:13:30] [#] A Wild Zubat appeared! [CP 98] [Potential 0.8]
> [2016-07-30 23:13:30] [#] IV [Stamina/Attack/Defense] = [14/9/13]
> [2016-07-30 23:13:33] [x] Using Pokeball (chance: 62.29%)... (176 left!)
> [2016-07-30 23:13:33] [x] Captured Zubat! [CP 98] [IV 0.8]
> [2016-07-30 23:13:33] [x] Captured Zubat! [CP 98]
> 

I don't know what was going on earlier, but it's been fixed.  My question now is, can I go back into my json file and re-add the use lucky egg true without any problems?
