### ISSUE TITLE
[Question] What does "FollowSpiral" do in tasks in the configuration file?

### ISSUE THREAD

**Issue by KiraEnishi** [PokemonGoF/PokemonGo-Bot#1999]
I read the wiki and it says

"Note the last two tasks, MoveToFort and FollowSpiral. When a task is still in progress, it won't run the next things in the list. So it will move towards the fort, on each step running through the list of tasks again. Only when it arrives at the fort and there are no other stops available for it to move towards will it continue to the next step and follow the spiral."

From seeing the difference in running the bot with and without this task it looks like the only difference is that it makes the bot walks to a specific coordinate point instead of a target (BOLD LINES):

> **[00:31:14] Walking from (38.9238585456713, -77.04388373724197) to [38.9238585456713, -77.04388373724197] 0.00km**
[00:31:15]  Server seems to be busy or offline - try again - 1/5
[00:31:16] Moving towards fort Adams Morgan Heritage Trail, 0.07km left
[00:31:16] Arrived at pokestop.
[00:31:16] **Walking from (38.923398, -77.043324) to [38.925658545671304, -77.04388373724197] 0.26km**
[00:31:19] Moving towards fort Adams Morgan Heritage Trail, 0.05km left
[00:31:19] Arrived at pokestop.

Also from the wiki I think it means that it should only do this if there's nothing else to do but as you can see in the code it arrives at the pokestop but it hasn't spin it yet but it moves instead of spinning but it should've have move last after it spins right?

And this is my configuration for the tasks:

```
"tasks": [
        {
            "type": "HandleSoftBan"
        },
        {
            "type": "IncubateEggs",
            "config": {
                "longer_eggs_first": true
            }
        },
        {
            "type": "EvolveAll"
        },
        {
            "type": "CatchVisiblePokemon"
        },
        {
            "type": "CatchLuredPokemon"
        },
        {
            "type": "TransferPokemon"
        },
        {
            "type": "SpinFort"
        },
        {
            "type": "RecycleItems"
        },
        {
            "type": "MoveToFort"
        },
        {
            "type": "FollowSpiral"
        }
    ],
```
That line of code also seems to be the path that create this looping path that some users experience before. #1876 

Is this a bug?

on commit https://github.com/PokemonGoF/PokemonGo-Bot/commit/dc2fa60b14cd7be1ed689de509e1d32ba63aa4fe

**Comment by douglascamata** [comment]
Pay attention to how you structured your task list. You spin forts, then recycle items, move to fort (YOU DON'T SPIN THIS), then u walk in spiral.
