### ISSUE TITLE
[dev] Evolve_all not sleep 

### ISSUE THREAD

**Issue by ryc111** [PokemonGoF/PokemonGo-Bot#2003]
### Expected Behavior
Should sleep some time between two evolve.

### Actual Behavior
[12:50:09]  [x] Next egg incubates in 1.23 km 
[#] Successfully evolved Zubat with 376 CP and 0.78 IV!
[#] Successfully evolved Zubat with 339 CP and 0.76 IV!
[#] Successfully evolved Zubat with 313 CP and 0.76 IV!
[#] Successfully evolved Zubat with 464 CP and 0.69 IV!
[#] Successfully evolved Zubat with 339 CP and 0.6 IV!
[#] Successfully evolved Zubat with 297 CP and 0.47 IV!
[#] Successfully evolved Zubat with 293 CP and 0.27 IV!
[12:50:14]  -- Discarded

### Other Information
OS: Ubuntu 16
Git Commit: 32c611fe2b43d212aa8a46e56f0c6c2f2722b6ec

**Comment by gregtampa** [comment]
why?
