### ISSUE TITLE
Not Able to run the bot

### ISSUE THREAD

**Issue by abs07** [PokemonGoF/PokemonGo-Bot#2006]
### Expected Behavior

I have cloned the dev version and copied and edited config.json with the details.  I am getting this error as i put in ./run.sh.

issues : 1 i couldnt find release_config.json.example
2. steps i followed - cloned, copied and edited config.json. 
3. ./run.sh
### Actual Behavior

Traceback (most recent call last):
  File "pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/var/www/Abhinav/poke/PokemonGo-Bot/pokemongo_bot/__init__.py", line 25, in <module>
    from pokemongo_bot.socketio_server.runner import SocketIoRunner
  File "/var/www/Abhinav/poke/PokemonGo-Bot/pokemongo_bot/socketio_server/runner.py", line 5, in <module>
    from eventlet import patcher, wsgi
  File "/usr/local/lib/python2.7/dist-packages/eventlet/patcher.py", line 4, in <module>
    from eventlet.support import six
  File "/usr/local/lib/python2.7/dist-packages/eventlet/support/__init__.py", line 4, in <module>
    from eventlet.support import greenlets, six
  File "/usr/local/lib/python2.7/dist-packages/eventlet/support/greenlets.py", line 3, in <module>
    import greenlet
ImportError: /usr/local/lib/python2.7/dist-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object

### Other Information
OS: linux
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by mrthrowaway** [comment]
have you run `pip install -r requirements` since your last `git pull`?

**Comment by abs07** [comment]
root@ATOM /var/www # mkdir Abhinav
root@ATOM /var/www # cd Abhinav
root@ATOM /var/www/Abhinav # mkdir poke
root@ATOM /var/www/Abhinav # cd poke
root@ATOM /var/www/Abhinav/poke # git clone --recursive -b dev https://github.com/PokemonGoF/PokemonGo-Bot
Cloning into 'PokemonGo-Bot'...
remote: Counting objects: 5312, done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 5312 (delta 34), reused 0 (delta 0), pack-reused 5235
Receiving objects: 100% (5312/5312), 6.12 MiB | 1.43 MiB/s, done.
Resolving deltas: 100% (2832/2832), done.
Submodule 'web' (https://github.com/OpenPoGo/OpenPoGoWeb.git) registered for path 'web'
Cloning into 'web'...
remote: Counting objects: 1058, done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 1058 (delta 20), reused 0 (delta 0), pack-reused 1013
Receiving objects: 100% (1058/1058), 6.50 MiB | 1.87 MiB/s, done.
Resolving deltas: 100% (130/130), done.
Submodule path 'web': checked out '83463c2bcd5c4360adbc41c61e6572406fec54ce'
root@ATOM /var/www/Abhinav/poke # cd PokemonGo-Bot
root@ATOM /var/www/Abhinav/poke/PokemonGo-Bot # pip install -r requirements.txt
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi (from -r requirements.txt (line 1))
  Cloning https://github.com/tejado/pgoapi.git (to 81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b) to ./src/pgoapi
  Could not find a tag or branch '81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b', assuming commit.
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): protobuf==3.0.0b4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): protobuf-to-dict==0.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): googlemaps==2.4.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): colorama==0.3.7 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): enum34==1.1.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): pyyaml==3.11 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): haversine==0.4.5 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): polyline==1.3.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): python-socketio==1.4.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): flask==0.11.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): socketIO_client==0.7.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): eventlet==0.19.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): universal-analytics-python==0.2.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 18))
Collecting gpxpy==1.1.1 (from -r requirements.txt (line 19))
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading gpxpy-1.1.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from pgoapi->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/dist-packages (from protobuf==3.0.0b4->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): future in /usr/local/lib/python2.7/dist-packages (from s2sphere==0.2.4->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in /usr/local/lib/python2.7/dist-packages (from gpsoauth==0.3.0->-r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): python-engineio>=0.8.0 in /usr/local/lib/python2.7/dist-packages (from python-socketio==1.4.2->-r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from flask==0.11.1->-r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/local/lib/python2.7/dist-packages (from flask==0.11.1->-r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from flask==0.11.1->-r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): click>=2.0 in /usr/local/lib/python2.7/dist-packages (from flask==0.11.1->-r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): websocket-client in /usr/local/lib/python2.7/dist-packages (from socketIO_client==0.7.0->-r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.3 in /usr/local/lib/python2.7/dist-packages (from eventlet==0.19.0->-r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/local/lib/python2.7/dist-packages (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): backports.ssl_match_hostname in /usr/local/lib/python2.7/dist-packages (from websocket-client->socketIO_client==0.7.0->-r requirements.txt (line 16))
Installing collected packages: pgoapi, gpxpy
  Running setup.py develop for pgoapi
  Running setup.py install for gpxpy ... done
Successfully installed gpxpy-1.1.1 pgoapi-1.1.0

root@ATOM /var/www/Abhinav/poke/PokemonGo-Bot # cd configs
root@ATOM /var/www/Abhinav/poke/PokemonGo-Bot/configs # ls
config.json.example       config.json.pokemon.example
config.json.path.example  path.example.json

root@ATOM /var/www/Abhinav/poke/PokemonGo-Bot/configs # cp config.json.example config.json
root@ATOM /var/www/Abhinav/poke/PokemonGo-Bot/configs # ls
config.json          config.json.path.example     path.example.json
config.json.example  config.json.pokemon.example

root@ATOM /var/www/Abhinav/poke/PokemonGo-Bot/configs # nano config.json

root@ATOM /var/www/Abhinav/poke/PokemonGo-Bot/configs # cd ..
root@ATOM /var/www/Abhinav/poke/PokemonGo-Bot # ls
configs             install.sh                    proto                setup.py
CONTRIBUTORS.md     LICENSE                       pylint-recursive.py  src
data                pokecli.py                    README.md            web
docker-compose.yml  pokemongo_bot                 requirements.txt
Dockerfile          pokemon_spawn_locations.json  run.sh
root@ATOM /var/www/Abhinav/poke/PokemonGo-Bot # ./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/var/www/Abhinav/poke/PokemonGo-Bot/pokemongo_bot/__init__.py", line 25, in <module>
    from pokemongo_bot.socketio_server.runner import SocketIoRunner
  File "/var/www/Abhinav/poke/PokemonGo-Bot/pokemongo_bot/socketio_server/runner.py", line 5, in <module>
    from eventlet import patcher, wsgi
  File "/usr/local/lib/python2.7/dist-packages/eventlet/patcher.py", line 4, in <module>
    from eventlet.support import six
  File "/usr/local/lib/python2.7/dist-packages/eventlet/support/__init__.py", line 4, in <module>
    from eventlet.support import greenlets, six
  File "/usr/local/lib/python2.7/dist-packages/eventlet/support/greenlets.py", line 3, in <module>
    import greenlet
ImportError: /usr/local/lib/python2.7/dist-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object

**Comment by abs07** [comment]
@mrthrowaway yes i did.  Please find the full stack what i did from start. Sorry to be messy, but i am a newbie here

**Comment by mrthrowaway** [comment]
May have something to do with different versions of python.

https://github.com/python-greenlet/greenlet/issues/24
https://github.com/python-greenlet/greenlet/issues/25
