### ISSUE TITLE
No task are configured.

### ISSUE THREAD

**Issue by nealqu** [PokemonGoF/PokemonGo-Bot#2012]
Can anyone post me a basic sample task configuration?

**Comment by justinbeatz** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files#configuring-tasks

**Comment by nealqu** [comment]
[02:10:35]  No config argument specified, checking for /configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 490, in <module>
    main()
  File "pokecli.py", line 52, in main
    config = init_config()
  File "pokecli.py", line 124, in init_config
    load.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 20 column 1 - line 49 column 1 (char 426 - 775)

For some reason I get this error. Is it something on my configuration file?

**Comment by pokemule** [comment]
Yeah

**Comment by nealqu** [comment]
Anyone care to share to me a basic running config file? Even a simple walking task would be fine as long as it has no erros. Still need to see how it works.  Thanks in advance.

**Comment by pokemule** [comment]
You can check your config folder and go to config.json.example if you're on the latest dev.
Here:
{
    "auth_service": "google",
    "username": "YOUR_USERNAME",
    "password": "YOUR_PASSWORD",
    "location": "SOME_LOCATION",
    "gmapkey": "GOOGLE_MAPS_API_KEY",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolveAll"
      },
      {
        "type": "RecycleItems"
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort"
      },
      {
        "type": "FollowSpiral"
      }
    ],
    "max_steps": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "Pokeball":       { "keep" : 100 },
      "Potion":         { "keep" : 10 },
      "Super Potion":   { "keep" : 20 },
      "Hyper Potion":   { "keep" : 30 },
      "Revive":         { "keep" : 30 },
      "Razz Berry":     { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "evolve_speed": 20,
    "evolve_cp_min": 300,
    "use_lucky_egg": false,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

**Comment by nealqu** [comment]
It works! I thank you!

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
