### ISSUE TITLE
DEV - this new "Tasks" config style is terrible. 

### ISSUE THREAD

**Issue by Kassius509** [PokemonGoF/PokemonGo-Bot#2015]
This new config style sucks to work with. Just sayin. 
Old Config style, 1 Variable per line, Y or N to activate/deactivate, all options listed. Much simpler.

**Comment by TheSavior** [comment]
For more context as to why we are making this change, and the things it provides down the road, please check out the proposal for this structure: https://github.com/PokemonGoF/PokemonGo-Bot/issues/142

**Comment by matheussampaio** [comment]
I like this new style. Avoid conflicts. You can easily change the order. The only downside is it's more complex.
