### ISSUE TITLE
the "auth_service" error 

### ISSUE THREAD

**Issue by huhjess** [PokemonGoF/PokemonGo-Bot#2016]
I put "auth_service": "google"

however it kept on saying "
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-p PASSWORD] [-l LOCATION] [-lc LOCATION_CACHE] [-m MODE]
                  [-w WALK] [-k GMAPKEY] [-ms MAX_STEPS]
                  [-it INITIAL_TRANSFER] [-d DEBUG] [-t TEST]
                  [-du DISTANCE_UNIT] [-if ITEM_FILTER] [-ev EVOLVE_ALL]
                  [-ec EVOLVE_CAPTURED]
**pokecli.py: error: argument -a/--auth_service is required**

Could Anyone help me with this?

Thanks!!!

**Comment by gregtampa** [comment]
go to the slack chatroom then in #help someone will help you setup the bot correctly
closed: NOT A BUG
