### ISSUE TITLE
[DEV] Bug VIP Configs

### ISSUE THREAD

**Issue by lshaf** [PokemonGoF/PokemonGo-Bot#2021]
### Expected Behavior
I've never put voltorb as vips and it should be detected as VIP

### Actual Behavior
Suddenly when bot fought with Voltorb, it's detected as VIP Pokemon
![image](https://cloud.githubusercontent.com/assets/4636265/17275237/dc459c8c-572a-11e6-8045-1d579f1fc62f.png)

### Steps to Reproduce
just try to catch voltorb somewhere

### Other Information
OS: Windows
Git Commit: 3138249e123ed264fa35699cbba59cb67cec03d8

**Comment by Anakin5** [comment]
You did in fact put him as a VIP in your config. Any: iv >0.9 and this Voltorb has iv 0.93.

**Comment by lshaf** [comment]
haha, I just realize it.
and why Pikachu isn't?

```
[14:27:17]  A Wild Pikachu appeared! [CP 57] [Potential 0.51]
[14:27:17] IV [Stamina/Attack/Defense] = [7/4/12]
[14:27:20] Using Pokeball (chance: 37.08%)... (93 left!)
[14:27:21]  Oh no! Pikachu vanished! :(
```

is condition not implemented here?

**Comment by SvenPe** [comment]
It tried to catch the Pikachu, it just fled before you were able to catch it.

**Comment by lshaf** [comment]
@SvenPe I know, but I put Pikachu on VIP config and why Pikachu didn't recognized as VIP pokemon?
