### ISSUE TITLE
Lower iv pokemon being evolved

### ISSUE THREAD

**Issue by almandot** [PokemonGoF/PokemonGo-Bot#2029]
### Expected Behavior
When attempting to evolve after catching a pokemon, the bot should select the best pokemon of that type.

### Actual Behavior
The bot attempts to evolve the specific pokemon which was just caught. For example, a Rhyhorn with CP 518 and potential 0.73 was caught. The bot evolved that Rhyhorn even though I have another Rhyhorn with CP 336 but potential 0.98.

### Steps to Reproduce
Set evolve_all to "all" and catch a pokemon such that there is now enough candy to evolve it.

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by skorokithakis** [comment]
The bot evolves the best CP pokemon.

**Comment by almandot** [comment]
First time glancing at the code but it looks like it isn't even doing that. It looks like it's evolving the just-caught pokemon regardless of CP/IV. Which I guess is a literal interpretation of the "evolve captured" setting but I thought that setting meant "try to evolve a pokemon type when you capture it" including the rules for which one to evolve and not just "evolve the pokemon you just caught."

https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/cell_workers/pokemon_catch_worker.py#L144-L148
