### ISSUE TITLE
[tasks] add possibility to activate or deactivate task

### ISSUE THREAD

**Issue by arnogues** [PokemonGoF/PokemonGo-Bot#2030]
### Expected Behavior
Adding an activate and deactivate in tasks
```
"tasks": [
    {
      "type": "IncubateEggs",
      "active" : false,
      "config": {
        "longer_eggs_first": true
      }
    }
  ]
```
By default active is true if it's not given in options.

### Actual Behavior
Task cannot be commented inside json file.

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by TheSavior** [comment]
You can remove the task to disable it.
