### ISSUE TITLE
Path of bots is very strange

### ISSUE THREAD

**Issue by arnogues** [PokemonGoF/PokemonGo-Bot#2031]
### Expected Behavior
Bot walk at ramdom
 

### Actual Behavior
The path of bot is very very strange : 
bot one 
![bot 1 path](http://reho.st/self/96c2e379385f80e4e24c04f40fc6bab75118779b.png)
bot two 
![bot 2 path](http://reho.st/self/0d4f54ee201dcb5088437af9f741ade0d8a5d1ed.png)

My configuration file : 
```
{
    "auth_service": "XXX",
    "username": "XXX",
    "password": "XXX",
    "location": "49.050657,2.096715",
    "gmapkey": "XXX",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolveAll",
        "config": {
          "evolve_speed": 20,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems"
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort"
      },
      {
        "type": "FollowSpiral"
      }
    ],
    "max_steps": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "walk": 12,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
        "1": { "keep" : 30 },
        "2": { "keep" : 30 },
        "3": { "keep" : 100 },
        "4": { "keep" : 40 },
        "101": { "keep" : 0 },
        "102": { "keep" : 30 },
        "103": { "keep" : 120 },
        "201": { "keep" : 80 },
        "202": { "keep" : 70 },
        "701": { "keep" : 40 }
    },
    "//initial_transfer":700,
    "//evolve_all": "none",
    "evolve_all": "Pidgey,Rattata,Spearow,Zubat,Drowzee",
    "//evolve_speed": 20,
    "//evolve_captured": "none",
    "cp_min": 600,
    "//use_lucky_egg": false,
    "catch": {
        "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or",  "keep_best_cp": 1, "keep_best_iv": 1},
        "// Example of always catching Rattata:": {},
        "// Rattata": { "always_catch" : true }
    },
    "release": {
        "any": {"release_below_cp": 900, "release_below_iv": 0.90, "logic": "and"},
        "// Example of always releasing Rattata:": {},
        "// Rattata": { "always_release" : true }
    }
}
```

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Altaflux** [comment]
Mine too, just downloaded latest commit and bot just seems to zigzag a lot without really trying to get close to the forts.

**Comment by juanriaza** [comment]
Dupe #2008 

Current solution until it gets fixed is to remove evolve task

**Comment by Moonlight-Angel** [comment]
@juanriaza The evolve task has nothing to do with that.
Current solution is removing the `FollowSpiral` task.

**Comment by Pimentoso** [comment]
+1, today I wanted to only spin pokestops but bot doesn't seem to locate any of them.
Already removed the Evolve task and set evolve_all to NONE.
My tasks
```
"tasks": [
      {
        "type": "RecycleItems"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort"
      },
      {
        "type": "FollowSpiral"
      }
    ],
```

log
```
[11:03:59] Walking from (45.472794351781026, 9.179340343664318) to [45.472794351781026, 9.179340343664318] 0.00m
[11:04:00] Walking from (45.472794351781026, 9.179340343664318) to [45.47459435178103, 9.179340343664318] 200.15m
[11:04:53] Walking from (45.47459435178103, 9.179340343664318) to [45.47459435178103, 9.181140343664318] 140.35m
[11:05:31] Walking from (45.47459435178103, 9.181140343664318) to [45.472794351781026, 9.181140343664318] 200.15m
[11:06:22] Walking from (45.472794351781026, 9.181140343664318) to [45.47099435178102, 9.181140343664318] 200.15m
[11:07:11] Walking from (45.47099435178102, 9.181140343664318) to [45.472794351781026, 9.181140343664318] 200.15m
[11:07:56] Walking from (45.472794351781026, 9.181140343664318) to [45.47459435178103, 9.181140343664318] 200.15m```

**Comment by Altaflux** [comment]
yes, removing FollowSpiral  did the trick,
Removing the  Evolve Task did not help

**Comment by raxxon** [comment]
If you're following a path, shouldn't FollowSpiral be changed to FollowPath?

**Comment by xorinzor** [comment]
I'm agree with the strange path, in fact, my bot is walking away from the fort it's supposed to walk towards to..

![untitled](https://cloud.githubusercontent.com/assets/4212335/17275861/271ceecc-5717-11e6-825a-2f9163700046.png)

**Comment by klingan** [comment]
Mine is stuck at 

[12:14:57]  Starting PokemonGo Bot....
[12:14:57]  [x] Next egg incubates in 3.34 km
[12:14:58]  No lucky eggs... skipping evolve!

**Comment by xorinzor** [comment]
@klingan please create your own issue, that has nothing to do with this issue

**Comment by klingan** [comment]
@xorinzor Just realized it was still the issue with evolve, however it was just walking when Spiral was active... so its not completely unrelated.

**Comment by Drambuie** [comment]
as soon as I remove  FollowSpiral task my bot just stands still

Have disabled all the evolve config and the path is still weird

**Comment by xorinzor** [comment]
@Drambuie the FollowSpiral task will make sure the bot keeps moving when there are no forts nearby to walk towards to (because they are on timeout or because they're simply just not around).

So removing that, would make your bot stand still if there are no things to walk towards to, yes.

**Comment by Drambuie** [comment]
Ok thanks for the explanation, i guess i will just wait for a dev fix as mine does not seem to be moving towards any forts

**Comment by ksawerykarwacki** [comment]
Something is definitely wrong with last dev

![capture](https://cloud.githubusercontent.com/assets/11694791/17276158/82a4f9c0-5720-11e6-9ef5-8dd40e32b0a0.PNG)

**Comment by Pimentoso** [comment]
Any workarounds for this yet?

**Comment by klingan** [comment]
[13:57:33] Moving towards fort Groene Stierenkop, 55.98m left
[13:57:39] Moving towards fort Groene Stierenkop, 50.45m left
[13:57:42] Moving towards fort Groene Stierenkop, 45.11m left
[13:57:50] Moving towards fort Groene Stierenkop, 45.37m left
[13:57:59] Moving towards fort Groene Stierenkop, 48.74m left
[13:58:07] Moving towards fort Groene Stierenkop, 49.87m left
[13:58:20] Moving towards fort Groene Stierenkop, 55.55m left

**Comment by beranPro** [comment]
Same Problem as @arnogues here

**Comment by Pimentoso** [comment]
Installing the bot again in a new folder seems to have fixed the issue. Are there some cache files to try to delete in cases like this?

**Comment by beranPro** [comment]
Didn't fixed the issue. Used example configs.

**Comment by iruy** [comment]
Is there any fix for avoid removing `FollowSpiral`?

**Comment by iruy** [comment]
I tried to dig a bit into FollowSpiral code, and here is the result with few Spiral POI calculated [LINK](http://jsfiddle.net/ZLuTg/1311/)
So, considering that when the last POI is reached the path is followed in reverse order, `max_step` should never be less than 9, if you want a spiral path.
