### ISSUE TITLE
Bot doesn't release like expected

### ISSUE THREAD

**Issue by letomcat** [PokemonGoF/PokemonGo-Bot#2039]
### Expected Behavior

Bot should release any pokemon with cp below 400 and iv below 0.9 and then should only keep one with the best iv.

### Actual Behavior

Bot only keeps pokemon with best iv and doesn't care about the other configuration.

### Steps to Reproduce

Use this in the release config part:

```json
"release": {
      "any": {"release_below_cp": 400, "release_below_iv": 0.9, "logic": "or"},
      "any": { "keep_best_iv": 1 }
}
```

### Other Information
Linux 4.4.11+ armv6l
Git Commit: bdaddec9ee64691e5b0a8bda55bf76f83442232f

**Comment by berong91** [comment]
It's the logic I think, let try this:
````
"any": {"release_below_cp": 400, "release_below_iv": 0.9, "logic": "and"},
"any": { "keep_best_iv": 1 }
````
or 
````
"any": {"release_below_cp": 400, "release_below_iv": 0.9, "keep_best_iv": 1, "logic": "or"},
"// anything else": { }
````

**Comment by xorinzor** [comment]
You cant put `any` twice. It will override the previous `any`

**Comment by Anakin5** [comment]
Is it implemented like that today. Your configuration may be confusing:
Does it mean you want to keep only the best iv, but only if it has come greater than 400 or iv greater than 0.9. And if not keep nothing ?
Or does it mean that you want to keep all Pokémon with cp greater than 400 or iv greater than 0.9, and if none exists with such criteria, you still want to keep the best cp ?

To avoid this kind of headaches, it looks like parameters are exclusive. If you choose to keep the best cp/iv, other parameters won't be used.

**Comment by letomcat** [comment]
```json
"release": {
    "any": {"release_below_cp": 400, "release_below_iv": 0.9, "keep_best_iv": 1, "logic": "or"},
    "// anything else": { }
}
```

I tried that, but that is also not working…

> Does it mean you want to keep only the best iv, but only if it has come greater than 400 or iv greater than 0.9. And if not keep nothing ?

Yeah that's exactly, what I want.

**Comment by xorinzor** [comment]
@letomcat there's currently not an option to do so I'm afraid.

**Comment by xorinzor** [comment]
```
"catch": {
    "any": {"catch_above_cp": 400, "catch_above_iv": 0.9, "logic": "or"},
    "// anything else": { }
},
"release": {
    "any": {"keep_best_iv": 1},
    "// anything else": { }
}
```

That should do the trick

**Comment by letomcat** [comment]
Yeah but then I wouldn't get the XP for catching...

**Comment by berong91** [comment]
I think it should be like this:
````
"any": {"release_below_cp": 100, "release_below_iv": 0.8, "logic": "or", "keep_best_iv": 2, "logic": "or" },
````

Here's what I get from making that changes:
````
[03:36:12]  Keep 2 best Pidgey, based on iv 
[03:36:12]  Pidgey [CP 371] [Potential 0.51] 
[03:36:12]  Pidgey [CP 158] [Potential 0.42] 
[03:36:12]  Transferring 2 pokemon 
[03:36:12]  Exchanging Pidgey [CP 90] [Potential 0.33] for candy! 
[03:36:15]  Exchanging Pidgey [CP 107] [Potential 0.38] for candy! 
[03:36:18]  Keep 2 best Dratini, based on iv 
[03:36:18]  Dratini [CP 460] [Potential 0.8] 
[03:36:18]  Dratini [CP 511] [Potential 0.78] 
[03:36:18]  Transferring 2 pokemon 
[03:36:18]  Exchanging Dratini [CP 585] [Potential 0.71] for candy! 
[03:36:22]  Exchanging Dratini [CP 452] [Potential 0.76] for candy! 
[03:36:25]  Keep 2 best Spearow, based on iv 
[03:36:25]  Spearow [CP 372] [Potential 0.76] 
[03:36:25]  Spearow [CP 331] [Potential 0.78] 
[03:36:25]  Transferring 2 pokemon 
[03:36:25]  Exchanging Spearow [CP 292] [Potential 0.53] for candy! 
[03:36:28]  Exchanging Spearow [CP 281] [Potential 0.49] for candy! 
[03:36:30]  Keep 2 best Nidoran F, based on iv 
[03:36:30]  Nidoran F [CP 292] [Potential 0.49] 
[03:36:30]  Nidoran F [CP 10] [Potential 0.44] 
[03:36:30]  Transferring 2 pokemon 
[03:36:30]  Exchanging Nidoran F [CP 311] [Potential 0.38] for candy! 
[03:36:33]  Exchanging Nidoran F [CP 335] [Potential 0.33] for candy! 
[03:36:34]  Keep 2 best Nidoran M, based on iv 
[03:36:34]  Nidoran M [CP 56] [Potential 0.71] 
[03:36:34]  Nidoran M [CP 453] [Potential 0.44] 
[03:36:34]  Transferring 1 pokemon 
````

**Comment by xorinzor** [comment]
@letomcat I'm afraid thats currently the only way of implementing the logic you want

@berong91 that's not how JSON works

**Comment by WillM88** [comment]
@berong91 Lol that doesn't look good. You're exchanging your higher cp dratinis right there!

**Comment by berong91** [comment]
Hah I'm not sure how they parse `"logic" : "and/or"` into a real statement, so I just assume there's some kind of parser to convert the each sentence into one statement. Like the above statement will turn into 
(a and b or c) or ...

**Comment by xorinzor** [comment]
@berong91 well, like I explained in a comment above, a `key` must be unique, so defining `logic` twice, does absolutely nothing except overriding the previous value. order is not a factor here.

The bot just has no logic implemented to handle this all within the `release` rule alone, you'd have to combine it with the `catch` rule as I wrote in my example

**Comment by berong91** [comment]
@xorinzor Interesting. I read something about applying tree structure for the JSON config file a few minutes ago, now it's clearly to me that it's out of the current scope. But still, then I'm curious about other of logic checking? It must be hard coding somewhere in the code right, the other of which one will be checked first, `release_below_cp`, `release_below_iv` or `keep_best_iv`.

**Comment by xorinzor** [comment]
@berong91  It's not a matter of which to check first, but rather, what to do if keep_best_iv is `true` or `false`.

Currently, as far as I'm aware, when `keep_best_iv` is `true` it will always keep the highest IV, and release others, (the same for `keep_best_cp`).

When `false` it will fallback to the `release_below_cp` and `release_below_iv` values

**Comment by crusardri** [comment]
#1530 
I guess this suggestion will solve this problem
