### ISSUE TITLE
Catch_under_cp?

### ISSUE THREAD

**Issue by WillM88** [PokemonGoF/PokemonGo-Bot#2042]
Is there a catch under cp option? I'm running out of pokeballs because of the high cp pidgeys and such. Anyone else having this problem?

**Comment by astose** [comment]
modify your release_config.json to your needs.

**Comment by astose** [comment]
However, if you want not to capture pokemon that have IV higher than default value (0.8) and have for example CP < 100, you'll have to replace the lines in `def should_release_pokemon` in pokemon_catch_worker.py and evolve_all_worker.py.

`
if 'release_under_iv' in release_config:
                min_iv = release_config['release_under_iv']
                if iv < min_iv:
                    release_results['iv'] = True
                else:
                    if release_results['cp'] == True:
                        release_results['iv'] = True
`

**Comment by WillM88** [comment]
@astose  Thank you!
