### ISSUE TITLE
How can i make the bot release all pokes and only keep the strongest one of each kind

### ISSUE THREAD

**Issue by Parth6182** [PokemonGoF/PokemonGo-Bot#2045]
And in which config do i put the command?

**Comment by katanakiwi** [comment]
Run the bot with this in any config file.
```
"release": {
      "any": {"keep_best_cp": 1}
},
```

Also please, don't make issues for this. You can find this out by simply reading the wiki.

**Comment by Parth6182** [comment]
Thanks :D
