### ISSUE TITLE
[Dev]bot gets stuck between following path and moving to fort

### ISSUE THREAD

**Issue by Ced4** [PokemonGoF/PokemonGo-Bot#2046]
### Expected Behavior
Follow Path and stop at forts to spin

### Actual Behavior
get stuck between moving a fort that is not on the path and following the path. A

### Steps to Reproduce
put 
>       {
>         "type": "SpinFort"
>       },
> 	  {
>         "type": "MoveToFort"
>       },
>       {
>         "type": "FollowPath"
>       }
into config and wait till the bot wants to spin a fort that's not directly on the path

### Other Information
newest DEV commit

Seems like the "move to fort" and the "follow path" algorithm run against each other.

**Comment by xorinzor** [comment]
Please don't open bogus issues.

**Comment by raxxon** [comment]
Drop MoveToFort if you're using a path....

**Comment by Ced4** [comment]
> Please don't open bogus issues.
Sorry, just hit the enter-button accidentally.

**Comment by Ced4** [comment]
> Drop MoveToFort if you're using a path....

Yeah, that works. But I thougt, that FollowPath would be an alternative for FollowSpiral. So that the bot would work at the forts until they are on timeout and then gonna continue following the given path.

**Comment by raxxon** [comment]
You're giving the code too much intelligence. ;)  Right now these are 2 different movement paradigms and therefor are technically mutually exclusive. Basically with both active the movement goes split-brain and if the Stop that the FollowSpiral has latched on to is in opposition to your FollowPath marker then they go back and forth basically arguing over who's right and your bot goes nowhere....

**Comment by Ced4** [comment]
Okay, thanks! I'll take this answer as: "it's not a bug, it's a feature :P" xD
Gonna plan my path more accurate so that it passes all forts that are nearby.

**Comment by raxxon** [comment]
Yeah, I spent a half hour or so with Google Maps to get all the GPS points for my loop. ;)
