### ISSUE TITLE
Stops working after 20 minutes

### ISSUE THREAD

**Issue by AshKetchum07302016** [PokemonGoF/PokemonGo-Bot#2048]
### Expected Behavior
The bot shouldn't crash at all. 
It should be stable and run 24/7 without crashes.

### Actual Behavior
After 20 minutes the screen from my hyper-v ubuntu 14 machine goes black. Status from the system ist working but the bot stands still, no error messages, just dont work anymore

### Steps to Reproduce
Start and wait 20 min

### Other Information
OS: Ubuntu 14
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by raxxon** [comment]
You might be seeing something similar to https://github.com/PokemonGoF/PokemonGo-Bot/issues/2009  although most of us aren't getting 20 minutes I think.... I haven't seen much more than 9 personally....

**Comment by AshKetchum07302016** [comment]
Thanks for the reply raxxon, i get the: "server seems .. " sometimes but the bot works after this outputs, its maybe a hyper-v thing, but i really need help. Cant let the bot work for more then 20 minutes because i think the hyper-v connection goes in a sleep mode

**Comment by raxxon** [comment]
I'm running direct from Win10 so I'm not sure if hyperv is screwing with you or not, but I wouldn't expect it unless the system is completely non-responding (can't ping, can't get the web interface, etc). I get single entries for "Server seems" while the bot is running and then when it crashes it counts to 5 and dies...

**Comment by AshKetchum07302016** [comment]
The system responds, the bot just stops.. i dont know why, no errors and nothing just stop working

**Comment by raxxon** [comment]
Are you running the bot actively or did you background the process?  What are the last lines of output when the bot goes dead?

**Comment by AshKetchum07302016** [comment]
The bot runs actively. I will post the lines next time. actually it works

**Comment by AshKetchum07302016** [comment]
![image](https://cloud.githubusercontent.com/assets/20744003/17277007/d4bbd20c-5738-11e6-82ac-cb2b650e0430.png)

**Comment by Nathanian** [comment]
Same here, it worked for like 5 Hours today and now it suddenly stops after 1-10 Minutes of work. No Crashes no Errors just stops.
![image](https://cloud.githubusercontent.com/assets/20759070/17278841/fa122000-5766-11e6-9652-48ffc86cb093.png)

**Comment by Nathanian** [comment]
Found the Solution in another Post. I removed the FollowSpiral task, so my bot has no more tasks in his list. If you did the same then you need to give it a new task instead of the spiral task. Example: 
{
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_file": "configs/NY.json"
        }

**Comment by Nathanian** [comment]
Edit : Use the config.json.path.example file as your config instead of the config.json.example

**Comment by AshKetchum07302016** [comment]
hey nathanian, thanks for your help! i will check it and post the updates here
