### ISSUE TITLE
[Suggestion] Bind with Pogo-Optimiser

### ISSUE THREAD

**Issue by seadog007** [PokemonGoF/PokemonGo-Bot#205]
If the bind pgoapi with [Pogo-Optimiser](https://github.com/justinleewells/pogo-optimizer), then it should can display the status like the screenshot below.  
  
![screenshot](https://camo.githubusercontent.com/c687c245284008c3e90d248b1e753f44709c67eb/687474703a2f2f692e696d6775722e636f6d2f335638787731472e706e67)

BTW, you guys really should use Github Issues Label System :)

**Comment by jtdroste** [comment]
> BTW, you guys really should use Github Issues Label System :)

Eventually.  We have to deal with the backlog of issues first!  :)

**Comment by seadog007** [comment]
I found the way to connect Pogo-Optimiser to this project.
But can any one invent me to the slack? I can't use the link in readme.

**Comment by jtdroste** [comment]
I think you'll have to try again in 24 hours @seadog007.  Our slack channel got rate-limited, and we're unable to invite any more people for a bit.  Sorry!

**Comment by surfaace** [comment]
@seadog007 please try again to reach us from slack so this can be handled
