### ISSUE TITLE
[Suggestion] Multithreading

### ISSUE THREAD

**Issue by crusardri** [PokemonGoF/PokemonGo-Bot#2054]
is possible to add multithreading to the bot?

For example, one thread to scan for visible pokemons, lured pokemons and incubating eggs, other thread to move and other thread to spin forts, catch pokemons, manage inventory and pokemons.

I guess the bot skip pokemons and forts with task config, only catch one pokemon, then spin fort, then move, and repeat.

I think this will be a great feature to add because will improve the efficiency of the bot, catch pokemons and spin forts while move.

**Comment by xorinzor** [comment]
Doing these things simountaneously would lose the bot's human-like behaviour though and might lead to soft-bans since it's with the legitimate app not possible to perform these actions in quick succession to eachother

**Comment by crusardri** [comment]
@xorinzor why? in IRL i can move while catch pokemon, and move while spin forts, and manage inventory while i'm moving or catching pokemon

**Comment by xorinzor** [comment]
@crusardri thats true, although I could see an bug coming out of this, the bot tries to spin whenever it's just in range of a pokestop, not when he's actually right on top of it.

Multithreading this could cause the bot to walk away before it spinned the pokestop thus creating a loop.

It could be a good feature, but I don't think much speed will be gained from this honestly, perhaps a few seconds over the course of an hour.

**Comment by crusardri** [comment]
@xorinzor
i see this.
Thread 1: Move
Thread 2: Scan area about pokestops and pokemons
Thread 3: Spin pokestop if is possible, if is not, server will cancel the acction, catch pokemon, if the bot is far away, the pokemon will vanished.

I try to put the same task three times in config, move, move, move, catch, catch, catch, spin, spin, spin, and, this move tree times, catch 0-3 pokemons, and spin 0-3 forts. This take aprox 10 o more sec to move three times.

With one task, will move one time, catch one time, and spin one time, then, repeat

**Comment by crusardri** [comment]
Please, don't let this suggestion die, i guess the bot really need it.

**Comment by crusardri** [comment]
@xorinzor i still test the bot, i set the speed to 90km/h (25m/s) and the bot take 1h to run a path 5km length.
I remove some tasks, and the bot go faster, but still slow.

**Comment by xorinzor** [comment]
@crusardri I have no idea how the settings for the walk-speed work, altough I'm pretty sure this has been broken for a while now.

That said, why would you even want to go 90km/h ? hatching eggs only works up to 13km/h. Just put the bot in a place with a lot of pokestops if you want to farm items and it will work great

**Comment by crusardri** [comment]
@xorinzor yes, i know that, but this is other history.
I set the speed to 90KM/h to test.
If the bot is a "Human like bot", i guess the bot will walk while catch or spin forts.
I try to say the bot will be more efficient with multithreading, do the same thing a lot faster, wall without interruptions, and catch more pokemons in the half time of the actual bot.
