### ISSUE TITLE
My bot seems to be walking the same route & no pokeballs

### ISSUE THREAD

**Issue by peteoconnell** [PokemonGoF/PokemonGo-Bot#2056]
Since grabbing the latest dev, my bot is walking the same route and now it seems I have no pokeballs.

How do I get the bot to use Great Balls instead? I also want the bot to walk to different poke stops and not just walk round and round.

My config is as follows:

{
    "auth_service": "google",
    "username": "???",
    "password": "???",
    "location": "53.4479568,-2.2898822",
    "gmapkey": "???",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolveAll",
        "config": {
          "evolve_speed": 20,
          "use_lucky_egg": true
        }
      },
      {
        "type": "RecycleItems"
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort"
      },
      {
        "type": "FollowSpiral"
      }
    ],
    "max_steps": 10,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 8.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "Pokeball":       { "keep" : 130 },
      "Potion":         { "keep" : 10 },
      "Super Potion":   { "keep" : 20 },
      "Hyper Potion":   { "keep" : 30 },
      "Revive":         { "keep" : 30 },
      "Razz Berry":     { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "evolve_cp_min": 300,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "// any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "any": {"keep_best_cp": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

**Comment by Di9** [comment]
try to del these lines:
```
"forts": {
"avoid_circles": true,
"max_circle_size": 50
},
```

**Comment by beranPro** [comment]
Same here... My Bot is walking a "L"  all the time. How does the fort option impact the route?

**Comment by Di9** [comment]
maybe it helped my just occasionally, otherwise I disable map cache, it also helped me once...

**Comment by peteoconnell** [comment]
The fix to this is to change from FollowSpiral to FollowCluster - this will start walking to poke stops again
