### ISSUE TITLE
[Bug] Server Busy or offline count is incorrect

### ISSUE THREAD

**Issue by xorinzor** [PokemonGoF/PokemonGo-Bot#2057]
### Expected Behavior
Increment the count by 1 each time

### Actual Behavior
stuck at 1

![untitled](https://cloud.githubusercontent.com/assets/4212335/17276684/8ebbdd04-5730-11e6-9198-14b87fe1eb8d.png)

### Steps to Reproduce
Run & wait

### Other Information
OS: Win 10 x64
Git Commit: bdaddec9ee64691e5b0a8bda55bf76f83442232f

**Comment by Gregwar** [comment]
Same thing for me, happen after an exchange

**Comment by raxxon** [comment]
Given the time lapse between these events, I would think that it had a communication error, then had successful communication which reset the count and then had an error again. From the start the app has had connectivity problems and did not handle interruptions in communication well (it has gotten better). Seems like the bot isn't immune to this, just better equipped to recover.

**Comment by xorinzor** [comment]
@raxxon not sure, I think the time lapses are normal because it'd be unwise to re-send the request straight away. also this is still happening on one of the latest `git pull`'s 589ada8f8d7dcc78921a09a848cfd84485423239

**Comment by raxxon** [comment]
I just did a git pull and everything is still functional, I am still seeing the message, but it's never 1 second apart which should be the fastest that it's going to fire a call, usually it's 5 seconds or more which is over the max default set in config.... Have you set it into debug mode and looked at the request timing/density by chance?

**Comment by xorinzor** [comment]
@raxxon not yet, because whenever I enable debug mode I get way too much information for me to see what is actually going on

**Comment by raxxon** [comment]
Scroll back and log files are your friend... ;)  But yeah the debug mode is a serious blitz of info....
