### ISSUE TITLE
Your inventory is full - Not exchanging candies

### ISSUE THREAD

**Issue by myeunggithub** [PokemonGoF/PokemonGo-Bot#206]
[#] Bag Storage: 211/350
[#] Pokemon Storage: 127/250

Using command -c 500

Receive line "[###] Your inventory is full! Please manually delete some items." after every capture:

[x] Captured Drowzee! [CP389] - exchanging for candy
[###] Your inventory is full! Please manually delete some items.
[#] A Wild Staryu appeared! [CP282]
[x] Using Pokeball...
[x] Captured Staryu! [CP282] - exchanging for candy
[###] Your inventory is full! Please manually delete some items.

Pokemon not being exchanged for candies on manual check.

**Comment by Klohto** [comment]
Run latest dev branch, that fixed it for me.
