### ISSUE TITLE
How incubate eggs ?

### ISSUE THREAD

**Issue by Critically** [PokemonGoF/PokemonGo-Bot#2060]
So, my question, how incubate eggs ?

**Comment by mrthrowaway** [comment]
This feature is available in the dev branch at this time through a config setting

https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/configs/config.json.example

**Comment by Critically** [comment]
It's working ?

**Comment by mrthrowaway** [comment]
Working for me at this time, yes

**Comment by Critically** [comment]
Thanks, closing....
