### ISSUE TITLE
unexpected use of lucky egg

### ISSUE THREAD

**Issue by sgitkene** [PokemonGoF/PokemonGo-Bot#2061]
### Expected Behavior
Use lucky eggs only when evolving at least 60 or so pokemon and evolve_all flag is not "NONE"

### Actual Behavior
Suddenly a lucky egg was used, for no apparent reason. I then panicked and stopped the bot, changed in settings to evolve all (to use the lucky egg time).

### Steps to Reproduce
[Pastebin](http://pastebin.com/m0HAKAGS) to orginal config and console log.
Lucky egg use is at [15:05:43] and config is at the bottom.

### Other Information
OS: Arch Linux
Git Commit: 1915aa2456392725764af6397d7aa847933f815a

**Comment by sgitkene** [comment]
It tried to do it again! [Pastebin](http://pastebin.com/50EC3iDk)

**Comment by sgitkene** [comment]
Won't start bot again, I'm scared :(

**Comment by vicch** [comment]
Did you copy from `config.json.example`? Using lucky egg by default:
```
"type": "EvolveAll",
"config": {
"evolve_speed": 20,
"use_lucky_egg": true
}
```
It got me too.

**Comment by sgitkene** [comment]
But... This should only apply lucky egg when evolving, not just randomly!
I figure part of the evolve_all routine starts, it pops lucky egg, but then sets there's nothing to evolve and stops.

**Comment by vicch** [comment]
Didn't check the code, it just happened, so remember to turn it off in config.

**Comment by Pawamoy** [comment]
Happens to me too. Bot is using lucky egg but does not evolve any pokemon. Even worse, if you restart the bot, it will use A SECOND LUCKY EGG, while the first is still working. I hope it cumulates the bonuses...

**Comment by sgitkene** [comment]
It doesn't. At least for me it only tries using. In any case, lucky egg don't stack.

________________________________

**Comment by Pawamoy** [comment]
Yes you're right, I realized that. But the logs say that it is, so it's confusing :)
