### ISSUE TITLE
[REQUEST] Update to new OpenPoGoWeb

### ISSUE THREAD

**Issue by DimaVIII** [PokemonGoF/PokemonGo-Bot#2066]
Would be nice if someone can update to the new version of OpenPoGoWeb.

**Comment by MZorzy** [comment]
git pull origin master ?

**Comment by DimaVIII** [comment]
Was not working...
But I got it now
```
cd web
git reset --hard origin/master
```

Anyway will be nice if a dev can add the new version of OpenPoGoWeb to the main pull.
I can confirm that the new OpenPoGoWeb version is working, looks much better and provide more Pokemon information. 
<img width="840" alt="screen shot 2016-07-31 at 16 20 46" src="https://cloud.githubusercontent.com/assets/8462893/17277085/c4fc02a4-573a-11e6-8ae9-812047cb2a5d.png">

**Comment by MariuszT** [comment]
@DimaVIII Did you update location and format of your config file after git pull? It was changed some time ago.

**Comment by DimaVIII** [comment]
@MariuszT I just renamed config/userdata.js.example to config/userdata.js and add my information.

**Comment by DimaVIII** [comment]
I also changed https://github.com/OpenPoGo/OpenPoGoWeb/blob/master/js/main.js#L233
Removed:
```
      styles: [ 
        { "featureType": "road", "elementType": "geometry.fill", "stylers": [ { "color": "#4f9f92" }, { "visibility": "on" } ] },
        { "featureType": "water", "elementType": "geometry.stroke", "stylers": [ { "color": "#feff95" }, { "visibility": "on" }, { "weight": 1.2 } ] },
        { "featureType": "landscape", "elementType": "geometry", "stylers": [ { "color": "#adff9d" }, { "visibility": "on" } ] },
        { "featureType": "water", "stylers": [ { "visibility": "on" }, { "color": "#147dd9" } ] },
        { "featureType": "poi", "elementType": "geometry.fill", "stylers": [ { "color": "#d3ffcc" } ] },{ "elementType": "labels", "stylers": [ { "visibility": "off" } ] } 
]

```
As the map was ugly as **** and wasn't showing the street names.
(This happens if a dev thinks he is a designer xD)

**Comment by jayhostan** [comment]
yeah much better without those styles :D :D

**Comment by BartKoppelmans** [comment]
Could you help me in getting the map working? Right now I can't see my character at all...

**Comment by jayhostan** [comment]
@BartKoppelmans you have to run the web script from the bot's /web folder.
change the example config file to userdata.js , add your map api key and email, then run a web server from the folder with for example 
 python -m SimpleHTTPServer 8001 
 so your map will run on http://localhost:8001

still the old version of the map is packed with the dev bot, if you want the new one, just override the contents of /web folder with the new map files

**Comment by MartinTerp** [comment]
If you get "origin master", how do you come around the socket.io?

[01/Aug/2016 19:40:02] code 404, message File not found
"[01/Aug/2016 19:40:02] "GET /socket.io/?EIO=3&transport=polling&t=LP7E8F8 HTTP/1.1" 404 -"

**Comment by KeePon79** [comment]
same problem here

"GET /socket.io/?EIO=3&transport=polling&t=LPCLZ-b HTTP/1.1" 404
