### ISSUE TITLE
"Login Error - Server Busy"

### ISSUE THREAD

**Issue by ThomasMW** [PokemonGoF/PokemonGo-Bot#2067]
### Expected Behavior
Normal Login on Windows 7 and Linux [Debian]

### Actual Behavior
Normal Login on Windows 7
"Login error, server busy" on Linux

### Steps to Reproduce
Use exact same build on Linux and Windows, get different results.

### Other Information
OS: Linux [Debian]

As of last night everytime I try to login on my Linux box I get "Login error, server busy". I've been using the Bot on my Linux box for more than a week without any problems.

I was running an older version but even after moving to the latest Master branch I still have the same issue. I can login via the Bot on Windows 7 just fine [Same branch and version]. The Linux box is a server hosted in the US and my Windows client is here at home in the Netherlands. So it could be an IP/GPS matching issue.

Any ideas?

**Comment by ThomasMW** [comment]
Debug Output:

2016-07-31 13:56:39,572 [   rpc_api] [DEBUG] Execution of RPC
2016-07-31 13:56:39,574 [connectionpool] [ INFO] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
2016-07-31 13:56:39,649 [connectionpool] [DEBUG] "POST /plfe/rpc HTTP/1.1" 403 None
2016-07-31 13:56:39,650 [   rpc_api] [DEBUG] Parsing main RPC response...
2016-07-31 13:56:39,650 [   rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 403
2016-07-31 13:56:39,650 [   rpc_api] [DEBUG] HTTP output: 
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.11.1</center>
</body>
</html>
2016-07-31 13:56:39,650 [    pgoapi] [ INFO] Cleanup of request!
2016-07-31 13:56:39,651 [    pgoapi] [ INFO] Login failed!

**Comment by Den1al** [comment]
I got the same also.

**Comment by Zgrkaralar** [comment]
Also I got the same error

**Comment by dheche** [comment]
I think they banned IP from cloud provider (aws, heroku, digitalocean, etc). My box in digitalocean got banned too.

**Comment by ThomasMW** [comment]
Agreed, such a shame. Guess I'm running the bot from home then.

**Comment by Stasmo** [comment]
Can confirm on AWS as well.

**Comment by ThomasMW** [comment]
I've been using PythonAnywhere btw, guess they're within the IP range too.

**Comment by Den1al** [comment]
Confirmed that on my pc the bot works well. Might be VPS providers blockage.

**Comment by bourgouinadrien** [comment]
I launched from my server@home and got the issue.
Did they ban my ip ? :o
