### ISSUE TITLE
Use high level pokeballs when low level pokeballs are still available 

### ISSUE THREAD

**Issue by TianCNCA** [PokemonGoF/PokemonGo-Bot#208]
### Expected Behavior
Use low level pokeball first, if all used or failed more than three times, switch to a higher level pokeball

### Actual Behavior
Keep using Great Ball when there is still normal pokeball left

### Steps to Reproduce
Run the bot to catch some pokemons

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by CtrlAltDefeat94** [comment]
#116 #119
