### ISSUE TITLE
[QUESTION] XP per hour

### ISSUE THREAD

**Issue by Yanush7** [PokemonGoF/PokemonGo-Bot#2080]
Obviously bot have many settings that can be altered by user, and i think it would be good to know if the config used is efficient.
But for that you need something to compare to, so you can decide if you need to tweak more or not.
What is the "good" ratio XP/hour ? What would you consider min, normal, and max that you can get?
(of course im talking only about using the bot in "safe from ban" conditions")

**Comment by jokoast** [comment]
I just agree with you. It could allow us to make the best config.json for the place we bot. 

+1

**Comment by sgitkene** [comment]
I have had XP/h from 4k to 8k. what's yours?

**Comment by Yanush7** [comment]
It seems to be normal to get around 6k-8k xp with considerably "safe" settings. Of course in a good area.
Im curious what is the most efficient walk speed, which still doesn`t trigger ban.
