### ISSUE TITLE
Master Branch Bot continuously failing to start.

### ISSUE THREAD

**Issue by ultiferrago** [PokemonGoF/PokemonGo-Bot#2084]
### Expected Behavior
Start up bot
Bot runs.

### Actual Behavior
Start up bot
One of two errors occurs. Haven't been able to run bot at all today.
Was working fine yesterday.

### Steps to Reproduce
python pokecli.py -cf ulti.json
(ulti.json) http://pastie.org/private/pqtfxciepqnukc1ql6eta
Then the following two errors cycle in and out of occurring.
<img width="706" alt="screen shot 2016-07-31 at 10 40 38 am" src="https://cloud.githubusercontent.com/assets/5969978/17277567/b0ce4fdc-570b-11e6-82ec-31b70884d191.png">
<img width="995" alt="screen shot 2016-07-31 at 10 44 22 am" src="https://cloud.githubusercontent.com/assets/5969978/17277570/c84442d4-570b-11e6-82f9-106451402a83.png">

### Other Information
OS: MacOS 10.12 Beta
Git Commit: 4794ecb9a37ff8915662946be700b00c4d306b7d

The second image shows a frequent error, that has something to do with a status code 52 returned instead of information. Looking into it, it appears to have something to do with the buffer being too small or something. In my own version I have a simple check for the error code and request info again rather than crashing out.

The first image I have no idea, I just started getting it, but I am unable to run any bot currently.

**Comment by ultiferrago** [comment]
No ideas?

**Comment by Baconnaise** [comment]
I get the second error on Master Branch at startup every single time. Sometimes the bot will start if you run it again immediately other times it just won't work. I've had up to six different accounts open and they all get this on initial startup. A couple of them will startup on the second attempt. Dev Branch doesn't fix the issue as Dev Branch doesn't release and evolve as well (if it even works latest does not) as Master.
