### ISSUE TITLE
Pokemons are not being released

### ISSUE THREAD

**Issue by ftykazaf** [PokemonGoF/PokemonGo-Bot#2085]
This is my release_config.json setting

{
	"any": {
		"keep_best_cp": 1
	}
}

**Comment by BlueHaunter** [comment]
Can you create a [Gist](https://gist.github.com/) with the full config file and
also post the command you're running the bot with?

**Comment by ftykazaf** [comment]
<script src="https://gist.github.com/ftykazaf/15d2bbdf4e6a9aab89beb3f08da4144e.js"></script>

**Comment by BlueHaunter** [comment]
Empty comment?

**Comment by ftykazaf** [comment]
https://gist.github.com/ftykazaf/15d2bbdf4e6a9aab89beb3f08da4144e#file-release

**Comment by ftykazaf** [comment]
not knowing how to post a gist sorry...

**Comment by ftykazaf** [comment]
https://gist.githubusercontent.com/ftykazaf/307ea1630f6fd70ba65d7d41477ebb7e/raw/b3f74656d933e8080a3fb5de3e03bb590b5b13a3/Config

The gist of config, hope you can see
