### ISSUE TITLE
UnboundLocalError: local variable 'pokecount' referenced before assignment

### ISSUE THREAD

**Issue by xtriforcex1985** [PokemonGoF/PokemonGo-Bot#2086]
File "/home/ubuntu/workspace/PokemonGo-Bot/pokemongo_bot/__init__.py", line 423, in get_inventory_count
    return pokecount
UnboundLocalError: local variable 'pokecount' referenced before assignment

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by fyberoptik** [comment]
I just had this same problem, couldn't find the source but did manage to get around it by running git pull.
