### ISSUE TITLE
Bot sleep in the bot.heartbeat()

### ISSUE THREAD

**Issue by Stayhomeforever** [PokemonGoF/PokemonGo-Bot#2087]
### Expected Behavior
Bot never fell to sleep

### Actual Behavior
Sleeping alway in the bot.heartbeat() during the "moving towards fort" process.
See the attached Pic.
### Other Information
OS: Win 10 also Ubuntu 15
Git Commit: bdaddec9ee64691e5b0a8bda55bf76f83442232f

![image](https://cloud.githubusercontent.com/assets/20743236/17277564/4c48f2fc-5746-11e6-9a2d-4a975974a4e9.png)

**Comment by Pacane** [comment]
Show what commit/branch you're using.

**Comment by DayBr3ak** [comment]
where is the sleep ? I don't see it

**Comment by Stayhomeforever** [comment]
Bot fell to sleep at the last line.

I use branch 'dev'

**Comment by DayBr3ak** [comment]
I still don't see anything the last line is 'I am in heartbeat' and before that 'Move toward...' what's wrong with this ?

**Comment by Stayhomeforever** [comment]
The last line shows "I am in HeartBeat". Then the bot should be out of the bot.heartbeat(), but he doesn't.
