### ISSUE TITLE
Some print about eggs remaining distance

### ISSUE THREAD

**Issue by jokoast** [PokemonGoF/PokemonGo-Bot#2090]
Hello,

Thank's for your work, the best one and using python (the best language for this kind of bot i think).

Could you add some prints allowing us to see the remaining distance of our eggs ?

I still don't know if we can see when we got the pokemon in and when the bot incubates an egg but just a simple detail of our eggs could be great (and kinda simple).

Thank's a lot.

**Comment by sgitkene** [comment]
[18:56:17]  Exchanging Zubat [CP 284] [Potential 0.53] for candy! 
__[18:56:33]  [x] Next egg incubates in 0.25 km __
[18:56:43] Walking from (47.3729359, 8.5480928) to [47.3729359, 8.5462928] 0.14km

Bot actually does it.

**Comment by jokoast** [comment]
Ooh great. Sorry. My bad.

Good to know :D
