### ISSUE TITLE
Can't install requirements

### ISSUE THREAD

**Issue by iruy** [PokemonGoF/PokemonGo-Bot#2091]
### Expected Behavior
Install 

### Actual Behavior
Getting error from _src/MD2.c:28_

### Steps to Reproduce
I'm getting this error when running "pip install -r requirements.txt" command on my mac.

### Other Information
![schermata 2016-07-31 alle 18 06 19](https://cloud.githubusercontent.com/assets/8875681/17277701/a58ec99c-5749-11e6-95c5-6eb716ac1534.png)
OS: OS X El Capitan 10.11.6

**Comment by Lordedi** [comment]
Did you install requirements from src first ?

**Comment by iruy** [comment]
@Lordedi I didn't know I should do that. Just tried, and ended up with this error:

```
        RuntimeError: maximum recursion depth exceeded
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9h/d8zmc4pd6hx3j_zz7_11g30w0000gn/T/pip-build-08kQcS/pycryptodomex/
```

**Comment by Lordedi** [comment]
Which version do you have master or dev ?

**Comment by iruy** [comment]
Ops, master.. Just switched to dev and I get the same error

**Comment by Lordedi** [comment]
Make à python setup.py in src

**Comment by iruy** [comment]
Still getting that error

`error: Setup script exited with error: command 'gcc-4.2' failed with exit status 1`

**Comment by iruy** [comment]
I finally got it to work. Thank you @Lordedi for your help.
Had to fix some broken links for python. Thanks to `brew doctor`
