### ISSUE TITLE
Full Bag Crashes instead of Transferring

### ISSUE THREAD

**Issue by JohnnyOmm** [PokemonGoF/PokemonGo-Bot#2094]
### Expected Behavior
To transfer pokemon after bag is full or even as soon as I start up the bot

### Actual Behavior
```
[12:23:27] Something rustles nearby!
[12:23:28]
[12:23:28]  Ran for 0:04:24
[12:23:28]  Total XP Earned: 1210  Average: 16476.78/h
[12:23:28]  Travelled 0.03km
[12:23:28]  Visited 11 stops
[12:23:28]  Encountered 4 pokemon, 1 caught, 0 released, 1 evolved, 0 never seen before
[12:23:28]  Threw 4 pokeballs
[12:23:28]  Earned 100 Stardust
[12:23:28]
[12:23:28]  Highest CP Pokemon: Pidgey [CP: 251] [IV: 13/6/5] Potential: 0.53
[12:23:28]  Most Perfect Pokemon: Pidgey [CP: 251] [IV: 13/6/5] Potential: 0.53 
Traceback (most recent call last):
  File "C:\PokemonGo-Bot\pokecli.py", line 532, in <module>
    main()
  File "C:\PokemonGo-Bot\pokecli.py", line 71, in main
    bot.tick()
  File "C:\PokemonGo-Bot\pokemongo_bot\__init__.py", line 90, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\PokemonGo-Bot\pokemongo_bot\cell_workers\catch_visible_pokemon.py", line 29, in work
    return self.catch_pokemon(self.bot.cell['catchable_pokemons'][0])
  File "C:\PokemonGo-Bot\pokemongo_bot\cell_workers\catch_visible_pokemon.py", line 41, in catch_pokemon
    return_value = worker.work()
  File "C:\PokemonGo-Bot\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 36, in work
    raise RuntimeError('Pokemon Bag is full!')
RuntimeError: Pokemon Bag is full!
```

**Comment by Pacane** [comment]
Do you have any recycle Task? show us your config. What branch/commit are you using?

**Comment by JohnnyOmm** [comment]
im using dev branch the most recent commit

`"tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolveAll",
        "config": {
          "evolve_speed": 20,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems"
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort"
      },
      {
        "type": "FollowSpiral"
      }
    ],
    "max_steps": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "Pokeball":       { "keep" : 100 },
      "Potion":         { "keep" : 10 },
      "Super Potion":   { "keep" : 20 },
      "Hyper Potion":   { "keep" : 30 },
      "Revive":         { "keep" : 30 },
      "Razz Berry":     { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "evolve_cp_min": 300,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3},
	  	"any": {"keep_best_cp": 1},
	"any": {"keep_best_iv": 1},

      "// ##### MY RELEASES #####:": {},
    "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
	"Eevee": {"release_below_cp": 500, "release_below_iv": 0.8, "logic": "and"},
	
      "// ##### MY ALWAYS RELEASES #####:": {},
	"Pidgey": { "always_release" : true },
	"Caterpie": { "always_release" : true },
	"Weedle": { "always_release" : true },
	"Rattata": { "always_release" : true },
	
      "// ##### MY NEVER RELEASES #####:": {},
	"Dragonite": { "never_release" : true },
	"Venusaur": { "never_release" : true },
	"Charizard": { "never_release" : true },
	"Blastoise": { "never_release" : true },
	"Nidoqueen": { "never_release" : true },
	"Nidoking": { "never_release" : true },
	"Alakazam": { "never_release" : true },
	"Machamp": { "never_release" : true },
	"Golem": { "never_release" : true },
	"Gengar": { "never_release" : true },
	"Gyarados": { "never_release" : true },
	"Vaporeon": { "never_release" : true },
	"Jolteon": { "never_release" : true },
	"Flareon": { "never_release" : true },
	"Aerodactyl": { "never_release" : true },
	"Articuno": { "never_release" : true },
	"Zapdos": { "never_release" : true },
	"Moltres": { "never_release" : true },
	"Dragonair": { "never_release" : true },
	"Mew": { "never_release" : true },
	"Mewtwo": { "never_release" : true }
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}
`

**Comment by AlexBailey** [comment]
Same issue here, essentially the same config too - the dev branch has always had this issue for me ever since I installed it a couple of days ago. I've gone back to the master for the time being, but would rather use the dev for the features etc
