### ISSUE TITLE
Path followed but does not Spin Pokestops on way

### ISSUE THREAD

**Issue by Drambuie** [PokemonGoF/PokemonGo-Bot#2096]
### Expected Behavior

Would expect bot to follow pre-defined path but to collect Pokestops on the way

      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort"
      },
      {
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_file": "configs/path.test.json"
        }
      }
    ],

Move to fort does not seem to do anything here

### Actual Behavior

Bot follows path and collects pokemon, but does not spin any pokestops that it passes

### Steps to Reproduce

Using the latest dev branch and a path.json file as a route

### Other Information
OS: Ubuntu
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Drambuie** [comment]
Please close I have resolved issue within config

**Comment by littlebigcat** [comment]
What was your fix?
