### ISSUE TITLE
[Idea] Smooth walking instead of teleporting

### ISSUE THREAD

**Issue by tstumm** [PokemonGoF/PokemonGo-Bot#21]
We can move at 2 Meters per second (which would count into egg hatching), more would be okay too (but would be too fast for egg hatching). Teleporting is just too dangerous, so walking should be implemented.

**Comment by mrsmn** [comment]
Maybe a flag so people can disable the teleporting in favor of walking if they prefer it.

**Comment by tstumm** [comment]
Solved be #37, needs to be accepted
