### ISSUE TITLE
Poke balls get over and then the bot doesn't do anything

### ISSUE THREAD

**Issue by Parth6182** [PokemonGoF/PokemonGo-Bot#2100]
The bot just keeps throwing -1 poke balls at wild pokemon when the poke balls are over

Can someone write something to put into the config that makes the bot stop catching pokes if it has 0 poke balls and keep spinning pokestops until it reaches about 50 poke balls then it keeps doing the same thing over and over again

Also something that makes it run from battle or use a better pokeball if it has none

**Comment by xc-mezcal** [comment]
@Parth6182  Previously, master/dev has a feature as what you have stated.

No pokeball -> farming mode.

I don't know when/why they removed it.

**Comment by Parth6182** [comment]
Hopefully someone can come up with something to put into the config file that can make it switch to farming mode until it has a certain amount of poke balls and something that makes it run from battle at 0 poke balls as keeping the bot on overnight is impossible with this error

**Comment by Philipp59** [comment]
"farming mode" would be changing order or disable 
        "type": "CatchVisiblePokemon"
        "type": "CatchLuredPokemon"
tasks by switch
maybe someone can do a pr for it

**Comment by TCB13** [comment]
I also have this issue. Does it help to spin first and then catch?

**Comment by Aaronucci** [comment]
I have the same issue.  When you are talking about switching the mode.. can you disable Catch Visible and Catch lured in a backup config so you can in effect start farming for pokeballs?

I'm out now but he still gets distracted by the pokemon.  If I could do that temporarily until I have poke balls again that would be great.

**Comment by Parth6182** [comment]
The situation seems to get better at about level 20 as there are 3 different types of poke balls and they seems to balance each other out

I would suggest setting the limit to potions and revives in your config files to 0 so the only thing the player stocks up on is different kinds of pokeballs and berries
