### ISSUE TITLE
[Question & Feature Request?] Is it possible to get the name of the going-to-be-hatched Pokemon from the eggs or while incubating them?

### ISSUE THREAD

**Issue by BobbyWibowo** [PokemonGoF/PokemonGo-Bot#2101]
So yeah, as the title says.

If it's possible, I'd like to request for the Pokemon name to be dumped to inventory-USERNAME.json file. I kinda want to implement showing the Pokemon within the egg on the web interface if possible.

**Comment by xorinzor** [comment]
If you mean if the egg has a determined pokemon before it's even hatched, the answer is no. This is randomly decided by the server at the moment of hatching the egg

**Comment by BobbyWibowo** [comment]
Alrighty then. Just a thought.
