### ISSUE TITLE
Bot doesn't catch.......

### ISSUE THREAD

**Issue by gianvoci** [PokemonGoF/PokemonGo-Bot#2118]
The bot seams not catch all pokemon, maybe?

**Comment by regzzz** [comment]
If you mean dev version than same with me. It just walk, spin and hatch egg.

**Comment by gianvoci** [comment]
yes dev version, sometimes catch but rarely........so? we need to install master version?

**Comment by regzzz** [comment]
Up to you. If you want get more XP then use master version (at least now).

**Comment by DayBr3ak** [comment]
Yes no pokemons are caught. That's sad
