### ISSUE TITLE
File "pokecli.py", line 38 ImportError

### ISSUE THREAD

**Issue by nordinlol4** [PokemonGoF/PokemonGo-Bot#2121]
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    import requests
ImportError: No module named requests

Pls help!

**Comment by jomarocas** [comment]
this line working for me thanks

```
pip2 install -r requirements.txt
```

**Comment by paulohdc** [comment]
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: cannot import name ServerSideRequestThrottlingException

**Comment by jrjhealey** [comment]
I have the same issue with no requests module found.

I've run the installation requirements via pip (a couple of versions) and no luck.

Virtualenv is running Python 2.7.11, but have also tried with 2.7.9 and still have the same problem. Virtualenv is version 15.0.2.

Running on a Ubuntu 14.04 box. Weirdly I got it working basically first time on my Mac though.

**Comment by jomarocas** [comment]
@jrjhealey you stay in dev enviroment?

**Comment by jrjhealey** [comment]
Do you mean the dev environment of the bot, or a python dev env?

I do already have pip installed. Multiple versions for that matter, and I have tried several of them. Here's what I currently have:

`ubuntu@joe-3:~/PokemonGo-Bot$ pip` 
`pip     pip2    pip2.7`

and

`ubuntu@joe-3:~/PokemonGo-Bot$ python`
`python             python2.7-config   python2-jsonpatch  python3.4m`
`python2            python2-config     python3            python3m`
`python2.7          python2-jsondiff   python3.4          python-config`

**Comment by paulohdc** [comment]
Now i know what is wrong
you have to do scripts\activate then python pokecli.py -cf ./configs/config.json
the pronpt look like this (PokemonGo-Bot) C:\PokemonGo-Bot>

**Comment by jrjhealey** [comment]
I'm not sure if that was part of the issue or not, I was always activating the virtualenv. However I've circumvented the problem by switching to the dev branch instead of the master.
