### ISSUE TITLE
Can't release nidoran F / M

### ISSUE THREAD

**Issue by bimahp** [PokemonGoF/PokemonGo-Bot#2123]
### Expected Behavior
Nidoran M /F released based on configuration

### Actual Behavior
Nidoran M / F stays

### Steps to Reproduce

> "Nidoran M": { "release_under_cp": 400, "release_under_iv": 0.8, "logic": "and" },
> "Nidoran F": { "release_under_cp": 400, "release_under_iv": 0.8, "logic": "and" },

Catch nidoran.
http://imgur.com/a/gdtBd

### Other Information
Is there any special character for nidorans?
anyway evolve_all works well if i put Nidoran F / M on evolve list, only release that broken

OS: Windows 10 
Git Commit: 3fe8eb07c098c45c87db0d643d579ac4f7464cf6

**Comment by lhung** [comment]
I'm running the latest dev branch and this works for me.
>       "Nidoran M": { "release_below_cp": 156, "release_below_iv": 0.8, "logic": "and" },
      "Nidoran F": { "release_below_cp": 156, "release_below_iv": 0.8, "logic": "and" },

**Comment by bimahp** [comment]
sorry my bad, i didn't check again after copied from old config, should be `release_below` lol
