### ISSUE TITLE
[+110 exp] Bot alwasy catch with 110xp

### ISSUE THREAD

**Issue by DimaVIII** [PokemonGoF/PokemonGo-Bot#2128]
@matheussampaio Bot alwasy catch with 110xp, is the calculation wrong? https://github.com/PokemonGoF/PokemonGo-Bot/commit/3d6b347a578dc6255d8e34810a24010f040acb42

Or is something wrong with this (b91ec50de8996942ffd901c0c135ea5734ba5920) commit and the bot only throwing spin balls?
As "--catch_randomize_reticle_factor" is allow only 1.0 

### my config
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,

### Other Information
Git Commit: All dev

**Comment by lhung** [comment]
curveball bonus?

**Comment by DimaVIII** [comment]
Yes but he also should add excellent bonus +50xp.
If I set "catch_randomize_spin_factor": 0.0 it will do 100xp or 110xp.

**Comment by matheussampaio** [comment]
I'll check that, but we have problems if the throwing code: #1843

**Comment by DimaVIII** [comment]
@kbinani math mistake?
+# Humanized `spin_modifier` parameter for `catch_pokemon` API.
+# 0.0 => normal ball, 1.0 => super spin curve ball

+# Humanized `normalized_reticle_size` parameter for `catch_pokemon` API.
+# 1.0 => normal, 1.950 => excellent

**Comment by DimaVIII** [comment]
fixed https://github.com/PokemonGoF/PokemonGo-Bot/commit/a160fa70c9caa0d0530a9daad6f0914c18f1abda
