### ISSUE TITLE
How to start pokemon go bot while pokemon go map is running in terminal

### ISSUE THREAD

**Issue by Parth6182** [PokemonGoF/PokemonGo-Bot#2129]
The webpage opens up with my character and the pokestops etc. but how to actually start the PokemonGo bot? The python pokecli.py command doesn't work on the terminal while the PokemonGo-Web is running

**Comment by Lunik** [comment]
Use `screen` ? or `&`at the end of your commands to put them in background.

**Comment by Parth6182** [comment]
can you explain further please? my terminal is open my bot is running what would i do to add the webpage too? ( the web file is configured already )

**Comment by Parth6182** [comment]
Nvm lol i just found the option to make a second terminal window :D thanks :) 
# resolved
