### ISSUE TITLE
How to force the bot to use a specified location and not the last used location

### ISSUE THREAD

**Issue by Parth6182** [PokemonGoF/PokemonGo-Bot#2134]
### **Uses location where it left off**

[01:01:05] [x] Coordinates found in passed in location, not geocoding.
[01:01:05] 
[01:01:05] Location Found: 37.787994,-122.407440
[01:01:05] GeoPosition: (37.787994, -122.40744, 0)
[01:01:05] 
[01:01:05] [x] Parsing cached location...
[01:01:05] 
[01:01:05] [x] Last location flag used. Overriding passed in location
[01:01:05] [x] Last in-game location was set as: (37.7963525004378, -122.39431257768616, 0)

**Comment by jayhostan** [comment]
did you pull recent code? this is sorted. checks if config location changed and if yes it overrides last in-game

**Comment by nburn42** [comment]
Turn off use cached location in config file

**Comment by jayhostan** [comment]
it works fine with cached loc. on (and i would keep cached on..)

**Comment by Nathanian** [comment]
if he keeps cached on it will not use the location he sets. So why should he keep it on?

**Comment by jayhostan** [comment]
starting location is stored in the same file as last in-game. so if he changes the starting loc. the bot realises that and overrides cached one.. so new loc. works and avoiding teleports is in place as well. thats why

**Comment by sgitkene** [comment]
just `rm data/location..xxx...` when you want it to not use last location

**Comment by antoineneff** [comment]
Yes, you have to remove the file `data/last-location-username.json` so you have no previous location stored.

**Comment by Parth6182** [comment]
Thanks :D its working now
