### ISSUE TITLE
"Server seems to be busy or offline - try again - 1/5"

### ISSUE THREAD

**Issue by Nexus-** [PokemonGoF/PokemonGo-Bot#2139]
### Expected Behavior

To login, start bot and continue regularly.

### Actual Behavior

![behaviour](http://image.prntscr.com/image/ca4754cf845b4c87b409e700b268761e.png)

### Steps to Reproduce

Simply start the bot. It happens every time.

### Other Information
OS: Windows 10
Git Commit: a160fa70c9caa0d0530a9daad6f0914c18f1abda

**Comment by leovarmak** [comment]
@Nexus Why did you close this ? have you found a solution ?

**Comment by Nexus-** [comment]
d0976105ca75f0c7da182d0fb07b950ab1466893 seems to have fixed the issue, somehow lmao
