### ISSUE TITLE
Bot updating itself?

### ISSUE THREAD

**Issue by KLVN** [PokemonGoF/PokemonGo-Bot#2147]
### Expected Behavior
Only update if I `git pull`.

### Actual Behavior
Updates config.json after first run.

### Steps to Reproduce
Initial: I deleted the folder `PokemonGo-Bot` with `sudo rm -rf PokemonGo-Bot` and copied a backup on my Pi again (backup is an 2 days old dev with an old config.json, see below).
I start the bot, everything runs fine, map is also working. If I stop it now and open my config.json it's the newest config file with these 'tasks'. If I start the bot again now it will transfer all pokemons like instructed in the example file. I lost all my high CP pokemon and the map isn't working anymore... :disappointed: 

old config layout:
`{
    "auth_service": "google",
    "username": "deeznuts@gmail.com",
    "password": "haagoteem",
    "location": "37.797904, -122.408905",
    "gmapkey": "elgoog",
    "max_steps": 300,
    "catch_pokemon": true,
    "websocket_server": true,
    "spin_forts": true,
    "walk": 20,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "1": { "keep" : 40 },
      "2": { "keep" : 80 },
      "101": { "keep" : 10 },
      "102": { "keep" : 20 },
      "103": { "keep" : 30 },
      "201": { "keep" : 30 },
      "701": { "keep" : 30 }
    },
    "evolve_all": "NONE",
...`

### Other Information
OS: Raspbian on a Raspberry Pi
Git Commit: 3dc8e8ba39151130e987e39796ad6151c9ee5c67
Python Version: Python 2.7.9

**Comment by xorinzor** [comment]
The config has changed throughout the dev-builds the last couple of days so whenever you do a `git pull` you should compare your `config.json` with the `configs/config.json.example` to make sure it's still good to go.

**Comment by KLVN** [comment]
> whenever you do a `git pull`

The funny thing is that I never did a `git pull`. Just re-ran the bot and everything changed.

> paste your full config file

That was my old config file where everything was fine. The updated config.json transfered all pokemon < 300 CP `or` < 0.8 IV (i think)

> I really hope for you that's not your real email and password

Don't worry :D

**Comment by xorinzor** [comment]
@KLVN well, the bot shouldn't update itself, 99.9% sure that isn't a thing :P

**Comment by KLVN** [comment]
I know, it's really strange :D And if I open the config.json via FTP it's the old file again. Like dafuq.

**Comment by xorinzor** [comment]
@KLVN that's.. not possible, sorry to say, but you must've done something wrong along the way or forgotten about something you did ;) computers simply do what they're told to do :P
