### ISSUE TITLE
Bot will not follow path

### ISSUE THREAD

**Issue by littlebigcat** [PokemonGoF/PokemonGo-Bot#2148]
### Expected Behavior

The bot to follow a given path linearly of 10 points

### Actual Behavior

Using the example config file and a valid paths file I'm unable to get the bot to follow a path, it just starts going in the opposite direction and acting as if the path wasn't specified

### Steps to Reproduce

Have copied the example path config file and amend as below
      {
        "type": "FollowPath"
      }
    },
    "navigator": {
      "type": "path",
      "path_mode": "linear",
      "path_file": "configs/path.json"
    },

### Other Information

Current Dev branch

**Comment by Philipp59** [comment]
```
        "type": "MoveToFort"
      },
      {
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_file": "configs/path.example.json"
        }
      }
    ],
```
remove        
```
 "type": "MoveToFort"
      },
      {
```

**Comment by littlebigcat** [comment]
Thanks, strange it was in example config.
