### ISSUE TITLE
Exchanging pokemon

### ISSUE THREAD

**Issue by DevPhreak** [PokemonGoF/PokemonGo-Bot#216]
### Expected Behavior
Exchanges pokemon with low rarity/combat power

### Actual Behavior
It prints that the exchange was succesful however the pokemons are still in my inventory.

### Steps to Reproduce
Run the bot?

### Other Information
OS: 
Kali linux rolling. Fresh install with pythob 2.7.

**Comment by jtdroste** [comment]
What branch are you on (type `git branch`).  Does it say master?

**Comment by douglascamata** [comment]
@DevPhreak did you finish the tutorial? If you running from the `dev` branch, did you run pull the latest changes?

**Comment by DevPhreak** [comment]
Pulled the development branch, issue still persists.

**Comment by douglascamata** [comment]
Fixed in dev branch.
