### ISSUE TITLE
[Suggestion] Allow for setting a cp/iv threshold and a number of duplicate pokemons below it for keeping

### ISSUE THREAD

**Issue by Arderos** [PokemonGoF/PokemonGo-Bot#2163]
It seems like a nice feature to be able to set the following logic:

Set a cp/iv threshold
Do not transfer pokemons above it
Keep a configurable amount of strongest (by iv/cp) pokemons below it.

**Comment by Nathanian** [comment]
In the Dev-Branch u can set to not transfer the best pokemon of a kind. 
![image](https://cloud.githubusercontent.com/assets/20759070/17289035/1e148c42-57d8-11e6-8fe1-3c0fded36a15.png)

**Comment by Arderos** [comment]
It's not what I am suggesting.
The point is - any pokemon above iv 0.95 is worth keeping. 10 0.95 vaporeons, for example. But say you encounter something rare, and you do not know what. If your setting for "any" is release below 0.95 that rare pokemon would be released. At the same time, if you configure the bot for keeping the best 10 pokemons, you would quickly use all pokemon storage.
