### ISSUE TITLE
release all pokemon post evolution

### ISSUE THREAD

**Issue by decix** [PokemonGoF/PokemonGo-Bot#2164]
### Expected Behavior

Bot evolves pokemon specified. Then releases the evolved pokemon based on release config.

### Actual Behavior

Bot evolves pokemon, releases everything.

![image](https://cloud.githubusercontent.com/assets/6101512/17280590/73ee3d70-5747-11e6-8cce-d481df574dba.png)

### Steps to Reproduce
First time this has happened. I have no idea how, usually the bot will not even evolve even if I have specified pokemon.

**Comment by MrCarlosJr** [comment]
Maybe you rule for exchange is true for news pokemons.
