### ISSUE TITLE
Adding Second Bot Makes pgoapi Module Unavailable In 1st

### ISSUE THREAD

**Issue by JonnyBoy333** [PokemonGoF/PokemonGo-Bot#2167]
I'm having a problem where after installing a second bot in a second folder the bot in the first folder bot no longer runs and I get an error of "No module named pgoapi.exceptions." So then in terminal I go into the first bot folder and do 

$ source bin/activate
$ pip install -r requirements.txt

Now when I run the bot in the first folder everything is fine. Then I go to the second folder and try to run it and get the same error as above. Following the steps above I get it to work in the second folder but then it no longer works in the first. What's going on here?

### Other Information
OS: OSX Yosemite 10.10.5
Git Commit: cc3e9545d65fe764602ebb73f557cd797038b374
Python Version: 2.7.10

**Comment by MZorzy** [comment]
try use
screen -S name
and then run bot

**Comment by JonnyBoy333** [comment]
Still got the same error when I tried running 'screen -S name' before running the bot. My workaround right now is that I've added 

$ source bin/activate
$ pip install -r requirements.txt

into my applescript so that it re downloads all the dependencies before running the bot. It takes 10x longer to start all the bots but it does work.

**Comment by daemonsyn** [comment]
Use the same diretory use the option -cf

**Comment by JonnyBoy333** [comment]
I'll close this now. I just have to type the 'source bin/activate' command before running the bot each time which is not a big deal.
