### ISSUE TITLE
Keep Login Error, Server busy

### ISSUE THREAD

**Issue by nafmal** [PokemonGoF/PokemonGo-Bot#2174]
Anyone know what's the problem? 
It keep Login Error, server busy......

**Comment by shunam** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2152

**Comment by ddrght12345** [comment]
Aww crap. I was looking for that issue.
Beat me to it

**Comment by Bilters** [comment]
I've got the same issue straight out of the box. Downloaded it; and nothing happened except for the server busy sign. The reference from @shunam didn't help. Any other advice?

**Comment by wynkth** [comment]
Do you have 2-factor authentication enabled in your Google account?
I have seen in the code that it's not supported

**Comment by nafmal** [comment]
after disable 2-factor authentication, it work! thanks!

**Comment by wynkth** [comment]
You can preserve the 2-factor authentication:
Go to [App passwords](http://security.google.com/settings/security/apppasswords) and create a custom password for the bot, it should work ;)
