### ISSUE TITLE
[Suggestion] Open Area to Share Popular Config.Json Setups

### ISSUE THREAD

**Issue by Whosdaman** [PokemonGoF/PokemonGo-Bot#2175]
### Expected Behavior
Copy and paste or download popular config.json set ups.

### Actual Behavior
Does not exist

### Steps to Reproduce
Google

### Other Information
OS: MacOS
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by glitchsnob** [comment]
I really like this idea, I have played around a lot with the config between movement and release settings trying to get the "perfect" config

**Comment by Whosdaman** [comment]
And I also say, while we are at it, why not also a section to share path files too?

**Comment by nivong** [comment]
Just add with pull request stuff to this list with your name in the branche:
https://github.com/nivong/pokemongo_config
