### ISSUE TITLE
Bot won't follow path

### ISSUE THREAD

**Issue by 15calderm** [PokemonGoF/PokemonGo-Bot#2179]
### Expected Behavior
Bot to follow waypoints designated in path.json

### Actual Behavior
Bot deviates from path and wanders to random pokestops

### Steps to Reproduce
simply run the bot

### Other Information
OS: Win10
**Config.json:**
```
{
    "auth_service": "google",
    "username": "XXX",
    "password": "XXX",
    "location": "XXX",
    "gmapkey": "XXX",
    "max_steps": 5,
    "walk": 10,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": false,
    "distance_unit": "km",
    "item_filter": {
      "1": { "keep" : 60 },
      "101": { "keep" : 0 },
      "102": { "keep" : 0 },
      "103": { "keep" : 0 },
      "104": { "keep" : 50 },
      "201": { "keep" : 25 },
      "701": { "keep" : 80 }
    },
    "evolve_all": "Pidgey,Rattata,Weedle,Zubat",
    "tasks": [
    {
      "type": "IncubateEggs",
      "config": {
        "longer_eggs_first": true
       }
      },
      {
      "type": "TransferPokemon"
      },
      {
      "type": "EvolveAll",
      "config": {
         "evolve_speed": 20,
	 "use_lucky_egg": false
        }
      },
      {
      "type": "RecycleItems"
      },
      {
      "type": "CatchVisiblePokemon"
      }, 
      {
      "type": "CatchLuredPokemon"
      },
      {
      "type": "SpinFort"
      },
      {
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_file": "configs/path.json
        }
      }
     ],  
...
```
**Path.json**

[
	{"location": "-31.95986104211438 lon=115.84395289421082"},
	{"location": "-31.95962892680318 lon=115.84395289421082"},
	{"location": "-31.959139662215847 lon=115.84399044513702"},
	{"location": "-31.9585661952885 lon=115.84403067827225"},
	{"location": "-31.95835683345449 lon=115.8440414071083"},
	{"location": "-31.957790188705474 lon=115.84408432245255"},
	{"location": "-31.957414699295303 lon=115.84412187337875"},
	{"location": "-31.95705968971385 lon=115.8441486954689"}
]

**Comment by tstumm** [comment]
Do you have `MoveToFort` activated?

**Comment by Philipp59** [comment]
try to configure your path config to this format:

`	{"location": "40.763740,-73.969621"},`

**Comment by 15calderm** [comment]
> 

try to configure your path config to this format:

{"location": "40.763740,-73.969621"},

I can't believe I didn't notice this before, thank you it worked.
