### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by Lordedi** [PokemonGoF/PokemonGo-Bot#218]
Hi guys,
I share here my problem,
I have a issue with googlemaps,
thanks in advance,

there it is:

 import googlemaps
ImportError: No module named googlemaps

**Comment by vladlaptev** [comment]
try this
`pip install googlemaps`

**Comment by jtdroste** [comment]
Please follow the README.md file.

Run: `pip install -r requirements.txt`.  This will require you to have python and pip already installed.

**Comment by Lordedi** [comment]
thanks all :)


2016-07-22 17:58 GMT+02:00 James Droste <notifications@github.com>:
