### ISSUE TITLE
Not spinning/moving any forts as there aren't enough space.

### ISSUE THREAD

**Issue by Thieund** [PokemonGoF/PokemonGo-Bot#2180]
### Expected Behavior
Normal behavior
### Actual Behavior
There are many "Server seems to be busy or offline - try again - 1/5"
And app keeps posting "Not spinning/moving (to) any forts as there aren't enough space."

### Other Information
OS: Windows server 2012.
P/s: Working fine and no error/warning in windows 10 with the SAME configuration.

**Comment by Anakin5** [comment]
Bot should spin whether we have space or not since it always rewards xp. It does not make sense to stop walking toward forts and stop spinning them if there is not space in  inventory.

**Comment by aTadTasty** [comment]
agreed with @Anakin5 this is prob just a bug?
