### ISSUE TITLE
Incorrect XP reported?

### ISSUE THREAD

**Issue by raxxon** [PokemonGoF/PokemonGo-Bot#2181]
### Expected Behavior
XP Gains reported

### Actual Behavior
XP Gains appear to be incorrect for capturing pokemon, Stops uneffected

### Steps to Reproduce
"run bot".

[00:21:43] Something rustles nearby!
[00:21:44]  A Wild Caterpie appeared! [CP 25] [Potential 0.49]
[00:21:44] IV [Stamina/Attack/Defense] = [12/1/9]
[00:21:47] Using Pokeball (chance: 92.71%)... (63 left!)
[00:21:47]  Captured Caterpie! [CP 25] [Potential 0.49] [12/1/9] [+210 exp]
[00:21:52]  Now at Pokestop: ************************
[00:21:52]  Spinning ...
[00:21:53]  Loot:
[00:21:53]  50 xp
[00:21:53]  - 3x Pokeball (Total: 66)
[00:21:53] PokeStop on cooldown. Time left: 4 minutes, 51 seconds

Double checked, it hasn't popped a Lucky Egg, checked from my "live" account on my phone, captures still generate 100 XP base. If Lucky Egg were running the bot would gain 220 XP for capture (100 XP base, 10 XP Curveball, Doubled) and 100 XP for PokeStops.

### Other Information
OS: Windows 10 x64
$ git log -n 1 --pretty=format:"%H" ; python -V
82f547769c396e1f4a8c0e771ee62343add6c7fb
Python 2.7.10

**Comment by pokemule** [comment]
You are right: 100 XP Base and 10 XP Curve ball summed equals 110 exp. However, there's also an additional configuration to each throw: Normal, Nice, Great, and Excellent throws. This can be configured in your config.json using the variable ""catch_randomize_reticle_factor" : 0". The value 0 means that throwing a normal, nice, great, or excellent throw is completely randomized. The value 1 means the bot will always throw an excellent throw. An excellent throw gives you 100 extra exp, summing to a total of 210 exp. Not entirely sure how much exp each of the other throws give.

**Comment by raxxon** [comment]
Did those get fixed? Last I saw in Dev branch they weren't working and the bot doesn't report back a breakdown. If they're working, Awesome, I finally get some leveling. ;)

**Comment by pokemule** [comment]
Yeah haha #2130

**Comment by raxxon** [comment]
Oh. Excellent. Then this is a complete non-issue. :)
