### ISSUE TITLE
 False/True added to SpinForts

### ISSUE THREAD

**Issue by iDervy** [PokemonGoF/PokemonGo-Bot#2183]
Would it be possible to add a False/True in the configs for SpinForts? This way, instead of having to delete/re-add the task consistently, we can just change a single value.

Alternatively, why not bring back Poke/Farm/All option back?

Having to make multiple configs just for Farm Pokemon/Farm PokeStops is getting tedious.

**Comment by mrthrowaway** [comment]
You can change the `type: "SpinFort"` to `type: "//SpinFort"` to disable it
