### ISSUE TITLE
[DEV] Walks in rectangular pattern and keeps repeating is

### ISSUE THREAD

**Issue by WebberTakken** [PokemonGoF/PokemonGo-Bot#2186]
### Expected Behavior

Walk like in the bot would in Master

### Actual Behavior

After almost 6 hours. It didn't walk far and repeated the following pattern;
![rectangular pattern](https://cloud.githubusercontent.com/assets/20756439/17285311/4d0b715c-57c2-11e6-9770-600511d984f4.PNG)

### Steps to Reproduce

Run the bot as is.

### Other Information
OS: Windows
Git Commit: a9b56531a444e94e60ad6cb12e76b71564285072
Python Version: Python 2.7.12

**Comment by pokemule** [comment]
Try increasing your max_steps value in config.json.

**Comment by tstumm** [comment]
Not a bug. Please read the wiki.
