### ISSUE TITLE
Automatic Restart on Mac?

### ISSUE THREAD

**Issue by drees5** [PokemonGoF/PokemonGo-Bot#2187]
I know this isn't really an issue but is there any way to make bots restart automatically after crash?

**Comment by sayasemut** [comment]
use daemon ...

**Comment by leovarmak** [comment]
@drees5 yes, if a bot crashes you can automatically restart it using a simple bash script which was mentioned by @MeGaPk . All you need to do is put a bash script file in PokemonGo-Bot folder and run it.

`#!/bin/bash`
`while true`
`do`
`./pokecli.py`
`echo ">pokecli exited... restarting...";`
`sleep 5;`
`done`

Now save save this file as`start.sh` and put it in `PokemonGo-Bot` . Now start the program in the terminal using .`/start.sh `all the time

**Comment by Philipp59** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Restarting-bot(s)

**Comment by Di9** [comment]
many times the bot just freeze until I press cmd+c and start it again, is it possible to restart bot every hour automatically?

**Comment by leovarmak** [comment]
@Philipp59 are you talking about Dev ?
