### ISSUE TITLE
[Bug] The Bot doesn't walk to the nearest Pokestop

### ISSUE THREAD

**Issue by dominikue** [PokemonGoF/PokemonGo-Bot#219]
### Expected Behavior
The Bot moves to the nearest Pokestop.

### Actual Behavior
The next Pokestop isn't the nearest one and the Bot moves 750 Meters instead of >20.

![screen](https://cloud.githubusercontent.com/assets/17249002/17062849/e29dc2b4-5034-11e6-9d4e-6e24adddafeb.jpg)
**Screenshot from the log**

![spawn_position](https://cloud.githubusercontent.com/assets/17249002/17062852/e72b6836-5034-11e6-99bb-cc1791fcad54.jpg)
**The spawn location in NY Central Park (40.771133, -73.974187)**

![next_pokestop](https://cloud.githubusercontent.com/assets/17249002/17062885/091536ac-5035-11e6-87d4-595cb9892a91.jpg)
**The next PokeStop where the bot wants to move**

![image_2016-07-22_at_17-48-35](https://cloud.githubusercontent.com/assets/17249002/17062895/1a97e2f8-5035-11e6-9d22-113943c67f54.jpg)
**There you can see all Pokestops in the near of the spawn. - I think this need to fixed**

### Steps to Reproduce

Spawn to NY Central Park - works for me 5/5.

### Other Information
OS: Windows10 - 64
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here) 17:00

**Comment by Orrielel** [comment]
Was about the report the same. It picks one 1238m away, instead of the closest which about 80m

**Comment by dominikue** [comment]
Duplicate with #186

**Comment by douglascamata** [comment]
This is a known behaviour that we need to fix.

**Comment by ChronoAS** [comment]
#141

**Comment by dominikue** [comment]
Saw it too late - sorry.

**Comment by jtdroste** [comment]
I want to say, this is a beautiful issue.  10/10 would read again.

**Comment by CapCap** [comment]
@jtdroste @douglascamata  Is this as simple as adding `Reverse=true` to my forts sorting in bot.py, or is this something larger?

**Comment by douglascamata** [comment]
@CapCap I'm not sure. Test it please. I'll close this to avoid duplicated issue spam.
