### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by Fellner96** [PokemonGoF/PokemonGo-Bot#22]
Traceback (most recent call last):
  File "pokecli.py", line 32, in <module>
    import requests
ImportError: No module named requests

**Comment by harsh1412** [comment]
Redownload the whole ZIP again.

**Comment by dominikueruem** [comment]
Have you donwload python and runned the pip install -r requirements.txt command with cmd?

**Comment by jtdroste** [comment]
Closing this.

Make sure you run `pip install -r requirements.txt`
