### ISSUE TITLE
Dev branch wont start

### ISSUE THREAD

**Issue by ASAPHAANING** [PokemonGoF/PokemonGo-Bot#2202]
### Expected Behavior
Bot starting

### Actual Behavior
It wont

### Steps to Reproduce
Checkout to dev branch. Run with the same config files as the master.

### Other Information
OS: Linux 64bit

Traceback (most recent call last):
  File "pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/home/x/PokemonGo-Bot/pokemongo_bot/__init__.py", line 14, in <module>
    from pgoapi.utilities import f2i, get_cell_ids
ImportError: cannot import name get_cell_ids

Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
89b112c92d1ce012040c96304f286619d2636fb9

Python Version: (run 'python -V' and paste it here)
Python 2.7.12

**Comment by ASAPHAANING** [comment]
Google does not index the issues page well and all I needed to do was search similar issues on GitHub.

Switching to the dev branch requires a reinstall of the `pgoapi` using the command

`pip install -r requirements.txt`

Works. Closed.

**Comment by ironbishop** [comment]
I think "dev" will never run, using the same config file from current "master".

So many differences.
https://github.com/PokemonGoF/PokemonGo-Bot/compare/dev
