### ISSUE TITLE
Proposal to consolidate example configuration files

### ISSUE THREAD

**Issue by Philipp59** [PokemonGoF/PokemonGo-Bot#2206]
instead of removing task from the example config and also instead of giving path.config and cluster.config can we just commit to show features that are available but not necessary needed for staple with just adding another empty task line? for sleeper, renaming,cluster and path task.
 for e.g.:

```
   "// tasks": [
    {
        "type": "Sleeper",
        "config": {
         "time": "12:00",
         "duration":"5:30",
         "time_random_offset": "00:30",
         "duration_random_offset": "00:30"
     }
 },
      {
        "type": "FollowCluster",
        "config": {
            "radius": 50,
            "lured": true
        }
```

**Comment by TheSavior** [comment]
While this sounds great in theory, I know a lot of people blindly copy from the config.json and use it. I would be concerned that having a bunch of tasks and configuration to show the possibilities would actually cause us more harm. 

I do agree though, having multiple example configs that only change slightly to show a new feature is *not* the correct approach. If people have more ideas of how we can approach this problem, we are all ears.

**Comment by mrthrowaway** [comment]
What about a basic one that goes into config.json.example with the most commonly used settings, and an advanced one that has all the possible variables

**Comment by sgitkene** [comment]
@TheSavior I think what @Philipp59 proposes is not to add every possibility to the config, but rather have "tasks":[] with all the tasks that are used, and a "unused tasks(or //tasks)":[] with additional possibilities, that are ignored.

**Comment by Philipp59** [comment]
exactly

**Comment by TheSavior** [comment]
Ah. That sounds better to me. 

I don't think will solve all of our problems here though because some of the other configs don't just add another worker, they have different top level configuration for things like release settings.
