### ISSUE TITLE
pip requirements failure

### ISSUE THREAD

**Issue by leadboots5** [PokemonGoF/PokemonGo-Bot#221]
pip requirements doesn't work for me on commit 4191f46. i believe im doing everything right.

Error:
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-oIdS7B/protobuf-to-dict/

**Comment by seadog007** [comment]
Please provide whole error message

**Comment by deathcoderz** [comment]
I think u are using python 2.7 try pip uninstall -r requirements.txt and than reinstall it

**Comment by leadboots5** [comment]
Nothing to uninstall @deathcoderz 
Full text @seadog007 

> Obtaining pgoapi from git+git://github.com/tejado/pgoapi.git@1f25e907f3e5f1b603330e71041e1ad7bee7580f#egg=pgoapi (from -r requirements.txt (line 1))
  Skipping because already up-to-date.
Collecting geopy==1.11.0 (from -r requirements.txt (line 2))
  Downloading geopy-1.11.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 1.0MB/s 
Collecting protobuf==3.0.0b4 (from -r requirements.txt (line 3))
  Downloading protobuf-3.0.0b4.tar.gz (210kB)
    100% |████████████████████████████████| 215kB 1.7MB/s 
Collecting requests==2.10.0 (from -r requirements.txt (line 4))
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 1.4MB/s 
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 5))
  Downloading s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 6))
  Downloading gpsoauth-0.3.0.tar.gz
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 7))
  Downloading protobuf-to-dict-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    
    Installed /private/tmp/pip-build-iSE8gP/protobuf-to-dict/nosexcover-1.0.10-py2.7.egg
    Searching for coverage
    Reading https://pypi.python.org/simple/coverage/
    Best match: coverage 4.2b1
    Downloading https://pypi.python.org/packages/ca/76/75cb8a80084dc08d373ef39a04237a658e6dcf4adeaba3fe2a9753a904e3/coverage-4.2b1.tar.gz#md5=587019c5f1a0af28c08e9e9586d5a60a
    Processing coverage-4.2b1.tar.gz
    Writing /tmp/easy_install-K36OYs/coverage-4.2b1/setup.cfg
    Running coverage-4.2b1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-K36OYs/coverage-4.2b1/egg-dist-tmp-cv6_Du
    warning: no previously-included files found matching 'ci/appveyor.token'
    no previously-included directories found matching 'doc/_build'
    no previously-included directories found matching 'tests/eggsrc/build'
    no previously-included directories found matching 'tests/eggsrc/dist'
    no previously-included directories found matching 'tests/eggsrc/*.egg-info'
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    
    Installed /private/tmp/pip-build-iSE8gP/protobuf-to-dict/coverage-4.2b1-py2.7-macosx-10.11-intel.egg
    Searching for nose>=1.0
    Reading https://pypi.python.org/simple/nose/
    Best match: nose 1.3.7
    Downloading https://pypi.python.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz#md5=4d3ad0ff07b61373d2cefc89c5d0b20b
    Processing nose-1.3.7.tar.gz
    Writing /tmp/easy_install-yQq5IE/nose-1.3.7/setup.cfg
    Running nose-1.3.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-yQq5IE/nose-1.3.7/egg-dist-tmp-iES55Z
    no previously-included directories found matching 'doc/.build'
    
    Installed /private/tmp/pip-build-iSE8gP/protobuf-to-dict/nose-1.3.7-py2.7.egg
    Searching for protobuf>=2.3.0
    Reading https://pypi.python.org/simple/protobuf/
    Best match: protobuf 3.0.0b4
    Downloading https://pypi.python.org/packages/8b/fa/2a4f48c3579a5d88bfe4e8408227cb12731efcb30da4ba423cf115a1d320/protobuf-3.0.0b4-py2.7.egg#md5=e29a69cb89fff0bc39f099e705e4e93e
    Processing protobuf-3.0.0b4-py2.7.egg
    creating /private/tmp/pip-build-iSE8gP/protobuf-to-dict/protobuf-3.0.0b4-py2.7.egg
    Extracting protobuf-3.0.0b4-py2.7.egg to /private/tmp/pip-build-iSE8gP/protobuf-to-dict
    
    Installed /private/tmp/pip-build-iSE8gP/protobuf-to-dict/protobuf-3.0.0b4-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-iSE8gP/protobuf-to-dict/setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 263, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (six 1.4.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('six>=1.9'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-iSE8gP/protobuf-to-dict/

**Comment by eggins** [comment]
I have just updated the WIKI with an installation tutorial for mac.

Please check it out - and re-open if you have anymore issues.

https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation

**Comment by leadboots5** [comment]
the additional virtualenv stuff seems to have resolved it
