### ISSUE TITLE
DEV Better enforce rules about Pokemons to retain

### ISSUE THREAD

**Issue by Philipp59** [PokemonGoF/PokemonGo-Bot#2213]
ff62273291a7e8e3ef13105c1be46a44830be0ba

can we pls delete this.

there is no logic behind and it broke 
`{"keep_best_iv": 3},` 
complete.

> Rules about maximum CP and IV to transfer Pokemons are applied
> also when keeping the best ones.

There is absolutely no reason to add cp and iv maximum when releasing after the keep best cp/iv logic.
The logic should be the old one, because when i want to keep the best X IV or X CP Pokemon then i just want to keep the best of that kind. The old logic worked great. No reason to make this too complicated.

IV and CP Maximum should not work with "keep best" together.

When i want to keep after CP/IV threshold then there is 
`{"release_below_cp": 9, "release_below_iv": 0.99, "logic": "or"}`

I don't get this idea behind this "new" logic completely messed up.

Also it is necessary to update example config when changing release logic. just to give an example of the meaning.....

#2211
#2200

**Comment by sgitkene** [comment]
It is to enable users to save space most likely. They want to keep their best, but anything below the treshhold gets released. so after letting the bot for a long time, they have only the best and everything that's weak got released to save space. Ideally this will give you an inventory of only strong pokemon. If you don't want the rule applied, set it to 0, thus never releasing pokemon on that rule.

**Comment by Philipp59** [comment]
Tell me were is the difference ? 
e.g. Magyar i only want to keep the "strongest" of them

there i have 2 options:
1.) IV
I only want to have a max of X magma then i set keep best iv to X for e.g. to 5

2.) I want to keep only magma with IV > x for e.g i only want to dust up 100er IV then i can set {"release_below_cp": 9, "release_below_iv": 0.99, "logic": "or"}.

There is no room for keep best with CP/IV Max parameters .

This new feature does not save inventory space in the long rung because your target is to keep the 5 best magmars with the parameters IV/CP combined the save only inventory space UNTIL you catch them. As I told there is no difference in the long run.

**Comment by giomasce** [comment]
@Philipp59 "You don't like something" != "There is no room for it". To me it is completely logical wanting to keep the 3 best Pokemons of a type, but if you are so lucky that you found 4 good ones, then keep all of them. If the old behavior is broken, than that can be fixed, but there is no need to throw away a feature that other users like for that.

**Comment by giomasce** [comment]
Apparently #2215 fixes your bug while still retaining the behavior that I (and other users) like.

**Comment by Philipp59** [comment]
close
