### ISSUE TITLE
[Feature Request] Alternative to Item Filter: Keep max inventory -n

### ISSUE THREAD

**Issue by HecticSeptic** [PokemonGoF/PokemonGo-Bot#2219]
### Desired Behavior
When active, try to keep n number of free slots in inventory (probably 1 default) because anything earned when not full is kept (and allows us to remove potions or pokeballs instead of hyper potions).
1. List order of importance of items, default (least to best) potion, pokeball, razzberry, greatball, super etc. for user configuration
2. As inventory becomes full (as close to full as (n) denotes) then remove items until this is no longer true

NB: This may allow for 0 balls, but then the user can simply start using the other high value items. If necessary, a small number of balls could be kept on hand - exempt from this logic.
Alternatively, this feature could kick in for that situation where you have 450/400 inventory with 0 balls, removing the 144 potions you happen to have

### Actual Behavior
Item filter allows us to specify exact numbers of items desired, but this isn't easy to predict (efficient) for best utilization of space and quickly results in full inventory due to wanting as much good inventory as possible (i.e. level up -> max potions -> full inventory -> suddenly hyper potions are removed instead of just potions)

**Comment by HecticSeptic** [comment]
#2207 
Duplicate of this.

**Comment by yahwes** [comment]
I changed this in my fork in [seen_fort_worker.py](https://github.com/yahwes/PokemonGo-Bot/commit/766123c02117d4f5d6daf41b9ee1c96b2cd6099a?diff=unified#diff-81044be212df0c715eb210253ab6d4eb). I have it set to discard up to 10 of each items in the filter config.
