### ISSUE TITLE
Client behaviour: pokemon spawn distance

### ISSUE THREAD

**Issue by vosk** [PokemonGoF/PokemonGo-Bot#2220]
### Expected Behavior
The real game does not spawn pokemon to the user unless they are inside the horizon radius (~40m?) 
### Actual Behavior
The bot tries and succeeds to catch pokemon really really far (for now it does..) Is this really ok?

### Other Information
all branches,

**Comment by tstumm** [comment]
Niantic changed the radius to 70m, so basically we follow all game rules.

**Comment by vosk** [comment]
If indeed 70m is the limit, still, some pokemon appear much further, I just print()ed the distance() inside PokemonCatchWorker and I still get some 103, 105m, simply because catchable_pokemon contains data in some cell.
