### ISSUE TITLE
[BUG] Bot is unable to parse the egg hatching response

### ISSUE THREAD

**Issue by xorinzor** [PokemonGoF/PokemonGo-Bot#2226]
### Expected Behavior
Show information about the hatched pokemon

### Actual Behavior
![untitled](https://cloud.githubusercontent.com/assets/4212335/17295804/4fd1e8da-57fe-11e6-93c6-6e5251a462f3.png)

over and over again

### Steps to Reproduce
Run the bot and wait for an egg to hatch

### Other Information
OS: Win 10 x64
Git Commit: 589ada8f8d7dcc78921a09a848cfd84485423239
Python Version: 2.7.12

**Comment by reddivision** [comment]
See my response in #2228

**Comment by xorinzor** [comment]
@reddivision ah, I had a quick look around to make sure it wasn't created yet, my bad.

**Comment by reddivision** [comment]
nah, you were fine; yours was first, I just saw the other and answered it first while going down the list.

**Comment by xorinzor** [comment]
@reddivision im glad haha, I'll leave it closed in favor of the other one anyway, it seems to have gotten more attention
