### ISSUE TITLE
EvolveAll not working?

### ISSUE THREAD

**Issue by hklcf** [PokemonGoF/PokemonGo-Bot#2230]
config.json

`      {`
`        "type": "EvolveAll",`
`        "config": {`
`          "evolve_all": "all",`
`          "evolve_cp_min": 0,`
`          "evolve_speed": 20,`
`          "use_lucky_egg": true`
`        }`

nothing happens

a90a77abe0f6a59f1adc330ea7db40eb24470a7d

**Comment by Nathanian** [comment]
Look a few lines below, i guess after evolve all it says none in your config


"evolve_all": "Pidgey,Rattata,Weedle,Spearow,Drowzee",
	"evolve_cp_min": 300,
	"evolve_captured": "Rattata",

**Comment by Nathanian** [comment]
Under your item filter list theres another evolve option

"evolve_all": "Pidgey,Rattata,Weedle,Spearow,Drowzee",
	"evolve_cp_min": 300,
	"evolve_captured": "Rattata",

**Comment by Nathanian** [comment]
in the tasks you should just use 

"type": "EvolveAll",
        "config": {
          "evolve_speed": 20,
          "use_lucky_egg": false

**Comment by inzaghi89** [comment]
Confirm that doesn't work. Even on this configuration.

**Comment by hklcf** [comment]
@Nathanian not working for me

**Comment by Floriferous** [comment]
Same problem!

**Comment by Nathanian** [comment]
hm works for me, post you configs please

**Comment by Floriferous** [comment]
Are you sure you are on the latest dev commit?

**Comment by Nathanian** [comment]
Not sure my last update was 20 hours ago

**Comment by Floriferous** [comment]
Yes, your config file would be invalid on the latest commit.

**Comment by Nathanian** [comment]
Oh, i guess then its good that i didnt update yet, i hope your bugs get fixed soon

**Comment by Nathanian** [comment]
So i updated now and caught a few pidgeys and its evlolving just fine

**Comment by Nathanian** [comment]
{
	"auth_service": "google",
	"username": "xxx",
	"password": "xxxx",
	"location": "xxxxxx",
	"gmapkey": "xxxxxxx",
	"tasks": [{
			"type": "HandleSoftBan"
		}, {
			"type": "CollectLevelUpReward"
		}, {
			"type": "IncubateEggs",
			"config": {
				"longer_eggs_first": true
			}
		}, {
			"type": "TransferPokemon"
		}, {
			"type": "EvolveAll",
			"config": {
				"evolve_all": "Pidgey",
				"evolve_cp_min": 0,
				"evolve_speed": 20,
				"use_lucky_egg": false
			}
		}, {
			"type": "RecycleItems",
			"config": {
				"item_filter": {
					"Pokeball": {
						"keep": 100
					},
					"Greatball": {
						"keep": 70
					},
					"Ultraball": {
						"keep": 80
					},
					"Potion": {
						"keep": 0
					},
					"Super Potion": {
						"keep": 40
					},
					"Hyper Potion": {
						"keep": 30
					},
					"Revive": {
						"keep": 30
					},
					"Razz Berry": {
						"keep": 50
					}
				}
			}
		}, {
			"type": "CatchVisiblePokemon"
		}, {
			"type": "CatchLuredPokemon"
		}, {
			"type": "SpinFort"
		}, {
			"type": "MoveToFort"
		}

	],
	"max_steps": 5,
	"forts": {
		"avoid_circles": true,
		"max_circle_size": 50
	},
	"websocket_server": false,
	"walk": 11.16,
	"action_wait_min": 1,
	"action_wait_max": 4,
	"debug": false,
	"test": false,
	"health_record": true,
	"location_cache": false,
	"distance_unit": "km",
	"reconnecting_timeout": 15,
	"evolve_captured": "NONE",
	"catch_randomize_reticle_factor": 1.0,
	"catch_randomize_spin_factor": 1.0,
	"catch": {
		"any": {
			"catch_above_cp": 0,
			"catch_above_iv": 0,
			"logic": "or"
		},
		"// Example of always catching Rattata:": {},
		"// Rattata": {
			"always_catch": true
		}
	},
		"release": {
			"Magikarp": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"Dratini": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"Dragonair": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"Eevee": {
				"keep_best_cp": 3,
				"keep_best_iv": 0
			},
			"Electabuzz": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"Jynx": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"Goldeen": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"Horsea": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"Krabby": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"Hypno": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"Gastly": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"Haunter": {
				"keep_best_cp": 2,
				"keep_best_iv": 0
			},
			"Shellder": {
				"keep_best_cp": 3,
				"keep_best_iv": 0
			},
			"Cloyster": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"Magnemite": {
				"keep_best_cp": 2,
				"keep_best_iv": 0
			},
			"Abra": {
				"keep_best_cp": 2,
				"keep_best_iv": 0
			},
			"Poliwag": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"Golbat": {
				"keep_best_cp": 2,
				"keep_best_iv": 0
			},
			"Zubat": {
				"keep_best_cp": 3,
				"keep_best_iv": 0
			},
			"Jigglypuff": {
				"keep_best_cp": 2,
				"keep_best_iv": 0
			},
			"Fearow": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"Spearow": {
				"keep_best_cp": 4,
				"keep_best_iv": 0
			},
			"Raticate": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"Pidgeotto": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"Pidgey": {
				"keep_best_cp": 5,
				"keep_best_iv": 0
			},
			"Rattata": {
				"keep_best_cp": 5,
				"keep_best_iv": 0
			},
			"Bellsprout": {
				"keep_best_cp": 2,
				"keep_best_iv": 0
			},
			"Seel": {
				"keep_best_cp": 10,
				"keep_best_iv": 0
			},
			"Magmar": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"Seadra": {
				"keep_best_cp": 1,
				"keep_best_iv": 0
			},
			"any": {
				"keep_best_cp": 5,
				"keep_best_iv": 0
			},
			"// Example of always releasing Rattata:": {},
			"// Rattata": {
				"always_release": true
			},
			"// Example of keeping 3 stronger (based on CP) Pidgey:": {},
			"// Pidgey": {
				"keep_best_cp": 3
			},
			"// Example of keeping 2 stronger (based on IV) Zubat:": {},
			"// Zubat": {
				"keep_best_iv": 2
			},
			"// Also, it is working with any": {},
			"// any": {
				"keep_best_iv": 3
			},
			"// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
			"// Zubat": {
				"keep_best_cp": 2,
				"keep_best_iv": 3
			}
		},
		"vips": {
			"Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
			"any": {
				"catch_above_cp": 1200,
				"catch_above_iv": 0.9,
				"logic": "or"
			},
			"Lapras": {},
			"Moltres": {},
			"Zapdos": {},
			"Articuno": {},

			"// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
			"Mewtwo": {},
			"Dragonite": {},
			"Snorlax": {},
			"// Mew evolves to Mewtwo": {},
			"Mew": {},
			"Arcanine": {},
			"Vaporeon": {},
			"Gyarados": {},
			"Exeggutor": {},
			"Muk": {},
			"Weezing": {},
			"Flareon": {}

		}
	
}

**Comment by iruy** [comment]
I have the same issue with the same configuration proposed by sample json
