### ISSUE TITLE
RemoveSoftBan before cating Pokémon in new Area

### ISSUE THREAD

**Issue by alexanderrock** [PokemonGoF/PokemonGo-Bot#2234]
Check the distance between actual location and the one before when switing to another location (land) and first revoke the softban before cating pokemon.

Just "fly" to 55.7978696109,37.6082894602 to catch a porygon but it's vanished because of softban

**Comment by MFizz** [comment]
There are 2 major PRs regarding this: #1887 #1992 Merge pending
