### ISSUE TITLE
Evolve all, but keep at least 1

### ISSUE THREAD

**Issue by Lunik** [PokemonGoF/PokemonGo-Bot#2235]
### Expected Behavior
Add new config options for `evolve_all` that keep at least X pokemon of this type.

### Actual Behavior
Evolve all

### Steps to Reproduce
```
{
        "type": "EvolveAll",
        "config": {
          "evolve_all": "Rattata,Pidgey,Slowpoke,Caterpie,Metapod,Weedle,Kakuna,Pidgeo$
          "evolve_cp_min": 10,
          "evolve_speed": 20,
          "use_lucky_egg": false
        }
}
```
### Other Information
OS: Linux
Git Commit: 494bc055543c3cb674cca781ec545311d3c9bad1
Python Version: Python 2.7.9

**Comment by JohnKarel** [comment]
Configurate your "release" tot his:
`    "release": {
      "any": {"keep_best_cp": 1, "keep_best_iv": 1, "release_below_cp": 999, "release_below_iv": 0.9, "logic": "or"}
}`

and make sure the evolve task in your tasks array is BEFORE your transfer task.

**Comment by Lunik** [comment]
I already have `"any": {"keep_best_cp": 2}` and the evolve task is before the transfert.
But I think you missunderstood, when evolving all, I want to evolve `total - 1` and then keep 1 not evolved. It is not about releasing pokemon...

**Comment by MZorzy** [comment]
good idea
evolve NOT ALL (Rattata,Pidgey...) but keep one 'safe' and then evolve all other.
which one? can be the starred/preferred one ? or 1st (2nd?) by iv / cp?

**Comment by Lunik** [comment]
I think we can apply the same options than release `keep_best_cp, keep_best_iv, ...`

**Comment by MZorzy** [comment]
scenario : have
Vaporeon 14/14/14
Eevee (nicknamed Rainer ) 15/15/15
Evee 14/14/14

is not better keep eevee 14/14/14 and evolve 15/15/15 ?

**Comment by Lunik** [comment]
Hum... so we need to have new options like `evolve_best_cp, ...`?

**Comment by jokoast** [comment]
Where do you paste this ?

Config.json or config_release ?

"release": { "any": {"keep_best_cp": 1, "keep_best_iv": 1, "release_below_cp": 999, "release_below_iv": 0.9, "logic": "or"} }
