### ISSUE TITLE
pathfinding issue while on path mode

### ISSUE THREAD

**Issue by Dunduro** [PokemonGoF/PokemonGo-Bot#2237]
### Expected Behavior
bot on path mode should grab pokestops but generaly follow the laid out path

### Actual Behavior
bot wil wander further away from the city somehow but that isnt an issue the issue is it just spassing out as you can see in the images below

### Steps to Reproduce
have your bot run around near the edge of a populated city

### Other Information
OS: Debian 8.5
Git Commit: a90a77abe0f6a59f1adc330ea7db40eb24470a7d
Python Version: 2.7.9
![image](https://cloud.githubusercontent.com/assets/5494765/17297904/f746971a-5807-11e6-889b-3b82f88728ca.png)
![image](https://cloud.githubusercontent.com/assets/5494765/17297916/09a9ee5c-5808-11e6-885b-0cbeabd258a0.png)

**Comment by Dunduro** [comment]
on a side note restarting the bot wil generaly fix the issue but kinda annoying to have to reset them after set interval

**Comment by Lunik** [comment]
Same as issue #2192

**Comment by nujabse** [comment]
@Dunduro Bye the way, how do you managed to draw all the tracks? I mean, the red lines in the picture?
