### ISSUE TITLE
[Ask] Can I set the bot to capture mode but do not move from certain location?

### ISSUE THREAD

**Issue by holywend** [PokemonGoF/PokemonGo-Bot#224]
### Expected Behavior
The bot stay still in one location waiting pokemon to spawn from the pokestops with lures.

### Actual Behavior
The bot move away

### Steps to Reproduce
Login from phone, look for pokestop with lures then find the exact position to get spawn from the pokestop. Then set the bot to that location.

**Comment by douglascamata** [comment]
use `--maxstep 1`

**Comment by aTadTasty** [comment]
make sure to NOT add the -s

**Comment by holywend** [comment]
thx @douglascamata ! cheers

**Comment by ginetrix** [comment]
Is it actually possible to stay at a spot and just spin the pokestops around you?
