### ISSUE TITLE
Option to rename the pokemon based on the stat

### ISSUE THREAD

**Issue by kalyon** [PokemonGoF/PokemonGo-Bot#2240]
### Expected Behavior
Rename the pokemon after catch it based on the stats

### Steps to Reproduce
IvPercent = ((pokemon.individual_attack + pokemon.individual_defense + pokemon.individual_stamina)*100)/45
monster = [pokedex[pokemon.pokemon_id],pokemon.cp,pokemon.individual_attack,pokemon.individual_defense,pokemon.individual_stamina,IvPercent,pokemon]
print '\n NAME            | CP    | ATK | DEF | STA | IV% '
print '---------------- | ----- | --- | --- | --- | ----'
logging.info(' %-15s | %-5s | %-3s | %-3s | %-3s | %-3s | %s',monster[0],monster[1],monster[2],monster[3],monster[4],monster[5],monster[6].nickname)
session.nicknamePokemon(monster[6],str(monster[5]) + '-' + str(monster[2]) + '/' + str(monster[3]) + '/' + str(monster[4]))

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by lukemeaden** [comment]
Post your config or go on Slack for help

**Comment by yweitkemper** [comment]
Does this code work or were you looking to get it to work?

**Comment by vdubus** [comment]
It seems an implementation of such a functionality was done it ticket #1850 
It's available on the dev branch and seems to work fine.
