### ISSUE TITLE
Seg Fault on dev

### ISSUE THREAD

**Issue by visikov** [PokemonGoF/PokemonGo-Bot#2242]
OpenBLAS blas_thread_init: RLIMIT_NPROC 1029716 current, 1029716 max
run.sh: line 18:  8172 Segmentation fault

On Ubuntu 14.04

**Comment by visikov** [comment]
The commit that breaks it: https://github.com/PokemonGoF/PokemonGo-Bot/commit/e65602eec5526a74941f17e36f0c90ce49ef018a

**Comment by maestroi** [comment]
works fine now on dev.
