### ISSUE TITLE
is it possible to add a socks5 proxy

### ISSUE THREAD

**Issue by kalagxw** [PokemonGoF/PokemonGo-Bot#2248]
### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by xorinzor** [comment]
what are you trying to ask specifically?

**Comment by MrCarlosJr** [comment]
Have notice niantic filter vps ips

**Comment by cwild** [comment]
I thought you could do that with requests and an environment variable:
```/usr/bin/environ HTTPS_PROXY="http://127.0.0.1:12345" python pokecli.py```

I haven't tested this though.

**Comment by em202020** [comment]
@xorinzor Hes asking if there could be proxy integration, as he is worried about Niantic blocking VPSs running (assuming) multiple bots at the same time.

**Comment by xorinzor** [comment]
@em202020 ah, gotcha, that makes sense.

the bot itself doesn't, but it looks like @cwild may have an workaround for this.

Also I wouldn't worry about using multiple bots on the same IP. If you have friends over at your house you're all using the same IP too ;) (or what about people in guest-wifi at a hospital or restaurant?)

**Comment by h3k1ru** [comment]
@xorinzor I think he meant this: https://www.reddit.com/r/pokemongodev/comments/4vhygk/vps_providers_banned_from_accessing_apis/
