### ISSUE TITLE
Never seem to get 100exp

### ISSUE THREAD

**Issue by metheos** [PokemonGoF/PokemonGo-Bot#2250]
### Expected Behavior
Should sometimes get 100exp when catching pokemon.

### Actual Behavior
Lowest value I've seen is 110exp.

### Steps to Reproduce
Set the spin and reticle factors to 0. 
    "catch_randomize_reticle_factor": 0.0,
    "catch_randomize_spin_factor": 0.0,
Wait while pokemon are caught and monitor the EXP earned.

### Other Information
OS: Win64
Git Commit: 494bc055543c3cb674cca781ec545311d3c9bad1
Python Version: 2.7

**Comment by Nathanian** [comment]
Since i updated to the newest version i even get 210 exp with every Pokemon i catch

**Comment by Likael** [comment]
Hello metheos,

It is exact that in the current state you never get to do just a normal it. I am working on the dev that will allow to have a better control over the type of throw you do, and normal throw without bonus will be reintroduced,

**Comment by metheos** [comment]
@Likael Great! Thanks!

**Comment by yoot55** [comment]
@Likael Isn't this dangerous as currently its not possible to get the aim (Nice/Great/Exceellent) bonus on the platform. Not sure if the change was intentional from Niantic's side. But if it was, it would easy to flag botters.

**Comment by Likael** [comment]
Well, that's one more reason to be able to customize the type of throw you want. Also, as far as I know they don't monitor the app version we are using, so even if it was removed, we could still be having an old version that trigger the nice/great/... throws.
