### ISSUE TITLE
[Question-bug?] It's possible catch pokemon and walk simultaneously

### ISSUE THREAD

**Issue by crusardri** [PokemonGoF/PokemonGo-Bot#2254]
I see the bot stop when do actions, for example, in my task config, the bot stop, spin a fort, catch pokemons, recicle items, move, transfer and repeat, and this took about 3-5 seconds or more to move in the map.
It is possible to make te bot walk and catch pokemon/spin forts/transfer/other actions simultaneously?

**Comment by xorinzor** [comment]
Duplicate of #2054 

Please check for existing issues first

**Comment by crusardri** [comment]
@xorinzor yes... and no.
It's not a duplicate, but it like that issue.
I'm not sure if the bot can do this or is the map that gives me that felling

**Comment by xorinzor** [comment]
@crusardri no the bot can't do that yet because it runs only 1 task at a time.

What you're looking for is to do 2 tasks at the same time, ie: multithreading.

**Comment by crusardri** [comment]
@xorinzor ok the, closse this issue then. sorry about the question

**Comment by xorinzor** [comment]
@crusardri you can close the issue yourself :) I don't have the permissions to do so

**Comment by crusardri** [comment]
@xorinzor Ha OK ;D
