### ISSUE TITLE
Why is Zubat released?

### ISSUE THREAD

**Issue by tvb** [PokemonGoF/PokemonGo-Bot#2259]
### Expected Behavior

Keep Zubat 😭 

### Actual Behavior
```
[20:40:09]  A Wild Zubat appeared! [CP 123] [Potential 0.96]
[20:40:09] IV [Attack/Defense/Stamina] = [14/14/15]
[20:40:11]  [-] Zubat is a VIP Pokemon! [CP 123] [Potential 0.96] Nice! Try our best to catch it!
[20:40:11] Catch Rate with normal Pokeball is low (57.27%). Thinking to throw a Razz Berry... (49 left!)
[20:40:12] Threw a berry! Catch Rate with normal Pokeball has increased to 85.91%
[20:40:12] Using Greatball (chance: 108.10%)... (74 left!)
[20:40:13]  Captured Zubat! [CP 123] [Potential 0.96] [14/14/15] [+210 exp]
[20:40:23]  Releasing Zubat with CP 123 and IV 0.96. Matching release rule: CP < 400 OR IV < 0.8.
[20:40:23]  Exchanging Zubat [CP 123] [Potential 0.96] for candy!
```
### Steps to Reproduce
set config:
```
      "any": {"release_below_cp": 400, "release_below_iv": 0.8, "logic": "or"}
```
```
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" }
...
}
```

### Other Information
OS: Pi
Git Commit: 2efe1b581c67e06e4599ab6b714f3c843455647e
Python Version: Python 2.7.3

**Comment by tvb** [comment]
I don't get it. The IV is higher then `0.8` so it should have kept it, even when the CP was below 400.

**Comment by xorinzor** [comment]
the logic is `or` , so when a zubat is below 400 cp OR below 0.8 iv it is released.

If you want zubats to be released when they have less than 400 cp AND less than 0.8 iv you need to set `"logic": "and"`

**Comment by tvb** [comment]
But it this case it had CP of `123` and an IV of `0.96`. So the `"logic": "and"` would not work.

**Comment by 1cu** [comment]
`and`: If CP value is below threshold **and** IV value is below threshold, then the zubat is released.
`or`: If CP value is below threshold **or** IV value is below threshold, then the zubat is released.

If i'm correct, the vip section of your config is irrelevant in this case.

**Comment by xorinzor** [comment]
@tvb let's try to explain it using a math example :)

if the answer to a question is YES, the value is 1, else 0.
OR is +
AND is *

the result needs to be > 0 to work.

So, with the release rule it would work like this:
```
CP < 400 [or] IV < 0.8 (is CP < 400? YES)
1 [or] IV < 0.8 (is CP < 0.8? NO)
1 [or] 0 (or = +)
1 + 0
result: 1
```

if the logic would be AND it would look like:
```
CP < 400 [and] IV < 0.8 (is CP < 400? YES)
1 [and] IV < 0.8 (is CP < 0.8? NO)
1 [and] 0 (and = *)
1 * 0
result: 0
``` 

so with OR the zubat would be released, with AND it wouldnt

**Comment by tvb** [comment]
Thank you for the clear explanation @xorinzor. Shame interpret it wrong 😞

**Comment by xorinzor** [comment]
@tvb no problem, I'm glad you understood what I was trying to teach haha
