### ISSUE TITLE
Walking to pokemons but not catching them?

### ISSUE THREAD

**Issue by harsh1412** [PokemonGoF/PokemonGo-Bot#226]
### Expected Behavior

Catch the pokemons -.-'
### Actual Behavior

So sometimes i see its just walking to some random places but not catching the pokemon and then rewalk from there to some place..
like this:

[#] Walking from (30.319318300000003, 78.0343003) to (30.3218183, 78.0343003) fo
r approx. 10.0 seconds
walking hook  8 [#] Finished walking to (30.3218183, 78.0343003)
(30.3218183, 78.0343003, 0)
[#] Scanning area for objects (46 / 100)
map_cells are 21
[#] Walking from (30.3218183, 78.0343003) to (30.3243183, 78.0343003) for approx
. 10.0 seconds
walking hook  8 [#] Finished walking to (30.3243183, 78.0343003)
(30.3243183, 78.0343003, 0)
[#] Scanning area for objects (47 / 100)
map_cells are 21
[#] Walking from (30.3243183, 78.0343003) to (30.326818300000003, 78.0343003) fo
r approx. 10.0 seconds
walking hook  8 [#] Finished walking to (30.326818300000003, 78.0343003)
(30.326818300000003, 78.0343003, 0)
[#] Scanning area for objects (48 / 100)
map_cells are 21
[#] Something rustles nearby!
[x] Found pokemon at distance 780.949632048m
[#] Walking from (30.326818300000003, 78.0343003) to (30.326137919779427, 78.033
94158134181) for approx. 3.0 seconds
[#] Finished walking to (30.326137919779427, 78.03394158134181)

But some times it catches a pokemon

Why is this so?

**Comment by eggins** [comment]
Just by looking at this - you are using an outedated version. Please pull the latest version of dev and let me know how you go

**Comment by ckrmml** [comment]
Latest version of dev crashes with

```
Traceback (most recent call last):
  File "pokecli.py", line 107, in <module>
    main()
  File "pokecli.py", line 99, in main
    bot.start()
  File "/PokemonGo-Bot/pokemongo_bot/__init__.py", line 26, in start
    self._setup_api()
  File "/PokemonGo-Bot/pokemongo_bot/__init__.py", line 160, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'
```

**Comment by hero16** [comment]
my observation is this is that 

bot scans the area -> found pokemon > walk to location

then upon arrival on pokemon location starts to walk again to another location then the loop goes on. then sometimes actually meets the pokemon at the end of the walk and initiates a capture. but detecting pokemon and walking to location and then scan and move again. 

. Im not sure if this is because of despawn but it happens fairly even with the latest dev. (including master)

**Comment by harsh1412** [comment]
@eggins i am getting same error as @ckrmml when runnning Dev

**Comment by douglascamata** [comment]
@harsh1412 please, destroy your entire environment and reinstall everything from scratch. I also recommend using virtualenv. @eggins can you link the installation tutorial, please?

**Comment by eggins** [comment]
Please follow the tutorial on the Wiki: https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation

**Comment by harsh1412** [comment]
@eggins using windows here :p no wiki for windows

**Comment by harsh1412** [comment]
@douglascamata why do i need to do all that stuffs? The master is running fine except for the walking error other then that Dev should also run..
I may be missing some files.??
Could you check if Dev have complete project?

**Comment by eggins** [comment]
@harsh1412 we are still developing features in the dev part -and once there is a stable release we will release it to the public

**Comment by Calcyfer** [comment]
In my experience, the `player_data` key is not present if there are login issues.
Just run the script again in a few minutes.

And if you're not planning on developing, use the master release. :)

**Comment by hero16** [comment]
by experience yeah player_data is normally associated with login issues as said by Calcyfer

**Comment by eggins** [comment]
These are both incorrect.
Delete the pgoapi folder, and re run the `pip install -r requirements.txt`

**Comment by harsh1412** [comment]
@eggins @Calcyfer @hero16 When i try to run Dev project just by downloading the zip it shows this:

Traceback (most recent call last):
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokecli.py", line 42, in <mod
ule>
    from pokemongo_bot import PokemonGoBot
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", l
ine 10, in <module>
    from pgoapi import PGoApi
ImportError: No module named pgoapi

Then i copied the pgoapi from master...

Now this error pops up:

Traceback (most recent call last):
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokecli.py", line 42, in <mod
ule>
    from pokemongo_bot import PokemonGoBot
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", l
ine 11, in <module>
    from cell_workers import PokemonCatchWorker, SeenFortWorker
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\__
init__.py", line 3, in <module>
    from pokemon_catch_worker import PokemonCatchWorker
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\po
kemon_catch_worker.py", line 5, in <module>
    from utils import distance, print_green, print_yellow, print_red
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\ut
ils.py", line 5, in <module>
    from colorama import init
ImportError: No module named colorama

**Comment by Calcyfer** [comment]
Check the previous comment from @eggins , you need to install the required modules using 
`pip install -r requirements.txt`

**Comment by ckrmml** [comment]
I just redownloaded/cloned the project, followed the wikilink by @eggins https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation and it worked

**Comment by harsh1412** [comment]
@eggins @ckrmml @Calcyfer got the dev bot working but the walking walking walking is still there..
Is this normal or its a bug?

[#] Something rustles nearby!
[#] A Wild Doduo appeared! [CP 372]
[x] Using Pokeball...
[x] Captured Doduo! [CP 372]
[#] A Wild Zubat appeared! [CP 78]
[x] Using Pokeball...
[x] Captured Zubat! [CP 78] - exchanging for candy
[#] Zubat has been exchanged for candy!
[#] Scanning area for objects (4 / 100)
[#] Walking from (30.326818300000003, 78.04430029999999) to (30.3243183, 78.0443
0029999999) for approx. 10.0 seconds
[#] Finished walking
[#] (30.3243183, 78.04430029999999, 0)
[#] Scanning area for objects (5 / 100)
[#] Walking from (30.3243183, 78.04430029999999) to (30.3218183, 78.044300299999
99) for approx. 10.0 seconds
[#] Finished walking
[#] (30.3218183, 78.04430029999999, 0)
[#] Scanning area for objects (6 / 100)
[#] Walking from (30.3218183, 78.04430029999999) to (30.3218183, 78.041800299999
99) for approx. 8.0 seconds

as we can see bot walked 3 times for something right??

**Comment by Calcyfer** [comment]
As you can see, the bot scans for objects in a cell but doesnt find anything. You need to set a location that has a couple of pokestops.

**Comment by harsh1412** [comment]
@eggins Please add a note that we need GIT to run the Dev project..

**Comment by harsh1412** [comment]
@Calcyfer I am not using -s in the command so pokestops are irrelevant in this matter, right?

**Comment by Calcyfer** [comment]
@harsh1412 There has just been a commit that removed the -s parameter and replaced with -m or --mode.

The default parameter is --mode all , meaning search for stops and pokemon.

**Comment by harsh1412** [comment]
@Calcyfer Oww.. but i am near so many pokestops and its not farming any of them..

**Comment by Calcyfer** [comment]
What command line are you using? (dont forget to remove your credentials)

**Comment by harsh1412** [comment]
@Calcyfer pokecli.py -a google -u xxx -p xxx -l "xxx,xxx"  -w 30 --maxstep 10

**Comment by harsh1412** [comment]
Noob question: how do i use the web? :p

**Comment by Calcyfer** [comment]
Your walking speed is pretty high, that's why objects won't load.
Try reducing -w to 4 or so.

For web, use `python -m SimpleHTTPServer 8000` (or another port) in the web folder and open 127.0.0.1:8000 in your browser

**Comment by harsh1412** [comment]
Okay thanks @calcyfer :D

**Comment by harsh1412** [comment]
@calcyfer I tried the map but it shows directory in the 127.0.0.1:8000

**Comment by Calcyfer** [comment]
Make sure you run the command in the \PokemonGo-Bot-dev\web folder, where the index.html file is.

**Comment by harsh1412** [comment]
@calcyfer just navigated to web folder from browser and it worked. lol

**Comment by Calcyfer** [comment]
@jtdroste This issue can be closed.

**Comment by harsh1412** [comment]
Looks like another issue pops up with the latest dev:

  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokecli.py", line 107, in <mo
dule>
    main()
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokecli.py", line 104, in mai
n
    bot.take_step()
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", l
ine 31, in take_step
    self.stepper.take_step()
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokemongo_bot\stepper.py", li
ne 58, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokemongo_bot\stepper.py", li
ne 100, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", l
ine 52, in work_on_cell
    hack_chain = worker.work()
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\se
en_fort_worker.py", line 35, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokemongo_bot\stepper.py", li
ne 79, in _walk_to
    self._work_at_position(i2f(self.api._position_lat), i2f(self.api._position_l
ng), alt, False)
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokemongo_bot\stepper.py", li
ne 100, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", l
ine 38, in work_on_cell
    worker.work()
  File "C:\Users\DrDeath\Desktop\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\po
kemon_catch_worker.py", line 86, in work
    self.transfer_pokemon(list(Set(id_list2) - Set(id_list1)))
NameError: global name 'id_list1' is not defined

**Comment by Calcyfer** [comment]
Best to create a new issue for this, as it's unrelated to this one.
