### ISSUE TITLE
HTTP Request receiving 403 [Forbidden] not 200 [OK]

### ISSUE THREAD

**Issue by yhSimple** [PokemonGoF/PokemonGo-Bot#2265]
### Expected Behavior
The bot should have a 200 HTTP server response (HTTP OK)

### Actual Behavior
The bot receives a 403 HTTP server response (HTTP Forbidden)
> [19:44:12]  PokemonGO Bot v1.0 
> [19:44:12]  No config argument specified, checking for /configs/config.json 
> [19:44:12]  Configuration initialized 
> [19:44:12] [x] Coordinates found in passed in location, not geocoding.
> 2016-08-01 19:44:12,747 [pgoapi.pgoapi] [DEBUG] Set Position - Lat: 48.495722 Long: -4.878503 Alt: 0.0
> [19:44:12] 
> [19:44:12] Location Found: 48.495722,-4.878503
> [19:44:12] GeoPosition: (48.495722,-4.878503, 0)
> [19:44:12] 
> [19:44:12] [x] Parsing cached location...
> 2016-08-01 19:44:12,748 [pgoapi.pgoapi] [DEBUG] Set Position - Lat: 48.495722 Long: -4.878503 Alt: 0.0
> [19:44:12] 
> [19:44:12] [x] Last location flag used. Overriding passed in location
> [19:44:12] [x] Last in-game location was set as: (48.495722, -4.878503, 0)
> [19:44:12] 
> [19:44:12] Attempting login to Pokemon Go.
> 2016-08-01 19:44:12,748 [pgoapi.pgoapi] [DEBUG] Set Position - Lat: 48.495722 Long: -4.878503 Alt: 0.0
> 2016-08-01 19:44:12,748 [pgoapi.pgoapi] [DEBUG] Auth provider: google
> 2016-08-01 19:44:12,748 [pgoapi.auth] [ INFO] Google login for: XXXX@gmail.com
> 2016-08-01 19:44:12,760 [requests.packages.urllib3.connectionpool] [ INFO] Starting new HTTPS connection (1): android.clients.google.com
> 2016-08-01 19:44:13,751 [requests.packages.urllib3.connectionpool] [DEBUG] "POST /auth HTTP/1.1" 200 None
> 2016-08-01 19:44:13,756 [requests.packages.urllib3.connectionpool] [ INFO] Starting new HTTPS connection (1): android.clients.google.com
> 2016-08-01 19:44:13,937 [requests.packages.urllib3.connectionpool] [DEBUG] "POST /auth HTTP/1.1" 200 None
> 2016-08-01 19:44:13,943 [pgoapi.auth] [ INFO] Google Login successful.
> 2016-08-01 19:44:13,944 [pgoapi.auth] [DEBUG] Google Session Token: eyJhbGciOiJSUzI1NiIsImtpZ
> 2016-08-01 19:44:13,944 [pgoapi.pgoapi] [ INFO] Starting RPC login sequence (app simulation)
> 2016-08-01 19:44:13,944 [pgoapi.pgoapi] [ INFO] Create new request...
> 2016-08-01 19:44:13,944 [pgoapi.pgoapi] [ INFO] Adding 'GET_PLAYER' to RPC request
> 2016-08-01 19:44:13,944 [pgoapi.pgoapi] [ INFO] Adding 'GET_HATCHED_EGGS' to RPC request
> 2016-08-01 19:44:13,944 [pgoapi.pgoapi] [ INFO] Adding 'GET_INVENTORY' to RPC request
> 2016-08-01 19:44:13,944 [pgoapi.pgoapi] [ INFO] Adding 'CHECK_AWARDED_BADGES' to RPC request
> 2016-08-01 19:44:13,945 [pgoapi.pgoapi] [ INFO] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
> 2016-08-01 19:44:13,945 [pgoapi.pgoapi] [DEBUG] Arguments of 'DOWNLOAD_SETTINGS': 
> {'hash': '05daf51635c82611d1aac95c0b051d3ec088a930'}
> 2016-08-01 19:44:13,945 [pgoapi.pgoapi] [ INFO] Execution of RPC
> 2016-08-01 19:44:13,945 [pgoapi.rpc_api] [DEBUG] Generating main RPC request...
> 2016-08-01 19:44:13,946 [pgoapi.rpc_api] [DEBUG] Generating sub RPC requests...
> 2016-08-01 19:44:13,987 [pgoapi.rpc_api] [DEBUG] Subrequest class: POGOProtos.Networking.Requests.Messages_pb2.DownloadSettingsMessage
> 2016-08-01 19:44:13,988 [pgoapi.rpc_api] [DEBUG] Generated protobuf request: 
> status_code: 2
> request_id: 8145806132888207460
> requests {
>   request_type: GET_PLAYER
> }
> requests {
>   request_type: GET_HATCHED_EGGS
> }
> requests {
>   request_type: GET_INVENTORY
> }
> requests {
>   request_type: CHECK_AWARDED_BADGES
> }
> requests {
>   request_type: DOWNLOAD_SETTINGS
>   request_message: "\n(05daf51635c82611d1aac95c0b051d3ec088a930"
> }
> latitude: 48.495722
> longitude: -4.878503
> auth_info {
>   provider: "google"
>   token {
>     contents: "eyJhbGciOiJSUzI1NiIsImtpZCI6IjYxOTJhNmIwNjE2ODUzMjE3MzJjNGJhMTBjMDEwOTY5YWUyZjU1YmMifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXVkIjoiODQ4MjMyNTExMjQwLTdzbzQyMWpvdHIyNjA5cm1xYWtjZXV1MWx1dXEwcHRiLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTEzMzI2MTQ4MjEyMTA2NDU3NjMwIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6Ijg0ODIzMjUxMTI0MC0zdmRydHJmZG50bGpmMnU0bWxndG5ubGhuaWduMzVkNS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImVtYWlsIjoianVzdHJlZWNlYmVuc29uQGdtYWlsLmNvbSIsImlhdCI6MTQ3MDA4MDY1NCwiZXhwIjoxNDcwMDg0MjU0fQ.K6PKHnJKR96IxIYnW77m9H9Q15S43tiJzlRde30zm_9nwM0QhGjKfrJ0FETwl64OffrquWSrLNhjuHoLg-jCuTfnVT9MhZcUmh8dVplMOqODjCfkdtxrtkFXDm8EpQtRhylF5o2AXjAqifpfKntX6KVDfppAOM2Td8pikipsSO-tn3nXK8h3uecSeQXp4RRwhJ45qEOnhOR8mPszCz-nVd8S2mYBnF5-OZyLUnqyFQiOczRz8Kq4Le_KTqIP0bJwPPF-SJG2QdQB5X_rm7ywMlnSRDSom9Di2ckmZJy7bBaShHVFLja0PRJXpyeNKCC0mSyywLUFOZrGJLzb_XoArw"
>     unknown2: 59
>   }
> }
> unknown12: 989
> 
> 2016-08-01 19:44:13,988 [pgoapi.rpc_api] [DEBUG] Execution of RPC
> 2016-08-01 19:44:13,990 [requests.packages.urllib3.connectionpool] [ INFO] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
> 2016-08-01 19:44:14,142 [requests.packages.urllib3.connectionpool] [DEBUG] "POST /plfe/rpc HTTP/1.1" 403 None
> 2016-08-01 19:44:14,144 [pgoapi.rpc_api] [DEBUG] Parsing main RPC response...
> 2016-08-01 19:44:14,144 [pgoapi.rpc_api] [WARNING] Unexpected HTTP server response - needs 200 got 403
> 2016-08-01 19:44:14,144 [pgoapi.rpc_api] [DEBUG] HTTP output: 
> <html>
> <head><title>403 Forbidden</title></head>
> <body bgcolor="white">
> <center><h1>403 Forbidden</h1></center>
> <hr><center>nginx/1.11.1</center>
> </body>
> </html>
> 
> 2016-08-01 19:44:14,144 [pgoapi.pgoapi] [ INFO] Cleanup of request!
> 2016-08-01 19:44:14,147 [pgoapi.pgoapi] [ INFO] Login failed!
> [19:44:14]  [X] Login Error, server busy 
> [19:44:14]  [X] Waiting 10 seconds to try again

### Steps to Reproduce
Download latest git from dev and run.

### Other Information
OS: CentOS Linux release 7.2.1511 (Core)
Git Commit: da73b3dbe08959e572853fbe13ac25744732cdab
Python Version: 2.7.5

**Comment by MartinTerp** [comment]
are you using an VPS?
it looks like they blocked alot of vps providers, amazon, azura, digital ocean

**Comment by yhSimple** [comment]
Yes I am. Seems like that would be the issue, will confirm later on and try the same build on my PC.

On 1 Aug 2016, at 21:15, MartinTerp <notifications@github.com<mailto:notifications@github.com>> wrote:


are you using an VPS?
it looks like they blocked alot of vps providers, amazon, azura, digital ocean

-
