### ISSUE TITLE
ValueError: Expecting , Delimiter (Python Version related?)

### ISSUE THREAD

**Issue by jring314** [PokemonGoF/PokemonGo-Bot#2267]
### Expected Behavior
Bot should start

### Actual Behavior
Errors out before starting

### Other Information
OS: Windows 10

Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\jring_000>cd C:\Users\jring_000\Downloads\Pokemon\PokemonGo-Bot4\PokemonGo-Bot

C:\Users\jring_000\Downloads\Pokemon\PokemonGo-Bot4\PokemonGo-Bot>git pull
Already up-to-date.

C:\Users\jring_000\Downloads\Pokemon\PokemonGo-Bot4\PokemonGo-Bot>pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): numpy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): networkx==1.11 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi (from -r requirements.txt (line 3))
  Skipping because already up-to-date.
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): protobuf==3.0.0b4 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): protobuf-to-dict==0.1.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): googlemaps==2.4.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): colorama==0.3.7 in c:\python27\lib\site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): enum34==1.1.6 in c:\python27\lib\site-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): pyyaml==3.11 in c:\python27\lib\site-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): haversine==0.4.5 in c:\python27\lib\site-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): polyline==1.3.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): python-socketio==1.4.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): flask==0.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): socketIO_client==0.7.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): eventlet==0.19.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): universal-analytics-python==0.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 20))
Requirement already satisfied (use --upgrade to upgrade): gpxpy==1.1.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 21))
Requirement already satisfied (use --upgrade to upgrade): mock==2.0.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 22))
Requirement already satisfied (use --upgrade to upgrade): timeout-decorator==0.3.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 23))
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.4.0 in c:\python27\lib\site-packages (from networkx==1.11->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): six in c:\python27\lib\site-packages (from pgoapi->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from protobuf==3.0.0b4->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): future in c:\python27\lib\site-packages (from s2sphere==0.2.4->-r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): python-engineio>=0.8.0 in c:\python27\lib\site-packages (from python-socketio==1.4.2->-r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): click>=2.0 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): websocket-client in c:\python27\lib\site-packages (from socketIO_client==0.7.0->-r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.3 in c:\python27\lib\site-packages (from eventlet==0.19.0->-r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): funcsigs>=1; python_version < "3.3" in c:\python27\lib\site-packages (from mock==2.0.0->-r requirements.txt (line 22))
Requirement already satisfied (use --upgrade to upgrade): pbr>=0.11 in c:\python27\lib\site-packages (from mock==2.0.0->-r requirements.txt (line 22))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in c:\python27\lib\site-packages (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 17))
Installing collected packages: pgoapi
  Running setup.py develop for pgoapi
Successfully installed pgoapi-1.1.0

C:\Users\jring_000\Downloads\Pokemon\PokemonGo-Bot4\PokemonGo-Bot>python pokecli.py -cf configs\config.json
[14:51:14]  PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 452, in <module>
    main()
  File "pokecli.py", line 53, in main
    config = init_config()
  File "pokecli.py", line 124, in init_config
    load.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 87 column 7 (char 2093)

C:\Users\jring_000\Downloads\Pokemon\PokemonGo-Bot4\PokemonGo-Bot>

**Comment by thereyrey** [comment]
I usually get this error when i make a mistake in my config file. 

Worth to check it.. like it says line 87 in your config.

**Comment by jring314** [comment]
yep, found it. Was a missing "," at the end of a line I added to the release rules. Thanks
