### ISSUE TITLE
Softbanned

### ISSUE THREAD

**Issue by drees5** [PokemonGoF/PokemonGo-Bot#2270]
how to set mode to "poke"
OSX

**Comment by xorinzor** [comment]
It is very unclear what you're trying to ask.

What `mode` are you talking about? and what does it have to do with beeing softbanned?

**Comment by drees5** [comment]
sorry i should of searched previous issues first

**Comment by Philipp59** [comment]
did you mean  https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Softban ?
its outdated for dev, dev has an urban spin task.
It was written for master

**Comment by xorinzor** [comment]
@philipp59 ah, that makes sense :)

**Comment by pokecunt** [comment]
![81298424-588f-11e6-8d3a-e8f887b64582](https://cloud.githubusercontent.com/assets/20769107/17323209/34cb7934-5899-11e6-944e-d0a1d3fa0eae.jpg)

**Comment by N3W4L** [comment]
Hi have the same question, what did you found ? could you share it ? 
I don't understand the softban page.
I am in the middle oft central Park, but there is literaly nothing. Do you have a solution please ?
Many thanks.

**Comment by Philipp59** [comment]
ny server is down
