### ISSUE TITLE
KeyError: 'GET_INVENTORY'

### ISSUE THREAD

**Issue by xiejiachen** [PokemonGoF/PokemonGo-Bot#2271]
```python
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/Users/jiachenxie/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/Users/jiachenxie/PokemonGo-Bot/pokemongo_bot/__init__.py", line 159, in _setup_api
    balls_stock = self.pokeball_inventory()
  File "/Users/jiachenxie/PokemonGo-Bot/pokemongo_bot/__init__.py", line 234, in pokeball_inventory
    inventory_dict = inventory_req['responses']['GET_INVENTORY'][
KeyError: 'GET_INVENTORY'


```

**Comment by Evanito** [comment]
This error is usually due to some level of Niantic Servers being down.

Are you running the most recent version? After updating I stopped seeing this error.

**Comment by DrTheMick** [comment]
If you get this or the login error, just try to run it again. Depending on how the server is doing I will have to try 2-3x.

**Comment by McAttack** [comment]
One dirty quick way to fix this is:
For this to work you have to be running the python script from within the directory it resides.
When this catches the `KeyError` it just runs an os.system command to launch the script again.
The reason I say it is a bit dirty is that you now have the real thread running as a sub process of the original thread which threw the exception. This could be implemented in the code base pretty easily with a better handling of the exception then just re-running the script again.

``` 
# pokecli.py replace line 206
    try:
        bot = PokemonGoBot(config)
        try:
            bot.start()
        except KeyError:
            logger.log('[x] Restarting, got KeyError', 'red')
            os.system("./pokecli.py")

```
