### ISSUE TITLE
Bot not recycling items

### ISSUE THREAD

**Issue by Dud3z** [PokemonGoF/PokemonGo-Bot#2273]
Im on DEV Branch

### Expected Behavior
Not needed inventory will be thrown away.

### Actual Behavior
not throwing anything away.

### Steps to Reproduce
Start the bot

### Other Information
OS: 
Git Commit: da73b3dbe08959e572853fbe13ac25744732cdab
Python Version: Python 2.7.9

Config Looks like this:
![image](https://cloud.githubusercontent.com/assets/20781313/17309327/97cfeb06-583e-11e6-954c-355e6221ced7.png)

Bot says:
![image](https://cloud.githubusercontent.com/assets/20781313/17309366/d041f218-583e-11e6-8c08-bc430867b423.png)

as of the config it should throw alot away... but it doesnt...

Problem exists since last git pull

**Comment by Evanito** [comment]
You have it improperly configured:
```
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
			  "1": { "keep" : 50 },
			  "2": { "keep" : 50 },
			  "3": { "keep" : 50 },
			  "101": { "keep" : 10 },
			  "102": { "keep" : 25 },
			  "103": { "keep" : 25 },
			  "201": { "keep" : 25 },
			  "701": { "keep" : 100 }
          }
        }
      },
```

**Comment by Dud3z** [comment]
no i havent.. dev wiki says i can use the names.

**Comment by Evanito** [comment]
Pay very close attention to the part where it says:
`"item_filter": {`

**Comment by Dud3z** [comment]
oh... damn... sorry!

PS.: THX
