### ISSUE TITLE
Tasks in Config File gets ignored

### ISSUE THREAD

**Issue by Waliers** [PokemonGoF/PokemonGo-Bot#2275]
### Expected Behavior
The tasks I assign into the config file must be used.

### Actual Behavior
No mather what I put into the config file it doesn't do the tasks I assign. When using the example of just farming pokestops it still catches pkmn. It does read the credentials, location and Google Key.

### Steps to Reproduce
Default master installation and the following in the config file:

```
{
    "auth_service": "google",
    "username": "username@gmail.com",
    "password": "password",
    "location": "30.0072868, -95.5207881",
    "gmapkey": "GOOGLE KEY",
    "tasks": [
    {
      "type": "RecycleItems"
    },
    {
      "type": "SpinFortWorker"
    },
    {
      "type": "MoveToFortWorker"
    }
  ],
    "max_steps": 5,
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104",
    "evolve_all": "NONE"
    
}

```

**Comment by katanakiwi** [comment]
Rename the file to config.json
Standard installation asks you to execute
`cp config.json.example config.json`

Other option would be to execute with
`python pokecli.py -cf configs/config.json.example`

**Comment by Philipp59** [comment]
search the difference 

```
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
```

**Comment by Waliers** [comment]
Fixed. TY Philipp59! Don't know what went wrong but just started from scratch and now it works.
