### ISSUE TITLE
error in config file

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [PokemonGoF/PokemonGo-Bot#2276]
"// Mew evolves to Mewtwo": {},

I'm not sure what this does, but Mew does NOT evolve into Mewtwo

**Comment by Mooseymax** [comment]
The // at the start means it is just a comment.
Probably an oversight by whoever made the example config file.

**Comment by justinbeatz** [comment]
I think what @CtrlAltDefeat94 means is that Mew doesn't evolve into Mewtwo, they are 2 separates pokemon.

**Comment by Evanito** [comment]
Everyone knows that when two mews love each other very much...
