### ISSUE TITLE
[Problem] 

### ISSUE THREAD

**Issue by gagas3113** [PokemonGoF/PokemonGo-Bot#228]
module object has no attribute 'fork'

**Comment by jtdroste** [comment]
Please re-pull from the dev branch.  The fork code was removed in a later commit

**Comment by gagas3113** [comment]
Cloning into 'PokemonGo-Bot'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by jtdroste** [comment]
Make sure you're running `git clone https://github.com/PokemonGoF/PokemonGo-Bot.git`

**Comment by douglascamata** [comment]
@gagas3113 using windows?

**Comment by gagas3113** [comment]
yes, but i dont know its already fixed now.

**Comment by gagas3113** [comment]
THANKS TO ALL
