### ISSUE TITLE
ValueError: Expecting property name: line 60 column 7 (char 1324)

### ISSUE THREAD

**Issue by dguillot** [PokemonGoF/PokemonGo-Bot#2280]
### Expected Behavior
Should start Pokemon BOT

### Actual Behavior
Traceback (most recent call last):
  File "pokecli.py", line 452, in <module>
    main()
  File "pokecli.py", line 53, in main
    config = init_config()
  File "pokecli.py", line 124, in init_config
    load.update(json.load(data))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 60 column 7 (char 1324)

### Steps to Reproduce
Just pull the latest DEV branch, used the new config file example and changed my login info. When I run it, it fails.

pok1@pokebot1:~/PokemonGo-Bot$ git pull
remote: Counting objects: 81, done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 81 (delta 48), reused 35 (delta 35), pack-reused 12
Unpacking objects: 100% (81/81), done.
From https://github.com/PokemonGoF/PokemonGo-Bot
   a9fd95b..eee7ba4  dev        -> origin/dev
   5df9610..b3c53ce  feature/event-log -> origin/feature/event-log
Updating a9fd95b..eee7ba4
Fast-forward
 CONTRIBUTORS.md                             |  2 ++
 configs/config.json.example                 |  5 ++++-
 pokecli.py                                  |  1 -
 pokemongo_bot/__init__.py                   | 41 +++++++++++++++++++++--------------------
 pokemongo_bot/cell_workers/incubate_eggs.py |  2 +-
 pokemongo_bot/cell_workers/move_to_fort.py  | 63 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
 web                                         |  2 +-
 7 files changed, 91 insertions(+), 25 deletions(-)

**Comment by justinbeatz** [comment]
Replace MoveToFort section with this:

{
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
},

**Comment by dguillot** [comment]
it crashed after that pull.
According to the pull, there was some changes to configs/config.json.example | 5 ++++-

So I created a new config.json  from it and put my login info and changed back to my settings:

"max_steps": 10,
 "walk": 4,
 "location_cache": false,
"release": {
      "any": {"release_below_cp":20000, "release_below_iv": 0, "logic": "or"},

**Comment by dguillot** [comment]
ok let me try this

**Comment by yihengli** [comment]
@justinbeatz 
It works. They missed a bracket

**Comment by dguillot** [comment]
@justinbeatz Give this man a raise! thx

**Comment by thedewil** [comment]
Created a PR to fix the issue with #2282
