### ISSUE TITLE
evolve_all "all" is not working

### ISSUE THREAD

**Issue by JSchwerberg** [PokemonGoF/PokemonGo-Bot#2281]
### Expected Behavior
Bot would try to evolve all eligible pokemon when "evolve_all": "all" is set

### Actual Behavior
Bot does not evolve anything when "evolve_all": "all" is set.  If I set it to "evolve_all": "all,Weedle" I get the following output: 

```
[19:11:08]  Starting PokemonGo Bot....
[19:11:09]  [x] Current egg hatches in 0.85 km
[19:11:10] [#] Successfully evolved Weedle with 180 CP and 0.4 IV!
[19:11:13] [#] Successfully evolved Weedle with 113 CP and 0.51 IV!
```

### Steps to Reproduce
Set "evolve_all" to all on this commit

### Other Information
OS: Ubuntu 14.04.4 LTS
Git Commit: eee7ba49c5c4e6bb1b3efefcf9f99a7c72a48671
Python Version: python 2.7.6

**Comment by CadeBrown** [comment]
Having this bug as well.

**Comment by OliverNicolini** [comment]
Las working commit 86472c0a2f8aa61381bebff3022acbffc568998c

**Comment by JSchwerberg** [comment]
I've made pull request #2305 which fixes this -- if anyone wants to test and confirm, and comment over there, I'd appreciate it :)

**Comment by ewold** [comment]
Confirmed working fix 👍

**Comment by feydreva** [comment]
same issue on dev.
"evolve_all": "all" do not work
"evolve_all": "Rattata, Zubat" works fine
