### ISSUE TITLE
Keep Best CP/IV only if above release_below_cp/iv

### ISSUE THREAD

**Issue by CapCap** [PokemonGoF/PokemonGo-Bot#2283]
```
"release": {
    "any": {
                "keep_best_cp": 3, 
                "keep_best_iv": 3, 
                "release_below_cp": 500, 
                "release_below_iv": 0.5, 
                "logic": "and"
    }
}
```

Would mean:
keep best 3 by CP, best 3 by IV, but only if they're above the release_below_cp/iv

**Comment by MFizz** [comment]
No currently it keeps best 3 by CP, best 3 by IV and then applies the other criteria. Now I think this case needs to be choosable to, so we would need another parameter for priority. Is there a way to configure that in a cleaner way?

**Comment by Arderos** [comment]
Guys, could we please also implement a version of this logic, but not above release_below_cp/iv but **below** it?

**Comment by mzygmunt** [comment]
Yea, it is awesome feature. I'm waiting for it a long time.
