### ISSUE TITLE
Feature Request: Wildcard Item Handling

### ISSUE THREAD

**Issue by Evanito** [PokemonGoF/PokemonGo-Bot#2284]
### Idea: ###
Instead of keeping 50 Pokeballs, 50 Greatballs, and 50 Ultraballs, use a wildcard to represent all items of the same type ("AnyBall", "AnyBerry", "AnyRevive", "AnyPotion") so you can keep a set number of that type, while discarding the lowest priority version to make room for the better items.

### Example: ###
1. Config is set to keep 100 of AnyBall
2. Player holds 30 Pokeballs, 60 Greatballs, 10 Ultraballs, totalling 100 of AnyBall
3. Player picks up 3 Ultraballs at a pokestop, going over the target.
4. 3 Pokeballs are discarded, because they are the lowest priority.

Follow this pattern with the other wildcard types:
- "AnyBall"
- "AnyBerry"
- "AnyRevive"
- "AnyPotion"

After all, why would you discard an Ultraball when you can get rid of something worse instead?

**Comment by pokecunt** [comment]
![81298424-588f-11e6-8d3a-e8f887b64582](https://cloud.githubusercontent.com/assets/20769107/17323381/e9f3b5e2-5899-11e6-82d3-918fb0b03856.jpg)

**Comment by aleskr** [comment]
I do agree with you, there is no point in specifying what to keep like we do today. I don't see any reason of doing it any other way than this.

I did just create a pull request(#2459) that allows the user to specify a number of balls to keep, and then the good balls will be prioritized. My opinion is that the recycle stuff should be recreated and instead behave like you are specifying here, for both potions and balls.
