### ISSUE TITLE
[BUG][DEV] Error in _is_response_valid

### ISSUE THREAD

**Issue by avallete** [PokemonGoF/PokemonGo-Bot#2285]
### Expected Behavior
After login, display the user current inventory.

### Actual Behavior
After login, the api_wrapper always give an error "Server is busy...." in the function `self._print_character_info()` after `self.login()`.

### Steps to Reproduce
On my side, just launch the bot after a fresh clone.

### Other Information

After a little debugging the error seem to come from the method `_is_response_valid` in `pokemongo_bot/api_wrapper.py`.

In the last check, we check if every requests performed have a response in the api. But, when I debug each `request_caller in request_callers`.

I can see the error occurs every time a `request_caller` named `_REQ_METHOD_LIST` is in the request. But I was unable to locate where this method was implemented in the request (don't find it in pgoapi, nor in  POGOProtos or RPC_Calls).

So, I tried to add an exception to didn't check check if the api give a response to this request `_REQ_METHOD_LIST`. And with this exception, the bot work fine (loggin, connect, start walk, catch, etc..)

If I'm not the only one experiencing this issue, that would be great de dig deeper on this problem (Where he come from, how to avoid it cleanly).

OS: Linux
Git Commit: b04c1ccf301e16022d1683309f46c7c7d9636e2d
Python Version: Python 2.7.6

**Comment by pokecunt** [comment]
![81298424-588f-11e6-8d3a-e8f887b64582](https://cloud.githubusercontent.com/assets/20769107/17323381/e9f3b5e2-5899-11e6-82d3-918fb0b03856.jpg)
