### ISSUE TITLE
[Feature Request] Adding GPS coordinates to captured log

### ISSUE THREAD

**Issue by DimaVIII** [PokemonGoF/PokemonGo-Bot#2287]
It will be nice to log where Pokemon's been captured.
If the bot capture a nice Pokemon you can note the exact location and time so after a while you have a nice list of rare pokemon spots. 

A bit more advanced:
The bot is capture one of your configured VIP Pokemon's and save the time, location and name in a separate text file.

### Expected Behavior
[01:47:51]  Captured Shellder! [CP 383] [Potential 0.69] [5/12/14] [+210 exp] [40.213555,-73.123663]

**Comment by Evanito** [comment]
Good idea, this will help with finding rare pokemon "nests"!

**Comment by MartinTerp** [comment]
maybe to a seperate file? 
Also it could be cool to create a community based gmap of all the points collected.

**Comment by pokecunt** [comment]
![81298424-588f-11e6-8d3a-e8f887b64582](https://cloud.githubusercontent.com/assets/20769107/17323381/e9f3b5e2-5899-11e6-82d3-918fb0b03856.jpg)
