### ISSUE TITLE
[new function needed] in my environment，i had to set a socks5 （not http） proxy to access the internet

### ISSUE THREAD

**Issue by kalagxw** [PokemonGoF/PokemonGo-Bot#2290]
i am wondering if there is a way to add socks proxy function to the config files，and use “true” or “flase” to switch on and off。

**Comment by pokecunt** [comment]
![81298424-588f-11e6-8d3a-e8f887b64582](https://cloud.githubusercontent.com/assets/20769107/17323381/e9f3b5e2-5899-11e6-82d3-918fb0b03856.jpg)
