### ISSUE TITLE
Keeps login error

### ISSUE THREAD

**Issue by ChristianYeah** [PokemonGoF/PokemonGo-Bot#2293]
### Expected Behavior
Login Error, server busy

### Actual Behavior
Login Error, server busy

### Steps to Reproduce
I'd like to run it on my servers on digitalocean, but it failed on logging in.

Did niantic bans all cloud providers' ip?

### Other Information
OS: 
Git Commit: 78c5f2bc8c5aeafb902309583cfab621179bed4e
Python Version: 2.7.*

**Comment by ChristianYeah** [comment]
I updated the whole project and still got the same problem

**Comment by justinbeatz** [comment]
All known cloud services are banned from niantic.

**Comment by jomarocas** [comment]
OK FOR ME I DEACTIVATED AUTH IN TWO STEPS of google and working
