### ISSUE TITLE
Fastest pokemon go bot ! 300pkms/h

### ISSUE THREAD

**Issue by mfron** [PokemonGoF/PokemonGo-Bot#2294]
IM A FUCKING LOSER WHO HAS NO LIFE

**Comment by ConflictWY** [comment]
This suppose to be advertisement?

**Comment by fari-99** [comment]
@ConflictWY yes. this guy need someone to recognize his work.

**Comment by WillM88** [comment]
Make sure to go to his profile and report him with the current page url link.

**Comment by fari-99** [comment]
how to report this guy,
1. go to his profile by click [here](https://github.com/mfron).
2. in top you will see block or report button, click that
3. tell github that he's using issue in someone git to advertise his work or something. 
4. don't forget to link this issue, and he's create another issue too.
5. click send request.

**Comment by perru** [comment]
Logged just to report him :).

Thx to real developpers.

**Comment by perru** [comment]
Logged just to report him :).

Thx to real developpers.

**Comment by perru** [comment]
Logged just to report him.

Thx to real developpers.

**Comment by perru** [comment]
Logged just to report him.

Thx to real developpers.

**Comment by perru** [comment]
Logged just to report him.

Thank to real developpers.

**Comment by eggins** [comment]
Bye.
