### ISSUE TITLE
stops walking

### ISSUE THREAD

**Issue by albinzeka** [PokemonGoF/PokemonGo-Bot#2295]
### Expected Behavior
keep exploring

### Actual Behavior
moves two locations then stops

**Comment by chadhao** [comment]
sounds like we've got the same problem here. #2291

**Comment by pokecunt** [comment]
![81298424-588f-11e6-8d3a-e8f887b64582](https://cloud.githubusercontent.com/assets/20769107/17323381/e9f3b5e2-5899-11e6-82d3-918fb0b03856.jpg)

**Comment by sgitkene** [comment]
full inventory most likely. reduce amount of pokeballs or something, so it throws away stuff.

**Comment by g0wfv** [comment]
Same here!

I am recycling (bag not full) and removed FollowSpiral task in config.

Commit 5927c3b8a900ff79ce72fb8447c6c75dbb8ea858

Log:
> [06:28:12] Moving towards fort National Cycle Network, 0.05km left
> [06:28:16]  Now at Pokestop: National Cycle Network 
> [06:28:16]  Spinning ... 
> [06:28:16]  Loot:  
> [06:28:16]  50 xp 
> [06:28:17]  - 2x Pokeball (Total: 49) 
> [06:28:17]  - 1x Greatball (Total: 1) 
> [06:28:17] PokeStop on cooldown. Time left: 4 minutes, 59 seconds
> [06:31:02]  [x] Next egg incubates in 1.87 km 
> [06:43:43]  Session stale, re-logging in 
> [06:43:43] Attempting login to Pokemon Go.
> [06:43:44]  Login to Pokemon Go successful. 
> [07:12:44]  Session stale, re-logging in 
> [07:12:44] Attempting login to Pokemon Go.
> [07:12:45]  Login to Pokemon Go successful. 
> [07:19:38] Something rustles nearby!
> [07:19:38]  A Wild Goldeen appeared! [CP 393] [Potential 0.51] 
> [07:19:38] IV [Attack/Defense/Stamina] = [8/1/14]
> [07:19:41] Using Pokeball (chance: 37.43%)... (48 left!)
> [07:19:42]  Captured Goldeen! [CP 393] [Potential 0.51] [8/1/14] [+210 exp] 
> [07:19:48]  Keep 2 best Goldeen, based on cp and iv 
> [07:19:48]  Goldeen [CP 540] [Potential 0.93] 
> [07:19:48]  Goldeen [CP 564] [Potential 0.76] 
> [07:19:48]  Transferring 1 pokemon 
> [07:19:48]  Exchanging Goldeen [CP 393] [Potential 0.51] for candy! 
> [07:41:45]  Session stale, re-logging in 
> [07:41:45] Attempting login to Pokemon Go.
> [07:41:46]  Login to Pokemon Go successful. 
> [08:10:46]  Session stale, re-logging in 
> [08:10:46] Attempting login to Pokemon Go.
> [08:10:48]  Login to Pokemon Go successful. 
> [08:19:38] Something rustles nearby!
> [08:19:39]  A Wild Staryu appeared! [CP 299] [Potential 0.71] 
> [08:19:39] IV [Attack/Defense/Stamina] = [10/9/13]
> [08:19:42] Using Pokeball (chance: 43.22%)... (47 left!)
> [08:19:43]  Captured Staryu! [CP 299] [Potential 0.71] [10/9/13] [+210 exp] 
> [08:19:49]  Keep 2 best Staryu, based on cp and iv 
> [08:19:49]  Staryu [CP 299] [Potential 0.71] 
> [08:19:49]  Staryu [CP 550] [Potential 0.49] 
> [08:19:49]  Transferring 1 pokemon 
> [08:19:49]  Exchanging Staryu [CP 484] [Potential 0.64] for candy! 

Log 2:

> [17:30:45] Moving towards fort Monks Road Coop Bell Tower, 0.04km left
> [17:30:50]  Now at Pokestop: Monks Road Coop Bell Tower 
> [17:30:50]  Spinning ... 
> [17:30:51]  Loot:  
> [17:30:51]  50 xp 
> [17:30:51]  - 3x Pokeball (Total: 53) 
> [17:30:51] PokeStop on cooldown. Time left: 4 minutes, 58 seconds
> [17:30:55]  -- Discarded 3x Pokeball (keeps only 50 maximum)  
> [17:34:28]  ------------------------------ 
> [17:34:28]  [!] Eggs hatched, but we had trouble with the response. Please check your inventory to find your new pokemon! 
> [17:34:28]  [x] Now incubating a 2.0km egg 
> [17:37:02] Something rustles nearby!
> [17:37:02]  A Wild Zubat appeared! [CP 225] [Potential 0.62] 
> [17:37:02] IV [Attack/Defense/Stamina] = [7/14/7]
> [17:37:04] Using Pokeball (chance: 40.01%)... (49 left!)
> [17:37:06]  Captured Zubat! [CP 225] [Potential 0.62] [7/14/7] [+210 exp] 
> [17:37:12]  Keep 2 best Zubat, based on cp and iv 
> [17:37:12]  Zubat [CP 382] [Potential 0.51] 
> [17:37:12]  Zubat [CP 225] [Potential 0.62] 
> [17:37:12]  Transferring 1 pokemon 
> [17:37:12]  Exchanging Zubat [CP 359] [Potential 0.6] for candy! 
> [17:38:10] Something rustles nearby!
> [17:38:11]  A Wild Pidgey appeared! [CP 26] [Potential 0.6] 
> [17:38:11] IV [Attack/Defense/Stamina] = [4/15/8]
> [17:38:14] Using Pokeball (chance: 100.00%)... (48 left!)
> [17:38:15]  Captured Pidgey! [CP 26] [Potential 0.6] [4/15/8] [+210 exp] 
> [17:38:21]  Keep 2 best Pidgey, based on cp and iv 
> [17:38:21]  Pidgey [CP 393] [Potential 0.6] 
> [17:38:21]  Pidgey [CP 292] [Potential 0.71] 
> [17:38:21]  Transferring 1 pokemon 
> [17:38:21]  Exchanging Pidgey [CP 26] [Potential 0.6] for candy! 
> [17:38:30] Something rustles nearby!
> [17:38:31]  A Wild Pidgey appeared! [CP 336] [Potential 0.62] 
> [17:38:31] IV [Attack/Defense/Stamina] = [3/15/10]
> [17:38:33] Using Greatball (chance: 45.74%)... (9 left!)
> [17:38:34]  Captured Pidgey! [CP 336] [Potential 0.62] [3/15/10] [+210 exp] 
> [17:38:40]  Keep 2 best Pidgey, based on cp and iv 
> [17:38:40]  Pidgey [CP 393] [Potential 0.6] 
> [17:38:40]  Pidgey [CP 292] [Potential 0.71] 
> [17:38:40]  Transferring 1 pokemon 
> [17:38:40]  Exchanging Pidgey [CP 336] [Potential 0.62] for candy! 
> [17:41:14] Something rustles nearby!
> [17:41:15]  A Wild Zubat appeared! [CP 58] [Potential 0.56] 
> [17:41:15] IV [Attack/Defense/Stamina] = [8/2/15]
> [17:41:18] Using Pokeball (chance: 78.21%)... (47 left!)
> [17:41:19]  Captured Zubat! [CP 58] [Potential 0.56] [8/2/15] [+210 exp] 
> [17:41:25]  Keep 2 best Zubat, based on cp and iv 
> [17:41:25]  Zubat [CP 382] [Potential 0.51] 
> [17:41:25]  Zubat [CP 225] [Potential 0.62] 
> [17:41:25]  Transferring 1 pokemon 
> [17:41:25]  Exchanging Zubat [CP 58] [Potential 0.56] for candy!

**Comment by g0wfv** [comment]
Or maybe it stops for some other reason - there seems to be a time gap between spinning the Pokestop then hatching the egg suggesting that it's stopped moving prior to hatching?!
