### ISSUE TITLE
[!] Eggs hatched, but we had trouble with the response. 

### ISSUE THREAD

**Issue by metheos** [PokemonGoF/PokemonGo-Bot#2297]
### Expected Behavior
See information about pokemon that just hatched.

### Actual Behavior
[!] Eggs hatched, but we had trouble with the response. Please check your inventory to find your new pokemon!

### Steps to Reproduce
Hatch an egg.

### Other Information
OS: Win64
Git Commit: e58bf3d57c1c74d7847fdfa55b08410f48917bd0
Python Version: 2.7

**Comment by lhung** [comment]
Repeat #2228

**Comment by pokecunt** [comment]
![81298424-588f-11e6-8d3a-e8f887b64582](https://cloud.githubusercontent.com/assets/20769107/17323381/e9f3b5e2-5899-11e6-82d3-918fb0b03856.jpg)

**Comment by sgitkene** [comment]
Have had this too.

**Comment by maestroi** [comment]
please close repeat #2228
