### ISSUE TITLE
TransferPokemon Worker Relies on Pokemon Name & Not ID

### ISSUE THREAD

**Issue by scottgoering** [PokemonGoF/PokemonGo-Bot#2298]
### Expected Behavior
TransferWorker should transfer pokemon, regardless of their name, if any pokemon meet the criteria in the config file.

### Actual Behavior
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/transfer_pokemon.py#L15
The transfer worker is based on the name and not an ID.  When using the NicknameWorker (b35260d76d5a86beada062f84deb475bd5d4a06c) and changing the name to anything besides the default, the Pokebag fills up.

### Steps to Reproduce
Here's my config: http://pastebin.com/0x8041LZ
Line 21 is for the NicknameWorker: "nickname_template": "{iv_pct}_{iv_ads}"
Since the new names (i.e. "100_15/15/15" or "18_0/7/1") don't match any names in the "release" config, it doesn't transfer any.

### Other Information
OS: Ubuntu 16.04 LTS
Git Commit: e58bf3d57c1c74d7847fdfa55b08410f48917bd0
Python Version: Python 2.7.12

**Comment by scottgoering** [comment]
Actually, you might be able to close this.  Testing now.  I didn't have the TransferPokemon task in the task list.

**Comment by reddivision** [comment]
#2238
