### ISSUE TITLE
* FEATURE * Assign value to a pokemon instead of only accounting for CP or IV

### ISSUE THREAD

**Issue by CadeBrown** [PokemonGoF/PokemonGo-Bot#2301]
### Expected Behavior

We should be able to assign a value to the pokemon, based on CP, IV, and Level to rank them, and decide which to evolve/transfer. For example.
{cp} represents cp
{iv} represents iv
{lvl} represents the pokemon level
{trainer_lvl} represents the trainer's level

I would say the value is the {iv} * {cp}, and it would sort each  species by this, and transfer the lowest value of {iv} * {cp}.

Let's look at an example: Magikarp. Say I have 3 magikarp, and we need to decide which to evolve.
1. 180 CP, .13 IV
2. 13 CP, .98 IV
3. 150 CP, .7 IV

If we had it transfer all lower CPs, we would get a 180CP and .13IV magikarp, if we sorted by IV, we would get a 13 CP, .98 IV magikarp. But, if we sorted by IV * CP, we would get 150 CP, .7 IV, which I would rather have. This is not a pressing feature, but I think it would be nice.

Example usage (in config):
"value_formula": "{iv} * {cp}"
And then under "release_config",
"keep_top_value_formula": 2
And that config would keep the top 2 pokemons with the highest CP * IV

### Actual Behavior

Currently only CP or IV is used

### Steps to Reproduce

Feature request

**Comment by iruy** [comment]
I was rather thinking to implement something like this to decide which pokemon to keep, like a `keep_best_cp_iv` with a `cp_iv_tollerance` value, to range for example 10% below or above CP and IV value. Then, the `evolve_all` task would pick the best choice

**Comment by pokecunt** [comment]
![81298424-588f-11e6-8d3a-e8f887b64582](https://cloud.githubusercontent.com/assets/20769107/17323381/e9f3b5e2-5899-11e6-82d3-918fb0b03856.jpg)

**Comment by cprior** [comment]
A maximizing strategy supposedly is to not eveolve until Level 20 or higher. So any suggestion that takes the trainer level into account gets my
+1

Of course one could run a bot for ~50 hours and then check its level manually -- eventually followed by a manual restart with new config settings.

These are the commonly suggested Pokemons to use in level >20 together with XP-boost
jq '.[] | {name: .Name, candycost: ."Next Evolution Requirements".Amount} | select(.candycost != null) |  select(.candycost < 25)' pokemon.json.txt 
{
  "name": "Caterpie",
  "candycost": 12
}
{
  "name": "Weedle",
  "candycost": 12
}
{
  "name": "Pidgey",
  "candycost": 12
}

**Comment by pokecunt** [comment]
I agree. 

![download](https://cloud.githubusercontent.com/assets/20769107/17323633/c5edc6b4-589a-11e6-8285-3efa33c75939.jpg)

**Comment by sgitkene** [comment]
Actually cp is kinda irrelevant. the only thing with cp is, the more you have, the stronger the pokemon *now*. But IV is the pokemon's potential. that 13cp 91IV magikarp will only need about 50 more candy and some dust to be far stronger than the other ones.
You may think now "but the 13cp magikarp will only be a 166cp gyarados". But that can be boosted with candy and dust. every pokemon has 40.5 levels and if it has more cp then the other, it likely means it is just a higher level already, meaning it will cost a little less dust and candy to reach max level. But it will always cost the same to reach level 40.5 and there will be significant difference in their cp and hp at level 40.5 based on their IV.
check [pokeassistant](https://pokeassistant.com/main/ivcalculator)

@cprior concerning not evolving until lvl 20< : you are better off evolving and thus reaching higher levels quicker and saving up the high IV pokemon. You will undoubtedly have enough stardust and candy to spend on powering up pokemon especially if you use a bot.

Remember, the only thing that makes a higher cp pokemon more valuable is the stardust and candy saved on leveling it up. If they all have perfect IV, then of course I'd take the one with highest cp, but not before.
