### ISSUE TITLE
[MASTER] RazzBerry not being used !

### ISSUE THREAD

**Issue by leovarmak** [PokemonGoF/PokemonGo-Bot#2302]
### Expected Behavior

Use Razz Berry when needed

### Actual Behavior

Razz Berry is not used at all. How should I configure that in the `config.json` ? I need to enable that on **Master**
### Other Information
OS: Mac OS X 10.11.6
Git Commit: 4182e93f9bfbe471d07b74e95c55cdfbacda127b
Python Version: Python 2.7.12

**Comment by urbels** [comment]
Update to dev. Master does not use razz berries afaik

**Comment by pokecunt** [comment]
![81298424-588f-11e6-8d3a-e8f887b64582](https://cloud.githubusercontent.com/assets/20769107/17323381/e9f3b5e2-5899-11e6-82d3-918fb0b03856.jpg)

**Comment by maestroi** [comment]
works on dev please close.

**Comment by leovarmak** [comment]
@maestroi Its better you keep your mouth shut. I was asking about `Master` not `dev`. Read the thing properly first. If you can't help please don't comment unnecessaryly
