### ISSUE TITLE
requirements.txt error

### ISSUE THREAD

**Issue by beauterham** [PokemonGoF/PokemonGo-Bot#2307]
After downloading requirements.txt i get a big red command error
After downloading this it ask to download the pgoapi but that never seems to work

https://puu.sh/qmtJV/13f0d4fc58.png

**Comment by iruy** [comment]
Maybe this can help for pgoapi issue [link](http://stackoverflow.com/a/27871374/1151408)

**Comment by dkim1000** [comment]
What was the big red command error?

**Comment by reddivision** [comment]
that's because you can't install pgoapi directly from pip, it's not an actual package. you have to install it from `requirements.txt` which uses pip magic to turn the pgoapi github repo into a python package that pip can install.

**Comment by dkim1000** [comment]
I'm not an expert on this, but it seems to me like pgoapi is not the problem here. The python script is complaining that it cannot find the module to load in pgoapi.

I suspect this is because your setup failed while installing requirements.txt and this might have messed up the imports.

**Comment by reddivision** [comment]
@dkim1000, they issued the command `sudo pip install pgoapi`, which you just can't do. but you're right, they need to resolve whatever issues were happening when they run `sudo pip install -r requirements.txt`

**Comment by beauterham** [comment]
@reddivision @dkim1000 

i tryed using 'sudo pip install -r requirements.txt' but still the same error:

`Command "/Users/Jonas/Desktop/pokemonGo/PokemonGo-Bot/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-cjFkvR/pycryptodomex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-YkhnGJ-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/Jonas/Desktop/pokemonGo/PokemonGo-Bot/bin/../include/site/python2.7/pycryptodomex" failed with error code 1 in /private/tmp/pip-build-cjFkvR/pycryptodomex/`

So there is notting what i can do to fix this? The owner have to fix it?

**Comment by pokecunt** [comment]
![81298424-588f-11e6-8d3a-e8f887b64582](https://cloud.githubusercontent.com/assets/20769107/17323381/e9f3b5e2-5899-11e6-82d3-918fb0b03856.jpg)

**Comment by iruy** [comment]
@pokecunt could you just stop spamming this f**ing img?! Notifications keep blinking

**Comment by sgitkene** [comment]
do you have only python2 installed?

**Comment by beauterham** [comment]
i only have python 2.7 installed yes. Do i also need to have 3.5?

**Comment by sgitkene** [comment]
no I was thinking maybe python3 was interfering because that happens if you have both installed.

**Comment by maestroi** [comment]
Try to run setup.py

**Comment by bel90** [comment]
I have the same problem. Running _sudo pip install -r requirements.txt_ don't work well. I installed some of the requirements with _pip install name_ but that dont work with the pgoapi. 
http://imgur.com/a/2yQyv (Screenshot when the installing fails. I use python 2.7 and linux). I hope someone can help.

**Comment by maestroi** [comment]
sudo pip install --upgrade -r requirements.txt

**Comment by Dreanmer** [comment]
sudo apt-get install python-dev 
pip install -r requirements.txt

**Comment by maestroi** [comment]
@Dreanmer dont do this in your os, do this in virtualenv
