### ISSUE TITLE
Evolve low pokemons that have many candies, 

### ISSUE THREAD

**Issue by julienkessels** [PokemonGoF/PokemonGo-Bot#231]
### Expected Behavior
command -e (evolve) if im using the 30 minutes double xp egg to evolve pokemons and get double xp out of it. Manually it takes for ever and i cant even evolve half of my pokemons during those 30 minutes. As i get tons of candies through botting

### Actual Behavior
not implemented yet

### Steps to Reproduce
-e (evolving)
evolves pidgeys, ratatas, etc

**Comment by 2spook5me** [comment]
This is already on the to-do list.

**Comment by surfaace** [comment]
Evolve function added dd2b11af77f3546c204d0799dfe04becf7394ba1
