### ISSUE TITLE
[DEV] Often "Server seems to be busy or offline - try again"

### ISSUE THREAD

**Issue by Gregwar** [PokemonGoF/PokemonGo-Bot#2312]
I am getting really often the `Server seems to be busy or offline - try again` message, resulting in a really slow bot:

![busy](https://cloud.githubusercontent.com/assets/367022/17322224/c3e1a884-589c-11e6-848b-3bf53239798b.png)

I'm using follow cluster strategy, so most  of the pokemons catched are lured.

**Comment by arnogues** [comment]
because server seems to be busy or offline...

**Comment by Gregwar** [comment]
@arnogues it doesn't look like so, because the behaviour would be more erratic then
In this case, it almost always block at the same action

**Comment by pokecunt** [comment]
![81298424-588f-11e6-8d3a-e8f887b64582](https://cloud.githubusercontent.com/assets/20769107/17323381/e9f3b5e2-5899-11e6-82d3-918fb0b03856.jpg)

**Comment by Gregwar** [comment]
@pokecunt this is Github, not 9Gag

**Comment by Gregwar** [comment]
@pokecunt I know they added emojis and smileys, but this is still for coding

**Comment by Gregwar** [comment]
@arnogues I confirm this doesn't seems to happen when using `MoveToFort`

**Comment by vicch** [comment]
Have you tried the solution at https://github.com/tejado/pgoapi/commit/e6db98b9a931731a9f449365a31dc1a9b794f5a0 ? Worked for me.
