### ISSUE TITLE
Location cannot be parsed

### ISSUE THREAD

**Issue by ou-snaaksie** [PokemonGoF/PokemonGo-Bot#2313]
### Expected Behavior
Bot starts at location as defined in `config.json`.

### Actual Behavior
Error message:
```
[2016-08-02 10:36:04] [x] PokemonGO Bot v1.0
[2016-08-02 10:36:04] [x] Configuration initialized
[2016-08-02 10:36:04] [x] The location given using -l could not be parsed. Checking for a cached location.
```

### Steps to Reproduce
Start the bot on the newest Master.

**Comment by arnogues** [comment]
It's not a bug, it's a user bug, if you don't define good location, the last location will be used.

**Comment by pokecunt** [comment]
![81298424-588f-11e6-8d3a-e8f887b64582](https://cloud.githubusercontent.com/assets/20769107/17323381/e9f3b5e2-5899-11e6-82d3-918fb0b03856.jpg)
