### ISSUE TITLE
[Issue] Suddenly transfer pokemons on startup with master branch

### ISSUE THREAD

**Issue by afro001** [PokemonGoF/PokemonGo-Bot#2314]
### Expected Behavior
Start script as usual without changing config and start farming.

### Actual Behavior
At startup suddenly started to transfer weaker pokemons. I don't know the rule that bot applied (CP or IV)

### Other Information
OS: Windows 10 64bit
Master branch.
Initial transfer was never changed from false.
I had ~100 pokemons so not full.
Python Version: 2.7

**Comment by arnogues** [comment]
use dev branch

**Comment by iruy** [comment]
Bot should be printing out matched rules when releasing

**Comment by pokecunt** [comment]
![81298424-588f-11e6-8d3a-e8f887b64582](https://cloud.githubusercontent.com/assets/20769107/17323381/e9f3b5e2-5899-11e6-82d3-918fb0b03856.jpg)

**Comment by afro001** [comment]
Unfortunately no rule printed.

> [2016-08-02 06:19:22] [x] Starting PokemonGo Bot....
[2016-08-02 06:19:22] [#] Scanning area for objects (1 / 4)
[2016-08-02 06:19:22] [#] Walking from (54.3518848, 18.6505109) to (54.3518848, 18.6505109) for approx. 0.00 seconds
[#] (54.3518848, 18.6505109, 0)
[#] Attempting to evolve all pokemons ...
[#] Evolved 101 pokemons! Checking if any of them needs to be released ...
[2016-08-02 06:19:23] [#] Parasect has been exchanged for candy!
[2016-08-02 06:19:24] [#] Raticate has been exchanged for candy!
[2016-08-02 06:19:24] [#] Raticate has been exchanged for candy!
[2016-08-02 06:19:24] [#] Lickitung has been exchanged for candy!
[2016-08-02 06:19:25] [#] Clefairy has been exchanged for candy! 

I don't use dev because there is always development pending and it is often not working. I don't know when it is stable in dev.

**Comment by iruy** [comment]
What do you have in config.json under `release`?

**Comment by afro001** [comment]
> "any": {
        "release_under_cp": 700,
        "release_under_iv": 0.9,
        "cp_iv_logic": "and"
    },
    "Bulbasaur":    { "release_under_cp": 374, "release_under_iv": 0.8, "cp_iv_logic": "and" },
    "Ivysaur":      { "release_under_cp": 571, "release_under_iv": 0.8, "cp_iv_logic": "and" },
    "Venusaur":     { "release_under_cp": 902, "release_under_iv": 0.8, "cp_iv_logic": "and" },
    "Charmander":   { "release_under_cp": 333, "release_under_iv": 0.8, "cp_iv_logic": "and" },
    "Charmeleon":   { "release_under_cp": 544, "release_under_iv": 0.8, "cp_iv_logic": "and" },
    "Charizard":    { "release_under_cp": 909, "release_under_iv": 0.8, "cp_iv_logic": "and" },
    "Squirtle": { "release_under_cp": 352, "release_under_iv": 0.8, "cp_iv_logic": "and" },
    .....

But this release config shouldn't be used only for new catched pokemons? For them it is working perfect.
Strange is sudden initial release when I just run script with not modified configs after 2 hours since last use. It transfered even pokemons I had for longer than a week.

**Comment by iruy** [comment]
release config will be applied when you get a new pokemon, which can happen in 2 ways; the pokemon appears and you catch it, the pokemon is result of evolution. So, probably, those released pokemon matched your `release` `any` config

**Comment by afro001** [comment]
Yes, for sure they matched. But why I used this script for few days running it more than 50 times and it initially transfered pokemons just this morning and using rules that should be applied only for new obtained pokemons? That is strange to me.

**Comment by iruy** [comment]
How many times were your pokemon evolved during last 50 plays? If any, probably you were keeping low leveled pokemon, that once evolved matched the release config

**Comment by afro001** [comment]
I do few evolvings a day, manually on my mobile using official app.
Decision which pokemons to evolve is made by me basing on statistics of catched pokemons from bot log (usually key is highest CP).
However there was transfered also Lickitung which has no possible evolution and was with me for more than a week. All the pokemons transfered today were 1-7 days old.

As I said before, I don't see any logic in this transfer, I will be maybe more carefull during bot launch.

Sorry for the offtopic - how to know if I can use dev revision or not? I don't clone repo using git, just download the zip file. I know that dev has many enhancements now and unfortunately there was no master update for few days (only readme file updated lately). I have tried few times dev with other ptc account but it was always unstable revision, not catching pokemons, crushing after launch or something. But on the other hand I can see that people are somehow using dev revision so is there any way to download working dev revision?

**Comment by sgitkene** [comment]
I think on startup it is checked if there are any pokemon to be released. just set the filter so that it only releases pokemon you really don't want. Usually you should keep the highest IV pokemon. IV determines which pokemon are going to be strongest in the long run.
for using dev:
`git clone https://github.com/pokemongof/pokemongo-bot
git checkout dev`
and follow install instructions from the wiki.
