### ISSUE TITLE
configuration error?

### ISSUE THREAD

**Issue by gilgo** [PokemonGoF/PokemonGo-Bot#2316]
### Actual Behavior
$ python pokecli.py -cf ./configs/config2.json
[11:58:14]  PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 442, in <module>
    main()
  File "pokecli.py", line 53, in main
    config = init_config()
  File "pokecli.py", line 124, in init_config
    load.update(json.load(data))
  File "D:\Program Files (x86)\Python\lib\json\__init__.py", line 290, in load
    **kw)
  File "D:\Program Files (x86)\Python\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files (x86)\Python\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files (x86)\Python\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

### Steps to Reproduce
This happens with every config file i use (this one is the example file saved as a regular config2.json but same error occures with edited configs)

already tried reinstalling the requirements files.

### Other Information
OS:  windows 7
Git Commit: cd21fdd002183cd8709e506282a378606f696a40
Python Version: Python 2.7.10

**Comment by iruy** [comment]
Check the [Wiki](https://github.com/PokemonGoF/PokemonGo-Bot/wiki/No-JSON-object-could-be-decoded-or-decoder.py-error)

**Comment by gilgo** [comment]
.jason checks out as valid

**Comment by iruy** [comment]
Can you post your config2.json?

**Comment by MZorzy** [comment]
check example.json, maybe missed some new change

**Comment by gilgo** [comment]
I feel like an idiot...
well i cant seem to understand why but i tried to do the same again and now it checks out and returned to normal...

thanks for the help guys and sorry for wasting your time

**Comment by pokecunt** [comment]
![81298424-588f-11e6-8d3a-e8f887b64582](https://cloud.githubusercontent.com/assets/20769107/17323381/e9f3b5e2-5899-11e6-82d3-918fb0b03856.jpg)

**Comment by gilgo** [comment]
[http://imgur.com/gallery/LbrPKu1](url)

**Comment by bebci** [comment]
I'm having the same JSON issue and I checked the JSON Validator with the config.json file and it says that the problem is with my gmail. Does anyone know why?
