### ISSUE TITLE
[Problem] Nub Question - cannot install pgoapi

### ISSUE THREAD

**Issue by dominikue** [PokemonGoF/PokemonGo-Bot#232]
I have some trouble to install pgoapi for the new dev version with the git commant. Can i just download it and put it to /Scripts? Doesn't find any information with google.

_C:\Users\name\Desktop\PokemonGo-Bot>pip install -e git://github.com/tejado/pgoapi.git#egg=pgoapi
Obtaining pgoapi from git+git://github.com/tejado/pgoapi.git#egg=pgoapi
  Cloning git://github.com/tejado/pgoapi.git to c:\users\dominik\desktop\pokemongo-bot\src\pgoapi
  Error [Error 2] The System cannot find the file while executing command git clone -q git://github.com/tejado/pgoapi.git C:\Users\Dominik\Desktop\PokemonGo-Bot\src\pgoapi
Cannot find command 'git'_

### Other Information
OS: Windows 10 -64
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by eggins** [comment]
Cannot find command 'git'

You dont have git installed to your command line~!
