### ISSUE TITLE
upgrade /data/items.json

### ISSUE THREAD

**Issue by MZorzy** [PokemonGoF/PokemonGo-Bot#2324]
### Expected Behavior
add new item quantity to RecycleItems to drop if many , like "Incense" or "Lure Module"

### Actual Behavior
drop "Incense"
crash if add "Lure Module"

i see that is not "Lure Module" on /data/items.json , upgrade to reflect pokemongo name item?

**Comment by maestroi** [comment]
Error Message is nog included here.
please provide
