### ISSUE TITLE
remove deprecated cli arguments

### ISSUE THREAD

**Issue by kinvaris** [PokemonGoF/PokemonGo-Bot#2326]
### Expected Behavior

For the CLi to work or it should be removed.

### Actual Behavior

```
jonas@moon:~/PokemonGo-Bot$ ./pokecli.py -cf release_config.json.example
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-p PASSWORD] [-l LOCATION] [-lc LOCATION_CACHE] [-m MODE]
                  [-w WALK] [-k GMAPKEY] [-ms MAX_STEPS]
                  [-it INITIAL_TRANSFER] [-d DEBUG] [-t TEST]
                  [-du DISTANCE_UNIT] [-if ITEM_FILTER] [-ev EVOLVE_ALL]
                  [-ec EVOLVE_CAPTURED]
pokecli.py: error: argument -a/--auth_service is required
```

### Steps to Reproduce

`./pokecli.py -cf release_config.json.example`

### Other Information
OS:  `Linux moon 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
Python Version: `Python 2.7.6`

**Comment by xorinzor** [comment]
try renaming `release_config.json.example` to `release_config.json`

**Comment by kinvaris** [comment]
No, if you don't use the CLi anymore. You should remove the python parser from `pokecli`

**Comment by xorinzor** [comment]
@kinvaris CLI is still used by people though, and there is no reason to remove that functionality

**Comment by maestroi** [comment]
You need to use 

> config.json 

not release?

**Comment by xorinzor** [comment]
@maestroi ah, yes, I completely overlooked that :) 

its indeed the `config.json` file you need, not `release_config.json`

If you updated from an older version, check out the new config files in the /configs directory, there have been a lot of changes.

**Comment by maestroi** [comment]
@xorinzor yes dev is crazy :+1:  Please close issue
