### ISSUE TITLE
Hatching eggs is not working

### ISSUE THREAD

**Issue by RomanFausek** [PokemonGoF/PokemonGo-Bot#2327]
### Expected Behavior
Bot should put egg into incubator the moment it receives a new egg if any of the incubators are available.

### Actual Behavior
No mark in terminal of putting the eggs in incubators. After logging in with iOS device the incubators are empty and the inventory is full of unhatched eggs.

### Steps to Reproduce
Followed instructions during the installation - everything works fine: catching pokémons, walking etc. However It seems not taking into count the fact that it should hatch eggs automatically.

### Other Information
OS: OSX
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by xorinzor** [comment]
What does your config look like? did you add the tasks for the eggs?

**Comment by RomanFausek** [comment]
I am using example config from git and now I am trying to add this code but no change.

`"tasks": [
    {
      "type": "IncubateEggs",
      "config": {
        "longer_eggs_first": true
      }
    }`

**Comment by xorinzor** [comment]
Do you only have the `IncubateEggs` task?

You will need the bot to walk around if you actually want to see anything happen too (ie: move to forts, or `FollowSpiral`)

**Comment by RomanFausek** [comment]
Well i thought hatching eggs is default behavior. Do you have example config with classic behavior + hatching? This is what I have now https://infinit.io/_/QBdqcnu

**Comment by xorinzor** [comment]
@RomanFausek have a look at the example config files.

Especially: https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/configs/config.json.pokemon.example

**Comment by RomanFausek** [comment]
I copy pasted whole config and terminal is still not hatching eggs

**Comment by xorinzor** [comment]
@RomanFausek can you run the commands from **other information** so we know what commit and python version you're using? That might help.

Also please copy your complete config here (make sure to remove your google maps key, username and password)

**Comment by RomanFausek** [comment]
Config is exactly the one you sent. Only with my info.

git: 78c5f2bc8c5aeafb902309583cfab621179bed4e
python: Python 2.7.12

**Comment by maestroi** [comment]
master or dev?
dev is working fine

**Comment by xorinzor** [comment]
@maestroi check his latest comment with the git commit info, it's the master branch

**Comment by ubu13** [comment]
Yes dev working fine, i do new dev clone today using elementary os 64bit inside my vmware. Install from beginning, reconfigure release config, what i got today is bot very aggresive to catch pokemon and moving..

**Comment by RomanFausek** [comment]
And now I've got another problem with new cfg. It is evolving all caught pokemons. Config is caching somehow?

`{
        "type": "EvolveAll",
        "config": {
          "evolve_all": "NONE",
          "evolve_cp_min": 1000,
          "evolve_speed": 20,
          "use_lucky_egg": false
        }
      },`

**Comment by maestroi** [comment]
@xorinzor it was a readme commit xD

**Comment by xorinzor** [comment]
@RomanFausek check your `evolve_captured` value

**Comment by RomanFausek** [comment]
@xorinzor `"evolve_captured": "NONE",`

**Comment by INGCRENGIFO** [comment]
why "location cache": false,? is better?

**Comment by maestroi** [comment]
@INGCRENGIFO everytime u restart bot it goes from where it left if put it to true, is better than teleporting back and forward every time
