### ISSUE TITLE
Not moving to any forts as there aren't enough space. You might want to change your config to recycle more items if this message appears consistently.

### ISSUE THREAD

**Issue by igoldny** [PokemonGoF/PokemonGo-Bot#2328]
what is this new message means?

what am is suppose to change? RecycleItems section?
{
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },

**Comment by xorinzor** [comment]
it means your item bag is full, so spinning pokestops would be of no use

**Comment by Likael** [comment]
Well, Pokestops are still a usefull quick source of xp.
#2188 has the solution for that, but still need to be validated.

**Comment by Taylor-S** [comment]
You can also set your item filter so that your total items in your bag won't reach their limit. For example, I set potions to 0 as I find plenty of supers and hypers now.

**Comment by igoldny** [comment]
nice idea, thnx for the help
