### ISSUE TITLE
[DEV] Text colors removed

### ISSUE THREAD

**Issue by DokterPhill** [PokemonGoF/PokemonGo-Bot#2331]
### Expected Behavior
In the DEV build the colored text in cmd had been replaced with normal (white) text, while master uses colored text for all kinds of notifications e.d. Is there any reason for this? I liked being able to see in one glance what's going on.

### Other Information
OS: win10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by 1cu** [comment]
Works fine here. 

Sure you didn't change the terminal (settings)?

Current dev:
![02-08-2016 13-03-10](https://cloud.githubusercontent.com/assets/1742418/17326449/c5baeeee-58b1-11e6-8fee-be5245d5ef85.png)

**Comment by DokterPhill** [comment]
I checked, if i run it manually (cmd pokecli.py) i get the colored version, if i use run.bat i dont.
