### ISSUE TITLE
[FEATURE] join a gym if there is available place

### ISSUE THREAD

**Issue by mushi8** [PokemonGoF/PokemonGo-Bot#2333]
I know there is a strong stance against automating gym battles but what about just join in a gym that is owned by your team and have a place for you?

### Actual Behavior
When seeing a gym for that is owned by your team and the lvl i high enough go to it and join it.

**Comment by 1cu** [comment]
Defending a gym (by joining it) is just like attacking - won't happen.

**Comment by mushi8** [comment]
Then its closed
