### ISSUE TITLE
ValueError: Expecting property name

### ISSUE THREAD

**Issue by Erody** [PokemonGoF/PokemonGo-Bot#2335]
### Actual Behavior
Just updated to latest dev, and now the bot won't start.

When starting the bot this happens:   
   

> [13:26:00]  PokemonGO Bot v1.0 
> Traceback (most recent call last):
>   File "pokecli.py", line 442, in <module>
>     main()
>   File "pokecli.py", line 53, in main
>     config = init_config()
>   File "pokecli.py", line 124, in init_config
>     load.update(json.load(data))
>   File "/usr/lib/python2.7/json/__init__.py", line 290, in load
>     **kw)
>   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
>     obj, end = self.scan_once(s, idx)
> ValueError: Expecting property name: line 30 column 9 (char 666)
> 

Here is the relevant part of the config file:  
  
```
 "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolveAll",
        "config": {
          "evolve_speed": 20,
          "use_lucky_egg": false,
          "evolve_all": "NONE",
          "evolve_cp_min": 300,
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort"
      },
      {
        "type": "FollowSpiral"
      },
      {
        "type": "FollowCluster",
        "config": {
            "radius": 50,
            "lured": true
        }
      },
      {
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_file": "configs/path.example.json"
        }
      }
    ],
    "max_steps": 7,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 10
    },
    "walk": 7,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
```

### Other Information
OS: Ubuntu 14.04
Git Commit: 5927c3b8a900ff79ce72fb8447c6c75dbb8ea858
Python Version: Python 2.7.6

**Comment by rodang** [comment]
`"config": {
          "evolve_speed": 20,
          "use_lucky_egg": false,
          "evolve_all": "NONE",
          "evolve_cp_min": 300,
        }`

The last comma after "evolve_cp_min":300 is incorrect JSON. Try changing it to 

`"config": {
          "evolve_speed": 20,
          "use_lucky_egg": false,
          "evolve_all": "NONE",
          "evolve_cp_min": 300
        }`

You can copy paste your entire config file to https://jsonformatter.curiousconcept.com/ to see if there is any more JSON-errors.

**Comment by Erody** [comment]
Changed that, now I'm getting this error:   
   

> Traceback (most recent call last):
  File "pokecli.py", line 442, in <module>
    main()
  File "pokecli.py", line 53, in main
    config = init_config()
  File "pokecli.py", line 124, in init_config
    load.update(json.load(data))
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by Erody** [comment]
Nevermind, found another error in my config. Now it's working.
