### ISSUE TITLE
[feature request] add ability to use potions, instead/before recycling

### ISSUE THREAD

**Issue by jimmywarting** [PokemonGoF/PokemonGo-Bot#2338]
I want a task where i heal Pokémon instead of recycle them

**Comment by maestroi** [comment]
please provide more information

**Comment by ironbishop** [comment]
Healing is for battles, battle is for gyms, gym will not be implemented.
It's described in the README.

**Comment by jimmywarting** [comment]
I think healing should not be part of the battle/gym it can be a separat task

**Comment by maestroi** [comment]
so what has healing to do with recycle ? there is no option for gym fights.
@ironbishop is right

**Comment by jimmywarting** [comment]
instad of throwing them away, try and see if there are any pokemon's that needs it

**Comment by maestroi** [comment]
Dude you mean that items needs to be used on pokemons instead of recycle a potion?
if there will be any fighting implemented than it has use

**Comment by jimmywarting** [comment]
> Dude you mean that items needs to be used on pokemons instead of recycle a potion?
Yes

**Comment by ironbishop** [comment]
you should change the title to "[feature request] add ability to use potions, instead/before recycling"
