### ISSUE TITLE
Mac cpu went to 96 degree when try to evolve pokemon

### ISSUE THREAD

**Issue by yqrashawn** [PokemonGoF/PokemonGo-Bot#2339]
### Expected Behavior
cooler mac and evolve

### Actual Behavior
mac's cpu went to 95 degree, stuck attempt to evolve pokemon

### Steps to Reproduce
Just evolve bunch of pokemons

### Other Information
OS: macOS 10.11.5
Git Commit: (7ae44aaaa4ff75a7f9e0834bcde611396be8bef0)
Python version : 2.7.12

**Comment by maestroi** [comment]
You meen cpu usage is 96%?
if it get 95 degrees warm its a problem of your mac not the bot.
