### ISSUE TITLE
[Suggestion] New parameters to use pokkeballs

### ISSUE THREAD

**Issue by crusardri** [PokemonGoF/PokemonGo-Bot#234]
A parameter to say the bot when you can use a pokeball, for example.

--Pokeball 500 (Only catch pokemon PC 0-500 with pokeballs, high priority)
--Greatball 1000 (Only catch pokemon PC 0-1000 with great balls, low priority)
--Ultraball false (don't catch pokemons with ultraballs)

I hope you understand my idea
Sorry for my bad english

**Comment by Klohto** [comment]
#116 #119 #208

**Comment by crusardri** [comment]
my idea is for say the bot when must use a pokeball, or if you don't want to use a pokeball.

**Comment by jtdroste** [comment]
This is tied with #142 - and is also a current ongoing discussion.  I'm going to close this in favor of #142
