### ISSUE TITLE
NicknamePokemon don't rename when the name already respect the template.

### ISSUE THREAD

**Issue by kalyon** [PokemonGoF/PokemonGo-Bot#2340]
### Expected Behavior
do nothing when the name of the pokemon it's already ok

### Actual Behavior
If you activate the function 
      {
        "type": "NicknamePokemon",
        "config": {
		"nickname_template": "{iv_pct}_{iv_ads}"
	}
      },
it will rename the pokemon who are already rename previously
should compare the current name to avoid a not necessary renaming.

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by reddivision** [comment]
It already checks if the current nickname matches the new nickname and skips it. Any pokemon being renamed do not match the current template. Otherwise your entire inventory would be renamed each tick.
