### ISSUE TITLE
installing requirements error

### ISSUE THREAD

**Issue by thelegendy** [PokemonGoF/PokemonGo-Bot#2341]
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-94u813q6/pycryptodomex/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_fofnak7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-94u813q6/pycryptodomex/

### Other Information
OS: OpenSuse Leap 42.1
Git Commit: 4182e93f9bfbe471d07b74e95c55cdfbacda127b
Python Version: Python 2.7.12

**Comment by maestroi** [comment]
you need python 2.7 not 3.
also you need to provide full log and the branch

**Comment by thelegendy** [comment]
cloned from master branch if you saying this. when i try to install requirements, i'm having this error and of course i'cant run pokecli.py

which log do you want? while installing requirements?

**Comment by maestroi** [comment]
Did you use python 2.7 this time?

**Comment by ChrisEngstrom** [comment]
I had the same issue. Running the requirements command with pip2 instead of pip worked for me if I remember correctly.

**Comment by maestroi** [comment]
@ChrisStory that is more common on windows, you are not using opensuse i guess?

**Comment by thelegendy** [comment]
I'm using Python 2.7.12 already.

There is no option like pip2 :(

**Comment by ChrisEngstrom** [comment]
Oops, my bad. Forgot to check thelegendy's OS. You are correct though, was a Windows issue for me.

**Comment by maestroi** [comment]
@thelegendy  "/usr/bin/python3 -u  is python 3 not 2, please provide new error,
pip2 is in windows.

**Comment by hackenho** [comment]
I got this and I installed gcc then it worked.

**Comment by thelegendy** [comment]
I already installed gcc :) but still don't work
