### ISSUE TITLE
Bot not walking to location in path.json

### ISSUE THREAD

**Issue by Erody** [PokemonGoF/PokemonGo-Bot#2343]
### Expected Behavior
Walks from location to location as specified in path.json

### Actual Behavior
Just wanders off to random pokestops, usually in the opposite direction from the location in the file.   
   
My config:   
```   
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolveAll",
        "config": {
	  "evolve_all": "NONE",
	  "evolve_cp_min": 300,
          "evolve_speed": 20,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 50 },
	    "Ultraball":      { "keep" : 100},
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 0 },
            "Hyper Potion":   { "keep" : 20 },
            "Revive":         { "keep" : 0 },
            "Razz Berry":     { "keep" : 80 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": false,
            "lure_max_distance": 500
        }
      },
      {
        "type": "FollowSpiral"
      },
      {
        "type": "FollowCluster",
        "config": {
            "radius": 50,
            "lured": true
        }
      },
      {
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_file": "configs/path.example.json"
        }
      }
    ],
```

My path.example.json file:

`[
	{"location": "40.739769, -73.983389"},
	{"location": "40.7405645512,-73.9825897155"}
]`

### Steps to Reproduce
Set a path, watch the bot ignore it

### Other Information
OS: 14.04
Git Commit: 5927c3b8a900ff79ce72fb8447c6c75dbb8ea858 
Python Version: 2.7.6

**Comment by INGCRENGIFO** [comment]
Hi, sorry but I'm new at this. What you try to do is scroll through the bot pokestop only 2 ?? I have nothing and works well defined, making it ban prevents your way?

**Comment by maestroi** [comment]
walk speed? those cordinates are pretty close

**Comment by mrik974** [comment]
I would remove the `FollowSpiral` part, as it (if I got it right) restarts the tasks loop. If you have a defined path you don't need it.
 Also, the task loop is ordered by priority. The `MoveToFort` task conflicts with your `FollowPath` task and has a higher priority. You can remove it. Any fort the bot will find in your defined path will be spinned with the `SpinFort` task

**Comment by rajtho** [comment]
same for me as well.  The bot doesnt start walking after the login.
      {
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_file": "./configs/path.short.newport.json"
        }
      }

cout for bot is (nothing happens after the last statement):
[19:50:11] Resolving Navigation Paths (GeoLocating Strings)
[19:50:11] [x] Coordinates found in passed in location, not geocoding.
[19:50:11] [x] Coordinates found in passed in location, not geocoding.
[19:50:11] [x] Coordinates found in passed in location, not geocoding.
[19:50:11]  Starting PokemonGo Bot.... 
[19:50:12]  [x] Current egg hatches in 1.38 km
