### ISSUE TITLE
Need a complete documentation of the config and task system

### ISSUE THREAD

**Issue by Yutsa** [PokemonGoF/PokemonGo-Bot#2346]
I think the [actual documentation](https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files) is not exhaustive enough. 

For instance what does `FollowSpiral` do exactly ? Can we use additional configuration to this task ?

It'd be great if every task was explained in depth with all its possible arguments and what it exactly does. As well as the other configuration parameters.

**Comment by MZorzy** [comment]
"dev" branch can't be "in depth with all its possible arguments" dut to frequently changes.

**Comment by maestroi** [comment]
@MZorzy is right
