### ISSUE TITLE
Bot's New Update - BitDefender Total Security - Virus Alert 

### ISSUE THREAD

**Issue by OneGoodMan** [PokemonGoF/PokemonGo-Bot#2351]
After new update, Bitdefender has removed bot's exe file.

It worked for 2 hours; but now **it has been blocked in terms of firewall attack.**

**Comment by gpires** [comment]
False Positive, Disable Firewall or apply an exception.

**Comment by CapCap** [comment]
@OneGoodMan Where did you find an exe file? What was the path to it? What did it say the virus was?

**Comment by justinbeatz** [comment]
bot.exe? this is python code, it doesn't have binary files.
