### ISSUE TITLE
[dev branch] Doesn't notify when bag is full

### ISSUE THREAD

**Issue by pierrecholhot** [PokemonGoF/PokemonGo-Bot#2352]
### Expected Behavior

Notify that bag is full

### Actual Behavior

Infinite loop

### Steps to Reproduce

```
"tasks": [{
  "type": "HandleSoftBan"
}, {
  "type": "CollectLevelUpReward"
}, {
  "type": "IncubateEggs",
  "config": {
    "longer_eggs_first": true
  }
}, {
  "type": "TransferPokemon"
}, {
  "type": "EvolveAll",
  "config": {
    "evolve_all": "NONE",
    "evolve_cp_min": 300,
    "evolve_speed": 20,
    "use_lucky_egg": false
  }
}, {
  "type": "RecycleItems",
  "config": {
    "item_filter": {
      "Pokeball": {
        "keep": 100
      },
      "Potion": {
        "keep": 10
      },
      "Super Potion": {
        "keep": 10
      },
      "Hyper Potion": {
        "keep": 10
      },
      "Revive": {
        "keep": 20
      },
      "Razz Berry": {
        "keep": 100
      }
    }
  }
}, {
  "type": "CatchVisiblePokemon"
}, {
  "type": "CatchLuredPokemon"
}, {
  "type": "FollowSpiral",
  "config": {
    "diameter": 4,
    "step_size": 70
  }
}],
"map_object_cache_time": 5,
"forts": {
  "avoid_circles": true,
  "max_circle_size": 50
},
"websocket_server": false,
"walk": 10.12,
"action_wait_min": 1,
"action_wait_max": 4,
"debug": false,
"test": false,
"health_record": true,
"location_cache": true,
"distance_unit": "km",
"reconnecting_timeout": 15,
"evolve_captured": "NONE",
"catch_randomize_reticle_factor": 1.0,
"catch_randomize_spin_factor": 1.0,
"catch": {
  "any": {
    "catch_above_cp": 0,
    "catch_above_iv": 0,
    "logic": "or"
  }
}

```

### Log

> [16:03:42] Something rustles nearby!
> [16:03:48] Walking from (XX, YY) to [XX, YY] 0.00km
> [16:03:49] Something rustles nearby!
> [16:03:55] Walking from (XX, YY) to [XX, YY] 0.07km
> [16:03:57] Something rustles nearby!
> [16:04:05] Something rustles nearby!
> [16:04:13] Something rustles nearby!
> [16:04:21] Something rustles nearby!
> [16:04:28] Walking from (XX, YY) to [XX, YY] 0.06km
> [16:04:36] Something rustles nearby!
> [16:04:43] Something rustles nearby!
> [16:04:50] Something rustles nearby!
> [16:04:56] Walking from (XX, YY) to [XX, YY] 0.07km
> [16:04:59] Something rustles nearby!
> [16:05:07] Something rustles nearby!
> [16:05:15] Something rustles nearby!

### Other Information

OS: (OS X El Capitan)
Git Commit: (5927c3b)
Python Version: (Python 2.7.10)

**Comment by Philipp59** [comment]
did you mean just the missing log ?
Or the missing release cycle ?
Because you have no release logic in your config

**Comment by pierrecholhot** [comment]
It's just missing the log, I haven't configured (or tested using) the release config.

**Comment by Slayslot** [comment]
I can confirm that the log is missing. I have a release config and still didn't get notified.
