### ISSUE TITLE
[dev] finds/catches far less pokemon then [master]

### ISSUE THREAD

**Issue by kratzert** [PokemonGoF/PokemonGo-Bot#2353]
### Expected Behavior
To have approx. the same Pokemon/hour catch rate

### Actual Behaviour
I did some tests during the last two days. E.g. [dev]-Bot was running for 3 hours - found approx. 30 Pokemon. [master] is starting from the same position and walking around in the same part of the city and has nearly 1 Pokemon/minute. 

### Steps to Reproduce
For me it's just starting [master] or [dev] without any special changes.

### Other Information
Sometimes the [dev]-bot is walking past ~5 Pokestops and isn't finding any Pokemon. [master] is nearly constantly finding Pokemon between any Pokestop. Don't know where to search actually. Should be some problem with checking for Pokemon in each cell?
Anybody with same observations?

**Comment by urbels** [comment]
Depends on dev version as I tested. Sometimes it`s good, sometimes bad even with the same config.

**Comment by fenrirs** [comment]
same here.

**Comment by kratzert** [comment]
would love to help. maybe any dev can point to parts of the code to look at. Would be also good if other could do some tests like:

running [master] for 30min/60min starting from location X.
then write down pokemon found/time, afterwards
running [dev] from 30min/60min starting from same location X.
and write down the same statistic pokemon found/time

Important: I think it's important to start both runs immediately after each other, as time of the day seems to influence the spawn rate drastically.

**Comment by GithubSTC** [comment]
Also experience this problem. However [master] is not testable for me anymore due to KeyError: returns #1490 problem being unfixed (work around: use [dev] instead).

**Comment by kratzert** [comment]
seems #1741 is about the same. I still can run [master] and [dev] but seems like [master] also has a low catch/encounter rate. Don't know what changed. in #1741 they say Necrobot is still working well. But would prefer PokemonGo-Bot as everything is in Python.. No dev has an idea where to look at?

**Comment by iruy** [comment]
I don't know if this is the reason, but in master, the 'catch pokemon' part is in [`pokemongo_bot/__init__.py`](https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/__init__.py), while in dev is in [`pokemongo_bot/cell_workers/catch_visible_pokemon.py`](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/catch_visible_pokemon.py). And, as you can see, master loops on all catchable pokemon trying to catch them (ln 63 or ln 76), while dev only tries to catch the first in array (ln 24 or ln 32)
