### ISSUE TITLE
[Improvement request] Show fort name instead of ID for lured pokemon

### ISSUE THREAD

**Issue by xorinzor** [PokemonGoF/PokemonGo-Bot#2362]
The `MoveToFort` task already uses the fort's name instead of ID in the console output

Lured pokemon however still show `Lured pokemon at fort <id>` in the console output

### Other Information
OS: Win10 x64
Git Commit: 494bc055543c3cb674cca781ec545311d3c9bad1
Python Version: 2.7.12

**Comment by leadboots5** [comment]
Already put this in yesterday. You're just on an older version.
https://github.com/PokemonGoF/PokemonGo-Bot/pull/2249

**Comment by xorinzor** [comment]
@leadboots5 hmm.. weird that I missed that :/ I did look for existing tickets / Pull Requests.

**Comment by leadboots5** [comment]
@xorinzor I like looking at the 'Pulse' tab :)

**Comment by xorinzor** [comment]
@leadboots5 thats a good one! ill keep that in mind
