### ISSUE TITLE
WebSocket only for one bot

### ISSUE THREAD

**Issue by alxnegrila** [PokemonGoF/PokemonGo-Bot#2365]
From what configs contain, only one bot can have WSS enabled.

Support for multiple bots should be added. For example:
One standalone WSS listener and all bots use(send and receive) the same listener.

**Comment by Marco208** [comment]
U can use python -m SimpleHTTPServer 8000, python -m SimpleHTTPServer 8001 etc. or setup a nginx/apache server with symlinks to webfolders
