### ISSUE TITLE
Dev Branch, Requirements error - pgoapi

### ISSUE THREAD

**Issue by demogorgonz** [PokemonGoF/PokemonGo-Bot#2366]
./install.sh 
Setting up Python virtualenv...
New python executable in /home/git/PokemonGo-Bot/bin/python
Installing setuptools, pip, wheel...done.
Python virtualenv setup successfully.
Installing pip requirements...
Collecting numpy==1.11.0 (from -r requirements.txt (line 1))
  Downloading numpy-1.11.0.tar.gz (4.2MB)
    100% |████████████████████████████████| 4.2MB 19kB/s 
Collecting networkx==1.11 (from -r requirements.txt (line 2))
  Downloading networkx-1.11-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 45kB/s 
Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi (from -r requirements.txt (line 3))
  Cloning https://github.com/tejado/pgoapi.git (to 81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b) to ./src/pgoapi
  **Could not find a tag or branch '81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b', assuming commit.**

Any solution/fix for this :) ?

**Comment by JonathanRosado** [comment]
Same issue

**Comment by reddivision** [comment]
This isn't an error, it's saying that there's no tag/branch with that hash, so it's assuming that hash refers to a commit, which it does. PGOAPI does not coordinate their tagging with us and we wouldn't expect them to.

**Comment by lindakun** [comment]
hey,has your question being resolved? i have the same problem with u
