### ISSUE TITLE
[Suggestion] Release lower level Pokemon of already caught Pokemon

### ISSUE THREAD

**Issue by ckrmml** [PokemonGoF/PokemonGo-Bot#237]
### Expected Behavior
Running the bot with parameter -c 150, it captures a Zubat with CP 160. I already have one with CP 170. Bot exchanges the Zubat with CP 160 even though i run it with parameter -c 150. 

### Actual Behavior
The bot keeps all Pokemon above CP 150, so many of them double or triple

### Steps to Reproduce
Just run the bot

**Comment by douglascamata** [comment]
Being implemented right now at https://github.com/PokemonGoF/PokemonGo-Bot/pull/274. Because this is a duplicate I'll close it.
