### ISSUE TITLE
Evolve_all issues on both master + dev

### ISSUE THREAD

**Issue by surewhynotmon** [PokemonGoF/PokemonGo-Bot#2371]
### Expected Behavior
evolve_all: all should evolve all pokemons.

### Actual Behavior
On an earlier version of dev at commit 7b3f70f4e8e9a58d90d8367e4a75348503e98597
I added some log output, I have about 150 pokemons to evolve. But the api stopped working after 52 evolutions with evolve_speed set to 25. Double checked log output, it is due to the evolve api call not working. 

On the very latest edge version, commit 5927c3b8a900ff79ce72fb8447c6c75dbb8ea858
The evolve_all task does not work at all. 
It doesn't even reach the evolve api call, but evolve_list will not find any evolvable pokemons at all.

### Steps to Reproduce
Set evolve_all to "all"

### Other Information
OS: Ubuntu
Git Commit:Mentioned above
Python Version: Python 2.7.11

**Comment by JSchwerberg** [comment]
This is fixed in the latest commit to dev; PR #2305 Commit 550b2c3c357ce2f40aade8e63c3efda9beae6ab7

**Comment by surewhynotmon** [comment]
@JSchwerberg amazing. will try it

**Comment by TheGoldenXY** [comment]
Fixed in latest `dev` branch.

/closed
