### ISSUE TITLE
evolve_speed flag not applied when some pokemons fail to evolve

### ISSUE THREAD

**Issue by surewhynotmon** [PokemonGoF/PokemonGo-Bot#2377]
### Expected Behavior
Evolve every 25 seconds

### Actual Behavior

Evolved 52 pokemons in 3 min...that is 3.5 seconds evolve speed. Either it couldn't get self.bot.config.evolve_speed due to the schema change, and applied 3.7 second, or it is because of the 0.7 sleep on api fail.

I feel like the default fail wait needs to be longer. Current version sleep(0.7) when evolve API fails...so if evolve API fails sometimes, it will have really fast evolution speed. I don't think we should ever wait only 0.7 seconds on a for loop to hit server, in any case.

[13:16:46]  Ran for 0:03:49
[13:16:46]  Total XP Earned: 61000  Average: 957468.37/h
[13:16:46]  Travelled 0.00km
[13:16:46]  Visited 0 stops
[13:16:46]  Encountered 0 pokemon, 0 caught, 0 released, 52 evolved, 9 never seen before

### Steps to Reproduce
evolve: "all"

### Other Information
OS: Ubuntu
Git Commit: 7b3f70f
Python Version: 2.7.11

**Comment by JSchwerberg** [comment]
Default evolve_speed in the evolve_all worker is currently set to 3.7.  What is your evolve_speed set to in your config? 

```
class EvolveAll(BaseTask):
    def initialize(self):
        self.evolve_all = self.config.get('evolve_all', [])
        self.evolve_speed = self.config.get('evolve_speed', 3.7)
        self.evolve_cp_min = self.config.get('evolve_cp_min', 300)
        self.use_lucky_egg = self.config.get('use_lucky_egg', False)
        self._validate_config()
```

**Comment by surewhynotmon** [comment]
I set it to 20, copied from example.

**Comment by vicch** [comment]
A PR for this problem https://github.com/PokemonGoF/PokemonGo-Bot/pull/2239
