### ISSUE TITLE
KeyError: 'player_data'

### ISSUE THREAD

**Issue by philbritton** [PokemonGoF/PokemonGo-Bot#238]
C:\Development\PokemonGo-Bot [dev ↑]> python2 .\pokecli.py
[x] PokemonGO Bot v1.0
[x] Configuration initialized

[x] Address found: Rochester New York
[x] Position in-game set as: (43.16103, -77.6109219, 0.0)

Traceback (most recent call last):
  File ".\pokecli.py", line 107, in <module>
    main()
  File ".\pokecli.py", line 99, in main
    bot.start()
  File "C:\Development\PokemonGo-Bot\pokemongo_bot\__init__.py", line 26, in start
    self._setup_api()
  File "C:\Development\PokemonGo-Bot\pokemongo_bot\__init__.py", line 160, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'
C:\Development\PokemonGo-Bot [dev ↑]>

**Comment by ckrmml** [comment]
check issue [#226](https://github.com/PokemonGoF/PokemonGo-Bot/issues/226) 
>> I just redownloaded/cloned the project, followed the wikilink by @eggins https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation and it worked

**Comment by harsh1412** [comment]
@philbritton Download the GIT from here
https://git-scm.com/download/win 
Then run requirements.
You will be fine.

**Comment by philbritton** [comment]
I ended up changing line 160 to profile and a few other things were parsing wrong, seems to be right in master wrong in dev.

**Comment by CtrlAltDefeat94** [comment]
@philbritton i take it you're going to commit that?
