### ISSUE TITLE
Too much transferring logs every tick

### ISSUE THREAD

**Issue by surewhynotmon** [PokemonGoF/PokemonGo-Bot#2382]
### Expected Behavior
Transfer and keep log only shows up when transferring.
When 0 transfer and 0 evolution happened, probably no point to go over the rules at every tick.
At least it should only happen once at the start.

### Actual Behavior
[14:33:02]  Keep 2 best Pinsir, based on iv
[14:33:02]  Pinsir [CP 1185] [Potential 0.89]
[14:33:02]  Pinsir [CP 92] [Potential 0.91]
[14:33:02]  Transferring 0 Pinsir
[14:35:02]  0 pokemon transferred total. 0 evolutions ready (based on pokemons additional to the ones kept with cp/iv criteria)

### Steps to Reproduce
Run the latest dev

### Other Information
OS: Ubuntu
Git Commit: d5622898c0817c7f4913e1cec6076a687e4acf16
Python Version:2.7.11

**Comment by relomy** [comment]
This was recently reverted I believe. Not for this purpose, though.

**Comment by JSchwerberg** [comment]
Update.  This fix has been reverted.

**Comment by surewhynotmon** [comment]
@JSchwerberg Currently it output the entire list of pokemons every transfer/keep operation it seems.

**Comment by JSchwerberg** [comment]
@surewhynotmon Not as of commit 9b1fdefb03d4ab0752cc2d626a4a52260ee8d4f0

**Comment by surewhynotmon** [comment]
@JSchwerberg confirmed fixed.

**Comment by surewhynotmon** [comment]
@JSchwerberg that commit also randomly released pokemons regardless of rule input....sadness.
