### ISSUE TITLE
Unable to Configure "RecycleItems" task.

### ISSUE THREAD

**Issue by jpcguy89** [PokemonGoF/PokemonGo-Bot#2383]
Hi there,

I'm having trouble getting the configuration (specifically, "item_filter") for RecycleItems correct. 

Here's how I'm currently attempting to set it up in the config.json file:

`"tasks": {
   ...
   {
       "type":"RecycleItems",
       "config":{
                    "item_filter": "101,102,103,104"
        }
    },
`

Here's the traceback (jic, I'm sure I'm just getting the syntax wrong):

`Traceback (most recent call last):`
  `File "pokecli.py", line 442, in <module>`
   ` main()`
  `File "pokecli.py", line 64, in main`
    `tree = TreeConfigBuilder(bot, config.raw_tasks).build()`
  `File "/Users/joecavallaro/PokemonGo-Bot/pokemongo_bot/tree_config_builder.py", line 30, in build`
  `  instance = worker(self.bot, task_config)`
  `File "/Users/joecavallaro/PokemonGo-Bot/pokemongo_bot/cell_workers/base_task.py", line 6, in __init__`
  `  self.initialize()`
  `File "/Users/joecavallaro/PokemonGo-Bot/pokemongo_bot/cell_workers/recycle_items.py", line 10, in initialize`
    `self._validate_item_filter()`
  `File "/Users/joecavallaro/PokemonGo-Bot/pokemongo_bot/cell_workers/recycle_items.py", line 14, in _validate_item_filter`
`    for config_item_name, bag_count in self.item_filter.iteritems():`
`AttributeError: 'unicode' object has no attribute 'iterates'`

**Comment by theVDude** [comment]
{
      "type": "RecycleItems",
      "config": {
        "item_filter": {
          "1": { "keep" : 20 },
          "2": { "keep" : 30 },
          "3": { "keep" : 60 },
          "101": { "keep" : 0 },
          "102": { "keep" : 0 },
          "103": { "keep" : 15 },
          "104": { "keep" : 25 },
          "201": { "keep" : 10 },
          "202": { "keep" : 15 },
          "701": { "keep" : 50 },
          "801": { "keep" : 50 }
        }
      }
    },

This is what I have in mine and it works, maybe check against the most current config.json.example file when you pull?

**Comment by jpcguy89** [comment]
Thanks.
