### ISSUE TITLE
[FEATURE REQUEST] Improve usage of lucky egg

### ISSUE THREAD

**Issue by skartoffel** [PokemonGoF/PokemonGo-Bot#2385]
### Expected Behavior

The best behaviour would be: If an evolution family has more than one evolution, evolve the basic evolution first (or since it doesn't matter, always evolve the basic evolution first). For example if you have 20 Pidgeys and 5 Pidgeottos, first evolve all 20 Pidgeys before trying to evolve a Pidgeotto. This will lead to a great XP/candy ratio.

Maybe some options can be implemented:
- strongest_first
- basic_evolution_first
- highest_evolution_first

### Actual Behavior

Last time I checked the evolution priority seemed to be "strongest first". That's why my Pidgeottos where evolved before the Pidgeys, which was a great waste of candy.

**Comment by coderplay** [comment]
-1 on the idea. 
If basic_evolution_first, then the upper evolution never happen only if there is no basic pokemon in the family.  Basic evolution's candy requirement is easier to reach. The bot will always try to evolve the basic.

**Comment by skartoffel** [comment]
@coderplay Well yes, and in combination with a lucky egg that is exactly the behaviour you (or at least I) want. Evolve as many pokemon as possible with as little candy as possible. I've set my bot to keep 20 Pidgeys, Weedles, Caterpies and Rattatas because these are the mons where you usually have the most candy and the first evolution is pretty cheap.

If "use_lucky_egg" is set to false or if you are short on candy, a different evolve strategy should be used. Something like "if it's at least A-tier evolve the high IV/CP second evolution first, else evolve the basic evolution first".

**Comment by coderplay** [comment]
Hey @skartoffel 

I actually implemented one at my branch https://github.com/coderplay/PokemonGo-Bot/commit/837f23d4d469c047b9169465772fdd29653b82b0

if user use `first_evolve_by` = cp,  then it's your highest_evolution_first
if user use `first_evolve_by` = iv,   then it's your strongest_first (strongest is with best potential in your meaning, right?)

**Comment by skartoffel** [comment]
Hey @coderplay 

Well usually yes, but not in this case. This is NOT about evolving good pokemon that you want to keep and/or actively use and level up.

This is about "fooder" pokemon, purely meant for gaining XP.

A short explanation: My strategy for making a good amount of XP is the following: 

- Catch a lot of "useless" mons (Pidgeys, Zubats, Rattatas, Weedles, Caterpies, Drowzees, whatever).
- If you have enough "useless" mons and enough candy to evolve them all, use a lucky egg
- Evolve all "useless" mons and gain about 90k XP in 30 minutes

However, this strategy only works if you use your candy for the mons with the least amount of needed candy. The bot does something like the opposite. He will waste all your candy on your Pidgeottos (since they are stronger) and then when it should evolve the remaining Pidgeys, there is no (or not much) candy left.
