### ISSUE TITLE
[FEATURE REQUEST] Hashed passwords?

### ISSUE THREAD

**Issue by gartia** [PokemonGoF/PokemonGo-Bot#2387]
I don't like storing my passwords in open texts on my linux box because i am not the only person with access to them. Any possible way to hash the passwords

**Comment by JSchwerberg** [comment]
Hashes are, by nature, not reversible.  Since there would be no way to reverse your password from the hash, I'd say this is unlikely.

Use a Google App Password, rather than your actual Google password.  https://support.google.com/accounts/answer/185833?hl=en

**Comment by MZorzy** [comment]
epic.
shared linux box, maybe root ?

**Comment by reddivision** [comment]
Along with @JSchwerberg's suggestion, you can always leave your credentials out of the config, the bot will prompt you for them on startup.
