### ISSUE TITLE
release not working once the pokemon are renamed

### ISSUE THREAD

**Issue by kalyon** [PokemonGoF/PokemonGo-Bot#2394]
### Expected Behavior

release pokemon as configure in the release part 
"release": {
      "any": {"keep_best_cp": 2, "keep_best_iv": 2},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },

### Actual Behavior
nothing release

### Steps to Reproduce
rename the pokemon with

  "type": "NicknamePokemon",
        "config": {
		"nickname_template": "{iv_pct}_{iv_ads}"
	}

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by reddivision** [comment]
This seems to be a popular notion, but it's incorrect. Pokemon are transferred based on their id, not their nickname. The only code in our bot that even looks at the `nickname` field of a pokemon is the nickname code itself. 

![sample](https://cloud.githubusercontent.com/assets/8896778/17351181/45e7612c-58e1-11e6-838b-ff851beb0cf1.png)

**Comment by reddivision** [comment]
Closing this for now. If you have a log or screencap indicating this functionality is still broken on current dev, we can re-open.
