### ISSUE TITLE
Use Incivator

### ISSUE THREAD

**Issue by Evan666** [PokemonGoF/PokemonGo-Bot#2397]
### Expected Behavior
Im new on this but I try to find in forum the answer but dont see it, its posible use incuvator ?
Thx guys

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by mjmadsen** [comment]
If you're using the dev branch you can use the following:

    "tasks": [
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
    ]

I don't think it is in the master branch.

You can switch with the following:
    $ git checkout dev
    $ git pull
    $ pip install --upgrade -r requirements.txt

You'll need to setup the a new configuration using ./configs/config.json.example as a template. Egg Incubation is on by default.

**Comment by reddivision** [comment]
@mjmadsen's answer is excellent. closing this. if you have further questions, please check out the wiki or the #help channel in our Slack.
