### ISSUE TITLE
Not an issue, sorry for that. just a wrapper for us OSX users

### ISSUE THREAD

**Issue by ckrmml** [PokemonGoF/PokemonGo-Bot#2398]
If somebody could add this to the wiki, that would be great

currently it will
- install master or dev branch
- update bot and requirements
- init/update submodule
- install/init Python virtualenv
- install requirements
- start as many bots as you like (in new Terminal window)

https://github.com/ckrmml/PokemonGo-Bot_wrapper_osx

**Comment by Corecrafts** [comment]
@ckrmml no configs to change?

**Comment by ckrmml** [comment]
at the moment you have to edit the config yourself, haven't had the motivation to do this. but it will come later on

**Comment by Corecrafts** [comment]
@ckrmml do i set the downloaded folder as my default in terminal and just start it up? i cant seem to find any config in that.

**Comment by ckrmml** [comment]
clone or download the files, unzip if you did download from the site. 
Open up Terminal and cd to the folder, something like 
```
/Users/YOUR-NAME/PokemonGo-Bot_wrapper_osx
```
or 
```
/Users/YOUR-NAME/Downloads/PokemonGo-Bot_wrapper_osx
```
 enter 
```
chmod +x start.sh
```
to make executable and enter
```
./start.sh
```
to start the script
