### ISSUE TITLE
[request/help] Release Logic

### ISSUE THREAD

**Issue by mjmadsen** [PokemonGoF/PokemonGo-Bot#2399]
"release": {
      "Fearow": {"release_below_cp": 1200, "release_below_iv": 0.1, "keep_best_cp": 2, "logic": "or"}
    }

The above will always keep the top two CP but keep everything beyond 1200 CP and .1 IV.

If instead you want to ONLY keep the top two CP for those beyond 1200 CP and .1 IV, there is currently (as far as I know) no means to do this. Something like the following:
 "Fearow": {{"release_below_cp": 1200, "logic": "or", "release_below_iv": 0.1}, "logic": "and", "keep_best_cp": 2}

Thoughts on how to do this with the current setup?

**Comment by RedViper9** [comment]
I'm somewhat confused by the end of your question.
From what I understand you want:
Release CP < 1200 AND Release IV < 0.1 AND Keep best CP = 2
Does this not work?
`{"release_below_cp": 1200, "release_below_iv": 0.1, "keep_best_cp": 2, "logic": "and"}`

**Comment by reddivision** [comment]
@RedViper9 no, that won't work as you're expecting. `logic` only impacts how `release_below_cp` and `release_below_iv` get calculated. 

@mjmadsen this is a really odd use case. Unless there's some reason why you _need_ 0 pokemon of a certain type _unless_ they are over 1200, then just using `"keep_best_cp": 2` alone should be sufficient for you, as you will always have the best two of a given type, whether they're over or under 1200.

**Comment by lhung** [comment]
I think this is a valid use case. Given the default box size is 250 and there are 145 catchable pokemons, it does not take long for `"keep_best_cp": 2, "keep_best_iv":1` to fill up the box. It would be great `release_below_cp` and `release_below_iv` can kick in and do some gate keeping job.

**Comment by mjmadsen** [comment]
@lhung exactly. Not to mention the hordes of pidgeys and the like I save for lucky egg evolves.
