### ISSUE TITLE
Missing pgoapi

### ISSUE THREAD

**Issue by fvorez** [PokemonGoF/PokemonGo-Bot#240]
Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pokemongo_bot import PokemonGoBot
  File "C:\Users\Orez\Desktop\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line
 10, in <module>
    from pgoapi import PGoApi
ImportError: No module named pgoapi

**Comment by dominikue** [comment]
> To install the pgoapi use pip install -e git://github.com/tejado/pgoapi.git#egg=pgoapi
Also make sure you add git to the PATH if you use windows.

**Comment by Klohto** [comment]
pip install -r ./requirements.txt

**Comment by fvorez** [comment]
Figured i was missing a req, but now

  Error [Error 2] The system cannot find the file specified while executing comm
and git clone -q git://github.com/tejado/pgoapi.git C:\Users\Orez\Desktop\Pokemo
nGo-Bot-dev\src\pgoapi
Cannot find command 'git'

**Comment by Klohto** [comment]
Don't have git installed in your console

**Comment by dominikue** [comment]
> Also make sure you add git to the PATH if you use windows.
Are you using windows? 
http://stackoverflow.com/questions/11000869/command-line-git-on-windows

**Comment by fvorez** [comment]
Thanks m8s, sorry about my noobness

**Comment by dominikue** [comment]
Wrote the same question 20 min ago.. :D If it doesn't work try to open the cmd in your git directory "C:\Users\<user>\AppData\Local\GitHub\PortableGit_<guid>\cmd" - worked for me.

**Comment by aTadTasty** [comment]
for mac users, please use the code `pip install -r ./requirements.txt --ignore-installed six`

**Comment by douglascamata** [comment]
Mac users should use `virtualenv`, it's the proper solution for clean local python environments.
