### ISSUE TITLE
404 errors socket.io

### ISSUE THREAD

**Issue by WinsleyJ** [PokemonGoF/PokemonGo-Bot#2403]
### Expected Behavior

No socket errors & working web log

### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/20803684/17347432/2b59b27c-5910-11e6-9ac3-512a72ceeb8a.png)

```
127.0.0.1 - - [03/Aug/2016 00:21:21] "GET /catchable-XXXX@gmail.com.json?v=1470176481883 HTTP/1.1" 200 -
127.0.0.1 - - [03/Aug/2016 00:21:22] code 404, message File not found
127.0.0.1 - - [03/Aug/2016 00:21:22] "GET /socket.io/?EIO=3&transport=polling&t=LPDMDKz HTTP/1.1" 404 -
127.0.0.1 - - [03/Aug/2016 00:21:22] "GET /location-XXXX@gmail.com.json?v=1470176482622 HTTP/1.1" 200 -
127.0.0.1 - - [03/Aug/2016 00:21:22] "GET /catchable-XXXX@gmail.com.json?v=1470176482622 HTTP/1.1" 200 -
```

Log stops after trainer loaded

```
Logs
00:23
Loading Data..
00:23
Data Loaded!
00:23
[XXXX@gmail.com] Ekans appeared
00:23
Trainer loaded: XXXX@gmail.com
```

### Steps to Reproduce

$ python -m SimpleHTTPServer 8000
$ python pokecli.py

### Other Information
OS: OSX Yosemite 10.10.5
Git Commit: bdf2e7d9cc0b2fa5fb04bb9dc4f9f09f967cd9ea
Python Version: 2.7.12

**Comment by Moonlight-Angel** [comment]
Currently, I'm not sure if updating the web view via socket is available and working.
The web view probably added socket updating but the bot itself doesn't seem to be completely ready for this.
Also, this error doesn't break the web view, it's just telling you it cannot establish a socket connection to the bot but it's still updating the view through the "old" way (and probably the way things work currently).

**Comment by niranjanreddy891** [comment]
@WinsleyJ, try this `python -m http.server`
