### ISSUE TITLE
Only lets me login 1 time per account?

### ISSUE THREAD

**Issue by Rodwiththegreatbod** [PokemonGoF/PokemonGo-Bot#2405]
### Expected Behavior
To be able to start the Bot in terminal, then stop it, then be able to start it again whenever I choose.

### Actual Behavior
I can only run the bot one time per account. After that, I have to change my account information in the config file for it to work.

### Steps to Reproduce
Just running the bot

### Other Information

This is the error that shows in terminal
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 206, in main
    bot.start()
  File "/Users/userstuff/PokemonGo-Bot/pokemongo_bot/__init__.py", line 31, in start
    self._setup_api()
  File "/Users/userstuff/PokemonGo-Bot/pokemongo_bot/__init__.py", line 159, in _setup_api
    balls_stock = self.pokeball_inventory()
  File "/Users/userstuff/PokemonGo-Bot/pokemongo_bot/__init__.py", line 234, in pokeball_inventory
    inventory_dict = inventory_req['responses']['GET_INVENTORY'][
KeyError: 'GET_INVENTORY'
OS: 
Git Commit: commit 4182e93f9bfbe471d07b74e95c55cdfbacda127b
Python Version: Python 2.7.10

**Comment by DayBr3ak** [comment]
your error has nothing to do with what you are describing

**Comment by Rodwiththegreatbod** [comment]
Could you please explain how to fix both issues? The error I show only
appears when I use Control C in terminal to stop the bot, then try to
restart the bot with the same account logged in. For example, if I tried to
use the bot with bob@gmail.com, it would work fine for the first use. But
if I stopped the bot in terminal, then tried to start it again (still using
the account bob@gmail.com) the error I pasted in my issue would appear.
However, the error disappears after I try using a new account with the bot.
Any help would be greatly appreciated.

Cheers

**Comment by Avaryan** [comment]
I get that Get_Inventory error often, usually first time starting the bot. I just attempt to start it again immediately afterwards and it works.
