### ISSUE TITLE
Evolve_captured is not working properly

### ISSUE THREAD

**Issue by RomanFausek** [PokemonGoF/PokemonGo-Bot#2408]
### Expected Behavior
`"evolve_captured": "Weedle"` should evolve ONLY captured weedles

### Actual Behavior
Evolves all pokemons even with parameter NONE

### Steps to Reproduce
`"evolve_captured": "Weedle"`
`"evolve_captured": "NONE"`

only deleting this variable helps

### Other Information
OS: W10
Git Commit: 4182e93f9bfbe471d07b74e95c55cdfbacda127b
Python Version: Python 2.7.10

**Comment by randypfohl** [comment]
I'm also noting this issue.

**Comment by RomanFausek** [comment]
Wierd. What can I do wrong? My friend has the same problems as me (we installed together).

**Comment by RomanFausek** [comment]
Didn't help. I really don't know what the fuck is that. But thanks anyway
