### ISSUE TITLE
[Bug] -c doesn't exchange pokemons

### ISSUE THREAD

**Issue by dominikue** [PokemonGoF/PokemonGo-Bot#241]
### Expected Behavior
The command--cp 200 exchanging pokemons under 200 for candy.

### Actual Behavior
The pokemon is not exchanging for candy. You can see it in the cmd it but its still in the inventory - also the message  _Your inventory is full!_  is wrong.

```
[#] Something rustles nearby!
[#] A Wild Weedle appeared! [CP94]
[x] Using Pokeball...
[x] Captured Weedle! [CP94] - exchanging for candy
[###] Your inventory is full! Please manually delete some items.
[#] A Wild Eevee appeared! [CP103]
[x] Using Pokeball...
[x] Captured Eevee! [CP103] - exchanging for candy
[###] Your inventory is full! Please manually delete some items.
### Steps to Reproduce
```

### Other Information
OS: 
Git Commit: dev 19

**Comment by dominikue** [comment]
duplicate again.. #237

**Comment by CtrlAltDefeat94** [comment]
#127 #142 #15 
i just wish people would check if something is reported already..

**Comment by douglascamata** [comment]
This is fixed in master already. Thanks for the report.
