### ISSUE TITLE
[Feature Request] Use set amount of pokeballs

### ISSUE THREAD

**Issue by pickett2k** [PokemonGoF/PokemonGo-Bot#2412]
Would be good if we could define how many attempts the bot will make to catch the Pokemon in the config file, say 2 poke balls instead of until it runs or gets caught, even better if we could define which Pokemon individually to try harder on too

**Comment by th4tc0d3r** [comment]
or something like how NecroBot is setup, with thresholds for which ball to use.


"UseGreatBallAboveCp": 100000,
"UseUltraBallAboveCp": 100000,
"UseMasterBallAboveCp": 100000,
"UseGreatBallAboveIv": 100000,
"UseUltraBallAboveIv": 100000,
"UseGreatBallBelowCatchProbability": 0.30,
"UseUltraBallBelowCatchProbability": 0.15,
"UseMasterBallBelowCatchProbability": 0.01,
