### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by KingArsalan14** [PokemonGoF/PokemonGo-Bot#2417]
Hey i couldn't find anything on my problem so hopefully someone can help :)

When i try to run the bot this is what comes up

Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 197, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Any help??

**Comment by RedViper9** [comment]
Looks like your config file may have a syntax error.
Try this: https://github.com/PokemonGoF/PokemonGo-Bot/wiki/No-JSON-object-could-be-decoded-or-decoder.py-error

**Comment by lhung** [comment]
Check your config.json on http://jsonlint.com/ for errors.

**Comment by KingArsalan14** [comment]
When i check my config.json all it does is separate the _____ part of my username from the @gmail.com in the format of _____@gmail.com ---> ____ @gmail.com

**Comment by KingArsalan14** [comment]
so i changed that and it says the same thing

**Comment by RedViper9** [comment]
For the sake of argument, post your config please.

**Comment by KingArsalan14** [comment]
okay!

**Comment by KingArsalan14** [comment]
{
    "auth_service": "google",
    "username": “arxxxxx@gmail.com",
    "password": “_______”,
    "location": “San Francisco, California“,
    "gmapkey": "______",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104",
    "evolve_all": "NONE"
}

**Comment by RedViper9** [comment]
Your config file seems outdated. Please update the bot and then rewrite your config file to match the current config.json.example

**Comment by KingArsalan14** [comment]
to update the bot do i just repeat the process and change the master to dev?

**Comment by KingArsalan14** [comment]
sorry I'm probably asking the stupidest questions but I'm really clueless as you can see

**Comment by RedViper9** [comment]
To be honest, I haven't run the Master branch at all, so I have no idea if it's working or not. Perhaps someone else can help you fix your installation.

If you want to use the Dev branch:
1. Save your config.json somewhere (like your desktop) so you can easily get your username, pass, API when you reinstall.
2. Delete the whole PokemonGo-Bot folder.
3. Follow Installation instructions, but wherever you see master, use dev.
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation

**Comment by KingArsalan14** [comment]
okay yes i just did, unfortunately i didn't copy the config.json thing and anyways this one from the dev branch has a lot of other things that the one i posted earlier didn't. Just to make sure are all your config.json etc things in a folder called configs. And did you take away the example ending on all of them?

**Comment by RedViper9** [comment]
Yes, your config file should be in the configs folder.

You only need one config.json. The large number of example files shows variations on what is possible. 

To start I would copy config.json.example and rename the copy as config.json. Enter your user info and the bot should work. Then you can read through the Wiki and the other example files to learn how to use the other features.

[Wiki ](https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files)

**Comment by KingArsalan14** [comment]
okay cool, and once again i ran the bot and the problem is still the decoding thing. The website keeps telling me its my username thats the problem, my username i put in is arsxxxxyaxxx3@gmail.com and this is the error they are telling me to fix

Error: Parse error on line 3:
...ogle",	"username": “arsxxxxyaxxxxa3 @gm
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

**Comment by RedViper9** [comment]
Did you forget to close the quotation marks after your username?
Correct syntax for the start of file is:
```
{
    "auth_service": "google",
    "username": "asdfqwoeituvkm@gmail.com",
    "password": "asdoibjcnjxvcoiuyw",
    "location": "Lat, Long",
    "gmapkey": "asdl;fjoixcubioej",
    "tasks": [
                { "type": "HandleSoftBan"
                },
```
You need to have all the parentheses, quotation marks, commas, and spaces  as above. Do not put a space in username@gmail.com.

**Comment by KingArsalan14** [comment]
Yep thats how I've had it the entire time :( I'm so confused

**Comment by KingArsalan14** [comment]
Keeps saying the same thing,  File "pokecli.py", line 446, in <module>
    main()
  File "pokecli.py", line 53, in main
    config = init_config()
  File "pokecli.py", line 131, in init_config
    load.update(json.load(data))
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by KingArsalan14** [comment]
could you send me your file without your information and maybe ill just fill that in? hopefully that might work :(

**Comment by Ledicious** [comment]
It's most likely a problem with the text editor you are using.  I don't know what OS you are on but try saving using Notepad++, TextWrangler, or edit the file via the command line.

**Comment by KingArsalan14** [comment]
BRO I FINALLY FIXED IT I THINK!!! I just rewrote the entire first half of the config file and it worked!

**Comment by KingArsalan14** [comment]
Yea led i think that is what it was !

**Comment by KingArsalan14** [comment]
Thanks for the help you guys i never expected this kind of positive response. Tyvm!

**Comment by Ledicious** [comment]
Good luck and have fun!

**Comment by KingArsalan14** [comment]
Will do ! Thanks ! Any good locations i may not know about ?


________________________________

**Comment by Ledicious** [comment]
Santa Monica Pier is pretty good...
