### ISSUE TITLE
data/last-location-%s.json not  exists

### ISSUE THREAD

**Issue by llwijvbw123** [PokemonGoF/PokemonGo-Bot#2419]
because ./data/ not exists  last-location-%s.json file 

pokemongo_bo/stepper.py 
 124:            if os.path.isfile(user_data_lastlocation):
                        with open(user_data_lastlocation, 'w') as outfile:
                            outfile.truncate()
                            json.dump({'lat': lat, 'lng': lng}, outfile)

so never run

**Comment by reddivision** [comment]
I'm assuming you're running with "location_cache" enabled in your config. please remove that key from your config and try again.
