### ISSUE TITLE
[Feature Request] Run 'EvolvePokemon' When Pokemon Storage Full

### ISSUE THREAD

**Issue by JonnyBoy333** [PokemonGoF/PokemonGo-Bot#2422]
It would be nice if we had the option to run the EvolvePokemon task once the storage has been filled with Pokemon. So in my case as soon as I hit 250 Pokemon it would run EvolvePokemon and all my Pidgey's, Weedles, etc. would evolve and then get transferred according to the release rules. Maybe something in the EvolvePokemon config could be 
"config": {
	            "evolve_all": "none",
	            "logic": "or",
                    "evolve_when_full": true,
                    "evolve_all": "Pidgey, Weedle, Caterpie",
	            "evolve_speed": 20,
	            "use_lucky_egg": true
}

**Comment by lokiiiii** [comment]
+1 would be a really nice option :)

**Comment by Pyrofer** [comment]
Or even a warning/quit before dumping all the unevolved pokemon.
I have thousands of Pidgey candy and never get to do the egg trick because each time It has enough pokemon before I get to trigger the egg and evolve it dumps them all!
So I start again collecting and when I am not watching it dumps them all!

**Comment by JonnyBoy333** [comment]
@Pyrofer How come it's dumping them all for you? Do you have something in the release config that would release all of them? I have it set to keep_best_cp: 60 for all my evolve pokemon and then I just watch the bot and wait for it to reach capacity on pokemon. Then I stop the bot, change the config to use lucky egg and evolve pokemon and run it again. Once it's done evolving I stop it and go back to my regular config. Works but it's a pain when you have 10 bots..
