### ISSUE TITLE
Cannot install requirment.txt

### ISSUE THREAD

**Issue by celus** [PokemonGoF/PokemonGo-Bot#2423]
### Expected Behavior

pip install -r requirements.txt
should install
### Actual Behavior

(PokemonGo-Bot) Celus:PokemonGo-Bot Celus$ pip install -r requirements.txt
-bash: /Volumes/Supply Co./Downloads/untitled folder 4/PokemonGo-Bot/bin/pip: "/Volumes/Supply: bad interpreter: No such file or directory
### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by hklcf** [comment]
https://pip.pypa.io/en/stable/installing/

**Comment by celus** [comment]
My pip is already up to date.
Requirement already up-to-date: pip in /usr/local/lib/python2.7/site-packages

**Comment by hklcf** [comment]
because of "/Volumes/Supply: bad interpreter: No such file or directory"

change your folder name from Supply Co. to Supply-Co.

**Comment by celus** [comment]
Thanks a bunch!
