### ISSUE TITLE
Could not reach PokemonGo-Map Server

### ISSUE THREAD

**Issue by OVO647** [PokemonGoF/PokemonGo-Bot#2429]
How do I get to view the map step by step? I'm new to coding so sorry if this is a simple question. Right now I do the following in terminal.

cd desktop
cd pogo
pip install -r requirements.txt
python pokecli.py

**Comment by lhung** [comment]
map is a submodule of this project. Check this out https://github.com/OpenPoGo/OpenPoGoWeb#installation-and-use.

**Comment by OVO647** [comment]
How exactly do I run both though?

**Comment by OVO647** [comment]
What exactly do I type in terminal so the bot can run and I can see whats happening on the map?

**Comment by timwharton** [comment]
cd web  
python -m SimpleHTTPServer

**Comment by OVO647** [comment]
Do I type that after the bot runs?

**Comment by timwharton** [comment]
Yeah in a separate terminal window but from your pogo folder.

**Comment by OVO647** [comment]
ok thanks

**Comment by OVO647** [comment]
Then how do I view the map?

**Comment by lhung** [comment]
By default, it is at localhost:8000

**Comment by JSchwerberg** [comment]
Guys.  He's not talking about OpenPoGoWeb map.  He's referring to the Pokemon-Go Map Server for commit 21254bc0f21ca7bd7612eab0ac480d080ccea9f9 

It's something completely different.

**Comment by OVO647** [comment]
Exactly thats what I'm talking about JSchwerberg

**Comment by JSchwerberg** [comment]
@OVO647 https://github.com/AHAAAAAAA/PokemonGo-Map will have instructions to set it up -- this is an entirely different server

**Comment by OVO647** [comment]
I dont really understand whats on there.

**Comment by OVO647** [comment]
I get the page on http://localhost:8000 but it is completely white

**Comment by flopk** [comment]
I've tried using both and I get errors from both or a map centred in the middle of France. No data or icons on it. Keep getting errors from Openpogo
127.0.0.1 - - [03/Aug/2016 11:24:02] code 404, message File not found
127.0.0.1 - - [03/Aug/2016 11:24:02] "GET /location-**wrongusername***.json?v=1470219842724 H                                                                      TTP/1.1" 404 -
It would be nice to work it out but it still catches which is the important thing
