### ISSUE TITLE
How to find good GPS coordinates for location

### ISSUE THREAD

**Issue by zchen1018** [PokemonGoF/PokemonGo-Bot#2435]
Not an issue. Just curious how do you guys find the initial coordinates for good spots.

**Comment by leadboots5** [comment]
Either personal experience or using sort of tool(pokevision when it was still up. now alternatives or personal scanner apps) to see where spawns are good.

You can also setup a path that you think is good and then watch it to see during what parts it is catching pokemon and which ones its not and then refine the path. This takes a bit longer, but has garnered good results personally.

There are other options as well. Some people have a place where there are grouped up pokestops all lured and they just plop the bot down and don't have it move.

**Comment by MrCarlosJr** [comment]
google maps
