### ISSUE TITLE
[Feature Request] Evolve All based on IV

### ISSUE THREAD

**Issue by Drambuie** [PokemonGoF/PokemonGo-Bot#2444]
Can;t see anyway of doing this in the current Dev configuration file so sorry if i missed something

At the cmoment the configuration allows for

      {
        "type": "EvolveAll",
        "config": {
          "evolve_all": "all",
          "evolve_cp_min": 300,
          "evolve_speed": 20,
          "use_lucky_egg": true
        }

Which allows you to set a CP minimum, however what I have noted is that it is usually my worst IV pokemon that end up getting eveolved purely because they happen to have a higher CP at at low level

For instance i have 3 charmanders on one of my accounts, highest being a 0.47 lowest besin a 0.27, 

the 0.27 charmander was the pokemon that was evolved,

Could be have some configuration that says use highest IV or even a way of setting a threshhold for IV so that it doesnt evolve below a set value?

just a thought that I personally think would be useful feature

**Comment by 1cu** [comment]
This feature is in dev since eight hours ago :+1: 

Take a look at the PR #2244

**Comment by Drambuie** [comment]
Must have missed this in the patch notes,

Thanks will check it out
