### ISSUE TITLE
Add log summary?

### ISSUE THREAD

**Issue by g2384** [PokemonGoF/PokemonGo-Bot#2449]
### Expected Behavior

I simply use `script file.txt` to record the terminal, and use a Python script to summarize the log. I suppose it can be added in the bot to be an hourly summary or after `^c`. 

        Bellsprout (2): 399 121
        Drowzee (25): 669 649 600 ...
        Jynx (3): 933 550 119
        Psyduck (1): 347
        Venonat (1): 470
        Zubat (8): 342 315 253 ...
    Caught: 40, Visited: 115 [22440 exp]
    Types: 6, Released: 34, net: 8
    ran away (3): Shellder[136], Rattata[141], Drowzee[658]
    Eggs hatched: 2

net = caught - released + eggs hatched.
Only top 3 CP are displayed.
Show what pokemon run away and their CP. (I think this info is quite important)

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by Baanin** [comment]
Could you please share your script ?

**Comment by g2384** [comment]
Code: [log_sum.py](https://gist.github.com/g2384/62a69ef9c72f3a80dc7cf3817f4f3cc5) (messy and inefficient)
Required module: `termcolor`. (you can remove `colored()` function, if you don't want to install `termcolor` module)

One easy way to use this script is to 

1. save the file in the root folder of the bot.
2. before running, type `script file.txt`
3. while running or after running, in another terminal window, type `python log_sum.py` to view the summary
4. after running, type `exit` to stop `script` function
