### ISSUE TITLE
Unable to uninstall six-1.4.1

### ISSUE THREAD

**Issue by rkodali22** [PokemonGoF/PokemonGo-Bot#245]
Obtaining pgoapi from git+git://github.com/tejado/pgoapi.git@1f25e907f3e5f1b603330e71041e1ad7bee7580f#egg=pgoapi
  Skipping because already up-to-date.
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in /Library/Python/2.7/site-packages (from pgoapi)
Collecting protobuf>=3.0.0a3 (from pgoapi)
  Downloading protobuf-3.0.0b4.tar.gz (210kB)
    100% |████████████████████████████████| 215kB 2.0MB/s 
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in /Library/Python/2.7/site-packages (from pgoapi)
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in /Library/Python/2.7/site-packages (from pgoapi)
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in /Library/Python/2.7/site-packages (from pgoapi)
Collecting six>=1.9 (from protobuf>=3.0.0a3->pgoapi)
  Downloading six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf>=3.0.0a3->pgoapi)
Requirement already satisfied (use --upgrade to upgrade): future in /Library/Python/2.7/site-packages (from s2sphere==0.2.4->pgoapi)
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in /Library/Python/2.7/site-packages (from gpsoauth==0.3.0->pgoapi)
Installing collected packages: six, protobuf, pgoapi
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-H12_rn-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

**Comment by aTadTasty** [comment]
for el-capitain users, make sure you add the flag: `--ignore-installed six`

**Comment by Klohto** [comment]
Sudo? 🤔

**Comment by aTadTasty** [comment]
@Klohto with that it just won't work for mac osx 10.11 i tried multiple times. it has to do with the built in 1.4.1... so you have to add `--ignore-installed six` and this will fix the requirements :D

**Comment by douglascamata** [comment]
Consider using `virtualenv`, please. You won't want to mess with your system's Python.

**Comment by rkodali22** [comment]
got this error while using virtualenv:
sudo: unable to execute /path/to/PokemonGo-Bot/venv/bin/pip: No such file or directory

**Comment by WangSiyao** [comment]
Try this.
sudo pip install six  --ignore-installed six
