### ISSUE TITLE
[Feature] Snipe_min

### ISSUE THREAD

**Issue by Lunik** [PokemonGoF/PokemonGo-Bot#2450]
### Expected Behavior
Only snipe pokemon with more than 100 in the `MoveToMapPokemon` config
adding `snipe_min: 100`

### Actual Behavior
Snipe every pokemon

### Steps to Reproduce
````
"config": {
          "address": "http://localhost:5050",
          "max_distance": 500,
          "min_time": 60,
          "prioritize_vips": true,
          "snipe": false,
          "update_map": true,
          "mode": "priority",
          "catch": {
            ...
          }
}
````

### Other Information
OS: Linux
Git Commit: 361c0fa11783085ea201a71a99f6c43859e8c239
Python Version: Python 2.9.7

**Comment by mhdasding** [comment]
just remove the pokemon from the caught list if you don't want them to be sniped?

**Comment by Lunik** [comment]
Hum yes xD That is a stupide question... 
Thanks :)

**Comment by Lunik** [comment]
Yes why not :)
But my point is: If snip option is enable, the bot will snip every pokemon. Could we add some filter.

**Comment by mhdasding** [comment]
it doesn't snipe every pokemon, only those defined in the caught list

**Comment by Lunik** [comment]
Yes, but we could have some pokemon in the caught list, but not snip all of them

**Comment by mhdasding** [comment]
why have them in the caught list if you don't want to snipe them?

**Comment by Lunik** [comment]
To follow them if there is anything to catch

**Comment by mhdasding** [comment]
created #2463

**Comment by Lunik** [comment]
Thanks :)
