### ISSUE TITLE
[Feature Request] Pushover support (push message when pokemon has been caught)

### ISSUE THREAD

**Issue by iamhaller** [PokemonGoF/PokemonGo-Bot#2457]
It would be a nice feature that when I leave my pc/server running with the bot on that a push message could be sent to let me know a pokemon has been caught. 
This would mostly be nice for rare/very rare pokemons or with a specific CP/IV.
I put pushover in the title but there are a lot more push message services that could be used for this.

**Comment by nullpixel1** [comment]
Push message to what system / OS? As in like a email?

**Comment by iamhaller** [comment]
Push message to for example an iPhone running the Pushover app. Email could be a possibilty as well

**Comment by nullpixel1** [comment]
Yeah. I actually can't see this being hard at all. I will look into adding it, and making a pull request.

**Comment by nullpixel1** [comment]
Only thing is, users will have to supply their own API key for it, which isn't free

**Comment by iamhaller** [comment]
@nullpixel1 that would be awesome! I know that pushover uses an api key and user key. Not sure for other notification services like PushBullet and Growl for example if they need this as well. I would imagine they would need some kind of authentification/api..

**Comment by Lunik** [comment]
@iamhaller PushBullet implementation could be nive :+1:

**Comment by iamhaller** [comment]
I think the services below are used the most for thing like this

Pushalot
Website: https://pushalot.com/

PushBullet
Website: https://www.pushbullet.com/

NotifyMyAndroid
Website: http://www.notifymyandroid.com/

Pushover
Website: https://pushover.net/

Growl
Website: http://growl.info/

Prowl
Website: http://www.prowlapp.com/

Email

**Comment by nullpixel1** [comment]
Email could be the easiest and most widespread.

The others all have downfall, and require significant coding and / or money
