### ISSUE TITLE
[Fix for minor issue] Bag full with Max Potions on high level + no Max potions in summary

### ISSUE THREAD

**Issue by JeroTwi** [PokemonGoF/PokemonGo-Bot#2460]
If a bot reaches higher level (20+) pokestops give out Max Potions (item number 104).
I started to notice the item bag of my bot was full because of this potion missing in the config file.
Also the summary at bot start didn't show the Max Potion.
I did some research and fixed this 'issue' by editing the following.

Edit RecycleItems section in config.json file and add in "Max Potion" like below:
```
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 50 },
            "Greatball":      { "keep" : 50 },
            "Ultraball":      { "keep" : 50 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 0 },
            "Hyper Potion":   { "keep" : 20 },
            "Max Potion":     { "keep" : 20 },
            "Revive":         { "keep" : 20 },
            "Razz Berry":     { "keep" : 30 }
          }
        }
      },
```

Addition to the ./pokemongo_bot/__init__.py file (for the summary to display Max Potion at bot start):
```
Remove line 362:
--             ' | HyperPotion: ' + str(items_stock[103]), 'cyan')

And replace with:
++             ' | HyperPotion: ' + str(items_stock[103]) +
++             ' | MaxPotion: ' + str(items_stock[104]), 'cyan')
```

I'm not very familiar with Github issue or fix submits or how this should be done.
So please tell me if there is another channel for submitting fixes.

**Comment by JaapMoolenaar** [comment]
I made a PR for this, see: #2456

**Comment by JeroTwi** [comment]
Ok, cool! I'm reading through github support right now. Scanning through and/or making a pull request would have made more sense. Thanks for the comment though!

**Comment by maestroi** [comment]
Close this and put more in pr

**Comment by JeroTwi** [comment]
#2456
