### ISSUE TITLE
List out all pokemon in the inventory

### ISSUE THREAD

**Issue by g2384** [PokemonGoF/PokemonGo-Bot#2466]
### Expected Behavior

An example:

    #1 Bulbasaur: [237/0.49][206/0.29]
    #4 Charmander: [113/0.58][94/0.78]
    #7 Squirtle: [553/0.84][546/0.33][502/0.31][500/0.11][462/0.49]
    .
    .
    .

Including number, name, CP, IV

This can be written to a json file or text file in `data` folder. I have edited the `transfer_pokemon.py` file to do this. It is updated every 10 min and if it has new pokemon in inventory.

This data can be a reference for users to some extent, when they choose which one to evolve/max CP.

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by mommy742** [comment]
how did you do this?

**Comment by g2384** [comment]
The code is really messy, you can optimise it if you want.
Code:  [transfer_pokemon_改.py](https://gist.github.com/g2384/3b7d667a0fdcc399fa88cac03bda0a8c)

**Comment by mommy742** [comment]
cool also i might ask again about it later since i literally just started editing the config like 2 minutes ago
