### ISSUE TITLE
[Request] Wiki entry for MoveToMapPokemon

### ISSUE THREAD

**Issue by Erody** [PokemonGoF/PokemonGo-Bot#2467]
Right now there is only a example config file for this task, which doesn't explain anything. I'm not sure how I'm supposed to use this task, and I'm most likely not the only one. I know that it works with [PokemonGo-Map](https://github.com/AHAAAAAAA/PokemonGo-Map), but that's pretty much all.

**Comment by Arderos** [comment]
Yeah, wiki needs a good update on all of the new features

**Comment by Yutsa** [comment]
Yep the config system is kind of confusing and really verbose.

Do you know if the `config.json.example` can be used as it is ? Just editing the login info and then launch the bot. Will it spin forts and catch pokemons ?

My  bot has been running around not spinning or catching pokemons for more than an hour now...
