### ISSUE TITLE
sniping feature

### ISSUE THREAD

**Issue by ocoot** [PokemonGoF/PokemonGo-Bot#2468]
hellooooo. i'm confused how to using sniping feature? bcz on f.a.q didn't explained how to using it. thanks!

**Comment by VirtualSatai** [comment]
Setup https://github.com/AHAAAAAAA/PokemonGo-Map, edit the config following the config.json.map.example.

**Comment by IcicleTF** [comment]
Question, what do the values next to the seperators do? For example,      
```

            "==========Semi Rare==========": 0,
            "Porygon": 200,
            "Scyther": 200,
            "Jynx": 200,

            "==========Uncommon==========": 0,

            "Omanyte": 150,
            "Omastar": 500,

            "Seel": 300,
            "Dewgong": 500,

```

I figure the values next to the pokemon are the minimum CP, but what are the values next to the "uncommon" and "semi rare", etc?

**Comment by VirtualSatai** [comment]
Nothing, this is just a lookup table for when you have a pokemon to see its "value", since no pokemon is called `==========Uncommon==========` it's value will never be looked up. However it needs to be there to be valid JSON since JSON doesn't have comments.

**Comment by IcicleTF** [comment]
Gotcha, thank you very much.
