### ISSUE TITLE
how to disable or stop standby on lure

### ISSUE THREAD

**Issue by akbaribnu** [PokemonGoF/PokemonGo-Bot#2469]
how to disable stop and stay on lure .? i trys to set lure to false, but that not work.?

**Comment by Arderos** [comment]
Same here. Set "lure_attraction": false, but when the bot runs, it still prefers lured pokestops:[20:07:09] Moving towards fort <->, 0.10km left (attraction of lure 0.14km)
[20:07:16] Moving towards fort <->, 0.09km left (attraction of lure 0.13km)
