### ISSUE TITLE
Pokemon naming not working correctly

### ISSUE THREAD

**Issue by matwithers** [PokemonGoF/PokemonGo-Bot#2474]
Just noticed something odd, I just saw my bot catch a Jigglypuff with an IV of 0.8. I'm using the Task:
{
  "type": "NicknamePokemon",
  "config": {
    "nickname_template": "{name}_{iv_pct}"
  }
}

but the bot renamed it to:
Jigglypuff_8

Shouldn't it rename to Jigglypuff_80 ? or is there something wrong with my config ?

**Comment by LuckyMe4Evers** [comment]
Niantic imposes a 12-character limit on all pokemon nicknames, so any new nickname will be truncated to 12 characters if over that limit. Thus, it is up to the user to exercise judgment on what template will best suit their need with this constraint in mind.

**Comment by LuckyMe4Evers** [comment]
use 
 "nickname_template":"{name:.8s}-{iv_pct}"
and it should make
Jigglypu_80

**Comment by matwithers** [comment]
Ah right, thanks makes perfect sense.

I'll use that.

Cheers

Mat

**Comment by Raiven66** [comment]
or you could also change the template to
{iv_pct}_{name}
to have the IV first and name of fitting size after
