### ISSUE TITLE
[Dev] ServerSideRequestThrottlingException

### ISSUE THREAD

**Issue by DokterPhill** [PokemonGoF/PokemonGo-Bot#2476]
### Expected Behavior
At starting a bot, exception ServerSideRequestThrottlingException is thrown:

``\PokemonGo-Bot>pokecli.py
Traceback (most recent call last):
  File``\pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: cannot import name ServerSideRequestThrottlingException

### Steps to Reproduce
starting bot.

### Other Information
OS: win10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here): 361c0fa11783085ea201a71a99f6c43859e8c239
Python Version: (run 'python -V' and paste it here):  Python 2.7.12

**Comment by N3W4L** [comment]
Hi,
I have exactly the same problem since I updated to the last version.
Before everything worked fine, I only "git pull"

Any ideas ?

**Comment by pokemule** [comment]
Run 'pip install -r requirements.txt'

**Comment by DokterPhill** [comment]
@pokemule did that, got new error.

![image](https://cloud.githubusercontent.com/assets/20598893/17368337/cd09462c-5993-11e6-8b1f-c4e90d705547.png)

**Comment by N3W4L** [comment]
Many thanks!
I ran 
sudo pip install -r requirements.txt

And everything worked fine except some incompatibilites due to new version, but I will manage it
