### ISSUE TITLE
Stop moving towards pokemon after being captured

### ISSUE THREAD

**Issue by bixuanzju** [PokemonGoF/PokemonGo-Bot#2478]
### Expected Behavior

Stop moving towards pokemon after being captured

### Actual Behavior

It continues to move towards the location even though the pokemon we are after has been captured.

### Steps to Reproduce

![screen shot 2016-08-03 at 9 39 10 pm](https://cloud.githubusercontent.com/assets/1680704/17367556/03b45e80-59c3-11e6-96d0-fe074059351d.png)

As can been seen, Growlithe has been captured, but the bot still moves towards it.

### Other Information
OS: MacOS
Git Commit: 361c0fa11
Python Version: Python 2.7.12

**Comment by Arcasss** [comment]
why is it closed? i have same behaviour :/
