### ISSUE TITLE
Missing Dratini in exemple

### ISSUE THREAD

**Issue by Lunik** [PokemonGoF/PokemonGo-Bot#2479]
In `configs/config.json.pokemon.exemple

**Comment by nikhil-pandey** [comment]
Nidoran M and Nidoran F are also missing.

**Comment by nivong** [comment]
add it and make a pull request?

**Comment by Lunik** [comment]
I don't have the optimised values for release section :p

**Comment by nivong** [comment]
That makes no sense....
