### ISSUE TITLE
Trying to launch the code using a .bat file

### ISSUE THREAD

**Issue by Oncoming-Storm** [PokemonGoF/PokemonGo-Bot#2484]
### Expected Behavior
Using this
`cd C:\Users\My\Downloads
  
cd PokemonGo-Bot
  virtualenv .
  Scripts\activate
  python pokecli.py`

I expected it to open the cmd and run each command and launch the bot.

### Actual Behavior
It runs every command up to Scripts\activate which when it runs it it just closes the cmd window

### Other Information
OS: Windows 7 Home Edition
Git Commit: (No idea how to get this and I believe is irrelevant.)
Python Version: 2.7.12

I'm a huge noob so PLEASE bare with me... Thank you for reading!

**Comment by leadboots5** [comment]
i think you need 'Scripts\activate.bat'

**Comment by BoGnY** [comment]
this is not necessary.. you have only to double click on pokecli.py and bot start..
