### ISSUE TITLE
How does the reticle factor and spin factor work?

### ISSUE THREAD

**Issue by trippyhat** [PokemonGoF/PokemonGo-Bot#2488]
There is a config setting that we can set that changes the `reticle factor` and `spin factor`, but I don't quite understand what those do.

In the code, these are some of the parameters:

    normalized_reticle_size   (double)
    spin_modifier             (double)
    normalized_hit_position   (double)

Can someone explain in-depth what these parameters are and how they affect catching pokemon?

ie, how does `normalized_reticle_size=10.0`, `spin_modifier=5.0`, `normalized_hit_position=10.0` affect the throw and catch success?

And how does those parameters relate to what we see on the in-game catch pokemon screen? ie, what determines the `nice`, `great`, `excellent`, etc messages when a pokeball makes contact with a pokemon?

**Comment by pokemule** [comment]
I'm pretty sure max number for normalized reticle size is 1.95, spin modifier is 1, and normalized hit pos is 1. When the reticle factor you defined in your json is 0, then the code chooses a random number between 0 and 1.95. This random number, which is the normalized reticle size, basically determines if your throw is nice great or excellent. I'm not exactly sure what the threshold is for each, but the higher the number, the more likely it is to be a better throw. Thus, a reticle factor (in the config.json) of 1 chooses a random number between 1.95 and 1.95 and sets that number to the normalized reticle size. Obviously, the only number that satisfies that condition is 1.95, so the throw is always excellent if the reticle factor is 1. Basically, you can only choose a number between 0 and 1 for each of the two variables: reticle factor and spin factor in the config.json. The higher the number you choose, the more chance that your throw will be an upper tier throw (i.e. great or excellent). The lower the number you choose, the more randomized what type of throw is chosen.

Spin factor and spin modifier work in a similar way, where a higher number in spin factor (maximum number of 1) correlates to a higher chance that you spin the ball.

I'm pretty sure normalized hit position is the % chance that the ball will actually hit. So if you choose 0.5 then the ball hits the pokemon 50% of the time, and the other 50% means you basically just lost a pokeball. I'm not entirely sure about that one though.

**Comment by trippyhat** [comment]
@pokemule Thanks, that was a really good overview! Do you know what the range of reticle values  would be for the `nice`, `great`, and `excellent` messages?

I'm still confused on spin modifier/factor though. What exactly is a pokeball 'spin' in the game, and how does it affect capture success (compared to reticle)? And does setting spin factor higher is better?

**Comment by pokemule** [comment]
@trippyhat I'm not entirely sure what the threshold is for each of the type of pokeball throws (nice, great, and excellent). The website https://rankedboost.com/pokemon-go/tier-list/ states that the capture rate modifier for Excellent Throws is 1.5, Great Throw is 1.3, and Nice Throw is 1, but I'm not sure if that's related at all to the normalized reticle size or reticle factor.

The spin factor and modifiers basically manipulate the pokeball's spin as you throw it. The YouTube video https://www.youtube.com/watch?v=WEz0jQEQ094 shows how spinning the pokeball in game works. If you capture a Pokemon when there are those yellow sparks coming out the pokeball as you spin it, you get a bonus of 10 exp. I believe this also increases your chance of catching the Pokemon, but I'm entirely sure about that (see http://www.imore.com/how-to-throw-curveball-pokemon-go). 

If you set the spin factor higher, there's a higher % chance that you spin the ball when you throw it (and thus giving you 10 more exp, and maybe a better chance to catch the Pokemon). I normally just keep that value at 0.85 so it'll spin most of the time, but still simulates human behavior.

Overall, I'm fairly certain that throwing a nice, great or excellent throw increases your chance of capturing the Pokemon the higher tier the throw is (i.e. excellent = best chance of catching the Pokemon). I'm not entirely sure if curving the ball (spinning it) influences the chance you capture the Pokemon, but it does give you 10 more exp.
