### ISSUE TITLE
Showing stats and inventory on keypress

### ISSUE THREAD

**Issue by JaapMoolenaar** [PokemonGoF/PokemonGo-Bot#2493]
I think the CLI could be enhanced somewhat by being able to show intermediate stats by pressing a key, like getting current stats (to for instance see xp/hr) and showing the current inventory.

I tred to get this done in Python, which is not my main language, but I got it working: https://github.com/JaapMoolenaar/PokemonGo-Bot/commit/f37f54f12b692f0db4ff23b1b23599dd38308b4e

This runs the bot in a separate "thread", and uses the ioctl/cli to capture key presses. Pressing i shows inventory, pressing s shows current stats. I only tested this in Linux, as I understand it Windows has different ways of capturing key strokes (which I did include).

### Expected Behavior
-

### Actual Behavior
-

### Steps to Reproduce
-

### Other  #Information
-

**Comment by JaapMoolenaar** [comment]
Please add [enhancement] / [new feature] labels.

**Comment by sgitkene** [comment]
nice option. currently you can already use web submodule to check info on bot (or read the files yourself), in case you didn't know.

**Comment by JaapMoolenaar** [comment]
I sure did! I use it frequently, in fact, I modified it to generate gpx files (or the json variant actually).

Not all stats are available however, like xp per hour (or time running). Hence I wrote this little thing. Making more stats available in the web interface (or the .json files really) would be better, are there plans to do so?

**Comment by cprior** [comment]
@JaapMoolenaar : There is an interesting PR #2528 to make a central class for inventory handling. This is promising.

My interest in this game and the bots is to collect lots of data. So in case the API-access comes back I will work on "stats". I think I will run this in a second python process using "just" the api, not the bot. (Logins still work, by the way, also get_inventory and get_player!)
