### ISSUE TITLE
[Features Request] Bot Report, XP and Egg Notifications

### ISSUE THREAD

**Issue by joaodragao** [PokemonGoF/PokemonGo-Bot#2495]
### Bot Report Feature

I would like to have a report that tells me which Pokemons were captured and which were kept and released after a few hours running the bot. So I modified some code to have this on test file.

```
Magikarp -- CP 89 -- 0.84 
Zubat -- CP 82 -- 0.87 
Zubat -- CP 332 -- 0.36 -- released
Rattata -- CP 10 -- 0.53 -- released
Pidgey -- CP 96 -- 0.44 -- released
Weedle -- CP 216 -- 0.42 -- released
Eevee -- CP 451 -- 0.89 
Weedle -- CP 16 -- 0.64 -- released
Pidgey -- CP 56 -- 0.24 -- released
Pidgey -- CP 176 -- 0.4 -- released
Caterpie -- CP 105 -- 0.42 -- released
Tentacool -- CP 180 -- 0.58 -- released
```

If it possible to include this feature where users can turn on and off in the configuration file.

This is the code.

```
if not is_vanished:
    with open(
            os.path.join(os.path.dirname(__file__),
                         os.pardir,
                         os.pardir,
                         'caught_pokemons.txt'),
            'a') as fileout:
        print >> fileout, '{} -- CP {} -- {} {}'.format(
            wild_pokemon_name,
            wild_poekemon_cp,
            wild_pokemon_potential,
            '-- released' if is_released_pokemon else '')
else:
    # runaway Pokemon! If you want to get that report too
```

Some other useful reports could be:
* How many XP did player earned
* Stardusts and Candies
* New Pokemon found?

### XP Notification Feature

I would like to capture the **Level Up** screenshot. However, the bot won't stop for that. If there is a feature that terminates the bot when it is about 200 XP to reach next level, that would be cool. I can implement that but I want you to adapt that feature.

### Hatch Egg Notification Feature

I also want to record egg hatching moment. For 2Km or 5Km, I can use to fake GPS. But 10Km requires a few hours. If the bot can stop after like 100m before hatching, that would be awesome. Can you adapt that feature too.

All of these features can be turn on and off in the configuration file.

**Comment by sgitkene** [comment]
you get a short recap when you stop bot so I assume this is already logged. maybe tap into that?
Also why stop for a levelup? the bot takes the levelup rewards already. and egg hatching? you get the pokemon, not risk it vanishing in the app.

anyway, you can make a pr if you have already implemented the features, no?

**Comment by joaodragao** [comment]
I want an auto-termination feature, so that I can log in the game and play around to get the **Level Up** or **Egg Hatching** moment where I can record or screenshot them. We use bot and we're not going sit down and watch it runs all the time, are we?

I don't have permission to contribute that's why I suggest the features here. :)
