### ISSUE TITLE
Seems tasks statement in config.json doesn't work, what's wrong in my conf?

### ISSUE THREAD

**Issue by andruxabr** [PokemonGoF/PokemonGo-Bot#2497]
{
    "auth_service": "google",
    "username": "-",
    "password": "-",
    "location": "-",
    "gmapkey": "NONE",
    "tasks": [
        {
            "type": "HandleSoftBan"
        },
        {
            "type": "CollectLevelUpReward"
        },
        {
            "type": "NicknamePokemon",
            "config": {
                "nickname_template": "{name:.8s}_{iv_pct}"
            }
        },
        {
            "type": "IncubateEggs",
            "config": {
                "longer_eggs_first": true
                }
        },
        {
            "type": "TransferPokemon"
        }, 
        {
            "type": "RecycleItems"
        }, 
        {
            "type": "CatchVisiblePokemon"
        }, 
        {
            "type": "CatchLuredPokemon"
        }, 
        {
            "type": "SpinFort"
        }, 
        {
            "type": "MoveToFort"
        }, 
        {
            "type": "FollowSpiral"
        },
        {
            "type": "RecycleItems",
            "config": {
                "item_filter": {
                "Pokeball":       { "keep" : 60 },
                "Greatball":       { "keep" : 60 },
                "Ultraball":       { "keep" : 60 },
                "Potion":         { "keep" : 0 },
                "Super Potion":   { "keep" : 10 },
                "Hyper Potion":   { "keep" : 70 },
                "Revive":         { "keep" : 25 },
                "Razz Berry":     { "keep" : 30 }
          }
        }
      }
    ],
    "max_steps": 8,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "1,2,101,102,103,104,201,701",
    "evolve_all": "NONE"
}

**Comment by g2384** [comment]
`max_steps` has been removed. What is the error info? Which version are you using?

**Comment by andruxabr** [comment]
No error message occur, just not put egg into incubator and rename pokemons not working, version python 2.7.11
I download zip archive from master branch yesterday

**Comment by g2384** [comment]
master branch code is really behind, It doesn't support rename I suppose.
