### ISSUE TITLE
Connexion failed

### ISSUE THREAD

**Issue by ElGecko76** [PokemonGoF/PokemonGo-Bot#25]
Hello,

I tried to log on replacing "python2 pokecli.py -a ptc -u tejado -p 1234 --location "New York, Washington Square" by my IDs but I have an error, my login and password yet they are ok, I don't understand :(

thanks in advance

**Comment by eggins** [comment]
Are you replacing the tejado:1234 section?

I cant seem to replicate the issue....

**Comment by ElGecko76** [comment]
Yes I have replaced "tejado" by my login and "1234" by my password .. :/

**Comment by dominikue** [comment]
I think i have the same problem:

`2016-07-21 14:13:09,019 [   pokecli] [ INFO] Your given location: LOCATION
2016-07-21 14:13:09,023 [   pokecli] [ INFO] lat/long/alt: [..]
2016-07-21 14:13:09,026 [  auth_ptc] [ INFO] Login for: USERNAME
2016-07-21 14:13:09,720 [  auth_ptc] [ERROR] Could not retrieve token: Your username or password is incorrect. You have 3 attempts left before you will be locked out of your account for 15 minutes.
2016-07-21 14:13:09,765 [    pgoapi] [ INFO] Login process failed`

**Comment by millejosh** [comment]
Are you logging in the a Google account or Pokemon trainer club?

If Google you need to change 'ptc' to google

**Comment by dominikue** [comment]
It is a Pokemon Trainer Club account and it work for me on any other devices. 
That was my input in the CMD and i running Windows64:
`E:\Pokemon GO\Bot2\PokemonGo-Bot-master>pokecli.py -a ptc -u USER -p PASS --location "City, Place"`

**Comment by eggins** [comment]
add `python` to the start.

> python pokecli.py -a ptc -u USER -p PASS --location "City, Place"

**Comment by dominikue** [comment]
Still the same error and to run the cmd as admin doesn't help too.

**Comment by eggins** [comment]
Please copy / screenshot the error that happens once you attempt it.

**Comment by dominikue** [comment]
Thank you for your fast helping btw :)

![image_2016-07-21_at_14-25-27](https://cloud.githubusercontent.com/assets/17249002/17022616/46da3ea6-4f4f-11e6-9a54-e23dd04bf7e0.jpg)

**Comment by eggins** [comment]
You will need to check agian in 15 - or start a new account and test with that!

**Comment by ElGecko76** [comment]
I have exactly the same problem

**Comment by dominikue** [comment]
@eggins It wasnt disabled as I tried it - it was the fourth trial.

**Comment by dominikue** [comment]
I created an google account and it doesnt work for me too.

`2016-07-21 14:59:43,473 [auth_google] [ INFO] Google login for: [name]@gmail.com
2016-07-21 14:59:43,816 [auth_google] [ INFO] Google Login failed.
2016-07-21 14:59:43,819 [    pgoapi] [ INFO] Login process failed`

**Comment by ElGecko76** [comment]
You as your login is correct when you log on the website or app ?

**Comment by harsh1412** [comment]
log in the google from your browser then run the bot ,it may be suspicious to google or something -.-'

**Comment by dominikue** [comment]
Still login process failed "Login process failed" :(

**Comment by ElGecko76** [comment]
nobody has an idea ? :(

**Comment by ElGecko76** [comment]
thanks @millejosh , I replaced "ptc" by google, it works !

**Comment by millejosh** [comment]
@ElGecko76 awesome man! glad to hear it

**Comment by dominikue** [comment]
Found the bug for me:
Old password was "u8lJx^f2fs6@T3n" and i replaced it with a simpler one. Think your programm cant handle all chars :)
