### ISSUE TITLE
how to edit config and use tasks

### ISSUE THREAD

**Issue by mommy742** [PokemonGoF/PokemonGo-Bot#2500]
hey, so i am trying to learn how to use tasks and advance configuration and i don't find out anywhere how. if anyone can help and yes i have look on the slack chat for help in the #help channel and still no help. i just want to know how to add tasks in the config and use advanced configuration. if you can help it would be greatly appreciated. thanks bye ^-^. using windows 10.

**Comment by jomarocas** [comment]
yes i very hard because you need enter to all files that you find in configs, in this place you can see all related with advanced configuration, config.example all in this folder

**Comment by mommy742** [comment]
@jomarocas umm what are you talking about? because i don't get what you're referencing to.

**Comment by liudayu** [comment]
?
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files

**Comment by mommy742** [comment]
@

**Comment by mommy742** [comment]
@liudayu i was using the master and not dev never mind.

**Comment by jomarocas** [comment]
the you need use 

```
git fetch && git checkout dev
pip install --upgrade -r requirements.txt
```
