### ISSUE TITLE
How to stop character

### ISSUE THREAD

**Issue by adrianolsz** [PokemonGoF/PokemonGo-Bot#2509]
### Expected Behavior
I would like to have trainer stay only in one place set with my cords and don't move. For example near 3-4 pokestops, which are with lure modules almost whole day

### Actual Behavior
When I run bot, it spin first pokestop and starts moving out

What and where I should set it?

**Comment by tr3intaydos** [comment]
why not create a path between those pokestops?

**Comment by vicch** [comment]
Exclude these from your config: MoveToFort, FollowSpiral, FollowPath, MoveToMapPokemon. This should give your bot nothing to do but stand still.

**Comment by adrianolsz** [comment]
I can't find path.example file in my PoGoBot folder
