### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by LuisEGR** [PokemonGoF/PokemonGo-Bot#2516]
### Expected Behavior
Search and show the actual  Highest CP Pokemon.

### Actual Behavior
The bot fails when searching the  Highest CP Pokemon, and stops working
Screenshot:
http://imgur.com/a/P1p6D

### Steps to Reproduce
Just run the bot normally

### Other Information
OS: Windows 7 x64
Git Commit: 4182e93f9bfbe471d07b74e95c55cdfbacda127b
Python Version: 2.7.11
NodeJs Version: 5.8.0

**Comment by TCB13** [comment]
I've the exact same issue, however it doesn't seem constant... Any tips on fixing this?
