### ISSUE TITLE
Bot Is Only Searching for Pokemon

### ISSUE THREAD

**Issue by JackPowellFBI** [PokemonGoF/PokemonGo-Bot#252]
### Expected Behavior
Specifying the -s flag (or "spinstop": "True" in json.config) should spin PokeStops.

### Actual Behavior
It either ignores the  -s flag/argument or can't find it somehow, and then will only search for Pokemon.

### Steps to Reproduce
Fresh clone of repo (master or dev, have tried both),
run pip install command and then try to start the bot, 
it complains and error reads: "pokecli.py: error: argument -a/--auth_service is required" 
even though i'm using the following command in the directory:
pokecli.py -a ptc -u USERNAME -p PASSWORD -l 41.078865,-81.5436767 -w 4.16 -t -s -c 100

username and password removed for security

As a workaround I tried to set those arguments in a json.config file but it still doesn't seem to recognize my arguments correctly.

Any help would be greatly appreciated.

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Calcyfer** [comment]
Regarding your argument issue : the location needs quotes around it.

-s has been replaced by -m a few commits ago, try that instead.

**Comment by StahlJonas** [comment]
-m all does only catch pokemons for me

**Comment by rkodali22** [comment]
python pokecli.py -a google -u xxx -p xxx -l "40.785091,-73.968285"  -c 60 -m all -w 10
[x] PokemonGO Bot v1.0
[x] Configuration initialized

[x] Address found: 40.785091,-73.968285
[x] Position in-game set as: (40.7837665, -73.9651175, 0.0)

[#]
[#] Username: xxx
[#] Acccount Creation: 2016-07-10 20:11:29.092000
[#] Bag Storage: 330/350
[#] Pokemon Storage: 222/250
[#] Stardust: 31353
[#] Pokecoins: 0
[#] -- Level: 14
[#] -- Experience: 89845
[#] -- Experience until next level: 10155
[#] -- Pokemon Captured: 288
[#] -- Pokestops Visited: 143
[#]
[x] Starting PokemonGo Bot....
[#] Scanning area for objects (1 / 25)
[#] Walking from (40.7837665, -73.9651175) to (40.7837665, -73.9651175) for approx. 0.0 seconds
[#] Finished walking
[#] (40.7837665, -73.9651175, 0)
Found fort 1afcf0b0fa494c12943dceea7c7c7abe.12 at distance 607.674132274m
Need to move closer to Pokestop
[#] Walking from (40.7837665, -73.9651175) to (40.778799, -73.962109) for approx. 61.0 seconds
[#] Something rustles nearby!
[#] A Wild Doduo appeared! [CP 216]
[x] Using Pokeball...
[x] Captured Doduo! [CP 216]
[#] Something rustles nearby!

**Comment by Calcyfer** [comment]
Seems like the error was introduced a few minutes ago. With all these commits following eachother so fast, it's quite impossible to pinpoint the exact moment when.

I'm on commit [08e03dc7c238348ff10a30a26e8a9fb08cfe4baf](https://github.com/PokemonGoF/PokemonGo-Bot/tree/08e03dc7c238348ff10a30a26e8a9fb08cfe4baf) and can confirm that one's working.

**Comment by CapCap** [comment]
```
[x] Walked to Pokemon
[#] A Wild Doduo appeared! [CP381]
[x] Using Greatball...
[x] Captured Doduo! [CP381]
[x] Found pokemon at distance 52.0520073622m
[#] Walking from (21.265614828112568, -157.82162955950363) to (21.26551563598147, -157.82218843176165) for approx. 21.0 seconds
[#] Finished walking to (21.26551563598147, -157.82218843176165)
[x] Walked to Pokemon
[x] Found pokemon at distance 50.5072501907m
[#] Walking from (21.26551563598147, -157.82218843176165) to (21.265853451888105, -157.82144326878532) for approx. 30.0 seconds
[#] Finished walking to (21.265853451888105, -157.82144326878532)
[x] Walked to Pokemon
[x] Found pokemon at distance 45.3674269089m
[#] Walking from (21.265853451888105, -157.82144326878532) to (21.265614828112568, -157.82162955950363) for approx. 12.0 seconds
[#] Finished walking to (21.265614828112568, -157.82162955950363)
[x] Walked to Pokemon
[#] Walking from (21.265614828112568, -157.82162955950363) to (21.2659149, -157.8219262) for approx. 16.0 seconds
walking hook  14 [#] Finished walking to (21.2659149, -157.8219262)
```

Latest master- am seeing walk w/o pokemon capture- shouldnt it also be checking for pokemon presence every x steps?

**Comment by JackPowellFBI** [comment]
Even after putting the location data in quotes (i've tried single and double quotes) 
it still says -a/--auth_service required. here is my new command:
pokecli.py -a ptc -u USERNAME -p PASSWORD -l '41.078865,-81.5436767' -w 15 -c 100 -m farm

**Comment by Calcyfer** [comment]
Your command works on my end, try downloading the repo again so you have the latest commit.

**Comment by JackPowellFBI** [comment]
I just pulled down a fresh version and it still complains, I am up to the latest commit as of now.

**Comment by Calcyfer** [comment]
Does using `--auth_service` instead of `-a` work?

**Comment by JackPowellFBI** [comment]
Sadly, no. =(

**Comment by JackPowellFBI** [comment]
Once the PTC login server becomes available again I will test this with a fix I found. It looks like it involves Python on a registry level, and isn't uncommon. Will post back soon.

**Comment by Calcyfer** [comment]
Look forward to hearing the results.

**Comment by surfaace** [comment]
was fixed at some point, working in latest DEV branch

**Comment by JackPowellFBI** [comment]
Changing a python registry value to include more arguments fixed my issue.
