### ISSUE TITLE
Eggs not working with simple addition to config.json

### ISSUE THREAD

**Issue by HelloTroy** [PokemonGoF/PokemonGo-Bot#2520]
### Expected Behavior
{
    "auth_service": "google",
    "username": "",
    "password": "",
    "location": "",
    "gmapkey": "",
    "tasks": [
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
    ]
}

**Shouldn't this simple addition work? I have it located in config.json**

### Actual Behavior
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 17 column 5 (char 449)

**Is this just some sort of word processing error**

### Other Information
OS: X yosemite
Git Commit: 
Python Version: 2.7

**Comment by WebberTakken** [comment]
Please use indents in your config, it would have made it more clear that you missed a } right before your ].

Please use the link on this wikipage to validate your config; https://github.com/PokemonGoF/PokemonGo-Bot/wiki/No-JSON-object-could-be-decoded-or-decoder.py-error

Bot works as intended, please close

**Comment by AcorpBG** [comment]
You seems to have missplaced the ] bracket of the tasks you need to close both {} one for the type one for the config. Also if you have more parameters after task you need comma after the ]
