### ISSUE TITLE
Can‘t log in to PokemonGo with Bot

### ISSUE THREAD

**Issue by paddlephreak** [PokemonGoF/PokemonGo-Bot#2522]
I've just installed the latest dev version and tried to run it.
When it tries to log in it always says:
[20:39:07] Attempting login to Pokemon Go.
[20:39:08]  [X] Login Error, server busy 
[20:39:08]  [X] Waiting 10 seconds to try again 

When I start PokemonGo on my phone it works.

**Comment by WebberTakken** [comment]
did you put the right password?

**Comment by Bilters** [comment]
Take a look at; #2174

**Comment by paddlephreak** [comment]
Everything was right. Just copied username an password from an older config and it worked. nothing has changed but it works now. weird.

**Comment by Bilters** [comment]
Please proceed to close this ticket :no_entry_sign:
