### ISSUE TITLE
[Dev] Not catching any pokemons or taking pokestops

### ISSUE THREAD

**Issue by firzzen** [PokemonGoF/PokemonGo-Bot#2533]
### Expected Behavior

Bag full or not full, bot should catch pokemons when walking.

### Actual Behavior

Bot says:

[22:23:17]  Not spinning any forts as there aren't enough space. You might want to change your config to recycle more items if this message appears consistently.
[22:23:17]  Not moving to any forts as there aren't enough space. You might want to change your config to recycle more items if this message appears consistently.

The bot just keeps walking and walking....

[22:38:03] Walking from (34.013863560994714, -118.4940364734424) to [34.013863560994714, -118.49466583492193] 0.06km
[22:38:10] Walking from (34.013863560994714, -118.49466583492193) to [34.01323051338843, -118.49466583492193] 0.07km

And keeps running to next pokestops but not catching any pokemons in the meantime.

### Steps to Reproduce

Run this config:

     {
    "auth_service": "ptc",
    "username": "xxxxx",
    "password": "xxxxx",
    "location": "34.011330, -118.493397",
    "gmapkey": "xxxxxx",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 80 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 0 },
            "Hyper Potion":   { "keep" : 0 },
            "Revive":         { "keep" : 0 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config":{
          "lure_attraction": true,
          "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 100
    },
    "websocket_server": false,
    "walk": 12,
    "action_wait_min": 0,
    "action_wait_max": 1,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "all",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or" },

      "// Pokemons with example": { "always_catch": true },
      "// Gets filtered with release parameters": {},

      "// Legendary pokemons (Goes under S-Tier)": {},
      "Lapras": { "always_catch": true },
      "Moltres": { "always_catch": true },
      "Zapdos": { "always_catch": true },
      "Articuno": { "always_catch": true },

      "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
      "Mewtwo": { "always_catch": true },
      "Dragonite": { "always_catch": true },
      "Snorlax": { "always_catch": true },
      "// Mew evolves to Mewtwo": {},
      "Mew": { "always_catch": true },
      "Arcanine": { "always_catch": true },
      "Vaporeon": { "always_catch": true },
      "Gyarados": { "always_catch": true },
      "Exeggutor": { "always_catch": true },
      "Muk": { "always_catch": true },
      "Weezing": { "always_catch": true },
      "Flareon": { "always_catch": true },

      "// Growlithe evolves to Arcanine": {},
      "Growlithe": { "always_catch": true },
      "// Dragonair evolves to Dragonite": {},
      "Dragonair": { "always_catch": true },
      "// Grimer evolves to Muk": {},
      "Grimer": { "always_catch": true },

      "// Magikarp evolves to Gyarados": {},
      "Magikarp": { "always_catch": true },
      "// Exeggcute evolves to Exeggutor": {},
      "Exeggcute": { "always_catch": true },
      "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
      "Eevee": { "always_catch": true },

      "// A-Tier pokemons": {},
      "Slowbro": { "always_catch": true },
      "Victreebel": { "always_catch": true },
      "Machamp": { "always_catch": true },
      "Poliwrath": { "always_catch": true },
      "Clefable": { "always_catch": true },
      "Nidoking": { "always_catch": true },
      "Venusaur": { "always_catch": true },
      "Charizard": { "always_catch": true },
      "Golduck": { "always_catch": true },
      "Nidoqueen": { "always_catch": true },
      "Vileplume": { "always_catch": true },
      "Blastoise": { "always_catch": true },
      "Omastar":  { "always_catch": true },
      "Aerodactyl": { "always_catch": true },
      "Golem": { "always_catch": true },
      "Wigglytuff": { "always_catch": true },
      "Dewgong": { "always_catch": true },
      "Ninetales": { "always_catch": true },
      "Magmar": { "always_catch": true },
      "Kabutops": { "always_catch": true },
      "Electabuzz": { "always_catch": true },
      "Starmie": { "always_catch": true },
      "Jolteon": { "always_catch": true },
      "Rapidash": { "always_catch": true },
      "Pinsir": { "always_catch": true },
      "Scyther": { "always_catch": true },
      "Tentacruel": { "always_catch": true },
      "Gengar": { "always_catch": true },
      "Hypno": { "always_catch": true },
      "Pidgeot": { "always_catch": true },
      "Rhydon": { "always_catch": true },
      "Seaking": { "always_catch": true },
      "Kangaskhan": { "always_catch": true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or" },

      "// Legendary pokemons (Goes under S-Tier)": {},
      "Lapras": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Moltres": { "release_below_cp": 1132, "release_below_iv": 0.8, "logic": "and" },
      "Zapdos": { "release_below_cp": 1087, "release_below_iv": 0.8, "logic": "and" },
      "Articuno": { "release_below_cp": 1039, "release_below_iv": 0.8, "logic": "and" },

      "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
      "Mewtwo": { "release_below_cp": 1447, "release_below_iv": 0.8, "logic": "and"},
      "Dragonite": { "release_below_cp": 1221, "release_below_iv": 0.8, "logic": "and" },
      "Snorlax": { "release_below_cp": 1400, "release_below_iv": 0.8, "logic": "and" },
      "// Mew evolves to Mewtwo": {},
      "Mew": { "release_below_cp": 1152, "release_below_iv": 0.8, "logic": "and" },
      "Arcanine": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Vaporeon": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Gyarados": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Exeggutor": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Muk": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Weezing": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Flareon": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },

      "// Growlithe evolves to Arcanine": {},
      "Growlithe": { "release_below_cp": 600, "release_below_iv": 0.8, "logic": "and" },
      "// Dragonair evolves to Dragonite": {},
      "Dragonair": { "release_below_cp": 700, "release_below_iv": 0.8, "logic": "and" },
      "// Grimer evolves to Muk": {},
      "Grimer": { "release_below_cp": 700, "release_below_iv": 0.8, "logic": "and" },
      "// Magikarp evolves to Gyarados": {},
      "Magikarp": { "release_below_cp": 150, "release_below_iv": 0.8, "logic": "and" },
      "// Exeggcute evolves to Exeggutor": {},
      "Exeggcute": { "release_below_cp": 600, "release_below_iv": 0.8, "logic": "and" },
      "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
      "Eevee": { "release_below_cp": 600, "release_below_iv": 0.8, "logic": "and" },

      "// A-Tier pokemons": {},
      "Slowbro": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Victreebel": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Machamp": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Poliwrath": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Clefable": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Nidoking": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Venusaur": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Charizard": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Golduck": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Nidoqueen": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Vileplume": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Blastoise": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Omastar":  { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Aerodactyl": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Golem": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Wigglytuff": { "release_below_cp": 1050, "release_below_iv": 0.8, "logic": "and" },
      "Dewgong": { "release_below_cp": 1050, "release_below_iv": 0.8, "logic": "and" },
      "Ninetales": { "release_below_cp": 1050, "release_below_iv": 0.8, "logic": "and" },
      "Magmar": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Kabutops": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Electabuzz": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Starmie": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Jolteon": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Rapidash": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Pinsir": { "release_below_cp": 1300, "release_below_iv": 0.8, "logic": "and" },
      "Scyther": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Tentacruel": { "release_below_cp": 1300, "release_below_iv": 0.8, "logic": "and" },
      "Gengar": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Hypno": { "release_below_cp": 1300, "release_below_iv": 0.8, "logic": "and" },
      "Pidgeot": { "release_below_cp": 1500, "release_below_iv": 0.8, "logic": "and" },
      "Rhydon": { "release_below_cp": 1000, "release_below_iv": 0.8, "logic": "and" },
      "Seaking": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Kangaskhan": { "release_below_cp": 1000, "release_below_iv": 0.8, "logic": "and" },

      "// Koffing evolves to Weezing (A-Tier)": {},
      "Koffing": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },

      "// Below is B-tier and lower pokemons": {},
      "Caterpie": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Weedle": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Diglett": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Metapod": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Kakuna": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Rattata": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Abra": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Zubat": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Chansey": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Pidgey": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Spearow": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Meowth": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Krabby": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Sandshrew": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Poliwag": { "release_below_cp": 600, "release_below_iv": 0.8, "logic": "and" },
      "Horsea": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Gastly": { "release_below_cp": 400, "release_below_iv": 0.8, "logic": "and" },
      "Ekans": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Shellder": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Vulpix": { "release_below_cp": 400, "release_below_iv": 0.8, "logic": "and" },
      "Voltorb": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Geodude": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Doduo": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Onix": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Mankey": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Pikachu": { "release_below_cp": 400, "release_below_iv": 0.8, "logic": "and" },
      "Magnemite": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Tentacool": { "release_below_cp": 550, "release_below_iv": 0.8, "logic": "and" },
      "Paras": { "release_below_cp": 550, "release_below_iv": 0.8, "logic": "and" },
      "Jigglypuff": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Ditto": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Staryu": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Charmander": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Goldeen": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Squirtle": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Cubone": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Venonat": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Bulbasaur": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Drowzee": { "release_below_cp": 600, "release_below_iv": 0.8, "logic": "and" },
      "Machop": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Psyduck": { "release_below_cp": 600, "release_below_iv": 0.8, "logic": "and" },
      "Seel": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Kabuto": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Bellsprout": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Omanyte": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Kadabra": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Oddish": { "release_below_cp": 550, "release_below_iv": 0.8, "logic": "and" },
      "Dugtrio": { "release_below_cp": 550, "release_below_iv": 0.8, "logic": "and" },
      "Rhyhorn": { "release_below_cp": 550, "release_below_iv": 0.8, "logic": "and" },
      "Clefairy": { "release_below_cp": 550, "release_below_iv": 0.8, "logic": "and" },
      "Slowpoke": { "release_below_cp": 550, "release_below_iv": 0.8, "logic": "and" },
      "Pidgeotto": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Farfetch'd": { "release_below_cp": 441, "release_below_iv": 0.8, "logic": "and" },
      "Poliwhirl": { "release_below_cp": 550, "release_below_iv": 0.8, "logic": "and" },
      "Nidorino": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Haunter": { "release_below_cp": 550, "release_below_iv": 0.8, "logic": "and" },
      "Nidorina": { "release_below_cp": 500, "release_below_iv": 0.8, "logic": "and" },
      "Graveler": { "release_below_cp": 501, "release_below_iv": 0.8, "logic": "and" },
      "Beedrill": { "release_below_cp": 504, "release_below_iv": 0.8, "logic": "and" },
      "Raticate": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Butterfree": { "release_below_cp": 800, "release_below_iv": 0.8, "logic": "and" },
      "Hitmonlee": { "release_below_cp": 520, "release_below_iv": 0.8, "logic": "and" },
      "Ponyta": { "release_below_cp": 530, "release_below_iv": 0.8, "logic": "and" },
      "Hitmonchan": { "release_below_cp": 530, "release_below_iv": 0.8, "logic": "and" },
      "Charmeleon": { "release_below_cp": 544, "release_below_iv": 0.8, "logic": "and" },
      "Wartortle": { "release_below_cp": 700, "release_below_iv": 0.8, "logic": "and" },
      "Persian": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Lickitung": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Ivysaur": { "release_below_cp": 900, "release_below_iv": 0.8, "logic": "and" },
      "Electrode": { "release_below_cp": 900, "release_below_iv": 0.8, "logic": "and" },
      "Marowak": { "release_below_cp": 900, "release_below_iv": 0.8, "logic": "and" },
      "Gloom": { "release_below_cp": 900, "release_below_iv": 0.8, "logic": "and" },
      "Porygon": { "release_below_cp": 900, "release_below_iv": 0.8, "logic": "and" },
      "Seadra": { "release_below_cp": 900, "release_below_iv": 0.8, "logic": "and" },
      "Jynx": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Weepinbell": { "release_below_cp": 800, "release_below_iv": 0.8, "logic": "and" },
      "Tangela": { "release_below_cp": 1000, "release_below_iv": 0.8, "logic": "and" },
      "Fearow": { "release_below_cp": 1500, "release_below_iv": 0.8, "logic": "and" },
      "Parasect": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Machoke": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Arbok": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Sandslash": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Alakazam": { "release_below_cp": 633, "release_below_iv": 0.8, "logic": "and" },
      "Kingler": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Dodrio": { "release_below_cp": 1000, "release_below_iv": 0.8, "logic": "and" },
      "Tauros": { "release_below_cp": 643, "release_below_iv": 0.8, "logic": "and" },
      "Primeape": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Magneton": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Venomoth": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and" },
      "Golbat": { "release_below_cp": 1200, "release_below_iv": 0.8, "logic": "and" },
      "Raichu": { "release_below_cp": 708, "release_below_iv": 0.8, "logic": "and" },
      "Cloyster": { "release_below_cp": 1100, "release_below_iv": 0.8, "logic": "and"},
      "Mr. Mime": { "release_below_cp": 900, "release_below_iv": 0.8, "logic": "and" }
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
	"Charizard": {},
	"Exeggutor": {},	
        "Flareon": {}

    }
}

### Other Information
OS: Ubuntu 15.04
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: 2.7.9

**Comment by firzzen** [comment]
The bot just keeps walking and walking....

[22:38:03] Walking from (34.013863560994714, -118.4940364734424) to [34.013863560994714, -118.49466583492193] 0.06km
[22:38:10] Walking from (34.013863560994714, -118.49466583492193) to [34.01323051338843, -118.49466583492193] 0.07km

Doing nothing else in between, only walking...

**Comment by thelord810** [comment]
Same issue observed. After setting debug: true, I can only see some issue with protoc:
2016-08-04 01:17:30,819 [pgoapi.rpc_api] [DEBUG] Decode raw over protoc (protoc has to be in your PATH):
Couldn't find protoc in your environment OR other issue...

But Protoc is present in my PATH.

**Comment by firzzen** [comment]
I'm not using any configs besides the modified config.json.pokemon.example. Should i be altering some other configs and running them as well?

Right now i've got three bots running with same configs (different location) and all have the same issue.

Please help!

**Comment by firzzen** [comment]
Ok i think this is related to the unstable servers at the moment because i'm running one other piece of software (with the same goal) as well and it has the same thing, just walking around and looking for pokemons but not finding anything.

Anyone else?

**Comment by tarpan2** [comment]
same for me

**Comment by ChrisHaPunkt** [comment]
same here

**Comment by jomarocas** [comment]
ok same here, any update of api

**Comment by Yutsa** [comment]
I have the same issue, the bot is just wandering without spinning forts or catching pokemons.

**Comment by nineeightseven** [comment]
Walkin and walkin...
Same problem
I think need an upgrade.

**Comment by jcleigh** [comment]
I did a fresh pull of dev a few hours ago and it was working fine; now it is only walking like mentioned above.

**Comment by brantje** [comment]
Read: https://github.com/PokemonGoF/PokemonGo-Bot/issues/2540
