### ISSUE TITLE
Bot will not spin pokestops when bag is full

### ISSUE THREAD

**Issue by cth90** [PokemonGoF/PokemonGo-Bot#2537]
### Expected Behavior
Bot continues to spin pokestops in order to gain experience.

### Actual Behavior
Bot does not spin pokestops because the bag is full.

### Other Information
OS: Ubuntu
Git Commit: dev

**Comment by jcleigh** [comment]
I have this issue on Windows 7 also. You still get XP from spinning even if your bags are full, so there should be a flag to allow it.

**Comment by Anti-CCP** [comment]
Same problem here,I changed the config and fixed it
Just add ultraball and ultraball into the config.json
For example
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 20 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 50 },
            "Greatball":     { "keep" : 40 },
            "Ultraball":     { "keep" : 40 }

**Comment by Anti-CCP** [comment]
I hate my input program
Just add Greatball and Ultraball into the config.json
