### ISSUE TITLE
ImportError: No module named googlemaps

### ISSUE THREAD

**Issue by Arcasss** [PokemonGoF/PokemonGo-Bot#2542]
### Actual Behavior
python pokecli.py --config configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 4, in <module>
    import googlemaps
ImportError: No module named googlemaps

### Other Information
OS: W10 bash
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here) 4182e93f9bfbe471d07b74e95c55cdfbacda127b
Python Version: (run 'python -V' and paste it here)
Python 2.7.10

**Comment by Norton50** [comment]
install requirements.txt

**Comment by Arcasss** [comment]
thanks
