### ISSUE TITLE
Running the bot unattended with nohup/screen?

### ISSUE THREAD

**Issue by jrjhealey** [PokemonGoF/PokemonGo-Bot#2543]
I realise the answer to this is probably just: go try it...

But I have a *nix server I'd be tempted to leave the bot running on so that my laptop isn't stuck running it.

Will the bot tolerate being called with `nohup` and having the output redirected? Or will it simply stop running if the session its closed?

**Comment by Chaemelion** [comment]
I use the bot within a named screen session on my home server and all works fine. You'll have to use screen's copy mode to scroll through the history, but that's the only issue I've experienced.

**Comment by jalliance** [comment]
I used it with nohup for a while, here is the code from my script. Not great but it works and low overhead. 
```python
#!/bin/sh
while true; do
 nohup python pokecli.py --config config.json > $!.txt > test.out 
done &
```

**Comment by switowski** [comment]
Works perfectly fine with tmux for me.

**Comment by kinvaris** [comment]
I use byobu works perfectly

**Comment by jrjhealey** [comment]
Yeah nohup worked fine. I think screen is probably the better bet for being able to hop in and out of it.
