### ISSUE TITLE
Authenication Error

### ISSUE THREAD

**Issue by srobayo222** [PokemonGoF/PokemonGo-Bot#2544]
Hi im having this issue

usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-p PASSWORD] [-l LOCATION] [-lc LOCATION_CACHE] [-m MODE]
                  [-w WALK] [-k GMAPKEY] [-ms MAX_STEPS]
                  [-it INITIAL_TRANSFER] [-d DEBUG] [-t TEST]
                  [-du DISTANCE_UNIT] [-if ITEM_FILTER] [-ev EVOLVE_ALL]
                  [-ec EVOLVE_CAPTURED]
pokecli.py: error: argument -a/--auth_service is required

http://imgur.com/a/6uun2

any help?

**Comment by kinvaris** [comment]
you have to add the command -cf config.json

**Comment by brantje** [comment]
Currently Niantic's API has changed, so the bot needs to be updated.

**Comment by brantje** [comment]
Read: https://github.com/PokemonGoF/PokemonGo-Bot/issues/2540
