### ISSUE TITLE
Bot just walking

### ISSUE THREAD

**Issue by Kozeo** [PokemonGoF/PokemonGo-Bot#2546]
### Expected Behavior

capture pokemon and use pokestops

### Actual Behavior

just walking
Here us the log:

> [2016-08-03 22:54:50] [x] PokemonGO Bot v1.0
> [2016-08-03 22:54:50] [x] Configuration initialized
> [2016-08-03 22:54:51] 
> [2016-08-03 22:54:51] [x] Address found: New York, Times Square
> [2016-08-03 22:54:51] [x] Position in-game set as: (40.7592686, -73.98412739999999, 0.0)
> [2016-08-03 22:54:51] 
> [2016-08-03 22:54:54] [#] Username: Kozeoh
> [2016-08-03 22:54:54] [#] Acccount Creation: 2016-07-11 21:47:26.260000
> [2016-08-03 22:54:55] [#] Bag Storage: 240/350
> [2016-08-03 22:54:55] [#] Pokemon Storage: 101/250
> [2016-08-03 22:54:55] [#] Stardust: 111094
> [2016-08-03 22:54:55] [#] Pokecoins: 0
> [2016-08-03 22:54:55] [#] PokeBalls: 120
> [2016-08-03 22:54:55] [#] GreatBalls: 68
> [2016-08-03 22:54:55] [#] UltraBalls: 29
> [2016-08-03 22:54:55] [#] -- Level: 21
> [2016-08-03 22:54:55] [#] -- Experience: 270545
> [2016-08-03 22:54:55] [#] -- Experience until next level: 64455
> [2016-08-03 22:54:55] [#] -- Pokemon Captured: 980
> [2016-08-03 22:54:55] [#] -- Pokestops Visited: 467
> [2016-08-03 22:54:55] [#]
> [2016-08-03 22:54:56] [x] Starting PokemonGo Bot....
> [2016-08-03 22:54:56] [#] Scanning area for objects (1 / 25)
> [2016-08-03 22:54:56] [#] Walking from (40.7592686, -73.98412739999999) to (40.7592686, -73.98412739999999) for approx. 0.00 seconds
> [#] (40.7592686, -73.98412739999999, 0)
> [#] Attempting to evolve all pokemons ...
> [2016-08-03 22:55:05] [#] Scanning area for objects (2 / 25)
> [2016-08-03 22:55:05] [#] Walking from (40.7592686, -73.98412739999999) to (40.761768599999996, -73.98412739999999) for approx. 28.00 seconds
> [2016-08-03 22:55:53] [#] Finished walking
> [#] (40.761768599999996, -73.98412739999999, 0)
> [2016-08-03 22:56:01] [#] Scanning area for objects (3 / 25)
> [2016-08-03 22:56:01] [#] Walking from (40.761768599999996, -73.98412739999999) to (40.761768599999996, -73.9816274) for approx. 22.00 seconds
> [2016-08-03 22:56:34] [#] Finished walking
> [#] (40.761768599999996, -73.9816274, 0)
> [2016-08-03 22:56:41] [#] Scanning area for objects (4 / 25)
> [2016-08-03 22:56:41] [#] Walking from (40.761768599999996, -73.9816274) to (40.7592686, -73.9816274) for approx. 28.00 seconds
> [2016-08-03 22:57:33] [#] Finished walking
> [#] (40.7592686, -73.9816274, 0)
> [2016-08-03 22:57:46] [#] Scanning area for objects (5 / 25)
> [2016-08-03 22:57:46] [#] Walking from (40.7592686, -73.9816274) to (40.7567686, -73.9816274) for approx. 28.00 seconds
> [2016-08-03 22:58:41] [#] Finished walking
> [#] (40.7567686, -73.9816274, 0)

### Steps to Reproduce

run the bot with python pokecli.py

### Other Information
OS: OSX 10.11.5
Git Commit: Not a git repository (or any of the parent directories): .git
Python Version: 2.7.12

**Comment by losnaj** [comment]
same here!

**Comment by BobbyWibowo** [comment]
Seems like Pokemon Go dev did something with their API. It's not only PokemonGo-Bot.
https://www.reddit.com/r/pokemongodev/comments/4w0jum/all_ptcgoogle_logins_failing_from_api/
So basically right now the bot doesn't know where to go because it can't fetch map data.

**Comment by Sterkoel** [comment]
Please read recent threads before opening a new one.
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2540
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2545

Niantic changed their API, the bot needs a fix.

**Comment by Kozeo** [comment]
Sorry, so should we just wait?

**Comment by BobbyWibowo** [comment]
@Kozeo What else is there to do? We'll just have to see if the dev can come up with anything to counteract this.

**Comment by SpencerCarstens** [comment]
Are you asking us what to do with your own time?

**Comment by Kozeo** [comment]
Well I meant something like, is it going to be fixed soon or not

**Comment by BobbyWibowo** [comment]
@Kozeo https://github.com/PokemonGoF/PokemonGo-Bot/issues/2540#issuecomment-237374185

**Comment by roamingwizard** [comment]
@SpencerCarstens No. He/She was using indirect language to politely ask if there was a fix being released; it's a fairly common among those who have manors. Stop Trolling.

**Comment by AndyBean** [comment]
*manners

Now that is trolling.

**Comment by jacobzlogar** [comment]
lol Expectations vs Reality.

**Comment by roamingwizard** [comment]
@AndyBean Doh! Large meat hook abominations and auto correct are not compatible apparently.

**Comment by softstar1990** [comment]
same here! any fix? Thx!

**Comment by yyz20002008** [comment]
Same here, and each step response so slow, does anyone know how to fix?
[21:16:30]
[21:16:31]  Starting PokemonGo Bot....
[21:16:32]  [x] Next egg incubates in 8.67 km
[21:16:32] Walking from (40.2802795, -76.6093077) to [40.2802795, -76.6093077] 0.00km
[21:16:34] Walking from (40.2802795, -76.6093077) to [40.2820795, -76.6093077] 0.20km
[21:19:04] Walking from (40.2820795, -76.6093077) to [40.2820795, -76.6075077] 0.15km
[21:20:35] Walking from (40.2820795, -76.6075077) to [40.2802795, -76.6075077] 0.20km

**Comment by xiaoxin628** [comment]
That's not about the Bot, it's about the API.

**Comment by d0t1q** [comment]
"04/08/2016 - 02:07 GMT+1 : It's becoming more evident that this is a non-trivial change, and will take much longer than planned to get reverse engineered again."

Might be a long wait for this one
