### ISSUE TITLE
Integration of CP evolution calculator?

### ISSUE THREAD

**Issue by tchit** [PokemonGoF/PokemonGo-Bot#2548]
### Expected Behavior
I wish we could see the CP after evolution for any Pokemon that can be evolved. I have Pokemons that are already evolved and very often I don't know if it's a good idea to evolve a new Pokemon because I am not sure it's CP after evolution will be high enough.
I would love to be able to see the informations added to the other informations like IV.

### Actual Behavior
Right now I can sort out my Pokemons by IV and it's pretty cool. But I don't know their CP after evolution and I need to go online to check this manually.

What do you think?

**Comment by MZorzy** [comment]
good. 
and maybe let bot to evolve only 'will-have-good-cp-after-evolution'
