### ISSUE TITLE
Is master working ??? Mine is just walking and walking

### ISSUE THREAD

**Issue by abs07** [PokemonGoF/PokemonGo-Bot#2550]
### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by mattlawer** [comment]
No. Niantic just changed their APIs and forced all users to switch to the last update. Old APIs are not working anymore.

**Comment by Gl00mY-ZeiZ** [comment]
Seems like Nautica dev-team did something with their API.

See here #2546
