### ISSUE TITLE
git pull???

### ISSUE THREAD

**Issue by suhdude19** [PokemonGoF/PokemonGo-Bot#2554]
### Actual Behavior
error

### Steps to Reproduce

![screen shot 2016-08-03 at 8 47 47 pm](https://cloud.githubusercontent.com/assets/20786466/17386760/aa38efa8-59bb-11e6-8062-d9adde2691aa.png)

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by Gobberwart** [comment]
This isn't an error with the bot. It's a problem with your git setup. Not sure how you "installed" the bot, but that folder name isn't correct if you did it using a git clone request (should just be "PokemonGo-Bot") so I suspect you need to go back to step 1 and start again, following the instructions exactly.

**Comment by DrBlackross** [comment]
run that from inside the main PokemonGo-Bot folder

**Comment by DrBlackross** [comment]
follow the mac sections 
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation

**Comment by INGCRENGIFO** [comment]
![error](https://cloud.githubusercontent.com/assets/12200313/17387714/d1887fc4-59bb-11e6-90ca-d2ff42b46e73.png)
I did a pull and gives me error

**Comment by Gobberwart** [comment]
There's no error there???

**Comment by INGCRENGIFO** [comment]
![image](https://cloud.githubusercontent.com/assets/12200313/17387954/f46ae372-59bd-11e6-9a5d-d7850dd6a4b7.png)
this @Gobberwart

**Comment by Gobberwart** [comment]
Ok, gotcha. You'll need to update your config.json file as the "EvolveAll" task no longer exists.

Your best bet is to take the new config.json.example and just plug in your details (username, password, api key etc), then save it as config.json as a few other things have changed as well.

**Comment by DrBlackross** [comment]
Yep, now your ready for the next update....

**Comment by iruy** [comment]
Always take a look at new configs before executing bot. Changes happen almost on daily basis
