### ISSUE TITLE
Can't find a pokestop in xxxm!

### ISSUE THREAD

**Issue by FoldSeven** [PokemonGoF/PokemonGo-Bot#2557]
i'm having a problem started this morning, it is written like "Can't find a pokestop within 10000m!" and it is keep retrying like drunk, somebody has the same issue? or it is just me? how about the other bot?

**Comment by JSchwerberg** [comment]
Please look through the issues.  The API is broken, all bots are failing.

**Comment by G3NES15** [comment]
All bots are offline until issues are resolved by their Devs. Please be patient.

**Comment by FoldSeven** [comment]
okay, thanks fellas
