### ISSUE TITLE
Don't work in Brazil

### ISSUE THREAD

**Issue by MrCarlosJr** [PokemonGoF/PokemonGo-Bot#2560]
### Actual Behavior
Don't work

### Steps to Reproduce
For test:
-l "Setor Universitario Goiania Brasil"
-l "74683410"
-l "Parque Vaca Brava Goiania Brasil"

### Other Information
OS: Fedora 24
Git Commit: 053e0a4213a9f8c01d356187aded35f5f08c5e39
Python Version: 2.7

**Comment by leovarmak** [comment]
@MrCarlosJr Maybe that place is on Geo Block ?

**Comment by PraeceptorXS** [comment]
As of now the Niantic API has changed so the bot is having issues. Give it a few hours and try again with a fresh install

**Comment by eggins** [comment]
Game hasnt launched in Brazil.....

**Comment by pokemule** [comment]
@eggins Indeed it has -> http://www.thewrap.com/pokemon-go-released-in-brazil-just-in-time-for-the-olympics/
