### ISSUE TITLE
About an error in running the "pokecli.py" 

### ISSUE THREAD

**Issue by qwezhangqi** [PokemonGoF/PokemonGo-Bot#2562]
When we run it, it should show the character going to walk and collect pokemons.

But when I run it, it shows as follows:
https://cloud.githubusercontent.com/assets/20830801/17390310/96a8e608-59d1-11e6-9d39-5e7d9257242c.png
You can open the link to see it says there is no request module.
Can you help me? Thank you!

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by PraeceptorXS** [comment]
Install the requirements.txt. Do pip install -r requirements.txt
