### ISSUE TITLE
Can't start bot

### ISSUE THREAD

**Issue by Budderpants** [PokemonGoF/PokemonGo-Bot#2566]
Can't start the bot through python pokecli.py or with docker. I've tried almost everything and it always says "ImportError: No module named googlemaps" or "ValueError: No JSON object could be decoded" even though i deleted, reinstalled, and reloaded everything. All the configs are correct, it says I have googlemaps already installed, and I don't know what to do.

**Comment by iamhaller** [comment]
Post you config file, remove your email and pass and other sensitive information. Or try an online JSON file validator.

**Comment by iruy** [comment]
There is no need to fix anything atm, read this https://github.com/PokemonGoF/PokemonGo-Bot/issues/2540
