### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by updatesvc** [PokemonGoF/PokemonGo-Bot#2567]
I am getting this error.
`C:\Users\home pc>python "C:\Users\home pc\Documents\GitHub\PokemonGo-Bot-master\pokecli.py"
Traceback (most recent call last):
  File "C:\Users\home pc\Documents\GitHub\PokemonGo-Bot-master\pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "C:\Users\home pc\Documents\GitHub\PokemonGo-Bot-master\pokemongo_bot\__init__.py", line 358
    except Exception, e:
                    ^
SyntaxError: invalid syntax`

**Comment by kinvaris** [comment]
Check this file `C:\Users\home pc\Documents\GitHub\PokemonGo-Bot-master\pokemongo_bot\__init__.py` on this line `358`. Apparently there is a syntax mistake.

**Comment by updatesvc** [comment]
Here is a code snippet i ma not sure what is wrong
` def _filter_ignored_pokemons(self, cell):
        process_ignore = False
        try:
            with open("./data/catch-ignore.yml", 'r') as y:
                ignores = yaml.load(y)['ignore']
                if len(ignores) > 0:
                    process_ignore = True
        except Exception, e:
            pass`

**Comment by updatesvc** [comment]
The line 358: `except Exception, e:`

**Comment by iruy** [comment]
Since variable `e` is not used, you can try both of following fix:
`except Exception:`
or
`except Exception as e:`

**Comment by rodang** [comment]
Try to change the line to: 
except Exception as e:

**Comment by cbogithub** [comment]
try use python 2 , python 3 Incompatible

**Comment by iruy** [comment]
There is no need to fix anything atm, read this https://github.com/PokemonGoF/PokemonGo-Bot/issues/2540

**Comment by brantje** [comment]
Read: https://github.com/PokemonGoF/PokemonGo-Bot/issues/2540
