### ISSUE TITLE
error pokecli

### ISSUE THREAD

**Issue by piensaenpixel** [PokemonGoF/PokemonGo-Bot#2569]
any idea?

`Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: cannot import name ServerSideRequestThrottlingException`

**Comment by iruy** [comment]
There is no need to fix anything atm, read this https://github.com/PokemonGoF/PokemonGo-Bot/issues/2540

**Comment by kimonniez** [comment]
pip install -r requirements.txt

**Comment by piensaenpixel** [comment]
thanks @kimonniez it's working now :)
