### ISSUE TITLE
Bot stops at: [next_egg_incubates]

### ISSUE THREAD

**Issue by Godlex** [PokemonGoF/PokemonGo-Bot#2571]
If I start the Bot it starts normally but then it then it shows me: "[next_egg_incubates] Next egg incubates in 4.03 km" and nothing more happens. 

Does anyone else having the same issue?

**Comment by Nerkyator** [comment]
Please check [#2540](https://github.com/PokemonGoF/PokemonGo-Bot/issues/2540)

**Comment by Bzzz666** [comment]
same issue
