### ISSUE TITLE
The application won't start

### ISSUE THREAD

**Issue by SpotRudloff** [PokemonGoF/PokemonGo-Bot#2574]
The app loads my profile data and the location I set, but it won't go any further. I enclose a screenshot.

<img width="487" alt="bez nazvu" src="https://cloud.githubusercontent.com/assets/332505/17400398/e0ab2ed4-5a47-11e6-9c90-a702d84448d7.png">

**Comment by Nerkyator** [comment]
please check #2540

**Comment by brantje** [comment]
Read: https://github.com/PokemonGoF/PokemonGo-Bot/issues/2540
