### ISSUE TITLE
Feature? Auto start-stop.

### ISSUE THREAD

**Issue by firzzen** [PokemonGoF/PokemonGo-Bot#2575]
Whilst the devs are busy working on RE-ing the updated API i thought i'd throw this in here as a question/discussion.

I've used the Bot before but haven't noticed any auto start-stop functions, maybe i'm just blind.

What i mean by that is you set a schedule for the bot to login @ 14:52 GMT, log out @ 22:11 GMT, or something like that, and it would do so every day (or every other day or whatever) along with the function of varying the login/logout times by +- 10 minutes for example.

Together with a varying walk speed, random stops etc it could make it more realistic therefore having smaller odds of getting banned.

Does something like this exist already? If not could something like this be added?

**Comment by antoineneff** [comment]
There is a sleep schedule task found in the code (`pokemongo_bot/cell_workers/sleep_schedule.py`), config look like this : 
```
"type": "SleepSchedule",
        "config": {
          "time": "12:00",
          "duration":"5:30",
          "time_random_offset": "00:30",
          "duration_random_offset": "00:30"
        }
```

**Comment by firzzen** [comment]
@antoineneff so in the config something like this?

   {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "SleepSchedule",
        "config": {
          "time": "23:47",
          "duration":"7:31",
          "time_random_offset": "00:15",
          "duration_random_offset": "00:15"
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 80 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 0 },
            "Hyper Potion":   { "keep" : 0 },
            "Revive":         { "keep" : 0 },
            "Razz Berry":     { "keep" : 50 }
          }
        }
      },

**Comment by antoineneff** [comment]
I never used it so I won't be able to help much but it seems to be the way. I took the config example from the file `sleep_schedule.py`.
