### ISSUE TITLE
Feature request? Inventory List

### ISSUE THREAD

**Issue by flopk** [PokemonGoF/PokemonGo-Bot#2576]
I can't seem to find this in any of the wiki. I know as part of the keep_best_cp/iv it sorts the caught Pokemon but is there a way to pull up a complete inventory of all your current pokemon to view their CP and IV in a big list sorted either by CP # IV or whatever? This would help me work out which Pokemon to power up/evolve.

Thanks

**Comment by omgcatbear** [comment]
In config.properties, set:

`export=CSV`

**Comment by antoineneff** [comment]
If you look at this : https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Google-Maps-API-(web-page)

You'll be able to see your bot walking on the map and you have multiple buttons to see your items and your pokemons. You can also sort them by IV or CP, it might help.

**Comment by flopk** [comment]
Thanks for your response Antoine. I have tried but can not get the map to work, I either get a blank map or a list of errors with the wrong username.json name. It is so frustrating.

**Comment by iruy** [comment]
Since PokeBot is not running, json files won't be up to date, but you can still see what was your last situation. Can you post the errors you got?

**Comment by cprior** [comment]
When you are inside the virtualenv (so after you did . ./bin/activate) this does still produce a current inventory in the file data.json:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json
from pgoapi import PGoApi

def main():
    api = PGoApi()
    api.set_position(LAT, LON, 0.0)
    api.login('google OR ptc', 'USER', 'PASS')

    req = api.create_request()
    req.get_player()
    req.get_inventory()
    response = req.call()

    with open('data.json', 'w') as fp:
        json.dump(response, fp)

if __name__ == '__main__':
    main()

```

Save this in a file pgbapi.py, replace LAT, LON, google|ptc, USER, PASS and run it with:

```./pgbapi.py && cat data.json |jq '.responses.GET_INVENTORY.inventory_delta.inventory_items[] | .inventory_item_data | [ {pokemon: [ .pokemon_data.pokemon_id , .pokemon_data.cp]}, { pokedex: [.pokedex_entry.pokemon_id, .pokedex_entry.times_captured]}, {item: [.item.item_id, .item.count]} ]' -c```

https://stedolan.github.io/jq/manual/ explains how to use jq, a convenient way to slice JSON.

**Comment by nealqu** [comment]
Here's what I did on mine so I don't need a list. On the config.json

"release": {
"any": {"release_below_cp": 700, "release_below_iv": 0.80, "logic": "and"},

I edited the part so that it will convert to candy any pokemon that is at 700 cp or below that has 0.80 IV. You can adjust the CP value or iv accordingly.

The pokemons that are left on my inventory are the ones that I can upgrade.
