### ISSUE TITLE
Pokebot not working since yesterday

### ISSUE THREAD

**Issue by rahulbanerjee1992** [PokemonGoF/PokemonGo-Bot#2581]
### Expected Behavior
Was working fine till yesterday around 9:30pm. 
### Actual Behavior
![capture](https://cloud.githubusercontent.com/assets/20841637/17406507/470464b4-5a81-11e6-9ef2-94e4d3360fb8.PNG)

### Steps to Reproduce
Tried different profiles. Same messages in loop. Please help.

### Other Information
OS: Windows10

**Comment by userwau** [comment]
Guys, please read the forums before posting new issues. this has been a known problem since Niantic did changes to the API.

**Comment by rahulbanerjee1992** [comment]
I am sorry.. I couldnt find any relevant threads. Does this mean that we have to wait for a new version of Pokebot? And Pokebot is unusable till then?

**Comment by randypfohl** [comment]
please close, this issue has too many posts already.

**Comment by psyrax** [comment]
> I am sorry.. I couldnt find any relevant threads. Does this mean that we have to wait for a new version of Pokebot? And Pokebot is unusable till then?

yes

**Comment by rohimkudus** [comment]
@rahulbanerjee1992  yes just wait update will soon.

> 

I am sorry.. I couldnt find any relevant threads. Does this mean that we have to wait for a new version of Pokebot? And Pokebot is unusable till then?

**Comment by iruy** [comment]
Read here for more info https://github.com/PokemonGoF/PokemonGo-Bot/issues/2540

**Comment by rahulbanerjee1992** [comment]
Thank you so much for your prompt replies. I will close this thread now, and wait for an update. :)
