### ISSUE TITLE
Many config files?

### ISSUE THREAD

**Issue by LightAMV** [PokemonGoF/PokemonGo-Bot#2588]
I have little knowledge in scripting. I did read the config files section.

Am I supposed to only have 1 config.json file? or could I do

```
config.json
config.json.pokemon
config.json.map
etc.
```
Will close asap.

**Comment by LightAMV** [comment]
Also, if you cannot have multiple config files, can I just forge them all into 1 config file?

**Comment by mjmadsen** [comment]
The only necessary one to setup is config.json.

The others are for different features.

**Comment by LightAMV** [comment]
@mjmadsen
Mkay thanks
