### ISSUE TITLE
Problem Loading Bot

### ISSUE THREAD

**Issue by Crimsoncycl0ne** [PokemonGoF/PokemonGo-Bot#2589]
Hello! This is my first time doing stuff like this so please bear with me if I sound confusing. 
So basically I tried doing the pokemon go bot from this video: https://www.youtube.com/watch?v=rz7r181EsCk
I followed exactly everything but I have an error on the last step when entering the" python pokecli.py" where it reads
(PokemonGo-Bot) MyMac-iMac:PokemonGo-Bot (MyName)$ python pokecli.py

Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 197, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
(PokemonGo-Bot) MyMac-iMac:PokemonGo-Bot (MyName)$ 
(PokemonGo-Bot) MyMac-iMac:PokemonGo-Bot (MyName)$ 
(PokemonGo-Bot) MyMac-iMac:PokemonGo-Bot (MyName)$ 
Can anyone please help me?

**Comment by Crimsoncycl0ne** [comment]
I have also read #2540 but I don't think that covers my error

**Comment by mjmadsen** [comment]
Looks like it couldn't find a config.json. If you're in master branch is should be filled out and in your bot's root directory. If dev is should be in /configs/config.json

**Comment by Crimsoncycl0ne** [comment]
I do have a config .json file though. What do you mean by bot's root directory or if dev? Sorry for my noobness

**Comment by mjmadsen** [comment]
If you're using the master branch the config goes in the bot's root directory.

If you're using the dev branch the config goes in your bots /configs directory.

Did you rename it from config.json.example to config.json? Apart from those two, I'm not sure what the issue would be.

**Comment by Crimsoncycl0ne** [comment]
I did rename the file. How do I check which branch I am using and how do I reach the bot's directory?

**Comment by iruy** [comment]
Probably there is some problem with your JSON. Check [Wiki](https://github.com/PokemonGoF/PokemonGo-Bot/wiki/No-JSON-object-could-be-decoded-or-decoder.py-error)

**Comment by Crimsoncycl0ne** [comment]
{
	"auth_service": "ptc",
	"username": “(username) ",
	"password": “(password)”,
	"location": “New York,
	Central Park”,
	"gmapkey": "AIzaSyDIJQMPT4WZ2HkizryGQh-LizcxUnIQDZkY",
	"max_steps": 5,
	"mode": "all",
	"walk": 4.16,
	"debug": false,
	"test": false,
	"initial_transfer": 0,
	"location_cache": true,
	"distance_unit": "km",
	"item_filter": "101,102,103,104",
	"evolve_all": "NONE"
}  
http://imgur.com/a/wtOVA
So how do I correct it?

**Comment by mjmadsen** [comment]
I don't imagine this is it, but is there a space behind your username?

Location is also long/lat. Central Park is around "40.7829, 73.9654".

**Comment by brantje** [comment]
No JSON object could be decoded mean that your config file is malformed.
Run it through a validator (like this one: http://jsonlint.com/).

**Comment by tstumm** [comment]
Since this is no issue with the bot itself, I'll close this issue. You cant still comment on fixing the malformed syntax in the authors config.
