### ISSUE TITLE
importError: no module named request

### ISSUE THREAD

**Issue by ryannguyen100** [PokemonGoF/PokemonGo-Bot#2592]
![untitled](https://cloud.githubusercontent.com/assets/20844588/17412216/971e334a-5a49-11e6-8ea7-ee42dd68f76a.png)

i get stack over 
please help me out
thanks

**Comment by handuos** [comment]
Try `$ source bin/activate` and run the script again?

**Comment by ryannguyen100** [comment]
thx

**Comment by klvs** [comment]
@ryannguyen100 please close this
