### ISSUE TITLE
TypeError: exceptions must be old-style classes or derived from BaseException, not str

### ISSUE THREAD

**Issue by TheSavior** [PokemonGoF/PokemonGo-Bot#2595]
https://app.getsentry.com/pokemongof/pokemongo-bot/issues/147509034/

```
TypeError: exceptions must be old-style classes or derived from BaseException, not str
  File "pokecli.py", line 490, in <module>
    main()
  File "pokecli.py", line 122, in main
    raise "Google Maps API key over requests limit."

TypeError: exceptions must be old-style classes or derived from BaseException, not str
```

**Comment by mjmadsen** [comment]
"Google Maps API key over requests limit." The Google Maps API free keys have limited use (per month?).

Though, the exception wasn't implemented correctly in the last dev commit.

**Comment by TheSavior** [comment]
Yeah, it needs to be an `Exception()`. Happy to accept a PR. :)
