### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by TheSavior** [PokemonGoF/PokemonGo-Bot#2596]
Looks like when the bot is starting up, these fields aren't populated so we get `None` back. We should return 0 if either of these are None

https://app.getsentry.com/pokemongof/pokemongo-bot/issues/147416492/

```
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
  File "pokecli.py", line 490, in <module>
    main()
  File "pokecli.py", line 95, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    logger.info('Total XP Earned: {}  Average: {:.2f}/h'.format(metrics.xp_earned(), metrics.xp_per_hour()))
  File "pokemongo_bot/metrics.py", line 28, in xp_earned
    return self.xp['latest'] - self.xp['start']

TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

**Comment by fence1247** [comment]
I am having this issue. How to we alter the pokecly.py files so that I no longer get this error?

**Comment by TheSavior** [comment]
This is still a problem.

**Comment by PokemonGoF-IssueMover** [comment]
This issue was moved to PokemonGoF/PokemonGo-Bot-Issues#3

**Comment by Moonlight-Angel** [comment]
Looks like this happens on first login with a fresh new account.
`UpdateLiveStats` tries to get the XP to display the stats and fails at it.
Temporary fix I found is :
* Disabling the worker
* Running the bot once, let it catch a Pokemon, spin a Pokestop, do stuff
* Re-enable the worker
* Watch it work 👍

**Comment by keugnu** [comment]
Can we make this fix?

**Comment by MasterCATZ** [comment]
yes this is what needs to be done 

but it's not a fix 

account just needs to be level 1 before livestats can be enabled

**Comment by Moonlight-Angel** [comment]
@MasterCATZ Yes, it's not a fix. If being level 1 is enough to make it work, we could add a level check in `update_live_stats._should_display` to avoid fetching stats when we're not level 1.

**Comment by keugnu** [comment]
#4088
