### ISSUE TITLE
ImportError: No Module named pgoapi

### ISSUE THREAD

**Issue by ryannguyen100** [PokemonGoF/PokemonGo-Bot#2602]
![untitled](https://cloud.githubusercontent.com/assets/20844588/17414768/c61a04f2-5a54-11e6-981a-c95acf26cd8f.png)
anyone can help this pls
thanks so much

**Comment by GitPupper** [comment]
The bot is currently not woking. To see progress go to the announcement (second post) on reddit.com/r/pokemongodev

**Comment by mjmadsen** [comment]
You're also missing requirements from requirements.txt

**Comment by ryannguyen100** [comment]
thanks guys

**Comment by ishanshukla97** [comment]
Mine isn't showing this error. It's iterating over "found 1 pokestops near \nStarting show \nCharging
I think its not working.
