### ISSUE TITLE
Pokecli.py Error

### ISSUE THREAD

**Issue by pokemonJB** [PokemonGoF/PokemonGo-Bot#2603]
I'm now getting this error message, not sure what to do.
 
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-p PASSWORD] [-l LOCATION] [-lc LOCATION_CACHE] [-m MODE]
                  [-w WALK] [-k GMAPKEY] [-ms MAX_STEPS]
                  [-it INITIAL_TRANSFER] [-d DEBUG] [-t TEST]
                  [-du DISTANCE_UNIT] [-if ITEM_FILTER] [-ev EVOLVE_ALL]
                  [-ec EVOLVE_CAPTURED]
pokecli.py: error: argument -a/--auth_service is required
 
 Any help would be appreciated, thank you.

**Comment by Abraxas000** [comment]
You need to run `pip2 install -r requirements.txt`

**Comment by Abraxas000** [comment]
Keep in mind that the bot isn't working right now though: https://github.com/PokemonGoF/PokemonGo-Bot/issues/2540

**Comment by pokemonJB** [comment]
Well that is some pretty pertinent information.

**Comment by LightAMV** [comment]
It is true that you need to install, but you also need to configure the config files.
If you don't know how to do that, just do this instead:
python pokecli.py -a (google/ptc) -u (username) -p (password) -l (location)

**Comment by brantje** [comment]
You have to define the auth service used. Either in config.json or with the -a flag, as shown in the error.
