### ISSUE TITLE
NOOB QUESTION aven't update from a week ...

### ISSUE THREAD

**Issue by mehdi-S** [PokemonGoF/PokemonGo-Bot#2607]
hey there, i git pull this night, wasn't here from almost 2 weeks now
i ve done the classic, git pull > submodule update > pip install --update and config the json
the bot is working flawlessly but.. it do nothing else than recycling object, checking for my egg and walk.. it walk endlessly without catching or spinning anything, i basically copy paste the default config.json and done no tweaking aside from release pokemon and object setting
even the web map show nothing, not stops, no pokemon

thanks for passing by and helping me and sorry for being noobish

**Comment by Yakusari** [comment]
Please read first and only post if there is no info.

Info:
[#2540](https://github.com/PokemonGoF/PokemonGo-Bot/issues/2540)
https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/
