### ISSUE TITLE
Bot don't work in Brazil

### ISSUE THREAD

**Issue by MrCarlosJr** [PokemonGoF/PokemonGo-Bot#2608]
Locations for test

"74683410"
"Setor universitario goiania brasil"
"Parque  Vaca brava goiania brasil"

**Comment by Calcyfer** [comment]
Try this location instead : `-16.675447,-49.2405828`

**Comment by MrCarlosJr** [comment]
just walk no catch pokemon or visit pokestop

**Comment by Calcyfer** [comment]
Niantic changed some things, bots aren't working at the moment.

**Comment by MrCarlosJr** [comment]
@Calcyfer thanks
