### ISSUE TITLE
[Suggestion] Shut down "Issues" Section until Bot is Fixed

### ISSUE THREAD

**Issue by Whosdaman** [PokemonGoF/PokemonGo-Bot#2610]
If/when that happens...we don't know if it'll be possible with this new API

**Comment by userwau** [comment]
I second this suggestion.

**Comment by brantje** [comment]
Yea, but once everything works again, new issue's will arise, so then it's trivial to have a issue tracking system. For now i'll keep an eye on the issue's. And will close the duplicates.

**Comment by gokaygurcan** [comment]
Maybe it'd be nice to label them. Something like *Unknown6* maybe, idk.

**Comment by nivong** [comment]
you cant shut down the issue section on github for as far as I know ;)

**Comment by gokaygurcan** [comment]
@nivong You can. Just go to the Settings tab and find Features section. You can enable/disable issues as well as wiki in that section.

**Comment by TheSegfault** [comment]
Some issues remains issues and need to be fix, the API change is not the only issue, don't shutdown ^^

**Comment by Whosdaman** [comment]
There are no new issues though. You can't even run the bot. Having the issue section open does not but allow people to keep adding more issues about the bot not working properly
