### ISSUE TITLE
[Suggestion] How to fix people from using this as a forum.

### ISSUE THREAD

**Issue by zunox** [PokemonGoF/PokemonGo-Bot#2616]
I been on reddit for some time and here reading articles and progress. This section has been miss used quite a bit. This is meant for issues with the program and not so much talking. A while back i purchased a domain. Over the past week i have been working to improve it. I added a forum.  Would the staff want to make their own thread or section so people can talk and not open up issues when its just general chat?

Anyways if interested everything is fresh. http://pokemongohelp.net 

Let me know if its something you guys would be interested in.

Cheers!

**Comment by RedViper9** [comment]
To add to @zunox, there are already reddit, slack, and discord threads up that are constantly populated. As such, perhaps we can have someone moderate the issues board and simply close out non-issues?

**Comment by TheSegfault** [comment]
Slack is supposed to be it !

**Comment by brantje** [comment]
We have slack, no forums needed.
