### ISSUE TITLE
 There pokestops around.

### ISSUE THREAD

**Issue by piai46** [PokemonGoF/PokemonGo-Bot#2619]
Hello , I do not speak English fluently and I'm using google translator, if any word or phrase you are without feeling , I'm sorry .
I was using bot in earlier versions and it worked without problem, after I updated to the latest version he started giving the following error:
" [ 23:21:48 ] We cant find any PokeStops in the range of 10000m !
[ 23:21:48 ] We cant find any PokeStops , Which are unused ! Probably Server unstable , or you visted them all . Retrying .. "
So I wonder if any of you know how to solve this error , thank you in advance , I await response .

PS : This is on all accounts .
PS2 : also occurs in all coordinates.

:)

**Comment by saxenanihal95** [comment]
right now no bots are working developers are working on it

**Comment by samuelfernando13** [comment]
developers are working on it, just relax

**Comment by brantje** [comment]
Just thead the fcking read me. Issue 7889675 about this.
