### ISSUE TITLE
Log in successful but only walk from position to position, no other task be conducted

### ISSUE THREAD

**Issue by guagua36** [PokemonGoF/PokemonGo-Bot#2626]
### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by brantje** [comment]
API is broken, it's listed in the issues and in the readme. Closing

**Comment by my2ndLanguage** [comment]
they're getting close though 😄
