### ISSUE TITLE
 Help me please

### ISSUE THREAD

**Issue by piai46** [PokemonGoF/PokemonGo-Bot#2629]
Hello everyone, I do not speak English fluently and am currently with a half obvious problem that perhaps do not know. The problem is this , I downloaded the latest version of the bot a few minutes and I do not know how I do it to start , someone could help me ? Thank you in advance , hugs !

**Comment by JohnnyOmm** [comment]
doesnt woerk yet wait for update

**Comment by nivong** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2780
