### ISSUE TITLE
Can we get the new API implemented from keyphact/pgoapi

### ISSUE THREAD

**Issue by my2ndLanguage** [PokemonGoF/PokemonGo-Bot#2630]
### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by Ph4i1ur3** [comment]
I would imagine it's incoming based off the main core of coders here overlaps a little bit with those who worked tirelessly to break open the API. Amazing job too, I can't imagine the countless hours spent on it

**Comment by boriss579** [comment]
No we can't...
come one man... just be patient.

**Comment by my2ndLanguage** [comment]
@Ph4i1ur3 It was exhausting just watching them work. trying amazing work no doubt. Sorry if i came off as impatient. That wasn't the intent of this post, it was just about informing it has been released and also asking if it was feasible with without rewriting the entire thing.

**Comment by nburn42** [comment]
There is a branch open where this is actively being worked on.
Don't nag them about doing the thing they are currently doing.

https://github.com/PokemonGoF/PokemonGo-Bot/commits/upgrade_to_the_new_api

**Comment by k4n30** [comment]
@my2ndLanguage can you close this now please?
