### ISSUE TITLE
how to use it ?

### ISSUE THREAD

**Issue by pawpsicle** [PokemonGoF/PokemonGo-Bot#2631]
I newbie in bot, and i need help, how to use it ? thanks

**Comment by Ph4i1ur3** [comment]
Wait for update

**Comment by pawpsicle** [comment]
You mean this is not new update ? i think this is a new update

**Comment by PraeceptorXS** [comment]
Shouldn't be long now. They finished reverse engineering the API.

**Comment by nivong** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2780
