### ISSUE TITLE
Errors/Warnings on running install.sh

### ISSUE THREAD

**Issue by pranavperfect** [PokemonGoF/PokemonGo-Bot#2632]
### Expected Behavior
The requirements.txt links to old pgoapi link.

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by pranavperfect** [comment]
Getting this error when i run the bot.

Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

If i comment that line, it throws error for next line and then next line and then next line.

**Comment by SGColdSun** [comment]
You wait until its released. While the api has been dealt with, the bot still needs to make a few more changes.

**Comment by Happyrain67** [comment]
Ok thanx ;)

**Comment by pranavperfect** [comment]
warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
