### ISSUE TITLE
More Human Like to avoid a Ban

### ISSUE THREAD

**Issue by rahmanash777** [PokemonGoF/PokemonGo-Bot#2635]
I saw a comment on reddit that Niantic  should know the difference between a normal and an MITM apps . I also don't know how Niantic could find it out as there was no other information regarding that in the thread. But  i think it is important to understand and solve this before releasing the bot after upgrading to the new api

Ref Link :  https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/d65hrv5 
I  c/p the comment from the thread below

"GMT +1, 18:30 - We would like to repeat that the API-cracking community does not support bots. We are here to crack the API, thats it. That said we would like to confirm that Niantic can detect any MITM apps, these are apps that somehow modify data sent to the server. For example an app that ensures a perfect pokeballthrow. If you used an app like that Niantic could know.
We do not know whether you'll get banned for using such an app, we merely confirmed that Niantic could (theoretically) detect it. And it is not our concern, our concern is cracking the API.?"

**Comment by fari-99** [comment]
what?? haha. give reference, please.

**Comment by Happyrain67** [comment]
It is true that the robot is not discreet
Maybe a random pokeball success rate and an altitude ?
And If we put their knees server , they will investigate.

(sorry for my english)

**Comment by fari-99** [comment]
well, when i check the code (i dont know you check it) but there is algorithm for that like this.
`reticle_size_parameter = normalized_reticle_size(self.config.catch_randomize_reticle_factor)
spin_modifier_parameter = spin_modifier(self.config.catch_randomize_spin_factor)`

but when I play the bot, most the time I get 210 EXP, means (100 EXP catch, 100EXP excellent, 10 EXP curve CMIIW). but sometimes I only get 110EXP (100 EXP catch and 10 EXP curve).

about Pokeball success rate, if you use greater Pokeball or razzberry, the success rate is raising. it depends on the response the server gives you know.*

*example: when there is Pokemon, and you use Greate Ball and razz berry, and then you throw the ball and get an excelent catch, you CAN still get "the Pokemon broke free".

**Comment by yoot55** [comment]
Getting any sort of aim bonus will probably easy to flag you as a bot, considering its not possible to do so on the platforms (Niantic has confirmed it's a 'bug').

**Comment by kwanglee** [comment]
add_config(
        parser,
        load,
        long_flag="--catch_randomize_reticle_factor",
        help="Randomize factor for pokeball throwing accuracy (DEFAULT 1.0 means no randomize: always 'Excellent' throw. 0.0 randomizes between normal and 'Excellent' throw)",
        type=float,
        default=1.0
    )
    add_config(
        parser,
        load,
        long_flag="--catch_randomize_spin_factor",
        help="Randomize factor for pokeball curve throwing (DEFAULT 1.0 means no randomize: always perfect 'Super Spin' curve ball. 0.0 randomizes between normal and 'Super Spin' curve ball)",
        type=float,
        default=1.0

**Comment by zbyte64** [comment]
Altitude issue: #2762

**Comment by GitPupper** [comment]
We're aware of this, thanks for your input 👍
