### ISSUE TITLE
failed bot start? Help?!

### ISSUE THREAD

**Issue by nzflex** [PokemonGoF/PokemonGo-Bot#2637]
OSX issue starting bot I get the following error.

New python executable in /Users/flex/PokemonGo-Bot/bin/python
Installing setuptools, pip, wheel...done.
(PokemonGo-Bot) macbook-pro:pokemongo-bot flex$ python pokecli.py -cf ./configs/config.json
2016-08-07 14:15:42,588 [ cli] [INFO] PokemonGO Bot v1.0
Traceback (most recent call last):
File "pokecli.py", line 493, in 
main()
File "pokecli.py", line 126, in main
if bot:
UnboundLocalError: local variable 'bot' referenced before assignment

**Comment by my2ndLanguage** [comment]
Same here

**Comment by Happyrain67** [comment]
Wait and see !
a bot commit is comming !

**Comment by rohimkudus** [comment]
encrypt.so?

**Comment by DennyHoang** [comment]
I had similar error, make sure you config file is correct. Copy and paste it online on a json validator to make sure there are no errors. I had an extra comma in my file.

**Comment by nivong** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2780
