### ISSUE TITLE
showing error

### ISSUE THREAD

**Issue by adamtong1110** [PokemonGoF/PokemonGo-Bot#2638]
Cannot use it? any help?

C:\poke\PokemonGo-Bot-new>python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: cannot import name ServerSideRequestThrottlingException

**Comment by jolivier** [comment]
git clone --recursive  https://github.com/PokemonGoF/PokemonGo-Bot

**Comment by FrenkDenk** [comment]
Same issue here, suggested solution bij jolivier did not work..

**Comment by jolivier** [comment]
$ git clone --recursive -b master https://github.com/PokemonGoF/PokemonGo-Bot  
$ cd PokemonGo-Bot  
$ virtualenv .  
$ source bin/activate  
$ pip install -r requirements.txt

$ git checkout upgrade_to_the_new_api

and now ?

**Comment by adamtong1110** [comment]
i install it in Window 10, and virtualenv . command is not working. (i am newbie)

C:\poke\PokemonGo-Bot>virtualenv .
'virtualenv' is not recognized as an internal or external command,
operable program or batch file.

**Comment by FrenkDenk** [comment]
This is what I get after the git clone command

MacBook:~ username$ git clone --recursive -b master https://github.com/PokemonGoF/PokemonGo-Bot
fatal: destination path 'PokemonGo-Bot' already exists and is not an empty directory.

**Comment by andriiaveiro** [comment]
i have same issue

i run pip install -r requirements.txt and i get error

pip install -r requirements.txt

> Command "/root/PokemonGo-Bot/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-yGFilg/xxhash/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-OAh8MQ-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/PokemonGo-Bot/include/si

**Comment by adamtong1110** [comment]
after switch to upgrade_to_the_new_api,

C:\poke\PokemonGo-Bot>git checkout upgrade_to_the_new_api
Branch upgrade_to_the_new_api set up to track remote branch upgrade_to_the_new_api from origin.
Switched to a new branch 'upgrade_to_the_new_api'

C:\poke\PokemonGo-Bot>python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "c:\poke\pokemongo-bot\src\pgoapi\pgoapi\__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "c:\poke\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "c:\poke\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 46, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "c:\poke\pokemongo-bot\src\pgoapi\pgoapi\utilities.py", line 30, in <module>
    import xxhash
ImportError: No module named xxhash

**Comment by adamtong1110** [comment]
i also run pip install -r requirements.txt and i get error


`Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\chunwa~1\\appdata\\local\\temp\\pip-build-dpcblg\\xxhash\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\chunwa~1\appdata\local\temp\pip-nvuaih-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\chunwa~1\appdata\local\temp\pip-build-dpcblg\xxhash\`

**Comment by nowayrlz** [comment]
same here

**Comment by m-a-g-o** [comment]
I have the same error on win7:
Traceback (most recent call last):
  File "C:\git\version-control\newapipkmgo\PokemonGo-Bot\pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: cannot import name ServerSideRequestThrottlingException

Someone know how to solve this error? (I tried to remove the ServerSideRequestThrottlingException but then I got other import problems in other files...)

**Comment by nivong** [comment]
./install.sh will fix it

**Comment by m-a-g-o** [comment]
We are on windows but install.sh just do the commands reported in the Installation Wiki so it doesn't fix anything :(

**Comment by RedViper9** [comment]
@m-a-g-o try this from the PokemonGo-Bot folder
```
git fetch --all
git reset --hard origin master
```
then do `pip install -r requirements.txt`

**Comment by nivong** [comment]
Use docker windows isn't supported and will never be.
