### ISSUE TITLE
[Ubuntu 16.04] Already put encrypt.so but error not found.

### ISSUE THREAD

**Issue by earthchie** [PokemonGoF/PokemonGo-Bot#2645]
I already put encrypt.so compiled for linux x64 in the project folder alongside with pokecli.py but still got errors

![image](https://cloud.githubusercontent.com/assets/7013039/17460469/4a931734-5c92-11e6-90ba-476968b6f657.png)

**Comment by DragoonZ** [comment]
where did you get the encrypt.so?

**Comment by MarianoCordoba** [comment]
Same for me. I downloaded `encrypt.so` from https://slack-files.com/T1U6G9ZEW-F1YV50RGQ-cc979942b7

**Comment by earthchie** [comment]
@DragoonZ same as @MarianoCordoba. from pinned slac item

**Comment by DragoonZ** [comment]
I think you have to compile it by yourself, do you know where to find encrypt.c?

**Comment by Happyrain67** [comment]
Same for me.
Where to find it ?

**Comment by DragoonZ** [comment]
got it from here

http://pgoapi.com/

**Comment by earthchie** [comment]
.__. have no idea how to compile it

**Comment by andriiaveiro** [comment]
how to compile pgoencrypt.tar.gz?

**Comment by Happyrain67** [comment]
@eatchie : make

**Comment by danielhampton** [comment]
Install gcc, and then run "sudo make" in the src directory

**Comment by Happyrain67** [comment]
but i have download & compile it... but not work !

**Comment by danielhampton** [comment]
I'm getting when try run " Exception while downloading map: Odd-length string" @Happyrain67 

You?

**Comment by earthchie** [comment]
ok compiled. but still not work. same error

**Comment by louisgv** [comment]
Shouldn't do `sudo make`. `make` should be sufficent.

@Happyrain67 Pull this fermuch's master and use it until his PR ( #2643 ) is approved.

https://github.com/fermuch/PokemonGo-Bot

**Comment by LHagood** [comment]
If you downloaded encrypt.so from one of the links in these comments, verify that it's actually executable with "ldd encrypt.so".  I discovered I had a bad file this way, and once I got the correct file, everything started working.

**Comment by earthchie** [comment]
@LHagood 

![image](https://cloud.githubusercontent.com/assets/7013039/17460643/4ea9d2ec-5c9a-11e6-9af7-f85f527cd0f0.png)

**Comment by Happyrain67** [comment]
@louisgv : yeah i'm in Root ;) Thank you for this link, i see & try it !

I have same "ldd" of @earthchie ..  ;)

**Comment by jryd** [comment]
@LHagood I get `not a dynamic executable`. What link did you use to pull in `encrypt.so`?

**Comment by LHagood** [comment]
I got the link from the slack discussion.  There are several links to various versions of the file for different OSs

**Comment by LHagood** [comment]
Try this link:  https://files.slack.com/files-pri/T1U6G9ZEW-F1YVDQB39/download/encrypt.so  I think this is the one that worked for me Ubuntu 64bit

**Comment by jryd** [comment]
@LHagood doesn't seem to work for me still. I will spin up an Ubuntu machine and see if that helps.

**Comment by DragoonZ** [comment]
in pokemongo_bot/__init__.py

change self.api.activate_signature("encrypt.so") to
self.api.activate_signature("./encrypt.so")

**Comment by lukeyanchen** [comment]
thank you all!

**Comment by simonsmh** [comment]
same here

**Comment by pranavperfect** [comment]
Compiled the files. Renamed libencrypt.so to encrypt.so

Kept it in home directory of bot. Got the following error.

Traceback (most recent call last):
File "pokecli.py", line 493, in 
main()
File "pokecli.py", line 127, in main
report_summary(bot)
File "pokecli.py", line 136, in report_summary
metrics.capture_stats()
File "/mnt/c/Users/prana/Desktop/Bot/Updated/pokemongo_bot/metrics.py", line 76, in capture_stats
response_dict = request.call()
File "/mnt/c/Users/prana/Desktop/Bot/Updated/pokemongo_bot/api_wrapper.py", line 106, in call
result = self.call()
File "/mnt/c/Users/prana/Desktop/Bot/Updated/pokemongo_bot/api_wrapper.py", line 63, in call
return PGoApiRequest.call(self)
File "/mnt/c/Users/prana/Desktop/Bot/Updated/src/pgoapi/pgoapi/pgoapi.py", line 209, in call
request.activate_signature(lib_path)
File "/mnt/c/Users/prana/Desktop/Bot/Updated/src/pgoapi/pgoapi/rpc_api.py", line 82, in activate_signature
ctypes.cdll.LoadLibrary(lib_path)
File "/usr/lib/python2.7/ctypes/__init.py", line 443, in LoadLibrary
return self.dlltype(name)
File "/usr/lib/python2.7/ctypes/__init_.py", line 365, in init
self._handle = _dlopen(self._name, mode)
OSError: encrypt.so: cannot open shared object file: No such file or directory

**Comment by Happyrain67** [comment]
Oh my god ! It's Working !!

@louisgv : Fermuch's master work !
@DragoonZ : Switch this string work !

For encrypt.so i have compile source file of pgoapi.com

But... Where is the coloring in the console ?? =D =D =D
it's soo evil =)

**Comment by andriiaveiro** [comment]
thx its working for me :)

**Comment by snesevermore** [comment]
Thanks, all. Got it working.

To get the program to load the encrypt.so, either use [fermuch's build](https://github.com/fermuch/PokemonGo-Bot) or manually change the line in pokemongo_bot/__init__.py as follows:

self.api.activate_signature("encrypt.so")
to
self.api.activate_signature("./encrypt.so")

To install encrypt file (Linux version):
1. Visit the [Official API site ](http://pgoapi.com/)to pull the tarball
2. Extract tarball (tar -xf <filename>)
3. Enter directory <filename>/src
4. Run 'make' (requires gcc and make)
5. Copy libencrypt.so to target directory
6. Rename libencrypt.so as encrypt.so
7. Run the bot as normal

Appears to be working on Ubuntu 16.04. Spinning pokestops, catching pokemon, the works.

**Comment by Derfirm** [comment]
change `self.api.activate_signature("encrypt.so") ` =>
`self.api.activate_signature(os.path.abspath("encrypt.so"))`
work for me
os: ubuntu 16.04
