### ISSUE TITLE
python can't find config.json

### ISSUE THREAD

**Issue by thundertoast** [PokemonGoF/PokemonGo-Bot#2647]
Hi there, completely new to this stuff.

When I try to run the pokecli.py with python, I get an error stating "There's no ./configs/config.json file" even though I have a config.json file in the configs folder. Any help would be appreciated.

**Comment by leadboots5** [comment]
you likely don't have it in .json format.

on Mac  - right click get info and see if it still has something on the end to remove. On PC Save As and choose all files and make sure its .json

**Comment by thundertoast** [comment]
OK thank you!

**Comment by thundertoast** [comment]
I'm on Mac but it says under name and extension "config.json" and when I hide the extension it just becomes "config"

**Comment by pablossp** [comment]
Check that the path is actually correct, if you're running it on the main project directory it should be "config/config.json". 

By running 
`python pokecli.py`
It takes the configs/config.json file as the default configuration.

If you are struggling with this, you could run
`python pokecli.py -cf "p:/ath/to/your/file.json"`
This way you can use a custom path and filename :)
