### ISSUE TITLE
TypeError: __init__() takes exactly 6 arguments (5 given)

### ISSUE THREAD

**Issue by stumpyb** [PokemonGoF/PokemonGo-Bot#2648]
Get this error after starting bot

> 2016-08-06 23:34:22,192 [       cli] [INFO] PokemonGO Bot v1.0
> 2016-08-06 23:34:22,194 [       cli] [INFO] No config argument specified, checking for /configs/config.json
> 2016-08-06 23:34:22,197 [       cli] [INFO] Configuration initialized
> 2016-08-06 23:34:22,201 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
> 2016-08-06 23:34:22,202 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
> 2016-08-06 23:34:22,204 [PokemonGoBot] [INFO] [location_found] Location found: [REDACTED]
> 2016-08-06 23:34:22,204 [PokemonGoBot] [INFO] [position_update] Now at [REDACTED]
> 2016-08-06 23:34:22,205 [PokemonGoBot] [INFO] [login_started] Login procedure started.
> Traceback (most recent call last):
>   File "pokecli.py", line 493, in <module>
>     main()
>   File "pokecli.py", line 127, in main
>     report_summary(bot)
>   File "pokecli.py", line 136, in report_summary
>     metrics.capture_stats()
>   File "/home/stumpyb/pokemongo_bot/metrics.py", line 73, in capture_stats
>     request = self.bot.api.create_request()
>   File "/home/stumpyb/pokemongo_bot/api_wrapper.py", line 27, in create_request
>     self._position_alt
>   File "/home/stumpyb/pokemongo_bot/api_wrapper.py", line 43, in __init__
>     PGoApiRequest.__init__(self, *args)
> TypeError: __init__() takes exactly 6 arguments (5 given)

### Other Information
OS: Debian 8
Git Commit: c21fad0e476a2ab77e8ec6eb898c03b1c3dbf3dd
Python Version: Python 2.7.9

**Comment by sia84** [comment]
Getting the same error

**Comment by TheSavior** [comment]
Same

**Comment by sia84** [comment]
Latest change made to dev branch fixes this issue

**Comment by stumpyb** [comment]
didn't fix it for me

**Comment by asdf93500** [comment]
same issue here

**Comment by sia84** [comment]
I also compiled ecnrypt.so/encrypt.dll from source downloaded from here: 

http://pgoapi.com

Previously I had downloaded it from a random link on the internet.

Also in my config I changed health_record to false:

"health_record": false

Not sure if any of those changes might have fixed the issue.

**Comment by fili28** [comment]
Running  `pip install -r requirements.txt` fixed it for me.

**Comment by stumpyb** [comment]
thanks @fili28 - worked for me too. dunno why install.sh didn't run that for me. feeling very silly.

**Comment by TheSavior** [comment]
Closing. 

If this occurs to you it means you probably haven't update since the new bot. You need to re run your pip install and make sure you have the encrypt.so or encrypt.dll.
