### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by piai46** [PokemonGoF/PokemonGo-Bot#2651]
One would teach me how to use the bot ?

**Comment by randypfohl** [comment]
Quit opening issues, this is not an issue with the build. 

There is a wiki page, and the bot isn't currently functional. 

if you need to learn how to run a script/command line or other basics this is not the place to ask for help. 

This thread is for issues with the code. Please take a course, or use google to learn the basics, all the rest is available in the wiki.

**Comment by twistedpro** [comment]
Does this actually still work considering pgo api? or is that fixed now

**Comment by nivong** [comment]
please close this noob request. @brantje
