### ISSUE TITLE
There is no release json file

### ISSUE THREAD

**Issue by leovarmak** [PokemonGoF/PokemonGo-Bot#2653]
### Expected Behavior

There was supposed to be a release file

### Actual Behaviour

The release json file is missing

### Steps to Reproduce

Just cloned on Mac (Master)

### Other Information
OS: Mac OS X 10.11.6

Python Version: 2.7

**Comment by rootbeersoup** [comment]
It's part of the master config file now it seems

**Comment by pablossp** [comment]
The release conditions are in the main configuration file template now (located in configs/config.json.example), you'll notice how it follows a new set of rules.

There are two examples of how to build up your custom rules, they are on "configs/config.json.example" and "configs/config.json.pokemon.example". 

I'm not sure if there's a full tutorial on how to use them, but they're pretty neat once you get the hang of it.

**Comment by leovarmak** [comment]
@pablossp Thanks man !
