### ISSUE TITLE
Local Variable Error

### ISSUE THREAD

**Issue by agastimhatre** [PokemonGoF/PokemonGo-Bot#2657]
### Expected Behavior
Script should run normally

### Actual Behavior
2016-08-07 10:34:34,334 [       cli] [INFO] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 126, in main
    if bot:
UnboundLocalError: local variable 'bot' referenced before assignment

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by camarokris** [comment]
Had this happen to me. look for an extra comma in your config file. Perhaps running your config through http://jsonlint.com/ will find it. It did for me.

**Comment by agastimhatre** [comment]
https://github.com/camarokris Thanks Buddy, one extra comma in location itself. it worked.
