### ISSUE TITLE
Pokemons keep vanishing?

### ISSUE THREAD

**Issue by mauriez** [PokemonGoF/PokemonGo-Bot#266]
### Expected Behavior
Capture of a Pokemon

### Actual Behavior
[#] A Wild Zubat appeared! [CP 10]
[x] Using Pokeball...
[x] Oh no! Zubat vanished! :(

*all* pokemons seem to vanish :(

### Steps to Reproduce
Run the program.

### Other Information
OS: OSX 10.11.5
Git Commit: acc2d4f

**Comment by deathcoderz** [comment]
There is a chance you are soft banned dont know for sure

**Comment by TheGoldenXY** [comment]
/softbanned.

**Comment by daemonfire300** [comment]
@mauriez Please do not use the Pokemon GO App while the bot is running with the same account. This gets you (soft)banned very very fast. Stop the bot, wait 10-20 minutes. Open the Mobile App and try to spin a PokeStop, if it is working (returin Items) then your softban most probably was lifted.
Then you can proceed by, this is what I do

 1. Logout of the Mobile App
 2. (This is optional: If your farming spot is not the same as your physical location, then you should probably wait some time, to prevent the discrepency between locations to be some what alerting)
 3. Start the Bot

**Comment by douglascamata** [comment]
@mauriez you can use the bot with `-m farm`. It will try to spin a PokeStop and it will detect if you are soft banned or not.

**Comment by mauriez** [comment]
Yeah.. softbanning seems to be it. Didnt know about it. Hope it clears me soon :) Thanks!
