### ISSUE TITLE
MacOSX 10.11.6 install: last step fails

### ISSUE THREAD

**Issue by Casual-User** [PokemonGoF/PokemonGo-Bot#2660]
### Expected Behavior
Clean installation after steps in Mac installation description are followed

### Actual Behavior
last steps doesn't work (the '$ pip install -r requirements.txt')

see log:
(PokemonGo-Bot) Yann:PokemonGo-Bot Analysis$ pip install -r requirements.txt
-bash: /usr/local/bin/pip: "/Applications/MEDIA/Programs/Pokebot/PokeMonBot/neu: bad interpreter: No such file or directory

### Steps to Reproduce
every time.

### Other Information
OS: X10.11.6
Git Commit: (c21fad0e476a2ab77e8ec6eb898c03b1c3dbf3dd)
Python Version: (Python 2.7.12)

**Comment by leovarmak** [comment]
@Casual-User lol. Remove that `$` symbol and do it xD

**Comment by prestonbrown** [comment]
I have tried the same thing, only I get:

`Command "python setup.py egg_info" failed with error code 1 in /Users/prestonbrown/PokemonGo-Bot/src/pgoapi/`

**Comment by leovarmak** [comment]
@prestonbrown are you trying to run the bot ? If yes , do this `python pokecli.py`

**Comment by prestonbrown** [comment]
No. I am trying to pip install.

**Comment by prestonbrown** [comment]
Running `python pokecli.py` gives me:
`  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions`

After looking around on the issue logs I found [this thread](https://github.com/PokemonGoF/PokemonGo-Bot/issues/2646).

This is the only response on that page:
"things have changed. You gotta rm -rf pgoapi and do the pip install again."

So now I am stuck on the command:
`and pip install -r requirements.txt`
Because I get the error:
`Command "python setup.py egg_info" failed with error code 1 in /Users/prestonbrown/PokemonGo-Bot/src/pgoapi/`

**Comment by Casual-User** [comment]
@leovarmak: please... the $ is the last key of the terminal's output, and not my own input. I just cited this step out of the description, not pasted the $ itself. Otherwise I wouldn't have had success wit the four earlier steps either ;-)

**Comment by leovarmak** [comment]
@Casual-User Sorry :D . Try this once and post a screenshot if you have an error `sudo pip install -r requirements.txt`

**Comment by Casual-User** [comment]
@leovarmak 
Tried this and for whatever reason I got this (full log below).

> (PokemonGo-Bot) Yann:PokemonGo-Bot Analysis$ sudo pip install -r requirements.txt
Password:
> sudo: unable to execute /usr/local/bin/pip: No such file or directory 

After that response I double checked my pip install but: first, it was there as it should be and second, I got this response when I tried to re-install:

> Yann:Python Install Analysis$ python get-pip.py
> Requirement already up-to-date: pip in /usr/local/lib/python2.7/site-packages

Hmmm. Still don't know what could cause the hassle

**Comment by leovarmak** [comment]
Just try this once in the `PokemonGo-Bot` folder `pip`

**Comment by Casual-User** [comment]
I got the very same "No such file or directory" comment.
So I git-pulled everything again into a new folder and voilà, only have to fill out the json file again, since I got (as the last line) > pokecli.py: error: argument -a/--auth_service is required.
I still don't know why that happened, but having some stacked and iterated Pokemongo-bot folders, builts and images might have contributed to bad path recognitions... Thanks so far!

**Comment by leovarmak** [comment]
@Casual-User Did you just enter `pip` ?

**Comment by leovarmak** [comment]
That usual happens when you have multiple repo based on pokemon go

**Comment by Casual-User** [comment]
@leovarmak Yeah, I just did 'pip'. And the multiple repo thing might be the case here.

But since it seems I overcame that hurdle, I'm now too stuck @prestonbrown's problem with the very same error-report of:

> Yann:PokemonGo-Bot Analysis$ python pokecli.py -cf ./configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions
