### ISSUE TITLE
There is no option to ignore pokemon ?

### ISSUE THREAD

**Issue by leovarmak** [PokemonGoF/PokemonGo-Bot#2661]
### Expected Behavior

The bot should ignore few pokemons. There was catch-ignore.yaml before

### Actual Behavior

File missing

### Steps to Reproduce

Try Master on OS X

### Other Information

OS: Mac OS X 10.11.6

Python Version: 2.7

**Comment by SGColdSun** [comment]
You can specify things not to catch in the config.json file now.

**Comment by fari-99** [comment]
please see configs/config.json.example. there is configuration for that.

**Comment by leovarmak** [comment]
@SGColdSun @fari-99 Its isn't releasing all tho. I have double check the CP and IV, the pokemon is less than them both but the pokemon is not getting released

**Comment by fari-99** [comment]
can we see your config @leovarmak ? please hide your details.

**Comment by leovarmak** [comment]
@fari-99 Sure 👍 . I am taking a simple example of the diglet I captured.

This is the config file 
![screen shot 2016-08-07 at 11 17 07 am](https://cloud.githubusercontent.com/assets/14135553/17460757/c8e0aff4-5c90-11e6-8949-f04519dc7f7b.png)

This is the terminal output 
![screen shot 2016-08-07 at 11 16 47 am](https://cloud.githubusercontent.com/assets/14135553/17460759/dcb5dd88-5c90-11e6-8e20-d1d627144e0a.png)

Now this is the Poliwag
![screen shot 2016-08-07 at 11 21 32 am](https://cloud.githubusercontent.com/assets/14135553/17460774/370f0052-5c91-11e6-81cd-3b1885e02038.png)

This is the terminal output 
![screen shot 2016-08-07 at 11 20 56 am](https://cloud.githubusercontent.com/assets/14135553/17460777/41ac79d6-5c91-11e6-9477-3424506bfd60.png)

**Comment by fari-99** [comment]
welp, if that config for capture i get it with your terminal output.
but if that config for release, and after captured not releasing, i don't know what happened.

**Comment by k4n30** [comment]
@leovarmak Are you still experiencing this issue? If so can you please post your complete config file with username, password, and gmapkey removed.

**Comment by leovarmak** [comment]
@k4n30 Sure. I am out now. I will post it on 3-4 hours.

**Comment by leadboots5** [comment]
I believe this file was removed as the never_catch feature was rolled into the config. example:
"Pidgey": {"never_catch": true}

closing.
