### ISSUE TITLE
%1 is not a valid Win32 application

### ISSUE THREAD

**Issue by crvfts** [PokemonGoF/PokemonGo-Bot#2663]
I have the correct .so file in the root directory. 
I have VC++ installed.
I have all other requirements.

Anyone have any idea how to fix this? I see other people are having this error, too.

**Comment by akimbosnacks** [comment]
I'm having the same error.

**Comment by QuadTog** [comment]
Downgrade to Python 2.7 32 bit.

**Comment by crvfts** [comment]
that worked! thank you!
