### ISSUE TITLE
error when starting the application

### ISSUE THREAD

**Issue by INGCRENGIFO** [PokemonGoF/PokemonGo-Bot#2664]
it happens just run the application, and update the repository, I need something new?

![error](https://cloud.githubusercontent.com/assets/12200313/17460684/1a683392-5c37-11e6-9fdf-3e9ad2a9aa8f.png)

![err](https://cloud.githubusercontent.com/assets/12200313/17460849/3d608682-5c3d-11e6-8dd6-a793574a9416.png)

OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by k4n30** [comment]
#2768

**Comment by INGCRENGIFO** [comment]
@k4n30 Sorry, I do not understand your comment xD

**Comment by RedViper9** [comment]
You need to get a copy of encrypt.dll . You can compile one yourself or you can see if someone on slack has one they're willing to share.
