### ISSUE TITLE
Problem with 9c070a789029792a75be34aed408906ee3e3653f

### ISSUE THREAD

**Issue by takenek** [PokemonGoF/PokemonGo-Bot#2665]
i try install and got strange error:

Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@9c070a789029792a75be34aed408906ee3e3653f#egg=pgoapi (from -r requirements.txt (line 3))
  Cloning https://github.com/keyphact/pgoapi.git (to 9c070a789029792a75be34aed408906ee3e3653f) to ./src/pgoapi
  **Could not find a tag or branch '9c070a789029792a75be34aed408906ee3e3653f', assuming commit.**

Best Regards
TaKeN

**Comment by DimaVIII** [comment]
run again the:
pip install -r requirements.txt
