### ISSUE TITLE
Error: No /configs/config.json or specified config

### ISSUE THREAD

**Issue by htugsdr** [PokemonGoF/PokemonGo-Bot#2667]
Hi guys I need help with my configs. I copied the config.json.example and pasted it into the same folder. Then i renamed it to config.json and put in my details however, when i run python pokecli.py i get this:

$ python pokecli.py
2016-08-07 15:10:33,695 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 15:10:33,696 [       cli] [INFO] Error: No /configs/config.json or specified config
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-ws WEBSOCKET.SERVER_URL]
                  [-wss WEBSOCKET.START_EMBEDDED_SERVER]
                  [-wsr WEBSOCKET.REMOTE_CONTROL] [-p PASSWORD] [-l LOCATION]
                  [-lc LOCATION_CACHE] [--forts.spin FORTS.SPIN] [-w WALK]
                  [-k GMAPKEY] [-e SHOW_EVENTS] [-d DEBUG] [-t TEST]
                  [-du DISTANCE_UNIT] [-ec EVOLVE_CAPTURED]
                  [-rt RECONNECTING_TIMEOUT] [-hr HEALTH_RECORD]
                  [-ac FORTS.AVOID_CIRCLES] [-mcs FORTS.MAX_CIRCLE_SIZE]
                  [--catch_randomize_reticle_factor CATCH_RANDOMIZE_RETICLE_FACTOR]
                  [--catch_randomize_spin_factor CATCH_RANDOMIZE_SPIN_FACTOR]
                  [--map_object_cache_time MAP_OBJECT_CACHE_TIME]
pokecli.py: error: argument -a/--auth_service is required

On Mac OSX 
my main folder with all the file is called Pokemongo-bot and is saved on my desktop if that changes anything.

**Comment by rootbeersoup** [comment]
For me, the JSON was invalid as it was. Check yours as JSONlint.com

**Comment by htugsdr** [comment]
okay ill give it a go

**Comment by WaffleMoose** [comment]
Config Files moved to Configs folder, I had the same issue this morning after doing a pull request for the PGO updates

**Comment by Elim160** [comment]
@WaffleMoose  but which configs do we change? I just figured out they were in the folder but I have no clue which ones to change.

**Comment by WaffleMoose** [comment]
in the configs folder are just examples, rename the config.json.example to config.json, and then have a look at the other config files for templates of what you can use, dont forget to update the file to your settings

**Comment by Elim160** [comment]
@WaffleMoose Okay I have done that now I am getting the same error as him hm.

**Comment by WaffleMoose** [comment]
@Elim160  as above, check that your json is correct on http://jsonlint.com/
Also does it have rights to the folder?
