### ISSUE TITLE
UnicodeDecodeError, i even can't  walk 

### ISSUE THREAD

**Issue by GucciChen** [PokemonGoF/PokemonGo-Bot#2668]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
2016-08-07 13:47:00,635 [sentry.errors.uncaught] [ERROR] [u'OSError: encrypt.so: cannot open shared object file: No such file or directory', u'  File "pokecli.py", line 493, in <module>', u'  File "pokecli.py", line 127, in main', u'  File "pokecli.py", line 136, in report_summary', u'  File "pokemongo_bot/metrics.py", line 76, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 209, in call', u'  File "pgoapi/rpc_api.py", line 82, in activate_signature', u'  File "ctypes/__init__.py", line 440, in LoadLibrary', u'  File "ctypes/__init__.py", line 362, in __init__']
### Actual Behavior

OS: 
Git Commit: c81666d751b9ca8cd338760fdf920194fabf4ee4

Python Version:Python 2.7.12

**Comment by ffigueroa** [comment]
Same issue

**Comment by squirrelwang** [comment]
same issue

**Comment by xren11** [comment]
Same issue

**Comment by Happyrain67** [comment]
Look carefully. All error say "ascii decode..."
Maybe this hides a true error below.

**Comment by zbyte64** [comment]
Doing this got me past this issue: https://github.com/PokemonGoF/PokemonGo-Bot/issues/2673#issuecomment-238066266

**Comment by zbyte64** [comment]
After disabling `health_record` I get:


```
bot1-pokego_1     | Traceback (most recent call last):
bot1-pokego_1     |   File "pokecli.py", line 498, in <module>
bot1-pokego_1     |     main()
bot1-pokego_1     |   File "pokecli.py", line 132, in main
bot1-pokego_1     |     report_summary(bot)
bot1-pokego_1     |   File "pokecli.py", line 141, in report_summary
bot1-pokego_1     |     metrics.capture_stats()
bot1-pokego_1     |   File "/usr/src/app/pokemongo_bot/metrics.py", line 76, in capture_stats
bot1-pokego_1     |     response_dict = request.call()
bot1-pokego_1     |   File "/usr/src/app/pokemongo_bot/api_wrapper.py", line 106, in call
bot1-pokego_1     |     result = self._call()
bot1-pokego_1     |   File "/usr/src/app/pokemongo_bot/api_wrapper.py", line 63, in _call
bot1-pokego_1     |     return PGoApiRequest.call(self)
bot1-pokego_1     |   File "/usr/src/app/src/pgoapi/pgoapi/pgoapi.py", line 210, in call
bot1-pokego_1     |     request.activate_signature(lib_path)
bot1-pokego_1     |   File "/usr/src/app/src/pgoapi/pgoapi/rpc_api.py", line 85, in activate_signature
bot1-pokego_1     |     self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
bot1-pokego_1     |   File "/usr/local/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
bot1-pokego_1     |     return self._dlltype(name)
bot1-pokego_1     |   File "/usr/local/lib/python2.7/ctypes/__init__.py", line 362, in __init__
bot1-pokego_1     |     self._handle = _dlopen(self._name, mode)
bot1-pokego_1     | OSError: encrypt.so: cannot open shared object file: No such file or directory
```

**Comment by Mortemer** [comment]
I have the same issue.

**Comment by davidkernell** [comment]
try the fix documented here: https://github.com/PokemonGoF/PokemonGo-Bot/issues/2639

Download the encrypt.so file from here: https://slack-files.com/T1U6G9ZEW-F1YV50RGQ-cc979942b7

then move it to the root directory of the project.

This worked for me.

**Comment by Mortemer** [comment]
I just tried it and it still didn't work.

**Comment by Mortemer** [comment]
Do I need to change any code in any of the files?

**Comment by jerdie** [comment]
having python.exe - Bad image error in windows using .so from slack.

**Comment by ErrorFlexXx** [comment]
Regarding to the ascii decode error I fixed it in another way:

Edit pokecli.py and insert the following
after this:
if sys.version_info >= (2, 7, 9):
    ssl._create_default_https_context = ssl._create_unverified_context

reload(sys)
sys.setdefaultencoding('UTF8')

Seems now to be working and is able to output something like 'ö'.

Regards

**Comment by GitPupper** [comment]
Assuming this problem was fixed. If not just use encrypt.so on mac and encrypt.dll on windows 👍
