### ISSUE TITLE
Event spin_pokestop not registered

### ISSUE THREAD

**Issue by sia84** [PokemonGoF/PokemonGo-Bot#2669]
It's able to walk and catch pokemons but fails when trying to spin pokestops:

Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 129, in main
    raise e
pokemongo_bot.event_manager.EventNotRegisteredException: Event spin_pokestop not registered...

Regards,
Sia84

**Comment by riseno** [comment]
same here

**Comment by jmcquillan** [comment]
Same error for me.

OS: MacOS 10.11.6
Git Commit: dc0f38
Python Version: Python 2.7.12

**Comment by tejanium** [comment]
find `spun_pokestop` and replace it with `spin_pokestop`

**Comment by furthurr** [comment]
in which file?

**Comment by sia84** [comment]
Closing since fixed by solderzzc
