### ISSUE TITLE
Log in Color

### ISSUE THREAD

**Issue by DimaVIII** [PokemonGoF/PokemonGo-Bot#2675]
How to activate the log in color as it was before the api update?

**Comment by SGColdSun** [comment]
The colors have been stripped. There is no easy toggle at the moment.

**Comment by celus** [comment]
Why was the color removed in the first place?

**Comment by DimaVIII** [comment]
It's somewhere in https://github.com/keyphact/pgoapi right?

**Comment by SGColdSun** [comment]
No. It isn't in the pgoapi, and there is no easy way to turn it in.

**Comment by Baconnaise** [comment]
They stripped the color before the change if I recall then the API changed. It's sort of a mess right now compared to before. I don't know if they plan to move this info to the map or not. The old map you could just drop clones of folders with different configs for different bots and open each index to see where they were at. They changed that as well so I haven't bothered to look again.

I do miss that color coding as I run multiple monitors so if I'm walking by or happen to be at the desk I know exactly what's going and if things are running correctly. I'll have to look and see if the map is any good like before.

**Comment by iruy** [comment]
It is such a mess right now without colors... Please somebody bring them back

**Comment by tvb** [comment]
+1 I favor the colors as well! Much easier to read back

**Comment by nikmess** [comment]
Quick and dirty fix:
Save this as colorizer.sh in the PokemonGo-Bot directory:
```
#!/bin/bash

red=$(tput bold;tput setaf 1)            
green=$(tput setaf 2)                    
yellow=$(tput bold;tput setaf 3)         
fawn=$(tput setaf 3)
blue=$(tput bold;tput setaf 4)           
purple=$(tput setaf 5)
pink=$(tput bold;tput setaf 5)           
cyan=$(tput bold;tput setaf 6)           
gray=$(tput setaf 7)                     
white=$(tput bold;tput setaf 7)          
normal=$(tput sgr0)                      

sep=`echo -e '\001'` # use \001 as a separator instead of '/'

while [ -n "$1" ] ; do
  color=${!1}
  pattern="$2"
  shift 2

  rules="$rules;s$sep\($pattern\)$sep$color\1$normal${sep}g"
done

#stdbuf -o0 -i0 sed -u -e "$rules"
sed -u -e "$rules"
```
(from https://stackoverflow.com/questions/241325/color-regex-matches-without-dropping-misses)

Then run something like this: 
`python pokecli.py 2>&1 | colorizer.sh red ".*PokemonCatchWorker.*" blue ".*TransferPokemon.*" green ".*IncubateEggs.*" yellow ".*SpinFort.*"`

**Comment by Kyokoo** [comment]
> Then run something like this: 
python pokecli.py 2>&1 | ./colorizer.sh red ".*PokemonCatchWorker.*" blue ".*TransferPokemon.*" green ".*IncubateEggs.*" yellow ".*SpinFort.*" pink ".*CollectLevelUpReward.*"

If you're using Mac you may need to install gnu-sed using brew.
Then you must change `sed -u -e "$rules"` to `gsed -u -e "$rules"`

**Comment by crvfts** [comment]
anyone know how to do this in windows?
`python pokecli.py 2>&1 | ./colorizer.sh red ".*PokemonCatchWorker.*" blue ".*TransferPokemon.*" green ".*IncubateEggs.*" yellow ".*SpinFort.*" pink ".*CollectLevelUpReward.*"`
end up giving an error

**Comment by nikmess** [comment]
That script works only on *nix systems. You might want to have a look at [Cygwin](https://www.cygwin.com/), which gives you a unix style terminal under Windows.

**Comment by crvfts** [comment]
@nikmess works perfectly with Git for Windows! I was attempting to run the line from Windows. 
Thank you for your help!

**Comment by Kyokoo** [comment]
@nikmess Using your script I donc have any stats when session end :/

**Comment by nikmess** [comment]
It seems the problem is not (only?) my script, but rather the mingw shell. Killing "python pokecli.py" with ^c gives no stats either in mingw.

**Comment by NikolayBlokhin** [comment]
Other way to add colors:

```
diff --git a/pokemongo_bot/base_task.py b/pokemongo_bot/base_task.py
index 22bbedf..b286a48 100644
--- a/pokemongo_bot/base_task.py
+++ b/pokemongo_bot/base_task.py
@@ -1,4 +1,5 @@
 import logging
+from termcolor import colored


 class BaseTask(object):
@@ -19,6 +20,16 @@ class BaseTask(object):
   def emit_event(self, event, sender=None, level='info', formatted='', data={}):
     if not sender:
       sender=self
+
+    if event == 'pokemon_appeared':
+      formatted = colored(formatted, 'magenta')
+    if event == 'pokemon_caught':
+      formatted = colored(formatted, 'green')
+    if event == 'pokemon_vanished':
+      formatted = colored(formatted, 'red')
+    if event == 'softban':
+      formatted = colored(formatted, 'red')
+
     self.bot.event_manager.emit(
       event,
       sender=sender,
```

P.S. Before it, install lib termcolor: "pip install termcolor".

**Comment by serberus7** [comment]
Or you can just use my cell workers.
I added colors and they are working fine.

[cell_workers.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/405611/cell_workers.zip)

**Comment by Zedronar** [comment]
@serberus7 not working for Windows 10 unfortunately.

**Comment by serberus7** [comment]
Lol @Zedronar then what is this?
![lol](https://cloud.githubusercontent.com/assets/20890081/17463873/f8d6fb90-5c96-11e6-8d6f-e4dd8e20e337.png)

**Comment by Zedronar** [comment]
@serberus7 Must be something wrong with my configuration then.

**Comment by Sayujya** [comment]
For anyone on OSX, go to the directory, and type
`source bin/activate 
brew install gsed
sudo vim colorizer.sh`

then inside vim copy paste this version of @nikmess 's script

`#!/bin/bash

red=$(tput bold;tput setaf 1)            
green=$(tput setaf 2)                    
yellow=$(tput bold;tput setaf 3)         
fawn=$(tput setaf 3)
blue=$(tput bold;tput setaf 4)           
purple=$(tput setaf 5)
pink=$(tput bold;tput setaf 5)           
cyan=$(tput bold;tput setaf 6)           
gray=$(tput setaf 7)                     
white=$(tput bold;tput setaf 7)          
normal=$(tput sgr0)                      

sep=`echo -e '\001'` # use \001 as a separator instead of '/'

while [ -n "$1" ] ; do
  color=${!1}
  pattern="$2"
  shift 2

  rules="$rules;s$sep\($pattern\)$sep$color\1$normal${sep}g"
done

#stdbuf -o0 -i0 gsed -u -e "$rules"
gsed -u -e "$rules"`

type `:wq` to save  and quit the file

then type 
`sudo chmod 777 colorizer.sh`

After that you can use @nikmess 's script again 
`python pokecli.py 2>&1 | ./colorizer.sh red ".*PokemonCatchWorker.*" blue ".*TransferPokemon.*" green ".*IncubateEggs.*" yellow ".*SpinFort.*" pink ".*CollectLevelUpReward.*"`

**Comment by Baconnaise** [comment]
@serberus7 Works great. Thank you. 

Win7x64.

**Comment by Vvkmnn** [comment]
@serberus7 Where are you putting that zip file? 

I made a directory called `resources` in the parent and directory and the sub directory, but the script won't seem to notice, despite being on commit fc4e802dd760508e45c9e2f79cdc9704a514b896, which should have .zip support.

**Comment by relomy** [comment]
It's just his cell_workers folder.

**Comment by Vvkmnn** [comment]
Ah. I thought we could just leave plugins in the directory now, as per #2766.

I'll just extract into `./pokemongo_bot/cell_workers/`

**Comment by Baconnaise** [comment]
@Vvkmnn That would actually be great if we had various color and formatting plugins.

**Comment by SingularityIO** [comment]
Updated version of @serberus7 colours as of the live change 30+ Mins ago

http://puu.sh/qtlX7/570de9c1a3.zip

**Comment by hklcf** [comment]
#2809

**Comment by douglascamata** [comment]
This is not a bug, it's an intended behaviour. Colourful log might come back in future updates.
