### ISSUE TITLE
ImportError: No module named gpxpy

### ISSUE THREAD

**Issue by ForPokemon** [PokemonGoF/PokemonGo-Bot#2680]
### Actual Behavior
File "pokecli.py", line 41, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "D:\PokemonGo\PokemonGo-Bot\pokemongo_bot\__init__.py", line 17, in <module>
    import cell_workers
  File "D:\PokemonGo\PokemonGo-Bot\pokemongo_bot\cell_workers\__init__.py", line 15, in <module>
    from follow_path import FollowPath
  File "D:\PokemonGo\PokemonGo-Bot\pokemongo_bot\cell_workers\follow_path.py", line 3, in <module>
    import gpxpy
ImportError: No module named gpxpy

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by ManiacMike** [comment]
I have run into the same issue. And the installing command  "sudo ./install.sh" run without error.

OS:MAC OS 10.11.4
Python 2.7.10
git version: affcbf020c118df458d5a697b208fa956fd81e48

**Comment by ForPokemon** [comment]
Sorry forgot to add in below:

Other Information

OS: Windows 10
Git Commit: 23b4a78738a61f10c0566cde76949d0838e194cb
Python Version: 2.7.10

**Comment by nivong** [comment]
run pip install -r requirments.txt
or run ./install.sh
and update your pst dont add.
