### ISSUE TITLE
Error on Mac OSX OS

### ISSUE THREAD

**Issue by JaydenHamence** [PokemonGoF/PokemonGo-Bot#2681]
(PokemonGo-Bot) Jaydens-Air:PokemonGo-Bot JaydenHamence$ python pokecli.py -cf configs/config.json
2016-08-07 16:48:06,131 [       cli] [INFO] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 126, in main
    if bot:
UnboundLocalError: local variable 'bot' referenced before assignment

**Comment by SGColdSun** [comment]
Paste your json file into here:

http://jsonlint.com/

It will show you where you have mis-matched braces. Possible a missing comma or brace.

**Comment by MikeDX** [comment]
@SGColdSun Good advice ;)

**Comment by SGColdSun** [comment]
I learned from the best *tips hat to you* :D

**Comment by fglo11** [comment]
@JaydenHamence I am also having this issue. What was your solution?

**Comment by leadboots5** [comment]
he has had new issues in the past few days so he getting further than this. closing.
