### ISSUE TITLE
AttributeError: 'module' object has no attribute 'HTTPSHandler'

### ISSUE THREAD

**Issue by hklcf** [PokemonGoF/PokemonGo-Bot#2682]
![image](https://cloud.githubusercontent.com/assets/410302/17460984/ff4b7aa6-5cae-11e6-823b-fd28dc27a12c.png)

44a6602ceecf202e5ab0bf05a960b8efcb595551

**Comment by SGColdSun** [comment]
The issue is that your encrypt.so file is not being found.
Check https://github.com/PokemonGoF/PokemonGo-Bot/pull/2643/files for a fix or wait until the pull request is merged.

**Comment by k4n30** [comment]
#2768
