### ISSUE TITLE
Web interface - Catchable not updating

### ISSUE THREAD

**Issue by raxxon** [PokemonGoF/PokemonGo-Bot#2687]
### Expected Behavior

Catchable file in web directory gets updated for the web interface to display pokemon

### Actual Behavior

File is not created and no updates are made when file is manually made

### Steps to Reproduce

Install dev branch and get it working

### Other Information
OS: Windows 10.1 (Bash shell from Windows 10 Anniversary Update)
hazer@BREAKPOINT:~/PokemonGo-Bot$ git log -n 1 --pretty=format:"%H" ; python -V ; uname -a ; bash --version
44a6602ceecf202e5ab0bf05a960b8efcb595551
Python 2.7.6
Linux BREAKPOINT 3.4.0+ #1 PREEMPT Thu Aug 1 17:06:05 CST 2013 x86_64 x86_64 x86_64 GNU/Linux
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
hazer@BREAKPOINT:~/PokemonGo-Bot$

**Comment by SGColdSun** [comment]
There seems to be a user_web_catchable in the root bot directory. You may want to create a symbolic link and have it be in the web directory as catchable-Username.json

**Comment by raxxon** [comment]
That is indeed a fix. Linked it over and it's updating the web interface with spawning pokemon...

Guess there's something that will need to be tinkered in a later push once more serious things are addressed.

**Comment by SGColdSun** [comment]
Glad to have it resolved :)

**Comment by MikeDX** [comment]
I wouldn't call this resolved at all.

In catch_visible_pokemon.py:

under def work(self):

user_web_catchable = 'web/catchable-%s.json' % (self.bot.config.username)


then change with open('user_web_catchable', 'w') as outfile:

to 
with open(user_web_catchable, 'w') as outfile:

**Comment by raxxon** [comment]
The current issue is resolved to a functional state. The issue is still open so that the Devs can make a permanent fix. Eventually the proper resolution will be merged into the code base and everything will be fine, however I think they have bigger fish to deal with and no, I don't mean the 200CP Magikarp.

**Comment by MikeDX** [comment]
@raxxon what i just posted is the correct fix. However I will leave it up to someone else to make a pull request based on those changes.

Symlinking the current "user_web_catchable" file does not work if you are running multiple instances of the bot with a single web interface.

**Comment by raxxon** [comment]
Good point, but last I saw there were issues running multiple bots from the same directory tree... have those issues been dealt with since the new API release?

**Comment by MikeDX** [comment]
@raxxon I have no idea, I was running multiple bots here for a while but not tried since the unknown6 carnival... The web interface never really worked properly for multiple bots anyway, it sort of worked, but not really. Only the first bot showed an avatar / path but it was useful for the stats for the other bots.

**Comment by raxxon** [comment]
I saw several reports for the dev branch of the bot not working past the first iteration. I assume that if you setup multiple independent directories you could still run multiple, but yeah, then the unknown6 fiesta started....

Why run multiple bots?
