### ISSUE TITLE
pgoapi. install error

### ISSUE THREAD

**Issue by Unscrupulor** [PokemonGoF/PokemonGo-Bot#2688]
`C:\Users\Chris\PokemonGo-Bot>pip2 --version
pip 8.1.2 from c:\python27\lib\site-packages (python 2.7)

C:\Users\Chris\PokemonGo-Bot>pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): numpy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): networkx==1.11 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@249d3be7fbbdabc7f9adea17cbc899d6549e47a2#egg=pgoapi (from -r requirements.txt (line 3))
  Cloning https://github.com/keyphact/pgoapi.git (to 249d3be7fbbdabc7f9adea17cbc899d6549e47a2) to c:\users\chris\pokemongo-bot\src\pgoapi
  Could not find a tag or branch '249d3be7fbbdabc7f9adea17cbc899d6549e47a2', assuming commit.
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): protobuf==3.0.0b4 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): protobuf-to-dict==0.1.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): googlemaps==2.4.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): colorama==0.3.7 in c:\python27\lib\site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): enum34==1.1.6 in c:\python27\lib\site-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): pyyaml==3.11 in c:\python27\lib\site-packages (from -r requirements.txt (line 13))
Requirement already satisfied (use --upgrade to upgrade): haversine==0.4.5 in c:\python27\lib\site-packages (from -r requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): polyline==1.3.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 15))
Requirement already satisfied (use --upgrade to upgrade): python-socketio==1.4.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): flask==0.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): socketIO_client==0.7.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): eventlet==0.19.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): gpxpy==1.1.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 20))
Requirement already satisfied (use --upgrade to upgrade): mock==2.0.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 21))
Requirement already satisfied (use --upgrade to upgrade): timeout-decorator==0.3.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 22))
Collecting raven==5.23.0 (from -r requirements.txt (line 23))
  Using cached raven-5.23.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.4.0 in c:\python27\lib\site-packages (from networkx==1.11->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): six in c:\python27\lib\site-packages (from pgoapi->-r requirements.txt (line 3))
Collecting xxhash (from pgoapi->-r requirements.txt (line 3))
  Using cached xxhash-0.6.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from protobuf==3.0.0b4->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): future in c:\python27\lib\site-packages (from s2sphere==0.2.4->-r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): python-engineio>=0.8.0 in c:\python27\lib\site-packages (from python-socketio==1.4.2->-r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): click>=2.0 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in c:\python27\lib\site-packages (from flask==0.11.1->-r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): websocket-client in c:\python27\lib\site-packages (from socketIO_client==0.7.0->-r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.3 in c:\python27\lib\site-packages (from eventlet==0.19.0->-r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): funcsigs>=1; python_version < "3.3" in c:\python27\lib\site-packages (from mock==2.0.0->-r requirements.txt (line 21))
Requirement already satisfied (use --upgrade to upgrade): pbr>=0.11 in c:\python27\lib\site-packages (from mock==2.0.0->-r requirements.txt (line 21))
Collecting contextlib2 (from raven==5.23.0->-r requirements.txt (line 23))
  Using cached contextlib2-0.5.4-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in c:\python27\lib\site-packages (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 17))
Building wheels for collected packages: xxhash
  Running setup.py bdist_wheel for xxhash ... error
  Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\chris\\appdata\\local\\temp\\pip-build-d6njdi\\xxhash\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\users\chris\appdata\local\temp\tmp3bk4ugpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'xxhash' extension
  error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27

  ----------------------------------------
  Failed building wheel for xxhash
  Running setup.py clean for xxhash
Failed to build xxhash
Installing collected packages: xxhash, pgoapi, contextlib2, raven
  Running setup.py install for xxhash ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\chris\\appdata\\local\\temp\\pip-build-d6njdi\\xxhash\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\chris\appdata\local\temp\pip-wsn0ne-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'xxhash' extension
    error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\chris\\appdata\\local\\temp\\pip-build-d6njdi\\xxhash\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\chris\appdata\local\temp\pip-wsn0ne-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\chris\appdata\local\temp\pip-build-d6njdi\xxhash\
`
I get this error at the end, can't install the latest build; however the previous builds worked for me.

**Comment by Baconnaise** [comment]
Install Microsoft Visual C++ 9.0 (Python) and you should be good to go.

**Comment by Unscrupulor** [comment]
I can install, thanks!

**Comment by CoderFX** [comment]
Didn't help

**Comment by kevin-ta** [comment]
@CoderFX If you are on Linux, you can try : 

`apt-get install python-dev`
