### ISSUE TITLE
OSError: dlopen(encrypt.so, 6): image not found

### ISSUE THREAD

**Issue by Philipp59** [PokemonGoF/PokemonGo-Bot#2690]
OSError: dlopen(encrypt.so, 6): image not found

can so tell me more... 

i have:
encrypt .c
encrypt.h
man.c 

what to do with that?

**Comment by SGColdSun** [comment]
You need to compile it for your system and generate a encrypt.so or encrypt.dll.

**Comment by Philipp59** [comment]
Ok changed the question in HOW to compile it for noobs

**Comment by SGColdSun** [comment]
g++ -shared -fPIC encrypt.c

In the future, you may want to look at how to compile c on google or something.

**Comment by Philipp59** [comment]
thx

**Comment by z4ppy** [comment]
I don't have these files with the latest dev version :'(

**Comment by z4ppy** [comment]
Ok found here : http://pgoapi.com/

**Comment by nivong** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2780
