### ISSUE TITLE
help install pls. rus-__-

### ISSUE THREAD

**Issue by brianna1337** [PokemonGoF/PokemonGo-Bot#2691]
hallo, my eng bad, and idk how install bot, help...
maybe recording video tutorial ?;3

**Comment by rbJARB** [comment]
Please look on the wiki for information. https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Getting-Started

**Comment by SGColdSun** [comment]
Follow the wiki installation guide. This isn't the place for installation walkthroughs. If you have a hard time following the wiki (not sure how, as it's pretty straight forward) try going to the slack discussion link found on the main page)
