### ISSUE TITLE
thx

### ISSUE THREAD

**Issue by Grumble86tit** [PokemonGoF/PokemonGo-Bot#2694]
thx

**Comment by SGColdSun** [comment]
The bot is working correctly if you're using the new api. As you've been running it for 8 hours, its safe to assume your using the old api and no, you won't catch anything with it.

**Comment by Grumble86tit** [comment]
I stopped after
a test

**Comment by Grumble86tit** [comment]
cheers
ill give this 1 a go

**Comment by Grumble86tit** [comment]
just do a fresh install  ?
