### ISSUE TITLE
No config argument specified error

### ISSUE THREAD

**Issue by congochicken** [PokemonGoF/PokemonGo-Bot#2699]
**Input**
`python pokecli.py
`
**Output**

```
No config argument specified, checking for /configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 126, in main
    if bot:
UnboundLocalError: local variable 'bot' referenced before assignment
(PokemonGo-Bot) Maxs-MacBook-Pro-3:PokemonGo-Bot maxsher$ source bin/activate 
(PokemonGo-Bot) Maxs-MacBook-Pro-3:PokemonGo-Bot maxsher$ python pokecli.py
2016-08-07 00:39:46,072 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 00:39:46,073 [       cli] [INFO] No config argument specified, checking for /configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 126, in main
    if bot:
UnboundLocalError: local variable 'bot' referenced before assignment
```

**Other Information**
OS: OSX

**Comment by raxxon** [comment]
note the lack of a . or the use of the /

Basically it's looking on the root for the file.

run.sh configs/config.json   should work, assuming you've edited one of the example files and saved it. I have multiple configs for my bot based on location/path and if I'm farming everything or just balls....

**Comment by rbJARB** [comment]
This same issue was posted about 20 minutes ago. Please check previous issue before posting another. Copy and paste your config.json into that website to check for errors, that should help as it helped me.
http://jsonlint.com/

**Comment by congochicken** [comment]
@rbJARB that solution didn't work for me, I actually left a comment on that thread. Thanks though. @raxxon, thanks I'll try that now.

**Comment by congochicken** [comment]
@raxxon, thanks for responding so quickly. 

I probably should have mentioned that I'm in Terminal on OSX within the directory of pokeclip.ly, and when I run run.sh configs/config.json it returns ` File "run.sh", line 6
    if [ ! -z $1 ]; then
         ^
SyntaxError: invalid syntax`
