### ISSUE TITLE
which commit released all pokemon of given -c ?

### ISSUE THREAD

**Issue by jplusc** [PokemonGoF/PokemonGo-Bot#270]
There was a commit that would release all pokemon under the given -c  (even when using -s)

I know we have moved well past that, but I want to wipe out many of my pokemons and I don't remember which version that was...

anyone recall the commit?  I tried the one I had from last night, but it was too new..

I guess in the current version, an option to remove all <CP pokemon would be good.

thanks!

**Comment by ckrmml** [comment]
I get 

---
2016-07-22 21:27:23,711 [    pgoapi] [ERROR] Login failed - unexpected server response!
Login Error, server busy

---

at the moment but as far as i know thats still working. Did at least work for me like an hour ago

**Comment by douglascamata** [comment]
@jplusc this feature is on the works right now at https://github.com/PokemonGoF/PokemonGo-Bot/pull/274.

**Comment by jplusc** [comment]
Cool, merge it in, i'll be the guinea pig for you.
... As soon as servers are back up that is : )
