### ISSUE TITLE
ImportError: No module named 'cell_workers'

### ISSUE THREAD

**Issue by iHatePython** [PokemonGoF/PokemonGo-Bot#2700]
### Expected Behavior
Expected the bot to start

### Actual Behavior
Returns an error:
  File "pokecli.py", line 41, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "E:\Bot\PokemonGo-Bot\pokemongo_bot\__init__.py", line 17, in <module>
    import cell_workers
ImportError: No module named 'cell_workers'

### Steps to Reproduce
Followed installation guide for Windows step-by-step with no errors up until I run (python pokecli.py)

### Other Information
OS: Windows 10 32bit
Python Version: Python 3.5.2

**Comment by ArdalanM** [comment]
Experienced same issue.

Switch to python 2.7. It solved the issue for me

**Comment by zdrgdr** [comment]
i got same error with python 2.7

**Comment by iHatePython** [comment]
Switching to Python 2.7.x fixed that error for me, thanks.

**Comment by zdrgdr** [comment]
deletec python 3.4 form my system and now i get his error: ImportError: 
No module named pgoapi.exceptions

**Comment by zdrgdr** [comment]
Solved: after removing python 3.4, i used  pip install -r requirements.txt  command in cmd
