### ISSUE TITLE
Update run with docker instructions

### ISSUE THREAD

**Issue by pan-long** [PokemonGoF/PokemonGo-Bot#2701]
### Expected Behavior
Bot is working

### Actual Behavior
Bot complaining couldn't find encrypt.so

### Steps to Reproduce
Follow the instructions [here](https://github.com/PokemonGoF/PokemonGo-Bot/wiki/How-to-run-with-Docker)

### Other Information
OS: OSX(docker)
Git Commit: ad6c21aa1dc0902c62e4001f9a81ce1fcd8a9f59

**Comment by lafin** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/pull/2695

**Comment by pan-long** [comment]
@lafin Thanks for that, I will then wait the PR to be merged and close this issue.

**Comment by acaranta** [comment]
btw, I tested the PR + my dockerfile modification, bot is currently running smoothly ;)

**Comment by pan-long** [comment]
@acaranta I just applied your PR and rebuild my docker. It doesn't work for me. It still gives me `OSError: encrypt.so: cannot open shared object file: No such file or directory` Any ideas?

**Comment by trademarrk** [comment]
$ docker build -t pokemongo-bot
"docker build" requires exactly 1 argument(s).
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

looking for some help dont really no how to get from this to 

docker run --name=pokego-bot1 --rm -it -v $(pwd)/configs/config-account1.json:/usr/src/app/configs/config.json pokemongo-bot

this is new to me, im a noob :(

**Comment by pan-long** [comment]
@trademarrk `docker build -t pokemongo-bot .' don't forget the `.` at the end.

**Comment by newjanson** [comment]
@acaranta I changed the dockerfile and rebuilt it, but I still get OSError: encrypt.so: cannot open shared object file: No such file or directory

**Comment by acaranta** [comment]
As said in my Dockerfile PR, it **needs** the #2643 PR to be applied, (at least the emodification to the init file ! otherwise, nope it will t work ;) sorry ;)) ..
What I did to try, run, and PR is to manually edit the init file in order for the encrypt.so file to be check "locally".

**Comment by trademarrk** [comment]
@pan-long thanks a lot, got past it now and the image is created (y), seemed to get this issue pokecli.py: error: argument -a/--auth_service is required

when i put in this 
docker run --name=pokego-bot1 --rm -it -v $(pwd)/configs/config-account1.json:/usr/src/app/configs/config.json pokemongo-bot
 I already edited the config.json though :S
