### ISSUE TITLE
pokecli.py: error: argument -a/--auth_service is required

### ISSUE THREAD

**Issue by EricFelbs** [PokemonGoF/PokemonGo-Bot#2703]
what em I doing wrong ?
 

pokecli.py: error: argument -a/--auth_service is required

### Other Information
OS: OS X

**Comment by plgonzalezrx8** [comment]
Are you passing the loging arguments? You have to select the type of account after "-a", the argument can be either "google" or "ptc"

**Comment by plgonzalezrx8** [comment]
I recommend using a config.json file instead of manually entering parameters when running the bot.

**Comment by saldanhaz** [comment]
Same problem here. ( pokecli.py: error: argument -a/--auth_service is required)
My config.json starts like this tho...
{
    "auth_service": "google",
    "username": "adrianosubzero@gmail.com",
    "password": "xxx",
    "location": "xxx",
    "gmapkey": "xxx",
     ......
}

**Comment by nivong** [comment]
follow the guide to post issues here this is an incomplete issue.
@brantje
