### ISSUE TITLE
windows run issue

### ISSUE THREAD

**Issue by NoProgramist** [PokemonGoF/PokemonGo-Bot#2705]
Here  http://pastebin.com/jraB1AyA is result of try run the bot.

**Comment by VinderOrnitier** [comment]
Same error on win10

**Comment by Youlilbotter** [comment]
I'm getting this as well

**Comment by agastimhatre** [comment]
1. Have you guys set health_record to false.

**Comment by Youlilbotter** [comment]
I didn't

**Comment by NoProgramist** [comment]
I have set healt_record to false. Now I'm getting this http://pastebin.com/J35XcEv0.

**Comment by Youlilbotter** [comment]
is it alrite if u throw my same thing here as well 
![whatsup](https://cloud.githubusercontent.com/assets/12982391/17461450/0c7a9a92-5cd0-11e6-9df6-7dd3a82fc22f.jpg)

**Comment by reside** [comment]
+1, same issue

**Comment by k4n30** [comment]
#2768

**Comment by nivong** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2780
