### ISSUE TITLE
WindowsError, other solutions didnt work

### ISSUE THREAD

**Issue by aviel600** [PokemonGoF/PokemonGo-Bot#2706]
**### Expected Behavior**
Bot run as expected

**### Actual Behavior**
**Drops error :** 

Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()
  File "C:\poke\PokemonGo-Bot\pokemongo_bot\metrics.py", line 76, in capture_sta
ts
    response_dict = request.call()
  File "C:\poke\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\poke\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "c:\users\aviel\desktop\pg\src\pgoapi\pgoapi\pgoapi.py", line 210, in cal
l
    request.activate_signature(lib_path)
  File "c:\users\aviel\desktop\pg\src\pgoapi\pgoapi\rpc_api.py", line 85, in act
ivate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError:

**### Steps to Reproduce**
downloaded the encrypt.dll , put it in the main folder and did as commanded in other thread : 

> might want to look into pokemongo_bot/__init__.py and change self.api.activate_signature("encrypt.so") to `self.api.activate_signature("./encrypt.dll")`

### Other Information
OS: win 7 64
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (2.7)

**Comment by Unscrupulor** [comment]
I have the same exact error, and a windows pops up saying 'ecrypt.so is not designed to run on windows or it contains an error.'

**Comment by agastimhatre** [comment]
@Unscrupulor you must be having encrypt.so in your root folder, delete it and then try, i m assuming you did followed all the above steps.

**Comment by dezayner** [comment]
I got this error

WindowsError: [Error 193] %1 is not a valid Win32 application

**Comment by Chris221** [comment]
You have to use the 64 bit version of encrypt.dll (encrypt64bit.dll on slack)

**Comment by aviel600** [comment]
@Chris221 where can i find it ?

**Comment by Calcyfer** [comment]
Here's a folder with the windows 32 and 64 bit : 
https://mega.nz/#fm/Jh1ijT5B

**Comment by dezayner** [comment]
@Chris221 Thanks for your suggestion. My bot is working now.

**Comment by aviel600** [comment]
Solved tnx to Chris221.

**Comment by NoProgramist** [comment]
@Chris221 @Calcyfer @aviel600 @dezayner could you reupload encrypt.dll ?

**Comment by Calcyfer** [comment]
@NoProgramist New link : https://mega.nz/#F!dpskCAga!pLw8ZdeF9cmbdHPnjgGJlg

**Comment by cswxin** [comment]
@Chris221 @Calcyfer could you guys reupload encrypt.dll please?

**Comment by Calcyfer** [comment]
@cswxin Here you go : https://mega.nz/#F!Q0cyhbIA!qTQQlkhhAv8ta0zjxyfhtA
