### ISSUE TITLE
No tasks and config even though there is

### ISSUE THREAD

**Issue by EthanXP** [PokemonGoF/PokemonGo-Bot#2707]
C:\Users\Ethan\PokemonGo-Bot>python pokecli.py -cf ./configs/config.json -a ptc
-u Classified -p Classified -l "40.780789302711135, -73.975492444657789"
2016-08-07 03:26:37,555 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 03:26:37,556 [       cli] [INFO] Error: No /configs/config.json or sp
ecified config
2016-08-07 03:26:37,559 [      root] [ERROR] No tasks are configured. Did you me
an to configure some behaviors? Read https://github.com/PokemonGoF/PokemonGo-Bot
/wiki/Configuration-files#configuring-tasks for more information

Any help?

**Comment by gilgo** [comment]
same problem here

**Comment by gilgo** [comment]
@EthanXP i tried reinstalling from scratch (i had a problem with installing requirements aswell), i still get an error but a different one - might work for you tho

**Comment by k4n30** [comment]
@EthanXP Are you still experiencing this issue? If so can you post your complete config with username, password and gmapkey removed. Also please indicate what release / branch / commit you are using
