### ISSUE TITLE
UnboundLocalError: local variable 'bot' referenced before assignment

### ISSUE THREAD

**Issue by 15calderm** [PokemonGoF/PokemonGo-Bot#2708]
### Expected Behaviour
Bot to run as normal.

### Actual Behavior
Get:
"UnboundLocalError: local variable 'bot' referenced before assignment"
When running pokecli.py

### Steps to Reproduce
run pokecli.py

### Other Information
OS: Win10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by agastimhatre** [comment]
check this https://github.com/PokemonGoF/PokemonGo-Bot/issues/2657

**Comment by nivong** [comment]
read the issue template and try again..
