### ISSUE TITLE
Maximising Lvling

### ISSUE THREAD

**Issue by MettheRZ** [PokemonGoF/PokemonGo-Bot#271]
How to set --maxstep MAX_STEP to maximise my XP? Is default "5" good for intense lvling?

**Comment by MettheRZ** [comment]
I live in Słubice-Frankfurt Oder and there I have big area with pokestops, gyms etc.

**Comment by myeunggithub** [comment]
Default is fine.

On another note, please refrain from using the Issues tab to ask for advice. It is for problems/bugs with the code, so that the devs can make changes accordingly.

**Comment by douglascamata** [comment]
Closing this.
