### ISSUE TITLE
Message "Inventory Full" while more than 100 slots over.

### ISSUE THREAD

**Issue by M3NTI0N** [PokemonGoF/PokemonGo-Bot#2724]
### Expected Behavior
Just loot pokestops until the bag is full. 

### Actual Behavior
Tells me that the bags are full while there are still atleast 100 slots open.

Shows message:
2016-08-07 11:16:17,527 [MoveToFort] [INFO] [inventory_full] Not moving to any forts as there aren't enough space. You might want to change your config to recycle more items if this message appears consistently.

### Other Information
OS: Linux 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Git Commit: a05b542ea71172556cf0eb0e00cbe665607c4319
Python Version: Python 2.7.12

**Comment by chinkong83** [comment]
I also have the same problem

**Comment by LDengX** [comment]
Can you check if it's the same issue as https://github.com/PokemonGoF/PokemonGo-Bot/issues/2942 ?
Probably only config "Pokeball", but no "GreatBall" etc?
