### ISSUE TITLE
script\activate command not found

### ISSUE THREAD

**Issue by danko16** [PokemonGoF/PokemonGo-Bot#2725]
Owner@Owner-PC MINGW64 ~/PokemonGo-bot (master)
$ script\activate
bash: scriptactivate: command not found

Owner@Owner-PC MINGW64 ~/PokemonGo-bot (master)
$ script\activate
bash: scriptactivate: command not found

please help

**Comment by Kalashnikitty** [comment]
scripts not script

**Comment by dimasnp** [comment]
`Scripts\activate`

**Comment by danko16** [comment]
just same

Owner@Owner-PC MINGW64 ~/pokemongo-bot (master)
$ scripts\activate
bash: scriptsactivate: command not found

Owner@Owner-PC MINGW64 ~/pokemongo-bot (master)
$ scripts\activate
bash: scriptsactivate: command not found

**Comment by Kalashnikitty** [comment]
use scripts/activate

**Comment by dimasnp** [comment]
```
$ git clone -b master https://github.com/PokemonGoF/PokemonGo-Bot  
$ cd PokemonGo-Bot
$ virtualenv .
$ scripts\activate  
$ pip2 install -r requirements.txt
$ git submodule init
$ git submodule update
```

**Comment by Yanush7** [comment]
@Kalashnikitty is right, different slash:
use scripts**/**activate (not scripts**\**activate)

**Comment by danko16** [comment]
Owner@Owner-PC MINGW64 ~/pokemongo-bot (master)
$ scripts/activate
bash: scripts/activate: No such file or directory

Owner@Owner-PC MINGW64 ~/pokemongo-bot (master)
$ script/activate
bash: script/activate: No such file or directory

another step is ok , just this script activate that cannot execute

**Comment by Kalashnikitty** [comment]
because u are using the wrong branch -> use dev branch on windows

**Comment by Gandaflux** [comment]
there is no folder named scripts, and activate is in bin, maybe its about that file?
It should be run using:

source bin/activate

**Comment by Decimation** [comment]
I fixed it by doing this:

`cd Scripts`

`activate`

**Comment by rajuraj8881** [comment]
Use::
. \Scripts\activate
