### ISSUE TITLE
Writing Logs to external file/s

### ISSUE THREAD

**Issue by NicholasMolenaar** [PokemonGoF/PokemonGo-Bot#2729]
### Expected Behavior
We used to be able to separate output log, info & exception info to different logs (with for example supervisor) std_err & std_out.

```
while true; do
pkill -f pokecli
eval "python pokecli.py --config configs/config.json >> logs/log.txt" &
eval "python pokecli.py --config configs/config1.json >> logs/log1.txt" &
sleep 1800
done
```

I'm using this bash script for restarting the bots every 30 minutes. It used to keep the logs in the separate files but i guess after the changes to the logging logic it doesn't do the same. I call my bash script with this command.
"nohup ./run.sh >> logs/restart.txt &"
it was logging the exceptions into "restart.txt" and other stuff into respective log files but not anymore. Everything goes into restart.txt right now.

Can we add a config option like "pathToLogFile: './logs/log.txt'" and keep the logs in there? It may work as now when this config is not specified or false.

Edited by mod: To clarify other user wanted features

**Comment by NicholasMolenaar** [comment]
I think you can change the behaviour by changing:
`logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(name)10s] [%(levelname)s] %(message)s')`

to:

`logging.basicConfig(
    level=logging.INFO,
    stream=sys.stdout,
    format='%(asctime)s [%(name)10s] [%(levelname)s] %(message)s')`

**Comment by k4n30** [comment]
@NicholasMolenaar Are you still experiencing this issue? If so can you please indicate what release / branch / commit you are using.

**Comment by NicholasMolenaar** [comment]
@k4n30 Yes i still exp. this problem. master branch - d90a203194bbf97d06c66f1f6325c4576c8f8dde

**Comment by IceBreeze** [comment]
I use this in pokecli.py:

```py
from datetime import timedelta, datetime
[...]
# set up logging to file (filename: "bot_YYYYMMDD.log")
logging.basicConfig(
    filename=datetime.now().strftime('bot_%Y%m%d.log'),
    level=logging.INFO,
    format='%(asctime)s [%(levelname).3s] [%(name)10s] %(message)s')
logger = logging.getLogger('cli')
logger.setLevel(logging.INFO)

# set up logging to console
console = logging.StreamHandler()
console.setLevel(logging.INFO)
formatter = logging.Formatter('%(asctime)s [%(levelname).3s] [%(name)10s] %(message)s')
console.setFormatter(formatter)
# add console to root logger
logging.getLogger('').addHandler(console)
```
These settings log bot to console and screen, rotating the file daily.

It also changes a the formatter from

```
'%(asctime)s [%(name)10s] [%(levelname)s] %(message)s'
```

to

```
'%(asctime)s [%(levelname).3s] [%(name)10s] %(message)s'
```

resulting in this type of log:

```
2016-01-01 01:20:01,051 [INF] [PokemonCatchWorker] [threw_pokeball] Used Pokeball, with chance 100.00 (14 left)
2016-01-01 01:20:02,052 [INF] [PokemonCatchWorker] [pokemon_caught] Captured Pidgey! [CP 20] [Potential 0.31] [5/7/2] [+100 exp]
2016-01-01 01:20:03,053 [INF] [PokemonCatchWorker] [gained_candy] You now have 123 Pidgey candy!
2016-01-01 01:20:04,054 [INF] [MoveToFort] [moving_to_fort] Moving towards pokestop XXXXXXXXXXXXXXXXXXXX - 0.06km
2016-01-01 01:20:05,055 [INF] [NicknamePokemon] [rename_pokemon] Pokemon Pidgey renamed to Pidgey031
```

The drawback is that you get color codes inside the log file, but i like it I need to "cat" or "less -R" the log.

**Comment by k4n30** [comment]
@IceBreeze are you able to make a Pull Request? It would be greatly appreciated

**Comment by IceBreeze** [comment]
Yes I can, but not right now. I think I can do it in a few hours.

**Comment by k4n30** [comment]
No rush, just ensure you include this issue in the "closes" area so it will close when it's merged :)

**Comment by oralunal** [comment]
@NicholasMolenaar are you still experiencing this issue?
