### ISSUE TITLE
Bot didnt catch pokemons, just walking and spinning pokestops

### ISSUE THREAD

**Issue by MettheRZ** [PokemonGoF/PokemonGo-Bot#273]
### Expected Behavior
Pokemons are being catched

### Actual Behavior
Bot didnt catched any pokemon in 30 minutes

Help me plz

**Comment by VirtualSatai** [comment]
Consider providing some debug logs (run with the argument "-d"), this makes it easier for other people to help you.

**Comment by Razapo** [comment]
What version of the bot are you using and also what string of commands are you typing in?

**Comment by Maximum-throwaway** [comment]
I personally have the opposite problem, and I know there are a handful of pokestops very close.

Using the -m switch on the latest master branch doesn't work.

~/gitrepos/PokemonGo-Bot$ ./pokecli.py -a google -u $foo -p $bar -l $foobar -w 30 -m "all"
[x] Initializing PokemonGO Bot v1.0
[x] PokemonGo Bot [@PokemonGoF | @eggins | @crack00r | @ethervoid | /r/pokemongodev]
usage: pokecli.py [-h] -a AUTH_SERVICE -u USERNAME -p PASSWORD -l LOCATION
                  [-s] [-v] [-w WALK] [-c CP] [-k GMAPKEY]
                  [--maxsteps MAXSTEPS] [-d] [-t]
pokecli.py: error: unrecognized arguments: -m all

'-m farm' doesn't work either.

**Comment by ckrmml** [comment]
It's not implemented in master, use latest dev or -s variable

**Comment by Maximum-throwaway** [comment]
Ah. I assumed it was in master because README.md said it was available and poking around pokecli.py in github shows it.

What I didn't notice was that github was showing me the dev branch. :^)

**Comment by surfaace** [comment]
catching pokemon in dev branch f1933d3089b340392780da8fc9356e84e2fa2bf8
