### ISSUE TITLE
Issue running docker image.

### ISSUE THREAD

**Issue by Newbie4124** [PokemonGoF/PokemonGo-Bot#2731]
Hello, I am having an issue where PowerShell will not be able to run the command "docker run --name=pokego-bot1 --rm -it -v $(pwd)/configs/config-account1.json:/usr/src/app/configs/config.json pokemongo-bot".... it tells me to do docker run --help for more information. MAy anyone help me fix this issue?

**Comment by k4n30** [comment]
@Newbie4124 Are you still experiencing this issue? If so can you post your complete config with username, password and gmapkey removed. Also please indicate what release / branch / commit you are using.

**Comment by leadboots5** [comment]
There have been 4 docker related merges since this was opened. I am going to close it, please do git a pull and open a new issue if you're having trouble.
