### ISSUE TITLE
Doens't catch pokemon after a while

### ISSUE THREAD

**Issue by OniZakuma** [PokemonGoF/PokemonGo-Bot#2735]
### Expected Behavior
Walking around and keep catching pokemon.

### Actual Behavior
Catches pokemon at start, but after a while only runs around to pokestops.

### Steps to Reproduce
Start it. (near East Village, New York)

### Other Information
OS: Windows 10
Git Commit: 85f7607c6fbc7e4b13dc370877f01f45c5e241af
Python Version: Python 2.7.11
Config: https://we.tl/wxfoTKqph4
Release: dev

Restarting the bot helps for a few minutes, but then it goes back to just walking.
It's set to catch all pokemon, and discard everything but top IV or CP.

**Comment by hew-xavier** [comment]
Duplicate #2698

**Comment by NicholasMolenaar** [comment]
Please for feature reports try to use pastebin.com for small / medium sized text files.
