### ISSUE TITLE
Guys, Please Help ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by jninsong** [PokemonGoF/PokemonGo-Bot#2736]
C:\Users\USER\PokemonGo-Bot>python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "c:\users\user\pokemongo-bot\src\pgoapi\pgoapi\__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "c:\users\user\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "c:\users\user\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "c:\users\user\pokemongo-bot\src\pgoapi\pgoapi\utilities.py", line 30, in <module>
    import xxhash
ImportError: DLL load failed: %1 is not a valid Win32 application.

I'm using python-2.7.12.amd64(Downloaded file) and Git-2.9.2-64-bit

**Comment by NicholasMolenaar** [comment]
Could you please update your issue with the reporting template. at least include the Python version  and git commit.

**Comment by tomalbrc** [comment]
Do you have the encrypt.dll for your architecture in your `PokemonGo-Bot` folder?

**Comment by jninsong** [comment]
yes I did have it. I'm running 2.7.12 64 bit, same with git 64bit

**Comment by jninsong** [comment]
@NicholasMolenaar I'm using python-2.7.12.amd64(Downloaded file) and Git-2.9.2-64-bit
@tomalbrc  yes I have the encrypt.dll on,

**Comment by dezayner** [comment]
@jninsong  you must change into valid DLL file. I already tried several DLLs until my bot was working

**Comment by shmily1140** [comment]
@dezayner  can you tell me where i can find encrypt.dll file?  i am using python 2.7.9

**Comment by dezayner** [comment]
#2706

**Comment by k4n30** [comment]
#2768
