### ISSUE TITLE
UnboundLocalError: local variable 'bot' referenced before assignment

### ISSUE THREAD

**Issue by arkriloth** [PokemonGoF/PokemonGo-Bot#2741]
### Upon running master branch:
$ ./run.sh
2016-08-07 18:03:59,911 [       cli] [INFO] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 126, in main
    if bot:
UnboundLocalError: local variable 'bot' referenced before assignment

### Other Information
OS: Windows 10
Git Commit: ad6c21aa1dc0902c62e4001f9a81ce1fcd8a9f59
Python Version: 2.7.12

**Comment by loklam** [comment]
I got this error before, when the config file have syntax error, missing a comma. Suggest u check ur config file.

**Comment by arkriloth** [comment]
thanks!

**Comment by k4n30** [comment]
@arkriloth Can this be closed?

**Comment by arkriloth** [comment]
yup
