### ISSUE TITLE
NicknamePokemon task is ignored

### ISSUE THREAD

**Issue by MRokas** [PokemonGoF/PokemonGo-Bot#2742]
### Expected Behavior
It should rename pokemons

### Actual Behavior
It doesn't

### Steps to Reproduce
Include ```
      {
        "type": "NicknamePokemon",
        "nickname_template": "{cp}_{iv_pct}"
      }```

in config.json at taskss, run bot and pay attention to output.

### Other Information
OS: Ubuntu 14
Git Commit: ad6c21aa1dc0902c62e4001f9a81ce1fcd8a9f59
Python Version:  2.7

**Comment by MRokas** [comment]
oh, ty!

**Comment by Eastkap** [comment]
task must be placed above the TransferPokemon task btw (per the spec), this could also cause the malfunction

**Comment by ahammond** [comment]
This really suggests a doc fix.
