### ISSUE TITLE
How do i update the bot ( dev branch )

### ISSUE THREAD

**Issue by Parth6182** [PokemonGoF/PokemonGo-Bot#2746]
How do i update my bot from what it was 2 days ago to the new version

Do i also have to update python and stuff? The bit was working b4 the new Api

Please let me know the changes i have to make to use the bot again :D

**Comment by tomalbrc** [comment]
Add encrypt.so or encrypt.dll (depending on platform) to the `PokemonGo-Bot` folder
use `git pull` to update
be sure to `checkout` the `dev` branch tho

**Comment by Parth6182** [comment]
... Thanks for the info but i didn't understand :( 
could you tell me stuff like make this file
run this in the terminal or stuff like that I'm just 15 and want the bot to work i don't understand that stuff ^ srry

**Comment by Parth6182** [comment]
So hmm i make a file called encrypt.dll ( mac ) in my pokemongo-bot folder
then i run the like ( git pull ) in my terminal ?
and thats it?

**Comment by tomalbrc** [comment]
On mac and linux you need encrypt.so
We can't provide the file here because it contains copyrighted code

**Comment by Philipp59** [comment]
but you could link to the site ;)

**Comment by tomalbrc** [comment]
Not sure if this is allowed but here your go: encrypt.so for OS X 64bit  (SHASUM: 1e9b7e25f176a02a427e3d1963aa1033b21e2bf8)

http://www.mediafire.com/download/engnf5fvj65duxa/encrypt.so

**Comment by JaydenHamence** [comment]
thanks working finally

**Comment by Parth6182** [comment]
This happened : 

Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: cannot import name ServerSideRequestThrottlingException

**Comment by nightlydoesmodz** [comment]
@Parth6182  i got the same thing

**Comment by shmily1140** [comment]
@Parth6182  would you teach me how i can get encrypt.dll?  i am using windiwos.

**Comment by Parth6182** [comment]
@tomalbrc Do you have any idea about how to fix this issue

> Traceback (most recent call last):
File "pokecli.py", line 38, in 
from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: cannot import name ServerSideRequestThrottlingException

**Comment by m-a-g-o** [comment]
I have the same error on win7:
Traceback (most recent call last):
File "C:\git\version-control\newapipkmgo\PokemonGo-Bot\pokecli.py", line 38, in
from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: cannot import name ServerSideRequestThrottlingException

Someone know how to solve this error? (I tried to remove the ServerSideRequestThrottlingException but then I got other import problems in other files...)

**Comment by nivong** [comment]
please close the issue if it's fixed, for others:
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2780

**Comment by swangaa** [comment]
what is a git pull?

**Comment by nivong** [comment]
@swangaa if you pay me I will teach you tricks (small hint it includes how to use google!)
