### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by mztriz** [PokemonGoF/PokemonGo-Bot#275]
### Expected Behavior
`./pokecli.py -a google -u myuser -p mypass -l 10.2873,-11.3210 -w 4  -c 200`
- Log me in and begin

### Actual Behavior

> [x] Position in-game set as: ( 10.2873, -11.3210, 0.0)
> 2016-07-22 15:42:34,017 [auth_google] [ INFO] Google login for: myuser
> Traceback (most recent call last):
>   File "./pokecli.py", line 124, in <module>
>     main()
>   File "./pokecli.py", line 116, in main
>     bot.start()
>   File "/Users/myuser/Scripts/git/PokemonGo-Bot/bot.py", line 25, in start
>     self._setup_api()
>   File "/Users/myuser/Scripts/git/PokemonGo-Bot/bot.py", line 87, in _setup_api
>     if not self.api.login(self.config.auth_service, self.config.username, self.config.password):
>   File "/Users/myuser/Scripts/git/PokemonGo-Bot/pgoapi/pgoapi.py", line 179, in login
>     if not self._auth_provider.login(username, password):
>   File "/Users/myuser/Scripts/git/PokemonGo-Bot/pgoapi/auth_google.py", line 45, in login
>     login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
>   File "/usr/local/lib/python2.7/site-packages/gpsoauth/__init__.py", line 66, in perform_master_login
>     return _perform_auth_request(data)
>   File "/usr/local/lib/python2.7/site-packages/gpsoauth/__init__.py", line 22, in _perform_auth_request
>     headers={'User-Agent': useragent})
>   File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 111, in post
>     return request('post', url, data=data, json=json, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
> 

### Other Information
OS: Darwin mypc 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:48:19 PDT 2016; root:xnu-3248.60.10~2/RELEASE_X86_64 x86_64
Git Commit: c0d62595a999a7a3359b72897c10f8e9f9a8427c

**Comment by jplusc** [comment]
login servers are currently down, where you able to log in before with the bot, or is this your first attempt?

**Comment by mztriz** [comment]
I am able to log into the game with no issues.

**Comment by VirtualSatai** [comment]
@jplusc Only PTC login is down, Google login is fine.

**Comment by ckrmml** [comment]
@VirtualSatai are you sure about that? 
PTC won't work with phone nor with the bot for me right now, 
Google works on phone but till now not once worked with the bot. It always tells me `Login Error, server busy`

**Comment by VirtualSatai** [comment]
@ckrmml I was just going by http://ispokemongodownornot.com/ and my own exp, didn't try it with the bot, was just talking in general.

**Comment by ckrmml** [comment]
@VirtualSatai Nice site, i was watching this on http://www.mmoserverstatus.com/pokemon_go but as of now i'm unable to login via PTC

**Comment by surfaace** [comment]
loginservers was probably overloaded.

**Comment by mztriz** [comment]
Still experiencing this issue. It is not from the login servers.

**Comment by surfaace** [comment]
2step auth?

**Comment by mztriz** [comment]
No, I don't have 2 factor auth set up on my account.

**Comment by ckrmml** [comment]
i had an escape chracter in my pw which i had to escape -.- so look out if you have \ in your pw and escape, aka \\. worked for me

**Comment by zhudan** [comment]
same error！
because use https_proxy!   eg: [xx-net](https://github.com/XX-net/XX-Net)

i think @mztriz can support proxy! 

i'am in china, Google service can not use! play this game must use proxy.  

so, please support it! thinks! @mztriz

**Comment by surfaace** [comment]
@mztriz  are you also going through proxy?

**Comment by zhudan** [comment]
@surfaace when i use the proxy， the error 。。again and again!

 Google service can not be reached in China，because the GFW block it。

**Comment by surfaace** [comment]
supporting http proxy is on the todo list
