### ISSUE TITLE
Error: No /configs/config.json or specified config

### ISSUE THREAD

**Issue by htugsdr** [PokemonGoF/PokemonGo-Bot#2756]
I keep getting when i try to run the bot

$ python pokecli.py -cf ./configs/config.json -a "ptc"
2016-08-07 20:10:38,270 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 20:10:38,271 [       cli] [INFO] Error: No /configs/config.json or specified config
Username: flambam
Password: Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 132, in main
    raise e
IOError: [Errno 22] Invalid argument

OS: mac osx
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by htugsdr** [comment]
![screen shot 2016-08-07 at 20 11 14](https://cloud.githubusercontent.com/assets/20790788/17461983/bcb1587c-5cdc-11e6-9509-efd294bef719.png)

**Comment by SGColdSun** [comment]
don't use a ./

python pokecli.py -cf configs/config.json -a "ptc"

**Comment by htugsdr** [comment]
thats what i have it my folder idk why it cant find it

**Comment by htugsdr** [comment]
just tried what you suggested it still got the same thing

**Comment by Philipp59** [comment]
python pokecli.py -cf configs/config.json

**Comment by htugsdr** [comment]
cheers philipp59 but still got this: 
$ python pokecli.py -cf configs/config.json
2016-08-07 20:25:35,466 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 20:25:35,468 [       cli] [INFO] Error: No /configs/config.json or specified config
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-ws WEBSOCKET.SERVER_URL]
                  [-wss WEBSOCKET.START_EMBEDDED_SERVER]
                  [-wsr WEBSOCKET.REMOTE_CONTROL] [-p PASSWORD] [-l LOCATION]
                  [-lc LOCATION_CACHE] [--forts.spin FORTS.SPIN] [-w WALK]
                  [-k GMAPKEY] [-e SHOW_EVENTS] [-d DEBUG] [-t TEST]
                  [-du DISTANCE_UNIT] [-ec EVOLVE_CAPTURED]
                  [-rt RECONNECTING_TIMEOUT] [-hr HEALTH_RECORD]
                  [-ac FORTS.AVOID_CIRCLES] [-mcs FORTS.MAX_CIRCLE_SIZE]
                  [--catch_randomize_reticle_factor CATCH_RANDOMIZE_RETICLE_FACTOR]
                  [--catch_randomize_spin_factor CATCH_RANDOMIZE_SPIN_FACTOR]
                  [--map_object_cache_time MAP_OBJECT_CACHE_TIME]
pokecli.py: error: argument -a/--auth_service is required

**Comment by Philipp59** [comment]
`pokecli.py: error: argument -a/--auth_service is required`

**Comment by htugsdr** [comment]
![screen shot 2016-08-07 at 20 28 25](https://cloud.githubusercontent.com/assets/20790788/17462008/8a8014aa-5cdd-11e6-9f40-d4077e89401c.png)
i have that in the config.json

**Comment by htugsdr** [comment]
i havent touched any other .json.x.examples if that changes anything nor have i tampered with path.example.json

**Comment by pierobj** [comment]
Same error here on Mag OS X.

**Comment by Philipp59** [comment]
![bildschirmfoto 2016-08-07 um 13 04 49](https://cloud.githubusercontent.com/assets/20689345/17462039/b0c5dd2c-5c9f-11e6-8ed5-967cb6756250.png)

check this pls under properties that it is really .json

**Comment by htugsdr** [comment]
yes it is
![screen shot 2016-08-07 at 20 37 56](https://cloud.githubusercontent.com/assets/20790788/17462045/e61d0bbe-5cde-11e6-8bdf-8b69c8cfb494.png)

**Comment by Philipp59** [comment]
and just `python pokecli.py ` ? Maybe if you are using config.json you do not need -cf, but its really strange at all

**Comment by Philipp59** [comment]
maybe set the whole bot new up ? : D
or try git pull and pip install --upgrade -r requirements.txt

**Comment by jbwettergreen** [comment]
I'm having the exact same issue when using google as authenticator. 

"Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 132, in main
    raise e
ValueError: Invalid control character at: line 3 column 50 (char 81)"

**Comment by htugsdr** [comment]
okay how am i gonna go about uninstalling everything because upgrading the bot hasnt worked for me either

**Comment by Philipp59** [comment]
just copy your encrypt.so and config.json out then delete the rest and paste them in after new installation.

```
$ git clone --recursive -b dev https://github.com/PokemonGoF/PokemonGo-Bot  
$ cd PokemonGo-Bot  
$ virtualenv .  
$ source bin/activate  
$ pip install -r requirements.txt
```

**Comment by htugsdr** [comment]
okay ill give it a try

**Comment by htugsdr** [comment]
okay found i was editing files in a completely wrong folder and i wasnt even in the actual root directory so just make sure you are editing the right folder peeps. its all g now.
