### ISSUE TITLE
Stuck at the docker started part

### ISSUE THREAD

**Issue by spdragon** [PokemonGoF/PokemonGo-Bot#2757]
`$ docker run --name=pokego-bot1 --rm -it -v $(pwd)/configs/config-account1.json:/usr/src/app/configs/config.json pokemongo-bot
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
`
what to do with this?

**Comment by RobertHaitsma** [comment]
Same here

**Comment by tristo7** [comment]
I get the same error as well. Docker image was created.
