### ISSUE TITLE
Can any one told where i can download encrypt.dll for windows? 

### ISSUE THREAD

**Issue by shmily1140** [PokemonGoF/PokemonGo-Bot#2758]
### Expected Behavior
Bot running 

### Actual Behavior
RuntimeError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 127, in main
    report_summary(bot)
  File "pokecli.py", line 136, in report_summary
    metrics.capture_stats()

### Steps to Reproduce
Python pokelcli.py

### Other Information
OS: Win 8.1
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here) 2.7.10

**Comment by shmily1140** [comment]
no one... i cannot find .dll file...

**Comment by BobbyWibowo** [comment]
You can look at the Slack channel: https://pokemongo-bot.slack.com/

**Comment by brantje** [comment]
#2780

**Comment by CoderFX** [comment]
@BobbyWibowo
Can you post normal instructions instead of private group link that nobody can get into?

**Comment by BobbyWibowo** [comment]
@CodeFX I'm pretty sure that's the official Slack group for PokemonGo-Bot. And to be honest, I couldn't remember how I got the invitation link so I just left the group link there, in assumption that people had already joined somehow.
