### ISSUE TITLE
Bot Failing to start

### ISSUE THREAD

**Issue by gforpokemon** [PokemonGoF/PokemonGo-Bot#2759]
### Expected Behavior
Bot running

### Actual Behavior

![err](https://cloud.githubusercontent.com/assets/20886183/17462013/5b941084-5c96-11e6-8215-d6486128f92d.png)

### Steps to Reproduce
Python pokelcli.py

### Other Information
OS: Win 10
Same On Branch Dev or Master
(health_record : false in config.json)
It sign's in successfully but fails here. Visual C++ compiler for python is installed! Any suggestions?

**Comment by gforpokemon** [comment]
### Update 
I downloaded encrypt.dll from here : 
32 Bit : https://www.sendspace.com/file/bq0hcn
64 Bit : https://pokemongo-bot.slack.com/files/pgofan/F1Z0H2PFY/encrypt.so.dll (On windows, rename from encrypt.so.dll tp encrypt.dll)

and pasted in the root directory. 

Then I made the change to __int__.py in pokemon_bot directory, from 
  self.api.activate_signature("encrypt.so") to self.api.activate_signature("./encrypt.dll")

Works like a charm.

**Comment by helmut1337** [comment]
Make sure you edited your pokemongo_bot\__init__.py Line 603 "encrypt.so" to "encrypt.dll"

Also make sure the correct encrypt.dll is placed in your "PokemonGo-Bot-master" root folder

x64 encrypt.dll : http://www.xup.in/dl,24825511/encrypt.dll/
x86 encrypt.dll: http://www.xup.in/dl,18495488/encrypt.dll/
