### ISSUE TITLE
In mode "all" combat should not be engaged unless there are PokéBalls available.

### ISSUE THREAD

**Issue by VirtualSatai** [PokemonGoF/PokemonGo-Bot#276]
### Expected Behavior
Don't engage combat unless the Pokémon could be caught. 

### Actual Behavior
Endless loop (Until pokemon despawn i presume)
```
[#] A Wild Drowzee appeared! [CP 131]
[x] Out of pokeballs...
[#] A Wild Drowzee appeared! [CP 131]
[x] Out of pokeballs...
[#] Something rustles nearby!
[#] A Wild Drowzee appeared! [CP 131]
[x] Out of pokeballs...
[#] A Wild Drowzee appeared! [CP 131]
[x] Out of pokeballs...
[#] Something rustles nearby!
[#] A Wild Drowzee appeared! [CP 131]
[x] Out of pokeballs...
[#] A Wild Drowzee appeared! [CP 131]
[x] Out of pokeballs...
[#] Something rustles nearby!
[#] A Wild Drowzee appeared! [CP 131]
[x] Out of pokeballs...
[#] A Wild Drowzee appeared! [CP 131]
[x] Out of pokeballs...
[#] Something rustles nearby!
[#] A Wild Drowzee appeared! [CP 131]
[x] Out of pokeballs...
[#] A Wild Drowzee appeared! [CP 131]
[x] Out of pokeballs...
[#] Something rustles nearby!
```

### Steps to Reproduce
Run the bot for long enough for it to run out of PokéBalls, then it will enter a loop.

### Other Information
OS: Ubuntu 16.04
Git Commit: 345ccb8f7b1e9609a768b9d0fc7d2754b0d86f92
"mode": "all"

**Comment by zx900930** [comment]
same problem here with "mode": "farm" ,  dev commit: 6199d49  

`[#] A Wild Pidgey appeared! [CP 60]
[x] Out of pokeballs...
[#] A Wild Pidgey appeared! [CP 60]
[x] Out of pokeballs...
[#] Something rustles nearby!
[#] A Wild Rattata appeared! [CP 125]
[x] Out of pokeballs...
[#] A Wild Rattata appeared! [CP 125]
[x] Out of pokeballs...
[#] Something rustles nearby!
[#] A Wild Pidgey appeared! [CP 60]
[x] Out of pokeballs...
[#] A Wild Pidgey appeared! [CP 60]
[x] Out of pokeballs...
[#] Something rustles nearby!
[#] A Wild Rattata appeared! [CP 125]
[x] Out of pokeballs...
[#] A Wild Rattata appeared! [CP 125]
[x] Out of pokeballs...`

**Comment by VirtualSatai** [comment]
Closed in https://github.com/PokemonGoF/PokemonGo-Bot/pull/333
