### ISSUE TITLE
Can't start bot on OS X (both dev and master)

### ISSUE THREAD

**Issue by iruy** [PokemonGoF/PokemonGo-Bot#2763]
### Expected Behavior
Start the bot

### Actual Behavior
Added library encrypt.so but still getting this error in
```
OSError: dlopen(encrypt.so, 6): no suitable image found.  Did find:
	encrypt.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```
### Steps to Reproduce
Tried both manual downloading and git , but get the same error.
`health_record` is set to `false`

### Other Information
OS: OS X El Capitan

**Comment by tomalbrc** [comment]
Wrong encrypt.so, see #2746

**Comment by iruy** [comment]
Thanks, working now!
