### ISSUE TITLE
bot doesnt catch lured pokemon

### ISSUE THREAD

**Issue by JaydenHamence** [PokemonGoF/PokemonGo-Bot#2774]
### Expected Behavior
detects and catches lured pokemon

### Actual Behavior
2016-08-07 21:32:36,524 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort Rhythms of the Metropolis (a9ab130b6fbf44e4b1224b34f57b96e9.11)
detects pokemon and doesnt try and catch
OS: OSX

**Comment by beranPro** [comment]
same here

**Comment by andriiaveiro** [comment]
same to me

**Comment by hackenho** [comment]
As far as I understand, it catches the Pokémon, it just delegate the task to `PokemonCatchWorker` which makes it look like it didn't.

If you notice the logs, after the lured_pokemon_found shows, there is almost all the time PokemonCatchWorker logs.

**Comment by kanemasa1987** [comment]
I had same issue, but it seems to have been solved by this.
https://github.com/PokemonGoF/PokemonGo-Bot/pull/2771

**Comment by firzzen** [comment]
I'm getting the same issue and no, the bot is not catching the lured pokemons. Just walks by them.

**Comment by JaydenHamence** [comment]
for me now it doesnt seem to even detect lured pokemon

**Comment by RovingSpirit** [comment]
Same here

**Comment by flippamike** [comment]
Any update on this, having this update a.t.m
