### ISSUE TITLE
Which dll/so?

### ISSUE THREAD

**Issue by ckrmml** [PokemonGoF/PokemonGo-Bot#2778]
Could anyone update the README so that it's clear what is needed?

```
Where to get the dll/so ? A help channel is comming.

You need grab them from internet.
```

is simply not enough

**Comment by tomalbrc** [comment]
The most painless way for Linux/ OS X users is this

Run: `wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make && mv libencrypt.so encrypt.so`
Then copy encrypt.so into your bots main folder, done

**Comment by brantje** [comment]
We can't provide them directly, however, users in the slack channel can help you here.

**Comment by michihu** [comment]
ok heres the full way for mac users:

1) in terminal:

brew install wget


2) cd PokemonGo-Bot

3) wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make && mv libencrypt.so encrypt.so

4) search in finder for file encrypt.so and copy it into the PokemonGo-Bot folder

5) start bot, should work

**Comment by tomalbrc** [comment]
##Here's a more optimized command
cd into PokemonGo-Bot folder
`cd PokemonGo-Bot`
### This command is optional if wget is already installed:
`brew install wget`
### Then run
`wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make && mv libencrypt.so ../../encrypt.so`

###Bot should work

**Comment by jgarci33** [comment]
how do i do this for windows?
