### ISSUE TITLE
Multiple items from pokestops

### ISSUE THREAD

**Issue by Razapo** [PokemonGoF/PokemonGo-Bot#278]
### Expected Behavior
Display the correct amount of items when a multiple of the same item is given from a pokestop.

### Actual Behavior
```
- Loot:
- 50 xp
- 1x Revive
- 1x Potion
```

### Steps to Reproduce
Run the bot wait for it to spin a pokestop and no matter how many multiple items the stop may give you the bot always says 1x (Item).

**Comment by Klohto** [comment]
#236 Thanks, was too lazy to edit my post

**Comment by Razapo** [comment]
@Klohto No Problem. Saw you're issues a few minutes before I posted this however, with it being a few hours since you posted it I decided to create a new one with more detail. If you want to you can close the issue or just copy and paste this issue into yours.
