### ISSUE TITLE
[PSA] Read this before creating an issue

### ISSUE THREAD

**Issue by brantje** [PokemonGoF/PokemonGo-Bot#2780]
Hi all!
As you might noticed the bot started to work again.
However thing are more complicated then they've been.

I would like to ask you **NOT** to create any **how to / help** issues.
Those issue's will be closed without further comment.
Please be patient, and give us time to update the wiki.

**Comment by nivong** [comment]
Add a few when new noob posts arrive I will reference this post so you can close them.

**Comment by nivong** [comment]
Add a few when new noob posts arrive I will reference this post so you can close them.

**Comment by frossaren** [comment]
Do we know anything about how long time it will take untill the wiki is updated?

**Comment by nivong** [comment]
working on it if you can help out it will take less time ;)

**Comment by BobbyWibowo** [comment]
@brantje Should questions be asked here instead? Well, at least for the time being.
cc: @brambi

**Comment by brantje** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2808

**Comment by cicatiello** [comment]
@brantje TL;DR we need to compile encrypt.dll base on the code hosted on http://pgoapi.com/ ?

**Comment by BobbyWibowo** [comment]
@cicatiello You can get the compiled version from the Slack group though. Not sure how I got the invitation link to the group, but I got my copies from there.

**Comment by cicatiello** [comment]
@BobbyWibowo shouldn't be easier to just throw them on dev branch? legal issue ftw?

**Comment by BobbyWibowo** [comment]
@cicatiello One of the dev mentioned that they weren't going to ship it with the repo. Can't remember the reason though, lol

**Comment by nivong** [comment]
@BobbyWibowo this is the link: https://pokemongo-bot.herokuapp.com/
and you can't get it as far as I know (at least not for linux) you need to create it yourself. Oh and I would advice @cicatiello to run a docker in windows, much easier and cleaner and saver :)

**Comment by BobbyWibowo** [comment]
@nivong If you're already registered into the Slack group, you can browse all uploaded files from here: https://pokemongo-bot.slack.com/files and you can find encrypt.so, encrypt.dll and encrypt64bit.dll.

**Comment by frossaren** [comment]
@nivong well if there is anything i can help with just shout :)
