### ISSUE TITLE
Question - how to make bot evolve all pokemon which able to ?

### ISSUE THREAD

**Issue by aviel600** [PokemonGoF/PokemonGo-Bot#2781]
as mentioned in headline i want the bot to evolve every pokemon which able to evolve.

I saw in Config file the next line :     "evolve_captured": "NONE",
is it possible to evolve all without mention each pokemon in the game ?

**edit** - also saw the next code : 
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 10,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }

what should i write in "evolve all" ? true ?

**Comment by tomalbrc** [comment]
I put in 'all'

**Comment by aviel600** [comment]
@tomalbrc Tnx, ill try and update soon

**Comment by aviel600** [comment]
solved tnx to @tomalbrc
