### ISSUE TITLE
UnboundLocalError: local variable 'bot'

### ISSUE THREAD

**Issue by Waliers** [PokemonGoF/PokemonGo-Bot#2783]
### Expected Behavior
Starting the Bot

### Actual Behavior
Error:
```
2016-08-07 13:56:50,526 [       cli] [INFO] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 126, in main
    if bot:
UnboundLocalError: local variable 'bot' referenced before assignment
```

### Steps to Reproduce
1. Fresh installation with Wiki steps followed. (Same with upgrade on working before bot)
2. Visit the Official API site to pull the tarball
3. Extract tarball (tar -xf )
4. Enter directory /src
5. Run 'make' (requires gcc and make)
6. Copy libencrypt.so to target directory
7. Rename libencrypt.so as encrypt.so
8. Run the bot as normal

### Other Information
OS: Debian 8 64-it
Git Commit: ad6c21aa1dc0902c62e4001f9a81ce1fcd8a9f59
Python Version: 2.7.9

**Comment by brantje** [comment]
#2780
