### ISSUE TITLE
Build Docker image failed on Raspberry Pi

### ISSUE THREAD

**Issue by edysantosa** [PokemonGoF/PokemonGo-Bot#2788]
### Expected Behavior
A Docker image should be created

### Actual Behavior
Failed to create image

### Steps to Reproduce
Running command to build image
```
$ docker build -t pokemongo-bot .
Sending build context to Docker daemon 5.463 MB
Step 1 : FROM python:2.7-onbuild
# Executing 3 build triggers...
Step 1 : COPY requirements.txt /usr/src/app/
 ---> Using cache
Step 1 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Running in 1cd2b3867cce
rpc error: code = 2 desc = "oci runtime error: exec format error"
```

### Other Information
OS: Arch Linux ARM

**Comment by BlazeMuisNL** [comment]
Same problem here on my RPi 3..

**Comment by BobXWu** [comment]
I got the same problem. Maybe the docker image you are using is built for x86/x64 architecture. And your cpu is based on ARM.
