### ISSUE TITLE
TransferPokemon keep_best_release 

### ISSUE THREAD

**Issue by AcorpBG** [PokemonGoF/PokemonGo-Bot#2790]
### Expected Behavior
TransferPokemon should not call or log non stop.
2016-08-07 15:20:25,217 [TransferPokemon] [INFO] [keep_best_release] Keeping best 4 Zubat, based on cp and iv
2016-08-07 15:20:25,218 [TransferPokemon] [INFO] [future_pokemon_release] Releasing Zubat (CP 10/IV 0.71) based on rule: CP < 225 OR IV < 0.8
2016-08-07 15:20:25,640 [TransferPokemon] [INFO] [pokemon_release] Exchanged Zubat [CP 10] [IV 0.71] for candy.
Check keep_best_release  then release extras.

### Actual Behavior
2016-08-07 15:20:25,217 [TransferPokemon] [INFO] [keep_best_release] Keeping best 4 Zubat, based on cp and iv
2016-08-07 15:20:25,218 [TransferPokemon] [INFO] [future_pokemon_release] Releasing Zubat (CP 10/IV 0.71) based on rule: CP < 225 OR IV < 0.8
2016-08-07 15:20:25,640 [TransferPokemon] [INFO] [pokemon_release] Exchanged Zubat [CP 10] [IV 0.71] for candy.
2016-08-07 15:20:28,945 [TransferPokemon] [INFO] [keep_best_release] Keeping best 3 Drowzee, based on cp and iv
2016-08-07 15:20:38,960 [TransferPokemon] [INFO] [keep_best_release] Keeping best 3 Drowzee, based on cp and iv
2016-08-07 15:20:49,143 [TransferPokemon] [INFO] [keep_best_release] Keeping best 3 Drowzee, based on cp and iv
2016-08-07 15:20:49,966 [TransferPokemon] [INFO] [keep_best_release] Keeping best 3 Drowzee, based on cp and iv
2016-08-07 15:20:50,698 [  SpinFort] [INFO] [spun_pokestop] Spun pokestop п═я┐п╦пҐп╦ 2. Experience awarded: 50. Items awarded: {u'Razz Berry': 1, u'Pokeball': 1, u'Super Potion': 1}
2016-08-07 15:21:01,985 [TransferPokemon] [INFO] [keep_best_release] Keeping best 3 Drowzee, based on cp and iv
2016-08-07 15:21:02,548 [RecycleItems] [INFO] [item_discarded] Discarded 1x Super Potion (maximum 0).
2016-08-07 15:21:12,615 [TransferPokemon] [INFO] [keep_best_release] Keeping best 3 Drowzee, based on cp and iv

This problem seems to happen with Drowzee either this event is the first one that apear and it keep getting logged or there is something else going on. 
As you can see it is only checking keep_best_release and not releasing anything

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by dezayner** [comment]
same to me

**Comment by AcorpBG** [comment]
You have the issue only with vaporeon ?

**Comment by dezayner** [comment]
Vaporeon, Starmie and Pinsir

**Comment by antoineneff** [comment]
I have this issue only with Vaporeon because it's only one I got twice (with more than 1200CP and 0.9IV). But I guess this will be the same for every pokemon you have twice (or more).

The issue comes from the config I think, what's your release configs ?

**Comment by AcorpBG** [comment]
Here it is:
`    
      "release": {
      "any": {"keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 999, "release_below_iv": 0.9, "logic": "or"},
      "//any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or" },

      "// Legendary pokemons (Goes under S-Tier)": {},
      "Lapras": { "release_below_cp": 1041, "release_below_iv": 0.8, "logic": "and" },
      "Moltres": { "release_below_cp": 1132, "release_below_iv": 0.8, "logic": "and" },
      "Zapdos": { "release_below_cp": 1087, "release_below_iv": 0.8, "logic": "and" },
      "Articuno": { "release_below_cp": 1039, "release_below_iv": 0.8, "logic": "and" },

      "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
      "Mewtwo": { "release_below_cp": 1447, "release_below_iv": 0.8, "logic": "and"},
      "Dragonite": { "release_below_cp": 1221, "release_below_iv": 0.8, "logic": "and" },
      "Snorlax": { "release_below_cp": 1087, "release_below_iv": 0.8, "logic": "and" },
      "// Mew evolves to Mewtwo": {},
      "Mew": { "release_below_cp": 1152, "release_below_iv": 0.8, "logic": "and" },
      "Arcanine": { "release_below_cp": 1041, "release_below_iv": 0.8, "logic": "and" },
      "Vaporeon": { "release_below_cp": 984, "release_below_iv": 0.8, "logic": "and" },
      "Gyarados": { "release_below_cp": 938, "release_below_iv": 0.8, "logic": "and" },
      "Exeggutor": { "release_below_cp": 1032, "release_below_iv": 0.8, "logic": "and" },
      "Muk": { "release_below_cp": 909, "release_below_iv": 0.8, "logic": "and" },
      "Weezing": { "release_below_cp": 784, "release_below_iv": 0.8, "logic": "and" },
      "Flareon": { "release_below_cp": 924, "release_below_iv": 0.8, "logic": "and" },

      "// Growlithe evolves to Arcanine": {},
      "Growlithe": { "release_below_cp": 465, "release_below_iv": 0.8, "logic": "and" },
      "// Dragonair evolves to Dragonite": {},
      "Dragonair": { "release_below_cp": 609, "release_below_iv": 0.8, "logic": "and" },
      "// Grimer evolves to Muk": {},
      "Grimer": { "release_below_cp": 448, "release_below_iv": 0.8, "logic": "and" },
      "// Magikarp evolves to Gyarados": {},
      "Magikarp": { "release_below_cp": 91, "release_below_iv": 0.8, "logic": "or" },
      "// Exeggcute evolves to Exeggutor": {},
      "Exeggcute": { "release_below_cp": 384, "release_below_iv": 0.8, "logic": "and" },
      "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
      "Eevee": { "release_below_cp": 376, "release_below_iv": 0.8, "logic": "and" },

      "// A-Tier pokemons": {},
      "Slowbro": { "release_below_cp": 907, "release_below_iv": 0.8, "logic": "and" },
      "Victreebel": { "release_below_cp": 883, "release_below_iv": 0.8, "logic": "and" },
      "Machamp": { "release_below_cp": 907, "release_below_iv": 0.8, "logic": "and" },
      "Poliwrath": { "release_below_cp": 876, "release_below_iv": 0.8, "logic": "and" },
      "Clefable": { "release_below_cp": 837, "release_below_iv": 0.8, "logic": "and" },
      "Nidoking": { "release_below_cp": 864, "release_below_iv": 0.8, "logic": "and" },
      "Venusaur": { "release_below_cp": 902, "release_below_iv": 0.8, "logic": "and" },
      "Charizard": { "release_below_cp": 909, "release_below_iv": 0.8, "logic": "and" },
      "Golduck": { "release_below_cp": 832, "release_below_iv": 0.8, "logic": "and" },
      "Nidoqueen": { "release_below_cp": 868, "release_below_iv": 0.8, "logic": "and" },
      "Vileplume": { "release_below_cp": 871, "release_below_iv": 0.8, "logic": "and" },
      "Blastoise": { "release_below_cp": 888, "release_below_iv": 0.8, "logic": "and" },
      "Omastar":  { "release_below_cp": 780, "release_below_iv": 0.8, "logic": "and" },
      "Aerodactyl": { "release_below_cp": 756, "release_below_iv": 0.8, "logic": "and" },
      "Golem": { "release_below_cp": 804, "release_below_iv": 0.8, "logic": "and" },
      "Wigglytuff": { "release_below_cp": 760, "release_below_iv": 0.8, "logic": "and" },
      "Dewgong": { "release_below_cp": 748, "release_below_iv": 0.8, "logic": "and" },
      "Ninetales": { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
      "Magmar": { "release_below_cp": 792, "release_below_iv": 0.8, "logic": "and" },
      "Kabutops": { "release_below_cp": 744, "release_below_iv": 0.8, "logic": "and" },
      "Electabuzz": { "release_below_cp": 739, "release_below_iv": 0.8, "logic": "and" },
      "Starmie": { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
      "Jolteon": { "release_below_cp": 746, "release_below_iv": 0.8, "logic": "and" },
      "Rapidash": { "release_below_cp": 768, "release_below_iv": 0.8, "logic": "and" },
      "Pinsir": { "release_below_cp": 741, "release_below_iv": 0.8, "logic": "and" },
      "Scyther": { "release_below_cp": 724, "release_below_iv": 0.8, "logic": "or" },
      "Tentacruel": { "release_below_cp": 775, "release_below_iv": 0.8, "logic": "and" },
      "Gengar": { "release_below_cp": 724, "release_below_iv": 0.8, "logic": "and" },
      "Hypno": { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
      "Pidgeot": { "release_below_cp": 729, "release_below_iv": 0.8, "logic": "and" },
      "Rhydon": { "release_below_cp": 782, "release_below_iv": 0.8, "logic": "and" },
      "Seaking": { "release_below_cp": 712, "release_below_iv": 0.8, "logic": "and" },
      "Kangaskhan": { "release_below_cp": 712, "release_below_iv": 0.8, "logic": "and" },

      "// Koffing evolves to Weezing (A-Tier)": {},
      "Koffing": { "release_below_cp": 403, "release_below_iv": 0.8, "logic": "and" },

      "// Below is B-tier or lower pokemons": {},
      "Caterpie": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 156, "release_below_iv": 0.8, "logic": "or" },
      "Weedle": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 156, "release_below_iv": 0.8, "logic": "or" },
      "Diglett": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 158, "release_below_iv": 0.8, "logic": "or" },
      "Metapod": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 168, "release_below_iv": 0.8, "logic": "or" },
      "Kakuna": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 170, "release_below_iv": 0.8, "logic": "or" },
      "Rattata": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 204, "release_below_iv": 0.8, "logic": "or" },
      "Abra": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 208, "release_below_iv": 0.8, "logic": "or" },
      "Zubat": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 225, "release_below_iv": 0.8, "logic": "or" },
      "Chansey": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 235, "release_below_iv": 0.8, "logic": "or" },
      "Pidgey": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 200, "release_below_iv": 0.8, "logic": "or" },
      "Spearow": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 240, "release_below_iv": 0.8, "logic": "or" },
      "Meowth": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 264, "release_below_iv": 0.8, "logic": "or" },
      "Krabby": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 276, "release_below_iv": 0.8, "logic": "or" },
      "Sorshrew": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 278, "release_below_iv": 0.8, "logic": "or" },
      "Poliwag": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 278, "release_below_iv": 0.8, "logic": "or" },
      "Horsea": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 278, "release_below_iv": 0.8, "logic": "or" },
      "Gastly": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 280, "release_below_iv": 0.8, "logic": "or" },
      "Ekans": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 288, "release_below_iv": 0.8, "logic": "or" },
      "Shellder": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 288, "release_below_iv": 0.8, "logic": "or" },
      "Vulpix": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 290, "release_below_iv": 0.8, "logic": "or" },
      "Voltorb": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 292, "release_below_iv": 0.8, "logic": "or" },
      "Geodude": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 297, "release_below_iv": 0.8, "logic": "or" },
      "Doduo": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 297, "release_below_iv": 0.8, "logic": "or" },
      "Onix": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 300, "release_below_iv": 0.8, "logic": "or" },
      "Mankey": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 307, "release_below_iv": 0.8, "logic": "or" },
      "Pikachu": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 309, "release_below_iv": 0.8, "logic": "or" },
      "Magnemite": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 312, "release_below_iv": 0.8, "logic": "or" },
      "Tentacool": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 316, "release_below_iv": 0.8, "logic": "or" },
      "Paras": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 319, "release_below_iv": 0.8, "logic": "or" },
      "Jigglypuff": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 321, "release_below_iv": 0.8, "logic": "or" },
      "Ditto": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 321, "release_below_iv": 0.8, "logic": "or" },
      "Staryu": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 326, "release_below_iv": 0.8, "logic": "or" },
      "Charmorer": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 333, "release_below_iv": 0.8, "logic": "or" },
      "Goldeen": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 336, "release_below_iv": 0.8, "logic": "or" },
      "Squirtle": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 352, "release_below_iv": 0.8, "logic": "or" },
      "Cubone": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 352, "release_below_iv": 0.8, "logic": "or" },
      "Venonat": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 360, "release_below_iv": 0.8, "logic": "or" },
      "Bulbasaur": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 374, "release_below_iv": 0.8, "logic": "or" },
      "Drowzee": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 374, "release_below_iv": 0.7, "logic": "or" },
      "Machop": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 381, "release_below_iv": 0.8, "logic": "or" },
      "Psyduck": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 386, "release_below_iv": 0.8, "logic": "or" },
      "Seel": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 386, "release_below_iv": 0.8, "logic": "or" },
      "Kabuto": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 386, "release_below_iv": 0.8, "logic": "or" },
      "Bellsprout": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 391, "release_below_iv": 0.8, "logic": "or" },
      "Omanyte": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 391, "release_below_iv": 0.8, "logic": "or" },
      "Kadabra": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 396, "release_below_iv": 0.8, "logic": "or" },
      "Oddish": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 400, "release_below_iv": 0.8, "logic": "or" },
      "Dugtrio": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 408, "release_below_iv": 0.8, "logic": "or" },
      "Rhyhorn": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 412, "release_below_iv": 0.8, "logic": "or" },
      "Clefairy": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 420, "release_below_iv": 0.8, "logic": "or" },
      "Slowpoke": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 424, "release_below_iv": 0.8, "logic": "or" },
      "Pidgeotto": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 427, "release_below_iv": 0.8, "logic": "or" },
      "Farfetch'd": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 441, "release_below_iv": 0.8, "logic": "or" },
      "Poliwhirl": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 468, "release_below_iv": 0.8, "logic": "or" },
      "Nidorino": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 480, "release_below_iv": 0.8, "logic": "or" },
      "Haunter": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 482, "release_below_iv": 0.8, "logic": "or" },
      "Nidorina": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 489, "release_below_iv": 0.8, "logic": "or" },
      "Graveler": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 501, "release_below_iv": 0.8, "logic": "or" },
      "Beedrill": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 504, "release_below_iv": 0.8, "logic": "or" },
      "Raticate": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 504, "release_below_iv": 0.8, "logic": "or" },
      "Butterfree": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 508, "release_below_iv": 0.8, "logic": "or" },
      "Hitmonlee": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 520, "release_below_iv": 0.8, "logic": "or" },
      "Ponyta": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 530, "release_below_iv": 0.8, "logic": "or" },
      "Hitmonchan": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 530, "release_below_iv": 0.8, "logic": "or" },
      "Charmeleon": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 544, "release_below_iv": 0.8, "logic": "or" },
      "Wartortle": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 552, "release_below_iv": 0.8, "logic": "or" },
      "Persian": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 568, "release_below_iv": 0.8, "logic": "or" },
      "Lickitung": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 568, "release_below_iv": 0.8, "logic": "or" },
      "Ivysaur": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 571, "release_below_iv": 0.8, "logic": "or" },
      "Electrode": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 576, "release_below_iv": 0.8, "logic": "or" },
      "Marowak": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 578, "release_below_iv": 0.8, "logic": "or" },
      "Gloom": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 590, "release_below_iv": 0.8, "logic": "or" },
      "Porygon": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 590, "release_below_iv": 0.8, "logic": "or" },
      "Seadra": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 597, "release_below_iv": 0.8, "logic": "or" },
      "Jynx": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 600, "release_below_iv": 0.9, "logic": "or" },
      "Weepinbell": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 602, "release_below_iv": 0.8, "logic": "or" },
      "Tangela": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 607, "release_below_iv": 0.8, "logic": "or" },
      "Fearow": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 609, "release_below_iv": 0.8, "logic": "or" },
      "Parasect": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 609, "release_below_iv": 0.8, "logic": "or" },
      "Machoke": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 614, "release_below_iv": 0.8, "logic": "or" },
      "Arbok": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 616, "release_below_iv": 0.8, "logic": "or" },
      "Sorslash": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 631, "release_below_iv": 0.8, "logic": "or" },
      "Alakazam": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 633, "release_below_iv": 0.8, "logic": "or" },
      "Kingler": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 636, "release_below_iv": 0.8, "logic": "or" },
      "Dodrio": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 640, "release_below_iv": 0.8, "logic": "or" },
      "Tauros": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 643, "release_below_iv": 0.8, "logic": "or" },
      "Primeape": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 650, "release_below_iv": 0.8, "logic": "or" },
      "Magneton": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 657, "release_below_iv": 0.8, "logic": "or" },
      "Venomoth": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 660, "release_below_iv": 0.8, "logic": "or" },
      "Golbat": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 672, "release_below_iv": 0.8, "logic": "or" },
      "Raichu": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 708, "release_below_iv": 0.8, "logic": "or" },
      "Cloyster": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 717, "release_below_iv": 0.8, "logic": "or"},
      "Mr. Mime": { "keep_best_cp": 2, "keep_best_iv": 2, "release_below_cp": 650, "release_below_iv": 0.8, "logic": "or" }
    },
`

**Comment by thereyrey** [comment]
I have the same issue only with this:
2016-08-07 15:18:23,482 [TransferPokemon] [INFO] [keep_best_release] Keeping best 3 Venonat, based on cp and iv
2016-08-07 15:18:23,484 [TransferPokemon] [INFO] [keep_best_release] Keeping best 4 Krabby, based on cp and iv
2016-08-07 15:18:23,487 [TransferPokemon] [INFO] [keep_best_release] Keeping best 3 Electrode, based on cp and iv
2016-08-07 15:18:23,490 [TransferPokemon] [INFO] [keep_best_release] Keeping best 3 Exeggcute, based on cp and iv
2016-08-07 15:18:23,492 [TransferPokemon] [INFO] [keep_best_release] Keeping best 3 Rhyhorn, based on cp and iv
2016-08-07 15:18:23,493 [TransferPokemon] [INFO] [keep_best_release] Keeping best 3 Staryu, based on cp and iv
2016-08-07 15:18:23,496 [TransferPokemon] [INFO] [keep_best_release] Keeping best 4 Magikarp, based on cp and iv

on every move

config:

"any": {"keep_best_cp": 1, "keep_best_iv": 3, "release_below_cp": 100, "release_below_iv": 0.75, "logic": "or"},

**Comment by antoineneff** [comment]
I guess keep_best and release_below don't go together ...

**Comment by AcorpBG** [comment]
It worked with the old api. Something was changed we have to figure out what exactly

**Comment by antoineneff** [comment]
Well, it's "working", we got our pokemons like we want. It's just the logging ... since everything changed.

**Comment by AcorpBG** [comment]
It might have been the same before, it is just weird case looking at my drowzees: 
I have 3 that met the keep best rules. But another one that don't match the release rule. So release rule check and find 3 pokemons to keep but it see there are 4 pokemons, And call it again.

**Comment by dezayner** [comment]
yeah, just logging that make my console dirty :)

**Comment by durd** [comment]
Same as for @AcorpBG, got tons of pokes that aren't getting matched against release rules:
`    "release": {
      "any": { "keep_best_iv": 3, "release_below_cp": 300, "release_below_iv": 0.5, "logic": "or" },
      ...
      "Drowzee": { "keep_best_iv": 3, "release_below_cp": 374, "release_below_iv": 0.8, "logic": "and" },`
I did try also:
`    "release": {
      "any": { "release_below_cp": 300, "release_below_iv": 0.5, "logic": "and", "keep_best_iv": 3 },
      ...
      "Drowzee": { "release_below_cp": 374, "release_below_iv": 0.8, "logic": "and", "keep_best_iv": 3 },`
But the bot doesn't release the rest, the same goes for other pokes like Krabby, Magikarp, Magnemite, Rattata.

**Comment by m-a-g-o** [comment]
I get this Keeping best flood too. I tried to remove all the "if best_pokemons and all_pokemons:" and it worked (no more logs) but the pokemon transfer doesn't worked anymore...I have to try this again

**Comment by TheSavior** [comment]
Fixed in https://github.com/PokemonGoF/PokemonGo-Bot/pull/3223
