### ISSUE TITLE
[DEV] MoveToMapPokemon worker still uses logger.log

### ISSUE THREAD

**Issue by BobbyWibowo** [PokemonGoF/PokemonGo-Bot#2792]
### Expected Behavior
Uses the new events thingy.

### Actual Behavior
Uses logger.log which cause lots of 'deprecated feature' messages.

### Steps to Reproduce
None.

### Other Information
OS: Win 10
Git Commit: d5bb09fd758e779b8eee859d8374f0d198e58abb
Python Version: 2.7.10

**Comment by BobbyWibowo** [comment]
Actually I'm not sure whether master branch is already using the new events thingy.

**Comment by brantje** [comment]
Today we merged dev to master, so it should not happen.
What is the output of `git status`

**Comment by BobbyWibowo** [comment]
`On branch dev
Your branch is up-to-date with 'origin/dev'.`

**Comment by zetasq** [comment]
I'm on Dev branch and got the same warning.

**Comment by BobbyWibowo** [comment]
You can clearly see that it's still using `logger.log` here: https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/move_to_map_pokemon.py
While everything else had begun using the new events thingy.

**Comment by beldar** [comment]
I've seen this too, getting lots of deprecation warnings when using that task

**Comment by jordahlk** [comment]
You can get around this temporarily by going into \PokemonGo-Bot\pokemongo_bot\logger.py and removing the last line of the file: "warnings.warn(message, DeprecationWarning)"

**Comment by beldar** [comment]
Yep, did that, must be changed tho, not the ideal solution

**Comment by BobbyWibowo** [comment]
On my local copies, I made new events and changed all instances of logger.log in that worker to use the new events. But honestly, I had no idea whether the naming I used for the events were as intended by the developers here, so I didn't make any PR.
