### ISSUE TITLE
Error while starting bot

### ISSUE THREAD

**Issue by Parth6182** [PokemonGoF/PokemonGo-Bot#2793]
Traceback (most recent call last):
File "pokecli.py", line 38, in 
from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: cannot import name ServerSideRequestThrottlingException

**Comment by nivong** [comment]
you should search dude really.. it has been said many times already

**Comment by brantje** [comment]
I suggest you should go buy glasses instead of getting the bot to work. Read: #2780
