### ISSUE TITLE
ImportError: No module named pgoapi.exceptions

### ISSUE THREAD

**Issue by updatesvc** [PokemonGoF/PokemonGo-Bot#2795]
### Expected Behavior
Logging in and bot starts.

### Actual Behavior

`Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions
`
### Steps to Reproduce

`pthyon pokecli.py`
### Other Information
OS: Debian 64 bit
Git Commit: ad6c21aa1dc0902c62e4001f9a81ce1fcd8a9f59

Python Version: 2.7

I had a successful run before restarting my computer.

**Comment by brantje** [comment]
You have too update your pgoapi using `pip install -r requirements.txt`
