### ISSUE TITLE
Error after using bot

### ISSUE THREAD

**Issue by FlorinBaDz** [PokemonGoF/PokemonGo-Bot#2797]
So, I have used a bot this morning and when I try to play PokemonGO on my Android device the game doesn't respond after 5 seconds since it loaded.

I have tried some things but none of them worked: uninstalling then reinstalling the game, logging out and relogging with my google account, force arresting the app and cancelling caches, restarting the device. I don't know what to do and I didn't find this issue nowhere. Please help me! :'(

**Comment by brantje** [comment]
#2780
