### ISSUE TITLE
Exchange for candy doesn't work

### ISSUE THREAD

**Issue by TianCNCA** [PokemonGoF/PokemonGo-Bot#280]
### Expected Behavior
when set -c 300 the bot should automatically exchange any pokemon below 300 for candy

### Actual Behavior
it says it did, but it actually doesn't

### Steps to Reproduce
run the bot with -c option on

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Razapo** [comment]
Look at the issue below this one. And check before posting.

**Comment by crusardri** [comment]
Yep, still not working

**Comment by aTadTasty** [comment]
#279 yeah i'm getting same even with a git pull or git clone

**Comment by Skeyelab** [comment]
also same issue.

**Comment by douglascamata** [comment]
More debug information would be helpful. I'm soft banned for 2 hours and PTC is down to login with other accounts.

**Comment by kotecekk** [comment]
Same problem for me, pls fix asap.

**Comment by earthchie** [comment]
I went to double check, and can confirm that this line get the correct pid.

https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/pokemon_catch_worker.py#L93

May be this has something to do with pgoapi?

**Comment by em202020** [comment]
Also experiencing this issue.  Transferring works for me, though only roughly 30% of the time, leaving a lot of low level pokemon in my inventory.

**Comment by catchemnon** [comment]
also having the issue still

**Comment by surfaace** [comment]
issue was fixed at some point in dev. also config.json file is now used
