### ISSUE TITLE
Lure attraction

### ISSUE THREAD

**Issue by RomanFausek** [PokemonGoF/PokemonGo-Bot#2806]
### Expected Behavior
Bot shouldn't be attracted to lures

### Actual Behavior
Bot is attracted to lures

### Steps to Reproduce
 {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": false,
            "lure_max_distance": 0
        }
      },

### Other Information
OS: W10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by brantje** [comment]
Duplicate. See #2774
