### ISSUE TITLE
Move custom path

### ISSUE THREAD

**Issue by Fr33loader** [PokemonGoF/PokemonGo-Bot#2807]
Hi guys,

First of: many thanks for your great work on the project and in releasing the bot so soon. I've been following the RE efforts on Discord over the past few days with great interest. The installation was well explained on the wiki.

I just have one issue that I can't seem to wrap my head around: I planned out a custom path around my city, but I can't seem to get the program to follow it.

I realize this will likely be a 'noob' question, apologies in advance:

1. I have the custom path set up in configs/path.json

2. I tried adapting the main config as such:
`
 {
            "type": "FollowPath",
            "config": {
                "path_mode": "linear",
                "path_file": "configs/path.json"
            }
        },
{
            "type": "MoveToFort",
            "config": {
                "lure_attraction": false,
                "lure_max_distance": 0
            }
        }       
`
When I run the bot, however, it goes the opposite direction ("moving_to_lured_fort"). As you can see, I set 'lure_attraction' to false and 'lure_max_distance' to 0 in order to stop it from going to a lure in the other direction, but it doesn't seem to do much.

Any help would be much appreciated.

Further, if I use standard settings, my xp per hour is limited to 4-5k exp (my city is loaded with pokestops however, a lot of them on lure).

By way of example, I keep getting logs like these, without much action (catching or spinning):

2016-08-07 15:35:51,819 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop [XXX] - 0.12km (attraction of lure 0.18km)
2016-08-07 15:36:44,840 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort [XXX] (e2fa9ea1be514d548840e7d728aXXXd.11)

(Anonymized some aspects with a blob [XXX])

**Comment by AcorpBG** [comment]
You should not use movetofort, Both modes are incompatible.

**Comment by Nik0lashka** [comment]
@AcorpBG , do you know if "FollowPath" conflicts with "MoveToMapPokemon"?
