### ISSUE TITLE
Color in Bash lost since the big update

### ISSUE THREAD

**Issue by designer2k2** [PokemonGoF/PokemonGo-Bot#2809]
### Expected Behavior

Colored output, like catching in green, pokestop in yellow, vanished pokemon in red

### Actual Behavior

only white output.

### Steps to Reproduce

start bot, let it run

### Other Information
OS:  Win 10 64Bit
Git Commit: ad6c21aa1dc0902c62e4001f9a81ce1fcd8a9f59
Python Version: Python 2.7.12

**Comment by brantje** [comment]
We introduced an new event system, it's still in development.
But therefore we needed to get rid of the old `logger.log` including the ability for colored output.
Not sure if it comes back @douglascamata might knows more about this.

**Comment by nikmess** [comment]
See https://github.com/PokemonGoF/PokemonGo-Bot/issues/2675#issuecomment-238080811 for a fix ad interim.

**Comment by TerraSkye** [comment]
The event system isnt working with linux grep.
Dont know if its an improvent. Even the blocksizes. [       ] arent fixed size. Wich blocks the visibility. (Personal prefference)

**Comment by douglascamata** [comment]
This is not a bug, it's an intended behaviour. Colourful log might come back in future updates.
