### ISSUE TITLE
Web - Error 404 for socket.io

### ISSUE THREAD

**Issue by iruy** [PokemonGoF/PokemonGo-Bot#2817]
Could this be the reason why the buttons "Evolve" and "Release" are not appearing?

### Actual Behavior
In my browser console I see this error message
![404 Error](https://cloud.githubusercontent.com/assets/8875681/17462922/f639b9de-5cbb-11e6-9ace-2ae159a38f7f.png)

### Steps to Reproduce
Happening both on Windows and OS X

**Comment by helmut1337** [comment]
Also for Windows 7 for the catchable-USERNAME.json file
![catchable](https://cloud.githubusercontent.com/assets/20885690/17463373/254654dc-5cc4-11e6-9ba2-343c32f8463b.png)

**Comment by Kujawadl** [comment]
#2547

**Comment by Kujawadl** [comment]
@helmut1337 create a file in your web directory called catchable-[your username].json with just `{}` in it. The other error is from #2547

**Comment by StudioNoctis** [comment]
@Kujawadl Still seeing this as an issue, the catchable, location and inventory JSONs are creating and updated, but the socket issue is broken.

Not seeing any other ticket's that got this resolved so far.

socket.io/?EIO=3&transport=polling&t=LPhT30A

**Comment by andikatanpah** [comment]
any update for socket.io 404?
im use ubuntu 12.04 and run apache2..
or i must trun on "python -m SimpleHTTPServer 8001" first?

**Comment by hdchuong** [comment]
have you used the same google map key for userdata.js and config.json? If yes, the solution is getting another key for js. The 2 files can't share the same key.

**Comment by AndikaTanpaH** [comment]
@hdchuong  i just add different gmap key.. but its still happening

> Failed to load resource: the server responded with a status of 404 (File not found)
> GET http://localhost:8000/socket.io/?EIO=3&transport=polling&t=LPucIJL 404 (File not found)

where is socket.io ? i dint find on folder web.

**Comment by hdchuong** [comment]
@AndikaTanpaH is the new key for javascript?

**Comment by AndikaTanpaH** [comment]
@hdchuong yes i just create a new key..
/configs/config.js
/web/config/userdata.js

This is not a problem the operating system? i'm use ubuntu 12.04 64bit

I'll try later with another operating system (windows 8.1)

**Comment by hdchuong** [comment]
@AndikaTanpaH hmm this is weird coz I'm having exact the same problem and solved by the right gmap key.
I run with docker on Mac though using docker-compose.yml file

**Comment by nujabse** [comment]
Got the same error too on Archlinux, can't find a solution.
