### ISSUE TITLE
Bot can't start 

### ISSUE THREAD

**Issue by STNDBS** [PokemonGoF/PokemonGo-Bot#282]
![d66ddd4673764671a995074586f59dc8](https://cloud.githubusercontent.com/assets/20604101/17070854/ebeaf12a-5066-11e6-9cde-fb9264b106a0.png)

**Comment by Klohto** [comment]
Servers are down

**Comment by aTadTasty** [comment]
are you shure you have all the requirements installed?

**Comment by STNDBS** [comment]
Yes, i am sure 
If it is problem with servers - ok

**Comment by aTadTasty** [comment]
server is up and working fine for me. you just gotta make sure you have your `pip install -r ./requirements.tx` and that should fix it. if that doesn't work, i don't know what else to do. best of luck!

**Comment by Klohto** [comment]
PTC servers are down, Google servers up. Don't share misinformation.

**Comment by aTadTasty** [comment]
@Klohto seems to be up and running fine for me with PTC accounts

**Comment by Klohto** [comment]
@aTadTasty US or EU? Bet you're on EU.

**Comment by slonce** [comment]
soory can you help me? I am don't can install pip. I have this mistake ```
"C:\Users\sLoNcE\Desktop\PokemonGo-Bot-dev>pip install -r ./requirements.txt
Obtaining pgoapi from git+git://github.com/tejado/pgoapi.git@1f25e907f3e5f1b603330e71041e1ad7bee7580f#egg=pgoapi (from -r ./requirements.txt (line 1))
  Cloning git://github.com/tejado/pgoapi.git (to 1f25e907f3e5f1b603330e71041e1ad7bee7580f) to c:\users\slonce\desktop\pokemongo-bot-dev\src\pgoapi
  Error [Error 2]  while executing command git clone -q git://github.com/tejado/pgoapi.git C:\Users\sLoNcE\Desktop\PokemonGo-Bot-dev\src\pgoapi
Cannot find command 'git'"
```
What can i do?)Thanks

**Comment by aTadTasty** [comment]
@Klohto US NYC based m8. and @slonce you have to install git.

**Comment by Klohto** [comment]
@aTadTasty Checked with everyone I know and one one can login with PTC based accounts.

**Comment by vanrzuf** [comment]
i have same error like Klohto after last dev update

**Comment by slonce** [comment]
Klohto, but if i am install it, then i have mistake in start bot...(Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pokemongo_bot import PokemonGoBot
  File "C:\Users\sLoNcE\Desktop\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 4, in <module>
    import googlemaps
ImportError: No module named googlemaps)
What is this? Thanks

**Comment by vanrzuf** [comment]
@slonce pip install -r ./requirements.txt

**Comment by slonce** [comment]
vanrzuf, i wrote early i have mistale when install pip [https://github.com/PokemonGoF/PokemonGo-Bot/issues/282#issuecomment-234655198](url)

**Comment by vanrzuf** [comment]
@slonce if you installed git it shoul work now. PL?

**Comment by Klohto** [comment]
@slonce Open up new issue, this is someone's else. Just install git and do the pip command and oyu should be fine.

**Comment by vanrzuf** [comment]
@Klohto and what about this:
`Traceback (most recent call last):
  File "pokecli.py", line 107, in <module>
    main()
  File "pokecli.py", line 99, in main
    bot.start()
  File "/******/pokemongo_bot/__init__.py", line 26, in start
    self._setup_api()
  File "/******/pokemongo_bot/__init__.py", line 146, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'`

**Comment by Klohto** [comment]
@vanrzuf Pretty sure it's still server side issue. Been getting different errors for a while now.

**Comment by ataetgi** [comment]
Traceback (most recent call last):
  File "pokecli.py", line 126, in <module>
    main()
  File "pokecli.py", line 118, in main
    bot.start()
  File "C:\PokemonGobot\bot.py", line 26, in start
    self._setup_api()
  File "C:\PokemonGobot\bot.py", line 85, in _setup_api
    self._set_starting_position()
  File "C:\PokemonGobot\bot.py", line 220, in _set_starting_position
    self.position = self._get_pos_by_name(self.config.location)
  File "C:\PokemonGobot\bot.py", line 231, in _get_pos_by_name
    loc = geolocator.geocode(location_name)
  File "C:\Python27\lib\site-packages\geopy\geocoders\googlev3.py", line 217, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\Python27\lib\site-packages\geopy\geocoders\base.py", line 158, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderQueryError: HTTP Error 400: Bad Request

i need help guys?

**Comment by s1x** [comment]
@STNDBS issue seems to be resolved.

@ataetgi Please feel free the open a new issue when necessary, as the initial issue is resolved.
