### ISSUE TITLE
Not seeing any changes in game

### ISSUE THREAD

**Issue by Megasteel32** [PokemonGoF/PokemonGo-Bot#2824]
### Expected Behavior
I see the bot catching and releasing pokemon, and walking 60-70 meters to hatch eggs, as well as listing my items and XP.

### Actual Behavior
When I go into the app after closing the script, I dont see any XP changes, or any more candies in my inventory.

### Other Information
OS: Windows 10

**Comment by Corecrafts** [comment]
#2813

**Comment by Megasteel32** [comment]
Not the same issue. It appears to work, and keeps working, but nothing
happens when I check the app

**Comment by k4n30** [comment]
Confirm you are using the same login for the bot and the legit app.  Create a new issue using the issue template if you still have issues
