### ISSUE TITLE
No module named pgoapi.exceptions

### ISSUE THREAD

**Issue by Fr33loader** [PokemonGoF/PokemonGo-Bot#2825]
### Expected Behavior

Occurs on bot startup - haven't been able to login for the past half hour.

### Actual Behavior
> PokemonGo-Bot MyHome$ ./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

### Steps to Reproduce
./run.sh

### Other Information
OS: 
Git Commit: ad6c21aa1dc0902c62e4001f9a81ce1fcd8a9f59
Python Version: Python 2.7.10

**Comment by brantje** [comment]
Read the psa
