### ISSUE TITLE
First Banned :(

### ISSUE THREAD

**Issue by helloitu** [PokemonGoF/PokemonGo-Bot#2828]
### Expected Behavior
Don't be banned

### Actual Behavior
after the bot catch some pokemons and start response with errors , when i try to loggin in my phone i get error to retry logging , and in ptc official site i get a message to wait until the game has been released ( WTF?) 
sorry for my bad english.

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by nivong** [comment]
Please read the issue template and fill everything in as it should be filled in. Also if there are errors post them otherwise this will be closed @brantje

**Comment by helloitu** [comment]
not erros here man , i am just alert that ban is comming , with use the bot ......

**Comment by nivong** [comment]
Again update your first post. I read in it:
"after the bot catch some pokemons and start response with errors<<<<<" you write errors...

**Comment by BobbyWibowo** [comment]
@helloitu You should have made sure that before you login with your phone, you had masked your location to the last location the bot used. Also made sure that your PTC account was registered to the country that were faking.
