### ISSUE TITLE
[Question] Is the bot able to play the tutorial?

### ISSUE THREAD

**Issue by aceus1** [PokemonGoF/PokemonGo-Bot#2830]
Question in title.
If yes
   Thats good! I can run multible bots with fresh created google/ptc accounts and I could generate configs for every new account and run it autonomously.
If no
  Do I have to play the tutorial before the first start?
  And maybe, after updates for stability, a feature...

**Comment by BobbyWibowo** [comment]
I'm not sure by now, but previously it can't. Though I suggest waiting for someone who has more knowledge about this in particular.

**Comment by nivong** [comment]
you can it wont be able to get level up rewards though and the likeliness of getting banned will be higher.

**Comment by brambi** [comment]
#2780

**Comment by BobbyWibowo** [comment]
@nivong I'm pretty sure the new task worker: "CollectLevelUpReward" can get the level up rewards no matter from which level you level up though.

**Comment by nivong** [comment]
@brambi please stop posting that to every dam issue....
@BobbyWibowo you are right! When I started with the bot a few weeks ago it didn't had any of that. Not sure about now. But he I wouldn't risk it someone that didn't finish the tutorial and is level 25 will be found really quickly in the database of pokemon go lol

**Comment by brantje** [comment]
@brambi is flagging issues for us. So we can work instead of closing shitty issues

**Comment by BobbyWibowo** [comment]
@nivong Oh well, I can't comment anything about tutorial playing anyway. I had always played the tutorial on my bots before running them through the bot.

**Comment by nivong** [comment]
@brantje doing the same although only flagging issues that are related to "beginners" and encrypted issues. not to every issue
@BobbyWibowo same here! savest way to go!

**Comment by brantje** [comment]
They are spamming the issues not reading the psa or the read me. We are working on it and each minute we spend on closing issues, is a minute longer till a stable bot.

**Comment by nivong** [comment]
if you need me to help you with closing issues, I am all up for it.
