### ISSUE TITLE
[Dev]OSError: Encrypt.so Invalid ELF Header

### ISSUE THREAD

**Issue by kenshi08** [PokemonGoF/PokemonGo-Bot#2831]
### Expected Behavior
Successful Run

### Actual Behavior
OSError: encrypt.so: invalid ELF header

### Steps to Reproduce
./run.sh

### Other Information
OS: Ubuntu
Git Commit: 4eb7b388d950ff9d9517b5223967aa10adfbb10d
Python Version: 2.7.12

**Comment by nivong** [comment]
search before posting an "issue"
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2808
