### ISSUE TITLE
Module called "LevelUp" to use Lucky egg when enough evolutions to level up available

### ISSUE THREAD

**Issue by pranavperfect** [PokemonGoF/PokemonGo-Bot#2833]
Trying to store pokemon in order to use a lucky egg and perform bulk evolutions. Want to understand how I can perform this using some configuration in config.json.

Essentially, if i have 36 Pidgey candies, bot should let 3+ pidgey be. If 60 pidgey candies, let 5+ pidgey be.

Can someone help out with this kind of config? This can help ensure that i get the most out of my lucky egg in one go.

**Comment by brambi** [comment]
#2780

**Comment by nivong** [comment]
@brambi this has nothing to do with that please delete your comment.
And @pranavperfect please use the template for making an issue.

**Comment by pranavperfect** [comment]
@nivong I believe @brambi just wants to tell me to read 2780 which refers to an update in the wiki being an upcoming task and not an immediate task. And i understand that. Which is why you guys can close it and I can comment on it later after the wiki is updated.

**Comment by nivong** [comment]
@pranavperfect that issue where brambi was linking to has to do with the new encrypted updates and how to run the new bot ;)
Your "issue" isn't an issue it's a #newfeature.

**Comment by pranavperfect** [comment]
Here is the detailed description of the new feature:

Just like we have modules for catching pokemon and evolving pokemon, if there could be a "level up" module which would act as follows:

1. Calculate XP required to new level ==> XP required for next level - XP present
2. Count number of Pidgey+Weedle+Caterpie in inventory available for level up
3. Calculate possible XP earned if evolved using lucky egg (2*500*no. of evolutions)
*Not taking into account XP earned from catching pokemon and swiping pokestops
4. If Possible XP earned >= XP required for Level up
- Pause all other activity
- Start Lucky Egg
- Evolve Pidgey, Weedle and Caterpie
- After leveling up, keep strongest by CP or IV as set in config file
- Resume regular activity
5. Else, continue catching pokemon and re-check after x mins

For step 2 to happen, bot needs to catch and release weak pokemon such that 
weak pokemon in inventory = (candy/12)+1
So if there was 60 Pidgey candy, there should be 6 Pidgey in inventory.
weak pokemon should not be governed by the keep_best_cp/iv rule.

**Comment by pranavperfect** [comment]
@nivong please let me know if this is enough details.

**Comment by pranavperfect** [comment]
And again, this will not be an "always on" feature since lucky eggs are limited.

**Comment by mousetree** [comment]
@pranavperfect: in your `release` section, include settings like this:

```
"Caterpie": { "keep_for_evo": true },
"Weedle": { "keep_for_evo": true },
"Rattata": { "keep_for_evo": true },
"Zubat": { "keep_for_evo": true },
"Pidgey": { "keep_for_evo": true },
```

When you are ready you can add a task like:

```
{
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "Pidgey,Rattata,Weedle,Tentacool,Zubat,Ekans,Psyduck,Spearow,Caterpie",
            "first_evolve_by": "cp",
            "evolve_above_cp": 100,
            "evolve_above_iv": 0.1,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": true
        }
      }
```

YMMV, but this seems to work well for me (on latest `dev` branch)

**Comment by pranavperfect** [comment]
@mousetree - First of all, the script does not display XP/stats periodically which i can monitor and be like "Hey i can level up now because i have enough evolutions etc.". Secondly, This would require me to keep changing my config whereas that is a module which actively monitors my possible evolutions and my required evolutions and then do it auto-magically. I'm just trying to have least restarts.

@nivong - Can we not display the stats periodically which are displayed only when the bot is stopped?
It would be helpful to know how we are progressing.

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by mjmadsen** [comment]
Done to an extent. Please reopen and expand if not.

**Comment by pranavperfect** [comment]
I don't see the option? Do we have a wiki for it? Can you please explain where this feature has been added?

**Comment by nivong** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/commits/master

**Comment by pranavperfect** [comment]
@nivong  i don't understand how the commit helps. I can't find any reference to my feature request in the commits.

**Comment by pranavperfect** [comment]
Level up thing definitely doesn't work. Or i don't know how to make it work. some guidance is required.

**Comment by k4n30** [comment]
@pranavperfect reopened for you :)

**Comment by pranavperfect** [comment]
@k4n30 Thank you! I couldn't find a way to open it!

@mjmadsen mentioned that this feature has been built into the bot. But i don't see it happening. Is there some configuration that needs to be done for it?

**Comment by mjmadsen** [comment]
@pranavperfect Sorry, I misread the wants. My bad!

**Comment by pranavperfect** [comment]
@mjmadsen the config.json.optimizer.example has some content which relates to what i'd asked. but it is asking the user to tell how many evolutions are needed etc. but what the module should do is keep hoarding pidgey, weedle and caterpie and other "common" pokemon for an area and then once enough to level up using lucky egg, then start evolving. also taking into account that in 30 minutes, you'd be able to do roughly 60 evolutions.

**Comment by pranavperfect** [comment]
@mjmadsen is this still under development or has been disregarded?

**Comment by mjmadsen** [comment]
I don't know if anyone is currently working on this. A lot of bug fixes and small improvements. 

Everything you asked for seems to be in the bot except for taking in account exp to next level or what not. Personally, I don't see much value in it. Exp is exp.

**Comment by oralunal** [comment]
I agree with @mjmadsen . Exp is exp. No need to something like this.
