### ISSUE TITLE
encrypt.so is not found!

### ISSUE THREAD

**Issue by avneetsb** [PokemonGoF/PokemonGo-Bot#2835]
Where to find this file
Using Mac OSX El Capitan
Saw the python code in __init__.py
get_encryption_lib function
from where do I copy this file into the bots directory ??

Any help will be appreciated
Thanks

**Comment by firzzen** [comment]
Please have a look at #2808 and if still not working, comment there.

**Comment by TheTaxDoctor** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2769

Please look at this existing issue to resolve yours.

**Comment by nivong** [comment]
ugh....
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2780

**Comment by avneetsb** [comment]
Thanks @firzzen for the quick reply, sorted the issue right away

**Comment by avneetsb** [comment]
closed #2835
