### ISSUE TITLE
Is not accepting the config.json file

### ISSUE THREAD

**Issue by Parth6182** [PokemonGoF/PokemonGo-Bot#2836]
2016-08-07 20:56:23,648 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 20:56:23,649 [       cli] [INFO] No config argument specified, checking for /configs/config.json
2016-08-07 20:56:23,652 [      root] [ERROR] No tasks are configured. Did you mean to configure some behaviors? Read https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files#configuring-tasks for more information

This is the same config file that was working with the previous version of the bot before the Api broke

**Comment by Parth6182** [comment]
{
    "auth_service": "google",
    "username": "DELETED",
    "password": "DELETED",
    "location": "51.5085300,-0.1257400",
    "gmapkey": "DELETED",
    "max_steps": 10,
    "catch_pokemon": true,
    "forts": {
      "spin": true,
      "move_to_spin": true,
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 14.96,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "1": { "keep" : 250 },
      "101": { "keep" : 0 },
      "102": { "keep" : 0 },
      "103": { "keep" : 0 },
      "201": { "keep" : 0 },
      "701": { "keep" : 100 }
    },
    "evolve_all": "NONE",
    "evolve_speed": 20,
    "evolve_cp_min": 300,
    "use_lucky_egg": false,
    "hatch_eggs": true,
    "longer_eggs_first": false,
    "evolve_captured": "NONE",
    "release_pokemon": true,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"keep_best_cp": 1},
      "Eevee": {"keep_best_cp": 1}
    },    
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},
        "Snorlax": {},
        "Dragonite": {},
        "Gengar": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
        
    } 
}

**Comment by Nathanian** [comment]
Same Problem.

"tasks": [{
		"type": "HandleSoftBan"
	}, {
		"type": "CollectLevelUpReward"
	}, {
		"type": "IncubateEggs",
		"config": {
			"longer_eggs_first": true
		}
	}, {
		"type": "TransferPokemon"
	}, {
		"type": "EvolvePokemon",
		"config": {
			"evolve_all": "Pidgey,Weedle,Drowzee,Rattata,Spearow",
			"first_evolve_by": "cp",
			"evolve_above_cp": 1,
			"evolve_above_iv": 0.01,
			"logic": "or",
			"evolve_speed": 20,
			"use_lucky_egg": false
		}
	}, {
		"type": "RecycleItems",
		"config": {
			"item_filter": {
				"Pokeball": {
					"keep": 80
				},
				"Greatball": {
					"keep": 70
				},
				"Ultraball": {
					"keep": 40
				},
				"Potion": {
					"keep": 0
				},
				"Super Potion": {
					"keep": 20
				},
				"Hyper Potion": {
					"keep": 60
				},
				"Revive": {
					"keep": 50
				},
				"Razz Berry": {
					"keep": 50
				}
			}
		}
	}, {
		"type": "CatchVisiblePokemon"
	}, {
		"type": "CatchLuredPokemon"
	}, {
		"type": "SpinFort"
	}, {
		"type": "MoveToFort",
		"config": {
			"lure_attraction": true,
			"lure_max_distance": 2000
		}
	}, {
		"type": "FollowSpiral",
		"config": {
			"diameter": 4,
			"step_size": 70
		}
	}],
	"map_object_cache_time": 5,
	"forts": {
		"avoid_circles": true,
		"max_circle_size": 50
	},
	"websocket_server": false,
	"walk": 11.16,
	"action_wait_min": 1,
	"action_wait_max": 4,
	"debug": false,
	"test": false,
	"health_record": true,
	"location_cache": true,
	"distance_unit": "km",
	"reconnecting_timeout": 15,
	"evolve_captured": "NONE",
	"catch_randomize_reticle_factor": 1.0,
	"catch_randomize_spin_factor": 1.0,
	"catch": {
		"any": {
			"catch_above_cp": 0,
			"catch_above_iv": 0,
			"logic": "or"
		},
		"// Example of always catching Rattata:": {},
		"// Rattata": {
			"always_catch": true
		}
	},
	"release": {
		"Magikarp": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Dratini": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Dragonair": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Eevee": {
			"keep_best_cp": 3,
			"keep_best_iv": 1
		},
		"Electabuzz": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Jynx": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Goldeen": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Horsea": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Krabby": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Hypno": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Gastly": {
			"keep_best_cp": 2,
			"keep_best_iv": 1
		},
		"Haunter": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Shellder": {
			"keep_best_cp": 2,
			"keep_best_iv": 1
		},
		"Cloyster": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Magnemite": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Abra": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Poliwag": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Golbat": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Zubat": {
			"keep_best_cp": 2,
			"keep_best_iv": 1
		},
		"Jigglypuff": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Fearow": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Spearow": {
			"keep_best_cp": 4,
			"keep_best_iv": 0
		},
		"Raticate": {
			"keep_best_cp": 1,
			"keep_best_iv": 0
		},
		"Pidgeotto": {
			"keep_best_cp": 1,
			"keep_best_iv": 0
		},
		"Pidgey": {
			"keep_best_cp": 5,
			"keep_best_iv": 0
		},
		"Rattata": {
			"keep_best_cp": 5,
			"keep_best_iv": 0
		},
		"Bellsprout": {
			"keep_best_cp": 2,
			"keep_best_iv": 1
		},
		"Seel": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Magmar": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"Seadra": {
			"keep_best_cp": 1,
			"keep_best_iv": 1
		},
		"any": {
			"keep_best_cp": 4,
			"keep_best_iv": 1
		},
		"// Example of always releasing Rattata:": {},
		"// Rattata": {
			"always_release": true
		},
		"// Example of keeping 3 stronger (based on CP) Pidgey:": {},
		"// Pidgey": {
			"keep_best_cp": 3
		},
		"// Example of keeping 2 stronger (based on IV) Zubat:": {},
		"// Zubat": {
			"keep_best_iv": 2
		},
		"// Also, it is working with any": {},
		"// any": {
			"keep_best_iv": 3
		},
		"// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
		"// Zubat": {
			"keep_best_cp": 2,
			"keep_best_iv": 3
		}
	},
	"vips": {
		"Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
		"any": {
			"catch_above_cp": 1200,
			"catch_above_iv": 0.9,
			"logic": "or"
		},
		"Lapras": {},
		"Moltres": {},
		"Zapdos": {},
		"Articuno": {},

		"// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
		"Mewtwo": {},
		"Dragonite": {},
		"Snorlax": {},
		"// Mew evolves to Mewtwo": {},
		"Mew": {},
		"Arcanine": {},
		"Vaporeon": {},
		"Gyarados": {},
		"Exeggutor": {},
		"Muk": {},
		"Weezing": {},
		"Flareon": {}

	}
}

**Comment by BobbyWibowo** [comment]
@Parth6182 Please follow the example in config.json.example. As you can see in your file, you haven't configured any tasks (https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/pogom).
@Nathanian Please wrap them within code markup. They're hard to read that way.

**Comment by Nathanian** [comment]
solved my problem with just renaming the file from "config.json" to "config"

**Comment by BobbyWibowo** [comment]
@Nathanian If you were on Windows, you probably had file extension hidden and it actually already had the JSON extension.

**Comment by Parth6182** [comment]
Thanks :D i was using the old bots template
