### ISSUE TITLE
Botting more than 100 accounts?

### ISSUE THREAD

**Issue by crilleaz** [PokemonGoF/PokemonGo-Bot#2839]
Heya,

Currently setting up around 100 instances for the bot, is there any issue running alot of them at the same time? On the same machine?

There's a tracer behind the characters, any way to delete these?
http://prnt.sc/c2pmj7

Thanks

**Comment by BobbyWibowo** [comment]
@crilleaz I'm assuming as long as your machine is strong enough (both hardware and network), you'll be good to go. Also, why do people still use Lightshot? That thing is horrible. Also I can't ever load any picture from that.

**Comment by nivong** [comment]
I would recommend proxy if you are going to do 100 instances (why on earth do you want so many bots anyways!?) is just not logical for niantac and it will be easier to bann you if you don't use a proxy.

**Comment by crilleaz** [comment]
Alright, the hardware is more then enough.

I will give it a try now when the bot is working.

**Comment by Kassadd** [comment]
> There's a tracer behind the characters, any way to delete these?
http://prnt.sc/c2pmj7

The red lines? Change botPath in userdata.js (web/config) to false...

**Comment by crilleaz** [comment]
@Kassadd thank you

**Comment by BobbyWibowo** [comment]
@Kassadd Oh, the bot path in the web interface.. Well, there you go.

**Comment by crilleaz** [comment]
Is there any resources being used for these paths? alot of requests to the API?

**Comment by aceus1** [comment]
@crilleaz 100 bots?? #did you play the tutorial yourself on your mobile or did the bot do it? #2830

**Comment by nivong** [comment]
@crilleaz surreee you are giving them away for free ;) dont ruin the game that's all i can say. please close if it's answered. It logs the location to a file so yes.

**Comment by BobbyWibowo** [comment]
@crilleaz No. It simply logs every change from the location JSON file, which will be loaded regardless of whether you use bot path or not (since that file contains all location data such as pokestops, gyms and whatnot).

**Comment by crilleaz** [comment]
Thanks!

**Comment by crilleaz** [comment]
@BobbyWibowo thanks!

**Comment by nivong** [comment]
@BobbyWibowo so the resource being used is the I/O ;) ?

**Comment by BobbyWibowo** [comment]
@nivong Indeed. I actually meant to say no the "requests to the API" part, lol

**Comment by crilleaz** [comment]
@nivong yes, i give them out for free, im not planning to destroy anything but i'd like my friends and people around me to enjoy the game, wich you do not at the first 20 levels.

**Comment by nivong** [comment]
I totally disagree with that, you level up much quicker on a low level you get more rewards. After level 20 it gets much harder to get more rewards and catching pokemons gets more difficult too. I wouldn't recommend it to my friends to start of with lvl 20 (i wouldn't recommend that in any game tbh...)

**Comment by crilleaz** [comment]
you are welcome to disagree with anything i say! botting is fun, people enjoy the accounts.
