### ISSUE TITLE
Where do you guys usually set the location?

### ISSUE THREAD

**Issue by cdpiano** [PokemonGoF/PokemonGo-Bot#2841]
I noticed many people could get around 50k experience per hour but I can usually get around 25k experience where I set in Fishman's Wharf. I'm wondering if there is a better place to farm using the bot?
Any recommendations is greatly appreciated!

**Comment by brambi** [comment]
#2780 

but central park and santa monica pier are pretty good

**Comment by BobbyWibowo** [comment]
+1 to central park, though I'm up for suggestion as well

**Comment by helmut1337** [comment]
Won't I get banned if I farm in central park and then play in germany?

**Comment by designer2k2** [comment]
nearest big city downtown.

**Comment by PraeceptorXS** [comment]
Santa Monica pier has a diverse range of fairly good pokemon: it is a hotspot for growlithes, kabutos, machops, nidorans, and less often, starter pokemon. Central park is a great place to catch electrabuzzes, but (in my opinion) doesn't have as much diversity as Santa Monica Pier.
