### ISSUE TITLE
Where do i find encrypt.so for windows x86 OS.?

### ISSUE THREAD

**Issue by rahul1205** [PokemonGoF/PokemonGo-Bot#2844]

**Comment by BobbyWibowo** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2706#issuecomment-238074250

**Comment by rahul1205** [comment]
Thank You!!! You rock!!!

**Comment by rahul1205** [comment]
@BobbyWibowo  can i request you to host those 'dll' files somewhere as i dont have acess to slack chat. Your help would be much appreciated. :)

**Comment by BobbyWibowo** [comment]
@rahul1205 Register at the Slack group: https://pokemongo-bot.herokuapp.com/ then look for all uploaded files in the group from this link: https://pokemongo-bot.slack.com/files after that, simply look for encrypt.dll (if you're on Win x86).

**Comment by relomy** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/pogom

**Comment by rahul1205** [comment]
@relomy  Thanks mate..!! Help was much appreciated..Closing this issue now. Resolved..:)
