### ISSUE TITLE
Error after -> Found encrypt_64.dll!

### ISSUE THREAD

**Issue by Lukkasss** [PokemonGoF/PokemonGo-Bot#2848]
### Expected Behavior
Bot running.

### Actual Behavior
Bot doesn't run and ends with the error below after checking encrypt_64.dll.

`2016-08-07 12:48:02,953 [PokemonGoBot] [INFO] Found encrypt_64.dll! Platform: win32 Bot root directory: C:\Users\GoE\desktop\dev\PokemonGo-Bot
2016-08-07 12:48:02,953 [PokemonGoBot] [INFO]
Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 130, in main
    report_summary(bot)
  File "pokecli.py", line 139, in report_summary
    metrics.capture_stats()
  File "C:\Users\GoE\desktop\dev\PokemonGo-Bot\pokemongo_bot\metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "C:\Users\GoE\desktop\dev\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 106, in call
    result = self._call()
  File "C:\Users\GoE\desktop\dev\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "c:\users\GoE\desktop\dev\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "c:\users\GoE\desktop\dev\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)`

### Steps to Reproduce
Run bot.

### Other Information
OS: Windows 10
Git Commit: 6960f356a8d841cefbfd1018b23877b73a6a0d12
Python Version: Python 2.7.11

How can I fix this issue, I'm actually trying to run the bot in the last 3 days but didn't got any luck.

I've tried master and now trying dev versions.

Thanks in advance.

**Comment by BobbyWibowo** [comment]
Were you running the bot with Python 64 bit and on Windows 64 bit? I honestly can't understand that "error" message, so I'm just gonna guess here.

cc: #2780

**Comment by Lukkasss** [comment]
Yes, both Python and Windows x64.

**Comment by nivong** [comment]
use docker :) so much easier

**Comment by BobbyWibowo** [comment]
I'm lost then. I ran the bot with Python 64 bit and on Windows 64 bit, also with encrypt_64.dll and it worked without issue. Sorry, but you'll have to wait for someone who know more about this.

**Comment by Lukkasss** [comment]
@nivong I'll try to setup and use docker now, thanks for the suggestion.

**Comment by jurjen2000** [comment]
I have the same problem. Did running with docker fix it for you?

**Comment by jurjen2000** [comment]
@BobbyWibowo Where did you get encrypt_64.dll. For me the issue is that I can't find it anywhere....

**Comment by BobbyWibowo** [comment]
@jurjen2000 https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/pogom take encrypt64bit.dll and name it as encrypt_64.dll.

**Comment by jurjen2000** [comment]
@BobbyWibowo Thanks a lot. Everything is working now. :)

**Comment by Lukkasss** [comment]
@BobbyWibowo and @nivong just for you guys know, It's fixed now. The problem was the DLL, I think I've gotten a corrupted one. I just replaced the encrypt64.dll with that one Bobby posted and everything is working now.

Thanks for your support.
