### ISSUE TITLE
Stuck requirements.txt

### ISSUE THREAD

**Issue by savoyepolo** [PokemonGoF/PokemonGo-Bot#2857]
### Expected Behavior

Install requirements.txt

### Actual Behavior

Stuck on : Running setup.py bdlist_wheel for numpy

### Steps to Reproduce

$ git clone --recursive -b master https://github.com/PokemonGoF/PokemonGo-Bot  
$ cd PokemonGo-Bot
$ virtualenv .
$ source bin/activate  
$ pip install -r requirements.txt

### Other Information
OS: Raspbian
Git Commit: eeecbc6c78d292fc916e4830fba1df290adb6ec4
Python Version: Python 2.7.9

Thank's for your help

**Comment by nivong** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2808

**Comment by savoyepolo** [comment]
Ok thank's i check that

**Comment by savoyepolo** [comment]
Now i got Failed building wheel for numpy :/

**Comment by jcoinas** [comment]
hey how did u get over this?
