### ISSUE TITLE
No /configs/config.json or specified config

### ISSUE THREAD

**Issue by icecubeice** [PokemonGoF/PokemonGo-Bot#2865]
Whenever I start the bot using python pokecli.py this happens:
$ python pokecli.py
2016-08-08 00:47:22,256 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-08 00:47:22,259 [       cli] [INFO] Error: No /configs/config.json or sp                                                                                                                                                      ecified config
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-ws WEBSOCKET.SERVER_URL]
                  [-wss WEBSOCKET.START_EMBEDDED_SERVER]
                  [-wsr WEBSOCKET.REMOTE_CONTROL] [-p PASSWORD] [-l LOCATION]
                  [-lc LOCATION_CACHE] [--forts.spin FORTS.SPIN] [-w WALK]
                  [-k GMAPKEY] [-e SHOW_EVENTS] [-d DEBUG] [-t TEST]
                  [-du DISTANCE_UNIT] [-ec EVOLVE_CAPTURED]
                  [-rt RECONNECTING_TIMEOUT] [-hr HEALTH_RECORD]
                  [-ac FORTS.AVOID_CIRCLES] [-mcs FORTS.MAX_CIRCLE_SIZE]
                  [--catch_randomize_reticle_factor CATCH_RANDOMIZE_RETICLE_FACT                                                                                                                                                      OR]
                  [--catch_randomize_spin_factor CATCH_RANDOMIZE_SPIN_FACTOR]
                  [--map_object_cache_time MAP_OBJECT_CACHE_TIME]
pokecli.py: error: argument -a/--auth_service is required

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by icecubeice** [comment]
Maybe I'm editing the wrong directory? How to find the correct one

**Comment by chr1spy** [comment]
You want to rename /configs/example.config.json to /configs/config.json.

**Comment by icecubeice** [comment]
Ohhhok ty I'm working on it, turns out the ones I edited were examples

**Comment by Nathanian** [comment]
same problem even though i made a config.json file
