### ISSUE TITLE
[Feature request] Random walk speed

### ISSUE THREAD

**Issue by Tetranima** [PokemonGoF/PokemonGo-Bot#2869]
### Expected Behavior
Make the bot randomly increase/decrease actual speed value between two values.
In order to make our stats less detectable as a bot player.

in config.json we could have this :
"maxWalk": 13,
"minWalk": 4,

And then in your code:
- something that memorize actual walk speed : actualWalk
- something that randomly change the actual walk speed like :

speedChange = random number between -2 and 2 (so its seems normal speed walk change) (maybe other values idk, its just an example)

newWalkSpeed = actualWalk + speedChange;

if (newWalkSpeed <= maxWalk && newWalkSpeed >= minWalk)
{
    actualWalk = newWalkSpeed ;
}

### Actual Behavior
Constant speed walk

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by leadboots5** [comment]
implemented with #3943
