### ISSUE TITLE
[Feature Request] Generate random path in given area.

### ISSUE THREAD

**Issue by seehuily** [PokemonGoF/PokemonGo-Bot#2876]
Sorry I don't how to make this as an enhancement. 

This enhancement is like:
1). Define a square(define 4 GPS points, e.g. a building, a park) in config.json. 
2). Bot loop walking inside this area, won't walk out of range. 

Thanks.

**Comment by dezayner** [comment]
Use "FollowPath" task

**Comment by seehuily** [comment]
FollowPath only follows a straight line right? how about randon pacing within an area.

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by mjmadsen** [comment]
With noise and FollowPath, this is somewhat met. Please reopen and expand if needs not met.
