### ISSUE TITLE
/TUTO/ Which files modify after installing the program? /ON IOS MAC/

### ISSUE THREAD

**Issue by blackchass** [PokemonGoF/PokemonGo-Bot#2878]
### Expected Behavior
Run the bot from the file downloaded on GitHub

### Actual Behavior
Don't know which file modify since there is no tuto since the API update

Could someone explain to me how to run the bot on mac? There is no explanation about the new bot, the wiki is note up to date.
After creating a file , running on the terminal, downloading files, what config files should i modify? 
can't manage to run it properly. 

Many thanks in advance

**Comment by PraeceptorXS** [comment]
Edit the config.json.example with your information and delete the rest of the files in the configs folder if you do not need them. Make sure to rename configs.json.example to config.json. Validate your .json at  [this website](http://jsonlint.com) and then paste the info back into the file. You should be able to run it now.

**Comment by blackchass** [comment]
I deleted all the other files in /config, i kept config.json , fulfilled my information. I still get this error when trying to run the bot

2016-08-08 02:51:21,661 [PokemonGoBot] [INFO] Platform: darwin Bot root directory: /Users/louischassagne/Desktop/PokeBot/PokemonGo-Bot

Any idea?
