### ISSUE TITLE
Problem Starting Bot...

### ISSUE THREAD

**Issue by Oncoming-Storm** [PokemonGoF/PokemonGo-Bot#2879]
Alright I apologize for the stupidity I am about to demonstrate, sorry... I'm a noob
So basically I downloaded the new .zip unziped it on my desktop went to the configs folder removed the .example and I put all my settings except on the google mpas API I left that blank I remember a tutorial telling me to do that.... Then running install.sh and then run.sh but when I run that I just pops up and closes right after. It says bash: Python: command not found. Help me out here please...

OS: Windows 7 64 Home Edition
Git Commit: (no idea how to do this)
Python Version: (Python 2.7.12)

**Comment by mrthrowaway** [comment]
Perhaps try again with these instructions for your OS
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation

A tutorial asking you to run .sh files is probably meant for MacOS/Linux

**Comment by leadboots5** [comment]
proper installation likely fixed as he has opened a new ticket about config.
