### ISSUE TITLE
Can't see my trainer on the google map

### ISSUE THREAD

**Issue by krook1024** [PokemonGoF/PokemonGo-Bot#288]
### Expected Behavior
Seeing my trainer on the Google maps, a little icon follows its moves.

### Actual Behavior
Nothing is shown.

### Steps to Reproduce
Just run the script and see if your map updates.

### Other Information
OS: Windows 7
Git Commit: 270a79dbe52cf9eec7404bbb5bc112fea4fb219d

**Comment by krook1024** [comment]
![image](https://cloud.githubusercontent.com/assets/9162926/17071467/fcbd7d56-5061-11e6-8f0b-b2a5ce55c0c7.png)

**Comment by crusardri** [comment]
install xampp, start apache, move the folder web to C:\xampp\htdocs
Go to localhost/web
