### ISSUE TITLE
Typo in EvolvePokemon

### ISSUE THREAD

**Issue by BeAtS85** [PokemonGoF/PokemonGo-Bot#2883]
### Expected Behavior
"type": "EvolvePokemon",
        "config": {
            "evolve_all": "all",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": true
        }

Bot evolved all pokemon meeting the conditions and activates a lucky egg. 

### Actual Behavior
Bot gives an error and quits.

### Steps to Reproduce
Set Use_lucky_egg to "true"

The problem is in evolve_pokemon.py. 

```
        # Make sure the user has a lucky egg and skip if not
        if lucky_egg_count > 0:
            response_dict_lucky_egg = self.bot.use_lucky_egg()
            if response_dict_lucky_egg:
                result = response_dict_lucky_egg.get('responses', {}).get('USE_ITEM_XP_BOOST', {}).get('result', 0)
                if result is 1:  # Request success
                    self.emit_event(
                        'used_lucky_egg',
                        formmated='Used lucky egg ({amount_left} left).',
                        data={
                             'amount_left': lucky_egg_count - 1
                        }
```
Change **formmated='Used lucky egg ({amount_left} left).',** to **formatted='Used lucky egg ({amount_left} left).',**
### Other Information
OS: Win 10
Git Commit: 6960f356a8d841cefbfd1018b23877b73a6a0d12
Python Version: Python 2.7.11

**Comment by mjmadsen** [comment]
#2912 There is a PR in for this
