### ISSUE TITLE
The cool UI and colours are gone

### ISSUE THREAD

**Issue by Parth6182** [PokemonGoF/PokemonGo-Bot#2885]
The spacing, UI and colours that depicted a caught pokemon, hatching, spinning and other stuff are gone ( mac )

**Comment by Nathanian** [comment]
same on windows

**Comment by hklcf** [comment]
same

2750255a974ac1d2c83db26a47b19092d45293d4

**Comment by hklcf** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/2809#issuecomment-238083148
