### ISSUE TITLE
Stuck installing numpy

### ISSUE THREAD

**Issue by savoyepolo** [PokemonGoF/PokemonGo-Bot#2891]
##Expected Behavior

Install requirements.txt

##Actual Behavior

Stuck on : Running setup.py bdlist_wheel for numpy

##Steps to Reproduce

$ git clone --recursive -b master https://github.com/PokemonGoF/PokemonGo-Bot

$ cd PokemonGo-Bot
$ virtualenv .
$ source bin/activate

$ pip install -r requirements.txt

##Other Information

OS: Raspbian
Git Commit: eeecbc6c78d292fc916e4830fba1df290adb6ec4
Python Version: Python 2.7.9

Thank's for your help

**Comment by 4m4rOk** [comment]
Try running pip in verbose mode e.g. `pip install -r -v -v requirements.txt` and see if it get's stuck anywhere.
A raspberry pi is not the fastest machine and there is possibility it's still compiling in the background.

**Comment by savoyepolo** [comment]
Thanks ! I will check that

**Comment by luxh93** [comment]
any updates on this? @savoyepolo was it just the compilation in the background?

**Comment by savoyepolo** [comment]
@lux93 yep thank's @4m4rOk that took 1h
