### ISSUE TITLE
[Bug] Keep best cp 0 keeps all.

### ISSUE THREAD

**Issue by firzzen** [PokemonGoF/PokemonGo-Bot#2892]
### Expected Behavior

"Jynx": {"keep_best_cp": 0},

Should release/transfer all Jynx.

### Actual Behavior

Does not transfer any Jynx.

### Steps to Reproduce

In config release setup put:

"Jynx": {"keep_best_cp": 0},

### Other Information
OS: Ubuntu 15.04
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: 2.7.9

![screenshot11](https://cloud.githubusercontent.com/assets/20745074/17464350/fd234e1c-5ce4-11e6-9dd6-166d31efe400.JPG)

**Comment by RaizenInstinct** [comment]
well no. Keep = keep. Release = release. Just change the keep to relelase and it will release all jynx. Or change the CP 0 to 2000 and it will release all jynx as well... unless you get a strong one which you might wanna keep anyways :)

**Comment by firzzen** [comment]
@RaizenInstinct the "0" in the config does not refer to the CP of the pokemon, it refers to how many you want to keep.

Therefore if Keep = 0 then it should not keep any.

**Comment by imvikash00** [comment]
True. Even I have faced this. I will try to change it to "release_below_cp" and then see what happens

**Comment by imvikash00** [comment]
Try this 
 Rattata": {"always_release": true},
might work. It is present in the example.json

**Comment by firzzen** [comment]
Ok the always_release: true works of course, so does if you just put keep_best_cp: 1 and it will transfer all others.

Nevertheless i believe if keep = 0 it should transfer all.

**Comment by imvikash00** [comment]
I agree that keep=0 should transfer all but that's how it is! :p

**Comment by firzzen** [comment]
Why was this closed? Is it fixed in some commit?
