### ISSUE TITLE
pokecli.py: error: argument -a/--auth_service is required

### ISSUE THREAD

**Issue by spencerby28** [PokemonGoF/PokemonGo-Bot#2893]
PLEASE HELP ME I DO NOT UNDERSTAND WHY THIS KEEPS HAPPENING
![screen shot 2016-08-07 at 11 20 31 am](https://cloud.githubusercontent.com/assets/20891150/17464343/fbca5d8e-5c90-11e6-9acf-fc749fd3baa3.png)

### Other Information
OS: macOS Sierra
Git Commit: idk how to do this
Python Version: 2.7.12

**Comment by chypriote** [comment]
You need to specify an authentication service, i.e: google or ptc

This is because you have no config file, see the error above: 'No /configs/config.json or specified config'

**Comment by spencerby28** [comment]
how do i specify a config.json

**Comment by kyleboe** [comment]
@spencerby28 Just as the error says your auth service is not properly defined.

The script looks for `/configs/config.json` by default and it looks like you have renamed `config.json` to `config-account1.json`. You can do this but you have to specify your new config file location/name in `run.sh` or in whatever startup script you have written.

To be completely honest, if you are not willing to at least do some research/reading and learn how to properly post relevant information 
![image](https://cloud.githubusercontent.com/assets/4054771/17464417/06fc8c48-5c93-11e6-9410-d222e0fa6ef3.png)
 you shouldn't be creating an issue on github. Try posting someplace less code-focused, like reddit.

**Comment by spencerby28** [comment]
okay thanks
& sorry

**Comment by kyleboe** [comment]
@spencerby28 no worries friend. I do want you to get the help you need, just in the right forum so that development of the bot can be focused and efficient.

**Comment by spencerby28** [comment]
yea I've been trying to figure it out on my own but i couldn't so i just asked @kyleboe

**Comment by kyleboe** [comment]
@spencerby28 I would not recommend using docker either if you don't know how it works/what all of the configuration options are. Just use [Homebrew](http://brew.sh/) (macOS package manager) to install python

```
brew install python
```
 use git to clone in the dev branch 
```
git clone git@github.com:PokemonGoF/PokemonGo-Bot.git
git checkout dev
```
 use pip to install the requirements
```
pip install -r requirements.txt
```
then make sure you have the `encrypt.so` file in the root of the project directory as well as your `config.json` (named exactly like that) in the configs folder.

After that you should be able to simply use included shell script by executing:
```
./run.sh
```
and it should work correctly.

**Comment by SamBonedJody** [comment]
Hey @spencerby28 

You May want to check out my response in #2955 and see if that does the trick
