### ISSUE TITLE
Cannot pip install on dev branch, but master works

### ISSUE THREAD

**Issue by rwwagner90** [PokemonGoF/PokemonGo-Bot#290]
### Expected Behavior
Be able to pip install

### Actual Behavior
Getting this error:

```
Obtaining pgoapi from git+git://github.com/tejado/pgoapi.git@1f25e907f3e5f1b603330e71041e1ad7bee7580f#egg=pgoapi (from -r requirements.txt (line 1))
  Updating ./venv/src/pgoapi clone (to 1f25e907f3e5f1b603330e71041e1ad7bee7580f)
  Could not find a tag or branch '1f25e907f3e5f1b603330e71041e1ad7bee7580f', assuming commit.
  Running setup.py egg_info for package pgoapi
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/Users/rwwagner/PokemonGo-Bot/venv/src/pgoapi/setup.py", line 9, in <module>
        install_reqs = parse_requirements(path_req, session=False)
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/rwwagner/PokemonGo-Bot/venv/src/pgoapi/setup.py", line 9, in <module>

    install_reqs = parse_requirements(path_req, session=False)

TypeError: parse_requirements() got an unexpected keyword argument 'session'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /Users/rwwagner/PokemonGo-Bot/venv/src/pgoapi
Storing complete log in /Users/rwwagner/.pip/pip.log
```

### Steps to Reproduce
Just following the OS X setup instructions on the dev branch and the pip install will fail

### Other Information
OS: OS X 10.11.5
Git Commit: 270a79dbe52cf9eec7404bbb5bc112fea4fb219d

**Comment by Grace** [comment]
In order to get `pip install -r requirements.txt` on Mac OS X, I had to make a few changes.

1. Change the first line of requirements.txt to `-e git+https://github.com/tejado/pgoapi.git#egg=pgoapi`
2. Install updated colorama with `pip install colorama --upgrade`
3. Run `sudo pip install -r requirements.txt`

**Comment by rwwagner90** [comment]
@Grace I tried your instructions and I am getting the same error. `TypeError: parse_requirements() got an unexpected keyword argument 'session'`

**Comment by douglascamata** [comment]
Consider using `virtualenv` guys.  It should work.

**Comment by rwwagner90** [comment]
@douglascamata I am using virtualenv. It only works with master. Cannot get dev running

**Comment by douglascamata** [comment]
output of `which pip` and `which python`?

**Comment by vanrzuf** [comment]
i have the same error with installing requirements

**Comment by rwwagner90** [comment]
@douglascamata 

`/Users/rwwagner/PokemonGo-Bot/venv/bin/pip`

and

/Users/rwwagner/PokemonGo-Bot/venv/bin/python

**Comment by douglascamata** [comment]
I did mention the wrong issue in my commit, ignore it.

**Comment by douglascamata** [comment]
What a weird error, makes no sense!

**Comment by rwwagner90** [comment]
It's something with the dev branch specifically, so not really sure

**Comment by douglascamata** [comment]
it's because of the way we download pgoapi, which needs to be locket to a specific commit, otherwise people may get different code if they install before/after others

**Comment by rwwagner90** [comment]
@douglascamata I'm not sure how pulling a specific commit is making this error happen though

**Comment by rwwagner90** [comment]
For anyone else with this issue install pip from here https://pip.readthedocs.io/en/stable/installing/

The pip included when you `brew install python` was breaking things
