### ISSUE TITLE
Use lucky egg isnt working

### ISSUE THREAD

**Issue by reside** [PokemonGoF/PokemonGo-Bot#2900]
### Expected Behavior
"use_lucky_egg": true is working

### Actual Behavior
016-08-07 21:26:07,943 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "C:\Users\PokemonGo-Bot-devencr\PokemonGo-Bot-dev\pokecli.py", line 501, in <module>
    main()
  File "C:\Users\PokemonGo-Bot-devencr\PokemonGo-Bot-dev\pokecli.py", line 132, in main
    raise e
TypeError: emit_event() got an unexpected keyword argument 'formmated'

### Steps to Reproduce
"use_lucky_egg": true

### Other Information
Unknown how long it has been broken.

**Comment by WHAAAT** [comment]
hello, 
as you can see the error is 
TypeError: emit_event() got an unexpected keyword argument 'formmated'

can you please try to change in pokecli the line 
"formmated" to"formated" ?

maybe it fixes the error

**Comment by BeAtS85** [comment]
See [https://github.com/PokemonGoF/PokemonGo-Bot/issues/2883]

**Comment by mjmadsen** [comment]
#2912 There is a PR in for this
