### ISSUE TITLE
Can't Start

### ISSUE THREAD

**Issue by Jot18** [PokemonGoF/PokemonGo-Bot#2901]
Can someone please make a tutorial for a newbie... I can't get it to start After I downloaded the PyYAML file i run in gitbash and it says no such file or directory even though I saved it in the download folder... I am a total noob and have no idea how this really works if someone can make a tutorial for a dummy I'll be thankful.
Windows 10 64 Bit.

**Comment by kyleboe** [comment]
I mentioned this in [another thread](https://github.com/PokemonGoF/PokemonGo-Bot/issues/2893#issuecomment-238099754), but GitHub issues really isn't the place to be creating noobie questions like this. I would recommend posting on reddit or just doing a solid amount of googling/reading before posting a more specific issue here.

**Comment by Jot18** [comment]
I would have posted on reddit but didn't they just started banning/warning users that posted about bots? I've been googling about this but didn't find anything.

**Comment by kyleboe** [comment]
Ah, I didn't know about the reddit bot ban. I use a mac to run the bot so, unfortunately I can't be of any assistance when it comes to Windows 10.

**Comment by MikeDX** [comment]
This should be asked on slack, or you should follow the instructions on the WIKI.
