### ISSUE TITLE
Bot Won't Start | UnicodeDecodeError

### ISSUE THREAD

**Issue by GitPupper** [PokemonGoF/PokemonGo-Bot#2903]
### Expected Behavior
Bot runs.
***
### Actual Behavior
Bot errors out.
***
### Steps to Reproduce
`$ python pokecli.py`
***
### Other Information
OS:  Mac OSX El Capitan
Git Commit: fddf30dd64322219c945a1aba3483f603ce55bcc
Python Version: Python 2.7.12
[Pastebin Error](http://pastebin.com/9EdxSFrA)
[Pastebin Config.json](http://pastebin.com/qBJid7n9)
I have the Config.son in the main directory and in the Config directory. Doesn't make a difference.
My API project is set to a **Google Maps Directions API**.
***
#### Edit
Thanks [manu183](https://github.com/manu183)!
I updated my Config to change the coordinates to Lat/Long instead of just having it typed out. That fixed my **NoPlayerPositionSetException** error but I still have the **UnicodeDecodeError** (UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128))
***
####Update
Thanks [manu183](https://github.com/manu183)!
The fix is [Here](https://github.com/PokemonGoF/PokemonGo-Bot/issues/2866#issuecomment-238094123)

**Comment by kgurnani96** [comment]
im getting the same error as you

**Comment by manu183** [comment]
You could try entering the geocoordinates, e.g. 34.0201813,-118.6919205 for LA.

**Comment by kgurnani96** [comment]
got the fix, https://github.com/PokemonGoF/PokemonGo-Bot/issues/2866#issuecomment-238094123
