### ISSUE TITLE
Location Events log level should be the same

### ISSUE THREAD

**Issue by RomikB** [PokemonGoF/PokemonGo-Bot#2904]
### Expected Behavior

location cache events log level should be the same as location_found event log level

### Actual Behavior

location_found log level is info,
location cache log level is debug

### Steps to Reproduce

just run

### Other Information
OS: Linux
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by kyleboe** [comment]
I will, respectfully, say that this is more of a design opinion than an actual issue. The location cache information is not entirely relevant to those simply wanting to start where they left off. Location_Found information is relevant to all users, hence the info categorization. 

If you like seeing the location cache information you are free to leave the debug flag set to true but for those that find that information irrellevant, they can set debug to false and carry on without knowledge as to whether or not the location_cache was used.

**Comment by RomikB** [comment]
This events are fired one after another only on start. if log level is info and location cache is true I see in log not actual position where I start.
