### ISSUE TITLE
Encryption? Issues. Bot only walking, not performing.

### ISSUE THREAD

**Issue by vulgy** [PokemonGoF/PokemonGo-Bot#2906]
### Expected Behavior

Proper functioning bot.

### Actual Behavior

Good afternoon,

My bot was properly functioning before the recent API change. Now that the bot is up again, I am able to start it, but it only walks around, not hatching/catching/spinning. Some others are sharing my experience. I downloaded the encrypt.so file, placed it in the PokemonGO-Bot folder. I looked inside my __init__.py file, but didn't find an encrypt line. Using command+F, it wasn't detected. I suspect my issue is with the encryption part, but I don't know how to rectify.

Any insight would help as I am very new to these programs and code-language.

[14:53:32]  Server seems to be busy or offline - try again - 1/5 
[14:53:34]  Starting PokemonGo Bot.... 
[14:53:35]  [x] Next egg incubates in 3.26 km 
[14:53:39] Walking from (XX, -XX) to [XX, -XX] 0.00km
[14:53:44] Walking from (XX, -XX) to [XX, -XX] 0.20km
[14:56:29] Walking from (XX, -XX) to [XX, -XX] 0.15km
[14:58:40] Walking from (XX, -XX) to [XX, -XX] 0.20km
etc

### Steps to Reproduce

cd PokemonGo-Bot  
virtualenv .  
source bin/activate  
pip install -r requirements.txt
python pokecli.py

### Other Information
OS: OSX

**Comment by sinthu94** [comment]
do you have the latest version of the bot?
did you perform a git pull?

**Comment by Mlieou** [comment]
It seems you are still using old version, you should get the latest version of the bot.
See #2540

**Comment by vulgy** [comment]
Thanks, guys. I did perform a git pull. As for the version, I ran pip install -r requirements.txt to get the new pgoapi and I also downloaded the encrypt.so file.

Does that constitute updating the version?

**Comment by kyleboe** [comment]
@vulgy that should be enough. I found that running `pip install --upgrade -r requirements.txt` can sometimes resolve out-dated dependency related issues.

**Comment by vulgy** [comment]
Kyle, thank you for that. It returned me this:

Installing collected packages: pgoapi, setuptools
  Running setup.py develop for pgoapi
  Found existing installation: setuptools 25.1.3
    Uninstalling setuptools-25.1.3:
      Successfully uninstalled setuptools-25.1.3
Successfully installed pgoapi-1.1.0 setuptools-25.1.6

Unfortunately, that did not alleviate the bot's unresponsiveness.

**Comment by jokoast** [comment]
I have a question for you.
Where did you found your encrypt.so on Mac ?
Can't find it ...

**Comment by vulgy** [comment]
I downloaded it from the slack chat. 
I would upload it, but .so files aren't supported in this forum.

**Comment by jokoast** [comment]
Ok thx buddy. I'll see if i can connect on.

**Comment by jokoast** [comment]
I can connect on but it reached the integration limit ... Can you send me a DL link via PM or post it here ?

**Comment by vulgy** [comment]
I have found a solution in this way: I deleted my PokemonGo-Bot folder, ran:
git clone --recursive -b dev https://github.com/PokemonGoF/PokemonGo-Bot
(make sure its _dev_ and not _master_), then the usual:
cd PokemonGo-Bot  
virtualenv .  
source bin/activate  
pip install -r requirements.txt
python pokecli.py

And it worked! Caught my first poke since the API change. Thanks everyone for the help.
