### ISSUE TITLE
Release config question

### ISSUE THREAD

**Issue by surewhynotmon** [PokemonGoF/PokemonGo-Bot#2907]
### Expected Behavior
Releasing eevee that is below 0.80 in iv

### Actual Behavior
I have 5 eevee and one of them has 0.59 iv

But the 0.49 iv eevee just won't be released.
By the way, can you do keep and release config together?

### Steps to Reproduce
Use following release config
````
"any": {"keep_best_iv": 3, "release_below_cp": 1000, "release_below_iv": 0.8, "logic": "and"}, 
"// Eevee evolves to many versions, like Vaporeon, Flareon": {},
"Eevee": { "release_below_iv": 0.8 },
````
It won't try to release the eevee  with 0.59 iv and 507 cp

### Other Information
OS: 
Git Commit: 4eb7b388d950ff9d9517b5223967aa10adfbb10d
Python Version: 2.7.11

**Comment by RedViper9** [comment]
Are you still having issues with the release config?

**Comment by DDock** [comment]
I'm trying to do this same thing.

`"Raticate": {"keep_best_iv": 4, "release_below_iv": 0.85, "release_below_cp": 0, "logic": "and"},`

Somehow I have 5 Raticates with a IV: 71 and 84 mixed in.

Same question as OP: Can you use both `"keep_best_iv":` and `"release_below_iv":` in the same statement?
