### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by jallart** [PokemonGoF/PokemonGo-Bot#2919]
### Expected Behavior
Install -r requirements.

### Actual Behavior
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sd/9mn7znqn3vs0rrz1v5nw_zqm0000gn/T/pip-build-uP3UKO/protobuf-to-dict/

### Steps to Reproduce
pip install -r requirements.txt

### Other Information
OS: Mac OS
Python Version: 2.7.12

**Comment by MicaelCarvalho** [comment]
Some of your libs were installed by apt-get instead of pip. You have to uninstall them with apt-get and reinstall them using pip, I had the same error and fixed this way. To find out which libs are problematic, see the logs pip created.

**Comment by jallart** [comment]
Here is the log, there are a lot of issues... : 
(PokemonGo-Bot) MacBook-Pro-de-Julien:PokemonGo-Bot jallart$ pip install -r requirements.txt
Collecting numpy==1.11.0 (from -r requirements.txt (line 1))
  Using cached numpy-1.11.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting networkx==1.11 (from -r requirements.txt (line 2))
  Using cached networkx-1.11-py2.py3-none-any.whl
Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@249d3be7fbbdabc7f9adea17cbc899d6549e47a2#egg=pgoapi (from -r requirements.txt (line 3))
  Skipping because already up-to-date.
Collecting geopy==1.11.0 (from -r requirements.txt (line 4))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==3.0.0b4 (from -r requirements.txt (line 5))
  Using cached protobuf-3.0.0b4-py2.py3-none-any.whl
Collecting requests==2.10.0 (from -r requirements.txt (line 6))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 7))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 8))
  Using cached gpsoauth-0.3.0.tar.gz
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 9))
  Using cached protobuf-to-dict-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/nosexcover/: [Errno 54] Connection reset by peer -- Some packages may not be found!
    Couldn't find index page for 'nosexcover' (maybe misspelled?)
    No local packages or working download links found for nosexcover
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/sd/9mn7znqn3vs0rrz1v5nw_zqm0000gn/T/pip-build-aOPPyj/protobuf-to-dict/setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/jallart/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/dist.py", line 348, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/jallart/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/dist.py", line 394, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/jallart/PokemonGo-Bot/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/jallart/PokemonGo-Bot/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1098, in best_match
        return self.obtain(req, installer)
      File "/Users/jallart/PokemonGo-Bot/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1110, in obtain
        return installer(requirement)
      File "/Users/jallart/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/dist.py", line 461, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/jallart/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 658, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('nosexcover')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/sd/9mn7znqn3vs0rrz1v5nw_zqm0000gn/T/pip-build-aOPPyj/protobuf-to-dict/

**Comment by MicaelCarvalho** [comment]
You should always run pip with sudo, and with the upgrade flag:
sudo pip install --upgrade -r requirements.txt

**Comment by jallart** [comment]
Got it, it works, thanks ! :)

**Comment by rfagen** [comment]
I avoid running "sudo pip install..." on a macOS box. First, the system python is used by the system, and I wouldn't want to mess that up. Second, the system python is almost never as up to date as possible. I usually follow the directions at http://docs.python-guide.org/en/latest/starting/install/osx/ to install python2 (and I want to start using python3). Then, I create a virtualenv for each project. It helps cut down on dependency madness.
