### ISSUE TITLE
how do i install update? Sorry 

### ISSUE THREAD

**Issue by keremkayseri** [PokemonGoF/PokemonGo-Bot#2921]
i have the old bot in a file i click on it and start the apk so then it says there is a new Version so i downloaded the update und pulled the new datas to the old files (where the old bot is).
then i start the apk but it says there a new Version do you want to open it?
i´m really sorry buti am new and i dont know how to do this.

**Comment by MikeDX** [comment]
Please ask questions like this on the slack channel. 

Github Issues are not a place to post support requests, they are for reporting bugs

**Comment by nivong** [comment]
You use git commands. Ask Google or go into slack.
