### ISSUE TITLE
 The bot is already working?

### ISSUE THREAD

**Issue by piai46** [PokemonGoF/PokemonGo-Bot#2922]
The bot is already working?

**Comment by piai46** [comment]
how do I use it?

**Comment by SGColdSun** [comment]
Not the place for these questions. You should read the wiki and if you have further questions, join the slack discussion (link on the main page).

**Comment by liudayu** [comment]
Please stop posting 'issues' like this and check before you post.
#2780

**Comment by nivong** [comment]
No for you the bot is broken
