### ISSUE TITLE
new object Signature doesn't send special values

### ISSUE THREAD

**Issue by mrik974** [PokemonGoF/PokemonGo-Bot#2924]
I'm not a python expert, and I have trouble finding the default values for the new Signature proto sent. 
This [reddit comment](https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/d6776g2) says `Also all API requests will appear to Niantic to be coming from IOS users`.
I looked through the code of the API in the new repo by `Keyphact` and I've been totally unable to find any reference to `iPhone` but a comment in [this file](https://github.com/keyphact/pgoapi/blob/master/pgoapi/protos/Signature.proto) saying `string firmware_brand = 10; // On Android: product.name, on iOS: "iPhone OS"`

I can't see where the default value for this is set, and I'm afraid it is finally not set at all. I'm posting this here, but also on the `pgoapi` repo to have a clear answer. Can the bot set this value at this time, and is it doing so, or is there a default value somewhere that I have missed? 

EDIT : 
My question on `pgoapi` [has been answered](https://github.com/keyphact/pgoapi/issues/44).
Here's the answer : 
`You can see what goes into the signature by looking at signature_pb2.py we generate the details in rpc_api.py - I wouldn't worry about the data you send though, the only thing that is validated are the hashed fields which we painstakingly recreated.`

Indeed, there is no special setting for elements like `DeviceInfo`. 

This means **Niantic can actually know who is calling their API from bots**

**Comment by k4n30** [comment]
Issued resolved externally
