### ISSUE TITLE
MoveToPokemonMap - number of workers and snipe

### ISSUE THREAD

**Issue by ksawerykarwacki** [PokemonGoF/PokemonGo-Bot#2925]
Is snipe safe way to catch pokemons? Also what as best number of workers depending on city size to get best results? My city is about 16x22km and I'm looking for good amount of workers to scan.

**Comment by infeedel** [comment]
There's a tool in the PokemonGo-Map under Tools called beehive generator, it generates a ssh which starts multiple accounts from a csv file

https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/Tools/Hex-Beehive-Generator/Instructions_for_location_generator.txt
