### ISSUE TITLE
ImportError: No module named pgoapi.exceptions

### ISSUE THREAD

**Issue by stealdre** [PokemonGoF/PokemonGo-Bot#2927]
Hi guys I had a lot of issues before this one... I start the bot with python pokecli.py or ./run.sh.
But I always have this error: 

Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

Help plz!

### Other Information
OS: Mac OS 
Git Commit: fddf30dd64322219c945a1aba3483f603ce55bcc
Python Version: Python 2.7.10

**Comment by MicaelCarvalho** [comment]
run
> sudo pip install --upgrade -r requirements.txt

**Comment by stealdre** [comment]
I just ruined the pip requirement.txt command and it's working now! Thx

**Comment by PedroTrujilloV** [comment]
also inside the folder "source bin/activate" and run after

**Comment by Benjaminhu** [comment]
the problem (pip install --upgrade -r requirements.txt):
....
Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@a2755eb42dfe49e359798d2f4defefc97fb8163d#egg=pgoapi (from -r requirements.txt (line 3))
  Updating ./src/pgoapi clone (to a2755eb42dfe49e359798d2f4defefc97fb8163d)
  Could not find a tag or branch 'a2755eb42dfe49e359798d2f4defefc97fb8163d', assuming commit.
...
