### ISSUE TITLE
Bot doesn't show correct info with new account

### ISSUE THREAD

**Issue by tomalbrc** [PokemonGoF/PokemonGo-Bot#2929]
### Expected Behavior

Show correct stats with a new account
Example:
`2016-08-07 23:11:41,333 [       cli] [INFO] Ran for 0:15:42`
`2016-08-07 23:11:41,333 [       cli] [INFO] Total XP Earned: 12345  Average: 12345.00/h`
`2016-08-07 23:11:41,333 [       cli] [INFO] Travelled 1.23km`
`2016-08-07 23:11:41,333 [       cli] [INFO] Visited 123 stops`
`2016-08-07 23:11:41,333 [       cli] [INFO] Encountered 123 pokemon, 123 caught, 53 released, 0 evolved, 123 never seen before`
`2016-08-07 23:11:41,333 [       cli] [INFO] Threw 123 pokeballs`
`2016-08-07 23:11:41,333 [       cli] [INFO] Earned 12345 Stardust`

123 values are example values, not actual ones ;)

### Actual Behavior

Outputs:
`2016-08-07 23:11:41,333 [       cli] [INFO] Ran for 0:15:42`
`2016-08-07 23:11:41,333 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h`
`2016-08-07 23:11:41,333 [       cli] [INFO] Travelled 0.00km`
`2016-08-07 23:11:41,333 [       cli] [INFO] Visited 0 stops`
`2016-08-07 23:11:41,333 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 53 released, 0 evolved, 0 never seen before`
`2016-08-07 23:11:41,333 [       cli] [INFO] Threw 0 pokeballs`
`2016-08-07 23:11:41,333 [       cli] [INFO] Earned 0 Stardust`

### Steps to Reproduce

1. Register new account @ PTC
2. Edit config.json
3. Run bot
4. Quit bot

### Other Information
OS: macOS 10.11
Git Commit: fc4e802dd760508e45c9e2f79cdc9704a514b896
Python Version: 2.7.12

**Comment by MikeDX** [comment]
You need to complete the tutorial in the game before your stats will work properly.

**Comment by tomalbrc** [comment]
They work when I run the bot a second time
