### ISSUE TITLE
[Feature Request] Check That Pokemon Storage Is Full Before EvolvePokemon Action

### ISSUE THREAD

**Issue by JonnyBoy333** [PokemonGoF/PokemonGo-Bot#2931]
It would be nice to put a condition on the EvolvePokemon action to only run when the pokemon storage is full. Something like this:

```
		{
			"type": "EvolvePokemon",
			"config": {
                "evolve_when_storage_full": true,
	            "evolve_all": "Pidgey, Weedle, Caterpie",
	            "first_evolve_by": "cp"
	        }
		}
```

**Comment by Anakin5** [comment]
You can try out my pull request and give me your comments about it.
https://github.com/PokemonGoF/PokemonGo-Bot/pull/2956

**Comment by JonnyBoy333** [comment]
This looks promising. Can you update the config file with an example of the new task and it's parameters?

**Comment by k4n30** [comment]
@JonnyBoy333 can this be closed now that the PR has been merged?

**Comment by JonnyBoy333** [comment]
I'd say so. Just updated to the latest commit so I'm eagerly testing the new feature out.
