### ISSUE TITLE
starting again in 10 seconds...

### ISSUE THREAD

**Issue by giordanojr** [PokemonGoF/PokemonGo-Bot#2934]
### Expected Behavior

[18:45:37] Exception: System.ArgumentNullException: Valor não pode ser nulo.
Nome do parâmetro: value
   em Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   em Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   em PokemonGo.RocketAPI.Logic.Utils.LocationUtils.getElevation(Double lat, Dou
ble lon) na C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-New
API\PokemonGo.RocketAPI.Logic\Utils\LocationUtils.cs:linha 23
   em PokemonGo.RocketAPI.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate
 sourceLocation, Double distanceInMeters, Double bearingDegrees) na C:\Users\Ari
\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.RocketAPI.
Logic\Utils\LocationUtils.cs:linha 64
   em PokemonGo.RocketAPI.Logic.Navigation.<HumanLikeWalking>d__4.MoveNext() na
C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonG
o.RocketAPI.Logic\Navigation.cs:linha 48
--- End of stack trace from previous location where exception was thrown ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   em PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__17.
MoveNext() na C:\Users\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-N
ewAPI\PokemonGo.RocketAPI.Logic\Logic.cs:linha 395
--- End of stack trace from previous location where exception was thrown ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   em PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__10.MoveNext() na C:\U
sers\Ari\Desktop\PokemonGo Bot\Github - New API\PokemonGoBot-NewAPI\PokemonGo.Ro
cketAPI.Logic\Logic.cs:linha 129
### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by infeedel** [comment]
Uh, you sure you're in the right repo ?
