### ISSUE TITLE
How to make the Bot ignore the lure factor on the pokestops

### ISSUE THREAD

**Issue by h2xtreme** [PokemonGoF/PokemonGo-Bot#2938]
### Expected Behavior
I have the task Move to Fort with this configuration:

  "type": "MoveToFort",
        "config": {
            "lure_attraction": false,

So I can avoid circling only in the lured pokestops.
### Actual Behavior
The bot is choosing lured pokestops anyway so ends up running the 3,4 pokestops. After one hour the bot crashes and has walked about 300 meters.

### Other Information
OS: Raspbian
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here) latest dev pull
Python Version: (run 'python -V' and paste it here) 2.7

**Comment by alextj** [comment]
I seem to have the same issue. The bot is constantly choosing lured pokestops even though I have "lure_attraction": false
