### ISSUE TITLE
Bot starts but crashes after encountering a pokemon

### ISSUE THREAD

**Issue by DSFARGEG** [PokemonGoF/PokemonGo-Bot#2940]
### Expected Behavior
Catches pokemon 

### Actual Behavior
Encounter a pokemon then shows its iv details and crashes shortly after

### Steps to Reproduce
Run the bot and encounter a pokemon 

### Other Information
OS: Windows 10 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: 2.7.10

Crash Details

> 2016-08-07 15:09:19,733 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Clefairy appeared! [CP 669] [Potential 0.53] [S/A/D 5/5/14]
> 2016-08-07 15:09:23,546 [       cli] [INFO]
> 2016-08-07 15:09:23,546 [       cli] [INFO] Ran for 0:00:29
> 2016-08-07 15:09:23,548 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
> 2016-08-07 15:09:23,549 [       cli] [INFO] Travelled 0.00km
> 2016-08-07 15:09:23,551 [       cli] [INFO] Visited 0 stops
> 2016-08-07 15:09:23,552 [       cli] [INFO] Encountered 1 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
> 2016-08-07 15:09:23,553 [       cli] [INFO] Threw 0 pokeballs
> 2016-08-07 15:09:23,555 [       cli] [INFO] Earned 0 Stardust
> 2016-08-07 15:09:23,555 [       cli] [INFO]
> 2016-08-07 15:09:23,556 [       cli] [INFO] Highest CP Pokemon:
> 2016-08-07 15:09:23,558 [       cli] [INFO] Most Perfect Pokemon:
> Traceback (most recent call last):
>   File "pokecli.py", line 496, in <module>
>     main()
>   File "pokecli.py", line 132, in main
>     raise e
> AttributeError: 'NoneType' object has no attribute 'get'
>

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this has been resolved.
