### ISSUE TITLE
Not moving to any forts

### ISSUE THREAD

**Issue by savoyepolo** [PokemonGoF/PokemonGo-Bot#2942]
### Expected Behavior

Farming 

### Actual Behavior

Not moving to any forts as there aren't enough scace.

### Steps to Reproduce

./run.sh

### Other Information
OS: Raspbian
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by kdemoya** [comment]
That means your inventory is full, you have to configure `RecycleItems` in your `config.json` in order to limit quantities for each item.

For example: 

```json
{
            "type": "RecycleItems",
            "config": {
                "item_filter": {
                    "Pokeball": {
                        "keep": 50
                    },
                    "Greatball": {
                        "keep": 100
                    },
                    "Potion": {
                        "keep": 10
                    },
                    "Super Potion": {
                        "keep": 20
                    },
                    "Hyper Potion": {
                        "keep": 30
                    },
                    "Revive": {
                        "keep": 30
                    },
                    "Razz Berry": {
                        "keep": 25
                    }
                }
            }
        }
```

**Comment by savoyepolo** [comment]
I did it woth low amounts but not working :/

**Comment by leadboots5** [comment]
what is your config? what does your log look like?

**Comment by BriceSD** [comment]
@savoyepolo Be sure you put RecycleItems before MovingToFort

**Comment by ZeroxD** [comment]
[00:42:27]  Server seems to be busy or offline - try again - 1/5
[00:42:28]  Starting PokemonGo Bot....
[00:42:29]  [x] Current egg hatches in 2.22 km
[00:42:29] Walking from (40.768281143499706, -73.97640533811747) to [40.768281143499706, -73.97640533811747] 0.00km
[00:42:30] Walking from (40.768281143499706, -73.97640533811747) to [40.76891139016751, -73.97640533811747] 0.07km

how can i fix this i am just new here don't know how to start a new topic i did update the bot via git pull. second i change the  "health_record":  to false and now i am confuse what to do next 

every kind of help is welcome

**Comment by savoyepolo** [comment]
My config file is config.json.pokemon.example and @BriseSD RecycleItems is before MovingToFort

**Comment by BriceSD** [comment]
@savoyepolo So you're new and blindly following one config example. Can't blame you for this, by try to delete this snippet until you understand everything in your config file :
```
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
```

**Comment by savoyepolo** [comment]
Ok thank's i try that @BriceSD !

**Comment by savoyepolo** [comment]
@BriceSD error : 

File "pokecli.py" line 501 in <module> main()
File "pokecli.py" line 132 in <module> main()

ValueError: No JSON object could be decoded

**Comment by BriceSD** [comment]
@savoyepolo Hmm weird, I think you deleted too many parenthesis or forgot a "," or something

**Comment by savoyepolo** [comment]
@BriceSD Ok now it's working but same inventory_full error :/

In my config i said : 50 Pokeballs, 5 Potions, 10 SuperPotion
Only low amounts of items :/

**Comment by kdemoya** [comment]
@savoyepolo I insist it's a configuration problem. If you are using the configuration from `config.json.pokemon.example` it doesn't take into consideration `Greatball` and `Ultraball`, so those will be stacking without any limit.

Whenever you start the bot, it should tell you how many units you have for each item, you could easily identify there which is the one not being regulated.

**Comment by LDengX** [comment]
+1 what kdemoya mentioned. 
I have the same issue by copying config from example. What happened was that I have too many Greatballs but I didn't config Greatball in my config.json

**Comment by ikirt** [comment]
edit your config and add the following under "Pokeball":       { "keep" : 50 },

 "Greatball":       { "keep" : 50 },
 "Ultraball":       { "keep" : 50 },

This will drop the excess Great Balls and Ultra Balls
