### ISSUE TITLE
bot crashed

### ISSUE THREAD

**Issue by skywalker878** [PokemonGoF/PokemonGo-Bot#2951]
### Actual Behavior
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
IndexError: list index out of range

### Other Information
OS: windows 7 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by josegrobles** [comment]
same error here

**Comment by celus** [comment]
same, was running fine for hours

**Comment by xlren11** [comment]
Same here

**Comment by iphonitest** [comment]
Same issue

**Comment by taxi333** [comment]
same here

**Comment by Vvkmnn** [comment]
Same on commit dee28d9fb1a973b95019bc07fb1e206872bd986d. Seems related to #2951

**Comment by z4ppy** [comment]
same here : 

Error in pokecli.py on line 76
Error in /home/z4ppy/dev/PokemonGo-Bot/pokemongo_bot/__init__.py on line 75
Error in /home/z4ppy/dev/PokemonGo-Bot/pokemongo_bot/__init__.py on line 647
Error in /home/z4ppy/dev/PokemonGo-Bot/pokemongo_bot/__init__.py on line 463
Error in /home/z4ppy/dev/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py on line 122
Error in /home/z4ppy/dev/PokemonGo-Bot/pokemongo_bot/api_wrapper.py on line 106
Error in /home/z4ppy/dev/PokemonGo-Bot/pokemongo_bot/api_wrapper.py on line 63
Error in /home/z4ppy/dev/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py on line 220
Error in /home/z4ppy/dev/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py on line 129
Error in /home/z4ppy/dev/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py on line 359
Error in /home/z4ppy/dev/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py on line 376
Traceback (most recent call last):
  File "pokecli.py", line 508, in <module>
    main()
  File "pokecli.py", line 139, in main
    raise e
IndexError: list index out of range

New protocole change ! :(

**Comment by thebringerofdeath789** [comment]
bot works again for me

**Comment by BobbyWibowo** [comment]
+1

**Comment by sherbert250** [comment]
Same problem. Hoping Niantic didn't make another update. Not banned though. Checked on my phone and my account is still functioning just fine.

**Comment by Aaronucci** [comment]
I have the same issue.  Happened after pulling g latest dev build. 

Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 132, in main
    raise e
IndexError: list index out of range

**Comment by thebringerofdeath789** [comment]
Well you can all expect niantic to issue updates regularly changing the codezzz

**Comment by trickpattyFH20** [comment]
same, only happens when I'm near a certain pokestop though... if I change the gps coords it doesn't crash. seems like maybe something to do with being near a lured pokestop?

**Comment by Aaronucci** [comment]
Of course but the odds of it happening today and no app updates.






[http://i59.tinypic.com/oazofq.png]<http://tinypic.com?ref=oazofq>


Aaron Bianucci
aaron@bianucci.us<mailto:aaron@bianucci.us>
@AaronBianucci<http://www.twitter.com/AaronBianucci>
http://www.aaronbianucci.com


On Sun, Aug 7, 2016 at 6:34 PM -0500, "thebringerofdeath789" <notifications@github.com<mailto:notifications@github.com>> wrote:


Well you can all expect niantic to issue updates regularly changing the codezzz

-

**Comment by BobbyWibowo** [comment]
I'm also occasionally getting `Exception while downloading map: list index out of range` in PokemonGo-Map (it still works, but it happens like once every 10 seconds or so).

**Comment by sherbert250** [comment]
Also, if I do get the bot to run, it stays in the `FollowSpiral` phase walking endlessly. It moves from coordinate to coordinate without printing out names of any kind.

**Comment by Baconnaise** [comment]
My one PTC account is running still on latest dev commit but I removed movetofort and spintofort as I had full item inventory. Wish it was as easy as changing poke/all/farm but the task system is superior IMO. The other PTC account is setup the same with full inventory yet resulted in same error. The google accounts all have spintofort and movetofort and error out immediately upon login. Figured I would mention it.

**Comment by BobbyWibowo** [comment]
I simply changed my starting location and removed stored last location from `data` folder and it started without issue.

**Comment by Baconnaise** [comment]
@sherbert250 Mine walks around and still catches pokes. PTC account with movetofort and spintofort removed.
![workingsortof](https://cloud.githubusercontent.com/assets/20616256/17466154/0de6e122-5cd7-11e6-9cc8-c50833c9e3d0.JPG)

**Comment by xinbei123** [comment]
Have the same issue, but it only crashed with a lured pokestop.

**Comment by GitPupper** [comment]
@sherbert250 
![screen shot 2016-08-07 at 4 16 19 pm](https://cloud.githubusercontent.com/assets/14209843/17466169/2c7e8e3a-5ccf-11e6-8d70-8a817536d89b.png)

**Comment by mrgohamilton** [comment]
followed @Baconnaise instructions above and back up and running

**Comment by BobbyWibowo** [comment]
@GitPupper How will it "walk" without that though?

**Comment by Baconnaise** [comment]
@BobbyWibowo You would have to change the config files and set a path most likely. I haven't tried that and don't know if it even works.

**Comment by bigkraig** [comment]
heres a stack trace, i don't have time to dig into it right now
```
2016-08-07 23:48:02,459 [       cli] [INFO] Highest CP Pokemon: 
2016-08-07 23:48:02,459 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 76, in main
    bot.start()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 75, in start
    self._setup_api()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 647, in _setup_api
    self.update_web_location()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 463, in update_web_location
    gym_longitude=fort.get('longitude')
  File "/usr/src/app/src/pgoapi/pgoapi/pgoapi.py", line 122, in function
    return request.call()
  File "/usr/src/app/pokemongo_bot/api_wrapper.py", line 106, in call
    result = self._call()
  File "/usr/src/app/pokemongo_bot/api_wrapper.py", line 63, in _call
    return PGoApiRequest.call(self)
  File "/usr/src/app/src/pgoapi/pgoapi/pgoapi.py", line 220, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "/usr/src/app/src/pgoapi/pgoapi/rpc_api.py", line 129, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/usr/src/app/src/pgoapi/pgoapi/rpc_api.py", line 359, in _parse_main_response
    response_proto_dict = self._parse_sub_responses(response_proto, subrequests, response_proto_dict)
  File "/usr/src/app/src/pgoapi/pgoapi/rpc_api.py", line 376, in _parse_sub_responses
    request_entry = subrequests_list[i]
IndexError: list index out of range
Traceback (most recent call last):
  File "pokecli.py", line 503, in <module>
    main()
  File "pokecli.py", line 134, in main
    raise e
IndexError: list index out of range
```

**Comment by BobbyWibowo** [comment]
@Baconnaise I removed:
```
"config": {
  "lure_attraction": true,
  "lure_max_distance": 2000
}
```
from `MoveToFort` and it works without issue so far. Yes, I still have `SpinFort`, `MoveToFort` and `FollowSpiral`. Just none of those 3 have any extra `config`.

**Comment by Vvkmnn** [comment]
Seems softban related. Many users have reported the bot suddenly working again after a certain amount of time.

Tried @BobbyWibowo's fix. Didn't work for me.

**Comment by TCB13** [comment]
I was running into the same issue some minutes ago, now it's working. The sever status was "unstable" according to http://cmmcd.com/PokemonGo/ I guess it was related to that...

**Comment by BobbyWibowo** [comment]
@Vvkmnn That's possible but kinda unlikely on my case. I started having that issue after being disconnected from the game for roughly 15 minutes because I was pulling latest dev and manually merging my small edits.

**Comment by BobbyWibowo** [comment]
@TCB13 Except the server is unstable a lot of the times, lol. Maybe possible though, considering I suddenly got the issue with multiple accounts.

**Comment by thebringerofdeath789** [comment]
I think it might be softban related. i had the issue, after 10 minutes it resolved itself. I let the bot run a little bit and moved it from SF to LA, now i get the error again and softban warnings. Meanwhile, the second account has never stopped once.

**Comment by TCB13** [comment]
@BobbyWibowo exactly, all at the same time. After my comment it crashed again and after a few minutes it was working again. I guess the bot should catch the exception and try later (like it does with others).
@thebringerofdeath789 Like @BobbyWibowo I didn't move.

**Comment by MrCarlosJr** [comment]
Its server, try again and works. Same commit

**Comment by iphonitest** [comment]
Still don't work :(

**Comment by thebringerofdeath789** [comment]
works again now...

**Comment by HecticSeptic** [comment]
I have one which reliably stops either on login or a few seconds in, another which has only failed once, one which failed a few times including on login, and 2 which haven't been affected yet. They are all in the same general area. Possible that it is a lured pokestop making them fail - coupled with whatever else is going on.

**Comment by BobbyWibowo** [comment]
@thebringerofdeath789 If you were only getting softban 'warnings' in which case can be handled by the bot as long as you have `HandleSoftBan` task and the current method was still working, it shouldn't have been related with our issue. I mean, it's perfectly normal to be softbanned after moving city. But my bot wasn't doing anything suspicious for 15 minutes (I was disconnected, seriously), and I suddenly got that issue.

To be honest, I'd like to think that it was server issue now.

**Comment by TCB13** [comment]
@heihachi I've lured pokestops here... Not causing issues right now.

**Comment by thebringerofdeath789** [comment]
yeah, i think it is a server issue

**Comment by Vvkmnn** [comment]
@BobbyWibowo Peculiar. Maybe there's more to it then.

I have another bot below it on a different account using literally the *same* code, and it's running perfectly fine. The one right above it whines about server throttling, then eventually breaks on another `raise e`. 

I'm going to give it a few minutes and then post results it later; given the span of users responses between broken and fixed, it **seems to resolve itself in 30 minutes somehow**.

**Comment by Baconnaise** [comment]
Seems like a server issue as all my bots are running now. Such is life.

**Comment by willyb321** [comment]
Mine crashes after about a minute or two, probably the server.

**Comment by BobbyWibowo** [comment]
Considering that I also got similar error with PokemonGo-Map as I stated here: https://github.com/PokemonGoF/PokemonGo-Bot/issues/2951#issuecomment-238116177. It's actually very likely a server issue (now that I think about it, lmao).

**Comment by tomalbrc** [comment]
mine is still running fine (using 12 hour old commit tho)

**Comment by nujabse** [comment]
Started running again, no more "raise e" errors, placed bot in Japan. Maybe it was just the server that went wrong.

**Comment by HecticSeptic** [comment]
It's still failing here, Specifically on one of the bots, despite being very similar to the rest. Catching and spinning works, but barely gets 2min before the list index out of range

**Comment by pbkwee** [comment]
print "req ", i, len(subrequests_list), subrequests_list[i] reports 
req  1 1 req  0 2 4
req  1 2 2

**Comment by Baconnaise** [comment]
@HecticSeptic I have one that does the same thing but once I deleted the last location data and cell data it would error out maybe once more then pick up again. YMMV

**Comment by HecticSeptic** [comment]
@Baconnaise that may have done the trick thanks, I feel a little better leaving it over night now.

**Comment by willyb321** [comment]
@HecticSeptic you could always just run ./run.sh && ./run.sh a few times and if one fails, the next will go.

**Comment by Vvkmnn** [comment]
Mine started working again. Been 20 minutes since I last got that error.

Whatever it is, it's time related.

**Comment by Calcyfer** [comment]
Solved for me by removing the cell and last location files in ./data as @Baconnaise suggested.

**Comment by iphonitest** [comment]
work for me now

**Comment by HecticSeptic** [comment]
@willyb321 more concerned about how suspicious it looks restarting immediately, instead having a nice random delay in-between, which I did with an extra py file. The error is still gone, so it seems the @Baconnaise workaround is the way to go

**Comment by Vvkmnn** [comment]
I imagine it has something to do with not being able to raise a new softban exception related to the updated API. When the bot looks for an error related to the softban, it can't find any in the list, and breaks.

Pure speculation though; I'm no dev. @bigkraig's stack trace probably has the real answer.

**Comment by willyb321** [comment]
@HecticSeptic ehh, I suppose you've got a point, was just suggesting lol.

**Comment by skywalker878** [comment]
I deleted cell and location files under data folder. 
It works now

**Comment by z4ppy** [comment]
Works for me too

**Comment by bigkraig** [comment]
stack trace looks like api response is missing something, so potentially some kind of issue with the server but we don't handle the problem well

**Comment by firzzen** [comment]
For me the suggestions by @Baconnaise and @BobbyWibowo do not help. Still the exact same issue.

For the people who got it fixed, did you download the latest dev branch? Mine is from Sunday. Have there been any merges/commits that fix this issue afterwards?

**Comment by gcaaa31928** [comment]
@firzzen dont worry. its fine now

that just api or server issues i think

**Comment by thebringerofdeath789** [comment]
This has to do with an error on the output of a catch, for google maps api
key quota
