### ISSUE TITLE
I've seen this problem a few times but with no real Solutions that have helped me 

### ISSUE THREAD

**Issue by EricFelbs** [PokemonGoF/PokemonGo-Bot#2955]
### Expected Behavior
bot to run

### Actual Behavior

(PokemonGo-Bot) Erics-MBP:PokemonGo-Bot ericfelber$ docker run --name=pokego-bot1 --rm -it -v $(pwd)/configs/config-account1.json:/usr/src/app/configs/config.json pokemongo-bot
2016-08-07 23:27:10,256 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-07 23:27:10,260 [       cli] [INFO] Error: No /configs/config.json or specified config
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-ws WEBSOCKET.SERVER_URL]
                  [-wss WEBSOCKET.START_EMBEDDED_SERVER]
                  [-wsr WEBSOCKET.REMOTE_CONTROL] [-p PASSWORD] [-l LOCATION]
                  [-lc LOCATION_CACHE] [--forts.spin FORTS.SPIN] [-w WALK]
                  [-k GMAPKEY] [-e SHOW_EVENTS] [-d DEBUG] [-t TEST]
                  [-du DISTANCE_UNIT] [-ec EVOLVE_CAPTURED]
                  [-rt RECONNECTING_TIMEOUT] [-hr HEALTH_RECORD]
                  [-ac FORTS.AVOID_CIRCLES] [-mcs FORTS.MAX_CIRCLE_SIZE]
                  [--catch_randomize_reticle_factor CATCH_RANDOMIZE_RETICLE_FACTOR]
                  [--catch_randomize_spin_factor CATCH_RANDOMIZE_SPIN_FACTOR]
                  [--map_object_cache_time MAP_OBJECT_CACHE_TIME]
pokecli.py: error: argument -a/--auth_service is required
(PokemonGo-Bot) Erics-MBP:PokemonGo-Bot ericfelber$ 

(my configs file is named config.json and is in the config folder, I have entered all the presets, and I have also validated it with http://jsonlint.com/    I'm on a mac everyone else I saw with this same problem was also on a mac maybe there is a file directory problem i don't know, and I apologize if this is the wrong place for this issue I'm not really sure where to get help please let me know if theres a better place to post this question)

### Other Information
OS: OS X El Captian
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by BobbyWibowo** [comment]
> (PokemonGo-Bot) Erics-MBP:PokemonGo-Bot ericfelber$ docker run --name=pokego-bot1 --rm -it -v $(pwd)/configs/config-account1.json:/usr/src/app/configs/config.json pokemongo-bot

I don't know what this command do, but are you sure that it'll set the custom config through --config parameter? On Windows, I specify custom config this way:
`python pokecli.py --config ./configs/config-1.json`

**Comment by SamBonedJody** [comment]
Hi Eric,

I had the same issue..

Navigate to your PokemonGo-Bot/configs/ folder and rename your preferred config file to the name used in your docker command

(I.E. If using the following command:

`docker run --name=pokego-bot1 --rm -it -v $(pwd)/configs/config-account1.json:/usr/src/app/configs/config.json pokemongo-bot`

Then rename your config file to config-account1.json

Docker may have created a folder with that name, If so delete it and rename the config file.

Happy Botting,
SBJ

**Comment by EricFelbs** [comment]
thank you so much Sam it works now

they should add that command to the wiki
