### ISSUE TITLE
IndexError: list index out of range | Error

### ISSUE THREAD

**Issue by GitPupper** [PokemonGoF/PokemonGo-Bot#2959]
### Error
IndexError
***
### Info
Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 132, in main
    raise e
IndexError: list index out of range
***
### Other Information
OS: Mac OSX El Capitan
Git Commit: fc4e802dd760508e45c9e2f79cdc9704a514b896
Python Version: Python 2.7.12

**Comment by BobbyWibowo** [comment]
#2951 duplicate

**Comment by Calcyfer** [comment]
Same here, full trace : 

`Traceback (most recent call last):`
`  File "pokecli.py", line 502, in <module>`
`    main()`
`  File "pokecli.py", line 133, in main`
`    raise e`
`IndexError: list index out of range`

After moving to a lured fort.

**Comment by GitPupper** [comment]
Duplicate. Sorry.
