### ISSUE TITLE
 Download error on https://pypi.python.org/simple/nosexcover/: [Errno 104] Connection reset by peer -- Some packages may not be found!

### ISSUE THREAD

**Issue by jcoinas** [PokemonGoF/PokemonGo-Bot#2960]
### Steps to Reproduce
running pip install -r requirements.txt on raspbian

Using cached protobuf-to-dict-0.1.0.tar.gz
  Downloading from URL https://pypi.python.org/packages/58/67/5f5702d8f593ec0697a1ae53d18be71f7727155f5b221c94fcecf2bf3e6d/protobuf-to-dict-0.1.0.tar.gz#md5=ae9fc7871b584475badc9ca6c70ab3d0 (from https://pypi.python.org/simple/protobuf-to-dict/)
  Running setup.py (path:/tmp/pip-build-9KsGwA/protobuf-to-dict/setup.py) egg_info for package protobuf-to-dict
    Running command python setup.py egg_info
    Download error on https://pypi.python.org/simple/nosexcover/: [Errno 104] Connection reset by peer -- Some packages may not be found!
    Couldn't find index page for 'nosexcover' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno 104] Connection reset by peer -- Some packages may not be found!
    No local packages or download links found for nosexcover
    Traceback (most recent call last):

**Comment by WillM88** [comment]
Is this a fresh install or update from previous release?

**Comment by jcoinas** [comment]
fresh install. i can run it on windows, I assume is a raspbian problem

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this has been resolved.
