### ISSUE TITLE
[help wanted] multiple bots

### ISSUE THREAD

**Issue by mjmadsen** [PokemonGoF/PokemonGo-Bot#2961]
I was curious if folks would be willing to offer advice on the best way to run multiple bots. I assume it wouldn't be the best to run multiple bots through the same IP.

**Comment by GitPupper** [comment]
It's on the wiki.

**Comment by mjmadsen** [comment]
@GitPupper Can you post a link? I've read all wiki pages multiple times.

**Comment by GitPupper** [comment]
Oh. Well in that case use a VPN.

**Comment by mjmadsen** [comment]
Can I ask how many you run per IP?

**Comment by GitPupper** [comment]
Most likely one. They'll trace multiple pokemon bots to the same IP and ban you.

**Comment by mjmadsen** [comment]
I am asking those who have run more than one for input. They, more than likely, will allow more than one per IP for tethered devices, those connected to WIFI, etc.

**Comment by middleagedman** [comment]
Here's one of the docker containers I use for vpns
https://github.com/binhex/arch-delugevpn

**Comment by SamBonedJody** [comment]
@middleagedman Great! Thank you for this! Just to clarify, I could use this docker to route my bot traffic through VPN?

Maybe an alternative is to force IPV6 since it's suspected that they have started IP Limiting? - #3233

**Comment by xSomeFoolx** [comment]
@mjmadsen I'm running 4 bots now and have been with no issue.

@GitPupper It would be hard for Niantic to enfroce a ban with multiple connections from one IP. That coffee shop down the road with 5 people playing on their wifi would be a target for banning in that case.

**Comment by RedViper9** [comment]
This topic should be discussed on the slack forum.
