### ISSUE TITLE
'status_code': 2,     'unknown6': [{   'response_type': 6, 'unknown2': {   'unknown1': 1L}}]}

### ISSUE THREAD

**Issue by veil98** [PokemonGoF/PokemonGo-Bot#2962]
I am on Mac OS.  I downloaded an encrypt.so file online which solved the "OSError: dlopen(encrypt.so, 6): image not found" problem.  I then ran "python pokecli.py -a ptc -u blah -p blah -l “blah”" and got the error message: 

'status_code': 2,
    'unknown6': [{   'response_type': 6, 'unknown2': {   'unknown1': 1L}}]}

Any idea what needs to be done now?

**Comment by BobbyWibowo** [comment]
I'm not familiar with that error. Did you get your encrypt.so from [here](https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/pogom)? If not, try the one from there. Make sure you download the right file (if you're on Mac, get libencrypt-osx-64.so) and name it as encrypt.so.

**Comment by veil98** [comment]
@BobbyWibowo , thank you for the response.  That actually isn't the encrypt.so file I downloaded. However, it still didn't work.  I downloaded the one you linked, put it in the base directory, renamed to encrypt.dll (anything else generates the response "OSError: dlopen(encrypt.dll, 6): image not found"), and then ran the script.  It ran for a little bit, but once again terminated with: 

'status_code': 2,
'unknown6': [{ 'response_type': 6, 'unknown2': { 'unknown1': 1L}}]}

I really don't know what to do.

**Comment by BobbyWibowo** [comment]
> I really don't know what to do. I thought that this 'unknown6' value error was the reason why the new API was made in the first place.

Which was why I mentioned that I wasn't familiar with that error, since it was supposed to be fixed and I haven't seen anything like that for many hours after I got my bot working. I can only suggest running `pip2 install -r requirements.txt --upgrade` for now. That'll upgrade the requirements file and hopefully upgrade pgoapi as well.

**Comment by veil98** [comment]
@BobbyWibowo Well the `pip2 install -r requirements.txt --upgrade`worked, but after that I ran `python pokecli.py -a ptc -u blah -p blah -l “blah” and it spit back the same error code:

'status_code': 2,
    'unknown6': [{   'response_type': 6, 'unknown2': {   'unknown1': 1L}}]}

Thank you for the help though!

**Comment by GitPupper** [comment]
@veil98 Rename it from `encrypt.dll` to `encrypt64.dll`

**Comment by veil98** [comment]
@GitPupper That gives me the error message `OSError: dlopen(encrypt.dll, 6): image not found`
It seems that for me, the script will not run unless the file is strictly named `encrypt.dll`

**Comment by BobbyWibowo** [comment]
Sorry, I'm pretty much lost for now. You'll have to wait for someone who has more knowledge in this.

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this has been resolved.

**Comment by veil98** [comment]
@RedViper9 do you mean updates on the API?
