### ISSUE TITLE
Unable to handle softban

### ISSUE THREAD

**Issue by PigeonNerd** [PokemonGoF/PokemonGo-Bot#2965]
Although we have closed the issue that "bot crashes".
But it looks like the bot cannot handle softban after the new API update. Whenever it tries to unban itself, it crashes.

**Comment by helloitu** [comment]
same problem here

**Comment by mouendless** [comment]
same issue here

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this has been resolved.
