### ISSUE TITLE
Error at start / Impossible to run the bot / MAC IOS

### ISSUE THREAD

**Issue by blackchass** [PokemonGoF/PokemonGo-Bot#2966]
I only kept the config.json file, deleted all the others in the /config folder.

When trying to start the bot, i get this error, do you have any idea how to fix this?

Many thanks in advance !!

**2016-08-08 02:55:56,578 [PokemonGoBot] [ERROR] encrypt.so is not found! Please place it in the bots root directory.
2016-08-08 02:55:56,578 [PokemonGoBot] [INFO] Platform: darwin Bot root directory: /Users/louischassagne/Desktop/PokeBot/PokemonGo-Bot**

**Comment by GitPupper** [comment]
# Wget Installation
***
`brew install wget`
***
`wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make && mv libencrypt.so ../../encrypt.so`
***
# Post Installation
***
Move `encrypt.so` to `PokemnGo-Bot/`

**Comment by moonlight2521** [comment]
can you give me step by step?

**Comment by DiegoRBaquero** [comment]
Download https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/pogom/libencrypt-osx-64.so and rename to encrypt.so ;)

**Comment by Evanito** [comment]
@DiegoRBaquero Dead link, is there anyway for me to get this file on Windows?

**Comment by 3ryanob3** [comment]
@blackchass im still having this issue how did you fix?

**Comment by 3ryanob3** [comment]
@blackchass im still having this issue can you please help?

**Comment by RedViper9** [comment]
Please ask for help in running the bot on our slack discussion board.
