### ISSUE TITLE
Making the bot colored again.

### ISSUE THREAD

**Issue by SamehAmnoun** [PokemonGoF/PokemonGo-Bot#2968]
Guys can you make the bot colored again. It helped a lot.

**Comment by GitPupper** [comment]
Pull Request #2604.
They did it, now they just have to make the commit to the project. Once the commit is made just follow the steps in the installation wiki to update.

**Comment by SingularityIO** [comment]
Upload the folder inside the zip to: PokemonGo-Bot\pokemongo_bot and let it replace and start bot, minor coloring back for now.

https://puu.sh/qtlX7/570de9c1a3.zip
