### ISSUE TITLE
"websocket_server": true 

### ISSUE THREAD

**Issue by FriskyScooter** [PokemonGoF/PokemonGo-Bot#2970]
I wanna run the web ui, I turned the "websocket_server": true in the, config file. and tried -m SimpleHTTPServer 8000 in the web folder dir nothing going on, bot working fine, anyhelp would be good thx

![1233](https://cloud.githubusercontent.com/assets/12982391/17467240/66b2bd8e-5d5f-11e6-8076-b41cebecfa22.JPG)

**Comment by MrCarlosJr** [comment]
add in path var dir of python

**Comment by FriskyScooter** [comment]
"C:\Python27" -m SimpleHTTPServer 80 didn't work

**Comment by uzzle1987** [comment]
c:\python27\python.exe -m "SimpleHTTPServer"
