### ISSUE TITLE
Cant start bot

### ISSUE THREAD

**Issue by icecubeice** [PokemonGoF/PokemonGo-Bot#2971]
$ python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequ
need help with this

### Other Information
OS: windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by zchen1018** [comment]
Same problem here.

Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: cannot import name ServerSideRequestThrottlingException

OS: Mac OS 10.10.5
Python Version: Python 2.7.10

**Comment by philly223** [comment]
Same here

Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 131, in main
    report_summary(bot)
  File "pokecli.py", line 140, in report_summary
    metrics.capture_stats()
 /pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  /pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  /pokemongo_bot/api_wrapper.py", line 58, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

Mac OS 10.11
Python 2.7.12

**Comment by Kyouga** [comment]
I solved this problem by running

pip2 install -r requirements.txt

as per https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation
