### ISSUE TITLE
Configuration [Question]

### ISSUE THREAD

**Issue by kriswong** [PokemonGoF/PokemonGo-Bot#2973]
Is there a way to set the bot to only spin pokestops? I just want to use this to farm pokeball and not pokemon. If there is a way to do that in the JSON file could you help me determine how to do it?  Thanks

**Comment by crvfts** [comment]
remove from config.json

`{
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },`

**Comment by ThunderVamp9** [comment]
You have to remove those, or could you change:

`    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},`

to 

`    "catch": {
      "// any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},`

?
