### ISSUE TITLE
AttributeError: 'module' object has no attribute 'HTTPSHandler'

### ISSUE THREAD

**Issue by hklcf** [PokemonGoF/PokemonGo-Bot#2978]
![image](https://cloud.githubusercontent.com/assets/410302/17468114/41056af8-5d57-11e6-8fce-ccad111ba146.png)

eeecbc6c48d292fc916e4830fba1df290adb6ec4

**Comment by jasonliu119** [comment]
saw the same issue

**Comment by RedViper9** [comment]
Looks like the connection was reset by the server.
