### ISSUE TITLE
Ignoring credentials supplied in config.json

### ISSUE THREAD

**Issue by zynjec** [PokemonGoF/PokemonGo-Bot#298]
### Expected Behavior
Not to be prompted for username/password when starting script, as they're supplied by config.json

### Actual Behavior
Prompted for username/password if it's not provided via command line arguments.

### Steps to Reproduce
Launch without username/password parameters.

### Other Information
OS: Ubuntu 14.04
Git Commit:  16f715d4561de0dc533b76c8d51bee8b3b8c5571

**Comment by ToxicSalt** [comment]
I think #259 fixes this

**Comment by Projectnsb** [comment]
I cant get no pokeballs or items ?! 
[#] Something rustles nearby!
[#] A Wild Pinsir appeared! [CP 836]
[x] Out of pokeballs...
[#] Something rustles nearby!
python ./pokecli.py -a google -u xxx -p xxxx-l "xxxx" -m all -c 100 -w 4

**Comment by zynjec** [comment]
@ToxicSalt Nope, it still ignores username/password even with that fix applied.

`$ python pokecli.py
Username:
Password:`

This problem starts as of d933c301b4a46a33627ad89a4108d8821f4d945f

**Comment by douglascamata** [comment]
@zynjec I think I'm going to revert d933c30... you think you can fix?

**Comment by rarshonsky** [comment]
I think the username/password prompts just need to be moved down. I'll fix it.

**Comment by douglascamata** [comment]
update from dev and check if my commit fixed, please.

**Comment by douglascamata** [comment]
I did mention the wrong issue, lol

**Comment by zynjec** [comment]
110dae2a5025d7bced92275d97775defaf5e0645 fixes the issue.

**Comment by douglascamata** [comment]
@zynjec thanks for the feedback!
