### ISSUE TITLE
can someone tell me how to install/use this :')

### ISSUE THREAD

**Issue by CurlzM8** [PokemonGoF/PokemonGo-Bot#2982]
### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by Elim160** [comment]
it clone -b dev https://github.com/PokemonGoF/PokemonGo-Bot 
cd PokemonGo-Bot 
virtualenv . 
source bin/activate 
pip install -r requirements.txt


put this into terminal if you have installed everything that is required.

**Comment by Elim160** [comment]
git* clone

**Comment by liudayu** [comment]
#2780
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation

**Comment by nivong** [comment]
this is not an issue, please delete your "issue" and use common sense and google.
