### ISSUE TITLE
how would i go about putting a exact location?

### ISSUE THREAD

**Issue by Elim160** [PokemonGoF/PokemonGo-Bot#2985]
just woundering how I would end up getting to an exact location like pier 39 in california.

OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by dockiem** [comment]
first you'd have to make sure that location is identified by google map. Then add the location parameter in your config file, like so:
`"location": "Central Park New York, NY",`

**Comment by davidson-git** [comment]
Exactly, or you can use latitude/longitude if it is not recognized.  I can pretty much promise I'm doing this the hard way, but I built a couple "nest maps" by using http://www.latlong.net/ and mapping individual points.

**Comment by Elim160** [comment]
@dockiem pier 39 is in San Francisco do i put "Pier 39 San Francisco, CA" ?

**Comment by dockiem** [comment]
yes it should work. I just tested the address in Google and it was found.
