### ISSUE TITLE
(AFTER successful login)apiwrapper.py, metrics.py,pgoapi.exceptions.NotLoggedInException

### ISSUE THREAD

**Issue by philly223** [PokemonGoF/PokemonGo-Bot#2988]
[PokemonGoBot] [INFO] [login_successful] Login successful.
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 131, in main
    report_summary(bot)
  File "pokecli.py", line 140, in report_summary
    metrics.capture_stats()
pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
pokemongo_bot/api_wrapper.py", line 58, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

OS: Mac 10.11
Python Version: 2.7.12

**Comment by Elholm** [comment]
bump, same problem

**Comment by madzul** [comment]
what's the cause of this problem?
I still got this problem from some of my machine (Linux and FreeBSD) with certain account (but the account is running fine on another machine —on another subnet.
Is it some kind of ban?
