### ISSUE TITLE
Bot can't start again

### ISSUE THREAD

**Issue by STNDBS** [PokemonGoF/PokemonGo-Bot#299]
![image](https://cloud.githubusercontent.com/assets/20604101/17072668/bb0f7038-5072-11e6-991d-7f9fe5b52cc2.png)

**Comment by zynjec** [comment]
Server issues, not a problem with bot.

**Comment by douglascamata** [comment]
PTC login is down.

**Comment by STNDBS** [comment]
Oh, thx
