### ISSUE TITLE
How to configure `max_steps`

### ISSUE THREAD

**Issue by jasonliu119** [PokemonGoF/PokemonGo-Bot#2995]
The original `max_steps` is not used any more:

https://github.com/PokemonGoF/PokemonGo-Bot/blob/5b3fe3d187b6b5fdfdede00f064bf7bcbd5a484d/pokecli.py#L416

How can I configure similar stuff like `max_steps` in current master?

Thanks

**Comment by Happyrain67** [comment]
you can make your GPX file (exemple here : http://callardin.free.fr/ )
I use it and it work ;)
Don't use "MoveToFort" and "FollowSpiral" but use "FollowLocation"
