### ISSUE TITLE
No Module named pgoapi.exceptions (Startup Issues

### ISSUE THREAD

**Issue by zviper13579** [PokemonGoF/PokemonGo-Bot#2999]
Need help starting. This is what I get.

$ python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

**Comment by jasonliu119** [comment]
did u run 'pip install -r requirements.txt' in the virtual environment?

**Comment by zviper13579** [comment]
I did, I also tried to re download, but got an error: pip install requirements.txt
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt

**Comment by jasonliu119** [comment]
distribution for what library?

**Comment by zviper13579** [comment]
After going back into virtual machine and redownloading pip i get the same error


Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

**Comment by jasonliu119** [comment]
After `virtualenv .` and `source bin/activate`, run `pip install -r requirements.txt`. please don't use `sudo` and remember to use `-r` in that command.

**Comment by lpy** [comment]
Di you use `--recursive` when you cloned the repository?

**Comment by Hok1988** [comment]
Have same error. To me help:
sudo apt-get install python-dev
After that:
pip install -r requirements.txt

**Comment by psycholyzern** [comment]
Please use python 2.7, ofcouse using virtualenv and requirements installed

**Comment by Ralliekj** [comment]
I'm having the same issue (Windows):

"Traceback (most recent call last):
File "C:\Users\Username\Documents\GitHub\PokemonGo-Bot\pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: cannot import name ServerSideRequestThrottlingException"

Didn't have any issues before. Uninstalled and retried 3 times, same error.

**Comment by Think-It** [comment]
Hi ! Same error here.
Launch command in good order (pretty sure). I tried in 3 servers (Debian 8) (in root and not root). Same error each time

There is a paste of my console ouput : http://pastebin.com/nQTg8yHF

I got an error after running pip command, see...

**Comment by psycholyzern** [comment]
Oh now I remember how I fixed that error yesterday. Clone dev branch instead of master. Using dev branch solved this issue on my side

**Comment by MrKaralis** [comment]
Other people and me had exactly  the same issue as reported here https://github.com/PokemonGoF/PokemonGo-Bot/issues/2882

**Comment by nivong** [comment]
did you use install.sh?

**Comment by lucas-sticky** [comment]
Tried with my ubuntu desktop at work. It works...

Dunno what is the issue with debian :(

**Comment by MrKaralis** [comment]
@nivong The bot worked flawlessly  for me before  the change Niantic  made last week,  yesterday I did a git pull to download  he changes that fixed the problem but the bot gave me that error.

**Comment by nivong** [comment]
TL:DR can you also anwser questions ?

**Comment by MrKaralis** [comment]
Not very experienced  so I only did  a git pull to "update" the formerly  working bot and didn't  know I had to run install.sh after that.

**Comment by nivong** [comment]
I give up

**Comment by MrKaralis** [comment]
Ok ty for your friendly efforts.

**Comment by PoubelleLaVie** [comment]
I have the same problem. I used instal.sh.
The files pgoapi are there but pokecli.py doesn't seems to find them.

Also, when i 
`-e git+https://github.com/keyphact/pgoapi.git@249d3be7fbbdabc7f9adea17cbc899d6549e47a2#egg=pgoapi`
(in requirements.txt)

there is the following error :
` Cloning https://github.com/keyphact/pgoapi.git (to 249d3be7fbbdabc7f9adea17cbc899d6549e47a2) to ./src/pgoapi
Could not find a tag or branch '249d3be7fbbdabc7f9adea17cbc899d6549e47a2', assuming commit.
`

**Comment by MrKaralis** [comment]
Ok i fixed it.  When doing `pip - r install requirements.txt` I've  found in the log that now I needed  to install vc for python 2.7  or else it wouldn't  find a needed  bat file.  After installing  it  from there 
https://www.microsoft.com/en-us/download/details.aspx?id=44266 you simply  need to  `pip - r install requirements.txt` again. Now I've to compile  the encrypt.dll (cross finger).

**Comment by locng** [comment]
In my case, try "sudo ./run.sh" and it works.

**Comment by spencerby28** [comment]
In this particular case, pip install -r requirements.txt will install all listed package versions to the exact specified version. Most of them work just fine as pip should behave, as they are managed packages of the pypi. The exception here is the pgoapi package, listed on line 3. It is not a pypi package. It is a github repository. Pip handle it badly. In occasions you have to remove the whole repository cloned by pip (rm -rf pgoapi) and do pip install again, i.e. pip install -r requirements.txt

This is a great opportunity to learn python!
