### ISSUE TITLE
No Pokemon

### ISSUE THREAD

**Issue by into** [PokemonGoF/PokemonGo-Bot#3]
It doesn't seem to be catching Pokemon, only spinning pokestops and getting EXP.

**Comment by into** [comment]
Actually, it does catch Pokemon but the inventory gets bugged and shows none. I have 9/250 but nothing is being shown in the inventory.

**Comment by into** [comment]
This is with ptc

**Comment by PokemonGoF** [comment]
hmm, could you please paste some log here?
The get_inventory only show delta items.

**Comment by into** [comment]
No no, I mean I would run the bot then go on the game via the app and it would show I have no Pokemon but the count was 9/250, so I do have Pokemon they're just not displaying? Only happened after running the bot, has happened on two accounts.

**Comment by into** [comment]
Just checked the journal and it only says it's receiving items from PokeStop.

No Pokemon catching.
![capture](https://cloud.githubusercontent.com/assets/14704204/17012685/61cf14f6-4ee7-11e6-9cd7-bc3831a9c4a5.PNG)

**Comment by PokemonGoF** [comment]
have you finished the tutorial ?  The pokemon caught before tutorial will not be listed there.
And you may want to restart the game to check the status.
Suggest  not to login them at the same time.

**Comment by harsh1412** [comment]
Its catching the pokemon. No shit :D you must finish the tutorial first.

**Comment by lcfoust** [comment]
I have the same problem. No pokemon being caught, just the pokestops being collected

**Comment by D3C1V3R** [comment]
same experience, logged in via google and it seems to only be spinning [http://i.imgur.com/OKP1FL1.png](url)

**Comment by MtDubious** [comment]
I'm having the opposite problem. Seems to be catching pokemon, but not spinning any pokestops even with the -s flag.

**Comment by crack00r** [comment]
WIll it drop the loest pokemon for a pokecoin/candy ore just release it?

**Comment by D3C1V3R** [comment]
@crack00r a feature listed is "Release low cp pokemon"
I'd assume it would keep higher cp pokemon and release the lower.

**Comment by crack00r** [comment]
@D3C1V3R  yes, i know, but when you send ot to doktor bla, you get a candy to upgrade the same pokemon, ore when he just delete it, you get nothing ;)

**Comment by MtDubious** [comment]
@crack00r there is no way to "just delete" pokemon.. they get transferred for candy yes.

**Comment by crack00r** [comment]
but it seams it send it do the doc
  "responses": {
    "RELEASE_POKEMON": {
      "result": 1,
      "candy_awarded": 1

**Comment by MtDubious** [comment]
Yes @crack00r pokemon with a cp of 100 or lower are transferred for candy.

**Comment by crack00r** [comment]
Ok, pokemons work, but no spinning, even with -s  ;)

**Comment by D3C1V3R** [comment]
Is there a possibility that there is a priority of pokestops over pokemon? Because I'm seeing a pattern of it repetitively spinning/checking pokestops and ignoring pokemon (If it is working)

**Comment by MtDubious** [comment]
Yea mine's doing the opposite. Catching tons of pokemon but isn't spinning stops at all as far as I can tell.

**Comment by D3C1V3R** [comment]
I'm assuming that previous versions were bugged and I highly reccommend getting the latest build (It fixed my isse) @MtDubious @into

**Comment by PokemonGoF** [comment]
yep...

**Comment by PokemonGoF** [comment]
close for now
