### ISSUE TITLE
No Pokémon in Party

### ISSUE THREAD

**Issue by alexanderrock** [PokemonGoF/PokemonGo-Bot#30]
I've run the bot a while and i used it with "-c 0" to get every pokemon in my party.
Or do i just have to leave "-c" off for catching
On the "Pokémon" tab in the game i see there are 9 bot nothing is displayed.

**Comment by harsh1412** [comment]
use -c 9 if you want every pokemon because 0 makes it -1 or something and bot bugs.

**Comment by CtrlAltDefeat94** [comment]
Same for me, says I've got 9/250 pokemon, but none are showing.

**Comment by eggins** [comment]
Check the readme - complete the tutorial first! :)

**Comment by alexanderrock** [comment]
Which tutorial do you refering to?

**Comment by alexanderrock** [comment]
may search too often, lets have a rest
need a rest
has pokemon
catchable_pokemon {'pokemon_id': 10, 'spawnpoint_id': u'479af86564d', 'longitude': 9.271662266288379, 'expiration_timestamp_ms': 1469112439348L, 'latitude': 47.69377995290147, 'encounter_id': 792954040159808765L}
A Wild Caterpie appeared! [CP14]
catchable_pokemon {'pokemon_id': 41, 'spawnpoint_id': u'479af8657c9', 'longitude': 9.27142308360026, 'expiration_timestamp_ms': -1L, 'latitude': 47.693644173340275, 'encounter_id': 1747984480465152861L}
A Wild Zubat appeared! [CP80]
catchable_pokemon {'pokemon_id': 13, 'spawnpoint_id': u'479af86577d', 'longitude': 9.271843143591932, 'expiration_timestamp_ms': 1469112521236L, 'latitude': 47.693144392024486, 'encounter_id': 3397565146074242301L}
A Wild Weedle appeared! [CP10]
wild_pokemons {'last_modified_timestamp_ms': 1469111858828L, 'spawnpoint_id': u'479af86564d', 'longitude': 9.271662266288379, 'pokemon_data': {'pokemon_id': 10}, 'latitude': 47.69377995290147, 'encounter_id': 792954040159808765L, 'time_till_hidden_ms': 580520}
wild_pokemons {'last_modified_timestamp_ms': 1469111858828L, 'spawnpoint_id': u'479af8657c9', 'longitude': 9.27142308360026, 'pokemon_data': {'pokemon_id': 41}, 'latitude': 47.693644173340275, 'encounter_id': 1747984480465152861L, 'time_till_hidden_ms': -233043597}
wild_pokemons {'last_modified_timestamp_ms': 1469111858828L, 'spawnpoint_id': u'479af86577d', 'longitude': 9.271843143591932, 'pokemon_data': {'pokemon_id': 13}, 'latitude': 47.693144392024486, 'encounter_id': 3397565146074242301L, 'time_till_hidden_ms': 662408}
