### ISSUE TITLE
It says we  can't find any pokestops in a range of 5000m!

### ISSUE THREAD

**Issue by sandor111** [PokemonGoF/PokemonGo-Bot#3001]
The error: 
we can't find any pokestops in a range of 5000m!
We can't find any pokestops, which are unused! probaly the server are unstable, or you visited them all. retrying....

**Comment by sandor111** [comment]
The error: 
we can't find any pokestops in a range of 5000m!
We can't find any pokestops, which are unused! probaly the server are unstable, or you visited them all. retrying....

**Comment by sandor111** [comment]
I keeps saying that

**Comment by SGColdSun** [comment]
What location, and post your config (without the account info obviously)

**Comment by Gandaflux** [comment]
probably ipsoftban. usually happens when you run 4+ bots from one ip

**Comment by lxlcampelxl** [comment]
u only have to take the .rar folder, and unrar de file again and that's it....

**Comment by farisyusry** [comment]
i still cant find pokestop even unrar the file. what should i do?

**Comment by sandor111** [comment]
Think with your brains

**Comment by bapoek** [comment]
I've been using the latest bot, but the problem is still the same.
like this capture :

![bot](https://cloud.githubusercontent.com/assets/20962751/17579029/aea96ec8-5fba-11e6-9827-572b8b78ec08.jpg)

Is there any latest updates..???

**Comment by oasist** [comment]
surely its ipsoftban, try with diferent connection, and you can play again..

**Comment by bapoek** [comment]
I already use a different connection, but moments later the problem occurs again.

this capture for different connection,

![screenshot_33](https://cloud.githubusercontent.com/assets/20962751/17591431/4c6574fc-6008-11e6-8e62-30ffde7f9064.jpg)

**Comment by bapoek** [comment]
This morning, i try with bot new update,
problem still the same.
![samebot](https://cloud.githubusercontent.com/assets/20962751/17611250/d6768de0-606f-11e6-9371-bfeb9efdcf6b.jpg)

Thank you very much

**Comment by oasist** [comment]
bapoek, i think uare from ina..
so this trick can you try.

1. close your bot, n try your account with your phone..
2. ussualy at the first try you cannot find/see any pokestop, close your pogo.. and try again..
u will see pokestop.close your pogo..
3. n now u try your bot again..
hope this work for you,
i dont know for any country..

**Comment by Slondermon** [comment]
would someone like to answer this? ekhm it has been 3 days... anyone? on proxy and same problem^
