### ISSUE TITLE
Priority in releasing logic

### ISSUE THREAD

**Issue by BartKoppelmans** [PokemonGoF/PokemonGo-Bot#3005]
### Expected Behavior
This release config:
```
"Growlithe": {
    "release_below_cp": 400, 
    "release_below_iv": 0.8, 
    "logic": "or", 
    "keep_best_iv": 3
}
```
should first release everything according to `'release_below_cp' or 'release_below_iv'`, and then keeping the 3 highest iv's of the remaining.

### Actual Behavior
The `keep_best_iv` has priority in the code, making the configuration order irrelevant.

### Steps to Reproduce
Use the above config.

### Other Information
OS: `Windows 10, 64bit`
Git Commit: eeecbc6c48d292fc916e4830fba1df290adb6ec4
Python Version: `Python 2.7.12`

### Suggestion
Perhaps we should try to have them act as small workers inside the transfer worker. Then it will allow customization on the priority, enabling users to combine their own logic out of the given pieces..

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by k4n30** [comment]
redundant with new release code
