### ISSUE TITLE
No example for Nidoran F or Nidoran M in config.json.pokemon.example file

### ISSUE THREAD

**Issue by HasanAliKaraca** [PokemonGoF/PokemonGo-Bot#3009]
### Expected Behavior

    "Nidoran F": {
      "release_below_cp": 420, // i dont know the default value, so i put a number for me
      "release_below_iv": 0.8,
      "logic": "and"
    },
    "Nidoran M": {
      "release_below_cp": 500, // i dont know the default value, so i put a number for me
      "release_below_iv": 0.8,
      "logic": "and"
    },

### Actual Behavior

no value

### Steps to Reproduce
Open "configs/config.json.pokemon.example" file and there is no example of this. Can someone add it?

**Comment by voldermort28** [comment]
Hi Hasan, you can add yourself, it works. For example, I add these line in my config:
"Nidoran M": { "release_below_cp": 300, "release_below_iv": 0.8, "logic": "and" },
"Nidoran F": { "release_below_cp": 300, "release_below_iv": 0.8, "logic": "and" },

**Comment by HasanAliKaraca** [comment]
I know it works, its why i posted. I just wanted someone to add it to the source

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this has been resolved.

**Comment by HasanAliKaraca** [comment]
Its not solved,  why did u close?
