### ISSUE TITLE
[Question] Use different ip

### ISSUE THREAD

**Issue by Gandaflux** [PokemonGoF/PokemonGo-Bot#3010]
Since i run bot on my dedic is there way to force bot to use different that default ip ?

I run bots without problems, but looks like niantic change limit per ip or smth since yesterday i got instantly ban when i run more than 4 bots.

I have few IPs on dedi, so will be nice to be able to use it.

**Comment by SGColdSun** [comment]
There is no built in way to choose which ip address you use at this time.
