### ISSUE TITLE
Can MoveToMapPokemon first check catch condition before teleport?

### ISSUE THREAD

**Issue by zetasq** [PokemonGoF/PokemonGo-Bot#3013]
I set the catch config like `"any": {"catch_above_cp": 200, "catch_above_iv": 0.5, "logic": "and"}`, but **MoveToMapPokemon** always first teleport then check if the pokemon needs to be catched. Can the bot check if the the pokemon meets the catch criteria before teleport? That would save a lot of time for the bot :)

**Comment by BobbyWibowo** [comment]
I kinda doubt you can get CP/IV information of catchable Pokemon. AFAIK you need to encounter the Pokemon for the remaining data to be delivered since AFAIK it'll be randomized on the fly by the server.

**Comment by zetasq** [comment]
@BobbyWibowo Sorry I didn't notice that the data was first randomized by the server
