### ISSUE TITLE
Error after login: encrypt.so is not found

### ISSUE THREAD

**Issue by eloivalles** [PokemonGoF/PokemonGo-Bot#3018]
After login successful and retriving my info I get this error:
[ERROR] encrypt.so is not found! Please place it in the bots root directory.

It happens in DEV and MASTER. I'm using MAC.

Any help please?

**Comment by HelloTroy** [comment]
figure it out?

**Comment by HelloTroy** [comment]
Same issue, if you figure it out lmk

**Comment by kinvaris** [comment]
You closed this without solution?
