### ISSUE TITLE
Transfer Function

### ISSUE THREAD

**Issue by willypho** [PokemonGoF/PokemonGo-Bot#302]
hi, i'm wondering if there's an option that lets you JUST transfer pokemon instead of catching&transferring. I have about 200+ pokemon that are low CP but the bot only transfers newly caught pokemon :(

**Comment by millejosh** [comment]
@willypho it should be pushed to the dev branch shortly

**Comment by douglascamata** [comment]
pushed to dev branch already, go check it out!
