### ISSUE TITLE
Inventory is full all the time...

### ISSUE THREAD

**Issue by takenek** [PokemonGoF/PokemonGo-Bot#3025]
Hello guys,
I got all the time Inventory is full and i don`t know what to do :/
Now i verry reduce limits and my config looks like:
          "item_filter": {
            "Pokeball":       { "keep" : 25 },
            "Potion":         { "keep" : 5 },
            "Super Potion":   { "keep" : 10 },
            "Hyper Potion":   { "keep" : 15 },
            "Revive":         { "keep" : 15 },
            "Razz Berry":     { "keep" : 25 }
          }
        }

When i run bot got:
2016-08-08 10:39:54,565 [PokemonGoBot] [INFO] Pokemon Bag: 57/250
2016-08-08 10:39:54,566 [PokemonGoBot] [INFO] Items: 273/350
2016-08-08 10:39:54,566 [PokemonGoBot] [INFO] Stardust: 33322 | Pokecoins: 0
2016-08-08 10:39:54,566 [PokemonGoBot] [INFO] PokeBalls: 25 | GreatBalls: 161 | UltraBalls: 0
2016-08-08 10:39:54,566 [PokemonGoBot] [INFO] RazzBerries: 25 | BlukBerries: 0 | NanabBerries: 0
2016-08-08 10:39:54,566 [PokemonGoBot] [INFO] LuckyEgg: 3 | Incubator: 3 | TroyDisk: 3
2016-08-08 10:39:54,566 [PokemonGoBot] [INFO] Potion: 5 | SuperPotion: 10 | HyperPotion: 15
2016-08-08 10:39:54,566 [PokemonGoBot] [INFO] Incense: 6 | IncenseSpicy: 0 | IncenseCool: 0
2016-08-08 10:39:54,566 [PokemonGoBot] [INFO] Revive: 15 | MaxRevive: 0

There is any option when inventory is full to start use GreatBalls or something like this?

Best Regards
TaKeN

**Comment by nivong** [comment]
add it to the config if you want. Al the items can be found here:
https://github.com/PokemonGoF/PokemonGo-Bot/blob/c5a7109fd82ea4644d4f8a598f5a83bab4361f63/data/items.json

**Comment by takenek** [comment]
So i need add:
"GreatBall": { "keep" : 100 },

What happened if i set:
"Pokeball": { "keep" : 0 },

He start use always GreatBalls ?

**Comment by agastimhatre** [comment]
this is mine, works for me.

"config": {
          "item_filter": {
            "Pokeball":       { "keep" : 30 },
	    "Greatball":      { "keep" : 100 },
	    "Ultraball":      { "keep" : 50 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }

**Comment by takenek** [comment]
The best will be if all will be in config.json... not add manually

**Comment by nivong** [comment]
The best will be if you make a bot of your own ;) it can't be easier than this....

**Comment by takenek** [comment]
No it`s not easier. Easier report a problem here to help everyone not doing own bot and happy because working for ME.
Looks like You don`t understand idea of github.

**Comment by nivong** [comment]
i dont understand the idea of github? Thanks that made my day! Next up for you: english class :+1:

**Comment by takenek** [comment]
Thank You for Your suggestion.
Best Regards.

**Comment by igor9silva** [comment]
Are you sure the message isn't `Your Pokémon Inventory is Full!`?

This means you can't carry more Pokémons, not items.
