### ISSUE TITLE
ImportError: No module named pgoapi.exceptions

### ISSUE THREAD

**Issue by sdhormess** [PokemonGoF/PokemonGo-Bot#3026]
.. everytime an new issue

**Comment by Tcheno** [comment]
Same here!

On  **pip install -r requirements.txt** from the latest master 
I get
**Cloning https://github.com/keyphact/pgoapi.git (to 249d3be7fbbdabc7f9adea17cbc899d6549e47a2) to ./src/pgoapi
  Could not find a tag or branch '249d3be7fbbdabc7f9adea17cbc899d6549e47a2', assuming commit.**

**Comment by nivong** [comment]
please close this and use search this has been asked noumerous times. Also use the freaking template that is profided when creating an issue....

**Comment by spencerby28** [comment]
In this particular case, pip install -r requirements.txt will install all listed package versions to the exact specified version. Most of them work just fine as pip should behave, as they are managed packages of the pypi. The exception here is the pgoapi package, listed on line 3. It is not a pypi package. It is a github repository. Pip handle it badly. In occasions you have to remove the whole repository cloned by pip (rm -rf pgoapi) and do pip install again, i.e. pip install -r requirements.txt

This is a great opportunity to learn python!
