### ISSUE TITLE
cannot run

### ISSUE THREAD

**Issue by mrwing1** [PokemonGoF/PokemonGo-Bot#303]
Traceback (most recent call last):
  File "pokecli.py", line 119, in <module>
    main()
  File "pokecli.py", line 107, in main
    bot.start()
  File "/Users/test/Downloads/PokemonGo-Bot-dev/pokemongo_bot/__init__.py", line 26, in start
    self._setup_api()
  File "/Users/test/Downloads/PokemonGo-Bot-dev/pokemongo_bot/__init__.py", line 93, in _setup_api
    inventory_dict = inventory_req['responses']['GET_INVENTORY']['inventory_delta']['inventory_items']
KeyError: 'GET_INVENTORY'

**Comment by mrwing1** [comment]
please help

**Comment by mrwing1** [comment]
now its Traceback (most recent call last):
  File "pokecli.py", line 120, in <module>
    main()
  File "pokecli.py", line 108, in main
    bot.start()
  File "/Users/test/Downloads/PokemonGo-Bot-dev 2/pokemongo_bot/__init__.py", line 26, in start
    self._setup_api()
  File "/Users/test/Downloads/PokemonGo-Bot-dev 2/pokemongo_bot/__init__.py", line 116, in _setup_api
    self.get_player_info()
  File "/Users/test/Downloads/PokemonGo-Bot-dev 2/pokemongo_bot/__init__.py", line 300, in get_player_info
    nextlvlxp = (int(playerdata['next_level_xp']) - int(playerdata['experience']))
KeyError: 'experience'

**Comment by douglascamata** [comment]
Not enough information to help us understand. Are you running latest `dev` version?

**Comment by mrwing1** [comment]
here full start 
[x] PokemonGO Bot v1.0
[x] Configuration initialized

[x] Address found: XXXXXXXX
[x] Position in-game set as: (XXXXXXXX)

Traceback (most recent call last):
  File "pokecli.py", line 120, in <module>
    main()
  File "pokecli.py", line 108, in main
    bot.start()
  File "/Users/test/Downloads/PokemonGo-Bot-dev 2/pokemongo_bot/__init__.py", line 26, in start
    self._setup_api()
  File "/Users/test/Downloads/PokemonGo-Bot-dev 2/pokemongo_bot/__init__.py", line 96, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'GET_PLAYER'

**Comment by mrwing1** [comment]
basicly it crashes few secs after start

**Comment by mrwing1** [comment]
please answer fast as i wanna sleep

**Comment by mrwing1** [comment]
hello?

**Comment by mrwing1** [comment]
help me pls

**Comment by mrwing1** [comment]
hellooß?

**Comment by carminaburana123** [comment]
I have the same errror as mrwing1 

> [x] PokemonGO Bot v1.0
> [x] Configuration initialized
> 
> [x] Address found: XXXXXXXX
> [x] Position in-game set as: (XXXXXXXX)
> 
> Traceback (most recent call last):
> File "pokecli.py", line 120, in 
> main()
> File "pokecli.py", line 108, in main
> bot.start()
> File "/Users/test/Downloads/PokemonGo-Bot-dev 2/pokemongo_bot/init.py", line 26, in start
> self.setup_api()
> File "/Users/test/Downloads/PokemonGo-Bot-dev 2/pokemongo_bot/__init_.py", line 96, in _setup_api
> player = response_dict['responses']['GET_PLAYER']['player_data']
> KeyError: 'GET_PLAYER'`

**Comment by tgeselle** [comment]
Same error. Servers are currently down.

**Comment by tgeselle** [comment]
Same error here.

**Comment by douglascamata** [comment]
Please, recreate your environment from scratch. Clone dev branch again and use virtualenv to avoid environment mess.

**Comment by carminaburana123** [comment]
Can anyone write a guide as if we never worked with a computer before. I tried everything but nothing seemed to work

**Comment by alatiera** [comment]
can confirm virtualenv solves the problem, i think bug report can be closed

**Comment by carminaburana123** [comment]
Still got some errors though (see previous post)
Maybe most of you are computer wizards I'm not though.  I'm only learning from mistakes i make

**Comment by s1x** [comment]
@carminaburana123 You are running with the master branch instead of the dev branch for the -m all flag.
Can you please double check that? Please feel free the open a new issue when necessary as this is now a different error as @mrwing1 is having.

@mrwing1 I assume your issue is resolved as there is no further correspondence.
