### ISSUE TITLE
ServerSideRequestThrottlingException?

### ISSUE THREAD

**Issue by SaipanDamashii** [PokemonGoF/PokemonGo-Bot#3030]
### Expected Behavior
Run the bot after typing python pokecli.py

### Actual Behavior

> Traceback (most recent call last):
>   File "pokecli.py", line 38, in <module>
>     from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
> ImportError: cannot import name ServerSideRequestThrottlingException
> 
> 

### Steps to Reproduce
type python pokecli.py, hit enter

### Other Information
OS: El Capitan
Git Commit: 5b3fe3d187b6b5fdfdede00f064bf7bcbd5a484d
Python Version: Python 2.7.10

**Comment by nivong** [comment]
fix this by running install.sh.... like mentoined alreadt 1000 times

**Comment by SaipanDamashii** [comment]
bash: install.sh: command not found
