### ISSUE TITLE
got away while using item pokeball

### ISSUE THREAD

**Issue by hazman87** [PokemonGoF/PokemonGo-Bot#3032]
![untitled](https://cloud.githubusercontent.com/assets/20870986/17475159/2fd420b4-5d8c-11e6-9300-02ec7bad8ba6.jpg)

**Comment by GitPupper** [comment]
You are soft banned from teleporting. Wait up to 3 hours before it will work again.

**Comment by hazman87** [comment]
i know what happen, great poke ball to much, so they cant take normal poke ball from pokestop.. now i throw around half great poke ball, then ok back..
