### ISSUE TITLE
[REQUEST][LOG] Misspelled "sender"

### ISSUE THREAD

**Issue by ChrisHaPunkt** [PokemonGoF/PokemonGo-Bot#3034]
Hi,

my log parser cannot parse log messages where the 'sender' (i guess) contains leading whitespaces.
So can someone clean the log messages from "SpinFort" to be printed right.

Thanks guys for ur awesome work.

### Expected Behavior

2016-08-08 11:27:58,372 [SpinFort]

### Actual Behavior
2016-08-08 11:27:59,021 [  SpinFort] 

### Steps to Reproduce

Look your lock files

### Other Information
OS: deb8
Git Commit: 563f898f61233ff86d38d83b68d8399c1f63051b
Python Version: 2.7

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this has been resolved.

**Comment by ChrisHaPunkt** [comment]
No, it is not fixed plz reopen this.

**Comment by mjmadsen** [comment]
Can we sum this up as configurable output per task?
