### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72

### ISSUE THREAD

**Issue by kinvaris** [PokemonGoF/PokemonGo-Bot#3038]
### Expected Behavior

The application to work

### Actual Behavior

During `pip install -r requirements.txt` on a fresh droplet.

```
Command /root/PokemonGo-Bot/bin/python -c "import setuptools, tokenize;__file__='/root/PokemonGo-Bot/build/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-adcl1x-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/PokemonGo-Bot/include/site/python2.7 failed with error code 1 in /root/PokemonGo-Bot/build/numpy
Traceback (most recent call last):
  File "/root/PokemonGo-Bot/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)
```

### Steps to Reproduce

`pip install -r requirements.txt` on dev branch

### Other Information
OS: `Linux jupiter 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
Git Commit: `5b3fe3d187b6b5fdfdede00f064bf7bcbd5a484d`
Python Version: `Python 2.7.6`

**Comment by Roenbaeck** [comment]
Can it be that a UTF-8 locale is not set? Try:
echo $LANG
It should be something like "en_US.UTF-8".

**Comment by cabralRodrigo** [comment]
Happening to me too, but on a VM on Windows 10.

OS: Linux Ubuntu 14.04.2 LST, Trusty Tahr
Git Commit: 8b5af8d766ac161be926932b05e3fc785a33661d
Python Version: Python 2.7.6
