### ISSUE TITLE
Start Gym Battle causes crash

### ISSUE THREAD

**Issue by xareyx** [PokemonGoF/PokemonGo-Bot#304]
api call to start_gym_battle causes response with just status_code=51 and that leads to crash
What does that code correspond to?

Call stack:
![image](https://cloud.githubusercontent.com/assets/14920015/17072965/30487fbe-5075-11e6-934e-7a5c15da7662.png)

**Comment by douglascamata** [comment]
Problem in `pgoapi` please report at https://github.com/tejado/pgoapi.

**Comment by xareyx** [comment]
lol, sorry, got lost in a shitton of repositories opened
