### ISSUE TITLE
Better inventory management

### ISSUE THREAD

**Issue by tiagoAnon** [PokemonGoF/PokemonGo-Bot#3040]
Hi,

I believe that a better approach to the bag management would be having a list of priority per item type instead of a list with the maximum number of each type of item.

For example, if we have the bag almost full and with 100 pokeballs, if we get 3 greatballs at a stop we should start throwing away pokeballs. Same thing for potions and revives.

My take is that we could have a config for how much percentage of the bag each item kind should take up (like 75% for balls, 15% for potions, 5% for revives, 5% for anything else), always keep the bag with 1 slot free to enable getting items from the pokestop and just let the bot manage which items are better to keep.

**Comment by cmezh** [comment]
Maybe it's better to make two recycle modes - by count (what is currently implemented - specifing count of each single item type) and by class (specifing count of items inside of class - Pokeballs (Pokeballs, Greatballs, Ultraballs, Masterballs), Potions, Revives etc.)
Percentage could be also useful feature is case of suggested alternative item storage mode.

**Comment by BriceSD** [comment]
@tiagoAnon Interesting. I like the idea of having the current recycling mode and this one. But I would rather do something like keep 150 items of class balls rather than keep 50% of inventory size for items of class balls. What do yo think ?
#2482

**Comment by k4n30** [comment]
Fixed in both dev & master
