### ISSUE TITLE
Wiki cleanup

### ISSUE THREAD

**Issue by gokaygurcan** [PokemonGoF/PokemonGo-Bot#3041]
Hello,

The current wiki is a bit inscrutable for newbies and/or non-technical people. I think it'd be nice to clean up the wiki pages and structure them a little. There're already some good examples that you can see here: https://github.com/showcases/projects-with-great-wikis

If noone is willing to do this, I can. But more important thing is the topics and content. 

I think these are "must have" topics:
- Home
- Installation
  - Windows
  - Macos
  - Linux
- Configs
  - Tasks
    - HandleSoftBan
    - CollectLevelUpReward
    - ...
  - Catch
    - ...
  - Release
    - ...
  - VIPs
    - ...
  - How to build a cluster
- Web UI
  - nginx
  - Apache
- ...
- ...
- Troubleshooting
  - FAQs
  - Open an issue
- Development

Please share your thoughts so that we can have a nice and clean wiki page for everyone. 

G.

**Comment by Kaijun** [comment]
+1 lot of configurations are missing so far

**Comment by cmezh** [comment]
Another suggestion is to make well-commenter config exmple

**Comment by gokaygurcan** [comment]
@cmezh 
Not related to the wiki but yes, that's also a problem.

There's this https://hjson.org/ project. It supports different types of comments (single line, multi line, etc.) and has Python implementation. Could be an option.

**Comment by gokaygurcan** [comment]
@RedViper9 ??

**Comment by RedViper9** [comment]
@gokaygurcan Sorry, it was the middle of the night. Didn't mean to shut you down silently.

Yes the readme and configs can use work. It's tough keeping up when there are new features introduced multiple times per day. Your input would be an enormous help, but please have this discussion with the rest of the community on the Slack discussion board and submit proposed changes as PR's.

A clean issues board lets the devs focus on problems in the code, so we're scrubbing everything not related to the bot's function.

**Comment by gokaygurcan** [comment]
@RedViper9 Thanks for the update. It still has some wrong urls, so I think I'll take a look at it as soon as possible.
