### ISSUE TITLE
Problems running multiple bots

### ISSUE THREAD

**Issue by AcorpBG** [PokemonGoF/PokemonGo-Bot#3044]
Seems like the api is not answering when running 10 instances of the bot.  It is either their api limiting req/s per ip
or just the new pokeapi/bot couldn't handle it.
I need info from other people if they have multuple bots running from the same ip/installation folder.

**Comment by JaroSound** [comment]
I think there is a ip limit when u run more than 3 bots.

**Comment by Philipp59** [comment]
iam running 9 without any throttling maybe 10 is the limit for your setup/api? this needs some investigation. maybe we have to create a new user running that instance or its the internet connection (read router)?

**Comment by JaroSound** [comment]
I cant run more than 3 :(

**Comment by takenek** [comment]
If will be option to select IP will be possible to run more than 3 - someone pull request: #3010

**Comment by AcorpBG** [comment]
With less than 3 bots I have no problem with 4 sometimes it hung one time for like 7 minutes.
Will experiment with map_object_cache 10 right now at 5.
