### ISSUE TITLE
km walk not works good

### ISSUE THREAD

**Issue by buzzo123** [PokemonGoF/PokemonGo-Bot#3048]
the map say i walk for 1 km but the eggs say only 400 m, why this?

**Comment by takenek** [comment]
Sounds like you move too fast that`s why.

**Comment by buzzo123** [comment]
i setting up walk to 10

**Comment by takenek** [comment]
You walk 10km/h ??
This is not walk...

**Comment by buzzo123** [comment]
ok but the max is 14 right?

**Comment by Outpox** [comment]
According to the comments, yes. Altough I've found setting it to a lower value (like 5 or 8) provides better results.

**Comment by buzzo123** [comment]
ok, i try, but more important i've this error : #3052

**Comment by cmezh** [comment]
My choice is 30 (!). Calculated manually walked distance and time and it looks like walking with speed around 6 km/h. I don't know why.

**Comment by buzzo123** [comment]
but if u write 30 its mean 30km/h!

**Comment by Outpox** [comment]
It's up to you if you want to try higher values.

**Comment by cmezh** [comment]
Checked it now:
Ran for 00:43
Travelled 1.58 km
Even with delays it looks like completely incorrect. It's with 30 km/h.

**Comment by pytrisss** [comment]
Yeah, but that should not be affected by that. At least before the api change it wasnt. There are a lot of issues open around this. I think it will be resolved soon.

**Comment by davidson-git** [comment]
I'm still having this issue.  3056 links to 3100 which is closed...

As pytrisss said, if this is related to the randomized wait counter it is performing differently than pre-api.  #General seems split on recommendations.  Some are reporting walk:30 == .33 km/hr actually= and other are reporting near walk == km/h.

**Comment by RedViper9** [comment]
@davidson-git Are you running the latest version of the bot?
