### ISSUE TITLE
bot error after 1 minute working

### ISSUE THREAD

**Issue by KrisMan555** [PokemonGoF/PokemonGo-Bot#3049]
Bot start crashing after 1 minute. 
error:Traceback (most recent call last):
  File "pokecli.py", line 499, in <module>
    main()
  File "pokecli.py", line 130, in main
    raise e
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 10: ordinal not in range(128)

### Other Information
OS: mac osx el capitan
Git Commit: (no idea how do it)
Python Version: Python 2.7.12

**Comment by takenek** [comment]
You got newlatest version from github? I think there was a patch for this....

**Comment by KrisMan555** [comment]
ok i updated it, error is solved but now bot only spinning poke stops and don't catching pokemons

**Comment by KrisMan555** [comment]
i am idiot my bag was full ok all working
