### ISSUE TITLE
Error initializing pokecli.py

### ISSUE THREAD

**Issue by Thedyolf** [PokemonGoF/PokemonGo-Bot#3050]
**Expected Behavior**
Starting pokecli.py

**Actual Behavior**
[Error Log](http://puu.sh/qtRCX/d08c136967.png)
(sorry for the format, not able to run most commands on my pc since my C drive is completely filled up with a lot of mess..)

**Steps to Reproduce**
Have been trying to get the bot to initialize for about 6 hours now, error after error, most of them I could fix using the issues section but even after finding some lookalike issues, their solution is not working for me. The error happens every time I run pokecli.py.

**Comment by takenek** [comment]
No config - check line number 3 - there is info why not working...

**Comment by cmezh** [comment]
It looks like you haven't set your config file correctly.
It tries to tell you that you haven't specifed location in your config.

**Comment by Thedyolf** [comment]
Thanks for the quick replies, was staring blind. The typo was found, thanks
