### ISSUE TITLE
Config for egg hatching

### ISSUE THREAD

**Issue by Xavendith** [PokemonGoF/PokemonGo-Bot#3051]
How do I set the config to move between forts but not spin the forts then move to the next one.
My aim is to just have the bot walk around to hatch the egg, but that happens is that when the bot arrives at the fort is stays there.

{
    "auth_service": "google",
    "username": "",
    "password": "",
    "location": "",
    "gmapkey": "",
    "tasks": [
        {
            "type": "IncubateEggs",
            "config": {
                "longer_eggs_first": true
            }
        },
        {
            "type": "RecycleItems"
        },
        {
            "type": "MoveToFort",
            "config": {
                "lure_attraction": true,
                "lure_max_distance": 2000
            }
        },
        {
            "type": "FollowSpiral",
            "config": {
                "diameter": 4,
                "step_size": 70
            }
        }
    ],
    "//tasks": [
        {
            "type": "HandleSoftBan"
        },
        {
            "type": "CollectLevelUpReward"
        },
        {
            "type": "IncubateEggs",
            "config": {
                "longer_eggs_first": true
            }
        },
        {
            "type": "TransferPokemon"
        },
        {
            "type": "EvolvePokemon",
            "config": {
                "evolve_all": "none",
                "first_evolve_by": "cp",
                "evolve_above_cp": 500,
                "evolve_above_iv": 0.8,
                "logic": "or",
                "evolve_speed": 20,
                "use_lucky_egg": false
            }
        },
        {
            "type": "RecycleItems",
            "config": {
                "item_filter": {
                    "Pokeball": {
                        "keep": 500
                    },
                    "Potion": {
                        "keep": 10
                    },
                    "Super Potion": {
                        "keep": 20
                    },
                    "Hyper Potion": {
                        "keep": 30
                    },
                    "Revive": {
                        "keep": 30
                    },
                    "Razz Berry": {
                        "keep": 100
                    }
                }
            }
        },
        {
            "type": "CatchVisiblePokemon"
        },
        {
            "type": "CatchLuredPokemon"
        },
        {
            "type": "SpinFort"
        },
        {
            "type": "MoveToFort",
            "config": {
                "lure_attraction": true,
                "lure_max_distance": 2000
            }
        },
        {
            "type": "FollowSpiral",
            "config": {
                "diameter": 4,
                "step_size": 70
            }
        }
    ],
    "map_object_cache_time": 5,
    "forts": {
        "avoid_circles": true,
        "max_circle_size": 10
    },
    "websocket_server": false,
    "walk": 4,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1,
    "catch_randomize_spin_factor": 1,
    "catch": {
        "any": {
            "catch_above_cp": 0,
            "catch_above_iv": 0,
            "logic": "or"
        },
        "// Example of always catching Rattata:": {},
        "Rattata": {
            "never_catch": true
        },
        "Pidgey": {
            "never_catch": true
        },
        "Spearow": {
            "never_catch": true
        },
        "Weedle": {
            "never_catch": true
        },
        "Zubat": {
            "never_catch": true
        },
        "Tangela": {
            "never_catch": true
        },
        "Raticate": {
            "never_catch": true
        },
        "Caterpie": {
            "never_catch": true
        },
        "Goldeen": {
            "never_catch": true
        },
        "Paras": {
            "never_catch": true
        }
    },
    "release": {
        "any": {
            "release_below_cp": 0,
            "release_below_iv": 0,
            "logic": "or"
        },
        "// Example of always releasing Rattata:": {},
        "// Rattata": {
            "always_release": true
        },
        "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
        "// Pidgey": {
            "keep_best_cp": 3
        },
        "// Example of keeping 2 stronger (based on IV) Zubat:": {},
        "// Zubat": {
            "keep_best_cp": 2,
            "keep_best_iv": 3
        },
        "// Also, it is working with any": {},
        "// any": {
            "keep_best_iv": 3
        },
        "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {}
    },
    "vips": {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {
            "catch_above_cp": 1200,
            "catch_above_iv": 0.9,
            "logic": "or"
        },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},
        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}

**Comment by jokoast** [comment]
The Wiki isn't up to date, max_steps' still in it for example (and nothing replaces it i think)

**Comment by k4n30** [comment]
@Xavendith - The bot and it's config has changed a bit in the last 4 days, are you still having this issue?
