### ISSUE TITLE
How to use pokemon trainer account ?

### ISSUE THREAD

**Issue by Motazlubbad** [PokemonGoF/PokemonGo-Bot#3053]
Hi all

can anyone tell me how yo use pokemon trainer account  to logon 

auth_service": "?????"

**Comment by cmezh** [comment]
ptc

**Comment by MikeDX** [comment]
Please use the WIKI for instal instructions or the SLACK for help. Github issues are not the place to post support requests.

**Comment by kesfaw** [comment]
plz close the issue
