### ISSUE TITLE
Run more then one user in the same computer

### ISSUE THREAD

**Issue by Carlito007** [PokemonGoF/PokemonGo-Bot#3054]
Hi,
i want to know what is the best way to run more then one bot in same computer.
its was worked before the update but now i think i getting soft ban becouse i logged from the same ip.
please write me what is the right way to run more then one bot from same computer.. 
thank you

**Comment by jannickv** [comment]
I'm running multiple users by creating multiple clones of this repo, each running in their own virtualenv

**Comment by iruy** [comment]
I just create one more `config-User2.json` file and use the same virtualenv in another console.
Once in virtualenv, I use command `./run.sh ./configs/config-User2.json`

**Comment by Carlito007** [comment]
i need to open new folder og PokemonGo-Bot for each user ?
i using virtualenv too but i dont understand how it work perfectly....

**Comment by chypriote** [comment]
You can just run in different terminals:
`python pokecli.py -u user1 -p pass1`
`python pokecli.py -u user2 -p pass2`

**Comment by Carlito007** [comment]
its working but when i run 7 users all are get softban i think or the bot stoping to work.. no catching pokes and move from pokestop to the other and i not get the loot.. it write that i need rest.
there way to use proxy server to login ?

**Comment by Carlito007** [comment]
#3022 like in this case.

**Comment by Dunduro** [comment]
ya getting same issue here

on side note method i use for running multiple sessions is through screen.
allows scripts to run even after the terminal or ssh connection is closed.
screen -ls to display al open screens
screen -S [SCREEN_RAME_HERE] to create a screen
screen -r [SCREEN_RAME_HERE] to reattach to a running screen.
exit while in screen to close the screen session
