### ISSUE TITLE
Can I choose what eggs to hatch?

### ISSUE THREAD

**Issue by bixuanzju** [PokemonGoF/PokemonGo-Bot#3058]
### Expected Behavior

I'd like the bot to choose 2km and 5km eggs to hatch, 10km is too precious, I'd like to save them until I reach higher levels.

### Actual Behavior

No such config exists.

**Comment by seratkurtulus** [comment]
That config actually exists. Please read the wiki!

set "longer_eggs_first" : false
{
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": false
        }
 }

**Comment by bixuanzju** [comment]
@seratkurtulus but that wouldn't guarantee that the bot won't hatch 10km eggs, does it?

**Comment by seratkurtulus** [comment]
Unless you have 9 "10km" eggs it won't hatch 10km eggs. In that case I assume you prefer hatching "10km" eggs. If you don't want to hatch any 10km eggs just remove the task at that point. But i think it doesn't make any sense.

**Comment by bixuanzju** [comment]
Fair enough, thanks!
