### ISSUE TITLE
Don't log TransferPokemon with keep_best_iv if rules don't match any

### ISSUE THREAD

**Issue by DiegoRBaquero** [PokemonGoF/PokemonGo-Bot#3064]
### Expected Behavior
Not logging about 3rd+ Pokemon based on IV because none should be released based on rules.

### Actual Behavior
Logging about releasing 3rd+ Pokemon when they don't match release rules:
````
[TransferPokemon] [INFO] [keep_best_release] Keeping best 2 Eevee, based on iv
[TransferPokemon] [INFO] [keep_best_release] Keeping best 2 Horsea, based on iv
````

This keeps showing up every 4 lines.

It does release others normally based on rules:
````
[TransferPokemon] [INFO] [keep_best_release] Keeping best 2 Eevee, based on iv
[TransferPokemon] [INFO] [keep_best_release] Keeping best 2 Pidgey, based on iv
[TransferPokemon] [INFO] [future_pokemon_release] Releasing Pidgey (CP 284/IV 0.38) based on rule: CP < 100 OR IV < 0.8
[TransferPokemon] [INFO] [pokemon_release] Exchanged Pidgey [CP 284] [IV 0.38] for candy.
````
### Steps to Reproduce
Having 3+ Pokemons that shouldn't be released and this config:
`"release": {"any": {"release_below_cp": 100, "release_below_iv": 0.8, "logic": "or", "keep_best_iv": 2} }`

### Other Information
OS: Mac OS
Git Commit: 5b3fe3d187b6b5fdfdede00f064bf7bcbd5a484d
Python Version: 2.7.12

**Comment by GitPupper** [comment]
Same problem. It's because the bot doesn't transfer pokemon for candy anymore. To fix this I just edited the config to keep best 0. It doesn't show it in the logs, but it still does't transfer pokemon.

**Comment by TheSavior** [comment]
Fixed in https://github.com/PokemonGoF/PokemonGo-Bot/pull/3223
