### ISSUE TITLE
[Feature request] config encrypt.so

### ISSUE THREAD

**Issue by JayJay1989** [PokemonGoF/PokemonGo-Bot#3066]
is there a possibility to add a config for emulating the bot as your own android/iOS device? 
the request of the bot are easy detectable cause everyone use the same fingerprint

**Comment by lelbo** [comment]
same 
[ERROR] encrypt.so is not found! Please place it in the bots root directory.
2016-08-08 16:05:20,917 [PokemonGoBot] [INFO] Platform: darwin Bot root directory: /Users/mica/BOT/PokemonGo-Bot

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by k4n30** [comment]
#3977
