### ISSUE TITLE
Help With Code Needed

### ISSUE THREAD

**Issue by JaydenHamence** [PokemonGoF/PokemonGo-Bot#3067]
need an example of a code to keep all Pidgey,Weedle,Caterpie instead of transferring all but best 4 like all the others?

**Comment by bixuanzju** [comment]
Not sure what kind of "best" (iv, cp?) you want, but here you go!

In the release config:
```
"any": { "keep_best_cp": 4, "keep_best_iv": 4 },
"Caterpie": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
"Pidgey": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
"Weedle": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"}
```

**Comment by balpoint** [comment]
Please read the [https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/README.md](url) before posting issues like this.

**Comment by JaydenHamence** [comment]
thanks but wont "any" release them all before it gets to 
"Caterpie": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
"Pidgey": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
"Weedle": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"}?

**Comment by seratkurtulus** [comment]
No, pokemon specific configurations override "any".

**Comment by JaydenHamence** [comment]
thanks!
