### ISSUE TITLE
Bot only walking and spin, not catching any poke balls. dev version

### ISSUE THREAD

**Issue by dwangfeng** [PokemonGoF/PokemonGo-Bot#3068]
### Expected Behaviour
should walk, spin and catch poke balls after starting bot.

### Actual Behaviour
bot can walk and spin pokestop, but cannot see any poke balls and catch them.

### Steps to Reproduce
start bot using python pokecli.py using dev version.

### Other Information
OS: Mac OS 10.11.6
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
bdcf2519d63555ac32246439fd17672896ee64e4
Python Version: (run 'python -V' and paste it here)
Python 2.7.12

Bot running summary log:
2016-08-08 09:34:14,160 [       cli] [INFO] 
2016-08-08 09:34:14,160 [       cli] [INFO] Ran for 0:03:14
2016-08-08 09:34:14,160 [       cli] [INFO] Total XP Earned: 300  Average: 5565.73/h
2016-08-08 09:34:14,160 [       cli] [INFO] Travelled 0.03km
2016-08-08 09:34:14,161 [       cli] [INFO] Visited 6 stops
2016-08-08 09:34:14,161 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-08 09:34:14,161 [       cli] [INFO] Threw 0 pokeballs
2016-08-08 09:34:14,161 [       cli] [INFO] Earned 0 Stardust
2016-08-08 09:34:14,161 [       cli] [INFO] 
2016-08-08 09:34:14,161 [       cli] [INFO] Highest CP Pokemon: 
2016-08-08 09:34:14,161 [       cli] [INFO] Most Perfect Pokemon:

**Comment by BriceSD** [comment]
@dwangfeng your pokemon inventory could be full.
Without your config we can't say much.

**Comment by dwangfeng** [comment]
Here is my config file, i double checked my item list and they are not full.

{
    "auth_service": "google",
    "username": "xxxxxxx@gmail.com",
    "password": "yyyyyyyy",
    "location": "43.898154, -79.401123",
    "gmapkey": "some key",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 30 },
            "Super Potion":   { "keep" : 30 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 20 },
            "Razz Berry":     { "keep" : 60 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 100, "catch_above_iv": 0.4, "logic": "and"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

**Comment by e0xify** [comment]
Same here. 

Last Pokemon catched 21 hours ago at bot startup on three accounts. 

The bot does not have catched any other Pokemon yet. 

Seems that it's just working one time when starting the bot

**Comment by BriceSD** [comment]
@dwangfeng POKEMON inventory, not ITEM inventory.
```
"release": {
"any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
```
You're releasing pokemon only if his CP or IV is below 0. In other word, you're not releasing any pokemon. You keep all of them.

Read the wiki please. You didn't even look at configuration parameters explanation ...
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files

**Comment by dwangfeng** [comment]
@BriceSD i cannot understand your comments, does the above parameter have anything to do with not catching any pokemons? 
by the way that is the default config for release config, what is the problem? can you tell me?

**Comment by djadstar** [comment]
Hey @dwangfeng  check out the config files wiki. You need to change the release CP and IV so the bot releases Pokemon. At the moment it's set to not release any by using 0. 

I realised mine was doing this so came to this section and found the answer, cheers @BriceSD

**Comment by dwangfeng** [comment]
@djadstar does your bot catch any pokemon after the change?
i have done the change, nothing has changed, bot still walking and spin. no pokemons show and none caught.

**Comment by djadstar** [comment]
Hey @dwangfeng once you added the code did your bot release a lot of pokemon?

If you look in the default config there are lots of lines that are commented out with //, if you remove the // on the line " // any": {"keep_best_iv": 3}, to make it "any": {"keep_best_iv": 3}, that will do what you need it to do. 

Hope that helps.

**Comment by dwangfeng** [comment]
@djadstar thanks, i figure it out, looks like a address issue, the place where i entered may not have any pokestops anymore, probably the reason, i changed the place, now it started working..
