### ISSUE TITLE
[suggestion] transferring all pokemon except the ones marked as favorites

### ISSUE THREAD

**Issue by kace91** [PokemonGoF/PokemonGo-Bot#307]
If you think about it, it makes sense as a tool for emptying your pokemon list. Just manually pick the ones that you like starring them in the actual app, and then let the bot transfer the rest. 

Options like transferring under x cp or leaving just one of each kind would always leave edge cases unnatended, while this caters to every possible problem!

**Comment by douglascamata** [comment]
All these features are coming.
