### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by JaydenHamence** [PokemonGoF/PokemonGo-Bot#3070]
### Expected Behavior
bot opens and runs as normal

### Actual Behavior
(PokemonGo-Bot) Jaydens-Air:PokemonGo-Bot JaydenHamence$ sh run.sh
2016-08-08 23:48:11,279 [       cli] [INFO] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
ValueError: Expecting , delimiter: line 99 column 1 (char 2556)

mac osx

**Comment by Dauth** [comment]
check your config

**Comment by JaydenHamence** [comment]
@Dauth cant find an error?

**Comment by djadstar** [comment]
Can you paste in your config file, somebody may be able to point out the issue

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
