### ISSUE TITLE
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'

### ISSUE THREAD

**Issue by joaop7marinho** [PokemonGoF/PokemonGo-Bot#3074]
I'm having the same error that I have on PokemonGo-Map spcrit. Every time I want to run it the console just says:
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'
I'm using Python 2.7.10 32bit version supposedly.
Also I've pip installed, but I can't use the 'pip2' command just the 'pip' one, is that it?
And what about changing from master to dev? I didn't manage to do sth like that...

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
