### ISSUE TITLE
Stops at 1 hour

### ISSUE THREAD

**Issue by icecubeice** [PokemonGoF/PokemonGo-Bot#3075]
The bot works perfectly fine but it stops after about 1hour, is there a way to extend this?

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by siembz** [comment]
@icecubeice i had the same problem. Try git pull, it solved my problem

**Comment by PlanetoftheMapes** [comment]
Yes, this is going to be fixed in a pull request for the Pokemon Go API. When it's applied, you'll want to to a pip install -r requirements.txt to pull the latest version. But as of right now that change hasn't been merged to master so it won't fix the issue just yet.

To fix it now instead of waiting for the PR:

- Go to file: "PokemonGo-Bot/src/pgoapi/pgoapi/auth_google.py"
- Add to line 94: "return self._access_token" (Line 94 is just below: "self.log.debug('Google Access Token: %s...', self._access_token[:25])")

That should fix it. The API forgot to return the token.

**Comment by Nathanian** [comment]
So just add return before self? "self.log.debug('Google Access Token: %s...', self._access_token[:25]) or what?

**Comment by akatasonov** [comment]
@Nathanian Here
![image](https://cloud.githubusercontent.com/assets/6917547/17488043/2887743c-5da0-11e6-816c-00693f5f1bf2.png)

**Comment by Nathanian** [comment]
Thank you so much :)

**Comment by fepersembe** [comment]
For Linux users with same problem:

```
#!/bin/sh
while true
do:
./run.sh
done
```

Just save it on a .sh file(I named it re-run.sh) and make it runnable by (sudo chmod a+x re-run.sh), then run it . Your bot runs again and again infinitely.

**Comment by icecubeice** [comment]
I have the return self.access_token but it wont go beyond 1 h

**Comment by noncicredo** [comment]
tried that solution, but didnt work. Still crashing after 1 hour :(

**Comment by pranavperfect** [comment]
Removed and updated pgoapi. 1+ hour running right now. No crash. Will update if it crashes (or not).
Update: Total Run time 1h 08m
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 547

Followed by Traceback (most recent call last):
  File "pokecli.py", line 493, in <module>
    main()
  File "pokecli.py", line 129, in main
    raise e
TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)

**Comment by icecubeice** [comment]
well let's just all wait for the PR

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
