### ISSUE TITLE
Bot crashes during stale behavior

### ISSUE THREAD

**Issue by jrsama123** [PokemonGoF/PokemonGo-Bot#3076]
### Expected Behavior
Bot to run without crashing.

### Actual Behavior
On stale behavior, attempts to reconnect but crashes.

> 
> 2016-08-08 09:17:09,806 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Construction Artwork - 0.04km (attraction of lure 0.04km)
> 2016-08-08 09:17:20,059 [PokemonGoBot] [INFO] [api_error] Session stale, re-logging in.
> 2016-08-08 09:17:20,059 [PokemonGoBot] [INFO] [login_started] Login procedure started.
> 2016-08-08 09:17:20,674 [PokemonGoBot] [INFO] [login_successful] Login successful.
> 2016-08-08 09:17:20,789 [       cli] [INFO]
> 2016-08-08 09:17:20,789 [       cli] [INFO] Ran for 0:28:49
> 2016-08-08 09:17:20,789 [       cli] [INFO] Total XP Earned: 9305  Average: 19377.28/h
> 2016-08-08 09:17:20,789 [       cli] [INFO] Travelled 1.25km
> 2016-08-08 09:17:20,789 [       cli] [INFO] Visited 26 stops
> 2016-08-08 09:17:20,789 [       cli] [INFO] Encountered 34 pokemon, 33 caught, 0 released, 1 evolved, 0 never seen before
> 2016-08-08 09:17:20,789 [       cli] [INFO] Threw 38 pokeballs
> 2016-08-08 09:17:20,789 [       cli] [INFO] Earned 4100 Stardust
> 2016-08-08 09:17:20,790 [       cli] [INFO]
> 2016-08-08 09:17:20,790 [       cli] [INFO] Highest CP Pokemon: Cloyster [CP: 1243] [IV: 5/7/12] Potential: 0.53
> 2016-08-08 09:17:20,790 [       cli] [INFO] Most Perfect Pokemon: Jynx [CP: 931] [IV: 15/15/15] Potential: 1.0
> Traceback (most recent call last):
>   File "pokecli.py", line 495, in <module>
>     main()
>   File "pokecli.py", line 131, in main
>     raise e
> AttributeError: 'PokemonGoBot' object has no attribute 'get_encryption_lib'
> 2016-08-08 09:17:20,798 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
> Traceback (most recent call last):
>   File "C:\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
>     super(ThreadedHTTPTransport, self).send(data, headers)
>   File "C:\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
>     ca_certs=self.ca_certs,
>   File "C:\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
>     return opener.open(url, data, timeout)
>   File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
>     response = self._open(req, data)
>   File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
>     '_open', req)
>   File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
>     result = func(*args)
>   File "C:\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
>     return self.do_open(ValidHTTPSConnection, req)
>   File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
>     h.request(req.get_method(), req.selector, req.data, headers)
>   File "C:\Python27\lib\httplib.py", line 1057, in request
>     self._send_request(method, url, body, headers)
>   File "C:\Python27\lib\httplib.py", line 1097, in _send_request
>     self.endheaders(body)
>   File "C:\Python27\lib\httplib.py", line 1053, in endheaders
>     self._send_output(message_body)
>   File "C:\Python27\lib\httplib.py", line 895, in _send_output
>     msg += message_body
>   File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
>     return codecs.utf_8_decode(input, errors, True)
> UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
> 2016-08-08 09:17:20,801 [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'PokemonGoBot' object has no attribute 'get_encryption_lib'", u'  File "pokecli.py", line 495, in <module>', u'  File "pokecli.py", line 131, in main']

### Steps to Reproduce
Run bot and wait.

### Other Information
OS: Win 10
Git Commit: ad6c21aa1dc0902c62e4001f9a81ce1fcd8a9f59
Python Version: Python 2.7.12

**Comment by jrsama123** [comment]
> Fixed by keyphact/pgoapi#49

Tried this.  Still crashing after 28:4# every time as I get session stale.

**Comment by k4n30** [comment]
If you're still experiencing this issue, it's because your version is 5 days old, significant changes have been made since then. Update and then create a new issue if you're experiencing any bugs non config related otherwise use the slack server for support
