### ISSUE TITLE
Docker-compose can't start bot-pokegoweb

### ISSUE THREAD

**Issue by YOUR1** [PokemonGoF/PokemonGo-Bot#3081]
### Expected Behavior
Working version..

### Actual Behavior
    Youris-MBP:pokebot youri$ docker-compose up
    Starting pokebot_bot-pokego_1
    Starting pokebot_bot-pokegoweb_1

    ERROR: for bot-pokegoweb  Cannot start service bot-pokegoweb: oci runtime error: rootfs_linux.go:53: mounting "/var/lib/docker/aufs/mnt/6ac1f75194cc7b828690d9b215082f40e41aa7228523101a935ea62ba1cecab6/usr/src/app/web/config/userdata.js" to rootfs "/var/lib/docker/aufs/mnt/6ac1f75194cc7b828690d9b215082f40e41aa7228523101a935ea62ba1cecab6" caused "not a directory"
    ERROR: Encountered errors while bringing up the project.

### Other Information
OS: 
Git Commit: 298006d868f3fe85a2c93526589a1ba6b26695f1
Python Version: 2.7.10

**Comment by k4n30** [comment]
@YOUR1 Update to the latest version as there has been some significant changes, and this may solve your problem
