### ISSUE TITLE
 Error in bot startup

### ISSUE THREAD

**Issue by piai46** [PokemonGoF/PokemonGo-Bot#3083]
Hello, I have a problem in bot and need your help. The problem is this, I installed the bot with the help of my friend, all right but when you open the cmd in the bot folder and type "python pokecli.py" he of the following error: "D: \ Documents \ Desktop \ PokemonGo-Bot-master> python pokecli.py
08/08/2016 12: 27: 10,480 [cli] [INFO] PokemonGO Bot v1.0
08/08/2016 12: 27: 10.483 [cli] [INFO] Error: No /configs/config.json or specified config
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-ws WEBSOCKET.SERVER_URL]
                  [-wss WEBSOCKET.START_EMBEDDED_SERVER]
                  [-wsr WEBSOCKET.REMOTE_CONTROL] [-p PASSWORD] [-l LOCATION]
                  [-lc LOCATION_CACHE] [--forts.spin FORTS.SPIN] [-w WALK]
                  [-k GMAPKEY] [-e SHOW_EVENTS] [-d DEBUG] [-t TEST]
                  [-du DISTANCE_UNIT] [-EC EVOLVE_CAPTURED]
                  [-rt RECONNECTING_TIMEOUT] [-HR HEALTH_RECORD]
                  [-ac FORTS.AVOID_CIRCLES] [-mcs FORTS.MAX_CIRCLE_SIZE]
                  [--catch_randomize_reticle_factor CATCH_RANDOMIZE_RETICLE_FACTOR]
                  [--catch_randomize_spin_factor CATCH_RANDOMIZE_SPIN_FACTOR]
                  [--map_object_cache_time MAP_OBJECT_CACHE_TIME]
pokecli.py: error: argument -a / - auth_service is required "

What should I do? I do not know what to do, I'm trying to get hours, but I can not, I await answers, thanks in advance!

PS: My operating system is Windows 10.
PS²: I leave a screenshot attached.
PS³: If anyone knows speak Portuguese will help me a lot.
Hugs!
![as](https://cloud.githubusercontent.com/assets/20868902/17485438/2bdb5f54-5d64-11e6-9ad8-f5d07d81d0f7.png)

**Comment by nseckinoral** [comment]
Rename config.json.example to config.json under /configs. You need to edit it first to put in your credentials, make sure to check out wiki for further information.

**Comment by piai46** [comment]
The file is already right, look at the picture :
![image](https://cloud.githubusercontent.com/assets/20868902/17500254/39cccd0a-5daa-11e6-9b73-fc990190b18b.png)
