### ISSUE TITLE
ValueError: Expecting , delimiter: line 18 column 3 (char 456)

### ISSUE THREAD

**Issue by mpappasx** [PokemonGoF/PokemonGo-Bot#3084]
### Expected Behavior
Run the bot

### Actual Behavior
Get error when running 

python pokecli.py -cf config.json 
2016-08-08 11:31:25,472 [       cli] [INFO] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
ValueError: Expecting , delimiter: line 18 column 3 (char 456)

### Steps to Reproduce
python pokecli.py -cf config.json 

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here) 

5b3fe3d187b6b5fdfdede00f064bf7bcbd5a484d

Linux 2.6.32-042stab113.21 #1 SMP Wed Mar 23 11:05:25 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux

Centos 7

Python Version: (run 'python -V' and paste it here)

Python 2.7.5

**Comment by Dauth** [comment]
can you check your config.json

**Comment by mpappasx** [comment]
Sure, I've removed some of the data 

{
    "auth_service": "google",
    "username": "[email]@gmail.com",
    "password": "[passwordhere]",
    "location": "41.881832,-87.623177",
    "gmapkey": "[gmap key]",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104,701,201",
    "evolve_all": "ALL"

  // ...
  "tasks": [
    { 
      "type": "TransferPokemon"
    },
    { 
      "type": "RecycleItems"
    },
    { 
      "type": "CatchVisiblePokemon"
    },
    { 
      "type": "CatchLuredPokemon"
    },
    { 
      "type": "SpinFort"
    },
    { 
      "type": "MoveToFort"
    },
    { 
      "type": "FollowSpiral"
    }
  ]
  // ...
}

**Comment by mjmadsen** [comment]
Assuming it wasn't deleted before posting here, there is a comma missing after evolve_all.

Try this http://jsonlint.com/ to check your config for formatting errors.

**Comment by mpappasx** [comment]
Ooo, that is handy, well, I put a comma in there and got this:

Error: Parse error on line 16:
...olve_all": "ALL",	// ...	"tasks": [{
---------------------^
Expecting 'STRING', got 'undefined'

**Comment by mpappasx** [comment]
Oh that's from the checker btw

**Comment by RedViper9** [comment]
Remove the line that starts with //

As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
