### ISSUE TITLE
[Suggestion] Config for logging file

### ISSUE THREAD

**Issue by seratkurtulus** [PokemonGoF/PokemonGo-Bot#3085]
`while true; do`
`	pkill -f pokecli`
`	eval "python pokecli.py --config configs/config.json >> logs/log.txt" &`
`	eval "python pokecli.py --config configs/config1.json >> logs/log1.txt" & `
`	sleep 1800`
`done`

I'm using this bash script for restarting the bots every 30 minutes. It used to keep the logs in the separate files but i guess after the changes to the logging logic it doesn't do the same. I call my bash script with this command.
`"nohup ./run.sh >> logs/restart.txt &"`
it was logging the exceptions into "restart.txt" and other stuff into respective log files but not anymore. Everything goes into restart.txt right now.

Can we add a config option like "pathToLogFile: './logs/log.txt'" and keep the logs in there? It may work as now when this config is not specified or false.

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by k4n30** [comment]
#2729
