### ISSUE TITLE
ImportError: No module named 'cell_workers'`

### ISSUE THREAD

**Issue by Benji26** [PokemonGoF/PokemonGo-Bot#3086]
### Expected Behavior
hello, i have this error on windows 10 anyone can help me please ?
`C:\Users\Nathan\Downloads\PokemonGo-Bot>python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 41, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "C:\Users\Nathan\Downloads\PokemonGo-Bot\pokemongo_bot\__init__.py", line 17, in <module>
    import cell_workers
ImportError: No module named 'cell_workers'`

### Other Information
OS: Windows 10 64Bits

**Comment by Dauth** [comment]
did you pip install in virtualenv?

**Comment by Benji26** [comment]
yes

**Comment by Dauth** [comment]
have you made sure to be inside the virtual env by activating?

**Comment by nelsyeung** [comment]
I believe this problem is from Python 3 where implicit import is turned off completely. One solution is to use Python 2 instead. Another one would be to fix every single `import` to use the `from .. import ..` form. I don't think I have the time to submit a pull request today.

**Comment by iHatePython** [comment]
Already posted #2700
