### ISSUE TITLE
Cannot Launch Bot - Issue with "pokecli.py"

### ISSUE THREAD

**Issue by Mike91188** [PokemonGoF/PokemonGo-Bot#3087]
Hello there! 

I will start out admitting I am a novice to setting this up, but I am pretty sure I have everything running properly. 

I installed the bot and updated the config files with my login info and I am unable to launch the Bot. 
I am receiving this error when i try to run the bot using "python pokecli.py":

"Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions"

![screen shot 2016-08-08 at 10 51 59 am](https://cloud.githubusercontent.com/assets/20898512/17486539/ca2c60d0-5d56-11e6-815b-bc41a82269ad.png)

Thanks! 
Mike

### Other Information
OS: OSX -
Git Commit: 
Python Version: 2.7.12

**Comment by manu183** [comment]
Did you install the requirements?
[https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation#installation-mac](https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation#installation-mac)

**Comment by Mike91188** [comment]
Yes, I actually went back and deleted everything and reinstalled to be sure I did not miss anything.

**Comment by Mike91188** [comment]
Here is the result of installing the pgoapi-1.1.6

![screen shot 2016-08-08 at 11 15 40 am](https://cloud.githubusercontent.com/assets/20898512/17487216/856d3930-5d59-11e6-9989-d66938ad4a83.png)

![screen shot 2016-08-08 at 11 15 43 am](https://cloud.githubusercontent.com/assets/20898512/17487247/9f0c4020-5d59-11e6-921c-41db49c72cbd.png)

I am still getting he same error.

**Comment by MrKaralis** [comment]
In Windows I fixed the problem by installing vc for python 2.7. 
Read my last post  here https://github.com/PokemonGoF/PokemonGo-Bot/issues/2999
Maybe it can help you  to find a solution for Mac.

**Comment by luispereira** [comment]
Getting the same error on windows and I did followed both 
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation#installation-mac
and
MrKaralis answer.

Still the same error appears

**Comment by MrKaralis** [comment]
After installing visual c for python  on Windows you've to run again `pip - r install requirements.txt`

**Comment by AlexBailey** [comment]
Same errors here for OSX
