### ISSUE TITLE
Run 2 bots

### ISSUE THREAD

**Issue by savoyepolo** [PokemonGoF/PokemonGo-Bot#3088]
### Expected Behavior

Run 2 bots 

### Actual Behavior

Error Adress already in use

### Steps to Reproduce

Copy new folder and run 2 bots with screen

### Other Information
OS: Raspbian
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by djadstar** [comment]
I had this issue on previous releases and used a virtual environment to run multiple bots. Not sure if this is the correct work around or not.

**Comment by fmdcarvalho** [comment]
Are you talking about the bot itself or the web module? If its the second you don't need to run 2 instances of the web module. read the wiki

**Comment by cbogithub** [comment]
you can try:
bot1: python pokecli.py --config configs/config1.json
bot2: python pokecli.py --config configs/config2.json

**Comment by TCB13** [comment]
I've been doing what @cbogithub suggested since ever without any issues.

**Comment by djadstar** [comment]
I've tried and get the following: 

 File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

**Comment by djadstar** [comment]
Found my mistake, hadn't activated the virtual environment.
