### ISSUE TITLE
How to run multiple bots?

### ISSUE THREAD

**Issue by Rodwiththegreatbod** [PokemonGoF/PokemonGo-Bot#3094]
I am currently running one bot, and I was wondering how I could run multiple at the same time. Using the dev branch

**Comment by cbogithub** [comment]
see https://github.com/PokemonGoF/PokemonGo-Bot/issues/3088

**Comment by Rodwiththegreatbod** [comment]
When I added another config.json file (names it config1.json) and tried running it in a separate terminal window, i got this error 
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

**Comment by RaizenInstinct** [comment]
just make a copy of your \PokemonGo-Bot-dev folder... change the log-in data in your second config file to different account and run the bot as usual...

**Comment by Baconnaise** [comment]
You can do something like what I have here. Copy the folder and edit the config.json for the different account settings. 

![likethis](https://cloud.githubusercontent.com/assets/20616256/17499988/99f7936e-5d9f-11e6-8747-89d620de4de0.JPG)
