### ISSUE TITLE
[CONFIG][REQUEST] keep best ONLY if cp and iv conditions met aswell. 

### ISSUE THREAD

**Issue by MrPurple6814** [PokemonGoF/PokemonGo-Bot#3097]
### requested Behavior
you can make it so it only catches above  x and y but the way the transfer code is done as long as the keep best flag is there it will always keep 1 even if below the cp and iv req. I have been trying (badly) to add in a config option myself so that you can choose which is checked first.

at the moment it checks for keep best first then cp and iv limit and I am praying for the ability to check cp and iv first and IF it matches then keep only 1 above those limits.
### Actual Behavior
if keep best is in the release config it doesnt matter what the release below is set to it will still keep 1.

if you remove the keep best then it will keep ALL above the cp and iv limit.

also the AND logic does not fix this

### Steps to Reproduce
normal use.

**Comment by GitPupper** [comment]
How'd you get keep best to work? Mine never recycles/transferrs anything.

**Comment by MrPurple6814** [comment]
"release": {
      "any": {"keep_best_cp": 1},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    } just works to keep 1 best of everything.

**Comment by k4n30** [comment]
Please add your config (removing user, pass, and gmapkey)
