### ISSUE TITLE
MoveToPokemonMap: Catch all and filter by standard catch.

### ISSUE THREAD

**Issue by TCB13** [PokemonGoF/PokemonGo-Bot#3099]
### Expected Behavior

There should be an option at worker MoveToMapPokemon.`catch` to simply move to all Pokemon. ( Maybe the current one shouldn't be there??). The Pokemon should be filtered later using the default `catch` option at the config.

### Actual Behavior

We need to manually specify all pokemons we want MoveToMapPokemon to go to.

### Other Information
OS: 
Git Commit: 563f898f61233ff86d38d83b68d8399c1f63051b

**Comment by k4n30** [comment]
Please use the issue template properly

**Comment by TCB13** [comment]
@k4n30 what's the propose of the `catch` section when I'm using `mode = dist`? Shouldn't it be optional? 

![captura de ecra 2016-08-12 as 01 19 29](https://cloud.githubusercontent.com/assets/6315832/17609243/f436b9f8-602a-11e6-9bc5-0780af3dcac6.png)

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md#sniping-movetolocation
