### ISSUE TITLE
unable to install : protobuf-to-dict

### ISSUE THREAD

**Issue by ilikesomething** [PokemonGoF/PokemonGo-Bot#31]
When i do  `pip install -r requirements.txt`

everything works until the last (proto-to-dict) and i have this error at the end :

`Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/g0/q9t3hxlj6r31jtshpx4qz1gw0000gn/T/pip-build-GIODRf/protobuf-to-dict/`

i also tried to install directly proto-to-dict but have same issue

`sudo -H pip install protobuf-to-dict`

`Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-w7f2vQ/protobuf-to-dict/`

i already have installed Python 2.7 and did a brew update and install thing in the readme.

Since proto to dict didn't install, i got an error at launch of the bot : 

> 
>   File "pokecli.py", line 32, in <module>
>     import requests
> ImportError: No module named requests

any idea ?

**Comment by Reaver01** [comment]
try ``pip install --upgrade -r requirements.txt``

**Comment by ilikesomething** [comment]
i just made a reboot and a new pip install and everything worked

**Comment by s1x** [comment]
I do have the same error on AWS EC2 Instance (AWS Linux). I used your command, updated pip used sudo.
Any idea?
