### ISSUE TITLE
Bot fills the pokebag and throws nothing

### ISSUE THREAD

**Issue by Tetranima** [PokemonGoF/PokemonGo-Bot#3102]
### Expected Behavior
Only keep best cp / iv depending on config.json

### Actual Behavior
Keeping all pokemons untill bag is full (since last update on dev branch) (08/08/2016)

### Steps to Reproduce

    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "any": {"keep_best_cp": 2},
      "Eevee": { "keep_best_cp": 5 },
    }

sh run.sh

### Other Information
OS: Win7 64
Git Commit: ff380cd0e07f225ad1ae2c739bea9f9f80e2f8ce
Python Version: Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (
AMD64)] on win32

**Comment by GitPupper** [comment]
Same problem. Most likely the bot's fault and not yours.

**Comment by leadboots5** [comment]
> "release": {
>   "any": {"keep_best_cp": 2},
>   "Eevee": { "keep_best_cp": 5 }
> }

**Comment by Tetranima** [comment]
oh ok i'll try this now.

**Comment by GitPupper** [comment]
@Tetranima You have two "any" lines. Here's my example config for you.
http://pastebin.com/p1FvwXv8
Also, keep the API key blank, it seems to crash if you use one. (for me at least)

**Comment by Tetranima** [comment]
Ok i removed the first "all" line and i'll gie it a try.

Are you talking about Gmap API key ? Never had issues with it.

**Comment by RaizenInstinct** [comment]
guys... release all below cp0 does that make sense? how many pokemon with cp below 0 do you see? you have to put cp and iv above 0 for it to work :D let's say you put cp 300 and iv0.85 then it will work as magic

**Comment by Tetranima** [comment]
Idk if it makes sense but as long as this was the example config, i only changed what i needed and it worked so far.
I prefer to keep on ebest iv and one best cp of each kind, regardless if its under any value.
