### ISSUE TITLE
Ability to use use a proxy

### ISSUE THREAD

**Issue by Unsworth94** [PokemonGoF/PokemonGo-Bot#3103]
### Expected Behavior
I saw there was a commit for adding proxies to the bot but it got reverted :( could we get this added? Would be awesome!

### Actual Behavior
Able to pass a proxy via command/config

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by ddrght12345** [comment]
Install proxychains.
Then just do `proxychains ./pokecli`
No need to inbuilt proxy

**Comment by Unsworth94** [comment]
@ddrght12345 so say I have a bash file that spins up bots, how would i use proxychains with this? (sorry I've never used proxychains)

I've tried `proxychains ./start.sh` already

**Comment by firzzen** [comment]
@ddrght12345 i'm not very familiar with running proxies on a server for a python script. Do you have any suggestions to which one to use on an Ubuntu 15.04 alongside the bot?

**Comment by Unsworth94** [comment]
@firzzen example: `nohup proxychains python pokecli.py -a ptc -u "$1" -p "$2" -l "$3"` After installing `proxychains` using `apt-get install proxychains` then add your proxies into the `/etc/proxychains.conf` file

**Comment by firzzen** [comment]
thanks @Unsworth94 , that helps a lot.

**Comment by firzzen** [comment]
@Unsworth94 i understand that proxychains offers dynamic, static or random proxy usage. But what if you're running five bots at the same time? Can you use different configs for proxychains for different bots?

One option would be to use proxychains random proxy so it cycles them each time but that would look bad if you login from different locations every day, or even worse when the bot crashes and you have to login again 5 minutes after initially starting it.

**Comment by Unsworth94** [comment]
@firzzen yes, you pass `-f /path/to/file/proxychains-xxxx.conf` to the `proxychains` command.

Example: `proxychains -f /path/to/file/proxychains-xxxx.conf  python pokecli.py -a ptc -u "$1" -p "$2" -l "$3"`

**Comment by firzzen** [comment]
@Unsworth94 Trying to run the script with proxychains -f /etc/proxychains.conf python pokecli.py -cf ./configs/config.json results in:

ProxyChains-3.1 (http://proxychains.sf.net)
/usr/bin/proxychains: 9: exec: -f: not found

**Comment by Unsworth94** [comment]
Check the documentation https://github.com/haad/proxychains

**Comment by firzzen** [comment]
Thanks @Unsworth94 . The suggestion might seem very straightforward and basic but now i actually focused into the instructions and realized that you copied commands for secondary config files, not the default one :).

**Comment by Unsworth94** [comment]
Oh I thought that's what you was after! Sorry!

**Comment by maddo7** [comment]
What's the solution for windows?
