### ISSUE TITLE
-m ALL dont work at all

### ISSUE THREAD

**Issue by STNDBS** [PokemonGoF/PokemonGo-Bot#311]
### Expected Behavior
Bot must spin pokestops and collect pokemons 

### Actual Behavior
Do anything

-m Poke works well

**Comment by Akadin** [comment]
Works fine for me

**Comment by STNDBS** [comment]
http://image.prntscr.com/image/dad990630fd340f39d5b77da2b7fa5cd.png
Just walking, dev branch

**Comment by mzupan** [comment]
works fine for me..

```
[#] Walking from (37.339235, -121.870831) to (37.340602, -121.870492) for approx. 16.0 seconds
[#] Something rustles nearby!
[#] A Wild Rattata appeared! [CP 234]
[x] Using Pokeball...
[x] Captured Rattata! [CP 234]
[#] Finished walking
[#] Arrived at Pokestop
[#] Now at Pokestop: Coyote Creek Bridge Tiles - Spinning...
[+] Loot:
[+] 50 xp
[+] 3x Pokeball
[+] 1x Super Potion
[#] PokeStop on cooldown. Time left: 299.877779961 seconds.
[#] Found fort b0aa17f950a34f82966fac816afb7dd8.16 at distance 994.546605519m
```

**Comment by Akadin** [comment]
I just did a pull from dev and restarted, it it both catching pokemon and spinning stops in my area.

**Comment by STNDBS** [comment]
I reinstall bot, reinstall dependences, same problem 10 scans 0 pokemons 0 spinstops

**Comment by STNDBS** [comment]
Poke and farm works well too

**Comment by STNDBS** [comment]
Suddenly all start working well.....
