### ISSUE TITLE
[FEATURE] Nest Farming Mode

### ISSUE THREAD

**Issue by Parth6182** [PokemonGoF/PokemonGo-Bot#3110]
**There should be an option in the config that says NEST MODE**

**When set to true -  The bot will stay inside the specified nest and catch the desired pokemon
eg : If you set it to a charmander nest the bot will only move within the small area of the nest and only catch charmanders**

**When set to false ( default ) - The bot will do what it usually does**

**The bot could also use the poksetops within the small specified nest area**

**Comment by GitPupper** [comment]
Great idea! +1

**Comment by Parth6182** [comment]
> Great idea! +1

Thanks @GitPupper I hope the thread doesn't get lost in the "Bot not Working" posts :D

**Comment by RedViper9** [comment]
You can do this to some extent if you use the MoveToMapPokemon option with "update_map": false,. Your bot's location won't get pushed to the map and you can drop the pin wherever you want the bot to go. It will still nab any pokemon on the way, but will go to the general area of your pin. To limit the area, just set the number of steps lower on the map (won't search as far).

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by k4n30** [comment]
Grouping like requests together - #3580

**Comment by mjmadsen** [comment]
I'd say this could be accomplished by setting your path and limiting stops with current commits.
