### ISSUE TITLE
[Confusing words] Fled vs Escape

### ISSUE THREAD

**Issue by DeviousFusion** [PokemonGoF/PokemonGo-Bot#3117]
Pull #3118 

### Expected Behavior

[pokemon_escaped] Eevee escaped.

### Actual Behavior

[pokemon_fled] Eevee fled.

### Steps to Reproduce

Run the bot as usual. Whenever a pokemon escapes from pokeball, the word usage is confusing

### Other Information
OS: 
Git Commit: ff380cd0e07f225ad1ae2c739bea9f9f80e2f8ce
Python Version: Python 2.7.12

**Comment by Marco208** [comment]
This is wrong. You can't just rename the event, please revert.

**Comment by Marco208** [comment]
pokemongo_bot.event_manager.EventNotRegisteredException: Event pokemon_escaped not registered...

**Comment by DeviousFusion** [comment]
@Marco208 : Fixing. I forgot to push __init__.py

**Comment by Marco208** [comment]
Thanks for your contributions :)

**Comment by RedViper9** [comment]
Thanks for noting this! I had thought the bot was just forcing the api to catch fled pokemon!

`2016-08-08 12:23:46,353 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Greatball, with chance 46.80 (52 left)

2016-08-08 12:23:47,738 [PokemonCatchWorker] [INFO] [pokemon_fled] Psyduck fled.

2016-08-08 12:23:49,401 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Greatball, with chance 46.80 (51 left)

2016-08-08 12:23:50,754 [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Psyduck! [CP 495] [Potential 0.18] [2/0/6] [+150 exp]
`
