### ISSUE TITLE
[Suggestion]Run in Flask

### ISSUE THREAD

**Issue by sarandafl** [PokemonGoF/PokemonGo-Bot#312]
The script could run on the web server allowing one to enter the location in the map or clicking in the map to go there.

**Comment by mzupan** [comment]
Be careful with clicking around maps.. With ingress Niantic monitored how fast players moved and if you had too many quick moves you'd get banned

i think the map is good to watch the bot move and see whats around it and maybe suggest pokemon/stops to hit

**Comment by douglascamata** [comment]
@mzupan bot movement is already watchable through a map.

**Comment by sarandafl** [comment]
@douglascamata With a web server in place the script can be run via a browser (as a frontend for the script).

For example clicking on Pokemon a on a filter and only showing those pokemon in the map. One could then click on them and walk to them.

There can be plenty of cool features implemented like this.

**Comment by mzupan** [comment]
@douglascamata i'd rather run it in flask and open a port.. there's a lot more we can do other then some static work.. you can actually have a control plane via the web for the bot instead of dropping json files all over the place for the two to interact.

**Comment by sarandafl** [comment]
@mzupan This is exactly what I mean
