### ISSUE TITLE
ImportError: No module named pgoapi.exceptions

### ISSUE THREAD

**Issue by Benji26** [PokemonGoF/PokemonGo-Bot#3123]
### Expected Behavior
hi, i have this problem when starting on debian:

`root@raspberrypi:/home/pi/PokemonGo-Bot# python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions`

i've ran pip install git+https://github.com/keyphact/pgoapi.git but nothing...

anyone have an idea ? Thank's
## Other Information
OS: Debian

**Comment by hklcf** [comment]
`pip install -r requirements.txt -U`

**Comment by dymsokei** [comment]
pip install pgoapi

**Comment by bibibkamal** [comment]
i got this error too. bot works just fine an hour ago then this showed up

**Comment by tnlin** [comment]
I just solve this problem on Ubuntu
My solution is switching from python3/pip3 to python2/pip2
It works like a charm

**Comment by spencerby28** [comment]
In this particular case, pip install -r requirements.txt will install all listed package versions to the exact specified version. Most of them work just fine as pip should behave, as they are managed packages of the pypi. The exception here is the pgoapi package, listed on line 3. It is not a pypi package. It is a github repository. Pip handle it badly. In occasions you have to remove the whole repository cloned by pip (rm -rf pgoapi) and do pip install again, i.e. pip install -r requirements.txt

This is a great opportunity to learn python!
