### ISSUE TITLE
Increase XP/hour

### ISSUE THREAD

**Issue by OVO647** [PokemonGoF/PokemonGo-Bot#3124]
Total XP Earned: 13290  Average: 11283.78/h. I'm running it in a populated area with multiple lures and pokestops next to each other. How can I improve my config?

Here is my config

    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 60 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 0 },
            "Hyper Potion":   { "keep" : 0 },
            "Revive":         { "keep" : 0 },
            "Razz Berry":     { "keep" : 60 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 1,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 65},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

**Comment by designer2k2** [comment]
"walk": 14.16,

**Comment by TD-Stanley** [comment]
{
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "Pidgey,Weedle,Rattata,Spearow,Caterpie,Zubat,Oddish,Meowth,Poliwag,Nidoran F, Nidoran M",
            "first_evolve_by": "cp",
            "evolve_above_cp": 1,
            "evolve_above_iv": 0.1,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": true
        }
      },

**Comment by MrPurple6814** [comment]
"walk": 14.16, is not as good as 13.8 as anything above 14 wont hatch eggs.  I personally prefer 12.8 just because.... idk I just do.

**Comment by OVO647** [comment]
How do I make my config rename pokemon as well as wait until it get the maximum number of evolvable pokemon before popping a lucky egg?

**Comment by andriiaveiro** [comment]
how to check exp earned? im using ubuntu

**Comment by SpencerCarstens** [comment]
```json
{
    "type": "NicknamePokemon",
    "config": {
        "nickname_template": "{name}_{iv_pct}"
    }
}
```

**Comment by OVO647** [comment]
@SpencerCarstens Where do I put that in config?

**Comment by OVO647** [comment]
I'm trying my best here never ran any sort of bot before.

**Comment by vicch** [comment]
`"walk": 58.2` still hatching eggs, that is not the actual speed.

**Comment by SpencerCarstens** [comment]
Then... what...

**Comment by TheSegfault** [comment]
This isn't an Issue...... Plz....
