### ISSUE TITLE
Bot teleport (gets softban)

### ISSUE THREAD

**Issue by StarForser** [PokemonGoF/PokemonGo-Bot#3127]
![11111](https://cloud.githubusercontent.com/assets/17098307/17492337/0c89c32a-5db4-11e6-8c77-ea9b92d832bb.JPG)

When using snipe mode

Everything was working fine 40 minutes ago to upgrade

**Comment by WHAAAT** [comment]
did it run before ?
can you post the significant parts of your config ?

**Comment by surewhynotmon** [comment]
...it is supposed to happen.

**Comment by omeryagmurlu** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3148

**Comment by g2384** [comment]
Ok, it is because python is running in the background. You have to kill python before starting a new journey. (The bot can handle unexpected interruption because somebody suggested it as a 'feature'.)

**Comment by my2ndLanguage** [comment]
So basically do not snipe until theres a new solution?
