### ISSUE TITLE
whats wrong with my config?

### ISSUE THREAD

**Issue by phatbasstrd** [PokemonGoF/PokemonGo-Bot#3128]
{
    "auth_service": "google",
    "username": "OMIT",
    "password": "OMIT",
    "location": "SOMEWHERE",
    "gmapkey": "OMIT",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "TransferPokemon",
        "config":{
         "release": {"any": {"release_below_cp": 300, "logic": "or", "keep_best_iv": 2}}
          
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 30 },
            "Super Potion":   { "keep" : 40 },
            "Hyper Potion":   { "keep" : 90 },
            "Revive":         { "keep" : 40 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
{
        "type": "MoveToMapPokemon",
        "config": {
          "address": "http://localhost:5000",
          "max_distance": 500,
          "min_time": 60,
          "prioritize_vips": true,
          "snipe": true,
          "update_map": true,
          "mode": "priority",
          "catch": {
            "==========Legendaries==========": 0,
            "Aerodactyl": 10,
            "Snorlax": 10,
            "Articuno": 10,
            "Zapdos": 10,
            "Moltres": 10,
            "Dratini": 10,
            "Dragonair": 10,
            "Dragonite": 10,
            "Mewtwo": 10,
            "Mew": 10,

            "==========Region Locked==========": 0,
            "Farfetch'd": 10,
            "Kangaskhan": 10,
            "Mr. Mime": 10,
            "Tauros": 10,

            "==========Very Rare==========": 0,
            "Lapras": 10,
            "Electabuzz": 10,
            "Magmar": 10,
            "Ditto": 10,

            "==========Starters==========": 0,
            "Bulbasaur": 10,
            "Ivysaur": 10,
            "Venusaur": 10,

            "Charmander": 10,
            "Charmeleon": 10,
            "Charizard": 10,

            "Squirtle": 10,
            "Wartortle": 10,
            "Blastoise": 10,

            "Pikachu": 10,
            "Raichu": 10,

            "==========Semi Rare==========": 0,
            "Porygon": 10,
            "Scyther": 10,
            "Jynx": 10,

            "==========Uncommon==========": 0,

            "Omanyte": 10,
            "Omastar": 10,

            "Seel": 10,
            "Dewgong": 10,

            "Grimer": 10,
            "Muk": 10,

            "Shellder": 10,
            "Cloyster": 10,

            "Gastly": 10,
            "Haunter": 10,
            "Gengar": 10,

            "Onix": 10,

            "Drowzee": 10,

            "Hypno": 10,

            "Vulpix": 10,
            "Ninetales": 10,

            "Paras": 10,
            "Parasect": 10,

            "Growlithe": 10,
            "Arcanine": 10,

            "Tentacool": 10,
            "Tentacruel": 10,

            "Mankey": 10,
            "Primeape": 10,

            "Clefairy": 10,
            "Clefable": 10,

            "Jigglypuff": 10,
            "Wigglytuff": 10,

            "Venonat": 10,
            "Venomoth": 10,

            "Diglett": 10,
            "Dugtrio": 10,

            "Meowth": 10,
            "Persian": 10,

            "Psyduck": 10,
            "Golduck": 10,

            "Geodude": 10,
            "Graveler": 10,
            "Golem": 10,

            "Eevee": 10,
            "Vaporeon": 10,
            "Jolteon": 10,
            "Flareon": 10,

            "Kabuto": 10,
            "Kabutops": 10,

            "Magikarp": 10,
            "Gyarados": 10,

            "Pinsir": 10,

            "Ponyta": 10,
            "Rapidash": 10,

            "Slowpoke": 10,
            "Slowbro": 10,

            "Magnemite": 10,
            "Magneton": 10,

            "Krabby": 10,
            "Kingler": 10,

            "Voltorb": 10,
            "Electrode": 10,

            "Exeggcute": 10,
            "Exeggcutor": 10,

            "Cubone": 10,
            "Marowak": 10,

            "Hitmonlee": 10,

            "Hitmonchan": 10,

            "Lickitung": 10,

            "Koffing": 10,
            "Weezing": 10,

            "Rhyhorn": 10,
            "Rhydon": 10,

            "Chansey": 10,

            "Tangela": 10,

            "Horsea": 10,
            "Seadra": 10,

            "Goldeen": 10,
            "Seaking": 10,

            "Staryu": 10,
            "Starmie": 10,

            "==========T1 Evolvers==========": 0,
            "Caterpie": 10,
            "Metapod": 10,
            "Butterfree": 10,

            "Weedle": 10,
            "Kakuna": 10,
            "Beedrill": 10,

            "Pidgey": 10,
            "Pidgeotto": 10,
            "Pidgeot": 10,

            "==========T2 Evolvers==========": 0,
            "Nidoran F": 10,
            "Nidorina": 10,
            "Nidoqueen": 10,

            "Nidoran M": 10,
            "Nidorino": 10,
            "Nidoking": 10,

            "Oddish": 10,
            "Gloom": 10,
            "Vileplume": 10,

            "Poliwag": 10,
            "Poliwhirl": 10,
            "Poliwrath": 10,

            "Abra": 10,
            "Kadabra": 10,
            "Alakazam": 10,

            "Machop": 10,
            "Machoke": 10,
            "Machamp": 10,

            "Bellsprout": 10,
            "Weepinbell": 10,
            "Victreebel": 10,

            "==========Trash==========": 0,

            "Rattata": 10,
            "Raticate": 10,

            "Spearow": 10,
            "Fearow": 10,

            "Ekans": 10,
            "Arbok": 10,

            "Sandshrew": 10,
            "Sandslash": 10,

            "Zubat": 10,
            "Golbat": 10,

            "Doduo": 10,
            "Dodrio": 10
          }
        }
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 15,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
"release": {"any": {"release_below_cp": 300, "logic": "or", "keep_best_iv": 2},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

**Comment by GitPupper** [comment]
{
    "auth_service": "google",
    "username": "email@gmail.com",
    "password": "pw",
    "location": "34.0087376, -118.5004127",
    "gmapkey": "GOOGLE_MAPS_API_KEY",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },{
		"type": "NicknamePokemon",
		"config": {
			"nickname_template": "{iv_pct}_{iv_ads}"
		},

        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Potion":         { "keep" : 20 },
            "Super Potion":   { "keep" : 50 },
            "Hyper Potion":   { "keep" : 100 },
            "Revive":         { "keep" : 100 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 10,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"keep_best_cp": 2},
      "Eevee": { "keep_best_cp": 5 }
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

**Comment by GitPupper** [comment]
Correct config above. Also fixes recycling.

**Comment by phatbasstrd** [comment]
Thank you. I thought it was my transferpokemon
