### ISSUE TITLE
Command '-m all' only catches Pokemon and '-m farm' don't farm

### ISSUE THREAD

**Issue by nvhk** [PokemonGoF/PokemonGo-Bot#313]
### Expected Behavior
Command '-m all' should visit pokestops

### Actual Behavior
Command '-m all' only catches Pokemon and '-m farm' don't farm

### Other Information
OS: Ubuntu 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by buusc0** [comment]
Could you post your logs? Is there an error message?

**Comment by douglascamata** [comment]
with all the respect, but bug reports with no debug information are not helpful, because for everybody else it works.

**Comment by Foxy1990** [comment]
Can't confirm 

```
[#] Now at Pokestop: Wissenschaftspferd - Spinning...
[+] Loot:
[+] 50 xp
[+] 3x Pokeball
[#] PokeStop on cooldown. Time left: 299.194000006 seconds.
need a rest
[#] Found fort 02b585ee06a94d2cbb822b9461562987.16 at distance 461.034767125m
[#] Need to move closer to Pokestop
[#] Walking from (50.77729, 6.078873) to (50.779305, 6.078742) for approx. 9.0 seconds
[#] Something rustles nearby!
[#] A Wild Zubat appeared! [CP 10]
[x] Using Pokeball...
[x] Captured Zubat! [CP 10]
[#] Something rustles nearby!
[#] A Wild Pidgey appeared! [CP 76]
[x] Using Pokeball...
```

**Comment by jdinh1** [comment]
It works fine. Here's my log "-m all" show that it catch and spin pokestops.

`[#] A Wild Ekans appeared! [CP 402]
[x] Using Pokeball...
[x] Oh no! Ekans vanished! :(
[#] Finished walking
[#] Arrived at Pokestop
[#] Now at Pokestop: Free Parking Fish Stencil  - Spinning...
[+] Loot:
[+] 50 xp
[+] 3x Pokeball
[#] PokeStop on cooldown. Time left: 282.668595076 seconds.
[#] Found fort b852a9273bd54c62a01190cc0198b62b.11 at distance 1506.95019585m
[#] Need to move closer to Pokestop
[#] Walking from (34.02334, -118.492047) to (34.022205, -118.48975) for approx. 13.0 seconds
`

**Comment by jdinh1** [comment]
It works fine for me. Here's my log showing "-m all" attempt to catch and spin a pokestop.

> [#] A Wild Ekans appeared! [CP 402]
[x] Using Pokeball...
[x] Oh no! Ekans vanished! :(
[#] Finished walking
[#] Arrived at Pokestop
[#] Now at Pokestop: Free Parking Fish Stencil  - Spinning...
[+] Loot:
[+] 50 xp
[+] 3x Pokeball
[#] PokeStop on cooldown. Time left: 282.668595076 seconds.
[#] Found fort b852a9273bd54c62a01190cc0198b62b.11 at distance 1506.95019585m
[#] Need to move closer to Pokestop
[#] Walking from (34.02334, -118.492047) to (34.022205, -118.48975) for approx. 13.0 seconds

**Comment by LostDGod** [comment]
Working flawlessly for me as well. It just takes way too much time to go from one pokestop to the next.

**Comment by douglascamata** [comment]
There's a delay with a random component when arriving at a pokestop, it's intentional to mimic human behaviour.

**Comment by popadiys** [comment]
fine for me as well

**Comment by s1x** [comment]
@nvhk Please create a new issue if necessary with a copy of your error.
