### ISSUE TITLE
BOT is not transferring/evolving pokemons

### ISSUE THREAD

**Issue by SypherMWB** [PokemonGoF/PokemonGo-Bot#3138]
**Hello, the BOT is somehow not transferring my pokemons nor is it evolving them, here is the config, does anyone know why?**

`{
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "Pidgey,Pidgeotto,Rattata,Weedle,Caterpie,Kakuna,Metapod,Zubat,Spearow",
            "first_evolve_by": "cp",
            "evolve_above_cp": 0,
            "evolve_above_iv": 0,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 20 },
            "Greatball":      { "keep" : 40 },
            "Ultraball":      { "keep" : 80 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 30 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "nickname_template": "{name:.9s}{iv_pct}"
        }  
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 12.13,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "Pidgey,Pidgeotto,Rattata,Weedle,Caterpie,Kakuna,Metapod,Zubat,Spearow,",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "Pidgeot": {"release_below_cp": 1400, "release_below_iv":0.8, "logic": "or" },
      "Pidgeotto": {"release_below_cp": 825, "release_below_iv":0.8, "logic": "or" },
      "Raticate": {"release_below_cp": 1200, "release_below_iv":0.8, "logic": "or" },
      "Weedle": {"keep_best_cp": 2},
      "Kakuna": {"keep_best_cp": 2},
      "Beedrill": {"keep_best_cp": 1},
      "Caterpie": {"keep_best_cp": 2},
      "Metapod": {"keep_best_cp": 2},
      "Butterfree": {"keep_best_cp": 1},
      "Venonat": {"keep_best_cp": 2},
      "Venomoth": {"keep_best_cp": 1},
      "Magikarp": {"keep_best_cp": 2},
      "Fearow": {"keep_best_cp": 1},
      "Abra": {"keep_best_cp": 1},
      "Nidoran F": {"keep_best_cp": 1},
      "Nidoran M": {"keep_best_cp": 1},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1400, "catch_above_iv": 0.95, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dratini": {},
        "Dragonair": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {},
        "Magmar": {}

    }
}`

**Comment by Kassadd** [comment]
"any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},

I guess.. try putting something like:

"any": {"release_below_cp": 500, "release_below_iv": 0.8, "logic": "and"},

# ((The "and" is important!!)

**Comment by SypherMWB** [comment]
**That fixed it, thanks Kassadd!**

**Comment by jane0815** [comment]
Have exactly the same problem. Made the changes suggested by Kassadd but bot only released Nidoran F, Nidoran M and Dratini. The only pokemons that are not in the config file.

**Comment by kyleboe** [comment]
@SypherMWB Side note: use 3 backticks to start and end your code block

    ```
    config files stuffs
    ```

**Comment by jane0815** [comment]
And where to find better config files?

**Comment by SypherMWB** [comment]
This config worked fine, until yesterday somehow.

**Comment by williamgilpin** [comment]
@SypherMWB, my regrets if this seems like an obvious suggestion, but in your config files did you completely uncomment all the common Pokemon names after you copied the default template? By this I mean that the config.json.example file has lines that look something like this:

`"// Pidgey": {"keep_best_cp": 3},
`

In your actual config.json you want this line to be some variation of this:

`"Pidgey": {"keep_best_cp": 3},
`

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
