### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by nanogirl21** [PokemonGoF/PokemonGo-Bot#3140]
I keep getting this error about 30 seconds into running my bot. Any tips on how to fix? 

Running Dev on OS X with Google account 

```
Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
IndexError: list index out of range

RESTARTING
Loop Iterations:  34
Runtime was 0 minutes and 29 seconds

```

**Comment by Kassadd** [comment]
#3121

**Comment by nanogirl21** [comment]
I'm not getting this 

[Traceback (most recent call last):
  File "pokecli.py", line 502, in <module>
    main()
  File "pokecli.py", line 133, in main
    raise e
KeyError: 'new_catch_rate'](url)
