### ISSUE TITLE
[QUESTION] Why is the log output no longer pretty?

### ISSUE THREAD

**Issue by Nurvx** [PokemonGoF/PokemonGo-Bot#3147]
I have been wondering, along the way, the bot log output went from being pretty with colors and proper formatting to this:

<img width="1275" alt="screen shot 2016-08-08 at 4 41 30 pm" src="https://cloud.githubusercontent.com/assets/6528118/17495507/47617772-5d87-11e6-8e03-a9197faced8b.png">

Why?

I have all the debug/test flags set to false.

**Comment by leadboots5** [comment]
They changed how logging was done

**Comment by Nurvx** [comment]
What was wrong with how it was done before?

**Comment by fyooree** [comment]
They use a own event system now.

I pushed a temporary fix which colored it again but they declined it because there is already a open pull request for this issue. 

Nobody knows when this is ready though. Thats why I made the temporary fix ;)

**Comment by Vvkmnn** [comment]
Nothing really, and other people have also been discussing it. 

PR #2604 proposes a possible fix, and there's some temporary workarounds in #2547 and #2675. 

I also thought it was fine, but @Kujawadl's [post](https://github.com/PokemonGoF/PokemonGo-Bot/issues/2547#issuecomment-237400490) outlined some of the possible benefits.

**Comment by Nurvx** [comment]
@fyooree Hopefully not just the coloring, but also the formatting as well. It's so hard on the eyes, unlike before I could just glance it over and see what was picked up from a PokeStop and what hatched from my egg (which doesn't show at all anymore). Thanks for the links @Vvkmnn

**Comment by fyooree** [comment]
Didn't touch that but it doesn't matter anyway. We have to wait for the PR #2604
