### ISSUE TITLE
not working google login

### ISSUE THREAD

**Issue by vanrzuf** [PokemonGoF/PokemonGo-Bot#315]
python2 pokecli.py -a google -u user -p pass always gives Login Error, server busy. I've checked on phone and i'm able to login without any problems

**Comment by msoedov** [comment]
if you have a two factor auth then try to create a new password for device

**Comment by darioblanco** [comment]
Confirmed it works with app password for me (I use two factor)

**Comment by ckrmml** [comment]
did not work a single time for me

**Comment by vanrzuf** [comment]
i dont have 2factor auth enabled but will try

**Comment by AlexeyToksarov** [comment]
Looks like it doesn't work if `-du` option enabled

**Comment by s1x** [comment]
@vanrzuf I hope your issue is resolved. 
Please feel free the open a new issue when necessary!
