### ISSUE TITLE
[SUGGESTION] Evolve to fill Pokedex

### ISSUE THREAD

**Issue by nicholasjohn** [PokemonGoF/PokemonGo-Bot#3150]
**It would be awesome to have a configuration setting which uses candy to prioritise filling the Pokedex.**

For example, if I had 4 Bellsprouts, 1 Weepinbell and 100 candies, the bot may come across a Bellsprout first and evolve it. There will of course then not be enough candy to evolve the Weepinbell...

Thoughts & opinions welcomed!

```
{
  "type": "EvolvePokemon",
  "config": {
    "evolve_all": "all",
    "prioritise_pokedex": true,
    "evolve_speed": 20
  }
}
```

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by Northernmmo** [comment]
Second this one.  It'd be great to be able to set an evolve mode, "evolve_pokedex" for example, to only evolve pokemon that we have enough candy for and would fill a missing pokedex slot.  Optionally you'd be able to prioritize highest cp/IV to evolve.
