### ISSUE TITLE
Receiving Error After Perfect Installation

### ISSUE THREAD

**Issue by adamvc21** [PokemonGoF/PokemonGo-Bot#3151]
### Expected Behavior
Bot Initiated, after following Wiki install guide perfectly without errors and configuring my config.
Also using http://jsonlint.com/ to validate my json
### Actual Behavior
Error Report:
[http://pastebin.com/yCukVqn4](http://pastebin.com/yCukVqn4)

My Config:
[http://pastebin.com/1XBLsdxF](http://pastebin.com/1XBLsdxF)

### Steps to Reproduce
Execute "python pokecli.py" in Git Bash in my bots root directory

### Other Information
OS: Windows 10
Git Commit: ae0ae815089bf1e3b17497b476d524a0468949e2
Python Version: Python 2.7.12

**Comment by iruy** [comment]
This `WindowsError: [Error 193] %1 is not a valid Win32 application` says a lot, probably you downloaded the wrong library version.
While for this one `UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)` there are some issues already open, check this https://github.com/PokemonGoF/PokemonGo-Bot/issues/2769

**Comment by adamvc21** [comment]
Thank you! I think this is the problem. I couldn't find that before. How do I find a good encrypt.dll for Windows 10? I noticed the last comment in that issue was also inquiring.

**Comment by iruy** [comment]
I don't know if there is a better source. I downloaded mine from here https://pokemongo-bot.slack.com/files.
Look for encrypt64bit.dll (please correct if I'm wrong) for x64

**Comment by adamvc21** [comment]
Wonderful thank you. I used 

https://files.slack.com/files-pri/T1U6G9ZEW-F1Z43THJ5/download/encrypt.dll

and it starts and functions perfectly.
