### ISSUE TITLE
[Output Error] Pokemon fled and then caught

### ISSUE THREAD

**Issue by nicholasjohn** [PokemonGoF/PokemonGo-Bot#3152]
### Expected Behaviour
EITHER:
1. When a Pokemon flees, to continue to other tasks.
2. When a ball fails, Pokemon either flees or stays to allow another ball to be thrown

### Actual Behaviour
When ball fails due to low chance rate, `Pokemon fled` is output. However, another ball is then thrown, and `Captured Pokemon!` is output.

### Steps to Reproduce
See output below:
```
[PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Spearow appeared! [CP 247] [Potential 0.4] [S/A/D 8/6/4]
[PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 38.66 (24 left)
[PokemonCatchWorker] [INFO] [pokemon_fled] Spearow fled.
[PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 38.66 (23 left)
[PokemonCatchWorker] [INFO] [pokemon_caught] Captured Spearow! [CP 247] [Potential 0.4] [8/6/4] [+420 exp]
```

### Other Information
OS: OSX El Capitan
Git Commit: 5b3fe3d187b6b5fdfdede00f064bf7bcbd5a484d
Python Version: Python 2.7.12

**Comment by iruy** [comment]
`Fled` doesn't mean `Vanished`, but just that the pokemon escaped the ball

**Comment by g2384** [comment]
By `fled` it means `broke free`. I don't understand this update. it's confusing

**Comment by leadboots5** [comment]
This has already been fixed:
https://github.com/PokemonGoF/PokemonGo-Bot/pull/3129

**Comment by g2384** [comment]
Update: By `escaped` it means broke free. I don't understand this update *either*. It's *still* confusing.

**Comment by nicholasjohn** [comment]
Closing. #3129 does indeed fix the wording issue.
