### ISSUE TITLE
Bot softban

### ISSUE THREAD

**Issue by icecubeice** [PokemonGoF/PokemonGo-Bot#3156]
Somehow I mistakenly put the coordinates to central park and I'm from new Zealand, I got sofbanned for 4 hours? so I went to my phone to check, I could catch and spin pokestops and pokemon. but when I use the bot with the correct cords it says probably got softbanned, pokemons are not captured and pokestops not giving items, seems like the bot is giving me a softban. But on my other account that is being botted it doesnt

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by g2384** [comment]
Check the actual position of the bot (in terminal or in `data/last-location-...`). It may use your last location (central park). Kill Python and delete that last-location file.
