### ISSUE TITLE
[Dev] Just wallking same place or not walking

### ISSUE THREAD

**Issue by ZgrK** [PokemonGoF/PokemonGo-Bot#3167]
My bot just walking :( 

### My config

`"tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "all",
            "first_evolve_by": "cp",
            "evolve_above_cp": 300,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": true
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 10 },
            "Greatball":      { "keep" : 30 },
            "Ultraball":      { "keep" : 40 },
            "Masterball":     { "keep" : 50 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 10 },
            "Hyper Potion":   { "keep" : 10 },
            "Revive":         { "keep" : 10 },
            "Razz Berry":     { "keep" : 10 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config":{
          "lure_attraction": true,
          "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 250
    },
    "websocket_server": false,
    "walk": 13.4,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "all",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or" },

      "// Pokemons with example": { "always_catch": true },
      "// Gets filtered with release parameters": {},

      "// Legendary pokemons (Goes under S-Tier)": {},
      "Lapras": { "always_catch": true },
      "Moltres": { "always_catch": true },
      "Zapdos": { "always_catch": true },
      "Articuno": { "always_catch": true },

      "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
      "Mewtwo": { "always_catch": true },
      "Dragonite": { "always_catch": true },
      "Snorlax": { "always_catch": true },
      "// Mew evolves to Mewtwo": {},
      "Mew": { "always_catch": true },
      "Arcanine": { "always_catch": true },
      "Vaporeon": { "always_catch": true },
      "Gyarados": { "always_catch": true },
      "Exeggutor": { "always_catch": true },
      "Muk": { "always_catch": true },
      "Weezing": { "always_catch": true },
      "Flareon": { "always_catch": true },

      "// Growlithe evolves to Arcanine": {},
      "Growlithe": { "always_catch": true },
      "// Dragonair evolves to Dragonite": {},
      "Dragonair": { "always_catch": true },
      "// Grimer evolves to Muk": {},
      "Grimer": { "always_catch": true },

      "// Magikarp evolves to Gyarados": {},
      "Magikarp": { "always_catch": true },
      "// Exeggcute evolves to Exeggutor": {},
      "Exeggcute": { "always_catch": true },
      "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
      "Eevee": { "always_catch": true },

      "// A-Tier pokemons": {},
      "Slowbro": { "always_catch": true },
      "Victreebel": { "always_catch": true },
      "Machamp": { "always_catch": true },
      "Poliwrath": { "always_catch": true },
      "Clefable": { "always_catch": true },
      "Nidoking": { "always_catch": true },
      "Venusaur": { "always_catch": true },
      "Charizard": { "always_catch": true },
      "Golduck": { "always_catch": true },
      "Nidoqueen": { "always_catch": true },
      "Vileplume": { "always_catch": true },
      "Blastoise": { "always_catch": true },
      "Omastar":  { "always_catch": true },
      "Aerodactyl": { "always_catch": true },
      "Golem": { "always_catch": true },
      "Wigglytuff": { "always_catch": true },
      "Dewgong": { "always_catch": true },
      "Ninetales": { "always_catch": true },
      "Magmar": { "always_catch": true },
      "Kabutops": { "always_catch": true },
      "Electabuzz": { "always_catch": true },
      "Starmie": { "always_catch": true },
      "Jolteon": { "always_catch": true },
      "Rapidash": { "always_catch": true },
      "Pinsir": { "always_catch": true },
      "Scyther": { "always_catch": true },
      "Tentacruel": { "always_catch": true },
      "Gengar": { "always_catch": true },
      "Hypno": { "always_catch": true },
      "Pidgeot": { "always_catch": true },
      "Rhydon": { "always_catch": true },
      "Seaking": { "always_catch": true },
      "Kangaskhan": { "always_catch": true }
    },
    "release": {"any": {"keep_best_cp": 1}},
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}
`

##ScreenShots
<img width="1307" alt="screen shot 2016-08-09 at 1 43 17 am" src="https://cloud.githubusercontent.com/assets/879674/17498875/af2f7eee-5dd2-11e6-9f0f-1e8c81c95725.png">

<img width="709" alt="screen shot 2016-08-09 at 1 43 51 am" src="https://cloud.githubusercontent.com/assets/879674/17498891/c053278e-5dd2-11e6-8a24-987573f269bf.png">

Os:ubuntu
Git Commit:4b16e9da985e689d57beae8bf18878f4d872bdc4

**Comment by ZgrK** [comment]
<img width="1380" alt="screen shot 2016-08-09 at 1 51 39 am" src="https://cloud.githubusercontent.com/assets/879674/17499104/00468826-5dd4-11e6-9192-27c9f8f74c72.png">

**Comment by LostDGod** [comment]
I just had the same problem just now and it was working fine less than 30min ago. I didn't update the bot and its working again now so theres no doubts it was a problem with their servers. Might have been the same for you.

**Comment by ZgrK** [comment]
@LostDGod how many bots are working on your server ?

**Comment by BriceSD** [comment]
@ZgrK Either reduce your walking speed or remove this : 
```
{
"type": "FollowSpiral",
"config": {
"diameter": 4,
"step_size": 70
}
}
```

**Comment by bornbygoogle** [comment]
I have the same issue =.='

@BriceSD  as you said, i remove FollowSpiral, but the bot won't work, ... it stuck after IncubateEgg ...

**Comment by ninovandenheuvel** [comment]
I have the same issue.
Starts but stops after the IncubateEgg statement.
Adding FollowSpiral makes it stand still and keep checking or something.

2016-08-09 15:03:44,484 [FollowSpiral] [INFO] [position_update] Walking from (59.31193642074128, 18.021953557311342, 0) to (59.31193642074128, 18.021792732007082, 0) (9.12678297608 m)
2016-08-09 15:03:48,229 [FollowSpiral] [INFO] [position_update] Walking from (59.31193642074128, 18.021792732007082, 0) to (59.31184660914891, 18.021792732007082, 0) (9.98672407307 m)
2016-08-09 15:03:51,696 [FollowSpiral] [INFO] [position_update] Walking from (59.31184660914891, 18.021792732007082, 0) to (59.31193642074128, 18.021792732007082, 0) (9.98672407307 m)
2016-08-09 15:03:55,209 [FollowSpiral] [INFO] [position_update] Walking from (59.31193642074128, 18.021792732007082, 0) to (59.31193642074128, 18.021953557311342, 0) (9.12678297608 m)
2016-08-09 15:03:58,442 [FollowSpiral] [INFO] [position_update] Walking from (59.31193642074128, 18.021953557311342, 0) to (59.31184660914891, 18.021953557311342, 0) (9.98672407307 m)

**Comment by Hetarnam** [comment]
same problem, i changed anything but bot just walk :(

**Comment by EvgeniyTaburyanskiy** [comment]
same problem!
10 bots. on server. synhronius walking by spiral.
restarting bots, not work.

**Comment by ZgrK** [comment]
if you have few bots you must use proxy :(
