### ISSUE TITLE
Not transferring pokemon after capturing.

### ISSUE THREAD

**Issue by em202020** [PokemonGoF/PokemonGo-Bot#317]
### Expected Behavior
When a pokemon under what is set with -c, it will transfer it.

### Actual Behavior
Console says that the pokemon has been transferred, but the pokemon remains in the inventory.  Happens most of the time, fails probably 90%(?) of the time.

### Steps to Reproduce
I set -c to 500, and just running it doesnt transfer those pokemon.

### Other Information
OS: Windows 
Git Commit: https://github.com/PokemonGoF/PokemonGo-Bot/commit/882232d1e850da4d857cce1e0935b173c969c406 is the one I DLd at.
Note: Transferring works with other bots, so I dont believe it is a problem with the servers.

~~Does it only not transfer it if it is the only one you have?  Like if I dont have a sandshrew, and I catch a CP10 sandshrew, and it is the only one I have, will it not transfer it?  As thats what its looking like.~~
Just tested this, had a 605 Ponyta, caught a 197 Ponyta, didnt transfer it.

**Comment by buusc0** [comment]
Experiencing same issue. Despite receiving a successful "[#] Pinsir has been exchanged for candy!" message, the pokemon actually stays in inventory.

**Comment by douglascamata** [comment]
duplicated, so will close to avoid spam.
