### ISSUE TITLE
Using .KML file ?

### ISSUE THREAD

**Issue by MrGeff** [PokemonGoF/PokemonGo-Bot#3178]
It is possible to use .kml as path?

**Comment by ThunderVamp9** [comment]
Not sure, but I don't think so. However, you can use this:

http://kml2gpx.com/

**Comment by Dauth** [comment]
look at the sample given.

`[
{"location": "lat, lon"}

]`

**Comment by MrGeff** [comment]
Ok, thanks for your attention.  I used sublime to edit the .kml file, leaving in the format used path.example.json.
