### ISSUE TITLE
BOt not work again?

### ISSUE THREAD

**Issue by fitjrian** [PokemonGoF/PokemonGo-Bot#3179]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by DiegoRBaquero** [comment]
Working for me

**Comment by MrGeff** [comment]
Working well!!!

**Comment by kyleboe** [comment]
Yep running just fine right now.

**Comment by nhuhoang0501** [comment]
My bot keep saying pokemon escape using item pokeball :( 
Any way to fix this (im not softbanned)

**Comment by shivamkalra** [comment]
How do you expect anyone to help you if you won't provide even necessary information. I suggest delete this or edit this post.
