### ISSUE TITLE
IRC channel instead of Slack

### ISSUE THREAD

**Issue by MaxLeiter** [PokemonGoF/PokemonGo-Bot#318]
Why use closed-source software when IRC runs perfectly well? I'm willing to run a version of [TheLounge](https://www.github.com/thelounge/lounge) purely for a PokemonGo channel, if people are unwilling to setup their own clients.

**Comment by douglascamata** [comment]
Slack as awesome as soon as we stop hitting the invite rate limit. Much more feature rich.

**Comment by MaxLeiter** [comment]
What are some features that Slack has over IRC/TheLounge?

**Comment by solderzzc** [comment]
IRC maybe same as Gitter, we can get Gitter back ?

**Comment by MaxLeiter** [comment]
Or just use IRC? Gitter would be a regression from Slack, if anything.

**Comment by solderzzc** [comment]
but we will lose the github integration

**Comment by MaxLeiter** [comment]
What Github integration? You can setup webhooks on the repo to announce commits, PRs, etc, plus I wrote a helpful bot for referencing issues and PR's which is available [here](https://www.github.com/lounge/lounge-bot). I'm willing to run lounge-bot (under a different name) and a github [announce bot](https://github.com/xpaw/wendysharp) on the channel if necessary.

**Comment by solderzzc** [comment]
Nice :)

**Comment by MaxLeiter** [comment]
I registered the channel and started a Lounge instance here: http://avatar.playat.ch:5000, and am currently setting the bots up

**Comment by douglascamata** [comment]
I don't see any advantages of IRC over Slack. Why should we change?

**Comment by MaxLeiter** [comment]
Not proprietary, open-source, multiple clients, more general use, no invite limit, etc.

https://drewdevault.com/2015/11/01/Please-stop-using-slack.html

**Comment by douglascamata** [comment]
@MaxLeiter and then we lose: code highlight with github flavoured markdown, text files hosting, image hosting, very powerful notifications control, powerful built-in search... I can name more if u want.

**Comment by MaxLeiter** [comment]
It all depends on the client you setup....people can use imgur, pastebin, gist, etc. for file hosting. Notifications are all handled by the client (IRC has many, Slack has one).

**Comment by douglascamata** [comment]
@MaxLeiter this way you're trusting the users to have the best experience by themselves. We should give them the best experience by default.

**Comment by TheSavior** [comment]
It sounds like you guys are arguing over something like tabs or spaces. It doesn't really matter as long as we pick one. The project has currently picked slack.

However, if people are unable to join the slack channel because it is too popular and there is a limit to the number of people in a room or the number of invitations that can be sent out (is this the problem?) then the pros and cons are different. But @MaxLeiter you should be explicit that *that* is the main problem you are hoping to solve.

**Comment by MaxLeiter** [comment]
While that is the main problem I'm trying to solve, there are also benefits to using IRC (many of which are mentioned in the blog post I linked above).

@douglascamata first and foremost, this is an opensource project posted to /r/pokemongodev: the people that use it should be relatively "advanced" users. They should be able to figure out IRC.

**Comment by douglascamata** [comment]
@TheSavior exactly. We send too many invites today and there's a limit to # of invitations sent per day. No limit to number of users in the slack group.

**Comment by douglascamata** [comment]
@MaxLeiter there are of lot of ppl that don't even have command line knowledge using this. Just look at the issue tracker and you will see many issues that a noob programmer would be able to handle by himself. Many of these I already closed, but there were ppl asking what git was.

**Comment by douglascamata** [comment]
@MaxLeiter they can figure out IRC, but how long will they need to find and configure a client to have a feature set close to Slack?

**Comment by MaxLeiter** [comment]
Those people probably shouldn't be using it, then. That's why I made #322: It links to an easy-to-use IRC web client I'm hosting.

**Comment by douglascamata** [comment]
@MaxLeiter then you come again to the point that you're making not so experienced developers and potential contributors' life harder.

**Comment by douglascamata** [comment]
@MaxLeiter open-source project best part is integration. Everyone one, no matter the experience, can help somehow. With IRC the communication part becomes clearly harder for ppl with less experience.

**Comment by MaxLeiter** [comment]
try using the [client](http://avatar.playat.ch:5000) I linked; it's pretty easy to use. Doesn't require an obscure hack to sign up.

**Comment by douglascamata** [comment]
@MaxLeiter can I past code there with highlighting? can I take a screenshot on my computer and just Control (or Command) + V there? can I paste a huge file in a proper way that doesn't spam the whole thing? No, for all these things I need external services.

**Comment by douglascamata** [comment]
`http://avatar.playat.ch:5000` is not even loading for me.

**Comment by MaxLeiter** [comment]
While those are benefits, I think if someone can't use pastebin/gist they shouldn't be using github. This way, everyone can join now, as opposed to waiting for an invite.

**Comment by douglascamata** [comment]
@MaxLeiter you're excluding less experienced people for no reason.

**Comment by MaxLeiter** [comment]
More people are able to use it, therefore more people are being included.

**Comment by douglascamata** [comment]
@MaxLeiter not true. Just look the closed issues here.

**Comment by bool-** [comment]
I'd rather use IRC cause I'm already on it and wasting resources with another silly web app is pointless.

**Comment by MaxLeiter** [comment]
@douglascamata look at the issues regarding not being able to join slack #324

**Comment by douglascamata** [comment]
@MaxLeiter they're going to end automatically with time, I already told you this. We got almost 400 starts in 24 hours. Every single person was clicking to get an slack invite. Of course this would happen. If it were in IRC the channel would be simply useless because of the spam. 

By tomorrow we should be given a few more hundred invites and the boom is gone, so we will be good with Slack.

**Comment by MaxLeiter** [comment]
It's more the principal that the invites exist: a FOSS project shouldn't use that. How many people do you think have tried getting a slack invite and have been expecting an email which won't ever come through because the heroku app doesn't report a failure?

**Comment by douglascamata** [comment]
@bool- "I'd rather use <my_tool> because I'm already on it and using resources for <your_tool> is pointless". Fill the gaps with whatever you want. Everyone has their preferences.

**Comment by TheSavior** [comment]
@MaxLeiter Probably fewer than the number of people who are already set up in Slack which would be uprooted switching again.

**Comment by buusc0** [comment]
Agree with doug here. Once the slack invite issues are fixed it's definitely preferable to IRC. Sure, not everyone will be happy, but the majority will.

**Comment by douglascamata** [comment]
@MaxLeiter why not? Do you also think I shouldn't be doing FOSS because I work on OS X machine (closed source)?

**Comment by MaxLeiter** [comment]
It's forcing people to use one; again, I recommend reading the blog post.

**Comment by douglascamata** [comment]
We're forcing people to use any paid app.

**Comment by douglascamata** [comment]
I don't agree with that blog post, it doesn't show any clear advantage of IRC over Slack that would make me switch.

**Comment by MaxLeiter** [comment]
You clearly didn't understand the blog post; it's not trying to force you to use IRC > slack, it's saying IRC is better for FOSS projects. You as an individual are fine to use whatever you choose, but don't have the community use slack by default imo.

**Comment by douglascamata** [comment]
And can I force IRC just because it's FOSS?

**Comment by douglascamata** [comment]
"you can't force the community to use Slack, but let's force the community to use IRC instead" 😉

**Comment by MaxLeiter** [comment]
You don't have to force it either-way (and shouldn't), I just think forcing an opensource and non-proprietary alternative is the better of two evils.

**Comment by douglascamata** [comment]
Why? I can't be convinced by your choice if you don't present me arguments. Just the fact that you prefer open source over proprietary (but free) don't convince me.

**Comment by MaxLeiter** [comment]
I think I know a solution.

**Comment by haykuro** [comment]
I 2nd (3rd, 4th?) the IRC chat instead..

Haven't been able to access Slack either..

Plenty of feature-rich clients for IRC.

Check out:

- http://irccloud.com
- http://www.mirc.com/
- https://hexchat.github.io/
- http://limechat.net/mac/

**Comment by ckrmml** [comment]
@douglascamata I don't know what you are trying when loading http://avatar.playat.ch:5000, im also on mac os and it loads like a charm

**Comment by solderzzc** [comment]
IRC will expose all our users' info, including ours. So that's not good.
Please let our development team focus on the big thing first, any issue can be log in issue list, so we won't miss anything.
Let me close the related topics/MR at the time, will reopen when we have time.

**Comment by MaxLeiter** [comment]
They can use the web client; at least can the development team bother properly reviewing PRs and testing code instead? And closing an issue for later is a terrible idea; leave it open and ignore it, if you want, but you should still allow discussion and for people to see its still relevant.
