### ISSUE TITLE
Bot doesn't start when using start.sh

### ISSUE THREAD

**Issue by Phoenix2601** [PokemonGoF/PokemonGo-Bot#3182]
### Expected Behavior

Bot should start by running the start.sh 

### Actual Behavior

Bot gave the error "There's no ./configs/config.json file", so I edited the path in the start.sh to the correct config.json. Now the terminal shows this error:
**"/Users/k/PokemonGo-Bot/run.sh ; exit;
python: can't open file 'pokecli.py': [Errno 2] No such file or directory"**

Note: It's possible to start the bot using 
"$ cd PokemonGo-Bot
$ virtualenv .
$ source bin/activate
$ pip install -r requirements.txt
$ python pokecli.py"

### Steps to Reproduce

Installed everything as recommended and started the start bash

### Other Information
OS: Mac OSX
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: Python 2.7.12

**Comment by Dauth** [comment]
python: can't open file 'pokecli.py': [Errno 2] No such file or directory"

ensure you are on the same level in the directory as pokeclip.py  Then run the following command

python pokecli.py

**Comment by Phoenix2601** [comment]
When I'm in the directory of pokecli.py (just inside the PokemonGo-Bot folder) there is another error:

**Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions**

I can start the bot just by "cd PokemonGo-Bot","source bin/activate" and then "python pokecli.py". Is there a way to implement those steps into the start.sh?

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
