### ISSUE TITLE
Incubating eggs question

### ISSUE THREAD

**Issue by Ballermocha** [PokemonGoF/PokemonGo-Bot#3186]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior
I want to save my extra incubators on the 10km eggs. What do I need to do to avoid the bot spending my extra ones on the 2km and the 5km eggs?

### Other Information
OS: Mac

**Comment by Dauth** [comment]
leave issues in github for bugs in the script

**Comment by Ballermocha** [comment]
I still need to figure this out. If this is not a good place, where should be the place to ask this question?
