### ISSUE TITLE
how do i change locations

### ISSUE THREAD

**Issue by siahmerritt** [PokemonGoF/PokemonGo-Bot#3188]
so i have it set for new york central park how do i switch locations what do i put instead can i use lat and long?

**Comment by lhung** [comment]
Set your lat long in the `location` field in your config.json, and `location_cache = false`. It is in the wiki.
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files#advanced-configuration

**Comment by Baconnaise** [comment]
You add in the coordinates of the location you like from https://www.google.com/maps/ or http://www.latlong.net/ 

![here1](https://cloud.githubusercontent.com/assets/20616256/17502793/ef53a942-5db8-11e6-907f-57c34479aeda.JPG)
![here2](https://cloud.githubusercontent.com/assets/20616256/17502795/f0e90acc-5db8-11e6-893c-6666c4aa3b36.JPG)
