### ISSUE TITLE
Struggling to run bot after new version with new api

### ISSUE THREAD

**Issue by yehan77** [PokemonGoF/PokemonGo-Bot#3189]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior
bot to work

### Actual Behavior
Last login: Tue Aug  9 12:28:25 on ttys000
sooriay:~ sooriay$ cd '/Users/sooriay/PokemonGo-Bot/' && '/usr/local/bin/pythonw'  '/Users/sooriay/PokemonGo-Bot/pokecli.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/sooriay/PokemonGo-Bot/pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: cannot import name ServerSideRequestThrottlingException
sooriay:PokemonGo-Bot sooriay$ 

### Steps to Reproduce
I deleted my old bot and installed the new master 

### Other Information
OS: OSX
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by Baconnaise** [comment]
Did you run "pip install -r requirements.txt" ??

**Comment by yehan77** [comment]
yes i have
