### ISSUE TITLE
Pip install -r requirements.txt failed

### ISSUE THREAD

**Issue by smokeyrd** [PokemonGoF/PokemonGo-Bot#3192]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior
pip install -r requirements.txt completed successfully

### Actual Behavior
<img width="949" alt="a" src="https://cloud.githubusercontent.com/assets/2348179/17502664/b05f1268-5db7-11e6-8e1a-ffb09f9b09bf.png">

### Steps to Reproduce
Fresh install:
Python 2.7.x
pip
git
virtualenv
protobuf 3

### Other Information
OS: Debian Jesse 8.5
Git Commit: 
<img width="435" alt="b" src="https://cloud.githubusercontent.com/assets/2348179/17502740/63aefce8-5db8-11e6-807f-f721d4554c26.png">

Python Version: 2.7.9

It's been a really long day, I might be stupid but tried twice and had the same issue both times

**Comment by hklcf** [comment]
**fatal error: python.h no such file or directory**

**Comment by kittinan** [comment]
@smokeyrd try to install python-dev package

`sudo apt-get install python-dev`

**Comment by smokeyrd** [comment]
As usual, user error. Thanks much!
