### ISSUE TITLE
Steplimit: 100 ? bot need to reboot...

### ISSUE THREAD

**Issue by Zeper666** [PokemonGoF/PokemonGo-Bot#32]
Why a step limit ?

**Comment by harsh1412** [comment]
Its a radius from which it goes to every direction for 100 steps.
It needs a limit otherwise it will go in a direction forever and you will be in Atlantic ocean in about few hours xD

**Comment by Zeper666** [comment]
okay but why the bot is stuck at message error "Steplimit: 100"

he make the 100 step radius nice... but why did he make not again and again ?

(sorry for the bad english)
