### ISSUE TITLE
bot cant catch pokemon using item great pokeball, only item normal red white pokeball can catch

### ISSUE THREAD

**Issue by hazman87** [PokemonGoF/PokemonGo-Bot#3204]
why ya?
![untitled](https://cloud.githubusercontent.com/assets/20870986/17503508/f0be6974-5e22-11e6-8e58-79cc5ffeb424.jpg)

**Comment by hazman87** [comment]
even i changed inventory become below 200 also cant catch using item great pokeball.. if others pokeball can..

**Comment by orchid666** [comment]
Side question, how do you get such nice output ? :)

**Comment by fari-99** [comment]
@orchid666 wrong bot maybe? LOL.

**Comment by Shikari22** [comment]
I am having the same problem with my account

**Comment by hazman87** [comment]
@orchid666 you means?
