### ISSUE TITLE
Map config not working

### ISSUE THREAD

**Issue by my2ndLanguage** [PokemonGoF/PokemonGo-Bot#3207]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior
To update/snipe locations 

### Actual Behavior
Not sniping/updating, or any response/errors what so ever.

### Steps to Reproduce
Run map config
{
        "type": "MoveToMapPokemon",
        "config": {
          "address": "http://*lan address*:5000",
          "max_distance": 500,
          "min_time": 60,
          "prioritize_vips": true,
          "snipe": true,
          "update_map": true,
          "mode": "priority",
          "catch": {

### Other Information
OS: OSX El' Capitan
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by shivamkalra** [comment]
Upload your full config and tell me branch you're on. I used snipe feature. It is working on `dev` branch. Also what errors do you see?

**Comment by my2ndLanguage** [comment]
i was running dev before but i might have switched to master after the new API build. i just did a pull, is there a way to know which branch im using?

[current_config.txt](https://github.com/PokemonGoF/PokemonGo-Bot/files/408187/current_config.txt)

**Comment by shivamkalra** [comment]
@my2ndLanguage   Please remove your comment and attach as a file (for future as well).

**Comment by LeeRongWen** [comment]
Hi @shivamkalra where i can find the stable version ?

**Comment by fari-99** [comment]
@LeeRongWen use master branch.

**Comment by LeeRongWen** [comment]
@fari-99  thanks for your sugestion....

**Comment by my2ndLanguage** [comment]
[current_config.txt](https://github.com/PokemonGoF/PokemonGo-Bot/files/408221/current_config.txt)

**Comment by my2ndLanguage** [comment]
switched branch to dev and is now working! closing
