### ISSUE TITLE
Not a issue - Few questions.

### ISSUE THREAD

**Issue by keaza** [PokemonGoF/PokemonGo-Bot#3210]
didnt know where else to post this as i couldnt see the infomation; please bear in mind its 6am and i hate reading pages of text. 

Is this a Headless linux bot? 

how many XP a hour?

**Comment by JarodKY** [comment]
I can't answer the first one, but in regards to the XP hour it depends on where you have the bot running and what your configurations are. I currently get around 60k XP per hour in a fairly populated city.

**Comment by keaza** [comment]
i can confirm this is a headless linux bot (SWEEEET) and i saw in another issues that there could be a way to connect it with a pokemon go map? such as my one?

**Comment by JarodKY** [comment]
It's all on the wiki https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Google-Maps-API-(web-page)

**Comment by keaza** [comment]
my config file is going to be huge... this will be fun!
