### ISSUE TITLE
How I can speed up egg hatches? 

### ISSUE THREAD

**Issue by moonlight2521** [PokemonGoF/PokemonGo-Bot#3211]
I have run the bot for one hour and it only walk 1.6km which is pretty slow. can some one help me solve this problem? what setting do I have to change for faster speed.

**Comment by mrthrowaway** [comment]
Its named 'walk' in the config. Walking too fast may cause the distance to not be registered on your egg, so adjust until you find the speed thats right for you

**Comment by moonlight2521** [comment]
I have the setting at 4.16. do you know the best setting for "walk"?
@mrthrowaway

**Comment by keaza** [comment]
you are allowed to walk upto 15 km/h before it doesnt register

**Comment by moonlight2521** [comment]
ok thanks guys will try the speed between 4-15

**Comment by ReinyDays** [comment]
Are you sure the speed variable is in m/s?
for me:
speed '4' was agonisingly slow.
speed '16' wasn't much better, 1 m/s perhaps?
speed '100' flew from pokestop to pokestop, so the setting does sómething.
speed '35' (last test i did for now) was around 2 to 3 m/s
