### ISSUE TITLE
The trainer is always walking to next fort

### ISSUE THREAD

**Issue by shmily1140** [PokemonGoF/PokemonGo-Bot#3214]
I am not clear the algorithm of the new version, from the log I noticed the trainer is always walking from one fort to another one,  he does not catch too often, do not use other balls except normal balls.  
Anyone here has a good configuration to avoid this?  
I miss the old version as it only contains two mode:  farm and catch. it was really efficient.

**Comment by keaza** [comment]
the only thing i could suggest is maybe do what im about to do and link it up to a pokemon go map? Where it knows the location of pokemon and catches them

**Comment by iruy** [comment]
Same here... Just going from a pokestop to the other and keep walking without finding any pokemon. Last dev branch has something wrong

**Comment by skywalker878** [comment]
I have same issue

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
