### ISSUE TITLE
[Feature] Let bot follow calculated route

### ISSUE THREAD

**Issue by iruy** [PokemonGoF/PokemonGo-Bot#3218]
Would it be possible to let the bot follow a route (e.g. like if it was calculated by google maps) instead of going directly from a PokeStop to the other passing through buildings? This way could maybe prevent bot from circles and weird path (like seen in the web page)

**Comment by Dauth** [comment]
there is already an inbuilt feature called FollowPath.

**Comment by Raiven66** [comment]
@Dauth for that you would have to set explicit waypoints for the roads manually
what the OP probably meant would be for the bot to walk from point A to point B not in a straight line but following actual roads on the map to simulate human behavior (=not run straight through buildings) better.

**Comment by Dauth** [comment]
@Raiven66 yes which is why if he wants it to happen he need to plan a route manually using only roads

**Comment by iruy** [comment]
The bot should go around by himself, following streets, wether I set FollowPath or FollowSpiral or FollowCluster...

**Comment by fari-99** [comment]
@iruy you want that? it's like @Dauth write, the feature is there, but if you have time and effort to built it.

**Comment by iruy** [comment]
Since bot should speed things up, this would be quite boring to set up, like putting hundreds of lat&lng together. But this was just a suggestion, because I always see weird path in my Web bot and usually it doesn't go that far away from the start location...unless I set longs `FollowPath`
