### ISSUE TITLE
MONITOR MY POKEMONBOT VIA WEB?

### ISSUE THREAD

**Issue by ponytails** [PokemonGoF/PokemonGo-Bot#3219]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior
see it walks web based?

### Actual Behavior
see it walks web based?

### Steps to Reproduce
normal

### Other Information
OS:  ubuntu
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by Dauth** [comment]
read the wiki. don't expect to be spoonfed even if you type in CAPS

**Comment by ponytails** [comment]
@Dauth  sorry for the caps... but i get this 404 not found 


404 Not Found
nginx/1.6.2 (Ubuntu)

**Comment by Didlid** [comment]
did you do Python -m SimpleHTTPServer 8000 in the web folder?

**Comment by ponytails** [comment]
@Didlid  that phyton command is just for windows

i use ubuntu.. i get 

/PokemonGo-Bot/web/index.html" is not found (2: No such file or directory)

**Comment by nburn42** [comment]
You need to dig a little deeper.

- Run this in the mian directory.

```
git submodule init
git submodule update
```

- Then get a google maps key
- Then setup your config file in web/config
- then start a webserver in the web directory

The web server works really well

**Comment by ponytails** [comment]
>  Run this in the mian directory
> git submodule init
> git submodule update
inside pokemong-bot folder = done..

nothing happens

root@oldtimes:~# cd PokemonGo-Bot
root@oldtimes:~/PokemonGo-Bot# git submodule init
root@oldtimes:~/PokemonGo-Bot# git submodule update
root@oldtimes:~/PokemonGo-Bot#

**Comment by nburn42** [comment]
The web folder is a separate git pointing to a separate github page.
Sub module init makes sure that the web folder git stuff has been downloaded.

**Comment by ponytails** [comment]
like this ?

root@oldtimes:~/PokemonGo-Bot# cd web
root@oldtimes:~/PokemonGo-Bot/web# git submodule init
root@oldtimes:~/PokemonGo-Bot/web# git submodule update
root@oldtimes:~/PokemonGo-Bot/web# git submodule init
root@oldtimes:~/PokemonGo-Bot/web# git submodule update
root@oldtimes:~/PokemonGo-Bot/web#

**Comment by nburn42** [comment]
do you have stuff in the web folder now?
if so then it worked or you had already run it as some part of the install in the past.

**Comment by ponytails** [comment]
hi,

i have files on web folder its inside PokemonGO-bot /web

**Comment by nburn42** [comment]
have you done the rest of the stuff?

Read the README file?
Setup you config in web/config?
Started the webserver in the web directory?

**Comment by ponytails** [comment]
hello.

yes i did.. when i access the web... via http/nginx
i get this error 
"/PokemonGo-Bot/web/index.html" is not found (2: No such file or directory),

**Comment by nburn42** [comment]
Is the file there?
Are you stating your webserver while in the web directory,
using the command in web/README?

**Comment by RedViper9** [comment]
Please redirect this discussion to the slack discussion boards.
