### ISSUE TITLE
[NotAnIssue] Dev Branch confirmed working on Raspberry Pi2 B!

### ISSUE THREAD

**Issue by pancakeykakes** [PokemonGoF/PokemonGo-Bot#3225]
CONFIRMED WORKING (EDIT: LASTEST dev branch as of time of writing-- not tested with master) ON RASPBERRY PI 2B RUNNING UBUNTU LINUX 16.04LTS (GNU/Linux 4.4.0-1009-raspi2 ARMV7l)

Not sure if this had been attempted already but I figured if no one has done it yet it would be good news for some folks.
Apologies in advance for sticking this here-- I'm sure there's a better place.

You can get up and running by following the same instructions as normal Ubuntu users, with only having to add 2 extra steps:

The following should be done before starting to follow the instructions listed for Ubuntu users:
  
    $ apt-get install build-essential
    $ apt-get install python-dev

Installing python-dev as described above MUST be done before attempting to run 

    $ pip install -requirements.txt 

as instructed in the normal install instructions on the PoGoBot github.

numpy will take FOREVER to install/compile, but the Pi2 does have enough RAM available to make it happen. Took about 15-20 minutes for me, but it succeeded.

![clipboard01](https://cloud.githubusercontent.com/assets/14805330/17507543/29cfd404-5dde-11e6-9140-45c00ab1d374.png)

**Comment by Philipp59** [comment]
nice work !
is there a difference to raspbian?

**Comment by iruy** [comment]
I'm trying to put it on Pine64. I will let you know

**Comment by ErrorFlexXx** [comment]
Just for info: I'm have the bot working, too on a PandaBoard (another arm SoC 1Ghz 1GB Ram). My numpy compilation took very long time, too. Seems to be normal since its a big project. Regards

**Comment by scarfield** [comment]
I've been running it on Rpi2 since day one with RaspbianOS. (debian/jesse). Yes numpy takes frikkin' forever, but it runs fine :)

**Comment by pancakeykakes** [comment]
@scarfield Yeah, even though I dev'd a project on Wheezy (TriPi), I honestly do not like the Raspbian OS. So I'm glad I found a use for my Pi again, because it was just collecting dust for a few months there.

**Comment by Philipp59** [comment]
so i got it running on rp3 but 2 things are really strange;
1.) I need source bin/activate without it does not run while on the mac there were no difference
2) xp/h dropped from 60 to 10 k -.- same config 
iam using ssh to start the bot and boot to cli not in the gui . any help ?

**Comment by pancakeykakes** [comment]
@Philipp59 Well, I don't have a Pi3, just a Pi2. However, are you using raspbian, or Ubuntu 16.04 LTS?

**Comment by Philipp59** [comment]
@pancakeykakes iam using raspbian 

what are your xp/h results Do you have some tweaks ? 

Its really word the difference from 60k/h to 10-15k/h  : S

iam using a 2.5 A power supply and a fast sd card don't know why there is such a huge difference

**Comment by pancakeykakes** [comment]
@Philipp59 Yeah see I don't like Raspbian for a lot of reasons. I couldn't even begin to help you troubleshoot the bot's performance on a Raspbian install. I dev'd TriPi for Raspbian, but that was all in bash anyway so I still don't know enough about it to troubleshoot extensively.

I do believe I saw a version of Ubuntu 16.04 LTS that was ported for the Pi3 on the same website I found my Pi2 version. Although it's unofficial, it's apparently stable enough for them to mention-- I would recommend you give that a try, set up the bot, and see what happens.

My bot isn't really geared towards maximizing XP. It is more about farming resources: Keep only if IV levels are .85+, and even then only if it's A or S tier, and I actually like said Pokemon. Otherwise, it's a catch & release-style candy, item, and egg hatching farm. If I want a huge XP boost, I modify it to keep all Pidgeys, Weedle, and Rattata, and once I have enough I have another bot "install" on the Pi where the ONLY thing it will do is pop and egg and evolve until it's ears bleed.

**Comment by Philipp59** [comment]
@pancakeykakes thx for the tip with ubuntu I will try it.
Iam also not an xp freak but iam just wondering why there is such a huge gap between a mac book air and a pi3 .
But in general maybe you can answer me that question. When I start the bot via ssh and close the ssh connection is it still running ? I can't check it tried it with vnc but the ssh terminal is not visual to that

**Comment by pancakeykakes** [comment]
Overclocking might help if you're on Raspbian, but isn't necessary when using the Ubuntu LTS.
If you're using ssh, what you should do before actually running the bot for the first time is run 

  screen

then start trying to run the bot

  cd PokemonGo-Bot
  source bin/activate
  ./run.sh


At that point, you'll be able to leave the ssh client if you want and the bot will still run.
When you want to check up on it, connect with your SSH client and then do 

  screen -raAd

and it will show you the outputting bot at it's current state (though it won't let you view the ENTIRE history).

**Comment by Philipp59** [comment]
thx with the screen works pretty good, my result are so far, that its not the hardware which result in the low xp/rate i overclocked the SD card by 100% -> no better result, overclock CPU/RAM -> no better result. I think its just the kernel. 

@pancakeykakes do you use Ubuntu server or desktop ? In theory server kernel must be better for low latency, right ?

**Comment by ErrorFlexXx** [comment]
I don't think that bots performance isn't as good as on an x86 or amd64 computer. You can look with tools like htop if the ressources are the culprit.
Are you sure that the configuration for the arm bot is the same as the one on OSX ?
I recognize approx. 10-20k EXP per hour on arm and on amd64 computers..
Or maybe they changed monsters spawning rates ?

**Comment by pancakeykakes** [comment]
@Philipp59 It's the server one, mate.

**Comment by Philipp59** [comment]
@ErrorFlexXx yeah its the same config as on the mac book , im running the pi now overclocked sd (100hz), cpu @1350 and ram @ 550 temperature is locked at 42 and its not the cpu load the average is between 8 and 18% and with htop i see peaks up to 80% for 1sec  iam now getting 18k/h. But i noticed that with the Pi i can run more then 2 bots. with the mac i ran into ip softban pretty quick with 3+ ... iam monitoring that seems pretty interesting

**Comment by pancakeykakes** [comment]
@Phillip59 The Linux LTS had SSH enabled by default, and on Raspbian it's installed but you may have to edit Raspi.cfg or whatever it is to enable it.

**Comment by pancakeykakes** [comment]
Honestly on the LTS I am not having to over clock at all and could probably run two bots at once if I wanted to bother spoofing the ip of one instance but meh.

**Comment by Philipp59** [comment]
patched (read compiled)  from 4.4 stable to 4.8 and rebuilt it with 1000 hz and low latency .
 
`Linux raspberrypi 4.8.0-rc1-v7+ #2 SMP PREEMPT Fri Aug 12 17:18:53 CEST 2016 armv7l GNU/Linux`
now this need some testing I will report, 
@pancakeykakes unfortunely ubuntu mate needs a manual installation after the first boot so i can't activate ssh without that : (

**Comment by pancakeykakes** [comment]
I'm not referring to Ubuntu mate.
I'm referring to this:

https://wiki.ubuntu.com/ARM/RaspberryPi

The 16.04 Ubuntu LTS for Pi2 is what I have and is what has SSH already turned on, because it's a server platform that doesn't include a GUI environment by default.

**Comment by k4n30** [comment]
If you feel this is relevant to add to the documentation, please make a pull request to include the steps to set this up
