### ISSUE TITLE
Task using pokesnipers.com API

### ISSUE THREAD

**Issue by Arcasss** [PokemonGoF/PokemonGo-Bot#3226]
### Expected Behavior
Task similar to MoveToMapPokemon. Bot would move to locations obtained from http://pokesnipers.com/api/v1/pokemon.json

### Actual Behavior
N/A

### Steps to Reproduce
N/A

### Other Information
OS: N/A
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here) N/A
Python Version: (run 'python -V' and paste it here) N/A

**Comment by keaza** [comment]
you can always ask someone kindly to host you a map?

**Comment by keaza** [comment]
or even better pay $5 for a digital ocean and run the bot and map on there?

**Comment by Philipp59** [comment]
its not needed ?
You can do it at your own very easy
you can search manually in the localhost map and built an auto script  which paste the data from a source in the map....
but anyway did sniping work ?
because of #3148 ? can someone confirm ?

**Comment by Arcasss** [comment]
Map repo was shutdown :(

**Comment by keaza** [comment]
was it? 

https://github.com/PokemonGoMap/PokemonGo-Map

**Comment by keaza** [comment]
i am currently running it.

**Comment by Arcasss** [comment]
Oh, what I was reading, somewhere here on this hub, I found https://github.com/AHAAAAAAA/PokemonGo-Map, which is shutdown.

I'll try yours, but anyway, using pokesnipers.com API would be nice. You wouldn't need to run another bot for scanning.

**Comment by fari-99** [comment]
@Arcasss actually there is in repo linked by @keaza. but i don't know how to use it. haha.

it's in config.ini in that repo, the config parameter is webhook.

**Comment by keaza** [comment]
if you need help to set it up i am more then happy to help you do so, if you have a linux box anyway. aha

**Comment by Arcasss** [comment]
@fari-99 yea, I checked @keaza 's repo, I'll make it work for sure (thanks keaza, I'll try by myself, should be pretty easy). 

Advantage of pokesnipers.com API
- not need to run another bot
- their bots are scanning bigger area
- data are shared, not necessary for every user to run his own bot
- data are already parsed in specific structure

**Comment by Pimentoso** [comment]
+1

**Comment by sffetlio** [comment]
Another good site: http://www.pokespawns.be/

**Comment by ksawerykarwacki** [comment]
Is there any good site for looking for specific pokemon not only from superb tier? I don't have tauros, pinsir, scyther or even butterfree which are not so special like snorlax or dragonite.

**Comment by Arcasss** [comment]
Please, dont hijack this thread.

**Comment by beranPro** [comment]
I have developed a cell worker for http://pokesnipers.com 
I'm currently making changes so it can be used as a plugin

**Comment by dogrocker** [comment]
Teleport to the pokemon got no ban ?

**Comment by beranPro** [comment]
Yes, works like a charm...

**Comment by Arcasss** [comment]
Can you let us know, when you finish your worker? Thanks

**Comment by beranPro** [comment]
Sure

**Comment by SpencerCarstens** [comment]
Excited to see this worker @beranPro .

**Comment by omeryagmurlu** [comment]
For anyone interested, here is the address of socket.io server that feeds http://www.pokespawns.be/.
Address: http://188.165.224.208
Port: 49001
Namespace: /pokes

Events:
- poke: emitted when a new pokemon is sent.
- helo: emitted on connection with an array of current pokemons

example event "poke": 
`{ name: 'Haunter', lat: '48.884766', lon: '2.370602', IV: '64' }`

example event "helo": 
`[ { name: 'Haunter',
    lat: '-22.899086',
    lon: '-43.209705',
    IV: '65' },
  { name: 'Aerodactyl',
    lat: '59.916478',
    lon: '10.773655',
    IV: '70' },
  { name: 'Haunter', lat: '41.881588', lon: '-87.629859', IV: '58' },
  { name: 'Snorlax', lat: '44.982666', lon: '-93.197206', IV: '76' },
  { name: 'Grimer', lat: '22.317712', lon: '114.171477', IV: '86' },
  { name: 'Haunter', lat: '48.884766', lon: '2.370602', IV: '64' },
  { name: 'Vileplume',
    lat: '(94%)\n-33.904696',
    lon: '151.23406',
    IV: null },
  { name: 'Vileplume',
    lat: '(94%)\n\n-33.904696',
    lon: '151.23406',
    IV: null },
  { name: 'Vileplume',
    lat: '-33.904696',
    lon: '151.23406',
    IV: '94' },
  { name: 'Snorlax', lat: '-3.273399', lon: '102.924801', IV: null },
  { name: 'Dratini',
    lat: '(100%)\n40.720741',
    lon: '-74.012707',
    IV: null },
  { name: 'Rapidash',
    lat: '40.737856',
    lon: '-74.001596',
    IV: null },
  { name: 'Pikachu',
    lat: '-33.892256',
    lon: '151.235426',
    IV: '29' },
  { name: 'Ninetales',
    lat: '-34.569054',
    lon: '-58.426208',
    IV: null },
  { name: 'Dratini',
    lat: '40.720741',
    lon: '-74.012707',
    IV: '100' },
  { name: 'Nidoking', lat: '47.909767', lon: '7.208761', IV: null },
  { name: 'Aerodactyl',
    lat: '19.445863',
    lon: '-99.161226',
    IV: null },
  { name: 'Chansey', lat: '45.453618', lon: '9.200219', IV: null },
  { name: 'Dragonite',
    lat: '33.969183',
    lon: '-84.497022',
    IV: null },
  { name: 'Magneton', lat: '40.732569', lon: '-73.96055', IV: null },
  { name: 'Lapras',
    lat: '(96%)\n52.516735',
    lon: '13.420694',
    IV: null },
  { name: 'Ivysaur', lat: '40.748117', lon: '-74.00481', IV: null },
  { name: 'Magmar', lat: '40.71905', lon: '-73.993149', IV: null },
  { name: 'Dratini',
    lat: '37.806955',
    lon: '-122.423588',
    IV: '100' },
  { name: 'Lapras', lat: '52.516735', lon: '13.420694', IV: '96' },
  { name: 'Snorlax', lat: '51.029151', lon: '7.660676', IV: null },
  { name: 'Dragonair',
    lat: '(100%)\n37.806955',
    lon: '-122.423588',
    IV: null },
  { name: 'Rapidash',
    lat: '(91%)\n34.037369',
    lon: '-118.204917',
    IV: null },
  { name: 'Wartortle',
    lat: '40.645315',
    lon: '-74.019867',
    IV: null },
  { name: 'Rapidash',
    lat: '34.037369',
    lon: '-118.204917',
    IV: '91' },
  { name: 'Aerodactyl',
    lat: '-37.8111963014523',
    lon: '144.954601552513',
    IV: '96' },
  { name: 'Dragonair',
    lat: '(100%)\n\n37.806955',
    lon: '-122.423588',
    IV: null },
  { name: 'Dratini',
    lat: '(98%)\n\n38.899486',
    lon: '-77.067374',
    IV: null },
  { name: 'Dragonair',
    lat: '37.806955',
    lon: '-122.423588\n\nIV:100',
    IV: null },
  { name: 'Dratini', lat: '38.899486', lon: '-77.067374', IV: '98' },
  { name: 'Ninetales',
    lat: '19.416939',
    lon: '-99.188738',
    IV: '41' },
  { name: 'Dragonite',
    lat: '40.713487',
    lon: '-74.017665',
    IV: null },
  { name: 'Dragonite',
    lat: '40.394362',
    lon: '-3.625937',
    IV: null },
  { name: 'Dragonair',
    lat: '40.713487',
    lon: '-74.017665',
    IV: null },
  { name: 'Lickitung', lat: '41.571036', lon: '1.99905', IV: null },
  { name: 'Arcanine', lat: '-33.444082', lon: '-70.655928', IV: 53 },
  { name: 'Lapras', lat: 'set)\n51.5056', lon: '-0.023687', IV: 97 },
  { name: 'Lapras',
    lat: '(97%)\n51.5056',
    lon: '-0.023687',
    IV: null },
  { name: 'Lapras',
    lat: '(97%)\n\n51.5056',
    lon: '-0.023687',
    IV: null },
  { name: 'Lapras', lat: '51.5056', lon: '-0.023687', IV: 97 },
  { name: 'Vaporeon',
    lat: '(82%)\n40.718926',
    lon: '-74.012982',
    IV: null },
  { name: 'Dragonite',
    lat: '59.907571',
    lon: '10.7420616',
    IV: null },
  { name: 'Charmeleon',
    lat: '(23%)\n-33.879369',
    lon: '151.206738',
    IV: null },
  { name: 'Vaporeon', lat: '40.718926', lon: '-74.012982', IV: 82 },
  { name: 'Gengar',
    lat: '(56%)\n51.870033',
    lon: '4.602433',
    IV: null } ]`

**Comment by SpencerCarstens** [comment]
@omeryagmurlu Have you linked this into the bot yet?

**Comment by omeryagmurlu** [comment]
@SpencerCarstens nope, I hate coding in python, posted it here so others maybe make a worker out of this

**Comment by omeryagmurlu** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3278

**Comment by SpencerCarstens** [comment]
> Running a PokemonGo-Map for snipes gives you bans even quicker...

Huh?

**Comment by jannickv** [comment]
More requests to the api for your ip...

**Comment by Arcasss** [comment]
@beranPro how is your progress? :)

**Comment by tnlin** [comment]
Take PogoLocationFeeder as example
it servers for Necrobot and integrates lots of location API
I'm trying build a python version of PogoLocationFeeder...
https://github.com/5andr0/PogoLocationFeeder/tree/master/PogoLocationFeeder/Repository

**Comment by k4n30** [comment]
#3666 #3355 #3278

**Comment by k4n30** [comment]
Going to close this issue and let it be tracked under #3672 as it is worded better to included all sniping focused sites
