### ISSUE TITLE
The bot caught few pokemon

### ISSUE THREAD

**Issue by Motazlubbad** [PokemonGoF/PokemonGo-Bot#3229]
Hi all 
my bot  caught few pokemon "about 2 every hour" , and the bot in area with 2 lured pokestop at minimum .

I used the default setting for config.

any help ?

**Comment by hklcf** [comment]
which default config file you use?

**Comment by Motazlubbad** [comment]
config.json.example

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
