### ISSUE TITLE
[Feature] Configurable log levels

### ISSUE THREAD

**Issue by nfrankel** [PokemonGoF/PokemonGo-Bot#3230]
Hi guys,

First, kudos to all for this great piece of software.

I've a small feature request. Right now, my log is flooded with `[keep_best_release] Keeping best` and `[inventory_full] Not moving to any forts as there aren't enough space` messages. Nothing serious, but this is not super interesting. I was wondering if it was possible to make a change so as to configure log levels for each worker (as I understand) separately.

**Comment by RedViper9** [comment]
I believe this is will be addressed as part of #3532
