### ISSUE TITLE
invite for Slack chat doesn't work

### ISSUE THREAD

**Issue by Brown-amazingness** [PokemonGoF/PokemonGo-Bot#324]
### Expected Behavior
heroku app should send me an invite link to my email

### Actual Behavior

nothing happens
### Steps to Reproduce
go to the slack.herokuapp.com and put an email. nothing will happen

**Comment by MaxLeiter** [comment]
Might want to comment on #318

**Comment by douglascamata** [comment]
@Brown-amazingness we're being rate limited because too many ppl asked for invites. We got more famous than we could handle. Tomorrow more invite are going to be available.

**Comment by solderzzc** [comment]
need close this issue.
