### ISSUE TITLE
Walk speed that won't get you acc reported

### ISSUE THREAD

**Issue by Lapito** [PokemonGoF/PokemonGo-Bot#3243]
Hello. So I've been using the bot since yesterday, but it seems like my account was reported by niantic and now I can't spin poke stops or catch any Pokemon. So I'd like to know a safe walk speed to prevent this from happening.

**Comment by Lunik** [comment]
8 is fine

**Comment by hklcf** [comment]
how many bot are you running?

**Comment by Lapito** [comment]
@hklcf I was running only one bot. But when I logged into the app those things happened.

**Comment by iruy** [comment]
For eggs the max walk speed is 14. The bot can handle softban when detected.

**Comment by hklcf** [comment]
slow down your walk speed

**Comment by Lapito** [comment]
@hklcf Is the account ever coming back?

**Comment by hklcf** [comment]
@Lapito sure, just wait a few minutes

**Comment by Lapito** [comment]
@hklcf @iruy @Lunik Thanks

**Comment by Lapito** [comment]
@hklcf Do you recommend 8 too?

**Comment by Waliers** [comment]
_I was running only one bot. But when I logged into the app those things happened._

If the bot was running fine and you get the soft ban while logging into the app...

- Did you disconnect the bot before you logged into the app? Can Bot and App at the same time.
- Is the bot in the same location as you? If the bot is in Central Park and you stop the bot and logged in the App while in Mexico you get a soft ban... if the Bot location and your real one are far apart wait a few hours before loggin in.

To cancel your softban spin the Pokestop 40-50 times. (Click, Spin, Close, Click, Spin Close, repeat until you get rewards)

**Comment by hklcf** [comment]
or just wait a few minutes/hours

**Comment by hklcf** [comment]
im using the default setting 4.16

**Comment by Lapito** [comment]
I'll try everything out, thanks. Will report back if it worked.

**Comment by twistedpro** [comment]
If your bot location is much further than you real location  on the pokemon go app, softban would occur... you could change the location of your bot to your current location... and the bot will take care of the soft ban, exit bot.. load app... should work?

**Comment by Lapito** [comment]
It worked guys! Thank you very much!
