### ISSUE TITLE
[Feature]How can I config to only use poke ball

### ISSUE THREAD

**Issue by HunterGeo** [PokemonGoF/PokemonGo-Bot#3246]
I found that sometimes the bot will use great ball to catch the pokemon instead of póke ball, but i would like to config the bot only use poke ball to catch them if it is not the vip pokemon.

Any thing I could do or it will be added in the future?

**Comment by iruy** [comment]
In `RecycleItems` task, set `"keep": 0` for other balls

**Comment by hklcf** [comment]
@iruy i think @HunterGeo want to keep the great ball and other

**Comment by HunterGeo** [comment]
@iruy 
Yup I want to keep other balls and only use poókeball.
Thanks @hklcf

**Comment by hklcf** [comment]
this is a feature request :laughing:

**Comment by iruy** [comment]
Ops sorry, then just add all pokemon to VIPS. The bot will use the best ball and berry

**Comment by iruy** [comment]
Ops, sorry.. I misread :)

**Comment by HunterGeo** [comment]
Ok. Thanks dude.
I just think whether there is a way to set this because u guys know the config file... is really complicated.
I guess I will change it to Feature .

**Comment by RedViper9** [comment]
Have you tried removing the pokemon listed under VIP? This should largely resolve your issue.

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680
