### ISSUE TITLE
Reducing API Requests = Improving xp/hr

### ISSUE THREAD

**Issue by TheSavior** [PokemonGoF/PokemonGo-Bot#3247]
Reducing unnecessary api requests is going to have the largest impact on improving xp/hr. I added logs for what API requests we are making. Here is a large amount of output: http://pastebin.com/4dGVasXa

Does anyone see anything that looks like we should be able to remove and speed up?

@aeckert, it seems like inventory management is a big piece we can improve here.

@douglascamata, any additional thoughts?

**Comment by eggins** [comment]
:+1:

**Comment by BriceSD** [comment]
@TheSavior What about the gym details we're requesting en though the bot doesn't interact with any of them ?
If it's for getting fort details there is an other api call to make
https://github.com/tejado/pgoapi/wiki/get_gym_details
https://github.com/tejado/pgoapi/wiki/fort_details

**Comment by TheSavior** [comment]
@BriceSD We have removed the calls to the gym_details in this PR (after I created the pastebin): https://github.com/PokemonGoF/PokemonGo-Bot/pull/3245

**Comment by BriceSD** [comment]
Concerning the inventory management I think that every task should track what it consumes/loot. The same way he's already doing it for candies.
This way we could init the iventory at the start of the bot and not havig to call the api again. Might not be very human-like though, I guess that the PokemongGo app is calling the api pretty often.

**Comment by douglascamata** [comment]
IMHO, tasks should not "track what it consumes/loot". We need a wrapper to API responses. Tasks shouldn't be aloud to access the raw api object. Instead they should only be allowed to access high-level objects, like a Pokemon object, with proper methods for releasing, for example, that will automatically update the inventory cache when called. This way it's impossible to have an outdated inventory cache and we get simpler tasks as bonus.

**Comment by g2384** [comment]
Please check my changes, I think I reduced several unnecessary API calls. Also, more changes are needed in `catch_visible_pokemon.py` and `catch_lured_pokemon.py` to slightly speed up the bot.

[pokemon_catch_worker_改.py](https://gist.github.com/g2384/624c33f62e75edb15cd629227458f005)

the idea is: remember what has been ignored, don't check it's info next time

**Comment by TheSavior** [comment]
@douglascamata That sounds great to me. That would keep us from getting into a situation where a task doesn't update the inventory correctly and messes everything up.

**Comment by BriceSD** [comment]
@douglascamata Like having a class PokemonAPI containing every (and only) api call related to pokemons ?

Hiding the inventory update from tasks seems great. The additional abstraction should also protect our bot from changes of the api too, which is always good to take imo.

**Comment by douglascamata** [comment]
@BriceSD yup, a bit like that.
