### ISSUE TITLE
Modified the map

### ISSUE THREAD

**Issue by nanoymaster** [PokemonGoF/PokemonGo-Bot#325]
not really an issue, but didn't know where to put it.
so I modified the map a bit, it now has console output overlay and line displaying where walking to (which doesn't go so you can view history)

wish we had a file containing stats etc to put on overlay.

would love peoples thoughts?

![map_mod](https://cloud.githubusercontent.com/assets/1678085/17074464/5eeecae6-5073-11e6-87be-eee0df1e4e15.png)

**Comment by solderzzc** [comment]
have you checked out the dev branch yet? PRs are welcome.

**Comment by douglascamata** [comment]
I saw that anarchy symbol btw, you punk!

**Comment by nanoymaster** [comment]
@solderzzc it's not really a part of the bot since requires php

here is the code: 
[pmon.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/379414/pmon.zip)

yes I know it is terrible! don't judge, made at midnight in about 20 mins.
My webserver is chrooted so had to run
pokecli.py [options] |& tee /var/www/html/log.txt
and in another tab:
while true; do cp location.json /var/www/html/location.json; sleep 2;done

any questions feel free to ask...
I hope this helps someone

**Comment by nanoymaster** [comment]
@douglascamata lol I was thinking pentagram :p
heres how I found it in the morning.. dead:
![bot-died](https://cloud.githubusercontent.com/assets/1678085/17076612/c2f04534-50ae-11e6-8ebd-801e877006f3.png)

**Comment by nanoymaster** [comment]
update... might end up creating a spin-off github if anyone is interested... 
added player current stats under log (updated every 10 mins or so)

![map_mod_2](https://cloud.githubusercontent.com/assets/1678085/17077990/7dad7430-50de-11e6-8046-240f0fb78e09.png)

**Comment by surfaace** [comment]
web development is now done at https://github.com/OpenPoGo/OpenPoGoWeb for example
