### ISSUE TITLE
localhost:5000/loc (also raw_data) returns 404 (OpenPoGoWeb)

### ISSUE THREAD

**Issue by joaodragao** [PokemonGoF/PokemonGo-Bot#3250]
Sorry to open this issue. But I had tried everything and it doesn't work.

Can anyone guide me to make `move_to_map_pokemon` work?

* I downloaded [OpenPoGoWeb](https://github.com/OpenPoGo/OpenPoGoWeb) and extracted it to `/PokemonGo-Bot/web`
* `cd /PokemonGo-Bot/web`
* `python -m SimpleHTTPServer 5000`

The `localhost:5000/` is ok. There is a map there.

But I always get:

`127.0.0.1 - - [09/Aug/2016 10:52:30] code 404, message File not found`

and

`[move_to_map_pokemon_fail] Failure! Map location data was not valid`

That happens because `localhost:5000/loc` and `localhost:5000/raw_data` return 404.

This is the `config.json`:

```
{
        "type": "MoveToMapPokemon",
        "config": {
          "address": "http://localhost:5000",
          "max_distance": 500,
          "min_time": 60,
          "min_ball": 50,
          "prioritize_vips": true,
          "snipe": false,
          "update_map": true,
          "mode": "priority",
```

and `userdata.js`:

```
var userInfo = {
	users: ["xxxxx"],
	userZoom: true,
	zoom: 16,
	userFollow: true,
	gMapsAPIKey: "xxxxxxxxxx...",
	botPath: true,
	actionsEnabled: false
};
```

**Comment by mizhgan** [comment]
you don`t need OpenPoGoWeb, you need https://github.com/PokemonGoMap/PokemonGo-Map

**Comment by ArcusD** [comment]
Had the same issue the first time i ran the HTTP

Are the following 3 files in your /web/ folder:
- catchable-username@gmail.com.json
- location-username@gmail.com.json
- inventory-username@gmail.com.json

If one of the files isn't in the /web/ folder, create an empty .json file using this naming.

**Comment by joaodragao** [comment]
So, this [wik (Google-Maps-API-(web-page))](https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Google-Maps-API-(web-page))i is out-of-date? And it's not compatible with OpenPoGoWeb anymore?

**Comment by joaodragao** [comment]
@ArcusD I have all the 3 JSON files in `/web/` directory. But OpenPoGoWeb seems to do nothing with it.

**Comment by mizhgan** [comment]
you don`t need OpenPoGoWeb, you need https://github.com/PokemonGoMap/PokemonGo-Map
OpenPoGoWeb is used to visualize bots moving only

**Comment by joaodragao** [comment]
@ArcusD I was confused with my username. I corrected it and it works. Thank you! But
`[move_to_map_pokemon_fail] Failure! Map location data was not valid` is still there.

**Comment by joaodragao** [comment]
@mizhgan I got it. Thank you. But may you tell me what is the advantage of using PokemonGo-Map? Can I ask my player to move to exact location that Pokemon pop up on the PokemonGo-Map?

**Comment by mizhgan** [comment]
Exactly, bot goes to position of the pokemon find by map. This is what map
worker do.

2016-08-09 13:33 GMT+03:00 joaodragao <notifications@github.com>:

**Comment by joaodragao** [comment]
@mizhgan Really?! Thank you very much!
