### ISSUE TITLE
Release Configuration Bug?

### ISSUE THREAD

**Issue by seratkurtulus** [PokemonGoF/PokemonGo-Bot#3251]
`Releasing Magikarp (CP 171/IV 0.91) based on rule: CP < 170 OR IV < 0.9`

I was wondering why am i not getting any magikarps lately.

**Comment by h3k1ru** [comment]
I think you should use 90 instead of 0.9, because I'm using this:

    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 95, "logic": "or"},
      "any": {"keep_best_iv": 2}
    }, 
and it's work fine.

**Comment by k4n30** [comment]
Can't assist without information asked for in issue template
