### ISSUE TITLE
Listen to capture events?

### ISSUE THREAD

**Issue by shivamkalra** [PokemonGoF/PokemonGo-Bot#3252]
I would like to subscribe to capture events along with details of the pokemon being captured? Is it possible to hook-up my code somewhere to do so? Possibly without changing the actual code and instead subscribing to its socket i/o?

**Comment by jrjhealey** [comment]
You could just redirect the bot STDOUT and do some simple grepping for strings in the capture lines?

**Comment by shivamkalra** [comment]
Would be much better to capture this

https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/cell_workers/pokemon_catch_worker.py#L66

But I'm not sure how this event catching work? Can I've an external program catching all these emitted events?
