### ISSUE TITLE
Server throttling if use_lucky_egg enabled

### ISSUE THREAD

**Issue by V-E-O** [PokemonGoF/PokemonGo-Bot#3253]
After UseItemXpBoostResponse, server throttling exception raised.

> 2016-08-09 10:25:38,541 [pgoapi.rpc_api] [DEBUG] Parsing sub RPC responses...
> 2016-08-09 10:25:38,541 [pgoapi.rpc_api] [DEBUG] Parsing class: POGOProtos.Networking.Responses_pb2.UseItemXpBoostResponse
> 2016-08-09 10:25:39,296 [pgoapi.pgoapi] [INFO] Execution of RPC
> 2016-08-09 10:25:39,296 [pgoapi.rpc_api] [DEBUG] Generating main RPC request...
> 2016-08-09 10:25:39,296 [pgoapi.rpc_api] [DEBUG] Incremented RPC Request ID: 870635796429835162
> 2016-08-09 10:25:39,296 [pgoapi.rpc_api] [DEBUG] Generating sub RPC requests...
> 2016-08-09 10:25:39,297 [pgoapi.rpc_api] [DEBUG] Subrequest class: POGOProtos.Networking.Requests.Messages_pb2.UseItemXpBoostMessage
> 2016-08-09 10:25:39,297 [pgoapi.auth] [DEBUG] Session Ticket still valid for further 00:29:43 hours (1470738339298 < 1470740122789)
> 2016-08-09 10:25:39,297 [pgoapi.rpc_api] [DEBUG] Found Session Ticket - using this instead of oauth token
> 2016-08-09 10:25:39,298 [pgoapi.rpc_api] [DEBUG] Generated protobuf request: 
> status_code: 2
> request_id: 870635796429835162
> requests {
>   request_type: USE_ITEM_XP_BOOST
>   request_message: "\010\255\002"
> }
> unknown6 {
>   request_type: 6
>   unknown2 {
>     unknown1: "\026WV\3130\225w=\217\234\030=\302\211\341Y\316\372p\320[\316\273l\022#}%\316(\250\311\334O\220<z\351]E#\302\246\262\327$\211q\212t5;\322\2464/\260boe\033\213\350\241\245\004\372\013\260=-\307\244\314\005\246\002\252P\334\013\377Cx\222 \353*\nm\354\000\031K\n\310\316\204\264\310~c\312\207\223n#\016\357b\321?5\3334\341Qs\020[\213\023\211\346&\243r\364\367\"\214\354\350\310\036q\\\030\365d?\277+\273L`\351\010y<\321\255R\232n\260\252\245b\361\223%\260\301\245\000\360<\311V\354}\320C\341m\315\301\343\004\337\375\274\021\264\003\236OYx\352\027\036\306/#2\252\034\336\001\'\374\356[\303!\265\264\235\366\267]>f.\003\006pA\322\214\352OF\253;\246\234\366m\275\274\365_\353\327d\021\340\030\364\017\353\230\243\341\'k\233\352\220{4\252\267\206\374\314\252\\\352\022TOxc\215\352\275\204\306\314\031Um\206\313\307^\321\201d\234\367z\t\036"
>   }
> }
> latitude: 35.6359706506
> longitude: 139.884160881
> altitude: 8
> auth_ticket {
>   start: "P\242\007\007\315\010+\036f\r\034\343}\020\374\306\235\351\205\221?\022\252g.Y\216\266\272\366A+\334<\363\353\217\261\333\244Z\024n{K\376\343\304\002J\240\330A\345\351m\360\025L\010\341\267\313\352"
>   expire_timestamp_ms: 1470740122789
>   end: "T\020\216\005C\366\254\020%ZK\001\024\331\244\261"
> }
> unknown12: 989
> 
> 2016-08-09 10:25:39,299 [pgoapi.rpc_api] [DEBUG] Execution of RPC
> 2016-08-09 10:25:39,302 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTPS connection (1): pgorelease.nianticlabs.com
> 2016-08-09 10:25:39,418 [requests.packages.urllib3.connectionpool] [DEBUG] "POST /plfe/459/rpc HTTP/1.1" 200 None
> 2016-08-09 10:25:39,420 [pgoapi.rpc_api] [DEBUG] Parsing main RPC response...
> 2016-08-09 10:25:39,420 [pgoapi.rpc_api] [DEBUG] Protobuf structure of rpc response:
> status_code: 52
> request_id: 870635796429835162
> unknown6 {
>   response_type: 6
>   unknown2 {
>     unknown1: 1
>   }
> }
> returns: ""
> 
> 2016-08-09 10:25:39,429 [pgoapi.rpc_api] [DEBUG] Decode raw over protoc (protoc has to be in your PATH):
> 1: 52
> 2: 870635796429835162
> 6 {
>   1: 6
>   2 {
>     1: 1
>   }
> }
> 100: ""
> 
> 2016-08-09 10:25:39,430 [pgoapi.rpc_api] [DEBUG] Parsing sub RPC responses...
> 2016-08-09 10:25:39,430 [pgoapi.rpc_api] [DEBUG] Parsing class: POGOProtos.Networking.Responses_pb2.UseItemXpBoostResponse
> 2016-08-09 10:25:39,437 [PokemonGoBot] [INFO] [api_error] Server is throttling, reconnecting in 30 seconds

**Comment by marcosalles** [comment]
Same happened with me, but I had the bot start the Evo process, then break it, then start it again. That's how I was able to replicate the bug. Turning lucky egg off and waiting for the Evo to finish "fixed" it, next Evo was done cleanly because I did not interrupt it.

**Comment by jaharkema** [comment]
Correct. Setting `use_lucky_egg` to `true`, then starting, stopping and restarting the application gives a `Server is throttling` error. If you set `use_lucky_egg` to `false` (even though your lucky egg should still be working), the application will work again.

**Comment by k4n30** [comment]
@V-E-O is this still an issue?

**Comment by V-E-O** [comment]
@k4n30 I'm hit seriously by ban wave, let me check my new account.

**Comment by Jasperrr91** [comment]
@V-E-O have you checked?

**Comment by V-E-O** [comment]
I can not reproduced it by far, you can close it for now

**Comment by r3pek** [comment]
yes.... still an issue. just happened to me

**Comment by keugnu** [comment]
This happened to me today.
