### ISSUE TITLE
[Need Help] Config Issues

### ISSUE THREAD

**Issue by JaydenHamence** [PokemonGoF/PokemonGo-Bot#3258]
Config:
"tasks": [{
        "type": "HandleSoftBan"
    }, {
              "type": "CollectLevelUpReward"
              },
              {
              "type": "IncubateEggs",
              "config": {
              "longer_eggs_first": true
              }
              },
              {
              "type": "RecycleItems",
              "config": {
              "run_interval": 60,
              "item_filter": {
            "Pokeball":       { "keep" : 50 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 0 },
            "Hyper Potion":   { "keep" : 50 },
            "Max Potion":     { "keep" : 50 },
            "Revive":         { "keep" : 25 },
            "Razz Berry":     { "keep" : 50 },
            "Greatball":      { "keep" : 75 },
            "Ultraball":      { "keep" : 75 }      
              }
              },
              {
              "type": "EvolvePokemon",
              "config": {
              "evolve_all": "Pidgey,Rattata,Zubat,Weedle,Drowzee,Spearow,Venonat,Caterpie,Krabby,Paras,Jigglypuff,Sandshrew,Vulpix,Meowth,Psyduck,Mankey,Tentacool,Ponyta,Slowpoke,Magnemite,Doduo,Seel,Voltorb,Horsea,Goldeen,Staryu,Ekans",
              "first_evolve_by": "cp",
              "evolve_above_cp": 0,
              "evolve_above_iv": 0,
              "logic": "or",
              "evolve_speed": 1,
              "use_lucky_egg": false,
              "run_interval": 180
              }
              },
              {
              "type": "TransferPokemon",
              "config": {
              "run_interval": 180
              }
              },
              {
              "type": "MoveToFort",
              "config": {
              "lure_attraction": true,
              "lure_max_distance": 2000,
              "ignore_item_count": true
              }
              },
              {
              "type": "SpinFort",
              "config": {
              "ignore_item_count": true
              }
              },
              {
              "type": "CatchVisiblePokemon"
              },
              {
              "type": "CatchLuredPokemon"
              }
              },
    "map_object_cache_time": 5,
    "forts": {
        "avoid_circles": true,
        "max_circle_size": 500
    },
    "websocket_server": false,
    "walk": 80,
    "action_wait_min": 0,
    "action_wait_max": 1,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": false,
    "distance_unit": "m",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
        "any": {
            "always_catch": true
        }
    },
    "release": {
        "any": {
            "keep_best_iv": 1
        },
        "Moltres": {
            "keep_best_iv": 3
        },
        "Zapdos": {
            "keep_best_iv": 3
        },
        "Articuno": {
            "keep_best_iv": 3
        },
        "Mewtwo": {
            "keep_best_iv": 3
        },
        "Dragonite": {
            "keep_best_iv": 3
        },
        "Dratini": {
            "keep_best_iv": 3
        },
        "Venusuar": {
            "keep_best_iv": 3
        },
        "Ivysaur": {
            "keep_best_iv": 3
        },
        "Blastoise": {
            "keep_best_iv": 3
        },
        "Charizard": {
            "keep_best_iv": 3
        },
        "Charmeleon": {
            "keep_best_iv": 3
        },
        "Wartortle": {
            "keep_best_iv": 3
        },
        "Pikachu": {
            "keep_best_iv": 3
        },
        "Charmander": {
            "keep_best_iv": 3
        },
        "Bulbasaur": {
            "keep_best_iv": 3
        },
        "Squirtle": {
            "keep_best_iv": 3
        },
        "Magikarp": {
            "keep_best_iv": 3
        },
        "Eevee": {
            "keep_best_iv": 3
        },
        "Dragonair": {
            "keep_best_iv": 3
        },
        "Lapris": {
            "keep_best_iv": 3
        },
        "Snorlax": {
            "keep_best_iv": 3
        }
    },
    "vips": {
        "any": {
            "catch_above_cp": 1000,
            "catch_above_iv": 0.9,
            "logic": "or"
        },
        "Zapdos": {},
        "Moltres": {},
        "Articuno": {},
        "Mew": {}
    }
}

Errors:
2016-08-09 21:13:02,054 [       cli] [INFO] PokemonGO Bot v1.0
./configs/config.json:35:14: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 35, column 14, offset 1149
   |  Object started at line 19, column 14, offset 545
./configs/config.json:35:14: Error: Missing value for object property, expected ":"
   |  At line 35, column 14, offset 1149
   |  Object started at line 19, column 14, offset 545
./configs/config.json:54:14: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 54, column 14, offset 1896
   |  Object started at line 19, column 14, offset 545
./configs/config.json:54:14: Error: Missing value for object property, expected ":"
   |  At line 54, column 14, offset 1896
   |  Object started at line 19, column 14, offset 545
./configs/config.json:68:14: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 68, column 14, offset 2276
   |  Object started at line 19, column 14, offset 545
./configs/config.json:68:14: Error: Missing value for object property, expected ":"
   |  At line 68, column 14, offset 2276
   |  Object started at line 19, column 14, offset 545
./configs/config.json:75:27: Error: Can not decode value starting with character u':'
   |  At line 75, column 27, offset 2457
./configs/config.json:75:30: Info: Recovering parsing after character u','
   |  At line 75, column 30, offset 2460
./configs/config.json:75:30: Info: Recovering parsing after character u','
   |  At line 75, column 30, offset 2460
./configs/config.json:76:11: Error: Can not decode value starting with character u':'
   |  At line 76, column 11, offset 2473
./configs/config.json:76:13: Info: Recovering parsing after character u'{'
   |  At line 76, column 13, offset 2475
./configs/config.json:76:13: Info: Recovering parsing after character u'{'
   |  At line 76, column 13, offset 2475
./configs/config.json:76:13: Error: Values must be separated by a comma
   |  At line 76, column 13, offset 2475
   |  Array started at line 8, column 9, offset 272
./configs/config.json:80:22: Error: Can not decode value starting with character u':'
   |  At line 80, column 22, offset 2568
./configs/config.json:80:29: Info: Recovering parsing after character u','
   |  At line 80, column 29, offset 2575
./configs/config.json:80:29: Info: Recovering parsing after character u','
   |  At line 80, column 29, offset 2575
./configs/config.json:81:10: Error: Can not decode value starting with character u':'
   |  At line 81, column 10, offset 2587
./configs/config.json:81:14: Info: Recovering parsing after character u','
   |  At line 81, column 14, offset 2591
./configs/config.json:81:14: Info: Recovering parsing after character u','
   |  At line 81, column 14, offset 2591
./configs/config.json:82:21: Error: Can not decode value starting with character u':'
   |  At line 82, column 21, offset 2614
./configs/config.json:82:24: Info: Recovering parsing after character u','
   |  At line 82, column 24, offset 2617
./configs/config.json:82:24: Info: Recovering parsing after character u','
   |  At line 82, column 24, offset 2617
./configs/config.json:83:21: Error: Can not decode value starting with character u':'
   |  At line 83, column 21, offset 2640
./configs/config.json:83:24: Info: Recovering parsing after character u','
   |  At line 83, column 24, offset 2643
./configs/config.json:83:24: Info: Recovering parsing after character u','
   |  At line 83, column 24, offset 2643
./configs/config.json:84:11: Error: Can not decode value starting with character u':'
   |  At line 84, column 11, offset 2656
./configs/config.json:84:18: Info: Recovering parsing after character u','
   |  At line 84, column 18, offset 2663
./configs/config.json:84:18: Info: Recovering parsing after character u','
   |  At line 84, column 18, offset 2663
./configs/config.json:85:10: Error: Can not decode value starting with character u':'
   |  At line 85, column 10, offset 2675
./configs/config.json:85:17: Info: Recovering parsing after character u','
   |  At line 85, column 17, offset 2682
./configs/config.json:85:17: Info: Recovering parsing after character u','
   |  At line 85, column 17, offset 2682
./configs/config.json:86:19: Error: Can not decode value starting with character u':'
   |  At line 86, column 19, offset 2703
./configs/config.json:86:26: Info: Recovering parsing after character u','
   |  At line 86, column 26, offset 2710
./configs/config.json:86:26: Info: Recovering parsing after character u','
   |  At line 86, column 26, offset 2710
./configs/config.json:87:20: Error: Can not decode value starting with character u':'
   |  At line 87, column 20, offset 2732
./configs/config.json:87:27: Info: Recovering parsing after character u','
   |  At line 87, column 27, offset 2739
./configs/config.json:87:27: Info: Recovering parsing after character u','
   |  At line 87, column 27, offset 2739
./configs/config.json:88:19: Error: Can not decode value starting with character u':'
   |  At line 88, column 19, offset 2760
./configs/config.json:88:21: Info: Recovering parsing after character u'"'
   |  At line 88, column 21, offset 2762
./configs/config.json:88:21: Info: Recovering parsing after character u'"'
   |  At line 88, column 21, offset 2762
./configs/config.json:88:21: Error: Values must be separated by a comma
   |  At line 88, column 21, offset 2762
   |  Array started at line 8, column 9, offset 272
./configs/config.json:89:26: Error: Can not decode value starting with character u':'
   |  At line 89, column 26, offset 2793
./configs/config.json:89:30: Info: Recovering parsing after character u','
   |  At line 89, column 30, offset 2797
./configs/config.json:89:30: Info: Recovering parsing after character u','
   |  At line 89, column 30, offset 2797
./configs/config.json:90:21: Error: Can not decode value starting with character u':'
   |  At line 90, column 21, offset 2820
./configs/config.json:90:23: Info: Recovering parsing after character u'"'
   |  At line 90, column 23, offset 2822
./configs/config.json:90:23: Info: Recovering parsing after character u'"'
   |  At line 90, column 23, offset 2822
./configs/config.json:90:23: Error: Values must be separated by a comma
   |  At line 90, column 23, offset 2822
   |  Array started at line 8, column 9, offset 272
./configs/config.json:91:36: Error: Can not decode value starting with character u':'
   |  At line 91, column 36, offset 2866
./configs/config.json:91:41: Info: Recovering parsing after character u','
   |  At line 91, column 41, offset 2871
./configs/config.json:91:41: Info: Recovering parsing after character u','
   |  At line 91, column 41, offset 2871
./configs/config.json:92:33: Error: Can not decode value starting with character u':'
   |  At line 92, column 33, offset 2906
./configs/config.json:92:38: Info: Recovering parsing after character u','
   |  At line 92, column 38, offset 2911
./configs/config.json:92:38: Info: Recovering parsing after character u','
   |  At line 92, column 38, offset 2911
./configs/config.json:93:11: Error: Can not decode value starting with character u':'
   |  At line 93, column 11, offset 2924
./configs/config.json:93:13: Info: Recovering parsing after character u'{'
   |  At line 93, column 13, offset 2926
./configs/config.json:93:13: Info: Recovering parsing after character u'{'
   |  At line 93, column 13, offset 2926
./configs/config.json:93:13: Error: Values must be separated by a comma
   |  At line 93, column 13, offset 2926
   |  Array started at line 8, column 9, offset 272
./configs/config.json:98:13: Error: Can not decode value starting with character u':'
   |  At line 98, column 13, offset 3008
./configs/config.json:98:15: Info: Recovering parsing after character u'{'
   |  At line 98, column 15, offset 3010
./configs/config.json:98:15: Info: Recovering parsing after character u'{'
   |  At line 98, column 15, offset 3010
./configs/config.json:98:15: Error: Values must be separated by a comma
   |  At line 98, column 15, offset 3010
   |  Array started at line 8, column 9, offset 272
./configs/config.json:166:10: Error: Can not decode value starting with character u':'
   |  At line 166, column 10, offset 4405
./configs/config.json:166:12: Info: Recovering parsing after character u'{'
   |  At line 166, column 12, offset 4407
./configs/config.json:166:12: Info: Recovering parsing after character u'{'
   |  At line 166, column 12, offset 4407
./configs/config.json:166:12: Error: Values must be separated by a comma
   |  At line 166, column 12, offset 4407
   |  Array started at line 8, column 9, offset 272
./configs/config.json:177:0: Error: Expected a ']' but saw '}'
   |  At line 177, column 0, offset 4627
   |  Array started at line 8, column 9, offset 272
./configs/config.json: has errors
2016-08-09 21:13:02,110 [       cli] [CRITICAL] Error with configuration file

**Comment by chr1spy** [comment]
Keep the right syntax. I mean, the even log tells you everything you need to know.

**Comment by KingTheRipper** [comment]
If you want setup a correct pokemon release please take a look to my sintax: `"release": {
    "any": {"release_below_cp": 400, "release_below_iv": 0.9, "logic": "and" },

    "Bulbasaur":    { "release_below_cp": 374, "release_below_iv": 0.8, "logic": "and" },
    "Ivysaur":      { "release_below_cp": 571, "release_below_iv": 0.8, "logic": "and" },
    "Venusaur":     { "release_below_cp": 902, "release_below_iv": 0.8, "logic": "and" },
    "Charmander":   { "release_below_cp": 333, "release_below_iv": 0.8, "logic": "and" },
    "Charmeleon":   { "release_below_cp": 544, "release_below_iv": 0.8, "logic": "and" },
    "Charizard":    { "release_below_cp": 909, "release_below_iv": 0.8, "logic": "and" },
    "Squirtle":     { "release_below_cp": 352, "release_below_iv": 0.8, "logic": "and" },
    "Wartortle":    { "release_below_cp": 552, "release_below_iv": 0.8, "logic": "and" },
    "Blastoise":    { "release_below_cp": 888, "release_below_iv": 0.8, "logic": "and" },
    "Caterpie":     { "release_below_cp": 156, "release_below_iv": 0.8, "logic": "and" },
    "Metapod":      { "release_below_cp": 168, "release_below_iv": 0.8, "logic": "and" },
    "Butterfree":   { "release_below_cp": 508, "release_below_iv": 0.8, "logic": "and" },
    "Weedle":       { "release_below_cp": 156, "release_below_iv": 0.8, "logic": "and" },
    "Kakuna":       { "release_below_cp": 170, "release_below_iv": 0.8, "logic": "and" },
    "Beedrill":     { "release_below_cp": 504, "release_below_iv": 0.8, "logic": "and" },
    "Pidgey":       { "release_below_cp": 237, "release_below_iv": 0.8, "logic": "and" },
    "Pidgeotto":    { "release_below_cp": 427, "release_below_iv": 0.8, "logic": "and" },
    "Pidgeot":      { "release_below_cp": 729, "release_below_iv": 0.8, "logic": "and" },
    "Rattata":      { "release_below_cp": 204, "release_below_iv": 0.8, "logic": "and" },
    "Raticate":     { "release_below_cp": 504, "release_below_iv": 0.8, "logic": "and" },
    "Spearow":      { "release_below_cp": 240, "release_below_iv": 0.8, "logic": "and" },
    "Fearow":       { "release_below_cp": 609, "release_below_iv": 0.8, "logic": "and" },
    "Ekans":        { "release_below_cp": 288, "release_below_iv": 0.8, "logic": "and" },
    "Arbok":        { "release_below_cp": 616, "release_below_iv": 0.8, "logic": "and" },
    "Pikachu":      { "release_below_cp": 309, "release_below_iv": 0.8, "logic": "and" },
    "Raichu":       { "release_below_cp": 708, "release_below_iv": 0.8, "logic": "and" },
    "Sandshrew":    { "release_below_cp": 278, "release_below_iv": 0.8, "logic": "and" },
    "Sandslash":    { "release_below_cp": 631, "release_below_iv": 0.8, "logic": "and" },
    "Nidoran F":    { "release_below_cp": 304, "release_below_iv": 0.8, "logic": "and" },
    "Nidorina":     { "release_below_cp": 489, "release_below_iv": 0.8, "logic": "and" },
    "Nidoqueen":    { "release_below_cp": 868, "release_below_iv": 0.8, "logic": "and" },
    "Nidoran M":    { "release_below_cp": 295, "release_below_iv": 0.8, "logic": "and" },
    "Nidorino":     { "release_below_cp": 480, "release_below_iv": 0.8, "logic": "and" },
    "Nidoking":     { "release_below_cp": 864, "release_below_iv": 0.8, "logic": "and" },
    "Clefairy":     { "release_below_cp": 420, "release_below_iv": 0.8, "logic": "and" },
    "Clefable":     { "release_below_cp": 837, "release_below_iv": 0.8, "logic": "and" },
    "Vulpix":       { "release_below_cp": 290, "release_below_iv": 0.8, "logic": "and" },
    "Ninetales":    { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
    "Jigglypuff":   { "release_below_cp": 321, "release_below_iv": 0.8, "logic": "and" },
    "Wigglytuff":   { "release_below_cp": 760, "release_below_iv": 0.8, "logic": "and" },
    "Zubat":        { "release_below_cp": 225, "release_below_iv": 0.8, "logic": "and" },
    "Golbat":       { "release_below_cp": 672, "release_below_iv": 0.8, "logic": "and" },
    "Oddish":       { "release_below_cp": 400, "release_below_iv": 0.8, "logic": "and" },
    "Gloom":        { "release_below_cp": 590, "release_below_iv": 0.8, "logic": "and" },
    "Vileplume":    { "release_below_cp": 871, "release_below_iv": 0.8, "logic": "and" },
    "Paras":        { "release_below_cp": 319, "release_below_iv": 0.8, "logic": "and" },
    "Parasect":     { "release_below_cp": 609, "release_below_iv": 0.8, "logic": "and" },
    "Venonat":      { "release_below_cp": 360, "release_below_iv": 0.8, "logic": "and" },
    "Venomoth":     { "release_below_cp": 660, "release_below_iv": 0.8, "logic": "and" },
    "Diglett":      { "release_below_cp": 158, "release_below_iv": 0.8, "logic": "and" },
    "Dugtrio":      { "release_below_cp": 408, "release_below_iv": 0.8, "logic": "and" },
    "Meowth":       { "release_below_cp": 264, "release_below_iv": 0.8, "logic": "and" },
    "Persian":      { "release_below_cp": 568, "release_below_iv": 0.8, "logic": "and" },
    "Psyduck":      { "release_below_cp": 386, "release_below_iv": 0.8, "logic": "and" },
    "Golduck":      { "release_below_cp": 832, "release_below_iv": 0.8, "logic": "and" },
    "Mankey":       { "release_below_cp": 307, "release_below_iv": 0.8, "logic": "and" },
    "Primeape":     { "release_below_cp": 650, "release_below_iv": 0.8, "logic": "and" },
    "Growlithe":    { "release_below_cp": 465, "release_below_iv": 0.8, "logic": "and" },
    "Arcanine":     { "release_below_cp": 1041, "release_below_iv": 0.8, "logic": "and" },
    "Poliwag":      { "release_below_cp": 278, "release_below_iv": 0.8, "logic": "and" },
    "Poliwhirl":    { "release_below_cp": 468, "release_below_iv": 0.8, "logic": "and" },
    "Poliwrath":    { "release_below_cp": 876, "release_below_iv": 0.8, "logic": "and" },
    "Abra":         { "release_below_cp": 208, "release_below_iv": 0.8, "logic": "and" },
    "Kadabra":      { "release_below_cp": 396, "release_below_iv": 0.8, "logic": "and" },
    "Alakazam":     { "release_below_cp": 633, "release_below_iv": 0.8, "logic": "and" },
    "Machop":       { "release_below_cp": 381, "release_below_iv": 0.8, "logic": "and" },
    "Machoke":      { "release_below_cp": 614, "release_below_iv": 0.8, "logic": "and" },
    "Machamp":      { "release_below_cp": 907, "release_below_iv": 0.8, "logic": "and" },
    "Bellsprout":   { "release_below_cp": 391, "release_below_iv": 0.8, "logic": "and" },
    "Weepinbell":   { "release_below_cp": 602, "release_below_iv": 0.8, "logic": "and" },
    "Victreebel":   { "release_below_cp": 883, "release_below_iv": 0.8, "logic": "and" },
    "Tentacool":    { "release_below_cp": 316, "release_below_iv": 0.8, "logic": "and" },
    "Tentacruel":   { "release_below_cp": 775, "release_below_iv": 0.8, "logic": "and" },
    "Geodude":      { "release_below_cp": 297, "release_below_iv": 0.8, "logic": "and" },
    "Graveler":     { "release_below_cp": 501, "release_below_iv": 0.8, "logic": "and" },
    "Golem":        { "release_below_cp": 804, "release_below_iv": 0.8, "logic": "and" },
    "Ponyta":       { "release_below_cp": 530, "release_below_iv": 0.8, "logic": "and" },
    "Rapidash":     { "release_below_cp": 768, "release_below_iv": 0.8, "logic": "and" },
    "Slowpoke":     { "release_below_cp": 424, "release_below_iv": 0.8, "logic": "and" },
    "Slowbro":      { "release_below_cp": 907, "release_below_iv": 0.8, "logic": "and" },
    "Magnemite":    { "release_below_cp": 312, "release_below_iv": 0.8, "logic": "and" },
    "Magneton":     { "release_below_cp": 657, "release_below_iv": 0.8, "logic": "and" },
    "Farfetch'd":   { "release_below_cp": 441, "release_below_iv": 0.8, "logic": "and" },
    "Doduo":        { "release_below_cp": 297, "release_below_iv": 0.8, "logic": "and" },
    "Dodrio":       { "release_below_cp": 640, "release_below_iv": 0.8, "logic": "and" },
    "Seel":         { "release_below_cp": 386, "release_below_iv": 0.8, "logic": "and" },
    "Dewgong":      { "release_below_cp": 748, "release_below_iv": 0.8, "logic": "and" },
    "Grimer":       { "release_below_cp": 448, "release_below_iv": 0.8, "logic": "and" },
    "Muk":          { "release_below_cp": 909, "release_below_iv": 0.8, "logic": "and" },
    "Shellder":     { "release_below_cp": 288, "release_below_iv": 0.8, "logic": "and" },
    "Cloyster":     { "release_below_cp": 717, "release_below_iv": 0.8, "logic": "and" },
    "Gastly":       { "release_below_cp": 280, "release_below_iv": 0.8, "logic": "and" },
    "Haunter":      { "release_below_cp": 482, "release_below_iv": 0.8, "logic": "and" },
    "Gengar":       { "release_below_cp": 724, "release_below_iv": 0.8, "logic": "and" },
    "Onix":         { "release_below_cp": 300, "release_below_iv": 0.8, "logic": "and" },
    "Drowzee":      { "release_below_cp": 374, "release_below_iv": 0.8, "logic": "and" },
    "Hypno":        { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
    "Krabby":       { "release_below_cp": 276, "release_below_iv": 0.8, "logic": "and" },
    "Kingler":      { "release_below_cp": 636, "release_below_iv": 0.8, "logic": "and" },
    "Voltorb":      { "release_below_cp": 292, "release_below_iv": 0.8, "logic": "and" },
    "Electrode":    { "release_below_cp": 576, "release_below_iv": 0.8, "logic": "and" },
    "Exeggcute":    { "release_below_cp": 384, "release_below_iv": 0.8, "logic": "and" },
    "Exeggutor":    { "release_below_cp": 1032, "release_below_iv": 0.8, "logic": "and" },
    "Cubone":       { "release_below_cp": 352, "release_below_iv": 0.8, "logic": "and" },
    "Marowak":      { "release_below_cp": 578, "release_below_iv": 0.8, "logic": "and" },
    "Hitmonlee":    { "release_below_cp": 520, "release_below_iv": 0.8, "logic": "and" },
    "Hitmonchan":   { "release_below_cp": 530, "release_below_iv": 0.8, "logic": "and" },
    "Lickitung":    { "release_below_cp": 568, "release_below_iv": 0.8, "logic": "and" },
    "Koffing":      { "release_below_cp": 403, "release_below_iv": 0.8, "logic": "and" },
    "Weezing":      { "release_below_cp": 784, "release_below_iv": 0.8, "logic": "and" },
    "Rhyhorn":      { "release_below_cp": 412, "release_below_iv": 0.8, "logic": "and" },
    "Rhydon":       { "release_below_cp": 782, "release_below_iv": 0.8, "logic": "and" },
    "Chansey":      { "release_below_cp": 235, "release_below_iv": 0.8, "logic": "and" },
    "Tangela":      { "release_below_cp": 607, "release_below_iv": 0.8, "logic": "and" },
    "Kangaskhan":   { "release_below_cp": 712, "release_below_iv": 0.8, "logic": "and" },
    "Horsea":       { "release_below_cp": 278, "release_below_iv": 0.8, "logic": "and" },
    "Seadra":       { "release_below_cp": 597, "release_below_iv": 0.8, "logic": "and" },
    "Goldeen":      { "release_below_cp": 336, "release_below_iv": 0.8, "logic": "and" },
    "Seaking":      { "release_below_cp": 712, "release_below_iv": 0.8, "logic": "and" },
    "Staryu":       { "release_below_cp": 326, "release_below_iv": 0.8, "logic": "and" },
    "Starmie":      { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
    "Mr. Mime":     { "release_below_cp": 520, "release_below_iv": 0.8, "logic": "and" },
    "Scyther":      { "release_below_cp": 724, "release_below_iv": 0.8, "logic": "and" },
    "Jynx":         { "release_below_cp": 600, "release_below_iv": 0.8, "logic": "and" },
    "Electabuzz":   { "release_below_cp": 739, "release_below_iv": 0.8, "logic": "and" },
    "Magmar":       { "release_below_cp": 792, "release_below_iv": 0.8, "logic": "and" },
    "Pinsir":       { "release_below_cp": 741, "release_below_iv": 0.8, "logic": "and" },
    "Tauros":       { "release_below_cp": 643, "release_below_iv": 0.8, "logic": "and" },
    "Magikarp":     { "release_below_cp": 91, "release_below_iv": 0.8, "logic": "and" },
    "Gyarados":     { "release_below_cp": 938, "release_below_iv": 0.8, "logic": "and" },
    "Lapras":       { "release_below_cp": 1041, "release_below_iv": 0.8, "logic": "and" },
    "Ditto":        { "release_below_cp": 321, "release_below_iv": 0.8, "logic": "and" },
    "Eevee":        { "release_below_cp": 376, "release_below_iv": 0.8, "logic": "and" },
    "Vaporeon":     { "release_below_cp": 984, "release_below_iv": 0.8, "logic": "and" },
    "Jolteon":      { "release_below_cp": 746, "release_below_iv": 0.8, "logic": "and" },
    "Flareon":      { "release_below_cp": 924, "release_below_iv": 0.8, "logic": "and" },
    "Porygon":      { "release_below_cp": 590, "release_below_iv": 0.8, "logic": "and" },
    "Omanyte":      { "release_below_cp": 391, "release_below_iv": 0.8, "logic": "and" },
    "Omastar":      { "release_below_cp": 780, "release_below_iv": 0.8, "logic": "and" },
    "Kabuto":       { "release_below_cp": 386, "release_below_iv": 0.8, "logic": "and" },
    "Kabutops":     { "release_below_cp": 744, "release_below_iv": 0.8, "logic": "and" },
    "Aerodactyl":   { "release_below_cp": 756, "release_below_iv": 0.8, "logic": "and" },
    "Snorlax":      { "release_below_cp": 1087, "release_below_iv": 0.8, "logic": "and" },
    "Articuno":     { "release_below_cp": 1039, "release_below_iv": 0.8, "logic": "and" },
    "Zapdos":       { "release_below_cp": 1087, "release_below_iv": 0.8, "logic": "and" },
    "Moltres":      { "release_below_cp": 1132, "release_below_iv": 0.8, "logic": "and" },
    "Dratini":      { "release_below_cp": 343, "release_below_iv": 0.8, "logic": "and" },
    "Dragonair":    { "release_below_cp": 609, "release_below_iv": 0.8, "logic": "and" },
    "Dragonite":    { "release_below_cp": 1221, "release_below_iv": 0.8, "logic": "and" },
    "Mewtwo":       { "release_below_cp": 1447, "release_below_iv": 0.8, "logic": "and" },
    "Mew":          { "release_below_cp": 1152, "release_below_iv": 0.8, "logic": "and" },

    "vips": {
    "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
    "Lapras": {},
    "Moltres": {},
    "Zapdos": {},
    "Articuno": {},
    "Mewtwo": {},
    "Dragonite": {},
    "Snorlax": {},
    "Mew": {},
    "Arcanine": {},
    "Vaporeon": {},
    "Gyarados": {},
    "Exeggutor": {},
    "Muk": {},
    "Weezing": {},
    "Flareon": {},
    "Pikachu": {}
    }
}`

**Comment by RedViper9** [comment]
In the future, run your config through http://jsonlint.com/ rather than posting it here.
You have two syntax errors crashing your config.

You have:
```
"Ultraball": { "keep" : 75 }

}
},
{
"type": "EvolvePokemon",
```
Should be:
```
"Ultraball": { "keep" : 75 }
}
}
},
{
"type": "EvolvePokemon",
```
You have:
```
"type": "CatchLuredPokemon"
}
},
"map_object_cache_time": 5,
"forts": {
```
Should be:
```
"type": "CatchLuredPokemon"
}
],
"map_object_cache_time": 5,
"forts": {
```
