### ISSUE TITLE
egg incubation wont work

### ISSUE THREAD

**Issue by sysandrew** [PokemonGoF/PokemonGo-Bot#3265]
egg wont work

**Comment by beranPro** [comment]
Your walking Speed?

**Comment by Dauth** [comment]
get it down to less than 14km per hour

**Comment by beranPro** [comment]
After the latest update  8km/h is the maximum

**Comment by sysandrew** [comment]
tnx ill try 8km/h

**Comment by eevee-github** [comment]
@sysandrew Did you see `Incubator in use.` messages repeated in your log when incubation did't work?

**Comment by beranPro** [comment]
@Dauth
Please close the issue if it works

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
