### ISSUE TITLE
Git window not showing stats after session end

### ISSUE THREAD

**Issue by 15calderm** [PokemonGoF/PokemonGo-Bot#3266]
### Expected Behavior
Window to show stats for the runtime (total xp earned, xp per hour, pokemon caught etc).

### Actual Behavior
Using ctrl+c just ends the bot, no stats shown.

### Steps to Reproduce
End bot after x time passed.

### Other Information
OS: Win10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by Dwite** [comment]
Works well for me, what is your branch and commit?

**Comment by 15calderm** [comment]
Using dev branch, latest commit - updated ~5 mins ago

**Comment by 15calderm** [comment]
I also run pokecli.py through GitBash, could that have something to do with it?

**Comment by k4n30** [comment]
@15calderm please post an example of the output with your issue
