### ISSUE TITLE
No Verbose output when followpath used

### ISSUE THREAD

**Issue by alexratman** [PokemonGoF/PokemonGo-Bot#3267]
### Expected Behavior
When using followpath behaviour bot will follow path and report on distance to next waypoint

### Actual Behavior
no output on location in log.

### Steps to Reproduce
run bot with path config

### Other Information
OS: Linux
Git Commit: 49f9177ef4226a6a69499d7afc1fb24e5c72fc50
Python Version: Python 2.7.9

**Comment by Dauth** [comment]
only way is to just track using the frontend

**Comment by alexratman** [comment]
Aware of that - and have been. But it is a little offputting that there is no output into the console regarding whether the path has been parsed or if it is being followed.

**Comment by k4n30** [comment]
@alexratman is this still an issue? and if it is, should it turn into a feature request?
