### ISSUE TITLE
Not issue - New release of Pokemon Go.

### ISSUE THREAD

**Issue by takenek** [PokemonGoF/PokemonGo-Bot#3268]
hey
Someone check what`s new in today release original Pokemon Go game for iOS/Androids?
I read on forum today there is a special function to detect real Pokemon Go clients  and detect old clients and bots.

Someone can confirm this? Using bots is still safe after today update?
Anyone debug new version to check "what`s new" Pokemon Go Clients send to servers?
Mayby another UNK6 waiting in background?

Best Regards
TaKeN

**Comment by cmezh** [comment]
It's not related to PokemonGo-Bot. It's about pogoapi.

**Comment by innrwrld** [comment]
I've see as of this morning issues with PMGbot having issues logging in with both account types, claiming:

`2016-08-09 08:35:09,954 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 4/15`

Which isn't at all true given the mobile apps work properly for both PTC & Google.  Looks like they had another card up their sleeves for whenever the devs cracked the changes from last week.

**Comment by kesfaw** [comment]
From Niantic news: http://pokemongo.nianticlabs.com/en/post/update-080816/
They fixed a bug that prevented ”Nice,” ”Great,” and “Excellent” Poké Ball throws from awarding the appropriate XP bonuses. Therefore, out bot gets not only the exp bonus but also the highest bonus possible for each throw. 

Is that possible for the bot using pgoapi to capture a pokemon with a random bonus or not?

**Comment by Marco208** [comment]
@innrwrld What was the fix?
