### ISSUE TITLE
[Feature][Need help] Evolution logic

### ISSUE THREAD

**Issue by cmezh** [PokemonGoF/PokemonGo-Bot#3274]
Need your help. I want to implement one more evolve mode based on resulting CP compared to other family-related pokemons CP. Is there any reliable info how we can calculate CP after evolving?

**Comment by Dwite** [comment]
@cmezh  you can try http://pogotoolkit.com/ or https://pokeassistant.com/main/evolver
As far as I understand there are min and max multipliers for each Pokemon that you can evolve.
