### ISSUE TITLE
Multiple Bots for the same account

### ISSUE THREAD

**Issue by samios** [PokemonGoF/PokemonGo-Bot#3275]
So I was wondering if it's possible to run multiple bots for the same account, It should since while running the bot on my computer I can still connect on my android device and play/earn XP at the same time. Or is it maybe just switching the location from my device with the location sent by the bot ?

**Comment by djadstar** [comment]
You're asking for a ban!

**Comment by samios** [comment]
Right now my android is on 4G while the computer runs the bot through another internet connection so the two IPs are different, is even that risky ? Whatever the case I'm planning to stop using the bot soon, perma ban is coming..

**Comment by PokeProgress** [comment]
Just curious here. Have the released anything talking about perma bans? im still tweaking my bots and have run into softbans . Ive finally found something that seems to have been running for 12 hours now without softbans by only running 2 accounts with specific settings.

**Comment by samios** [comment]
Nope still nothing. They did say that they are seriously considering this matter and would eventually do something but no perma ban yet (from what I've found). They could still figure out later whether a bot was used or not even when you stop using it and ban you then. Anyway that didn't answer my question so I guess I'm just gonna try it with some test accounts and see what happens. I'll post it here if it works or not.
