### ISSUE TITLE
[Feature] [Dev] Snipe for pokemons given as arguments / passed in a .csv

### ISSUE THREAD

**Issue by MMurarasu** [PokemonGoF/PokemonGo-Bot#3278]
### Expected Behavior
Since PokemonGo-Map is not working anymore, and it was pretty complexe that stuff, we would need something easier, easier, nice to update, for those who snipe from time to time, and only for special pokemons.

### What would be nice Behavior:
Have another file : pokemon-list.json,  or a csv, to fill it with pokemons and coordinates:
X, Y, name.
Make the current worker scan for updates at each Z-sleep interval, ( inserts, deletes, resets.. ) and use the snipe and teleport to catch those from the list.
Or, at least  (and in this case I will help with the .bat / sh to reset the bot and etcetera ) have the bot run with --snipe=x,y. So we might be able to do at least with location-cache directly the snipe then resume the farming in another script.

Thank you! It's not my main python, I tried something, but I'm a really bad .py dev. 

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by MMurarasu** [comment]
...Especially since: https://github.com/AHAAAAAAA/PokemonGo-Map 

was deleted

**Comment by Lunik** [comment]
This repo have been forked [here](https://github.com/PokemonGoMap/PokemonGo-Map)

**Comment by omeryagmurlu** [comment]
@Lunik But we still need a simple, UNIVERSAL, way to snipe for pokemons. There are lots of sources (leik: [this api)](http://pokesnipers.com/api/v1/pokemon.json) and [this socketio server](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3226#issuecomment-238681375) and making new workers for each of them is dumb.

**Comment by SpencerCarstens** [comment]
To add to the map options:

https://github.com/favll/pogom

```json
"update_map": false,
"map_path": "map-data",
```

^ To get it to work with sniping.

**Comment by beranPro** [comment]
I've coded a function which need the coordinates and the Pokemon-id and do all the magic. Teleport, encounter, teleport back and catch the Pokémon. Im currently make a plugin for the Bot. In the next days it will be released.
If you cant wait take a look at the cell_workee move_to_map_pokemon.py
in the snipe method.

**Comment by LDengXYZ** [comment]
Hi @beranPro , do you mean only do snipe for given pokemons? That's the exact feature I'm looking for. 
Because for common pokemons, I'd prefer walking (for eggs and forts), but use snipe for rare pokemons.

**Comment by k4n30** [comment]
#3666 #3355 #3226
