### ISSUE TITLE
PokemonGo updated, is the bot still working?

### ISSUE THREAD

**Issue by weedsativa420** [PokemonGoF/PokemonGo-Bot#3281]
Pokemon Go just updated, can we still use the bot?

**Comment by Dwite** [comment]
@weedsativa420 yeah, running it without problem right now. And I don't think such questions should be in github issue tracker, use slack instead.

**Comment by pavanjared** [comment]
@weedsativa420 Are you reporting that it does not work, or requesting that someone checks that it does?

**Comment by innrwrld** [comment]
#3268 & #3209 both have a little info in it that people are seeing with regard to login issues after the mobile apps were updated yesterday.
