### ISSUE TITLE
Evolve configuration

### ISSUE THREAD

**Issue by matrixxus** [PokemonGoF/PokemonGo-Bot#3282]
Hello Guys,

tried many scenarios, just can't figure it out.

I would like to evolve all cached pokemons to gain more exp, after that transfer them for a candy if they meet the requirements for a transfer. (requirement= keep 2 best by CP)

What the bot does now is first it transfers the pokemon, then it tries to evolve according to 'evolve_all_captured = true'

Not sure how to configure it.

Thanks! :)

**Comment by Dwite** [comment]
@matrixxus you can change order of your configuration tasks and probably this will fix you problem, but could you please ask such questions at #help slack chat and not github issue tracker?
