### ISSUE TITLE
I got this error when im try to do on cmd with docker command

### ISSUE THREAD

**Issue by newocs** [PokemonGoF/PokemonGo-Bot#3283]
docker run --name=pokego-bot1 --rm -it -v $(pwd)/configs/config-account1.json:/usr/src/app/configs/config.json pokemongo-bot

![error](https://cloud.githubusercontent.com/assets/20928091/17517559/288cc2b0-5e6e-11e6-98c2-f9a8b9e53db8.png)

And also face this error
![errs](https://cloud.githubusercontent.com/assets/20928091/17517881/a98c1cf2-5e6f-11e6-9ba0-39adcc7ac24d.png)

Pls help :(

**Comment by terbolous** [comment]
docker error: drop the dash in your config file name
virtualenv error: the command is `source bin/activate`

**Comment by newocs** [comment]
@terbolous Thanks, But i stucked with this Encrypt.dll error
![untitled](https://cloud.githubusercontent.com/assets/20928091/17519846/d2d54f9a-5e77-11e6-8066-921d33f423fe.png)
