### ISSUE TITLE
Mac - Can't launch bot from new terminal window

### ISSUE THREAD

**Issue by Meph88** [PokemonGoF/PokemonGo-Bot#3286]
Not sure what's going on.

If I go through the installation instructions, edit my config.json file and get the encrypt.so file and place it in the root directory I can launch the bot with `python pokecli.py` as long as I'm in the root directory.

If I want to run the bot from a new tab or I close terminal and try to run it again I get the output:
`Traceback (most recent call last):`
`  File "pokecli.py", line 38, in <module>`
`    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException`
`ImportError: cannot import name ServerSideRequestThrottlingException`

The only way I can figure to make it work again is to go through the installation again.
I'm sure I'm just missing something here but what?

Please help.

**Comment by Meph88** [comment]
SOLVED

Solved issue by running:
`$ virtualenv .  `
`$ source bin/activate `

before running `python pokecli.py`

**Comment by Dauth** [comment]
well it helps if you followed the instructions. so can you close this
