### ISSUE TITLE
Arrives at the pokemon but continues without catch it. 

### ISSUE THREAD

**Issue by muratcancicek** [PokemonGoF/PokemonGo-Bot#3287]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior

On the map config, moving and arriving at the pokemon and catch it.

### Actual Behavior

 arriving at the pokemon but, doesn't catch it, just move another target. My bag and pokeballs are okay and the both catches other pokemons regularly.  

### Steps to Reproduce

catch the the pokemon

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by muratcancicek** [comment]
Enabling snipe temporarily solved my problem.

**Comment by muratcancicek** [comment]
@PlanetoftheMapes For it doesn't even say  "encountered X", just arrived at X then it continues moving. 
Is sniping dangerous for banning?

**Comment by Happyrain67** [comment]
Same here.
Walking but never catching.

**Comment by Happyrain67** [comment]
Ok I have fixe it with a good config.

Juste place task "CatchVisiblePokemon" and "CatchLuredPokemon" AFTER "MoveToMapPokemon".
And I have place task "MoveToFort" in last.

This work !
The Bot Walking, Encoutered and catch pokemon.

**Comment by p1n9** [comment]
Hi I had the same issue and I corrected it by reordering the sequence of tasks and by adding the missing parameters from the file [config.json.map.example](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/configs/config.json.map.example) (dev version)

Now it works like a charm =)
