### ISSUE TITLE
Pgoapi does not return access token

### ISSUE THREAD

**Issue by guitared** [PokemonGoF/PokemonGo-Bot#3288]
With requirements.txt which have https://github.com/keyphact/pgoapi.git@249d3be7fbbdabc7f9adea17cbc899d6549e47a2#egg=pgoapi

on PokemonGo-Bot\src\pgoapi\pgoapi\auth_google.py
line 88 and below does not return access token

this causes #3031 #3098 .....

**Comment by urbels** [comment]
Update to latest dev.

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
