### ISSUE TITLE
Use lat/long/alt as location

### ISSUE THREAD

**Issue by Lanithro** [PokemonGoF/PokemonGo-Bot#33]
Hello, perhaps it is possible to use lat/long/alt as a location. This way it is easier to make a precise location to get specific pokemons.

**Comment by diordache** [comment]
It works, use `-l "xx.yyyy,zz.ttttt"` to set lat long for location.

**Comment by PokemonGoF** [comment]
Thanks @diordache will update FAQ. or a pull request :)
