### ISSUE TITLE
Error in bot startup

### ISSUE THREAD

**Issue by piai46** [PokemonGoF/PokemonGo-Bot#3302]
Hello , is experiencing an error when booting the bot, do not know what to do, please help me .
The following image:

![image](https://cloud.githubusercontent.com/assets/20868902/17521929/8f55a8e2-5e2b-11e6-8502-177c3a6eac04.png)

**Comment by RedViper9** [comment]
Please ask this question in the #help section on slack. This is not an issue with the bot.
