### ISSUE TITLE
ImportError: No module named pgoapi.exceptions

### ISSUE THREAD

**Issue by curtybird95** [PokemonGoF/PokemonGo-Bot#3303]
Curtiss-MacBook-Pro:PokemonGo-Bot curtismcintyre$ python pokecli.py --config ./configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

How to Fix this?

**Comment by KingArsalan14** [comment]
hey i had the same error and i fixed it by writing pip install -r requirements.txt , hope this helps !

**Comment by nifloutch** [comment]
Hi, maybe you forgot to run the first line :

$ source bin/activate
$ python pokecli.py

When I do not source the bin/activate file I have the same error

**Comment by spencerby28** [comment]
In this particular case, pip install -r requirements.txt will install all listed package versions to the exact specified version. Most of them work just fine as pip should behave, as they are managed packages of the pypi. The exception here is the pgoapi package, listed on line 3. It is not a pypi package. It is a github repository. Pip handle it badly. In occasions you have to remove the whole repository cloned by pip (rm -rf pgoapi) and do pip install again, i.e. pip install -r requirements.txt

This is a great opportunity to learn python!
