### ISSUE TITLE
Does a high walk speed (>20) stops the bot after the client update?

### ISSUE THREAD

**Issue by TianCNCA** [PokemonGoF/PokemonGo-Bot#3305]
After the update if the app detects you're moving too fast it pops up a window and ask the user to confirm they're not driving. Does the bot handle this case correctly by sending the "Yes" response? I noticed that if I set the walk speed to very high (50m/s) the bot stops receiving map objects after a little while (10, 20 minutes?), and it wasn't like this before.

**Comment by umutafacan** [comment]
No, try lower your response times in config.
