### ISSUE TITLE
Egg hatching is not working

### ISSUE THREAD

**Issue by tienn** [PokemonGoF/PokemonGo-Bot#3306]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior
Egg hatched

### Actual Behavior
I got egg_hatched [... : error, .... : error] and no eggs hatched in the journal

### Steps to Reproduce
"Walk" till it hatches

### Other Information
OS: Mac
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by GitPupper** [comment]
Post your config.json

**Comment by tienn** [comment]
{
    "auth_service": "google",
    "username": "xxxxxxx@gmail.com",
    "password": "xxxxxxx",
    "location": "1000 Great Hwy, San Francisco, CA",
    "gmapkey": "xxxxxxxx",
    "libencrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "Pidgey,Caterpie,Weedle,Psyduck,Magnemite,Voltorb,Krabby,Spearow,Doduo,Horsea,Slowpoke",
            "first_evolve_by": "cp",
            "evolve_above_cp": 0,
            "evolve_above_iv": 0,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "Meowth": {"always_release": true},
      "Rattata": {"always_release": true},
      "Tentacool": {"always_release": true},
      "Zubat": {"always_release": true},

      "Caterpie": {"keep_best_cp": 1},
      "Diglett": {"keep_best_cp": 1},
      "Doduo": {"keep_best_cp": 1},
      "Pidgey": {"keep_best_cp": 1},
      "Poliwag": {"keep_best_cp": 1},
      "Venonat": {"keep_best_cp": 1},
      "Voltorb": {"keep_best_cp": 1},

      "Arba": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Bellsprout": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Cubone": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Dratini": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Drowzee": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Eevee": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Electrode": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Exeggcute": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Fearow": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Gastly": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Geodude": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Golduck": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Growlithe": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Hitmochan": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Hitmolee": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Horsea": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Jigglypuff": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Kakuna": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Kingler": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Koffing": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Magikarp": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Magnemite": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Magneton": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Metapod": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Oddish": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Paras": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Pidgeotto": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Ponyta": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Rapidash": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Rhyhorn": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Scyther": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Seel": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Shellder": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Slowpoke": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Staryu": {"keep_best_cp": 1, "keep_best_iv": 1},

      "Ekans": {"keep_best_iv": 1},
      "Golbat": {"keep_best_iv": 1},
      "Goldeen": {"keep_best_iv": 1},
      "Krabby": {"keep_best_iv": 1},
      "Psyduck": {"keep_best_iv": 1},
      "Raticate": {"keep_best_iv": 1},
      "Spearow": {"keep_best_iv": 1}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {},
        "Machamp": {},
        "Kabutops": {},
        "Charizard": {},
        "Chansey": {}
    }
}

**Comment by GitPupper** [comment]
Use http://pastebin.com/UStttHL2 and keep the API key as is.

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
