### ISSUE TITLE
[api_error] Log logged in, reconnecting in 900

### ISSUE THREAD

**Issue by leoxnidas** [PokemonGoF/PokemonGo-Bot#3318]
i get this infor from linux terminal -->2016-08-09 13:03:02,949 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-09 13:03:02,953 [       cli] [INFO] Configuration initialized
2016-08-09 13:03:02,953 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-09 13:03:02,953 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-09 13:03:02,960 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-09 13:03:03,303 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-09 13:03:03,303 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-09 13:03:03,304 [PokemonGoBot] [INFO] [location_found] Location found: 59.333409,18.045008 (59.333409, 18.045008, 0.0)
2016-08-09 13:03:03,304 [PokemonGoBot] [INFO] [position_update] Now at (59.333409, 18.045008, 0)
2016-08-09 13:03:03,304 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-09 13:03:04,307 [pgoapi.auth] [ERROR] Could not retrieve token: Your username or password is incorrect. You have 4 attempts left before you will be locked out of your account for 15 minutes.
2016-08-09 13:03:04,308 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-09 13:03:04,309 [PokemonGoBot] [INFO] [api_error] Log logged in, reconnecting in 900

but it never connects

this is the basic config    ###file...
{
    "auth_service": "ptc",
    "username": "<<<<<<<<",
    "password": "<<<<<<<<<<<<<<<",
    "location": "59.333409,18.045008",
    "gmapkey": "XXXXXXXXXXXXxx",
    "libencrypt_location": "/XXX/PokemonGo-Bot",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

**Comment by z4ppy** [comment]
Same here but not last version (Aug 8, 351ea76b6)

**Comment by ctsstc** [comment]
My password was longer than 15 characters which is what caused my issue

**Comment by erdnaxela02** [comment]
@leoxnidas 
Hello
Sorry for my English, I am not English I use google trad
I had the same problem, you have a PTC account?
Because the PTC account need to validate the email address maximum two days after registration. You received an email with a link to confirm your email, if two days are passing you can log on with pokemonGo application and request the shipment of a new confirmation email. After that the error goes ;-)

**Comment by leoxnidas** [comment]
no, i normally use google account, but i did try both, google and ptc config, and always get error

**Comment by k4n30** [comment]
Not a bot bug, account related
