### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Cooltimmy41** [PokemonGoF/PokemonGo-Bot#3321]
Please check configuration at http://jsonlint.com/ before posting an issue.

### Expected Behavior

how do I run this on a MAC i hack already installed it

**Comment by bigkraig** [comment]
your config is invalid, paste it into jsonlint and fix your errors. you probably have missing/additional commas or unbalanced quotes

**Comment by Cooltimmy41** [comment]
Can you set it up plz I can do the email and pass tho

**Comment by bigkraig** [comment]
i'll get right on it

**Comment by Cooltimmy41** [comment]
Thx

**Comment by Cooltimmy41** [comment]
How is it coming along
