### ISSUE TITLE
Bot consistently stops after 1 hour

### ISSUE THREAD

**Issue by whitmanc** [PokemonGoF/PokemonGo-Bot#3322]
The bot is always stopping after ~1 hour and a few seconds. This has been happening since I began using it a few days ago. Is anyone else experiencing this? Screenshot included at the bottom. 

### Expected Behavior
Bot runs more than 1 hour

### Actual Behavior
Bot -always- stops after 1 hour

### Steps to Reproduce
Run bot as normal for at least 1 hour

### Other Information
OS: OS X 10.11.5
Git Commit: `e5b7eda` on `dev` branch
Python Version: 2.7.10

<img width="1102" alt="screen shot 2016-08-09 at 9 50 31 am" src="https://cloud.githubusercontent.com/assets/1023159/17525414/71fee128-5e17-11e6-84d5-743e1b51e58f.png">

**Comment by spencerby28** [comment]
same for me :( however i set health_record in the config to false & i am trying it again

**Comment by whitmanc** [comment]
Realized this is a dupe, sorry guys! 

Here are refs to issue it is a dupe of: #2864, #2874

**Comment by whitmanc** [comment]
@spencyby28 you can fix it by setting evolve to "none" and not evolving any
