### ISSUE TITLE
Walk Speed Too High?

### ISSUE THREAD

**Issue by DJFlawLess** [PokemonGoF/PokemonGo-Bot#3323]
### Expected Behavior
Bot walks round and the distance counts for eggs/mileage walked.

### Actual Behavior
Bot works as expected for a period then the walked distance stops increasing though still able to capture Pokemon and spin Pokestops.

### Steps to Reproduce
Run bot as usual with config:
`{
    "auth_service": "google",
    "username": "USERNAME",
    "password": "PASSWORD",
    "location": "34.0087332,-118.498224",
    "gmapkey": "GOOGLE_API_KEY",
    "proxy_ip": "",
    "proxy_port": 0,
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"}
    },
    "release": {
      "any": {"keep_best_cp": 1},
      "Eevee": {"keep_best_cp": 3}
    },
    "vips" : {
        "any": {"catch_above_cp": 2000, "catch_above_iv": 0.99, "logic": "or" },
        "Lapras": {},
        "Ditto": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Jolteon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}`

### Other Information
OS: Windows 10
Git Commit: fddf30dd64322219c945a1aba3483f603ce55bcc
Python Version: Python 2.7.10

**Comment by RedViper9** [comment]
Your walk speed seems fine.

As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
