### ISSUE TITLE
Coloured Output on Gnome Terminal

### ISSUE THREAD

**Issue by hansbonini** [PokemonGoF/PokemonGo-Bot#3324]
Coloured output wont working for me on Gnome Terminal with Arch Linux.
I`ve tested both installations (w/ and without docker) but no way.

### Expected Behavior
Colored Output

### Actual Behavior
- Followed installation guide.
- PokemonGO Bot works perfectly
- No coloured output on gnome terminal

### Other Information
OS: Arch Linux
Terminal: gnome-terminal

**Comment by smith-and-web** [comment]
Can confirm. Would be nice to have it.

**Comment by hansbonini** [comment]
http://imgur.com/HQ9JOj6

**Comment by leadboots5** [comment]
there is no colored output currently. so thats why its not working. There is already a pull request for it.

**Comment by extink** [comment]
PR #3198 will be the fix for this
