### ISSUE TITLE
Bot not using Greatballs

### ISSUE THREAD

**Issue by Lapito** [PokemonGoF/PokemonGo-Bot#3325]
### Expected Behavior
Use great balls

### Actual Behavior
Only using normal pokeballs

### Other Information
OS: Ubuntu 16.04 LTS
Git Commit: 4b16e9da985e689d57beae8bf18878f4d872bdc4
Python Version: 2.7.12

**Comment by hansbonini** [comment]
I think bot only uses Greats, Ultras and Masterballs when vips is set.

**Comment by jomarocas** [comment]
@Lapito @hansbonini yes, is correct when detect vip pokemon use great ball or ultra ball for me, is no a issue is a configuration of json file

**Comment by Tagada22** [comment]
"Bulbasaur": {},
"Ivysaur": {},
"Venusaur": {},
"Charmander": {},
"Charmeleon": {},
"Charizard": {},
"Squirtle": {},
"Wartortle": {},
"Blastoise": {},
"Piedgeot": {},
"Pikachu": {},
"Arcanine": {},
"Raichu": {},
"Sandslash": {},
"Ninetales": {},
"Vileplume": {},
"Golduck": {},
"Poliwhirl": {},
"Poliwrath": {},
"Kadabra": {},
"Alakazam": {},
"Machoke": {},
"Machamp": {},
"Weepinbell": {},
"Victreebel": {},
"Golem": {},
"Rapidash": {},
"Muk": {},
"Haunter": {},
"Gengar": {},
"Marowak": {},
"Hitmonlee": {},
"Hitmonchan": {},
"Vaporeon": {},
"Eevee": {},
"Jolteon": {},
"Flareon": {},
"Porygon": {},
"Omastar": {},
"Aerodactyl": {},
"Dratini": {},
"Dragonair": {},
"Dragonite": {},



if i can help you :)
