### ISSUE TITLE
Pokemon renamed

### ISSUE THREAD

**Issue by curtybird95** [PokemonGoF/PokemonGo-Bot#3327]
My bot is up and running and my pokemon got nicknamed "you got hacked you stupid american faggot" everybodys do this? lol

**Comment by randypfohl** [comment]
Yes, it is part of the renaming process...

to rename pokemon 30 characters past max size.

If you are going to act like a tool, please don't ruin the joke with basic use cases.

**Comment by randypfohl** [comment]
Also, close this trash.
