### ISSUE TITLE
Encrypt.so error

### ISSUE THREAD

**Issue by anantabhawuk** [PokemonGoF/PokemonGo-Bot#3328]
Running on Macbook Pro, getting this currently after it logs in successfully.

016-08-10 02:29:33,765 [PokemonGoBot] [ERROR] encrypt.so is not found! Please place it in the bots root directory or set libencrypt_location in config.
2016-08-10 02:29:33,765 [PokemonGoBot] [INFO] Platform: darwin Encrypt.so directory: /Users/anantabhawuk/PokemonGo-Bot

**Comment by JonesN7** [comment]
Please try to do some sort of googling on the (pretty clear) error message before posting. This is an issue track, not a support forum

`wget http://pgoapi.com/pgoencrypt.tar.gz
tar -xf pgoencrypt.tar.gz
cd pgoencrypt/src
make
cp libencrypt.so ../../encrypt.so`

**Comment by anantabhawuk** [comment]
Sorry for the mispost! I figured it out :)

**Comment by jomarocas** [comment]
@anantabhawuk close the issue
