### ISSUE TITLE
Start bot on reboot (Ubuntu)

### ISSUE THREAD

**Issue by PeanutBotter** [PokemonGoF/PokemonGo-Bot#3333]
Simple question:

How can I start the bot at reboot on Ubuntu 14.04?

I thought a root crontab job like this would work, but it doesn't:

    cd /home/pogo/PokemonGo-Bot
    source bin/activate
    ./run.sh configs/config.json

**Comment by smith-and-web** [comment]
Use Upstart and configure a service that starts on the right runlevels.

See here to get going http://upstart.ubuntu.com/getting-started.html

**Comment by PeanutBotter** [comment]
Thanks, that was great advice.

For posterity, I added a file /etc/init/runpogobot.conf, which contained:

    description "Startup the PokemonGo-Bot"
    start on runlevel [2345]
    script
            chdir /home/pogo/PokemonGo-Bot
            . bin/activate
            ./run.sh configs/config.json
    end script
