### ISSUE TITLE
Inventory is full, but it isn't

### ISSUE THREAD

**Issue by cmezh** [PokemonGoF/PokemonGo-Bot#3335]
Sorry for screenshot!
![screenshot_2016-08-10-01-26-23](https://cloud.githubusercontent.com/assets/20733365/17528616/517b98be-5e9a-11e6-8713-64792993410e.png)
Messages repeat permanently.
min_empty_space is set to 5. Tried to set it to 4 and 3, but no effect. It started to work when I set variable to 6.
Inventory is 395/400.
Prehaps, it happens when inventory free space == min_empty_space... Maybe not.

**Comment by TheSavior** [comment]
`min_empty_space` means only run when you have less than this amount of empty space. The Spin fort worker won't spin forts unless there are at least 5 spots in the bag. Sounds like these are in conflict in your config.
