### ISSUE TITLE
[Suggestion] Hangout at lured pokestop

### ISSUE THREAD

**Issue by fvorez** [PokemonGoF/PokemonGo-Bot#334]
Not an issue, not sure were else to post this, maybe have the bot stop and hang out at lured pokestops?

**Comment by ironbishop** [comment]
A cool new feature would be a parameter to recognize a multistop (3+ stops in the same area), and use a lure (if available) on all of them. Then, stay inside the lure area and catch/spin all the things. 

I already know where to find multistops around me, so i can go there with the --location parameter, and it would be awesome if the bot sticked around there. What I don't know is the time when multistops get lured by someone else, and this is where the bot could help.

**Comment by oinquer** [comment]
An easy way would be to scan pokestops around, if it has a lure it has priority.
