### ISSUE TITLE
Auto Transfert , Auto rename ( with IV ) ...

### ISSUE THREAD

**Issue by Tagada22** [PokemonGoF/PokemonGo-Bot#3345]
Hello ,

i think i don't saw options in config;json for auto-transfert pokemo ( with less 500 cp ou 80% IV for example ) 

And rename pokemon catch with the IV

Like necrobot for example 

thanks

**Comment by Calcyfer** [comment]
It's in the example configs. Ex : 

"type": "NicknamePokemon",
"config": {
          "nickname_template": "{name}_{iv_pct}"
}

"release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
}

**Comment by Tagada22** [comment]
Ok thanks ans I see that 

"// Example of keeping the 2 strongest (based$"// Zubat": {"keep_best_cp": 2, "keep_best_iv$},
"vips" : {

If i want do this for all pokemon 

Just enter "any" or add manually pokemon
