### ISSUE TITLE
Queue makes system not able to exit

### ISSUE THREAD

**Issue by joaodragao** [PokemonGoF/PokemonGo-Bot#3347]
### Expected Behavior

Control-C to exit.

### Actual Behavior

However, with this code, the system is not able to exit.

```
        try:
            self.web_update_queue.put_nowait(True)
        except Queue.Full:
            pass

    def update_web_location_worker(self):
        while True:
            self.web_update_queue.get()
            self.update_web_location()
```

### Steps to Reproduce

Please fix it.

### Other Information
OS:
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
