### ISSUE TITLE
Extract pokemon movesets before capture

### ISSUE THREAD

**Issue by shivamkalra** [PokemonGoF/PokemonGo-Bot#3348]
Is it possible to detect moveset at encounter? Can that information be used in release configuration of pokes? I would like to add my custom code at this point:

https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/cell_workers/pokemon_catch_worker.py#L85

So I could detect movesets of encountered pokemons.

**Comment by cicatiello** [comment]
should be possible: wild encounter seems to contain full pokemon data; pokemon data of course contain move1 and move2 ids.
So it should be possible to print moves, rename, release pokemon based on moves, bla bla whatever you have in mind
