### ISSUE TITLE
Problem with requirements.txt

### ISSUE THREAD

**Issue by pjdokosh** [PokemonGoF/PokemonGo-Bot#3349]
Hi guys I have problem with installing requirements.txt.
I have dev version, before the new api bot works normaly, after this i git pull my bot everything ok but if i try to install new reguirements I get this error:

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 13: ord
inal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\lovek~1\
appdata\local\temp\pip-build-hluaap\protobuf-to-dict\

Here is all command:

c:\pokemon\PokemonGo-Bot>pip install -r requirements.txt
Collecting numpy==1.11.0 (from -r requirements.txt (line 1))
  Using cached numpy-1.11.0-cp27-none-win32.whl
Collecting networkx==1.11 (from -r requirements.txt (line 2))
  Using cached networkx-1.11-py2.py3-none-any.whl
Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@a2755eb42dfe49e
359798d2f4defefc97fb8163d#egg=pgoapi (from -r requirements.txt (line 3))
  Skipping because already up-to-date.
Collecting geopy==1.11.0 (from -r requirements.txt (line 4))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==3.0.0b4 (from -r requirements.txt (line 5))
  Using cached protobuf-3.0.0b4-py2.py3-none-any.whl
Collecting requests==2.10.0 (from -r requirements.txt (line 6))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 7))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 8))
  Using cached gpsoauth-0.3.0.tar.gz
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 9))
  Using cached protobuf-to-dict-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:

    Installed c:\users\lovek~1\appdata\local\temp\pip-build-ekpv0d\protobuf-to-d
ict\.eggs\nosexcover-1.0.10-py2.7.egg
    Searching for coverage
    Reading https://pypi.python.org/simple/coverage/
    Downloading https://pypi.python.org/packages/ec/e1/19aeacc0dc40c332e16c8c572
3f3223c5899e121c642f599b23006b90cdd/coverage-4.2.win32-py2.7.exe#md5=864d60888fb
a27c356b07fa488d7e22b
    Best match: coverage 4.2
    Processing coverage-4.2.win32-py2.7.exe
    creating 'c:\users\lovek~1\appdata\local\temp\easy_install-cf6o_f\coverage-4
.2-py2.7-win32.egg' and adding 'c:\users\lovek~1\appdata\local\temp\easy_install
-cf6o_f\coverage-4.2-py2.7-win32.egg.tmp' to it
    creating c:\users\lovek~1\appdata\local\temp\pip-build-ekpv0d\protobuf-to-di
ct\.eggs\coverage-4.2-py2.7-win32.egg
    Extracting coverage-4.2-py2.7-win32.egg to c:\users\lovek~1\appdata\local\te
mp\pip-build-ekpv0d\protobuf-to-dict\.eggs
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\lovek~1\appdata\local\temp\pip-build-ekpv0d\protobuf-to-dic
t\setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "c:\python27\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 348, in __in
it__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 394, in fetc
h_build_eggs
        replace_conflicting=True,
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 826,
in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 1098,
 in best_match
        return self.obtain(req, installer)
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 1110,
 in obtain
        return installer(requirement)
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 461, in fetc
h_build_egg
        return cmd.easy_install(req)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 664, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 694, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 840, in install_eggs
        return [self.install_exe(dist_filename, tmpdir)]
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 982, in install_exe
        return self.install_egg(egg_path, tmpdir)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 933, in install_egg
        update_dist_caches(destination, fix_zipimporter_caches=False)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 1749, in update_dist_caches
        _uncache(normalized_path, sys.path_importer_cache)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 1823, in _uncache
        _update_zipimporter_cache(normalized_path, cache)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 1805, in _update_zipimporter_cache
        for p in _collect_zipimporter_cache_entries(normalized_path, cache):
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", l
ine 1784, in _collect_zipimporter_cache_entries
        if (np.startswith(normalized_path) and
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 13: ord
inal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\lovek~1\
appdata\local\temp\pip-build-ekpv0d\protobuf-to-dict\

Can somebody help me whats wrong?

**Comment by RedViper9** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation#get-encryptso-windows-part-writing-need-fine-tune

**Comment by lapukdee** [comment]
same in linux

**Comment by pjdokosh** [comment]
Tomorrow we try to repair it with one guy from slack with shared connection. He was able to solved this problem but than we get another error. Something with c++ and if we install it this shit came again and again today we try to repair it once again.

**Comment by k4n30** [comment]
@pjdokosh is this still an issue on the latest version?
