### ISSUE TITLE
Rename IV's using a hexadecimal format

### ISSUE THREAD

**Issue by metaember** [PokemonGoF/PokemonGo-Bot#3350]
## Enhancement proposition:
When renaming pokemon, there should be an option to dump the IV's as hexadecimal values. 

### Rationale
Space for the nickname is limited, and information is precious.

### Advantages: it would save space
- each double digit IV value can be reduced to a single character (so 3 letters saved)
- no longer any need for separators between values, as each is exactly one character

### Example :
`Pika13/10/12` becomes `PikachuDAC` (with two chars left to spare)

IMHO it's just as legible, should be relatively simple to implement, and saves a lot of space without increasing entropy.

**Comment by randypfohl** [comment]
This shouldn't be an issue, however this should be easily implemented, Send a pr.

**Comment by metaember** [comment]
@randypfohl Yeah sorry I'm quite new to Github. I'm not familiar enough with the code to implement it but just wanted to put this idea out there!

**Comment by Anakin5** [comment]
Alread possible if you don't mind having lower case letters:
`{iv_attack:X}{iv_defense:X}{iv_stamina:X}`
