### ISSUE TITLE
Keep getting consistently softbanned? Works fine in nox but client says im soft banned

### ISSUE THREAD

**Issue by Didlid** [PokemonGoF/PokemonGo-Bot#3351]
### Expected Behavior
Bot should run like normal

### Actual Behavior
After 1 or two captures/spins it says i'm soft banned and keeps spinning the same thing over and over.

### Steps to Reproduce
Leave bot running and eventually gets random soft ban. Log into nox and try it myself and some pokestops say "Try again" and after 2-3 spins or changing the pokestop i can collect items again. But when i go back to bot it starts over again looping saying softban

### Other Information
OS: Windows

I think maybe the servers are going on and offline which may be causing it? Anybody else having the same issue?

**Comment by SGColdSun** [comment]
Nope. Haven't gotten any unexpected softbans.

**Comment by GitPupper** [comment]
Nope. When I teleport from one area to another it realizes I'm soft banned, says it's fixing it, and about a minute later it says it's fixed and it's catching pokemon.

**Comment by randypfohl** [comment]
Is the app running on your phone?

**Comment by Didlid** [comment]
Nope i had another bot open at the same time as it but thats about it. But i even tried without the other bot running. For some reason the PTC bot works fine and keeps running yet the google acc one doesn't.

**Comment by randypfohl** [comment]
Check to see if the app is running in the background on any android phone. 

They have background threads that send requests to look for local pokemon, It has happened to me before, and the app needed to be force closed.

**Comment by Didlid** [comment]
Will do thanks, Just wondering would i be find to run two bots at the same time one ptc and one google? or would that likely cause this issue to happen? 

Seems i've fixed it by pulling the latest version. Fingers crossed

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
