### ISSUE TITLE
[feature] snipe get coord from external site

### ISSUE THREAD

**Issue by doko89** [PokemonGoF/PokemonGo-Bot#3355]
I see many who share high iv and rare pokemon coord in Discord channel or pokesnipers.com. may be added to the feature. this one of the channel http://discord.me/pokemon-go-spoofing
many tools for snipe of Discord but all only for windows, I use Ubuntu for the desktop, and I run a bot on ubuntu vps. thanks

**Comment by k4n30** [comment]
#3666 #3278 #3226
