### ISSUE TITLE
Bot not catching lured pokemon, seems to get in infinite loop state of noticing them. 

### ISSUE THREAD

**Issue by alekhurst** [PokemonGoF/PokemonGo-Bot#3362]
I have this as my catch configs in config.json

```
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
```

I have this at the top level of the config

```
   "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
```

In the older version from yesterday, and the newer version from today, I get in an infinite loop state of the bot "noticing" lured pokemon but not catching them. It looks like this:

<img width="1332" alt="screen shot 2016-08-09 at 8 01 38 pm" src="https://cloud.githubusercontent.com/assets/4837433/17537848/f87d3bae-5e6d-11e6-94bd-7053e875017c.png">

**Comment by GitPupper** [comment]
1. Try changing your location.

if that doesn't fix it (if it's for all lured pokemon)

2. Use my config as a reference. http://pastebin.com/UStttHL2

if that still doesn't work post your full config and I'll see if I can fix it. :/

**Comment by alekhurst** [comment]
Cool, will do

**Comment by andhikamaheva** [comment]
Cool! It work for me :D
I think my pokemon is full, so i can't catch anything.

**Comment by kloz8879** [comment]
I had the same problem, it ended up being my catch logic was to blame
"any": {"catch_above_cp": 300, "catch_above_iv": .85, "logic": "and"}
Seems it would cause the bot to get surrounded by pokemon that did not fall into this range and it would keep "looking" at them.

**Comment by GitPupper** [comment]
Cool! Glad to hear you guys fixed it.
