### ISSUE TITLE
MoveToMap using log.logger instead of self.logger

### ISSUE THREAD

**Issue by sandbochs** [PokemonGoF/PokemonGo-Bot#3366]
### Expected Behavior
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/cell_workers/move_to_map_pokemon.py#L177

Should be using `self.logger`

### Actual Behavior

It uses a non existent `log.logger` (not even the deprecated `logger.log`)

**Comment by k4n30** [comment]
@sandbochs can this be closed now? movetomap has had some work done since this issue was raised

**Comment by k4n30** [comment]
Waiting on PR

**Comment by mjmadsen** [comment]
@k4n30 Did this merge go through?

**Comment by k4n30** [comment]
@mjmadsen no it was closed by @solderzzc as the PR was severly outdated and not update by the OP

**Comment by k4n30** [comment]
@sandbochs is this still an issue?

**Comment by mjmadsen** [comment]
@k4n30 I'm assuming this is dead.
