### ISSUE TITLE
[Feature Request] Config for total Pokeballs, discarding lower level first

### ISSUE THREAD

**Issue by NemesisQ15** [PokemonGoF/PokemonGo-Bot#3367]
Would it be possible to set the config for total Pokeballs instead of setting different values for Pokeball, Greatball, and Ultraball, and when you hit the limit set in the config, it would discard the lower quality ones first?

Say I have it set to 200 Total_Pokeballs, and I go over that amount of the different types of pokeballs combined, it would discard Pokeballs first, then if those Pokeballs are at 0 and the total is still above 200, discard Greatballs, and if the Greatballs are at 0 and the total is still above 200, it would then discard Ultraballs till it hits 200 of them.

A slightly more complex way to get rid of Pokeballs would be to randomly "miss" when trying to capture Pokemon if above a soft cap, and then discard if you get above a hard cap, but that would probably be much hard to implement.

**Comment by WithoutWout** [comment]
I like this idea, also don't forget the same could be done to potions, as I currently have (normal) Potions, Super Potions, Hyper Potions and Max Potions. Each time I see the bot discard Hyper potions and keep (normal) Potions for example, my soul cries a little. The same goes for Revives/Max Revives when level 30+.

**Comment by PraeceptorXS** [comment]
But couldn't you just set it to only keep a certain number of certain poke balls?

**Comment by Avaryan** [comment]
I have mine set to keep, at max, 100 pokeballs. I keep all Great Balls and Ultra Balls.
I keep 10 Potions, 30 Super Potions, and keep all higher potions.

**Comment by PraeceptorXS** [comment]
Since I don't fight in gyms, I have it only keep berries and poke balls.

**Comment by TheSavior** [comment]
Sounds like you want this: https://github.com/PokemonGoF/PokemonGo-Bot/pull/3135

**Comment by Whosdaman** [comment]
There was config for "Anyball" that was added awhile back. Unsure if that still works or not.

**Comment by Whosdaman** [comment]
#2140 #2166 #2459 #2284

**Comment by WithoutWout** [comment]
Very informative references, I've learned this "anyball" feature was available for a short while, it was reverted for some reason though... It should definitely come back in my opinion, including AnyPotion and AnyRevive.

**Comment by k4n30** [comment]
#4005
