### ISSUE TITLE
Incense options

### ISSUE THREAD

**Issue by takenek** [PokemonGoF/PokemonGo-Bot#3376]
Hello Guys,
There is any option to force bot to use Incense?
I try find in config.json i see to use lucky eggs but no luck with Incense.
Will be awsome if there is option to use Incense + Lucky Eggs.

Best Regards
TaKeN

**Comment by LostDGod** [comment]
The bot doens't detect incense spawned pokemons.

**Comment by Gobberwart** [comment]
Ok, so change this to use incense and detect incense-spawned pokemon. Seems like two feature requests maybe?

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by k4n30** [comment]
@takenek Are you still after this? If so would you mind updating your FR to the new FR template with the following headings so that others may be more likely to assist you

Short Description

Possible solution

How it would help others

**Comment by takenek** [comment]
Thanks i update everyday :-)

Best Regards

**Comment by k4n30** [comment]
So you no longer want this?

**Comment by takenek** [comment]
A sorry i missunderstand of course i want it :-)

**Comment by k4n30** [comment]
@takenek Can you please follow instructions in https://github.com/PokemonGoF/PokemonGo-Bot/issues/3376#issuecomment-240724220 please

**Comment by takenek** [comment]
Interesting when i click to link nothing open ;-) open me this i don`t see any instruction :]

**Comment by k4n30** [comment]
My first comment is what it links to (same for your other FR):

> If so would you mind updating your FR to the new FR template with the following headings so that others may be more likely to assist you

> 

> Short Description
> 
> Possible solution
> 
> How it would help others

**Comment by takenek** [comment]
Cool i see Your post but i don`t see this template.... i don`t know what i must do :-(

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/new

That's the link to make a new one, just copy (and cancel creating a new one) and paste it into your original post and add detail as necessary :)
