### ISSUE TITLE
SoftBan Flag on Startup

### ISSUE THREAD

**Issue by tr33s** [PokemonGoF/PokemonGo-Bot#3377]
It would be nice to be able to force the softban handler to run on start up so we can teleport to locations and catch the pokemon there without them vanishing.

**Comment by dwangfeng** [comment]
good suggestion.

**Comment by Gobberwart** [comment]
Yes, but only if a softban is in effect. No point delaying startup for no reason.

**Comment by fari-99** [comment]
well, if i got softban, i just delete catch task, and after not got softban, i restart the bot and active the catch task. 

note: if you go to fort first instead catch pokemon, the softban task will handle it.

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by mjmadsen** [comment]
This is no longer a workaround.
