### ISSUE TITLE
[Suggestion] Small Randomization of Location on Startup

### ISSUE THREAD

**Issue by tr33s** [PokemonGoF/PokemonGo-Bot#3379]
It would be nice to slightly randomize the location on startup so we are not jumping back to the same place every time the bot is restarted.

**Comment by leadboots5** [comment]
Is there a reason you don't use the location cache to start up the same place it ended?

**Comment by tr33s** [comment]
@leadboots5 Does it do that automatically because if so I was unaware of that.

**Comment by lhung** [comment]
@tr33s `location_cache = true` in config.json. It is turned on by default.

**Comment by 1cu** [comment]
But not if you start the bot with `-l` to override the start location.

**Comment by Gobberwart** [comment]
If you have anything in the "location" setting in config.json. It will "jump" back to same place every time, even if location_cache = true. I tend to start the bot with a "location" setting, then remove that setting for future restarts.

**Comment by N3W4L** [comment]
As you may have noticed, after 1 or 2 h running, the bot find less and less pokemons, it could be great to have a "Jump" option happening every 1 or 2 hours in order to jump the bot at others well known places.
