### ISSUE TITLE
Crash during farm

### ISSUE THREAD

**Issue by gpires** [PokemonGoF/PokemonGo-Bot#338]
### Actual Behavior

> [x] Using Pokeball...
> [x] Captured Golbat! [CP 596]
> [#] Finished walking
> Arrived at Pokestop
> Traceback (most recent call last):
>   File "C:\Users\User\Desktop\PokemonGo-Bot-dev\pokecli.py", line 107, in <module>
>     main()
>   File "C:\Users\User\Desktop\PokemonGo-Bot-dev\pokecli.py", line 104, in main
>     bot.take_step()
>   File "C:\Users\User\Desktop\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 31, in take_step
>     self.stepper.take_step()
>   File "C:\Users\User\Desktop\PokemonGo-Bot-dev\pokemongo_bot\stepper.py", line 58, in take_step
>     self._work_at_position(position[0], position[1], position[2], True)
>   File "C:\Users\User\Desktop\PokemonGo-Bot-dev\pokemongo_bot\stepper.py", line 100, in _work_at_position
>     self.bot.work_on_cell(cell, position, pokemon_only)
>   File "C:\Users\User\Desktop\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 52, in work_on_cell
>     hack_chain = worker.work()
>   File "C:\Users\User\Desktop\PokemonGo-Bot-dev\pokemongo_bot\cell_workers\seen_fort_worker.py", line 45, in work
>     fort_details = response_dict['responses']['FORT_DETAILS']
> KeyError: 'FORT_DETAILS'
> 

### Steps to Reproduce
Farm normally...

**Comment by solderzzc** [comment]
which branch?

**Comment by gpires** [comment]
Probably due encoding?

### Other Information
OS: Win10
Git Commit: cb3d799b0c143ee0ad28aee9d50be7d4e13587c1

**Comment by ludicures** [comment]
This is the same issue as reported https://github.com/PokemonGoF/PokemonGo-Bot/issues/348 and is due to  response_dict['responses'] returning

{
  "status_code": 102, 
  "responses": {}
}

**Comment by surfaace** [comment]
Please clarify if issue still persists for you with latest dev

**Comment by gpires** [comment]
Its Fixed. Thanks
