### ISSUE TITLE
Egg Hatching logs do not truncate IV

### ISSUE THREAD

**Issue by bstpierr** [PokemonGoF/PokemonGo-Bot#3381]
### Expected Behavior

Egg hatching log output should match the rest of the log output.

### Actual Behavior

Log output does not match the rest of the bot's output.

`[23:27:12] Egg hatched with a Magmar (CP 1244 - IV 10/14/11 0.777777777778), 1000 exp, 2780 stardust and 27 candies.`

compared to the release output:

`[23:27:14] Exchanged Magmar [CP 1244] [IV 0.78] for candy.`

I'd expect the same `MonName [CP ###] [IV #.##]` output.

It might be worth adding this sort of string output formatting to the utils class.

**Comment by leadboots5** [comment]
Looks like it just needs to be changed over yet to using the inventory class(unless there is a reason this should be in utils instead of inventory?). Looks like transferring was just moved over to it:
https://github.com/PokemonGoF/PokemonGo-Bot/commit/8b5af8d766ac161be926932b05e3fc785a33661d

**Comment by bstpierr** [comment]
Didn't realize the Inventory class was now in. That sounds perfect for this.

**Comment by mjmadsen** [comment]
Seems resolved.
