### ISSUE TITLE
[Suggestion] commands on terminal

### ISSUE THREAD

**Issue by madalilng** [PokemonGoF/PokemonGo-Bot#3382]
i'm thinking on terminal commands.
like for example
when i enter 
i : list items in inventory
c : character information (name,exp,level , etc.)
p : pokemon lists.

or for some functions like
reload config
reload path
restart
relog

**Comment by Ph4i1ur3** [comment]
For the interim: Setting up the web server displays most of the relevant information that you are requesting

**Comment by leadboots5** [comment]
I think some of that can also be put in the window title if you want.

**Comment by Gobberwart** [comment]
I quite like the keyboard hook idea. Press i at any time displays current inventory. Nice idea.

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by mjmadsen** [comment]
Do we find it satisfactory to configure how often different tasks output data?

**Comment by k4n30** [comment]
@mjmadsen i'd say this feature request has been met, just not in the original form requested. If you really want to know stats, stop and restart bot (it's starts in the same place anyway) or change the frequency of the stats display
