### ISSUE TITLE
[Suggestion] Add support for separate json file for credentials

### ISSUE THREAD

**Issue by newjanson** [PokemonGoF/PokemonGo-Bot#3383]
Maintaining more than 3 config files is a nightmare, and since new parameters are being added rapidly, it would be nice to have one config file with bot specific credentials, and one config file for general parameters like tasks. Thoughts?

**Comment by tr33s** [comment]
Yes, this is a good idea.

**Comment by flopk** [comment]
I use separate config1.json/config2.json files and just created new run.sh files to point to each config. It seems to work ok.

**Comment by newjanson** [comment]
The complications happen when they change something in the config. ie: Change the way spinning pokestops work, then you need to change that in both files. Which is fine if you only have 2, but when you have like 4-5 it is pretty annoying if you have to change EVERY SINGLE ONE. I am proposing the idea that you make cred1.json,cred2.json,cred3.json, etc. with only the Usernames/passwords/Google API keys in it, and config.json with everything else, and if you need to change something, you would be able to change it in one place.

**Comment by Ph4i1ur3** [comment]
Create different shell files as @tr33s suggesting, but use the -u, -p, -k parameters when launching pokecli.py

**Comment by newjanson** [comment]
fixed in 61de70f7829066edb THANK YOU!
