### ISSUE TITLE
Cannot release Nidoran ♂ and Nidoran ♀

### ISSUE THREAD

**Issue by anhkhoi** [PokemonGoF/PokemonGo-Bot#3384]
I see in my poke bag, Nidoran seem as can not release.

**Comment by Ph4i1ur3** [comment]
Have you tried setting configuration for "Nidoran M" and "Nidoran F"?

**Comment by anhkhoi** [comment]
I don't see those names in config file. I'll try it.

**Comment by anhkhoi** [comment]
Oh, it's works. Thanks @Ph4i1ur3
