### ISSUE TITLE
Show Total Candies when transferring & evolving (in addition to capturing)

### ISSUE THREAD

**Issue by CykkaTron** [PokemonGoF/PokemonGo-Bot#3385]
After transferring a pokemon and receiving the  candy it would be nice to see the total amount listed.  

Edit:

So I guess I didn't explain lol. 

Anyways as I have my config set to evolve, and then it transfers if it doesn't meet req's so at that point I'd like to see whats left.

**Comment by leadboots5** [comment]
It shows when you catch a pokemon. You're wanting it to show a few lines later that it incremented by 1?

**Comment by Ph4i1ur3** [comment]
I really don't see a need to make the inventory call again that soon afterwards.

**Comment by CykkaTron** [comment]
So I'm unsure why mine doesn't show right after catching?? I just went back to check and nothing when catching.

**Comment by leadboots5** [comment]
You are maybe on to master/too old of a commit. There was an update about 6 hours ago that added it I believe:
https://github.com/PokemonGoF/PokemonGo-Bot/pull/3320

**Comment by CykkaTron** [comment]
LOL yup that's it, didn't even notice.

**Comment by Gobberwart** [comment]
I'm not sure that's quite what the request was. @CykkaTron asked for the number of candies to be displayed after transfer... and possibly evolve too.

eg.

[TransferPokemon] [INFO] [pokemon_release] Exchanged Pidgey [CP 90] [IV 0.4] for candy.
[TransferPokemon] [INFO] [gained_candy] You now have 28 Pidgey candy!

At the moment, the bot only shows the total number of candy after capturing a pokemon.
