### ISSUE TITLE
No usable pokeballs found! [Endless loop]

### ISSUE THREAD

**Issue by llcashll** [PokemonGoF/PokemonGo-Bot#3386]
### Expected Behavior
Utilize whatever balls are remaining in inventory.

### Actual Behavior
When Pokeballs are depleted, it will not switch to Great or Ultra balls and will get stuck in an endless loop.

### Your config.json (remove your credentials and any other private info)
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Greatball":      { "keep" : 100 },
            "Ultraball":      { "keep" : 200 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 0 },
            "Hyper Potion":   { "keep" : 0 },
            "Max Potion":     { "keep" : 20 },
            "Revive":         { "keep" : 0 },
            "Razz Berry":     { "keep" : 100 }

### Steps to Reproduce
Run out of Pokeballs, while having other balls in inventory.

### Other Information
OS: Mac OSX 
Git Commit: 8b5af8d766ac161be926932b05e3fc785a33661d
Python Version: Python 2.7.10

![image](https://cloud.githubusercontent.com/assets/20940752/17541754/92a9ea7a-5e90-11e6-8ca3-e10a8166bb02.png)

**Comment by Ph4i1ur3** [comment]
Is your VIP set to true, and are you positive that you have great balls?

**Comment by shoelsch** [comment]
Encountered this same error with 100 ultra balls in my bag.

**Comment by llcashll** [comment]
VIP is enabled, but shouldn't matter for this. I also [now] have 0 Greatballs and 120 Ultraballs. Should default to using Ultraballs.

![image](https://cloud.githubusercontent.com/assets/20940752/17552834/575bd100-5ed0-11e6-99ee-a99550dbefce.png)

**Comment by Ph4i1ur3** [comment]
When VIP is enabled the maximum the bot will use is a great all currently, turning off VIP should allow it to use ultraballs

**Comment by N3W4L** [comment]
@shoelsch Thanks for your help :)
