### ISSUE TITLE
[Suggestion] Save Player State/Information In File

### ISSUE THREAD

**Issue by pacpac42** [PokemonGoF/PokemonGo-Bot#3387]
Hi, would it be possible to save the player state/information in a json/text file in the data folder? 
The state information should include list of pokemons (most important) with their IVs, and everything that is currently printed at startup. This will also remove the need to print that at startup, and will allow all of us to inspect our lists of pokemons and other information without having to run the client. Thank you. 

E.g.
```
Pokemon      CP        IV          A        D        S
Psyduck      515       0.16        10       2        3
Pidgey       189       0.36        0        13       2
Staryu       201       0.38        7        2        15
...

Item       #
Pokeball   5
...
```

**Comment by Ph4i1ur3** [comment]
it kind of already is in the /web folder. Would be nicer to have it organized as you demonstrated. For the time being the web server provides the information you are asking for, and can be run separately from the bot

**Comment by pacpac42** [comment]
Ah I missed that. I agree that it would be great if all that information could be easily exported, but this does not seem to be very necessary at this point in time. Thanks for explaining.

**Comment by omeryagmurlu** [comment]
Made a plugin
https://github.com/omeryagmurlu/PokemonGo-Bot-exportfile-plugin

**Comment by pacpac42** [comment]
Awesome and thank you! It looks like there are also online tools to convert json to csv easily so i'll close this ticket.
