### ISSUE TITLE
Many pokemons vanished continiously

### ISSUE THREAD

**Issue by jboffel** [PokemonGoF/PokemonGo-Bot#3389]
When under softban it seems all attempt to catch a pokemon will actually fail in pokemon vanish and the impossibility to use a berry.

Is it possible to avoid throwing items for nothing and wait for some time when this happen by changing the configuration?

**Comment by Ph4i1ur3** [comment]
I defer you to: #3377

**Comment by Gobberwart** [comment]
Errr... yep. That's what happens when softbanned. Wait a few minutes and it should be fine.
