### ISSUE TITLE
[BUG] RecycleItems overflows the given limit

### ISSUE THREAD

**Issue by rendyep** [PokemonGoF/PokemonGo-Bot#3392]
Hi, I have updated to the latest dev, and seems like now the RecycleItems doesn't function correctly.

Example: I limit the Pokeball to 50, but there are now 81 Pokeballs in my inventory and they keep counting after visiting pokestop.

Here is my json config:

```json
{
    "type": "RecycleItems",
    "config": {
        "min_empty_space": 0,
        "item_filter": {
            "Pokeball":       { "keep" : 50 },
            "Greatball":      { "keep" : 100 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 50 },
            "Revive":         { "keep" : 20 },
            "Razz Berry":     { "keep" : 20 }
        }
    }
}
```

**Comment by DK4cm** [comment]
"min_empty_space" set to 0, so the recycle will start when the bag is full.
You can remove/comment this line and it will recycle everytime you get a new items.

**Comment by TCB13** [comment]
@DK4cm I don't have `min_empty_space` on my config and I'm having the same issue as @rendyep .

**Comment by BriceSD** [comment]
@TCB13 It’s not an issue. The RecycleItems task will run only when your inventory reaches a limit. By default it’s 6. You can change this parameter with ``` min_empty_space ```. Once you inventory reach 345 items it’ll start discarding items. 
Setting ```min_empty_space``` to your inventory size should trigger the recycling task every tick

**Comment by TCB13** [comment]
@BriceSD great tip! Thanks.

**Comment by k4n30** [comment]
Fixed in latest version
