### ISSUE TITLE
Endless loop between stops that are too close to each other

### ISSUE THREAD

**Issue by jj2003** [PokemonGoF/PokemonGo-Bot#3394]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. Are you running `master`? We work on the `dev` branch and then add that functionality to `master`. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.

### Expected Behavior

Walks from stops to stops

### Actual Behavior

Stuck between choosing stops (endless loop)

2016-08-10 01:01:55,888 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop1 - 0.05km
2016-08-10 01:01:57,489 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop2 - 0.06km
2016-08-10 01:01:59,858 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop2 - 0.05km
2016-08-10 01:02:01,358 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop1 - 0.05km
2016-08-10 01:02:03,191 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop2 - 0.05km
2016-08-10 01:02:06,022 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop1 - 0.05km
2016-08-10 01:02:08,117 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop2 - 0.05km
2016-08-10 01:02:09,753 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop1 - 0.05km
2016-08-10 01:02:12,520 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop2 - 0.05km
2016-08-10 01:02:14,315 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop1 - 0.05km
2016-08-10 01:02:15,857 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop2 - 0.05km
2016-08-10 01:02:18,404 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop2 - 0.05km
2016-08-10 01:02:20,769 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop1 - 0.05km
2016-08-10 01:02:22,447 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop2 - 0.05km
2016-08-10 01:02:25,052 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop1 - 0.05km
2016-08-10 01:02:26,868 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop2 - 0.05km
2016-08-10 01:02:28,551 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop1 - 0.05km
2016-08-10 01:02:30,207 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop2 - 0.05km
2016-08-10 01:02:31,825 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop1 - 0.05km
2016-08-10 01:02:34,809 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop2 - 0.06km
2016-08-10 01:02:36,355 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Stop2 - 0.05km
2016-08-10 01:02:36,575 [PokemonGoBot] [INFO] [bot_exit] Exiting bot.

### Your config.json (remove your credentials and any other private info)
```
your config here
```

### Steps to Reproduce

Stand between two stops?

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by Ph4i1ur3** [comment]
You should really fill out the parts of the issue form you ignored, instead of ignoring them. It really helps narrow the issue you are having. (Config, Commit)

**Comment by gorcsev71** [comment]
the same happens to me. OSX 10.00.6; python 2.7.12

**Comment by maestroi** [comment]
For the sake of all that is holy, ADD your commit AND config.

**Comment by Hoaas** [comment]
I have the same problem. Tried changing the order of MoveToFort and FollowPath, but then it did not seem to move at all.

`{
    "auth_service": "ptc",
    "username": "",
    "password": "",
    "location": "",
    "gmapkey": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "evolve_all": "all",
          "order_by": "iv",
          "evolve_iv_min": 0.6,
          "evolve_speed": 20,
          "use_lucky_egg": false
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 20 },
            "Greatball":      { "keep" : 45 },
            "Ultraball":      { "keep" : 75 },
            "Potion":         { "keep" :  5 },
            "Super Potion":   { "keep" : 10 },
            "Hyper Potion":   { "keep" : 20 },
            "Revive":         { "keep" : 20 },
            "Razz Berry":     { "keep" : 80 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort"
      },
      {
        "type": "FollowPath",
        "config": {
            "path_mode": "loop",
            "path_file": "configs/my_secret_path.json"
        }
      }
    ],
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 14.5,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or" }
    },
    "release": {
        "any": {
            "keep_best_iv": 1,
            "keep_best_cp": 1,
            "logic": "and"
          }
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}`

**Comment by cyberhck** [comment]
I've the same problem, since this issue didn't give full info to developers, I'm using your github's template:


> Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.

Yes, it was working, and in middle of execution I discovered this issue
> Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.

Yes, and it turned out to be this one, I was about to create a new issue

> Are you running `master`? We work on the `dev` branch and then add that functionality to `master`. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.

Yes I'm on master, not sure if this has been fixed

### Expected Behavior
When two pokestop are very close, it should pick one and move to that stop (check if you can swipe both from that location)

### Actual Behavior
It tries both, so it gets in a loop

### Your config.json (remove your credentials and any other private info)
```
{
    "auth_service": "google",
    "username": "myemailyoucanfinditongithubisuppose",
    "password": "myactualpasswordnotthisdonttrythisplease",
    "location": "13.680587, 100.609360",
    "gmapkey": "PRIVATE",
    "libencrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}
```

### Steps to Reproduce

Not sure, but starting at (13.680587, 100.60936, 0) should do it
### Other Information
OS: 
`uname -a` reveals:
>Linux my_computer_name 4.4.0-34-generic #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Git Commit: `63f777bac0c8cdc75d07f9ef491ca8b900c0148a`
Python Version: `Python 2.7.12`

**Comment by cyberhck** [comment]
By the way, quick workaround is to just delete `data/last-location-<your_username>.json`
Just do a `rm data/last-location` and press `Tab` and it should autocomplete and hit enter key and you can run again, but be careful, do it maybe after a while as it's gonna teleport as it'll start from starting point :)

**Comment by bibibkamal** [comment]
@cyberhck i deleted the data/last-location-<your_username>.json but still stuck on the loop. it just keep moving without doing anything

**Comment by cyberhck** [comment]
@bibibkamal , did you delete last-location-.json? that doesn't seem right, you didn't have your username in there?

**Comment by bibibkamal** [comment]
@cyberhck yes i deleted the last-location.json. what do you mean by username? in my config? of course i put my username in it

**Comment by cyberhck** [comment]
Can you post what directories you have under data directory?

**Comment by lliuyingjie** [comment]
@cyberhck  sir,  the last-location_username.conf has been deleted , but  the loop going on

**Comment by cyberhck** [comment]
@lliuyingjie , that means it's still going to the same location in a while, so what you can probably do is: change the location you initially start, or open last-location-username.json and change the coordinates to new one. And please be informed, this isn't a permanent fix, if you get this issue again, you've to the process again :)

**Comment by capitancardoza** [comment]
Hello there,
I might have found a solution (don't know if temporary or not):
deleting the "last-location-<username>.json" file didn't work for me, so.. I tried deleting the

**## "cells-<username>.json"**

It's working pretty much fine right now, not looping from the last time I started it, about 20 minutes ago.

**Comment by RedViper9** [comment]
Hey folks, if any of you are still having this problem, try one of the solutions suggested in #3646 . Let me know how it goes.

Forcing a manual location change does get you out of the jam.

**Comment by k4n30** [comment]
#3475 #3394 #3646
