### ISSUE TITLE
Make starred Pokemon stay in your inventory

### ISSUE THREAD

**Issue by aconite33** [PokemonGoF/PokemonGo-Bot#34]
Testing this out, found out that it grinded all my pokemon into candy that didn't meet my CP threashold, even the pokemon I had in my inventory, not just the pokemon I caught while running the bot.

**Comment by EvilSupahFly** [comment]
I encountered the same problem, and re-ran the bot with CP of 1 to keep everything this time, hoping to rebuild my collection (I lost 9 Eevees, and a couple rare ones I hatched from eggs).

**Comment by maestroi** [comment]
please iis this on dev or master?
Its fixed in dev @douglascamata close?
