### ISSUE TITLE
Hangs after walking to XXXXX until Ctrl + C is pressed to resume

### ISSUE THREAD

**Issue by bsjpark** [PokemonGoF/PokemonGo-Bot#3401]
This is same as issue  #827 that was raised before. Only thing is I see exactly the same behavior with OSX El Capitan Console when I run the cli. I was wondering if anyone have seen or know the fix to this.

Expected Behavior

Going to the next PokeStop and catching pokemon on the go

Actual Behavior

Bot hangs at Walking to XXXXXXXXX until I press Ctrl + C then it immediately starts encountering and catching pokemon and resumes running fine. It then hangs again after a couple minutes of running perfectly. Same way to kick it back into action.

Steps to Reproduce

Just let the bot run for 10 min to an hour and it hangs at a Walking to XXXXX until Ctrl + C is presset to resume for some reason.

Other Information

OS: OS-X El Capitan 10.11.5 (15F34)
Running Dev version

**Comment by mrgohamilton** [comment]
Having this problem however it arises every time from the start of the bot. 

1. bot logs in
2. bot says theres a level up reward being collected (which there shouldn't be on every start)
3. bot [followspiral] walks from XXXXXX(position1) to XXXXXX (position2)
4. bot continues to walk from position1 to position2  and vice versa without catching/evolving/transferring items or spinning pokestops

**Comment by dezayner** [comment]
Probably Niantic bans your IP

**Comment by bsjpark** [comment]
Lol, just may be. If IP is banned, I would assume, when I pressed Ctrl-C, it would have continue to catch/walk/etc. It still does. Same goes when I kill the script and run it again. That's the odd thing about it.

**Comment by k4n30** [comment]
Update please
