### ISSUE TITLE
[Suggestion] Activate Lucky Egg at Start Without Evolutions.

### ISSUE THREAD

**Issue by pacpac42** [PokemonGoF/PokemonGo-Bot#3404]
Hi, would it be possible to activate lucky egg at startup without having to evolve anything? Thanks.

EDIT: This is primarily because I want to save my candy for now, in case I catch a pokemon with better IVs. Also, if this feature is implemented, it could be used for incense (although it would be less useful for lure).

**Comment by CoderFX** [comment]
Why would anyone want to do that? That would be just losing xp

**Comment by licklake** [comment]
Maybe for users that invest money in their boted account and buy lucky eggs (whyever you should do that)

**Comment by k4n30** [comment]
#3911 You can't both win :p

**Comment by k4n30** [comment]
@pacpac42 still after this?

**Comment by pacpac42** [comment]
@k4n30 i stop using the bot so closing this ticket
