### ISSUE TITLE
Evolution changes?

### ISSUE THREAD

**Issue by raxxon** [PokemonGoF/PokemonGo-Bot#3408]
### Expected Behavior

Bot evolves pokemon and then processes further

### Actual Behavior

Bot evolves a few pokemon on start and then ignores the rest/recycles new targets on acquisition - Bot never evolves ALL available specified pokemon despite an excess of candies and never evolves any pokemon after initial load

### Your config.json (remove your credentials and any other private info)
```
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "evolve_all": "Pidgey,Rattata,Weedle,Zubat,Caterpie,Spearow,Krabby,Staryu,Tentacool",
          "evolve_speed": 20,
          "evolve_cp_min": 10,
          "use_lucky_egg": false
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "1":        { "keep" : 25 },
            "2":        { "keep" : 100},
            "3":        { "keep" : 100},
            "101":    { "keep" : 0 },
            "102":    { "keep" : 0 },
            "103":    { "keep" : 0 },
            "104":    { "keep" : 50 },
            "201":    { "keep" : 20 },
            "202":    { "keep" : 30 },
            "701":    { "keep" : 25 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_file": "************************"
        }
      }
    ],
```

### Steps to Reproduce

Run bot with Tasks configured as above

### Other Information
OS: Windows 10.1 (Bash Shell, Ubuntu)
Git Commit: 
hazer@BREAKPOINT:~/PokemonGo-Bot$ git log -n 1 --pretty=format:"%H" ; python -V
67fe00bcfc04fb6ddd2c78ca208aad4e4cbf2523
Python 2.7.6
hazer@BREAKPOINT:~/PokemonGo-Bot$

**Comment by extink** [comment]
There is a new config option `"evolve_captured": "NONE"`, see #3292

**Comment by raxxon** [comment]
Ah. It appears that hasn't been documented in the Wiki area yet. Thanks for the info. :)

**Comment by raxxon** [comment]
added evolve_captured, configured to match evolve_all, no change... bot is still not evolving pokemon. :|

**Comment by extink** [comment]
```
{
	"type": "EvolvePokemon",
	"config": {
		"evolve_all": "Caterpie, Weedle, Pidgey, Rattata, Spearow, Psyduck, Poliwag, Slowpoke, Drowzee, Goldeen, Staryu, Magikarp",
		"evolve_captured": "Caterpie, Weedle, Pidgey, Rattata, Spearow, Psyduck, Poliwag, Slowpoke, Drowzee, Goldeen, Staryu, Magikarp",
		"first_evolve_by": "iv",
		"evolve_above_cp": 0,
		"evolve_above_iv": 0,
		"logic": "and",
		"evolve_speed": 20,
		"use_lucky_egg": false
	}
},
```

This is mine EvolvePokemon task, which is working at the moment

**Comment by raxxon** [comment]
Looks like that's it... I removed the above cp/iv and logic tags as they didn't appear to impact things before... Now the bot is evolving everything and purging the backlog of excess birds.

Thanks. :D
