### ISSUE TITLE
[Suggestion] - Hunt Rare Pokemon 

### ISSUE THREAD

**Issue by TSM-EVO** [PokemonGoF/PokemonGo-Bot#341]
Enchancement: 

Include logic to allow the bot to hunt Rare pokemon with priority.

Maybe this means integrating with an existing system like[ Pokemongo-Finder ](https://github.com/malosaa/PokemonGo-Finder)

Or allow the user to fill out a config file with the names of the 'rare' pokemon they want to hunt

Then, when that pokemon appears on their local map, maybe within the cell range, the bot stops doing what it's doing and heads directly for that pokemon (if it can get there in time)

**Comment by solderzzc** [comment]
How do we define Rare pokemon?

**Comment by TSM-EVO** [comment]
As mentioned, a config file, or a csv, or an ini, where the end-user can add pokemon names/IDs in a comma separated list. 

See the https://github.com/malosaa/PokemonGo-Finder readme for an example of their config file. Theirs just looks like this:

  "notify": "dratini,magnemite,electabuzz,hitmonchan,hitmonlee,chansey,lapras,snorlax,porygon,mew,mewtwo,moltres,zapdos,articuno,ditto,seel,gyarados,cubone",
