### ISSUE TITLE
Berries and balls count not always updated

### ISSUE THREAD

**Issue by cmezh** [PokemonGoF/PokemonGo-Bot#3411]
3 berry throws and always "have 2". Last one with error.
![screenshot_2016-08-10-14-45-58](https://cloud.githubusercontent.com/assets/20733365/17546029/4b1c0876-5f0a-11e6-9d80-6d007930e96e.png)

One more haopening
![screenshot_2016-08-10-14-58-19](https://cloud.githubusercontent.com/assets/20733365/17546154/eb8f347c-5f0a-11e6-9efa-7951c6667646.png)

Same thing happens with Ultraballs. Probably, not only with Ultra- ones.
![screenshot_2016-08-10-16-42-16](https://cloud.githubusercontent.com/assets/20733365/17549281/add2d31e-5f19-11e6-8fe1-2014eacbc4a0.png)

**Comment by cmezh** [comment]
One more
![screenshot_2016-08-10-14-58-19](https://cloud.githubusercontent.com/assets/20733365/17546154/eb8f347c-5f0a-11e6-9efa-7951c6667646.png)

**Comment by cmezh** [comment]
Same thing happens with Ultraballs. Probably, not only with Ultra- ones.
![screenshot_2016-08-10-16-42-16](https://cloud.githubusercontent.com/assets/20733365/17549281/add2d31e-5f19-11e6-8fe1-2014eacbc4a0.png)

**Comment by Ph4i1ur3** [comment]
This looks like you may be on an older commit, which are you using?

**Comment by cmezh** [comment]
Almost latest
01bc14de0543196de6688dc6bd560739db59fd14
Nothing related to this issue was changed since this commit was merged to
dev.

10 авг. 2016 г. 19:02 пользователь "Ph4i1ur3" <notifications@github.com>
написал:

**Comment by cmezh** [comment]
Update: it happens always when catching several pokemons in one turn of task, even if catch completes successfully.
![screenshot_2016-08-10-23-17-33](https://cloud.githubusercontent.com/assets/20733365/17561621/20a55754-5f51-11e6-89f1-947593591522.png)

**Comment by cmezh** [comment]
#3496

**Comment by cmezh** [comment]
Fixed #3496
