### ISSUE TITLE
Keeps walking

### ISSUE THREAD

**Issue by Billy2Kid** [PokemonGoF/PokemonGo-Bot#3415]
### Expected Behavior

Spun pokestop
Capture pokemon

### Actual Behavior

Keeps walking

### Other Information
OSX El capitan
Git Commit: 
01bc14de0543196de6688dc6bd560739db59fd14
Python Version: 
Python 2.7.11

**Comment by Tetranima** [comment]
Same here. Bot is walking only and it does not even affects eggs incubation.

**Comment by razithekillers** [comment]
API update again?

**Comment by junibrosas** [comment]
Same here. "Skipping Recycling of Items. 110 space left in bag." and "Walking from"

**Comment by ariefbayu** [comment]
I think some commit screwed the path algorithm. Take a look at this:
<img width="318" alt="screen shot 2016-08-10 at 3 58 17 pm" src="https://cloud.githubusercontent.com/assets/55084/17547916/96df4ddc-5f13-11e6-9c48-d9eb8e0adc22.png">

Based on commit `01bc14de0543196de6688dc6bd560739db59fd14`

**Comment by junibrosas** [comment]
Some people say its IP banned.

**Comment by Fizcko** [comment]
I have got the same problem this morning, just move the bot from a close location by changing the location value in the config.json file

**Comment by Billy2Kid** [comment]
Worked for me !
Closing issue
