### ISSUE TITLE
Task Priority - Evolve vs Release

### ISSUE THREAD

**Issue by raxxon** [PokemonGoF/PokemonGo-Bot#3416]
### Expected Behavior

Tasks are executed in order that they are listed

### Actual Behavior

Evolve task is not given priority to release task

### Your config.json (remove your credentials and any other private info)
```
   "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "evolve_all": "Pidgey,Rattata,Weedle,Zubat,Caterpie,Spearow,Krabby,Staryu,Tentacool",
          "evolve_captured": "Pidgey,Rattata,Weedle,Zubat,Caterpie,Spearow,Krabby,Staryu,Tentacool",
          "evolve_speed": 20,
          "first_evolve_by": "iv",
          "evolve_above_cp": 0,
          "evolve_above_iv": 0,
          "logic": "and",
          "use_lucky_egg": false
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "1":      { "keep" : 25 },
            "2":      { "keep" : 100},
            "3":      { "keep" : 100},
            "101":    { "keep" : 0 },
            "102":    { "keep" : 0 },
            "103":    { "keep" : 0 },
            "104":    { "keep" : 50 },
            "201":    { "keep" : 20 },
            "202":    { "keep" : 30 },
            "701":    { "keep" : 25 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_file": "*****************"
        }
      }
    ],
```

### Steps to Reproduce

With the task list above one would expect that the bot would evolve a pokemon before considering the release options. Capture happens, the task list is looped back to the start (after checks for FortSpin and FollowPath is updated) and the Evolve task is encountered before the Transfer task. This is not how it's currently working as it will capture a pokemon and then release it on the spot. This is leading to a major excess in candies being collected and is wasteful in terms of XP gain as 'trash' pokemon can be evolved for 12 candies and then thrown away if they're not worth keeping. If we don't have the 12 candies *then* the trash pokemon can be ditched to keep storage under control.

Additional Note:  Hatched Pokemon get evolved before release. Only Captured Pokemon appear to be ignored.
```
[04:41:02] Egg hatched with a Caterpie (CP 245 - IV 15/10/15 0.888888888889), 200 exp, 764 stardust and 10 candies.
[04:41:02] Attempting to apply incubator EggIncubatorProto1811189268915205225 to egg 17407111328320799849
[04:41:02] Incubating a 2.0 egg.
[04:41:05] Successfully evolved Caterpie with CP 245 and IV 0.89!
[04:41:24] Releasing Metapod (CP 266/IV 0.89) based on rule: CP < 275 OR IV < 0.8
[04:41:25] Exchanged Metapod [CP 266] [IV 0.89] for candy.
```

**Comment by Fizcko** [comment]
This will be a great modification. Make evolve a Pokemon gives +500PX, so for the recurring Pokemons this is a lot of PX

**Comment by extink** [comment]
You need to swap the `TransferPokemon` and the `EvolvePokemon` task to let it work in that order.

For example I have this
```
{
	"type": "TransferPokemon"
},
{
	"type": "EvolvePokemon",
	"config": {
		"evolve_all": "Caterpie, Weedle, Pidgey, Rattata, Spearow, Psyduck, Poliwag, Slowpoke, Drowzee, Goldeen, Staryu, Magikarp",
		"evolve_captured": "Caterpie, Weedle, Pidgey, Rattata, Spearow, Psyduck, Poliwag, Slowpoke, Drowzee, Goldeen, Staryu, Magikarp",
		"first_evolve_by": "iv",
		"evolve_above_cp": 0,
		"evolve_above_iv": 0,
		"logic": "and",
		"evolve_speed": 20,
		"use_lucky_egg": false
	}
},
```

Which results in the following logs
```
[11:39:17] Something rustles nearby!                                                                                                                                                                    
[11:39:18] A wild Rattata appeared! [CP 256] [Potential 0.49] [A/D/S 11/5/6]
[11:39:22] Used Pokeball, with chance 35.29 (49 left)
[11:39:22] Rattata capture failed.. trying again!
[11:39:24] Used Pokeball, with chance 35.29 (48 left)
[11:39:24] Captured Rattata! [CP 256] [Potential 0.49] [11/5/6] [+210 exp]
[11:39:24] You now have 671 Rattata candy!
[11:39:30] Successfully evolved Rattata with CP 256 and IV 0.49!
```

**Comment by raxxon** [comment]
That would be completely backwards looking from a Top-Down execution tree....

**Comment by Plotin** [comment]
A better documentation of the task list would be really helpful, the wiki seems to be outdated anyways.

**Comment by Fizcko** [comment]
@extink Thanks ! This is working for me. But my config file is different.

See below :

> {
>     "auth_service": "ptc",
>     "username": "???",
>     "password": "???",
>     "location": "???",
>     "gmapkey": "???",
>     "libencrypt_location": "encrypt.so",
>     "logging_color": true,
>     "tasks": [
>       {
>         "type": "HandleSoftBan"
>       },
>       {
>         "type": "CollectLevelUpReward"
>       },
>       {
>         "type": "IncubateEggs",
>         "config": {
>           "longer_eggs_first": true
>         }
>       },
>       {
>         "type": "TransferPokemon"
>       },
>       {
>         "type": "EvolvePokemon",
>         "config": {
>           "evolve_all": "none",
>           "first_evolve_by": "iv",
>           "evolve_above_cp": 0,
>           "evolve_cp_min": 0,
>           "logic": "and",
>           "evolve_speed": 20,
>           "use_lucky_egg": false
>         }
>       },
> 	  [...]
> 	  ],
>     "websocket_server": false,
>     "walk": 7.16,
>     "action_wait_min": 1,
>     "action_wait_max": 4,
>     "debug": false,
>     "test": false,
>     "health_record": true,
>     "location_cache": true,
>     "distance_unit": "km",
>     "reconnecting_timeout": 15,
>     "evolve_captured": "Pidgey,Rattata,Zubat,Spearow,Weedle,Kakuna,Caterpie",
> 	[...]
> }
>
