### ISSUE TITLE
Double CTRL + C Feature does not work on linux.

### ISSUE THREAD

**Issue by Tetranima** [PokemonGoF/PokemonGo-Bot#3418]
### Expected Behavior
Bot should reboot if CTRL + C is pressed once.

### Actual Behavior
Bot completely stops when pressing CTRL + C and does not restart.

### My config.json
{
    "auth_service": "ptc",
    "username": "xxx",
    "password": "xxx",
    "location": "48.863883, 2.326204",
    "gmapkey": "XXX",
    "libencrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 20 },
            "Greatball":      { "keep" : 40 },
            "Ultraball":      { "keep" : 100 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 10 },
            "Hyper Potion":   { "keep" : 20 },
            "Max Potion":     { "keep" : 50 },
            "Revive":         { "keep" : 10 },
            "Razz Berry":     { "keep" : 50 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 14,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "//any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "any": { "keep_best_iv": 1, "keep_best_cp": 1 },
      "Eevee": { "keep_best_iv": 2, "keep_best_cp": 3 },
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},
	"Machamp": {},
	"Kabutops": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

### Steps to Reproduce
git checkout dev
sh run.sh
CTRL + C

### Other Information
OS: Debian Jessie 64bit
Git Commit: 01bc14de0543196de6688dc6bd560739db59fd14
Python Version: 2.7.9
What did i drink this morning : Orange juice

**Comment by extink** [comment]
CTRL+C is the SIGINT command, which will interrupt the current running process. This will end the bot. As far as my knowledge go, this is the expected behavior.

**Comment by Fizcko** [comment]
I start "./run.sh" in a "screen" session on my Debian Jessie. CTRL + C works find for me with this setup.

**Comment by Arcasss** [comment]
Works fine on Ubuntu

**Comment by Tetranima** [comment]
I tried in a "screen" session. Still didn't work. It just stopped the bot completely.
