### ISSUE TITLE
SpinFort and MoveToFort recycle more items

### ISSUE THREAD

**Issue by merkon** [PokemonGoF/PokemonGo-Bot#3419]
Is there any solution in that problem?

2016-08-10 11:20:03,155 [  SpinFort] [INFO] [inventory_full] Not moving to any forts as there aren't enough space. You might want to change your config to recycle more items if this message appears consistently.
2016-08-10 11:20:03,156 [MoveToFort] [INFO] [inventory_full] Not moving to any forts as there aren't enough space. You might want to change your config to recycle more items if this message appears consistently.

What should i change?

**Comment by Fizcko** [comment]
> change your config to recycle

Go to the config.json file and setup the part regarding to the recycle : 

>      {
>         "type": "RecycleItems",
>         "config": {
>           "min_empty_space": 15,
>           "item_filter": {
>             "Pokeball":       { "keep" : 100 },
>             "Potion":         { "keep" : 10 },
>             "Super Potion":   { "keep" : 20 },
>             "Hyper Potion":   { "keep" : 30 },
>             "Revive":         { "keep" : 30 },
>             "Razz Berry":     { "keep" : 100 }
>           }
>         }
>       },

**Comment by akizor** [comment]
Check pokemon count and lower the item_filter numbers from config's "RecycleItems". Usually i'm going with:
```
"config": {
      "item_filter": {
        "Pokeball":       { "keep" : 50 },
        "Potion":         { "keep" : 0 },
        "Super Potion":   { "keep" : 0 },
        "Hyper Potion":   { "keep" : 30 },
        "Revive":         { "keep" : 30 },
        "Razz Berry":     { "keep" : 50 }
      }
    }
```

Also, for now `"min_empty_space": 15` is causing a loop. Remove it temporarilly

**Comment by merkon** [comment]
And what if i want to keep more items, like more pokeballs or berries?

**Comment by extink** [comment]
If you want that, you can add them based on the name in this list: https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Item-ID's

This you need to do if you want to add Great Ball filtering
```
"config": {
	"item_filter": {
		"Pokeball": { "keep" : 50 },
		"Potion": { "keep" : 0 },
		"Super Potion": { "keep" : 0 },
		"Hyper Potion": { "keep" : 30 },
		"Revive": { "keep" : 30 },
		"Razz Berry": { "keep" : 50 },
		"Greatball": { "keep": 50 }
	}
}
```

**Comment by merkon** [comment]
I have no idea how to write a good changelog, is there anyone who can upload his?
For example if i want to keep 300 pokeballs, will i have problem with the spinfort and the movetofort again like before?

**Comment by extink** [comment]
If you want to have a higher number of items, just change the number to the desired number in `{ "keep" : 50 }` for the item you want to change

**Comment by merkon** [comment]
That's what i did before and suddenly that spinfort and movetofort problem happened...

So i should probably try to have the amount of items that i keep at low numbers? Like 30-50?

**Comment by extink** [comment]
That problem was being caused by the `"min_empty_space": 15` config, so it should not be a problem to have high numbers.

**Comment by merkon** [comment]
I didn't have that "min_empty_space" in my config at all! So? What else might be the problem?
Also, can i do something to level up more quickly?

**Comment by akizor** [comment]
@merkon It all matters on how you tune up your config. You have numerous variables that could help you do that. In order to level fast, put your account to farm in known areas that spawn a lot of pokemons, add evolving features to config at `"evolve_captured": "Pidgey,Rattata,Zubat,Weedle,Drowzee,Spearow,Venonat,Caterpie,Krabby,Paras,Sandshrew,Psyduck,Mankey,Tentacool,Magnemite,Doduo,Seel,Voltorb,Horsea,Goldeen,Staryu,Ekans",` and each time you capture one and have candy, evolve them. Leave the script open when you sleep and so on.

**Comment by merkon** [comment]
I don't know how to tune up the best my config... Do you have any change file that you can give me?
Also when i try to run the bot for a long time it crashes:

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 547

And then it says:

2016-08-10 14:57:00,567 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
