### ISSUE TITLE
Bot update error cant inbstall xxhash

### ISSUE THREAD

**Issue by Miamony** [PokemonGoF/PokemonGo-Bot#3426]
>flask==0.11.1->-r requirements.txt (line 17))
Installing collected packages: numpy, networkx, geopy, protobuf, requests, s2sphere, gpsoauth, xxhash, pgoapi, protobuf-to-dict, googlemaps, colorama, enum34, pyyaml, haversine, polyline, python-socketio, flask, socketIO-client, eventlet, gpxpy, mock, timeout-decorator, contextlib2, raven, demjson
  Running setup.py install for gpsoauth ... done
  Running setup.py install for xxhash ... error
    Complete output from command C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\asmar\\appdata\\local\\temp\\pip-build-mp0gjx\\xxhash\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\asmar\appdata\local\temp\pip-rejnd0-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'xxhash' extension
    error: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\asmar\\appdata\\local\\temp\\pip-build-mp0gjx\\xxhash\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\asmar\appdata\local\temp\pip-rejnd0-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\asmar\appdata\local\temp\pip-build-mp0gjx\xxhash\
Entering 'web'
From https://github.com/OpenPoGo/OpenPoGoWeb
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Press any key to continue . . .

**Comment by pablossp** [comment]
Try installing [this](https://github.com/PokemonGoF/PokemonGo-Bot/issues/2734#issuecomment-238073655)

**Comment by RedViper9** [comment]
Are you still having an issue?
