### ISSUE TITLE
[Bug] bot stopped

### ISSUE THREAD

**Issue by gagas3113** [PokemonGoF/PokemonGo-Bot#343]
sometimes bot stopped and show this

    fort_name = fort_details['name'].encode('utf8', 'replace')
KeyError: 'name'

sometimes this

    fort_details = response_dict['responses']['FORT_DETAILS']
TypeError: 'NoneType' object has no attribute '__getitem__'

sometimes this

    if spin_details['result'] == 1:
KeyError: 'result'

**Comment by s1x** [comment]
@gagas3113 If you still have the error or any problems please feel free the open a new issue.
