### ISSUE TITLE
nickname module removes trailing 0s

### ISSUE THREAD

**Issue by jrgutier** [PokemonGoF/PokemonGo-Bot#3430]
Hi, I have my bot appending IVs at the end of my nickname. I'm finding that its removing the trailing 0 if its there. For example, this bellsprout has 90%.

![img_0071](https://cloud.githubusercontent.com/assets/341563/17550318/0a08fe7a-5eba-11e6-9429-b1d4b7ac8321.jpg)

**Comment by gvasilev** [comment]
Use the following config:

`"nickname_template": "{name:.8s}_{iv_pct}"`

This will remove any letters from the name which are past the 8th symbol, so it will have space for the IV.
