### ISSUE TITLE
When the bag is full, should it do RecycleItems?

### ISSUE THREAD

**Issue by spoxus** [PokemonGoF/PokemonGo-Bot#3434]
### Expected Behavior
I added the "min_empty_space": 	0, line into config. Then it starts to collect all the items. When the bag is full, it should recycle according to the rules. And i have to stop the bot then change config and to log in again.
Also, the message of skip  recycle appeared every second line. Which is too much
### Your config.json (remove your credentials and any other private info)
```
			"config": {
				"min_empty_space": 	0,
				"item_filter": {
					"Pokeball":	{ "keep" :	 10 },
					"Greatball":	{ "keep" :	 30 },
..
```

**Comment by joaodragao** [comment]
It's a bug right now. set `// min_empty_space` or delete it.
