### ISSUE TITLE
bot stuck at "Next egg incubates in ..." at start

### ISSUE THREAD

**Issue by rlllam** [PokemonGoF/PokemonGo-Bot#3436]
### Expected Behavior
bot continues

### Actual Behavior
bot stuck at "Next egg incubates in ..." at start
bot relog every ~30mins and repeat

ex.
[06:40:23] Starting bot...
[06:40:23] Received level up reward: []
[06:40:23] Next egg incubates in 2.00 km

### Your config.json (remove your credentials and any other private info)
{
  "tasks": [
    {
      "type": "HandleSoftBan"
    },
    {
      "type": "CollectLevelUpReward"
    },
    {
      "type": "IncubateEggs",
      "config": {
        "longer_eggs_first": true
      }
    },
    {
      "type": "RecycleItems",
      "config": {
        "run_interval": 60,
        "item_filter": {
          "Pokeball": {
            "keep": 35
          },
          "Greatball": {
            "keep": 70
          },
          "Ultraball": {
            "keep": 100
          },
          "Masterball": {
            "keep": 0
          },
          "Potion": {
            "keep": 0
          },
          "Super Potion": {
            "keep": 0
          },
          "Hyper Potion": {
            "keep": 5
          },
          "Max Potion": {
            "keep": 5
          },
          "Revive": {
            "keep": 0
          },
          "Max Revive": {
            "keep": 5
          },
          "Razz Berry": {
            "keep": 80
          }
        }
      }
    },
    {
      "type": "EvolvePokemon",
      "config": {
        "evolve_all": "Pidgey,Rattata,Zubat,Weedle,Drowzee,Spearow,Venonat,Caterpie,Krabby,Paras,Jigglypuff,Sandshrew,Vulpix,Meowth,Psyduck,Mankey,Tentacool,Ponyta,Slowpoke,Magnemite,Doduo,Seel,Voltorb,Horsea,Goldeen,Staryu,Ekans",
        "first_evolve_by": "cp",
        "evolve_above_cp": 0,
        "evolve_above_iv": 0,
        "logic": "or",
        "evolve_speed": 1,
        "use_lucky_egg": false,
        "run_interval": 180
      }
    },
    {
      "type": "TransferPokemon",
      "config": {
        "run_interval": 180
      }
    },
    {
      "type": "MoveToFort",
      "config": {
        "lure_attraction": true,
        "lure_max_distance": 2000,
        "ignore_item_count": true
      }
    },
    {
      "type": "SpinFort",
      "config": {
        "ignore_item_count": true
      }
    },
    {
      "type": "CatchVisiblePokemon"
    },
    {
      "type": "CatchLuredPokemon"
    }
  ],
  "map_object_cache_time": 5,
  "forts": {
    "avoid_circles": true,
    "max_circle_size": 500
  },
  "websocket_server": false,
  "walk": 80,
  "action_wait_min": 0,
  "action_wait_max": 1,
  "debug": false,
  "test": false,
  "health_record": false,
  "location_cache": false,
  "distance_unit": "m",
  "reconnecting_timeout": 15,
  "evolve_captured": "NONE",
  "catch_randomize_reticle_factor": 1.0,
  "catch_randomize_spin_factor": 1.0,
  "catch": {
    "any": {
      "always_catch": true
    }
  },
  "release": {"any": {"release_below_cp": 0, "release_below_iv": 0.95, "logic": "or"}
  },
  "vips": {
    "any": {
      "catch_above_cp": 1200,
      "catch_above_iv": 0.9,
      "logic": "or"
    },
    "Lapras": {},
    "Moltres": {},
    "Zapdos": {},
    "Articuno": {},
    "Mewtwo": {},
    "Dragonite": {},
    "Snorlax": {},
    "Mew": {},
    "Arcanine": {},
    "Vaporeon": {},
    "Gyarados": {},
    "Exeggutor": {},
    "Muk": {},
    "Weezing": {},
    "Flareon": {}
  }
}

### Steps to Reproduce
python pokecli.py

### Other Information
OS: Windows 10 64bit
Git Commit: 0c3c4c004d5081b91ffe278850d1b1821e4f63b4
Python Version: Python 2.7.12

**Comment by Nik0lashka** [comment]
@rlllam check #3432

**Comment by rlllam** [comment]
@Nik0lashka I relaunched like 90times and its still the same...
Also tried the bot on a brand new account and the problem is still there

**Comment by bibibkamal** [comment]
I got the same problem, and when i play on my phone there is no pokestop, gym or anything. Help pleasee

**Comment by rlllam** [comment]
apparently they modified the server so that your ip would get banned if you're running too many bots
the max bots/ip is 2 now i think
