### ISSUE TITLE
Sniping: strange behavior

### ISSUE THREAD

**Issue by YvesHenri** [PokemonGoF/PokemonGo-Bot#3437]
### Expected Behavior
Teleport to pokemon, encounter pokemon, teleport back and catch it.

### Actual Behavior
Teleport to pokemon, encounter pokemon, teleport back, catch it and pretend to move towards it.

### Config snippet
{
        "type": "MoveToMapPokemon",
         "config": {
		   "address": "http://localhost:5000",
		   "max_distance": 500,
		   "min_time": 60,
		   "min_ball": 10,
		   "map_path": "raw_data",
		   "prioritize_vips": true,
		   "snipe": true,
		   "snipe_high_prio_only": true,
		   "snipe_high_prio_threshold": 400,
		   "update_map": false,
		   "mode": "priority",
           "catch": {
             "Mewtwo": 1000,
			 "Mew": 1000,
			 "Articuno": 1000,
			 "Zapdos": 1000,
			 "Moltres": 1000,
			 "Ditto": 1000,
			 "Snorlax": 1000,
			 "Dragonite": 1000,
			 "Lapras": 1000,
			 "Gyarados": 1000,
			 "Arcanine": 900,
			 "Aerodactyl": 900,
			 "Ivysaur": 900,
			 "Charizard": 900,
			 "Blastoise": 900,
			 "Jolteon": 900,
			 "Vaporeon": 900,
			 "Flareon": 900,
			 "Exeggcutor": 900,
			 "Exeggcute": 800,
			 "Dratini": 800,
			 "Dragonair": 800,
			 "Mr. Mime": 800,
			 "Kangaskhan": 800,
			 "Farfetch'd": 800,
			 "Electabuzz": 800,
			 "Porygon": 800,
			 "Gengar": 800,
			 "Wigglytuff": 800,
			 "Kabutops": 800,
			 "Omastar": 800,
			 "Rapidash": 800,
			 "Slowbro": 800,
			 "Rhydon": 800,
			 "Chansey": 800,
			 "Tangela": 800,
			 "Poliwrath": 800,
			 "Alakazam": 800,
			 "Machamp": 800,
			 "Victreebel": 800
           }
         }
      },

### Other Information
OS: Windows 10
Git Commit: 8b5af8d766ac161be926932b05e3fc785a33661d
Python Version: 2.7.12

[07:52:06] Encountered Pokemon: Vaporeon
[07:52:09] Teleporting back to previous location (42.3285253, -83.03698)
[07:52:11] A wild Vaporeon appeared! [CP 204] [Potential 0.89] [A/D/S 10/15/15]
[07:52:15] Used Greatball, with chance 38.67 (44 left)
[07:52:16] Captured Vaporeon! [CP 204] [Potential 0.89] [10/15/15] [+210 exp]
[07:52:16] You now have 329 Eevee candy!
[07:52:21] Moving towards Vaporeon, 1784.88km, left (4 minutes, 39 seconds)

**Comment by maggieonrails** [comment]
location cache maybe?

**Comment by YvesHenri** [comment]
@maggieonrails location cache IS set true. What does it have to do with it, though?

**Comment by Ph4i1ur3** [comment]
If you're referring the the fact that it moves to the Pokemon after already catching it via sniping, I believe the issue lies with the fact that the data being fed from The map data doesn't determine that the bot has already caught that Pokemon

**Comment by YvesHenri** [comment]
@Ph4i1ur3 the issue lies with the snipping config itself, I highly believe. We can see that the 'snipe' param can be either true or false, as we can see here: https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files#sniping-movetolocation, so it might be ignoring something

**Comment by Ph4i1ur3** [comment]
It looks like it's an actual coding error in the move_to_map_pokemon cell worker.

**Comment by YvesHenri** [comment]
@Ph4i1ur3 that too. That's why I opened this issue :)

**Comment by pepenliman** [comment]
I can not use the data.
after I use the copy and paste in jsonlint ..
it message like this 

Error: Parse error on line 507:
...w",		"mewtwo"	]} {	"type": "MoveToMa
--------------------^
Expecting 'EOF', '}', ',', ']', got '{'

please help me..

**Comment by k4n30** [comment]
#2851

**Comment by k4n30** [comment]
fixed
