### ISSUE TITLE
Suggestion - Set max # of items

### ISSUE THREAD

**Issue by leadboots5** [PokemonGoF/PokemonGo-Bot#344]
Ability to set a max # of items so that it discards when it goes over that amount or discards a bunch when it hits an upper limit on a range(if we want to avoid a discard call at every pokestop once it hits the limit). This would help with getting too many items in the inventory and the bot switching to search mode which probably leads to no pokeballs as eventually potions and berries will overrun.

Example 1:
max razz berry =20
Every pokestop that loots a razz berry will trigger a discard

Example 2(probably more human like):
max razzberyy=40
discarddownto razz berry=20
when razzberry count equals 40 it discards 20 at once.

**Comment by necrozis** [comment]
@leadboots5 i think we can make something like "item priority" may be in % for each item in config.
So max item # depends on max slots in bag. (may be)

**Comment by dominikue** [comment]
"item priority" would be nice :+1:  #76

**Comment by surfaace** [comment]
@dominikue could you assist here since you are already working on item filtering?

**Comment by leadboots5** [comment]
Max number was implemented at some point and is dev presently. closing.
