### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by Sharingisnotillegal** [PokemonGoF/PokemonGo-Bot#3441]
c:\pokemongo\PokemonGo-Bot>python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

**Comment by steffenix** [comment]
Same as https://github.com/PokemonGoF/PokemonGo-Bot/issues/3303

**Comment by lyriccoder** [comment]
Confirm it. Moreover, it worked some time ago and then suddenly stopped working, I didn't do anything, I just saw the error in the log file during last hour.

**Comment by GitPupper** [comment]
Closed since it's a duplicate as #3303 (A closed issue)
