### ISSUE TITLE
Not starting, docker. Following guide

### ISSUE THREAD

**Issue by Sharingisnotillegal** [PokemonGoF/PokemonGo-Bot#3442]
c:\pokemongo\PokemonGo-Bot>docker run --name=pokego-bot1 --rm -it -v /configs/config.json:/usr/src/app/configs/config.json pokemongo-bot
2016-08-10 11:17:32,388 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-10 11:17:32,391 [       cli] [INFO] Error: No /configs/config.json or specified config
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-ws WEBSOCKET.SERVER_URL]
                  [-wss WEBSOCKET.START_EMBEDDED_SERVER]
                  [-wsr WEBSOCKET.REMOTE_CONTROL] [-p PASSWORD] [-l LOCATION]
                  [-lc LOCATION_CACHE] [--forts.spin FORTS.SPIN] [-w WALK]
                  [-k GMAPKEY] [-e SHOW_EVENTS] [-d DEBUG] [-t TEST]
                  [-du DISTANCE_UNIT] [-ec EVOLVE_CAPTURED]
                  [-rt RECONNECTING_TIMEOUT] [-hr HEALTH_RECORD]
                  [-ac FORTS.AVOID_CIRCLES] [-mcs FORTS.MAX_CIRCLE_SIZE]
                  [--catch_randomize_reticle_factor CATCH_RANDOMIZE_RETICLE_FACTOR]
                  [--catch_randomize_spin_factor CATCH_RANDOMIZE_SPIN_FACTOR]
                  [--map_object_cache_time MAP_OBJECT_CACHE_TIME]
pokecli.py: error: argument -a/--auth_service is required

**Comment by thementos** [comment]
I have same problem. I use docker for windows
this my command 
`docker run --name=bot1-pokego --rm -it -v /c/Users/xxx/PokemoGo-Bot/configs/config.json:/usr/src/app/configs/config.json pokemongo-bot`

**Comment by lawliet89** [comment]
Sorry, I changed the `Dockerfile` recently and didn't update the documentation.

Use `-v /some/path/PokemoGo-Bot/configs/:/usr/src/app/configs/` instead. 

Relevant line: https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/Dockerfile#L4

**Comment by thementos** [comment]
I have same error
`Mentos@MENTOS-NB C:\Users\Mentos\PokemonGo-Bot
$ docker run --name=bot1-pokego --rm -it -v /C/Users/Mentos/PokemonGo-Bot/configs:/usr/src/app/configs pokemon-bot
2016-08-15 09:42:53,770 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-15 09:42:53,773 [       cli] [INFO] Error: No /configs/config.json or specified config
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-ws WEBSOCKET.SERVER_URL]
                  [-wss WEBSOCKET.START_EMBEDDED_SERVER]
                  [-wsr WEBSOCKET.REMOTE_CONTROL] [-p PASSWORD] [-l LOCATION]
                  [-lc LOCATION_CACHE] [--forts.spin FORTS.SPIN] [-w WALK]
                  [-k GMAPKEY] [-e SHOW_EVENTS] [-d DEBUG] [-t TEST]
                  [-du DISTANCE_UNIT] [-rt RECONNECTING_TIMEOUT]
                  [-hr HEALTH_RECORD] [-ac FORTS.AVOID_CIRCLES]
                  [-mcs FORTS.MAX_CIRCLE_SIZE] [-crf FORTS.CACHE_RECENT_FORTS]
                  [--map_object_cache_time MAP_OBJECT_CACHE_TIME]
                  [--logging_color LOGGING_COLOR]
                  [-cte CATCH_THROW_PARAMETERS.EXCELLENT_RATE]
                  [-ctg CATCH_THROW_PARAMETERS.GREAT_RATE]
                  [-ctn CATCH_THROW_PARAMETERS.NICE_RATE]
                  [-ctm CATCH_THROW_PARAMETERS.NORMAL_RATE]
                  [-cts CATCH_THROW_PARAMETERS.SPIN_SUCCESS_RATE]
pokecli.py: error: argument -a/--auth_service is required`

**Comment by lawliet89** [comment]
Can you `ls` the contents of `/C/Users/Mentos/PokemonGo-Bot/configs` please. By default, it expects the configuration file to be called `config.json`.

**Comment by thementos** [comment]
Mentos@MENTOS-NB C:\Users\Mentos\PokemonGo-Bot
$ dir /c/Users/Mentos/PokemonGo-Bot/configs
Invalid switch - "Users".

**Comment by thementos** [comment]
finally i find solution for mount dirctory
I use docker for windows (not toolbox). I must set docker to share drive by config on docker setting
like this link https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c#.c599qlb3z

I think this can close issue
