### ISSUE TITLE
unable to find image pokemongo-bot:latest

### ISSUE THREAD

**Issue by MustafaAdam** [PokemonGoF/PokemonGo-Bot#3443]
I follow the instructions with docker until I get to 
`docker run --name=pokego-bot1 --rm -it -v $(pwd)/configs/config-account1.json:/usr/src/app/configs/config.json pokemongo-bot`

I get this error

```
Unable to find image 'pokemongo-bot:latest' locally
Pulling repository docker.io/library/pokemongo-bot
docker: Error: image library/pokemongo-bot:latest not found.
See 'docker run --help'.
```

**Comment by pensiero** [comment]
Can you show the response of `docker images`?
If you used docker via dockerhub, you should see something like `svlentink/pokemongo-bot`
