### ISSUE TITLE
Please help, recycle items, tried everything and still don't work

### ISSUE THREAD

**Issue by merkon** [PokemonGoF/PokemonGo-Bot#3444]
I really don't know how to fix that issue:

2016-08-10 13:34:32,245 [  SpinFort] [INFO] [inventory_full] Not moving to any forts as there aren't enough space. You might want to change your config to recycle more items if this message appears consistently.
2016-08-10 13:34:32,246 [MoveToFort] [INFO] [inventory_full] Not moving to any forts as there aren't enough space. You might want to change your config to recycle more items if this message appears consistently.

My changelog looks like that, the part concerning with recycle items and spinfort:
     {
        "type": "RecycleItems",
        "config": {
          "item_filter": {								
            "Pokeball":       { "keep" : 300 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 10 },
            "Hyper Potion":   { "keep" : 35 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 40 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 4000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70

Is there any real solution?
Please help cause i have no idea about programming and python language.
Thanks in advance.

**Comment by Fizcko** [comment]
You can carry maximum 350 items

**Comment by merkon** [comment]
How can i fix that?

**Comment by Fizcko** [comment]
Change the number of the differents items, for example : 

"Pokeball": { "keep" : 200 },
"Potion": { "keep" : 0 },
"Super Potion": { "keep" : 0 },
"Hyper Potion": { "keep" : 10 },
"Revive": { "keep" : 30 },
"Razz Berry": { "keep" : 30 }

**Comment by merkon** [comment]
So I have to lower the numbers of the items i have, right?

**Comment by Fizcko** [comment]
Yes, the sum of all items have to be below 350

**Comment by merkon** [comment]
So, that was the problem? Thanks so much for the solution! 👍

**Comment by Fizcko** [comment]
You can close the Issue if it is done.
