### ISSUE TITLE
Remove protobuf installation via apt instead do everything via pip

### ISSUE THREAD

**Issue by kinvaris** [PokemonGoF/PokemonGo-Bot#3446]
Running on `dev` branch

### Expected Behavior

Install protobuf 3.0

### Actual Behavior

Installs protobuf 2.5

### Steps to Reproduce

```
apt-get install python-protobuf
```

### Other Information
OS: `Linux jupiter 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
See wiki: https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation

**Comment by Ph4i1ur3** [comment]
Why are you Installing protobuf via apt?

**Comment by Outpox** [comment]
I don't get the point of this issue, installing protobuf trough pip has already been suggested in several other issues.
@Ph4i1ur3 : Because that's what's suggested in the [wiki](https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation).

**Comment by Ph4i1ur3** [comment]
That's really weird, as protobuf is part of requirements.txt

**Comment by extink** [comment]
The requirements.txt is being used during the 'pip install -r requirements.txt' command to install these dependencies using pip

**Comment by kinvaris** [comment]
@extink indeed, the reason of my title is just saying that needs to be removed from the wiki

**Comment by Outpox** [comment]
If you guys follow @kinvaris links in his original post, you'll see that he's talking about a specific wiki page where the linux installation steps for protobuf is `apt-get install python-protobuf`, which as we just stated isn't the correct way of doing it.

**Comment by Ph4i1ur3** [comment]
I would think the title could be changed to reflect the suggested change a little better

**Comment by Outpox** [comment]
Yeah and adding the "enhancement" label (if you can do it @kinvaris ) would be helpful as well.

**Comment by k4n30** [comment]
Is this fixed in #3781 ? If not I'd suggest making comments in there

**Comment by Outpox** [comment]
@k4n30 : It seems that according to [this change](https://github.com/PokemonGoF/PokemonGo-Bot/pull/3781/commits/ecb6db0fe41231fd74a7bf26612bca5909cda4c1#diff-28c5e511b1c66b6342da6e5a36d08d30R36) it has not been fixed since it's still suggested to install protobuf using aptitude on Linux.

**Comment by k4n30** [comment]
@Outpox it's been updated since then https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/manual_installation.md

**Comment by Outpox** [comment]
Good!
