### ISSUE TITLE
ImportError: No module named Queue

### ISSUE THREAD

**Issue by MustafaAdam** [PokemonGoF/PokemonGo-Bot#3447]
Tried running it with the linux installation, until this damn error pops up

```
Traceback (most recent call last):
  File "pokecli.py", line 41, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/home/mustafa/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 12, in <module>
    import Queue
ImportError: No module named 'Queue'
Press any button or wait 20 seconds.
```

**Comment by Ph4i1ur3** [comment]
A more detailed log would be beneficial to solving your problem

**Comment by JoshuaGarrison27** [comment]
@Ph4i1ur3 I get the same when i try to run this on a new instance of windows as well. It works on my primary computer. So probably something was removed recently?

**Comment by Ph4i1ur3** [comment]
Have you done pip install -r requirements.txt?

**Comment by JoshuaGarrison27** [comment]
Yes. Ran with no errors too.

**Comment by Ph4i1ur3** [comment]
Check your version of Python. python -v

**Comment by JoshuaGarrison27** [comment]
Ah.. Good observation. For some reason it windows changed to start using Python3 instead of 2. Re-ran the requirements and tested the app after directly using the Python27 folder and it works. Thanks @Ph4i1ur3

**Comment by Ph4i1ur3** [comment]
No problem, you should close this issue.

**Comment by JoshuaGarrison27** [comment]
Only a mod or @MustafaAdam can I believe.
