### ISSUE TITLE
Keeps walking

### ISSUE THREAD

**Issue by 0x73** [PokemonGoF/PokemonGo-Bot#3448]
### Expected Behavior

Spun pokestop
Capture pokemon

### Actual Behavior

Keeps walking

### Other Information
OS: 
Git Commit: 63f777bac0c8cdc75d07f9ef491ca8b900c0148a
Python Version: 2.7.11

**Comment by rosalf** [comment]
make sure your bags are not full, i had this so many times and i had to clean up both bags.

**Comment by taxi333** [comment]
+1

**Comment by z4ppy** [comment]
+1 only one bot and nothing full

**Comment by anusoft** [comment]
See Issue #3435

**Comment by aasensiog** [comment]
the same behaviour
