### ISSUE TITLE
Invalid map data in MoveToMapPokemon task

### ISSUE THREAD

**Issue by iruy** [PokemonGoF/PokemonGo-Bot#3459]
### Expected Behavior
Read valid map data

### Actual Behavior
I'm using latest dev branch, bot is actually giving this error

```
[15:07:20] Moving towards pokestop San Palacio - 0.05km
[15:07:20] Arrived at fort.
[15:07:20] Failure! Map data was not valid
[15:07:23] Discarded 1x Potion (maximum 0).

```
### Your config.json (remove your credentials and any other private info)
```
{
    "auth_service": "google",
    "username": "XXXXX",
    "password": "XXXXX",
    
    "location": "45.464274, 9.189034",
    
    "gmapkey": " XXXXXX",
    "tasks": [
        {
            "type": "HandleSoftBan"
        },
        {
            "type": "CollectLevelUpReward"
        },
        {
            "type": "IncubateEggs",
            "config": {
                "longer_eggs_first": true
            }
        },
        {
            "type": "TransferPokemon"
        },
        {
            "type": "EvolvePokemon",
            "config": {
                "evolve_all": "Pidgey,Caterpie,Rattata,Weedle,Zubat,Goldeen,Krabby,Abra,Paras,Psyduck,Staryu,Spearow,Tentacool,Ekans",
                "first_evolve_by": "cp",
                "evolve_above_cp": 10,
                "evolve_above_iv": 0.1,
                "logic": "and",
                "evolve_speed": 20,
                "use_lucky_egg": false
            }
        },
        {
            "type": "RecycleItems",
            "config": {
                "item_filter": {
                    "Pokeball":     {"keep": 80},
                    "Greatball":    {"keep": 50},
                    "Ultraball":    {"keep": 50},
                    "Potion":       {"keep": 0},
                    "Super Potion": {"keep": 0},
                    "Hyper Potion": {"keep": 0},
                    "Revive":       {"keep": 0},
                    "Razz Berry":   {"keep": 40}
                }
            }
        },
        {
            "type": "CatchVisiblePokemon"
        },
        {
            "type": "CatchLuredPokemon"
        },
        {
            "type": "SpinFort"
        },
        {
            "type": "MoveToFort",
            "config": {
                "lure_attraction": true,
                "lure_max_distance": 2000
            }
        },
        {
            "type": "MoveToMapPokemon",
            "config": {
                "address": "http://localhost:5000",
                "max_distance": 500,
                "min_time": 60,
                "min_ball": 10,
                "map_path": "raw_data",
                "prioritize_vips": true,
                "snipe": true,
                "snipe_high_prio_only": true,
                "snipe_high_prio_threshold": 400,
                "update_map": false,
                "mode": "priority",
                "catch": {
                    ....
                }
            }
        }
    ],
```

### Steps to Reproduce
With some difficulties I installed pokemongo map (pokeminer now) and was now I can see the map at localhost:5000. But then I get that error in the bot

### Other Information
OS: OS X El Capitan
Git Commit: 67fe00bcfc04fb6ddd2c78ca208aad4e4cbf2523
Python Version: Python 2.7.11

**Comment by k4n30** [comment]
@iruy are you still having this issue with the latest version?

**Comment by trademarrk** [comment]
i get a similar error too

config
{
        {
        "type": "MoveToMapPokemon",
        "config": {
          "address": "http://localhost:5000",
          "max_distance": 500,
          "min_time": 60,
          "min_ball": 50,
          "prioritize_vips": true,
          "snipe": false,
          "snipe_high_prio_only": false,
          "snipe_high_prio_threshold": 200,
          "update_map": false,
          "mode": "priority",
          "map_path": "raw_data",
          "catch": {

i get the error message

[14:56:46] Moving towards pokestop G Ross Lord Park Service Yard  - 0.14km
[14:56:48] Failure! Could not get Pokemon data from PokemonGo-Map: http://localhost:5000. Is it running?
[14:56:48] Moving towards pokestop G. Ross Park Sports Pavilion - 0.15km
[14:56:50] Failure! Could not get Pokemon data from PokemonGo-Map: http://localhost:5000. Is it running?
[14:56:50] Moving towards pokestop G Ross Lord Park Service Yard  - 0.14km
[14:56:51] Failure! Could not get Pokemon data from PokemonGo-Map: http://localhost:5000. Is it running?
[14:56:51] Moving towards pokestop G. Ross Park Sports Pavilion - 0.14km
[14:56:54] Failure! Could not get Pokemon data from PokemonGo-Map: http://localhost:5000. Is it running?
[14:56:54] Moving towards pokestop G Ross Lord Park Service Yard  - 0.14km
[14:56:56] Failure! Could not get Pokemon data from PokemonGo-Map: http://localhost:5000. Is it running?

**Comment by k4n30** [comment]
@trademarrk that's not the same issue, are you running [PokemonGo-Map](https://github.com/PokemonGoMap/PokemonGo-Map)?
