### ISSUE TITLE
Update Title on Windows failed

### ISSUE THREAD

**Issue by uzzle1987** [PokemonGoF/PokemonGo-Bot#3464]
### Expected Behavior
Show the stats in the windows title screen

### Actual Behavior
Doest not work properly. Only types the first character of the username

### Steps to Reproduce
Enable UpdateTileStats and wait on Windows system

## Possible Solve
update_title_stats.py 

change from
ctypes.windll.kernel32.SetConsoleTitleA(title)
to
ctypes.windll.kernel32.SetConsoleTitleA(title.encode())

**Comment by Moonlight-Angel** [comment]
@TheSavior @douglascamata This can be closed. Fixed by https://github.com/PokemonGoF/PokemonGo-Bot/pull/3467
