### ISSUE TITLE
Pause and see my data and stats, how?

### ISSUE THREAD

**Issue by focamonca** [PokemonGoF/PokemonGo-Bot#3468]
the bot is running well but if I want to see my progress without stopping it, how to do?
how to pause and give the command?

thnx

**Comment by mrthrowaway** [comment]
If you're using the web module, you can see the stats there without having to stop the bot

**Comment by flopk** [comment]
And if we aren't using the web module?

**Comment by icecubeice** [comment]
In the web module, how do you show the stats?

**Comment by abiran** [comment]
You can stop using location services for your iOS/android app and open it to see your progress. Since the app won't send location to Niantic it won't cause a soft ban. **At least it worked for me.**

**Comment by icecubeice** [comment]
@abiran I think he meant the xp/hr, highest cp, most perfetc, etc

**Comment by icecubeice** [comment]
@mrthrowaway I'm in the web module, what to do next?

**Comment by abiran** [comment]
See #3467

**Comment by focamonca** [comment]
Please, how to find and install that plug in? I have osx

Il 10 ago 2016 16:59, "abiranlopez" <notifications@github.com> ha scritto:

**Comment by k4n30** [comment]
Please use the live stats functionality - not a bot issue
