### ISSUE TITLE
[Question] bot transfer pokemon

### ISSUE THREAD

**Issue by gagas3113** [PokemonGoF/PokemonGo-Bot#347]
### Expected Behavior
The bot only transfer a low cp pokemon as i set -cp CP

### Actual Behavior
The bot also transfer the same pokemon , and only keep the highest CP pokemon

How to set the bot only transfer a low cp pokemon ?

**Comment by leadboots5** [comment]
are you full on pokemon?

**Comment by gagas3113** [comment]
is this issue only happen if my pokemon storage full ? or caused the command line ?

**Comment by gagas3113** [comment]
i think it cause the command --initial-transfer

**Comment by surfaace** [comment]
This this has been merged at some point.

**Comment by ZgrK** [comment]
It's was fixed on last version
