### ISSUE TITLE
HandleSoftBan still working ???

### ISSUE THREAD

**Issue by henricavalcante** [PokemonGoF/PokemonGo-Bot#3470]
Today Pokemon go has an update and I think HandleSoftBan feature is not working anymore. Can someone else check please?

**Comment by Ph4i1ur3** [comment]
Do you mean that the method no longer works for undoing softbans, or that the function itself is not functioning properly?

**Comment by jannickv** [comment]
They rolled out ip based banning today, is that what you mean? That can't be undone by the HandleSoftBan

**Comment by zekone** [comment]
@jannickv is there more info about this somewhere?

**Comment by Ph4i1ur3** [comment]
#3406

**Comment by simonsmh** [comment]
If you driving too fast you will receive a clean cell with nothing on it like the country which blocked as China (sad). But if you wait for some time it will get unbanned.

**Comment by henricavalcante** [comment]
I'll wait until tomorrow if my softban will go away and I'll also restart my server IP.

**Comment by Ph4i1ur3** [comment]
Your soft an should be gone within an hour or so. I've heard botting too far from your IP location, as well as running too many bots on one IP is earning IP bans

**Comment by henricavalcante** [comment]
It's ok now. Thanks.
