### ISSUE TITLE
Is possible to choose a place with running program?

### ISSUE THREAD

**Issue by adrianoresende** [PokemonGoF/PokemonGo-Bot#3474]
### Expected Behavior
Choose a place with running program.
Because it has time a place is a lot of people and high possibility of monsters.
Not is good to logout and log in with different location, possibility of take ban.

Example with Desktop:
Click place in map, then walks to the marked location, after back normal.

**Comment by Ph4i1ur3** [comment]
One option would be to create paths using the configuration and launch them with different shell files, then you can simulate the walking between locations with minimal effort after the initial work
