### ISSUE TITLE
Bot not evolving pokemon

### ISSUE THREAD

**Issue by d0ntchadon** [PokemonGoF/PokemonGo-Bot#3476]
### Expected Behavior
Evolving Pidgey/caterpie/rattata/weedle when there is enough candies

### Actual Behavior
Bot is simply releasing the pokemon even though there are enough candies

### Your config.json (remove your credentials and any other private info)
"tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "Pidgey,Weedle,Rattata,Caterpie",
            "first_evolve_by": "cp",
            "evolve_cp_min": 10,
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "TransferPokemon"
      },

### Other Information
OS: linux
Git Commit: 72622b438ebd65283ee14d136e2ee610612c43f6
Python Version: Python 2.7.12

**Comment by d0ntchadon** [comment]
update: for some reason, the bot evolved my rattata after collecting 37 candies, there are currently 104 pidgey candies but the bot is not evolving any pidgey,

**Comment by leadboots5** [comment]
I believe that will evolve on startup only? I think you need to use '"evolve_captured": "NONE"' to evolve something when its caught. "evolve_captured" is not inside the evolve task.

**Comment by d0ntchadon** [comment]
hmm. is that something new? the old version that i was using was working fine without any issues. this problem came after i updated the bot today.

**Comment by d0ntchadon** [comment]
seems to be working now after i added "evolve_captured": "Pidgey,Weedle,Rattata,Caterpie".
seems weird to me since it was all working well before the latest update. thanks nevertheless.

**Comment by N3W4L** [comment]
Hi, I have the same problem, 
Could you give me your config ? where did you put the evolve_captured": "Pidgey,Weedle,Rattata,Caterpie"  line ?
Many thanks for your help.

**Comment by anhvn01457** [comment]
I had this issue too and I solve this by added

```
            "first_evolve_by": "cp",
            "evolve_above_cp": 0,
            "evolve_above_iv": 0,
            "logic": "or",
```
to evolve config
