### ISSUE TITLE
Use Proxies to override the IP softban

### ISSUE THREAD

**Issue by absalom996** [PokemonGoF/PokemonGo-Bot#3477]
Hello,

First af all, thanks to developers for this amazing job :+1: 

I live in France, so I have a french IP adress.

When I use the BOT, in the US for example, my IP is banned for few hours (the bot walk and don't see nothing).
I would try to use a US HTTP proxy to override the ban, do you think it's possible ?

Under Linux you can set a http proxy easily with the command:

**export http_proxy='http://YourProxyAdress:TheProxyPort'**

But I don't know if the BOT communicate with Niantic servers only with the http port (80/443) ?
Could someone help me on this point ?

Thank you in advance

### Other Information
OS: Raspbian Jessie
Git Commit: master
Python Version: 2.7.9

**Comment by Ph4i1ur3** [comment]
Generally speaking this is the point of a proxy.

**Comment by jekku** [comment]
Without the code being there yet, you can try torify and torsocks.

I also tried proxychains. It's better than the prior, but you gotta have your own server that can accept ToR requests.

**Comment by jekku** [comment]
That being:

```sh
pandora@jekku:~ torify ./run.sh
```

**Comment by ulovehash** [comment]
it would be great if someone who uses proxy could describe how to connect them to bot
i have some issues with softban from another country too, using os x

**Comment by Carlito007** [comment]
me too need help how to connect to bot with proxy in windows...

**Comment by tnlin** [comment]
proxychains with tor sock is good

**Comment by absalom996** [comment]
Thank you for your responses.

I tried Proxychains with TOR. The Niantic Servers deny the access to the TOR Ip...
So I tried Proxychains with several IP Proxy found on the net and every time it is : Denied or Timeout.

:(

If anyone have an idea...
