### ISSUE TITLE
Problem with evolve function, wrong and bad pokemon evolved

### ISSUE THREAD

**Issue by jane0815** [PokemonGoF/PokemonGo-Bot#3478]
### Expected Behavior

Bot evolve only pokemons in config file AND if bot evolves it evolves the best pokemon available.

### Actual Behavior

Bot evolved Pokemon NOT on list:

2016-08-10 17:05:27,398 [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Magikarp! [CP 96] [Potential 0.58] [12/2/12] [+210 exp]
2016-08-10 17:05:27,398 [PokemonCatchWorker] [INFO] [gained_candy] You now have 390 Magikarp candy!
2016-08-10 17:05:28,000 [PokemonCatchWorker] [INFO] [pokemon_evolved] Magikarp evolved!

Bot evolved bad pokemon:

It evolved a random magikarp (guess the one just caught) also set the bot to keep good magikarp with good IV. I have one with 93 and 91% IV

Gyarados
CP:1092
IV: 0.58

### Your config.json (remove your credentials and any other private info)

"evolve_all": "Pidgey,Rattata,Zubat,Weedle,Drowzee,Spearow,Venonat,Caterpie,Krabby,Paras,Jigglypuff,Sandshrew,Vulpix,Meowth,Psyduck,Mankey,Tentacool,Ponyta,Slowpoke,Magnemite,Doduo,Seel,Grimer,Shellder,Voltorb,Exeggcute,Cubone,Koffing,Rhyhorn,Horsea,Goldeen,Staryu,Eevee,Omanyte,Kabuto,Ekans,Pikachu,Clefairy,Diglet,Growlithe,Poliwag",

**Comment by jane0815** [comment]
Yes you are right. I did not know that "evolve_captured": existed. It was much further down in the config. 

I still think it should have evolved a good Magikarp and not this bad one. 400 candys wasted.

**Comment by jane0815** [comment]
Damn i even have a worse Gyarados! 800 candys wasted. :(

HP: 64 / 64
CP:428
IV: 0.69
A/D/S: 15/4/12

**Comment by seratkurtulus** [comment]
It evolves the captured pokemon and doesn't check anything about cp or iv. Of course when there is enough candy.
It is set to "None" by default, so you manually  changed it to "all" yourself.
Btw it is not a big deal, leave the bot near a magikarp spawn you will get the all candy :) I have 10k magikarp candy right now
