### ISSUE TITLE
error with configuration file

### ISSUE THREAD

**Issue by Tagada22** [PokemonGoF/PokemonGo-Bot#3479]
hello,

i download the (dev) bot but i have a critical error when i launch the script .

here its my config

http://pastebin.com/5cMY3hWK

and i can't upload on json editor online because i have this error 

http://prntscr.com/c4078c

if you have an idea please ?

thanks

**Comment by Tagada22** [comment]
error in console

root@vps302994:~# cd /home/PokemonGo-Bot/
root@vps302994:/home/PokemonGo-Bot# virtualenv .
New python executable in /home/PokemonGo-Bot/bin/python
Installing setuptools, pip, wheel...done.
root@vps302994:/home/PokemonGo-Bot# source bin/activate
(PokemonGo-Bot) root@vps302994:/home/PokemonGo-Bot# screen
   |  At line 63, column 6, offset 1608
   |  Object started at line 24, column 6, offset 527
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:69:6: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 69, column 6, offset 1705
   |  Object started at line 24, column 6, offset 527
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:69:6: Error: Missing value for object property, expected ":"
   |  At line 69, column 6, offset 1705
   |  Object started at line 24, column 6, offset 527
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:83:4: Error: Expected a '}' but saw ']'
   |  At line 83, column 4, offset 1984
   |  Object started at line 24, column 6, offset 527
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:119:6: Warning: Object contains duplicate key: u'// Zubat'
   |  At line 119, column 6, offset 3276
   |  Object started at line 108, column 15, offset 2700
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:174:8: Warning: Object contains duplicate key: u'Dragonite'
   |  At line 174, column 8, offset 4793
   |  Object started at line 121, column 13, offset 3347
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:178:8: Warning: Object contains duplicate key: u'Arcanine'
   |  At line 178, column 8, offset 4900
   |  Object started at line 121, column 13, offset 3347
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:179:8: Warning: Object contains duplicate key: u'Vaporeon'
   |  At line 179, column 8, offset 4924
   |  Object started at line 121, column 13, offset 3347
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:182:8: Warning: Object contains duplicate key: u'Muk'
   |  At line 182, column 8, offset 4997
   |  Object started at line 121, column 13, offset 3347
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:184:8: Warning: Object contains duplicate key: u'Flareon'
   |  At line 184, column 8, offset 5039
   |  Object started at line 121, column 13, offset 3347
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json: has errors
2016-08-10 17:17:39,511 [       cli] [CRITICAL] Error with configuration file
root@vps302994:/home/PokemonGo-Bot#

**Comment by simonsmh** [comment]
try ./setup.sh -c

**Comment by leadboots5** [comment]
Jsonlint is tell you exactly where the error is. Line 24 you just have a random '{'. remove that.

**Comment by Tagada22** [comment]
thanks

i have this error

[ERROR] encrypt.so is not found! Please place it in the bots root directory or set libencrypt_location in config.


i know there are a long command but i last this you have that ?

but config working

i edit the config for add that 

        "Bulbasaur": {},
        "Ivysaur": {},
        "Venusaur": {},
        "Charmander": {},
        "Charmeleon": {},
        "Charizard": {},
        "Squirtle": {},
        "Wartortle": {},
        "Blastoise": {},
        "Piedgeot": {},
        "Pikachu": {},
        "Arcanine": {},
        "Raichu": {},
        "Sandslash": {},
        "Ninetales": {},
        "Vileplume": {},
        "Golduck": {},
        "Poliwhirl": {},
        "Poliwrath": {},
        "Kadabra": {},
        "Alakazam": {},
        "Machoke": {},
        "Machamp": {},
        "Weepinbell": {},
        "Victreebel": {},
        "Golem": {},
        "Rapidash": {},
        "Muk": {},
        "Haunter": {},
        "Gengar": {},
        "Marowak": {},
        "Hitmonlee": {},
        "Hitmonchan": {},
        "Vaporeon": {},
        "Eevee": {},
        "Jolteon": {},
        "Flareon": {},
        "Porygon": {},
        "Omastar": {},
        "Aerodactyl": {},
        "Dratini": {},
        "Dragonair": {},
        "Dragonite": {},



for use great ball and master ball ( vip pokemon )

and that for my items 



            "Pokeball":       { "keep" : 0 },
            "Greatball":      { "keep" : 50 },
            "Ultraball":      { "keep" : 100 },
            "Masterball":     { "keep" : 0 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 10 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }






and when i run i have this error 



2016-08-10 17:31:57,418 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-10 17:31:57,420 [       cli] [INFO] No config argument specified, checking for /configs/config.json
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:112:6: Warning: Object contains duplicate key: u'// Zubat'
   |  At line 112, column 6, offset 3140
   |  Object started at line 101, column 15, offset 2564
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:157:8: Error: Values must be separated by a comma
   |  At line 157, column 8, offset 4339
   |  Object started at line 114, column 13, offset 3211
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:159:8: Warning: Object contains duplicate key: u'Dragonite'
   |  At line 159, column 8, offset 4458
   |  Object started at line 114, column 13, offset 3211
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:163:8: Warning: Object contains duplicate key: u'Arcanine'
   |  At line 163, column 8, offset 4565
   |  Object started at line 114, column 13, offset 3211
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:164:8: Warning: Object contains duplicate key: u'Vaporeon'
   |  At line 164, column 8, offset 4589
   |  Object started at line 114, column 13, offset 3211
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:167:8: Warning: Object contains duplicate key: u'Muk'
   |  At line 167, column 8, offset 4662
   |  Object started at line 114, column 13, offset 3211
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json:169:8: Warning: Object contains duplicate key: u'Flareon'
   |  At line 169, column 8, offset 4704
   |  Object started at line 114, column 13, offset 3211
/home/PokemonGo-Bot/pokemongo_bot/../configs/config.json: has errors
2016-08-10 17:31:57,457 [       cli] [CRITICAL] Error with configuration file
root@vps302994:/home/PokemonGo-Bot#

**Comment by Tagada22** [comment]
@jsonlit

Yes , thanks i have forget an " , " at dragonite ( vip pokemon ) its working now i just checked for the command of encrypt.so .

I have other question what's config for transfert pokemon by low iv ?

**Comment by nivong** [comment]
dude run the bloodt setup.sh ....

**Comment by leadboots5** [comment]
Tagada. You should read the wiki.

**Comment by Tagada22** [comment]
problems fix ! 

thanks all
