### ISSUE TITLE
Request: Use the latitude and longitude to get the local altitude from Google

### ISSUE THREAD

**Issue by dmunozfer** [PokemonGoF/PokemonGo-Bot#3481]
Add feature of PokemonGoMap to grab altitude from latitude and longitude (Niantic could use this info for ban).

Implemented in [runserver.py#L101](https://github.com/PokemonGoMap/PokemonGo-Map/blob/7c45a1ebaeba51a07b1f9215d2e465f5e0a64c0c/runserver.py#L101) added in commit https://github.com/PokemonGoMap/PokemonGo-Map/commit/d95014acf7a83dd8f1648db60f0f3efc2ce91dc4

Thanks!

**Comment by Ph4i1ur3** [comment]
Duplicate: #2762
