### ISSUE TITLE
[Feature Request] Discard to make room, not by default

### ISSUE THREAD

**Issue by thisismyurl** [PokemonGoF/PokemonGo-Bot#3485]
Currently the script discards all items above an inventory maximum, regardless of available inventory slots, and does so precisely.

Technically accurate, but not what a human player would do. Instead, the script should test to see if there are inventory slots available, then discard items to make room for potential items.

### Actual Behavior

> Spun pokestop The Lifeboat Station. Experience awarded: 50. Items awarded: {u'Pokeball': 1, u'Greatball': 1, u'Revive': 1}
> Discarded 1x Pokeball (maximum 10).
> Discarded 1x Revive (maximum 20).

**Comment by Kassius509** [comment]
I like this idea. Change title to "[Feature Request] Discard to make room, not by default"

**Comment by knobunc** [comment]
```
Already in dev:
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
```
min_empty_space sets the threshold for recycling.  Don't set it to 5 or below or you won't spin stops.
