### ISSUE TITLE
Permanent IP ban

### ISSUE THREAD

**Issue by seratkurtulus** [PokemonGoF/PokemonGo-Bot#3488]
I was getting soft ip bans two days ago due to excessive amount of bots (7 to be axact) running on same cloud machine. Yesterday I stopped 5 of them and 2 of the remaining bots were running fine. Last night remaining bots have stopped and i started getting this errror:
`raise ServerSideAccessForbiddenException("Seems your IP Address is banned or something else went badly wrong...")`
It has been 15 hours and situation is still the same. So I rented another cloud machine with other ip but I'm still getting the same error. I guess they banned a certain range of ips rather than the single ip used by that machine.  I want to point out that I can use the bot on my personal computer, so issue is not related with the accounts.
I haven't heard anyone with this situation, so i wanted to share it. (I know it is not an issue)
I think It would be very good to implement some proxy mechanism as soon as possible before everybody gets their ip banned.

**Comment by Kassius509** [comment]
@seratkurtulus What cloud hosting provider were you useing? Its possible they are preventing any of that service's IP addresses, as occurred with AWS.

**Comment by seratkurtulus** [comment]
@Kassius509 I was using Linode.

**Comment by Ph4i1ur3** [comment]
Have you also tried logging one of the bots from the actual app on a phone? I knew Niantic started banning accounts as well

**Comment by seratkurtulus** [comment]
@Ph4i1ur3 Yea, I can login with the phone also

**Comment by Ph4i1ur3** [comment]
Then it sounds like they're adding more and more to the list of blocked providers

**Comment by boveloco** [comment]
Your ip should be in the same ip region that the server you are trying to play. 
Have this same error using on my AWS machine but using on my pc it's fine..

**Comment by seratkurtulus** [comment]
@boveloco, correct me if i got it wrong but if you are talking about the lat, lng values in the config with the "server you are trying to play", my pc is not in the same ip region either but bot works fine.

**Comment by boveloco** [comment]
@seratkurtulus hmm.. Strange you could play with your machine ip without any vpn.
Before the release here in Brasil, i needed to use a VPN and fake gps to login.
My guess is that they use load balancer with ip range, so for you to be in some location, you should be using the ip from that location and be there...
That's what i'm trying to tell.. 
So, if your ip is 55.x.x.x you should be in NA, if it start with 190.x.x.x you should be in SA, and so go on!
If you use the packaget whois, you can search where your ip is physically located and put you location nearby. It should work!

**Comment by seratkurtulus** [comment]
@boveloco the game is not released in my country yet and my pc ip is in my home country as far as you can guess (193.x.x.x). But bot is catching pokemons in san francisco right now. 
On the other hand my cloud machine ip is in NA (45.x.x.x) but it can't even login to the account. It's an ip range block rather than region specific blocking.

**Comment by boveloco** [comment]
@seratkurtulus yeah, i'm guessing that they'v banned all ip range of all services like AWS, Linode, Gcloud, ETC.
Try to use it in your PC, and if it doesn't run, try to use a VPN on your pc to get an external IP to NA!
