### ISSUE TITLE
Config.json.map not working

### ISSUE THREAD

**Issue by Tagada22** [PokemonGoF/PokemonGo-Bot#3491]
Hello,

i make my config.json and my config.json.map correctly .

the bot works great but i see the config.json.map not working or not launching .

my map works perfectly ( pokemon go map ) , but not snipe .
there are a commande specific to launch ? 

thanks

**Comment by seratkurtulus** [comment]
I didn't use Pokemon sniping feature yet but you should have only one config file. I guess you are starting your bot with your config.json file and config.json.map file is not even read by the bot. Merge the logic in those two files into one proper json file and then start the bot with it.

**Comment by Tagada22** [comment]
Ah ok thanks but i don't think its possible to make a "mix " files , i think there are a commande for that

**Comment by Chris221** [comment]
The contents of config.json.map are examples of what to put for to use the map. you have to either change it to config.json or more the parts you want to use over to your config.json file

**Comment by Tagada22** [comment]
Ok thanks i tried that 

You have a good text editor ? 

Because nano is not pratic and default block note on windows not paste line by line

**Comment by seratkurtulus** [comment]
use winscp to connect to the machine and access the files

**Comment by Tagada22** [comment]
i edit with notepad , i help me with json editor online for prevent error code 

and ....

its working very good ^^

http://image.prntscr.com/image/170565d04ffb4230a232b22e68857b9a.png


thanks .

**Comment by Chris221** [comment]
google editpad
