### ISSUE TITLE
NIckname with IV = Suspect ?

### ISSUE THREAD

**Issue by adrianoresende** [PokemonGoF/PokemonGo-Bot#3495]
If we put the pokemon name with numbers like IV, they will appear to the public at **GYM**, so do not think people are going to report?

The calculation IV only works out of the game?
Because I did not think the status (attack, defense and others) in the game.

**Comment by Ph4i1ur3** [comment]
Wait your really put up w Pokemon with its IVs in its name at a gym? I was thinking this issue was going to be about Niantic cracking down on it, which made way more sense to me logically

**Comment by pmquan** [comment]
Mark your top pokemons as favourites and change their name.

#2496

**Comment by adrianoresende** [comment]
@pmquan Thanks, one small doubt, you can check the pokemon name of others in the fight inside the gym?
I have good knowledge of privacy on the name of pokemon to get smarter lol

**Comment by knobunc** [comment]
I don't think other people see the names of your pokemon.

**Comment by adrianoresende** [comment]
@knobunc Public see the names of your pokemon defending at Gym.
But there is more of it? In the battle of the academy?

**Comment by pmquan** [comment]
@adrianoresende The custom name will be displayed in both of gym info & in the battle.
![pokename](https://cloud.githubusercontent.com/assets/5755393/17567518/8dd02604-5ef4-11e6-8a86-a7a9530b29a8.jpg)

**Comment by Setsu-BHMT** [comment]
Pretty sure the nickname is only visible to the trainer who named them.

Source:
http://gaming.stackexchange.com/questions/278956/will-other-players-see-my-pok%C3%A9mons-nickname-if-i-put-it-into-a-gym

**Comment by adrianoresende** [comment]
@Setsu-BHMT Thanks =)
