### ISSUE TITLE
[Request] Add conf option to list all current pokemon in bag

### ISSUE THREAD

**Issue by d0t1q** [PokemonGoF/PokemonGo-Bot#3497]
Would be nice if we could have an option so that the bot on launch lists all of the current pokemon in the bag and include the CP/IV number in the output.

**Comment by ksawerykarwacki** [comment]
It's already in inventory json. That's the way webUI obtains that data, just parse it.

**Comment by d0t1q** [comment]
ah I dont use the webui, thanks!
