### ISSUE TITLE
Whats causing this???

### ISSUE THREAD

**Issue by curtybird95** [PokemonGoF/PokemonGo-Bot#3498]
docker run --name=pokego-bot1 --rm -it -v $(pwd)/configs/config-account1.json:/usr/src/app/configs/config.json pokemongo-bot
2016-08-10 12:30:11,578 [ cli] [INFO] PokemonGO Bot v1.0
2016-08-10 12:30:11,582 [ cli] [INFO] Error: No /configs/config.json or specified config
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
[-ws WEBSOCKET.SERVER_URL]
[-wss WEBSOCKET.START_EMBEDDED_SERVER]
[-wsr WEBSOCKET.REMOTE_CONTROL] [-p PASSWORD] [-l LOCATION]
[-lc LOCATION_CACHE] [--forts.spin FORTS.SPIN] [-w WALK]
[-k GMAPKEY] [-e SHOW_EVENTS] [-d DEBUG] [-t TEST]
[-du DISTANCE_UNIT] [-ec EVOLVE_CAPTURED]
[-rt RECONNECTING_TIMEOUT] [-hr HEALTH_RECORD]
[-ac FORTS.AVOID_CIRCLES] [-mcs FORTS.MAX_CIRCLE_SIZE]
[--catch_randomize_reticle_factor CATCH_RANDOMIZE_RETICLE_FACTOR]
[--catch_randomize_spin_factor CATCH_RANDOMIZE_SPIN_FACTOR]
[--map_object_cache_time MAP_OBJECT_CACHE_TIME]
pokecli.py: error: argument -a/--auth_service is required

I keep getting this error. I validated my file on jsonlint.com and it is fine. The bot worked yesterday fine just not sure whats causing this now?

**Comment by GitPupper** [comment]
Make sure it is named `config.json` exactly.

**Comment by curtybird95** [comment]
well now all i get is command not found that is my launcher code below.

docker run --name=pokego-bot1 --rm -it -v $(pwd)/configs/config-account1.json:/usr/src/app/configs/config.json pokemongo-bot

**Comment by GitPupper** [comment]
Your path in the command/launcher code may be wrong. Try checking that.

**Comment by curtybird95** [comment]
i just created another docker image reran it and it is working perfectly.
