### ISSUE TITLE
Select IP address for bot ( support vhosts ).

### ISSUE THREAD

**Issue by takenek** [PokemonGoF/PokemonGo-Bot#3499]
Please add option to select IP address to connect to nantic servers.
I got server with 16 IP address from many /24 classes will be awsome if i can change/select other ip if i get ban.

Best Regards
TaKeN

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
@takenek Are you still after this? If so would you mind updating your FR to the new FR template with the following headings so that others may be more likely to assist you

Short Description

Possible solution

How it would help others

**Comment by takenek** [comment]
Sorry i missunderstand of course i want it option :-)
