### ISSUE TITLE
Yellow text on white background?

### ISSUE THREAD

**Issue by jane0815** [PokemonGoF/PokemonGo-Bot#3501]
I like that the log in now colored again but why yellow text? It is nearly impossible to read.

**Comment by GitPupper** [comment]
Hey there! If you're on a Mac press `Terminal` at the top, then go into `Preferences`. After that go into the `Profiles` tab and set it to any one of them that has a darker background of your choice. You can also change it around. My personal favorite is `Pro` or `Homebrew`. Another option would be to install a program called `iTerm` (link below). It has many different options to choose from and it a whole lot better than stock terminal in my opinion. Just make sure to move it to your Applications folder after you unzip it.
[iTerm.app.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/411899/iTerm.app.zip)

**Comment by relomy** [comment]
Alternatively, you can change the event colors individually:

https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/event_handlers/colored_logging_handler.py

`'inventory_full':                   'yellow',`

I highly recommend a darker (black) background for your terminal, though. I couldn't read the default dark blue so I added magenta and changed it to that.

**Comment by jane0815** [comment]
Well in white it looks better and it is easier to read.

**Comment by Gobberwart** [comment]
@relomy Not a fan of editing the code like that, as any code updates will overwrite the changes. This might be a good thing to add to a config file perhaps? eg. ./configs/colors.json. Default colors would remain set in colored_logging_handler.py but would accept changes from the config file if it exists.

That said, if you use a dark terminal it's not an issue.
