### ISSUE TITLE
Configure which incubators use 2, 5 or 10km

### ISSUE THREAD

**Issue by morrislaptop** [PokemonGoF/PokemonGo-Bot#3503]
As per #1997

I'm happy to buy incubators, but I only want to use them on the 10km ones. I don't get value for money from 2km eggs. It would be great to do something like:

Infinite: 2km, 5km
Breakable: 10km

It should always prefer using the infinite if available if config allows both types for a particular distance.

**Comment by bsjpark** [comment]
I would love this feature. I have been thinking of this. All my incubators were wasted on 2km/5km...

**Comment by fari-99** [comment]
well you can configure it in config using this
```
{
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
}
```

with that, the incubator always using 10km egg to incubate.
but if you want some like this

```
{
        "type": "IncubateEggs",
        "config": {
             "infinite_incubator" : {2,5}, //infinite incubator for 2 and 5 km ball
             "incubator": {10}  //charged incubator only 10.
        }
}
```

i love to see that too.

**Comment by rickycc** [comment]
@fari-99 Would love to see the second script too. Used up all my incubator on 2 & 5 km eggs..

**Comment by fari-99** [comment]
Maybe add someone in dev to recreate this task? Haha.
