### ISSUE TITLE
Segregate Config to module based

### ISSUE THREAD

**Issue by asthemic** [PokemonGoF/PokemonGo-Bot#3506]
Separate bot/pokemon/map config from authentication/location config. 

What do you think? 

- I'm not keen on having the password in plaintext in the same file as the rest of the settings. 
- Can have a separate config for emulated device settings? 
- Splitting them will let me mess around with the config whilst I'm at work on my break. :)
- Also makes requesting new users post their config easier because now you can by default just copy the example one when the config doesn't exist so it doesn't contain their account details.

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by bstpierr** [comment]
I would also like this feature. It would also make developers' lives easier since they would only have to update one config example when adding or changing config keys.
