### ISSUE TITLE
Keep running out of poke balls

### ISSUE THREAD

**Issue by OVO647** [PokemonGoF/PokemonGo-Bot#3507]
Does anyone have a config to let the bot run longterm without full inventory or running out of poke balls?

**Comment by srg2k5** [comment]
"item_filter": {
            "Pokeball":       { "keep" : 80 },
            "Potion":         { "keep" : 0 },
            "Greatball":      { "keep" : 50 },
            "Ultraball":      { "keep" : 50 },
            "Super Potion":   { "keep" : 0 },
            "Hyper Potion":   { "keep" : 0 },
            "Revive":         { "keep" : 10 },
            "Razz Berry":     { "keep" : 40 },
            "Max Potion":     { "keep" : 100 }
          }

is what I use.  My guy walks super fast through Disney Land though, so balls is not an issue, walk speed of like 25 seems to avoid me getting into an arriving at fort loop.
