### ISSUE TITLE
Can get to run it for the first time....

### ISSUE THREAD

**Issue by EnriqueBravo** [PokemonGoF/PokemonGo-Bot#3512]
### Expected Behavior

To finally run what I have been trying to run, at least watch it go.

### Actual Behavior

Not even running, all I get when trying to run install -r requirements.txt is 

>     error: Unable to find vcvarsall.bat

    ----------------------------------------
Command "c:\users\__hp__\appdata\local\programs\python\python36\python.exe -u -c                                                                                       "import setuptools, tokenize;__file__='C:\\Users\\__Hp__\\AppData\\Local\\Temp\                                                                                      \pip-build-zbs_qakl\\numpy\\setup.py';exec(compile(getattr(tokenize, 'open', ope                                                                                      n)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record                                                                                       C:\Users\__Hp__\AppData\Local\Temp\pip-t3r4pnlc-record\install-record.txt --sing                                                                                      le-version-externally-managed --compile" failed with error code 1 in C:\Users\__                                                                                      Hp__\AppData\Local\Temp\pip-build-zbs_qakl\numpy\

And when running python pokecli.py is 

> $ python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottl                                                                                      ingException, ServerBusyOrOfflineException
ImportError: No module named 'pgoapi'

### Your config.json (remove your credentials and any other private info)

{
    "auth_service": "google",
    "username": "-----",
    "password": "-----",
    "location": "19.537071, -96.907390",
    "gmapkey": "-----",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104",
    "evolve_all": "NONE"
}

### Other Information
OS: Windows 10
Git Commit: format63f777bac0c8cdc75d07f9ef491ca8b900c0148a
Python Version: Python 3.6.0a3

**Comment by GitPupper** [comment]
Make sure you do these commands in a new CMD window:

`cd PokemonGo-Bot`
`source bin/activate` (This part you're probably forgetting)
`python pokecli.py`

**Comment by EnriqueBravo** [comment]
Tried to run the source bin/activate command on a new cmd in that route. All I get is either 

Git bash:
bash: bin/activate: No such file or directory
or in CMD:
Unrecognized command, file or exe.

Dont know exactly what Im doing wrong, don't know if its because of my env.

Thanks for the answer, tho.

**Comment by siembz** [comment]
@EnriqueBravo 

https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Installation#installation-windows

**Comment by ManchuElijah** [comment]
It said that my encrypt.dll not found?
