### ISSUE TITLE
Unable to install and launch the web module

### ISSUE THREAD

**Issue by focamonca** [PokemonGoF/PokemonGo-Bot#3516]
Who can gently teach clearly hot to download --> install ->  run the web module to see live the stats and progress? 
THANKS

**Comment by Ph4i1ur3** [comment]
What OS are you using?

**Comment by focamonca** [comment]
Osx El capitan

Il 10 ago 2016 22:26, "Ph4i1ur3" <notifications@github.com> ha scritto:

**Comment by focamonca** [comment]
up

**Comment by RedViper9** [comment]
Please ask these types of question in the #help section of our slack discussion board.
