### ISSUE TITLE
Ip ban. Normal speed 4bots. 

### ISSUE THREAD

**Issue by xGine** [PokemonGoF/PokemonGo-Bot#3519]
I always get ip ban. I use 4 bots at normal walk speed.

**Comment by xGine** [comment]
Walk: 4.16

**Comment by db-coder** [comment]
I always get IP bans and I'm just using 1 bot.

**Comment by oleerik** [comment]
huh, does it have something to do with the host you are using, maybe? I've been running it without an issue for a while.

**Comment by zviper13579** [comment]
using 1 bot and ip ban

**Comment by Adastras** [comment]
Odds are Niantic is banning entire IP blocks for known VPS providers like Linode or DigitalOcean. If you're running it on one of those you're probably going to get those.

**Comment by zviper13579** [comment]
just running it from home network

**Comment by db-coder** [comment]
Running it in my PC only. But I can think of a few reasons:
1) Pokemon-Go isn't officially released in my country yet.
2) My institute uses just 3-4 public IPs, so if it's just tracking IPs then this is a major problem.

**Comment by HelloTroy** [comment]
I was getting IP banned when running two bots in my own country or one bot in a foreign country.  Now that I'm just running 1 bot everything is working swimmingly.

**Comment by siembz** [comment]
Im running 2 bots  for 18 hours a day and have never been banned.

**Comment by nazox9** [comment]
Does speed have anything to do with it? I can now only run one bot at a time.  My walk speed is set to 10. If I run the second bot I get IP banned after about 10-15 minutes.

**Comment by xGine** [comment]
Reducing walk: 3.16 still ip ban. Testing 1:1 if it will still work.

**Comment by xGine** [comment]
Im not using vps. . Im botting it at home. My pub ip is dynamic i can change it anytime wihout using vpn.

**Comment by xSomeFoolx** [comment]
#3233 Seems similar.

**Comment by zviper13579** [comment]
Turns out with the new git pull the location I was using was causing it to get stuck. I changed the last few gps coordinates and it is working fine now. Make sure your coordinates don't have a space. It should look like this "xx.xxxxxx,xx.xxxxxxx". Mine had a space as well. After fixing that it is working smoothly with 3.

**Comment by xGine** [comment]
Something is wrong. When im using my account on apps. Pokemon can be seen. But with bot cant. Hmmmmmmm

**Comment by nazox9** [comment]
@xGine When bot can not see if I'm attached to wifi on my phone it still can't. If app is running from same IP you'll get the same thing. No pokemon, sightings, stops, or gyms will show up on the map.

**Comment by xGine** [comment]
I use incense. On bot cant see pokemons but w/ working pokestop. But when im on the app. Pokemon shows w/ pokestop.

**Comment by siembz** [comment]
@xGine my walke speed is set to 14.9

**Comment by xGine** [comment]
I try to login to app but not at the same time. .  I'm testing whats the difference.
