### ISSUE TITLE
how to setup own private proxy server on ubuntu

### ISSUE THREAD

**Issue by jokerHao** [PokemonGoF/PokemonGo-Bot#3528]
i want open 2 bot same time
the HideMyAss proxy server almost not working
how to setup own private proxy server on ubuntu ?
or another solution ?

thank.

**Comment by JayJay1989** [comment]
im running 2 bots for more than 52hrs, i dont have any problem with running it without proxy

**Comment by simonsmh** [comment]
how about setting up a ssh tunnel?
