### ISSUE TITLE
Auto transfert > TransfertFirstLowIV

### ISSUE THREAD

**Issue by AschHack** [PokemonGoF/PokemonGo-Bot#3534]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. Are you running `master`? We work on the `dev` branch and then add that functionality to `master`. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.

### Expected Behavior
When having enough specific pokemon (let's say squirtle), the bot transfert the squirtle with the lower IV

### Actual Behavior
The bot transfert the squirtle with the higher IV.

**Comment by Ph4i1ur3** [comment]
Post your config.json, please
