### ISSUE TITLE
Being soft banned when running multiple bots with different credentials

### ISSUE THREAD

**Issue by tcchiu0** [PokemonGoF/PokemonGo-Bot#3536]
Being soft banned when running multiple bots on home PC.
Each bot uses its own account.
No device is running in background on any mobile device.
There is no problem when running single bot.

### Expected Behavior
Pokestops and catchables are visible

### Actual Behavior
No scanned pokestops and catchables.
Bot just moves around aimlessly.

### Your config.json (remove your credentials and any other private info)
{
    "auth_service": "google",
    "username": "",
    "password": "",
    "location": "",
    "gmapkey": "",
	"libencrypt_location": "encrypt.dll",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "evolve_all": "Pidgey,Weedle,Caterpie",
            "first_evolve_by": "cp",
            "evolve_above_cp": 100,
            "evolve_above_iv": 0.1,
            "logic": "or",
            "evolve_speed": 1,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 15 },
			"Greatball":      { "keep" : 80 },
			"Ultraball":      { "keep" : 70 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 0 },
            "Hyper Potion":   { "keep" : 20 },
			"Max Potion":     { "keep" : 60 },
            "Revive":         { "keep" : 0 },
            "Max Revive":     { "keep" : 50 },
            "Razz Berry":     { "keep" : 20 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 40
    },
    "websocket_server": false,
    "walk": 10,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 1,
    "evolve_captured": "Pidgey,Weedle,Caterpie",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 10},
	  "// Weedle": {"keep_best_cp": 10},
	  "// Caterpie": {"keep_best_cp": 10},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "any": {"keep_best_iv": 2},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

### Steps to Reproduce
Running multiple bots using different credentials.

### Other Information
OS: Windows 7
Git Commit: 41e5758961d7308f68aed4bad137f1201e5ed209
Python Version: Python 2.7.11 (32 bit)

**Comment by rbJARB** [comment]
Are you sure it's a soft ban? I got IP banned for about half an hour yesterday when running 4 bots. Pretty sure you can run one or two bots per IP.

**Comment by tcchiu0** [comment]
Even if running 2 bots for about 5-10 min, either one works.
Bot resumes normally after ~1hr
I am not sure if it is related to the device ID in the request message as related device info is configurable in C# API.

**Comment by Grimzwrath** [comment]
Boyfriend and I usually play on two different computers, one account each with no problems, now if we run both accounts at the same time we get banned.

**Comment by Tohrment** [comment]
I ran 2 bots for about 4 hours straight today and while I had an error pop it wasnt from a soft ban. I think it had to do with a perfect iv pokemon(seen a similar error on another issue and they were told it had to do with a perfect iv not registering properly). I just restarted them and away they went.

**Comment by Baconnaise** [comment]
I used to run six to seven at a time and after the update to latest .33 I think it is version. You cannot have more than two accounts on the same IP in my experience. I've run one and two bots no problems. Three or more you will get hit with spinning stop need to take a rest (softban). It's usually immediate but not permanent.

**Comment by bradleytje97** [comment]
@Baconnaise @Tohrment I am running different vpns of Virtual machines but i noticed when i run two bots at one VM they get banned after 5-10 min. Someone has an solution or somthing i an really stuck..

**Comment by siembz** [comment]
Im running  2 bots for 18 hours a day on the same computer. Never been banned
