### ISSUE TITLE
Mass Evolve Causing Soft IP Ban

### ISSUE THREAD

**Issue by lhung** [PokemonGoF/PokemonGo-Bot#3537]
### Expected Behavior
Evolving pokemons should not raise a flag and cause IP bans.

### Actual Behavior
No pokestops found right after mass evolving. Bot just walks randomly like other threads in https://github.com/PokemonGoF/PokemonGo-Bot/issues/3493, https://github.com/PokemonGoF/PokemonGo-Bot/issues/3435 or https://github.com/PokemonGoF/PokemonGo-Bot/issues/3406. I was only running one bot all the time.

### Your config.json
```
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "Bulbasaur,Charmander,Squirtle,Caterpie,Weedle,Pidgey,Rattata,Spearow,Ekans,Pikachu,Sandshrew,Nidoran F,Nidoran M,Clefairy,Vulpix,Jigglypuff,Zubat,Oddish,Paras,Venonat,Diglett,Meowth,Psyduck,Mankey,Growlithe,Poliwag,Abra,Alakazam,Machop,Bellsprout,Tentacool,Geodude,Ponyta,Slowpoke,Magnemite,Doduo,Seel,Grimer,Shellder,Gastly,Drowzee,Krabby,Voltorb,Exeggcute,Cubone,Koffing,Rhyhorn,Horsea,Goldeen,Staryu,Magikarp,Eevee,Omanyte,Kabuto,Dratini",
            "first_evolve_by": "cp",
            "evolve_above_cp": 0,
            "evolve_above_iv": 0,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": true
        }
```

### Steps to Reproduce
1. Save 120+ pokemons and pop lucky egg with above config.
2. The mass evolving should be completed around 35 minutes
3. Take another 5 minutes to release 
4. Bot starts walking randomly with no pokestops found, changing location yields same result
5. It does not involve multiple bots.
6. I was evolving at ~180k/hr speed for 35-40 minutes.

### Other Information
OS: Linux
Git Commit: 9ae1b785f0836d8769d011626d2bc071ed338bff
Python Version: 2.7.5

**Comment by Ph4i1ur3** [comment]
Maybe the evolve speed was too quick? Might be something worth testing

**Comment by CyberMew** [comment]
This happened to me as well. Rather than a soft ip ban, it was a soft ip ban + account because other accounts was working fine on the same ip. The default delay was ~20 seconds.

**Comment by PlanetoftheMapes** [comment]
Maybe we need to add some sort of random wait to humanize this it a bit..

**Comment by hklcf** [comment]
comfirm, same here

**Comment by nealqu** [comment]
Same here mass evolve next day I was banned.

**Comment by mjmadsen** [comment]
We've added configurable delays to these. If request not met, please reopen and clarify.
