### ISSUE TITLE
UpdateTitlestats not refreshing

### ISSUE THREAD

**Issue by orchid666** [PokemonGoF/PokemonGo-Bot#3538]
### Expected Behavior

 SHould refresh

### Actual Behavior

Is being displayed once in title but never refresh

### Your config.json (remove your credentials and any other private info)

  {
	  "type": "UpdateTitleStats",
	  "config": {
	  "min_interval": 10,
	  "stats": ["login", "uptime", "km_walked", "level_stats", "xp_earned", "xp_per_hour"],
	  "terminal_log": true,
	  "terminal_title": true
	  }
	  }

#
OS: OSX

**Comment by Moonlight-Angel** [comment]
Does it still log the stats inside the terminal ?

**Comment by relomy** [comment]
I think he has the latest dev judging from `"terminal_log": true` - maybe he has to  just change the name to `UpdateLiveStats` like you said.
