### ISSUE TITLE
Bot prints 'Hitmonlee' for 'Hitmonchan' candy

### ISSUE THREAD

**Issue by keugnu** [PokemonGoF/PokemonGo-Bot#3539]
### Expected Behavior
`[19:17:02] Captured Hitmonchan! [CP 964] [Potential 0.71] [15/3/14] [+210 exp]
[19:17:02] You now have 19 Hitmonchan `candy!`

### Actual Behavior
`[19:17:02] Captured Hitmonchan! [CP 964] [Potential 0.71] [15/3/14] [+210 exp]
[19:17:02] You now have 19 Hitmonlee candy!`

### Steps to Reproduce
Capture Hitmonchan

### Other Information
OS: Windows 10
Git Commit: 9ae1b785f0836d8769d011626d2bc071ed338bff
Python Version: 2.7.12

**Comment by Vvkmnn** [comment]
Lol.

**Comment by leadboots5** [comment]
This may be fixed in the latest dev.

**Comment by RedViper9** [comment]
Fixed in [#3455 ](https://github.com/PokemonGoF/PokemonGo-Bot/pull/3455)
