### ISSUE TITLE
In auto evolve, if not enough candy, should be faster

### ISSUE THREAD

**Issue by spoxus** [PokemonGoF/PokemonGo-Bot#3540]
### Expected Behavior
This should be a very fast check too see if there are enough candies. Or maybe i am wrong?
In the log, it took 5 seconds.
### Actual Behavior
[17:29:13] Captured Pidgey! [CP 391] [Potential 0.38] [0/7/10] [+210 exp]
[17:29:13] You now have 8 Pidgey candy!
[17:29:14] Failed to evolve Pidgey!
[17:29:19] Spun pokestop Gilda's Club. Experience awarded: 50. Items awarded: {u'Pokeball': 4}
[17:29:21] Moving towards pokestop Guardian  - 0.08km
### Your config.json (remove your credentials and any other private info)
```
	"evolve_captured":			"Caterpie, Pidgey, Weedle, Rattata",
```

**Comment by GitPupper** [comment]
The mods have been discussing about this. They might plan to remove the unnecessary pauses. Stay tuned!

**Comment by Happyrain67** [comment]
I do not recommend this evolve_captured.

This parametre send request to pgo's API for evolve without look number of candy.
Is Not like officiel's app and Is not comportement human like.

It's easy for Niantic to landmark use of bot with this and banned.... =S

Please, **Juste Use a Task "EvolvePokemon"**, this count candy before request API.

**Comment by spoxus** [comment]
Thank you @Happyrain67 @giomasce  for the input. Now I know about the causes, I'll close this.
