### ISSUE TITLE
Help needed with ipv6 access.

### ISSUE THREAD

**Issue by simonsmh** [PokemonGoF/PokemonGo-Bot#3543]
How to access niantic server with ipv6? 
Vultr(vps) IP was banned due to yesterday's upgrade. I want to have a try with ipv6, but how?

**Comment by z4ppy** [comment]
Same question here ! ^^

**Comment by retraut** [comment]
Same!

**Comment by k4n30** [comment]
Niantic don't support ipv6 connections - blame them :(
