### ISSUE TITLE
Wiki docs are out of date

### ISSUE THREAD

**Issue by simonsheridan** [PokemonGoF/PokemonGo-Bot#3544]
### Expected Behavior

Wiki docs have accurate information in the *Configuration* section about how to get up-and-running

### Actual Behavior

In the first paragraph of the first section in the wiki, the *Configuration* section titled * Usage (up-to-date)* says:

> copy config.json.example to config.json and release_config.json.example to release_config.json

https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files

However, release_config.json.example doesn't exist.  It's not a big change but not the most encouraging when the first thing you look at is wrong :D.

**Comment by Ph4i1ur3** [comment]
This will be updated sooner rather than later.

**Comment by GitPupper** [comment]
I updated the Wiki. Thanks for the heads up! 😊
