### ISSUE TITLE
Python doesn't find pokecli.py

### ISSUE THREAD

**Issue by PrinceHimeros** [PokemonGoF/PokemonGo-Bot#3545]
I have been following many tutorials to install the Bot and when I try to run it. it says that the pokecli.py file does not exist. How can I solve this? Thank you in advance.

Python Version: Python 2.7.12

**Comment by GitPupper** [comment]
`cd PokemonGo-Bot`
`source bin/activate`
`python pokecli.py`

Have fun 😀

**Comment by leadboots5** [comment]
Prince. you need to be in the PokemonGo-Bot directory. which is what @GitPupper said by 'cd PokemonGo-Bot'

**Comment by Klockner** [comment]
Prince are you using win32?

**Comment by pensiero** [comment]
@PrinceHimeros, if what @GitPupper said did not work for you, check if you are inside the correct folder

**Comment by RedViper9** [comment]
Please ask for help on the #help slack discussion board.
