### ISSUE TITLE
location-[user].json not updating on dev

### ISSUE THREAD

**Issue by madalilng** [PokemonGoF/PokemonGo-Bot#3546]
the location.json on web is not updating only on first run it gets updated

**Comment by orchid666** [comment]
I have the same issue, a "code 404, message File not found" appear on terminal that runs the server. Also, I can see the catchable pokemons getting updated but not the trainer.

**Comment by madalilng** [comment]
nope the problem is not in the web application..
its in the bot itself the bot not updating the location

**Comment by Adastras** [comment]
This was disabled [here](https://github.com/PokemonGoF/PokemonGo-Bot/commit/41de6f7250f408e51e49ff0380b029f0a3e9632e#diff-a8e82d1c2066f1b62d2f396a4e0e585bL994) in prep for a new web system, though I'm not sure why it was disabled when it isn't ready yet. You can edit pokemongo_bot/__init__.py and comment out the `pass` and uncomment the 3 lines below it to re-enable it.

**Comment by orchid666** [comment]
Thanks, it fixed my problem :)

**Comment by madalilng** [comment]
thankyou

**Comment by Niuuuuu** [comment]
nice, thanks!

**Comment by Dropbear67** [comment]
This fix worked for me too. Thanks very much

**Comment by silva96** [comment]
now the fix makes the distance empty

```
[13:18:48] Moving towards pokestop Instituto Confucio - 0.09km
[13:18:48] {'distance_unit': '', 'distance': '', 'current_position': (-33.442803022429835, -70.66315780035433), 'last_position': (-33.44282336361273, -70.66313832839448)}
```

```
2016-08-11 13:18:50,457 [       cli] [INFO] Ran for 0:01:17
2016-08-11 13:18:50,457 [       cli] [INFO] Total XP Earned: 150  Average: 6980.14/h
2016-08-11 13:18:50,457 [       cli] [INFO] Travelled 0.00km
```

**Comment by rohimkudus** [comment]
thanks

**Comment by rohimkudus** [comment]
thank you

**Comment by k4n30** [comment]
#3767 has been merged, should be fixed in latest dev version
