### ISSUE TITLE
[Feature Request] Differentiate Between Unlimited and "Purchased" Incubator use.

### ISSUE THREAD

**Issue by imvikash00** [PokemonGoF/PokemonGo-Bot#3552]
Blue incubators are difficult to get so I use it only for 10km eggs. Is there any configuration to prevent bot from using Blue Incubator?

**Comment by RedViper9** [comment]
I don't believe this feature exists.

**Comment by jimmywarting** [comment]
Why should it matter?
In the end you have to use all eggs anyway to get new eggs. You can not throw away any.

So you might as well use them all
the quicker you get rid of 2km egg the faster you will get a 10km egg

**Comment by imvikash00** [comment]
@jimmywarting I am under the assumption that eggs hatched under Blue incubator yield new and powerful pokemon. That is why I thought this could be added as a feature. Correct me If m wrong.

**Comment by jimmywarting** [comment]
@imvikash00 do you have something to back up that story?

**Comment by imvikash00** [comment]
@jimmywarting That story is just based on my personal experience which may not be true. But [https://youtu.be/QcqUfCYapbo?t=63](this) video by Lifehacker talks about an interesting way of using eggs. So I believe bot should be smart enough to use blue incub. for 10 km whenever available.

**Comment by pensiero** [comment]
That video is intended for people who are not using any bot :) Bot don't cares about hatching eggs, they walk as tireless walkers, better than olympics contestants :P

**Comment by imvikash00** [comment]
@pensiero I think you are forgetting the point that most of the PRs in this proj. talks about collecting more XPs and this trick definitely fits in that picture.

**Comment by pensiero** [comment]
The video doesn't say that if you use a unlimited incubator you get less powerful pokemon

**Comment by imvikash00** [comment]
@pensiero I think you should read the comments above. Whole discussion is about how to effectively use incubators and I believe I have made a valid point.

**Comment by jimmywarting** [comment]
The video dosent say that you will get more XP or better Pokemon The most efficient way is when you have a available incubators then use it directly

**Comment by RedViper9** [comment]
Arguments aside, this is a feature request.

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by imvikash00** [comment]
I did.

**Comment by k4n30** [comment]
Feathub may be turned off in favour of better GitHub tags, issue templates, and voting structures. Please feel free to continue using this issue (but don't delete the Feathub request just yet)

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680
