### ISSUE TITLE
Copy and pasted directly from the original config and still getting this error.. 

### ISSUE THREAD

**Issue by VerseCity** [PokemonGoF/PokemonGo-Bot#3554]
Just started getting this error after it had been working fine for 24 hours. Stopped and started several times and I didn't change anything in my config. I am intelligent but by no means a programmer. Please help. 
```

configs/config.json:5:16: Error: Can not decode value starting with character u'\u201c'
   |  At line 5, column 16, offset 119
configs/config.json:5:23: Info: Recovering parsing after character u','
   |  At line 5, column 23, offset 126
configs/config.json:108:6: Warning: Object contains duplicate key: u'// Zubat'
   |  At line 108, column 6, offset 2952
   |  Object started at line 97, column 15, offset 2376
configs/config.json: has errors
2016-08-10 23:26:33,848 [       cli] [CRITICAL] Error with configuration file

**Comment by anourani959** [comment]
paste your config into http://jsonlint.com/ to check for errors

feel free to share the config itself

**Comment by VerseCity** [comment]
@anourani959

{
	"auth_service": "google",
	"username": "*******",
	"password": "******",
	"location": “ ** ** * ”,
	"gmapkey": "********",
	"libencrypt_location": "",
	"tasks": [{
		"type": "HandleSoftBan"
	}, {
		"type": "CollectLevelUpReward"
	}, {
		"type": "IncubateEggs",
		"config": {
			"longer_eggs_first": true
		}
	}, {
		"type": "TransferPokemon"
	}, {
		"type": "EvolvePokemon",
		"config": {
			"evolve_all": "none",
			"first_evolve_by": "cp",
			"evolve_above_cp": 500,
			"evolve_above_iv": 0.8,
			"logic": "or",
			"evolve_speed": 20,
			"use_lucky_egg": false
		}
	}, {
		"type": "RecycleItems",
		"config": {
			"min_empty_space": 15,
			"item_filter": {
				"Pokeball": {
					"keep": 4
				},
				"Potion": {
					"keep": 0
				},
				"Super Potion": {
					"keep": 10
				},
				"Hyper Potion": {
					"keep": 75
				},
				"Revive": {
					"keep": 30
				},
				"Razz Berry": {
					"keep": 25
				}
			}
		}
	}, {
		"type": "CatchVisiblePokemon"
	}, {
		"type": "CatchLuredPokemon"
	}, {
		"type": "SpinFort"
	}, {
		"type": "MoveToFort",
		"config": {
			"lure_attraction": true,
			"lure_max_distance": 2000
		}
	}, {
		"type": "FollowSpiral",
		"config": {
			"diameter": 4,
			"step_size": 70
		}
	}],
	"map_object_cache_time": 5,
	"forts": {
		"avoid_circles": true,
		"max_circle_size": 50
	},
	"websocket_server": false,
	"walk": 4.16,
	"action_wait_min": 1,
	"action_wait_max": 4,
	"debug": false,
	"test": false,
	"health_record": true,
	"location_cache": true,
	"distance_unit": "km",
	"reconnecting_timeout": 15,
	"evolve_captured": "NONE",
	"catch_randomize_reticle_factor": 1.0,
	"catch_randomize_spin_factor": 1.0,
	"catch": {
		"any": {
			"catch_above_cp": 0,
			"catch_above_iv": 0,
			"logic": "or"
		},
		"// Example of always catching Rattata:": {},
		"// Rattata": {
			"always_catch": true
		}
	},
	"release": {
		"any": {
			"release_below_cp": 0,
			"release_below_iv": 0,
			"logic": "or"
		},
		"// Example of always releasing Rattata:": {},
		"// Rattata": {
			"always_release": true
		},
		"// Example of keeping 3 stronger (based on CP) Pidgey:": {},
		"// Pidgey": {
			"keep_best_cp": 3
		},
		"// Example of keeping 2 stronger (based on IV) Zubat:": {},
		"// Zubat": {
			"keep_best_iv": 2
		},
		"// Also, it is working with any": {},
		"// any": {
			"keep_best_iv": 3
		},
		"// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
		"// Zubat": {
			"keep_best_cp": 2,
			"keep_best_iv": 3
		}
	},
	"vips": {
		"Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
		"any": {
			"catch_above_cp": 900,
			"catch_above_iv": 0.9,
			"logic": "or"
		},
		"Lapras": {},
		"Moltres": {},
		"Zapdos": {},
		"Articuno": {},

		"// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
		"Mewtwo": {},
		"Dragonite": {},
		"Snorlax": {},
		"// Mew evolves to Mewtwo": {},
		"Mew": {},
		"Arcanine": {},
		"Vaporeon": {},
		"Gyarados": {},
		"Exeggutor": {},
		"Muk": {},
		"Weezing": {},
		"Flareon": {}

	}
}

**Comment by bubbyhill** [comment]
"location": “ * ** * ”,

fix the 2nd set of quotes

**Comment by VerseCity** [comment]
wft... so simple. thanks.
