### ISSUE TITLE
Suggestion Use Curve Ball

### ISSUE THREAD

**Issue by zviper13579** [PokemonGoF/PokemonGo-Bot#3566]
Anyone know how to code it so the bot will always use curveballs? It will increase the amount of xp per hour.

**Comment by IAP-Reloaded** [comment]
How would it do this?

**Comment by lhung** [comment]
It is already made available in the config and is on be default.
```    
"catch_randomize_reticle_factor": 1.0,
"catch_randomize_spin_factor": 1.0
```
