### ISSUE TITLE
[wiki] a lot of broken links

### ISSUE THREAD

**Issue by nivong** [PokemonGoF/PokemonGo-Bot#3571]
https://github.com/PokemonGoF/PokemonGo-Bot/wiki
```
How to run with Docker
Linux
Mac
Windows
```
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Getting-Started
```
Check installation guide(s)
Also have a look at our FAQ
Want do contribute/develop?
```
https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Softban
```
still linking to the old wiki
```
I can contribute to it sadly enough 
@eggins and @projectbarks please check/fix :)

**Comment by TheSavior** [comment]
@nivong I believe all of the valuable content from the wiki is now either in the `docs/` folder or on the README. I have disabled the wiki. Feel free to open PRs for any other documentation changes we need to make. 

Thanks!

**Comment by nivong** [comment]
Yup that is better I believe, will have to update the readme now though ;)
