### ISSUE TITLE
Implement Proxy Support

### ISSUE THREAD

**Issue by nazzer23** [PokemonGoF/PokemonGo-Bot#3574]
## Idk how to request that you add proxy support so uhm here?

**Comment by RedViper9** [comment]
Correct me if I'm wrong, but a proxy only handles browser traffic. You want a VPN. There are free and paid ones and the bot works fine through a VPN.

**Comment by TheSavior** [comment]
We had a [PR](https://github.com/PokemonGoF/PokemonGo-Bot/pull/2358) that added proxy support to the bot so that you can use a VPN. It had a bug and was [reverted](https://github.com/PokemonGoF/PokemonGo-Bot/pull/2374). 

Perhaps @alecuba16 can re-add that functionality, or someone can utilize the code he wrote the first time to implement this feature.

**Comment by maddo7** [comment]
There are HTTP and Socks proxies. HTTP proxies tunnel HTTP/HTTPS requests only while socks can tunnel all requets. But isn't Pokemon Go just using HTTP(S) requests anyways? A VPN would be overkill. There aren't that many VPNs so ppl would end up having the same and getting banned anyways, there are far more HTTP/SOCKS proxies out there.

**Comment by Lordedi** [comment]
I think I have IP banned because I can't login with my google account:
[11:32:38] Loading cached location...
[11:32:38] Loaded location (34.009797, -118.49813, 0.0) from cache
[11:32:38] Login procedure started.Traceback (most recent call last):
  File "pokecli.py", line 530, in <module>
    main()
  File "pokecli.py", line 138, in main
    report_summary(bot)
  File "pokecli.py", line 147, in report_summary
    metrics.capture_stats()
  File "/home/raviss_e/PokemonGo-Bot/pokemongo_bot/metrics.py", line 76, in capture_stats
    response_dict = request.call()
  File "/home/raviss_e/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
    if not self.can_call():
  File "/home/raviss_e/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 58, in can_call
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

but with my PTC account, it's work fine...

**Comment by Dracon23** [comment]
@RedViper9 No, proxies handle all sorts of traffic, depending on their type. Most Socks proxies handle a lot more then just your browser traffic.

**Comment by ale-batt** [comment]
@Lordedi When you're IP banned, the bot it's just walking but no pokemon appear.
I think your problem is somewhere else..

**Comment by Lordedi** [comment]
@ale-batt  maybe but since yesterday I cannot resolve my problem :/

**Comment by ale-batt** [comment]
Are you using the `dev` branch ?

**Comment by Lordedi** [comment]
Yes

**Comment by ale-batt** [comment]
the last update ?
`git fetch ; git pull`

**Comment by Lordedi** [comment]
Yes 💃

**Comment by Carlito007** [comment]
hi how can i use vpn/proxy to connect bot ?

**Comment by ale-batt** [comment]
@Lordedi So no idea... Try a different config file :/

**Comment by Lordedi** [comment]
@ale-batt Yes, strange because ptc account works fine but not google mh
Anyway thanks for your help

**Comment by MaxPPP** [comment]
I am running the Bot on a Ubuntu VPS and it works perfect for an Hour or two..then it looks like i
get a IP-Ban because he wont find Pokestops or Pokemon to catch.

Is there a known work-around for using a proxy with the Bot ?

**Comment by jalliance** [comment]
Set an environment variable and just run normally. 
    
    ` export http_proxy=http://server-ip:port/`

**Comment by mrik974** [comment]
Will there be support for SOCKS Proxies as well ?

**Comment by umbreon222** [comment]
Similiar issues #3489  #3488  #3477  #3233

**Comment by steffenreimann** [comment]
Where this variable has to be inserted?

`export http_proxy=http://server-ip:port/ `

**Comment by mrik974** [comment]
You dont have to "insert it", just type this command before launching the bot via your command prompt.

**Comment by alxnegrila** [comment]
If you need socks, you can use proxychains(4).

**Comment by firzzen** [comment]
@jalliance problem with that is it can only be used for one bot. I suppose the idea of proxying is meant for multiple.

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by k4n30** [comment]
Tor support has been added to the docker implementation of the bot #4108 Although it may not be the final solution you're after, it's a step in the right direction

**Comment by mcrowson** [comment]
The way it is done in #4108 is just to set the environment variables for the bot so the requests library uses the proxy.

http://docs.python-requests.org/en/master/user/advanced/#proxies

I'm sure you could use this for any proxy you wanted.

**Comment by br0kenb1nary** [comment]
I have created a plugin that adds proxy support by finding available proxies based on your players latitude and longitude position. Hope it helps: https://github.com/br0kenb1nary/PogoPlugin

**Comment by k4n30** [comment]
@br0kenb1nary do you mind creating a pull request or is this the first candidate for the [plugins](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/plugins.md) 

@TheSavior - FYI

**Comment by br0kenb1nary** [comment]
Created a pull request. The plugin is stable however being that it is Shell based on not Python based I am not sure what you want included to support the Plugin format laid out here: https://github.com/TheSavior/test-pgo-plugin

**Comment by k4n30** [comment]
@TheSavior care to elaborate, are we going to allow plugin PRs against dev? or what was the plan to show users the available plugins?

**Comment by br0kenb1nary** [comment]
Perhaps a master plugin repo list with array: name, git URL and init file. Clone to subdirectory on initial load and run the init file as: if sh then if Python then

Keeps everything independent and avoids cross branch conflicts

**Comment by TheSavior** [comment]
The goal of plugins is that end users can add additional tasks from repos that other people create than what is in this repo. They can install the ones they want by adding them to their config. They would not be installed automatically or for all users. 

However, what you have created isn't a plugin in the pokemongo-bot sense. It is just a run script. I think if we were to accept a PR adding this functionality to core, it would probably be some change to `pokecli.py`. Essentially exactly like this PR: https://github.com/PokemonGoF/PokemonGo-Bot/pull/2358

When I say exactly, I think I mean exactly that PR + whatever fix is needed that caused the failures. What the failures were, I'm not sure I remember anymore.
