### ISSUE TITLE
Failed building wheel for xxhash

### ISSUE THREAD

**Issue by R1cc0** [PokemonGoF/PokemonGo-Bot#3576]
Hi guys !
I have found lots of errors like this in "issues" section, just install python-devel and it's ok...but doesn't work for me...

 Running setup.py clean for xxhash
  Running setup.py bdist_wheel for pycryptodomex ... ^Cerror
  Failed building wheel for pycryptodomex
Complete output from command /root/Poke/bounthyht/PokemonGo-Bot/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ulwiEt/xxhash/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpdz3DSqpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'xxhash' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/xxhash
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DVERSION=0.6.1 -I/usr/include/python2.7 -c python-xxhash.c -o build/temp.linux-x86_64-2.7/python-xxhash.o -std=c99 -O3 -Wall -W -Wundef -Wno-error=declaration-after-statement
  gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
  error: command 'gcc' failed with exit status 1

[root@WarMachine PokemonGo-Bot]# rpm -qa | grep python | grep 2.7
python-2.7.12-1.fc24.i686
python-devel-2.7.12-1.fc24.x86_64
python-libs-2.7.12-1.fc24.i686
python-2.7.12-1.fc24.x86_64
python-libs-2.7.12-1.fc24.x86_64
libreport-python3-2.7.2-1.fc24.x86_64
python-devel-2.7.12-1.fc24.i686

[root@WarMachine PokemonGo-Bot]# uname -a
Linux WarMachine 4.6.5-300.fc24.x86_64

Thanks a lot

**Comment by Dracon23** [comment]
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory <--- Try and find that RPM?

**Comment by R1cc0** [comment]
GOOD !!!! thanks a lot
