### ISSUE TITLE
ERROR. Snipping feature

### ISSUE THREAD

**Issue by ocoot** [PokemonGoF/PokemonGo-Bot#3577]
i'm using latest dev version of both repos. when on map appears the pokemon what i want to snipe, my bot didn't change the location to target location. its normal like this?

**Comment by Ph4i1ur3** [comment]
Follow the issue template, config.json, OS, git version, etc.

**Comment by k4n30** [comment]
yes that's correct as it's done only to encounter the bot and then change back, there is no time to log the location
