### ISSUE TITLE
Master isn't accepting -m or --mode

### ISSUE THREAD

**Issue by EvilSupahFly** [PokemonGoF/PokemonGo-Bot#358]
### Expected Behavior
Use -m or --mode

### Actual Behavior
pokecli.py: error: unrecognized arguments: --mode all

### Steps to Reproduce
Run python pokecli.py -a google -u [USER] -p [PASS] --location "37 Church Street, St. Catharines, ON" -c 50 -w 4.16 --mode all

### Other Information
OS: Ubuntu Linux 15.10 running kernel 4.5.3-040503-generic #201605041831 SMP Wed May 4 22:33:50 UTC 2016 on x86_64 x86_64

Git Commit: 1f426d427d1f258d8fb8d2abdcf4d3dee7a42c7f

**Comment by hnq90** [comment]
@EvilSupahFly There's no `mode` option in master branch. Try to read their README here: https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/README.md

**Comment by EvilSupahFly** [comment]
Sorry!

I was looking at the Read-Me for the DEV branch!
