### ISSUE TITLE
Limit radius of movement / Make bot stay in a certain area

### ISSUE THREAD

**Issue by Dropbear67** [PokemonGoF/PokemonGo-Bot#3580]
I want to stick to a certain radius of my location start point, but don't to have to create a map of waypoints..

Is there a way of getting the bot to wander around within an area of pokestops within a certain distance of the starting point?

**Comment by ReinyDays** [comment]
I found making a map of waypoints to be pretty simple and effective, actually...
All you need to do is plan a 5 min tour past as many (frequently lured) pokestops as possible. This method is usually more efficient than the walking algorithms.

**Comment by oleerik** [comment]
I'm wondering about this too:

max_steps was removed from the configuration options.

You can now change the behavior of the bot by modifying the \"tasks\" key.

Sadly it doesn't give much more info as the config doc also shows max_steps.


@ReinyDays do you have any proper examples of a config file + waypoint file that works? I've had issues getting it to actually follow the points myself.

**Comment by jrjhealey** [comment]
```
   {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
```

If my understanding is correct, this task in the config.json controls how your avatar moves within a defined area.

**Comment by oleerik** [comment]
@jrjhealey I believe you are correct but I cannot find any documentation regarding diameter and step_size, so modifying that to something more usable would be rough without knowing what they amount to in terms of meters, for instance.

**Comment by ReinyDays** [comment]
@oleerik  you have to make changes in the config, similar to config.json.path.example.
you have to replace the normal walking algorithm
`        {
            "type": "MoveToFort",
            "config": {
                "lure_attraction": true,
                "lure_max_distance": 2000
            }
        },
        {
            "type": "FollowSpiral",
            "config": {
                "diameter": 4,
                "step_size": 70
            }
        }`
with the pathing:
`        {
            "type": "FollowPath",
            "config": {
                "path_mode": "loop",
                "path_start_mode": "first",
                "path_file": "configs/path.example.json"
            }
        }
`
and you need to make a file 'path.example.json' (or something else, but it should be the same as mentioned in code above) with coordinates (you can get em easily in google maps), like so:

[
	{"location": "51.304910, 4.290544"},
	{"location": "51.304258, 4.289299"},
	{"location": "51.303594, 4.288720"},
	{"location": "51.304084, 4.288409"},
        {"location": "51.304440, 4.287787"}

]

^ this is a short path near Antwerp Belgium. only 3 pokestops, but perma lured and only rare pokemon spawn there.

**Comment by oleerik** [comment]
Ah, thank you very much @ReinyDays. My problem was that I kept MoveToFort as a task :) 

This still doesn't properly resolve the original question but it helps me personally greatly!

**Comment by RedViper9** [comment]
You can do this to some extent if you use the MoveToMapPokemon option with "update_map": false,. Your bot's location won't get pushed to the map and you can drop the pin wherever you want the bot to go. It will still nab any pokemon in the search radius, but won't leave that area.

**Comment by Anakin5** [comment]
Can be done with CampFort. Closed.
