### ISSUE TITLE
Workaround for network restrictions?

### ISSUE THREAD

**Issue by ReinyDays** [PokemonGoF/PokemonGo-Bot#3581]
I'm having a rather niche problem I'm afraid...

### Expected Behavior

Installed and tested bot on work laptop at home, it worked.

### Actual Behavior

I'd like to run it at work, but after login the character doesn't move and no logs are reported.
In the git cmd, it gets stuck on:
'Python: (date+time) [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com'
After a while i get an error:
'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range (128) (url: https://app.getsentry.com/api/90254/store/) ...
followed by:
max retries exceede with url /collect ...
which i guess meant that he tried too much and it didn't help?

### Steps to Reproduce

Network restrictions, probably?

Can someone tell me if there is some sort of workaround or am i just screwed? :(

### Information

OS: windows 7
Git commit: 584782fa1425e19ff9d94d16728d95781ade3312
Python Version: 2.7.10

**Comment by vamirineni87** [comment]
set     "health_record": false

**Comment by ReinyDays** [comment]
ah yes, that skips the first step, but next up is the account login, which faces more or less the same problem. 
I will have to fix some sort of vpn, i believe there's probably nothing that can be done from within the program itself?

**Comment by GitPupper** [comment]
No, you would have to use a VPN. Some known services are being banned by Niantic so be careful with your choice.
