### ISSUE TITLE
Dev - disable lat long logging

### ISSUE THREAD

**Issue by BasvanH** [PokemonGoF/PokemonGo-Bot#3582]
### Expected Behavior
I want to disable the 'lat' 'long' logging in the dev build.

### Actual Behavior
{'distance_unit': '', 'distance': '', 'current_position': (52.061011021257656, 4.2319219650586595), 'last_position': (52.06107408529108, 4.231919556713865)}

### Steps to Reproduce
Run the dev build.

### Other Information
OS: CentOS 7
Git Commit: 350148e8443e35a6f5b74169b7ac5fd26815fe7b
Python Version: Python 2.7.5

**Comment by FranWatcher** [comment]
#3484 is the same issue

**Comment by relomy** [comment]
In `colored_logging_handler.py` you can add:

``` python
if event == 'position_update':
    return
```

under

``` python
# Replace message if necessary
if event == 'catchable_pokemon':
    message = 'Something rustles nearby!'
```

And it'll stop updating with that message.

**Comment by k4n30** [comment]
#3484
