### ISSUE TITLE
Detect config changes on the fly

### ISSUE THREAD

**Issue by Dracon23** [PokemonGoF/PokemonGo-Bot#3588]
New bot user, following development for two weeks now...

I'm still tinkering with the bot, tweaking config here and there... which leads me to my request...

Is it possible to have to bot monitor the config and actually reload it when parts like release, recycling config or tasks to run have changed **_without_** having to restart?

**Comment by fari-99** [comment]
wow, this is a good feature, but if you do that, I will recommend setting the update for every cycle for every like 15 minutes. because if you check it every cycle it will overhead. I think haha. or you can just use keyboard input to check the config. but hey that's a good feature.

**Comment by Dracon23** [comment]
There are possibilities to do this in python on linux, don't know how mac and windows compare.

**Comment by fari-99** [comment]
hoo, so you get "notice" the file is changing, and then restart the bot. love to see that happen. if i want to just farming pokeball, i need to delete catch task, after get enough pokebal i put the task back.

**Comment by Dracon23** [comment]
@fari-99 exactly my thought.

**Comment by HecticSeptic** [comment]
This is possible on Windows, one of the Po-Go-Map projects had this enabled, though it may have been due to debugging being enabled.

**Comment by Dracon23** [comment]
I haven't touched windows in over two years, let alone did stuff to it (aka wrote something) at all. So I wouldn't know

Just wanted to give some input :F

**Comment by Dracon23** [comment]
Necro does this, so it's def possible on win, just may not be in python

**Comment by raxxon** [comment]
Just attach it to the relog cycle. Bot already has a login recycle event every 30 minutes or so, just re-read configuration when logging back in.

**Comment by Dracon23** [comment]
I wouldn't want to wait for a relog cycle to be honest... I'm currently investigating a use case for a different app I work on, this shouldn't be too hard from what I gather...

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by sohje** [comment]
I already did this with with following changes:
Config_changed
```python
def initialize(bot, config):
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
    bot.workers = tree
    bot.metrics.capture_stats()
    bot.health_record = BotEvent(config)
    bot.config_file = config_file

def check_config_modification(config_file):
    mtime = [os.stat(config_file).st_mtime]
    config_file = config_file

    def check_cfg():
        mdate = os.stat(config_file).st_mtime
        if mtime[0] == mdate:  # mtime didnt change
            return False
        else:
            mtime[0] = mdate
            return True

    return check_cfg
```
Inside loop, i think there should be a delay beetween checks, but just fast work-around.
```python
while not finished:
    try:
        bot = PokemonGoBot(config)
        bot.start()
        initialize(bot, config)
        config_changed = check_config_modification(config_file)

        bot.event_manager.emit(
            'bot_start', sender=bot,
            level='info', formatted='Starting bot...'
        )

        while True:
            bot.tick()
            if config_changed():
                logger.info('Config changed! Re-apply configuration.')
                config, _ = init_config()
                if config:
                    initialize(bot, config)
                else:
                    logger.info('Check your configration!')
```
Maybe this will broke some bot logic - im totally new to this project.
Not sure about Windows system, but it works under OSx - 10 bots running fine for ~ 7hours.

**Comment by k4n30** [comment]
@sohje do you mind creating a pull request? The devs will review it before merging so you can get feedback on if it breaks anything or not

**Comment by mjmadsen** [comment]
Merged
