### ISSUE TITLE
Task Order not honored

### ISSUE THREAD

**Issue by Dracon23** [PokemonGoF/PokemonGo-Bot#3589]
### Expected Behavior
Bot honors the task order, for example spin pokestops BEFORE catching pokemon

### Actual Behavior
Bot catches pokemon first, no matter what I tell it, resulting in it running out of pokeballs and thus stuck in "wild xyz appeared - no usable pokeballs" loop, till I remove catch tasks from config.

### Your config.json (remove your credentials and any other private info)
https://gist.github.com/Dracon23/4b296cefd5ed4f09b282fd68d2b2a50e

### Steps to Reproduce

1. Find a spot rich with pokemon and not in spin range of any pokemon.
2. Let it sit there, catch pokemon, it WILL run out at some point.
3. Next pokemon appears, loop.

### Other Information
OS: Ubuntu Linux 16.04.1 - headless server
Git Commit: a8242f7bda8cfb1b726173018a903fd4c58f87cc
Python Version: Python 2.7.12 (default, Jul  1 2016, 15:12:24)

**Comment by BriceSD** [comment]
@Dracon23 Please post your logs

**Comment by Dracon23** [comment]
[Fresh right now](https://gist.github.com/Dracon23/aa1db1c22371101ca22900f5ce694412)

**Comment by Gobberwart** [comment]
Interesting. Your log says you have 99 Ultra Balls available. Should the bot not use these if you have no Pokeballs or Great Balls in your inventory? Seems odd to me. The pokemon catch worker should use whatever the lowest available ball is by default:

```
            current_ball = ITEM_POKEBALL
            while items_stock[current_ball] == 0 and current_ball < maximum_ball:
                current_ball += 1
            if items_stock[current_ball] == 0:
                self.emit_event('no_pokeballs', formatted='No usable pokeballs found!')
                break
```

I realise this doesn't answer your question, but there appears to be an issue somewhere related to ball selection. 

Maybe if no usable balls, then bot should "run away" to avoid getting stuck in a loop?

**Comment by BriceSD** [comment]
@Gobberwart if you’re right and he doesn’t use his ultraball, it’s a known issue and a fix is coming for this. #3421

**Comment by keugnu** [comment]
Potentially related #3563

**Comment by Dracon23** [comment]
Yes, I have ultras.... And i,'ve seen the other issue and was pointed to a fix on slack.

**Comment by Dracon23** [comment]
What's bugging me (heh)... Is that he won't continue to a poke stop... He just keeps looping the encounter, and doesn.'t do jack till the mon disappears...

**Comment by k4n30** [comment]
OP Issue resolved
