### ISSUE TITLE
use curl instead of wget as fallback

### ISSUE THREAD

**Issue by jimmywarting** [PokemonGoF/PokemonGo-Bot#3590]
I tried to run `setup.sh -e` on mac 

```
./setup.sh: line 17: wget: command not found
tar: Error opening archive: Failed to open 'pgoencrypt.tar.gz'
```

wget don't come pre installed on mac, curl dose

**Comment by simonsmh** [comment]
Wget should be installed by default not curl.
Which system do you use?

**Comment by simonsmh** [comment]
OK i see you are on mac.

**Comment by simonsmh** [comment]
Does `curl -O http://pgoapi.com/pgoencrypt.tar.gz` work?

**Comment by jimmywarting** [comment]
> Does curl -O http://pgoapi.com/pgoencrypt.tar.gz work?

yes

**Comment by nivong** [comment]
Thanks for the report, will be fixed in next PR.

**Comment by simonsmh** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/pull/3592

**Comment by simonsmh** [comment]
I don't have mac so I don't know how shell actually worked on mac. Hope it works or anyone have a better solution.
:(

**Comment by nivong** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/pull/3593

**Comment by kestel** [comment]
Curl may be better, but curl it's not in base system on FreeBSD for example, I think we need additional checks and OS detection.

**Comment by simonsmh** [comment]
Close plz. #3593

**Comment by lightyoruichi** [comment]
brew install wget
