### ISSUE TITLE
Recycle item not working 

### ISSUE THREAD

**Issue by Tagada22** [PokemonGoF/PokemonGo-Bot#3594]
Hello

I see in my bot, recycle item not working 

My config 

 "type": "RecycleItems",
"config": {
"min_empty_space": 10,
"item_filter": {
"Pokeball":     { "keep" : 0 },
"Greatball":    { "keep" : 100 },
"Ultraball":    { "keep" : 130 },
"Max Revive":   { "keep" : 20 },
"Potion":{ "keep" : 0 },
"Super Potion": { "keep" : 0 },
"Hyper Potion": { "keep" : 10 },
"Revive":{ "keep" : 10 },
"Razz Berry":   { "keep" : 100 }

Ans when i look my bag pokemon 

I have 

50 pokeball 
1 greatball 
0 super ball 

30 potion 
....

Bref not working.

Have you got an idea ? 

Thanks

**Comment by nivong** [comment]
Use the issue template or don't create an issue. It's working fine for me.

**Comment by Tagada22** [comment]
Config working 

But not recycle items not numer what i enter

**Comment by nikhil-pandey** [comment]
When you specify `min_empty_space`, it only recycles when space is less than specified number.

Close the issue.

**Comment by LeeRongWen** [comment]
@nikhil-pandey 

how about if we config like this ?

{
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
			"Greatball":      { "keep" : 50 },
			"Ultraball":      { "keep" : 50 },
            "Potion":         { "keep" : 5 },
            "Super Potion":   { "keep" : 5 },
            "Hyper Potion":   { "keep" : 5 },
			"Max Potion":     { "keep" : 5 },
            "Revive":         { "keep" : 5 },
            "Razz Berry":     { "keep" : 50 }
          }
        }
      },
