### ISSUE TITLE
Not able to see wiki link

### ISSUE THREAD

**Issue by imvikash00** [PokemonGoF/PokemonGo-Bot#3595]
I am unable to see wiki link. Anyone facing similar issue?

**Comment by tnlin** [comment]
Same there, just about to open an issue

**Comment by pensiero** [comment]
They are probably moving it to the docs folder

**Comment by chrisgzf** [comment]
Please see a8242f7. The wiki should be closed at the moment.

**Comment by tnlin** [comment]
docs here
https://github.com/PokemonGoF/PokemonGo-Bot/tree/master/docs

**Comment by imvikash00** [comment]
Thanks @tnlin

**Comment by k4n30** [comment]
#3602 #3615
