### ISSUE TITLE
bot seems to do nothing

### ISSUE THREAD

**Issue by Miamony** [PokemonGoF/PokemonGo-Bot#3597]
yesterday the bot just does this
[12:54:37] {'distance_unit': '', 'distance': '', 'current_position': (53.55415336271413, 10.144893923285677), 'last_position': (53.554157094292975, 10.144969475108015)}
[12:54:39] Skipping Recycling of Items. 164 space left in bag.
[12:54:39] {'distance_unit': '', 'distance': '', 'current_position': (53.554171115426655, 10.144821841312917), 'last_position': (53.55415336271413, 10.144893923285677)}
[12:54:41] Skipping Recycling of Items. 164 space left in bag.
[12:54:41] {'distance_unit': '', 'distance': '', 'current_position': (53.55418156767736, 10.144749400759386), 'last_position': (53.554171115426655, 10.144821841312917)}
[12:54:42] Skipping Recycling of Items. 164 space left in bag.
[12:54:42] {'distance_unit': '', 'distance': '', 'current_position': (53.55416512090939, 10.144681327025266), 'last_position': (53.55418156767736, 10.144749400759386)}
[12:54:44] Skipping Recycling of Items. 164 space left in bag.
[12:54:44] {'distance_unit': '', 'distance': '', 'current_position': (53.55416163121482, 10.144624433655734), 'last_position': (53.55416512090939, 10.144681327025266)}
[12:54:45] Skipping Recycling of Items. 164 space left in bag.
[12:54:45] {'distance_unit': '', 'distance': '', 'current_position': (53.554154654473436, 10.14456756899911), 'last_position': (53.55416163121482, 10.144624433655734)}
[12:54:47] Skipping Recycling of Items. 164 space left in bag.
[12:54:47] {'distance_unit': '', 'distance': '', 'current_position': (53.554151567304544, 10.144477750370003), 'last_position': (53.554154654473436, 10.14456756899911)}
[12:54:48] Skipping Recycling of Items. 164 space left in bag.
[12:54:48] {'distance_unit': '', 'distance': '', 'current_position': (53.55417285765628, 10.144396858421832), 'last_position': (53.554151567304544, 10.144477750370003)}
[12:54:52] Skipping Recycling of Items. 164 space left in bag.

und i dont see any fort spins or pokemon captures  for abouzt 6 hours

**Comment by crusardri** [comment]
same here

**Comment by extink** [comment]
Please use the template to create an issue, now we are missing some crucial information (OS, Python version, config, etc.)

**Comment by Miamony** [comment]
OS: Win10

config 1:
"libencrypt_location": "./encrypt.so",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball":         { "keep" : 50 },
            "Greatball":        { "keep" : 50 },
            "Ultraball":        { "keep" : 50 },
            "Masterball":       { "keep" : 50 },
            "Potion":           { "keep" : 0 },
            "Super Potion":     { "keep" : 0 },
            "Hyper Potion":     { "keep" : 0 },
            "Max Potion":       { "keep" : 0 },
            "Revive":           { "keep" : 0 },
            "Max Revive":       { "keep" : 0 },
            "Lucky Egg":        { },
            "Incense":          { },
            "Spicy Incense":    { },
            "Cool Incense":     { },
            "Floral Incense":   { },
            "Troy Disk":        { },
            "X Attack":         { "keep" : 0 },
            "X Defense":        { "keep" : 0 },
            "X Miracle":        { "keep" : 0 },
            "Razz Berry":       { "keep" : 50 },
            "Bluk Berry":       { "keep" : 50 },
            "Nanab Berry":      { "keep" : 0 },
            "Wepar Berry":      { "keep" : 0 },
            "Pinap Berry":      { "keep" : 0 },
            "Special Camera":   { "keep" : 0 }

          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_start_mode": "first",
          "path_file": "configs/path.json"
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": true,
    "walk": 5.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "m",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"keep_best_cp": 2, "keep_best_iv": 1},"logic":  "or"}
    
    
}



config 2:

"libencrypt_location": "./encrypt.so",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball":         { "keep" : 50 },
            "Greatball":        { "keep" : 50 },
            "Ultraball":        { "keep" : 50 },
            "Masterball":       { "keep" : 50 },
            "Potion":           { "keep" : 0 },
            "Super Potion":     { "keep" : 0 },
            "Hyper Potion":     { "keep" : 0 },
            "Max Potion":       { "keep" : 0 },
            "Revive":           { "keep" : 0 },
            "Max Revive":       { "keep" : 0 },
            "Lucky Egg":        { },
            "Incense":          { },
            "Spicy Incense":    { },
            "Cool Incense":     { },
            "Floral Incense":   { },
            "Troy Disk":        { },
            "X Attack":         { "keep" : 0 },
            "X Defense":        { "keep" : 0 },
            "X Miracle":        { "keep" : 0 },
            "Razz Berry":       { "keep" : 50 },
            "Bluk Berry":       { "keep" : 50 },
            "Nanab Berry":      { "keep" : 0 },
            "Wepar Berry":      { "keep" : 0 },
            "Pinap Berry":      { "keep" : 0 },
            "Special Camera":   { "keep" : 0 }

          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": true,
    "walk": 5.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "m",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"keep_best_cp": 2, "keep_best_iv": 1},"logic":  "or"}
    
    
}

**Comment by crusardri** [comment]
OS: Windows 10
Python 2.7
git: 0292c2f (dev)
config:
http://pastebin.com/rrJASkU6

**Comment by fari-99** [comment]
possibly got ip banned?

**Comment by crusardri** [comment]
same on the last master

**Comment by crusardri** [comment]
i can't see any pokestop and pokemon near me in the app, maybe it's a ban IP

**Comment by fari-99** [comment]
yup your ip just got ban. try another hour.

please close this issue.

2016-08-11 18:26 GMT+07:00 crusardri <notifications@github.com>:

**Comment by breinntaguilar** [comment]
How do I run this on mac? Please help. Sorry for the noob question.

**Comment by GitPupper** [comment]
@breinntaguilar It's on the readme. @Miamony You got IP banned. Closing this 👍
