### ISSUE TITLE
[Question] How can I save the output log to a file?

### ISSUE THREAD

**Issue by licklake** [PokemonGoF/PokemonGo-Bot#3599]
Hi,

I would like to analyse the steps of the bot afterwards. So I need a file where every step is saved in.
How can I accomplish that?

**Comment by omeryagmurlu** [comment]
`./run.sh > output.file`

**Comment by licklake** [comment]
nope, isn't working for me

**Comment by kestel** [comment]
./run.sh | tee -a bot.log
It will show log to stdout and also write to bot.log

**Comment by licklake** [comment]
I am running on 64 bit Debian and that method isn't working

**Comment by kestel** [comment]
Any error message?

Also, you can try python ./pokecli.py -cf config/config.json | tee -a bot.log

**Comment by licklake** [comment]
no, that doesn't work for me... no error messages, nothing. It just shows me the output on the terminal and doesn't save anything to the file

**Comment by licklake** [comment]
no, the file is getting created, but theres nothing in it

**Comment by RomainPrevot** [comment]
I use :
`python pokecli.py --config ./configs/config.json > bot.log 2>&1 &`

in an .sh file
