### ISSUE TITLE
Pokemons are invisibles and runnig away?

### ISSUE THREAD

**Issue by IAmYeled** [PokemonGoF/PokemonGo-Bot#36]
First, I thnig it is improtant to to say im not a programmer.
Now, I have used the bot on a level 2 player, I don't know if this related, but it seems that every pokemon run away from me.

Also, in the top left hand corrner it says that I have 8 pokemons but I can see them.

![screenshot_20160721-165657](https://cloud.githubusercontent.com/assets/20579957/17025447/94821ec0-4f64-11e6-8671-bf1422643414.png)

-----------------------------------------------------------------------------------------------------------

![screenshot_20160721-165719](https://cloud.githubusercontent.com/assets/20579957/17025448/94823658-4f64-11e6-8650-4c390d974ce2.png)

Help?

**Comment by harsh1412** [comment]
Seems like a softban for teleporting a long distance.

**Comment by IAmYeled** [comment]
@harsh1412 Thank you for your answer.
