### ISSUE TITLE
[FEATURE REQUEST] Adding IV to Pokemon nickname

### ISSUE THREAD

**Issue by davidspeijer** [PokemonGoF/PokemonGo-Bot#3601]
Would it be an option to set nicknames of Pokemon including IV stats?

**Comment by BriceSD** [comment]
We already got this feature.

**Comment by carlosmuller** [comment]
"nickname_template": "{name:.8s}_{iv_pct}"

**Comment by davidspeijer** [comment]
I just found it :)
