### ISSUE TITLE
Wiki down?

### ISSUE THREAD

**Issue by ibaguio** [PokemonGoF/PokemonGo-Bot#3602]
Hi, is the wiki being updated? It seems to be down. Thanks

**Comment by nivong** [comment]
everything can be found here:

**Comment by simonsmh** [comment]
the master branch should be merged asap.

**Comment by GitPupper** [comment]
@simonsmh We're having problems with a recent update on the dev branch. Please standby as it's fixed. 😊

**Comment by k4n30** [comment]
#3595 #3615
