### ISSUE TITLE
commands

### ISSUE THREAD

**Issue by JaydenHamence** [PokemonGoF/PokemonGo-Bot#3608]
need command for install and runnning dev on mac osx

**Comment by nivong** [comment]
you need to use the template for creating issues and read the doc files

**Comment by JaydenHamence** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot#installation-mac isnt working just need the commands bud

**Comment by nivong** [comment]
us this for now, as soon as the dev bug is fixed it will be merged to master
https://github.com/nivong/PokemonGo-Bot/blob/dbda1717d3d96a764004bf6388f8b84b16ddeb61/docs/installation.md

**Comment by JaydenHamence** [comment]
thanks
