### ISSUE TITLE
Syntax error on program run

### ISSUE THREAD

**Issue by kaise123** [PokemonGoF/PokemonGo-Bot#361]
![ss 2016-07-23 at 04 44 15](https://cloud.githubusercontent.com/assets/1339312/17076570/ded19ef6-50f4-11e6-84d0-c341c0b0e85e.png)
### Expected Behavior

Program Runs

### Actual Behavior

The following error:

Traceback (most recent call last):
  File "pokecli.py", line 43, in <module>
    from pokemongo_bot import PokemonGoBot
  File "/home/kaise123/pokemon/PokemonGo-Bot/pokemongo_bot/__init__.py", line 14, in <module>
    from stepper import Stepper
  File "/home/kaise123/pokemon/PokemonGo-Bot/pokemongo_bot/stepper.py", line 96
    response_dict['responses']['GET_MAP_OBJECTS']['status'] is 1:
                                                                ^
SyntaxError: invalid syntax

### Steps to Reproduce

Run pokecli.py with any options
E.G 'python pokecli.py -h'

### Other Information
OS: Ubuntu 14.04
Git Commit: 89b6ca5636b4a03d579c114e4c921b16045bb07e

**Comment by Akadin** [comment]
I too get this error on OSX

**Comment by Notnuk** [comment]
Same problem.
