### ISSUE TITLE
Teleport and catch don't work

### ISSUE THREAD

**Issue by noncicredo** [PokemonGoF/PokemonGo-Bot#3613]
When i start the bot it detects the ''fake'' location and teleports there to catch the pokemon (well,one of those around my pin), after that, if there are other pokemons around my pin the bot gets into a kind of loop/crash. As u can see below, there were 1 eevee and 2 charmender, the bot first caught eevee (idk why, nvm) then, even if i tried to move the pin a little bit, it completely ignored the charmeders and kept trying to catch the eevee (already caught) so it wento into the loop. Im experiencing this issue since the first day of this map bot, and i tried to git pull every single day, without solving this problem. 

Your help would be VERY appreciated

![schermata 2016-08-11 alle 14 35 20](https://cloud.githubusercontent.com/assets/20777055/17589740/9ee7a61e-5fd6-11e6-8d97-7b40d87dd5c8.png)

im on dave, git pull yesterday night

MY CFG

"tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
	{
        "type": "TransferPokemon"
      },
      {
      	"type": "EvolvePokemon",
        "config": {
          "evolve_all": "Pidgey, Rattata, Caterpie, Weedle, Zubat",
          "evolve_above_cp": 1,
          "evolve_speed": 25,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 40 },
            "Greatball":       { "keep" : 60 },
            "Ultraball":       { "keep" : 70 },
            "Potion":         { "keep" : 30 },
            "Super Potion":   { "keep" : 30 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 30 }
          }
        }
      },
     {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToMapPokemon",
        "config": {
          "address": "http://localhost:5000",
          "max_distance": 500,
          "min_time": 10,
          "min_ball": 10,
          "prioritize_vips": true,
          "snipe": true,
          "snipe_high_prio_only": true,
          "snipe_high_prio_threshold": 400,
          "update_map": true,
          "mode": "priority",
          "catch": {
            "==========Legendaries==========": 0,
            "Aerodactyl": 1000,
            "Snorlax": 1000,
            "Articuno": 1000,
            "Zapdos": 1000,
            "Moltres": 1000,
            "Dratini": 1000,
            "Dragonair": 1000,
            "Dragonite": 1000,
            "Mewtwo": 1000,
            "Mew": 1000,

            "==========Region Locked==========": 0,
            "Farfetch'd": 1000,
            "Kangaskhan": 1000,
            "Mr. Mime": 1000,
            "Tauros": 1000,

            "==========Very Rare==========": 0,
            "Lapras": 900,
            "Electabuzz": 900,
            "Magmar": 900,
            "Ditto": 900,

            "==========Starters==========": 0,
            "Bulbasaur": 400,
            "Ivysaur": 600,
            "Venusaur": 1000,

            "Charmander": 400,
            "Charmeleon": 600,
            "Charizard": 1000,

            "Squirtle": 400,
            "Wartortle": 600,
            "Blastoise": 1000,

            "Pikachu": 600,
            "Raichu": 1000,

            "==========Semi Rare==========": 0,
            "Porygon": 400,
            "Scyther": 400,
            "Jynx": 400,

            "==========Uncommon==========": 0,

            "Omanyte": 40,
            "Omastar": 500,

            "Seel": 300,
            "Dewgong": 500,

            "Grimer": 400,
            "Muk": 500,

            "Shellder": 200,
            "Cloyster": 500,

            "Gastly": 400,
            "Haunter": 500,
            "Gengar": 1000,

            "Onix": 600,

            "Drowzee": 600,

            "Hypno": 600,

            "Vulpix": 600,
            "Ninetales": 600,

            "Growlithe": 600,
            "Arcanine": 700,

            "Mankey": 60,
            "Primeape": 600,

            "Clefairy": 500,
            "Clefable": 500,

            "Jigglypuff": 500,
            "Wigglytuff": 500,

            "Diglett": 500,
            "Dugtrio": 500,

            "Meowth": 500,
            "Persian": 500,

            "Geodude": 500,
            "Graveler": 500,
            "Golem": 800,

            "Eevee": 500,
            "Vaporeon": 800,
            "Jolteon": 800,
            "Flareon": 800,

            "Kabuto": 500,
            "Kabutops": 500,

            "Magikarp": 150,
            "Gyarados": 800,

            "Ponyta": 500,
            "Rapidash": 500,

            "Slowpoke": 200,
            "Slowbro": 500,

            "Magnemite": 50,
            "Magneton": 500,

            "Voltorb": 500,
            "Electrode": 500,

            "Exeggcute": 500,
            "Exeggcutor": 500,

            "Cubone": 500,
            "Marowak": 800,

            "Hitmonlee": 400,

            "Hitmonchan": 400,

            "Lickitung": 500,

            "Koffing": 500,
            "Weezing": 500,

            "Rhyhorn": 500,
            "Rhydon": 500,

            "Chansey": 800,

            "Horsea": 200,
            "Seadra": 600,

            "Goldeen": 150,
            "Seaking": 500,

            "Staryu": 200,
            "Starmie": 800,

            "==========T1 Evolvers==========": 0,
            
            "Butterfree": 500,

            "Beedrill": 500,

            "==========T2 Evolvers==========": 0,
            "Nidoran F": 400,
            "Nidorina": 400,
            "Nidoqueen": 400,

            "Nidoran M": 400,
            "Nidorino": 400,
            "Nidoking": 400,

            "Oddish": 100,
            "Gloom": 400,
            "Vileplume": 600,

            "Poliwag": 200,
            "Poliwhirl": 400,
            "Poliwrath": 800,

            "Abra": 400,
            "Kadabra": 600,
            "Alakazam": 800,

            "Machop": 400,
            "Machoke": 400,
            "Machamp": 800,

            "Bellsprout": 400,
            "Weepinbell": 400,
            "Victreebel": 800

          }
        }
      },
      {
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_file": "configs/path.json"
        }
     }
    ],
    
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 12,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "ALL",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"}
        },
....
....

LOG (in this case it tried to teleport to the charmender, but failed and showd its disappear time; it did the same thing with eevee after i logged out and re logged in); i've also tried to delete cache and reboot everything. Looks like it couldnt teleport anymore, it just WALKED to the charmender (that was very far ofc)

[14:29:53] Updated PokemonGo-Map to 43.76956, 11.255814
[14:29:54] Teleporting to Eevee. (250.75km)
[14:29:54] Encountered Pokemon: Eevee
[14:29:57] Teleporting back to previous location (43.76956, 11.255814)
[14:29:59] A wild Eevee appeared! [CP 562] [Potential 0.89] [A/D/S 10/15/15]
[14:30:02] This is a VIP pokemon. Catch!!!
[14:30:02] Catch rate of 27.48 with Pokeball is low. Throwing Razz Berry (have 31)
[14:30:02] Threw a Razz Berry! Catch rate with Pokeball is now: 27.48
[14:30:02] Used Ultraball, with chance 71.11 (15 left)
[14:30:03] Captured Eevee! [CP 562] [Potential 0.89] [10/15/15] [+210 exp]
[14:30:03] You now have 177 Eevee candy!
[14:30:08] Moving towards Eevee, 250.75km, left (7 minutes, 55 seconds)
[14:30:08] {'distance_unit': '', 'distance': '', 'current_position': (43.76964367275203, 11.255731942699622), 'last_position': (43.76956, 11.255814)}
[14:30:09] Next egg incubates in 5.00 km
[14:30:10] Moving towards Charmander, 250.76km, left (8 minutes, 35 seconds)
[14:30:10] {'distance_unit': '', 'distance': '', 'current_position': (43.76973920587733, 11.255643338562258), 'last_position': (43.76964367275203, 11.255731942699622)}
[14:30:12] Moving towards Charmander, 250.75km, left (8 minutes, 33 seconds)
[14:30:12] {'distance_unit': '', 'distance': '', 'current_position': (43.76981438460524, 11.255528752687907), 'last_position': (43.76973920587733, 11.255643338562258)}
[14:30:14] Moving towards Charmander, 250.74km, left (8 minutes, 31 seconds)
[14:30:14] {'distance_unit': '', 'distance': '', 'current_position': (43.76991495017981, 11.255438939091455), 'last_position': (43.76981438460524, 11.255528752687907)}

**Comment by cliffalbert** [comment]
Looks like it checks as following (pseudo code):

$pokemon_prio > $snipe_threshold_prio then snipe

should probably read 

$pokemon_prio >= $snipe_threshold_prio then snipe

**Comment by noncicredo** [comment]
yeah.. i guess im gonna keep only one pokemon each time i wanna snipe
-i load the map
-i pin the position
-i look for a pokemong i want to snipe
-i change my cfg putting that pokemon on the list (only it)
-i snipe

i'll let u know if it works ;)

**Comment by k4n30** [comment]
There is no issue here, you have your units set to km, and your max_distance set to 500 (500km), you also have your snipe_high_prio_threshold set to 400, so anything above 400 will be sniped, and anything under will be walked to. The bot is working as configured

If you are still require help join the slack support server @ https://pokemongo-bot.herokuapp.com/ and join the #help channel

**Comment by noncicredo** [comment]
@k4n30 just a question: what ''max distance'' mean in this case?

thank you

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md#options
