### ISSUE TITLE
Where is your Wiki?

### ISSUE THREAD

**Issue by Loganxu** [PokemonGoF/PokemonGo-Bot#3615]
What's wrong with the wiki? Can't find it today

**Comment by rained23** [comment]
its inside docs folder but I hope they return back the wiki page ...

**Comment by k4n30** [comment]
Depending opn what version you're running
https://github.com/PokemonGoF/PokemonGo-Bot/tree/master/docs
or
https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev/docs

**Comment by k4n30** [comment]
#3602 #3595
