### ISSUE TITLE
Map view for items should include max quantity from config.json

### ISSUE THREAD

**Issue by tdk337** [PokemonGoF/PokemonGo-Bot#3616]
# Feature Request:
The map view on Pokemongo-Bot should have not only items quantity listed but also what their configured max is. This will make it easier to rebalance if your inventory is full.

**Comment by k4n30** [comment]
Please explain further. The bot does the auto item dropping for you

**Comment by tdk337** [comment]
You are absolutely correct. The problem with the auto item dropping is that there could be potential use cases where you want a backup plan. Let's take Pokeballs for example.

Let's say you only have room in your inventory for 100 Pokeballs. Ideally it will be 100 of your best available type. We'll use Ultra Balls as an example here.
000 Poke Ball
000 Great Ball
100 Ultra Ball

Your current inventory looks like this with max set after /.
010/010 Poke Ball
040/100 Great Ball
050/100 Ultra Ball

Why is the above limits set way above my available inventory totals of 100? Answer: Because I don't want it to drop Great Balls when I am still so far from obtain all Ultra Balls. The requested feature request will just make it easier for me to readjust when I hit the no more room in inventory error. Better yet the script will automatically get 100 of the best available balls for you.

**Comment by k4n30** [comment]
So is this Feature request for the bot or the webview - https://github.com/PokemonGoF/PokemonGo-Web
