### ISSUE TITLE
ChunkedEncodingError

### ISSUE THREAD

**Issue by beanstalkk** [PokemonGoF/PokemonGo-Bot#3617]
Was running yesterday. Updated to the last code and requirements. Ran the bot, encountered this. It was working occasionally afterwards.

Traceback (most recent call last):
  File "pokecli.py", line 501, in <module>
    main()
  File "pokecli.py", line 132, in main
    raise e
requests.exceptions.ChunkedEncodingError: ("Connection broken: error(10054, 'An existing connection was forcibly closed by the remote host')", error(10054, 'An existing connection was forcibly closed by the remote host'))

**Comment by k4n30** [comment]
The connection has been closed by the server, this is either an issue with your connection or niantics server shut the connection. Are you using anything else that creates connections? Mapping products, other bots?  When you say it was working occasionally, please define that better i.e every second time, crashed every 3 hours, etc

**Comment by beanstalkk** [comment]
about once an hour so far. No not running anything else :)

**Comment by k4n30** [comment]
I don't think we are going to be able to help you as it seems connection related, not an issue with the bot. Will leave the issue open to see if anyone else has the same issue, otherwise I'd suggest doing some connection testing

**Comment by GitPupper** [comment]
This is a connection issue. Try using 
[PokeBot.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/414312/PokeBot.zip)
It restarts your bot after 5 seconds if it crashes.
