### ISSUE TITLE
[new feature] using espeak to say log

### ISSUE THREAD

**Issue by eschultze** [PokemonGoF/PokemonGo-Bot#3620]
I have been using the bot like this

`python pokecli.py -cf configs/config.json | tee LOG`

On another terminal I run

`tail -f LOG | while read line ; do echo $line | grep -oE ".*A wild.*appeared.*" | cut -d' ' -f2-9| espeak ; done`

Every time "A wild $POKEMON appears" it says it using `espeak`

Does anyone would like to integrate this with the bot? maybe using another language... I can help if I'm able to, but my python skills are very bad :(

**Comment by Dracon23** [comment]
Not too sure how this would be handled on a headless machine, but this surely is an interesting approach to alerting the user ;F

**Comment by vanishing** [comment]
Don't think this is really necessary, you can whip up a quick shell script to do this:

```
#!/bin/bash
filename="$1"
message="$2"
tail -f $filename | egrep --line-buffered $message | while read line 
do
	espeak $line
done 
```
Run it with:
./script <logfile path> <message to look for>

**Comment by cyberhck** [comment]
I don't think this is really required, we can just use notify-send in linux distros to notify about new pokemons but saying out loud, might not be required at all :)

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by eschultze** [comment]
@k4n30 OK, I'm closing it and moved to feathub ;)

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by k4n30** [comment]
@eschultze It doesn't look like anyone is willing to help out. How would you like to proceed? Do you want to give it a go yourself?

**Comment by jrjhealey** [comment]
It looks to me like the shell scripting for this is A) easy, and B) done!

I'd say this can be closed, and if the functionality is still really desired, I suggest you offer up a PR and the devs can decide to include it or not.

**Comment by eschultze** [comment]
Sorry for the delay. I was going to close it as well.

Thanks for the reviews and comments.
