### ISSUE TITLE
Crash after running a while

### ISSUE THREAD

**Issue by pranavperfect** [PokemonGoF/PokemonGo-Bot#3624]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. Are you running `master`? We work on the `dev` branch and then add that functionality to `master`. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.

### Expected Behavior

run
### Actual Behavior
crash

### Your config.json (remove your credentials and any other private info)
```
your config here
```

### Steps to Reproduce
let run for a while

### Other Information
OS:
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

Error displayed:
```
Traceback (most recent call last):
  File "pokecli.py", line 521, in <module>
    main()
  File "pokecli.py", line 95, in main
    bot.tick()
  File "/mnt/c/Users/prana/Desktop/Bot/Updated/pokemongo_bot/__init__.py", line 453, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/mnt/c/Users/prana/Desktop/Bot/Updated/pokemongo_bot/cell_workers/recycle_items.py", line 41, in work
    item_count_dict = self.bot.item_inventory_count('all')
  File "/mnt/c/Users/prana/Desktop/Bot/Updated/pokemongo_bot/__init__.py", line 815, in item_inventory_count
    'GET_INVENTORY']['inventory_delta']['inventory_items']
TypeError: string indices must be integers, not unicode
```

**Comment by pranavperfect** [comment]
Also, not catching any pokemon. Just walking to pokestops. And not because of config issues. Have used the same config for past 3 days and has caught over 200 pokemon earlier.

**Comment by jrjhealey** [comment]
You need to give us way, way more information than this.

Are you on dev or master? What OS? What commit? Please edit the OP or we'll just shut it.
