### ISSUE TITLE
Noob at GitHub

### ISSUE THREAD

**Issue by joaodragao** [PokemonGoF/PokemonGo-Bot#3625]
Does anyone know how to sync with the current main repository? I forked the repository before and I made a PR. While it is in review, I can't pull another PR.

**Comment by nivong** [comment]
this is something you should google it's called pull requesting and this is not an issue with the bot...

**Comment by joaodragao** [comment]
I know. I just need a help from here.

**Comment by DiegoRBaquero** [comment]
Use branches :)

**Comment by nivong** [comment]
Well I'm not able to help since it has nothing to do with the bot...

**Comment by joaodragao** [comment]
I did it now with GitHub Desktop. I'm poor with `git` command line. But I'm good with Python 😉 kiddin!!
