### ISSUE TITLE
Bot cannot find module _base_dir 

### ISSUE THREAD

**Issue by theolive** [PokemonGoF/PokemonGo-Bot#3631]
After implementing edited code from #3578 , I'm getting this error in run.sh:

> Traceback (most recent call last):
  File "pokecli.py", line 41, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "C:\Program Files\Git\PokemonGo-Bot\pokemongo_bot\__init__.py", line 31, in <module>
    from pokemongo_bot.base_dir import _base_dir
ImportError: No module named base_dir

**Comment by joaodragao** [comment]
Does the file `base_dir.py` in your `pokemon_bot` directory? If not, download and drop it there.
