### ISSUE TITLE
Distance unit txt 

### ISSUE THREAD

**Issue by xLemonice** [PokemonGoF/PokemonGo-Bot#3636]
is there a way to remove this text?

![image](http://image.prntscr.com/image/db50f98d3cf845c18605d4e1f7c3ff3b.jpeg)

its spamming all the way..

**Comment by orchid666** [comment]
I think its just for the dev version, probably some test. Use the master or wait for new version :)

**Comment by RedViper9** [comment]
Devs are working on it. #3532
