### ISSUE TITLE
Infinite loop when pokemon bag is full

### ISSUE THREAD

**Issue by Setsu-BHMT** [PokemonGoF/PokemonGo-Bot#3641]
### Expected Behavior
Bot should ignore all pokemon when pokemon bag is full

### Actual Behavior
Bot gets stuck tracking down lure pokemon it can't catch.

### Your config.json (remove your credentials and any other private info)
Using a minimally modified example.json

### Steps to Reproduce
Fill pokemon bag completely, then run bot.
Eventually it will encounter lure pokemon and get stuck.

### Version
Latest Dev branch pull
Python 2.7.12 on Ubuntu 16.04

**Comment by Ph4i1ur3** [comment]
What would you propose the bot do? It sounds like you should adjust your config to release more Pokemon.

**Comment by Setsu-BHMT** [comment]
@Ph4i1ur3 The bot should just walk and spin forts is a more reasonable thing to do.

Ideally I'd like a config setting for when the pokemon bag is full to do evolving or more aggressive releasing

**Comment by jrjhealey** [comment]
I have to say some kind of sensible handling of this would be appealing. Trying to finesse the config file to maintain a steady level of pokemon release/retain can be tricky, especially if you're new to the bot.

**Comment by fari-99** [comment]
hmm, in old master bot, there is a mode for farm, catch and all. but in dev, it changed into a serial of a task we see today. what i can recommend now, just delete the catch pokemon task.

all = catch and farm (spin fort and catch pokemon)
catch = only catch pokemon 
farm = only spin fort.

**Comment by Setsu-BHMT** [comment]
@fari-99 True, but my point is the bot shouldn't need reconfiguration in order to deal with this issue.

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by mjmadsen** [comment]
This should be solved.
