### ISSUE TITLE
[FeatureRequest] Use Incense Config Option

### ISSUE THREAD

**Issue by imvikash00** [PokemonGoF/PokemonGo-Bot#3642]
Is there a config to tell the bot to use Incense? I couldn't find it in the configuration page

**Comment by DiegoRBaquero** [comment]
There isn't. This could be a feature request.

**Comment by Baconnaise** [comment]
Would be a great addition IMO.

**Comment by joaodragao** [comment]
I think it's useless because bot can easily catch a lot of Pokemons. Incense and Lure should be used when you somehow play the game directly. It's not fun for bot to play lol

**Comment by adrianoresende** [comment]
I think it works well with this new method https://github.com/PokemonGoF/PokemonGo-Bot/issues/3588 or new code to instant action (go to point A, use item, discard item, etc).

**Comment by k4n30** [comment]
#3376
