### ISSUE TITLE
Overview of the player

### ISSUE THREAD

**Issue by pensiero** [PokemonGoF/PokemonGo-Bot#3643]
Is there a tool that gives me an overview of my player without actually running the bot? Like the exact list of the Pokemon/items that I have in my inventory?

**Comment by RedViper9** [comment]
[This](https://www.reddit.com/r/pokemongodev/comments/4vq84x/blossoms_pokemon_go_manager_xpost_rpokemongoiv/?sort=new) might be what you're looking for. If not, feel free to ask around on our slack discussion board.
