### ISSUE TITLE
never_capture not working

### ISSUE THREAD

**Issue by Sechgulo** [PokemonGoF/PokemonGo-Bot#3644]
## Expected Behavior
Pokemons set to never_capture to not be captured

### Actual Behavior
Pokemons still get caught with rule set to true

```
[22:02:35] Something rustles nearby!
[22:02:36] A wild Gastly appeared! [CP 92] [Potential 0.44] [A/D/S 15/0/5]
[22:02:38] Used Pokeball, with chance 55.12 (49 left)
[22:02:39] Captured Gastly! [CP 92] [Potential 0.44] [15/0/5] [+210 exp]
[22:02:39] You now have 150 Gastly candy!
[22:02:44] Keeping best 1 Gastly, based on iv
[22:02:45] Exchanged Gastly [CP 92] [IV 0.44] for candy.
[22:02:48] Something rustles nearby!
[22:02:48] Something rustles nearby!
[22:02:48] A wild Drowzee appeared! [CP 376] [Potential 0.4] [A/D/S 8/4/6]
[22:02:51] Used Pokeball, with chance 40.01 (48 left)
[22:02:52] Captured Drowzee! [CP 376] [Potential 0.4] [8/4/6] [+210 exp]

```
### Your config.json (remove your credentials and any other private info)
```
"catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0.1, "logic": "or"},
      "Pidgey": {"never_capture": true},
      "Caterpie": {"never_capture": true},
      "Metapod": {"never_capture": true},
      "Weedle": {"never_capture": true},
      "Kakuna": {"never_capture": true},
      "Pidgeotto": {"never_capture": true},
      "Rattata": {"never_capture": true},
      "Raticate": {"never_capture": true},
      "Spearow": {"never_capture": true},
      "Ekans": {"never_capture": true},
      "Zubat": {"never_capture": true},
      "Oddish": {"never_capture": true},
      "Paras": {"never_capture": true},
      "Venonat": {"never_capture": true},
      "Mewowth": {"never_capture": true},
      "Psyduck": {"never_capture": true},
      "Tentacool": {"never_capture": true},
      "Magnemite": {"never_capture": true},
      "Magneton": {"never_capture": true},
      "Doduo": {"never_capture": true},
      "Gastly": {"never_capture": true},
      "Drowzee": {"never_capture": true},
      "Krabby": {"never_capture": true},
      "Voltorb": {"never_capture": true},
      "Horsea": {"never_capture": true},
      "Goldeen": {"never_capture": true},
      "Staryu": {"never_capture": true}
    },
```

### Steps to Reproduce
Use config above and start bot

### Other Information
OS:
1bfabca76050742eefdbca79d9ba1279737c6219
Python Version: Python 2.7.12

**Comment by joaodragao** [comment]
Use `never_catch`. `never_capture` is deprecated.

**Comment by Sechgulo** [comment]
Ok so there is no way to ignore catching a specific pokemon? Using rules like cp min 1000 and iv min .9 wont do, it just gets stuck and dont ignor pokemons after first look

**Comment by leadboots5** [comment]
@Sechgulo He is saying that you need to change:
"Pidgey": {"never_capture": true},
to
"Pidgey": {"never_catch": true},

You just have the wrong thing written.

**Comment by Sechgulo** [comment]
Hmm same result as with high criteria catch rules, just "Something rustles nearby!" for 5 minutes

**Comment by Sechgulo** [comment]
Am I missing something?

**Comment by leadboots5** [comment]
I assume something rustles nearby because you're not catching it, because you told your config not to. Does that not seem accurate?

**Comment by Sechgulo** [comment]
It does. But what doesn't is that it seems to get stuck, 0.01k takes minutes to walk which it normally doesn't (if you look at the snippets from my log). That's not what's wanted or?

**Comment by umbreon222** [comment]
Seems like bot makes the decision to not capture way to late in the call stack. This results in a lot of wasted operations which accounts for the wasted time in your logs.

**Comment by k4n30** [comment]
@Sechgulo is this still an issue?
