### ISSUE TITLE
SystemD Service

### ISSUE THREAD

**Issue by Trozz** [PokemonGoF/PokemonGo-Bot#3645]
Not an issue, I want to know if people want this committed to the repo, it does not stop the process correctly however it does work.

I use the run script as I have updated the script to include a `git pull` to ensure that I am using the latest of the dev branch.

### run.sh
```
[Unit]
Description=Pokemon Bot
After=network.target

[Service]
Type=Forking
WorkingDirectory=%PATH-TO-PokemonGo-Bot%
ExecStart=/bin/bash ./run.sh
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

### Python
```
[Unit]
Description=Pokemon Bot
After=network.target

[Service]
Type=Forking
WorkingDirectory=%PATH-TO-PokemonGo-Bot%
ExecStart=/usr/bin/python pokecli.py -cf ./configs/config.json
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

**Comment by k4n30** [comment]
It's been awhile since I tinkered with systemd but isn't there an option to kill processes on crash? Either that or on start/restart kill any python processes (dirty but does the job). Either way I would create a pull request and have your enhancement added and any niggling issues dealt with there

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by k4n30** [comment]
@Trozz Are you still keen to create a PR for this?

**Comment by mjmadsen** [comment]
@Trozz @k4n30 We *kind* of have this (at least a notice). Can we close?

**Comment by k4n30** [comment]
@mjmadsen This isn't really implemented, but I think there are sufficient scripts to probably achieve what it's functionally trying to achieve. Happy to close as OP hasn't responded
