### ISSUE TITLE
Pokemon keep fleeing away

### ISSUE THREAD

**Issue by MrZanja** [PokemonGoF/PokemonGo-Bot#3647]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. Are you running `master`? We work on the `dev` branch and then add that functionality to `master`. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.

### Expected Behavior
Pokemons to stay in their balls.

### Actual Behavior
All pokemon flee, only using of the bot. 

### Your config.json (remove your credentials and any other private info)
```
your config here
```

### Other Information
OS:
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by MrZanja** [comment]
Some say it is a softban, but it happens everytime. Even when I wait 12 hours in between, without changing location. What can I do?

**Comment by jrjhealey** [comment]
Please edit your OP with your config file and the commit of the bot you are running. We can't help without more information.

**Comment by k4n30** [comment]
Discussion in #3700
