### ISSUE TITLE
Web UI - click on a point and say "go here"

### ISSUE THREAD

**Issue by yyoshii** [PokemonGoF/PokemonGo-Bot#3650]
### Expected Behavior
New Feature request:
At the Web UI, click on a destination and say "go to here".
After that the character go from the actual position to the new one.
If a pokemon spawn, than the character collect the pokemon and continuous afterward the walk to the new position. When the character reach the new destination, the character start the "normal" behave defined in the config.js file, 

Maybe it can be implemented by adding the new destination to path.json and then reload the configuration? (Not sure how this work with the path.json)

With this feature it is possible to start at City "A", then let the bot farm there. 
After a while you can click on City "B", say "go to here" and let the bot "farm" at City "B" and so on...

### Actual Behavior
Not implemented

**Comment by seratkurtulus** [comment]
Or you can just start the bot with the new coordinates :) As far as i know it is not possible to write to an arbitrary location on the disk with javascript. You would probably need a server to catch those requests and execute them which is not a trivial task.

**Comment by yyoshii** [comment]
i agree, but clicking on the Map is more comfortable than stop the bot, search for the coordinates, add it to the file and then start the bot again.

What is if i change the config file and restart the bot?
Is the character going to the new coordinates or is it a jump directly to the new once?

If it is a jump, than it does not react like a human ;-)

**Comment by seratkurtulus** [comment]
yea also letting bot capture %100 iv pokemons powered up to max level from all around the world would be very comfortable but technology is not there yet :) btw walking between cities does not sound like a good idea, bot probably would be walking through rural areas without pokestops or pokemons during the journey which is not efficient at all.
for your question, yes bot directly jumps to the new location. If you want bot to walk between two cities you can set a path between them and use follow path configuration.

**Comment by yyoshii** [comment]
The "not efficient at all" is a good aspect.
My idea behind this request was to "simulate" the human behave.

If this is a bad idea, this "issue" can be closed ;-)

**Comment by RedViper9** [comment]
You can do this to some extent if you use the MoveToMapPokemon option with `"update_map": false,`. Your bot's location won't get pushed to the map and you can drop the pin wherever you want the bot to go. It will still nab any pokemon on the way, but will go to the general area of your pin.

**Comment by adrianoresende** [comment]
I think it need new code to instant action (go to point A, use item, discard item, etc).

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by k4n30** [comment]
@yyoshii Are you still after this? If so I'd suggest making the feature request on the actual [webui repo](https://github.com/OpenPoGo/OpenPoGoWeb/tree/6ba5609c6151507b5b832a74e471b6b7b1a182c9) and not here as this is not a bot request (although it could be), but the webui would need to implement it first

**Comment by mjmadsen** [comment]
I'm going to agree with @k4n30
