### ISSUE TITLE
Error: Can not decode value starting with character u

### ISSUE THREAD

**Issue by jaredthegamer** [PokemonGoF/PokemonGo-Bot#3651]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. Are you running `master`? We work on the `dev` branch and then add that functionality to `master`. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.

### Your config.json (remove your credentials and any other private info)
```
your config here
```
no need 
### Steps to Reproduce
./configs/config.json:3:16: Error: Can not decode value starting with character u'\u201c'
   |  At line 3, column 16, offset 48
./configs/config.json:3:41: Info: Recovering parsing after character u','
   |  At line 3, column 41, offset 73
./configs/config.json:4:16: Error: Can not decode value starting with character u'\u201c'
   |  At line 4, column 16, offset 91
./configs/config.json:4:26: Info: Recovering parsing after character u','
   |  At line 4, column 26, offset 101
./configs/config.json:7:27: Error: Can not decode value starting with character u'\u201c'
   |  At line 7, column 27, offset 226
./configs/config.json:7:29: Info: Recovering parsing after character u','
   |  At line 7, column 29, offset 228
./configs/config.json: has errors

### Other Information
do not understand this python error

OS: mac
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by Gobberwart** [comment]
You've said there's no need to provide your config.json, but that's where the error is. Character U201C is a "smart quote", specifically this one “. Note how that's different to a "normal" quote (it's slanted, not straight)? Look through your config.json and change any of these quotes and it should be fine.
