### ISSUE TITLE
Pokemon Inventory(Non-issue)

### ISSUE THREAD

**Issue by Tohrment** [PokemonGoF/PokemonGo-Bot#3655]
I have been trying to find where the pokemon data is stored locally for an account so that I can export it and parse it though powershell to get the data I want. The web ui isn't my cup of tea and is limited in what I can do with it.(like take it with me) I essentially want the data at my fingertips when I am actually playing the account.

**Comment by seratkurtulus** [comment]
it is stored in the web folder as inventory-username.json
