### ISSUE TITLE
evolve_all: list not evolve any

### ISSUE THREAD

**Issue by ntanto** [PokemonGoF/PokemonGo-Bot#3657]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.

yes, its valid

2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.

yes, there aren't any

3. Are you running `master`? We work on the `dev` branch and then add that functionality to `master`. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.

no, im running dev

### Expected Behavior
evolve when have enough candy

### Actual Behavior
[05:06:03] Captured Zubat! [CP 254] [Potential 0.58] [6/11/9] [+210 exp]
[05:06:03] You now have 79 Zubat candy!
[05:06:08] {'distance_unit': '', 'distance': '', 'current_position': (-7.234780634897764, 112.79478096439313), 'last_position': (-7.234669874052597, 112.79472549956063)}
[05:06:13] Exchanged Zubat [CP 254] [IV 0.58] for candy.

### Your config.json (remove your credentials and any other private info)
{
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "Caterpie,Weedle,Pidgey,Rattata,Spearow,Zubat",
            "first_evolve_by": "cp",
            "evolve_above_cp": 1,
            "evolve_above_iv": 0.1,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },

### Other Information
OS: Windows 10
Git Commit: 543226e81b864d0fd714337e7cce1da8ac0a0005
Python Version: 2.7.12

**Comment by keugnu** [comment]
Already brought this up. #3563

**Comment by seratkurtulus** [comment]
you should be keeping at least one pokemon to prevent this. 
"Zubat": {"keep_best_cp": 1} might solve your issue.
Also you can use "evolve_captured" config right now but it might be removed later.

**Comment by ntanto** [comment]
evolve_captured already removed
still trying moving
{
"type": "TransferPokemon"
},

below evolve task, will update soon after see the result
