### ISSUE TITLE
Update Issue Template

### ISSUE THREAD

**Issue by k4n30** [PokemonGoF/PokemonGo-Bot#3665]
Using this for a list of improvements for the issue template to help troubleshoot issues easier.

- Add branch type
- Potentially use pastebin for config / logs to reduce spam in issues
- Use of metadata tags for enhancements / suggestions / new features etc
- Location (if connection issues)

Anything else anyone can think of before submitting a PR?

@PokemonGoF/pokemongo-bot-community-support

**Comment by jrjhealey** [comment]
I think the template has gotten much better so I can't think of anything else to add.

What I have been thinking though (on a kind of related point) is perhaps we should take a zero tolerance policy toward people who fail to fill out the form properly? I think those issues should be closed outright and the OP made to edit/repost with the issue template properly filled out.
