### ISSUE TITLE
How to use the rename template

### ISSUE THREAD

**Issue by spoxus** [PokemonGoF/PokemonGo-Bot#3668]
I'm sorry I could not get it working.
Traceback (most recent call last):
  File "pokecli.py", line 559, in <module>
    main()
  File "pokecli.py", line 83, in main
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "E:\downloads\PokemonGo-Bot\pokemongo_bot\tree_config_builder.py", line 63, in build
    instance = worker(self.bot, task_config)
  File "E:\downloads\PokemonGo-Bot\pokemongo_bot\base_task.py", line 12, in __init__
    self.enabled = config.get('enabled', True)
AttributeError: 'unicode' object has no attribute 'get'

### Your config.json (remove your credentials and any other private info)
```
	"tasks": [
		{ "type": "HandleSoftBan" },
		{ "type": "CollectLevelUpReward" },
		{ "type": "IncubateEggs", "config": { "longer_eggs_first": true} },
		{ "type": "NicknamePokemon",  
		{ "type": "NicknamePokemon",  
			"config": "{iv_pct}"
		}, 
	}, 
```

**Comment by chrisjan99** [comment]
{
        "type": "NicknamePokemon",
        "config": {
            "nickname_template" : "{iv_pct}_{cp}_{iv_ads}"
        }
      },

**Comment by spoxus** [comment]
Thank you @chrisjan99
