### ISSUE TITLE
Web UI not showing position updates

### ISSUE THREAD

**Issue by surewhynotmon** [PokemonGoF/PokemonGo-Bot#3669]
### Expected Behavior
Seeing updated position on the web ui as bot runs

### Actual Behavior
Nothing moves

Web browser reported many errors with
socket.io-1.4.5.js:1 GET http://localhost:8110/socket.io/?EIO=3&transport=polling&t=LPyOSX0 404 (File not found)

Is it something to do with greenlet and socket.io not working? (It was working yesterday though)

###userdata.js
var userInfo = {
	users: ["USER-ID@EMAIL.COM"],
	userZoom: true,
	zoom: 16,
	userFollow: true,
	gMapsAPIKey: "KEY",
	botPath: true,
	actionsEnabled: false
};
### Steps to Reproduce
I am on the dev branch.

Run bot and open the web ui

I did find some error around socket.io
127.0.0.1 - - [11/Aug/2016 21:27:17] code 404, message File not found
127.0.0.1 - - [11/Aug/2016 21:27:17] "GET /socket.io/?EIO=3&transport=polling&t=LPyN4Vz HTTP/1.1" 404 -

I already tried `pip install -r requirements.txt` and don't see anything on dev that can break this...
It was working on commit 0f2bddd26675c5232b2e9f4e83dc6525c41a842d but broken on 138b66413e45efcef1ae015388b80a2725e7a7d8

### Other Information
OS: Ubuntu 
Git Commit: 138b66413e45efcef1ae015388b80a2725e7a7d8
Python Version: 2.7.11

**Comment by keugnu** [comment]
#3622

**Comment by k4n30** [comment]
#3546
