### ISSUE TITLE
Encountered pokemon but no catch?

### ISSUE THREAD

**Issue by jnguyen32** [PokemonGoF/PokemonGo-Bot#3674]
Here is what the bot shows, as you can see, there is an Aerodactyl here (I've been trying for 10 minutes). But it never attempts to catch it, it just keeps moving on:

2016-08-11 19:34:00,595 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Aerodactyl, 0.00km, left (1 minute, 27 seconds)
2016-08-11 19:34:00,727 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_encounter] Encountered Pokemon: Aerodactyl
2016-08-11 19:34:00,878 [MoveToFort] [INFO] [moving_to_lured_fort] Moving towards pokestop Fontaines - 0.04km (attraction of lure 0.07km)

Here is the config:

{
    "auth_service": "",
    "username": "",
    "password": "",
    "location": "",
    "gmapkey": "",
    "libencrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": false
        }
      },
    {
      "type": "CatchVisiblePokemon"
    },
    {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "Charmander,Charmeleon,Wartortle,Haunter,Ivysaur,Bulbasaur,Squirtle,Pikachu,Rhyhorn,Omanyte,Shellder,Cubone,Staryu,Horsea",
            "first_evolve_by": "iv",            
            "evolve_above_iv": 0.9,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": true,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "RecycleItems",
        "config": {
            "item_filter": {
              "Pokeball":       { "keep" : 50 },
              "Greatball":      { "keep" : 100 },
              "Ultraball":      { "keep" : 110 },
              "Potion":         { "keep" : 0 },
              "Super Potion":   { "keep" : 0 },
              "Hyper Potion":   { "keep" : 0 },
              "Max Potion":     { "keep" : 20 },
              "Revive":         { "keep" : 15 },
              "Razz Berry":     { "keep" : 100 }
            }
        }
      },
      {
        "type": "SpinFort",
        "config": {
            "ignore_item_count": true
        }
      },
     {
        "type": "MoveToMapPokemon",
        "config": {
          "address": "http://localhost:5000",
          "max_distance": 5000,
          "min_time": 0,
          "prioritize_vips": true,
          "snipe": false,
          "update_map": true,
          "mode": "priority",
          "catch": {
            "Aerodactyl": 2000,
            "Snorlax": 1000,
            "Articuno": 1000,
            "Lapras": 1000,
            "Zapdos": 1000,
            "Moltres": 1000,
            "Dratini": 1000,
            "Dragonair": 1000,
            "Dragonite": 1000,
            "Gyarados": 1000,
            "Mewtwo": 1000,
            "Mew": 1000,
            "Ditto": 1000,
            "Farfetch'd": 1000,
            "Kangaskhan": 1000,
            "Mr. Mime": 1000,
            "Tauros": 1000,
            "Poliwrath": 900,
            "Nidoqueen": 900,
            "Nidoking": 900,
            "Gastly": 900,
            "Golem": 900,
            "Golduck": 900,
            "Rhydon": 900,
            "Vileplume": 900,
            "Venusaur": 900,
            "Charizard": 900,
            "Blastoise": 900,
            "Raichu": 900,
            "Electabuzz": 900,
            "Magmar": 900,            
            "Vaporeon": 800,
            "Jolteon": 800,
            "Flareon": 800,
            "Arcanine": 800,
            "Muk": 700,
            "Clefable": 700,
            "Wigglytuff": 700,
            "Slowbro": 700,
            "Exeggcutor": 700,
            "Ivysaur": 600,
            "Charmeleon": 600,
            "Wartortle": 600,
            "Bulbasaur": 400,
            "Charmander": 400,
            "Squirtle": 400,
            "// Magikarp": 400
          }
        }
      },
      {
        "type": "MoveToFort",
        "config": {
            "ignore_item_count": true
        }
      }
    ],
    "other tasks": [
    {
      "type": "CatchLuredPokemon"
    },
        {
          "type": "EvolveAll",
          "config": {
            "evolve_all": "Pidgey,Caterpie,Bulbasaur,Metapod,Weedle,Kakuna,Rattata,Spearow,Ekans,Pikachu,Sandshrew,Zubat,Diglett,Meowth,Mankey,Tentacool,Magnemite,Doduo",
            "evolve_cp_min": 0,
            "evolve_speed": 20,
            "use_lucky_egg": false
          }
        },
          {
            "type": "FollowSpiral",
                    "config": {
                      "diameter": 4,
                      "step_size": 70
                    }
          }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 17.81,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 0.4,
    "catch_randomize_spin_factor": 0.2,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0.0, "logic": "or" }
    },
    "release": {
        "////////////////////////////////////////////////////////////////////////": {},
        "// Top Priority": {},
        "////////////////////////////////////////////////////////////////////////": {},
        "any": {"catch_above_cp": 0, "release_below_iv": 0.9, "logic": "or" },
        "Moltres": {"keep_best_cp": 3, "keep_best_iv": 3},
        "Zapdos": {"keep_best_cp": 3, "keep_best_iv": 3},
        "Articuno": {"keep_best_cp": 3, "keep_best_iv": 3},
        "Mew": {"keep_best_cp": 3, "keep_best_iv": 3},
        "Mewtwo": {"keep_best_cp": 3, "keep_best_iv": 3},
        "Dragonite": {"keep_best_cp": 3, "keep_best_iv": 3},
        "Gyarados": {"keep_best_cp": 3, "keep_best_iv": 3},
        "Snorlax": {"keep_best_cp": 3, "keep_best_iv": 3},
        "Lapras": {"keep_best_cp": 3, "keep_best_iv": 3},
        "Arcanine": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Vaporeon": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Jolteon": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Flareon": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Aerodactyl": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Mr. Mime": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Magmar": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Pinsir": {"keep_best_cp": 1, "keep_best_iv": 1},        
        "Farfetch'd": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Kangaskhan": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Tauros": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Charizard": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Blastoise": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Raichu": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Exeggcutor": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Muk": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Gengar": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Golem": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Tangela": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Horsea": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Magikarp": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Ditto": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Kabutops": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Porygon": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Omastar": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Starmie": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Seaking": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Lickitung": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Kingler": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Hypno": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Electrode": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Ninetales": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Onix": {"keep_best_cp": 1, "keep_best_iv": 1},        
        "Dewgong": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Cloyster": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Haunter": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Golem": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Weezing": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Victreebel": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Machamp": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Radidash": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Slowbro": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Hitmonlee": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Hitmonchamp": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Marowak": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Alakazam": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Venusaur": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Nidoqueen": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Nidoking": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Golem": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Poliwrath": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Rhydon": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Vileplume": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Clefable": {"keep_best_cp": 1, "keep_best_iv": 1},
        "Wigglytuff": {"keep_best_cp": 1, "keep_best_iv": 1}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},
        "Aerodactyl": {},
        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}

**Comment by jnguyen32** [comment]
It looks like it has to do with the order of the tasks. The Catch Pokemon task happens before the move to pokemon. Directly after it is move to fort.

**Comment by k4n30** [comment]
Great to hear you solved your own issue, can this be closed @jnguyen32 ?

**Comment by bruno-barbosa** [comment]
I have the same issue care to share your latest config?

Best Regards,

**Comment by pascaltiel** [comment]
i have the same issue
 i have the newest update but still he encounted all the pokemons 
 how can i fix this allready thanx for the help
![print](https://cloud.githubusercontent.com/assets/20987673/17618888/76fbc7aa-6082-11e6-9cbc-203d47335f63.png)

**Comment by k4n30** [comment]
@bruno-barbosa & @pascaltiel as per @jnguyen32 's comments his config is attached above, all he did was re order the tasks so it wasn't:

1. catch pokemon
2. move to pokemon
3. move to fort

I'm assuming he went 2,1,3

**Comment by pascaltiel** [comment]
i can not do that or even find it lol not so smart whit software to change :)

**Comment by k4n30** [comment]
#3605
