### ISSUE TITLE
evolve_captured removed?

### ISSUE THREAD

**Issue by kdim953** [PokemonGoF/PokemonGo-Bot#3675]
### Actual Behavior

Why was evolve_captured removed? This was actually useful as the evolve task only runs at startup. The ability to evolve immediately after capture (before transfer) was useful. Please return this functionality.

#3530 

### Other Information
OS: Ubuntu 14.04
Git Commit: b8af467f8e694adf3e2353876e27159d4f16daee
Python Version: Python 2.7.6

**Comment by fari-99** [comment]
can confirmed. pidget got captured but not evolved even using evolve capture and evolve pokemon.

actual behaviour
![screen shot 2016-08-12 at 9 42 00 am](https://cloud.githubusercontent.com/assets/8443932/17611441/7a8c9c70-6071-11e6-9ea6-7c767df9480e.png)

config:
```
{
        "type": "EvolvePokemon",
          "config": {
            "evolve_all": "Kabuto,Nidoran F,Nidoran M,Pidgey,Rattata,Zubat,Weedle,Drowzee",
            "first_evolve_by": "cp",
            "evolve_above_cp": 0,
            "evolve_above_iv": 0,
            "logic": "or",
            "evolve_speed": 3,
            "use_lucky_egg": false,
            "run_interval": 180
          }
      }
```

```
"evolve_captured": "Kabuto,Nidoran F,Nidoran M,Pidgey,Rattata,Zubat"
```

OS : windows 10 and Mac OSX 10.11
Git Commit : b8af467f8e694adf3e2353876e27159d4f16daee
Python version: Python 2.7.10

**Comment by kdim953** [comment]
#3530
