### ISSUE TITLE
Merge Issues -  <<<< HEAD syntax errors

### ISSUE THREAD

**Issue by thorowwasdf** [PokemonGoF/PokemonGo-Bot#3679]
Issue without proper information won't be answered

Expected Behavior

I want bot to START

Actual Behavior

$-MacBook-Pro:pokemongo-bot$ ./run.sh
Traceback (most recent call last):
File "pokecli.py", line 41, in 
from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
File "/Users/$/PokemonGo-Bot/pokemongo_bot/init.py", line 19, in 
import cell_workers
File "/Users/$/PokemonGo-Bot/pokemongo_bot/cell_workers/init.py", line 3, in 
from catch_lured_pokemon import CatchLuredPokemon
File "/Users/$/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_lured_pokemon.py", line 8, in 
from pokemongo_bot.cell_workers.pokemon_catch_worker import PokemonCatchWorker
File "/Users/$/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 306
<<<<<<< HEAD
^
SyntaxError: invalid syntax
Thu Aug 11 18:18:10 PDT 2016 Pokebot Stopped.
Press any button or wait 20 seconds to continue.

Steps to Reproduce

./run.sh

Information

OS Yosemite 10.10.5
Git commit ( to get git commit run git log -1 --format="%H")
Python V: Python 2.7.10

**Comment by k4n30** [comment]
Wow, bad merge

I don't want to be that guy, but the one vital piece of information that would have been able to help us help you is the Information -> Git commit section that you omitted. If you could provide this info, and what branch you're on, we can sort this out relatively quickly.

**Comment by thorowwasdf** [comment]
Sorry how do i find this?

**Comment by DavidBindloss** [comment]
**
Git commit ( to get git commit run git log -1 --format="%H")
**

**Comment by thorowwasdf** [comment]
b8af467f8e694adf3e2353876e27159d4f16daee

**Comment by k4n30** [comment]
Ok well no one else is reporting this issue, so it doesn't look like a bad commit

Have you made changes to PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py ? If not can you open the file and scroll to line 306 and see if you can see `<<<<<<< HEAD` anywhere around there

**Comment by lifesound7** [comment]
Hi, 
i have the same issue today... And yes, it is <<<<<<< HEAD in line 306

**Comment by k4n30** [comment]
Hmmmm the plot thickens.....
@lifesound7 what commit are you on? is it the same as @thorowwasdf ? also can you post your details, ie OS, branch, commit etc

**Comment by lifesound7** [comment]
OS: OS X El capitan
Git Commit: 44d7b39
Python Version: Python 2.7.10

I guess an issue was with bot files, because It works after I have deleted files and reinstalled.

**Comment by k4n30** [comment]
@thorowwasdf can you try the same please, that was my next step before @lifesound7 said they had the same issue. Can you try a fresh install (remember to keep your config)

**Comment by cmezh** [comment]
It looks like it is not completed git merge.
Try:
```
git reset --hard
git pull origin dev
```
Or if you use master branch replace dev to master in the second line.

**Comment by k4n30** [comment]
@ogalababa - https://github.com/PokemonGoF/PokemonGo-Bot/issues/3679#issuecomment-239498095

**Comment by thorowwasdf** [comment]
@cmezh  thanks for the tip but it didnt work

**Comment by k4n30** [comment]
@thorowwasdf As this is not a bot issue, i'm going to close this issue. I'd suggest (like before) a fresh install (remember to keep your config)
