### ISSUE TITLE
commands unknown

### ISSUE THREAD

**Issue by JaydenHamence** [PokemonGoF/PokemonGo-Bot#3681]
need commands for install and run on mac website isnt working

**Comment by 3ryanob3** [comment]
https://iosgods.com/topic/33072-updated-with-new-api-pokemon-go-bot-for-mac/

**Comment by k4n30** [comment]
[Install Guide](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/installation.md)

[Please don't use github issues for help related functions, that's what the chat server is for](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/README.md#pokemongo-bot)
