### ISSUE TITLE
Hatched Pokemon IV not truncated

### ISSUE THREAD

**Issue by keugnu** [PokemonGoF/PokemonGo-Bot#3685]
### Expected Behavior
Irrational fractions should be rounded or truncated at the second decimal place to match the rest of the output.

### Actual Behavior
`[23:37:29] Egg hatched with a Paras (CP 506 - IV 14/13/12 0.866666666667), 500 exp, 1466 stardust and 19 candies.`

Git Commit: 01ac445d48b5a5adeda84ed58388c525c6314f4a

**Comment by k4n30** [comment]
#3381
