### ISSUE TITLE
Auto GYM battle

### ISSUE THREAD

**Issue by jojonarte** [PokemonGoF/PokemonGo-Bot#3686]
Hi I'd like to ask since it is not in the documentation but I'm seeing some gym battle inputs in the proto folder. 

Is there no way yet to have the bot do gym battles?

**Comment by razithekillers** [comment]
Did you read the bot info? This not design to battle GYM!

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#gym-battles
