### ISSUE TITLE
updatelivestats

### ISSUE THREAD

**Issue by TSEFF** [PokemonGoF/PokemonGo-Bot#3687]
I found the level_completion_percentage was not correct...

So I changed it to show the ETA to next level instead.. :P

if experience_per_hour != 0:
            eta_next_lvl = float(require_xp/metrics.xp_per_hour())
        else:
            eta_next_lvl = 0

'level_completion': '{:,} XP ({:,.2f})hr'.format(require_xp,
                                                              eta_next_lvl),

**Comment by k4n30** [comment]
@TSEFF Why not create a [pull request](https://github.com/PokemonGoF/PokemonGo-Bot/compare) especially if you have already done the work

**Comment by TSEFF** [comment]
i am new to github... :P

**Comment by k4n30** [comment]
No worries, I've added the help wanted label so that someone can help you out :) Thanks for raising the issue

**Comment by k4n30** [comment]
@TSEFF has this been resolved?

**Comment by TSEFF** [comment]
@k4n30 yes... thank you
