### ISSUE TITLE
Error with configuration file

### ISSUE THREAD

**Issue by geraldagung** [PokemonGoF/PokemonGo-Bot#3689]
always getting this messages..pls help

2016-08-12 12:41:23,208 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-12 12:41:23,209 [       cli] [INFO] No config argument specified, checking for /configs/config.json
/Users/geraldagung/PokemonGo-Bot/pokemongo_bot/../configs/config.json:3:16: Error: Can not decode value starting with character u'\u201c'
   |  At line 3, column 16, offset 48
/Users/geraldagung/PokemonGo-Bot/pokemongo_bot/../configs/config.json:3:38: Info: Recovering parsing after character u','
   |  At line 3, column 38, offset 70
/Users/geraldagung/PokemonGo-Bot/pokemongo_bot/../configs/config.json:4:16: Error: Can not decode value starting with character u'\u201c'
   |  At line 4, column 16, offset 88
/Users/geraldagung/PokemonGo-Bot/pokemongo_bot/../configs/config.json:4:27: Info: Recovering parsing after character u','
   |  At line 4, column 27, offset 99
/Users/geraldagung/PokemonGo-Bot/pokemongo_bot/../configs/config.json:19:8: Warning: Object contains duplicate key: u'type'
   |  At line 19, column 8, offset 425
   |  Object started at line 13, column 8, offset 322
/Users/geraldagung/PokemonGo-Bot/pokemongo_bot/../configs/config.json:20:8: Warning: Object contains duplicate key: u'config'
   |  At line 20, column 8, offset 457
   |  Object started at line 13, column 8, offset 322
/Users/geraldagung/PokemonGo-Bot/pokemongo_bot/../configs/config.json: has errors
2016-08-12 12:41:23,234 [       cli] [CRITICAL] Error with configuration file

**Comment by doctordo0m** [comment]
Please use the issue template and fill out the required fields.

**Comment by keugnu** [comment]
As stated in the issue template that you didn't read and erased, use http://jsonlint.com to find errors in your config.

**Comment by geraldagung** [comment]
solved,,thx
