### ISSUE TITLE
[ERROR] Login process failed (for google)

### ISSUE THREAD

**Issue by theresthatguy** [PokemonGoF/PokemonGo-Bot#3690]
I am getting error `[ERROR] Login process failed: Invalid Google Username/password`. Which lead me to believe I had incorrectly put in my credentials. I triple checked username and password; both are correct. My config.jsn validates.

```
{
    "auth_service": "google",
    "username": "first.last@gmail.com",
    "password": "numberslettersonly123",
    "location": "latitude, longitude",
    "gmapkey": "REDACTED",
    "libencrypt_location": "/dir/pokemon",
    "tasks": [
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 10,
          "item_filter": {
            "Incense":        {"keep" : 0 },
            "Razz Berry":     { "keep" : 50 },
            "Pokeball":       { "keep" : 10 },
            "Greatball":      { "keep" : 80},
            "Ultraball":      { "keep" : 100},
            "Potion":         { "keep" : 25 },
            "Super Potion":   { "keep" : 50 },
            "Hyper Potion":   { "keep" : 75 },
            "Max Potion":     { "keep" : 100 },
            "Revive":         { "keep" : 50 },
            "Max Revive":     { "keep" : 100}
          }
        }
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort"
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 0.5,
    "catch_randomize_spin_factor": 0.5,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"}
    }
}
```

OS: Linux Mint 18 based on Ubuntu 16.04
Git Commit: fatal: Not a git repository (or any parent up to mount point /hdd)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Python Version: Python 2.7.12

Thanks in advance.

**Comment by k4n30** [comment]
What version of the bot are you using? dev or master?

**Comment by rumytaulu** [comment]
If you used google 2-step-verification, you can't use your google password, create an App password instead and put it in bot's password section.

https://support.google.com/accounts/answer/185833?hl=en

**Comment by k4n30** [comment]
@theresthatguy what did you do to solve the issue for those in future who have the same problem?

**Comment by theresthatguy** [comment]
If you used google 2-step-verification, you can't use your google password, create an App password instead and put it in bot's password section.

https://support.google.com/accounts/answer/185833?hl=en
