### ISSUE TITLE
[WARNING] Permabann

### ISSUE THREAD

**Issue by licklake** [PokemonGoF/PokemonGo-Bot#3694]
Today many players (me included) in the issue section, reddit and other platforms, got banned (proberbly perma) because of botusing (or cheating how casual players would it).
If you're not affected by this, I would advise you to be careful. Maybe stop the bot for a while or at least set the walking speed down and make a few breaks every now and then. 
It seams like Niantic is trying to shut us down before they implement trading.

**Comment by yweitkemper** [comment]
Yea seems like one of my bots got banned but other one didn't. Not sure what the criteria is because i usually always ran them at the same time and same path.

**Comment by k4n30** [comment]
Please don't use issues for this type of info, take it to the slack server
