### ISSUE TITLE
[Suggestion] Evolve conditions should take into account number of candies 

### ISSUE THREAD

**Issue by pacpac42** [PokemonGoF/PokemonGo-Bot#3695]
The idea that the bot knows IVs and is farming pokemon, candies and stardust should allow us to be less (or to not be) concerned about the CP, since this can be increased through player powerups if there are sufficient candies and stardusts.

So if it becomes more of a player responsibility to powerup their desired pokemons (as it seems to be intended) after the bot finishes running, the bot should ensure that a certain amount of candies would be left before evolving.

One way to do this would be to add a candies_to_keep logic in the evolution conditions, so that evolution happens if {(evolve_above_cp AND/OR evolve_above_iv) AND/OR candies_to_keep} is true, where both AND/OR logics are customizable. Happy to discuss how and whether this evolution logic should be changed.

**Comment by Anakin5** [comment]
@pacpac42 
You can choose to only evolve your best pokemons with the Pokemon optimizer task.
In case you also want to evolve some Pokemon for XP, there is also a logic that will prevent the task from using candies on rare pokemons.
