### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by lifesound7** [PokemonGoF/PokemonGo-Bot#3699]
Hello,
I cant update:

**After i run:** git pull

**I get:**
error: Pull is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Tried to fix with:**
git reset --hard HEAD

**And run again:** git pull , 
**i got:**

Auto-merging pokemongo_bot/event_handlers/colored_logging_handler.py
CONFLICT (content): Merge conflict in pokemongo_bot/event_handlers/colored_logging_handler.py
Auto-merging pokemongo_bot/cell_workers/pokemon_catch_worker.py
CONFLICT (content): Merge conflict in pokemongo_bot/cell_workers/pokemon_catch_worker.py
Auto-merging pokemongo_bot/__init__.py
Auto-merging CONTRIBUTORS.md
CONFLICT (content): Merge conflict in CONTRIBUTORS.md
Automatic merge failed; fix conflicts and then commit the result.

### Other Information
OS: OS X El capitan
Git Commit: 44d7b39ae3446ddc1af083be6d8dae38d4c68326
Python Version: Python 2.7.10

**Comment by k4n30** [comment]
The issue tracker is not for configuration problems. Take it to slack to discuss.

p.s my suggestion would be to do a fresh checkout, and then move your config back in
