### ISSUE TITLE
Trainer no longer shown on map

### ISSUE THREAD

**Issue by kaise123** [PokemonGoF/PokemonGo-Bot#370]
![ss 2016-07-23 at 05 41 27](https://cloud.githubusercontent.com/assets/1339312/17076881/1d326f1a-50fd-11e6-86c0-a30fae6455d2.jpg)

### Expected Behavior

Trainer icon to be shown on the map, and map to center on trainer.

### Actual Behavior

Map loads but shows Belgium no matter where your bot is currently, and does not show trainer on map.
This functionality was working earlier, I believe before the multiple users change.

### Steps to Reproduce

Point web server to 'web' folder, load map in browser.

### Other Information
OS: Ubuntu 14.04
Git Commit: e466101374a4a80fe9e84ddbb0d1e4bf1372ed8b

**Comment by Reaver01** [comment]
Right now you have to define your username in the html file. I am working on making username config be an external json file.

**Comment by kaise123** [comment]
I just worked that out actually. Should this be added to the readme so that it's clearer? Also should be stated that it must be login username not your trainer's name, and that it must be uncommented to work correctly.

**Comment by TheSavior** [comment]
This list should really be automated. The script on start knows what the username is, we should just be saving that to a file.

**Comment by surfaace** [comment]
web support is now a seperate project
