### ISSUE TITLE
Nidoran F or M

### ISSUE THREAD

**Issue by LuckyMe4Evers** [PokemonGoF/PokemonGo-Bot#3718]
Is there a possibility to truncate the space from Nidoran F and Nidoran M?
Because i use "nickname_template":"{name:.8s}-{iv_pct}" and they are both named Nidoran -000. If the space could be trucated then it would become NidoranF-000 or NidoranM-000.
I'm not a programmer and thats why i'm asking it.

**Comment by lfairy** [comment]
Can't we just use ♀ and ♂ directly? According to [this Reddit post][1] the game supports Unicode in nicknames.

[1]: https://www.reddit.com/r/TheSilphRoad/comments/4rxcqe/you_can_name_your_pokemon_with_unicode_symbols/

**Comment by k4n30** [comment]
@jrjhealey is this possible now?

**Comment by jrjhealey** [comment]
I'm not sure. I don't recall seeing any PRs to fix this (though I also didn't really look that hard).

I never bother to define rename rules, so I don't know if it's possible but perhaps you just need to define a slightly different renaming rule/different syntax to cope with the space in the name? Not sure if this is required to be integrated directly in to the bot code.

@TheSavior do you happen to know if this can be done already?

**Comment by Gobberwart** [comment]
Adding a string replace in nickname_pokemon.py should do it, around line 334.

Eg.

```
    pokemon.name.replace(" ","")
```

**Comment by k4n30** [comment]
@Gobberwart PR?

**Comment by Gobberwart** [comment]
I would but my current fork has a bunch of changes in it related to another PR, and I have no clue how to work on two simultaneous forks. Sorry, new to github.

**Comment by k4n30** [comment]
Branches :p 

Not urgent, feel free to wait until you have finished on the current work

**Comment by Gobberwart** [comment]
PR #4739

**Comment by Gobberwart** [comment]
This was done and can be closed now
