### ISSUE TITLE
[WARNING] Niantic seems to ban IP but not accounts

### ISSUE THREAD

**Issue by izanagi1995** [PokemonGoF/PokemonGo-Bot#3720]
After speaking a lot of people on Slack, it's seems that Niantic bans IP. Those people connects the bot and can't pokestops... But logging with the phone (with a different account) seems to solve the problem.

So I think that Niantic bans the bot's IP but not account! Why? I don't know... Maybe collecting other bot's IPs to ban them all!

PokeBot, ban them all!

**Comment by fari-99** [comment]
we already know about it, it's called the softban IP address. it will wore out after one hour or so. 

someone (my friend) got his account can connect but always get server error. even using bot and phone.

**Comment by izanagi1995** [comment]
@k4n30 please reopen the issue. It's a major change in the Niantic mind.

**Comment by k4n30** [comment]
#3700 for continued conversation

**Comment by alanwong5361** [comment]
I get this message when i logged in to pokemon go this morning. Failed to get data from server. Is it a perma ban from pokemon. Im just using this apps for 2 weeks. Any help?

**Comment by pogarek** [comment]
try the account on the legit game on phone. 
none of my 3 bots got banned - they are running since september.

**Comment by alanwong5361** [comment]
Im running it on my phone all the while.... only this morning happen. Last night still can on. Any help

**Comment by alanwong5361** [comment]
I was using phone to bot all this while. Only this morning happen. Last
night still can on my Pokemon Go
