### ISSUE TITLE
FollowSpiral loop between non existent positions

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#3721]
### Actual Behavior
everything was fine for two days, then
when bot starts, after 
[IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 3.74 km
[FollowSpiral] [INFO] [position_update] Walking from (48.86266, 2.330028, 0) to (48.86266, 2.330028, 0) (0.0 m)
it loops between inexistent coordinates:
[12:12:19] Skipping Recycling of Items. 129 space left in bag.
[12:12:19] Walking from (48.86266, 2.330028, 0) to (48.86266, 2.330028, 0) (0.0 m)
[12:12:20] Skipping Recycling of Items. 129 space left in bag.
[12:12:20] Walking from (48.86266, 2.330028, 0) to (48.86329194720581, 2.330028, 0) (70.2693093787 m)
[12:12:20] {'distance_unit': '', 'distance': '', 'current_position': (48.862720455172095, 2.330041857339295), 'last_position': (48.86266, 2.330028)}
[12:12:22] Skipping Recycling of Items. 129 space left in bag.

### Your config.json (remove your credentials and any other private info)
{
    "auth_service": "google",
    "username": "",
    "password": "",
    "location": "",
    "gmapkey": "",
    "// libencrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "catch_throw_parameters": {
      "excellent_rate": 0.1,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.6
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

your config here
MAC OSX Capitan

### Other Information
OS: OSX Capitan
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
f7838b8b431ff36b12f6c0bd643dbf673db34be5
Python Version: (run 'python -V' and paste it here)
Python 2.7.12

**Comment by RomikB** [comment]
same, all forts disappear from bot, but visible in game

**Comment by el1as** [comment]
Ip banned, try to change the ip and will work!

**Comment by fari-99** [comment]
related issue #3692

**Comment by Gurzeh** [comment]
Perfectly right! Do you know if IP are permanently banned?

**Comment by Gurzeh** [comment]
Then reading related issue:
"It's a softban, try to open your pokemongo account in your smartphone, you won't see any pokestop and/or pokemon, been there ;)
Stop botting for about an hour and you are good to go."

thx guys, you rock

**Comment by nivong** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3720
@k4n30

**Comment by fari-99** [comment]
btw please close this issue if you solve the problem.

happy "catch".

**Comment by k4n30** [comment]
#3308 #3394 #3475 #3646 #3692 #3711 #3721
