### ISSUE TITLE
Permanent ban wave is now! "My account got (hard) ban?"

### ISSUE THREAD

**Issue by joaodragao** [PokemonGoF/PokemonGo-Bot#3724]
My account got (hard) ban?

```
inventory_req = self.get_inventory_data()
inventory_dict = inventory_req['responses']['GET_INVENTORY'][
            'inventory_delta']['inventory_items']
```

And I got:

`KeyError: u'inventory_delta'`

**Comment by nivong** [comment]
#3720
@k4n30

**Comment by fari-99** [comment]
please use the issue template if you have a problem.

if you have problem regarding installing or configuration file. please use slack chat.

**Comment by joaodragao** [comment]
From Niantic (Your account was permanently terminated) lol
https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308

> Submit a ban appeal

> Your account was permanently terminated for violations of the Pokémon GO Terms of Service. This includes, but is not limited to: falsifying your location, using emulators, modified or unofficial software and/or accessing Pokémon GO clients or backends in an unauthorized manner including through the use of third party software.

> Our goal is to provide a fair, fun and legitimate game experience for everyone. We will continue to work with all of you to improve the quality of the gameplay, including ongoing optimization and fine tuning of our anti-cheat system. If you believe your account has been terminated in error incorrectly, you can appeal that termination through this form.  For privacy reasons, please do not post appeals on social media.

**Comment by fari-99** [comment]
@joaodragao welp, looks like you can ban people right now. well, i will not battle gym for now.

**Comment by joaodragao** [comment]
When I log in with actual game, this is what I get,

> Our servers are humbled by your incredible
> We are working to resolve the issue. Please try again soon!

![hard-ban](https://cloud.githubusercontent.com/assets/20815349/17620843/11c04c1c-6087-11e6-8deb-544f0be105c5.jpg)

**Comment by joaodragao** [comment]
I'll keep this issue open and report if I'm able to get back that account in a few hours later.

**Comment by fari-99** [comment]
can confirm, one of my friend got like this too. haha.

**Comment by joaodragao** [comment]
Another screenshot! I think it related to `inventory_delta` key is not found in the JSON data.

> Failed to get game data from the server.

![hard-ban-2](https://cloud.githubusercontent.com/assets/20815349/17621031/8bf5ff9e-6088-11e6-9323-e0c01f2807f4.png)

**Comment by joaodragao** [comment]
Wait. I saw many reports taht PTC server is down while Google server is ok. This account is PTC? So that's because of the server down?

**Comment by chuparCh0pper** [comment]
http://ispokemongodownornot.com/

**Comment by KoiPanda** [comment]
Is it perm ban if I can log in, but all the pokemon i try to catch runs away. ie, 10cp pidgy and used ultra ball -> runs away

**Comment by joaodragao** [comment]
the `response_dict`
```
{'status_code': 3, 'responses': {'GET_INVENTORY': {}}, 'request_id': 416745958203508484L}
```

**Comment by takenek** [comment]
@KoiPanda  This is soft ban when pokemons run away. if You get perm ban You can`t login to account.

**Comment by JaydenHamence** [comment]
@KoiPanda same as me can you still get pokestops too?

**Comment by LuckyMe4Evers** [comment]
Failed to get game data from the server.
Got this too with a bot i didn't use in a long time, but i started him with my phone not with my pc.
Tried my lan, tried the free lan of my ISP and tried my 4G. I got it on all of them. Niantec servers having problems.

**Comment by vicch** [comment]
PTC account running the map works fine, Google account running the bot getting "Server seems to be busy or offline", and on mobile app it's "Failed to get game data from the server."

**Comment by k4n30** [comment]
#3682

**Comment by ndacules** [comment]
me too cant log in
how to fix??
