### ISSUE TITLE
Not catching any pokemon

### ISSUE THREAD

**Issue by vinay-ellore** [PokemonGoF/PokemonGo-Bot#3726]
![screen shot 2016-08-12 at 4 27 24 pm](https://cloud.githubusercontent.com/assets/16683595/17620400/c0e48830-60a9-11e6-99b7-fe234983ab71.png)

**Comment by nivong** [comment]
#3720
@k4n30

**Comment by izanagi1995** [comment]
IP ban...

**Comment by JaydenHamence** [comment]
[21:28:15] A wild Zubat appeared! [CP 24] [Potential 0.42] [A/D/S 10/7/2]
[21:28:17] Used Pokeball, with chance 100.00 (64 left)
[21:28:18] Zubat vanished!

**Comment by JaydenHamence** [comment]
?

**Comment by ksiamro** [comment]
soft ban

**Comment by JaydenHamence** [comment]
@ksiamro can still spin stops get loot and hatch eggs?

**Comment by srg2k5** [comment]
same problem, I can spin forts and hatch eggs, but every pokemon vanishes.  my wife's bot isn't doing that however from the same machine so it defintely feels like something they marked on my account, but why it would still let me spin forts is confusing.

**Comment by lmondry** [comment]
Same here

**Comment by k4n30** [comment]
#3700
