### ISSUE TITLE
move_to_map_pokemon_move_towards (instead of move_to_fort) in snipe=true mode?

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#3727]
### Expected Behavior
After a successful teleport, the bot should resume to walk around it's initial location

### Actual Behavior
It does, going through his tasks, but I noticed in the dev branch that (after a teleport) it starts doing a lot of "move_to_map_pokemon_move_towards" to pokemon (instead of move_to_fort) when in fact it seems to be resuming his wandering in the original location.

### Your config.json (remove your credentials and any other private info)
{
    "auth_service": "google",
    "username": "",
    "password": "",
    "location": "",
    "gmapkey": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "23:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 10,
            "evolve_above_iv": 0.2,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 150 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToMapPokemon",
        "config": {
	"address": "http://localhost:5000",
	"max_distance": 500,
	"min_time": 60,
	"min_ball": 50,
	"prioritize_vips": true,
	"snipe": true,
	"snipe_high_prio_only": true,
	"snipe_high_prio_threshold": 600,
	"update_map": true,
	"mode": "priority",
          "catch": {
               "Alakazam":    1000,
               "Articuno":    1000,
		"Chansey":	1000,
		"Charizard":	1000,
		"Charmeleon":	1000,
		"Dewgong":	1000,
		"Ditto":	1000,
		"Farfetch'd":	1000,
		"Kabutops":	1000,
		"Kangaskhan":	1000,
		"Lapras": 	1000,
		"Magneton":	1000,
		"Mew": 		1000,
		"Mewtwo": 	1000,
		"Moltres":	1000,
		"Mr. Mime":	1000,
		"Muk": 		1000,
		"Primeape":	1000,
		"Raichu":	1000,
		"Rhydon":	1000,
		"Snorlax": 	1000,
		"Tauros":	1000,
		"Zapdos": 	1000,

		"———— always catch ————": 0,
		"Dragonair": 	1000,
		"Dragonite": 	1000,
		"Dratini": 	1000,

		"———— missing in Pokedex ————": 0,
		"Cubone":	1000,

		"———— for better IV ————": 0,

		"———— for evolve ————": 0,
		"Abra":		800,
		"Charmander":	800,
		"Eevee":	800,
		"Grimer": 	800,
		"Kabuto":	800,
		"Kadabra":	800,
		"Magnemite":	800,
		"Mankey":	800,
		"Pikachu":	800,
		"Rhyhorn":	800,

		"———— best fighters ————": 0,
		"Arcanine": 	700,
		"Blastoise":	700,
		"Exeggutor": 	700,
		"Flareon": 	700,
		"Gyarados": 	700,
		"Poliwrath": 	700,
		"Vaporeon": 	700,
		"Venusaur": 	700,
		
		"———— last level ————": 0,
		"Aerodactyl":	200,
		"Arbok":	200,
		"Beedrill":	200,
		"Butterfree":	200,
		"Clefable":	200,
		"Cloyster":	200,
		"Dodrio":	200,
		"Dugtrio":	200,
		"Electabuzz":	200,
		"Electrode":	200,
		"Fearow":	200,
		"Gengar":	200,
		"Golbat":	200,
		"Golem":	200,
		"Golduck":	200,
		"Graveler":	200,
		"Hitmonchan":	200,
		"Hitmonlee":	200,
		"Hypno":	200,
		"Jolteon":	200,
		"Jynx":		200,
		"Kingler":	200,
		"Lickitung":	200,
		"Machamp":	200,
		"Magmar":	200,
		"Marowak":	200,
		"Nidoking":	200,
		"Nidoqueen":	200,
		"Ninetales":	200,
		"Omanyte":	200,
		"Omastar":	200,
		"Onix":		200,
		"Parasect":	200,
		"Persian":	200,
		"Pidgeot":	200,
		"Pinsir":	200,
		"Porygon":	200,
		"Rapidash":	200,
		"Raticate":	200,
		"Scyther":	200,
		"Sandslash":	200,
		"Seadra":	200,
		"Seaking":	200,
		"Slowbro":	200,
		"Starmie":	200,
		"Tangela":	200,
		"Tentacruel":	200,
		"Venomoth":	200,
		"Victreebel":	200,
		"Vileplume":	200,
		"Weezing": 	200,
		"Wigglytuff":	200,

		"———— spareable ————": 0,
		"Bellsprout":	100,
		"Bulbasaur":	100,
		"Clefairy":	100,
		"Diglett":	100,
		"Doduo":	100,
		"Drowzee":	100,
		"Ekans":	100,
		"Gastly":	100,
		"Geodude":	100,
		"Gloom":	100,
		"Goldeen":	100,
		"Graveler":	100,
		"Growlithe": 	100,
		"Haunter":	100,
		"Horsea":	100,
		"Ivysaur":	100,
		"Jigglypuff":	100,
		"Kakuna":	100,
		"Koffing":	100,
		"Krabby":	100,
		"Machoke":	100,
		"Magikarp": 	100,
		"Machop":	100,
		"Meowth":	100,
		"Metapod":	100,
		"Nidorina":	100,
		"Nidorino":	100,
		"Nidoran F":	100,
		"Nidoran M":	100,
		"Pidgeotto":	100,
		"Oddish":	100,
		"Paras":	100,
		"Poliwag":	100,
		"Poliwhirl":	100,
		"Ponyta":	100,
		"Psyduck":	100,
		"Rattata":	100,
		"Sandshrew":	100,
		"Seel":		100,
		"Shellder":	100,
		"Slowpoke":	100,
		"Spearow":	100,
		"Squirtle":	100,
		"Staryu":	100,
		"Tentacool":	100,
		"Venonat":	100,
		"Voltorb":	100,
		"Vulpix":	100,
		"Wartortle":	100,
		"Weepinbell":	100,
		"Zubat":	100,

		"———— to upgrade pas ————": 0,
		"Pidgey":	10,
		"Caterpie":	10,
		"Weedle":	10
    
          }
        }
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.5,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging_color": true,
   "evolve_captured": "none",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Eevee:": {},
      "Eevee": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Best fighters, keep 2:": {},
      "Arcanine": {"keep_best_iv": 2},
      "Dragonair": {"keep_best_iv": 2},
      "Dragonite": {"keep_best_iv": 2},
      "Dratini": {"keep_best_iv": 2},
      "Exxegutor": {"keep_best_iv": 2},
      "Flareon": {"keep_best_iv": 2},
      "Gyarados": {"keep_best_iv": 2},
      "Poliwrath": {"keep_best_iv": 2},
      "Slowbro": {"keep_best_iv": 2},
      "Vaporeon": {"keep_best_iv": 2},
      "Venusaur": {"keep_best_iv": 2},

	"———— level final ————": 0,
      "Arbok": {"keep_best_iv": 1},
      "Beedrill": {"keep_best_iv": 1},
      "Butterfree": {"keep_best_iv": 1},
      "Clefable": {"keep_best_iv": 1},
      "Cloyster": {"keep_best_iv": 1},
      "Dodrio": {"keep_best_iv": 1},
      "Dugtrio": {"keep_best_iv": 1},
      "Fearow": {"keep_best_iv": 1},
      "Electabuzz": {"keep_best_iv": 1},
      "Electrode": {"keep_best_iv": 1},
      "Gengar": {"keep_best_iv": 1},
      "Golbat": {"keep_best_iv": 1},
      "Golduck": {"keep_best_iv": 1},
      "Golem": {"keep_best_iv": 1},
      "Hitmonchan": {"keep_best_iv": 1},
      "Hitmonlee": {"keep_best_iv": 1},
      "Hypno": {"keep_best_iv": 1},
      "Jolteon": {"keep_best_iv": 1},
      "Jynx": {"keep_best_iv": 1},
      "Kingler": {"keep_best_iv": 1},
      "Lickitung": {"keep_best_iv": 1},
      "Magmar": {"keep_best_iv": 1},
      "Marowak": {"keep_best_iv": 1},
      "Ninetales": {"keep_best_iv": 1},
      "Omastar": {"keep_best_iv": 1},
      "Onix": {"keep_best_iv": 1},
      "Parasect": {"keep_best_iv": 1},
      "Persian": {"keep_best_iv": 1},
      "Pidgeot": {"keep_best_iv": 1},
      "Pinsir": {"keep_best_iv": 1},
      "Ponyta": {"keep_best_iv": 1},
      "Porygon": {"keep_best_iv": 1},
      "Rapidash": {"keep_best_iv": 1},
      "Raticate": {"keep_best_iv": 1},
      "Scyther": {"keep_best_iv": 1},
      "Seadra": {"keep_best_iv": 1},
      "Seaking": {"keep_best_iv": 1},
      "Starmie": {"keep_best_iv": 1},
      "Tangela": {"keep_best_iv": 1},
      "Tentacruel": {"keep_best_iv": 1},
      "Venomoth": {"keep_best_iv": 1},
      "Victreebel": {"keep_best_iv": 1},
      "Weezing": {"keep_best_iv": 1},
      "Wigglytuff": {"keep_best_iv": 1},

	"———— level 2 ————": 0,
      "Haunter": {"keep_best_iv": 1},
      "Ivysaur": {"keep_best_iv": 1},
      "Nidorina": {"keep_best_iv": 1},
      "Nidorino": {"keep_best_iv": 1},
      "Pidgeotto": {"keep_best_iv": 1},
      "Wartortle": {"keep_best_iv": 1},

	"———— level 1 ————": 0,
      "Bulbasaur": {"keep_best_iv": 1},
      "Bellsprout": {"keep_best_iv": 1},
      "Clefairy": {"keep_best_iv": 1},
      "Cubone": {"keep_best_iv": 1},
      "Diglett": {"keep_best_iv": 1},
      "Doduo": {"keep_best_iv": 1},
      "Drowzee": {"keep_best_iv": 1},
      "Ekans": {"keep_best_iv": 1},
      "Fearow": {"keep_best_iv": 1},
      "Gastly": {"keep_best_iv": 1},
      "Geodude": {"keep_best_iv": 2},
      "Goldeen": {"keep_best_iv": 1},
      "Growlithe": {"keep_best_iv": 1},
      "Horsea": {"keep_best_iv": 1},
      "Jigglypuff": {"keep_best_iv": 1},
      "Kakuna": {"keep_best_iv": 1},
      "Koffing": {"keep_best_iv": 1},
      "Krabby": {"keep_best_iv": 1},
      "Magikarp": {"keep_best_iv": 1},
      "Meowth": {"keep_best_iv": 1},
      "Metapod": {"keep_best_iv": 1},
      "Nidoran F": {"keep_best_iv": 1},
      "Nidoran M": {"keep_best_iv": 1},
      "Paras": {"keep_best_iv": 1},
      "Poliwag": {"keep_best_iv": 1},
      "Poliwhirl": {"keep_best_iv": 1},
      "Ponyta": {"keep_best_iv": 1},
      "Psyduck": {"keep_best_iv": 1},
      "Rattata": {"keep_best_iv": 1},
      "Raticate": {"keep_best_iv": 1},
      "Shellder": {"keep_best_iv": 1},
      "Slowpoke": {"keep_best_iv": 1},
      "Spearow": {"keep_best_iv": 1},
      "Spearow": {"keep_best_iv": 1},
      "Squirtle": {"keep_best_iv": 1},
      "Staryu": {"keep_best_iv": 1},
      "Tentacool": {"keep_best_iv": 1},
      "Venonat": {"keep_best_iv": 1},
      "Voltorb": {"keep_best_iv": 1},
      "Vulpix": {"keep_best_iv": 1},
      "Zubat": {"keep_best_iv": 1},
      "Weepinbell": {"keep_best_iv": 1}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1500, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}
your config here
```

### Steps to Reproduce
with the DEV branch,
after a successful teleport, when teleporting back it starts to move_to_map_pokemon_move_towards instead of move_to_fort

I plan to log the location & pokemon to check where the bit is really (when soft ban is over) :)

### Other Information
OS: OSX Capitan
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
50cd7bf243eab90b88a2d8bd99e105b39647f331
Python Version: (run 'python -V' and paste it here)
Python 2.7.12

**Comment by Gurzeh** [comment]
I add some logs showing this behavior:
2016-08-12 13:17:27,771 [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Eevee! [CP 641] [Potential 0.47] [3/4/14] [+210 exp]
2016-08-12 13:17:28,272 [PokemonCatchWorker] [INFO] [gained_candy] You now have 258 Eevee candy!
2016-08-12 13:17:33,278 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Eevee, 0.22km, left (13 minutes, 27 seconds)
2016-08-12 13:17:37,335 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_teleport_to] Teleporting to Eevee. (0.28km)
2016-08-12 13:17:37,335 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_encounter] Encountered Pokemon: Eevee
2016-08-12 13:17:39,839 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_teleport_back] Teleporting back to previous location (48.8628677463, 2.33116598058)
2016-08-12 13:17:42,244 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Eevee appeared! [CP 12] [Potential 0.29] [A/D/S 0/13/0]
2016-08-12 13:17:44,397 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 100.00 (97 left)
2016-08-12 13:17:45,140 [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Eevee! [CP 12] [Potential 0.29] [0/13/0] [+210 exp]
2016-08-12 13:17:45,671 [PokemonCatchWorker] [INFO] [gained_candy] You now have 261 Eevee candy!
2016-08-12 13:17:50,676 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Eevee, 0.28km, left (2 minutes, 19 seconds)
2016-08-12 13:17:55,248 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_teleport_to] Teleporting to Eevee. (0.11km)
2016-08-12 13:17:55,248 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_encounter] Encountered Pokemon: Eevee
2016-08-12 13:17:57,775 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_teleport_back] Teleporting back to previous location (48.8628828368, 2.33108783616)

more...

2016-08-12 13:18:24,679 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Rattata, 0.08km, left (10 minutes, 35 seconds)
2016-08-12 13:18:28,321 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Rattata, 0.08km, left (10 minutes, 31 seconds)
2016-08-12 13:18:31,072 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Rattata, 0.07km, left (10 minutes, 28 seconds)
2016-08-12 13:18:33,338 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Rattata, 0.07km, left (10 minutes, 26 seconds)
2016-08-12 13:18:36,773 [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Rattata, 0.07km, left (10 minutes, 23 seconds)

I'm sure I don't want to snipe-walk to Rattata.. :)

**Comment by Gurzeh** [comment]
Is it because Rattata appears in the Teleport list?
"catch": {
..
    "Rattata":  100,
..

So the solution would be to just leave ONLY the pokemon I want to teleport to
(as such the "snipe_high_prio_threshold": 600 does not seems very helpful)

**Comment by k4n30** [comment]
Correct.
