### ISSUE TITLE
+210 xp ?

### ISSUE THREAD

**Issue by angnaybr** [PokemonGoF/PokemonGo-Bot#3729]
Bot always captures with +210 xp. if niantic detects it, can it be a way to ban users in future?
any suggestions?

**Comment by Chenyu-Tsai** [comment]
"catch_randomize_reticle_factor" : "0.0"
"catch_randomize_spin_factor" : "0.0"

done.

**Comment by angnaybr** [comment]
do i have to add this command to config.json ?

**Comment by k4n30** [comment]
Modify [this line](https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/configs/config.json.example#L116) and [this line](https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/configs/config.json.example#L117) in your config

Not an issue with the bot

**Comment by xscrable** [comment]
add to config:
"catch_throw_parameters":{
      "excelent_rate": 0.1,
      "great_rate": 0.3,
      "nice_rate": 0.5,
      "spin_success_rate": 0.6
    },
and remove 
catch_randomize_reticle_factor" : "0.0"
"catch_randomize_spin_factor" : "0.0"

**Comment by tolinwei** [comment]
Any update about this?

I tried to change "catch_randomize_reticle_factor" and "catch_randomize_spin_factor" to non-one value, like 0.7 and 0.8, all the pokemons were caught with 210 exp.

I also tried to add 
'''
    "catch_throw_parameters": {
        "excelent_rate": 0.1,
        "greate_rate": 0.4,
        "nice_rate": 0.6,
        "noraml_rate": 0.1,
        "spin_success_rate": 0.6
    }
'''
The bot is still capturing all with 210 exp.

**Comment by angnaybr** [comment]
yes just use this code
"catch_randomize_reticle_factor": 0.1,
"catch_randomize_spin_factor": 0.1,
