### ISSUE TITLE
ImportError: No module named pgoapi.exceptions

### ISSUE THREAD

**Issue by medienoekonom** [PokemonGoF/PokemonGo-Bot#3730]
HEy there, 

I initially wanted to setup everything. I chose the setup.sh method. But i get an error:

Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions
Fr 12. Aug 13:48:32 CEST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

![image](https://cloud.githubusercontent.com/assets/20904559/17621504/044910c0-6094-11e6-878e-a1072268f2ca.png)

**Comment by nivong** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/installation.md

**Comment by JosUijterwaal** [comment]
@nivong that's not a solution

@medienoekonom having the same issue, can be two things:

1. The google login is slow/down
2. playtime is limited by Niantic to prevent overloads

http://www.mmoserverstatus.com/pokemon_go indicates that both could be the case

**Comment by nivong** [comment]
@JosUijterwaal `ImportError: No module named pgoapi.exceptions` is an incorrected installation...

**Comment by JosUijterwaal** [comment]
@nivong apologies then!

where am I going wrong?

total 632
drwxr-xr-x  40 Jos  staff    1360 Aug 11 23:22 .
drwxr-xr-x+ 27 Jos  staff     918 Aug 12 11:13 ..
lrwxr-xr-x   1 Jos  staff      63 Aug 11 22:48 .Python -> /System/Library/Frameworks/Python.framework/Versions/2.7/Python
-rw-r--r--   1 Jos  staff      43 Aug 11 22:48 .dockerignore
drwxr-xr-x  14 Jos  staff     476 Aug 11 22:52 .git
drwxr-xr-x   4 Jos  staff     136 Aug 11 22:48 .github
-rw-r--r--   1 Jos  staff    1673 Aug 11 22:48 .gitignore
-rw-r--r--   1 Jos  staff      80 Aug 11 22:48 .gitmodules
-rw-r--r--   1 Jos  staff      34 Aug 11 22:48 .mention-bot
-rw-r--r--   1 Jos  staff     211 Aug 11 22:48 .pullapprove.yml
-rw-r--r--   1 Jos  staff      60 Aug 11 22:48 .pylintrc
-rw-r--r--   1 Jos  staff     112 Aug 11 22:48 .styles.yapf
-rw-r--r--   1 Jos  staff     288 Aug 11 22:48 .travis.yml
-rw-r--r--   1 Jos  staff     860 Aug 11 22:48 CONTRIBUTORS.md
-rw-r--r--   1 Jos  staff     735 Aug 11 22:48 Dockerfile
-rw-r--r--   1 Jos  staff    1081 Aug 11 22:48 LICENSE
-rw-r--r--   1 Jos  staff    3393 Aug 11 22:48 README.md
drwxr-xr-x  26 Jos  staff     884 Aug 11 22:49 bin
drwxr-xr-x   8 Jos  staff     272 Aug 12 11:13 configs
drwxr-xr-x   9 Jos  staff     306 Aug 11 23:22 data
-rw-r--r--   1 Jos  staff     510 Aug 11 22:48 docker-compose.yml
drwxr-xr-x  11 Jos  staff     374 Aug 11 22:48 docs
-rw-r--r--@  1 Jos  staff  209964 Aug 11 23:22 encrypt.so
drwxr-xr-x   4 Jos  staff     136 Aug 11 22:49 include
-rwxr-xr-x   1 Jos  staff    1807 Aug 11 22:48 install.sh
drwxr-xr-x   3 Jos  staff     102 Aug 11 22:48 lib
-rw-r--r--   1 Jos  staff      60 Aug 11 22:48 pip-selfcheck.json
-rw-r--r--   1 Jos  staff   16872 Aug 11 22:48 pokecli.py
drwxr-xr-x  41 Jos  staff    1394 Aug 11 23:00 pokemongo_bot
drwxr-xr-x   5 Jos  staff     170 Aug 11 22:48 proto
-rw-r--r--   1 Jos  staff    1596 Aug 11 22:48 pylint-recursive.py
-rw-r--r--   1 Jos  staff     482 Aug 11 22:48 requirements.txt
-rw-r--r--   1 Jos  staff     236 Aug 11 22:48 run.bat
-rwxr-xr-x   1 Jos  staff     440 Aug 11 22:48 run.sh
-rwxr-xr-x   1 Jos  staff    3174 Aug 11 22:48 setup.sh
drwxr-xr-x   3 Jos  staff     102 Aug 11 22:49 share
drwxr-xr-x   4 Jos  staff     136 Aug 11 22:49 src
drwxr-xr-x  10 Jos  staff     340 Aug 11 22:48 tests
drwxr-xr-x  20 Jos  staff     680 Aug 11 23:24 web
-rwxr-xr-x   1 Jos  staff     597 Aug 11 22:48 ws_server.py
SnappCars-MacBook-Pro-2:PokemonGo-Bot Jos$ sh run setup.sh -i
sh: run: No such file or directory
SnappCars-MacBook-Pro-2:PokemonGo-Bot Jos$ sh run setup.sh -c
sh: run: No such file or directory
SnappCars-MacBook-Pro-2:PokemonGo-Bot Jos$ run setup.sh -r
-bash: run: command not found
SnappCars-MacBook-Pro-2:PokemonGo-Bot Jos$ sh run setup.sh -r
sh: run: No such file or directory
SnappCars-MacBook-Pro-2:PokemonGo-Bot Jos$ sh run setup.sh -u
sh: run: No such file or directory

**Comment by JosUijterwaal** [comment]
The thing is that it was running fine and after I killed and restarted it a couple of times it threw this error

**Comment by nivong** [comment]
*SnappCars*-MacBook-Pro-2:PokemonGo-Bot Jos$ sh run setup.sh -i
sh: run: No such file or directory
You didn't follow the install instructions correctly.
Try these:
https://github.com/nivong/PokemonGo-Bot/blob/patch-5/docs/installation.md

@k4n30 please merge this commit to prefent these noob errors. https://github.com/PokemonGoF/PokemonGo-Bot/pull/3593

on a side note, snappcars macbook, really ? lol

**Comment by k4n30** [comment]
@nivong I dont have merge access :(

OP has closed the issue, please leave it alone now. There is a PR to prevent the issue in the future
