### ISSUE TITLE
Pokemon keep on vanishing in PokemonCatchWorker

### ISSUE THREAD

**Issue by AutopsyMania** [PokemonGoF/PokemonGo-Bot#3740]
Since Berlin time:
2016-08-12 15:54:31,772
using dev branch

But SpinFort is okay...

**Comment by AutopsyMania** [comment]
Using Necrobot, catching Pokemon is okay but not spinning forts...

**Comment by stevenyap** [comment]
Same here... pokemon keeps vanishing. Thought it was a softban after waiting out for 4 hours, the issue is still the same

**Comment by umbreon222** [comment]
Duplicate #3700

**Comment by jnguyen32** [comment]
Just started happening about 30 mins ago.

**Comment by AutopsyMania** [comment]
I switched to my real phone device and using Pokomon Go App. Tried to throw away (not hitting pokemon) 45 pokeballs and the the pokemons still got vanishing. Manual unban methods does not work for me.

**Comment by GitPupper** [comment]
#3746 - [**META** Banwaves - Permanent Bans](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3746)

**Comment by beanstalkk** [comment]
permanent bans have started.
