### ISSUE TITLE
Too much Xp, very few Stardust. Anyone can HELP me?

### ISSUE THREAD

**Issue by ibuSuki** [PokemonGoF/PokemonGo-Bot#3744]
Hi! I would like to catch the pokemon with the "usual" XP points. Bot always catch them with 210 XP, and then, the Stardust is not equilibrated, in my opinion. How can I set the bot to catch the Pokémon with the usual Xp (100-110-150...etc) ?
I will be very grateful to give me a simple answer, since I'm not a programmer, I'm just a user.

Sorry for my english, thanks.

# We are aware that there are mass bans of different magnitudes being experienced by a lot of the bot users with symptoms such as:
1. Bot being able to login, and catch pokemon but NOT spin forts
2. Bot being able to login, NOT catch pokemon (vanishing) but able to spin forts
4. Some accounts not being able to login at all

We are also aware of the getting stuck between 2 forts and getting caught in an infinite loop

# If any issues are created relating to the above KNOWN issues they will be closed without reason

## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. Are you running `master`? We work on the `dev` branch and then add that functionality to `master`. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.

### Your config.json (remove your credentials and any other private info)
```
your config here
```

### Other Information
OS:
Branch: dev or master
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by andirapandi** [comment]
Did you try

https://github.com/PokemonGoF/PokemonGo-Bot/issues/3746#issuecomment-239515961

?

There you can set probability of each catch result in your config.json.

**Comment by k4n30** [comment]
This is not a bot issue, configuration problems should be discussed in the slack chat
