### ISSUE TITLE
Transfer still not working

### ISSUE THREAD

**Issue by crusardri** [PokemonGoF/PokemonGo-Bot#375]
### Expected Behavior

Transfer a pokemon with low CP/IV

### Actual Behavior

Nothing

### Steps to Reproduce

Start the bot with filters (and without filters)

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Sorry, i don't know how i can know this info T.T
I just download the lastest dev a few minutes ago

**Comment by dominikue** [comment]
Have the same problem - just "--cp 300" and the bot doesn't transfer.

**Comment by jle3** [comment]
Same here. Pokemon aren't being exchanged for candy below the specified CP ceiling.

**Comment by Notnuk** [comment]
Same....

**Comment by tonz134** [comment]
-IV only working on me.
using both -c and -IV will not transfer candy nor using just -c.

**Comment by surfaace** [comment]
fixed in dev
