### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by MatteCarra** [PokemonGoF/PokemonGo-Bot#3751]
I have linux and I followed installation instructions but something is missing:
```
File "pokecli.py", line 38, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions
```

**Comment by seratkurtulus** [comment]
are you sure you have installed everything in requirements.txt successfully? and this section is for issues about the bot, please use slack for help.

**Comment by nivong** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues?utf8=%E2%9C%93&q=No%20module%20named%20pgoapi.exceptions

**Comment by TLuigi003** [comment]
Sometimes for some strange reason pip doesn't actually install all the dependencies properly
Re-run pip install - requirements.txt

**Comment by GitPupper** [comment]
#3682 - [**META** Server busy or offline issues](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3682)
#3308 - [**META** Stuck between two forts / Moving to 2 forts at the same time / Constant Loop](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3308)
#3700 - [**META** Soft bans - Try again spins / Pokemon vanishing](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3700)
#3746 - [**META** Banwaves - Permanent Bans](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3746)
