### ISSUE TITLE
bot getting this error "[21:47:52] () Exception caught, writing LogBuffer.  Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.    at PoGo.NecroBot.CLI.Program.CheckKillSwitch()    at PoGo.NecroBot.CLI.Program.Main(String[] args)" why?

### ISSUE THREAD

**Issue by neeth1994** [PokemonGoF/PokemonGo-Bot#3753]
i'm getting this new error, [21:47:52] () Exception caught, writing LogBuffer.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.CLI.Program.CheckKillSwitch()
   at PoGo.NecroBot.CLI.Program.Main(String[] args),
any idea anyone?

**Comment by apy230** [comment]
same problem. is this kind of ban? i tried to use a fresh copy of 0.8.5 and get the same error

**Comment by nivong** [comment]
use the fn issue template why delete everytrhing we write?

**Comment by abusalman** [comment]
wrong room pals..

**Comment by razithekillers** [comment]
necro not exists anymore and you are in wrong repo what wrong with you people!

**Comment by apy230** [comment]
do you know how to fix this guys?

**Comment by razithekillers** [comment]
Go clone PokemonGo-Bot pal
