### ISSUE TITLE
[Question] Game BOT Programming

### ISSUE THREAD

**Issue by BOSS124** [PokemonGoF/PokemonGo-Bot#3758]
Someone can tell me how the bot developers for this kind of game begins the project, the first steps, I mean, how can they identify the technologies used by the game and build a compiled or interpreted code that can simulate a player steps without opening the game. I was wondering if they begins using some kind of tool to capture and analyze the game packets. I don't know, someone help?
Thanks

**Comment by razithekillers** [comment]
its API

**Comment by cmezh** [comment]
It's question to pgoapi developers

**Comment by BOSS124** [comment]
Yeah, now I see, should've posted it on PokemonGO API programming. Sorry
