### ISSUE TITLE
items_stock missing in pokemon_catch_worker.py

### ISSUE THREAD

**Issue by ynvtlmr** [PokemonGoF/PokemonGo-Bot#3759]
On Dev.
**items_stock** global variable missing
referenced in lines **269** and **284** of
_PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py_

**Comment by OniZakuma** [comment]
Same here

**Comment by ChrisHaPunkt** [comment]
and here

**Comment by Vvkmnn** [comment]
Same on d580dfe39781f2590812815bf1c000b6d173cad7

**Comment by joaodragao** [comment]
Fixed #3760

**Comment by ynvtlmr** [comment]
Fix verified
