### ISSUE TITLE
error during starting

### ISSUE THREAD

**Issue by anticodo** [PokemonGoF/PokemonGo-Bot#3765]
# We are aware that there are mass bans of different magnitudes being experienced by a lot of the bot users with symptoms such as:
1. Bot being able to login, and catch pokemon but NOT spin forts
2. Bot being able to login, NOT catch pokemon (vanishing) but able to spin forts
4. Some accounts not being able to login at all

We are also aware of the getting stuck between 2 forts and getting caught in an infinite loop

# If any issues are created relating to the above KNOWN issues they will be closed without reason

## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. Are you running `master`? We work on the `dev` branch and then add that functionality to `master`. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.

### Your config.json (remove your credentials and any other private info)
```
your config here
```

### Other Information
OS:
Branch: dev or master
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by anticodo** [comment]
![pokemon go problem](https://cloud.githubusercontent.com/assets/20996408/17632060/cc74852a-60c6-11e6-9d72-d1145ac71e80.GIF)

**Comment by GitPupper** [comment]
#3682 - [**META** Server busy or offline issues](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3682)
#3308 - [**META** Stuck between two forts / Moving to 2 forts at the same time / Constant Loop](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3308)
#3700 - [**META** Soft bans - Try again spins / Pokemon vanishing](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3700)
#3746 - [**META** Banwaves - Permanent Bans](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3746)
