### ISSUE TITLE
Missing Pokestop

### ISSUE THREAD

**Issue by ntanto** [PokemonGoF/PokemonGo-Bot#3775]
mod im sorry

please consider this option about the problem
missing pokestop is about niantic server capacity, its happen after they open for several new country

how do i consider about it and not ip ban?
i use mobile network for my primary internet connection
and i never get any public ip, even i restart my device i always get same public ip

i ran bot for few minutes then restart it and bingo missing pokestop
so its not about cleaning the server, more about their capacity

**Comment by Unscrupulor** [comment]
Why did you open an issue for this???????
