### ISSUE TITLE
ERROR with pokecli.py

### ISSUE THREAD

**Issue by daybreakgaming** [PokemonGoF/PokemonGo-Bot#3778]
I get this error when I do ./run.sh

> 2016-08-12 19:55:56,321 [ cli] [INFO] PokemonGO Bot v1.0
> 2016-08-12 19:55:56,434 [ cli] [INFO] Configuration initialized
> 2016-08-12 19:55:56,434 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
> 2016-08-12 19:55:56,434 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
> 2016-08-12 19:55:56,829 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
> 
> [19:55:57] Setting start location.Traceback (most recent call last):
> File "pokecli.py", line 514, in
> main()
> File "pokecli.py", line 138, in main
> report_summary(bot)
> File "pokecli.py", line 147, in report_summary
> metrics.capture_stats()
> File "/Users/lars/PokemonGo-Bot/pokemongo_bot/metrics.py", line 84, in capture_stats
> response_dict = request.call()
> File "/Users/lars/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 90, in call
> if not self.can_call():
> File "/Users/lars/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 54, in can_call
> raise NoPlayerPositionSetException()
> pgoapi.exceptions.NoPlayerPositionSetException
> 2016-08-12 19:55:57,325 [sentry.errors] [ERROR] Sentry responded with an error: 'module' object has no attribute 'HTTPSHandler' (url: https://app.getsentry.com/api/90254/store/)
> Traceback (most recent call last):
> File "/Library/Python/2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
> super(ThreadedHTTPTransport, self).send(data, headers)
> File "/Library/Python/2.7/site-packages/raven/transport/http.py", line 47, in send
> ca_certs=self.ca_certs,
> File "/Library/Python/2.7/site-packages/raven/utils/http.py", line 44, in urlopen
> class ValidHTTPSHandler(urllib2.HTTPSHandler):
> AttributeError: 'module' object has no attribute 'HTTPSHandler'
> 2016-08-12 19:55:57,326 [sentry.errors.uncaught] [ERROR] [u'NoPlayerPositionSetException', u' File "pokecli.py", line 514, in ', u' File "pokecli.py", line 138, in main', u' File "pokecli.py", line 147, in report_summary', u' File "pokemongo_bot/metrics.py", line 84, in capture_stats', u' File "pokemongo_bot/api_wrapper.py", line 90, in call', u' File "pokemongo_bot/api_wrapper.py", line 54, in can_call']

```

**Comment by nivong** [comment]
use the template that is being provided for you or we can't help you....

**Comment by daybreakgaming** [comment]
Im new, I dont know what template you are talking about

**Comment by nivong** [comment]
the text you didn't read before posting this issue.

**Comment by daybreakgaming** [comment]
I said its what happens when I do ./run.sh

**Comment by nivong** [comment]
@k4n30 please close this

**Comment by k4n30** [comment]
@daybreakgaming when you created this issue, there is a bunch of text that you deleted without reading. Please create a new issue with all the required fields filled out so that we can help you without haveing to ask 100 questions back and forward
