### ISSUE TITLE
Ban wave - Most of us survived?

### ISSUE THREAD

**Issue by SypherMWB** [PokemonGoF/PokemonGo-Bot#3782]
Hello,

As everyone has noticed most botters that where using Necrobot got banned permanently, sending out emails etc. Did most of us survive as we are using an 'human-like' configuration file? I'm not sure if i want to start up the bot right now, so i want to know what most of you are all doing? And are you guys pausing BOTTING or will you keep going/waiting for an update?

**Comment by azydub** [comment]
I think I survived using that option... am able to login to my acc, no bans.

**Comment by SypherMWB** [comment]
Same here, my bot doesn't do weird stuff, seems we dodged the bullet for now..

**Comment by Waliers** [comment]
Ill just wait it out ;) lets see what happens after the initial ban wave. Maybe they will look through the logs and then ban the next accounts. (As in most obvious first and then this might be so let's take a closer look)

**Comment by pacpac42** [comment]
I did not get an email, but I wasn't able to figured out if I got IP banned or account banned, soft or hard. If I understand correctly, only those who got account hard-banned (permanently) will receive emails. My situation is pokemons appear but always flee, and I cannot get in range of pokestops. Are you having the same issue?

**Comment by SypherMWB** [comment]
On my phone everything works normally, i can use pokestops and catch pokemons, @Waliers I'm also waiting and hoping we dodged it for now.

**Comment by wyhfrank** [comment]
I can catch pokemons, but cannot spin pokestops, saying "out of range".

**Comment by YuMan-Tam** [comment]
I think if you can log in then you are softbanned. Just wait several hours. It worked for me.

**Comment by Vvkmnn** [comment]
Got the same thing as @wyhfrank. Playing the waiting game now.

**Comment by DiegoRBaquero** [comment]
My two accounts survived though I do see some pokestops not spinning and not being able to fight in a gym when gps-spoofing now.

**Comment by Tomygames** [comment]
I got 2 accounts perm banned :/

**Comment by Tomygames** [comment]
And i wan't see pokestops on 2 other accounts ...

**Comment by Waliers** [comment]
HOw you know your perma? Did they mail you?

**Comment by SypherMWB** [comment]
@Tomygames You should receive an email that they perm banned your account.

**Comment by Tomygames** [comment]
No, but i can't logging, it's most likely a perm ban, they just didn't have the right code to show the message, and i didn't get an email thought

**Comment by Waliers** [comment]
NO mail NO perma ban :)

**Comment by Tomygames** [comment]
Awesome :D, Do you know how much time before the urban ? :)

**Comment by GitPupper** [comment]
#3682 - [**META** Server busy or offline issues](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3682)
#3308 - [**META** Stuck between two forts / Moving to 2 forts at the same time / Constant Loop](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3308)
#3700 - [**META** Soft bans - Try again spins / Pokemon vanishing](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3700)
#3746 - [**META** Banwaves - Permanent Bans](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3746)

**Comment by pmquan** [comment]
I'm able to login. Can do gyms, swipe pokestops but I'm unable to catch any pokemons. They all fled.

**Comment by SypherMWB** [comment]
Yeah its a soft ban- try again in 4 hours.

**Comment by rickycc** [comment]
@pmquan That sounds weird, soft-ban tends to be no catches, pokestops and gyms, and you are definitely not getting a hard-ban since you can still log-in. Probably just wait it out should be fine.

**Comment by Waliers** [comment]
Its funny Niantic tried encryption, didnt work, tried legal action, didnt work now its banwave time! Just stay low, play safe and don't spoof like there is no tomorrow. I just go from Point A to B with Google Maps Travel time. So if it takes me 8 Hours to go to Mexico. I go to sleep and wake up in Mexico :P 

Don't underestimate there ability to find shit out. They have time, resources and logs. Play safe and senseable!

**Comment by shane17** [comment]
what about those of us that cant log in at all (Failed to get game data from server), but have no e-mail confirmation ?
Soft ban ?

**Comment by Waliers** [comment]
To clear up confusion there are several types of bans:
**Soft IP ban** Ban the IP but not the account (not permanent). All accounts on the ip will be unable to see pokestops and pokemon. Usually goes away after 20 mins of not accessing the pogo api from that IP.
**Hard IP ban** Ban the IP perm. This happened to cloud providers like AWS. You can't log in or access pogo at all from one of these IPs. Never goes away.
**Soft ban Account specific** - there are now multiple types of softbans: (time to go away varies)
- Spinning pokestops gives nothing, and pokemon always run on the first ball. (this was the original softban)
- Spinning pokestops is fine, but pokemon always run. (added today)
- All pokestops say out of range, and no pokemon ever spawn (added recently)
- You can catch pokemon fine, but can not spin pokestops ... there may be more
**Hard ban Perma ban** (Read data error on phone). This is the new ban that botters have been getting. If you get a login error, it does not mean you are banned for sure, but if you were botting or teleporting and you can't log in on that account from any IP, and you can use other accounts - good chance thats a hardban.

People wondering **what actions cause the ban**. It is still unknown, but it seems related to highly frequent requests involving teleporting. However, any third party api usage or GPS spoofing voilates their TOS and it is possible you can receive a ban. I recommend not using any 3rd party service or spoofing for at least 24 hours. IMO, If you have never botted or spoofed/sniped, it is unlikely you will get banned. But I would avoid using any services that require your login until this is sorted out.

**Comment by shane17** [comment]
one of my accounts got "banned" with walk set to 4.16 and no sniping .... ever

Failed to get data from server. but no e-mail received. What kind of a ban do you think this is ?

**Comment by yweitkemper** [comment]
I thought I survived one of my accounts got banned last night, then the other one just got banned about 30 mins ago.

**Comment by shane17** [comment]
you continued to bot ?

**Comment by yweitkemper** [comment]
Nah I didn't stopped yesterday one still didn't get banned till this morning

**Comment by kipperjx2** [comment]
I have catch flee and try again later for pokestops. Soft ban? Wait it out ?

**Comment by Thedyolf** [comment]
since 5.00 AM failed to get data from server error. Seems like that was the start of it. I believe it is a ban since most replies on forums are from botters (which I'm not sure what % of the community exists of right now) it's been about 21.5 hours and I'm still getting the same error message. Can log in to my main (completely legit) account right now. Start losing hope but it might still be a corrupted data file created by all guys logged in at 5AM standard time (England). Anyone who can confirm being logged in at that time who didn't get banned? Last option I see as a possibility. otherwise. r.i.p. pokemon go :(

**Comment by kokkie2012** [comment]
[12:59:19] (ERROR) Probably Permanent Ban!
[12:59:19] (ATTENTION) Program will continue after the key press...

That is what Necrobot says.... so yeah
