### ISSUE TITLE
MoveToMapPokemon not working

### ISSUE THREAD

**Issue by pingz27** [PokemonGoF/PokemonGo-Bot#3784]
I just noticed that my bot stop walking toward pokemon and aim to only pokestops. It worked perfectly before and I haven't changed my config file so far.

**Comment by nivong** [comment]
Use the template or dont get any help from us.

**Comment by GitPupper** [comment]
#3682 - [**META** Server busy or offline issues](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3682)
#3308 - [**META** Stuck between two forts / Moving to 2 forts at the same time / Constant Loop](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3308)
#3700 - [**META** Soft bans - Try again spins / Pokemon vanishing](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3700)
#3746 - [**META** Banwaves - Permanent Bans](https://github.com/PokemonGoF/PokemonGo-Bot/issues/3746)

**Comment by pingz27** [comment]
Yes I use the template and it was working very well until at some point it stopped looking for pokemon :(
