### ISSUE TITLE
error on launch bot : ssl

### ISSUE THREAD

**Issue by Tagada22** [PokemonGoF/PokemonGo-Bot#3789]
Hello guys ,

i have a problems when i launch my bot .

i have this error 

(PokemonGo-Bot) root@vps302994:/home/PokemonGo-Bot# ./run.sh configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 33, in <module>
    import ssl
  File "/usr/lib/python2.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl
Fri Aug 12 22:17:48 CEST 2016 Pokebot configs/config.json Stopped.
Press any button or wait 20 seconds to continue.

i don't know how to fix that , if you have an idea please .

a copy of my config.json

{
    "auth_service": "google",
    "username": "txxxxxxxxxr@gmail.com",
    "password": "xxxxxxxx",
    "location": "-33.870034, 151.207964",
    "gmapkey": "Axxxxxxxxxxxxxxx",
    "libencrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "iv",
            "evolve_above_cp": 500,
            "evolve_above_iv": 1,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":     { "keep" : 10 },
            "Greatball":    { "keep" : 100 },
            "Ultraball":    { "keep" : 100 },
            "Max Revive":   { "keep" : 20 },
            "Potion":       { "keep" : 0 },
            "Super Potion": { "keep" : 0 },
            "Hyper Potion": { "keep" : 10 },
            "Revive":       { "keep" : 10 },
            "Razz Berry":   { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
	    {
        "type": "MoveToMapPokemon",
        "config": {
          "address": "http://15xxx.xxx.x28:2020",
          "max_distance": 1000,
          "min_time": 60,
          "min_ball": 50,
          "prioritize_vips": true,
          "snipe": true,
          "snipe_high_prio_only": true,
          "snipe_high_prio_threshold": 400,
          "update_map": true,
          "mode": "priority",
          "map_path": "raw_data",
          "catch": {
            "==========Legendaries==========": 0,
            "Aerodactyl": 1000,
            "Snorlax": 1000,
            "Articuno": 1000,
            "Zapdos": 1000,
            "Moltres": 1000,
            "Dratini": 1000,
            "Dragonair": 1000,
            "Dragonite": 1000,
            "Mewtwo": 1000,
            "Mew": 1000,
            "==========Region Locked==========": 0,
            "Farfetch'd": 1000,
            "Kangaskhan": 1000,
            "Mr. Mime": 1000,
            "Tauros": 1000,
            "==========Very Rare==========": 0,
            "Lapras": 900,
            "Electabuzz": 900,
            "Magmar": 900,
            "Ditto": 900,
            "==========Starters==========": 0,
            "Bulbasaur": 400,
            "Ivysaur": 600,
            "Venusaur": 1000,
            "Charmander": 400,
            "Charmeleon": 600,
            "Charizard": 1000,
            "Squirtle": 400,
            "Wartortle": 600,
            "Blastoise": 1000,
            "Pikachu": 600,
            "Raichu": 1000,
            "==========Semi Rare==========": 0,
            "Porygon": 200,
            "Scyther": 200,
            "Jynx": 200,
            "==========Uncommon==========": 0,
            "Omanyte": 150,
            "Omastar": 500,
            "Seel": 300,
            "Dewgong": 500,
            "Grimer": 200,
            "Muk": 500,
            "Shellder": 200,
            "Cloyster": 500,
            "Gastly": 200,
            "Haunter": 500,
            "Gengar": 1000,
            "Onix": 600,
            "Drowzee": 600,
            "Hypno": 600,
            "Vulpix": 200,
            "Ninetales": 600,
            "Paras": 100,
            "Parasect": 500,
            "Growlithe": 200,
            "Arcanine": 700,
            "Tentacool": 200,
            "Tentacruel": 500,
            "Mankey": 150,
            "Primeape": 500,
            "Clefairy": 150,
            "Clefable": 500,
            "Jigglypuff": 150,
            "Wigglytuff": 500,
            "Venonat": 100,
            "Venomoth": 500,
            "Diglett": 200,
            "Dugtrio": 500,
            "Meowth": 250,
            "Persian": 500,
            "Psyduck": 150,
            "Golduck": 500,
            "Geodude": 100,
            "Graveler": 500,
            "Golem": 800,
            "Eevee": 200,
            "Vaporeon": 800,
            "Jolteon": 800,
            "Flareon": 800,
            "Kabuto": 150,
            "Kabutops": 500,
            "Magikarp": 150,
            "Gyarados": 800,
            "Pinsir": 150,
            "Ponyta": 200,
            "Rapidash": 500,
            "Slowpoke": 200,
            "Slowbro": 500,
            "Magnemite": 250,
            "Magneton": 500,
            "Krabby": 100,
            "Kingler": 500,
            "Voltorb": 200,
            "Electrode": 500,
            "Exeggcute": 250,
            "Exeggcutor": 500,
            "Cubone": 300,
            "Marowak": 800,
            "Hitmonlee": 400,
            "Hitmonchan": 400,
            "Lickitung": 500,
            "Koffing": 200,
            "Weezing": 500,
            "Rhyhorn": 200,
            "Rhydon": 500,
            "Chansey": 800,
            "Tangela": 300,
            "Horsea": 200,
            "Seadra": 600,
            "Goldeen": 150,
            "Seaking": 500,
            "Staryu": 200,
            "Starmie": 800,
            "==========T1 Evolvers==========": 0,
            "Caterpie": 10,
            "Metapod": 10,
            "Butterfree": 500,
            "Weedle": 10,
            "Kakuna": 10,
            "Beedrill": 500,
            "Pidgey": 10,
            "Pidgeotto": 10,
            "Pidgeot": 300,
            "==========T2 Evolvers==========": 0,
            "Nidoran F": 10,
            "Nidorina": 10,
            "Nidoqueen": 10,
            "Nidoran M": 10,
            "Nidorino": 10,
            "Nidoking": 10,
            "Oddish": 100,
            "Gloom": 200,
            "Vileplume": 600,
            "Poliwag": 200,
            "Poliwhirl": 400,
            "Poliwrath": 800,
            "Abra": 300,
            "Kadabra": 600,
            "Alakazam": 800,
            "Machop": 150,
            "Machoke": 400,
            "Machamp": 800,
            "Bellsprout": 100,
            "Weepinbell": 400,
            "Victreebel": 800,
            "==========Trash==========": 0,
            "Rattata": 10,
            "Raticate": 10,
            "Spearow": 10,
            "Fearow": 10,
            "Ekans": 10,
            "Arbok": 10,
            "Sandshrew": 10,
            "Sandslash": 10,
            "Zubat": 10,
            "Golbat": 10,
            "Doduo": 10,
            "Dodrio": 10
          }
        }
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"keep_best_iv": 1},
      "Arbok": {"keep_best_iv": 1},
      "Golbat": {"keep_best_iv": 1},
      "Charmeleon": {"keep_best_iv": 2},
      "Raticate": {"keep_best_iv": 1},
      "Sandslash": {"keep_best_iv": 1},
      "Nidoqueen": {"keep_best_iv": 1},
      "Nidoking": {"keep_best_iv": 1},
      "Pidgeotto": {"keep_best_iv": 1},
      "Spearow": {"keep_best_iv": 1},
      "Ekans": {"keep_best_iv": 1},
      "Kakuna": {"keep_best_iv": 1},
      "Clefairy": {"keep_best_iv": 1},
      "Clefable": {"keep_best_iv": 1},
      "Persian": {"keep_best_iv": 1},
      "Primeape": {"keep_best_iv": 1},
      "Arcanine": {"keep_best_iv": 1},
      "Machamp": {"keep_best_iv": 1},
      "Golem": {"keep_best_iv": 1},
      "Rapidash": {"keep_best_iv": 1},
      "Onix": {"keep_best_iv": 1},
      "Kingler": {"keep_best_iv": 1},
      "Rhydon": {"keep_best_iv": 1}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},
        "Blastoise": {},
        "Piedgeot": {},
        "Pikachu": {},
        "Arcanine": {},
        "Raichu": {},
        "Sandslash": {},
        "Ninetales": {},
        "Vileplume": {},
        "Golduck": {},
        "Poliwhirl": {},
        "Poliwrath": {},
        "Kadabra": {},
        "Alakazam": {},
        "Machoke": {},
        "Machamp": {},
        "Weepinbell": {},
        "Victreebel": {},
        "Golem": {},
        "Rapidash": {},
        "Muk": {},
        "Haunter": {},
        "Gengar": {},
        "Marowak": {},
        "Hitmonlee": {},
        "Hitmonchan": {},
        "Vaporeon": {},
        "Jolteon": {},
        "Flareon": {},
        "Porygon": {},
        "Omastar": {},
        "Aerodactyl": {},
        "Dratini": {},
        "Dragonair": {},
        "Dragonite": {},
        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Gyarados": {},
        "Exeggutor": {}
    }
}

I verified my config with json editor online and i have no error .

thanks

**Comment by Arlion** [comment]
Do you have the packages, openssl and python-openssl installed?

**Comment by k4n30** [comment]
Please read before you delete the text in the issue template, your missing key information which would help us help you
