### ISSUE TITLE
Starting bot in sleep cycle

### ISSUE THREAD

**Issue by OniZakuma** [PokemonGoF/PokemonGo-Bot#3792]
### Actual
When starting the bot while it should be in a sleep cycle, it waits for start of next sleep cycle.

### Expected
Bot should 'continue' sleeping and wake up on normal time.

**Comment by keugnu** [comment]
Is this the intended behavior?

**Comment by OniZakuma** [comment]
No, shouldn't be, sleep is sleep no matter when the bot starts.

**Comment by k4n30** [comment]
@OniZakuma does it sleep after 1 cycle of the bot (i.e a couple of seconds), or does it wait until the next day when the sleep cycle should start (i.e. 20 hours or so)

**Comment by OniZakuma** [comment]
No, it waits the full x-hours till next cycle starts.

**Comment by k4n30** [comment]
Sleep schedule may need to be updated after https://github.com/PokemonGoF/PokemonGo-Bot/pull/2956/commits/081d90de32de84810120a50b238b70093e51ef17

**Comment by k4n30** [comment]
#4031
