### ISSUE TITLE
Cant run pokecli.py

### ISSUE THREAD

**Issue by shane17** [PokemonGoF/PokemonGo-Bot#3793]
### Expected Behavior

Runs smoothly :D

### Actual Behavior

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\eventlet\__init__.py", line 5, in <module>
    from eventlet import greenthread
  File "C:\Python27\lib\site-packages\eventlet\greenthread.py", line 4, in <module>
    from eventlet import event
  File "C:\Python27\lib\site-packages\eventlet\event.py", line 3, in <module>
    from eventlet import hubs
  File "C:\Python27\lib\site-packages\eventlet\hubs\__init__.py", line 3, in <module>
    from eventlet import patcher
  File "C:\Python27\lib\site-packages\eventlet\patcher.py", line 4, in <module>
    from eventlet.support import six
  File "C:\Python27\lib\site-packages\eventlet\support\__init__.py", line 4, in <module>
    from eventlet.support import greenlets, six
  File "C:\Python27\lib\site-packages\eventlet\support\greenlets.py", line 3, in <module>
    import greenlet
ImportError: DLL load failed: The specified procedure could not be found.

Traceback (most recent call last):
  File "pokecli.py", line 41, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "E:\Programs\PokeBot\PokemonGo-Bot\pokemongo_bot\__init__.py", line 29, in <module>
    from pokemongo_bot.socketio_server.runner import SocketIoRunner
  File "E:\Programs\PokeBot\PokemonGo-Bot\pokemongo_bot\socketio_server\runner.py", line 5, in <module>
    from eventlet import patcher, wsgi
  File "C:\Python27\lib\site-packages\eventlet\patcher.py", line 4, in <module>
    from eventlet.support import six
  File "C:\Python27\lib\site-packages\eventlet\support\__init__.py", line 4, in <module>
    from eventlet.support import greenlets, six
  File "C:\Python27\lib\site-packages\eventlet\support\greenlets.py", line 3, in <module>
    import greenlet
ImportError: DLL load failed: The specified procedure could not be found.

### Your config.json (remove your credentials and any other private info)

{
    "auth_service": "google",
    "username": "YOUR_USERNAME",
    "password": "YOUR_PASSWORD",
    "location": "SOME_LOCATION",
    "gmapkey": "GOOGLE_MAPS_API_KEY",
    "libencrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"}
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"}
    },
    "vips" : {
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" }
    }
}

### Steps to Reproduce

python pokecli.py --config ./configs/config.json

### Other Information
OS: Windows 10 64x
Branch: dev AND master (both same error)
Git: b21b1449156b730fc224ed238f5b8bba606fe0f9
Python 2.7.12
pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)
Microsoft Visual C++ Compiler for Python 2.7. 
node --version     v6.3.1
npm --version     3.10.6

**Comment by GitPupper** [comment]
Try using a different encrypt.dll

**Comment by shane17** [comment]
Same problem :(
Even tried removing the encrypt.dll ~ same problem

**Comment by TridentNooch** [comment]
I have the same issue and it didn't start till i did a git pull this afternoon to get the latest update.

**Comment by shane17** [comment]
that fixed your issue ?

**Comment by TridentNooch** [comment]
No that didn't fix it. It's what broke it.

I was able to take the entire old install, and copy it back over to revert and that resolved my issue.  That's not saying that its not the encryption issue but the encrypt file that did work at least doesn't in the latest pull.  

My instinct is that its the pokecli.py file like it says, it doesn't like the format. I just haven't take the time to cut and paste it into a syntax checker.

**Comment by shane17** [comment]
switched python to 64 bit version fixed it.

Close pls

**Comment by TridentNooch** [comment]
Shane how did you do that?






[http://i59.tinypic.com/oazofq.png]<http://tinypic.com?ref=oazofq>


Aaron Bianucci
aaron@bianucci.us<mailto:aaron@bianucci.us>
@AaronBianucci<http://www.twitter.com/AaronBianucci>
http://www.aaronbianucci.com


On Fri, Aug 12, 2016 at 5:42 PM -0500, "shane17" <notifications@github.com<mailto:notifications@github.com>> wrote:


switched python to 64 bit version fixed it.

Close pls

-
