### ISSUE TITLE
why cant use command $wget?

### ISSUE THREAD

**Issue by stradazz12** [PokemonGoF/PokemonGo-Bot#3796]
Start to make encrypt.so
bash: wget: command not found
tar: pgoencrypt.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
bash: cd: pgoencrypt/src/: No such file or directory
bash: make: command not found
mv: cannot stat 'libencrypt.so': No such file or directory

that the flowing error i get when i use install.sh

**Comment by carlosbellino** [comment]
You need to install wget: 
debian based: apt-get install wget
arch: pacman -S wget
redhat based: yum -y install wget
suse: zypper install wget

**Comment by izaac** [comment]
setup.sh is missing this dependency for Mac OS X follow  @carlosbellino advice.

**Comment by nDarkness** [comment]
If you are using OSX then use this:
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
Once that finishes:
`brew update && brew upgrade && brew install wget`

**Comment by carlosbellino** [comment]
btw.. why would you want to bot in such a storm atm?

**Comment by Arlion** [comment]
a simple line could be added to the setup.sh script that looks like:

`command -v wget || echo "wget is not installed" ; exit 1`

This could also be enhanced to include other dependencies such as tar and make.

**Comment by k4n30** [comment]
Is someone going to create a PR for this fix?

**Comment by edysantosa** [comment]
@Arlion or better use curl instead of wget.

**Comment by stradazz12** [comment]
User@User-PC MINGW64 /d/try/PokemonGo-Bot (master)
$ tar xvfz pgoencrypt.tar.gz
pgoencrypt/
pgoencrypt/README.md
pgoencrypt/src/
pgoencrypt/src/test
pgoencrypt/src/.gitignore
pgoencrypt/src/encrypt.c
pgoencrypt/src/main.c
pgoencrypt/src/Makefile
pgoencrypt/src/encrypt.h
pgoencrypt/.git/
pgoencrypt/.git/index
pgoencrypt/.git/refs/
pgoencrypt/.git/refs/heads/
pgoencrypt/.git/refs/heads/master
pgoencrypt/.git/refs/tags/
pgoencrypt/.git/config
pgoencrypt/.git/hooks/
pgoencrypt/.git/hooks/pre-rebase.sample
pgoencrypt/.git/hooks/post-receive.sample
pgoencrypt/.git/hooks/pre-applypatch.sample
pgoencrypt/.git/hooks/prepare-commit-msg.sample
pgoencrypt/.git/hooks/applypatch-msg.sample
pgoencrypt/.git/hooks/update.sample
pgoencrypt/.git/hooks/commit-msg.sample
pgoencrypt/.git/hooks/post-commit.sample
pgoencrypt/.git/hooks/post-update.sample
pgoencrypt/.git/hooks/pre-commit.sample
pgoencrypt/.git/objects/
pgoencrypt/.git/objects/08/
pgoencrypt/.git/objects/08/189fb0ee7df6e7e79eab6851ac06dba2392848
pgoencrypt/.git/objects/20/
pgoencrypt/.git/objects/20/e76f78835f0f20aecf110f611807924d14c410
pgoencrypt/.git/objects/94/
pgoencrypt/.git/objects/94/a00f50f4c9164f145380af7d1068fa5dfe0441
pgoencrypt/.git/objects/98/
pgoencrypt/.git/objects/98/b8b4d17b40838cf609efe02b65345e453864e2
pgoencrypt/.git/objects/98/477fe40d6fcd993e3e7fd9bc37e56333a456bf
pgoencrypt/.git/objects/26/
pgoencrypt/.git/objects/26/a29d66791b1735ab031c53bffad7442604b72f
pgoencrypt/.git/objects/a2/
pgoencrypt/.git/objects/a2/8339c106bdcfc8cd9b66fb1138ab60b43233b8
pgoencrypt/.git/objects/pack/
pgoencrypt/.git/objects/2d/
pgoencrypt/.git/objects/2d/e16c8ec5bd13cafc8c3239ebf6a4a46c856f77
pgoencrypt/.git/objects/info/
pgoencrypt/.git/objects/cc/
pgoencrypt/.git/objects/cc/7836862df883f0d794109a5b02fa5c8b0144e5
pgoencrypt/.git/objects/6a/
pgoencrypt/.git/objects/6a/c8e1b2c7456925efddc4b37950a5a0e9181b21
pgoencrypt/.git/objects/2a/
pgoencrypt/.git/objects/2a/a10ed8cf7460c0c60929c31fac4df137ca6899
pgoencrypt/.git/objects/54/
pgoencrypt/.git/objects/54/07d1cbee8fde414bb2d8758786b6ec7aee78e0
pgoencrypt/.git/branches/
pgoencrypt/.git/info/
pgoencrypt/.git/info/exclude
pgoencrypt/.git/COMMIT_EDITMSG
pgoencrypt/.git/description
pgoencrypt/.git/logs/
pgoencrypt/.git/logs/refs/
pgoencrypt/.git/logs/refs/heads/
pgoencrypt/.git/logs/refs/heads/master
pgoencrypt/.git/logs/HEAD
pgoencrypt/.git/HEAD
pgoencrypt/tests/
pgoencrypt/tests/.gitignore

User@User-PC MINGW64 /d/try/PokemonGo-Bot (master)
$ cd pgoencrypt/src

User@User-PC MINGW64 /d/try/PokemonGo-Bot/pgoencrypt/src (master)
$ make
C:/cygwin64/bin/make.exe: error while loading shared libraries: cygguile-17.dll: cannot open shared object file: No such file or directory

-----------------------------------------------------------------------------------------------------------------
new prob can u fix command "make"
C:/cygwin64/bin/make.exe: error while loading shared libraries: cygguile-17.dll: cannot open shared object file: No such file or directory

i use cygwin to use tht command

**Comment by simonsmh** [comment]
Already fixed in dev. https://github.com/PokemonGoF/PokemonGo-Bot/pull/3593
Cygwin is not supported with setup.sh, but you can use bash on Windows instead.

**Comment by stradazz12** [comment]
but windows not sup command "make" some error msg not support bla''....
how can i use the command "make"?

**Comment by simonsmh** [comment]
@stradazz12 Try visual studio to build one? I don't know.

**Comment by stradazz12** [comment]
--2016-08-13 16:23:29--  http://pgoapi.com/pgoencrypt.tar.gz
Resolving pgoapi.com... 104.31.68.172, 104.31.69.172, 2400:cb00:2048:1::681f:45ac, ...
Connecting to pgoapi.com|104.31.68.172|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 243633 (238K) [application/x-tar]
Saving to: `pgoencrypt.tar.gz'

     0K .......... .......... .......... .......... .......... 21%  395K 0s
    50K .......... .......... .......... .......... .......... 42%  433K 0s
   100K .......... .......... .......... .......... .......... 63%  659K 0s
   150K .......... .......... .......... .......... .......... 84% 1.02M 0s
   200K .......... .......... .......... .......              100% 73.2K=0.9s

2016-08-13 16:23:30 (269 KB/s) - `pgoencrypt.tar.gz' saved [243633/243633]

g++    -c -o encrypt.o encrypt.c
<builtin>: recipe for target 'encrypt.o' failed
process_begin: CreateProcess(NULL, g++ -c -o encrypt.o encrypt.c, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [encrypt.o] Error 2
mv: cannot stat 'libencrypt.so': No such file or directory

@simonsmh

**Comment by simonsmh** [comment]
http://superuser.com/questions/154418/where-do-i-get-make-for-cygwin
