### ISSUE TITLE
Docker build doesn't include worker type UpdateLiveStats

### ISSUE THREAD

**Issue by Suppachart** [PokemonGoF/PokemonGo-Bot#3797]
The docker build images doesn't find a task type UpdateLiveStats. Hence, when docker run it fail because it can not find that type from get_worker_by_name

Snippet:
    def _get_worker_by_name(self, name):
        try:
            worker = getattr(cell_workers, name)
        except AttributeError:
            raise ConfigException('No worker named {} defined'.format(name))

file tree_config_builder.py

**Comment by k4n30** [comment]
Please use the issue template properly
