### ISSUE TITLE
Can't catch pokemon and spin pokespots with same command arguments

### ISSUE THREAD

**Issue by aconite33** [PokemonGoF/PokemonGo-Bot#38]
#67 is a similar issue
If you use -c <number> and -s, seems to only stop at pokespots and does not try to capture pokemon. Maybe because it's teleporting around too much to see pokemon appear?

**Comment by Janhouse** [comment]
Noticed the same thing. If this gets fixed then #39 would be less of a problem.

**Comment by aconite33** [comment]
Also noticed they are soft banning because of the teleporting around too fast. Getting alot of "may search too often, lets have a rest", and not getting any item rewards from the spin.

**Comment by aconite33** [comment]
Added a sleep(15) once it finds a pokespot. That seems to avoid the softban and you can keep spinning pokestops and getting items. Still not catching pokemon though.

**Comment by smith-and-web** [comment]
Increased sleeps as well, pokestops are working wonderfully but still no pokemon.

**Comment by julienkessels** [comment]
where do i add the sleep command pls?

**Comment by julienkessels** [comment]
may search too often, lets have a rest
need a rest 


allllll the time

**Comment by aconite33** [comment]
@julienkessels Search in working.py for "need a rest", you can can time.sleep(X) where X is the number of seconds you want to stop.
