### ISSUE TITLE
Nickname Pokemon IVs in hex (0..F)

### ISSUE THREAD

**Issue by MrCarlosJr** [PokemonGoF/PokemonGo-Bot#3803]
I think its good ideal option to usage hexadecimal in names usage less caracters and easy read in cellphone.
Other Ideal is usage others chars to separate like F.E.D F:E:D F|E|D F~E~D

**Comment by admk** [comment]
Perhaps this can be easily achieved in config.json with ``{!x}''?

**Comment by metaember** [comment]
Wrote about this a couple days ago : #3350

**Comment by kanemasa1987** [comment]
yeah, but the nickname class is calling lower()...

**Comment by MrCarlosJr** [comment]
I try this form:
in **_nickname_pokemon.py_**
```python
...
# IV values in Hex like: 4C9
iv_adshex=''+format(iv_attack, 'X')+format(iv_defense, 'X')+format(iv_stamina, 'X'),
...
```
