### ISSUE TITLE
How to add "send pokemon away after catching"?

### ISSUE THREAD

**Issue by MinaTheLoli** [PokemonGoF/PokemonGo-Bot#3804]
i want to know if there is any option to be able to send the catched pokemon away (cause my bag gets full)

P.S.: about the bans, actual i got that problem only while running more than 1 bot on the same ip (my friend had runned also a bot but on my connection so we got a ip ban but just me is fine)

**Comment by anziclone** [comment]
Please read the documentation on releasing pokemon and modify your config file accordingly.
