### ISSUE TITLE
%1 is not a valid Win32 application

### ISSUE THREAD

**Issue by htugsdr** [PokemonGoF/PokemonGo-Bot#3810]
I heard about people having this issue before but it never really applied to me as i was on mac. But now i am trying to get it on windows and i have this....
### Expected Behavior
To start botting and do normal stuff.

### Actual Behavior
`WindowsError: [Error 193] %1 is not a valid Win32 application`

### Your config.json (remove your credentials and any other private info)
` "auth_service": "google",
    "username": "x",
    "password": "x",
    "location": "x",
    "gmapkey": "GOOGLE_MAPS_API_KEY",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 10 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 10 },
            "Hyper Potion":   { "keep" : 20 },
            "Revive":         { "keep" : 15 },
            "Razz Berry":     { "keep" : 30 },
            "Greatball":      { "keep" : 50 },
            "Ultraball":      { "keep" : 50}
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": false,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowCluster",
           "config": {
               "radius": 2200,
               "lured": true
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 200
    },
    "websocket_server": false,
    "walk": 80,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
     "any": {"release_below_cp": 100, "release_below_iv": 0.2, "logic": "or"},
      "Rattata": {"keep_best_cp": 2},
      "Zubat": {"keep_best_cp": 2},
      "Ekans": {"keep_best_cp": 2},
      "Caterpie": {"keep_best_cp": 2},
      "Weedle": {"keep_best_cp": 2},
      "Pidgey": {"keep_best_cp": 2},
      "Spearow": {"keep_best_cp": 2},
      "Clefairy": {"keep_best_cp": 2},
      "Oddish": {"keep_best_cp": 2},
      "Paras": {"keep_best_cp": 2},
      "Bellsprout": {"keep_best_cp": 2},
      "Sandshrew": {"always_release": true},
      "Nidoran F": {"keep_best_cp": 2},
      "Nidoran M": {"keep_best_cp": 2},
      "Venonat": {"keep_best_cp": 2},
      "Meowth": {"keep_best_cp": 2},
      "Psyduck": {"keep_best_cp": 2},
      "Mankey": {"keep_best_cp": 2},
      "Growlithe": {"keep_best_cp": 3},
      "Machop": {"keep_best_cp": 2},
      "Geodude": {"keep_best_cp": 2},
      "Doduo": {"keep_best_cp": 2},
      "Cubone": {"keep_best_cp": 2},
      "Rhyhorn": {"keep_best_cp": 2},
      "Pinsir": {"keep_best_cp": 2},
      "Eevee": {"keep_best_cp": 2},
      "Goldeen": {"keep_best_cp": 2},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}
`
your config here
```

### Steps to Reproduce
Fresh install on windows 7  32bit
i have to bot on mac and it works fine im just getting used to windows 

### Other Information
OS: windows 7 32bit
Branch: dev
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by k4n30** [comment]
Have you followed the [installation guide](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/installation.md)? If you have, can you provide your cmd window output and not just the error message

Please also edit your OP to include git and python versions

**Comment by htugsdr** [comment]
all good its solved just got a different encrypt.dll file

**Comment by bilalkamoon** [comment]
@htugsdr where did you find the dll for win 32 bit? I couldn't find it anywhere

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot#pokemongo-bot - 3rd Paragraph
