### ISSUE TITLE
MoveToMapPokemon doesn't work as expected 

### ISSUE THREAD

**Issue by supana** [PokemonGoF/PokemonGo-Bot#3816]
I'm having a problem with MoveToMapPokemon. It seems only MoveToFort is working.

This is what happening
<img width="807" alt="screen shot 2016-08-13 at 04 07 15" src="https://cloud.githubusercontent.com/assets/21002458/17641141/ecc322ba-610b-11e6-897c-a1d3391e1967.png">

Here's my code. 
`{
	"auth_service": "google",
	"username": "",
	"password": "",
	"location": "",
	"gmapkey": "",
	"encrypt_location": "",
	"tasks": [{
		"type": "HandleSoftBan"
	}, {
		"type": "SleepSchedule",
		"config": {
			"enabled": false,
			"time": "22:54",
			"duration": "7:46",
			"time_random_offset": "00:24",
			"duration_random_offset": "00:43"
		}
	}, {
		"type": "CollectLevelUpReward"
	}, {
		"type": "IncubateEggs",
		"config": {
			"longer_eggs_first": true
		}
	}, {
		"type": "UpdateLiveStats",
		"config": {
			"enabled": false,
			"min_interval": 10,
			"stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
			"terminal_log": true,
			"terminal_title": true
		}
	}, {
		"type": "TransferPokemon"
	}, {
		"type": "NicknamePokemon",
		"config": {
			"enabled": true,
			"nickname_template": "{iv_pct}_{iv_ads}"
		}
	}, {
		"type": "EvolvePokemon",
		"config": {
			"evolve_all": "none",
			"first_evolve_by": "cp",
			"evolve_above_cp": 500,
			"evolve_above_iv": 0.8,
			"logic": "or",
			"evolve_speed": 20,
			"use_lucky_egg": false
		}
	}, {
		"type": "RecycleItems",
		"config": {
			"min_empty_space": 15,
			"item_filter": {
				"Pokeball": {
					"keep": 0
				},
				"Greatball": {
					"keep": 70
				},
				"Ultraball": {
					"keep": 200
				},
				"Potion": {
					"keep": 0
				},
				"Super Potion": {
					"keep": 0
				},
				"Hyper Potion": {
					"keep": 30
				},
				"Revive": {
					"keep": 20
				},
				"Razz Berry": {
					"keep": 50
				}
			}
		}
	}, {
		"type": "CatchVisiblePokemon"
	}, {
		"type": "CatchLuredPokemon"
	}, {
		"type": "SpinFort"
	}, {
		"type": "MoveToMapPokemon",
		"config": {
			"address": "http://localhost:5000",
			"max_distance": 500,
			"min_time": 30,
			"min_ball": 50,
			"prioritize_vips": true,
			"snipe": false,
			"snipe_high_prio_only": true,
			"snipe_high_prio_threshold": 600,
			"update_map": true,
			"mode": "priority",
			"map_path": "raw_data",
			"catch": {
				"==========Legendaries==========": 0,
				"Aerodactyl": 1000,
				"Snorlax": 1000,
				"Articuno": 1000,
				"Zapdos": 1000,
				"Moltres": 1000,
				"Dratini": 1000,
				"Dragonair": 1000,
				"Dragonite": 1000,
				"Mewtwo": 1000,
				"Mew": 1000,

				"==========Region Locked==========": 0,
				"Farfetch'd": 1000,
				"Kangaskhan": 1000,
				"Mr. Mime": 1000,
				"Tauros": 1000,

				"==========Very Rare==========": 0,
				"Lapras": 900,
				"Electabuzz": 400,
				"Magmar": 900,
				"Ditto": 900,

				"==========Starters==========": 0,
				"Bulbasaur": 600,
				"Ivysaur": 600,
				"Venusaur": 1000,

				"Charmander": 600,
				"Charmeleon": 600,
				"Charizard": 1000,

				"Squirtle": 600,
				"Wartortle": 600,
				"Blastoise": 1000,

				"Pikachu": 600,
				"Raichu": 1000,

				"==========Semi Rare==========": 0,
				"Porygon": 600,
				"Scyther": 600,
				"Jynx": 200,

				"==========Uncommon==========": 0,

				"Omanyte": 400,
				"Omastar": 500,

				"Seel": 400,
				"Dewgong": 500,

				"Grimer": 300,
				"Muk": 500,

				"Shellder": 200,
				"Cloyster": 400,

				"Gastly": 250,
				"Haunter": 250,
				"Gengar": 1000,

				"Onix": 500,

				"Drowzee": 100,

				"Hypno": 200,

				"Vulpix": 500,
				"Ninetales": 600,

				"Paras": 300,
				"Parasect": 400,

				"Growlithe": 500,
				"Arcanine": 700,

				"Tentacool": 200,
				"Tentacruel": 200,

				"Mankey": 300,
				"Primeape": 500,

				"Clefairy": 300,
				"Clefable": 500,

				"Jigglypuff": 300,
				"Wigglytuff": 500,

				"Venonat": 300,
				"Venomoth": 600,

				"Diglett": 400,
				"Dugtrio": 600,

				"Meowth": 400,
				"Persian": 500,

				"Psyduck": 150,
				"Golduck": 400,

				"Geodude": 300,
				"Graveler": 500,
				"Golem": 800,

				"Eevee": 500,
				"Vaporeon": 800,
				"Jolteon": 800,
				"Flareon": 800,

				"Kabuto": 500,
				"Kabutops": 600,

				"Magikarp": 300,
				"Gyarados": 800,

				"Pinsir": 500,

				"Ponyta": 500,
				"Rapidash": 600,

				"Slowpoke": 200,
				"Slowbro": 450,

				"Magnemite": 250,
				"Magneton": 500,

				"Krabby": 100,
				"Kingler": 450,

				"Voltorb": 300,
				"Electrode": 500,

				"Exeggcute": 400,
				"Exeggcutor": 500,

				"Cubone": 500,
				"Marowak": 800,

				"Hitmonlee": 600,

				"Hitmonchan": 600,

				"Lickitung": 500,

				"Koffing": 200,
				"Weezing": 500,

				"Rhyhorn": 400,
				"Rhydon": 500,

				"Chansey": 800,

				"Tangela": 500,

				"Horsea": 200,
				"Seadra": 300,

				"Goldeen": 150,
				"Seaking": 300,

				"Staryu": 200,
				"Starmie": 300,

				"==========T1 Evolvers==========": 0,
				"Caterpie": 10,
				"Metapod": 10,
				"Butterfree": 400,

				"Weedle": 10,
				"Kakuna": 10,
				"Beedrill": 400,

				"Pidgey": 10,
				"Pidgeotto": 10,
				"Pidgeot": 300,

				"==========T2 Evolvers==========": 0,
				"Nidoran F": 300,
				"Nidorina": 300,
				"Nidoqueen": 500,

				"Nidoran M": 300,
				"Nidorino": 300,
				"Nidoking": 500,

				"Oddish": 300,
				"Gloom": 500,
				"Vileplume": 600,

				"Poliwag": 300,
				"Poliwhirl": 400,
				"Poliwrath": 800,

				"Abra": 400,
				"Kadabra": 600,
				"Alakazam": 800,

				"Machop": 400,
				"Machoke": 400,
				"Machamp": 800,

				"Bellsprout": 300,
				"Weepinbell": 400,
				"Victreebel": 800,

				"==========Trash==========": 0,

				"Rattata": 10,
				"Raticate": 10,

				"Spearow": 10,
				"Fearow": 10,

				"Ekans": 200,
				"Arbok": 300,

				"Sandshrew": 300,
				"Sandslash": 400,

				"Zubat": 10,
				"Golbat": 10,

				"Doduo": 300,
				"Dodrio": 400
			}
		}
	}, {
		"type": "MoveToFort"
	}, {
		"type": "FollowSpiral"
	}],
	"map_object_cache_time": 5,
	"forts": {
		"avoid_circles": true,
		"max_circle_size": 50
	},
	"websocket_server": false,
	"walk": 7.24,
	"action_wait_min": 1,
	"action_wait_max": 4,
	"debug": false,
	"test": false,
	"health_record": true,
	"location_cache": true,
	"distance_unit": "km",
	"reconnecting_timeout": 15,
	"catch_randomize_reticle_factor": 1.0,
	"catch_randomize_spin_factor": 1.0,
	"min_ultraball_to_keep": 10,
	"logging_color": true,
	"catch": {
		"any": {
			"catch_above_cp": 0,
			"catch_above_iv": 0,
			"logic": "or"
		},

		"// Pokemons with example": {
			"always_catch": true
		},
		"// Gets filtered with release parameters": {},

		"// Legendary pokemons (Goes under S-Tier)": {},
		"Lapras": {
			"always_catch": true
		},
		"Moltres": {
			"always_catch": true
		},
		"Zapdos": {
			"always_catch": true
		},
		"Articuno": {
			"always_catch": true
		},

		"// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
		"Mewtwo": {
			"always_catch": true
		},
		"Dragonite": {
			"always_catch": true
		},
		"Snorlax": {
			"always_catch": true
		},
		"// Mew evolves to Mewtwo": {},
		"Mew": {
			"always_catch": true
		},
		"Arcanine": {
			"always_catch": true
		},
		"Vaporeon": {
			"always_catch": true
		},
		"Gyarados": {
			"always_catch": true
		},
		"Exeggutor": {
			"always_catch": true
		},
		"Muk": {
			"always_catch": true
		},
		"Weezing": {
			"always_catch": true
		},
		"Flareon": {
			"always_catch": true
		},

		"// Growlithe evolves to Arcanine": {},
		"Growlithe": {
			"always_catch": true
		},
		"// Dragonair evolves to Dragonite": {},
		"Dragonair": {
			"always_catch": true
		},
		"// Grimer evolves to Muk": {},
		"Grimer": {
			"always_catch": true
		},

		"// Magikarp evolves to Gyarados": {},
		"Magikarp": {
			"always_catch": true
		},
		"// Exeggcute evolves to Exeggutor": {},
		"Exeggcute": {
			"always_catch": true
		},
		"// Eevee evolves to many versions, like Vaporeon, Flareon": {},
		"Eevee": {
			"always_catch": true
		},

		"// A-Tier pokemons": {},
		"Slowbro": {
			"always_catch": true
		},
		"Victreebel": {
			"always_catch": true
		},
		"Machamp": {
			"always_catch": true
		},
		"Poliwrath": {
			"always_catch": true
		},
		"Clefable": {
			"always_catch": true
		},
		"Nidoking": {
			"always_catch": true
		},
		"Venusaur": {
			"always_catch": true
		},
		"Charizard": {
			"always_catch": true
		},
		"Golduck": {
			"always_catch": true
		},
		"Nidoqueen": {
			"always_catch": true
		},
		"Vileplume": {
			"always_catch": true
		},
		"Blastoise": {
			"always_catch": true
		},
		"Omastar": {
			"always_catch": true
		},
		"Aerodactyl": {
			"always_catch": true
		},
		"Golem": {
			"always_catch": true
		},
		"Wigglytuff": {
			"always_catch": true
		},
		"Dewgong": {
			"always_catch": true
		},
		"Ninetales": {
			"always_catch": true
		},
		"Magmar": {
			"always_catch": true
		},
		"Kabutops": {
			"always_catch": true
		},
		"Electabuzz": {
			"always_catch": true
		},
		"Starmie": {
			"always_catch": true
		},
		"Jolteon": {
			"always_catch": true
		},
		"Rapidash": {
			"always_catch": true
		},
		"Pinsir": {
			"always_catch": true
		},
		"Scyther": {
			"always_catch": true
		},
		"Tentacruel": {
			"always_catch": true
		},
		"Gengar": {
			"always_catch": true
		},
		"Hypno": {
			"always_catch": true
		},
		"Pidgeot": {
			"always_catch": true
		},
		"Rhydon": {
			"always_catch": true
		},
		"Seaking": {
			"always_catch": true
		},
		"Kangaskhan": {
			"always_catch": true
		}
	},
	"release": {
		"any": {
			"release_below_cp": 0,
			"release_below_iv": 0,
			"logic": "or"
		},
		"// Example of always releasing Rattata:": {},
		"// Rattata": {
			"always_release": true
		},
		"// Example of keeping 3 stronger (based on CP) Pidgey:": {},
		"// Pidgey": {
			"keep_best_cp": 3
		},
		"// Example of keeping 2 stronger (based on IV) Zubat:": {},
		"// Zubat": {
			"keep_best_iv": 2
		},
		"// Also, it is working with any": {},
		"any": {
			"keep_best_cp": 2,
			"keep_best_iv": 3
		},
		"Pidgey": {
			"keep_best_cp": 20
		},
		"Weedle": {
			"keep_best_cp": 10
		},
		"Caterpie": {
			"keep_best_cp": 10
		},
		"// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
		"// Zubat": {
			"keep_best_cp": 2,
			"keep_best_iv": 3
		}
	},
	"vips": {
		"Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
		"any": {
			"catch_above_cp": 1200,
			"catch_above_iv": 0.9,
			"logic": "or"
		},
		"Lapras": {},
		"Moltres": {},
		"Zapdos": {},
		"Articuno": {},

		"// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
		"Mewtwo": {},
		"Dragonite": {},
		"Snorlax": {},
		"// Mew evolves to Mewtwo": {},
		"Mew": {},
		"Arcanine": {},
		"Vaporeon": {},
		"Gyarados": {},
		"Exeggutor": {},
		"Muk": {},
		"Weezing": {},
		"Flareon": {}

	}
}`

**Comment by keugnu** [comment]
Can you provide evidence that you map scan is working?

**Comment by supana** [comment]
Here's for the map
<img width="713" alt="screen shot 2016-08-13 at 04 15 49" src="https://cloud.githubusercontent.com/assets/21002458/17641170/ba391ec0-610c-11e6-8305-a46855e81ef9.png">

**Comment by RedViper9** [comment]
Try removing the MoveToFort task from your config and see if MoveToMapPokemon works then.

**Comment by supana** [comment]
Actually I tried that. It stopped MoveToFort but it kept SpinFort. No MoveToMapPokemon anyway :(

**Comment by nDarkness** [comment]
Change min_ball to a lower number.

`"type": "MoveToMapPokemon",
				"config": {
					"address": "http://localhost:5000",
					"max_distance": 500,
					"min_time": 60,
					**"min_ball": 1**,
					"prioritize_vips": true,
					"snipe": true,
					"snipe_high_prio_only": true,
					"snipe_high_prio_threshold": 400,
					"update_map": true,
					"mode": "priority",
					"map_path": "raw_data",`

**Comment by keugnu** [comment]
@supana Test with `"update_map": false,`

**Comment by supana** [comment]
Works like a charm!!!! Cheers mate :)))

**Comment by supana** [comment]
@nDarkness Works like a charm!!! Cheers mate :)))
@keugnu Thx mate, though I hadn't tried that. The above suggestion does the trick :)))

**Comment by beanstalkk** [comment]
you guys aren't experiencing bans yet?

**Comment by agastimhatre** [comment]
why ban @beanstalkk

**Comment by fari-99** [comment]
@supana please close the issue if the problem solved. thanks. happy catch ; ).

**Comment by Chofoteddy** [comment]
@supana How set my conf.ini to change/update my current location at the same time PokemonGoBot?
