### ISSUE TITLE
How to create pull request?

### ISSUE THREAD

**Issue by leanhdaovn** [PokemonGoF/PokemonGo-Bot#3817]
Hi.

I used the bot and encountered some problems. I opened the code and fixed them. 

When I push the code, it says I don't have the permission.
How can I create a pull request for those fixes?

**Comment by Misterhex** [comment]
check out the docs?

https://help.github.com/articles/creating-a-pull-request/

**Comment by leanhdaovn** [comment]
@Misterhex thanks for your link but I'm stuck in the previous step when pushing a new branch to the repo

![push permission denied](https://s10.postimg.org/q46n93dc9/Screen_Shot_2016_08_13_at_10_35_26_AM.png)

**Comment by edysantosa** [comment]
You need to fork the repo first, create a branch for your commits, push to your forked repo, and then create pull request from that branch

**Comment by leanhdaovn** [comment]
Thanks @edysantosa. I'm able to create a PR already :)
