### ISSUE TITLE
Don't Catch - Out of pokeballs

### ISSUE THREAD

**Issue by gpires** [PokemonGoF/PokemonGo-Bot#382]
### Expected Behavior
Expected to catch I've poké balls and great ballls

### Actual Behavior

```
[#] Something rustles nearby!
[#] A Wild Growlithe appeared! [CP 473] [Potential 0.76]
[x] Out of pokeballs, switching to farming mode...
```

### Other Information
OS:  Win10
Git Commit: cb3d799b0c143ee0ad28aee9d50be7d4e13587c1

**Comment by LennertW** [comment]
This problem is caused by line 261, 264, 267  in /pokemongo_bot/__init__.py.
remove '.value' on each of those lines to fix it.
Item.ITEM_POKE_BALL.value   -->   Item.ITEM_POKE_BALL

**Comment by gpires** [comment]
@LennertW  the problem still persists

```
[#] PokeBalls: 0
[#] GreatBalls: 0
[#] UltraBalls: 0
```

**Comment by LennertW** [comment]
@gpires weird, seems to work for me (don't think I changed anything else): 

```
                if item['inventory_item_data']['item']['item_id'] == Item.ITEM_POKE_BALL:
                    print('Poke Ball count: ' + str(item['inventory_item_data']['item']['count']))
                    balls_stock[1] = item['inventory_item_data']['item']['count']
                if item['inventory_item_data']['item']['item_id'] == Item.ITEM_GREAT_BALL:
                    print('Great Ball count: ' + str(item['inventory_item_data']['item']['count']))
                    balls_stock[2] = item['inventory_item_data']['item']['count']
                if item['inventory_item_data']['item']['item_id'] == Item.ITEM_ULTRA_BALL:
                    print('Ultra Ball count: ' + str(item['inventory_item_data']['item']['count']))
                    balls_stock[3] = item['inventory_item_data']['item']['count']
```

```
[#] PokeBalls: 154
[#] GreatBalls: 0
[#] UltraBalls: 0
```

Make sure you saved changes.
Try adding print statements to check what values are checked:
print item['inventory_item_data']['item']['item_id']
print Item.ITEM_POKE_BALL

I changed a few (unrelated) things so my code is a mess, if its not fixed I will create a pull request later today.

**Comment by gpires** [comment]
@LennertW  That's what I have, Can't debug the code right now. But it must be a typo or something.

**Comment by surfaace** [comment]
please confirm if issue persists

**Comment by surfaace** [comment]
tracking in #801
