### ISSUE TITLE
auth broken in dev?

### ISSUE THREAD

**Issue by accident12123** [PokemonGoF/PokemonGo-Bot#3820]
I haven't tried to pinpoint which commit on 8/12 (eastern time, after noon) started this behavior but my ubuntu setup hasn't worked all afternoon.  ptc, google, app passwrod and not 2fa, nothing works on the dev branch.   everything is fine on master.

The error I see:

bot# ./run.sh 
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "/root/PokemonGo-Bot/src/pgoapi/pgoapi/utilities.py", line 30, in <module>
    import xxhash
ImportError: No module named xxhash
Sat Aug 13 00:14:56 EDT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

something is out of order where it's not logging in first, perhaps part of what appears to be changed for debian stuff?

**Comment by k4n30** [comment]
> ImportError: No module named xxhash

run `pip install -r requirements.txt --upgrade` after you have updated to the latest version

**Comment by simonsmh** [comment]
thx. fixed in https://github.com/PokemonGoF/PokemonGo-Bot/pull/3836
