### ISSUE TITLE
Need to update the documentation on config file

### ISSUE THREAD

**Issue by spoxus** [PokemonGoF/PokemonGo-Bot#3824]
The configure file has been added a lot of stuff.
Could someone update the documentation?

The logging option is really great, thanks!

**Comment by keugnu** [comment]
It is being done

**Comment by spoxus** [comment]
Thank you.

**Comment by fari-99** [comment]
close this issue if your problem solved.

note1 : btw you can see the configuration for config in `/[pokemon_bot_folder]/docs/configuration_files.md`

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md
