### ISSUE TITLE
evolve doesn't work

### ISSUE THREAD

**Issue by rishub** [PokemonGoF/PokemonGo-Bot#3825]
### Expected Behavior
Specified pokemon in config file evolve when bot starts

### Actual Behavior
It never evolves pokemon, even after they are caught

### Your config.json (remove your credentials and any other private info)
{
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "Pidgey,Caterpie,Weedle",
            "first_evolve_by": "cp",
            "evolve_above_cp": 0,
            "evolve_above_iv": 0,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
},

whole config file here: http://pastebin.com/qNTGLTuw

### Steps to Reproduce
I don't know what I'm doing wrong or how to reproduce this because it worked last night, and I don't remember changing much in the config file and it stopped working suddenly.

### Other Information
OS:
Branch: dev or master
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by keugnu** [comment]
Could you post a link to your entire config?

**Comment by rishub** [comment]
here it is: http://pastebin.com/qNTGLTuw
