### ISSUE TITLE
[Question] Documentation (MoveToMapPokemon)

### ISSUE THREAD

**Issue by supergithubo** [PokemonGoF/PokemonGo-Bot#3827]
What is the unit of `min_time` and `max_distance` set in the config? Thanks!

**Comment by fari-99** [comment]
min_time is minimum time for pokemon  to derespwan.
max_distance is max distanse the bot and the pokemon.

this is just my speculation btw. haha.

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md#options

**Comment by supergithubo** [comment]
Why you close the issue @k4n30? I'm asking for the UNIT?

**Comment by supergithubo** [comment]
The documentation does no clearly state the 'unit' (km or m for max_distance and sec, min or hours for the min_time) @fari-99  @k4n30

**Comment by fari-99** [comment]
min_time in second and max_distance is meter

**Comment by k4n30** [comment]
@supergithubo because the issue tracker is for ISSUES, not configuration help. You need to join the slack server for configuration help as per the README
