### ISSUE TITLE
Catch pokemons but miss throws

### ISSUE THREAD

**Issue by Tomygames** [PokemonGoF/PokemonGo-Bot#3830]
### Expected Behaviour
Catch pokemons but miss throws

### Actual Behaviour
Poke balls always lands on the pokemon and no poke balls are mist
That will bypass the catch flee ban

### Steps to Reproduce

Just use the bot x)

### Other Information
OS: OS X
Branch: dev
Git Commit: latest one
Python Version: Python 2.7.10

**Comment by k4n30** [comment]
@Tomygames does #2534 not meet your need?
