### ISSUE TITLE
Status of running bot

### ISSUE THREAD

**Issue by Laurin100** [PokemonGoF/PokemonGo-Bot#3832]
How can I terminate the running bot (like, to shut down my computer), such that the status is saved and I can continue after restarting the computer? Is there a keystroke to quit and save?

And what do I need to do to start it then using the previously saved status?
If this is not the right thread then please direct me where to pose.

**Comment by incmve** [comment]
I just press CTRL+C to stop the bot.
The last location file last-location-xxxx@gmail.com.json is saved in the /data folder it will pick it up next time it starts.

**Comment by Laurin100** [comment]
Thank you so much.

**Comment by Laurin100** [comment]
I Took a example config.json and typed in my datas and renamed it and the other. Now the bot is saying :Failure! Could not update trainer location PokemonGo-Map: http://localhost:5000. Is it running?

**Comment by tolinwei** [comment]
@Laurin100 Nah I don't think it's running... the location is at least a coordinate in a format like **(37.806468, -122.427803)**, you could find this one via Google Maps, and possibly it can accept other formats that I'm not aware of.

**Comment by k4n30** [comment]
Not a bot issue, please use the slack server for config help
