### ISSUE TITLE
Error when install in windows 10

### ISSUE THREAD

**Issue by fdxfdcfd** [PokemonGoF/PokemonGo-Bot#3837]
I got this when run` pip2 install -r requirements.txt`
```
 Using cached networkx-1.11-py2.py3-none-any.whl
Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@a2755eb42dfe49e359798d2f4defefc97fb8163d#egg=pgoapi (from -r requirements.txt (line 3))
  Error [Error 2] The system cannot find the file specified while executing command git config --get-regexp remote\..*\.url
Cannot find command 'git'
```
command: git still work

**Comment by fari-99** [comment]
@fdxfdcfd please use slack chat to get help for installation. don't use issue like this in here. thank you.
btw please install requirement app and follow install instruction. in [here](https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/installation.md)

cc @k4n30 to close this issue.
