### ISSUE TITLE
catch_randomize vs catch_throw_parameters

### ISSUE THREAD

**Issue by mmnsgo** [PokemonGoF/PokemonGo-Bot#3839]
can anyone explain how these params work?
```
    "catch_throw_parameters": {
        "excellent_rate": 0.1,
        "great_rate": 0.2,
        "nice_rate": 0.3,
        "normal_rate": 0.4,
        "spin_success_rate": 0.6
    }
```
 and 
```
    "catch_randomize_reticle_factor": 0.7,
    "catch_randomize_spin_factor": 0.9
```

thank you

**Comment by joaodragao** [comment]
These two are deprecated.
```
    "catch_randomize_reticle_factor": 0.7,
    "catch_randomize_spin_factor": 0.9
```

**Comment by mmnsgo** [comment]
@joaodragao thank you.

**Comment by maxprzemo** [comment]
sum 
`        "excellent_rate": 0.1,
        "great_rate": 0.2,
        "nice_rate": 0.3,
        "normal_rate": 0.4,`
must equal value 1?

**Comment by leadboots5** [comment]
```
"catch_randomize_reticle_factor": 0.7,
"catch_randomize_spin_factor": 0.9
```
These also don't work at all.

@maxprzemo I will say yes. it may not actually need to be(originally at least you could have any set of numbers and then the individual out of the total was the chance of it happening, but i think it was simplified to make it easier.)
