### ISSUE TITLE
Spotting 3 weeks spawned 

### ISSUE THREAD

**Issue by supana** [PokemonGoF/PokemonGo-Bot#3841]
I notice that now we have 3 week spawn pokemons, which is a little bit annoying cause no matter how many times we restart the bot, it will keep moving forward to these pokemons. 

Do we have "max_time" command for MoveToMapPokemon?

<img width="932" alt="screen shot 2016-08-13 at 12 50 59" src="https://cloud.githubusercontent.com/assets/21002458/17643007/a3f4e2e6-6154-11e6-94ab-44a8a6054df4.png">

**Comment by nis** [comment]
Ha! A bot-lure :D

**Comment by h3k1ru** [comment]
It's already fixed in PokemonGo-Map, also it will upgrade your database and remove those pokemons. 3 weeks pokemons are not exist naturally.

**Comment by supana** [comment]
@h3k1ru Thx :)
