### ISSUE TITLE
Banned Account Question

### ISSUE THREAD

**Issue by jayson0408** [PokemonGoF/PokemonGo-Bot#3842]
one of my account is now back catching pokemons normally.. 
I did not use it for 6hrs.. 
Does this mean the ban was lifted. 

2 other accounts.. Pokemon keeps on escaping..

**Comment by Arcasss** [comment]
What message did u have? I have 'Failed to get game data from the server' on mobile phone atm. Can't login since yesterday (+/- 12 hours now).
