### ISSUE TITLE
Feature Request - FeatHub Integration

### ISSUE THREAD

**Issue by k4n30** [PokemonGoF/PokemonGo-Bot#3843]
http://feathub.com/ to allow the separation of feature requests and issues. Allows voting to see what is more popular. Integrates with github too :)

**Comment by simonsmh** [comment]
cool

**Comment by MrKaralis** [comment]
Really interesting. The  hub for this project is not opened yet?

**Comment by k4n30** [comment]
@MrKaralis no not yet, I'm trying to gauge interest if we should use this or not

**Comment by BriceSD** [comment]
@k4n30 I love this idea. It’ll be easier to prioritize the work

**Comment by RedViper9** [comment]
Yes, please.

**Comment by k4n30** [comment]
Waiting on merge to include details in README.

Can start being used now if people would like - http://feathub.com/PokemonGoF/PokemonGo-Bot

Please keep feature requests to one feature at a time even though they may be linked. This allows for proper voting by other users who may see different features being wanted more than others

**Comment by k4n30** [comment]
Anyone want to volunteer to move feature requests over to the new system?

**Comment by accident12123** [comment]
A good way to weed out the people who no longer care about what they requested is to notify them to move it.   (and someone did that for the ones I opened today)

**Comment by jimmywarting** [comment]
I don't like the separation since you will now depend on another service.

Github has voting feature already and can be sorted on most up/down voted issues 
With github it's also easier to link stuff to relative issues, PR and code

**Comment by k4n30** [comment]
Where were you a day ago @jimmywarting ? I was like "What? no, it doesn't" but now I have found it :( Not sure whether it's worth reverting and making the doco clearer or continue the migration to Feathub.

For those still looking - https://github.com/PokemonGoF/PokemonGo-Bot/issues?q=is%3Aopen+is%3Aissue+sort%3Areactions-%2B1-desc

Thoughts? @accident12123 @RedViper9 @BriceSD @MrKaralis @simonsmh  @PokemonGoF/pokemongo-bot-community-support @PokemonGoF/admins

**Comment by jimmywarting** [comment]
Why did you make such a rush to change things then? At least have a decision with the community before making any big choices

**Comment by jimmywarting** [comment]
I did see this issue until mine was closed

**Comment by simonsmh** [comment]
It's great.
I thought I was in pr page but I was wrong. 
Is there any more colors about the tag?

**Comment by DiegoRBaquero** [comment]
I'd prefer keeping things on GitHub

**Comment by k4n30** [comment]
After discussing with other mods, we're going to revert from using feathub and just clean up how feature requests are done on github
