### ISSUE TITLE
Error starting bot

### ISSUE THREAD

**Issue by Dexter145** [PokemonGoF/PokemonGo-Bot#3855]
### Expected Behavior
Bot starting

### Actual Behavior
Error:
Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/root/PokemonGo-Bot/pokemongo_bot/__init__.py", line 29, in <module>
    from pokemongo_bot.socketio_server.runner import SocketIoRunner
  File "/root/PokemonGo-Bot/pokemongo_bot/socketio_server/runner.py", line 5, in <module>
    from eventlet import patcher, wsgi
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/patcher.py", line 4, in <module>
    from eventlet.support import six
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/support/__init__.py", line 4, in <module>
    from eventlet.support import greenlets, six
  File "/root/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/support/greenlets.py", line 3, in <module>
    import greenlet
ImportError: /root/PokemonGo-Bot/local/lib/python2.7/site-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object
Sat Aug 13 16:43:27 CEST 2016 Pokebot configs/config.json Stopped.
Press any button or wait 20 seconds to continue.

### Your config.json (remove your credentials and any other private info)
default, only login, gmap and location entered.

### Other Information
OS: Debian 7
Branch: dev and master, tried both
Git Commit: 1817d008db17c79447763c9708bb402526a5d338 / b21b1449156b730fc224ed238f5b8bba606fe0f9
Python Version: Python 2.7.3

**Comment by siembz** [comment]
I have the same problem

**Comment by nivong** [comment]
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. Are you running `master`? We work on the `dev` branch and then add that functionality to `master`. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.

**Comment by k4n30** [comment]
Doesn't look like you have run the setup correctly - https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/installation.md

**Comment by leftie1** [comment]
Issue with Python 2.7.3 on Debian/Ubuntu.
Try: 
`source bin/activate`
`pip freeze | grep "greenlet" | xargs pip uninstall -y`
`pip install greenlet==0.4.9`
`pip install -r requirements.txt`

**Comment by Dexter145** [comment]
Thank you @leftie1, bot works fine now.
