### ISSUE TITLE
Disabling/enabling other tasks at runtime

### ISSUE THREAD

**Issue by net8q** [PokemonGoF/PokemonGo-Bot#3858]
I'm developping a somewhat sizable plugin (thanks to the new plugin config) mainly for fun and learning python.

### Problem :
I'd like to use a navigator in one of my tasks, and fallback on a known one (Spiral or whatever) if conditions are not met, but I think it's quite ugly, and users should be able to use the config file to setup their own fallback navigator.

### Feature :

* Add for each task an optional "name" field from config, with default value the task class name
* Add a function to get the task instance with given name from the bot
* Add a function to enable/disable running this task during runtime (as opposed to editing config to set enabled to true or false and relaunching bot)

"Manager" tasks could then be written to switch the tasks around based on conditions : 
* Having several FollowPath tasks being switched  according to time (at day around your workplace, at night around your home)
* Having FollowSpiral take cleanly over MoveToFort when bag is full
etc.

### Other Information
OS: Linux
Branch: dev
Git Commit:  git merge-base HEAD origin/dev : d4200e9b
Python Version: Python 2.7.10

**Comment by k4n30** [comment]
Is this an issue you want help with? or just letting everyone know?

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by net8q** [comment]
Mainly asking for opinions and general interest before doing anything. Moved to feathub

**Comment by k4n30** [comment]
Feathub may be turned off in favour of better GitHub tags, issue templates, and voting structures. Please feel free to continue using this issue (but don't delete the Feathub request just yet)

**Comment by k4n30** [comment]
@mjmadsen y the close?

**Comment by mjmadsen** [comment]
There should be an enable/disable option on all options now. #4603

**Comment by k4n30** [comment]
Agree, but don't think that meets the entirety of the FR

**Comment by mjmadsen** [comment]
Alright. Reopening. My bad.

**Comment by mjmadsen** [comment]
@net8q Can we get a todo list of what has or has not been done in this? Between the title and the description, there is a wide variance. I keep looking at in the issues list thinking "oh, we did that".
