### ISSUE TITLE
Pokemon vanish but pokestops spin fine

### ISSUE THREAD

**Issue by rishub** [PokemonGoF/PokemonGo-Bot#3862]
### Expected Behavior
Pokemon can be caught

### Actual Behavior
Pokemon are vainishing

### Steps to Reproduce
Not sure, I didn't jump locations I just let the bot run. and suddenly it started saying all the pokemon are vanishing

I'm guessing its a softban but how come the pokestops work then?

**Comment by keugnu** [comment]
Temporarily suspended account. It may take several hours for this to go away. I'd advise you to stop the bot on that account if you haven't already.

**Comment by TCB13** [comment]
This has been discussed here: https://github.com/PokemonGoF/PokemonGo-Bot/issues/3700

**Comment by TCB13** [comment]
@keugnu any details on that "temporary suspension"?

**Comment by keugnu** [comment]
First hand experience with this problem. Pokemon ALWAYS vanish after first throw. It is similar to not seeing pokestops/lures/gyms on map in that it goes away after a while (I waited 10 hours). Possibly related to API request throttling.

**Comment by BriceSD** [comment]
Duplicated
