### ISSUE TITLE
Run.sh install error

### ISSUE THREAD

**Issue by iBinh** [PokemonGoF/PokemonGo-Bot#3864]
### Expected Behavior

pip install -r requirements.txt
### Actual Behavior
pip install -r requirements.txt
Collecting numpy==1.11.0 (from -r requirements.txt (line 1))
  Using cached numpy-1.11.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): networkx==1.11 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2))
Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@a2755eb42dfe49e359798d2f4defefc97fb8163d#egg=pgoapi (from -r requirements.txt (line 3))
  Skipping because already up-to-date.
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 4))
Collecting protobuf==3.0.0b4 (from -r requirements.txt (line 5))
  Using cached protobuf-3.0.0b4-py2.py3-none-any.whl
Collecting requests==2.10.0 (from -r requirements.txt (line 6))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 8))
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 9))
Collecting googlemaps==2.4.4 (from -r requirements.txt (line 10))
  Using cached googlemaps-2.4.4-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): colorama==0.3.7 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): enum34==1.1.6 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 12))
Collecting pyyaml==3.11 (from -r requirements.txt (line 13))
Collecting haversine==0.4.5 (from -r requirements.txt (line 14))
Collecting polyline==1.3.1 (from -r requirements.txt (line 15))
  Using cached polyline-1.3.1-py2.py3-none-any.whl
Collecting python-socketio==1.4.2 (from -r requirements.txt (line 16))
Collecting flask==0.11.1 (from -r requirements.txt (line 17))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): socketIO_client==0.7.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): eventlet==0.19.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): gpxpy==1.1.1 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 20))
Collecting mock==2.0.0 (from -r requirements.txt (line 21))
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting timeout-decorator==0.3.2 (from -r requirements.txt (line 22))
Collecting raven==5.23.0 (from -r requirements.txt (line 23))
  Using cached raven-5.23.0-py2.py3-none-any.whl
Collecting demjson==2.2.4 (from -r requirements.txt (line 24))
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.4.0 in /Library/Python/2.7/site-packages (from networkx==1.11->-r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): six in /Library/Python/2.7/site-packages (from pgoapi->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): xxhash in /Library/Python/2.7/site-packages (from pgoapi->-r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf==3.0.0b4->-r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): future in /Library/Python/2.7/site-packages (from s2sphere==0.2.4->-r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in /Library/Python/2.7/site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 8))
Collecting python-engineio>=0.8.0 (from python-socketio==1.4.2->-r requirements.txt (line 16))
Collecting itsdangerous>=0.21 (from flask==0.11.1->-r requirements.txt (line 17))
Collecting Werkzeug>=0.7 (from flask==0.11.1->-r requirements.txt (line 17))
  Using cached Werkzeug-0.11.10-py2.py3-none-any.whl
Collecting Jinja2>=2.4 (from flask==0.11.1->-r requirements.txt (line 17))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting click>=2.0 (from flask==0.11.1->-r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): websocket-client in /Library/Python/2.7/site-packages (from socketIO_client==0.7.0->-r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.3 in /Library/Python/2.7/site-packages (from eventlet==0.19.0->-r requirements.txt (line 19))
Collecting funcsigs>=1; python_version < "3.3" (from mock==2.0.0->-r requirements.txt (line 21))
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock==2.0.0->-r requirements.txt (line 21))
  Using cached pbr-1.10.0-py2.py3-none-any.whl
Collecting contextlib2 (from raven==5.23.0->-r requirements.txt (line 23))
  Using cached contextlib2-0.5.4-py2.py3-none-any.whl
Collecting MarkupSafe (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 17))
Installing collected packages: numpy, protobuf, requests, pgoapi, protobuf-to-dict, googlemaps, pyyaml, haversine, polyline, python-engineio, python-socketio, itsdangerous, Werkzeug, MarkupSafe, Jinja2, click, flask, funcsigs, pbr, mock, timeout-decorator, contextlib2, raven, demjson
  Found existing installation: numpy 1.8.0rc1
    DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.8.0rc1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/7g/35drymp16jb5jlm12m5vlxw80000gn/T/pip-tNiCAa-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy-1.8.0rc1-py2.7.egg-info'

### Other Information
OS: mac sierra 10.12
Branch:  master
Git Commit: b21b1449156b730fc224ed238f5b8bba606fe0f9
Python Version: 2.7.10

**Comment by BriceSD** [comment]
@iBinh Try ```pip2 install -r requirements.txt``` instead and let me know

**Comment by leftie1** [comment]
`virtualenv .`
`source bin/activate`
`pip2 install -r requirements.txt`

**Comment by simonsmh** [comment]
Found existing installation: numpy 1.8.0rc1
DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.

Already fixed.
run pip install -r requirements.txt --upgrade
or setup -u or git pull dev and then try again.
