### ISSUE TITLE
DLL load failed: %1 is not a valid Win32 Application

### ISSUE THREAD

**Issue by jdkuki** [PokemonGoF/PokemonGo-Bot#3875]
My stack trace mirrors: #2996

I followed the steps on the wiki to install. 
Then I built the .so from the wget command + source.
Moved the resulting.so to PokemonGo-Bot/encrypt_64.dll (Running 64 Win10)
Got the following error:

```
Traceback (most recent call last):
  File "./pokecli.py", line 39, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "c:\users\jakob\projects\pokemongo-bot\src\pgoapi\pgoapi\__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "c:\users\jakob\projects\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "c:\users\jakob\projects\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "c:\users\jakob\projects\pokemongo-bot\src\pgoapi\pgoapi\utilities.py", line 30, in <module>
    import xxhash
ImportError: DLL load failed: %1 is not a valid Win32 application.

```

Then followed the dummies [guide](https://github.com/PokemonGoF/PokemonGo-Bot/issues/2875) and grabbed the shared encrypt_64.dll from slack and installed it to PokemonGo-Bot/encrypt_64.dll

Same stack trace. 

To debug, modified my __init__.py to include:

```
@@ -685,11 +685,14 @@ class PokemonGoBot(object):
         full_path = path + '/'+ file_name
         if not os.path.isfile(full_path):
             self.logger.error(file_name + ' is not found! Please place it in the bots root directory or set encrypt_location in config.')
+           print("found");
             self.logger.info('Platform: '+ _platform + ' Encrypt.so directory: '+ path)
             sys.exit(1)
         else:
             self.logger.info('Found '+ file_name +'! Platform: ' + _platform + ' Encrypt.so directory: ' + path)
+           print("not found");

+        input("here")
         return full_path

     def _setup_api(self):
```

After adding statements, stack trace is the same. It looks like the exception is being thrown before it even looks for the encrypt so. Someone mentioned on slack it could be because of IP/Acc ban. Made new account and was able to login on same connect bot is failing on.

pip install xxhash returns "Requirement already satisifed". 

Using config.json.example with my ptc login/location.

### Other Information
OS: Win 10 64
Branch: dev
Git Commit: 9b72ee50f26df288001a0cac90b1387129410d82
Python Version: 2.7.11

**Comment by Y4kuzi** [comment]
I had the same issue. Using encrypt.dll fixed it for me.

**Comment by k4n30** [comment]
#2736 #2804 #2856 #3810 #3834
