### ISSUE TITLE
Help, don't know what went wrong!?

### ISSUE THREAD

**Issue by IThinkALot** [PokemonGoF/PokemonGo-Bot#3881]
Hey guys, so I'm all up to this part on my mac, and i run it but i get the following... 
Please help me!

This is my config file: 
{
    "auth_service": "google",
    "username": “xxxxxxxxxx”,
    "password": “xxxxxxxxxxx”,
    "location": "34.0091295,-118.4992379",
    "gmapkey": "xxxxxxxxxxxxxxxxxxx",
    "libencrypt_location": "",
    "tasks": [
      {

And this is the error I'm getting:
jesselees-MBP:PokemonGo-Bot Jesse-Lee$ docker run --name=pokego-bot1 --rm -it -v$(pwd)/configs/config-account1.json:/usr/src/app/configs/config.json pokemongo-bot
2016-08-13 21:34:36,453 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-13 21:34:36,456 [       cli] [INFO] No config argument specified, checking for /configs/config.json
/usr/src/app/pokemongo_bot/../configs/config.json:3:16: Error: Can not decode value starting with character u'\u201c'
   |  At line 3, column 16, offset 48
/usr/src/app/pokemongo_bot/../configs/config.json:3:44: Info: Recovering parsing after character u','
   |  At line 3, column 44, offset 76
/usr/src/app/pokemongo_bot/../configs/config.json:4:16: Error: Can not decode value starting with character u'\u201c'
   |  At line 4, column 16, offset 94
/usr/src/app/pokemongo_bot/../configs/config.json:4:30: Info: Recovering parsing after character u','
   |  At line 4, column 30, offset 108
/usr/src/app/pokemongo_bot/../configs/config.json: has errors
2016-08-13 21:34:36,741 [       cli] [CRITICAL] Error with configuration file
jesselees-MBP:PokemonGo-Bot Jesse-Lee$ 

Please HELP! I'm so lost...

Edit by mod : removed account info

**Comment by canpoyrazoglu** [comment]
```
"username": “testusername1995@gmail.com”,
"password": “PlayStation4”,

```
On your username and password (and please change your password immediately if it's the real one) You've used smart quotes which changes regular " sign to “. Please Replace “ with " (they look VERY similar but not the same) and save the file, and then try again.

**Comment by IThinkALot** [comment]
thank you, it was a dummy account to try this on, i will try it once I'm back! hopefully it works!

**Comment by k4n30** [comment]
The issue template has a step for checking your configuration file, which is what the error is indicating is the problem. Closing issue
