### ISSUE TITLE
[theory] other way do solve softban?

### ISSUE THREAD

**Issue by jimmywarting** [PokemonGoF/PokemonGo-Bot#3882]
I'm not sure you have experience the same thing when you travel to far and don't see anything on the map. The solution is to send 40-50 spin request otherwise. 
But since you don't see any pokestop could you then instead send 40-50 request where you change clothes? Then you don't have to find another pokestop to fix the softban

Do you think this could work?

**Comment by k4n30** [comment]
Any credible source to back this theory up?

**Comment by DevManny** [comment]
I saw it in a video (language is Spanish): https://youtu.be/-JFUm0Ws--I?t=1m39s

**Comment by jimmywarting** [comment]
Nope, i just thought about it 

And that video just shows how to spin pokestops not change clothes.

**Comment by k4n30** [comment]
If you can find a credible source, I'd say go ahead and create a feature request on our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

Going to close this issue as it's not an issue with the bot

**Comment by k4n30** [comment]
Feathub may be turned off in favour of better GitHub tags, issue templates, and voting structures. Please feel free to continue using this issue (but don't delete the Feathub request just yet)

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by mjmadsen** [comment]
Has anyone confirmed this? Might require an API update, but we should probably map all requests and responses to prepare for future server restrictions.
