### ISSUE TITLE
Issue in Windows

### ISSUE THREAD

**Issue by felipecaldas** [PokemonGoF/PokemonGo-Bot#3885]
Hi all,

So I followed every step of the Windows install and this is the output of the pip install requirements.txt 

....

Requirement already satisfied (use --upgrade to upgrade): pbr>=0.11 in c:\tools\python27\lib\site-packages (from mock==2.0.0->-r requirements.txt (line 21))
Requirement already satisfied (use --upgrade to upgrade): contextlib2 in c:\tools\python27\lib\site-packages (from raven==5.23.0->-r requirements.txt (line 23))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in c:\tools\python27\lib\site-packages (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 17))
Installing collected packages: pgoapi
  Running setup.py develop for pgoapi
Successfully installed pgoapi-1.1.6

When I run the run.bat, thats what I get:

> run
Running pokecli.py for count: 0
The system cannot find the path specified.
Running pokecli.py for count: 1
The system cannot find the path specified.

Just keeps looping...  Any idea?

**Comment by k4n30** [comment]
Please use the[ slack server](https://pokemongo-bot.herokuapp.com/) for support issues
