### ISSUE TITLE
Request: Variable Walk Speed (Humanize)

### ISSUE THREAD

**Issue by accident12123** [PokemonGoF/PokemonGo-Bot#3886]
I feel really dialed in except I'm constantly moving the same speed and that's just not humanish.

Thoughts on where I'd like to vary the speeds:
- wandering between forts
- bored and finding yet another common pokemon
- moving to a lured fort
- running after something not in my pokedex (should also ignore catching anything that I already have) while on the move to it.
- sprinting after a vip (should also ignore catching anything that comes up less than vip) while on the move to it.

If the "going after what I don't have" could also get some list of pokemon I'm hunting to get candy to evolve setting that would be brilliant as well.

Any run/sprint should also have a larger stop before engaging something.

There is also some times I'd like to see it not walk anywhere.
- take a break after a run or sprint 
- if in distance to 4+ forts with lures, rest x minutes and let them come to you.

These are probably better as feature requests on their own but to mention it as they are slightly related in case I'm wrong in this thought
- sit down between multiple lured pokestops for up to x minutes (or when lured drop below some threshold like 2), this should have some type of variable like only do it twice ever x minutes at most.  Aka stop moving for awhile and take a break in a spot pokemon come to you
- related: pokemongo-map added just spawn locations to their data so in event of no lured pokestops to chill, maybe a similar 2+ lure spots in range to just sit and relax.

**Comment by avexus** [comment]
maybe specify a rang of walking speed too. like from [0..10]
in config file.
and a random rest

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by accident12123** [comment]
moved as requested.

http://feathub.com/PokemonGoF/PokemonGo-Bot/+6

**Comment by k4n30** [comment]
Feathub may be turned off in favour of better GitHub tags, issue templates, and voting structures. Please feel free to continue using this issue (but don't delete the Feathub request just yet)

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by k4n30** [comment]
In latest version
