### ISSUE TITLE
request: MoveToMapPokemon dual mode

### ISSUE THREAD

**Issue by accident12123** [PokemonGoF/PokemonGo-Bot#3888]
I think a good humanize setting would be to do a dual mode where you only go after priority pokemon if they are below a certain disappear time threshold.     

For those that haven't found their honey hole small area yet, there will probably need to be some options like minimum priority if nearby pokemon still exist before it'll change also.    

examples in how I'd hope it would work.
- stay nearby capturing pokemon unless something has less than 6 minutes left in my priority list and then go get that one.
- stay nearby capturing pokemon until I run out and then start to go after priority ones and start the nearby process over if they are setup as 300 or less.
- break out of nearby when something 600 or more appears nearby but still use the time left to decide.
- don't immediately head towards new spawned pokemon until they have say 13-14 minutes left on the clock..    give it a moment to discover they are there for human like behavior.

what is considered nearby distance should be a separate config option for dual mode so you can define what stay nearby really means but not stop going after further away pokemon.

**Comment by avexus** [comment]
how do you know how much time left?

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by accident12123** [comment]
@avexus I moved it to the feature hub as requested so maybe better to ask there but the movetopokemon gets when a pokemon will disappear from pokemongo-map.

**Comment by accident12123** [comment]
moved as requested  http://feathub.com/PokemonGoF/PokemonGo-Bot/+3

**Comment by k4n30** [comment]
Feathub may be turned off in favour of better GitHub tags, issue templates, and voting structures. Please feel free to continue using this issue (but don't delete the Feathub request just yet)

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by k4n30** [comment]
@accident12123 Are these still valid as well?
