### ISSUE TITLE
request: Transferpokemon delay

### ISSUE THREAD

**Issue by accident12123** [PokemonGoF/PokemonGo-Bot#3889]
I've tried to dial in evolves before a transfer happens but i've still witnessed some transfers that stole getting something evolved for more XP first.  It's also not very human like in the speed that it happens.

1: Don't transfer if an evolve has happened within x seconds, default to about 1 minute
2: don't follow evolve setting if there is no pokebag room for more evolves to happen.

**Comment by k4n30** [comment]
1. is already done - https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/configs/config.json.example#L109
I'll place an enhancement tag for the other 2 points

**Comment by k4n30** [comment]
@accident12123 Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by accident12123** [comment]
Moved as requested

http://feathub.com/PokemonGoF/PokemonGo-Bot/+4

**Comment by k4n30** [comment]
Feathub may be turned off in favour of better GitHub tags, issue templates, and voting structures. Please feel free to continue using this issue (but don't delete the Feathub request just yet)

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by k4n30** [comment]
@accident12123 I've updated this FR and removed irrelevant comments / completed requests.  I realised 2. doesn't make sense to me.  Evolves don't need extra pokebag room it takes the existing Pokemon -> evolves -> places it back in the bag, no extra space is taken. Can you clarify this feature

Also, you may get better traction having your requests completed if you separate them into 2 separate FRs as they can be independently worked on
