### ISSUE TITLE
Ban Hammer is hitting hard!

### ISSUE THREAD

**Issue by jring314** [PokemonGoF/PokemonGo-Bot#3892]
Just got banned on 2 accts, I think. Be careful with walking speeds and duration of running the bot.
### Other Information
OS:
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by Trico3** [comment]
Mind sharing what your config looked like on the accounts that got banned? (Hide credentials)

**Comment by ponytails** [comment]
what is your account level ??

did u open your BOT on your legit home . and open the bot again on fake town/gps ?

**Comment by sky-mashiro** [comment]
I don't think we are clear about how the ban rule works right now, I just got softbanned on one account which ran for 3 hours, gained 10w XP, with sleep schedule. Yet the other one has run for 7hours, without any sleep schedule, gained 20W XP, still working fine, I am totally confused about it now

**Comment by jring314** [comment]
My account lvl was 26 at time of ban. I only ever opened the bot in the location that it was set to. Walking speed was probably too high at 10.16. I ran the bot overnight sometimes 10-12 hours, if it didn't crash beforehand. I think I had encountered some soft-bans before this week, in that I couldn't spin Stops sometimes or pokemon escaped after 1 toss.
