### ISSUE TITLE
Proposition : Break Schedule

### ISSUE THREAD

**Issue by supercourgette** [PokemonGoF/PokemonGo-Bot#3894]
Hi, I think it will improve the human behavior of the bot if it was able to take break from time to time. Based on the comments of the SleepSchedule, I would like to propose the following task:

    """Pauses the execution of the bot for some time

    Simulates the user taking a break for some time, based on human behavior 
    (eating, shopping, ...), the break time and the duration is changed 
    by a random offset defined in the config file.

    Example Config:
    {
        "type": "BreakSchedule",
        "config": {
          "interval_type": "fixed","fixed","interval"
          "time": "12:00","19:30", "03:00"
          "duration":"00:45","00:45","00:02"
          "time_random_offset": "00:15","00:15","00:01"
          "duration_random_offset": "00:05","00:05","00:01"
          "label":"lunch", "dinner", "bathroom"
          "logout":true,true,true
        }
    }
    interval_type: (fixed | interval) the break is either fixed in time or is fired
                        at a given interval
                        for this example a break start everyday at 12:00, 19:30 and every 03:00 hours      
    time: (HH:MM) local time that the bot should take a break
    duration: (HH:MM) the duration of the break
    time_random_offset: (HH:MM) random offset of time that the break will start
                        for this example the possible start time of the #1 break is 11:30-12:30
    duration_random_offset: (HH:MM) random offset of duration of the break
                        for this example the possible duration of the #1 break is 5:00-6:00
    logout: the bot logout at the start of the break, and login at the end of the break
    """

Eventually, I can do it (it would be best if the one who develop the SleepSchedule could do it though). Note that the logout option is just an idea, I'm not sure how to implement it.

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by supercourgette** [comment]
Done. I had to duplicate since I didn't find how to move it.

**Comment by k4n30** [comment]
Feathub may be turned off in favour of better GitHub tags, issue templates, and voting structures. Please feel free to continue using this issue (but don't delete the Feathub request just yet)

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by accident12123** [comment]
To add my comments from feathub since it looks like this is going to be the place again..

1; it's easy to add multiple break tasks, it should work with just 1 time and then anyone can config it as they need/want.

2: I would like to use this with other otions to really add in some humanizing breaks:   levels achieved, earned XP, KMs walked, eggs hatched, forts spun, pokemon caught I would config.

**Comment by supercourgette** [comment]
Just for discussion sake,

I m note sure about both of your points:
1/ Having one task for every break will be a bit redundant to configure. Gathering them all together under one task would be easier to configure for the user.
2/ The break task is different from the break option you propose (which would be great to have too). The break task is a task in itself, independent from other tasks. It is a break simulating a real life break (to go to the toilet for example), not a pause between in-game actions.

**Comment by mjmadsen** [comment]
Implemented with the random_pause task
