### ISSUE TITLE
Request: Option to catch Pokemon at a slower rate

### ISSUE THREAD

**Issue by Dcstegg228** [PokemonGoF/PokemonGo-Bot#3899]
### Expected Behavior
The bot would catch Pokemon at a human like rate to avoid being banned, possibly a 15 second delay between catches.

### Actual Behavior
The bot catches Pokemon faster than humanly possible.

### Steps to Reproduce
Run the bot with standard configuration.

### Other Information
OS: Windows 10
Git Commit: ? 
Python Version: 2.7

**Comment by avexus** [comment]
dont catch every pokemon you encounter.

**Comment by SGColdSun** [comment]
Simply put a few quantifiers in what you attempt to catch, such as an iv above .3 or so will cut down on how many pokemon you attempt to catch.

**Comment by accident12123** [comment]
i agree with this, as far as humanizing there would be longer between catches if there is multiple next to each other if you were in the app.   Same with the animation if it's new to get into the pokedex.

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
Feathub may be turned off in favour of better GitHub tags, issue templates, and voting structures. Please feel free to continue using this issue (but don't delete the Feathub request just yet)

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by alexyaoyang** [comment]
This is fixed with #3872
