### ISSUE TITLE
Trying to catch pokemons without pokeballs in inventory

### ISSUE THREAD

**Issue by Janhouse** [PokemonGoF/PokemonGo-Bot#39]
Seems like bot tries to catch pokemons even without any pokeballs in inventory.

When this happens, "CATCH_POKEMON" structure is empty (no status) and bot tries to keep going. For now I locally added sys.exit(0) when this happens but it should probably start collecting pokeballs for some time instead.

Sadly it doesn't automatically switch to pokestop spinning mode. When running in spinning mode it doesn't catch any pokemons.

**Comment by necrozis** [comment]
#12 Working on this right now)

**Comment by s1x** [comment]
This should be fixed now.
