### ISSUE TITLE
Bot fails to recognize the new type of softban

### ISSUE THREAD

**Issue by sky-mashiro** [PokemonGoF/PokemonGo-Bot#3902]
I found sth interesting, I am soft banned today(Can spin fort, but pokemon vanished after first toss), but only for less than an hour, maybe even shorter(I didn't try during that time), compared to yesterday, which lasted for more than 10 hours, it might have sth to do with the bot keeps running even it can't catch any pokemons, because last time I was letting the bot running all night, while this time I terminate the bot right after I found it was banned, the bot keeps running even it can't catch any pokemon is obvious not a human behavior, can we fix that? Maybe log out and re-login after an hour or so

### Expected Behavior
Bot is able to recognize the new ban, and logout/terminate, re-login after a customize time period

### Actual Behavior
The bot failed to recognize the new type of ban, and keeps running even can't catch any pokemon, which might extend the softban time.

**Comment by sky-mashiro** [comment]
I think I am pretty sure that the soft ban time is related to bot's behavior now, I just got banned again, but only for like 10 minutes, I terminate the bot after 5 pokemons vanished in a row

**Comment by mjmadsen** [comment]
We're working on this. Decent amount of the current work is avoiding the softban altogether, but hopefully we can get some PRs in to detect the variety of new bans.

**Comment by jokoast** [comment]
2016-08-14 10:31:54,484 [PokemonGoBot] [INFO] [api_error] Session stale, re-logging in.

is part of their new technics to get bots down right ? One each quarter of hour.

**Comment by TLuigi003** [comment]
I have a different ban type, bot is able to spin the fort, although It doesn't receive any items
Pokemon catch is working

**Comment by TLuigi003** [comment]
Forget about what I've said, It seems a inventory-related bug

**Comment by mjmadsen** [comment]
Should be detected now. Please reopen if you notice it is not.
