### ISSUE TITLE
DeviceId

### ISSUE THREAD

**Issue by fsimchen** [PokemonGoF/PokemonGo-Bot#3904]
"DevicePackageName": "galaxy-tab3",
  "DeviceId": "6795dfd237a8edaa",
  "AndroidBoardName": "smdk4x12",
  "AndroidBootloader": "T310UEUCOI1",
  "DeviceBrand": "samsung",
  "DeviceModel": "SM-T310",
  "DeviceModelIdentifier": "lt01wifiue",
  "DeviceModelBoot": "qcom",
  "HardwareManufacturer": "samsung",
  "HardwareModel": "SM-T310",
  "FirmwareBrand": "lt01wifiue",
  "FirmwareTags": "release-keys",
  "FirmwareType": "user",
  "FirmwareFingerprint": "samsung/lt01wifiue/lt01wifi:4.4.2/KOT49H/T310UEUCOI1:user/release-keys"

**Comment by k4n30** [comment]
?
