### ISSUE TITLE
Enhancement suggestion: Resume Path upon login

### ISSUE THREAD

**Issue by jring314** [PokemonGoF/PokemonGo-Bot#3908]
So I started using the path config and really like what it does. But when I resume the path after logging out for a bit, the guy wants to move directly back to the 1st location in the path list. It would be awesome if he could resume the path where he was currently located from. Maybe some form of interpolation or a report out to the "last-location" data file?

My biggest issue with the behavior as-is: Sometimes the path to get back to point 1 from a resume is across a large body of water or otherwise an unnatural, non-human path.

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
Feathub may be turned off in favour of better github tags, issue templates and voting structures. Please feel free to continue using this issue (but don't delete the Feathub request just yet)

**Comment by AcorpBG** [comment]
We have this feature already https://github.com/PokemonGoF/PokemonGo-Bot/commit/c8aaf4b82ca2733897a1a32dac203e23ca605a8d#diff-dd17d1c321697ec0d97a6b6f39b9c831
      {
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_file": "poke.gpx",
          "path_start_mode": "closest"
        }
      }
