### ISSUE TITLE
Path coordinate, no random

### ISSUE THREAD

**Issue by supercourgette** [PokemonGoF/PokemonGo-Bot#3909]
When using the FollowPath task, the bot goes exactly over the coordinates points defined in the path config file. Maybe it is the indented behavior, but in such a case, could we have the possibility to decide if we want to have a little bit of random displacement above those points?

### Expected Behavior

If the bot passes above a coordinates defined in the path config file, there should be a little bit of random in its displacement.

### Actual Behavior

The bot passes EXACTLY above those point, every time.

![capture](https://cloud.githubusercontent.com/assets/4060529/17647548/d44cb7bc-622f-11e6-992a-ca3f3652b7d4.PNG)

### Your config.json (remove your credentials and any other private info)

Part of my config

      {
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_start_mode": "first",
          "path_file": "configs/path_test.json"
        }
      }

The path file

```
[
	{"location": "35.408692, 139.595838"},
	{"location": "35.408640, 139.596106"},
	{"location": "35.409630, 139.596161"},
	{"location": "35.410486, 139.596138"},
	{"location": "35.410090, 139.595673"},
	{"location": "35.409169, 139.594980"},
	{"location": "35.408735, 139.594644"},
	{"location": "35.409057, 139.593690"},
	{"location": "35.408735, 139.594644"},
	{"location": "35.406922, 139.594217"},
	{"location": "35.407166, 139.595777"},
	{"location": "35.408605, 139.596055"},
	{"location": "35.408605, 139.596055"},
	{"location": "35.408605, 139.596055"},
	{"location": "35.408605, 139.596055"},
	{"location": "35.408896, 139.595787"}
]
```

### Steps to Reproduce

Just run it as usual, with the task FollowPath as defined above.

### Other Information

OS:Windows10
Git Commit: cdd1d532448446cb73e7b6b8a6deee13d29d8388 (dev branch)
Python Version: Python 2.7.11 (32b)

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by mjmadsen** [comment]
The noise added should improve this. If it does not add the degree of variance you would like, please reopen.
