### ISSUE TITLE
Problems with lucky eggs and evolving

### ISSUE THREAD

**Issue by accident12123** [PokemonGoF/PokemonGo-Bot#3911]
I've noticed several quirks with lucky eggs and evolving:

1. It will place a lucky egg in even if it doesn't have anything to evolve.
2. It cannot detect that a lucky egg is in use already (*see below*) 
3. It cannot detect that a lucky egg is in use when you start the bot.

More on 2:

I use 3 different evolvepokemon tasks to get the desired behavior for pokemon that are useless but good for evolve XP vs the better pokemon I want to have a little more control over when to evolve them.     The problem is if I have more than 1 set for lucky egg, only the one that placed the egg knows it's in use and the others "Skipping evolve because has no lucky egg." because it was my last egg.

**Comment by k4n30** [comment]
#3404 You can't both win :p

**Comment by Anakin5** [comment]
@accident12123 
Explain what you want to do with your transfer/evolution and we might  be able to suggest a working configuration

**Comment by k4n30** [comment]
@accident12123 ?

**Comment by mjmadsen** [comment]
Haven't heard anything in 5 days. Closing.
