### ISSUE TITLE
Log not showing softban fix

### ISSUE THREAD

**Issue by icecubeice** [PokemonGoF/PokemonGo-Bot#3919]
### Expected Behavior
log shows if softban is fixed

### Actual Behavior
[Edit] when fixing softban it shows nothing, after it says probably got softban it then goes to the same pokestop then voila! softban is gone

### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by Faithu** [comment]
You need to get to a pokestop for it to unban.

**Comment by icecubeice** [comment]
@Faithu I looked through some commits and now it fixes but no log that says softban is fixed, but the proof is that I can spin already compared to before

**Comment by fari-99** [comment]
hmm, please change the title to "log after softban fix not appear" or close this issue, because the softban is fixed.

**Comment by k4n30** [comment]
@icecubeice I'm assuming you don't have any logs to indicate the issue you were experiencing?

**Comment by icecubeice** [comment]
@k4n30 rn nothing, I'm describing it though, I mean after changing the softban python file through some commit it was fixed but it just doesn't show that it's fixed

**Comment by k4n30** [comment]
@icecubeice - I had a look and handle_soft_ban.py hasn't changed for 3 days and even then it wasn't a big change, so there haven't been major changes for nearly 2 weeks.  As I don't know what commit you were on before and what commit you're on now, it's hard to call this a bug, especially without any logs.

The other thing to take into account is the newer soft ban methods which aren't fully understood when the recent ban waves hit. Your soft ban could have been one of these which happened to have resolved itself around the time the problem went away

The soft ban file "looks" to be correct so I'm going to close this issue as there are too many unknowns. Feel free to come back and reopen it if you come across the issue again.
