### ISSUE TITLE
[Feature Request] Anti softban / Daily Limits

### ISSUE THREAD

**Issue by oleerik** [PokemonGoF/PokemonGo-Bot#3922]
From a post on the pokemongodev subreddit:
Pokestop ban:
- Occurs when you search roughly 2k pokestops in a 23 hour timespan.

Pokemon ban:
- Occurs when you catch 1k pokemon in a 23 hour timespan.

Are there any included anti-measures (take a long pause/quit when getting close to the limits, for instance) or would it be easy to include?

EDIT: Source: https://www.reddit.com/r/pokemongodev/comments/4xkqmq/new_ban_types_and_their_causes/

Other things that could be limited daily

EXP per 24 hours (or user defined)
km walked per 24 hours (or user defined)

**Comment by k4n30** [comment]
No there isn't currently, but you could create a feature request/s on our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

It would be helpful to include credible sources for the information if possible

**Comment by oleerik** [comment]
Thank you. Added a feature request there and added as credible of a source as I could find @k4n30.

**Comment by k4n30** [comment]
Feathub may be turned off in favour of better github tags, issue templates and voting structures. Please feel free to continue using this issue (but don't delete the Feathub request just yet)

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by MasterCATZ** [comment]
Defiantly need this 

would be great if we can pick a ranges for bot to randomise between 
in both quantity and time 

ie 500 - 999 Pokemon 24 - 36 hrs

**Comment by icecubeice** [comment]
Good place to start is lower your walk speed :)

**Comment by oleerik** [comment]
@icecubeice Yeah, that helps reaching the limits slower but it doesn't actually stop them for kicking in (unless you reduce it to a point where you are basically standing still). It would be much better with a proper solution built-in.

**Comment by Gurzeh** [comment]
@mjmadsen @k4n30 still no new parameter relative to that feature, right? Only daily_catch_limit?

**Comment by k4n30** [comment]
Not that I'm aware of, someone was asking for feedback on how to implement it though. Can't find the link right now

**Comment by Gurzeh** [comment]
@k4n30 ok, when I'm done with xp_per_level, I will check how  daily_catch_limit is implemented, should be similar.
