### ISSUE TITLE
Not recycling items

### ISSUE THREAD

**Issue by rayan111** [PokemonGoF/PokemonGo-Bot#3924]
### Expected Behavior

Recylce items

### Actual Behavior

Not recycling

### config.json

{
    "auth_service": "XXX",
    "username": "XXX",
    "password": "XXX",
    "location": "XXX",
    "gmapkey": "XXX",
    "tasks": [
        {"type": "HandleSoftBan"},
        {"type": "CollectLevelUpReward"},
        {
            "type": "IncubateEggs",
            "config": {
                "longer_eggs_first": true
            }
        },
        {
            "type": "RecycleItems",
            "min_empty_space": 10,
            "config": {
                "item_filter": {
                    "Pokeball":       { "keep" : 50 },
                    "Greatball":      { "keep" : 100 },
                    "Ultraball":      { "keep" : 50 },
                    "Potion":         { "keep" : 0 },
                    "Super Potion":   { "keep" : 0 },
                    "Hyper Potion":   { "keep" : 0 },
                    "Revive":         { "keep" : 0 },
                    "Max Potion" :    { "keep" : 50},
                    "Max Revive":     { "keep" : 50 },
                    "Razz Berry":     { "keep" : 50 }
                }
            }
        },
        {
            "type": "EvolvePokemon",
            "config": {
                "evolve_all": "Bulbasaur,Charmander,Squirtle,Caterpie,Weedle,Pidgey,Rattata,Spearow,Ekans,Pikachu,Sandshrew,Nidoran F, Nidoran M,Clefable,Vulpix,Jigglypuff,Zubat,Oddish,Paras,Venonat,Diglett,Meowth,Poliwag,Abra,Tentacool,Geodude,Ponyta,Slowpoke,Magnemite,Doduo,Seel,Gastly,Drowzee,Krabby,Voltorb,Cubone,Koffing,Rhyhorn,Horsea,Staryu,Omanyte,Kabuto",
                "first_evolve_by": "iv",
                "evolve_above_cp": 0,
                "evolve_above_iv": 0,
                "logic": "and",
                "evolve_speed": 1,
                "use_lucky_egg": false
            }
        },
        {
            "type" : "NicknamePokemon",
            "config" : {
                "nickname_template": "{name:.8s}-{iv_pct}",
                "dont_nickname_favorite": true
            }
        },
        {"type": "TransferPokemon"},
        {
            "type": "MoveToMapPokemon",
            "config": {
                "address": "http://localhost:5000",
                "mode": "priority",
                "prioritize_vips": true,
                "min_time": 15,
                "max_distance": 1,
                "snipe": true,
                "min_ball": 30,
                "snipe_high_prio_only": true,
                "snipe_high_prio_threshold": 1,
                "update_map": false,
                "catch": {
                    "Mewtwo":      990,
                    "Mew":         980,
                    "Moltres":     970,
                    "Zapdos":      960,
                    "Articuno":    950,

                    "Snorlax":     940,
                    "Lapras":      930,
                    "Dragonite":   920,
                    "Dragonair":   910,
                    "Dratini":     900,

                    "Vaporeon":    890,
                    "Eevee":       885,
                    "Arcanine":    880,
                    "Growlithe":   875,
                    "Exeggutor":   870,
                    "Exeggcute":   865,
                    "Gyarados":    860,
                    "Magikarp":    855,
                    "Muk":         850,
                    "Grimer":      845,

                    "Machamp":     790,
                    "Machop":      797,
                    "Machoke":     785,
                    "Victreebel":  780,
                    "Weepinbell":  787,
                    "Bellsprout":  775,
                    "Cloyster":    770,
                    "Shellder":    765,
                    "Golduck":     750,
                    "Psyduck":     745,

                    "Chansey":     100
                }
            }
        },
        {"type": "CatchVisiblePokemon"}, 
        {"type": "CatchLuredPokemon"},
        {"type": "SpinFort"},
        {
            "type": "MoveToFort",
            "config": {
                "lure_attraction": true,
                "lure_max_distance": 2000
            }
        },
        {
            "type": "FollowSpiral",
                "config": {
                "diameter": 5,
                "step_size": 100
            }
        }
    ],
    "map_object_cache_time": 5,
    "forts": {
        "avoid_circles": true,
        "max_circle_size": 100,
        "cache_recent_forts": true
    },
    "min_ultraball_to_keep": 10,
    "catch_throw_parameters": {
        "excellent_rate": 0.11,
        "great_rate": 0.55,
        "nice_rate": 0.25,
        "normal_rate": 0.09,
        "spin_success_rate" : 0.67
    },
    "websocket_server": true,
    "walk": 14.16,
    "action_wait_min": 0,
    "action_wait_max": 1,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {"any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"}},
    "release": {
        "//100 / 97.7 / 95.5 / 93.3 /  91.1 / 88.8 / 86.6 / 84.4 / 82.2 / 80.0 / 77.7 / 75.5 / 73.3 / 71.1": {},
        "any": {"release_below_cp": 0, "release_below_iv": 0.99, "logic": "or"},

        "Snorlax":     {"never_release": true},
        "Lapras":      {"never_release": true},
        "Dragonite":   {"never_release": true},
        "Dragonair":   {"keep_best_iv": 3},
        "Dratini":     {"keep_best_iv": 3},

        "Vaporeon":    {"never_release": true},
        "Eevee":       {"keep_best_iv": 3},
        "Arcanine":    {"never_release": true},
        "Growlithe":   {"keep_best_iv": 3},
        "Exeggutor":   {"never_release": true},
        "Exeggcute":   {"keep_best_iv": 3},
        "Gyarados":    {"never_release": true},
        "Magikarp":    {"keep_best_iv": 3},
        "Muk":         {"never_release": true},
        "Grimer":      {"keep_best_iv": 3},

        "Machamp":     {"never_release": true},
        "Machoke":     {"keep_best_iv": 3},
        "Machop":      {"keep_best_iv": 3},
        "Victreebel":  {"never_release": true},
        "Weepinbell":  {"keep_best_iv": 3},
        "Bellsprout":  {"keep_best_iv": 3},
        "Cloyster":    {"never_release": true},
        "Shellder":    {"keep_best_iv": 3},
        "Golduck":     {"release_below_iv": 0.77},
        "Psyduck":     {"release_below_iv": 0.77},

        "Mew":         {"never_release": true},
        "Mewtwo":      {"never_release": true},
        "Articuno":    {"never_release": true},
        "Zapdos":      {"never_release": true},
        "Moltres":     {"never_release": true},
        "Chansey":     {"keep_best_iv": 3},

        "Caterpie":    {"always_release": true},
        "Metapod":     {"always_release": true},
        "Butterfree":  {"always_release": true},
        "Weedle":      {"always_release": true},
        "Kakuna":      {"always_release": true},
        "Beedrill":    {"always_release": true},
        "Pidgey":      {"always_release": true},
        "Pidgeotto":   {"always_release": true},
        "Pidgeot":     {"always_release": true},
        "Rattata":     {"always_release": true},
        "Raticate":    {"always_release": true},
        "Spearow":     {"always_release": true},
        "Fearow":      {"always_release": true},
        "Ekans":       {"always_release": true},
        "Arbok":       {"always_release": true},
        "Sandshrew":   {"always_release": true},
        "Sandslash":   {"always_release": true},
        "Vulpix":      {"always_release": true},
        "Ninetails":   {"always_release": true},
        "Zubat":       {"always_release": true},
        "Golbat":      {"always_release": true},
        "Paras":       {"always_release": true},
        "Parasect":    {"always_release": true},
        "Venonat":     {"always_release": true},
        "Venomoth":    {"always_release": true},
        "Diglett":     {"always_release": true},
        "Dugtrio":     {"always_release": true},
        "Meowth":      {"always_release": true},
        "Persian":     {"always_release": true},
        "Mankey":      {"always_release": true},
        "Primeape":    {"always_release": true},
        "Ponyta":      {"always_release": true},
        "Rapidash":    {"always_release": true},
        "Doduo":       {"always_release": true},
        "Dodrio":      {"always_release": true},
        "Drowzee":     {"always_release": true},
        "Hypno":       {"always_release": true},
        "Krabby":      {"always_release": true},
        "Kingler":     {"always_release": true},
        "Goldeen":     {"always_release": true},
        "Seaking":     {"always_release": true}
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 0, "catch_above_iv": 0.99, "logic": "and" },
        "Mewtwo":       {},
        "Mew":          {},
        "Moltres":      {},
        "Zapdos":       {},
        "Articuno":     {},
        "Snorlax":      {},
        "Lapras":       {},
        "Dragonite":    {},
        "Dragonair":    {},
        "Dratini":      {},
        "Vaporeon":     {},
        "Arcanine":     {},
        "Exeggutor":    {},
        "Gyarados":     {},
        "Muk":          {},
        "Grimer":       {},
        "Machamp":      {},
        "Victreebel":   {},
        "Cloyster":     {}
    }
}

### Steps to Reproduce

Run bot with above config.

### Other Information
OS: Windows 10, running in a bash shell or whatever (using console2)
Git Commit: 5c9cdb53e69b5069cee6fe100d39e3cf5d63539c
Python Version: Python 2.7.10

**Comment by supergithubo** [comment]
I think it will going to recycle items when 'min_empty_space' was reached unlike recycling everytime on previous versions.

**Comment by rayan111** [comment]
increased min_empty_space to force recycling, still not working

**Comment by neogan86** [comment]
Same issue for me too. I don't have min_empty_space configured.

**Comment by BriceSD** [comment]
If you set ```min_empty_space``` to your inventory size (350 if you didn’t buy an upgrade), it’ll recycle every tick.
