### ISSUE TITLE
Pokemon transfer

### ISSUE THREAD

**Issue by Pietr** [PokemonGoF/PokemonGo-Bot#3940]
Hi!
I have a question. How to set to automatically transfer Pokemon? So that left a 2 best Pokemon of each species and some species do not transfer.

The next question is... Is it possible to set automatic evolution?

Thank you for your help.
Regards.

**Comment by avexus** [comment]
I also want to know if I want to transfer pokemons on start up, how to set up this:
{ "type": "TransferPokemon" },

**Comment by DiegoRBaquero** [comment]
See https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/configuration_files.md and https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/configs/config.json.example

Focus on the `EvolvePokemon` task and `release` config

**Comment by Pietr** [comment]
Thanks!
Whoever knows how to separate one species to transfer? Because there is no sense to write out all of them excluding one.

**Comment by DiegoRBaquero** [comment]
@Pietr it has many examples on how to do it:

`````
"release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
`````

**Comment by guibr321** [comment]
Transfering pokemon is not working for me :(

**Comment by Pietr** [comment]
Yes.
But ... I want to transfer all the Pokemon with the except Eevee.

**Comment by DiegoRBaquero** [comment]
@Pietr so... you do this:

This will transfer **ALL** pokemons except Eevees

`````
"release": {
      "any": {"release_below_cp": 4000, "release_below_iv": 1, "logic": "or"},
      "Eevee": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
````
