### ISSUE TITLE
[META] Share the wealth - configs

### ISSUE THREAD

**Issue by jrjhealey** [PokemonGoF/PokemonGo-Bot#3952]
I saw some old issue threads that were sharing people's configs and the XP they were generating per hour in given locations. I'd like to resurrect that and see what configs people are running now (especially since the patches and the ban-wave, if you've managed to stay off the radar).

If you're willing to share, I suggest people past their configs at pastebin, and add some perma-links below along with their stats. Also if you have found any location co-ordinates that are particularly decent for certain rare pokemon share the wealth!

(Obviously remove your private details as usual)

**Comment by k4n30** [comment]
Wouldnt this be better suited to the [configs channel in Slack](https://pokemongo-bot.slack.com/messages/configs/) @jrjhealey

**Comment by jrjhealey** [comment]
I find slack is too transient. Once you have too many comments it stops archiving them too.

I know this isn't the ideal place for this but I couldn't think of a better option (open to suggestions)?

**Comment by raffomania** [comment]
How about a gist?

**Comment by k4n30** [comment]
Ahhhh the limitations of slack, how I despise thee. Explains why a lot of dev groups moved away from Slack and towards Discord. Maybe we should look at migrating now that the community is a log bigger than it used to be.  At least then we could have one central place for all pokemongodev stuff (pokemongodev, pokemongo-map, silph road, /r/pokemondev are all on there already) and you don't have the limitations like Slack does (and it's free :p)

**Comment by jrjhealey** [comment]
I think this was mentioned in the mods channel last week some time, but it was decided that the community is way too large to be migrated smoothly ( @TheSavior ?)

A gist might not be a bad idea, I'd forgotten about those. Or perhaps we should look in to reddit or something (but with the age-old trade off of requiring yet another platform.) It's a real shame github doesn't have a forum kind of functionality.

**Comment by k4n30** [comment]
Yeah, it wouldn't be smooth, there'd have to be a migration period but sometimes you have to make a hard choice. I might make a feature request, but not be so quick to jump on executing it this time (aka the Feathub fail, lol)

We have the wiki on Github, but I don't know how you'd police it and keep it clean

**Comment by jrjhealey** [comment]
What was decided with the wiki now all the docs are separate? Is the wiki basically free to be used for something different all together?

**Comment by jrjhealey** [comment]
@brantje is looking for some example configs as well so if you're happy to have yours used I would tag him in the post too.

We're after examples ranging from fairly minimal working examples to fully fledged XP miners.

**Comment by k4n30** [comment]
@jrjhealey can we close this?

**Comment by jrjhealey** [comment]
Guess so! Didn't quite catch on did it! Haha
