### ISSUE TITLE
Add support for FreeBSD - encrypt.so file path detection

### ISSUE THREAD

**Issue by Zapskii** [PokemonGoF/PokemonGo-Bot#3953]
Hi,
Is there any chance FreeBSD support can be added for encrypt.so file detection?

In `pokemongo_bot/__init__.py`

replace:
`if _platform == "linux" or _platform == "linux2" or _platform == "darwin":`

with:
`if _platform == "linux" or _platform == "linux2" or _platform == "darwin" or _platform == "freebsd10":`

Thanks

**Comment by BriceSD** [comment]
@Zapskii you could make a PR :)

**Comment by keugnu** [comment]
I would love FreeBSD support
