### ISSUE TITLE
Varying Random Ball Throw

### ISSUE THREAD

**Issue by telboon** [PokemonGoF/PokemonGo-Bot#3955]
### Expected Behavior
Experience per Pokemon caught to be different due to random ball throw

### Actual Behavior
Every 'standard' Pokemon caught gave me 210 xp

Default JSon

### Steps to Reproduce
It reproduces every time 

### Other Information
OS:
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by jimmywarting** [comment]
This is already in the dev branch called `catch_throw_parameters`

**Comment by telboon** [comment]
Found the answer. 

The catch throw parameters is in the default config, but is not updated in the path example config. I mistakenly assumed it would be in both.

Thanks guys for the awesome work! (:
