### ISSUE TITLE
Can not run run.sh

### ISSUE THREAD

**Issue by Ogalababa** [PokemonGoF/PokemonGo-Bot#3957]
I had successful run the setup.sh. 
But when I run ./run.sh I got this:

Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/Users/Su/PokemonGo-Bot/pokemongo_bot/__init__.py", line 19, in <module>
    import cell_workers
  File "/Users/Su/PokemonGo-Bot/pokemongo_bot/cell_workers/__init__.py", line 3, in <module>
    from catch_lured_pokemon import CatchLuredPokemon
  File "/Users/Su/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_lured_pokemon.py", line 8, in <module>
    from pokemongo_bot.cell_workers.pokemon_catch_worker import PokemonCatchWorker
  File "/Users/Su/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_catch_worker.py", line 5, in <module>
    from pokemongo_bot import inventory
  File "/Users/Su/PokemonGo-Bot/pokemongo_bot/inventory.py", line 182
    <<<<<<< HEAD
    ^

### Your config.json (remove your credentials and any other private info)
```
your config here
```
{
    "auth_service": "google",
    "username": "---",
    "password": "---",
    "location": "---",
    "gmapkey": "---",
    "encrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "03:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
       
            "type": "EvolvePokemon",
            "config": {
                "evolve_all": "Pidgey,Weedle,Caterpie,Spearow,Rattata,Zubat,Staryu,Goldeen",
                "first_evolve_by": "cp",
                "evolve_above_cp": 10,
                "evolve_above_iv": 0.1,
                "logic": "or",
                "evolve_speed": 20,
                "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball": {
                        "keep": 0
                    },
                    "Greatball": {
                        "keep": 100
                    },
                    "Ultraball": {
                        "keep": 170
                    },
                    "Potion": {
                        "keep": 0
                    },
                    "Super Potion": {
                        "keep": 0
                    },
                    "Hyper Potion": {
                        "keep": 0
                    },
                    "Max Potion": {
                        "keep": 10
                    },
                    "Revive": {
                        "keep": 10
                    },
                    "Razz Berry": {
                        "keep": 30
                    }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "websocket_server": false,
    "walk": 27,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
     "evolve_captured": "Pidgey,Weedle,Caterpie,Spearow,Rattata,Zubat,Staryu,Goldeen",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "min_ultraball_to_keep": 10,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "catch_throw_parameters": {
      "excellent_rate": 0.1,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.6
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
       "Rattata": {
            "keep_best_cp": 2
        },
        "Raticate": {
            "keep_best_cp": 2
        },
        "Pidgey": {
            "keep_best_cp": 1
        },
        "Pidgeotto": {
            "keep_best_iv": 1
        },
        "Pidgeot": {
            "keep_best_iv": 3
        },
        "Weedle": {
            "keep_best_cp": 1
        },
        "Kakuna": {
            "keep_best_iv": 1
        },
        "Beedrill": {
            "keep_best_iv": 1
        },
        "Spearow": {
            "keep_best_cp": 1
        },
        "Fearow": {
            "keep_best_cp": 2
        },
        "Zubat": {
            "keep_best_cp": 1
        },
        "Golbat": {
            "keep_best_cp": 2,
            "keep_best_iv": 1
        },
        "Staryu": {
            "keep_best_cp": 2
        },
        "Seaking": {
            "keep_best_cp": 2,
            "keep_best_iv": 2
        },
        "Goldeen": {
            "keep_best_cp": 1
        },
        "Horsea": {
            "keep_best_cp": 2
        },
        "Krabby": {
            "keep_best_cp": 1
        },
        "Hypno": {
            "keep_best_iv": 2
        },
        "Drowzee": {
            "keep_best_cp": 1
        },
        "Venonat": {
            "keep_best_cp": 1
        },
        "Venomoth": {
            "keep_best_iv": 1
        },
        "Paras": {
            "keep_best_cp": 1
        },
        "Caterpie": {
            "keep_best_cp": 1
        },
        "Metapod": {
            "keep_best_iv": 1
        },
        "Butterfree": {
            "keep_best_iv": 2
        },
        "Slowpoke": {
            "keep_best_cp": 1
        },
        "Slowbro": {
            "keep_best_iv": 3
        },
        "Shellder": {
            "keep_best_cp": 1
        },
        "Gastly": {
            "keep_best_cp": 1
        },
        "Eevee": {
            "keep_best_cp": 1
        },
        "Starmie": {
            "keep_best_cp": 2,
            "keep_best_iv": 2
        },
        "Magikarp": {
            "keep_best_cp": 1
        },
        "Dratini": {
            "keep_best_cp": 1,
            "keep_best_iv": 1
        },
      
      
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 5, "catch_above_iv": 0.7, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

### Other Information
OS: OS X El Capitan
Python Version: Python 2.7.12

**Comment by k4n30** [comment]
#3679
