### ISSUE TITLE
Keep heaviest pokemon

### ISSUE THREAD

**Issue by lmondry** [PokemonGoF/PokemonGo-Bot#3958]
### Edited by moderator:
Submitting a request to have an option in the config to keep pokemon by their stats.
Example: Recycle pokemon by size.

***
#### Original Post:

Hi,

Is there a way to keep pokemons based on their weight or size instead of only iv or cp ?

Thanks

**Comment by Setsu-BHMT** [comment]
Add a new feature request here:
http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by DiegoRBaquero** [comment]
But why?

**Comment by k4n30** [comment]
They like big Pokemon? You can't question why it's a just a matter of who else who do it :p

**Comment by breinntaguilar** [comment]
anyone of you guys have a sample config.json.optimizer file? I dont know how to correctly set the parameters under keep section. im still trying to understand the whole thing but if anyone can give me a working config.json.optimizer, i would appreciate it very much. sorry for barging into your thread bro @lmondry. :)

**Comment by k4n30** [comment]
@breinntaguilar join the slack server, there's 100s of ppl there with configs

**Comment by simonsmh** [comment]
Sounds interesting, tag it with feature requests. 😂😂😂

**Comment by Gurzeh** [comment]
I had the same concern, but I "solve" it by playing with the release parameter and logical operand. You can further customize by type of Pokemon:

      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
     "// Best fighters, keep 2:": {},
      "Arcanine": {"keep_best_iv": 2},

but I think your suggestion is relevant

**Comment by jrjhealey** [comment]
There is a stat rationale for keeping, not the heaviest _per se_, but XL pokemon. Rumour has it that the HP pool is greater for XL pokemon.

Seems like a decent feature request that is probably pretty easy to implement.

**Comment by Anakin5** [comment]
@jrjhealey 
If that is he case, you can use "hp_max" as a sorting key in Pokemon Optimizer.
