### ISSUE TITLE
Bot not Working - __init__ error

### ISSUE THREAD

**Issue by LokiSchwartz** [PokemonGoF/PokemonGo-Bot#3960]
### Expected Behavior
Bot Runing

### Actual Behavior
The following Error: 

> python pokecli.py
> 2016-08-14 20:50:40,421 [       cli] [INFO] PokemonGO Bot v1.0
> 2016-08-14 20:50:40,423 [       cli] [INFO] No config argument specified, checking for /configs/config.json
> 2016-08-14 20:50:40,424 [       cli] [INFO] Configuration initialized
> 2016-08-14 20:50:40,437 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
> 2016-08-14 20:50:40,438 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
> 2016-08-14 20:50:40,438 [PokemonGoBot] [INFO] [location_found] Location found: -23.567661, -46.649115 (-23.567661, -46.649115, 0.0)
> 2016-08-14 20:50:40,440 [PokemonGoBot] [INFO] [position_update] Now at (-23.567661, -46.649115, 0)
> 2016-08-14 20:50:40,441 [PokemonGoBot] [INFO] [login_started] Login procedure started.
> 2016-08-14 20:50:42,700 [PokemonGoBot] [INFO] [login_successful] Login successful.
> 2016-08-14 20:50:44,694 [PokemonGoBot] [INFO]
> 2016-08-14 20:50:44,696 [PokemonGoBot] [INFO] --- Tiolokizito ---
> 2016-08-14 20:50:44,697 [PokemonGoBot] [INFO] Level: 1 (Next Level: 400 XP) (Total: 600 XP)
> 2016-08-14 20:50:44,697 [PokemonGoBot] [INFO] Pokemon Bag: 1/250
> 2016-08-14 20:50:44,698 [PokemonGoBot] [INFO] Items: 54/350
> 2016-08-14 20:50:44,700 [PokemonGoBot] [INFO] Stardust: 100 | Pokecoins: 0
> 2016-08-14 20:50:44,700 [PokemonGoBot] [INFO] PokeBalls: 50 | GreatBalls: 0 | UltraBalls: 0 | MasterBalls: 0
> 2016-08-14 20:50:44,700 [PokemonGoBot] [INFO] RazzBerries: 0 | BlukBerries: 0 | NanabBerries: 0
> 2016-08-14 20:50:44,701 [PokemonGoBot] [INFO] LuckyEgg: 0 | Incubator: 0 | TroyDisk: 0
> 2016-08-14 20:50:44,703 [PokemonGoBot] [INFO] Potion: 0 | SuperPotion: 0 | HyperPotion: 0 | MaxPotion: 0
> 2016-08-14 20:50:44,703 [PokemonGoBot] [INFO] Incense: 2 | IncenseSpicy: 0 | IncenseCool: 0
> 2016-08-14 20:50:44,704 [PokemonGoBot] [INFO] Revive: 0 | MaxRevive: 0
> 2016-08-14 20:50:44,704 [PokemonGoBot] [INFO]
> 2016-08-14 20:50:44,706 [PokemonGoBot] [INFO] Found encrypt.dll! Platform: win32 Encrypt.so directory: C:\Python27\PokemonGo-Bot
> 2016-08-14 20:50:44,707 [PokemonGoBot] [INFO]
> Traceback (most recent call last):
>   File "pokecli.py", line 578, in <module>
>     main()
>   File "pokecli.py", line 145, in main
>     report_summary(bot)
>   File "pokecli.py", line 180, in report_summary
>     metrics.capture_stats()
>   File "C:\Python27\PokemonGo-Bot\pokemongo_bot\metrics.py", line 84, in capture_stats
>     response_dict = request.call()
>   File "C:\Python27\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 106, in call
>     result = self._call()
>   File "C:\Python27\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 63, in _call
>     return PGoApiRequest.call(self)
>   File "c:\python27\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 210, in call
>     request.activate_signature(lib_path)
>   File "c:\python27\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 85, in activate_signature
>     self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
>   File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
>     return self._dlltype(name)
>   File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
>     self._handle = _dlopen(self._name, mode)
> WindowsError

### Your config.json (remove your credentials and any other private info)

> 	{
> 		"auth_service": "google",
> 		"username": "*********@gmail.com",
> 		"password": "********",
> 		"location": "-23.567661, -46.649115",
> 		"gmapkey": "********",
> 		"encrypt_location": "",
> 		"tasks": [
> 		  {
> 			"type": "HandleSoftBan"
> 		  },
> 		  {
> 			"type": "SleepSchedule",
> 			"config": {
> 			  "enabled": false,
> 			  "time": "22:54",
> 			  "duration":"7:46",
> 			  "time_random_offset": "00:24",
> 			  "duration_random_offset": "00:43"
> 			}
> 		  },
> 		  {
> 			"type": "CollectLevelUpReward"
> 		  },
> 		  {
> 			"type": "IncubateEggs",
> 			"config": {
> 			  "longer_eggs_first": true
> 			}
> 		  },
> 		  {
> 			"type": "UpdateLiveStats",
> 			"config": {
> 			  "enabled": false,
> 			  "min_interval": 10,
> 			  "stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
> 			  "terminal_log": true,
> 			  "terminal_title": true
> 			}
> 		  },
> 		  {
> 			"type": "TransferPokemon"
> 		  },
> 		  {
> 			"type": "NicknamePokemon",
> 			"config": {
> 			  "enabled": false,
> 			  "nickname_template": "{iv_pct}_{iv_ads}"
> 			}
> 		  },
> 		  {
> 			"type": "EvolvePokemon",
> 			"config": {
> 				"evolve_all": "none",
> 				"first_evolve_by": "cp",
> 				"evolve_above_cp": 500,
> 				"evolve_above_iv": 0.8,
> 				"logic": "or",
> 				"evolve_speed": 20,
> 				"use_lucky_egg": false
> 			}
> 		  },
> 		  {
> 			"type": "RecycleItems",
> 			"config": {
> 			  "min_empty_space": 15,
> 			  "item_filter": {
> 				"Pokeball":       { "keep" : 100 },
> 				"Potion":         { "keep" : 10 },
> 				"Super Potion":   { "keep" : 20 },
> 				"Hyper Potion":   { "keep" : 30 },
> 				"Revive":         { "keep" : 30 },
> 				"Razz Berry":     { "keep" : 100 }
> 			  }
> 			}
> 		  },
> 		  {
> 			"type": "CatchVisiblePokemon"
> 		  },
> 		  {
> 			"type": "CatchLuredPokemon"
> 		  },
> 		  {
> 			"type": "SpinFort"
> 		  },
> 		  {
> 			"type": "MoveToFort",
> 			"config": {
> 				"lure_attraction": true,
> 				"lure_max_distance": 2000
> 			}
> 		  },
> 		  {
> 			"type": "FollowSpiral",
> 			"config": {
> 			  "diameter": 4,
> 			  "step_size": 70
> 			}
> 		  }
> 		],
> 		"map_object_cache_time": 5,
> 		"forts": {
> 		  "avoid_circles": true,
> 		  "max_circle_size": 50,
> 		  "cache_recent_forts": true
> 		},
> 		"websocket_server": false,
> 		"walk": 4.16,
> 		"action_wait_min": 1,
> 		"action_wait_max": 4,
> 		"debug": false,
> 		"test": false,
> 		"health_record": false,
> 		"location_cache": true,
> 		"distance_unit": "km",
> 		"reconnecting_timeout": 15,
> 		"catch_randomize_reticle_factor": 1.0,
> 		"catch_randomize_spin_factor": 1.0,
> 		"min_ultraball_to_keep": 10,
> 		"logging_color": true,
> 		"catch": {
> 		  "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
> 		  "// Example of always catching Rattata:": {},
> 		  "// Rattata": { "always_catch" : true }
> 		},
> 		"catch_throw_parameters": {
> 		  "excellent_rate": 0.1,
> 		  "great_rate": 0.5,
> 		  "nice_rate": 0.3,
> 		  "normal_rate": 0.1,
> 		  "spin_success_rate" : 0.6
> 		},
> 		"release": {
> 		  "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
> 		  "// Example of always releasing Rattata:": {},
> 		  "// Rattata": {"always_release": true},
> 		  "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
> 		  "// Pidgey": {"keep_best_cp": 3},
> 		  "// Example of keeping 2 stronger (based on IV) Zubat:": {},
> 		  "// Zubat": {"keep_best_iv": 2},
> 		  "// Also, it is working with any": {},
> 		  "// any": {"keep_best_iv": 3},
> 		  "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
> 		  "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
> 		},
> 		"vips" : {
> 			 "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
> 			"any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
> 			"Lapras": {},
> 			"Moltres": {},
> 			"Zapdos": {},
> 			"Articuno": {},
> 
> 			"// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
> 			"Mewtwo": {},
> 			"Dragonite": {},
> 			"Snorlax": {},
> 			"// Mew evolves to Mewtwo": {},
> 			"Mew": {},
> 			"Arcanine": {},
> 			"Vaporeon": {},
> 			"Gyarados": {},
> 			"Exeggutor": {},
> 			"Muk": {},
> 			"Weezing": {},
> 			"Flareon": {}
> 
> 		}
> 	}

### Steps to Reproduce
Run "run.sh" or "windows_bat/PokemonGo-Bot-Start.bat"

### Other Information
OS: Win10
Git Commit: 5c9cdb53e69b5069cee6fe100d39e3cf5d63539c
Python Version: 2.7.1

**Comment by k4n30** [comment]
Looks like you have the wrong dll

**Comment by LokiSchwartz** [comment]
@k4n30 Do you know any place where I can download the dll por 64bits?

**Comment by LokiSchwartz** [comment]
Found one Here https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/pogom/libencrypt

I Hope this help someone else.
