### ISSUE TITLE
permabanned

### ISSUE THREAD

**Issue by eloivalles** [PokemonGoF/PokemonGo-Bot#3962]
After walking for some time, but not catching too much pokemon cause I have many filters, and geoposition near my home I got this message:

[api_error] Probably permabanned, Game Over ! Play again at https://club.pokemon.com/us/pokemon-trainer-club/sign-up/

**Comment by GitPupper** [comment]
Check #3700 #3746 or any of the other meta posts for more info about this. It looks like you are permabanned and you can't revert this unless you submit an appeal (and that wouldn't work since you were using a bot).

**Comment by liwenzhuo1216** [comment]
hey man, each time you caught a pokemon, how much exp you got?  210? right?
