### ISSUE TITLE
Ban?

### ISSUE THREAD

**Issue by takenek** [PokemonGoF/PokemonGo-Bot#3969]
hey i dont use one of my bot for like 3 days when was 1 wave of bans but everyday i only login from iOS device to check its working or not... today morning i can`t login on phone: "Failed to get game data from the server." and when i try run a bot got:

2016-08-15 07:48:31,140 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-15 07:48:33,091 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-15 07:48:38,452 [pokemongo_bot.api_wrapper] [WARNING] Server seems to be busy or offline - try again - 4/15

This is a ban? I don`t get any information from Nantic on e-mail and i can login to my account via webpage to [PTC](https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin)

Thank for info.

**Comment by avexus** [comment]
I'd say it looks like a ban

**Comment by takenek** [comment]
Strange because my bot walk amazing slow 2km/h and walk max 6 hours per day...

**Comment by avexus** [comment]
I just tried to log on to bot. The server is slow. I thought I was banned, then checked, it is not.

**Comment by shadypenguin21** [comment]
getting that same message on 1 account. Id say banned but you could try filling out that form and hope they respond

**Comment by takenek** [comment]
I am not sure but looks like a global problem.... my friend just tell me he get same problem on 100% legal account.... mayby this is a global problem?

**Comment by turtlehunter** [comment]
Getting the same error first time use, so its probably their servers been down as usual
