### ISSUE TITLE
Enhanced _do_catch method for PokemonCatchWorker (exposing more param?)

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#3978]
this is related to #3938 

// Expected Behavior
stop catching when low on special balls

// Actual Behavior
it seems (with my config below) that the bot is always low on special balls
And looking at work method in PokemonCatchWorker and helper _do_catch I saw
" # settings that may be exposed at some point.."

// Question
is there work in progress on that I could link to or participate?

// Config
config.json (relevant parts)
{
    "auth_service": "google",
    "username": "",
    "password": "",
    "location": "",
    "gmapkey": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "23:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "all",
            "first_evolve_by": "iv",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.9,
            "logic": "and",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 110 },
            "Greatball":      { "keep" : 50 },
            "Ultraball":      { "keep" : 50 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 10 },
            "Hyper Potion":   { "keep" : 10 },
            "Max Potion":     { "keep" : 30 },
            "Revive":         { "keep" : 10 },
            "Razz Berry":     { "keep" : 110 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToMapPokemon",
        "config": {
	"address": "http://localhost:5000",
	"max_distance": 500,
	"min_time": 60,
	"min_ball": 50,
	"prioritize_vips": true,
	"snipe": true,
	"snipe_high_prio_only": true,
	"snipe_high_prio_threshold": 600,
	"update_map": true,
	"mode": "priority",
          "catch": {
		"———— Mystic ————": 0,
               "Articuno":    1000,
		"Chansey":	1000,
		"Ditto":	1000,
		"Mew": 		1000,
		"Mewtwo": 	1000,
		"Moltres":	1000,
		"Zapdos": 	1000
        }
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.8,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging_color": true,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"}
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Best fighters, keep 2:": {},
      "Arcanine": {"keep_best_iv": 2},
      "Blastoise": {"keep_best_iv": 2}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1500, "catch_above_iv": 0.9, "logic": "and" },
        "Articuno": {}
    }
}

// OS: OSX
Git Commit: b21b144
Python Version: Python 2.7.12

**Comment by k4n30** [comment]
@Gurzeh considering this closed as the functionality you're after is now available, please reopen if you think it's not

**Comment by Gurzeh** [comment]
@k4n30 agree.
