### ISSUE TITLE
nickname config error

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#3981]
Even i set 
"dont_nickname_favorite": true,
It still rename it according to template
Or does the order in "type" matter?

{ "type":	"NicknamePokemon", "config": { "nickname_template": "{ivcp_pct2}%{iv_ads}"}, "enabled": true, "dont_nickname_favorite": true, "good_attack_threshold": 0.7},

**Comment by k4n30** [comment]
please use the issue template

**Comment by avexus** [comment]
@k4n30 sry, new to this. where is the issue template?
thank you

**Comment by k4n30** [comment]
You would have deleted the text (template) when u created this issue
