### ISSUE TITLE
Teleport behavior incorrectly, cycling?

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#3984]
### Expected Behavior
[XX:XX:XX] Teleporting to Pokemon
[XX:XX:XX] Encounter Pokemon
[XX:XX:XX] Teleporting back
[XX:XX:XX] A wild Pokemon appeared
[XX:XX:XX] Used ball
[XX:XX:XX] Capture Pokemon

### Actual Behavior
it seems to cycle : pile teleporting, and not unpiling. Logs is:
[11:48:15] Teleporting to Tentacool. (2.47km)
[11:48:15] Encountered Pokemon: Tentacool
[11:48:18] Teleporting back to previous location (48.8574579124, 2.2968982984)
[11:48:20] Moving towards Tentacool, 2.47km, left (3 weeks, 1 day, 5 hours, 8 minutes, 2 seconds)[11:48:20] 
[11:48:22] Keeping best 1 Paras, based on iv
[11:48:22] Exchanged Paras [CP 254] [IV 0.53] for candy.
[11:48:26] Teleporting to Paras. (2.55km)
[11:48:26] Encountered Pokemon: Paras
[11:48:29] Teleporting back to previous location (48.8574727508, 2.29697764294)
[11:48:32] Moving towards Paras, 2.55km, left (3 weeks, 1 day, 5 hours, 7 minutes, 50 seconds)[11:48:32] 
[11:48:35] Teleporting to Eevee. (2.66km)
[11:48:35] Encountered Pokemon: Eevee
[11:48:38] Teleporting back to previous location (48.857504017, 2.29700948418)
[11:48:43] Moving towards Eevee, 2.66km, left (3 weeks, 1 day, 5 hours, 7 minutes, 39 seconds)[11:48:43] 
[11:48:58] Teleporting to Slowpoke. (2.81km)
[11:48:58] Encountered Pokemon: Slowpoke
[11:49:05] Teleporting back to previous location (48.8575528531, 2.29700679093)
[11:49:10] Moving towards Slowpoke, 2.81km, left (3 weeks, 1 day, 5 hours, 7 minutes, 12 seconds)[11:49:10] 
[11:49:15] Teleporting to Tangela. (2.83km)
[11:49:15] Encountered Pokemon: Tangela
[11:49:17] Teleporting back to previous location (48.8575485531, 2.29705197996)
[11:49:22] Moving towards Tangela, 2.83km, left (3 weeks, 1 day, 5 hours, 7 minutes, 0 seconds)

### Your config.json (remove your credentials and any other private info)
{
    "auth_service": "ptc",
    "username": "",
    "password": "",
    "location": "",
    "gmapkey": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "23:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "all",
            "first_evolve_by": "iv",
            "evolve_above_cp": 200,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Greatball":      { "keep" : 50 },
            "Ultraball":      { "keep" : 50 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 10 },
            "Hyper Potion":   { "keep" : 10 },
            "Max Potion":     { "keep" : 30 },
            "Revive":         { "keep" : 10 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToMapPokemon",
        "config": {
	"address": "http://localhost:5000",
	"max_distance": 500,
	"min_time": 60,
	"min_ball": 50,
	"prioritize_vips": true,
	"snipe": true,
	"snipe_high_prio_only": true,
	"snipe_high_prio_threshold": 600,
	"update_map": true,
	"mode": "priority",
          "catch": {
		"———— Mystic ————": 0,
               "Articuno":    1000,
		"Ditto":	1000,
		"Farfetch'd":	1000,
		"Kangaskhan":	1000,
		"Mew": 		1000,
		"Mewtwo": 	1000,
		"Moltres":	1000,
		"Mr. Mime":	1000,
		"Tauros":	1000,
		"Zapdos": 	1000,

		"———— always catch ————": 0,
		"Dragonair": 	1000,
		"Dragonite": 	1000,
               "Eevee":	1000,
		"Dratini": 	1000,

		"———— missing in Pokedex ————": 0,
               "Aerodactyl":    1000,
               "Alakazam":    1000,
               "Beedrill":	1000,
               "Butterfree":	1000,
               "Cloyster":	1000,
		"Charizard":	1000,
		"Charmeleon":	1000,
		"Charizard":	1000,
		"Cubone":	1000,
  	 	"Dewgong":	1000,
               "Drowzee":	1000,
               "Dugtrio":	1000,
               "Electrode":	1000,
               "Gastly":	1000,
               "Gengar":	1000,
               "Golem":	1000,
               "Golduck":	1000,
               "Graveler":	1000,
               "Growlithe":	1000,
               "Hitmonchan":	1000,
               "Hitmonlee":	1000,
               "Hypno":	1000,
               "Jigglypuff":	1000,
               "Jolteon":	1000,
               "Kabutops":	1000,
               "Kadabra":	1000,
               "Lickitung":	1000,
               "Machamp":	1000,
               "Machoke":	1000,
 	 	"Magneton":	1000,
               "Marowak":	1000,
               "Metapod":	1000,
               "Nidoking":	1000,
               "Nidoqueen":	1000,
               "Nidorino":	1000,
               "Ninetales":	1000,
		"Muk":	 	1000,
		"Omanyte":	1000,
		"Omastar":	1000,
		"Onix":	 	1000,
		"Paras":	1000,
		"Persian":	1000,
		"Pidgeotto":	1000,
		"Pidgeot":	1000,
		"Pikachu":	1000,
	 	"Primeape":	1000,
	 	"Raichu":	1000,
               "Omastar":	1000,
               "Onix":		1000,
               "Persian":	1000,
               "Porygon":	1000,
               "Rhydon":	1000,
               "Sandslash":	1000,
               "Seel":		1000,
               "Slowpoke":	1000,
               "Slowbro":	1000,
               "Starmie":	1000,
               "Tentacool":	1000,
               "Tentacool":	1000,
               "Tentacruel":	1000,
               "Venonat":	1000,
               "Victreebel":	1000,
               "Vileplume":	1000,
               "Wartortle":	1000,
               "Weezing":	1000,
               "Wigglytuff":	1000,

		"———— for better IV ————": 0,

		"———— for evolve ————": 0,
		"Abra":		800,
		"Charmander":	800,
		"Grimer": 	800,
		"Kabuto":	800,
		"Kadabra":	800,
		"Mankey":	800,

		"———— best fighters ————": 0,
		"Arcanine": 	700,
		"Blastoise":	700,
		"Exeggutor": 	700,
		"Flareon": 	700,
		"Gyarados": 	700,
		"Jolteon": 	700,
		"Lapras": 	700,
		"Poliwrath": 	700,
		"Snorlax": 	700,
		"Vaporeon": 	700,
		"Venusaur": 	700          }
        }
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 4.5,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging_color": true,
    "evolve_captured": "none",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"}
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Best fighters, keep 2:": {},
      "Arcanine": {"keep_best_iv": 2},
      "Dragonair": {"keep_best_iv": 2},
      "Dragonite": {"keep_best_iv": 2},
      "Dratini": {"keep_best_iv": 2},
      "Eggegutor": {"keep_best_iv": 2},
      "Flareon": {"keep_best_iv": 2},
      "Gyarados": {"keep_best_iv": 2},
      "Poliwrath": {"keep_best_iv": 2},
      "Slowbro": {"keep_best_iv": 2},
      "Vaporeon": {"keep_best_iv": 2},
      "Venusaur": {"keep_best_iv": 2},

	"———— level final ————": 0,
      "Abra": {"keep_best_iv": 2},
      "Arbok": {"keep_best_iv": 1},
      "Beedrill": {"keep_best_iv": 1},
      "Butterfree": {"keep_best_iv": 1},
      "Charmander": {"keep_best_iv": 2},
      "Clefable": {"keep_best_iv": 1},
      "Cloyster": {"keep_best_iv": 1},
      "Dodrio": {"keep_best_iv": 1},
      "Dugtrio": {"keep_best_iv": 1},
      "Fearow": {"keep_best_iv": 1},
      "Electabuzz": {"keep_best_iv": 1},
      "Electrode": {"keep_best_iv": 1},
      "Exeggcute": {"keep_best_iv": 2},
      "Gengar": {"keep_best_iv": 1},
      "Golbat": {"keep_best_iv": 1},
      "Golduck": {"keep_best_iv": 1},
      "Golem": {"keep_best_iv": 1},
      "Grimer": {"keep_best_iv": 1},
      "Hitmonchan": {"keep_best_iv": 1},
      "Hitmonlee": {"keep_best_iv": 1},
      "Hypno": {"keep_best_iv": 1},
      "Jolteon": {"keep_best_iv": 1},
      "Jynx": {"keep_best_iv": 1},
      "Kabuto": {"keep_best_iv": 1},
      "Kingler": {"keep_best_iv": 1},
      "Lickitung": {"keep_best_iv": 1},
      "Magmar": {"keep_best_iv": 1},
      "Magnemite": {"keep_best_iv": 1},
      "Mankey": {"keep_best_iv": 2},
      "Marowak": {"keep_best_iv": 1},
      "Ninetales": {"keep_best_iv": 1},
      "Omastar": {"keep_best_iv": 1},
      "Onix": {"keep_best_iv": 1},
      "Parasect": {"keep_best_iv": 1},
      "Persian": {"keep_best_iv": 1},
      "Pidgeot": {"keep_best_iv": 1},
      "Pinsir": {"keep_best_iv": 1},
      "Ponyta": {"keep_best_iv": 1},
      "Porygon": {"keep_best_iv": 1},
      "Rapidash": {"keep_best_iv": 1},
      "Raticate": {"keep_best_iv": 1},
      "Rhyhorn": {"keep_best_iv": 1},
      "Scyther": {"keep_best_iv": 1},
      "Seadra": {"keep_best_iv": 1},
      "Seaking": {"keep_best_iv": 1},
      "Starmie": {"keep_best_iv": 1},
      "Tangela": {"keep_best_iv": 1},
      "Tentacruel": {"keep_best_iv": 1},
      "Venomoth": {"keep_best_iv": 1},
      "Victreebel": {"keep_best_iv": 1},
      "Weezing": {"keep_best_iv": 1},
      "Wigglytuff": {"keep_best_iv": 1},

	"———— level 2 ————": 0,
      "Haunter": {"keep_best_iv": 1},
      "Ivysaur": {"keep_best_iv": 1},
      "Nidorina": {"keep_best_iv": 1},
      "Nidorino": {"keep_best_iv": 1},
      "Pidgeotto": {"keep_best_iv": 1},
      "Wartortle": {"keep_best_iv": 1},

	"———— level 1 ————": 0,
      "Bulbasaur": {"keep_best_iv": 1},
      "Bellsprout": {"keep_best_iv": 1},
      "Clefairy": {"keep_best_iv": 1},
      "Cubone": {"keep_best_iv": 1},
      "Diglett": {"keep_best_iv": 1},
      "Doduo": {"keep_best_iv": 1},
      "Drowzee": {"keep_best_iv": 1},
      "Ekans": {"keep_best_iv": 1},
      "Eevee": {"keep_best_iv": 1},
      "Exxegcute": {"keep_best_iv": 1},
      "Fearow": {"keep_best_iv": 1},
      "Gastly": {"keep_best_iv": 2},
      "Geodude": {"keep_best_iv": 2},
      "Goldeen": {"keep_best_iv": 1},
      "Growlithe": {"keep_best_iv": 1},
      "Horsea": {"keep_best_iv": 1},
      "Jigglypuff": {"keep_best_iv": 1},
      "Kakuna": {"keep_best_iv": 1},
      "Koffing": {"keep_best_iv": 1},
      "Krabby": {"keep_best_iv": 1},
      "Magikarp": {"keep_best_iv": 1},
      "Meowth": {"keep_best_iv": 1},
      "Metapod": {"keep_best_iv": 1},
      "Nidoran F": {"keep_best_iv": 1},
      "Nidoran M": {"keep_best_iv": 1},
      "Paras": {"keep_best_iv": 1},
      "Poliwag": {"keep_best_iv": 1},
      "Poliwhirl": {"keep_best_iv": 1},
      "Ponyta": {"keep_best_iv": 1},
      "Psyduck": {"keep_best_iv": 1},
      "Rattata": {"keep_best_iv": 1},
      "Raticate": {"keep_best_iv": 1},
      "Shellder": {"keep_best_iv": 1},
      "Slowpoke": {"keep_best_iv": 1},
      "Spearow": {"keep_best_iv": 1},
      "Spearow": {"keep_best_iv": 1},
      "Squirtle": {"keep_best_iv": 1},
      "Staryu": {"keep_best_iv": 1},
      "Tentacool": {"keep_best_iv": 1},
      "Venonat": {"keep_best_iv": 1},
      "Voltorb": {"keep_best_iv": 1},
      "Vulpix": {"keep_best_iv": 1},
      "Zubat": {"keep_best_iv": 1},
      "Weepinbell": {"keep_best_iv": 1}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1500, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

### Steps to Reproduce
just running the bot

### Other Information
OS:OSX Capitan
Git Commit: b21b1449156b730fc224ed238f5b8bba606fe0f9
Python Version: Python 2.7.12

**Comment by k4n30** [comment]
According to your commit, you're using a 3 day old master version. Please update to the latest version and try again (master was updated a few hours ago)

**Comment by Gurzeh** [comment]
Good now.
