### ISSUE TITLE
Less pokemon encounter

### ISSUE THREAD

**Issue by lbanz** [PokemonGoF/PokemonGo-Bot#3989]
Since last Friday? I started getting soft IP bans. I set the intervals longer and slower walk speed. Used different IP address and I'm able to continue. However I noticed that there is less pokemon encounters. I get about 1 pokemon every 4-5 stops now. Roughly 1-2km before it encounters something. Anyone noticed the same problem?

**Comment by rickdoesburg** [comment]
I've noticed the same, restarting will catch 3-4 right away and then continues walking while not catching or encountering anything

**Comment by suzuke** [comment]
I can also confirm this issue

**Comment by Naiters** [comment]
Yeah, bot catches pokemons very rarely now, probably missing some on its path?

**Comment by Xat59** [comment]
Same behavior for me. How could I help you ?

**Comment by sohje** [comment]
9 pokestops = 1 pokemon...

**Comment by vixxxx** [comment]
yep same here.

**Comment by Naiters** [comment]
Would any dev like to make an improvement to catching more pokemon? :dancer:

**Comment by lbanz** [comment]
Pretty sure it's not the code. It must be the softban or our accounts getting flagged up. If I create a brand new account on different IP. Same config file but just different account details. I don't have that problem. But as soon as after running it for a few hours. I notice that the problems start occurring.

**Comment by Naiters** [comment]
Hmm, I encouter a lot more pokemon when Im playing with my phone -same account.

**Comment by cypha88** [comment]
I have adjusted the catch rates to make normal throws occur more. I set the move speed down to 3.0 and I'll adjust it every 2 hours to mimic fatigue. I'm sometimes getting the slow pokemon appearance too.

It's a bit troubling.

**Comment by Naiters** [comment]
Any updates on the issue, guys?

**Comment by cypha88** [comment]
@Naiters 

Could be an IP softban. I had this occurring and stopped the bot. Waited 5 minutes to mimic walking home, and then logged into the app on my phone, on the wifi I use my laptop bot on... and there was nothing loading on my map. But if I went on cellular data, everything instantly loaded...

I saw someone mention on reddit he was botting 3 hours on, 2 hours off and he just hit level 37, no ban. Try realistically mimicking human behavior i.e. throw normal throws, slow your walk rate down, bot for only 3-4 hours. I'm trying it and seeing how far I can get.

**Comment by 0z4ck** [comment]
I have been saying the same thing but no one understood me >< 
#3562

**Comment by lbanz** [comment]
Well. Looks like I just got 2 accounts perma banned.so yeah I think this might be symptoms before a ban.

**Comment by cypha88** [comment]
@lbanz How long were  you letting the bot go? Were you throwing a lot of excellent throws? What was your walking pace? How many levels did you get in one run?

**Comment by lbanz** [comment]
@cypha88 Honestly no idea how long I ran it. But it took probably 1 week to level 30. Walking pace is 14km/h. Only one of the account didn't get banned. The one that I bot and also play myself @ level 29. All the other ones doesn't have any gym battles and got banned.

I use torr so the bot all run on multiple IPs with the same bot configs.

**Comment by Benjaminhu** [comment]
+1, same here

**Comment by Benjaminhu** [comment]
Latest result, slow down the speed:
    "walk_min": 0.2,
    "walk_max": 3.9,
 result:
Ran for 0:33:56, Visited 21 stops, Encountered 14 pokemon, 13 caught

**Comment by Nerkyator** [comment]
Same settings as @Benjaminhu, result:
Uptime : 1:24:42 | Earned 3,200 Stardust | +7,840 XP | Caught 32 pokemon | Visited 57 stops

**Comment by net8q** [comment]
Noticed that when using PoGoMap, bot pass near spawn points but does not encounter them. imho the server is definitively filtering encounters seen by accounts, depending on their performance. Throttling down/sleeping more seems the only solution

**Comment by Benjaminhu** [comment]
"[api_error] Probably permabanned, Game Over !" :(

**Comment by mjmadsen** [comment]
Meta issue about this:  #4601

As we can mostly agree, it is a ban.
