### ISSUE TITLE
Transfering catched pokemon even if above IV/CP

### ISSUE THREAD

**Issue by surfaace** [PokemonGoF/PokemonGo-Bot#399]
### Expected Behavior
After catching, it should keep the pokemon, as IV value 0.8 should keep pokemons above 0.5 according to docu

### Actual Behavior
[#] A Wild Hitmonchan appeared! [CP 376] [Potential 0.76]
[x] Using Greatball...
[x] Captured Hitmonchan! [CP 376] [IV 0.76] - exchanging for candy
[#] Hitmonchan has been exchanged for candy!

### Steps to Reproduce
pokecli.py -a ptc -u U -p P -l location --maxsteps 10 -w 4.16 -c 250 -iv 0.8 -m all --initial-transfer

### Other Information
OS: Win10 x64 pro
Git Commit: 59033f59676a093521c2285537840c2c4d71084f

**Comment by Calcyfer** [comment]
Where did you read the 0.5 value?

IV has priority over CP in the code, so 376 CP with IV 0.76 will be transferred since IV is lower than your given 0.8.

**Comment by surfaace** [comment]
I was wondering why docu was differ 0.3. as it says -iv 0.8 will be 0.5 according to docu, probably typo error in docu then
