### ISSUE TITLE
"No Player Position Set Exception" Error

### ISSUE THREAD

**Issue by user121349** [PokemonGoF/PokemonGo-Bot#3994]
Every time I try to run the bot, I get the following error, 

`[sentry.errors.uncaught] [ERROR] [u'NoPlayerPositionSetException', u'  File "pokecli.py", line 595, in <module>', u'  File "pokecli.py", line 162, in main', u'  File "pokecli.py", line 197, in report_summary', u'  File "pokemongo_bot/metrics.py", line 84, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 101, in call', u'  File "pokemongo_bot/api_wrapper.py", line 57, in 'can_call']`

How do you fix this?

**Comment by Matttter** [comment]
Could you please provide your config file, OS, ...? I'd think you forgot to put coordinates in it.

**Comment by user121349** [comment]
@Matttter Sure. Config files are in .JSON and I am running OS X 10.11.5. I put in coordinates when prompted to do so

**Comment by Matttter** [comment]
Can you go into the configs folder (which is inside the PokemonGo-Bot
folder) and copy/paste the config.json content (don't forget to delete
password and account and gmap api key) here? That's what I meant, sorry.

**Comment by user121349** [comment]
@Matttter Here it is. I ran through the set up using `./setup.sh -i`, but when I go into the config file the username, password, location, and gmapkey all have placeholders. Is that normal?

`{
    "auth_service": "google",
    "username": "YOUR_USERNAME",
    "password": "YOUR_PASSWORD",
    "location": "SOME_LOCATION",
    "gmapkey": "GOOGLE_MAPS_API_KEY",
    "encrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46”,l
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "min_ultraball_to_keep": 10,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "catch_throw_parameters": {
      "excellent_rate": 0.1,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.6
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}
`

**Comment by Matttter** [comment]
That is not normal, but it is what I expected. This is why you are having
errors. Please replace the values with valid ones, and try running the bot
again.

Op ma 15 aug. 2016 om 16:24 schreef user121349 <notifications@github.com>:

**Comment by user121349** [comment]
@Matttter I did that but still get a lot of errors and it won't run. 

`./configs/config.json:3:16: Error: Can not decode value starting with character u'\u201c'
   |  At line 3, column 16, offset 48
./configs/config.json:3:29: Info: Recovering parsing after character u','
   |  At line 3, column 29, offset 61
./configs/config.json:4:16: Error: Can not decode value starting with character u'\u201c'
   |  At line 4, column 16, offset 79
./configs/config.json:4:26: Info: Recovering parsing after character u','
   |  At line 4, column 26, offset 89
./configs/config.json:17:29: Error: Line terminator characters must be escaped inside string literals: 'U+000A'
   |  At line 17, column 29, offset 427
   |  String started at line 17, column 21, offset 419
./configs/config.json:18:11: Warning: JSON does not allow identifiers to be used as strings: u'time_random_offset'
   |  At line 18, column 11, offset 439
./configs/config.json:18:11: Error: Values must be separated by a comma
   |  At line 18, column 11, offset 439
   |  Object started at line 14, column 18, offset 341
./configs/config.json:18:11: Error: Missing value for object property, expected ":"
   |  At line 18, column 11, offset 439
   |  Object started at line 14, column 18, offset 341
./configs/config.json:18:30: Error: Can not decode value starting with character u':'
   |  At line 18, column 30, offset 458
./configs/config.json:18:32: Info: Recovering parsing after character u'"'
   |  At line 18, column 32, offset 460
./configs/config.json:18:32: Error: Values must be separated by a comma
   |  At line 18, column 32, offset 460
   |  Object started at line 14, column 18, offset 341
./configs/config.json:18:32: Error: Missing value for object property, expected ":"
   |  At line 18, column 32, offset 460
   |  Object started at line 14, column 18, offset 341
./configs/config.json:19:34: Error: Can not decode value starting with character u':'
   |  At line 19, column 34, offset 503
./configs/config.json:19:36: Info: Recovering parsing after character u'"'
   |  At line 19, column 36, offset 505
./configs/config.json:19:36: Info: Recovering parsing after character u'"'
   |  At line 19, column 36, offset 505
./configs/config.json:19:36: Error: Values must be separated by a comma
   |  At line 19, column 36, offset 505
   |  Object started at line 14, column 18, offset 341
./configs/config.json:19:36: Error: Missing value for object property, expected ":"
   |  At line 19, column 36, offset 505
   |  Object started at line 14, column 18, offset 341
./configs/config.json:21:6: Error: Can not decode value starting with character u'}'
   |  At line 21, column 6, offset 529
./configs/config.json:21:7: Info: Recovering parsing after character u','
   |  At line 21, column 7, offset 530
./configs/config.json:22:6: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 22, column 6, offset 538
   |  Object started at line 14, column 18, offset 341
./configs/config.json:22:6: Error: Missing value for object property, expected ":"
   |  At line 22, column 6, offset 538
   |  Object started at line 14, column 18, offset 341
./configs/config.json:31:6: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 31, column 6, offset 709
   |  Object started at line 14, column 18, offset 341
./configs/config.json:31:6: Error: Missing value for object property, expected ":"
   |  At line 31, column 6, offset 709
   |  Object started at line 14, column 18, offset 341
./configs/config.json:44:6: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 44, column 6, offset 1072
   |  Object started at line 14, column 18, offset 341
./configs/config.json:44:6: Error: Missing value for object property, expected ":"
   |  At line 44, column 6, offset 1072
   |  Object started at line 14, column 18, offset 341
./configs/config.json:63:6: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 63, column 6, offset 1550
   |  Object started at line 14, column 18, offset 341
./configs/config.json:63:6: Error: Missing value for object property, expected ":"
   |  At line 63, column 6, offset 1550
   |  Object started at line 14, column 18, offset 341
./configs/config.json:80:6: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 80, column 6, offset 2039
   |  Object started at line 14, column 18, offset 341
./configs/config.json:80:6: Error: Missing value for object property, expected ":"
   |  At line 80, column 6, offset 2039
   |  Object started at line 14, column 18, offset 341
./configs/config.json:86:6: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 86, column 6, offset 2136
   |  Object started at line 14, column 18, offset 341
./configs/config.json:86:6: Error: Missing value for object property, expected ":"
   |  At line 86, column 6, offset 2136
   |  Object started at line 14, column 18, offset 341
./configs/config.json:100:4: Error: Expected a '}' but saw ']'
   |  At line 100, column 4, offset 2415
   |  Object started at line 14, column 18, offset 341
./configs/config.json:100:4: Error: Expected a '}' but saw ']'
   |  At line 100, column 4, offset 2415
   |  Object started at line 12, column 6, offset 288
./configs/config.json:144:6: Warning: Object contains duplicate key: u'// Zubat'
   |  At line 144, column 6, offset 3918
   |  Object started at line 133, column 15, offset 3342
./configs/config.json: has errors
2016-08-15 12:41:22,251 [       cli] [CRITICAL] Error with configuration file
Mon Aug 15 12:41:22 EDT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
2016-08-15 12:41:42,936 [       cli] [INFO] PokemonGO Bot v1.0
./configs/config.json:3:16: Error: Can not decode value starting with character u'\u201c'
   |  At line 3, column 16, offset 48
./configs/config.json:3:29: Info: Recovering parsing after character u','
   |  At line 3, column 29, offset 61
./configs/config.json:4:16: Error: Can not decode value starting with character u'\u201c'
   |  At line 4, column 16, offset 79
./configs/config.json:4:26: Info: Recovering parsing after character u','
   |  At line 4, column 26, offset 89
./configs/config.json:17:29: Error: Line terminator characters must be escaped inside string literals: 'U+000A'
   |  At line 17, column 29, offset 427
   |  String started at line 17, column 21, offset 419
./configs/config.json:18:11: Warning: JSON does not allow identifiers to be used as strings: u'time_random_offset'
   |  At line 18, column 11, offset 439
./configs/config.json:18:11: Error: Values must be separated by a comma
   |  At line 18, column 11, offset 439
   |  Object started at line 14, column 18, offset 341
./configs/config.json:18:11: Error: Missing value for object property, expected ":"
   |  At line 18, column 11, offset 439
   |  Object started at line 14, column 18, offset 341
./configs/config.json:18:30: Error: Can not decode value starting with character u':'
   |  At line 18, column 30, offset 458
./configs/config.json:18:32: Info: Recovering parsing after character u'"'
   |  At line 18, column 32, offset 460
./configs/config.json:18:32: Error: Values must be separated by a comma
   |  At line 18, column 32, offset 460
   |  Object started at line 14, column 18, offset 341
./configs/config.json:18:32: Error: Missing value for object property, expected ":"
   |  At line 18, column 32, offset 460
   |  Object started at line 14, column 18, offset 341
./configs/config.json:19:34: Error: Can not decode value starting with character u':'
   |  At line 19, column 34, offset 503
./configs/config.json:19:36: Info: Recovering parsing after character u'"'
   |  At line 19, column 36, offset 505
./configs/config.json:19:36: Info: Recovering parsing after character u'"'
   |  At line 19, column 36, offset 505
./configs/config.json:19:36: Error: Values must be separated by a comma
   |  At line 19, column 36, offset 505
   |  Object started at line 14, column 18, offset 341
./configs/config.json:19:36: Error: Missing value for object property, expected ":"
   |  At line 19, column 36, offset 505
   |  Object started at line 14, column 18, offset 341
./configs/config.json:21:6: Error: Can not decode value starting with character u'}'
   |  At line 21, column 6, offset 529
./configs/config.json:21:7: Info: Recovering parsing after character u','
   |  At line 21, column 7, offset 530
./configs/config.json:22:6: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 22, column 6, offset 538
   |  Object started at line 14, column 18, offset 341
./configs/config.json:22:6: Error: Missing value for object property, expected ":"
   |  At line 22, column 6, offset 538
   |  Object started at line 14, column 18, offset 341
./configs/config.json:31:6: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 31, column 6, offset 709
   |  Object started at line 14, column 18, offset 341
./configs/config.json:31:6: Error: Missing value for object property, expected ":"
   |  At line 31, column 6, offset 709
   |  Object started at line 14, column 18, offset 341
./configs/config.json:44:6: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 44, column 6, offset 1072
   |  Object started at line 14, column 18, offset 341
./configs/config.json:44:6: Error: Missing value for object property, expected ":"
   |  At line 44, column 6, offset 1072
   |  Object started at line 14, column 18, offset 341
./configs/config.json:63:6: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 63, column 6, offset 1550
   |  Object started at line 14, column 18, offset 341
./configs/config.json:63:6: Error: Missing value for object property, expected ":"
   |  At line 63, column 6, offset 1550
   |  Object started at line 14, column 18, offset 341
./configs/config.json:80:6: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 80, column 6, offset 2039
   |  Object started at line 14, column 18, offset 341
./configs/config.json:80:6: Error: Missing value for object property, expected ":"
   |  At line 80, column 6, offset 2039
   |  Object started at line 14, column 18, offset 341
./configs/config.json:86:6: Error: Object properties (keys) must be string literals, numbers, or identifiers
   |  At line 86, column 6, offset 2136
   |  Object started at line 14, column 18, offset 341
./configs/config.json:86:6: Error: Missing value for object property, expected ":"
   |  At line 86, column 6, offset 2136
   |  Object started at line 14, column 18, offset 341
./configs/config.json:100:4: Error: Expected a '}' but saw ']'
   |  At line 100, column 4, offset 2415
   |  Object started at line 14, column 18, offset 341
./configs/config.json:100:4: Error: Expected a '}' but saw ']'
   |  At line 100, column 4, offset 2415
   |  Object started at line 12, column 6, offset 288
./configs/config.json:144:6: Warning: Object contains duplicate key: u'// Zubat'
   |  At line 144, column 6, offset 3918
   |  Object started at line 133, column 15, offset 3342
./configs/config.json: has errors
2016-08-15 12:41:42,976 [       cli] [CRITICAL] Error with configuration file
Mon Aug 15 12:41:43 EDT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.`

**Comment by Matttter** [comment]
Just follow every error, look at the lines. They explain what you did
wrong. Proofread very carefully every line of it to assure it's proper
JSON.

**Comment by CyberMew** [comment]
Use json lint to validate the file

**Comment by jrjhealey** [comment]
Edit the placeholders with the relevant information for your account.

You need to provide your account info, a location, and so on

> `test code`
