### ISSUE TITLE
ImportError: No module named xxhash

### ISSUE THREAD

**Issue by gsmith257** [PokemonGoF/PokemonGo-Bot#3999]
I am currently using the dev branch:
`hidden-home:PokemonGo-Bot GrantSmith$ git branch
* dev
`
I have read all the issues about this and someone made a pull request to fix it and after that I reinstalled the bot and also reinstalled the requirements. It still gives me the error that it been giving me for the past 4 days. It worked fine until the end of friday and the gave me the xxhash error.

### Expected Behavior:
`(PokemonGo-Bot) hidden-home:Documents GrantSmith$ ./pokemongobot.sh
2016-08-12 17:11:14,986 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-12 17:11:14,998 [       cli] [INFO] Configuration initialized
2016-08-12 17:11:14,998 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more logrmation:
2016-08-12 17:11:14,999 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-12 17:11:15,247 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-12 17:11:15,999 [PokemonGoBot] [INFO] [set_start_location] Setting start location.
2016-08-12 17:11:15,999 [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
2016-08-12 17:11:16,000 [PokemonGoBot] [INFO] [location_found] Location found: 34.0522300, -118.2436800 (34.05223, -118.24368, 0.0)
2016-08-12 17:11:16,000 [PokemonGoBot] [INFO] [position_update] Now at (34.05223, -118.24368, 0)
2016-08-12 17:11:16,002 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-12 17:11:20,990 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-12 17:11:22,804 [PokemonGoBot] [INFO] 
`

### Actual Behavior:
`hidden-home:Documents GrantSmith$ ./pokemongobot.sh
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "/Users/GrantSmith/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/Users/GrantSmith/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/Users/GrantSmith/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "/Users/GrantSmith/PokemonGo-Bot/src/pgoapi/pgoapi/utilities.py", line 30, in <module>
    import xxhash
ImportError: No module named xxhash
`

### Your config.json (remove your credentials and any other private info)
```
{
    "auth_service": "google",
    "username": "Username",
    "password": "password",
    "location": "34.0522300, -118.2436800",
    "gmapkey": "Javascript API key",
    "encrypt_location": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "websocket_server": false,
    "walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "min_ultraball_to_keep": 10,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "catch_throw_parameters": {
      "excellent_rate": 0.1,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.6
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

```

### Other Information
OS: Mac OS
Git Commit: `hidden-home:PokemonGo-Bot GrantSmith$ git log -n 1 --pretty=format:"%H"
caefe8463e45427ac40db1f9dd6b7d65353f891d`
Python Version: `hidden-home:PokemonGo-Bot GrantSmith$ python -V
Python 2.7.10`

**Comment by imvikash00** [comment]
Did u run "pip install -r requirements.txt" ? 
Or you could simply run setup.sh

**Comment by accident12123** [comment]
I ran into this and the only solution was "./setup.py -u" and not really sure why that worked and typing everything by hand didn't.

**Comment by gsmith257** [comment]
Yes I did run 'pip install -r requirements.txt' and my startup script just says 

`cd /Users/GrantSmith/PokemonGo-Bot/
python pokecli.py -cf ./configs/config.json
python pokecli.py -cf ./configs/config.json
python pokecli.py -cf ./configs/config.json
python pokecli.py -cf ./configs/config.json`

**Comment by gsmith257** [comment]
what does the -u do?

**Comment by accident12123** [comment]
@gsmith257 upgrade

**Comment by jrjhealey** [comment]
`pip install xxhash` and `pip install raven` (possibly will need to throw a sudo in front of those). I would then re-run `pip install -r requirements.txt`.

Are you using virtualenv?

**Comment by gsmith257** [comment]
@accident12123 I have the latest version. just upgraded today. and @jrjhealey I am using whatever the pokecli.py file is using. I will also try those commands and let you know. Thanks

**Comment by gsmith257** [comment]
after running those I get this error

`ImportError: No module named networkx.algorithms.clique`

**Comment by jrjhealey** [comment]
If you used the `install.sh` script, you should be working in a python virtual environment, in which case the python modules will also need to be installed within that VE.

The requirements.txt should take care of this, but in any event, try running the commands I mentioned from inside the PokemonGo-Bot main folder after running `source bin/activate`

**Comment by gsmith257** [comment]
how should i run "source bin/activate"?

**Comment by jrjhealey** [comment]
Just as I said. That is the command.

If you run it from the main folder, your command prompt will change and have (PokemonGo-Bot) at the start. Assuming that you didn't name the venv anything else, which I doubt you did...

**Comment by gsmith257** [comment]
ok thanks

**Comment by gsmith257** [comment]
it worked! thanks so much!
