### ISSUE TITLE
Problem with FollowPath and MoveToFort

### ISSUE THREAD

**Issue by iruy** [PokemonGoF/PokemonGo-Bot#4001]
### Expected Behavior
Going back to original path after moving to fort

### Actual Behavior
When it encounter a fort, it diverts from the Path and doesn't go back to it

### Config.json
```
	{
		"type": "SpinFort"
	},
	{
		"type": "MoveToFort",
		"config": {
			"lure_attraction": true,
			"lure_max_distance": 2000
	}
	},
	{
		"type": "FollowPath",
		"config": {
			"path_mode": "linear",
			"path_start_mode": "first",
			"path_file": "configs/path.json"
		}
	}
```

**Comment by suksit** [comment]
Quoted from [Example configuration](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md#example-configuration):

> The following configuration tells the bot to transfer all the Pokemon that match the transfer configuration rules, then recycle the items that match its configuration, then catch the pokemon that it can, so on, so forth. Note the last two tasks, MoveToFort and FollowSpiral. **When a task is still in progress, it won't run the next things in the list**. So it will move towards the fort, on each step running through the list of tasks again. **Only when it arrives at the fort and there are no other stops available for it to move towards will it continue to the next step and follow the spiral**.

So this is by design.

**Comment by iruy** [comment]
What if I put MoveToFort as last task? Would it still go to forts or they would be discarded at all?

**Comment by accident12123** [comment]
not exactly the same thing your doing but i'm trying to get a path to walk before moving onto just walking between forts and it's not working right.    even having followpath first and both followpath and movetofort are trying to walk at the same time to different places so it's constantly going back and forth.

I do think there is a bug here as I would expect followpath to work the same as other tasks like movetomappokemon where they run until they can't and then tasks below it get their turn to walk around.

**Comment by k4n30** [comment]
@iruy is your issue resolved?
