### ISSUE TITLE
[META] Legal Stuff (Recommendations)

### ISSUE THREAD

**Issue by mjmadsen** [PokemonGoF/PokemonGo-Bot#4002]
As many of you know, Necrobot supposedly received a cease and desist order from Niantic legal and they shortly after shut down their GitHub. I personally have had a website shut down for a similar situation with Blizzard and a d2 bot. They claimed copyright infringement and GoDaddy didn't blink before shutting off my services. That being said, here are a few things we might want to do to prepare:

- Cite copyright holders information when using the words "Pokemon", "PokemonGo", "Niantic", etc. 
- State that using this software is intended for academic purposes and should not be used to play the game, as it violates TOS and is unfair to the community. 
- State that we do not support the use of 3rd party apps

These are flimsy. I am also curious on github rules. Whatever they are, I'm sure if they received something from Niantic legal, they wouldn't think twice before shutting down this hub.

Any thoughts, recommendations and comments would be appreciated. If any of you happen to work in law, that'd be cool too. I'm beginning to enjoy working on the bot more than playing, and I would love if this project could continue forward.

Thanks guys!

***

Edits made by, moderator: [Grammarly](https://www.grammarly.com/?q=brand&utm_source=google&utm_medium=cpc&utm_campaign=brand_f2&utm_content=99403879086&utm_term=grammarly&matchtype=e&placement=&network=g&gclid=Cj0KEQjw0MW9BRDxtYTn2_S699MBEiQAw33y47jWLbJmXjbJ3oDc00glOMNfgIJdiaF6QE5e93wbDHsaAiO18P8HAQ) suggestions.

**Comment by bykof** [comment]
You maybe should move the repo to Gitlab. Or take a server and install gitlab on it and then push the code to it.

**Comment by jrjhealey** [comment]
Perhaps stress that the bot is strictly not for profit as well.

Again a flimsy defence if they really want to cause issues but can't hurt either.

**Comment by GitPupper** [comment]
Fixed your grammar again ;P
