### ISSUE TITLE
Just a thought to actually mimic human behaviour

### ISSUE THREAD

**Issue by imvikash00** [PokemonGoF/PokemonGo-Bot#4006]
Bot, after running for few hours should go into just  walking state and by that I mean it should'nt make any calls to the server (totally disconnect) during which it should just keep walking for 5-10 mins probably skip 4-5 pokestops. Then connects to server and follow the usual routine. 
IMO this will mimic actual human behaviour as if the app has gone into background 

Edit:
Could be used for moving from one lure fort to another?

**Comment by orchid666** [comment]
Can't you already achieve that with the sleep function?

**Comment by imvikash00** [comment]
@orchid666 does the bot keep walking during that sleep period? I thought the bot will sleep and start from the same location after sleep cycle is over

**Comment by avexus** [comment]
@orchid666 Can you specify how the sleep function work?

**Comment by avexus** [comment]
Like give an example to sleep 15 min every hour?
Thank you

**Comment by orchid666** [comment]
The Sleepschedule that can be put in your config. It's pretty new and im not a specialist but on slack I've seen people putting like 4-5 of those at different times to simulate breaks. 
Sleep 15 min every hour is therefore doable, just a lot of copy-paste :)  
{
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }

**Comment by orchid666** [comment]
@imvikash00 Not the bot stops everything during the "sleep" and then start from where it stopped. Its basically a pause in the script.

**Comment by ponytails** [comment]
u should make it random.. .even u put bot sleeps that way.. it will be just the same

= must be random sleep

**Comment by imvikash00** [comment]
@orchid666 by pause u mean script is paused (no interaction with the server)  but the bot keeps walking?

**Comment by orchid666** [comment]
@imvikash00 Everything is paused, bot is not walking during sleep.

**Comment by mjmadsen** [comment]
@ponytails time_random_offset and duration_random_offset are the random elements.
