### ISSUE TITLE
What does "Sleep schedule" task actually do?

### ISSUE THREAD

**Issue by imvikash00** [PokemonGoF/PokemonGo-Bot#4012]
There is no info in the wiki as to what Sleep Schedule does, so I thought I would ask.

What is the purpose of Sleep Schedule? Does it stop the bot completely or does it stop any interaction with the server mimicking as if the app is in background. Does the bot keep walking during this sleep period? 

Here's a sample task.
{
"type": "SleepSchedule",
"config": {
"enabled": false,
"time": "22:54",
"duration":"7:46",
"time_random_offset": "00:24",
"duration_random_offset": "00:43"
}

**Comment by keugnu** [comment]
Pauses the bot for a time. In this case 27.960 plus or minus 2,580 seconds at 22:54 plus or minus 1,440 seconds.

**Comment by MasterCATZ** [comment]
still needs a bit of a tune , for me it keeps setting its next sleep time 24 hr later 

ie) if you start bot about an hr before when you want its first sleep , it will not do it until the following day 


here i set the config to start sleep Today 13:18
but it did tomorrow
date
Mon 15 Aug 13:14:01 CEST 2016
Next sleep at 2016-08-16 13:18:59.964978
tried again 13:33
date
Mon 15 Aug 13:33:33 CEST 2016
Next sleep at 2016-08-16 13:33:43.749257
so I came to the conclusion it will not do same day unless the full duration can be acomplished before the sleep time started 
which would mean for this to activate on the same day it would have to be at least 13:55
 {
        "type": "SleepSchedule",
        "config": {
          "enabled": true,
          "time": "15:55",
          "duration":"1:00",
          "time_random_offset": "00:10",
          "duration_random_offset": "00:30"
        }
      },
the problem being how do you get the bot to shutdown after running 1 hr  on first run ? if it will keep making the next day the time ?

**Comment by k4n30** [comment]
Please take configuration discussion to slack
