### ISSUE TITLE
UpdateLiveStats when SleepSchedule

### ISSUE THREAD

**Issue by keugnu** [PokemonGoF/PokemonGo-Bot#4017]
Improvement in user experience.

### Expected Behavior
Run UpdateLiveStats when bot sleeps

### Actual Behavior
None

**Comment by k4n30** [comment]
Don't think this possible due to not being multi threaded, but going to mark it as a Feature Request.

Small question - wouldn't the stats not change while it's sleeping anyway?

**Comment by keugnu** [comment]
@k4n30 I don't understand the double negative.... The intention is to just show stats when the bot goes to sleep and be done with it.

**Comment by k4n30** [comment]
Updated my response to help clarify

**Comment by keugnu** [comment]
Really, these should be combined. Rename it to SleepAndStats if you have to keep things "modular." :)
