### ISSUE TITLE
[Feature Request] Pause if earned x amount of xp and/or caught y amount of pokemon

### ISSUE THREAD

**Issue by CyberMew** [PokemonGoF/PokemonGo-Bot#4019]
I think it would be great if we had an option to pause/stop the bot at least temporary for the day (or depending on sleep schedules) once we have met our 'quota'.

**Comment by tolinwei** [comment]
+1, I read about this in other issues (and the Reddit post of course), not sure if it's WIP.

**Comment by keugnu** [comment]
#3922

**Comment by mjmadsen** [comment]
On the todo list as well (#4004). I'm going to begin work on this tonight, less I find another PR already up.

**Comment by mjmadsen** [comment]
Contained in #3922.

**Comment by mjmadsen** [comment]
#3922 Duplicate
