### ISSUE TITLE
"terminal_title" didn't show on gitbash window

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#4020]
### Expected Behavior
To show on the title bar. gitbash on Window 10 doesn't show.
However, cmd  on Window 10 shows this. Also, Terminal in Mac OSX shows too.
### Your config.json (remove your credentials and any other private info)
```
		{ "type":	"UpdateLiveStats",
			"config": {
				"enabled":			true,
				"min_interval":		50,
				"stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
				"terminal_log":		true,
				"terminal_title":	true
			}
		}
```

**Comment by nanogirl21** [comment]
@avexus  This does not have anything to do with the config.json. If you open your Terminal Preferences (command+comma) click Title and then look at the opens you can select what info you want ALONG WITH the config.json 

directory or document name
active process and
shell command name
profile name
the list goes on...

**Comment by avexus** [comment]
@nanogirl21 Terminal in Mac works fine. cmd in Windows works fine.
Just GitBash in Windows10 doesn't work.
And I know it's not the config that's causing the problem. But some where in the code, if it can detect GitBash, maybe something can be done there.

**Comment by mjmadsen** [comment]
@avexus Does it work yet?
