### ISSUE TITLE
Very Little Farm

### ISSUE THREAD

**Issue by bernardocasanova** [PokemonGoF/PokemonGo-Bot#4027]
I have recently noticed that the bot has farm very little XP. 
What's happening ? 
it`s normal? 
Obs: i have tested in to a new account.

Example: 
2016-08-15 17:08:23,382 [UpdateLiveStats] [INFO] [log_stats] Bernardocasanova | Uptime : 0:08:36 | Earned 800 Stardust | +3,600 XP | 25,099 XP/h | Visited 7 stops

**Comment by Setsu-BHMT** [comment]
If you're using the latest dev, the most likely reason is the implementation of percent chance of various ball throws.
In previous versions the bot always threw excellent throws every time; you can still do that if you want, though it is not recommended.

**Comment by jrjhealey** [comment]
Are you using a densely populated location?

**Comment by yweitkemper** [comment]
Yea I am, pier 39 in san Francisco, usually 5 lures are up in the spot I start at alone.

**Comment by icecubeice** [comment]
me too

**Comment by bernardocasanova** [comment]
@jrjhealey yes, I am in sydney.. why?

**Comment by jrjhealey** [comment]
Speed at which you'll earn XP is very dependent on where you have the bot operate. Density of Pokestops, pokemon spawns etc.

**Comment by iruy** [comment]
Yesterday I started a new account and with bot, I reached lv 20 in just one day... So, it is probably a matter of configs

**Comment by bernardocasanova** [comment]
@jrjhealey tell me one good place to operate..?

**Comment by youberser** [comment]
@bernardocasanova Im using `40.417338, -3.683095`

**Comment by jrjhealey** [comment]
I've used Santa Monica pier and times square mostly

**Comment by bernardocasanova** [comment]
@jrjhealey and @youberser which the average of your`s farm?

**Comment by youberser** [comment]
@bernardocasanova 37K/h avg.

**Comment by k4n30** [comment]
Can this discussion be taken to the slack server, as it's config related and not an actual issue with the bot
