### ISSUE TITLE
PokeStop error

### ISSUE THREAD

**Issue by Fellner96** [PokemonGoF/PokemonGo-Bot#403]
#[#] Finished walking
[#] Arrived at Pokestop
[#] Now at Pokestop: LONDON OLD LEICESTER SQUARE CH - Spinning...
[+] Loot: 
[#] Nothing found.
Traceback (most recent call last):
  File "pokecli.py", line 126, in <module>
    main()
  File "pokecli.py", line 119, in main
    bot.take_step()

**Comment by s1x** [comment]
This should be fixed with the newst master/dev branch. Please feel free the open a new issue when necessary!
