### ISSUE TITLE
[Feature Request] Make bot stay within a certain area.

### ISSUE THREAD

**Issue by GitPupper** [PokemonGoF/PokemonGo-Bot#4030]
> If this is wanted, we could add an optional config for bounding box lat-longs and have the workers check against it. - Ben St-Pierre

I was thinking of a config option that makes it where the bot stays within a certain area. An example would be the Santa Monica State Beach. If you set the bot to stay there, then it could just farm Pokemon and gain stardust/XP. Just a suggestion.

**Comment by kirikay** [comment]
this is possible if you set your config FollowPath, just place at least 2 coordinates where your bot will walk back and forth.

**Comment by Setsu-BHMT** [comment]
@kirikay Not if you define MoveToFort. If you do, and if the local density of pokestops is high enough, then you wander off into oblivion.

This would be a great addition IMO; something like a set radius from the location definition in the config.

**Comment by k4n30** [comment]
#3580
