### ISSUE TITLE
Need help with pgoapi.exceptions can't find any info on it *detailed*

### ISSUE THREAD

**Issue by Plousios** [PokemonGoF/PokemonGo-Bot#4043]
Hello, I am new and I am basically trying to get PokemonGo-Bot working and then I will tweak my config. I will do my best to summarize here and then provide any possible relevant information below
[logs.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/419256/logs.zip)
[logs.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/419257/logs.zip)
[logs.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/419262/logs.zip)

. I am running Linux Mint Rosa 17.3. I used the 'easy automatic' install method. I have a very 'beginners' understanding of coding, and python. If I had to guess the root of the problem is an incomplete install as trying to follow 'easy automatic' install method, I will point out why I think the install is complete at the bottom. Logs under 'other relevant information' at the bottom.

##When inputting command to attempt to start PokemonGo-Bot sh run.sh the following output occurs:

Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions
Mon Aug 15 16:26:23 PDT 2016 Pokebot  Stopped.
run.sh: 18: read: Illegal option -s

##When inputting command to attempt to start PokemonGo-Bot python pokecli.py the following output occurs:

Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

##When inputting command to attempt to start PokemonGo-Bot ./run.sh the following output occurs:

Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions
Mon Aug 15 16:38:35 PDT 2016 Pokebot  Stopped.

Press any button or wait 20 seconds to continue.
Before you create an Issue, please check the following:

##My config.json is set to the default parameters

{
    "auth_service": "google",
    "username": "removed to protect private info",
    "password": "removed to protect private info",
    "location": "removed to protect private info",
    "gmapkey": "removed to protect private info",
    "encrypt_location": "",
    "websocket_server": false,
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "first_evolve_by": "cp",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "min_ultraball_to_keep": 10,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "catch_throw_parameters": {
      "excellent_rate": 0.1,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.6
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

### Other Information
OS: 
<Linux Mint 17.3> 
Branch: 
<'dev' I think... not sure how to tell what this is>  *n00b* 
Git Version: 
<git 1.9.1> 
Python Version: 
<python 2.7.12> 

## Steps to reproducing issue: 
Have above OS, Branch, Git Version, Python Version + all the extra utils plus following 'easy automatic installation' method listed here: http://blog.pokemongofun.com/working-pokemongo-bot-step-by-step-07252016/#linux_mac

##What I think the problem is, occurs during 'step 2: ./setup.sh -i' *logs attached*:

----------------------------------------
Cleaning up...
Command /usr/bin/git fetch -q failed with error code 255 in /home/user/PokemonGo-Bot/src/pgoapi
Storing debug log for failure in /tmp/tmpLKGF76
Downloading/unpacking numpy==1.11.0 (from -r requirements.txt (line 1))
  Downloading numpy-1.11.0.tar.gz (4.2MB): 4.2MB downloaded
  Running setup.py (path:/home/user/PokemonGo-Bot/build/numpy/setup.py) egg_info for package numpy
    Running from numpy source directory.
    
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
Downloading/unpacking networkx==1.11 (from -r requirements.txt (line 2))
  Downloading networkx-1.11-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@a2755eb42dfe49e359798d2f4defefc97fb8163d#egg=pgoapi (from -r requirements.txt (line 3))
  Updating ./src/pgoapi clone (to a2755eb42dfe49e359798d2f4defefc97fb8163d)
error: cannot open .git/FETCH_HEAD: Permission denied

  Complete output from command /usr/bin/git fetch -q:
  
----------------------------------------
Cleaning up...
Command /usr/bin/git fetch -q failed with error code 255 in /home/user/PokemonGo-Bot/src/pgoapi
Storing debug log for failure in /tmp/tmpf1pZkk
Start to make encrypt.so.
--2016-08-15 17:08:24--  http://pgoapi.com/pgoencrypt.tar.gz
Resolving pgoapi.com (pgoapi.com)... 104.31.69.172, 104.31.68.172, 2400:cb00:2048:1::681f:44ac, ...
Connecting to pgoapi.com (pgoapi.com)|104.31.69.172|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 243633 (238K) [application/x-tar]
Saving to: ‘pgoencrypt.tar.gz’

##Log files: 'tmpLKGF76' and 'tmpf1pZkk'  *attached* Please note I also changed my user directory username in errors and logs to conceal private information: user eg. /home/user/
[logs.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/419263/logs.zip)

**Comment by Plousios** [comment]
sorry, the logs.zip are listed 4 times...

**Comment by k4n30** [comment]
Please provide Git Commit:  run 'git log -n 1 --pretty=format:"%H"' in your terminal window

Also follow our guide - https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/installation.md

I'm not sure if the guide you followed is correct or not

**Comment by Plousios** [comment]
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by mjmadsen** [comment]
Try:
`git init`

My guess is the "Easy install" script didn't work out for you - However, I am not familiar with the script (or cross platform installations), but that is my guess. @solderzzc Do you know why this might occur?

**Comment by k4n30** [comment]
@Plousios As you are relatively new, I'm going to suggest you join the slack server and ask for assistance there. Your issue is not a bot problem, but more about assistance in setting the bot up which is what the slack is there for.

https://github.com/PokemonGoF/PokemonGo-Bot#configuration-issueshelp
