### ISSUE TITLE
Fix Banning Problem

### ISSUE THREAD

**Issue by mustii82** [PokemonGoF/PokemonGo-Bot#4044]
Niantic starts to bann People who use a Bot how can we fix this issue ?

We must check how the algorithm Niantic use to recognize Bots work to make a workaround we must make some experiments to get it out.

**Comment by z4ppy** [comment]
All accounts banned here :'(

**Comment by MrCarlosJr** [comment]
my 3 accounts banned..
You use snipe functions?

**Comment by z4ppy** [comment]
Not for all
