### ISSUE TITLE
FEATURE REQUEST :Time to stop bot and resart it a while

### ISSUE THREAD

**Issue by skywalker878** [PokemonGoF/PokemonGo-Bot#4045]
Now we have sleeping scheduler. that is great.
.
i have another idea. Can we to have a feature that set a timer to schedule bot stop and have a rest?

for example:
we can set 

BotRunningTine : 120 min
BotRestTime: 30 min
TimerOffset : 15min

so bot will stop everi 105-120 min and restart after 15-30min

Thank you so much

**Comment by k4n30** [comment]
duplicate of #3894
