### ISSUE TITLE
How catch_randomize_reticle_factor and catch_randomize_spin_factor work?

### ISSUE THREAD

**Issue by bidakung** [PokemonGoF/PokemonGo-Bot#4047]
I am trying to configure bot to throw PokeBall with some error, and my config is

    "catch_randomize_reticle_factor": 0.5,
    "catch_randomize_spin_factor": 0.9,

but my bot still throw Excellent and curve ball. i dont know this is bug or misconfiguration.

Thank you.

**Comment by mjmadsen** [comment]
Those values are no longer used. 

Use the following instead
`    "catch_throw_parameters": {
      "excellent_rate": 0.1,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.6
    }`

**Comment by bidakung** [comment]
Thank you. It now works.
