### ISSUE TITLE
Not collecting stops or pokemon

### ISSUE THREAD

**Issue by yweitkemper** [PokemonGoF/PokemonGo-Bot#4049]
### Expected Behavior
 Catch pokemon / collect stops

### Actual Behavior

Running this on the latest dev doesn't seem to be doing anything but walking
] Next sleep at 2016-08-15 23:10:18.057338
2016-08-15 20:45:28,251 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-15 20:45:28,507 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-15 20:45:28,508 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 4.60 km
2016-08-15 20:45:29,938 [FollowSpiral] [INFO] [position_update] Walking from (37.80921385070496, 122.41437136679049, 0) to (37.80921385070496, 122.41437136679049, 0) (0.0 m)
2016-08-15 20:45:31,563 [FollowSpiral] [INFO] [position_update] Walking from (37.80923260923257, 122.41438501095995, 0) to (37.809844887497974, 122.41437136679049, 0) (68.0927795406 m)
2016-08-15 20:46:12,735 [FollowSpiral] [INFO] [position_update] Walking from (37.80985703341944, 122.41435270009224, 0) to (37.809844887497974, 122.41513212453977, 0) (68.4853326569 m)
2016-08-15 20:46:53,431 [FollowSpiral] [INFO] [position_update] Walking from (37.80983236413674, 122.41511256959599, 0) to (37.80921385070496, 122.41513212453977, 0) (68.7970301294 m)
2016-08-15 20:47:43,428 [FollowSpiral] [INFO] [position_update] Walking from (37.8092335338224, 122.41511082623892, 0) to (37.80858281391194, 122.41513212453977, 0) (72.3809429618 m)

Config file
 "encrypt_location": "",
    "websocket_server": false,
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "evolve_all": "Pidgey, Rattata, Weedle, Caterpie, Zubat, Golbat, Tentacool, Krabby, Spearow, Psyduck, Goldeen, Nidoran F, Nidoran M, Staryu, Paras",

            "first_evolve_by": "iv",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "min_ultraball_to_keep": 10,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "catch_throw_parameters": {
      "excellent_rate": 0.1,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.6
    },
    "release": {
		"any": {
			"keep_best_iv": 2,
			"keep_best_cp": 1,
			"release_below_cp": 2000,
			"release_below_iv": 0.1,
			"logic": "or"
		},
		"vips": {
			"Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
			"any": {
				"catch_above_cp": 1200,
				"catch_above_iv": 0.9,
				"logic": "or"
			},
			"Lapras": {},
			"Moltres": {},
			"Zapdos": {},
			"Articuno": {},

			"// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
			"Mewtwo": {},
			"Dragonite": {},
			"Snorlax": {},
			"// Mew evolves to Mewtwo": {},
			"Mew": {},
			"Arcanine": {},
			"Vaporeon": {},
			"Gyarados": {},
			"Exeggutor": {},
			"Muk": {},
			"Weezing": {},
			"Flareon": {}

		}
	}
}

### Other Information
OS: IOS
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by mjmadsen** [comment]
You're probably softbanned and can't see any pokemon, gyms or stops. Try the account again in 24 hours.

**Comment by yweitkemper** [comment]
It seems to work fine on my phone now, just the bot doesn't work.

**Comment by dutchiexl** [comment]
Same here, the mobile app works, but the Bot doesn't collect stops or pokemon.

**Comment by dutchiexl** [comment]
Also the desktop stable build has the same issue, it seems like somehow they are stopping the bot from receiving information
