### ISSUE TITLE
Password containing special chars (!;:'.,)

### ISSUE THREAD

**Issue by TimmD** [PokemonGoF/PokemonGo-Bot#405]
### Expected Behavior
Password containing these special chars to login

### Actual Behavior
Password containing these special chars, returns an login/wrong password error

**Comment by VirtualSatai** [comment]
Have you tried putting it in quotes or using the config.json file?

**Comment by jtdroste** [comment]
What @VirtualSatai said is correct.  Please put your password in quotes, or inside the config.json file.

Closing.
