### ISSUE TITLE
Better form of choosing between accounts.

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#4056]
Something like this will help us with multiple accounts. Just change one line of code can choose between accounts instead of 3 now.
"
  <AuthType: Google/Ptc
  <PtcPassword:
  <PtcUsername:
  <GoogleUsername:
  <GooglePassword:
"

**Comment by avexus** [comment]
Is this not a legit feature?

**Comment by k4n30** [comment]
The second half wasn't there when I closed the issue

**Comment by rawgni** [comment]
wouldn't separate auth files be better ?

The auth file will only contain:
- auth_type
- user
- password
- gmapkey
- location (maybe?)

**Comment by Faithu** [comment]
He's got this off another bot? I have the other bot he took this from :/

**Comment by LuckyMe4Evers** [comment]
Rename your config.json to namebot.json
then use 
python pokecli.py -cf ./configs/namebot.json 
and you can run all of your bots

**Comment by k4n30** [comment]
You're going to have issues, syncing the detail in them without making changes to both every time a change is made, or regularly doing a diff. I think this request is a valid one, whether someone takes it on is a different story

**Comment by avexus** [comment]
Yes, I saw this from another bot and saw it has some good point.
I could use separate files. Not of high priority.

**Comment by avexus** [comment]
I like what you did to separate auth and config.
