### ISSUE TITLE
Probably permabanned, Game Over for any account

### ISSUE THREAD

**Issue by alxnegrila** [PokemonGoF/PokemonGo-Bot#4059]
Getting **Probably permabanned, Game Over ! Play again at https://club.pokemon.com/us/pokemon-trainer-club/sign-up/** for any account I try.

**Comment by oleerik** [comment]
Huh, what exactly is the issue?

**Comment by alxnegrila** [comment]
Are statuses interpreted correctly for d4200e9b34ef6ec9826eb81a6ceb420162b8c674?

**Comment by k4n30** [comment]
Please use the issue template

**Comment by MZorzy** [comment]
Me too
