### ISSUE TITLE
Sniniping Documentation Clarification

### ISSUE THREAD

**Issue by MatteCarra** [PokemonGoF/PokemonGo-Bot#4060]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md#sniping-movetolocation

max_distance - Maximum distance the pokemon is allowed to be when walking, ignored when sniping

Default is 500 but I can't understand the unit!

(It's understandable but not obvious)

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot#configuration-issueshelp

**Comment by Raiven66** [comment]
I understand he wanted to point out the documentation being unclear rather to ask for help setting it up
