### ISSUE TITLE
Help offered: moderate issues

### ISSUE THREAD

**Issue by consti** [PokemonGoF/PokemonGo-Bot#4064]
Hey there!

I'd like to offer some help with moderating the issues/taking care of some of the comments.
I might be a little more "aggressive" in locking conversations, but it looks like that's needed - there are a lot of comments such as "I got banned" that are not part of the ticket. Happy to clean that up.

@Dracon23 (kaltenstein on slack) also offered his help.

No worries of no help is needed - feel free to close/delete this ticket.
Thanks!

**Comment by k4n30** [comment]
Hey @consti we just got a bunch of new moderators (myself included) who are slowly wading through the issues. Good news is we are making progress :)

I have no issue with the random comments unless they are completely off topic, it's more about educating people than being aggressive. Now that we have a better issue template we need to see if it changes issues.  As for your offer to help, I'm not the person to make that decision, but you'd probably be better off starting to help in the slack server and you will get noticed by the admins and will be approached if required :)

**Comment by consti** [comment]
@k4n30 thanks for finding the time to reply! 👍 

I concur with everything you said. I'd just like to keep the amount of "same issue here" or "unrelated question, that should go in a separate ticket" comments low.

Conversations could be locked / or have an automatic comment on the top with a notice that you can subscribe to conversations if you want to get updates on them, you can add emoticons to comments to show that you have the same issue/agree and that you should create a new ticket if you feel like it's important to address another issue.

Maybe it helps if I update the README and push the "Installation" and "FAQ" up a little bit - currently they are hidden away in the "Table of Contents" section (whereas the Slack channel and dev/master info is coming first).

Maybe this is also all a non-existing issue and I should spend my time more wisely ;)

**Comment by k4n30** [comment]
Pull requests are more than welcome. I've tried cleaning up the support a bit and more ideas are welcome :)

**Comment by Dracon23** [comment]
@k4n30 : We're trying to cull the random troll on slack already, and help where possible (I've run the bot for a small while, working on a different project for mainly my own consumption in the meantime.). 
Reason we offered to help is the influx of people who absolutely have no idea, what they're doing and why they're doing it. The important issues seem to get lost a bit... If you guys need any form of help, just give us a shout ;P

**Comment by k4n30** [comment]
@Dracon23 no worries, like I said to consti, I don't get to make the decisions

We're starting to get the issues here on GitHub under control, and weed out all the random support stuff which is not bug related, and I (my opinion only) don't see us needing any more assistance. I don't, however, participate much in the slack (other than the admin channels), my only suggestion would be to update the [FAQ](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/faq.md) that consti suggested to include some of the more common issues you're seeing in the slack (where to get the dll, common errors etc)
