### ISSUE TITLE
[Instant softban feature] Bot jumps from Germany to Phoenix Arizona when using -lc flag 

### ISSUE THREAD

**Issue by ckrmml** [PokemonGoF/PokemonGo-Bot#407]
### Expected Behavior
Bot starts where i exited it

### Actual Behavior
Bot jumps to Phoenix Arizona. This are like 8971 km (5574 miles) and i get softbanned all the way
one-time 8971km jump: approx. 1713.05 seconds banned (it's the pokestop cooldown time)
triple-time 8971km jump: approx. 36742.75 seconds banned
this really sucks hard

### Steps to Reproduce
Use Bot with -lc flag

### Other Information
OS: OSX
Git Commit: b82fc63ec8a367f2e8c75155923ca0d743246e4b

**Comment by Skeyelab** [comment]
how are you getting your ban time?

**Comment by ckrmml** [comment]
I simply assume the pokestop cooldowntime equals bantime

**Comment by gregtampa** [comment]
teleporting gets you softban...
we have a feature already in works to solve this
