### ISSUE TITLE
Defined number of loop in the path navigator mode

### ISSUE THREAD

**Issue by rladlb** [PokemonGoF/PokemonGo-Bot#4072]
### Short Description
When we use the path navigator loop mode the bot do an infinity loop. 
to reducing the bot detection, we can defined a number of loop and stop the bot after

### Possible solution
We can defined a number of loop and stop the bot after

### How it would help others
 Reducing the bot detection

**Comment by alexyaoyang** [comment]
I'm thinking limiting the total distance travelled would be a better option? Since everyone using paths may have difference sized loops. In this case this issue is related to #3922 and #4019 but limit with distance travelled.
