### ISSUE TITLE
What am I doing wrong ?

### ISSUE THREAD

**Issue by Drole2Type** [PokemonGoF/PokemonGo-Bot#4073]
Hi all !

I'm french, so I'll do my best to speak english and hope you'll understand what I try to explain :dancer: 

I'm on Windows Vista, I Downloaded every requested program before installation, and no problem.

I DLed PokemonGo-Bot-Install.bat, then I edited configs/config.json and web/config.userdata.js, with my username and API key ... ALRIGHT ... I THINK I DID IT RIGHT !!!

Now, when I run PokemonGo-Bot-Start.bat, I have this message : 

> Serving HTTP on 0.0.0.0 port 8000 . . .

and when I open http://http://127.0.0.1:8000 I get this : 

> 127.0.0.1 - - [16/Aug/2016 14:38:56] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2016 14:38:56] "GET /css/main.css HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2016 14:38:57] "GET /config/userdata.js HTTP/1.1" 200 -
127.0.0.1 - - [16/Aug/2016 14:38:57] "GET /js/main.js HTTP/1.1" 200 -

and I only have a white page with a settings menu on Firefox (with "pan" "zoom" and "bot path", with on/off on each, and a LOGS button ... But nothing else happens ...

Can someone try to help me please. I went on the slack chat, #help, some users tried to help me (thanks guys !!!) but we didn't find where it came from ...

HELP ME PLEASE !!!

**Comment by k4n30** [comment]
Wait... did you say Vista? That's a blast from the past

Please use the issue template that you would have highlighted and deleted to create this issue otherwise, we are unable to help you

**Comment by vamirineni87** [comment]
in the web\config directory, there is a userdata.js.example. make a copy and rename it userdata.js and fill in required details.

**Comment by Drole2Type** [comment]
@k4n30 : This is supposed to work on Vista isn't it ? 

@vamirineni87 : I already did that (it's specified in my initial post)

**Comment by k4n30** [comment]
Issue template please

**Comment by Drole2Type** [comment]
I'm doing it ... But my english isn't perfect, sorry.
