### ISSUE TITLE
Possible info in "UpdateLiveStats"

### ISSUE THREAD

**Issue by xyc1993** [PokemonGoF/PokemonGo-Bot#4076]
Hi!
What kind of information can I get via "UpdateLiveStats"?
Can I have my bot's current coordiantes? If yes then how? I'd like to see the path that my bot takes.
So far I have this:

{
        "type": "UpdateLiveStats",
        "config": {
          "enabled": true,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited", "pokemon_caught", "captures_per_hour", "km_walked"],
          "terminal_log": true,
          "terminal_title": true
        }
      }

When I put in stats "locations", "position", "latitude", "longitude" I get an error so that doesn't work.

**Comment by Nerkyator** [comment]
From comment in code:

```
    Available stats :
    - login : The account login (from the credentials).
    - username : The trainer name (asked at first in-game connection).
    - uptime : The bot uptime.
    - km_walked : The kilometers walked since the bot started.
    - level : The current character's level.
    - level_completion : The current level experience, the next level experience and the completion
                         percentage.
    - level_stats : Puts together the current character's level and its completion.
    - xp_per_hour : The estimated gain of experience per hour.
    - xp_earned : The experience earned since the bot started.
    - stops_visited : The number of visited stops.
    - pokemon_encountered : The number of encountered pokemon.
    - pokemon_caught : The number of caught pokemon.
    - captures_per_hour : The estimated number of pokemon captured per hour.
    - pokemon_released : The number of released pokemon.
    - pokemon_evolved : The number of evolved pokemon.
    - pokemon_unseen : The number of pokemon never seen before.
    - pokemon_stats : Puts together the pokemon encountered, caught, released, evolved and unseen.
    - pokeballs_thrown : The number of thrown pokeballs.
    - stardust_earned : The number of earned stardust since the bot started.
    - highest_cp_pokemon : The caught pokemon with the highest CP since the bot started.
    - most_perfect_pokemon : The most perfect caught pokemon since the bot started.
```

**Comment by xyc1993** [comment]
So no current position? (I'm asking because that's the most vital stat I need to get)

**Comment by Nerkyator** [comment]
Exactly, no current position at this time (just checked code)

**Comment by xyc1993** [comment]
:(
But thanks for the answer.

**Comment by k4n30** [comment]
@xyc1993 You could create a feature request for this functionality as there are already numerous FR for similar updates to live stats

**Comment by avexus** [comment]
@Nerkyator Thank you. I was looking for that info too.
