### ISSUE TITLE
Keep best 2 attack pokemon

### ISSUE THREAD

**Issue by Tagada22** [PokemonGoF/PokemonGo-Bot#4084]
Hello 

Its possible to keep pokemon with the bestet attack 

Exemple :

Dragonite  :

Dragon claw :  35
Dragon : dragon pulse : 65 

Transfert pokemon 

Dragon claw : 35

Hyper beam : 120 

Keep pokemon 

http://www.pokemongodb.net/2016/05/dragonite.html?m=1

Combined this setting and iv 100% we can have the most powerful pokemon.

Maybe options is already implanted or next feature ?

**Comment by Anakin5** [comment]
You can use "dps" as a sorting order in Pokemon optimizer. Check if it fits your need.

**Comment by k4n30** [comment]
What determines the best attack in your mind @Tagada22 ? DPS as Anakin mention, or highest number is best?

**Comment by tolinwei** [comment]
Gym fighting is not just a matter of attack value, some secondary moves have longer "Dodge Window", that allows players to dodge the still easier; some moves have lower attack value but higher DPS, which generates more damage.
Check out the link here: https://pokemongo.gamepress.gg/pokemon/149
For Dragonite, **Dragon Claw** has lowest "attack value" - 35, but it has hightest DPS, which is the best for attacking.

**Comment by Foulwerp** [comment]
You can use dps_defense and dps_attack not sure how accurately these are calculated though.

dps_defense I believe would be the best for defending a gym, and the other is attacking a gym. 

I think the AI for gym defense needs a rework, Since they don't dodge and can attack only every 2 seconds makes most gyms with enough time a push over.

```
                if keep_best_dps >= 1:
                    dps_limit = keep_best_dps
                    best_dps_pokemons = sorted(group, key=lambda x: (x.moveset.dps, x.iv, x.cp), reverse=True)[:dps_limit]
                    best_pokemon_ids |= set(pokemon.id for pokemon in best_dps_pokemons)
                    order_criteria = 'Moveset DPS'   
                    
                if keep_best_dps_defense >= 1:
                    dps_limit = keep_best_dps_defense
                    best_dps_pokemons = sorted(group, key=lambda x: (x.moveset.dps_defense, x.iv, x.cp), reverse=True)[:dps_limit]
                    best_pokemon_ids |= set(pokemon.id for pokemon in best_dps_pokemons)
                    order_criteria = 'Defensive Moveset DPS'   
                    
                if keep_best_dps_attack >= 1:
                    dps_limit = keep_best_dps_attack
                    best_dps_pokemons = sorted(group, key=lambda x: (x.moveset.dps_attack, x.iv, x.cp), reverse=True)[:dps_limit]
                    best_pokemon_ids |= set(pokemon.id for pokemon in best_dps_pokemons)
                    order_criteria = 'Offensive Moveset DPS'
```
Not sure how well this would work.

I don't know python very well but if you could define the key to sort by in the config for each pokemon then use that key it could be neat. 

For example...

```
            "Charmander": { 
                "keep_best_custom": "dps_attack,iv,cp", 
                "amount": 2
            }
```

**Comment by supercourgette** [comment]
On the dev branch, you can now keep your Pokemons according to a selection of your own criteria among: 'cp','iv', 'iv_attack', 'iv_defense', 'iv_stamina', 'moveset.attack_perfection', 'moveset.defense_perfection', 'hp', 'hp_max'. Check the docs and let me know if it's working and answer your question. ;)

**Comment by k4n30** [comment]
@supercourgette is this pokemonoptimizer?

**Comment by supercourgette** [comment]
No I haven't touched yet at pokemonoptimizer. It was done in transfer pokemon. Should I have done it in pokemonoptimizer?

**Comment by k4n30** [comment]
@supercourgette no I was asking as I hadn't noticed this change yet. Can you link to the PR or commit the change was made in please, and then we'll close this issue

**Comment by supercourgette** [comment]
I'm not sure if this is exactly Tagada22 asked for since this feature haven't been tested by users yet and I'm a bit confuse about the meaning of moveset.defense_perfection and moveset.attack_perfection.

**Comment by k4n30** [comment]
@Tagada22 Can you review latest dev and see if it meets your needs
