### ISSUE TITLE
zero pokestops visited in FollowCluster mode

### ISSUE THREAD

**Issue by WernonX** [PokemonGoF/PokemonGo-Bot#4086]
### Expected Behavior

in cluster mode bot should spin all near pokestops every 5+ minutes

### Actual Behavior

i did 31m test in FollowCluster, bot visited 0 pokestops

2016-08-16 15:15:21,210 [PokemonGoBot] [INFO] Pokemon Captured: 5739 | Pokestops Visited: 5703
2016-08-16 15:15:43,951 [FollowCluster] [INFO] [arrived_at_cluster] Arrived at cluster. 5 are in a range of 50m radius.

...
captured 25 pokemons ...
...

2016-08-16 15:46:12,446 [PokemonGoBot] [INFO] Pokemon Captured: 5764 | Pokestops Visited: 5703
### Your FULL config.json (remove your username, password, gmapkey and any other private info)

{
    "auth_service": "google",
    "username": "",
    "password": "",
    "libencrypt_location": "",
    "websocket_server": false,
    "// location": "",
    "gmapkey": "",
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "none",
            "// evolve_all": "Pidgey,Weedle,Caterpie,Rattata,Drowzee,Zubat,Goldeen,Spearow,Clefairy,Venonat,Staryu,Psyduck,Shellder,Magikarp,Poliwag,Slowpoke,Goldeen,Growlithe,Tentacool,Pikachu,Paras,Jigglypuff,Nidoran F,Nidoran M,Krabby,Exeggcute,Cubone,Horsea,Koffing,Mankey",
            "first_evolve_by": "cp",
            "evolve_above_cp": 10,
            "evolve_above_iv": 0.1,
            "logic": "or",
            "evolve_speed": 25,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "max_balls_keep": 300,
          "max_potions_keep": 0,
          "max_berries_keep": 120,
          "max_revives_keep": 10,
          "item_filter": {
            "Pokeball":       { "keep" : 200 },
            "Greatball":      { "keep" : 120 },
            "Ultraball":      { "keep" : 120 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 0 },
            "Hyper Potion":   { "keep" : 5 },
            "Max Potion":     { "keep" : 10 },
            "Revive":         { "keep" : 10 },
            "Razz Berry":     { "keep" : 80 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "FollowCluster",
        "config": {
            "enabled": true,
            "radius": 50,
            "lured": true
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "walk_max": 6.16,
    "walk_min": 4.16,
    "// walk": 4.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "// location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "min_ultraball_to_keep": 10,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "catch_throw_parameters": {
      "excellent_rate": 0.1,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate": 0.6
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"}
    },

    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}

### Other Information
OS: 
 linux
Branch: debian
 master
Git Commit: 
 52495aee0cd0882077270c9c3ed9445bcee31f4d
Python Version: 
 Python 2.7.12+
Any other relevant files/configs (eg: path files)

**Comment by k4n30** [comment]
Waiting on #4115
