### ISSUE TITLE
Bot does not spin fort when looping around configured path and bot not using ultraball

### ISSUE THREAD

**Issue by d0ntchadon** [PokemonGoF/PokemonGo-Bot#4087]
### Expected Behavior
Bot spins fort,
Bot uses ultraball when no pokeball or greatball available

### Actual Behavior
I configured the bot to loop around 7 pokestops.

Bot is not spinning fort
Bot reports no pokeballs usable. Inventory has 68ultraballs but 0/0 pokeball/greatball.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

     {
        "type": "SpinFort"
      },
      {
        "type": "FollowPath",
        "config": {
          "path_mode": "loop",
          "path_start_mode": "first",
          "path_file": "configs/path.json"
        }
      }

### Output when issue occurred
[PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Psyduck appeared! [CP 305] [Potential 0.11] [A/D/S 0/5/0]
[PokemonCatchWorker] [INFO] [no_pokeballs] No usable pokeballs found!

### Other Information
OS:  ubuntu 64bit
Branch:  dev
Git Commit: 
0937029fb07ad3eb0d7198e696626e82fe7cff0e
Python Version: 
Python 2.7.12

**Comment by PokemonGoZ** [comment]
#3421 #3683 #3760 #3861 #3107
