### ISSUE TITLE
UpdateLiveStats Caching Username

### ISSUE THREAD

**Issue by JonnyBoy333** [PokemonGoF/PokemonGo-Bot#4091]
### Expected Behavior
Log shows correct username for the bot that is running.

### Actual Behavior
Log shows username of a previous account that was used but is no longer being used anymore.

### Steps to Reproduce
Run the bot using different logins (input as parameters in the terminal command), then use different accounts another day and the log is still showing the username of the previous accounts. Seems like the usernames are getting cached somewhere and not cleared out when a new instance of the bot is run.  Maybe I can remove them manually so they are recreated?

### Other Information
OS: OSX
Branch: dev

**Comment by BriceSD** [comment]
Please add the exact commit you’re using

**Comment by mjmadsen** [comment]
@JonnyBoy333 Still an issue?

**Comment by JonnyBoy333** [comment]
I'll shut it down for now, will need to test more when I get a chance.
