### ISSUE TITLE
"UpdateLiveStats" inventory info

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#4092]
I would like to have info on how many Pokeballs/Great Balls/Razz Berry we have right now.
But it's not in "UpdateLiveStats", I think.
Also, is there a way that this info can have a line break?

**Comment by BriceSD** [comment]
#3950

**Comment by TheCannings** [comment]
In addition to this, i'm not sure if i'm not just missing it but would we be able to get distance to egg hatch as a live stat?

**Comment by k4n30** [comment]
@TheCannings you would be better off making a new feature request as this is just waiting on being merged and will be closed as soon as it is

**Comment by TheCannings** [comment]
ahh thanks @k4n30 new to all this git jazz, have created it #4150
