### ISSUE TITLE
Bot just seems to walk.

### ISSUE THREAD

**Issue by yweitkemper** [PokemonGoF/PokemonGo-Bot#4096]
### Expected Behavior
Catch Pokemon and collect Pokestops

### Actual Behavior  
Bot just walks, have tried two separate internet connections to change up the IP and it works fine on my phone so not banned. Been doing this for 2 days now. On the newest Dev. 

2016-08-16 09:41:31,347 [PokemonGoBot] [INFO] 
2016-08-16 09:41:31,347 [PokemonGoBot] [INFO] Found encrypt.so! Platform: darwin Encrypt.so directory: /Users/naturalhealingways/PokemonGo-Bot
2016-08-16 09:41:31,347 [PokemonGoBot] [INFO] 
2016-08-16 09:41:33,519 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-16 22:42:26.519783
2016-08-16 09:41:34,002 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-16 09:41:34,616 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-16 09:41:34,617 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 4.60 km
2016-08-16 09:41:35,538 [FollowSpiral] [INFO] [position_update] Walking from (37.80798794405108, 122.414544738114, 0) to (37.80798794405108, 122.414544738114, 0) (0.0 m)
2016-08-16 09:41:37,146 [FollowSpiral] [INFO] [position_update] Walking from (37.80796391471999, 122.41456285704399, 0) to (37.80861895802825, 122.414544738114, 0) (72.854840342 m)
2016-08-16 09:42:29,786 [FollowSpiral] [INFO] [position_update] Walking from (37.80861103198898, 122.41455569145666, 0) to (37.80861895802825, 122.41530749937095, 0) (66.052910028 m)
2016-08-16 09:43:15,750 [FollowSpiral] [INFO] [position_update] Walking from (37.80863524443925, 122.41532955854959, 0) to (37.8079

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

This is my config file 
  "auth_service": "google",
 
	,
    "encrypt_location": "",
    "websocket_server": false,
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
           {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "evolve_all": "Pidgey, Rattata, Weedle, Caterpie, Zubat, Golbat, Tentacool, Krabby, Spearow, Psyduck, Goldeen, Nidoran F, Nidoran M, Staryu, Paras",

            "first_evolve_by": "iv",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "min_ultraball_to_keep": 10,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "catch_throw_parameters": {
      "excellent_rate": 0.1,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.6
    },
    "release": {
		"any": {
			"keep_best_iv": 2,
			"keep_best_cp": 1,
			"release_below_cp": 2000,
			"release_below_iv": 0.1,
			"logic": "or"
		},
		"vips": {
			"Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
			"any": {
				"catch_above_cp": 1200,
				"catch_above_iv": 0.9,
				"logic": "or"
			},
			"Lapras": {},
			"Moltres": {},
			"Zapdos": {},
			"Articuno": {},

			"// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
			"Mewtwo": {},
			"Dragonite": {},
			"Snorlax": {},
			"// Mew evolves to Mewtwo": {},
			"Mew": {},
			"Arcanine": {},
			"Vaporeon": {},
			"Gyarados": {},
			"Exeggutor": {},
			"Muk": {},
			"Weezing": {},
			"Flareon": {}

		}
	}
}

### Other Information
OS: IOS
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by Tujin** [comment]
Did you resolve this? I'm having the same issue.

**Comment by yweitkemper** [comment]
nah i didn't, i just deleted everything and started over. Now I'm having way different issues though lol
