### ISSUE TITLE
[BUG] future_pokemon_release does not work as defined

### ISSUE THREAD

**Issue by rendyep** [PokemonGoF/PokemonGo-Bot#4098]
```JSON
"release": {
      "any": {"release_below_cp": 500, "release_below_iv": 0.8, "logic": "or"},
}
```

```BASH
[TransferPokemon] [INFO] [future_pokemon_release] Releasing Magmar [CP 1353] [IV 0.64] based on rule: CP < 500 OR IV < 0.8
[TransferPokemon] [INFO] [pokemon_release] Exchanged Magmar [CP 1353] [IV 0.64] for candy.
```

If I'm not mistaken, the future_pokemon_release logic does not work as defined. CP 1353 and IV 0.64 must not be released with the config above.

**Comment by justinbeatz** [comment]
Your logic operator is "or", so the code works as expected, it should be "and".

Release if cp < 500 OR iv < 0.8
Magmar iv = 0.64

**Comment by rendyep** [comment]
Hi, @justinbeatz, I'm actually a programmer, and of course I'm familiar with AND and OR logics.
Could you please read [logical expressions](http://www.cs.utah.edu/~germain/PPS/Topics/truth_tables_and_logic.html) for more information about why future_pokemon_release works incorrectly and how it should work.

Here are examples:
#1 OR
Release if CP < 500 OR IV < 0.8
Magmar => CP 1353, IV 0.64
Hence Magmar should not be released because it satisfy one of the given conditions.

#2 AND
Release if CP < 500 AND < 0.8
Magmar => CP 1353, IV 0.64
Hence Magmar should be released because he doesn't satisfy one of the given conditions.

**Comment by Setsu-BHMT** [comment]
@rendyep You are confused. You are interpreting the logical conditions as if they were "keep" instead of "release".

Example:
"Release if CP < 500 OR IV < 0.8" means that:
1. CP501 IV0.8 is kept
2. CP499 IV0.8 is released
3. CP501 IV0.79 is released

**Comment by avexus** [comment]
@rendyep 
Release if (CP < 500 OR IV < 0.8)
Magmar => CP 1353, IV 0.64
It should BE released, because inside () evaluate to ture.
