### ISSUE TITLE
Can't start the bot / Discord?

### ISSUE THREAD

**Issue by alexanderrock** [PokemonGoF/PokemonGo-Bot#41]
Just updated the Bot, it shows the following error:

Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'

Can you add the link to discord in the readme?

**Comment by ironbishop** [comment]
Maybe this blockstack/pybitcoin/issues/28 is the same issue, and https://github.com/blockstack/pybitcoin/commit/5386e2c383c1e62814ccf931e2b8cea0a38a8229 can be the solution, or just get Python >2.7.9

**Comment by Boren** [comment]
+1 on the discord channel. I keep writing code and ready to submit a PR only to find out someone else just commited the same thing.

**Comment by jtdroste** [comment]
We have a slack channel right now - please join!

**Comment by Brown-amazingness** [comment]
@jtdroste the slack heroku doesn't work though. I've tried countless emails and no avail :/

**Comment by jtdroste** [comment]
Try again @Brown-amazingness .  We got rate limited by slack, but it was just lifted!
