### ISSUE TITLE
Exchanging all for candy

### ISSUE THREAD

**Issue by rwwagner90** [PokemonGoF/PokemonGo-Bot#410]
### Expected Behavior
Not exchanging all for candy and correctly adhering to `--cp`

### Actual Behavior
Running with `--cp 100` is still transferring all Pokemon

### Steps to Reproduce
Use the `--cp` flag

### Other Information
OS: OS X 10.11.5
Git Commit: 6681d7c10ad3e694db62b9dd0a10f6b1bac918d3

**Comment by anonymouslulz22** [comment]
same happening with me i gave --cp 500 but it transfers pokemons of more than that cp also -c also does the same although -iv works for me

**Comment by tzull** [comment]
@anonymouslulz22 how we know IV potential set? because i got CP 900 with Potential 0.7 and another pokemon with CP 125 with potential 0.9.
