### ISSUE TITLE
New kind of ban?

### ISSUE THREAD

**Issue by winstonnolten** [PokemonGoF/PokemonGo-Bot#4102]
All pokemons flee, but stops work. is this because i copied the bot folder from someone else so we share the same device and deviceID?

**Comment by chuenlok** [comment]
you may have a look on this issue. #3977

**Comment by yoot55** [comment]
This started happening about a week ago. It's their new 'soft' ban. 
You might be lucky and get unsoft banned, or it might escalate to a perma ban. 
I wouldn't really suggest botting with it that much, just check once in a while to see if the soft ban is lifted.

**Comment by incmve** [comment]
I had the same thing, removed the capture pokemon part of my config and ran the bot again.
After visiting a pokestop the softban was removed and I put the capture part back in the config.

**Comment by DBa2016** [comment]
There is a cap of 1k Pokemons per 24 hours. If you exceed it, all pokemons will flee until you are well under that limit again. Google for "catchflee".

**Comment by oleerik** [comment]
Why the thumbs down for @DBa2016 ? I believe he is right.

**Comment by PokemonGoZ** [comment]
@oleerik It's an IP ban. (like a regular softban where you spin the pokestop 40 times) you have to throw 10+ pokeballs at the pokemon (without it hitting).

**Comment by PokemonGoZ** [comment]
#4111
