### ISSUE TITLE
Config file / tasks setting for restocking items (no capture-mode)

### ISSUE THREAD

**Issue by subzerofun** [PokemonGoF/PokemonGo-Bot#4103]
### Short Description
I would like to see an example config that was written for just stocking up on items. When i´m using the bot with the PokemonGo-Map config file (config.json.map.example) i quickly run out of Razz Berries and Greatballs because my map simply shows too much pokemon. So the bot uses more items than it can get from the pokestops because it´s constantly jumping to every capturing opportunity.

How can i disable all the catching tasks, so that the bot only goes from pokestop to pokestop collecting items (maybe for a certain time or until the items are filled up again)? Do i have to just delete the parts from the config json with "catch", "release" and "vips"? Or do i have to add a specific value (bool?) to the `"type": "CatchVisiblePokemon"` and `"type": "CatchLuredPokemon"`?

Is it possible to specify a task to skip catching alltogether when the items (balls and razz berries) get under a certain threshold?

### Possible solution
Maybe just delete `"type": "CatchVisiblePokemon"` and `"type": "CatchLuredPokemon"` from the tasks section in the config file.

### How it would help others
It would help counteracting failed captures of rare pokemon if you don´t have the necessary amount of items to retry a throw.

**Comment by DanielVolz** [comment]
Interesting, I have the opposite "problem", I discard more Pokeballs than I can catch Pokemon, but yes. Just delete the "CatchVisiblePokemon" and "CatchLuredPokemon" workers form the config and the bot should just go to the stops.
