### ISSUE TITLE
Bot isn't starting, Newest dev

### ISSUE THREAD

**Issue by yweitkemper** [PokemonGoF/PokemonGo-Bot#4104]
### Expected Behavior
Run the bot

### Actual Behavior
Press any button or wait 20 seconds to continue.
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
  File "/Users/naturalhealingways/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/Users/naturalhealingways/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/Users/naturalhealingways/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 47, in <module>
    from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, generateLocation1, generateLocation2, generateRequestHash, f2i
  File "/Users/naturalhealingways/PokemonGo-Bot/src/pgoapi/pgoapi/utilities.py", line 30, in <module>
    import xxhash
ImportError: No module named xxhash
Tue Aug 16 11:46:13 PDT 2016 Pokebot  Stopped.

##

 "encrypt_location": "",
    "websocket_server": false,
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
           {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "evolve_all": "Pidgey, Rattata, Weedle, Caterpie, Zubat, Golbat, Tentacool, Krabby, Spearow, Psyduck, Goldeen, Nidoran F, Nidoran M, Staryu, Paras",

            "first_evolve_by": "iv",
            "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          }
        }
      },
      {
        "type": "CatchVisiblePokemon"
      },
      {
        "type": "CatchLuredPokemon"
      },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "min_ultraball_to_keep": 10,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "catch_throw_parameters": {
      "excellent_rate": 0.1,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.6
    },
    "release": {
		"any": {
			"keep_best_iv": 2,
			"keep_best_cp": 1,
			"release_below_cp": 2000,
			"release_below_iv": 0.1,
			"logic": "or"
		},
		"vips": {
			"Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
			"any": {
				"catch_above_cp": 1200,
				"catch_above_iv": 0.9,
				"logic": "or"
			},
			"Lapras": {},
			"Moltres": {},
			"Zapdos": {},
			"Articuno": {},

			"// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
			"Mewtwo": {},
			"Dragonite": {},
			"Snorlax": {},
			"// Mew evolves to Mewtwo": {},
			"Mew": {},
			"Arcanine": {},
			"Vaporeon": {},
			"Gyarados": {},
			"Exeggutor": {},
			"Muk": {},
			"Weezing": {},
			"Flareon": {}

		}
	}
}

### Other Information
OS:  IOS
 
Branch: Dev
Git Commit:  abb8570f3e0ddb95ad8eab3b2e24b5aa9e995256
 
Python Version:  2.7.12

**Comment by xSidewinderx** [comment]
run pip install -r requirements.txt

**Comment by yweitkemper** [comment]
Oh thought i did, guess it didn't go thru getting this error. 

(PokemonGo-Bot) Yannics-MacBook-Air:PokemonGo-Bot naturalhealingways$ pip install -r requirements.txt
-bash: /Users/naturalhealingways/PokemonGo-Bot/bin/pip: /Users/naturalhealingways/PokemonGo-Bot/bin/python2.7: bad interpreter: Too many levels of symbolic links
(PokemonGo-Bot) Yannics-MacBook-Air:PokemonGo-Bot naturalhealingways$ pip install --upgrade -r requirements.txt
-bash: /Users/naturalhealingways/PokemonGo-Bot/bin/pip: /Users/naturalhealingways/PokemonGo-Bot/bin/python2.7: bad interpreter: Too many levels of symbolic links

**Comment by yweitkemper** [comment]
Managed to fix that problem, not I'm just getting 

Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions
Tue Aug 16 12:03:14 PDT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by gfreivasc** [comment]
Try deleting the pgoapi folder inside /src/, then run `pip install -r requirements.txt` again.

**Comment by yweitkemper** [comment]
Still getting the same error

**Comment by DanielVolz** [comment]
try `source bin/activate` in the pogo-bot dir.

**Comment by yweitkemper** [comment]
Already tried that

**Comment by DanielVolz** [comment]
try source bin/activate and then pip install -r requirements.txt

**Comment by yweitkemper** [comment]
Did that to, this is the whole log. I saw there is a error at the end of pip install maybe that could be it. 

Last login: Tue Aug 16 13:17:59 on ttys000
Yannics-MacBook-Air:~ naturalhealingways$ cd PokemonGo-Bot  
Yannics-MacBook-Air:PokemonGo-Bot naturalhealingways$ virtualenv .  
New python executable in /Users/naturalhealingways/PokemonGo-Bot/bin/python
Installing setuptools, pip, wheel...done.
Yannics-MacBook-Air:PokemonGo-Bot naturalhealingways$ source bin/activate  
(PokemonGo-Bot) Yannics-MacBook-Air:PokemonGo-Bot naturalhealingways$  pip install -r requirements.txt
Collecting numpy==1.11.0 (from -r requirements.txt (line 1))
  Using cached numpy-1.11.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting networkx==1.11 (from -r requirements.txt (line 2))
  Using cached networkx-1.11-py2.py3-none-any.whl
Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@a2755eb42dfe49e359798d2f4defefc97fb8163d#egg=pgoapi (from -r requirements.txt (line 3))
  Skipping because already up-to-date.
Collecting geopy==1.11.0 (from -r requirements.txt (line 4))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==3.0.0b4 (from -r requirements.txt (line 5))
  Using cached protobuf-3.0.0b4-py2.py3-none-any.whl
Collecting requests==2.10.0 (from -r requirements.txt (line 6))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 7))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 8))
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 9))
Collecting googlemaps==2.4.4 (from -r requirements.txt (line 10))
  Using cached googlemaps-2.4.4-py2-none-any.whl
Collecting colorama==0.3.7 (from -r requirements.txt (line 11))
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting enum34==1.1.6 (from -r requirements.txt (line 12))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting pyyaml==3.11 (from -r requirements.txt (line 13))
  Using cached PyYAML-3.11.zip
Collecting haversine==0.4.5 (from -r requirements.txt (line 14))
Collecting polyline==1.3.1 (from -r requirements.txt (line 15))
  Using cached polyline-1.3.1-py2.py3-none-any.whl
Collecting python-socketio==1.4.2 (from -r requirements.txt (line 16))
Collecting flask==0.11.1 (from -r requirements.txt (line 17))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting socketIO_client==0.7.0 (from -r requirements.txt (line 18))
Collecting eventlet==0.19.0 (from -r requirements.txt (line 19))
  Using cached eventlet-0.19.0-py2.py3-none-any.whl
Collecting gpxpy==1.1.1 (from -r requirements.txt (line 20))
Collecting mock==2.0.0 (from -r requirements.txt (line 21))
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting timeout-decorator==0.3.2 (from -r requirements.txt (line 22))
Collecting raven==5.23.0 (from -r requirements.txt (line 23))
  Using cached raven-5.23.0-py2.py3-none-any.whl
Collecting demjson==2.2.4 (from -r requirements.txt (line 24))
Collecting greenlet==0.4.9 (from -r requirements.txt (line 25))
  Using cached greenlet-0.4.9.zip
Collecting decorator>=3.4.0 (from networkx==1.11->-r requirements.txt (line 2))
  Using cached decorator-4.0.10-py2.py3-none-any.whl
Collecting six (from pgoapi->-r requirements.txt (line 3))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting xxhash (from pgoapi->-r requirements.txt (line 3))
  Using cached xxhash-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/nose/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'nose' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    No local packages or working download links found for nose>=1.3.0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/12/tynmmybj55x7jjvj0wg99btr0000gn/T/pip-build-bs517W/xxhash/setup.py", line 58, in <module>
        'Programming Language :: Python :: Implementation :: CPython',
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/dist.py", line 348, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/dist.py", line 394, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1098, in best_match
        return self.obtain(req, installer)
      File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1110, in obtain
        return installer(requirement)
      File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/dist.py", line 461, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 658, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('nose>=1.3.0')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/12/tynmmybj55x7jjvj0wg99btr0000gn/T/pip-build-bs517W/xxhash/
(PokemonGo-Bot) Yannics-MacBook-Air:PokemonGo-Bot naturalhealingways$ ./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions
Tue Aug 16 13:19:48 PDT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by jrjhealey** [comment]
try running the install with sudo.

Also please add the required information to your OP, such as commit, python version etc.

**Comment by DanielVolz** [comment]
Download error on https://pypi.python.org/simple/nose/: [SSL: CERTIFICATE_VERIFY_FAILED] 
Thats strange. But I have no idea why it happens. 

Are you on a special network? Like on your job?

**Comment by yweitkemper** [comment]
Yea i am actually, on my work network.

**Comment by yweitkemper** [comment]
It worked on here a few days ago, but maybe ill try it again when I'm home.

**Comment by DanielVolz** [comment]
Yes, try that.

**Comment by Tagada22** [comment]
You have openssl and python-openssl packet ?

**Comment by k4n30** [comment]
This clearly isn't a bot issue, but a network issue (ie corporate blocking)
