### ISSUE TITLE
Realistic geolocation altitudes

### ISSUE THREAD

**Issue by gfreivasc** [PokemonGoF/PokemonGo-Bot#4106]
### Short Description
Currently the bot only sends coordinates with consant altitude to Niantic servers, this could be a way of detecting bot users. Geospacial shapes are not flat and a simple SQL query on stored locations could tell a system wether someone has been walking too much on constant elevation.

### Possible solution
Randomizing the value might help but I guess that irrealistic altitude is not a good idea either. There are APIs that tells us realistic heights on latitude/longitude that consist in simple queries to return our desired data.

One candidate I've found is [Mapzen Elevation API](https://mapzen.com/documentation/elevation/elevation-service/#outputs-of-the-elevation-service).

### How it would help others
It's one less way to detect botting based on data sent to server.

**Comment by avexus** [comment]
I didn't see a conf entry for altitude.
Is this info actually sent over to server?
It should be kept on GPS signal, right?

**Comment by PokemonGoZ** [comment]
@avexus Whenever the bot crashes then "respawns" it shows `lat, long, alt` and `alt`=`0` every time, so this can get accounts flagged.

**Comment by Roekeye** [comment]
It could use elevation information from a GPX file. A rout created from http://www.gpsies.com/ has elevation data in the export:

    <trkseg>
      <trkpt lat="41.89118048" lon="-87.6108705">
        **<ele>190.00000</ele>**
      </trkpt>

**Comment by jboffel** [comment]
https://developers.google.com/maps/documentation/elevation/intro

The bot already require a google maps API key, then let's use the already available functions...

**Comment by k4n30** [comment]
#2762

**Comment by jboffel** [comment]
I may suggest something like that in: PokemonGo-Bot\pokemongo_bot__init__.py
```
import googlemaps

class PokemonGoBot(object):
    @property
    def position(self):
        logger = logging.getLogger('AltitudeFaker')
        logger.setLevel(logging.INFO)
        # logger.info('Start to capture altitude for current location!')
        alt = 0
        if self.alt_cache.has_key((self.api._position_lat, self.api._position_lng)):
            alt = self.alt_cache[(self.api._position_lat, self.api._position_lng)]
        else:
            # logger.info('Not in cache yet')
            try:
                gmaps = googlemaps.Client(key=self.config.gmapkey)
                # logger.info('Got client')
                alt = gmaps.elevation((self.api._position_lat, self.api._position_lng))
                # logger.info('Got response')
                alt = alt[0]['elevation']
                # logger.info('Show response: {}'.format(alt))
                self.alt_cache[(self.api._position_lat, self.api._position_lng)] = alt
            except IOError as e:
                logger.info('Cannot get alt: %s' % e)
                alt = 0
        # logger.info('Current lng: {}, lat: {} then alt: {}'.format(self.api._position_lat, self.api._position_lng, alt))
        return self.api._position_lat, self.api._position_lng, alt
.....
```
I didn't take a close look at everything in the code but it was looking like a central place to retrieve current bot position to be used as input for most of the call.

But I guess there are some place in the code where the returned alt value was ignored and or overwritten eventually...
