### ISSUE TITLE
cannot run -mode farm

### ISSUE THREAD

**Issue by mrwing1** [PokemonGoF/PokemonGo-Bot#411]
here is a full run 
[x] Initializing PokemonGO Bot v1.0
[x] PokemonGo Bot [@PokemonGoF | @eggins | @crack00r | @ethervoid | /r/pokemongodev]
usage: pokecli.py [-h] -a AUTH_SERVICE -u USERNAME -p PASSWORD -l LOCATION
                  [-s] [-v] [-w WALK] [-c CP] [-k GMAPKEY]
                  [--maxsteps MAXSTEPS] [-d] [-t] [-tl TRANSFER_LIST]
pokecli.py: error: unrecognized arguments: -mode farm

**Comment by ckrmml** [comment]
do you run the master branch? mode only works in dev as far as i know and also it should be -m or --mode

**Comment by mrwing1** [comment]
yes master

**Comment by solderzzc** [comment]
let me close this one since no this mode on master.
