### ISSUE TITLE
Setup.sh dont works!

### ISSUE THREAD

**Issue by SaubereSacheLP** [PokemonGoF/PokemonGo-Bot#4110]
### Expected Behavior
The setup should setup the thing

### Actual Behavior
auberesachelp@SaubereSache ~/Downloads/PokemonGo-Bot-dev $ sh setup.sh 
setup.sh: 6: setup.sh: Syntax error: "(" unexpected

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
Havent got one

### Output when issue occurred
auberesachelp@SaubereSache ~/Downloads/PokemonGo-Bot-dev $ sh setup.sh 
setup.sh: 6: setup.sh: Syntax error: "(" unexpected

### Other Information
OS: 
Linux Mint
Branch: 
Both

**Comment by dneern** [comment]
This is not a problem with the bot, but rather a problem with your understanding of how to use the bot.

**Comment by simonsmh** [comment]
use bash plz?
