### ISSUE TITLE
Update wiki for docker on windows

### ISSUE THREAD

**Issue by supercourgette** [PokemonGoF/PokemonGo-Bot#4116]
### Short Description

To run the bot + map with Docker on Windows, there are a few steps which are not described.

The correct command to run the bot container AND the map container, without Docker's compose are the following:

Bot container (change to mount the web directory):
` docker run --name=bot1-pokego --rm -it -v $(pwd)/configs/config.json:/usr/src/app/configs/config.json -v $(pwd)/web/:/usr/src/app/web/ pokemongo-bot`

Map container (no change):
`docker run --name=bot1-pokegoweb --rm -it --volumes-from bot1-pokego -p 8000:8000 -v $(pwd)/configs/userdata.js:/usr/src/app/web/userdata.js -w /usr/src/app/web python:2.7 python -m SimpleHTTPServer`

Then to access the host of the VM:
`docker-machine ip default`

**Why not just use Docker compose ?**

The rendering in the Docker console is not colored.

### How it would help others

I spent a few hours yesterday to understand why the map wasn't working.  It was my first time using Docker, and I didn't have enough understanding of it to spot my mistake. A lot of others users may be in the same case.

**Info**

This proposition follow this issue: #https://github.com/PokemonGoF/PokemonGo-Bot/issues/4083

**Comment by k4n30** [comment]
@supercourgette Can you make a pull request for this?

**Comment by supercourgette** [comment]
Done with the best of my aptitude (since I'm not an expert) here : #4136
