### ISSUE TITLE
Web UI path not updating

### ISSUE THREAD

**Issue by jane0815** [PokemonGoF/PokemonGo-Bot#4118]
Since a few update my map does not show the path of the bots. I pulled all new but still it shows no path.

Was anything changed? How can i get path working again?

**Comment by k4n30** [comment]
Please use the issue template

**Comment by jane0815** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/4126

**Comment by MZorzy** [comment]
See the same.
Start bot and open map page, under setting activate 'parh' , bot move but no visibile line of route/walk
