### ISSUE TITLE
[Bug?] UpdateLiveStats returns stats for all time, not up time.

### ISSUE THREAD

**Issue by RedViper9** [PokemonGoF/PokemonGo-Bot#4119]
Expect:
UpdateLiveStats gives UpTime/Stardust/XP/etc. for the duration that the bot is run (i.e. UpTime).

Actual:
![screenshot_2](https://cloud.githubusercontent.com/assets/20653340/17717335/4f68f33c-63c2-11e6-979e-a3054e17d632.png)
Bot seems to return stats based on the account totals.
(As much as I'd like to be getting 4x10^6 xp/hr)

Config:
http://pastebin.com/HkpcPUc6

Output:
N/A (see screenshot above).

To Reproduce:
Run with linked config.

Other Info:
OS: Linux Mint 18
Branch: Dev
Git Commit: e68c2e80202b9457311368eb2248c5a762fa35bc
Python Version: Python 2.7.12

**Comment by MasterCATZ** [comment]
personally I would like both 

total run time and session uptime

**Comment by BriceSD** [comment]
As yaborije said on Slack, #4088 is the reason of this bug. Checking for ```None``` and not ```0```.

```
self.xp['latest'] = playerdata.get('experience', 0)
                        if self.xp['start'] is None: self.xp['start'] = self.xp['latest']
```

@MasterCATZ We can’t have total as it is. We do not know for how long you ran the bot.
