### ISSUE TITLE
Web UI path not updating

### ISSUE THREAD

**Issue by jane0815** [PokemonGoF/PokemonGo-Bot#4126]
### Expected Behavior

Map to update path

### Actual Behavior

Map not updating path

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

Not needed for map.

### Output when issue occurred

Not Output, No path

### Steps to Reproduce

run rot, run map, open map

### Other Information
OS:  mac
Branch: Not working for many versions. Not in master not in dev  
Git Commit: 
e68c2e80202b9457311368eb2248c5a762fa35bc
Python Version: 
Python 2.7.12
Any other relevant files/configs (eg: path files)

**Comment by k4n30** [comment]
Seeing as the code for the updating of the web location hasn't changed for 4 days, we're going to need some more information from you that could have been provided if the template was used correctly.

Can you please provide:
[ ] Your FULL config
[ ] A sample of your output of the bot (even if it seems to be 100% working)
[ ] The steps you used to start the bot 
[ ] The steps you used to start the webui
[ ] A screenshot of the webui

**Comment by 0z4ck** [comment]
I'm not sure what is your problem, but I think it's because of the cache of the browser.

In general, if you change some configuration in the server, you need to clear caches before reloading .

**Comment by TheCannings** [comment]
I had this issue and hadn't realised that the userdata.js had moved to the configs folder within the web folder and needed to have the details put in there

**Comment by thereyrey** [comment]
You either forgot to change to the new account in userdata.js or try and change the port to a new port and it will suddenly work again. I could not load the map with a new account without doing this.

**Comment by jane0815** [comment]
After updating to latest master the ui path is working again. thx for your support!
