### ISSUE TITLE
Walking improvements: Directions API, Elevations API

### ISSUE THREAD

**Issue by th3w4y** [PokemonGoF/PokemonGo-Bot#413]
is there anything in your TODO list for this?

Was thinking to add a new walk logic to use the map generated by the Directions API for generating a polyline that would need to be walked with the speed that is set.

Additionally for the generated point we could fetch the alt from the Elevations API

this can improve the self.set_position(lat, lng, alt)

maybe this will make the bot walk more natural.

What are your opinions on this?

**Comment by solderzzc** [comment]
I like the idea, I was placed a google API there to simulate people walk.

**Comment by th3w4y** [comment]
`import polyline
import haversine
import time
from itertools import  chain

class PolylineWalker(object):

    def __init__(self, polyline_points, speed):
        """
        :param polyline_points:
        URL = 'https://maps.googleapis.com/maps/api/directions/json?origin=Cham,CH&destination=Baar,CH&mode=walking'
        polyline_points =[x['polyline']['points'] for x in
                          requests.get(URL).json()['routes'][0]['legs'][0]['steps']]
        :param speed:
        """
        self.speed = float(speed)
        self.points = self.get_points(polyline_points)
        self.lat, self.long = self.points[0][0], self.points[0][1]
        self.polyline = self.combine_polylines(self.points)
        self._timestamp = time.time()
        self.is_paused = False
        self._last_paused_timestamp = None
        self._paused_total = 0.0

    def reset_timestamps(self):
        self._timestamp = time.time()
        self.is_paused = False
        self._last_paused_timestamp = None
        self._paused_total = 0.0

    def get_points(self, polyline_points):
        crd_points = []
        for points in polyline_points:
            crd_points += polyline.decode(points)
        crd_points = [x for n,x in enumerate(crd_points) if x not in crd_points[:n]]
        return crd_points

    def combine_polylines(self, points):
        return polyline.encode(points)

    def pause(self):
        if not self.is_paused:
            self.is_paused = True
            self._last_paused_timestamp = time.time()

    def unpause(self):
        if self.is_paused:
            self.is_paused = False
            self._paused_total += time.time() - self._last_paused_timestamp
            self._last_paused_timestamp = None

    def walk_steps(self):
        if self.points:
            return zip(chain([self.points[0]], self.points),
                       chain(self.points, [self.points[-1]]))
        else:
            return []

    def walk(self):
        if not self.is_paused:
            walked_distance = 0.0
            time_passed = time.time()
            remaining_points = []
            time_passed_distance = self.speed * abs(time_passed - self._timestamp - self._paused_total)
            for step in self.walk_steps():
                step_distance = haversine.haversine(*step)*1000
                if walked_distance + step_distance >= time_passed_distance:
                    if walked_distance > time_passed_distance:
                        percentage_walked = 0.0
                    else:
                        if step_distance == 0.0:
                            percentage_walked = 1.0
                        else:
                            percentage_walked = (time_passed_distance - walked_distance)/step_distance
                    remaining_points += self.calculate_coord(percentage_walked,*step)
                else:
                    percentage_walked = 1.0
                walked_distance += step_distance * percentage_walked
            self.points = remaining_points
            if self.points:
                self.lat, self.long = self.points[0][0], self.points[0][1]
                self.polyline = self.combine_polylines(self.points)
            else:
                self.lat, self.long = None, None
                self.polyline = ''
            self.reset_timestamps()
        return (self.lat, self.long)

    def calculate_coord(self, percentage, o, d):
        lat = o[0]+ (d[0] -o[0]) * percentage
        lon = o[1]+ (d[1] -o[1]) * percentage
        return [(lat, lon)]

`


and tester

`
import requests
import time
import haversine
from polyline_walker import PolylineWalker
URL = 'https://maps.googleapis.com/maps/api/directions/json?origin=Baar,CH&destination=Cham,CH&mode=walking'
a = PolylineWalker([x['polyline']['points'] for x in  requests.get(URL).json()['routes'][0]['legs'][0]['steps']], 2.5)
len(a.points)
while a.points:
    before = a.points[1:]
    now = a.walk()
    print(len(a.points), len(a.points))
    after = a.points[1:]
    print('Remaining ', haversine.haversine(a.points[1], now)*1000, ' m. on current polyline. ', len(a.points), ' polylines remaining.')
    print('Estimated completion time: ', (sum([haversine.haversine(*x)*1000 for x in a.walk_steps()]) / a.speed) , ' seconds.')
    if before != after:
        print('Changed polyline: ', a.polyline)
    time.sleep(1.5)


`

**Comment by th3w4y** [comment]
got read of the .walk() concept the PolylineWalker() object has a .get_pos() method that returns the current position at call time on the polyline.

the are no methods anymore that update the .points content those remain the same during the life of the object with the initial points from the Google Direction API fetched points.
#667

if the polyline walk was finished the .get_pos() continues to return the position of the last point.
not sure what would be the best way to go...

any proposals/preferences what should the object return?

**Comment by th3w4y** [comment]
more improvements #697

**Comment by th3w4y** [comment]
more improvements #721

**Comment by Naramsim** [comment]
Maybe change sometime a little bit the movements speed. So the bot will look more natural

**Comment by th3w4y** [comment]
Good suggestion!

Posible solutions:
- one could use the .pause() .unpause() methods to achieve a small speed modulation 
- I also think one should stop the counter while working on a cell

**Comment by th3w4y** [comment]
I did a PR  #835 to push some fixes to master branch

**Comment by th3w4y** [comment]
Will need to rewrite some code due to the big refactor to Stepper class #737

**Comment by th3w4y** [comment]
routing the generated point to 5 digits precision ensure we are around ~50 cm around the point proposed by the Google Direction API.

I that good enough as a jitter?

**Comment by th3w4y** [comment]
fixes in PR #990
