### ISSUE TITLE
Latest git clone ~dev

### ISSUE THREAD

**Issue by ponytails** [PokemonGoF/PokemonGo-Bot#4131]
This is from latest Git pull on dev codes

https://snag.gy/BcQ1W2.jpg

i just add my user/pass @gmail nothing more.. all new files/fresh and started the bot.. and get this result see image above

**Comment by ponytails** [comment]
hello @k4n30 

its closed.. but why it keeps being softban ? i dont understand.. i just pick DEV codes to git clone.. and used it ?

no other changes just user/pass/location (same location) on old git version

**Comment by k4n30** [comment]
The issues are for bot bugs, not for configuration help or support. Please use the slack server as indicated in the README
