### ISSUE TITLE
After update bot i got No module named Requests

### ISSUE THREAD

**Issue by clubza1** [PokemonGoF/PokemonGo-Bot#4134]
before update,It's work well .After update bot i got No module named Requests

Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "D:\Bot\som\PokemonGo-Bot\pokemongo_bot\__init__.py", line 22, in <module>
    from api_wrapper import ApiWrapper
  File "D:\Bot\som\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 9, in <module>
    from pgoapi.protos.POGOProtos.Networking.Requests_pb2 import RequestType
ImportError: No module named Requests_pb2
-----------------------------------------------------------

I try #4104 but not work
 
i use home network

my bot is dev branch

**Comment by k4n30** [comment]
Did you follow the update process correctly and install any new requirements? If not, please come back and use the issue template properly

**Comment by clubza1** [comment]
I fix it 

i uninstall Python 2.7.x,pip,git,virtualenv and reinstall.
