### ISSUE TITLE
Issue #4128 not the same as #4113 #4124 #4125

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#4137]
@k4n30 just to be sure:

I had two issues you closed
1) Crash after sync dev in move_to_map_pokemon.py #4125 (due to expire vs disappear_time)
2) MoveToMapPokemon / MoveToFort cycling #4128 that you closed because duplicate of #4113
But #4113 is referring to problem 1 (expire) not the cycling issue.
And I don't see other issues similar to mine. 

I saw a pull related to it, fix followCluster & MoveToMapPokemon #4115 by @Raiven66 
do you confirm it will solve the cycling issue?

Anyway I will wait for the approval and merge to see.

**Comment by k4n30** [comment]
@Gurzeh you didn't have to create a new issue to refer to all the old issues. I think I understand what you're saying (after having to recheck all the links), but if you think one of your issues is not resolved by an impending merge, then please reopen it. I'm not going to get it right 100% of the time :p

I may have linked all the "MoveToMap" problems to the one merge as they were all very similar and most likely related.

Suggested way forward:
1. Close this issue (not bot bug related :p)
2. Wait for the merge and see if it fixes **ALL** of your issues
3. Repoen any issues that aren't fixed and tag me, and I will apply the appropriate labels for you :)

**Comment by k4n30** [comment]
@Gurzeh merge occurred, please validate

**Comment by Gurzeh** [comment]
@k4n30 seems very ok.
(but as I restart, my config.json is creepy)
thanks for your help! I really really appreciate.
btw, I don't see my pull anymore. Merged or deleted?
