### ISSUE TITLE
Documentation needs update

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#4138]
I just saw some changes in the config file. However, it is not easy for me to understand (sorry), especially those lines, what do they do?

    "encrypt_location": "",
    "heartbeat_threshold": 10,

Thank you very much!

**Comment by RedViper9** [comment]
> Character codes for fast/charged attack types.
> If attack is good character is uppecased, otherwise lowercased.
> Use 'good_attack_threshold' option for customization.

I take that to mean that setting to mean that only attacks of 90% or better will be uppercased.

**Comment by avexus** [comment]
@RedViper9 Thank you, i'll edit my post.

**Comment by Raiven66** [comment]
encrypt_location is the location of the encrypt.so file (i think)
heartbeat_threshold - is how many seconds should be used between requests to server for player information etc. This was every second before which was unnecessarily often, 10secs should be fine so probably leave the config on 10

**Comment by k4n30** [comment]
Can someone create a pull request out of the missing information please :)

**Comment by simonsmh** [comment]
"encrypt_location": "",
Point it to the location of encrypt.so/dll, if you put it in this Pogo-bot dir just leave it as blank
"heartbeat_threshold": 10,
It means to access to niantic api server every 10 seconds.

**Comment by k4n30** [comment]
@simonsmh already answered :p

**Comment by Raiven66** [comment]
where is this documented so I can make a PR while fixing other stuff? @k4n30

**Comment by k4n30** [comment]
In this conversation history, it needs to be added to https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md

**Comment by Gurzeh** [comment]
yes I do agree. I just fetched from upstream (almost every day) and I came across a new task that is not described:
{
	"type": "CatchPokemon",
	"config": {
		"catch_visible_pokemon": true,
			"catch_lured_pokemon": true,
			"min_ultraball_to_keep": 10,
			"catch_throw_parameters": {
			"excellent_rate": 0.1,
			"great_rate": 0.5,
			"nice_rate": 0.3,
			"normal_rate": 0.1,
			"spin_success_rate" : 0.6
		},
		"catch_simulation": {
			"flee_count": 3,
			"flee_duration": 2,
			"catch_wait_min": 2,
			"catch_wait_max": 6,
			"berry_wait_min": 2,
			"berry_wait_max": 3,
			"changeball_wait_min": 2,
			"changeball_wait_max": 3
		}
	 }
 },

@quantra and the source code catch_pokemon.py has no comment on the reason to introduce this new class / task.

**Comment by Quantra** [comment]
@Gurzeh  Have a look at pull request: #3966

**Comment by Gurzeh** [comment]
@Quantra thanks!

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/configs/config.json.example#L169

Also needs config_files.md addition too - I added it to the PR, but it was merged anyway

**Comment by mjmadsen** [comment]
#4283 Expanding the discussion. Looks like your particular problem was solved. Closing.
