### ISSUE TITLE
PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 9, in <module>     from pgoapi.protos.POGOProtos.Networking.Requests_pb2

### ISSUE THREAD

**Issue by MasterCATZ** [PokemonGoF/PokemonGo-Bot#4141]
===============ISSUE SECTION===============

 ./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/DATA/PokemonGo-Bot/pokemongo_bot/__init__.py", line 22, in <module>
    from api_wrapper import ApiWrapper
  File "/DATA/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 9, in <module>
    from pgoapi.protos.POGOProtos.Networking.Requests_pb2 import RequestType
ImportError: No module named Requests_pb2
Wed 17 Aug 09:30:25 CEST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

### Expected Behavior
Bot to start
has been like this 12 hrs now 
tried
./setup.sh 
pip install requirements.txt --upgrade
pip install requests --upgrade

### Actual Behavior
bot instantly crashing 

### Steps to Reproduce
git pull on dev branch

### Other Information
OS: 
4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Branch: 
dev 
Git Commit: 
7136348dda4217d8010aab4d8e6f1124cba64140
Python Version: 
Python 2.7.12

**Comment by clubza1** [comment]
try to reinstall 
    Python 2.7.x
    pip
    git
    virtualenv

**Comment by beltoft** [comment]
Have the same error since latest pull

**Comment by k4n30** [comment]
What steps did you take other than git pull? Can you explain each step and someone will hopefully realise you have missed a step. Also what guide did you follow or did u literally just use run.sh?

**Comment by MasterCATZ** [comment]
apt-get install --reinstall python-dev python-protobuf python2.7 gitReading package lists... Done
Building dependency tree       
Reading state information... Done
0 to upgrade, 0 to newly install, 4 reinstalled, 0 to remove and 101 not to upgrade.
Need to get 3,231 kB/3,330 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://ubuntu.mirrors.ovh.net/ftp.ubuntu.com/ubuntu xenial/main amd64 git amd64 1:2.7.4-0ubuntu1 [3,006 kB]
Get:2 http://ubuntu.mirrors.ovh.net/ftp.ubuntu.com/ubuntu xenial/main amd64 python-dev amd64 2.7.11-1 [1,160 B]
Get:3 http://ubuntu.mirrors.ovh.net/ftp.ubuntu.com/ubuntu xenial-updates/main amd64 python2.7 amd64 2.7.12-1~16.04 [224 kB]
Fetched 3,231 kB in 0s (3,548 kB/s)
(Reading database ... 157349 files and directories currently installed.)
Preparing to unpack .../git_1%3a2.7.4-0ubuntu1_amd64.deb ...
Unpacking git (1:2.7.4-0ubuntu1) over (1:2.7.4-0ubuntu1) ...
Preparing to unpack .../python-dev_2.7.11-1_amd64.deb ...
Unpacking python-dev (2.7.11-1) over (2.7.11-1) ...
Preparing to unpack .../python2.7_2.7.12-1~16.04_amd64.deb ...
Unpacking python2.7 (2.7.12-1~16.04) over (2.7.12-1~16.04) ...
Preparing to unpack .../python-protobuf_2.6.1-1.3_amd64.deb ...
Unpacking python-protobuf (2.6.1-1.3) over (2.6.1-1.3) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up git (1:2.7.4-0ubuntu1) ...
Setting up python-dev (2.7.11-1) ...
Setting up python2.7 (2.7.12-1~16.04) ...
Setting up python-protobuf (2.6.1-1.3) ...

wget https://bootstrap.pypa.io/get-pip.py
python2.7 get-pip.py
python2.7 get-pip.py
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages

 pip install virtualenv --upgrade
Requirement already up-to-date: virtualenv in /usr/local/lib/python2.7/dist-packages

virtualenv .
New python executable in /DATA/PokemonGo-Bot/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 9, in <module>
    load_entry_point('virtualenv==15.0.3', 'console_scripts', 'virtualenv')()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 924, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1230, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 40] Too many levels of symbolic links: '/DATA/PokemonGo-Bot/bin/python'


 pip install -r requirements.txt

wget http://pgoapi.com/pgoencrypt.tar.gz
tar -xzvf pgoencrypt.tar.gz
cd pgoencrypt/src/
make
cd ../../
mv pgoencrypt/src/libencrypt.so encrypt.so


./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/DATA/PokemonGo-Bot/pokemongo_bot/__init__.py", line 22, in <module>
    from api_wrapper import ApiWrapper
  File "/DATA/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 9, in <module>
    from pgoapi.protos.POGOProtos.Networking.Requests_pb2 import RequestType
ImportError: No module named Requests_pb2
Wed 17 Aug 18:48:26 CEST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.



what else am I missing ?
hundreds of others in slack same problem , no answers

**Comment by MasterCATZ** [comment]
still no idea what the cause was 
did another git pull still same issue 

so  I renamed the folder because I was going to do fresh separate master / dev folders 
then for kicks thought I would run it  
it worked ?? 

and then after it started renamed it back .. still worked , its got me stumped

**Comment by nalancer08** [comment]
Its a bann, im ssorry but you lose your account like everyone here jajajaja

**Comment by net8q** [comment]
Did you install PokemonGo-Map too ? they have forked their own pgoapi and moved around some files.

https://github.com/PokemonGoMap/pgoapi/commit/a5785771b835fca01ae052dbaecca0191214169e

**Comment by MasterCATZ** [comment]
pretty sure it was updated still , but its working for now so will leave everything along

**Comment by beltoft** [comment]
did all of the above (including the rename trick) but i still got the error. 

Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/__init__.py", line 22, in <module>
    from api_wrapper import ApiWrapper
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 9, in <module>
    from pgoapi.protos.POGOProtos.Networking.Requests_pb2 import RequestType
ImportError: No module named Requests_pb2
Thu Aug 18 08:37:56 CEST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.


I have PokemonGo-Map running just fine - I just updated that and its still running without problems

**Comment by beltoft** [comment]
I deleted everything but my config file and reinstalled. and its working again.

Now its only movetomap thats failing but I've made a new issue about that
