### ISSUE TITLE
Starting bot

### ISSUE THREAD

**Issue by yweitkemper** [PokemonGoF/PokemonGo-Bot#4162]
===============ISSUE SECTION===============

 have been getting this error for the last 2 days now, already deleted everything and started over and still getting it. Can anyone help? On the newest dev now but also tried the master same error. Also tried different networks still no change.  

Edit: Also just tried running it as sudo still no change.

Yannics-MacBook-Air:~ naturalhealingways$ cd PokemonGo-Bot  
Yannics-MacBook-Air:PokemonGo-Bot naturalhealingways$ virtualenv .  
New python executable in /Users/naturalhealingways/PokemonGo-Bot/bin/python
Installing setuptools, pip, wheel...done.
Yannics-MacBook-Air:PokemonGo-Bot naturalhealingways$ source bin/activate  
(PokemonGo-Bot) Yannics-MacBook-Air:PokemonGo-Bot naturalhealingways$ pip install -r requirements.txt
Collecting numpy==1.11.0 (from -r requirements.txt (line 1))
  Using cached numpy-1.11.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting networkx==1.11 (from -r requirements.txt (line 2))
  Using cached networkx-1.11-py2.py3-none-any.whl
Obtaining pgoapi from git+https://github.com/keyphact/pgoapi.git@a2755eb42dfe49e359798d2f4defefc97fb8163d#egg=pgoapi (from -r requirements.txt (line 3))
  Skipping because already up-to-date.
Collecting geopy==1.11.0 (from -r requirements.txt (line 4))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting protobuf==3.0.0b4 (from -r requirements.txt (line 5))
  Using cached protobuf-3.0.0b4-py2.py3-none-any.whl
Collecting requests==2.10.0 (from -r requirements.txt (line 6))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 7))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 8))
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 9))
Collecting googlemaps==2.4.4 (from -r requirements.txt (line 10))
  Using cached googlemaps-2.4.4-py2-none-any.whl
Collecting colorama==0.3.7 (from -r requirements.txt (line 11))
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting enum34==1.1.6 (from -r requirements.txt (line 12))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting pyyaml==3.11 (from -r requirements.txt (line 13))
  Using cached PyYAML-3.11.zip
Collecting haversine==0.4.5 (from -r requirements.txt (line 14))
Collecting polyline==1.3.1 (from -r requirements.txt (line 15))
  Using cached polyline-1.3.1-py2.py3-none-any.whl
Collecting python-socketio==1.4.2 (from -r requirements.txt (line 16))
Collecting flask==0.11.1 (from -r requirements.txt (line 17))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting socketIO_client==0.7.0 (from -r requirements.txt (line 18))
Collecting eventlet==0.19.0 (from -r requirements.txt (line 19))
  Using cached eventlet-0.19.0-py2.py3-none-any.whl
Collecting gpxpy==1.1.1 (from -r requirements.txt (line 20))
Collecting mock==2.0.0 (from -r requirements.txt (line 21))
  Using cached mock-2.0.0-py2.py3-none-any.whl
Collecting timeout-decorator==0.3.2 (from -r requirements.txt (line 22))
Collecting raven==5.23.0 (from -r requirements.txt (line 23))
  Using cached raven-5.23.0-py2.py3-none-any.whl
Collecting demjson==2.2.4 (from -r requirements.txt (line 24))
Collecting greenlet==0.4.9 (from -r requirements.txt (line 25))
  Using cached greenlet-0.4.9.zip
Collecting yoyo-migrations==5.0.3 (from -r requirements.txt (line 26))
  Using cached yoyo-migrations-5.0.3.tar.gz
Collecting decorator>=3.4.0 (from networkx==1.11->-r requirements.txt (line 2))
  Using cached decorator-4.0.10-py2.py3-none-any.whl
Collecting six (from pgoapi->-r requirements.txt (line 3))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting xxhash (from pgoapi->-r requirements.txt (line 3))
  Using cached xxhash-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/nose/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'nose' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    No local packages or working download links found for nose>=1.3.0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/12/tynmmybj55x7jjvj0wg99btr0000gn/T/pip-build-8RdrP8/xxhash/setup.py", line 58, in <module>
        'Programming Language :: Python :: Implementation :: CPython',
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/dist.py", line 348, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/dist.py", line 394, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1098, in best_match
        return self.obtain(req, installer)
      File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1110, in obtain
        return installer(requirement)
      File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/dist.py", line 461, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/naturalhealingways/PokemonGo-Bot/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 658, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('nose>=1.3.0')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/12/tynmmybj55x7jjvj0wg99btr0000gn/T/pip-build-8RdrP8/xxhash/
(PokemonGo-Bot) Yannics-MacBook-Air:PokemonGo-Bot naturalhealingways$ ./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions
Wed Aug 17 08:21:03 PDT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

### Other Information
OS: IOS

Branch: 
Tried Both
Git Commit: 
423e4dea72c0b04d8882ef90f03949fe3bf35ac2
Python Version: 
2.7.12

**Comment by jalliance** [comment]
Try doing pip install -r requirements.txt --no-cache-dir

**Comment by avexus** [comment]
i just did a git pull.
the setup.sh -r ran without any errors.
it is up and running
Macbook Air. Latest OSX

**Comment by yweitkemper** [comment]
Still the same error, could it be something in my computer settings? not sure what it would be but seems like its working for other people and i just did a clean install.

**Comment by jalliance** [comment]
Weird it works fine for me on multiple machines. Did you `deactivate` before trying a clean install?

**Comment by avexus** [comment]
i had problem on Mac. turned out to be the text editor i'm using. i changed to BBEdit, then the problem went away.
Just curious, the program does not send OS info to server, right?

**Comment by jalliance** [comment]
@yweitkemper also, have you tried doing `pip install nose` or `pip install pgoaopi` manually to see if the error still occurs?

**Comment by yweitkemper** [comment]
That worked thanks
