### ISSUE TITLE
Bot stops responding after ~10 minutes

### ISSUE THREAD

**Issue by Z3r0byte** [PokemonGoF/PokemonGo-Bot#4164]
The bot stops encountering any pokemon after ~10 minutes and a few minutes later it stops walking. Its still doing the output of the stats. I've had this issue multiple times.<br /><br />EDIT: I have this issue on both master and dev branch.<br /><br /><br />2016-08-17 17:24:17,318 [  SpinFort] [INFO] [spun_pokestop] Spun pokestop Santa Monica Clocktower. Experience awarded: 50. Items awarded: {u'Pokeball': 2, u'Greatball': 1}<br />2016-08-17 17:24:19,396 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Puma Statue - 0.10km<br />2016-08-17 17:24:21,375 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Puma Statue - 0.10km<br />2016-08-17 17:24:23,496 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Puma Statue - 0.10km<br />2016-08-17 17:24:25,608 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Puma Statue - 0.10km<br />2016-08-17 17:24:27,305 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Puma Statue - 0.09km<br />2016-08-17 17:24:29,251 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Puma Statue - 0.09km<br />2016-08-17 17:24:30,755 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Puma Statue - 0.08km<br />2016-08-17 17:24:41,158 [UpdateLiveStats] [INFO] [log_stats] NblablaR | Uptime : 0:10:42 | Earned 1,600 Stardust | +2,920 XP | 16,385 XP/h | Visited 13 stops<br />2016-08-17 17:24:45,131 [IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 2.25 km<br />2016-08-17 17:24:50,439 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Puma Statue - 0.08km<br />**Stops working here**</br>2016-08-17 17:25:14,156 [UpdateLiveStats] [INFO] [log_stats] NblablaR | Uptime : 0:11:15 | Earned 1,600 Stardust | +2,920 XP | 15,584 XP/h | Visited 13 stops<br />2016-08-17 17:25:47,040 [UpdateLiveStats] [INFO] [log_stats] NblablaR | Uptime : 0:11:47 | Earned 1,600 Stardust | +2,920 XP | 14,859 XP/h | Visited 13 stops

**Comment by MiniWire** [comment]
Can you tell where it is not responding anymore? it creates a new line every ~5-10secs?

The problem i have is, that it stops running and doesnt respond anymore (no new log-lines and not running anymore). I can fix it by typing a spacebar or any key to the cmdline (Win10). Cant provide any logs right now, will do it when it happens next time.

**Comment by Z3r0byte** [comment]
@MiniWire I updated my post.

**Comment by MiniWire** [comment]
@Z3r0byte Now I see, I still haven't found out why. But it behaves quite differntly as it seems, My problem occurs on 2 different Windows 10 machines

**Comment by Z3r0byte** [comment]
@MiniWire I'm using Ubuntu, so its not platform specific.

**Comment by MiniWire** [comment]
@Z3r0byte I would like to debug things, but I'm a newbie in Python. Problem occured for me since the first versions of the bot, but thought that would be a problem related with my connection/Windows10.

**Comment by Faithu** [comment]
Mine stops after 30 mins

**Comment by bimahp** [comment]
Same here. Mine stops after 8 ~ 10 mins

**Comment by sohje** [comment]
Check amount of pokestops on your UI map. Maybe all of them cached and bot just stand still?
I got this situation once cause only few pokestops on botting area. Bot already visited all of them and put them into cache and was standing on same spot without single move.

**Comment by Faithu** [comment]
@sohje  Naw its on it's way to a pokestop and then just stops doesn't turn up to the pokestop

**Comment by Z3r0byte** [comment]
@sohje How do I enable that webUI?

**Comment by tomorrowplusone** [comment]
do you have the never_catch flag active?

**Comment by Z3r0byte** [comment]
@tomorrowpulseone Nope, iets configured tot catch all pokémon

**Comment by MiniWire** [comment]
I just ran my bot on a debian x86_64 machine with python-dev. It ran 8 hrs without hanging up. Maybe our problem has to do with the python version? But I could also be completely wrong, just saying.

**Comment by Z3r0byte** [comment]
I just noticed the bot stopper after  it logged about ten times it found two lured pokemon. That was the only thing it logged. Then it just hang

**Comment by bimahp** [comment]
i disabled liveStats and bot running fine for 8+ hours, dunno if its the problem

**Comment by dextercai** [comment]
l found this problem about 2 weeks ago, but l found that although there are no new lines, the bot is still running after some mins.

**Comment by k4n30** [comment]
@Z3r0byte please update your OP with the detail requested in the issue template so that the proper assistance can be provided

**Comment by MiniWire** [comment]
Just wanted to add that it works on Debian fine, but still idles on Windows10 after a random time with the same config(sometimes minutes, sometimes hours; no network disconnect or anything related to standby/energysaving) . I suppose that it has something to do with Python itself or the encrypt lib?
