### ISSUE TITLE
Request: Please add "log_stats" to colored_logging handler

### ISSUE THREAD

**Issue by neogan86** [PokemonGoF/PokemonGo-Bot#4165]
### Short Description
Please add "log_stats" to colored_logging handler

### Possible solution
The following line can be added to colored_logging_handler.py

### How it would help others
It will be easy to track the progress with so many lines printed on the console between 2 status logs.

**Comment by BreezeLo** [comment]
Fixed in https://github.com/PokemonGoF/PokemonGo-Bot/pull/4230
