### ISSUE TITLE
Google App Account Server Error

### ISSUE THREAD

**Issue by kriswong** [PokemonGoF/PokemonGo-Bot#417]
### Expected Behavior
Google App Email Account should login as previous version

### Actual Behavior
Google App Email Account cause "Login Error, server busy" Message

### Steps to Reproduce
Login with older version, works perfectly.
Login with the latest Dev Branch, Server Error.
Login via client Device, works perfectly.

### Other Information
OS: OSX
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by jtdroste** [comment]
This is going to sound silly, can you verify you're passing everything correctly?  Also when supplying the password, wrap it between quotes.  If you have special characters, your terminal might do funky things to it.

**Comment by kriswong** [comment]
Quotes did the trick. 
Its weird because previous version didn't seem to need them

**Comment by blackmambacode** [comment]
same problem for me in latest dev. need help
