### ISSUE TITLE
Use last location when Bot restart.

### ISSUE THREAD

**Issue by sediyama** [PokemonGoF/PokemonGo-Bot#4170]
### Expected Behavior
When the Bot restart, it should use the location at the file ./data/last-location-NAME@HOST, not the location at ./configs/config.json

### Actual Behavior
Every restart, the bot restart at the location found at the config.json file. 

### Steps to Reproduce
Start the bot, wait a few minutes. It will walk. Stop the bot and restart. It will restart at the default config.json location.

### Possible solution
Use the location at ./data/last-location-NAME@HOST or at least randomize a little the start position.

### How it would help others
It seems to be more human like.

**Comment by Foulwerp** [comment]
``` "location_cache": true,```

Pretty sure this is implemented, I believe this starts the bot at the location it was last at.

**Comment by akanezumi** [comment]
remove the location option from your config file and the bot starts as last known location.

**Comment by MiniWire** [comment]
@akanezumi can confirm.

**Comment by PokemonGoZ** [comment]
Either of the above fixes should work.
