### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by mehdi-S** [PokemonGoF/PokemonGo-Bot#4174]
### Expected Behavior
bot log in and start doing whatever a bot do normally

### Actual Behavior
bot quit after the log in section

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/XxUAZ0yQ

### Output when issue occurred
http://i.imgur.com/DSU3UZM.jpg

### Steps to Reproduce
```
git pull
./setup.sh -u
complete the config.json
./run.sh
```

### Other Information
OS: Debian x86_x64
Branch: 
dev
Git Commit: 
96bdbb698981a6fc544d8064f504fdab48830d06
Python Version: 
Python 2.7.9
Any other relevant files/configs (eg: path files) 
the account tested is a fresh one, never used for play or botting

**Comment by MiniWire** [comment]
I could fix it by using the 32 bit libencrypt. That just worked on Debian x86_64.

I used the following command: python2.7 pokecli.py

**Comment by yweitkemper** [comment]
I'm having the same problem, what exactly did you do to fix it?

**Comment by MiniWire** [comment]
I had to run it with "sudo python2.7 pokecli.py"

**Comment by mehdi-S** [comment]
unfortunatly doesnt work for me @MiniWire

**Comment by MiniWire** [comment]
did you run "pip install -r requirements.txt" ?
and do you have an encrypt-lib for your platform in your bot-root-directory?

**Comment by chihkang** [comment]
try don't use [CatchPokemon] this task, change it to [CatchVisiblePokemon] and [CatchLuredPokemon]

**Comment by k4n30** [comment]
@mehdi-S - The log message indicates you have been banned

@chihkang [CatchPokemon] replaced [CatchVisiblePokemon] and [CatchLuredPokemon] recently so that is not an option. Please don't give the wrong advice

**Comment by mehdi-S** [comment]
@k4n30 if you read my issue, i cannot be banned since my account is fresh created from the second before trying to bot

**Comment by k4n30** [comment]
IP banned, do you share your ip with anyone else or have botted before or run pokemongo-map? There's lots of ways to be banned

**Comment by Netfreak25** [comment]
i am using a proxy and the servers original IP is banned. from time to time the bot crashes with the same error. Maybe not every connection is using the proxy?
