### ISSUE TITLE
Status code 4

### ISSUE THREAD

**Issue by trippyhat** [PokemonGoF/PokemonGo-Bot#4180]
Sometimes when the bot throws a pokeball I see this:

```
{'status_code': 1, 'unknown6': [{'unknown2': {'unknown1': 1L}, 'response_type': 6}], 'responses': {'CATCH_POKEMON': {'status': 4}}, 'request_id': xxxxxxxx }
```
What does this mean?

I changed the `hit_pokemon=0.60` in the `catch_pokemon` request.

**Comment by Gregwar** [comment]
I think 4 means you missed the pokemon
IMO hit pokemon is just a binary flag that tell the server if your pokeball touched the pokemon

**Comment by trippyhat** [comment]
@Gregwar What is the difference between status 2 and status 4?

**Comment by DeXtroTip** [comment]
@trippyhat Status 2 means pokemon escaped from pokeball and status 4 means the pokeball didn't hit the pokemon.
There's a PR about this ([#4107](https://github.com/PokemonGoF/PokemonGo-Bot/pull/4107)), that gives a probability of missing the pokemon purpose.

**Comment by Gregwar** [comment]
Status 2 means that the pokemon escaped the pokeball, this is decided server side
Status 4 means that your pokeball missed the pokeball, which is actually a choice made on the client side (your app do the odd collision test and tell the server 0 or 1)
This is how I understand it
