### ISSUE TITLE
Error:  Please run `pip install -r requirements.txt` 

### ISSUE THREAD

**Issue by Dexter145** [PokemonGoF/PokemonGo-Bot#4181]
### Expected Behavior
Bot starts running

### Actual Behavior
Error:
/root/PokemonGo-Bot/pokemongo_bot/datastore.py:17: UserWarning: Please run `pip install -r requirements.txt` to ensure you have the latest required packages
  warnings.warn('Please run `pip install -r requirements.txt` to ensure you have the latest required packages')
Wed Aug 17 22:50:55 CEST 2016 Pokebot configs/config.json Stopped.
Press any button or wait 20 seconds to continue.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/gDcav1AJ

### Output when issue occurred
After latest update, before it was running well.

### Steps to Reproduce

Run pip install -r requirements.txt

### Other Information
OS: Debian 7
Branch: 
master
Git Commit: 
86fc77478dfe85ee3609169040be825d4fa3512e
Python Version: 2.7.3
Any other relevant files/configs (eg: path files)

**Comment by Dexter145** [comment]
It's working again, don't no why it stops working and a few minutes later works again.

**Comment by cwild** [comment]
Are you using `virtualenv`? I cannot reproduce this.

**Comment by trademarrk** [comment]
im getting this issue too not sure whats wrong

**Comment by cwild** [comment]
Are you on the same commit? Did you update the required packages?

**Comment by trademarrk** [comment]
yea updated it and yes same commit

**Comment by cwild** [comment]
What does `pip freeze` show please?

**Comment by trademarrk** [comment]
alabaster==0.7.9
argh==0.26.2
Babel==2.3.4
backports-abc==0.4
certifi==2016.8.8
click==6.6
colorama==0.3.7
CommonMark==0.5.4
ConfigArgParse==0.10.0
contextlib2==0.5.4
decorator==4.0.10
demjson==2.2.4
docutils==0.12
enum34==1.1.6
eventlet==0.19.0
Flask==0.11.1
Flask-CacheBust==1.0.0
Flask-Compress==1.3.0
Flask-Cors==2.1.2
funcsigs==1.0.2
future==0.15.2
geopy==1.11.0
googlemaps==2.4.4
gpsoauth==0.3.0
gpxpy==1.1.1
greenlet==0.4.9
haversine==0.4.5
imagesize==0.7.1
iniherit==0.3.4
itsdangerous==0.24
Jinja2==2.8
LatLon==1.0.1
livereload==2.4.1
MarkupSafe==0.23
mock==2.0.0
networkx==1.11
numpy==1.11.0
pathtools==0.1.2
pbr==1.10.0
peewee==2.8.1
pgoapi==1.1.6
polyline==1.3.1
port-for==0.3.1
protobuf==3.0.0b4
protobuf-to-dict==0.1.0
pycryptodomex==3.4.2
Pygments==2.1.3
PyMySQL==0.7.5
pyproj==1.9.5.1
PySocks==1.5.6
python-engineio==0.9.2
python-slugify==1.2.0
python-socketio==1.4.2
pytz==2016.6.1
PyYAML==3.11
raven==5.23.0
recommonmark==0.4.0
requests==2.10.0
s2sphere==0.2.4
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
socketIO-client==0.7.0
Sphinx==1.4.5
sphinx-autobuild==0.6.0
sphinx-rtd-theme==0.1.9
timeout-decorator==0.3.2
tornado==4.4.1
Unidecode==0.4.19
virtualenv==15.0.3
watchdog==0.8.3
websocket-client==0.37.0
Werkzeug==0.11.10
xxhash==0.6.1
yoyo-migrations==5.0.3

**Comment by trademarrk** [comment]
any idea what it could be?

**Comment by cwild** [comment]
Could you add `raise` on the line above this:
https://github.com/PokemonGoF/PokemonGo-Bot/blob/da8143e9655ed9ee3fb39c23bafa8981e15cd1e8/pokemongo_bot/datastore.py#L17

What output is shown now?

**Comment by trademarrk** [comment]
try:
    from yoyo import read_migrations, get_backend
except ImportError:
**raise**
    warnings.warn('Please run `pip install -r requirements.txt` to ensure you have the latest required packages')
    sys.exit(-1)
like that?

**Comment by cwild** [comment]
Yes, just make sure you match the indentation with the correct number of spaces.

**Comment by trademarrk** [comment]
Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/Users/PokemonGo-Bot/pokemongo_bot/__init__.py", line 32, in <module>
    from pokemongo_bot.datastore import DatabaseManager, Datastore
  File "/Users/PokemonGo-Bot/pokemongo_bot/datastore.py", line 17, in <module>
    Raise
NameError: name 'Raise' is not defined
Wed 17 Aug 2016 18:12:40 EDT Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by trademarrk** [comment]
try:
    from yoyo import read_migrations, get_backend
except ImportError:
    Raise
    warnings.warn('Please run `pip install -r requirements.txt` to ensure you have the latest required packages')
    sys.exit(-1)

**Comment by trademarrk** [comment]
thats what how the edit looks in the file

**Comment by cwild** [comment]
Lowercase `raise`

**Comment by trademarrk** [comment]
Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/Users/PokemonGo-Bot/pokemongo_bot/__init__.py", line 32, in <module>
    from pokemongo_bot.datastore import DatabaseManager, Datastore
  File "/Users/PokemonGo-Bot/pokemongo_bot/datastore.py", line 15, in <module>
    from yoyo import read_migrations, get_backend
ImportError: No module named yoyo
Wed 17 Aug 2016 18:15:27 EDT Pokebot  Stopped.

**Comment by trademarrk** [comment]
i get that when raise is put in

**Comment by cwild** [comment]
I was kind of hoping for something else to be honest as the `pip freeze` showed **yoyo-migrations==5.0.3** correctly.

Are you using a virtualenv? You haven't dropped out of it by mistake? Can you re-activate with `source bin/activate` (or as appropriate for the venv)?

**Comment by trademarrk** [comment]
yea thats what i downloaded, should still be there i can reinstall if anything, not to sre how to re activate

**Comment by trademarrk** [comment]
The directory '/Users/Paradox/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/Paradox/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): virtualenv in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages

this is what i get when i reinstall virtualenv

**Comment by trademarrk** [comment]
got it to work had to ./setup.sh -i

**Comment by cwild** [comment]
Glad to hear it it resolved for you.

**Comment by trademarrk** [comment]
thanks for the help though (y)
