### ISSUE TITLE
Don't spin fort if inventory is nearly full

### ISSUE THREAD

**Issue by g2384** [PokemonGoF/PokemonGo-Bot#4182]
### Short Description

Ignore some forts if inventory is nearly full.

### Possible solution

add `SpinFortRate`, `inventory_full_threshold`

    SpinFortRate = 0.6
    inventory_full_threshold = 330
    if inventory_count > inventory_full_threshold:
        if random().random() < SpinFortRate:
            spin()
    else:
            ignore()

add `spin_every_n_forts`

    if self.spin_count < spin_every_n_forts:
        self.spin_count += 1
        ignore()
    else:
        spin()
        self.spin_count = 0

### How it would help others

Be more humanised, slow the exp rate. (High ban rate for > lvl 25 accounts)

**Comment by iruy** [comment]
In real life, I usually recycle some items when my inventory is full so that I can spin forts, and this is what bot actually does, recycling only when bag is full

**Comment by g2384** [comment]
Slow down the exp/h rate is the purpose. Most of the >25 bot accounts are banned.

You spin the fort because you wanna level up. You want to level up because it's a valid account and you are sure you will not be banned.

**Comment by iruy** [comment]
If the inventory is emptied before spinning the fort, I don't see the point of this, because this wouldn't mean the bot to be more humanised, maybe less

**Comment by g2384** [comment]
Yes, you are right, it is totally human-like to do 'ignore rattata -> spin fort -> dump potions -> spin fort -> dump potions -> spin fort -> dump potions -> ignore pidgey -> spin fort -> dump potions -> spin fort -> dump potions -> spin fort -> dump potions'

**Comment by CyberMew** [comment]
I think this is a good idea. I don't visit every forts in real life as well.
