### ISSUE TITLE
Failing when using optimizer task

### ISSUE THREAD

**Issue by Arcasss** [PokemonGoF/PokemonGo-Bot#4184]
### Actual Behavior
When I use optimizer task, I am always getting following error:

`2016-08-17 23:19:16,181 [       cli] [INFO] Most Perfect Pokemon:
Traceback (most recent call last):
  File "pokecli.py", line 570, in <module>
    main()
  File "pokecli.py", line 104, in main
    bot.tick()
  File "....\PokemonGo-Bot\pokemongo_bot\__init__.py", line 508, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "....\PokemonGo-Bot\pokemongo_bot\cell_workers\catch_pokemon.py", line 19, in work
    if cw.work() == WorkerResult.RUNNING:
  File "....\PokemonGo-Bot\pokemongo_bot\cell_workers\catch_visible_pokemon.py", line 49, in work
    self.catch_pokemon(self.bot.cell['catchable_pokemons'].pop(0))
  File "....\PokemonGo-Bot\pokemongo_bot\cell_workers\catch_visible_pokemon.py", line 69, in catch_pokemon
    worker = PokemonCatchWorker(pokemon, self.bot, self.config)
  File "....\PokemonGo-Bot\pokemongo_bot\cell_workers\pokemon_catch_worker.py", line 35, in __init__
    super(PokemonCatchWorker, self).__init__(bot, config)
  File "....\PokemonGo-Bot\pokemongo_bot\datastore.py", line 58, in __init__
    migrations = read_migrations(path)
  File "....\Python27\lib\site-packages\yoyo\migrations.py", line 278, in read_migrations
    for path in os.listdir(directory)
WindowsError: [Error 3] The system cannot find the path specified: '....\\PokemonGo-Bot\\pokemongo_bot\\cell_workers\\migrations/*.*'
`
config
`{
	  "type": "PokemonOptimizer",
	  "config": {
		"// the 'transfer' parameter activate or deactivate the transfer of pokemons": {},
		"// at false, no pokemon is going to be transfered, ever": {},
		"// at false, you will still get the log information of what the optimizer": {},
		"// would have transfered if the parameter was true": {},
		"transfer": true,
		"// 'transfer_wait_min' and 'transfer_wait_max' are the minimum and maximum": {},
		"// time to wait when transferring a pokemon": {},
		"transfer_wait_min": 1,
		"transfer_wait_max": 4,
		"// the 'evolve' parameter activate or deactivate the evolution of pokemons": {},
		"// at false, no pokemon is going to be evolved, ever": {},
		"// at false, you will still get the log information of what the": {},
		"// optimizer would have evolved if the parameter was true": {},
		"evolve": true,
		"evolve_time": 20,
		"// the 'use_candies_for_xp' parameter let you choose if you want the optimizer": {},
		"// to use your candies to evolve low quality pokemons in order to maximize your xp": {},
		"// at false, the optimizer will still use candies to evolve your best Pokemons": {},
		"use_candies_for_xp": true,
		"// the 'use_lucky_egg' parameter let you choose if you want the optimizer": {},
		"// to use a lucky egg right before evolving Pokemons. At false; the optimizer": {},
		"// is free to evolve Pokemons even if you do not have any lucky egg.": {},
		"use_lucky_egg": true,
		"// the 'evolve_only_with_lucky_egg' parameter let you choose if you want the optimizer": {},
		"// to only Evolve Pokemons when a lucky egg is available": {},
		"evolve_only_with_lucky_egg": false,
		"// the 'minimum_evolve_for_lucky_egg' parameter let you define the minimum": {},
		"// number of Pokemons that must evolve before using a lucky egg": {},
		"// If that number is not reached, and evolve_only_with_lucky_egg is true, evolution will be skipped": {},
		"// If that number is not reached, and evolve_only_with_lucky_egg is false,": {},
		"// evolution will be performed without using a lucky egg": {},
		"minimum_evolve_for_lucky_egg": 30,
		"// the 'keep' parameter let you define what pokemons you consider are the 'best'. These Pokemons": {},
		"// will be keep and evolved. Note that Pokemons are evaluated inside their whole family": {},
		"// Multiple way of ranking can be defined. Following configuration let you keep the best iv,": {},
		"// the best ncp and the best cp": {},
		"keep": [
		  {
			"// Following setting let you keep the best iv of the family": {},
			"// the 'top' parameter allow you to define how many Pokemons you want to keep": {},
			"// at the top of your ranking. If several Pokemons get the same score, they are": {},
			"// considered equal. Thus, top=1 might result in keeping more than 1 Pokemon.": {},
			"top": 2,
			"// the 'evolve' parameter let you choose if you want to evolve the Pokemons you keep": {},
			"evolve": true,
			"// the 'sort' parameter define how you want to rank your pokemons": {},
			"// Critera are sorted fro, the most important to the least important.": {},
			"// Available criteria are:": {},
			"// 'iv' = individual value": {},
			"// 'ivcp' = iv weigted so that for equal iv, attack > defense > stamina": {},
			"// 'cp' = combat power (can be increased with candies)": {},
			"// 'cp_exact' = combar power (not rounded)": {},
			"// 'ncp' (normalized cp) or 'cp_percent' = ratio cp / max_cp": {},
			"// iv_attack = attach component of iv": {},
			"// iv_defense = defense component of iv": {},
			"// iv_stamina = stamina component of iv": {},
			"// dps = raw dps based on the moves of the pokemon": {},
			"// dps_attack = average dps when attacking": {},
			"// dps_defense = average dps when defending": {},
			"// Note that the more criteria you add to this list, the less likely Pokemons": {},
			"// will be equals": {},
			"sort": [
			  "iv"
			]
		  },
		  {
			"// Following setting let you keep keep the best normalized cp of the family": {},
			"// That is the Pokemon with higher CP once fully evolved": {},
			"top": 2,
			"evolve": true,
			"sort": [
			  "ncp"
			]
		  },
		  {
			"// Following setting let you keep keep the best cp of the family.": {},
			"// But will not evolve it further (in favor of the best ncp)": {},
			"top": 1,
			"evolve": false,
			"sort": [
			  "cp"
			]
		  }
		]
	  }
	},`

### Steps to Reproduce

When there is over 220 pokemons in bag

### Other Information
OS: Windows 10, gitbash
 
Branch: dev
 
Git Commit: 453804c3711984e12e8b3986291dcdf98a80da9d

**Comment by thereyrey** [comment]
Having an issue with optimizer not releasing even tho its set to true also.

{
            "type": "PokemonOptimizer",
            "config": {
                    "// the 'transfer' parameter activate or deactivate the transfer of pokemons": {},
                    "// at false, no pokemon is going to be transfered, ever": {},
                    "// at false, you will still get the log information of what the optimizer": {},
                    "// would have transfered if the parameter was true": {},
                "transfer": true,
                    "// 'transfer_wait_min' and 'transfer_wait_max' are the minimum and maximum": {},
                    "// time to wait when transferring a pokemon": {},
                "transfer_wait_min": 2,
                "transfer_wait_max": 5,
                    "// the 'evolve' parameter activate or deactivate the evolution of pokemons": {},
                    "// at false, no pokemon is going to be evolved, ever": {},
                    "// at false, you will still get the log information of what the": {},
                    "// optimizer would have evolved if the parameter was true": {},
                "evolve": false,
                    "// Time in seconds to wait between two evolve": {},
                "evolve_time": 20,
                    "// the 'evolve_for_xp' parameter let you choose if you want the optimizer": {},
                    "// to use your candies to evolve low quality pokemons in order to maximize your xp": {},
                    "// at false, the optimizer will still use candies to evolve your best Pokemons": {},
                "evolve_for_xp": false,
                    "// the 'evolve_only_with_lucky_egg' parameter let you choose if you want the optimizer": {},
                    "// to only Evolve Pokemons when a lucky egg is available": {},
                "evolve_only_with_lucky_egg": false,
                    "// the 'evolve_count_for_lucky_egg' parameter let you define the minimum": {},
                    "// number of Pokemons that must evolve before using a lucky egg": {},
                    "// If that number is not reached, and evolve_only_with_lucky_egg is true, evolution will be skipped": {},
                    "// If that number is not reached, and evolve_only_with_lucky_egg is false,": {},
                    "// evolution will be performed without using a lucky egg": {},
                "evolve_count_for_lucky_egg": 300,
                    "// the 'may_use_lucky_egg' parameter let you choose if you want the optimizer": {},
                    "// to use a lucky egg right before evolving Pokemons. At false; the optimizer": {},
                    "// is free to evolve Pokemons even if you do not have any lucky egg.": {},
                "may_use_lucky_egg": false,
                    "// the 'keep' parameter let you define what pokemons you consider are the 'best'. These Pokemons": {},
                    "// will be keep and evolved. Note that Pokemons are evaluated inside their whole family": {},
                    "// Multiple way of ranking can be defined. Following configuration let you keep the best iv,": {},
                    "// the best ncp and the best cp": {},
                "keep": [
                    {
                            "// Following setting let you keep the best iv of the family": {},
                            "// the 'top' parameter allow you to define how many Pokemons you want to keep": {},
                            "// at the top of your ranking. If several Pokemons get the same score, they are": {},
                            "// considered equal. Thus, top=1 might result in keeping more than 1 Pokemon.": {},
                        "top": 2,
                            "// the 'evolve' parameter let you choose if you want to evolve the Pokemons you keep": {},
                        "evolve": false,
                            "// the 'sort' parameter define how you want to rank your pokemons": {},
                            "// Critera are sorted fro, the most important to the least important.": {},
                            "// Available criteria are:": {},
                            "// 'iv' = individual value": {},
                            "// 'ivcp' = iv weigted so that for equal iv, attack > defense > stamina": {},
                            "// 'cp' = combat power (can be increased with candies)": {},
                            "// 'cp_exact' = combar power (not rounded)": {},
                            "// 'ncp' (normalized cp) or 'cp_percent' = ratio cp / max_cp": {},
                            "// iv_attack = attach component of iv": {},
                            "// iv_defense = defense component of iv": {},
                            "// iv_stamina = stamina component of iv": {},
                            "// dps = raw dps based on the moves of the pokemon": {},
                            "// dps_attack = average dps when attacking": {},
                            "// dps_defense = average dps when defending": {},
                            "// Note that the more criteria you add to this list, the less likely Pokemons": {},
                            "// will be equals": {},
                        "sort": ["ivcp"]
                    },
                    {
                        "// Following setting let you keep keep the best normalized cp of the family": {},
                        "// That is the Pokemon with higher CP once fully evolved": {},
                        "top": 0,
                        "evolve": false,
                        "sort": ["ncp"]
                    },
                    {
                        "// Following setting let you keep keep the best cp of the family.": {},
                        "// But will not evolve it further (in favor of the best ncp)": {},
                        "top": 0,
                        "evolve": false,
                        "sort": ["cp"]
                    }
                ]
            }
        },

**Comment by cwild** [comment]
This should have been fixed in the more recent `dev`. Can you try again and report back please?

**Comment by maradlgl** [comment]
same issue here...

Git Commit: 8d2182cb0e35031ca50ee6f6f9c96ca0387be498

**Comment by k4n30** [comment]
Before I add the bug tag, can you ensure you have run
`pip2 install --upgrade -r requirements.txt` or pip if not on windows

**Comment by thereyrey** [comment]
@k4n30 "pip2 install --upgrade -r requirements.txt" has been used. Doesnt release pokemons still.

Coupple days ago it didnt release any until it was nearly full. This was great. Now it catches until pokebag is full and then says 0 pokemon released... Bag full cant catch.

**Comment by k4n30** [comment]
@thereyrey your issue is not the same as Arcasss's - I'd suggest creating your own issue

**Comment by Anakin5** [comment]
@thereyrey
The problem are your two rules with keep top 0. Since they are invalid, the optimizer does not take risk and keep them.  Remove these 2 rules.

**Comment by Arcasss** [comment]
Well, there was commit, which fixed it. Can't find exact one, but works properly now. Closing issue.
