### ISSUE TITLE
I got this error in the last version...

### ISSUE THREAD

**Issue by ItaloSama** [PokemonGoF/PokemonGo-Bot#4185]
File "C:\Python27\PokemonGo-Bot\lib\distutils\__ init __ .py", line 23, in <module>
    __ version __ = real_distutils.__ version __
AttributeError: 'module' object has no attribute '__ version __' 

I tried reinstalling the bot, but the error keeps happening (without the gaps between the double underscores).

**Comment by manu183** [comment]
I had the same error, running it manually solved it for me though.
To do that open cmd (just search cmd or run cmd.exe) and paste 

> cd C:\Python27\PokemonGo-Bot\ & python pokecli.py

 there

**Comment by ItaloSama** [comment]
Thank you so much man, it got fixed!
