### ISSUE TITLE
Still Throwing Pokeballs After Caught

### ISSUE THREAD

**Issue by celinereine** [PokemonGoF/PokemonGo-Bot#4187]
![screen shot 2016-08-17 at 6 30 05 pm](https://cloud.githubusercontent.com/assets/20616776/17755579/b1b4836c-64a8-11e6-894c-832fba79aee5.png)

Dev branch, Mac OS x

**Comment by cwild** [comment]
Which commit on dev though?

**Comment by celinereine** [comment]
How do I check the exact commit? I downloaded the latest one from maybe 20 hours ago?

**Comment by cwild** [comment]
`git rev-parse HEAD`

**Comment by celinereine** [comment]
423e4dea72c0b04d8882ef90f03949fe3bf35ac2

**Comment by k4n30** [comment]
Please use issue template
