### ISSUE TITLE
New ban rules

### ISSUE THREAD

**Issue by xGine** [PokemonGoF/PokemonGo-Bot#4190]
Dont know if it is legit info. 

http://www.slashgear.com/pokemon-go-permanent-ban-new-soft-rules-and-reasons-why-15451835/

**Comment by pauloalem** [comment]
I got banned today and probably ran the bot 2 or 3 times. Its probably not safe to use it anymore

**Comment by xGine** [comment]
I have a bot account that i haven't played for few days to preserve it but still banned. It was banned 1st before the hard botted new accounts.

**Comment by geminiyellow** [comment]
can you add a daily reports about how many pokemon cached and , how many shop access?
