### ISSUE TITLE
Pokestop Limit Discussion

### ISSUE THREAD

**Issue by BreezeRo** [PokemonGoF/PokemonGo-Bot#4194]
Was able to get a working example of pokemon catch limits and database logging in https://github.com/PokemonGoF/PokemonGo-Bot/pull/4188 based on database/migrations implementation by @cwild starting in https://github.com/PokemonGoF/PokemonGo-Bot/pull/4129, personally I'm pretty content with the logic there.

What I'm wondering now is how do you guys think the pokestop limit should be handled? Assuming pokestops are logged to the database as the catch logs are, we can easily query the data to grab stops made in the past 24 hours, and count them. If the count is higher than config.pokestop_daily_limit, what should we do? 

- Shut the bot down
- Put it to sleep for a period of time
- Kill the bot
- Stop spinning stops but keep catching

I'd really appreciate some ideas, input (including on the logic)

**Comment by celinereine** [comment]
Honestly, there are enough configurations currently with catch delays that the bot can really slow down to a human level. Just increase the delays and decrease the walk speed. It'd be impossible to even reach the ban limit.

**Comment by mjmadsen** [comment]
What I would like to see down the road, is we run an account until we meet user defined limits. Then we switch to the next account on file and repeat the process.

**Comment by BreezeLo** [comment]
That's a good idea @mjmadsen, noted

**Comment by RedViper9** [comment]
I propose that both the pokestop limit and the pokemon catch limit could be controlled implicitly by providing a maximum walk distance +/- some randomization. The odds of a city dweller walking 30+km per day multiple days per week are fairly low, I think.

Such a limit should also make it fairly simple for the bot to "go home" as some users have requested. No human input (or catching there of) needed.

Thoughts?

**Comment by MerlionRock** [comment]
@RedViper9 Good Idea. Perhaps a new variable call HomeLocation?  Once reached % of userdefined_limit  , it will walk home and inactive for a user defined hrs?

**Comment by INGCRENGIFO** [comment]
some example of settings account ??? They have already banned me :( 2 counts that I have wrong in my config

**Comment by rawgni** [comment]
How do you make sure the user do not login to the bot (using other bot, snipping app or the mobile app) and do things that may skew the data.

Regarding the question, I think it's better if there is a way to randomly throttle the bot behaviour such that it never reaches the limit. However, if it does reach the limit, killing it will be great after doing some stuff, such as:
- checking out profile page
- checking out items
- checking out shop
- walk for awhile (passing pokestops and/or pokemons)
- stop (not moving or catch pokemon) for awhile
- evolve/transfer/rename/favourite

Assume that the code get the bot to do X after hitting the limit, this will be repeated or seen across multiple bots. Suspicious.

**Comment by BreezeLo** [comment]
Good point @rawgni in regard to walking without activity + the bot hitting the same limit on multiple accounts (could especially be obvious if originating from the same IP using other similar variables in config). Perhaps the limit could be offset a little bit (like the mix/max walk values).

@RedViper9 as for returning home in this way, that's a good idea as well - it could even be incorporated into the sleep task in a way that the distance between current position and home could be calculated with the speed variables to send the user home with just enough time before sleep is enabled. So if the bot goes to sleep in 30 minutes and it takes 25 minutes to get home it would stop all activity at that period to make it home "on time"

**Comment by NatNew0** [comment]
Another point might be that people usually follow the streets ;-) 
The bot seems to go through buildings, rivers and so on.
This could possibly be analyzed from the userdata in the database. 
If you have an unrealistic walking path that might trigger a ban.

**Comment by RedViper9** [comment]
@rawgni I think that the user using different applications is not and should not be our concern. That's the user's responsibility. If you know you want to play on your phone later, set the bot's limit to 2/3 normal distance.

I do not think that people using sniping apps are concerned with humanization of the bot, which would be the main goal of using implicit limit rather than explicit limits.

That said, we can manage users switching among different config files in our bot by having the distance traveled since (time) be logged as part of the last-location file.

**Comment by alexyaoyang** [comment]
Stopping all the bot at a fixed number daily is suspicious too. We should randomize based on user provided offset or min/max. Same goes for the daily catch limit which has been merged.

**Comment by MerlionRock** [comment]
Suggestion: Add a % randomness to values that need variance? So that every bot across all user will not seem have a fix routine. Optional  but default to true?

**Comment by Gurzeh** [comment]
@RedViper9 what is the limit on Pokestop visited?

**Comment by k4n30** [comment]
#4906
