### ISSUE TITLE
Idea anti-ban

### ISSUE THREAD

**Issue by Bjr49000** [PokemonGoF/PokemonGo-Bot#4197]
(sorry I'm French so ^^) I think you can use Google Maps Api to know what is the players altitude's for say at pokemon the true altitude and not all times 0 meter altitude ^^.

**Comment by BreezeLo** [comment]
google api refers to it as "elevation"

`{
   "results" : [
      {
         "elevation" : 1608.637939453125,
         "location" : {
            "lat" : 39.73915360,
            "lng" : -104.98470340
         },
         "resolution" : 4.771975994110107
      }
   ],
   "status" : "OK"
}`

**Comment by Bjr49000** [comment]
I see two people say the elevation was all time at 8 or 0 : 
@jboffel 
I'm not a Python dev but it looks like the altitude hard-coding is in src\pgoapi\pgoapi\rpc_apy.pi 
request.altitude = 8

**Comment by jboffel** [comment]
Those subjects have been discussed already in issue: #4114 and #2762
I don't think it needs a new topic.

**Comment by Bjr49000** [comment]
The first issue don't speak about that but about a guy which account was ban after normal use of bot.

**Comment by Bjr49000** [comment]
The first issue don't speak about that but about a guy which account was ban after normal use of bot.

**Comment by Bjr49000** [comment]
And the second, ok we can close this issue sorry I don't see.

**Comment by RedViper9** [comment]
There are two PR's that should be capable of providing altitude support soon.
#3912 
#2986
