### ISSUE TITLE
Show what kind of egg is being hatched.

### ISSUE THREAD

**Issue by Z3r0byte** [PokemonGoF/PokemonGo-Bot#4205]
So instead of this: 
[IncubateEggs] [INFO] [next_egg_incubates] Next egg incubates in 1.71 km
I'd like to see something like:
[IncubateEggs] [INFO] [next_egg_incubates] Next egg (5 km) incubates in 1.71 km

**Comment by jrjhealey** [comment]
I had thought this existed at one point but maybe I imagined it

**Comment by leadboots5** [comment]
@jrjhealey When its put into the incubator it says what kind is being put in.
