### ISSUE TITLE
[move_to_map_pokemon_fail] Failure! Map data was not valid

### ISSUE THREAD

**Issue by beltoft** [PokemonGoF/PokemonGo-Bot#4207]
### Expected Behavior
The bot should snipe using Pokemongo-Map. Map is running on same machine without problems and sniping have worked before.

### Actual Behavior

[MoveToMapPokemon] [INFO] [move_to_map_pokemon_fail] Failure! Map data was not valid

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
{
    "auth_service": "",
    "username": "",
    "password": "",
    "location": "",
    "gmapkey": "",
    "tasks": [
    {
      "type": "HandleSoftBan"
    },
    {
      "type": "CollectLevelUpReward"
    },
    {
      "type": "IncubateEggs",
      "config": {
        "longer_eggs_first": true
      }
    },
    {
      "type": "TransferPokemon"
    },
        {
            "type": "PokemonOptimizer",
            "config": {
                    "// the 'transfer' parameter activate or deactivate the transfer of pokemons": {},
                    "// at false, no pokemon is going to be transfered, ever": {},
                    "// at false, you will still get the log information of what the optimizer": {},
                    "// would have transfered if the parameter was true": {},
                "transfer": true,
                    "// the 'evolve' parameter activate or deactivate the evolution of pokemons": {},
                    "// at false, no pokemon is going to be evolved, ever": {},
                    "// at false, you will still get the log information of what the": {},
                    "// optimizer would have evolved if the parameter was true": {},
                "evolve": true,
                    "// the 'use_candies_for_xp' parameter let you choose if you want the optimizer": {},
                    "// to use your candies to evolve low quality pokemons in order to maximize your xp": {},
                    "// at false, the optimizer will still use candies to evolve your best Pokemons": {},
                "use_candies_for_xp": false,
                    "// the 'use_lucky_egg' parameter let you choose if you want the optimizer": {},
                    "// to use a lucky egg right before evolving Pokemons. At false; the optimizer": {},
                    "// is free to evolve Pokemons even if you do not have any lucky egg.": {},
                "use_lucky_egg": false,
                    "// the 'evolve_only_with_lucky_egg' parameter let you choose if you want the optimizer": {},
                    "// to only Evolve Pokemons when a lucky egg is available": {},
                "evolve_only_with_lucky_egg": false,
                    "// the 'minimum_evolve_for_lucky_egg' parameter let you define the minimum": {},
                    "// number of Pokemons that must evolve before using a lucky egg": {},
                    "// If that number is not reached, and evolve_only_with_lucky_egg is true, evolution will be skipped": {},
                    "// If that number is not reached, and evolve_only_with_lucky_egg is false,": {},
                    "// evolution will be performed without using a lucky egg": {},
                "minimum_evolve_for_lucky_egg": 90,
                    "// the 'keep' parameter let you define what pokemons you consider are the 'best'. These Pokemons": {},
                    "// will be keep and evolved. Note that Pokemons are evaluated inside their whole family": {},
                    "// Multiple way of ranking can be defined. Following configuration let you keep the best iv,": {},
                    "// the best ncp and the best cp": {},
                "keep": [
                    {
                            "// Following setting let you keep the best iv of the family": {},
                            "// the 'top' parameter allow you to define how many Pokemons you want to keep": {},
                            "// at the top of your ranking. If several Pokemons get the same score, they are": {},
                            "// considered equal. Thus, top=1 might result in keeping more than 1 Pokemon.": {},
                        "top": 1,
                            "// the 'evolve' parameter let you choose if you want to evolve the Pokemons you keep": {},
                        "evolve": true,
                            "// the 'sort' parameter define how you want to rank your pokemons": {},
                            "// Critera are sorted fro, the most important to the least important.": {},
                            "// Available criteria are:": {},
                            "// 'iv' = individual value": {},
                            "// 'ivcp' = iv weigted so that for equal iv, attack > defense > stamina": {},
                            "// 'cp' = combat power (can be increased with candies)": {},
                            "// 'cp_exact' = combar power (not rounded)": {},
                            "// 'ncp' (normalized cp) or 'cp_percent' = ratio cp / max_cp": {},
                            "// iv_attack = attach component of iv": {},
                            "// iv_defense = defense component of iv": {},
                            "// iv_stamina = stamina component of iv": {},
                            "// dps = raw dps based on the moves of the pokemon": {},
                            "// dps_attack = average dps when attacking": {},
                            "// dps_defense = average dps when defending": {},
                            "// Note that the more criteria you add to this list, the less likely Pokemons": {},
                            "// will be equals": {},
                        "sort": ["iv"]
                    },
                    {
                        "// Following setting let you keep keep the best normalized cp of the family": {},
                        "// That is the Pokemon with higher CP once fully evolved": {},
                        "top": 1,
                        "evolve": true,
                        "sort": ["ncp"]
                    },
                    {
                        "// Following setting let you keep keep the best cp of the family.": {},
                        "// But will not evolve it further (in favor of the best ncp)": {},
                        "top": 1,
                        "evolve": false,
                        "sort": ["cp"]
                    }
                ]
            }
        },
    {
      "type": "RecycleItems",
      "config": {
        "item_filter": {
          "1": { "keep" : 20 },
          "2": { "keep" : 30 },
          "3": { "keep" : 60 },
          "101": { "keep" : 0 },
          "102": { "keep" : 0 },
          "103": { "keep" : 15 },
          "104": { "keep" : 25 },
          "201": { "keep" : 10 },
          "202": { "keep" : 15 },
          "701": { "keep" : 50 },
          "801": { "keep" : 50 }
        }
      }
    },
	    {
	      "type": "CatchPokemon",
	      "config": {
	        "catch_visible_pokemon": true,
	        "catch_lured_pokemon": true,
	        "min_ultraball_to_keep": 5,
	        "catch_throw_parameters": {
	          "excellent_rate": 0.1,
	          "great_rate": 0.5,
	          "nice_rate": 0.3,
	          "normal_rate": 0.1,
	          "spin_success_rate" : 0.6
	        },
				  "catch_simulation": {
				    "flee_count": 3,
				    "flee_duration": 2,
				    "catch_wait_min": 2,
				    "catch_wait_max": 6,
				    "berry_wait_min": 2,
				    "berry_wait_max": 3,
				    "changeball_wait_min": 2,
				    "changeball_wait_max": 3
				  }
	      }
	    },
    {
        "type": "SpinFort",
        "config": {
          "spin_wait_min": 2,
          "spin_wait_max": 3
        }
      }, 
    {
      "type": "MoveToMapPokemon",
        "config": {
          "address": "http://10.120.36.50:5000/",
          "max_distance": 500,
          "min_ball": 50,
          "prioritize_vips": true,
          "snipe": true,
          "snipe_high_prio_only": true,
          "snipe_high_prio_threshold": 400,
          "update_map": false,
          "mode": "priority",
          "map_path": "raw_data",
          "catch": {
          "==========Legendaries==========": 0,
          "Aerodactyl": 1000,
          "Snorlax": 1000,
          "Articuno": 1000,
          "Zapdos": 1000,
          "Moltres": 1000,
          "Dratini": 1000,
          "Dragonair": 1000,
          "Dragonite": 1000,
          "Mewtwo": 1000,
          "Mew": 1000,

          "==========Region Locked==========": 0,
          "Farfetch'd": 1000,
          "Kangaskhan": 1000,
          "Mr. Mime": 1000,
          "Tauros": 1000,

          "==========Very Rare==========": 0,
          "Lapras": 900,
          "Electabuzz": 900,
          "Magmar": 900,
          "Ditto": 900,

          "==========Starters==========": 0,
          "Bulbasaur": 400,
          "Ivysaur": 600,
          "Venusaur": 1000,

          "Charmander": 400,
          "Charmeleon": 600,
          "Charizard": 1000,

          "Squirtle": 400,
          "Wartortle": 600,
          "Blastoise": 1000,

          "Pikachu": 600,
          "Raichu": 1000,

          "==========Semi Rare==========": 0,
          "Porygon": 200,
          "Scyther": 200,

          "==========Uncommon==========": 0,

          "Omastar": 500,

          "Dewgong": 500,

          "Muk": 500,

          "Cloyster": 500,

          "Haunter": 500,
          "Gengar": 1000,

          "Hypno": 600,

          "Vulpix": 200,
          "Ninetales": 600,

          "Wigglytuff": 500,

          "Dugtrio": 500,

          "Vaporeon": 800,
          "Jolteon": 800,
          "Flareon": 800,

          "Kabutops": 500,

          "Gyarados": 800,

          "Rapidash": 500,

          "Slowbro": 500,

          "Magnemite": 250,
          "Magneton": 500,

          "Kingler": 500,

          "Electrode": 500,

          "Exeggcutor": 500,

          "Hitmonlee": 400,

          "Hitmonchan": 400,

          "Lickitung": 500,

          "Weezing": 500,

          "Rhydon": 500,

          "Chansey": 800,

          "Tangela": 300,

          "Seadra": 600,

          "Seaking": 500,

          "Starmie": 800,

          "==========T1 Evolvers==========": 0,
          "Butterfree": 500,

          "Beedrill": 500,

          "Pidgeot": 300,

          "==========T2 Evolvers==========": 0,
          "Oddish": 100,
          "Gloom": 200,
          "Vileplume": 600,

          "Poliwhirl": 400,
          "Poliwrath": 800,

          "Abra": 300,
          "Kadabra": 600,
          "Alakazam": 800,

          "Machoke": 400,
          "Machamp": 800,

          "Weepinbell": 400,
          "Victreebel": 800
        }
      }
    },
    {
      "type": "MoveToFort",
      "config": {
        "lure_attraction": true,
        "lure_max_distance": 2000
      }
    }
  ],
  "map_object_cache_time": 5,
  "forts": {
    "avoid_circles": true,
    "max_circle_size": 50
  },
  "websocket_server": false,
  "walk_min": 13,
  "walk_max": 23,
  "action_wait_min": 1,
  "action_wait_max": 5,
  "debug": false,
  "test": false,
  "health_record": false,
  "location_cache": true,
  "distance_unit": "km",
  "reconnecting_timeout": 1,
  "catch_randomize_reticle_factor": 1.0,
  "catch_randomize_spin_factor": 1.0,
   "catch_throw_parameters": {
      "excellent_rate": 0.7,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.8
    },
  "catch": {
    "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or" },

    "// Pokemons with example": { "always_catch": true },
    "// Gets filtered with release parameters": {},

    "// Legendary pokemons (Goes under S-Tier)": {},
    "Lapras": { "always_catch": true },
    "Moltres": { "always_catch": true },
    "Zapdos": { "always_catch": true },
    "Articuno": { "always_catch": true },

    "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
    "Mewtwo": { "always_catch": true },
    "Dragonite": { "always_catch": true },
    "Snorlax": { "always_catch": true },
    "// Mew evolves to Mewtwo": {},
    "Mew": { "always_catch": true },
    "Arcanine": { "always_catch": true },
    "Vaporeon": { "always_catch": true },
    "Gyarados": { "always_catch": true },
    "Exeggutor": { "always_catch": true },
    "Muk": { "always_catch": true },
    "Weezing": { "always_catch": true },
    "Flareon": { "always_catch": true },

    "// Growlithe evolves to Arcanine": {},
    "Growlithe": { "always_catch": true },
    "// Dragonair evolves to Dragonite": {},
    "Dragonair": { "always_catch": true },
    "// Grimer evolves to Muk": {},
    "Grimer": { "always_catch": true },

    "// Magikarp evolves to Gyarados": {},
    "Magikarp": { "always_catch": true },
    "// Exeggcute evolves to Exeggutor": {},
    "Exeggcute": { "always_catch": true },
    "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
    "Eevee": { "always_catch": true },

    "// A-Tier pokemons": {},
    "Slowbro": { "always_catch": true },
    "Victreebel": { "always_catch": true },
    "Machamp": { "always_catch": true },
    "Poliwrath": { "always_catch": true },
    "Clefable": { "always_catch": true },
    "Nidoking": { "always_catch": true },
    "Venusaur": { "always_catch": true },
    "Charizard": { "always_catch": true },
    "Golduck": { "always_catch": true },
    "Nidoqueen": { "always_catch": true },
    "Vileplume": { "always_catch": true },
    "Blastoise": { "always_catch": true },
    "Omastar":  { "always_catch": true },
    "Aerodactyl": { "always_catch": true },
    "Golem": { "always_catch": true },
    "Wigglytuff": { "always_catch": true },
    "Dewgong": { "always_catch": true },
    "Ninetales": { "always_catch": true },
    "Magmar": { "always_catch": true },
    "Kabutops": { "always_catch": true },
    "Electabuzz": { "always_catch": true },
    "Starmie": { "always_catch": true },
    "Jolteon": { "always_catch": true },
    "Rapidash": { "always_catch": true },
    "Pinsir": { "always_catch": true },
    "Scyther": { "always_catch": true },
    "Tentacruel": { "always_catch": true },
    "Gengar": { "always_catch": true },
    "Hypno": { "always_catch": true },
    "Pidgeot": { "always_catch": true },
    "Rhydon": { "always_catch": true },
    "Seaking": { "always_catch": true },
    "Kangaskhan": { "always_catch": true }
  },
  "release": {
    "any": {"keep_best_cp":1, "keep_best_iv":1 },

    "Eevee": {"keep_best_iv":2 },
    "Dratini": {"keep_best_cp":3, "keep_best_iv":2}
  },
  "vips" : {
    "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
    "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
    "Lapras": {},
    "Moltres": {},
    "Zapdos": {},
    "Articuno": {},

    "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
    "Mewtwo": {},
    "Dragonite": {},
    "Snorlax": {},
    "// Mew evolves to Mewtwo": {},
    "Mew": {},
    "Arcanine": {},
    "Vaporeon": {},
    "Gyarados": {},
    "Exeggutor": {},
    "Muk": {},
    "Weezing": {},
    "Flareon": {}

  }
}

### Output when issue occurred
no error - bot is running but just not sniping

### Other Information
OS: ubuntu 14.04 LTS

Branch:  DEV

Git Commit: 

Python Version:  2.7.6

**Comment by Raiven66** [comment]
the data provided by the server you have set in config is not valid, not a bot problem, it is a problem of your map source... seems like it is not local either - tried reaching it and it times out

**Comment by beltoft** [comment]
its local and i can reach it just fine here. im using the local IP of the box because i haven't set localhost up on it

**Comment by beltoft** [comment]
Got it to work
the "address": "http://10.120.36.50:5000/",

should not be ended with a /
the correct is
"address": "http://10.120.36.50:5000",
