### ISSUE TITLE
Find and catch Pokémon to any location on the road

### ISSUE THREAD

**Issue by DarkPP** [PokemonGoF/PokemonGo-Bot#4208]
My observation, the pokemon born around pokestop, gym and near the road. Some time I want to my bot find and catch Pokémon to any location on the road. Can you add new feature.
thank

**Comment by sediyama** [comment]
It is already implemented, with, every move the Bot search for pokemon with the catchable_pokemon event.

**Comment by DarkPP** [comment]
Sorry, in detail I want to bot walk on the road from pokestop to anther pokestop. somtime, my bot swim to pokestop. it's impossible.

**Comment by k4n30** [comment]
#3854
