### ISSUE TITLE
ImportError: No module named RequestType_pb2

### ISSUE THREAD

**Issue by kenshi08** [PokemonGoF/PokemonGo-Bot#4214]
**Expected Behavior**
The bot to run python pokecli.py -cf configs/config.json

**Actual Behavior**
Could not run and throws error: ImportError: No module named RequestType_pb2

**Config.json**
http://pastebin.com/6cVYJHyd

**Steps to Reproduce**
git pull
sudo -H pip install --upgrade -r requirements
python pokecli.py -cf configs/config.json

**Other Information**
OS: Mac OS
Branch: dev
Git Commit: 8eba07a4e014e5dd2926bf512e462c3fd76c01ab
Python Version: Python 2.7.12

**Comment by maxprzemo** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/commit/8eba07a4e014e5dd2926bf512e462c3fd76c01ab

**Comment by solderzzc** [comment]
You need a refresh clone to upgrade the pgoapi.
https://github.com/keyphact/pgoapi/commit/12b2028cbf19342efd971020033027802b569769#diff-4bc4a3aa1c235ceabe560c992a4256f8L41
