### ISSUE TITLE
Randomize the catch pokemon logic?

### ISSUE THREAD

**Issue by trippyhat** [PokemonGoF/PokemonGo-Bot#4221]
Right now it's too perfect when catching pokemon: it's like a 100% success rate.

Can we make it so that the spin, reticule, and hit pokemon be randomized. I think right now it's just setting the reticule be at 1.95 (perfect) and the spin modifier at 1 (perfect spin), and the hit pokemon is always 100%. However, when dealing with VIP pokemons the success rate should be a lot higher like 80%.

or at least allow a setting in the config file so we can adjust it?

**Comment by NatNew0** [comment]
what's wrong with:

            "catch_throw_parameters": {
              "excellent_rate": 0.1,
              "great_rate": 0.5,
              "nice_rate": 0.3,
              "normal_rate": 0.1,
              "spin_success_rate" : 0.6
            },
in the config ?

**Comment by Tomygames** [comment]
The missed poke balls options (anti-ban hint) ;)

**Comment by Vvkmnn** [comment]
I agree. Maybe we should be summing up to less than 1, so we miss some attempts.

**Comment by leadboots5** [comment]
Closing as this functionality already exists as noted. Also as noted there is already a feature request for missing throws.
