### ISSUE TITLE
Server seems to be busy or offline??

### ISSUE THREAD

**Issue by Aakarshkaku** [PokemonGoF/PokemonGo-Bot#4222]
I recently starte my bot and this showed up. I can not access my pokemon go ptc account now.
Anyone please help?

**Comment by lucasmiguins** [comment]
I think u get banned, same to me.

**Comment by Aakarshkaku** [comment]
It's really heartbreaking man. Anyway back?

**Comment by nivong** [comment]
read the bloody read me and dont create an issue.

**Comment by Calcyfer** [comment]
You're probably permabanned. Make a new account :).
