### ISSUE TITLE
Feature Request - MoveToMapPokemon stop catching when VIP

### ISSUE THREAD

**Issue by thereyrey** [PokemonGoF/PokemonGo-Bot#4227]
### Short Description:

When not sniping and just walking towards a vip pokemon. It would be great if the bot could have a coupple settings like "don't-spin-pokestops". and "only-catch-VIP-until-encountered-VIP". 
Then resume after. 

Sometimes when you set the bot to walk slow and its encountering alot of pokemons, and even missing throws on purpose etc.., the timer runs out and you don't reach the VIP.

**Comment by jaimerson** [comment]
Also, this would make the more more human-like. I mean, who would ignore a Charizard and catch a bunch of Pidgeys?

**Comment by k4n30** [comment]
Who sets move to map to choose Pidgey's though? If you config it that way, u deserve to miss Charizard

**Comment by jaimerson** [comment]
@k4n30 sure, but maybe this feature should be always prioritise VIPs over other Pokémon/pokestops when they're available

**Comment by k4n30** [comment]
Or prioritise based on snipe value as long as conditions are met (i.e. it goes for 1000s -> 900 -> 800 etc if it can get there in time)

**Comment by Raiven66** [comment]
and when I proposed this 3 weeks ago noone wanted it -.-

This would require some global variable (eg. should_continue_catching) to be set and the catch task only would work based on this variable.
Would you guys like to have it for VIPs only or for example using the high_prio_threshold there is for sniping?

**Comment by thereyrey** [comment]
High_prio_threshold is a good idea to use..

**Comment by k4n30** [comment]
both? if you're going to add one, why not the other?

**Comment by Raiven66** [comment]
I have to see whether I can even do that :P other than that there is no real reason why not both, but probably I would maybe combine this with the sniping feature - if snipe is false, use it's settings for determining to ignore stuff

**Comment by ganagus** [comment]
I just missed a snorlax and a squirtle because bot was busy caching weedles and rattatas on the way to the point where snowlax was found on the map. So yes, I up vote this idea.

**Comment by k4n30** [comment]
@ganagus but you didn't actually upvote it :p

**Comment by masterpowers** [comment]
thumbs up

**Comment by k4n30** [comment]
@masterpowers actually use the thumbs up option on the OP or it wont be counted

**Comment by sohje** [comment]
Why not to make something like this:
```python
if pokemon['is_vip'] or nearest_fort is None:
    # skip nearest fort(if there any) and move directly to VIP pokemon
    step_walker = self._move_to(pokemon)
```

**Comment by sohje** [comment]
Merged, check it out guys.

**Comment by thereyrey** [comment]
Really great! Thanks alot for filling the request :)
