### ISSUE TITLE
Feature Request - breaking out Evolve/release configs to a config.d directory

### ISSUE THREAD

**Issue by pezhore** [PokemonGoF/PokemonGo-Bot#4229]
I'm switching between the pathing and the loop configurations (and a few variants of each), and finding it time consuming to ensure I have identical release/evolve key-value pairs in all of my json.

Is it possible (and where would I go about looking) to add a conf.d directory that would auto-load the various *.json files into the running config?

I would expect that there might be a release pokemon section, possibly an EvolvePokemon section as well.

**Comment by MZorzy** [comment]
also login & google api detail

**Comment by RedViper9** [comment]
#3506 Covers this issue, I believe.
