### ISSUE TITLE
transfer of pokemons above my given cp

### ISSUE THREAD

**Issue by anonymouslulz22** [PokemonGoF/PokemonGo-Bot#423]
### Expected Behavior
when i use -c 350 then it should transfer all the pokemons getting caught which is lower than cp 350

### Actual Behavior
but it transfers pokemons of cp more than give 

### Steps to Reproduce
--c

### Other Information
OS:kali 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by anonymouslulz22** [comment]
-iv although works for me

**Comment by J102030** [comment]
Same issue here when no -iv parameter used

**Comment by bgrimm** [comment]
same issue here. only using -c

**Comment by julesferreira** [comment]
pokemon are currently transferred if `CP` **OR** `IV` are less than configured values. (defaults: `CP:100`, `IV:0.8`)

**Comment by TSM-EVO** [comment]
This is very good and this is how it should be. 

If you want to keep trashy pokemon, you can set the params to 

-iv 0.1

and/or 

-c -1

**Comment by vtuan10** [comment]
is there a reason for setting default of IV to 0.8? 
Most people do not know what this is and and are wondering why their high cp pokemon were transferred.
And i would not like it if my 3000 cp dragoran with a IV of 0.7 would be transferred....

**Comment by ts91** [comment]
At the moment I believe it is -c **AND** -iv for transfered pokemons. The -iv should default to 0. What does it default to at the moment?

**Comment by ts91** [comment]
The default values are in _config.json.example_ so at the moment CP 100 and IV 0.7. Are these sensible  values?

**Comment by surfaace** [comment]
default values lowered and release_config.json is now used. please report new issue if you still have problems

closing due to alot of changes has been made to function
