### ISSUE TITLE
    "action_wait_min": It does not work on Dev

### ISSUE THREAD

**Issue by maxprzemo** [PokemonGoF/PokemonGo-Bot#4248]
Expected Behavior
Random the time to delay action
"action_wait_min": 2,
"action_wait_max": 5,

### Actual Behavior
    "action_wait_min": 2,
    "action_wait_max": 5,
No delays. Every action performed every second. Too many queries to the server "permabanned"
2016-08-19 10:45:48,301 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.09km
2016-08-19 10:45:49,676 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.08km
2016-08-19 10:45:51,081 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.08km
2016-08-19 10:45:52,672 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.08km
2016-08-19 10:45:54,111 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.07km
2016-08-19 10:45:55,592 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.07km
2016-08-19 10:45:56,967 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.07km
2016-08-19 10:45:58,259 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.07km
2016-08-19 10:45:59,263 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.06km
2016-08-19 10:46:00,460 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.06km
2016-08-19 10:46:02,049 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.06km
2016-08-19 10:46:03,703 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.06km
2016-08-19 10:46:05,170 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.06km
2016-08-19 10:46:06,663 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.05km
2016-08-19 10:46:08,116 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.05km
2016-08-19 10:46:09,503 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.05km
2016-08-19 10:46:10,884 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.05km
2016-08-19 10:46:12,273 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.04km
2016-08-19 10:46:13,326 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.04km
### Your FULL config.json (remove your username, password, gmapkey and any other private info)

`{
    "auth_service": "ptc",
    "username": "XXXXXXXX",
    "password": "XXXXXXXXX",
    "location": "XXXXXXXXX",
    "gmapkey": "XXXXXXXXXXXXXXXXXXXX",
    "encrypt_location": "",
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "14:06",
          "duration":"20:46",
          "time_random_offset": "00:13",
          "duration_random_offset": "00:09"
        }
      },
	  {
		"type": "RandomPause",
        "config": {
		  "enabled": true,
		  "min_duration": "00:00:10",
		  "max_duration": "00:01:00",
		  "min_interval": "00:05:00",
		  "max_interval": "00:30:00"
        }
	  },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
	        "enabled": true,
            "min_interval": 60,
            "stats": ["login", "uptime", "km_walked", "level_stats", "pokemon_caught", "xp_earned", "xp_per_hour", "stops_visited", "pokemon_stats", "highest_cp_pokemon"],
            "terminal_log": true,
            "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon"
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
            "evolve_all": "Rattata, Spearow, Caterpie, Weedle",
            "evolve_captured": "Rattata, Spearow, Caterpie, Weedle",
            "first_evolve_by": "cp",
            "evolve_above_cp": 10,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "evolve_speed": 20,
            "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 20,
          "max_balls_keep": 180,
          "max_potions_keep": 60,
          "max_berries_keep": 60,
          "max_revives_keep": 50,
          "item_filter": {
            "Pokeball":       { "keep" : 80 },
            "Greatball":      { "keep" : 50 },
            "Ultraball":      { "keep" : 50 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 40 }
          }
        }
      },
	    {
	      "type": "CatchPokemon",
	      "config": {
	        "catch_visible_pokemon": true,
	        "catch_lured_pokemon": true,
	        "min_ultraball_to_keep": 5,
	        "catch_throw_parameters": {
	          "excellent_rate": 0.1,
	          "great_rate": 0.1,
	          "nice_rate": 0.2,
	          "normal_rate": 0.6,
	          "spin_success_rate" : 0.0
	        },
				  "catch_simulation": {
				    "flee_count": 3,
				    "flee_duration": 2,
				    "catch_wait_min": 2,
				    "catch_wait_max": 6,
				    "berry_wait_min": 2,
				    "berry_wait_max": 3,
				    "changeball_wait_min": 2,
				    "changeball_wait_max": 3
			    }
	      }
	    },
      {
        "type": "SpinFort"
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 1000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 90
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 35,
      "cache_recent_forts": true
    },
    "walk_max": 3.88,
    "walk_min": 2.16,
    "action_wait_min": 2,
    "action_wait_max": 5,
    "debug": false,
    "test": false,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging_color": true,
    "daily_catch_limit": 500,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 10, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "Bellsprout": {"keep_best_cp": 3},
      "Caterpie": {"keep_best_cp": 1},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "Drowzee": {"keep_best_cp": 3, "keep_best_iv": 3, "logic": "and"},
      "Eevee": {"keep_best_cp": 3, "keep_best_iv": 3, "logic": "and"},
      "Hypno": {"keep_best_cp": 3, "keep_best_iv": 3, "logic": "and"},
      "Gastly": {"keep_best_cp": 3},
      "Nidoran M": {"keep_best_cp": 3},
      "Nidoran F": {"keep_best_cp": 3},
      "Horsea": {"keep_best_cp": 3},
      "Jynx": {"keep_best_cp": 3},
      "Magikarp": {"keep_best_cp": 3},
      "Magnemite": {"keep_best_cp": 3},
      "Meowth": {"keep_best_cp": 3},
      "Paras": {"keep_best_cp": 3},
      "Pidgeotto": {"keep_best_cp": 3},
      "Pidgey": {"keep_best_cp": 3},
      "Pidgeot": {"keep_best_cp": 3},
      "Psyduck": {"keep_best_cp": 3},
      "Raticate": {"keep_best_cp": 3},
      "Krabby": {"keep_best_cp": 3},
      "Oddish": {"keep_best_cp": 3},
      "Rattata": {"keep_best_cp": 2},
      "Spearow": {"keep_best_cp": 1},
      "Seel": {"keep_best_cp": 3},
      "Shellder": {"keep_best_cp": 3},
      "Squirtle": {"keep_best_cp": 3},
      "Tentacool": {"keep_best_cp": 3},
      "Venonat": {"keep_best_cp": 3},
      "Weedle": {"keep_best_cp": 1},
      "Zubat": {"keep_best_cp": 3},
      "Fearow": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 500, "catch_above_iv": 0.8, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}`

### Other Information
OS: 
Debian 8.5
Branch: 
Dev 

### Possible solution
There are no sources for code 
`    "action_wait_min": ,
    "action_wait_max": ,`
in dev branch
https://github.com/PokemonGoF/PokemonGo-Bot/pull/4255/commits/7136348dda4217d8010aab4d8e6f1124cba64140

**Comment by k4n30** [comment]
@maxprzemo Please read the description of #4048 

You're getting confused with heartbeat_threshold which is what does the call the servers, and this is in line with the official client so you won't get permabanned.  Just because your bot gives you an update doesn't mean it making calls to the server.
