### ISSUE TITLE
Switching From Master To Dev Throws Error on Start up: KeyError: 'player_data' -- RESOLVED

### ISSUE THREAD

**Issue by doctor-ew** [PokemonGoF/PokemonGo-Bot#425]
### RESOLVED

I recloned dev branch outside my original repo clone -- works perfect.

Leaving this here in case someone runs into same issue.

THANKS FOR THE WORK, TEAM!!

I've been running master throughout the night -- this project is awesome!

Wanted to try dev; however, the code errors out:
player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'

### Actual Behavior
Namespace(auth_service='google', cp=100, debug=False, distance_unit='km', gmapkey=None, initial_transfer=False, location='800 Cherokee Ave SE, Atlanta, GA 30315', location_cache=False, max_steps=50, mode='all', password='{pwd}', pokemon_potential=0.8, test=False, username='{un}', walk=2.5)
[x] PokemonGO Bot v1.0
[x] Configuration initialized

[x] Address found: 800 Cherokee Ave SE, Atlanta, GA 30315
[x] Position in-game set as: (33.7321624, -84.3713351, 0.0)

Traceback (most recent call last):
  File "pokecli.py", line 124, in <module>
    main()
  File "pokecli.py", line 112, in main
    bot.start()
  File "/Users/Sites/shuttlebay/PokemonGo-Bot/pokemongo_bot/__init__.py", line 28, in start
    self._setup_api()
  File "/Users/Sites/shuttlebay/PokemonGo-Bot/pokemongo_bot/__init__.py", line 141, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'

### Steps to Reproduce
Checked out dev, ran 
$ virtualenv .  
$ source bin/activate  
$ pip install -r requirements.txt  
$ pip install --upgrade -r requirements.txt

$ python pokecli.py -a google -u {usernme} -p {password} --location "{address}"

### Other Information
OS: OSX Yosemite
Git Commit: 9684c2cbfaead634d6372315ab23fc58427a0c3f

**Comment by Electrofenster** [comment]
@doctor-ew you should remove your google email and password from this issue!

**Comment by doctor-ew** [comment]
Carp! Thought I got all references. It's a throwaway, but thx.

**Comment by LasseSkogland** [comment]
You will need to change some values in: pokemongo_bot\__init__.py
Heres the patch: https://gist.github.com/LasseSkogland/5d064902dd054fbdfdf5ed7c76c5ac99

**Comment by doctor-ew** [comment]
@LasseSkogland -- re-cloning the repo did the trick. Thanks!
