### ISSUE TITLE
Bot will not run after updating, ImportError: No module named RequestType_pb2

### ISSUE THREAD

**Issue by Dcstegg228** [PokemonGoF/PokemonGo-Bot#4251]
### Expected Behavior
Before I updated to the latest dev build the bot ran as normal but now i get the same error no matter what I try.
 Everything was working fine until I tried to update.
`git pull` 
`pip install -r requirements.txt  --upgrade`

I have already tried to start over by deleting everything and running 
`git clone -b dev https://github.com/PokemonGoF/PokemonGo-Bot`
`pip install -r requirements.txt`

I also tried to update the pgo api as suggested [Here](https://github.com/PokemonGoF/PokemonGo-Bot/issues/4214) git clone the latest master branch of the pgoapi and placed it inside the src directory of the bot then ran `pip install -r requirements.txt`

### Actual Behavior

ImportError: No module named RequestType_pb2

### Your FULL config.json 

http://pastebin.com/eAPN97y6

### Output when issue occurred

$ python pokecli.py
Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pokemongo_bot import inventory
  File "C:\Bothax\PokemonGo-Bot\pokemongo_bot\__init__.py", line 22, in <module>
    from api_wrapper import ApiWrapper
  File "C:\Bothax\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 9, in <module>
    from pgoapi.protos.POGOProtos.Networking.Requests.RequestType_pb2 import RequestType
ImportError: No module named RequestType_pb2

### Steps to Reproduce
`git clone -b dev https://github.com/PokemonGoF/PokemonGo-Bot`
`pip install -r requirements.txt`
edit config file
place encrypt.dll where it needs to go
`python pokecli.py`

### Other Information
OS: 
windows 10
Branch: 
Dev 
Git Commit: 
#4107? Latest dev branch as of 15 minutes ago
Python Version: 
2.7

**Comment by HongxuChen** [comment]
`setup.sh -u` works for me.

**Comment by hlavicka** [comment]
try 
pip uninstall pgoapi
pip install -r requirements.txt

**Comment by Dcstegg228** [comment]
That worked, Thanks!
