### ISSUE TITLE
TypeError: walker_factory() takes at least 5 arguments (4 given)

### ISSUE THREAD

**Issue by p1n9** [PokemonGoF/PokemonGo-Bot#4253]
### Expected Behavior
Running fine with move to map pokemon enabled in conf

### Actual Behavior
Crash just after starting or few minutes later...
It seems that the update map position is working but each time it try to move to one pokemon it crash just after.

### FULL config.json
[http://pastebin.com/sEvBJsuR](http://pastebin.com/sEvBJsuR)

### Output when issue occurred
```
Traceback (most recent call last):
  File "pokecli.py", line 611, in <module>
    main()
  File "pokecli.py", line 105, in main
    bot.tick()
  File "/var/www/html/PokemonGo-Bot/pokemongo_bot/__init__.py", line 532, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/var/www/html/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_map_pokemon.py", line 279, in work
    step_walker = self._move_to(pokemon)
  File "/var/www/html/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_map_pokemon.py", line 383, in _move_to
    **{'parent': MoveToMapPokemon}
TypeError: walker_factory() takes at least 5 arguments (4 given)
```

### Steps to Reproduce
Running bot with move to map pokemon enabled

### Other Information
OS: ubuntu 14.04
Branch: dev
Git Commit: 324b752f031cdb39d52c396ea50e14a59841535e
Python Version: Python 2.7.6

**Comment by Raiven66** [comment]
`speed` argument is not being passed to `walker_factory`. It should not even be passed there since speed was determined by StepWalker itself from `self.speed = uniform(self.bot.config.walk_min, self.bot.config.walk_max)`

someone fiddling with walker without testing? :)

**Comment by Raiven66** [comment]
even `StepWalker` doesnt take 5 arguments

**Comment by Raiven66** [comment]
you can temporarily fix this by disabling the polyline worker in walker_factory.py

replace the contents of walker_factory.py with

```
from pokemongo_bot.walkers.polyline_walker import PolylineWalker
from pokemongo_bot.walkers.step_walker import StepWalker

def walker_factory(name, bot, dest_lat, dest_lng, *args, **kwargs):
    '''
    Charlie and the Walker Factory
    '''
    if 'StepWalker' == name:
        ret = StepWalker(bot, dest_lat, dest_lng)
    # elif 'PolylineWalker' == name:
    #     try:
    #         ret = PolylineWalker(bot, speed, dest_lat, dest_lng, *args, **kwargs)
    #     except:
    #         ret = StepWalker(bot, dest_lat, dest_lng)
    return ret
```

**Comment by hlavicka** [comment]
@Raiven66 it helped but then crashed again
```
Traceback (most recent call last):
  File "C:\PokemonGo-Bot\pokecli.py", line 611, in <module>
    main()
  File "C:\PokemonGo-Bot\pokecli.py", line 105, in main
    bot.tick()
  File "C:\PokemonGo-Bot\pokemongo_bot\__init__.py", line 532, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\PokemonGo-Bot\pokemongo_bot\cell_workers\move_to_map_pokemon.py", line 279, in work
    step_walker = self._move_to(pokemon)
  File "C:\PokemonGo-Bot\pokemongo_bot\cell_workers\move_to_map_pokemon.py", line 383, in _move_to
    **{'parent': MoveToMapPokemon}
  File "C:\PokemonGo-Bot\pokemongo_bot\walkers\walker_factory.py", line 9, in walker_factory
    ret = StepWalker(bot, speed, dest_lat, dest_lng)
NameError: global name 'speed' is not defined
```

**Comment by p1n9** [comment]
@Raiven66 your temp fix works for now, no more crash for me. Thanks =)
but MoveToMapPokemon task doesn't run, "move to" or "update location" are not displayed in log anymore

**Comment by Raiven66** [comment]
@hlavicka can you just copypaste the whole thing and not just choose the lines you wish? :P 
the fix works

**Comment by Raiven66** [comment]
@p1n9 make sure you have the config in good shape

**Comment by p1n9** [comment]
Fix is here #4254

**Comment by k4n30** [comment]
@p1n9 please leave open until merged

**Comment by p1n9** [comment]
@k4n30 Ok, I will close after the merge (sorry)

**Comment by mjmadsen** [comment]
Should be fixed now.
