### ISSUE TITLE
Ignore Pokemon based on candy

### ISSUE THREAD

**Issue by g2384** [PokemonGoF/PokemonGo-Bot#4256]
### Short Description

Ignore Pokemon based on the number of candies

### Possible solution

    candy = inventory.candies(True).get(pokemon.pokemon_id)
    if candy > candy_threshold:
        ignore()
    else:
        catch()

in config.json:

    "catch": {
          "any": {
                "candy_threshold": 200
          }
     },

### How it would help others

It will benefit collection-only users. Keep account exp/h low.

**Comment by lntn** [comment]
It will look more like human too.

**Comment by mjmadsen** [comment]
Merged
