### ISSUE TITLE
Add Egg_Count

### ISSUE THREAD

**Issue by g2384** [PokemonGoF/PokemonGo-Bot#4257]
### Short Description

Display number of eggs.

### Possible solution

               self.emit_event(
                    'next_egg_incubates',
                    formatted='Next egg incubates in {distance_in_km:.2f} km, Egg count: {egg_count}',
                    data={
                        'distance_in_km': km_left,
                        'egg_count': len(self.eggs)
                    }
                )

**Comment by mjmadsen** [comment]
PR #4274 plans on adding this.
