### ISSUE TITLE
XP limit per hour

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#4261]
### Short Description
related to #4019 #4188 #4191 #4194

### Expected Behavior
I'm trying to control overall XP / h rate (in addition of XP / 24h **because I'm more & more convinced that this is one of the critical factors of ban**). The only relevant seems to be walk_max but if you meet many pokemon in lure you will end with high XP even if you walk slowly

### Possible solution
a parameter **XP_per_hour** (or a shorter interval)
when this parameter is reached, no spin or catch is being done until the hour (or the time interval )is consumed

### How it would help others
prevent perm ban

**Comment by GrosCep** [comment]
I think it can't be just XP earned in an hour... Maybe XP earned with catching and spinning.
Playing completely legit with the app on your phone, you can get 180k XP in an hour if you have 180 pokemons to evolve and two lucky eggs...

**Comment by Gurzeh** [comment]
I totally agree with last comment. If someone want to overpass this limit (by evolving with lucky eggs)  it must still be possible.

Btw, it is exactly by doing this (evolving pokemon with lucky eggs, around 80k XP) that I got banned at level 40.

**Comment by GrosCep** [comment]
You did it manually ? Or with the bot ?

**Comment by Gurzeh** [comment]
with the bot.

**Comment by avexus** [comment]
That's a lot of work for 5 bots. I don't have a working account now. So, i'll relax for a bit.

**Comment by Gurzeh** [comment]
do you know hat is the limit Pokestop to visit / day?

**Comment by mjmadsen** [comment]
#3922 Duplicate
