### ISSUE TITLE
ban related documentation

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#4262]
### Short Description
related to #4261 #4188 #4191 #4194
I would like to have all parameters related to ban listed somewhere.
There is a **tremendous lot of efforts** nowadays to improve the bot but it is all cluttered in issues / pulls and it is difficult (*and I do read the different threads*) to spot them. Also, not often but sometimes, the doc is not updated.

### Possible solution
at the beginning of configuration_files, a **short** list of critical parameters, impact and recommended values.

### How it would help others
prevent ban

**Comment by Gurzeh** [comment]
As an example, I just saw the daily_catch_limit (which I did not found in code or sample config) in pull #4188

**Comment by mjmadsen** [comment]
If you didn't have daily_catch_limit wasn't in the example configs, you were in on the latest dev branch. 

#4138 Sorry documentation is lacking. Closing.

**Comment by YvesHenri** [comment]
I can't completely assure that the bans are related to the config files. I strongly believe theyre related to GPS/IP and protobuf files/device ID, mixed with the time spent per day and account creation date/level.

**Comment by Gurzeh** [comment]
@YvesHenri totally agree with you. This is what they look after, but config can help us start a reasonable ratio
