### ISSUE TITLE
Improvement Suggestion: Keep X number of evolvable pokemons  before evolve them

### ISSUE THREAD

**Issue by kustavo** [PokemonGoF/PokemonGo-Bot#4268]
Suggestion. Keep X number (defined in config file) of evolvable pokemons  before evolve them. This way uses the lucky egg more efficiently.

**Comment by alexyaoyang** [comment]
Check out config.json.optimizer.example `"evolve_count_for_lucky_egg": 90`.

**Comment by Gurzeh** [comment]
and be careful this can lead you to a ban (XP limitations / h / day)

**Comment by kustavo** [comment]
Maybe it would be better to pass the "PokemonOptimizer" parameters to "Evolve Pokemon", It would be less confusing and more intuitive. Limit the bot for xp / time or caught / time  would also be a good idea for another issue

**Comment by mjmadsen** [comment]
@kustavo Closing now that we have your enhancement request. #4281
