### ISSUE TITLE
infinite loop if Out of pokeballs

### ISSUE THREAD

**Issue by Hatsunyan** [PokemonGoF/PokemonGo-Bot#427]
[#] Something rustles nearby!
[#] A Wild Pidgey appeared! [CP 25]
[x] Out of pokeballs...
[#] A Wild Zubat appeared! [CP 167]
[x] Out of pokeballs...
[#] A Wild Pidgey appeared! [CP 25]
[x] Out of pokeballs...
[#] A Wild Zubat appeared! [CP 167]
[x] Out of pokeballs...
[#] Something rustles nearby!
[#] A Wild Pidgey appeared! [CP 25]
[x] Out of pokeballs...
[#] A Wild Zubat appeared! [CP 167]
[x] Out of pokeballs...
[#] A Wild Pidgey appeared! [CP 25]
[x] Out of pokeballs...
[#] A Wild Zubat appeared! [CP 167]
[x] Out of pokeballs...
[#] Something rustles nearby!
[#] A Wild Pidgey appeared! [CP 25]
[x] Out of pokeballs...
[#] A Wild Zubat appeared! [CP 167]
[x] Out of pokeballs...
[#] A Wild Pidgey appeared! [CP 25]
[x] Out of pokeballs...
[#] A Wild Zubat appeared! [CP 167]
[x] Out of pokeballs...

**Comment by s1x** [comment]
This should be fixed with the newest dev branch.
