### ISSUE TITLE
VPN issue

### ISSUE THREAD

**Issue by orchid666** [PokemonGoF/PokemonGo-Bot#4270]
### Expected Behavior
Should be able to connect through VPN

### Actual Behavior

- When i don't use VPN my bots work
- When i use my VPN service, I tried every location they have un the US, i get the ("Seems your IP Address is banned or something else went badly wrong...") message

Does it really mean that all their IPs are banned or is there something else?

**Comment by Sterkoel** [comment]
The public IP address of the VPN is probably banned. Did you try to use another VPN service?

**Comment by orchid666** [comment]
I found one that is working... In Iceland! 
Massive IP ban is just ridiculous...
Problem solved anyway :)

**Comment by mjmadsen** [comment]
The issue was lots of botters using the same VPN networks. They trace the IP to the VPN, find that networks address range, then ban them all. They probably had most of the data from Ingress. 

Closing, less you have further questions.
