### ISSUE TITLE
Altitude issues #4250

### ISSUE THREAD

**Issue by mjmadsen** [PokemonGoF/PokemonGo-Bot#4275]
It appears we are not reading or writing the altitude from the last known location. Getting 0.0 on startup. Looking into it. 

Edit: Merged a few bits to update last-location properly. Still not loading alt correctly at bot startup.

**Comment by halsafar** [comment]
I also notice Follow Path does not follow Altitude.

**Comment by kanemasa1987** [comment]
Are these valid?
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/walkers/step_walker.py#L23
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokecli.py#L500-L508

**Comment by mjmadsen** [comment]
@kanemasa1987 yes.

@halsafar I'll look through and see where we're not applying alt and make a PR.

**Comment by kanemasa1987** [comment]
Sounds to be this.
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/__init__.py#L1048

**Comment by kanemasa1987** [comment]
Included fixes at #3912

**Comment by mjmadsen** [comment]
Thanks @kanemasa1987

**Comment by k4n30** [comment]
@mjmadsen close?

**Comment by ckrmml** [comment]
still does not follow altitude on follow path mode

```
2016-08-20 12:07:03,243 [FollowPath] [INFO] [position_update] Walk to (50.87303, 8.03012, 0) now at (50.87333615656404, 8.030233476519202, 0), distance left: (34.9618206337 m) ..
```

**Comment by kanemasa1987** [comment]
Seems the printing is not correct.
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/follow_path.py#L139-L148

**Comment by kanemasa1987** [comment]
Added fix at #4350

**Comment by mjmadsen** [comment]
@k4n30 Leave up for now.

**Comment by mjmadsen** [comment]
Ah, closing for now. Let new alt issues be their own bug issue.
