### ISSUE TITLE
account perma bans

### ISSUE THREAD

**Issue by dwallis2012** [PokemonGoF/PokemonGo-Bot#4282]
seen quite a few perma bans from people using the bot last night, is there a way to get round this?
Luckilly I wasnt one of the people banned but have stopped the bot until the community verifys its safe to use again?

**Comment by mjmadsen** [comment]
Firstly, bots are never safe. If you use them, only do so on accounts you are willing to lose. You're cheating and breaking TOS. 

We are collecting data about bans in  #4114. Closing.

**Comment by avexus** [comment]
@dwallis2012 so, is your account safe? can you still log in?
