### ISSUE TITLE
[META] Documentation Update

### ISSUE THREAD

**Issue by mjmadsen** [PokemonGoF/PokemonGo-Bot#4283]
Please post documentation issues here.

**Comment by MZorzy** [comment]
docs configuration_files.md: Set the maximum walking speed (1 is about 1.5km/hr)
but in lot of issue it look like m/s so 1 -> 3,6km/hr and 4,16 is 15km/h , max speed for egg.

**Comment by surewhynotmon** [comment]
I don't think any docs currently mentions anything about the new required sqlib3 dependency on `dev`? If it's here to stay, it should be mentioned that you might need to rebuild Python to include that .so file...(if someone knows a way without doing it, please let me know) Is there a config flag to not use the db?

**Comment by k4n30** [comment]
#4295 needs values added to doco

**Comment by alexyaoyang** [comment]
I'll do #4295, it's my PR, my responsibility.

**Comment by k4n30** [comment]
#4596

**Comment by BreezeRo** [comment]
will update very soon @k4n30

**Comment by k4n30** [comment]
@BreezeRo no worries, we're just trying to keep track in case anything is missed. We'd rather the devs keep on dev'ing and if you do miss one or 2 we're happy to help if it means more great commits :p

**Comment by k4n30** [comment]
#4672

**Comment by mjmadsen** [comment]
@k4n30 I'm closing as I haven't updated in a long time and it's rather deep in the issue list.
