### ISSUE TITLE
encrypt.so and encrypt.dll or encrypt_64.dll aren't included with the download

### ISSUE THREAD

**Issue by garomation** [PokemonGoF/PokemonGo-Bot#4286]
Where do I find these files on the internet? any links I follow show me a page about legalities in Australia, and the files that come from it don't do anything.....

**Comment by alexyaoyang** [comment]
Try the manual installation: https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/manual_installation.md

**Comment by RedViper9** [comment]
Please direct issues with installing the bot to the slack #help page.
