### ISSUE TITLE
Create small random change of position to resume the Bot after some time off

### ISSUE THREAD

**Issue by kustavo** [PokemonGoF/PokemonGo-Bot#4292]
When you stop the Bot (by more than X hours for example) does not return the exact same position. It is strange to stay a few hours without running the bot and it resumes in the same previous position.

**Comment by NatNew0** [comment]
I agree, but image that you stay at home with the phone turned off over night. Then the position would be the same the next morning. Maybe it's just some GPS noise at the logon that should be added. It would also be strange if you "never" had the  same position on resuming ;-)

**Comment by surewhynotmon** [comment]
Think some adjustable param for GPS signal noise would be nice. There is already random_lat_long_delta() now but not a very good config for different range.

**Comment by kustavo** [comment]
@NatNew0 @surewhynotmon If Bot starts in the same position few times, I agree with you, It could be my home, for example (even so could have noise before sending the first position in the "location" field). But I say about when we use the field "location_cache" in this case will always be the previous position where Bot stopped (even after hours off). In this case, it does not seem to be my home, as this position depends on where the Bot stopped the last time.

**Comment by surewhynotmon** [comment]
@kustavo what you are suggesting sounds like adding a new spawn_points.json config file that the bot can randomly select from to spawn. (A delta to that location can be random). 

It sounds like location_cache should be part of a consolidated Spawn Task that covers where the bot spawns at the start. It can be random from a config, home at a fixed point, last location, or a particular gps location. There isn't such a spawn worker atm.

**Comment by kustavo** [comment]
Sometimes its can occurs, but always it seems unnatural

**Comment by kustavo** [comment]
I think it could start in the near the last location location, like a stronger noise, That would be enough

**Comment by k4n30** [comment]
#3912 should be able to meet your needs, this is done all the time, so standing still will still have the same effect.

Please advise if this solves your request
