### ISSUE TITLE
question about mode

### ISSUE THREAD

**Issue by mrwing1** [PokemonGoF/PokemonGo-Bot#430]
i ask bc i wanna bot in japan (pic of it here http://image.prntscr.com/image/901eae14f0004fd0a53937f8f2af945b.png)

now i wanna use pokestops too so what should i do for a mode farm all or poke

**Comment by mrwing1** [comment]
ah got it farm is the one i like but going to japan got me softbannd

**Comment by doctor-ew** [comment]
append with --mode "all"

python2 pokecli.py -a google -u tejado -p 1234 --location "New York, Washington Square"  --mode "all"
