### ISSUE TITLE
Unexpected movesets [Mud Slap, Rock Slide] - Graveler, [Tackle, Bubble Beam] - Staryu

### ISSUE THREAD

**Issue by david-griffith** [PokemonGoF/PokemonGo-Bot#4301]
(updated, now with Staryu. Niantic doing some tweaking perhaps?)

### Expected Behavior
Normal operation of bot

### Actual Behavior
[   Pokemon] [ERROR] Unexpected moveset [Mud Slap, Rock Slide] for #75 Graveler, please update info in pokemon.json and create issue/PR
[   Pokemon] [ERROR] Unexpected moveset [Tackle, Bubble Beam] for #120 Staryu, please update info in pokemon.json and create issue/PR

### Steps to Reproduce
Operate until you get a graveler or Staryu, presumably.

### Other Information
OS: 
linux
Branch: 
dev
Git Commit: 
86fc77478dfe85ee3609169040be825d4fa3512e

**Comment by leandronn** [comment]
Same here

[   Pokemon] [ERROR] Unexpected moveset [Tackle, Swift] for #120 Staryu, please update info in pokemon.json and create issue/PR


OS: Ubuntu 16.04.1
Branch: master

**Comment by du-tran** [comment]
same here 
[   Pokemon] [ERROR] Unexpected moveset [Tackle, Power Gem] for #120 Staryu, please update info in pokemon.json and create issue/PR

OS: Mac 10.11.6
Branch: master

**Comment by nelsoncomk** [comment]
[ERROR] Unexpected moveset [Poison Jab, Sludge Bomb] for #88 Grimer

OS: Mac 
Branch: Master

**Comment by niktest** [comment]
[ERROR] Unexpected moveset [Tackle, Power Gem] for #120 Staryu, please update info in pokemon.json and create issue/PR

OS: Win64, v10.0.10586
Branch: Master

**Comment by 65narrow** [comment]
[ERROR] Unexpected moveset [Feint Attack, Dazzling Gleam] for #39 Jigglypuff, please update info in pokemon.json and create issue/PR

OS:Mac 
Branch: Master

**Comment by tabletenniser** [comment]
[   Pokemon] [ERROR] Unexpected moveset [Lick, Icy Wind] for #86 Seel, please update info in pokemon.json and create issue/PR

OS: Mac
Branch: Master
Think Nintendo has an update on the pokemon moveset.

**Comment by thebringerofdeath789** [comment]
Same. [ERROR] Unexpected moveset [Poison Jab, Sludge Bomb] for #88 Grimer, please update info in pokemon.json and create issue/PR

**Comment by kernelzin** [comment]
2016-08-19 23:29:14,644 [   Pokemon] [ERROR] Unexpected moveset [Tackle, Swift] for #120 Staryu, please update info in pokemon.json and create issue/PR

OS: ARCHLINUX
Branch: Master

**Comment by ayodyadas** [comment]
i edit pokemon.json to this 

-find Diglett ( number #50)
   
and edit fast attack ( add "Mud Slap" )
 "Fast Attack(s)": [
      "Mud Slap",
      "Mud Shot",
      "Scratch"

 and error gone

**Comment by denielchiang** [comment]
#4321

**Comment by XiotSamuel** [comment]
Solve by add "tackle"  to staryu "fast attack(s)" skill set at Pokemon GoBot/data/pokemon.json.
