### ISSUE TITLE
Incubating eggs broken on dev branch

### ISSUE THREAD

**Issue by Holzberg** [PokemonGoF/PokemonGo-Bot#4304]
### Expected Behavior
I expect that eggs will incubate.

### Actual Behavior
no incubation messages appear and the bot does not start incubating new eggs.  This has been happening since yesterday.  Others have mentioned in #help

### Your config.json (remove your username, password, gmapkey and any other private info)
 {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },

Branch: dev (latest pull since the time of this post)

**Comment by mjmadsen** [comment]
I noticed that it wasn't displaying the message earlier. Have you confirmed there is no progress on the hatching?

**Comment by Ko-Lin** [comment]
Eggs are hatching but it does not incubate new eggs.  also noted that inventory counted 0 incubators

**Comment by NovaDev94** [comment]
Resolved in https://github.com/PokemonGoF/PokemonGo-Bot/pull/4336

**Comment by mjmadsen** [comment]
Merged.
