### ISSUE TITLE
Unexpected moveset [Mud Slap, Mud Bomb] for #50 Diglett

### ISSUE THREAD

**Issue by namluu** [PokemonGoF/PokemonGo-Bot#4309]

**Comment by ayodyadas** [comment]
i edit pokemon.json to this 

-find Diglett ( number #50)
   
and edit fast attack ( add "Mud Slap" )
 "Fast Attack(s)": [
      "Mud Slap",
      "Mud Shot",
      "Scratch"

 and error gone

**Comment by mjmadsen** [comment]
Merged.
