### ISSUE TITLE
Pokeminer Support for MoveToMapPokemon

### ISSUE THREAD

**Issue by fourbytes** [PokemonGoF/PokemonGo-Bot#4311]
### Short Description
Support the pokeminer API for MoveToMapPokemon

### Possible solution
Add an option in the MoveToMapPokemon section that defines which map is running, use the appropriate API.

### How it would help others
Pokeminer tends to be quite a bit faster, have a much larger range, and can save the pokemon data for analysis later.

**Comment by k4n30** [comment]
#3672
