### ISSUE TITLE
We need someone to explain how to use this 

### ISSUE THREAD

**Issue by dumbuser1** [PokemonGoF/PokemonGo-Bot#4316]
I know I am dumb but for people who does not know everything someone needs to explain how to use the bot on phython step by step. ???

**Comment by osanseviero** [comment]
The docs are pretty clear. Feel free to ask. They explain both installation and configuration.

https://github.com/PokemonGoF/PokemonGo-Bot/tree/master/docs

**Comment by xSidewinderx** [comment]
Follow the documents provided. They have everything you need to get the bot running. If you have any questions please try the slack chat room for help. https://pokemongo-bot.slack.com/messages/help/

**Comment by dumbuser1** [comment]
**## Yes but it explains eeeeeverything.. I need to know how to make this code work in my computer.. do I copy the things in the code and paste to somewhere? Im realy dumb..**

**Comment by SGColdSun** [comment]
If you can't follow the installation documentation, perhaps the windows based bot would be better suited for you. It is literally is just following each step without any additional thought.

**Comment by k4n30** [comment]
Please take discussion to slack
