### ISSUE TITLE
Pokemon.json, Seel, missing Aqua Jet and Lick

### ISSUE THREAD

**Issue by fehgab** [PokemonGoF/PokemonGo-Bot#4327]
===============ISSUE SECTION===============

### Expected Behavior
Please update the pokemon.json file.

### Actual Behavior
2016-08-20 09:28:51,630 [   Pokemon] [ERROR] Unexpected moveset [Lick, Aqua Jet] for #86 Seel, please update info in pokemon.json and create issue/PR

Branch: 
I am using this master commit.

Commit: 86fc77478dfe85ee3609169040be825d4fa3512e [86fc774]
Parents: 423e4dea72
Author: Simba Zhang <solderzzc@users.noreply.github.com>
Date: 2016. augusztus 17., szerda 22:06:50
Committer: GitHub <noreply@github.com>
Labels: HEAD, ->, master, origin/master, origin/HEAD

**Comment by mjmadsen** [comment]
Added to #4323
