### ISSUE TITLE
add pokemon quick attacks

### ISSUE THREAD

**Issue by agetnc313** [PokemonGoF/PokemonGo-Bot#4329]
Pokemon] [ERROR] Unexpected moveset [Tackle, Bubble Beam] for #120 Staryu, please update info in pokemon.json and create issue/PR

[Pokemon] [ERROR] Unexpected moveset [Mud Slap, Mud Bomb] for #50 Diglett, please update info in pokemon.json and create issue/PR

[Pokemon] [ERROR] Unexpected moveset [Pound, Dazzling Gleam] for #39 Jigglypuff, please update info in pokemon.json and create issue/PR

**Comment by mjmadsen** [comment]
Added to #4323
