### ISSUE TITLE
bot wont open for me

### ISSUE THREAD

**Issue by tatgod91** [PokemonGoF/PokemonGo-Bot#433]
### Actual Behavior
it doesnt open at all for me 

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by buusc0** [comment]
We can't help you if that's all the info you provide. What's your OS? Is there an error message? What does it say?

**Comment by tatgod91** [comment]
sorry im on windows 10. the is no error message it i run exe and it simply does nothing. Sorry for lack of info

**Comment by dominikue** [comment]
There is no exe?
You need to install the Requirements first:
- Python 2.7.x
- pip
- git
- virtualenv (Optional)
- docker (Optional)
- protobuf 3 (OS Dependent, see below)

**Comment by s1x** [comment]
@tatgod91 If you still have the problem after checking the readme and @dominikue help, please feel free to open a new issue.

**Comment by dominikue** [comment]
@s1x Wasn't a question ^^
