### ISSUE TITLE
[Pokemon] [ERROR] Unexpected moveset [Lick, Aqua Jet] for #86 Seel, please update info in pokemon.json and create issue/PR

### ISSUE THREAD

**Issue by agetnc313** [PokemonGoF/PokemonGo-Bot#4332]
[Pokemon] [ERROR] Unexpected moveset [Lick, Aqua Jet] for #86 Seel, please update info in pokemon.json and create issue/PR

**Comment by agetnc313** [comment]
[Pokemon] [ERROR] Unexpected moveset [Poison Jab, Sludge] for #88 Grimer, please update info in pokemon.json and create issue/PR

**Comment by bruno-kenji** [comment]
Unnecessary double comments and duplicate of #4323
