### ISSUE TITLE
Config Example HELP

### ISSUE THREAD

**Issue by oralunal** [PokemonGoF/PokemonGo-Bot#4339]
Hi everyone,

I tried lots of method but couldn't configure how to do it. 

This is what I want list
1) Farm pokestop
2) Keep evolvable weak pokemons, evolve when inv 90% full. If exist use lucky egg before evolve. 
3) Keep pokemons over 90IV
4) Transfer the left pokemons

Thanks in advance

**Comment by doctordo0m** [comment]
What comes close to your requirement is the optimizer config: https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/configs/config.json.optimizer.example

What is missing, is to release pokemon below a certain IV, which could become a feature-request, as it could turn out useful I guess...

**Comment by oralunal** [comment]
I tried this but I didn't add release options. I'll add it and try again. Thank you

**Comment by doctordo0m** [comment]
It releases automatically. IMO if you have the optimizer you should not have an extra release option. Unless you specify a list of higher evolved Pokemon, then it might still work as intendet. But if you release the lower evolution Pokemon below some IV, it could maybe never, or at least only very slowly reach the desired number of evolutions!

**Comment by Anakin5** [comment]
@oralunal
I am pretty sure it is suboptimal to manage your pokemon that way. If you use a lucky egg as soon as your bag is full, you probably wont have enough evolutions to fully benefit from the lucky egg.
And having enough pokemon for the lucky egg require keeping some of them on the long run, including some who have iv less than 0.9.

Also, having low quality pokemon is only a transitional state. If you transfer your lower pokemon, the average quality of your pokemon is going to increase.
I cannot see a reason to explicitly discard pokemon with an iv less than an hardcoded value (here 0.9). What is important is whether a pokemon is the best you have or not. At some point, you will close to having them all above 0.9 and then you will have to reconfigure to discard below 0.95...

**Comment by k4n30** [comment]
Slack server please
