### ISSUE TITLE
Capture pokemon and exchanded for candy without giving that prarameter.

### ISSUE THREAD

**Issue by theonlyShiro** [PokemonGoF/PokemonGo-Bot#434]
### Expected Behavior
Only walk and capture Pokemons at the giving speed.

### Actual Behavior
walk at the giving speed and capture pokemons and exchanged all captured pokemon for candy 
### Steps to Reproduce
pokecli.py -a ptc -u xxx -p xxx -l xx,xx -w 3.16

### Other Information
OS: Win 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by millejosh** [comment]
What was the CP of the transferred pokemon? default transfer is CP 100
if you want lower than that you have to define as -c XX

**Comment by Witzbold** [comment]
I can say that the bot exchanged for me pokemon with cp higher than 500  (about 600+) although my -c setting is 500.

**Comment by clavat** [comment]
Take care about the -iv parameter too.

`-iv IV, --pokemon_potential                   Set the ratio for the IV values to transfer (eg. 0.8 will transfer a pokemon with IV 0.5)`

**Comment by doctor-ew** [comment]
my -c setting is default (not passed as parameter)

[#] A Wild Meowth appeared! [CP 173] [Potential 0.53]
[x] Using Pokeball...
[x] Captured Meowth! [CP 173] [IV 0.53] - exchanging for candy
[#] Meowth has been exchanged for candy!

Doh!

**Comment by doctor-ew** [comment]
Yeah -- something up with the iv

[#] A Wild Drowzee appeared! [CP 262] [Potential 0.44]
[x] Using Pokeball...
[x] Captured Drowzee! [CP 262] [IV 0.44] - exchanging for candy
[#] Drowzee has been exchanged for candy!

**Comment by gpires** [comment]
Same here

```
[#] A Wild Butterfree appeared! [CP 510] [Potential 0.04]
[x] Using Greatball...
[x] Captured Butterfree! [CP 510] [IV 0.04] - exchanging for candy
[#] Butterfree has been exchanged for candy!
```

```
    "cp": 150,
    "initial_transfer": false,
    "pokemon_potential": 0.70,
```

**Comment by Tekill** [comment]
```python
if (510 < 150 or 0.04 < 0.70) 
    # Exchange
```

**Comment by doctor-ew** [comment]
I compensated with:  -iv 0 -c 200

[#] A Wild Machop appeared! [CP 238] [Potential 0.87]
[x] Using Pokeball...
[x] Captured Machop! [CP 238]

**Comment by gpires** [comment]
@Tekill thanks your answer  :)
I was interpreting iv value backswords

**Comment by surfaace** [comment]
please clarify if issue persist, also pull latest git version to test with

**Comment by surfaace** [comment]
no respons
