### ISSUE TITLE
[Bug] pokemon_bag is not showing all pokemons

### ISSUE THREAD

**Issue by Arcasss** [PokemonGoF/PokemonGo-Bot#4342]
Hello folks,

### Expected Behavior
Show all pokemons in bag.

### Actual Behavior
Not showing last ID pokemon. For example, I have dragonite in my inventory, but pokemon_bag does not show it

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
"pokemon_bag": {
	"// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
	"show_at_start": true,
	"// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
	"show_count": true,
	"// 'pokemon_info' parameter define which info to show for each pokemon": {},
	"// the available options are": {},
	"// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
	"pokemon_info": [
	  "cp",
	  "iv_pct",
	  "ncp"
	]
  },

### Output when issue occurred
2016-08-20 12:21:19,255 [PokemonGoBot] [INFO] # 143 Snorlax[3]: (CP 1571, IV 0.84, NCP 0.5) | (CP 2430, IV 0.69, NCP 0.78) | (CP 1342, IV 0.6, NCP 0.43)
2016-08-20 12:21:19,256 [PokemonGoBot] [INFO] # 148 Dragonair[8]: (CP 938, IV 0.58, NCP 0.54) | (CP 1242, IV 0.69, NCP 0.71) | (CP 838, IV 0.58, NCP 0.48) | (CP 23, IV 0.73, NCP 0.01) | (CP 1377, IV 0.91, NCP 0.79) | (CP 654, IV 0.56, NCP 0.37) | (CP 475, IV 0.67, NCP 0.27) | (CP 506, IV 0.47, NCP 0.29)
2016-08-20 12:21:19,256 [PokemonGoBot] [INFO]

### Steps to Reproduce
Add pokemon_bag property to config. If you see logs, there should be also # 149 Dragonite.

### Other Information
OS: Windows 10, Gitbash
Branch: dev
Git Commit: 33720d5181cda888e5e7eec49228dc81a44d68ea
Python Version: Python 2.7.12

**Comment by mjmadsen** [comment]
Logic errors around line 906 of init. We could probably fix and clean this up quite a bit.

**Comment by DeXtroTip** [comment]
Yeah, my bad when coding this, it won't show any of the last pokemon. I can fix it later when i get home and also try to make it more clean.
