### ISSUE TITLE
[ERROR] Unexpected moveset

### ISSUE THREAD

**Issue by ntanto** [PokemonGoF/PokemonGo-Bot#4349]
### Actual Behavior
[ERROR] Unexpected moveset [Pound, Dazzling, Gleam] for #39 Jigglypuff, please update info in pokemon.json and create issue/PR

### Other Information
OS: Windows 10
Branch:  master
Git Commit: 81e16731200ff50c4cfe8a0ad049eac7f5441368
Python Version: 2.7.12

**Comment by k4n30** [comment]
#4323
