### ISSUE TITLE
Another altitude issue maybe?

### ISSUE THREAD

**Issue by MeretrixLxxv** [PokemonGoF/PokemonGo-Bot#4351]
Seen previous days discussions about alt parameters missing or not being passed.  Just noted one today and have attached a screenshot.
FollowSprial is passing X, Y, 0 , no altitude.

[FollowSpiral] [INFO] [position_update] Walking from (x,y,0)
![followspiral](https://cloud.githubusercontent.com/assets/21082904/17830999/c49773c2-66ab-11e6-8a30-9c6ce9eedd04.png)

Thanks.

**Comment by kanemasa1987** [comment]
Same as #4250.
The logging is not correct.

**Comment by kanemasa1987** [comment]
Added fix for this at #4350 aswell.

**Comment by mjmadsen** [comment]
Merged #4350
