### ISSUE TITLE
Unexpected moveset [Tackle, Power Gem] for #120 Staryu

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#4354]
### Actual Behavior
Unexpected moveset [Tackle, Power Gem] for #120 Staryu, please update info in pokemon.json and create issue/PR

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/XzFy46Tv

### Output when issue occurred
http://pastebin.com/Zwb4Bi9X

### Other Information
OS:  MAC OSX Capitan
Branch: dev
Git Commit: 9064af3e7d1005087a07544a24199ac2f8b12f4e
Python Version: Python 2.7.12

**Comment by maxprzemo** [comment]
Delete
    "username": "",
    "password": "",
    "location": "",
    "gmapkey": "",
and any other private info

**Comment by Gurzeh** [comment]
sorry. Done

**Comment by doctordo0m** [comment]
Duplicates #4323

**Comment by Gurzeh** [comment]
@k4n30 btw when this is merged, is it "safe" to upgrade to last dev commit? My version is pretty flawless now... :)

**Comment by mjmadsen** [comment]
#4323 Use dev branch.
