### ISSUE TITLE
Can't setup transfer pokemons! Need help

### ISSUE THREAD

**Issue by Hellycat** [PokemonGoF/PokemonGo-Bot#4355]
The problem that i can't transfer pokemons. They are get full and i got message: no space for pokemons. 
What i have in config:

"type": "TransferPokemon",
"config": {
"transfer_wait_min": 1,
"transfer_wait_max": 4
}

Any ideas?
Thank's!

**Comment by doctordo0m** [comment]
Do you have a release config?

`"release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
},`

see https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/configs/config.json.example

**Comment by Hellycat** [comment]
Yes, I have the following:


"tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 5,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "transfer_wait_min": 1,
          "transfer_wait_max": 4
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "evolve_all": "none",
          "first_evolve_by": "cp",
          "evolve_above_cp": 500,
          "evolve_above_iv": 0.8,
          "logic": "or",
          "evolve_speed": 20,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          },
          "recycle_wait_min": 1,
          "recycle_wait_max": 4
        }
      },
      {
        "type": "CatchPokemon",
        "config": {
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 5,
          "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.5,
            "nice_rate": 0.3,
            "normal_rate": 0.1,
            "spin_success_rate" : 0.6
          },
          "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 2,
            "catch_wait_max": 6,
            "berry_wait_min": 2,
            "berry_wait_max": 3,
            "changeball_wait_min": 2,
            "changeball_wait_max": 3
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "spin_wait_min": 2,
          "spin_wait_max": 3
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "lure_attraction": true,
          "lure_max_distance": 2000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "walk_max": 4.5,
    "walk_min": 2.16,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging_color": true,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV)
Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
    },

No working for me

**Comment by doctordo0m** [comment]
Well, the default does not release. Read the comments...

For example if you want to keep the best 1 Pokemon based on IV of any type, use `"any": {"keep_best_iv": 1},`

If you want to keep the best, based on CP, and the best based on IV, use `"any": {"keep_best_iv": 1, "keep_best_cp": 1},`

**Comment by Ogalababa** [comment]
you can copy this example:

    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0.7, "logic": "or"},
       "Rattata": {
            "keep_best_cp": 2
        },
        "Raticate": {
            "keep_best_iv": 2
        },
        "Pidgey": {
            "keep_best_cp": 1
        },
        "Pidgeotto": {
            "keep_best_iv": 1
        },
        "Pidgeot": {
            "keep_best_iv": 3
        },
        "Weedle": {
            "keep_best_cp": 1
        },
        "Kakuna": {
            "keep_best_iv": 1
        },
        "Beedrill": {
            "keep_best_iv": 1
        },
        "Spearow": {
            "keep_best_cp": 1
        },
        "Fearow": {
            "keep_best_iv": 1
        },
        "Zubat": {
            "keep_best_cp": 1
        },
        "Golbat": {
           
            "keep_best_iv": 1
        },
        "Staryu": {
            "keep_best_cp": 2
        },
        "Seaking": {
           
            "keep_best_iv": 2
        },
        "Goldeen": {
            "keep_best_iv": 1
        },
        "Horsea": {
            "keep_best_iv": 2
        },
        "Krabby": {
            "keep_best_iv": 1
        },
        "Hypno": {
            "keep_best_iv": 2
        },
        "Drowzee": {
            "keep_best_cp": 1
        },
        "Venonat": {
            "keep_best_iv": 1
        },
        "Venomoth": {
            "keep_best_iv": 1
        },
        "Paras": {
            "keep_best_iv": 1
        },
        "Caterpie": {
            "keep_best_iv": 1
        },
        "Metapod": {
            "keep_best_iv": 1
        },
        "Butterfree": {
            "keep_best_iv": 2
        },
        "Slowpoke": {
            "keep_best_iv": 1
        },
        "Slowbro": {
            "keep_best_iv": 3
        },
        "Shellder": {
            "keep_best_iv": 1
        },
        "Gastly": {
            "keep_best_iv": 1
        },
        "Eevee": {
            "keep_best_iv": 1
        },
        "Starmie": {
            
            "keep_best_iv": 2
        },
        "Magikarp": {
            "keep_best_iv": 1
        },
        "Dratini": {
           
            "keep_best_iv": 2
        },
        "Psyduck":		{ "keep_best_iv": 1	},
        "Golduck":		{"keep_best_iv": 2	},
        "Poliwag":		{ "keep_best_iv": 2	},
        "Poliwhirl":	{ "keep_best_iv": 2	},
        "Magnemite":	{ "keep_best_cp": 1 },
        "Magneton":		{ "keep_best_iv": 1 },
		"Voltorb":		{ "keep_best_cp": 1 },
		"Electrode":	{ "keep_best_iv": 1 },
      	"Meowth":		{ "keep_best_cp": 1 },

**Comment by Hellycat** [comment]
Thank's for helping.
Problem solved

суббота, 20 августа 2016 г. пользователь Ogalababa написал:
