### ISSUE TITLE
Answering "move too fast" dialog

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#4356]
### Short Description
Quite interesting: After botting a while in some area 5km away, and waiting some reasonable (so I thought) time, I opened the leg application at home. Then I got the message "you're moving too fast" and I had to acknowledge I was the passenger.

related to #4004 especially: API (not this project directly)
Complete "non-essential" API request/response analysis (any remaining unknowns)

### Possible solution
How is it possible to handle that, especially with teleportation which will always trigger that dialog.
I saw some discussion about it somewhere, but could not find it anymore?
The query (and what it is waiting) is in the packets exchanged. Does PokemonGo-Map has something about this?

### How it would help others
anti ban

**Comment by net8q** [comment]
After checking MITM dump while triggering the warning in the app, there is no evidence of API call triggered by acknowledging the warning nor specific reference to the warning in the traffic dump , so it is client side only, except if you have specific info about this.

**Comment by Calcyfer** [comment]
There are no API calls indeed. The warning you got on the app was because of an inaccurate GPS fix, causing you to move fast.

**Comment by mjmadsen** [comment]
I'm going to agree with @net8q and @Calcyfer
