### ISSUE TITLE
In web: Candy: undefined. Issue.

### ISSUE THREAD

**Issue by Wilbertvn** [PokemonGoF/PokemonGo-Bot#4357]
### Actual Behavior

In the web, when you click "Pokemon" I get to see Candy: undefined. While it normally it was working

### Expected Behavior

Well, this normally worked.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/7bYEBhBh 

### Output when issue occurred

Candy: undefined

### Steps to Reproduce

I updated the Pokemon go-bot for new features and perhaps bug fixes. Simple as that.

### Other Information
OS: Windows 10

**Comment by Calcyfer** [comment]
Are you on master or dev?

**Comment by Wilbertvn** [comment]
Master

**Comment by Calcyfer** [comment]
Try using the web folder from the dev branch instead, that one works.
