### ISSUE TITLE
Is location ignored if followPathmode used ?

### ISSUE THREAD

**Issue by nicobr75000** [PokemonGoF/PokemonGo-Bot#4361]
### Short Description

When using the followPathTask the location in the config file should be ignored to avoid a location jump.
I am not sure if it is currently the case.

**Comment by Calcyfer** [comment]
The location in config or the location in cache is being used.
However, you will not make a jump.
There are 2 options, depending on your config : 

- If path_start_mode is set to 'closest', the bot walks to the point in your path closest to the bot's location

- If path_start_mode is set to 'first', it walks to the first point.

**Comment by Calcyfer** [comment]
When I use a path, I use the first point in the path file as my location and make sure to delete the location cache in ./data

**Comment by mjmadsen** [comment]
@nicobr75000 Does that answer your question?

**Comment by nicobr75000** [comment]
It does !

Thanks
