### ISSUE TITLE
Unexpected movesets for some Pokemon

### ISSUE THREAD

**Issue by dapperDerek** [PokemonGoF/PokemonGo-Bot#4362]
Ran into unexpected movesets:
**Staryu** - Fast attack: Tackle
**Starmie** - Special attack: Psychic

Adding modified JSON:
  {
    "Number": "120",
    "Name": "Staryu",
    "Classification": "Starshape Pokemon",
    "Type I": [
      "Water"
    ],
    "Weaknesses": [
      "Electric",
      "Grass"
    ],
    "Fast Attack(s)": [
      "Quick Attack",
      "Water Gun",
      "Tackle"
    ],
    "Weight": "34.5 kg",
    "Height": "0.8 m",
    "Next Evolution Requirements": {
      "Amount": 50,
      "Family": 120,
      "Name": "Staryu candies"
    },
    "Next evolution(s)": [
      {
        "Number": "121",
        "Name": "Starmie"
      }
    ],
    "Special Attack(s)": [
      "Bubble Beam",
      "Power Gem",
      "Swift"
    ],
    "BaseAttack": 130,
    "BaseDefense": 128,
    "BaseStamina": 60,
    "CaptureRate": 0.4,
    "FleeRate": 0.15
  },
  {
    "Number": "121",
    "Name": "Starmie",
    "Classification": "Mysterious Pokemon",
    "Type I": [
      "Water"
    ],
    "Type II": [
      "Psychic"
    ],
    "Weaknesses": [
      "Electric",
      "Grass",
      "Bug",
      "Ghost",
      "Dark"
    ],
    "Fast Attack(s)": [
      "Quick Attack",
      "Water Gun"
    ],
    "Weight": "80.0 kg",
    "Height": "1.1 m",
    "Previous evolution(s)": [
      {
        "Number": "120",
        "Name": "Staryu"
      }
    ],
    "Special Attack(s)": [
      "Hydro Pump",
      "Power Gem",
      "Psybeam",
      "Psychic"
    ],
    "BaseAttack": 194,
    "BaseDefense": 192,
    "BaseStamina": 120,
    "CaptureRate": 0.16,
    "FleeRate": 0.06
  },

**Comment by mjmadsen** [comment]
#4323 Use dev branch.
