### ISSUE TITLE
Randomize multiple throw attempts

### ISSUE THREAD

**Issue by gi1gam3sh** [PokemonGoF/PokemonGo-Bot#4366]
### Short Description

When attempting to capture a pokemon and failing to do so on the first try. The bot seems to use the same exact chance on the follow up attempts. Assuming this capture rate is defined by how "well" you throw the ball when you are actually playing the game. I think it would be more human like if each subsequent attempt had a different/random probability of capture.  

[PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Clefairy appeared!
[PokemonCatchWorker] [INFO] [threw_berry] Threw a Razz Berry! Catch rate with Greatball is now: 49.03
[PokemonCatchWorker] [INFO] [threw_pokeball] Used Greatball, with chance 49.03 (0 left)
[pokemon_capture_failed] Clefairy capture failed.. trying again!
[PokemonCatchWorker] [INFO] [threw_berry] Threw a Razz Berry! Catch rate with Pokeball is now: 52.18
[PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 52.18 (7 left)
[PokemonCatchWorker] [INFO] [pokemon_capture_failed] Clefairy capture failed.. trying again!
[PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 52.18 (6 left)
[PokemonCatchWorker] [INFO] [pokemon_capture_failed] Clefairy capture failed.. trying again!
[PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 52.18 (5 left)
[PokemonCatchWorker] [INFO] [pokemon_capture_failed] Clefairy capture failed.. trying again!
[PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 52.18 (4 left) [PokemonCatchWorker] [INFO] [pokemon_capture_failed] Clefairy capture failed.. trying again!
[PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 52.18 (3 left)
[PokemonCatchWorker] [INFO] [pokemon_capture_failed] Clefairy capture failed.. trying again!
[PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeball, with chance 52.18 (2 left)
[PokemonCatchWorker] [INFO] [pokemon_vanished] Clefairy vanished!

### Possible solution

whatever randomize function is being used to perform the initial throw could be called for each subsequent throw?

### How it would help others

Lessen the chance of bot being detected.

**Comment by mjmadsen** [comment]
Capture chance listed is literally the chance of capturing with that ball (with a hit), i.e. the chance it will escape the ball.
