### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by takenek** [PokemonGoF/PokemonGo-Bot#4371]
1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.
YES

2. Have you [searched our issue tracker](https://github.com/PokemonGoF/PokemonGo-Bot/issues?q=is%3Aissue+sort%3Aupdated-desc) to see if the issue already exists? If so, comment on that issue instead rather than creating a new issue.
I don`t see anyone with this problem.

3. Are you running on the `master` branch? We work on the `dev` branch and then add that functionality to `master` when it is stable. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.
I use master but in dev same don`t see in dev any info about this bug.

### Expected Behavior
Run bot with no problem.

### Actual Behavior
Bot crash after few days working without any problem, when i try run again i got all the time error i  check and account working properly( this is not a ban) looks like bug:

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://www.wklej.org/hash/ec13d070259/

### Output when issue occurred
http://www.wklej.org/hash/3d3cb1f27aa/

### Steps to Reproduce
Run a bot...

### Other Information
OS: 
Debian SiD

Branch: 
81e16731200ff50c4cfe8a0ad049eac7f5441368

Python Version: 
Python 2.7.9

**Comment by mjmadsen** [comment]
Give the current dev branch a shot and let me know if you're still having a problem.

**Comment by takenek** [comment]
I am not sure what You mean - You want me to do:
git clone -b dev https://github.com/PokemonGoF/PokemonGo-Bot.git ?

Best Regards

**Comment by mjmadsen** [comment]
git checkout dev
git pull
git install -r requirements.txt

**Comment by takenek** [comment]
Same effect.
(PokemonGo-Bot) taken@PGO2:~/PokemonGo-Bot$ git checkout dev
M       pokemongo_bot/constants.py
Already on 'dev'
Your branch is up-to-date with 'origin/dev'.
(PokemonGo-Bot) taken@PGO2:~/PokemonGo-Bot$ git pull
Already up-to-date.
pip install -r requirements.txt
[CUT]
./run
same error.

**Comment by mjmadsen** [comment]
Thanks for trying. Added some flags to help get more devs attention.

**Comment by takenek** [comment]
I think i find what`s is wrong...
Old version of PokemonGo-BOT uses PGOAPI from:
https://github.com/keyphact/pgoapi.git
now it`s change to:
https://github.com/joelgreen/pgoapi.git
after completly delete PokemonGo-Bot/src/pgoapi/ and install again working properly.

But better devlopers looks at this mayby i am wrong but looks like that was a problem...
Best Regards
TaKeN
