### ISSUE TITLE
[Feature] Moving to fort but spin

### ISSUE THREAD

**Issue by tuanchauict** [PokemonGoF/PokemonGo-Bot#4372]
Hello, 

I would like to have a feature that I can let my character move along the Pokestops but spin to avoid level up while I want to hunt specified pokemons. 

I have try to disable task `FortSpin` but the character moving around a fort instead of skip the current and move to a new one.

Thanks.

**Comment by cbogithub** [comment]
try  set "max_circle_size": 50, => 60,70,80....

```
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
```

**Comment by mjmadsen** [comment]
Could remove the SpinFort task.

**Comment by tuanchauict** [comment]
When I remove SpinFort, it moves around the Fort. Not work at all. I also tried set `max_circle_size`, and it moved farther, level up from 2 to 7 after night.
