### ISSUE TITLE
[   Pokemon] [ERROR] Unexpected moveset [Sucker Punch, Sludge Bomb] for #94 Gengar, please update info in pokemon.json and create issue/PR

### ISSUE THREAD

**Issue by vwsc2015** [PokemonGoF/PokemonGo-Bot#4377]
There is a description problem for #94 Gengar, and after evolve an #94 Gengar, the bot has the problem as the title, after this, I release this, and the problem disappeared.

**Comment by vamirineni87** [comment]
Similar. 

2016-08-20 11:42:27,467 [   Pokemon] [ERROR] Unexpected moveset [Mud Slap, Dig] for #50 Diglett, please update info in pokemon.json and create issue/PR

**Comment by oongkung** [comment]
[   Pokemon] [ERROR] Unexpected moveset [Tackle, Hydro Pump] for #121 Starmie, please update info in pokemon.json and create issue/PR

**Comment by doctordo0m** [comment]
see #4323

**Comment by mjmadsen** [comment]
@vwsc2015 @vamirineni87 @oongkung 

Try the following:
git checkout dev
git pull
git install -r requirements.txt

**Comment by Fr3nchi3** [comment]
Similar and i updated before posting this.

[ERROR] Unexpected moveset [Tackle, Power Gem] for #120 Staryu, please update info in pokemon.json and create issue/PR

**Comment by Nik0lashka** [comment]
@vwsc2015 @vamirineni87 @oongkung @Fr3nchi3 as @doctordo0m said - post issues in #4323, stop duplicating please
