### ISSUE TITLE
Last dev release does not see any Pokemon!

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#4378]
### Expected Behavior
catching Pokemon

### Actual Behavior
none appears, when I do see them on the map

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/XzFy46Tv

### Output when issue occurred
http://pastebin.com/Zwb4Bi9X
another output
http://pastebin.com/d47ZqyjF

### Other Information
OS: OSX Capitan
Branch: dev
Git Commit: 0cbb9b030acb3739ccb272ad20d601efca181ec2
Python Version: Python 2.7.12

**Comment by mjmadsen** [comment]
Interesting. I wonder if this is some form of softban.

**Comment by Gurzeh** [comment]
Hum, I'll try with another account

**Comment by mjmadsen** [comment]
@Gurzeh Did yours see/catch any?

I saw and captured some, but they seemed to appear much less often. Possibly due to the visible lured catch merge.

**Comment by Gurzeh** [comment]
I did a clean reinstall. I don't see any, but I'm moving very slow (walk_max = 2)

**Comment by Gurzeh** [comment]
I have a map on the same location. Unfortunate I don't have the name of the Pokestop on PokemonGo-Map so I don't see where he is.

**Comment by osanseviero** [comment]
Same situation. No pokemon is appearing since yesterday. I had the sample configuration, it was working ok. Next day, with different accounts and same config, even slower configs, it goes and spins the forts, but isn't finding pokemons.

**Comment by Gurzeh** [comment]
@osanseviero @mjmadsen I reverted to
git checkout e63074be072b6956ba0c37156bcd83792469bb16
and started catching again Pokemon

**Comment by 0z4ck** [comment]
It was talked and talked. see #3989

**Comment by 0z4ck** [comment]
it is said it's a symptom of perma BAN

**Comment by Gurzeh** [comment]
No: the app works fine with these account. Please read the comment: why would it work by reverting to a previous commit?

**Comment by 0z4ck** [comment]
ok, you may have other problems, but @osanseviero and @mjmadsen must be in this symptom #3989

**Comment by Gurzeh** [comment]
@mjmadsen Hi Matt, did you have some time to check the code ? My older version is fine, but has some glitch (inventory related). It is ok, I can live with it, but I will be happy to join latest commit.

**Comment by mjmadsen** [comment]
@Gurzeh I haven't seen anything that would cause a reduction in pokemon seen. With latest commit I had two accounts catch far fewer than average, while accounts running concurrently on the same IP caught an average amount.

**Comment by Gurzeh** [comment]
@mjmadsen I finally found it: using config.json.example makes the bot running as usual. So the reason is my config.json. I will try to narrow down the culprit in json file. I close and will create an issue when found. Thanks for your help, much appreciated!
