### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by DokterPhill** [PokemonGoF/PokemonGo-Bot#438]
### Expected Behavior

Program running
### Actual Behavior

 print '[#] something rustles nearby!' 
SyntaxError: Missing parentheses in call to 'print'
### Steps to Reproduce
Pokecli.py -a google -u user -p pass - location location

### Other Information
OS: win10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by douglascamata** [comment]
you're using python 3 and we work with python 2

**Comment by Sharpienero** [comment]
Please close the issue if this resolves your issue.

**Comment by s1x** [comment]
@DokterPhill Follow the Readme. Feel free to open a new issue when necessary.
