### ISSUE TITLE
Device info for android?

### ISSUE THREAD

**Issue by nowak-mateusz** [PokemonGoF/PokemonGo-Bot#4388]
How change default setting for iphone to android in api_wrapper.py?
I can use deviceinfo app to get my Android Device ID.
It is nice to add it to config to set device info.

**Comment by k4n30** [comment]
You don't want to yet as we aren't sending all the right variables to the api for an android device, therefore you'll most likely get picked up for botting. There's no harm in having 2 devices - iphone (bot), android (real)
