### ISSUE TITLE
Blocking the bot (Circulates over and over again)

### ISSUE THREAD

**Issue by maxprzemo** [PokemonGoF/PokemonGo-Bot#4394]
### Actual Behavior

Bot hangs always in the same places.
http://i65.tinypic.com/2mlaf5.jpg

`
2016-08-20 19:45:22,127 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:45:22,139 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.04km
2016-08-20 19:45:23,755 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:45:23,762 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-20 19:45:26,846 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:45:26,854 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.04km
2016-08-20 19:45:28,841 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:45:28,849 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.04km
2016-08-20 19:45:31,674 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:45:31,682 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.04km
2016-08-20 19:45:35,019 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:45:35,026 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-20 19:45:36,479 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:45:36,486 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.04km
2016-08-20 19:45:38,520 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:45:38,529 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.04km
2016-08-20 19:45:41,668 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:45:41,675 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-20 19:45:43,420 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:45:43,429 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.04km
2016-08-20 19:45:45,467 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:45:45,475 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.04km
2016-08-20 19:45:48,966 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:45:48,974 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-20 19:45:50,602 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:45:50,611 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.04km
2016-08-20 19:45:54,251 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:45:54,258 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.04km
2016-08-20 19:45:55,679 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:45:55,687 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-20 19:45:57,491 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:45:57,498 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.04km
2016-08-20 19:46:01,102 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:46:01,110 [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-20 19:46:02,949 [  SpinFort] [INFO] [pokestop_searching_too_often] Possibly searching too often, take a rest.
2016-08-20 19:46:02,958 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop X - 0.04km
`
### Your FULL config.json 
`
{
    "auth_service": "ptc",
    "username": "xxxxxxxxxxxx",
    "password": "xxxxxxxxxxxx",
    "location": "xxxxxxxxxxxx",
    "gmapkey": "xxxxxxxxxxxx",
    "encrypt_location": "",
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
	  {
		"type": "RandomPause",
        "config": {
		  "enabled": true,
		  "min_duration": "00:00:10",
		  "max_duration": "00:02:00",
		  "min_interval": "00:05:00",
		  "max_interval": "00:30:00"
        }
	  },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": false,
          "// set a name": "",
          "nickname": ""
        }
      },
      {
         "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": false,
          "min_interval": 30,
          "show_all_multiple_lines": false,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "min_free_slot": 5,
          "transfer_wait_min": 1,
          "transfer_wait_max": 4
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "evolve_all": "none",
          "first_evolve_by": "cp",
          "evolve_above_cp": 10,
          "evolve_above_iv": 0.8,
          "logic": "or",
          "evolve_speed": 20,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 30,
          "max_balls_keep": 150,
          "max_potions_keep": 70,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 80 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 60 }
          },
          "recycle_wait_min": 1,
          "recycle_wait_max": 4
        }
      },
      {
        "type": "CatchPokemon",
        "config": {
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 5,
          "berry_threshold": 0.35,
          "vip_berry_threshold": 0.9,
          "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.1,
            "nice_rate": 0.2,
            "normal_rate": 0.6,
            "spin_success_rate" : 0.2,
            "hit_rate": 0.78
          },
          "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 2,
            "catch_wait_max": 6,
            "berry_wait_min": 2,
            "berry_wait_max": 3,
            "changeball_wait_min": 2,
            "changeball_wait_max": 3
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "spin_wait_min": 6,
          "spin_wait_max": 9
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "lure_attraction": true,
          "lure_max_distance": 500,
          "walker": "PolylineWalker"
        }
      },
      {
        "type": "FollowCluster",
        "config": {
            "radius": 50,
            "lured": true
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 35,
      "cache_recent_forts": false
    },
    "pokemon_bag": {
      "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
      "show_at_start": true,
      "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
      "show_count": false,
      "// 'pokemon_info' parameter define which info to show for each pokemon": {},
      "// the available options are": {},
      "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
      "pokemon_info": ["cp", "iv_pct"]
    },
    "walk_max": 3.88,
    "walk_min": 2.16,
    "alt_min": 500,
    "alt_max": 1000,
    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": false,
    "replicate_gps_z_noise": false,
    "gps_xy_noise_range": 0.000125,
    "gps_z_noise_range": 12.5,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging_color": true,
    "daily_catch_limit": 500,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "Bellsprout": {"keep_best_cp": 3},
      "Caterpie": {"keep_best_cp": 1},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "Drowzee": {"keep_best_cp": 3, "keep_best_iv": 3},
      "Eevee": {"keep_best_cp": 3, "keep_best_iv": 3},
      "Hypno": {"keep_best_cp": 3, "keep_best_iv": 3},
      "Gastly": {"keep_best_cp": 3},
      "Nidoran M": {"keep_best_cp": 3},
      "Nidoran F": {"keep_best_cp": 3},
      "Horsea": {"keep_best_cp": 3},
      "Jynx": {"keep_best_cp": 3},
      "Magikarp": {"keep_best_cp": 3},
      "Magnemite": {"keep_best_cp": 3},
      "Meowth": {"keep_best_cp": 3},
      "Paras": {"keep_best_cp": 3},
      "Pidgeotto": {"keep_best_cp": 3},
      "//Pidgey": {"keep_best_cp": 3},
      "Pidgeot": {"keep_best_cp": 3},
      "Psyduck": {"keep_best_cp": 3},
      "Raticate": {"keep_best_cp": 3},
      "Krabby": {"keep_best_cp": 3},
      "Oddish": {"keep_best_cp": 3},
      "//Rattata": {"keep_best_cp": 2},
      "Spearow": {"keep_best_cp": 1},
      "Seel": {"keep_best_cp": 3},
      "Shellder": {"keep_best_cp": 3},
      "Squirtle": {"keep_best_cp": 3},
      "Tentacool": {"keep_best_cp": 3},
      "Venonat": {"keep_best_cp": 3},
      "Weedle": {"keep_best_cp": 1},
      "//Zubat": {"keep_best_cp": 3},
      "Fearow": {"keep_best_cp": 3},
      "// Example of keeping 2 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3},
	  "// Example of custom order of static criterion": {},
	  "// Zubat": {"keep_best_custom": "iv, cp, hp_max", "amount":2}
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 500, "catch_above_iv": 0.8, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}

`

### config.json it does not matter because it happens at different settings

`
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
`

`
      {
        "type": "MoveToFort",
        "config": {
          "lure_attraction": true,
          "lure_max_distance": 2000,
          "walker": "StepWalker"
        }
      },
`

Also it happens.

### Other Information
OS: Debian 8.5
 
Branch: Dev

**Comment by josegrobles** [comment]
Same error

    "websocket_server": false,
    "heartbeat_threshold": 10,
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },
    {
    "type": "RandomPause",
        "config": {
      "enabled": true,
      "min_duration": "00:00:10",
      "max_duration": "00:10:00",
      "min_interval": "00:30:00",
      "max_interval": "02:00:00"
        }
    },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": false,
          "// set a name": "",
          "nickname": ""
        }
      },
      {
         "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": true,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": false,
          "min_interval": 120,
          "show_all_multiple_lines": false,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
        }
      },
   {
        "type": "TransferPokemon",
        "config": {
          "min_free_slot": 5,
          "transfer_wait_min": 1,
          "transfer_wait_max": 4
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "evolve_all": "Pidgey,Zubat,Caterpie,Psyduck,Slowpoke,Ekans,Spearow",
          "first_evolve_by": "cp",
          "evolve_above_cp": 0,
          "evolve_above_iv": 0,
          "logic": "or",
          "evolve_speed": 20,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          },
          "recycle_wait_min": 1,
          "recycle_wait_max": 4
        }
      },
      {
        "type": "CatchPokemon",
        "config": {
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 5,
          "catch_throw_parameters": {
            "excellent_rate": 0.3,
            "great_rate": 0.5,
            "nice_rate": 0.1,
            "normal_rate": 0.1,
            "spin_success_rate" : 0.6,
            "hit_rate": 0.75
          },
          "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 2,
            "catch_wait_max": 6,
            "berry_wait_min": 2,
            "berry_wait_max": 3,
            "changeball_wait_min": 2,
            "changeball_wait_max": 3
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "spin_wait_min": 2,
          "spin_wait_max": 3
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "lure_attraction": true,
          "lure_max_distance": 2000
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 80,
      "cache_recent_forts": true
    },
    "pokemon_bag": {
      "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
      "show_at_start": false,
      "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
      "show_count": true,
      "// 'pokemon_info' parameter define which info to show for each pokemon": {},
      "// the available options are": {},
      "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
      "pokemon_info": ["cp", "iv_pct"]
    },
    "walk_max": 10,
    "walk_min": 5,
    "alt_min": 3,
    "alt_max": 8,
    "gps_default_altitude": 3.0,
    "replicate_gps_xy_noise": true,
    "replicate_gps_z_noise": true,
    "gps_xy_noise_range": 0.000105,
    "gps_z_noise_range": 9.5,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging_color": true,
    "daily_catch_limit": 800,

**Comment by kanemasa1987** [comment]
The first one is I believe Polyline issue and I will send PR soon.
Suppose there are 2 forts, A and B. Moving toward fort A using Polyline may result in getting closer to fort B, vice versa. The bot ends up captured by the position because MoveToFort tries to move to closest fort from current position.

I am not sure with the second one...

**Comment by mjmadsen** [comment]
Please reopen if @kanemasa1987 s merge didn't solve the issue.
