### ISSUE TITLE
[Suggestion] Add more events to console

### ISSUE THREAD

**Issue by crusardri** [PokemonGoF/PokemonGo-Bot#44]
Please, add events to show in console like...
A Wild %POKEMON% appeared! Trying to capture... [CP %CP%]
Capturing...
Captured %POKEMON%, Pokeballs used %POKEBALLS%.
Captured %POKEMON%, Pokeballs used %POKEBALLS%, CP is too low, exchanging.
Yoy received %AMOUNT% %POKECANDY% of %POKEMON% and %STARTDUST% star dust.
%POKEMON% run away!
Searching pokemons nearby...
Found a pokestop. Trying to get the items.
You get:
%AMOUNT% %ITEM%
%AMOUNT% %ITEM%
%AMOUNT% %ITEM%
Your bag have %ITEMSINBAG%/%MAXBAGCAPACITY%.
Your bag is full!!!
The pokestop is disabled, skipping.
You level up!! Level %LEVEL%, exp to level up again %RESTEXP%.
You are running out of pokeballs!

Sorry for my bad english

**Comment by 3mph4515** [comment]
Maybe also add periodical profile fetch and display current DUST, etc.

**Comment by s1x** [comment]
Most events are now implemented. Feel free to open a new issue with new suggestions!
