### ISSUE TITLE
No Pokemon getting released

### ISSUE THREAD

**Issue by fourbytes** [PokemonGoF/PokemonGo-Bot#4405]
### Expected Behavior
Should transfer pokemon according to release rules (keep 1 best cp, and 1 best iv)

### Actual Behavior
Doesn't transfer any pokemon

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/4rvQRVJx

### Output when issue occurred
http://pastebin.com/KBAQSq8C

### Steps to Reproduce
Started the bot and let it run for a while, nothing released even when there are many pokemon that would normally be released.

### Other Information
OS: 
macOS Sierra
Branch: 
dev
Git Commit: 
ff331ea0cfae988a0937b8b091f2fbf51271c240
Python Version: 
2.7.11
Any other relevant files/configs (eg: path files)

**Comment by doctordo0m** [comment]
just a reminder that `"always_release": true` is most likely not what you want. Try removing it, the config looks ok otherwise.
You could try to pull and update your requirements if nothing else helps

**Comment by Baconnaise** [comment]
Same. No extras just set "any": {"release_below_cp": 100, "release_below_iv": 0.8, "logic": "or"}. It stopped working today. I assume it's due to this https://github.com/PokemonGoF/PokemonGo-Bot/commit/0f0c87ef306a904ec20b09de4598c925b6d5ff05

**Comment by dumbuser1** [comment]
"release": {
      "any": {"release_below_cp": 800, "release_below_iv": 0.75, "keep_best_cp": 1, "keep_best_iv": 1,  "logic": "and"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 1 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 1},
      "// Example of keeping 1 stronger (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 1},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 1},
      "// Example of keeping the 1 strongest (based on CP) and 1 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 1, "keep_best_iv": 1}
    },
I dont know anything about programming or something but I tried putting them together like this, it worked fine u can try..

**Comment by Baconnaise** [comment]
Just change what I circled to a value like 350 instead 5. It's in your config.json under transfer pokemon.
![capture](https://cloud.githubusercontent.com/assets/20616256/17834091/a92bfe7e-66ff-11e6-8d9e-f4ae316aad3d.JPG)

**Comment by fourbytes** [comment]
@Baconnaise commented earlier, but adding "min_free_slot": 69 fixed the issue.
