### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by macio525** [PokemonGoF/PokemonGo-Bot#4412]
Make websocket implementation for https://github.com/OpenPoGo/OpenPoGoWeb or https://github.com/OpenPoGo/OpenPoGoUI

**Comment by Arcasss** [comment]
it already exists

**Comment by macio525** [comment]
https://github.com/OpenPoGo/OpenPoGoWeb/issues/164

**Comment by macio525** [comment]
OpenPoGoWeb actions working only for OpenPoGoBot

**Comment by mjmadsen** [comment]
Please only one thread per issue.
