### ISSUE TITLE
[   Pokemon] [ERROR] Unexpected moveset [Poison Jab, Sludge Bomb] for #88 Grimer, please update info in pokemon.json and create issue/PR

### ISSUE THREAD

**Issue by swmerko** [PokemonGoF/PokemonGo-Bot#4414]
that's all :)

**Comment by vwsc2015** [comment]
release 88 Grimer
Problem will be solved, but i don't know the solution without releasing pokemon

**Comment by vamirineni87** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/4323
