### ISSUE TITLE
Server busy ?

### ISSUE THREAD

**Issue by Lordedi** [PokemonGoF/PokemonGo-Bot#442]
[x] PokemonGO Bot v1.0
[x] Configuration initialized

[x] Address found: 48.863381, 2.289107000000058
[x] Position in-game set as: (48.8636968, 2.2888097, 0.0)

Login Error, server busy

**Comment by millejosh** [comment]
It is just as it describes, the server cannot handle your request. Please try again

**Comment by tstumm** [comment]
Not a PokemonGo-Bot issue.

**Comment by Lordedi** [comment]
Ok thanks guys

**Comment by tstumm** [comment]
Maybe #417 does the trick
