### ISSUE TITLE
Google Login Error when app login is working

### ISSUE THREAD

**Issue by surewhynotmon** [PokemonGoF/PokemonGo-Bot#4420]
### Expected Behavior
Google login should work

### Actual Behavior
2016-08-20 18:50:20,089 [pgoapi.pgoapi] [ERROR] Login process failed: User login failed!
2016-08-20 18:50:20,090 [PokemonGoBot] [INFO] [login_failed] Login error, server busy. Waiting 10 seconds to try again.

### Steps to Reproduce
Login  

### Other Information
OS: Ubuntu
Branch: dev
Git Commit: 
cf4b45864222d739597204ea1fbc352493fd851c 
Python Version: 
Python 2.7.11

**Comment by Trico3** [comment]
I am also experiencing this issue

**Comment by Vvkmnn** [comment]
Also appears to be happening to ptc accounts as well, running f5ec24151155ebca0622c6d2e4feebf2a0224059.

I just made one and the exact same credentials work fine on the phone, and even in (PokemonGo-Map)[https://github.com/AHAAAAAAA/PokemonGo-Map]. Just not the bot.

**Comment by surewhynotmon** [comment]
@Vvkmnn looks like something related to the new pgoapi https://github.com/joelgreen/pgoapi/commits/master
But that repo has no issues page so hard to figure out what the problem exactly atm. 
I can log in to PTC accounts though.
