### ISSUE TITLE
Unexpected moveset [Tackle, Swift] for #120 Staryu, please update info in pokemon.json and create issue/PR

### ISSUE THREAD

**Issue by askovpen** [PokemonGoF/PokemonGo-Bot#4421]
Unexpected moveset [Tackle, Swift] for #120 Staryu, please update info in pokemon.json and create issue/PR

**Comment by Ogalababa** [comment]
found pokemon.json 
replace:
  {
    "Number": "120",
    "Name": "Staryu",
    "Classification": "Starshape Pokemon",
    "Type I": [
      "Water"
    ],
    "Weaknesses": [
      "Electric",
      "Grass"
    ],
    "Fast Attack(s)": [
      "Quick Attack",
      "Water Gun",
      "Tackle"
    ],
    "Weight": "34.5 kg",
    "Height": "0.8 m",
    "Next Evolution Requirements": {
      "Amount": 50,
      "Family": 120,
      "Name": "Staryu candies"
    },

**Comment by dextercai** [comment]
Ogalababa's way works well.

**Comment by LemonGraham** [comment]
I also had this issue, and fixed it the same way.

**Comment by mjmadsen** [comment]
#4323
