### ISSUE TITLE
Error in config.json?

### ISSUE THREAD

**Issue by duffreaper** [PokemonGoF/PokemonGo-Bot#4423]
### Expected Behavior 
 The bot should start and read off the config.json

### Actual Behavior
it won't read it

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/qCXJE01n

### Output when issue occurred
http://pastebin.com/d0Ywbqpr

### Steps to Reproduce
not sure? i just installed it follow he installation directions and this happened 

### Other Information
OS: 
 windows 7 
Branch: 
 ? 
Git Commit: 
All are up to date

**Comment by josegrobles** [comment]
Is the config file under the config folder? And if so what it is name?

**Comment by duffreaper** [comment]
@josegrobles https://gyazo.com/af85d2df3578fb0354e2ce6eae7dfa9a

**Comment by josegrobles** [comment]
Run it using the -cf flag like this 

> pokecly.py -cf /configs/config.json

**Comment by duffreaper** [comment]
@josegrobles how?

**Comment by josegrobles** [comment]
Using cmd

**Comment by duffreaper** [comment]
@josegrobles $ python pokecli.py -cf configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

**Comment by duffreaper** [comment]
that gets output

**Comment by josegrobles** [comment]
I don't really use Windows so I don't know if this will work but try

> source bin/activate

and then 

> python pokecli.py -cf configs/config.json

**Comment by duffreaper** [comment]
no such directory for the first thing

**Comment by josegrobles** [comment]
ok then go back to try executing the Start.bat file or wait until someone who uses Windows help you.

**Comment by Gobberwart** [comment]
> ImportError: No module named pgoapi.exceptions

Suggests you haven't updated the requirements. Run the following at the command prompt

`pip install -r .\requirements.txt --upgrade`

**Comment by Gobberwart** [comment]
I also note that you do not have a config.json file in your configs folder. What you actually have is a config.json.example file. Not the same thing.

You will need to open the config.json.example file, edit it as required (you will at least need your auth mode (ptc or google), username and password in there. Then save it as config.json (not config.json.example of config.json.txt).

Once you've done that, as well as updating the requirements, you should just be able to run it without any parameters and it should work fine.

python .\pokecli.py

Suggest you also read the documentation (in the docs folder) before asking any more questions, as this is all covered there.

**Comment by LuckyMe4Evers** [comment]
Did you download the bot from github or did the installer the download?
Because with the installer you don't get the folder "PokemonGo-Bot-Master" but you get the folder "PokemonGo-Bot"
