### ISSUE TITLE
[ERROR] Unexpected moveset [Tackle, Swift] for #120 Staryu, please update info in pokemon.json and create issue/PR

### ISSUE THREAD

**Issue by BVarella** [PokemonGoF/PokemonGo-Bot#4426]
[ERROR] Unexpected moveset [Tackle, Swift] for #120 Staryu, please update info in pokemon.json and create issue/PR

**Comment by josegrobles** [comment]
Are you using the Dev branch?

**Comment by BVarella** [comment]
No, sorry, I was using the master brach, but I just realized it is already fixed in the Dev.
