### ISSUE TITLE
Include elevation on FollowPath

### ISSUE THREAD

**Issue by KhanMaytok** [PokemonGoF/PokemonGo-Bot#4429]
The doc files reccommend get gpx path files from gpsies.com

The gpx file contains latitude, longitude and elevation, but the task FollowPath don't consider get the elevation.

In can be included for improvement on human behaviour

**Comment by Gobberwart** [comment]
follow_path.py now considers elevation... but breaks if a json file is used and it does not contain elevation.

**Comment by kanemasa1987** [comment]
As @Gobberwart says, it does from #4395.
The json issue should have been solved by #4452 as well.

**Comment by th3w4y** [comment]
@kanemasa1987 in the PolylineWalker you can use the new self.polyline_walker.get_alt() method  that i added in #4470
