### ISSUE TITLE
[enhancement] Make a --cp_percent command

### ISSUE THREAD

**Issue by dominikue** [PokemonGoF/PokemonGo-Bot#443]
Make a --cp_percent command, which can calculate with the pokemon max cp an optimal cp to keep it.

**For example:**
--cp_percent 0.8 
Exchange an Magikarp (Max CP 262.70) under 210.16
Exchange an Pikachu (Max CP 887.69) under 710.152

Source: http://pokemongo.gamepress.gg/pokemon-list

**Comment by douglascamata** [comment]
@dominikue how do we discover max CP of a pokemon?

**Comment by douglascamata** [comment]
This is a good thing!

**Comment by brantje** [comment]
Isn't the IV used for that?

**Comment by douglascamata** [comment]
@brantje dunno how IV works, I've been sleeping while ppl implemented it.

**Comment by dominikue** [comment]
@brantje the IV is the maximum CP, but the --cp parameter meas the CP at the moment.
#415 

_Luab commented 3 hours ago
@rwwagner90 IV is a long term quality of pokemon and it determines maximum CP, so while pokemons with higher IV could have less CP their upgrade potential is higher. And visa versa. 
http://gaming.stackexchange.com/questions/276692/in-pokemon-go-what-are-my-pokemons-hidden-iv-stats-and-why-do-they-matter_

**Comment by douglascamata** [comment]
@dominikue so if IV == 1 it means we found the highest CP version of a pokemon, right?

**Comment by popadiys** [comment]
I am not sure how correct is the current implementation:

[#] A Wild Shellder appeared! [CP 464] [Potential 0.6]
[x] Using Greatball...
[x] Captured Shellder! [CP 464] [IV 0.6] - exchanging for candy
[#] Shellder has been exchanged for candy!


Shellder CP 464 is pretty high, but the IV is calculated to 0.6 only

**Comment by douglascamata** [comment]
@popadiys as I understood, IV is potential to reach higher CP easily. In other words, let's say your Shellder gains 30 CP per power up.... maybe you can find Shellders that gain 40 or 50 CP per power up.

**Comment by douglascamata** [comment]
One problem is that when we evolve Pokemon, IV gets reseted. Maybe you Shellder can have become a great Cloyster.

**Comment by popadiys** [comment]
could have become, if the bot didn't exchange it for candy :) I think the IV potential is pretty misleading then, and the default value of 0.8 may discard valuable pokemons

**Comment by msdrahcir** [comment]
IVs do not get reset on evolution. CP is a combination of IV stats (indidual_attack, individual_defense,individual_stamina), base stats for pokemon, and pokemon half level (known through cp multiplier and additional cp multipler). http://pokemongo.gamepress.gg/pokemon-stats-advanced

**Comment by johnw424** [comment]
@douglascamata @popadiys 
High CP does not mean high IV.
Here is an example (fake #s).
Catch Lapras A (CP 1000, IV 30%).
Catch Lapras B (CP 400, IV 90%).
Which is better?
Currently, A is stronger, but this is their final maxed state:
Lapras A (CP 2500, IV 30%)
Lapras B (CP 2600, IV 90%)

[More info on IV.
](https://pokeassistant.com/main/ivcalculator)

**Comment by johnw424** [comment]
@douglascamata 
I believe what you're asking for IS the current implementation.
Each pokemon can have +0 to +15 on attack, stamina, and defense.
A perfect pokemon has (15 attack + 15 stamina + 15 defense)/(45 total) = 100% perfection aka 1.00 IV
A not perfect pokemon can have (0 attack + 5 stamina + 5 defense)/(45 total) = 22.2% perfection aka 0.22 IV.

**Comment by dominikue** [comment]
@johnw424 But i think a Lapras B (CP 400, IV 90%) isn't worth to upgrade.

**Comment by julesferreira** [comment]
@dominikue probably not until the late game. CP can always be maxed to 100% given enough candy/dust, IV never changes.

**Comment by julesferreira** [comment]
i.e. at max level, IV will determine the strongest pokemon

**Comment by dominikue** [comment]
Dust is a problem in late game. The idea with the --cp_percent command is: 
A pokemon with over 80% or 90% max cp and perfect IV are the best too keep and evolve.

If you just use -c 300 you will not caught an perfect Magikarp too evolve.

**Comment by buusc0** [comment]
@dominikue Tbh I don't really see dust as a problem late game if you're botting. I have over 200k at the moment...

**Comment by dominikue** [comment]
@buusc0 It cost 280k to max one pokemon.. https://docs.google.com/spreadsheets/d/1xZ1daunztOgvOZxO7ABfJPF41-2mqMDzY1Qs_0OWwq8/edit#gid=320772897

**Comment by buusc0** [comment]
@dominikue I understand, but considering that I'm getting about 60k a day, even with the bot still in its alpha stage, I don't think it'll be a problem. It'll be much harder to find a 95%+ IV perfection pokemon with the right moveset than to bot for a couple days for the dust to upgrade it.

**Comment by dominikue** [comment]
Hope somebodoy implements #452 - would help for IV :)

**Comment by gregtampa** [comment]
there is a 3rd party website that does this already check the readme i believe there is a link to it.
