### ISSUE TITLE
Expand UpdateLiveStats and make configurable

### ISSUE THREAD

**Issue by cbogithub** [PokemonGoF/PokemonGo-Bot#4434]
i think UpdateLiveStats should report in a day not at time when we start bot , and it should report pokemon cachted in a day 

"stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited" ,"pokemon_catched],

**Comment by orchid666** [comment]
without changing the whole thing maybe just add new stats options like stops_visited_day and pokemon_catched_day

**Comment by Gobberwart** [comment]
Better yet, maybe pokemon_caught...

Ya know, since neither cachted nor catched are words.
