### ISSUE TITLE
A new kind of softban???

### ISSUE THREAD

**Issue by seehuily** [PokemonGoF/PokemonGo-Bot#4437]
After using bot for several hours, I am not able to catch any pokemon(always vanished) but I am able to spin fort. I verified in bluestacks app player (A android simulator), it's showing the same. 

Is this a new kind of softban? Seems like it cannot be fixed by bot.

**Comment by oralunal** [comment]
I've first encountered this ban 5-6 days ago. You can spin forts but can't catch pokemons.

**Comment by seehuily** [comment]
Hi oralunal, what happened next ?

**Comment by oralunal** [comment]
After 2-3 days my account banned permanently :)

**Comment by seehuily** [comment]
OMG, that's too bad!!!!! I have two Snorlax on this account.

**Comment by seehuily** [comment]
aha, Not funny! so they are irrelevant? permanently banned and catchflee..

**Comment by oralunal** [comment]
I'm not sure, after it started to happen, I got perma ban in 2-3 days. In my account I have 3 dragonite with IV 100% and CP between 2100-2600, one snorlax with IV100% CP 2300 and list goes on :)

It was a great account :)

**Comment by mjmadsen** [comment]
Yeah, sorry. You're probably going to lose your account.

**Comment by avexus** [comment]
@oralunal nothing compared to my banned account.

**Comment by seehuily** [comment]
still active, let's see when I will be banned.
