### ISSUE TITLE
Complete Tutorial doesn't select Avatar

### ISSUE THREAD

**Issue by NatNew0** [PokemonGoF/PokemonGo-Bot#4445]
Hi,

the "complete tutorial" doesn't select an trainer avatar (google-account). 
After I logged on the trainer avatar is "invisible" (empty) and it's not possible to select one ;-)
Maybe it's possible to include a generic avatar selection in the "complete tutorial" task ?

**Comment by k4n30** [comment]
@net8q Are you able to assist?

**Comment by net8q** [comment]
Problem is that the pgoapi does not accept dict as argument in the API calls, and avatar is a dict with a value for each customisable choice (eye, ...)

We need to cherry-pick https://github.com/tejado/pgoapi/pull/214 (I've tested it with other calls, seems to work well)

Then the most easy way would be to random fill the avatar struct and just call the API at the opportune moment.

**Comment by mjmadsen** [comment]
Merged.
