### ISSUE TITLE
Stuck updating requirements.txt

### ISSUE THREAD

**Issue by icecubeice** [PokemonGoF/PokemonGo-Bot#4447]
### Expected Behavior
updates the items in requirements.txt

### Actual Behavior
It's stuck saying this:
The plan is to install the git repository https://github.com/joelgreen/pgoapi.git/

### Output when issue occurred
$ pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): numpy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): networkx==1.11 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Obtaining pgoapi from git+https://github.com/joelgreen/pgoapi.git/@b2927c5940a8d0febd41f006921d1c093542ddf8#egg=pgoapi (from -r requirements.txt (line 3))
  git clone in c:\users\anthony\downloads\pokemongo-bot\src\pgoapi exists with URL https://github.com/keyphact/pgoapi.git
  The plan is to install the git repository https://github.com/joelgreen/pgoapi.git/

### Steps to Reproduce
run pip install -r requirements.txt

### Other Information
OS: 
Windows 10
Branch: 
dev
commit:commit 5b901241eacc5942bd8699721038b81bc086d2de

**Comment by supergithubo** [comment]
Seems like they are changing the pgoapi to use the fork of @joelgreen

**Comment by odegraciajr** [comment]
Same error im getting git+https://github.com/joelgreen/pgoapi.git/@b2927c5940a8d0febd41f006921d1c093542ddf8#egg=pgoapi 404 on this link

**Comment by akymanau** [comment]
remove the / before the @ symbol

https://github.com/joelgreen/pgoapi.git@b2927c5940a8d0febd41f006921d1c093542ddf8#egg=pgoapi

**Comment by k4n30** [comment]
what commit are you on?

**Comment by icecubeice** [comment]
commit 5b901241eacc5942bd8699721038b81bc086d2de
@k4n30

**Comment by youweit** [comment]
delete `src/pgoapi` and try `pip install` again.

**Comment by jryd** [comment]
I was experiencing the same issue. 
Removing the src/pgoapi folder and running pip install worked for me.

**Comment by k4n30** [comment]
@icecubeice closing, please reopen if fix above doesn't work
