### ISSUE TITLE
Issue Bot not working, reload is not defined

### ISSUE THREAD

**Issue by yehan77** [PokemonGoF/PokemonGo-Bot#4450]
Okay, so i installed the bot using the install bat  and then i have filled out my config. 
I get the issue  reload is not defined

bash: bin/activate: No such file or directory
Traceback (most recent call last):
  File "pokecli.py", line 35, in <module>
    reload(sys)
NameError: name 'reload' is not defined
Sun, Aug 21, 2016 4:51:51 PM Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by yehan77** [comment]
why was it closed

**Comment by k4n30** [comment]
The Readme and the issue template both say your issue will be closed without notice if you don't create the issue correctly
