### ISSUE TITLE
Improvement over the config task wiki page

### ISSUE THREAD

**Issue by supercourgette** [PokemonGoF/PokemonGo-Bot#4451]
This is not a request for the bot, but for the wiki.  More precisely, the config file wiki page: https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md

I think this page could benefit from improvements (both from the user and developer perspective)

### Possible solution

- From a user perspective, in order to find an information about a task, you either (1) scroll over 500 lines or (2) use the search tool from your browser. This is an issue, since those workaround do not directly direct the user toward the information. A table of content may solve this issue.

- From a developer perspective, all the configuration of all the tasks are gathered in one file. This is an issue for developers, since it doesn't allow to keep track and clearly separate the information. A inclusion of files (one task = one file) into another file may solve this issue.

I know the default md format of github doesn't allow for an automatic table of content or even an include tag, but I'm pretty sure others options exists. :)

### How it would help others

A healthy wiki is a healthy community (I just made that up, but you good the idea) :)

**Comment by supercourgette** [comment]
Wa @mjmadsen  you are reactive. :+1:

**Comment by oralunal** [comment]
This improvement very important. I'm using this for three days and I'm not sure what types and options we have. I can't do what I want exactly because of inadequate configuration wiki.

**Comment by supercourgette** [comment]
I did a pr to add a table of content... It will only be available in dev for now. The table of content is not beautiful and is a bit broken but well... Better than nothing for the time being.

**Comment by supergithubo** [comment]
It would be great if a developer adding a new feature also update the wiki. (Add new config to wiki, give a bit description of the properties and possible values. Unit of measurement of the value is also important - hours, seconds, meters, feet, kilometers etc)

**Comment by oralunal** [comment]
If you don't want to work on this documentation please update PokemonGo-Config :)

**Comment by oralunal** [comment]
For example there is a new task named "CompleteTutorial". Who knows that what is this doing?

**Comment by leadboots5** [comment]
The 'wiki' is on the files that way anyone can contribute vs the wiki that can't. feel free to make it better.
