### ISSUE TITLE
The setting diameter and step_size under FollowSpiral

### ISSUE THREAD

**Issue by hobbes3** [PokemonGoF/PokemonGo-Bot#4455]
What is the undocumented `diameter` and `step_size` under `FollowSpiral`? I'm trying to not make the bot go so far from the starting location (stay near water to catch more Dratinis).

**Comment by philly223** [comment]
curious as well

**Comment by acurioustale** [comment]
See #2194:
> I also changed the configuration from a step count to a diameter. The spiral is always a square, so the diameter describes the width/height of the spiral (Height = diameter * 70m)

step_size is a distance in meters, diameter is a positive integer.
