### ISSUE TITLE
Throw ball miss % parameter?

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#4458]
### Question
What is the parameter that control the % of missed balls
Pokeball thrown to XXX missed.. trying again!

At some point I remember that Bot never missed (which was definitively weird) but I could not find a corresponding parameter in config files or doc.

Thx for the help.

**Comment by nowak-mateusz** [comment]
```
 "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.2,
            "nice_rate": 0.3,
            "normal_rate": 0.4,
            "spin_success_rate" : 0.6,
            "hit_rate": 0.75
          },
```

**Comment by Gurzeh** [comment]
@nowak-mateusz thx, so it is hit_rate. It was not in my config, so I guess there is a default. Many thanks for this quick reply.
