### ISSUE TITLE
Release/transfer pokemon is broken

### ISSUE THREAD

**Issue by kimdotnet** [PokemonGoF/PokemonGo-Bot#4459]
Neither in dev or master branch, I think rleease config is broken.

commit 601e21dbf464e2b3631d6a58e508b26af7fd470f
Author: Simba Zhang <solderzzc@users.noreply.github.com>
Date:   Sat Aug 20 20:53:39 2016 -0700

    Dev merge to master, PR (#4439)

    * Do not spin fort on timeout when restarting the bot (#3931)

    Fix bot stuck between forts when inventory is full

    * Fixed references to self.bot.config.walk (#4046)

    * Fixed error

    * Fixed error

    * Updating run.sh and install.sh (#4033)

    * Update run.sh

    * Update setup.sh

    * Update setup.sh

OS
==
ubuntu

**Comment by gusterwoei** [comment]
Yea the release config is not working suddenly after update

**Comment by supergithubo** [comment]
Yes, I think the logic changes instead of transfering pokemons on each cycle, the bot now will only transfer pokemons when `min_free_slot` is reached. I think changelog is helpful on each release.
