### ISSUE TITLE
-iv unsets -c

### ISSUE THREAD

**Issue by ts91** [PokemonGoF/PokemonGo-Bot#446]
### Expected Behavior
If -iv and -c are both set they should both be taken into account when deciding to transfer a caught pokemon.

### Actual Behavior
If -iv and -c are set. Only the -iv value is used, disregarding the -c.

### Other Information
OS: Linux
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by ts91** [comment]
Sorry I think it actually is doing the wanted behavior at the moment. How do I close this?

**Comment by dominikue** [comment]
Left button next the green Comment Button.
