### ISSUE TITLE
RandomPause : Bot pausing at end of path using random values

### ISSUE THREAD

**Issue by nicobr75000** [PokemonGoF/PokemonGo-Bot#4460]
The bot should pause respecting the duration and interval in config.

### Actual Behavior
I am not sure this is due to me changing the config and then restarting the bot but the bot log a correct ` [RandomPause] [INFO] [next_random_pause] Next random pause at 06:20:13, for a duration of 0:04:49`but after first action there is another log `[INFO] [path_lap_end] Great job, lot of calories burned! Taking a break now for 0:56:50, will resume at 06:17:09.`
I cannot find where it does come from in code !

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/jccTC55w

### Output when issue occurred
`[INFO] [path_lap_end] Great job, lot of calories burned! Taking a break now for 0:56:50, will resume at 06:17:09.`

### Steps to Reproduce
Not sure. 
Maybe set some values, then change and restart the bot.
I tried rebooting the terminal with no luck.

### Other Information
OS: 
Mac OS
Branch: 
Dev
Git Commit: 
da0b4c3db167290d4eb0524a576a9e49d8a6e1f2

Python Version: 
Python 2.7.10

**Comment by nicobr75000** [comment]
OK found it, there are new param to the followPath

```
    "number_lap": 10,
    "timer_restart_min": "00:01:00",
    "timer_restart_max": "00:01:10"
```
What is the goal compared to randomPause? Setting both seems a bit too much?

**Comment by mjmadsen** [comment]
Might be a bit redundant, but we currently have lots of folks adding elements to make everything as configurable as possible. We'll probably retool down the road. 

@nicobr75000 Can we close this now?

**Comment by nicobr75000** [comment]
Sure thanks
