### ISSUE TITLE
OpenPoGo Web UI Logs Not Updating

### ISSUE THREAD

**Issue by oralunal** [PokemonGoF/PokemonGo-Bot#4464]
It would be great if the logs update by second, it would be nice if it updates the logs
> Logs
> 11:15
> Loading Data..
> 11:15
> Data Loaded!
> 11:15
> Trainer loaded: oralunal
> 11:15
> [oralunal] Pidgey appeared

**Comment by mjmadsen** [comment]
This might be better suited for https://github.com/PokemonGoF/PokemonGo-Web

**Comment by oralunal** [comment]
Oh, I see. Thank you,
