### ISSUE TITLE
No module named pgoapi.exceptions

### ISSUE THREAD

**Issue by mrcyclo** [PokemonGoF/PokemonGo-Bot#4469]
Traceback (most recent call last):
  File "pokecli.py", line 43, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException
ImportError: No module named pgoapi.exceptions

 Something went wrong and the bot needed to be restarted. Please investigate the cause.

I got this error? How to fix it?

**Comment by supergithubo** [comment]
Have you installed the requirements? `pip install -r requirements.txt`

**Comment by mrcyclo** [comment]
How to install it? I use windows 10?

**Comment by earthchie** [comment]
then you better use Linux subsystem. It much more easier to run bot with docker.

**Comment by mrcyclo** [comment]
I have installed requirements but still got error. The previous version not got this error...

**Comment by Calcyfer** [comment]
Try `pip install -r requirements.txt --upgrade`

**Comment by TheOwl99** [comment]
i have the same error also windows 10 worked yesterday, today give me this error

**Comment by Calcyfer** [comment]
dev or master?

**Comment by TheOwl99** [comment]
master

**Comment by mrcyclo** [comment]
master. still got this error

**Comment by Calcyfer** [comment]
dev is working at the moment, use that branch while I check out what the cause is.

**Comment by TheOwl99** [comment]
Ok thanks please update us!

**Comment by iruy** [comment]
I also got this error, a second run of `pip2 install --upgrade -r requirements.txt` solved the issue

**Comment by mjmadsen** [comment]
@mrcyclo Please reopen if this isn't resolved.

**Comment by mrcyclo** [comment]
OK. It solved.
