### ISSUE TITLE
[Dev] Bot walking, but not found any stops or Pokemon

### ISSUE THREAD

**Issue by earthchie** [PokemonGoF/PokemonGo-Bot#4473]
My bot is keep walking in spiral, but not visit any Pokestop or encounter any Pokemon.

![image](https://cloud.githubusercontent.com/assets/7013039/17837109/b48486fe-67d3-11e6-9435-1649eac956dd.png)

![image](https://cloud.githubusercontent.com/assets/7013039/17837158/24032674-67d5-11e6-8cfa-5b95f18f445a.png)

**Comment by k4n30** [comment]
Use issue template please
