### ISSUE TITLE
Whats is NCP? Have option rename {ncp}

### ISSUE THREAD

**Issue by MrCarlosJr** [PokemonGoF/PokemonGo-Bot#4476]
I don't undestand why is ncp is (my CP) / ( Max CP) ?

**Comment by sohje** [comment]
NCP - normalized CP (percentage of Max CP pokemon can achieve)

**Comment by MrCarlosJr** [comment]
But its CP is the lv40 right?

**Comment by sohje** [comment]
@MrCarlosJr Yeap, i think so.

**Comment by MrCarlosJr** [comment]
@sohje Thanks man.
