### ISSUE TITLE
[Dev] Bot walking, but not found any stops or Pokemon

### ISSUE THREAD

**Issue by earthchie** [PokemonGoF/PokemonGo-Bot#4481]
### Expected Behavior
Visit nearby Pokestops and encounter Pokemon along the way.

### Actual Behavior
Not found any Pokestop or Pokemon.

### FULL config.json
http://pastebin.com/H8mpCNJJ

### Output when issue occurred

![image](https://cloud.githubusercontent.com/assets/7013039/17837551/3bb91926-67e0-11e6-90a0-f5a5eb250b87.png)

![image](https://cloud.githubusercontent.com/assets/7013039/17837552/3f1e5d56-67e0-11e6-90c0-60e386aa37c8.png)

### Steps to Reproduce
$ git clone -b dev https://github.com/PokemonGoF/PokemonGo-Bot.git pogobot
$ cd pogobot
$ wget http://pastebin.com/raw/H8mpCNJJ -O ./configs/config.json
$ docker build --build-arg timezone=Europe/London -t pokemongo-bot .
$ docker run --name=bot1-pokego --rm -it -v $(pwd)/configs/config.json:/usr/src/app/configs/config.json pokemongo-bot

### Other Information
OS: Ubuntu 16.04
Docker: Docker version 1.11.2, build b9f10c9
Branch:  dev 
Git Commit: cec90a56e2073c6b2b86bf5e68ededc07a7913f6
Python Version: 2.7.12

**Comment by mjmadsen** [comment]
Please try a different account. That looks like a softban.

**Comment by earthchie** [comment]
nah it not softbanned.

**Comment by nicobr75000** [comment]
+1

**Comment by nicobr75000** [comment]
May be IP ban, I tried the same bot from another computer and it works (same conf same commit)

**Comment by Hellycat** [comment]
Is it possible to use proxy in config?

**Comment by foster82** [comment]
I have been running 3 bots all seeing this issue , on 2 different computers.

**Comment by mjmadsen** [comment]
On the same IP @foster82?

**Comment by foster82** [comment]
yeah ,unfortunatly i have a static ip

**Comment by nicobr75000** [comment]
This is back to normal for me so I suspect either an IP ban or an IP quota on the API (but since phone operator in France share only a few IPs I suppose this is not that one :()

**Comment by foster82** [comment]
ok managed to try on another connection and it does seem to be an IP ban, any way round this ?
