### ISSUE TITLE
Rather odd error 

### ISSUE THREAD

**Issue by wardude202** [PokemonGoF/PokemonGo-Bot#4482]
Hey guys so i have been trying to get this to work for a wile now here is my error.

ImportError: DLL load failed: %1 is not a valid Win32 application.

not sure why this is happening?? 
any thoughts

tried fresh build and what not. using Win10 64bit

**Comment by mjmadsen** [comment]
What branch are you using? What commit are you using? Through what means did you try to install? Do you have install logs?

**Comment by BreezeRo** [comment]
Most likely happens when you are running 64-bit python and attempt to load a 32-bit dll or the reverse.

**Comment by ScriptKiddiez** [comment]
#2736 #2804 #2856 #3810 #3834

Please review similar issues that have been resolved already before posting a new one.
