### ISSUE TITLE
Do not release any pokemon

### ISSUE THREAD

**Issue by mrcyclo** [PokemonGoF/PokemonGo-Bot#4488]
This is my config, but it not release any pokemon. Tell me how to fix it?

[config.txt](https://github.com/PokemonGoF/PokemonGo-Bot/files/428930/config.txt)

**Comment by 03t02** [comment]
Duplicated #4459

**Comment by mrcyclo** [comment]
I know. But I want release immediately, not wait till full the bag.

**Comment by 03t02** [comment]
```
TransferPokemon
min_free_slot: Default 5 | Once the pokebag has less empty slots than this amount, the transfer process is triggered. | Big values (i.e 9999) will trigger the transfer process after each catch.
```

I saw it in the documentation.

**Comment by mrcyclo** [comment]
Ok, thanks. I not yet read new documentation :))
