### ISSUE TITLE
Do not release pokemon below cp in the bag

### ISSUE THREAD

**Issue by mrcyclo** [PokemonGoF/PokemonGo-Bot#4489]
{
    "type": "TransferPokemon",
    "config": {
        "min_free_slot": 9999,
        "transfer_wait_min": 1,
        "transfer_wait_max": 4
    }
},
"release": {
      "any": {"release_below_cp": 500, "release_below_iv": 0, "logic": "or"},
      "any": {"keep_best_cp": 1},
}

Give back this feature...

**Comment by xSidewinderx** [comment]
Same issue here. latest git pull on dev wont release any Pokemon for me.

**Comment by pranavperfect** [comment]
+1 to the issue

**Comment by MrTimide** [comment]
+1 wont release any pokemon since update git pull thanks a lot for answer

**Comment by muskosan** [comment]
+1 , this is on both master and dev

**Comment by ConorNevin** [comment]
+1

**Comment by AradeaTechno** [comment]
"any": {"release_below_cp": 500, "release_below_iv": 0, "logic": "or"}, 

take a look to your config,,,how could bot find which pokemon under IV 0 ?? release_below_iv : 0 , it's mean your pokemon shoul has IV < 0 to release...

for the latest update, bot will release pokemon when your max_pokemon_slot has reached. but not sure yet, caused i never reach the number yet...

**Comment by k4n30** [comment]
Would you like to update your feature request a bit better, other than some config options, so others know what you actually would like?

**Comment by Billy1988** [comment]
+1, pulled latest master branch has this problem

Bot do not release any pokemon with this config

{
"type": "TransferPokemon",
"config": {
"min_free_slot": 9999,
"transfer_wait_min": 1,
"transfer_wait_max": 4
}
},
"release": {
"any": {"release_below_iv": 0.9},
}

**Comment by ishepard** [comment]
Same problem here, bot never transfers pokemons with this configuration

"release": {
      "any": {"keep_best_cp": 2, "keep_best_iv": 1},
}

However, it seems that the release function is never called, maybe we just have to wait to have the bag full of pokemon, then it will start to release them.

**Comment by leadboots5** [comment]
Going to assume wrong configuration/misunderstanding of when release runs as I know some of the above works. open a new issue with more complete info if need be.
