### ISSUE TITLE
Change IP in Config, Ban IP Adrress

### ISSUE THREAD

**Issue by Hellycat** [PokemonGoF/PokemonGo-Bot#4498]
Is it possible to change IP in configs?

Probably i got ban by IP adress, because my bot just walking (tried few no banned accounts) and get no pokemon, no xp, nothing for 24 hours in few accounts, so i think it's ip banned or any ip limit.

If the answer is no, maybe someone now how to add this to BOT?

Thank's for advance!

**Comment by OursDesCavernes** [comment]
Just use another ISP, the bot has no way to choose the IP it's using.
Try to use your neighbor's WiFi or your phone AP.

**Comment by gjonville** [comment]
or you can use a VPN

**Comment by subzerofun** [comment]
1) easy solution: get a software that can handle proxy connections selectively, e.g. where you can select a specific app or process id and add rules which proxy server it should use. i am on OSX 10.10 and use [proxifier](https://www.proxifier.com/) to manage and change proxies for my bot and map workers. you can get it for windows too. and i´m sure there is something similar for linux out there.

2) more info: 
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3574 

3) a plugin for proxie support:
https://github.com/br0kenb1nary/PogoPlugin
