### ISSUE TITLE
Get banned 

### ISSUE THREAD

**Issue by Blackbird594** [PokemonGoF/PokemonGo-Bot#45]
Hello Community, I am aware of botting isn´t a good thing in PokemonGo, but i live in a rual area in Germany without any good Pokemons,only Pokemon aviable here are Rattata and the Pidgion Pokemon,so i took a look at https://www.reddit.com/r/pokemongodev/comments/4tv0er/open_source_fully_functioning_bot_for_farming_and/ and found some bots, for farming Pokestops and catching Pokemon in any location i want..

And the result was a Ban last Night...

http://imgur.com/a/SA3gg

My Hardware:

iPhone 5s without jailbreak

I run the Bot in total maybe 2hours. My fakelocation was only 1 hour from my real location located. As precaution i logged in my App only after the bot stopped for at least an hour,so i dont get banned but it didnt worked out..

**Comment by Janhouse** [comment]
Was that a question?

**Comment by 3mph4515** [comment]
Last updated leads to ban if using '-s' parameter.

**Comment by douglascamata** [comment]
I think you should be safe if using -w to "walk" instead of teleport.

**Comment by sidezzz** [comment]
Is it permanent ban?

**Comment by 3mph4515** [comment]
@sidezzz No, it is soft ban. 
@douglascamata Thank you for -w command. Have not noticed before

**Comment by Blackbird594** [comment]
@3mph4515 but i am still banned,for nearly 20hours and cant login anymore,even if i deinstall the app and reinstall it.

**Comment by sidezzz** [comment]
@3mph4515 but with soft ban u just cant use pokestop and catch pokemons.

**Comment by harsh1412** [comment]
@douglascamata dude is there a speed defined for walk?
When i used -w it says it need 1 more argument so i did -w 1 and its working now but did dev implemented any speed of walking that we can change?

**Comment by w1sht0l1v3** [comment]
you define your own speed with -w ...1 means 1meter per second....come on...it even explains in the documentation how to use it

**Comment by PokemonGoF** [comment]
Let me close this issue. :)
