### ISSUE TITLE
keep pokemon above certain cp

### ISSUE THREAD

**Issue by rishub** [PokemonGoF/PokemonGo-Bot#4500]
So I want to release any pokemon below an IV of 0.8. But, I want to keep any pokemon above a CP of 1500, even if its IV is not above 0.8. How can I add this to the config file, or is this something that needs to be added?

**Comment by Trico3** [comment]
Add this in your config under the release section.

    "release": {
      "any": {"release_below_cp": 1500, "release_below_iv": 0.8, "logic": "or"},

In the future for these questions you should use the chat help section at https://pokemongo-bot.slack.com

**Comment by rishub** [comment]
no but that will release a pokemon that is a cp of 1500 and iv 0.6 but i wanna keep that

**Comment by Trico3** [comment]
It should keep anything above 1500 **_OR_** IV 0.8 and release the rest.
If you are really worried you could even do 
"release": {
  "any": {"release_below_cp": 1499, "release_below_iv": 0.79, "logic": "or"},
