### ISSUE TITLE
Bot should take a break after being softbanned (all pokemons run away)

### ISSUE THREAD

**Issue by hobbes3** [PokemonGoF/PokemonGo-Bot#4510]
### Short Description

After running the bots for hours, the bot gets softbanned and all Pokemon runs away.

### Possible solution

Although the bot can still spin Pokestop, the bot should stop and take a break for a few hours since I have a theory that Niantic records how much a player keeps playing after being softbanned (to issue a permaban later).

### How it would help others

I believe less bots will be permabanned.

**Comment by ganagus** [comment]
I guess so.. and I goes some of my bot accounts were banned because it always spun pokestop for hours when being softbanned.

**Comment by ScriptKiddiez** [comment]
I can confirm this. I've had 3 accounts now be banned for running hours on end with encountering pokemon, but not catching any of them. I've also noticed that sometimes they will erase everything in your inventory and the console will spew out the message, "No usable pokeballs found.". After running for several hours without catching anything, they obviously know who is and isn't botting.

**Comment by hobbes3** [comment]
Currently I have to manually check to see if my bot is still catching Pokemons. If I see a bunch of vanishes then I manually stop the bot and restart it a few hours later...
