### ISSUE TITLE
 Something went wrong and the bot needed to be restarted. Please investigate the  cause.

### ISSUE THREAD

**Issue by gucabansimon** [PokemonGoF/PokemonGo-Bot#4512]
Working fine previously but after coming home from work (12hours) i ran the script, it updated and thrown error:

--------------------Starting bot--------------------

Traceback (most recent call last):
  File "pokecli.py", line 46, in <module>
    from pokemongo_bot import inventory
  File "C:\Python27\PokemonGo-Bot\pokemongo_bot\__init__.py", line 22, in <modul
e>
    from api_wrapper import ApiWrapper
  File "C:\Python27\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 12, in <mo
dule>
    from pgoapi.protos.POGOProtos.Networking.Requests.RequestType_pb2 import Req
uestType
ImportError: No module named RequestType_pb2

 Something went wrong and the bot needed to be restarted. Please investigate the
 cause.

Waiting for 50 seconds, press a key to continue ...

**Comment by iidanielmontes** [comment]
same here

**Comment by ganagus** [comment]
I resolved similar error by running the following command: pip install upgrade -r requirements.txt. I'm on Windows.

**Comment by k4n30** [comment]
Please follow correct procedure to upgrade. If the error persists, delete your /src directory inside the root of the bot and rerun `pip install --upgrade -r requirements.txt`
