### ISSUE TITLE
Connection stays open.

### ISSUE THREAD

**Issue by serberus7** [PokemonGoF/PokemonGo-Bot#4515]
Old revisions would open a connection, send and receive, then close a connection to open a new one again. The new revision opens a connection and keeps that same connection open to send receive.
Why?
That really messes up the bots for me and the way my proxies work. 
80% of the time bots stay at "Next egg incubates in.."
And repeats that every 120 seconds (as per the config)
I'm not using the new rev until the old connection standards are at least an option. :(
I love the new complete tutorial cell worker too... Feel free to ask me more about this issue if I'm not being descriptive enough, I would love to see it fixed.
![image](https://cloud.githubusercontent.com/assets/20890081/17841151/3dbe7068-67db-11e6-9748-cc02be3407a0.png)

**Comment by k4n30** [comment]
Please use issue template properly
