### ISSUE TITLE
pokecli.py error

### ISSUE THREAD

**Issue by gucabansimon** [PokemonGoF/PokemonGo-Bot#4525]
![screenshot_1](https://cloud.githubusercontent.com/assets/21140175/17844003/5dbf42f4-683d-11e6-9fcf-e36425403083.png)

**Comment by prickobello** [comment]
![screenshot 2016-08-22 07 14 10](https://cloud.githubusercontent.com/assets/21166710/17844283/137c4552-6838-11e6-900f-5d4ffa43fea7.png)
