### ISSUE TITLE
pip install -r requirements.txt fails

### ISSUE THREAD

**Issue by hobbes3** [PokemonGoF/PokemonGo-Bot#4526]
### Expected Behavior

`pip install -r requirements.txt` should succeed.

### Actual Behavior

It fails instead.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

This is a fresh install before even creating a `config.conf`

### Output when issue occurred

The logs are huuuge, so I'll just include the last few pages:

    x86_64-linux-gnu-gcc: numpy/linalg/lapack_lite/zlapack_lite.c

    numpy/linalg/lapack_lite/zlapack_lite.c: In function ‘zlaed7_’:

    numpy/linalg/lapack_lite/zlapack_lite.c:10000:59: warning: variable ‘ind2’ set but not used [-Wunused-but-set-variable]

        static integer i__, k, n1, n2, iq, iw, iz, ptr, ind1, ind2, indx, curr,

                                                            ^

    numpy/linalg/lapack_lite/zlapack_lite.c:10000:53: warning: variable ‘ind1’ set but not used [-Wunused-but-set-variable]

        static integer i__, k, n1, n2, iq, iw, iz, ptr, ind1, ind2, indx, curr,

                                                        ^

    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/numpy/linalg/umath_linalg.o build/temp.linux-x86_64-2.7/numpy/linalg/lapack_lite/python_xerbla.o build/temp.linux-x86_64-2.7/numpy/linalg/lapack_lite/zlapack_lite.o build/temp.linux-x86_64-2.7/numpy/linalg/lapack_lite/dlapack_lite.o build/temp.linux-x86_64-2.7/numpy/linalg/lapack_lite/blas_lite.o build/temp.linux-x86_64-2.7/numpy/linalg/lapack_lite/dlamch.o build/temp.linux-x86_64-2.7/numpy/linalg/lapack_lite/f2c_lite.o -Lbuild/temp.linux-x86_64-2.7 -lnpymath -o build/lib.linux-x86_64-2.7/numpy/linalg/_umath_linalg.so

    building 'numpy.random.mtrand' extension

    compiling C sources

    C compiler: x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC

    creating build/temp.linux-x86_64-2.7/numpy/random

    creating build/temp.linux-x86_64-2.7/numpy/random/mtrand

    compile options: '-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Inumpy/core/include -Ibuild/src.linux-x86_64-2.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python2.7 -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -c'

    x86_64-linux-gnu-gcc: numpy/random/mtrand/distributions.c

    x86_64-linux-gnu-gcc: numpy/random/mtrand/mtrand.c

    x86_64-linux-gnu-gcc: numpy/random/mtrand/initarray.c

    x86_64-linux-gnu-gcc: numpy/random/mtrand/randomkit.c

    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/numpy/random/mtrand/mtrand.o build/temp.linux-x86_64-2.7/numpy/random/mtrand/randomkit.o build/temp.linux-x86_64-2.7/numpy/random/mtrand/initarray.o build/temp.linux-x86_64-2.7/numpy/random/mtrand/distributions.o -Lbuild/temp.linux-x86_64-2.7 -o build/lib.linux-x86_64-2.7/numpy/random/mtrand.so

    running build_scripts

    creating build/scripts.linux-x86_64-2.7

    Creating build/scripts.linux-x86_64-2.7/f2py

    adding 'build/scripts.linux-x86_64-2.7/f2py' to scripts

    changing mode of build/scripts.linux-x86_64-2.7/f2py from 644 to 755

    running install_lib

    creating /usr/local/lib/python2.7/dist-packages/numpy

    error: could not create '/usr/local/lib/python2.7/dist-packages/numpy': Permission denied

    ----------------------------------------
    Cleaning up...
    Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-h9I6AI/numpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-JkZNbv-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-h9I6AI/numpy
    Traceback (most recent call last):
    File "/usr/bin/pip", line 9, in <module>
        load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
    File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
        return command.main(cmd_args)
    File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
        text = '\n'.join(complete_log)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)

### Steps to Reproduce

    git clone -b dev https://github.com/PokemonGoF/PokemonGo-Bot.git
    sudo apt-get install build-essential autoconf libtool pkg-config make python2.7-dev wget git
    pyenv local 2.7.12
    cd PokemonGo-Bot
    pip install -r requirements.txt

### Other Information
OS: Debian 8.1
 
Branch: dev
 
Git Commit: 695ca70305be244a5c6fc12464d5242f14f648e7
 
Python Version: 2.7.12
 
Any other relevant files/configs (eg: path files)

**Comment by supergithubo** [comment]
Try to run it as root `sudo`

**Comment by hobbes3** [comment]
It turned out my Python was still using system python since I did `su pokemon` instead of `su - pokemon` and `pyenv` was undefined. I fixed it now.
