### ISSUE TITLE
location_cache no longer works.

### ISSUE THREAD

**Issue by zynjec** [PokemonGoF/PokemonGo-Bot#453]
### Expected Behavior
The script to resume farming where it left off when launched with --location_cache, issue began after multi-account pull request was accepted (changed the name of location.json)

### Actual Behavior
Starts farming at supplied location (via command line or options).

### Steps to Reproduce
Run script with --location_cache.

### Other Information
OS: Ubuntu 14.04
Git Commit: 345f3412f0254132e4244c7c88c7dbadccbde0f5

**Comment by skydrome** [comment]
--location_cache true

**Comment by zynjec** [comment]
Documentation needs to be updated then, somewhere overnight it went from just passing --location_cache to needed a boolean value.

**Comment by dominikue** [comment]
The same with "-it, --initial_transfer".

**Comment by Skeyelab** [comment]
-it doesnt even work
`pokecli.py: error: unrecognized arguments: -it true`

**Comment by alxsah** [comment]
"-lc 1" and "-it 1" seem to work for me. Should be mentioned under the usage section of the readme I think.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
