### ISSUE TITLE
[Feature Request] Can we have the mons' stats in the log file?

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#4534]
Hi, I would like to post a feature.
Can we have stats for bots like iv, atk, defense, stamina, movesets written to a log file? That would be very nice to look at.
Also, in the config file, I would like an option to specify how many mons we want to display. Thank you!

**Comment by avexus** [comment]
I guess this is done? No?

**Comment by MZorzy** [comment]
stamina is now more defence-power so chansey bettrr to snorlax on gym
