### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mrcyclo** [PokemonGoF/PokemonGo-Bot#4538]
The directory name is invalid.
python: can't open file 'pokecli.py': [Errno 2] No such file or directory

 Something went wrong and the bot needed to be restarted. Please investigate the cause.

**Comment by liangchunn** [comment]
That probably means that your `pokecli.py` is not in the same directory as `run.sh`
Check if `pokecli.py` exists in the root folder or run it manually: 
`cd PokemonGo-Bot
source bin/activate
python pokecli.py -cf ./configs/config.json`

**Comment by mrcyclo** [comment]
Solved. Bot do not update PokemonGo-Bot-Start.bat. I must manually update it.
