### ISSUE TITLE
Stuck in multiple lured pokemons

### ISSUE THREAD

**Issue by ilcic** [PokemonGoF/PokemonGo-Bot#4541]
### Expected Behavior
straight forward to a lured pokemon instead of stuck in multiple lured pokemons

### Actual Behavior
stuck in two lured pokemon and stop moving

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
{
    "auth_service": "google",
    "username": "",
    "password": "",
    "location": "25.136627, 121.506174",
    "gmapkey": "",
    "encrypt_location": "",
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "tasks": [
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "SleepSchedule",
        "config": {
          "enabled": false,
          "time": "00:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43",
          "wake_up_at_location": ""
        }
      },
	  {
		"type": "RandomPause",
        "config": {
		  "enabled": false,
		  "min_duration": "00:00:10",
		  "max_duration": "00:10:00",
		  "min_interval": "00:10:00",
		  "max_interval": "02:00:00"
        }
	  },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": false,
          "// set a name": "",
          "nickname": ""
        }
      },
      {
         "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true,
          "min_interval": 120
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": false,
          "min_interval": 120,
          "show_all_multiple_lines": false,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "min_free_slot": 5,
          "transfer_wait_min": 1,
          "transfer_wait_max": 4
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_above_iv": 0.9,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "evolve_all": "none",
          "first_evolve_by": "cp",
          "evolve_above_cp": 500,
          "evolve_above_iv": 0.8,
          "logic": "or",
          "evolve_speed": 20,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "max_balls_keep": 200,
          "max_potions_keep": 30,
          "max_berries_keep": 30,
          "max_revives_keep": 30,
          "item_filter": {
            "Pokeball":       { "keep" : 50 },
            "Greatball":      { "keep" : 100 },
			"Ultraball":      { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 10 },
            "Hyper Potion":   { "keep" : 20 },
            "Revive":         { "keep" : 10 },
            "Razz Berry":     { "keep" : 30 }
          },
          "recycle_wait_min": 1,
          "recycle_wait_max": 4
        }
      },
      {
        "type": "CatchPokemon",
        "config": {
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 5,
          "berry_threshold": 0.35,
          "vip_berry_threshold": 0.9,
          "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.5,
            "nice_rate": 0.3,
            "normal_rate": 0.1,
            "spin_success_rate" : 0.6,
            "hit_rate": 0.75
          },
          "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 2,
            "catch_wait_max": 6,
            "berry_wait_min": 2,
            "berry_wait_max": 3,
            "changeball_wait_min": 2,
            "changeball_wait_max": 3
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "spin_wait_min": 3,
          "spin_wait_max": 5
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "lure_attraction": true,
          "lure_max_distance": 2000,
          "walker": "StepWalker"
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": false,
      "max_circle_size": 10,
      "cache_recent_forts": true
    },
    "pokemon_bag": {
      "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
      "show_at_start": true,
      "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
      "show_count": false,
      "// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
      "show_candies": false,
      "// 'pokemon_info' parameter define which info to show for each pokemon": {},
      "// the available options are": {},
      "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
      "pokemon_info": ["cp", "iv_pct"]
    },
    "walk_max": 3.16,
    "walk_min": 1.16,
    "alt_min": 500,
    "alt_max": 1000,
    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": false,
    "replicate_gps_z_noise": false,
    "gps_xy_noise_range": 0.000125,
    "gps_z_noise_range": 12.5,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging_color": true,
    "daily_catch_limit": 800,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "Krabby": {"never_capture": true},
      "Bellsprout": {"never_capture": true},
      "Goldeen": {"never_capture": true},
      "Pidgey": {"never_capture": true},
      "Zubat": {"never_capture": true},
      "Caterpie": {"never_capture": true},
      "Weedle": {"never_capture": true},
      "Rattata": {"never_capture": true},
      "Venonat": {"never_capture": true},
	  "Paras": {"never_capture": true},
      "Nidoran F": {"never_capture": true},
      "Nidoran M": {"never_capture": true},
      "Ekans": {"never_capture": true},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
	  "any": {"keep_best_iv": 2, "keep_best_cp": 1},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3},
	  "// Example of custom order of static criterion": {},
	  "// Zubat": {"keep_best_custom": "iv, cp, hp_max", "amount":2}
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "Dratini": {},
        "Dragonair": {},
        "Aerodactyl": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}

### Output when issue occurred
bot1-pokego_1     | 2016-08-22 09:04:18,038 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 09:04:20,433 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)
bot1-pokego_1     | 2016-08-22 09:04:20,433 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 09:04:22,451 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)
bot1-pokego_1     | 2016-08-22 09:04:22,452 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 09:04:23,896 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)
bot1-pokego_1     | 2016-08-22 09:04:23,896 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 09:04:26,183 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)
bot1-pokego_1     | 2016-08-22 09:04:26,183 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 09:04:28,564 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)
bot1-pokego_1     | 2016-08-22 09:04:28,564 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 09:04:30,633 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)
bot1-pokego_1     | 2016-08-22 09:04:30,634 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 09:04:32,919 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)
bot1-pokego_1     | 2016-08-22 09:04:32,919 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 09:04:33,804 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)
bot1-pokego_1     | 2016-08-22 09:04:33,804 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 09:04:36,402 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)
bot1-pokego_1     | 2016-08-22 09:04:36,402 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 09:04:38,275 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)
bot1-pokego_1     | 2016-08-22 09:04:38,276 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)

### Steps to Reproduce
set the location where lots of lured fort surrounded

### Other Information
OS: 
linux with docker-compose
Branch: 
dev
Git Commit: 
c1cfaf6f00c4b31bfd13d0ec68c046d19b44d473
Python Version: 
Python 2.7.12

**Comment by mjmadsen** [comment]
Hm, sorry about this. Let me look into it.

**Comment by mjmadsen** [comment]
Please try the above PR. Something fishy going on with how I was sorting our pokemon list.

**Comment by ilcic** [comment]
I have tried the patch. Unfortunately the problem still persist with the following log : (

bot1-pokego_1     | 2016-08-22 13:46:09,620 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 13:46:09,620 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)
bot1-pokego_1     | 2016-08-22 13:46:11,959 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 13:46:11,959 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)
bot1-pokego_1     | 2016-08-22 13:46:12,862 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 13:46:12,862 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)
bot1-pokego_1     | 2016-08-22 13:46:15,103 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 13:46:15,103 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)
bot1-pokego_1     | 2016-08-22 13:46:17,725 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 13:46:17,726 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)
bot1-pokego_1     | 2016-08-22 13:46:19,686 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 13:46:19,686 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)
bot1-pokego_1     | 2016-08-22 13:46:20,536 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort  (2dd57b0c298441fa8dedb4c4dd485c2d.16)
bot1-pokego_1     | 2016-08-22 13:46:20,536 [CatchPokemon] [INFO] [lured_pokemon_found] Lured pokemon at fort - (5d8f471360c3447fb88231762ce3e912.16)

**Comment by tomorrowplusone** [comment]
@helloj already did a patch, but he did not do a pull request
https://github.com/PokemonGoF/PokemonGo-Bot/issues/4153

**Comment by ilcic** [comment]
The patch from @helloj works like charm. Many thanks.

**Comment by mjmadsen** [comment]
Recent dev commit should solve this.
