### ISSUE TITLE
Character in examples config.json

### ISSUE THREAD

**Issue by LuckyMe4Evers** [PokemonGoF/PokemonGo-Bot#4543]
I don't know where to put this, but for me it's an ISSUE and an FEATURE REQUEST.

I'm making a PokemonGo-Bot-Configurator for windows, to make a config.json (for the beginners and also for others). 
For now it only generates the auth service, username, password, location and Google Maps API. Because these 5 lines are equal in all of the config.json example files. Maybe in the near future i can let the ppl choose to make a customized config.json.
The rest of the config.json will be imported out of the chosen (1 of 6) config.json example.
But due to some limitations in windows, some special characters (there's only 1 in the files) it can't be printed out in the config.json file that my Configurator generates. Which generates a fault in my made config.json.
Some of those characters with limitations in windows are <, >, | (pipe) and !. 
 
My question to the maker(s) of the config.json examples.
Can you remove the ! in your files and not to use the above listed characters ?

**Comment by Gobberwart** [comment]
What do you mean there's a limitation in windows preventing printing "special" characters? In what way does this limitation exist?
