### ISSUE TITLE
pip2 install -r requirements.txt - The plan is to install the git repository

### ISSUE THREAD

**Issue by LoadCroc** [PokemonGoF/PokemonGo-Bot#4550]
xxxxxxx@Connected1 MINGW64 /c/Program Files (x86)/pokemon/xxxxxx (master)
$ pip2 install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): numpy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): networkx==1.11 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Obtaining pgoapi from git+https://github.com/joelgreen/pgoapi.git/@b2927c5940a8d0febd41f006921d1c093542ddf8#egg=pgoapi (from -r requirements.txt (line 3))
c:\python27\lib\distutils\__init__.py:14: UserWarning: The virtualenv distutils package at %s appears to be in the same location as the system distutils?
  "The virtualenv distutils package at %s appears to be in the same location as the system distutils?")
  git clone in c:\python27\src\pgoapi exists with URL https://github.com/keyphact/pgoapi.git
  The plan is to install the git repository https://github.com/joelgreen/pgoapi.git/

 just updated to the main, after afew days. 
git bash hangs on   The plan is to install the git repository https://github.com/joelgreen/pgoapi.git/
any1 know how to install it  - didn't work ;( $ pip2 install -r requirements.txt

**Comment by BriceSD** [comment]
Delete  ```c:\python27\src\pgoapi``` and try again.
