### ISSUE TITLE
Wrong level_stats calculation

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#4553]
### Expected Behavior
at any level, level_stats should show (like the app):
XP earned at the current level / XP to pass next level

### Actual Behavior
in fact, level_apps shows (XP previous level + XP earned at the current level) / (XP previous level + XP to pass next level)
Ex: Level 16 is 20.000 and level 17 also, so when it starts, it shows 50% where it should show 0%
Level 16 (20,095 / 40,000, 50%)

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/XzFy46Tv

### Output when issue occurred
2016-08-22 14:57:34,214 [UpdateLiveStats] [INFO] [log_stats] XXX | Uptime : 0:19:01 | Earned 2,200 Stardust | +4,500 XP | 14,200 XP/h | Visited 15 stops | Level 16 (20,095 / 40,000, **50%**)

### Other Information
OS: OSX Capitan
Branch: dev
Git Commit: 4f2e976764242a69e4ed7551ceae805d19f3a55c
Python Version: Python 2.7.12

**Comment by Gurzeh** [comment]
The code uses prev_level_xp, but it should use the current_level_xp
For example, if player is at level 11, which is 55,000 reaching level 12 which is 65,000
it should use (experience - 55,000) / (65,000 - 55,000)
where in fact it uses level 9 value 45,000 and calculates (experience - 45,000) / (65,000 - 45,000)

**Comment by mjmadsen** [comment]
Sorry, I do not. We could easily hardcore those values - I don't expect them to change much.

**Comment by Gurzeh** [comment]
@mjmadsen Yes, I'm doing it. Will provide a pull request

**Comment by mjmadsen** [comment]
Merged! If there is a problem with the merge. please create a new issue.
