### ISSUE TITLE
were is the app in the files after downloading

### ISSUE THREAD

**Issue by Enviouse** [PokemonGoF/PokemonGo-Bot#4554]
<!--
i extracted them go through files no app to run just files needed help

**Comment by DDaroc** [comment]
Did you read the installation documents?

What OS are you on? There's no app except if you use this software:
https://github.com/PokemonGoF/PokemonGo-Bot-Desktop

**Comment by mjmadsen** [comment]
We haven't heard from you for a while. Please reopen if you need further help.
