### ISSUE TITLE
Treat as VIP missing Pokemon in Pokedex

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#4559]
### Short Description
Treat all missing (in Pokedex) Pokemon as VIP (or secure catch) ?

### Possible solution
Obvious: update config, but a programmatic solution would be more elegant

### How it would help others
For those who want to fill their Pokedex (and others)

**Comment by mjmadsen** [comment]
I like the idea. We could probably add something to append those missing from our dex (which we already fetch) to the VIP list. Shouldn't be TOO hard.
