### ISSUE TITLE
[Feature Request] Options to recycle 2.0 and 5.0km eggs

### ISSUE THREAD

**Issue by etiennebechara** [PokemonGoF/PokemonGo-Bot#4573]
It would be interesting to have configurations under incubate eggs cell worker that allow us to recycle 2km and 5km eggs in inventory.

These would allow people who only want to incubate 10km eggs an increased chance to have one when the previous hatch, since they are more rare to find and the 9 spots we have are usually spammed by the 2km ones.

**Comment by BriceSD** [comment]
Last time I checked this wasn’t feasible. You can’t discard an egg.

**Comment by etiennebechara** [comment]
That's right... thanks
