### ISSUE TITLE
Every bot reach 27 lvl get ban

### ISSUE THREAD

**Issue by takenek** [PokemonGoF/PokemonGo-Bot#4576]
Hello,
I know this is not issue but mayby help developers - looks like Nantic find a way how to find a bots - mayby something need to click on 27 lvl? or mayby special windows show i have no ideas... i saw every my bot reach lvl 27 get a ban anyone saw it ?
I got almost 10 bots and every bot who reach 27 lvl get a ban... other working with no problem till this lvl.

Best Regards

**Comment by GlennSmeulders** [comment]
I experienced the same thing today

**Comment by ONslaughTT** [comment]
Its not a permanent ban, its something like a softban punishment for playing too much, i have seen people get this kind of ban for playing too much, right now, i have an old pokemon account that was permanent terminated, cant log into it, and another one that I can log into but it has some sort of loong softban, i got it yesterday after some time catching pokemons in lvl 27

**Comment by geosdc19** [comment]
Add your findings to this issue thread (my account was 25 or 26 and just got banned):
https://github.com/PokemonGoF/PokemonGo-Bot/issues/4114

**Comment by ONslaughTT** [comment]
Right now we just have to wait and see what happens.

**Comment by imvikash00** [comment]
Probably they are just checking for fast one can reach level 27.

**Comment by kingkai808** [comment]
youre leveling up too fast. reduce settings.

**Comment by GlennSmeulders** [comment]
@kingkai808 I doubt that, the average exp/hr is around 15k

**Comment by maxprzemo** [comment]
How many days of training bot to 27 lvl

**Comment by Sztucznooki** [comment]
had 26 lvl and got perm ban with mail from niantic

**Comment by ONslaughTT** [comment]
Started playing in day 16 of this month (August), day 16, played from 13:28 to 00:21, day 17 played from 8:40 to 23:45, day 18, 16:48 to 01:56, day 19 11:48 to 21:48, day 20 13:33 to 01:01, day 21, 16:09 to 01:51(got soft ban), day 22(today), tried to run the bot at 15:28, softban still persists, more than 12 hours already, still can log into account.

**Comment by avexus** [comment]
I think it's not how much you run everyday, or how humanized the behavior. It's in the bot that gives some clue away.

**Comment by avexus** [comment]
@geosdc19 agreed. let's keep everything centralized in #4114. Can someone close this please?

**Comment by MZorzy** [comment]
Start new bot 4 day ago. Bot level 0-10 then 10-12 with phone. Banned 3 ours ago.
No mail

**Comment by RedViper9** [comment]
Agreed. This discussion belongs on Perm Ban Test Results #4114.

**Comment by seehuily** [comment]
They could also use IP detection. e.g.
1). IP address belongs to city XXX, but you actual in another city according to your cord.
2). more then 2 players in the same LAN with same public IP, one is in City A, the other is in City B. 

VPN could possibly be used but you could also become a suspect. 


I had 3 active accounts, I used them very carefully but still got banned. they all got banned when they reached above level 20.

**Comment by ONslaughTT** [comment]
Got permanent banned today, i never ran two bots at same time, always used only one account to play
