### ISSUE TITLE
-m -iv not working, Only catching Pokemon and not spinning Poke stops, Transfers all pokemons regardless of CP

### ISSUE THREAD

**Issue by gamehauz** [PokemonGoF/PokemonGo-Bot#458]
1. commands -m and -iv are not recognized

2. I can only do one thing at a time, it's either I spin poke stops or I catch pokemons.

3. It also transfers everything regardless of what I put on -c

**Comment by doctor-ew** [comment]
try prepending like: --mode 'all' -iv 0 -c 200

**Comment by ginetrix** [comment]
@doctor-ew I'm 99% sure he is on master branch

**Comment by gamehauz** [comment]
............ -73.972816" --mode 'all' --walk 4

and the response would be below

usage: pokecli.py [-h] -a AUTH_SERVICE -u USERNAME -p PASSWORD -l LOCATION
                  [-s] [-v] [-w WALK] [-c CP] [-k GMAPKEY]
                  [--maxsteps MAXSTEPS] [-d] [-t] [-tl TRANSFER_LIST]
pokecli.py: error: unrecognized arguments: --mode all

Sorry, I'm a noob. Did someone remove it from the new version? -s works, but I can only spin pokestops.

**Comment by ginetrix** [comment]
You should try to switch to the dev branch by typing: "git checkout -b dev origin/dev"

**Comment by gamehauz** [comment]
I'll try it out later, thanks ginetrix

**Comment by gamehauz** [comment]
I switched to the dev branch but there's a weird error.

No such file or directory: 'data/pokemon.json'

Even though pokemon.json is in there.

**Comment by doctor-ew** [comment]
@gamehauz -- I ended up removing the repo and re-cloning 

git clone -b dev git@github.com:PokemonGoF/PokemonGo-Bot.git

**Comment by gamehauz** [comment]
Removed the repo and re-cloned, it's still has the (No such file or directory: 'data/pokemon.json') error. I wonder why, thanks for the help anyway doctor-ew.

**Comment by gamehauz** [comment]
Oops my mistake, it's working now, thanks everyone.
