### ISSUE TITLE
Emulate phone battery

### ISSUE THREAD

**Issue by jaimerson** [PokemonGoF/PokemonGo-Bot#4583]
### Short Description
Bot could simulate battery depletion as it walks around and either take a break when it ends or "find a place to charge" and chill there, evolving pokémon or something until charged enough to continue. 

### Possible solution
Use the existing random breaks feature to take the breaks, and add config options for minimum battery (which should be random) needed to leave on a journey. One could also config a home location to go back to and charge. The break time would be calculated based on the current position and speed.

### How it would help others
It would make the bot behavior more human-like, thus making it harder to detect as a bot (considering behavior analysis is the only way to detect)

**Comment by mustii82** [comment]
Great Idea but is this important for Bot Detection ?

**Comment by jaimerson** [comment]
@mustii82 well, how could we know what methods are used? At the very least it would make it more belieavable as a human

**Comment by sediyama** [comment]
I think it would be more human like if the bot at least wait for a while before starting moving and from time to time, stop moving for a certain period of time.

**Comment by Nik0lashka** [comment]
@sediyama #4202

**Comment by sediyama** [comment]
@nik0lashka the feature that you pointed is not the same. What I am suggesting is to stay put, at the same place, logged in, searching for Pokemons and spining Forts. The feature at #4202, the bot logout.
Everybody playing stops for a while and keeps the phone running, it is what I am trying to suggest.

**Comment by mjmadsen** [comment]
Does #4672 meet your request?

**Comment by jaimerson** [comment]
@mjmadsen I guess so. Is there a config option to sometimes have an alive pause right after the random break? This would be perfect to simulate charging

**Comment by mjmadsen** [comment]
Not quite, the different sleepers are completely independent.
