### ISSUE TITLE
WebSocket Events

### ISSUE THREAD

**Issue by oralunal** [PokemonGoF/PokemonGo-Bot#4586]
I configured the webUI socket.io. Now I have a trouble with the methods. For example
```
	socket_io.on('item_discarded:username', function (data) {
		console.log(data['data']['msg']);
	});
```
With this command I can get discarded items. 
```
	socket_io.on('moving_to_fort:username', function (data) {
		console.log(data['data']['msg']);
	});
```
With this command I can get moving fort. Problem is should I do these actions for every event individualy? Instead of moving_to_fort, item_discarded, spun_pokestop just use "event:username" and get all data?

Is it possible?

**Comment by oralunal** [comment]
Why closed?

**Comment by k4n30** [comment]
Issues are not to be used for support - that's what slack server is for and is called out in the REAME and the issue template

**Comment by oralunal** [comment]
Okay, you are right but I want to develop this app btw I need some technical information. You know the documentation is very poor. Slack server isn't enough for development. It's hard to find answers. Or there should be something more effective.

Am I wrong? Anyway, thank you.

**Comment by k4n30** [comment]
There is a dedicated dev channel, which is monitored a lot better than random issues on here. The devs don't look at the issues, unless they are brought up in discussion in the dev channel.


Going to lock conversation as I think it has been discussed enough
