### ISSUE TITLE
como eu faço o download do bot ?

### ISSUE THREAD

**Issue by gabsanti** [PokemonGoF/PokemonGo-Bot#4593]
### Other Information
OS: 
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by SGColdSun** [comment]
You've failed to fill-out any of the template for assistance. Don't expect help.
As far as tutorials or how to install the bot, follow the readme and documents. The issue tracker isn't the place for that.
