### ISSUE TITLE
Great Balls not getting used

### ISSUE THREAD

**Issue by h2xtreme** [PokemonGoF/PokemonGo-Bot#46]
I only had great balls in my items and I couldn't catch any pokemon. After I grab some regular pokeballs from the pokestops I was able to catch pokemons again.

**Comment by 3mph4515** [comment]
Yes, have the same issue. Will be great to use all kinds of pocket balls

**Comment by necrozis** [comment]
@h2xtreme which condition to use Great Balls?

**Comment by 3mph4515** [comment]
@necrozis, CP > DEFINED_VALUE || defaut_balls_count == 0

**Comment by CtrlAltDefeat94** [comment]
I think this can be closed as -only- great balls are being used atm.
