### ISSUE TITLE
Reset avatar (for accounts created without one)

### ISSUE THREAD

**Issue by oNIenSis** [PokemonGoF/PokemonGo-Bot#4600]
### Short Description
Bot accounts created using "complete tutorial" didn't have an avatar selected, so it was blank in game and cannot be changed.  Apparently this was fixed for the tutorial in #4445.  Can it also be fixed for the accounts that have completed the tutorial and created without an avatar?

### Possible solution
It would be good now to reset the avatar for accounts that have already completed the tutorial.  Not sure how this would be called up by the API, I guess it would require somehow using the "customize" option in the UI.

### How it would help others
Be able to have an avatar in game for bots created after this feature was introduced and before the pull last night.

**Comment by k4n30** [comment]
@net8q sorry to ping you again, but is this possible in it's current form? Or does it need to be added?

**Comment by net8q** [comment]
Dirty way would be to just add a self._set_avatar() in https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/complete_tutorial.py#L48 then run the bot once, then remove the line.

Migrating the old accounts would need to get the avatar and check what it should look like, unfortunately I'm far from my dev desktop. I hope we can make a difference between no avatar and default avatar where everything is set to 0

**Comment by oNIenSis** [comment]
That temp fix worked fine.

**Comment by mjmadsen** [comment]
@oNIenSis @net8q Since there was only a 5 day period before we added set_avatar, do we think this is still necessary? There probably weren't too many fresh bots started during the period - at least maybe not enough to necessitate the leg work involved.

**Comment by sediyama** [comment]
I am having trouble using the self._set_avatar(), how should I edit the file?

**Comment by acurioustale** [comment]
I still have the same problem for some accounts, but the temp fix didn't work for me.

**Comment by Faralax** [comment]
Any news on this? Temp fix did nothing and the whole profile is bugged if you dont select an avatar

**Comment by supergithubo** [comment]
![img_20160916_025402](https://cloud.githubusercontent.com/assets/8290481/18605788/cf048640-7cce-11e6-891b-cac169df8945.JPG)
![screenshot_2016-09-14-14-37-49](https://cloud.githubusercontent.com/assets/8290481/18605790/db69ae10-7cce-11e6-8475-240c72c03117.png)

@Faralax @acurioustale is the issue you have similar to mine (screenshots). The avatar is not showing up and the profile actions are buggy and can't even exit the profile screen. I just login my account from app after botting since the first implementation of complete tutorial

**Comment by acurioustale** [comment]
@supergithubo Yep!

**Comment by k4n30** [comment]
This still an issue? or have all the bugged accounts died out?

**Comment by oNIenSis** [comment]
close it I reckon - surely all died by now.  Don't know why the temporary fix didn't help others, fixed my account ok.
