### ISSUE TITLE
META Not Catching Pokemon

### ISSUE THREAD

**Issue by mjmadsen** [PokemonGoF/PokemonGo-Bot#4601]
We have lots of folks creating issues about the bot not seeing any pokemon and thus not catching any or a significant fewer amount of pokemon. I've looked at all recent changes and the current state of the pokemon catchers and see nothing that would somehow cause this effect. My thought is we hit some sort of trigger on the server side and they begin reducing our spawns. I'm willing to bet that this happens in spurts and that the spawn reduction increases over time. 

Excerpt of a resent loss: http://pastebin.com/juByyqsG

EDIT: The log is long. Gist: Catch/see very few pokemon for hours and ended up with ban message. 

### Potential alterations:
If we "dry up" on pokemon for a while, take a break and/or log out and back in. If you played the first couple of weeks, you'll recall this being a rather common event. This would better mimic a human. If we don't see any pokemon for a while, we log out for a while and try again a bit later.

**Comment by crvfts** [comment]
People I have talked to said they getting the "driving" notification when they're jogging. I've lowered my walk_max to 4.01 and I'm seeing the volume I expect.

**Comment by mjmadsen** [comment]
@crvfts From what I have heard, responding to the message does not send a response to the server.

**Comment by crvfts** [comment]
I wonder what was causing it on my end then. weird

**Comment by k4n30** [comment]
You should consider setting up [PokemonGo-Map](https://github.com/PokemonGoMap/PokemonGo-Map) and setting it to scan on the same area as the bot is in and seeing if it misses any that are shown on the map. A couple of tests with increasing the walk speed should be able to determine the sweet spot. You need to remember that they "apparently" changed the app scan to every 10 seconds so it's possible that going above a certain speed will cause the 9.9999 sec interval between scans to miss any pokemon if your bot is going too fast - No credible source to back this up though

**Comment by mjmadsen** [comment]
@crvfts To which were you referring. Do you have logs?

**Comment by crvfts** [comment]
@mjmadsen after reading what you added to your post, as well as getting banned last night, my guess is i was in some form of softban state before i got perma'd. started a new account, walk_max is back around 4.16 and i'm catching like normal. what i was thinking before was i was traveling too fast and missing spawns. i never thought it was a bug in the bot. bot works great for me, i was simply trying to think in terms of what the 'app' would be doing etc.

**Comment by mjmadsen** [comment]
Closing #4601 as this hasn't been referenced in nearly two weeks.
