### ISSUE TITLE
Strange spam on screen on newlatest dev version.

### ISSUE THREAD

**Issue by takenek** [PokemonGoF/PokemonGo-Bot#4602]
Before you create an Issue, please check the following:

1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.
YES

2. Have you [searched our issue tracker](https://github.com/PokemonGoF/PokemonGo-Bot/issues?q=is%3Aissue+sort%3Aupdated-desc) to see if the issue already exists? If so, comment on that issue instead rather than creating a new issue.
YES

3. Are you running on the `master` branch? We work on the `dev` branch and then add that functionality to `master` when it is stable. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.
dev

4. All Issue sections MUST be completed to help us determine the actual problem and find its cause
I know
### Expected Behavior
No spam on screen

### Actual Behavior
Spam on screen

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
I think this is not need it.

### Output when issue occurred
2016-08-23 07:45:36,925 [PokemonGoBot] [INFO] [login_started] Login procedure started.
pgomapcatch/all/catchable/74 0 34.0118999401,-118.496021687,5132752274995820157
pgomapcatch/all/catchable/104 0 34.0118888695,-118.495747987,8408328944486764381
pgomapcatch/all/catchable/17 0 37.8060337161,-122.431904656,1253898590250416861
pgomapcatch/all/catchable/19 0 37.8062315839,-122.431019863,14493214305910525
pgomapcatch/all/catchable/19 0 37.8062442659,-122.43146226,7038093087127419933
pgomapcatch/all/catchable/20 0 37.8064076317,-122.430931383,18421731353777692429
pgomapcatch/all/catchable/16 0 37.8060010806,-122.431285302,7627845837456767773
2016-08-23 07:45:38,375 [PokemonGoBot] [INFO] [login_successful] Login successful.
2016-08-23 07:45:38,375 [PokemonGoBot] [INFO] Found encrypt.so! Platform: linux2 encrypt.so directory: /home/login/PokemonGo-Bot
2016-08-23 07:45:38,375 [PokemonGoBot] [INFO]
pgomapcatch/all/catchable/81 0 40.7585141896,-73.9703763988,6183672017631188909
2016-08-23 07:45:39,128 [PokemonGoBot] [INFO] Level: 1 (Next Level: 400 XP) (Total: 600 XP)
pgomapcatch/all/catchable/17 0 37.8060337161,-122.431904656,1253898590250416861
pgomapcatch/all/catchable/19 0 37.8062315839,-122.431019863,14493214305910525
pgomapcatch/all/catchable/19 0 37.8062442659,-122.43146226,7038093087127419933
pgomapcatch/all/catchable/20 0 37.8064076317,-122.430931383,18421731353777692429
pgomapcatch/all/catchable/16 0 37.8060010806,-122.431285302,7627845837456767773
pgomapcatch/all/catchable/54 0 25.1364616874,121.506711165,16163643224141897629
pgomapcatch/all/catchable/54 0 25.1367561371,121.505461956,15220322102140149069
pgomapcatch/all/catchable/72 0 -33.8586657365,151.210198631,15187119875658492173
pgomapcatch/all/catchable/17 0 37.8060337161,-122.431904656,1253898590250416861

### Steps to Reproduce
Run a bot on dev branch

### Other Information
OS: Debian SiD
Branch:  dev
Git Commit: 9147815716892adf74920a9fd4e110f381b84f14
Python Version: Python 2.7.9

Best Regards
TaKeN

**Comment by acurioustale** [comment]
See #4596.

This is a new feature to crowdsource data. Change enable_social to false in your config.json to disable it.

**Comment by takenek** [comment]
So mayby disable enable_social as default? 
I update everyday configs and whole bot and checking :-)

**Comment by Nik0lashka** [comment]
Well, we just need to remove such intensive logging, cause the more botters contribute into spawn data, the better it is for all of us.

**Comment by MasterCATZ** [comment]
its good spam , but definitely needs an option to enable / disable being displayed

**Comment by faegan** [comment]
@MasterCATZ it already has that option in config.json -> enable_social = false

**Comment by HecticSeptic** [comment]
@faegan @MasterCATZ it appears disabling enable_social does not only hide the spam, it stops contributing to the list of pokemon spawns we're crowdsourcing. We need to enable the crowdsource while still hiding the logging (which goes away if you [successfully] run the server in map-chat, but since that isn't on by default most users will just see excessive logging).

**Comment by Nik0lashka** [comment]
@BreezeRo check this issue please

**Comment by Gobberwart** [comment]
Seems fixed in latest dev. Best guess is it was there for debugging and didn't get removed before merging.

**Comment by mjmadsen** [comment]
Yes, set social to disabled and this won't appear.
