### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by takenek** [PokemonGoF/PokemonGo-Bot#4604]
1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.
YES

2. Have you [searched our issue tracker](https://github.com/PokemonGoF/PokemonGo-Bot/issues?q=is%3Aissue+sort%3Aupdated-desc) to see if the issue already exists? If so, comment on that issue instead rather than creating a new issue.
YES

3. Are you running on the `master` branch? We work on the `dev` branch and then add that functionality to `master` when it is stable. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.
DEV

### Expected Behavior
No errors or normal info about problem with connection? Or mayby this is a way how to Nantic detects a bot?

### Actual Behavior
Running bot and after few minutes get strange info:
[Errno 104] Connection reset by peer

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
Don`t need it.

### Output when issue occurred
2016-08-23 07:14:14,268 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Fasada Teatru Wielkiego - 0.05km
[Errno 104] Connection reset by peer
2016-08-23 07:14:16,029 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Fasada Teatru Wielkiego - 0.05km

### Steps to Reproduce
Run a bot

### Other Information
OS: Debian SiD
Branch:  dev
Git Commit: 9147815716892adf74920a9fd4e110f381b84f14
Python Version: Python 2.7.9

**Comment by mjmadsen** [comment]
Think that might be output from the API.

**Comment by takenek** [comment]
Possible you got right but 1 time i see this that`s why i report this - better if dev take a look on this.

**Comment by k4n30** [comment]
Don`t need it.

**Comment by MZorzy** [comment]
[2016-09-06 14:24:01] [MainThread] [MoveToFort] [INFO] ...
[2016-09-06 14:24:06] [MainThread] [  SpinFort] [INFO] Spun...
[Errno 104] Connection reset by peer
[2016-09-06 14:24:10] [MainThread] [MoveToFort] [INFO] Moving...
[Errno 104] Connection reset by peer
[2016-09-06 14:24:15] [MainThread] [ShowBestPokemon] [INFO]

config.json.map.example with modded altitude only & no pokemap run

**Comment by sohje** [comment]
@MZorzy Do you have social enabled?

**Comment by MZorzy** [comment]
yes. as map.example

**Comment by sohje** [comment]
check #5232 This is issue with social_handler.py

**Comment by k4n30** [comment]
Please create a new issue, dont comment on a 14 day old one
