### ISSUE TITLE
Can't see my character after botting without customized clothing

### ISSUE THREAD

**Issue by armmydev** [PokemonGoF/PokemonGo-Bot#4609]
Reproduce steps
1.Signup with Pokemon club account type
2.Botting (started at level 1 without customization clothing)
3.Open real app after level 20
Issue is cannot see my character and got white screen after select customize menu

![s__7192583](https://cloud.githubusercontent.com/assets/6060897/17887764/1e766562-6952-11e6-9b66-cc41548724f6.jpg)
![s__7192584](https://cloud.githubusercontent.com/assets/6060897/17887765/1e77cb78-6952-11e6-92f8-b005e5d83fa1.jpg)
![s__7192585](https://cloud.githubusercontent.com/assets/6060897/17887766/1e781718-6952-11e6-87a0-85f2f9c6b3ee.jpg)

**Comment by boom-season** [comment]
I got it too. 

There should be a way to customize character after botting.

I think there should be a feature for customizing characters.
