### ISSUE TITLE
Named locations in config files

### ISSUE THREAD

**Issue by lntn** [PokemonGoF/PokemonGo-Bot#4612]
### Short Description
We can predefined a number of named locations in the config file (or in a separated file), then use their name for "location" config parameter.

### Possible solution
A few line of code will do the trick

### How it would help others
The location will make sense to the user and allow us to quickly switch between our favourite locations. Even though copy & paste from a text file may do the trick but it's still worth to implement for the sake of user friendliness.

**Comment by MZorzy** [comment]
Need to chamge alltitude min/max for every location too
