### ISSUE TITLE
Migrate web interface to OpenPoGoUI

### ISSUE THREAD

**Issue by lntn** [PokemonGoF/PokemonGo-Bot#4613]
### Short Description
OpenPoGoWeb is deprecated 

### Possible solution
Output events like OpenPoGoBot

### How it would help others
Better UI with active support & development.

**Comment by OursDesCavernes** [comment]
How about moving to OpenPoGoBot ?

**Comment by k4n30** [comment]
Web interface is being worked on, we will not be moving to OpenPoGoWeb

**Comment by TridentNooch** [comment]
k4n30

An update regarding web ui?
