### ISSUE TITLE
Exchanging pokemons bug

### ISSUE THREAD

**Issue by TheGoldenXY** [PokemonGoF/PokemonGo-Bot#462]
### Expected Behavior
When I set the `-c 200 -iv 0.4` arg it should ONLY transfer 0-200 cp pokemons. It should keep ALL pokemons with cp higher than 200.

### Actual Behavior
If the bot finds pokemons with cp below 200, it exchanges them for candy.
If the bot finds a pokemon with cp above 200, it exchanges the pokemon for candy.
http://prntscr.com/bwkcsc
### Steps to Reproduce
Use this command:
`python pokecli.py -c 200 -iv 0.4 -w 3 -a google -u <usernameGoesHere> -p <passwordGoesHere> -l "40.785091, -73.968285" -m all`

### Other Information
OS: Ubuntu 14.04
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
a5cf48976651adcbfe02d29f129f0f625ba5d1ec

**Comment by dominikue** [comment]
Use -iv 0 to keep all pokemons above 200 CP.

**Comment by TheGoldenXY** [comment]
Thanks
