### ISSUE TITLE
Websocket? yes no?

### ISSUE THREAD

**Issue by tuudik** [PokemonGoF/PokemonGo-Bot#4622]
Hi!
I found the following application:
http://openpogoui.nicontoso.eu/
which I assume can be used to check what the bot is doing.

I have set the websocket to true in configuration file, but I can see that websocket is not created.
Checked from netstat -nltp and there's no bot.

Is websocket working or not?

**Comment by Cetino** [comment]
please look first on the already opend issues before you open a new one.
Look at https://github.com/PokemonGoF/PokemonGo-Bot/issues/4620 and https://github.com/PokemonGoF/PokemonGo-Bot/issues/3925
