### ISSUE TITLE
Send ip of the location playing from

### ISSUE THREAD

**Issue by krishven** [PokemonGoF/PokemonGo-Bot#4630]
### Short Description
One of the most probable reasons for ban might be because the ip stays static while the location keeps changing.

### Possible solution
Send a fake ip depending on the location

### How it would help others
Avoid a perma ban

**Comment by ciol06** [comment]
I see a --proxy argument in /src/pgoapi/pokecli.py but not in /pokecli.py
Could it be re-added to the current pokecli.py? Then use of a proxy could be possible :)

**Comment by krishven** [comment]
@ciol06 yes but will it send a new ip depending on location every few minutes or just a single proxy ip throughout?

**Comment by ciol06** [comment]
a single ip, sure... but if you stay in the same location, no problem?

**Comment by ntcong** [comment]
I don't think IP is a problem. ISPs NAT users all the time, and some people like me use always-on VPN on my phone.

**Comment by mjmadsen** [comment]
#3574 for adding a proxy.

I think that is about as close as we will get to this. As long as you're not moving miles away, there wouldn't be much need to keep changing it. 

https://www.quora.com/Does-my-mobile-phone-have-a-fixed-IP-address-or-does-it-change-frequently
