### ISSUE TITLE
Choose which egg to incubate and which incubator. 

### ISSUE THREAD

**Issue by sediyama** [PokemonGoF/PokemonGo-Bot#4634]
### Expected Behavior
Choose which egg to incubate and which incubator. I would like to incubate only 2km and 5km eggs, using only the infinite incubator in the first levels. At level 20 or so, I would start using all my incubators in 10km eggs. Because the pokemon hatched are directly related with the player level. 
How I would use it:
Incubate 2 Km and 5 Km eggs with the infinite incubator, incubate than 10 Km, only if no 2km or 5km egg present.
At level 20: Start incubating all eggs with all incubators, including the 3 use incubators. 

### How it would help others
Better Pokemon at higher levels.

**Comment by SGColdSun** [comment]
This has already been added. Perhaps you're using an outdated config file.

**Comment by sediyama** [comment]
Thank you @SGColdSun! I will check it!
