### ISSUE TITLE
can someone help me install. 

### ISSUE THREAD

**Issue by l3w123** [PokemonGoF/PokemonGo-Bot#4638]
I have downloaded both docker and python and now I am lost trying to follow the guide, if anyone is willing help it would be much appreciated.
-update 

Ive ran the install and setup files, also created a config.json file but when trying to click run it says

bash: bin/activate: No such file or directory
bash: python: command not found

**Comment by BreezeRo** [comment]
join slack chat https://pokemongo-bot.slack.com

**Comment by l3w123** [comment]
Thanks Breeze, I have joined there and asked but no ones replied quite yet. I just need someone to talk me through the installation and the setup to see where I'm going wrong as im new to all this
