### ISSUE TITLE
bot doesnt go to the nearest pokestop

### ISSUE THREAD

**Issue by anonymouslulz22** [PokemonGoF/PokemonGo-Bot#464]
### Expected Behavior
ok! so the bot is pretty good and it should go to the nearest pokestop

### Actual Behavior
it goes to the most far away pokestop

### Other Information
OS: kali
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by anonymouslulz22** [comment]
when will it get fixed?

**Comment by dominikue** [comment]
#141 #186 #219
