### ISSUE TITLE
FollowCluster Needs to "edge" to collect stops

### ISSUE THREAD

**Issue by Acuchillar** [PokemonGoF/PokemonGo-Bot#4643]
### Short Description
When using FollowCluster, it should know when stops are available to be spun and jitter near them. Using FollowCluster, it will just burn balls and if the pokestops are "just" out of reach it will only spin one or two forts while it is around 5 or more, giving a large net loss.

### Possible solution
When timeouts occur, walk to or "edge" to other pokestops which are calculated as "in range".  When out of balls, make the collection circle larger (oh god no traveling salesman).

### How it would help others
Part of the detection is likely based on Km walked a day, so the ability to efficiently use lured pokestops and other places that people are likely to "hang out" is an important feature to have.  As you are not able to use any other "Follow" config, this will need to handle the ball collection as well.

**Comment by mjmadsen** [comment]
#4430

**Comment by Acuchillar** [comment]
... I promise I'm not a COMPLETE moron, just a small one.  *sigh*
