### ISSUE TITLE
Web actions are not working

### ISSUE THREAD

**Issue by lntn** [PokemonGoF/PokemonGo-Bot#4646]
### Expected Behavior
Action on web UI such as Release/Evolve are very handful and should be working since they're added there.

### Actual Behavior
Nothing happens when hitting Release or Evolve

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
Not relevant

### Output when issue occurred
Nothing happens

### Steps to Reproduce
1. Enable web actions by editing userdata.js -> actionsEnabled: true
2. Reload the web interface, restart web server if necessary

### Other Information
Branch: 
master
Git Commit: 
f448a7728e575c1016328c02ab39e8493e983119
Python Version: 
2.7.10

**Comment by mjmadsen** [comment]
https://github.com/PokemonGoF/PokemonGo-Web
