### ISSUE TITLE
[FEATURE REQUEST] Split config file

### ISSUE THREAD

**Issue by geminiyellow** [PokemonGoF/PokemonGo-Bot#4648]
### Expected Behavior

modular bot's feature, so we can split config file to several separate files.

----
### Actual Behavior

The config file is now very long, and I do not know the specific role of each part.

----
### Your FULL config.json (remove your username, password, gmapkey and any other private info)

[config.json.pokemon.example](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/configs/config.json.pokemon.example)

----
### Output when issue occurred

*empty*

----
### Steps to Reproduce

*empty*

----
### Other Information
OS: **macOS beta**
 
Branch: **dev**
 
Git Commit: 
 
Python Version: **Python 2.7.10**
 
Any other relevant files/configs (eg: path files) 

### Short Description

----
### Possible solution

----

**Comment by k4n30** [comment]
#3506
