### ISSUE TITLE
BOT crash after starting (latest version - using social feature)

### ISSUE THREAD

**Issue by krishven** [PokemonGoF/PokemonGo-Bot#4654]
### Expected Behavior
Bot works normally

### Actual Behavior
Bot crashes

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
{
"auth_service": "",
"username": "",
"password": "",
"location": "",
"gmapkey": "",
"encrypt_location": "",
"websocket_server": false,
"heartbeat_threshold": 10,
"tasks": [
{
"type": "HandleSoftBan"
},
{
"type": "SleepSchedule",
"config": {
"enabled": false,
"time": "22:54",
"duration":"7:46",
"time_random_offset": "00:24",
"duration_random_offset": "00:43"
}
},
{
"type": "CompleteTutorial",
"config": {
"enabled": false,
"// set a name": "",
"nickname": ""
}
},
{
"type": "CollectLevelUpReward"
},
{
"type": "IncubateEggs",
"config": {
"longer_eggs_first": true,
"min_interval": 120
}
},
{
"type": "UpdateLiveStats",
"config": {
"enabled": false,
"min_interval": 10,
"stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
"terminal_log": true,
"terminal_title": true
}
},
{
"type": "UpdateLiveInventory",
"config": {
"enabled": false,
"min_interval": 120,
"show_all_multiple_lines": false,
"items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
}
},
{
"type": "TransferPokemon",
"config": {
"min_free_slot": 5,
"transfer_wait_min": 1,
"transfer_wait_max": 4
}
},
{
"type": "NicknamePokemon",
"config": {
"enabled": false,
"nickname_above_iv": 0.9,
"nickname_template": "{iv_pct}_{iv_ads}"
}
},
{
"type": "EvolvePokemon",
"config": {
"evolve_all": "none",
"first_evolve_by": "cp",
"evolve_above_cp": 500,
"evolve_above_iv": 0.8,
"logic": "or",
"evolve_speed": 20,
"use_lucky_egg": false
}
},
{
"type": "RecycleItems",
"config": {
"min_empty_space": 10,
"max_balls_keep": 150,
"max_potions_keep": 100,
"max_berries_keep": 30,
"max_revives_keep": 50,
"item_filter": {
"Pokeball": { "keep" : 40 },
"Greatball": { "keep" : 40 },
"Ultraball": { "keep" : 40 },
"Potion": { "keep" : 30 },
"Super Potion": { "keep" : 30 },
"Hyper Potion": { "keep" : 40 },
"Max Potion": { "keep" : 40 },
"Revive": { "keep" : 30 },
"Razz Berry": { "keep" : 30 }
},
"recycle_wait_min": 1,
"recycle_wait_max": 4
}
},
{
"type": "CatchPokemon",
"config": {
"catch_visible_pokemon": true,
"catch_lured_pokemon": true,
"min_ultraball_to_keep": 5,
"berry_threshold": 0.35,
"vip_berry_threshold": 0.9,
"catch_throw_parameters": {
"excellent_rate": 0.1,
"great_rate": 0.5,
"nice_rate": 0.3,
"normal_rate": 0.1,
"spin_success_rate" : 0.6
},
"catch_simulation": {
"flee_count": 3,
"flee_duration": 2,
"catch_wait_min": 2,
"catch_wait_max": 6,
"berry_wait_min": 2,
"berry_wait_max": 3,
"changeball_wait_min": 2,
"changeball_wait_max": 3
}
}
},
{
"type": "SpinFort",
"config": {
"spin_wait_min": 3,
"spin_wait_max": 5
}
}
],
"map_object_cache_time": 5,
"forts": {
"avoid_circles": true,
"max_circle_size": 50,
"cache_recent_forts": true
},
"pokemon_bag": {
"// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
"show_at_start": true,
"// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
"show_count": false,
"// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
"show_candies": false,
"// 'pokemon_info' parameter define which info to show for each pokemon": {},
"// the available options are": {},
"// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
"pokemon_info": ["cp", "iv_pct"]
},
"walk_max": 1,
"walk_min": 1,
"alt_min": 500,
"alt_max": 1000,
"debug": false,
"test": false,
"health_record": true,
"location_cache": true,
"distance_unit": "km",
"reconnecting_timeout": 15,
"logging_color": true,
"daily_catch_limit": 800,
"catch": {
"any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or" },

  "// Pokemons with example": { "always_catch": true },
  "// Gets filtered with release parameters": {},

  "// Legendary pokemons (Goes under S-Tier)": {},
  "Lapras": { "always_catch": true },
  "Moltres": { "always_catch": true },
  "Zapdos": { "always_catch": true },
  "Articuno": { "always_catch": true },

  "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
  "Mewtwo": { "always_catch": true },
  "Dragonite": { "always_catch": true },
  "Snorlax": { "always_catch": true },
  "// Mew evolves to Mewtwo": {},
  "Mew": { "always_catch": true },
  "Arcanine": { "always_catch": true },
  "Vaporeon": { "always_catch": true },
  "Gyarados": { "always_catch": true },
  "Exeggutor": { "always_catch": true },
  "Muk": { "always_catch": true },
  "Weezing": { "always_catch": true },
  "Flareon": { "always_catch": true },

  "// Growlithe evolves to Arcanine": {},
  "Growlithe": { "always_catch": true },
  "// Dragonair evolves to Dragonite": {},
  "Dragonair": { "always_catch": true },
  "// Grimer evolves to Muk": {},
  "Grimer": { "always_catch": true },

  "// Magikarp evolves to Gyarados": {},
  "Magikarp": { "always_catch": true },
  "// Exeggcute evolves to Exeggutor": {},
  "Exeggcute": { "always_catch": true },
  "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
  "Eevee": { "always_catch": true },

  "// A-Tier pokemons": {},
  "Slowbro": { "always_catch": true },
  "Victreebel": { "always_catch": true },
  "Machamp": { "always_catch": true },
  "Poliwrath": { "always_catch": true },
  "Clefable": { "always_catch": true },
  "Nidoking": { "always_catch": true },
  "Venusaur": { "always_catch": true },
  "Charizard": { "always_catch": true },
  "Golduck": { "always_catch": true },
  "Nidoqueen": { "always_catch": true },
  "Vileplume": { "always_catch": true },
  "Blastoise": { "always_catch": true },
  "Omastar":  { "always_catch": true },
  "Aerodactyl": { "always_catch": true },
  "Golem": { "always_catch": true },
  "Wigglytuff": { "always_catch": true },
  "Dewgong": { "always_catch": true },
  "Ninetales": { "always_catch": true },
  "Magmar": { "always_catch": true },
  "Kabutops": { "always_catch": true },
  "Electabuzz": { "always_catch": true },
  "Starmie": { "always_catch": true },
  "Jolteon": { "always_catch": true },
  "Rapidash": { "always_catch": true },
  "Pinsir": { "always_catch": true },
  "Scyther": { "always_catch": true },
  "Tentacruel": { "always_catch": true },
  "Gengar": { "always_catch": true },
  "Hypno": { "always_catch": true },
  "Pidgeot": { "always_catch": true },
  "Rhydon": { "always_catch": true },
  "Seaking": { "always_catch": true },
  "Kangaskhan": { "always_catch": true }
},
"release": {
  "// Legendary pokemons (Goes under S-Tier)": {},
  "Lapras": { "release_below_cp": 1, "release_below_iv": 0.8, "logic": "and" },
  "Moltres": { "release_below_cp": 1, "release_below_iv": 0.8, "logic": "and" },
  "Zapdos": { "release_below_cp": 1, "release_below_iv": 0.8, "logic": "and" },
  "Articuno": { "release_below_cp": 1, "release_below_iv": 0.8, "logic": "and" },

  "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
  "Mewtwo": { "release_below_cp": 1, "release_below_iv": 0.8, "logic": "and"},
  "Dragonite": { "release_below_cp": 1, "release_below_iv": 0.8, "logic": "and" },
  "Snorlax": { "release_below_cp": 1, "release_below_iv": 0.8, "logic": "and" },
  "// Mew evolves to Mewtwo": {},
  "Mew": { "release_below_cp": 1, "release_below_iv": 0.8, "logic": "and" },
  "Arcanine": { "release_below_cp": 1, "release_below_iv": 0.8, "logic": "and" },
  "Vaporeon": { "release_below_cp": 1, "release_below_iv": 0.8, "logic": "and" },
  "Gyarados": { "release_below_cp": 1, "release_below_iv": 0.8, "logic": "and" },
  "Exeggutor": { "release_below_cp": 1, "release_below_iv": 0.8, "logic": "and" },
  "Muk": { "release_below_cp": 1, "release_below_iv": 0.8, "logic": "and" },
  "Weezing": { "release_below_cp": 784, "release_below_iv": 0.8, "logic": "and" },
  "Flareon": { "release_below_cp": 924, "release_below_iv": 0.8, "logic": "and" },

  "// Growlithe evolves to Arcanine": {},
  "Growlithe": { "release_below_cp": 750, "release_below_iv": 0.8, "logic": "and" },
  "// Dragonair evolves to Dragonite": {},
  "Dragonair": { "release_below_cp": 609, "release_below_iv": 0.8, "logic": "and" },
  "// Grimer evolves to Muk": {},
  "Grimer": { "release_below_cp": 448, "release_below_iv": 0.8, "logic": "and" },
  "// Magikarp evolves to Gyarados": {},
  "Magikarp": { "release_below_cp": 150, "release_below_iv": 1, "logic": "and" },
  "// Exeggcute evolves to Exeggutor": {},
  "Exeggcute": { "release_below_cp": 600, "release_below_iv": 1, "logic": "and" },
  "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
  "Eevee": { "release_below_cp": 600, "release_below_iv": 1, "logic": "and" },

  "// A-Tier pokemons": {},
  "Slowbro": { "release_below_cp": 907, "release_below_iv": 0.8, "logic": "and" },
  "Victreebel": { "release_below_cp": 883, "release_below_iv": 0.8, "logic": "and" },
  "Machamp": { "release_below_cp": 907, "release_below_iv": 0.8, "logic": "and" },
  "Poliwrath": { "release_below_cp": 876, "release_below_iv": 0.8, "logic": "and" },
  "Clefable": { "release_below_cp": 837, "release_below_iv": 0.8, "logic": "and" },
  "Nidoking": { "release_below_cp": 864, "release_below_iv": 0.8, "logic": "and" },
  "Venusaur": { "release_below_cp": 902, "release_below_iv": 0.8, "logic": "and" },
  "Charizard": { "release_below_cp": 909, "release_below_iv": 0.8, "logic": "and" },
  "Golduck": { "release_below_cp": 832, "release_below_iv": 0.8, "logic": "and" },
  "Nidoqueen": { "release_below_cp": 868, "release_below_iv": 0.8, "logic": "and" },
  "Vileplume": { "release_below_cp": 871, "release_below_iv": 0.8, "logic": "and" },
  "Blastoise": { "release_below_cp": 888, "release_below_iv": 0.8, "logic": "and" },
  "Omastar":  { "release_below_cp": 780, "release_below_iv": 0.8, "logic": "and" },
  "Aerodactyl": { "release_below_cp": 756, "release_below_iv": 0.8, "logic": "and" },
  "Golem": { "release_below_cp": 804, "release_below_iv": 0.8, "logic": "and" },
  "Wigglytuff": { "release_below_cp": 760, "release_below_iv": 0.8, "logic": "and" },
  "Dewgong": { "release_below_cp": 748, "release_below_iv": 0.8, "logic": "and" },
  "Ninetales": { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
  "Magmar": { "release_below_cp": 792, "release_below_iv": 0.8, "logic": "and" },
  "Kabutops": { "release_below_cp": 744, "release_below_iv": 0.8, "logic": "and" },
  "Electabuzz": { "release_below_cp": 739, "release_below_iv": 0.8, "logic": "and" },
  "Starmie": { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
  "Jolteon": { "release_below_cp": 746, "release_below_iv": 0.8, "logic": "and" },
  "Rapidash": { "release_below_cp": 768, "release_below_iv": 0.8, "logic": "and" },
  "Pinsir": { "release_below_cp": 1400, "release_below_iv": 1, "logic": "and" },
  "Scyther": { "release_below_cp": 724, "release_below_iv": 0.8, "logic": "and" },
  "Tentacruel": { "release_below_cp": 775, "release_below_iv": 0.8, "logic": "and" },
  "Gengar": { "release_below_cp": 724, "release_below_iv": 0.8, "logic": "and" },
  "Hypno": { "release_below_cp": 763, "release_below_iv": 0.8, "logic": "and" },
  "Pidgeot": { "release_below_cp": 729, "release_below_iv": 0.8, "logic": "and" },
  "Rhydon": { "release_below_cp": 782, "release_below_iv": 0.8, "logic": "and" },
  "Seaking": { "release_below_cp": 712, "release_below_iv": 0.8, "logic": "and" },
  "Kangaskhan": { "release_below_cp": 712, "release_below_iv": 0.8, "logic": "and" },

  "// Koffing evolves to Weezing (A-Tier)": {},
  "Koffing": { "release_below_cp": 700, "release_below_iv": 1, "logic": "and" },

  "// Below is B-tier and lower pokemons": {},
  "Caterpie": { "release_below_cp": 230, "release_below_iv": 1, "logic": "and" },
  "Weedle": { "release_below_cp": 250, "release_below_iv": 1, "logic": "and" },
  "Diglett": { "release_below_cp": 170, "release_below_iv": 0.8, "logic": "and" },
  "Metapod": { "release_below_cp": 168, "release_below_iv": 0.8, "logic": "and" },
  "Kakuna": { "release_below_cp": 220, "release_below_iv": 1, "logic": "and" },
  "Rattata": { "release_below_cp": 380, "release_below_iv": 1, "logic": "and" },
  "Abra": { "release_below_cp": 300, "release_below_iv": 1, "logic": "and" },
  "Zubat": { "release_below_cp": 410, "release_below_iv": 1, "logic": "and" },
  "Chansey": { "release_below_cp": 235, "release_below_iv": 0.8, "logic": "and" },
  "Pidgey": { "release_below_cp": 430, "release_below_iv": 1, "logic": "and" },
  "Spearow": { "release_below_cp": 450, "release_below_iv": 1, "logic": "and" },
  "Meowth": { "release_below_cp": 425, "release_below_iv": 0.8, "logic": "and" },
  "Krabby": { "release_below_cp": 500, "release_below_iv": 1, "logic": "and" },
  "Sandshrew": { "release_below_cp": 278, "release_below_iv": 0.8, "logic": "and" },
  "Poliwag": { "release_below_cp": 500, "release_below_iv": 1, "logic": "and" },
  "Horsea": { "release_below_cp": 490, "release_below_iv": 1, "logic": "and" },
  "Gastly": { "release_below_cp": 400, "release_below_iv": 1, "logic": "and" },
  "Ekans": { "release_below_cp": 500, "release_below_iv": 1, "logic": "and" },
  "Shellder": { "release_below_cp": 288, "release_below_iv": 0.8, "logic": "and" },
  "Vulpix": { "release_below_cp": 400, "release_below_iv": 1, "logic": "and" },
  "Voltorb": { "release_below_cp": 550, "release_below_iv": 1, "logic": "and" },
  "Geodude": { "release_below_cp": 470, "release_below_iv": 1, "logic": "and" },
  "Doduo": { "release_below_cp": 450, "release_below_iv": 1, "logic": "and" },
  "Onix": { "release_below_cp": 300, "release_below_iv": 0.8, "logic": "and" },
  "Mankey": { "release_below_cp": 500, "release_below_iv": 1, "logic": "and" },
  "Pikachu": { "release_below_cp": 309, "release_below_iv": 0.8, "logic": "and" },
  "Magnemite": { "release_below_cp": 575, "release_below_iv": 1, "logic": "and" },
  "Tentacool": { "release_below_cp": 450, "release_below_iv": 1, "logic": "and" },
  "Paras": { "release_below_cp": 550, "release_below_iv": 1, "logic": "and" },
  "Jigglypuff": { "release_below_cp": 500, "release_below_iv": 1, "logic": "and" },
  "Ditto": { "release_below_cp": 321, "release_below_iv": 0.8, "logic": "and" },
  "Staryu": { "release_below_cp": 600, "release_below_iv": 1, "logic": "and" },
  "Charmander": { "release_below_cp": 333, "release_below_iv": 0.8, "logic": "and" },
  "Goldeen": { "release_below_cp": 650, "release_below_iv": 1, "logic": "and" },
  "Squirtle": { "release_below_cp": 500, "release_below_iv": 1, "logic": "and" },
  "Cubone": { "release_below_cp": 500, "release_below_iv": 1, "logic": "and" },
  "Venonat": { "release_below_cp": 660, "release_below_iv": 1, "logic": "and" },
  "Bulbasaur": { "release_below_cp": 550, "release_below_iv": 1, "logic": "and" },
  "Drowzee": { "release_below_cp": 600, "release_below_iv": 1, "logic": "and" },
  "Machop": { "release_below_cp": 650, "release_below_iv": 1, "logic": "and" },
  "Psyduck": { "release_below_cp": 600, "release_below_iv": 0.8, "logic": "and" },
  "Seel": { "release_below_cp": 386, "release_below_iv": 0.8, "logic": "and" },
  "Kabuto": { "release_below_cp": 386, "release_below_iv": 0.8, "logic": "and" },
  "Bellsprout": { "release_below_cp": 700, "release_below_iv": 1, "logic": "and" },
  "Omanyte": { "release_below_cp": 391, "release_below_iv": 0.8, "logic": "and" },
  "Kadabra": { "release_below_cp": 396, "release_below_iv": 0.8, "logic": "and" },
  "Oddish": { "release_below_cp": 700, "release_below_iv": 1, "logic": "and" },
  "Dugtrio": { "release_below_cp": 408, "release_below_iv": 0.8, "logic": "and" },
  "Rhyhorn": { "release_below_cp": 600, "release_below_iv": 1, "logic": "and" },
  "Clefairy": { "release_below_cp": 700, "release_below_iv": 1, "logic": "and" },
  "Slowpoke": { "release_below_cp": 675, "release_below_iv": 1, "logic": "and" },
  "Pidgeotto": { "release_below_cp": 675, "release_below_iv": 0.8, "logic": "and" },
  "Farfetch'd": { "release_below_cp": 441, "release_below_iv": 0.8, "logic": "and" },
  "Poliwhirl": { "release_below_cp": 468, "release_below_iv": 0.8, "logic": "and" },
  "Nidorino": { "release_below_cp": 480, "release_below_iv": 0.8, "logic": "and" },
  "Haunter": { "release_below_cp": 482, "release_below_iv": 0.8, "logic": "and" },
  "Nidorina": { "release_below_cp": 489, "release_below_iv": 0.8, "logic": "and" },
  "Graveler": { "release_below_cp": 501, "release_below_iv": 0.8, "logic": "and" },
  "Beedrill": { "release_below_cp": 504, "release_below_iv": 0.8, "logic": "and" },
  "Raticate": { "release_below_cp": 900, "release_below_iv": 1, "logic": "and" },
  "Butterfree": { "release_below_cp": 508, "release_below_iv": 0.8, "logic": "and" },
  "Hitmonlee": { "release_below_cp": 520, "release_below_iv": 0.8, "logic": "and" },
  "Ponyta": { "release_below_cp": 700, "release_below_iv": 1, "logic": "and" },
  "Hitmonchan": { "release_below_cp": 530, "release_below_iv": 0.8, "logic": "and" },
  "Charmeleon": { "release_below_cp": 544, "release_below_iv": 0.8, "logic": "and" },
  "Wartortle": { "release_below_cp": 552, "release_below_iv": 0.8, "logic": "and" },
  "Persian": { "release_below_cp": 568, "release_below_iv": 0.8, "logic": "and" },
  "Lickitung": { "release_below_cp": 568, "release_below_iv": 0.8, "logic": "and" },
  "Ivysaur": { "release_below_cp": 571, "release_below_iv": 0.8, "logic": "and" },
  "Electrode": { "release_below_cp": 850, "release_below_iv": 1, "logic": "and" },
  "Marowak": { "release_below_cp": 578, "release_below_iv": 0.8, "logic": "and" },
  "Gloom": { "release_below_cp": 590, "release_below_iv": 0.8, "logic": "and" },
  "Porygon": { "release_below_cp": 590, "release_below_iv": 0.8, "logic": "and" },
  "Seadra": { "release_below_cp": 597, "release_below_iv": 0.8, "logic": "and" },
  "Jynx": { "release_below_cp": 600, "release_below_iv": 0.8, "logic": "and" },
  "Weepinbell": { "release_below_cp": 602, "release_below_iv": 0.8, "logic": "and" },
  "Tangela": { "release_below_cp": 607, "release_below_iv": 0.8, "logic": "and" },
  "Fearow": { "release_below_cp": 609, "release_below_iv": 0.8, "logic": "and" },
  "Parasect": { "release_below_cp": 609, "release_below_iv": 0.8, "logic": "and" },
  "Machoke": { "release_below_cp": 614, "release_below_iv": 0.8, "logic": "and" },
  "Arbok": { "release_below_cp": 616, "release_below_iv": 0.8, "logic": "and" },
  "Sandslash": { "release_below_cp": 631, "release_below_iv": 0.8, "logic": "and" },
  "Alakazam": { "release_below_cp": 633, "release_below_iv": 0.8, "logic": "and" },
  "Kingler": { "release_below_cp": 636, "release_below_iv": 0.8, "logic": "and" },
  "Dodrio": { "release_below_cp": 640, "release_below_iv": 0.8, "logic": "and" },
  "Tauros": { "release_below_cp": 1200, "release_below_iv": 1, "logic": "and" },
  "Primeape": { "release_below_cp": 650, "release_below_iv": 0.8, "logic": "and" },
  "Magneton": { "release_below_cp": 657, "release_below_iv": 0.8, "logic": "and" },
  "Venomoth": { "release_below_cp": 660, "release_below_iv": 0.8, "logic": "and" },
  "Golbat": { "release_below_cp": 1200, "release_below_iv": 1, "logic": "and" },
  "Raichu": { "release_below_cp": 708, "release_below_iv": 0.8, "logic": "and" },
  "Cloyster": { "release_below_cp": 717, "release_below_iv": 0.8, "logic": "and"},
  "Mr. Mime": { "release_below_cp": 650, "release_below_iv": 0.8, "logic": "and" }
},
"vips" : {
     "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
    "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
    "Lapras": {},
    "Moltres": {},
    "Zapdos": {},
    "Articuno": {},

    "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
    "Mewtwo": {},
    "Dragonite": {},
    "Snorlax": {},
    "// Mew evolves to Mewtwo": {},
    "Mew": {},
    "Arcanine": {},
    "Vaporeon": {},
    "Gyarados": {},
    "Exeggutor": {},
    "Muk": {},
    "Weezing": {},
    "Flareon": {}

}
}

### Output when issue occurred
2016-08-23 23:58:11,588 [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-24 22:43:08.587899
2016-08-23 23:58:11,717 [EvolvePokemon] [WARNING] evolve_speed is deprecated, please use instead 'min_evolve_speed' and 'max_evolved_speed'.
2016-08-23 23:58:12,823 [PokemonGoBot] [INFO] [bot_start] Starting bot...
2016-08-23 23:58:14,458 [CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: []
2016-08-23 23:58:14,585 [IncubateEggs] [INFO] [next_egg_incubates] Eggs incubating: [1.51/2.0 km, 3.69/5.0 km, 5.21/10.0 km] (Eggs left: 6, Incubating: 3)
2016-08-23 23:58:14,745 [       cli] [INFO] 
2016-08-23 23:58:14,745 [       cli] [INFO] Ran for 0:00:07
2016-08-23 23:58:14,745 [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
2016-08-23 23:58:14,746 [       cli] [INFO] Travelled 0.00km
2016-08-23 23:58:14,746 [       cli] [INFO] Visited 0 stops
2016-08-23 23:58:14,746 [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before
2016-08-23 23:58:14,746 [       cli] [INFO] Threw 0 pokeballs
2016-08-23 23:58:14,746 [       cli] [INFO] Earned 0 Stardust
2016-08-23 23:58:14,746 [       cli] [INFO] Hatched eggs 0
2016-08-23 23:58:14,746 [       cli] [INFO] Next egg hatches in 0.49 km
2016-08-23 23:58:14,746 [       cli] [INFO] 
2016-08-23 23:58:14,747 [       cli] [INFO] Highest CP Pokemon: 
2016-08-23 23:58:14,747 [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 703, in <module>
    main()
  File "pokecli.py", line 118, in main
    bot.tick()
  File "/home/venkrish/PokemonGo-Bot/pokemongo_bot/__init__.py", line 568, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/venkrish/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_pokemon.py", line 34, in work
    self.get_visible_pokemon()
  File "/home/venkrish/PokemonGo-Bot/pokemongo_bot/cell_workers/catch_pokemon.py", line 75, in get_visible_pokemon
    'expiration_timestamp_ms': pokemon['expiration_timestamp_ms'],
  File "/home/venkrish/PokemonGo-Bot/pokemongo_bot/base_task.py", line 35, in emit_event
    data=data
  File "/home/venkrish/PokemonGo-Bot/pokemongo_bot/event_manager.py", line 65, in emit
    handler.handle_event(event, sender, level, formatted_msg, data)
  File "/home/venkrish/PokemonGo-Bot/pokemongo_bot/event_handlers/social_handler.py", line 59, in handle_event
    self.mqttc.publish("pgomapgeo/"+geo_hash+"/"+str(data['pokemon_id']), str(data['latitude'])+","+str(data['longitude'])+","+str(data['encounter_id'])+","+str(data['pokemon_id'])+","+str(data['expiration_timestamp_ms'])+","+str(data['pokemon_name']))
KeyError: 'pokemon_name'
2016-08-23 23:58:14,764 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-08-23 23:58:14,767 [sentry.errors.uncaught] [ERROR] [u"KeyError: 'pokemon_name'", u'  File "pokecli.py", line 703, in <module>', u'  File "pokecli.py", line 118, in main', u'  File "pokemongo_bot/__init__.py", line 568, in tick', u'  File "pokemongo_bot/cell_workers/catch_pokemon.py", line 34, in work', u'  File "pokemongo_bot/cell_workers/catch_pokemon.py", line 75, in get_visible_pokemon', u'  File "pokemongo_bot/base_task.py", line 35, in emit_event', u'  File "pokemongo_bot/event_manager.py", line 65, in emit', u'  File "pokemongo_bot/event_handlers/social_handler.py", line 59, in handle_event']

### Steps to Reproduce
Just start the bot

### Other Information
OS: 
MacOS
Branch: 
dev
Git Commit: 
a0cb16fabf243cbf0fd50cc9deb28db5403d704c
Python Version: 
Python 2.7.12

**Comment by MasterCATZ** [comment]
same rolled back to 

a1a71fb

**Comment by k4n30** [comment]
@BreezeRo looks to be social related

**Comment by MasterCATZ** [comment]
commit: fae2fb23deafccb8643298895ad6553effd52355
works

**Comment by foster82** [comment]
OK I am having the same issue,  where do I put the option to turn social off. 

Thanks

**Comment by cmezh** [comment]
Latest commit (36e66dd) works fine. ```enable_social``` is enabled.

**Comment by mjmadsen** [comment]
Seems to be resolved in the dev branch. Please reopen if not.

**Comment by BreezeRo** [comment]
Who ever updated it completely removed some of the other stuff like pokemon name string builder. As for this issue it could have been resolved with a simple check to see if social is enabled, if not do 'nothing'.
