### ISSUE TITLE
Bot Print "This is a VIP pokemon. Catch!!!" even low stat pokemon.

### ISSUE THREAD

**Issue by razithekillers** [PokemonGoF/PokemonGo-Bot#4665]
### Expected Behavior
IV below 0.8 Should not VIPs

### Actual Behavior
All pokemon catching is stated VIPs

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/kFwE76zv

### Output when issue occurred
![image](https://cloud.githubusercontent.com/assets/20743071/17924643/1007728a-6a1c-11e6-9a78-a5fcc4659530.png)

### Steps to Reproduce
Should not print "This is a VIP pokemon. Catch!!!" If IV below 0.8

### Other Information
OS: 
Ubuntu On Windows
Branch: 
Master
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by Bashin** [comment]
"treat_unseen_as_vip": true,
in your config.. set this to false

**Comment by razithekillers** [comment]
@Bashin Thanks, :D

**Comment by kenkclam** [comment]
I have the same problem:

2016-08-24 11:17:44,589 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Poliwag appeared! [CP 10] [NCP 0.01] [Potential 0.58] [A/D/S 7/11/8]
2016-08-24 11:17:47,591 [PokemonCatchWorker] [INFO] [vip_pokemon] This is a VIP pokemon. Catch!!!
2016-08-24 11:17:50,377 [PokemonCatchWorker] [INFO] [threw_pokeball] OK throw! Used Pokeball, with chance 100.00 (85 left)
2016-08-24 11:17:50,598 [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Poliwag! [CP 10] [NCP 0.01] [Potential 0.58] [7/11/8] [+100 exp]

As you can see, poliwag is not an unseen pokemon [+100 exp] not [+600 exp]
the bot still define it as VIP

**Comment by maxprzemo** [comment]
@kenkclam 
read what he wrote @Bashin 
* `treat_unseen_as_vip`: Default `"true"` | Set to `"false"` to disable treating pokemons you don't have in your pokedex as VIPs.

**Comment by davidspeijer** [comment]
Could it be that; 
bot starts and capture first Poliwag but doesn't update the captured pokemon? So next time it sees a Poliwag without a restart that it is still treaded as a VIP?

**Comment by sohje** [comment]
@kenkclam Show us your config.
@davidspeijer Just started a new bot. First Rattata treated as VIP, second one - as normal pokemon. So pokedex updated correctly. Same for Pidgeys.

**Comment by k4n30** [comment]
@Calcyfer - Can you look into please as this was your PR

**Comment by Calcyfer** [comment]
@k4n30 My PR only added the config value, the actual logic was added by @sohje in PR #4580 .
The config value seems to work, so I'd look into the logic direction.

**Comment by sohje** [comment]
@Calcyfer @k4n30 I made tests before and review code - dont see any problems with logic or code.
Need more logs and bots configs where problem accurs.

**Comment by Calcyfer** [comment]
@kenkclam A small reminder to show us your config, please.

**Comment by mjmadsen** [comment]
Since @razithekillers issue has been solved, please open up a new issue if you have problems (with configs and logs!)
