### ISSUE TITLE
Show name of captured pokemons never seen before

### ISSUE THREAD

**Issue by ishepard** [PokemonGoF/PokemonGo-Bot#4667]
### Short Description

Instead of showing only the number of pokemons never seen before, could be an option to show also the name.

### Example
from:
Encountered 134 pokemon, 122 caught, 182 released, 0 evolved, 2 never seen before
to:
Encountered 134 pokemon, 122 caught, 182 released, 0 evolved, 2 never seen before (Charizard and Snorlax)

**Comment by maxprzemo** [comment]
Great idea.
