### ISSUE TITLE
[Help needed] Better explanation for release configuration

### ISSUE THREAD

**Issue by lntn** [PokemonGoF/PokemonGo-Bot#4673]
my current config is as below:
```
"tasks": [{"type": "TransferPokemon"}],
"release": {
  "Rattata": {"release_below_iv": 0.85},
  "any": {release_below_iv": 0.75}
}
```
Hoping that the bot will release all rattata with iv < 0.85, and release all other pokemon with iv < 0.75.
But it's not working and the bot didn't release any of them.

I wish to learn more of:
- How "specific pokemon name" and "any" work together, as in the config above
- How "release_below_iv" and "keep_best_iv" work together as in "any": {release_below_iv": 0.75, "keep_best_iv": 1}

**Comment by supergithubo** [comment]
The bot will not transfer any pokemon when `min_slot` threshold is not reached under TransferPokemon task config. Check the new config examples.

**Comment by lntn** [comment]
I switch to use PokemonOptimizer but it still doesn't release any... and I currently have 6 psyducks, 6 magikarps in the bag.

```
{
      "type": "PokemonOptimizer",
      "config": {
        "enabled": true,
        "transfer": true,
        "transfer_wait_min": 3,
        "transfer_wait_max": 5,
        "evolve": false,
        "evolve_time": 20,
        "evolve_for_xp": false,
        "evolve_only_with_lucky_egg": false,
        "evolve_count_for_lucky_egg": 92,
        "may_use_lucky_egg": false,
        "keep": [
          {
            "top": 2,
            "evolve": false,
            "sort": ["ivcp"]
          },
          {
            "top": 2,
            "evolve": false,
            "sort": ["ncp"]
          },
          {
            "names": ["Dragonite", "Arcanine", "Muk"],
            "top": 2,
            "evolve": false,
            "sort": ["cp"]
          }
        ]
      }
    },
```

**Comment by supergithubo** [comment]
@lntn add the `min_free_slot` on the TransferPokemon task config. Set it to max capacity of you pokemon bag(250, default is 5) for the bot to transfer the pokemon immediately. Here's the code in the task:
`
def _should_work(self):
        return inventory.Pokemons.get_space_left() <= self.min_free_slot
`

**Comment by lntn** [comment]
How about these guys?

- How "specific pokemon name" and "any" work together, as in the config above
- How "release_below_iv" and "keep_best_iv" work together as in "any": {release_below_iv": 0.75, "keep_best_iv": 1}

**Comment by 4IbWNsis3S** [comment]
I just use this. I haven't had time to reverse engineer the undocumented config system off python code.. The optimizer JSON seems to just duplicate other JSON but in a single object. A lot of the objects depend on other objects to be enabled and their execution order isn't documented so there is plenty of room for bad conflicting configs.

```
   "release": {
      "// any": {"release_below_cp": 300, "release_below_iv": 0, "logic": "or"},
	  "any": {"keep_best_iv": 1},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Also, it is working with any": {},
      "// any": {"keep_best_iv": 3},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3},
	  "// Example of custom order of static criterion": {},
	  "// Zubat": {"keep_best_custom": "iv, cp, hp_max", "amount":2}
    }`
```

**Comment by Anakin5** [comment]
- "any" is uses if there is no configuration under the specific Pokemon name. It is a default value in case you do not have a specific Pokemon config.
- release_below_iv create a list of Pokemon under that iv to release.
keep_best_iv create a list of Pokemon to not release.
So at the end, you release everything in release_below_iv minus what is in keep_best_iv.
This configuration simply means: release everything under 0.75 iv but make sure you keep at least one pokemon, the best iv, regardless of the value.

All that only happens  if TransferPokemon task is present and your bag is full.

**Comment by mjmadsen** [comment]
@intn does that answer your question?

**Comment by mjmadsen** [comment]
Since I've seen you make some other posts since I asked, I'm going to assume you have your answer.

**Comment by lntn** [comment]
oops sorry somehow I missed out all the comments on this thread. Yup questions were answered. Thank you.

**Comment by mjmadsen** [comment]
@lntn awesome. Glad you got it figured out!
