### ISSUE TITLE
[Help needed] Has anyone been able to not get banned so far?

### ISSUE THREAD

**Issue by krishven** [PokemonGoF/PokemonGo-Bot#4679]
I have had 3 accounts get banned so far.
I've almost tried everything, playing with slow walking speed, playing for only few hours a day etc.

If anyone does have some tips on how to avoid getting banned, please share it.
Much appreciated.

**Comment by jlim0930** [comment]
all my accounts got banned.. the last round i only ran it 3 times per day for 2 hours and enabled take rests and put in random start/stop time and made sure no 2 bots ran at the same time from my ip.. once the bots hit >level 20 it was banned

my first 2 accounts my kids actually spent money on and got banned wondering if i can request for a refund...

**Comment by MZorzy** [comment]
No way. Data from bot is too different from app. Timing, request sort, sensor, device data ...

**Comment by krishven** [comment]
@MZorzy if that's true then there is no meaning in running the bot.
They can pick us out easily.

**Comment by mjmadsen** [comment]
I'm probably around 20 lost accounts. Settings all over the place and timing of ban (my level, etc) also all over the place. As @MZorzy said, it's just not there yet.

**Comment by ntanto** [comment]
this discussion still running at #4114
