### ISSUE TITLE
[FEATURE REQUEST] move after out of pokeball during camping

### ISSUE THREAD

**Issue by ntanto** [PokemonGoF/PokemonGo-Bot#4681]
### Short Description
when pokeball under certain amount it will move again just for spin fort
it work with move to fort, follow path, or follow spiral

### Possible solution
add camp task to config maybe like this
     {
     	"type": "Camp",
     	"config": {
     		"enabled": false,
     		"location": "1, 1, 1",
     		"min_pokeball": "10",
     		"max_pokeball": "100"
     	}
     }

### How it would help others
i think its closer to human behavior

**Comment by Vvkmnn** [comment]
We've tried to address this in #4675, but in a different way.
