### ISSUE TITLE
expiration_timestamp_ms spam in log

### ISSUE THREAD

**Issue by philly223** [PokemonGoF/PokemonGo-Bot#4683]
### Expected Behavior
bot to run normally w/ clean log

### Actual Behavior

excessive spam in log

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/8bcC0QjE

### Output when issue occurred
{u'pokemon_id': 16, u'longitude': -80.10495021522102, u'expiration_timestamp_ms': 1472057528884, u'latitude': 26.372961770602647, u'spawn_point_id': u'88d91e1b6c5', u'encounter_id': 7122949343930238573}
{u'pokemon_id': 33, u'longitude': -121.87338310613147, u'expiration_timestamp_ms': -1, u'latitude': 37.24149489430428, u'spawn_point_id': u'808e31669d9', u'encounter_id': 11360499658266623165L}
2016-08-24 09:46:39,843 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Magikarp appeared! [CP 123] [NCP 0.47] [Potential 0.6] [A/D/S 12/13/2]
{u'pokemon_id': 23, u'longitude': -118.4798726087074, u'expiration_timestamp_ms': 1472057469764, u'latitude': 34.02627887133028, u'spawn_point_id': u'80c2bb36859', u'encounter_id': 4048057804078879197}
{u'pokemon_id': 19, u'longitude': -73.98644639119172, u'expiration_timestamp_ms': 1472057448348, u'latitude': 40.770751627166405, u'spawn_point_id': u'89c2585ed17', u'encounter_id': 13755225678703496861L}
{u'pokemon_id': 129, u'longitude': 10.021648167511389, u'expiration_timestamp_ms': 1472057376100, u'latitude': 53.58216634251498, u'spawn_point_id': u'47b1892c399', u'encounter_id': 230326590828112333}
{u'pokemon_id': 72, u'longitude': -122.39402887232174, u'expiration_timestamp_ms': 1472057983116, u'latitude': 37.79818146193523, u'spawn_point_id': u'80858067693', u'encounter_id': 8916376434845847517}
{u'pokemon_id': 19, u'longitude': 139.7618137172697, u'expiration_timestamp_ms': 1472057343172, u'latitude': 35.72160225305285, u'spawn_point_id': u'60188dcd459', u'encounter_id': 9260674959762147277L}
{u'pokemon_id': 7, u'longitude': 121.61239835817588, u'expiration_timestamp_ms': 1472057253572, u'latitude': 25.071168617079888, u'spawn_point_id': u'3442acbb991', u'encounter_id': 8771128265397381229}
{u'pokemon_id': 79, u'longitude': 121.50671116466084, u'expiration_timestamp_ms': -1, u'latitude': 25.13646168735932, u'spawn_point_id': u'3442ae44c15', u'encounter_id': 3503288207578663949}
{u'pokemon_id': 120, u'longitude': -73.97744736091367, u'expiration_timestamp_ms': 1472057451700, u'latitude': 40.75704880511911, u'spawn_point_id': u'89c258fe815', u'encounter_id': 3629889823605129101}

### Steps to Reproduce
deleted PGobot folder and re-cloned. bot is running fine, just excessive clutter inside terminal

### Other Information
OS: OS X 10.11
 
Branch: master

Git Commit: commit de78768634795d1733f8d7e1902d57c238cf0207

Python Version: 
 2.7

**Comment by mjmadsen** [comment]
Try this in your config:
    "enable_social": false,

**Comment by PatatasFritas** [comment]
Comment or delete line 24 in pokemongo_bot/event_handlers/social_handler.py

> print pokemon

**Comment by mjmadsen** [comment]
We should have output configuration for social.

**Comment by philly223** [comment]
switching to false fixed it. Thanks!!
