### ISSUE TITLE
Expand #3868 as crowdsource map

### ISSUE THREAD

**Issue by ntanto** [PokemonGoF/PokemonGo-Bot#4688]
### Short Description
i read #3868 
is there any possibility to expand it as crowdsource map?
i notice there isn't any map covering the whole world

### How it would help others
it will help all player around the world
maybe creating spawn statistic and decide which random, habitat, or nest area

**Comment by KingTheRipper** [comment]
Is now amazing data see on Terminal

**Comment by mjmadsen** [comment]
Pretty sure our new social setting covers this. If you feel it does not, please elaborate and reopen.
