### ISSUE TITLE
Assign to Team after reaching lvl 5

### ISSUE THREAD

**Issue by ciego10** [PokemonGoF/PokemonGo-Bot#4691]
### Short Description

Add the ability to assign to a team (blue, red, yellow) after bot is reaching lvl5

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/pull/4070#issuecomment-240082814

**Comment by avexus** [comment]
I think those once in a life time tasks are better handled by manual operation.
Bots are best at repetitive tasks.
