### ISSUE TITLE
Is it possible to start run.sh using a different username and password without modifying config?

### ISSUE THREAD

**Issue by ultrafunkamsterdam** [PokemonGoF/PokemonGo-Bot#4695]
Sorry, no issue.

I would like each of my 200 accounts do 5/10 minutes of botting a day, scheduled at certain times, because they are used for maps, they never catch anyting and that looks suspicious, 

So my idea was to write as script that runs the application using account 1, stops after 5 mins, restarts the application using but using account 2. and 3, and 4.

**Comment by krishven** [comment]
Should be simple enough, pokecli.py should be modified to take in command line arguments

**Comment by cmezh** [comment]
Why not to generate 200 configs and pass it as argument to run.sh or pokecli.py?

**Comment by ultrafunkamsterdam** [comment]
thanks guys! did not know you could pass the config to run. now I have some directions how to do it.

**Comment by mjmadsen** [comment]
./run.sh ./configs/nameofconfig.json

I would like to extend the config to let you enter a list of username and passwords for this purpose. Just haven't gotten to it yet.
