### ISSUE TITLE
Getting error on latest download

### ISSUE THREAD

**Issue by infamousmax** [PokemonGoF/PokemonGo-Bot#47]
when trying to login I get this, it worked before I updated the files.

Traceback (most recent call last):
  File "C:\PokemonGo-Bot-master\pokecli.py", line 38, in <module>
    ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'

**Comment by ethervoid** [comment]
This PR fixes it https://github.com/PokemonGoF/PokemonGo-Bot/pull/48

**Comment by PokemonGoF** [comment]
Please let's know if still issue. Close for now. Thanks @ethervoid
