### ISSUE TITLE
Bot crashes on getting _INVENTORY

### ISSUE THREAD

**Issue by TheGoldenXY** [PokemonGoF/PokemonGo-Bot#470]
### Expected Behavior
The bot should be able to run 24/7 without crashing.

### Actual Behavior
After 40 minutes of uptime, the bot crashes with this message:
http://prntscr.com/bwl5j0

### Steps to Reproduce
N/A

### Other Information
OS: Ubuntu, 14.04
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
a5cf48976651adcbfe02d29f129f0f625ba5d1ec

**Comment by s1x** [comment]
Does it always crash after 40 minutes, or at a certain point/pokestop/catching pokemon?

For me the bot is running longer then 7h now.

**Comment by TheGoldenXY** [comment]
@s1x It doesn't always crash after 40 minutes. I think it crashes at a certain point/pokestop/catching pokemon, not entirely sure.

**Comment by mpawlucz** [comment]
sometimes it crashes and sometimes the output is following:

`[#] Scanning area for objects (114 / 2500)
[#] Walking from (52.222448, 20.9923161) to (52.224948, 20.9923161) for approx. 16.00 seconds
[#] Finished walking
[#] (52.224948, 20.9923161, 0)
[#] Scanning area for objects (115 / 2500)
[#] Walking from (52.224948, 20.9923161) to (52.227448, 20.9923161) for approx. 16.00 seconds
[#] Finished walking
[#] (52.227448, 20.9923161, 0)
[#] Scanning area for objects (116 / 2500)
[#] Walking from (52.227448, 20.9923161) to (52.229948, 20.9923161) for approx. 16.00 seconds
[#] Finished walking
[#] (52.229948, 20.9923161, 0)
[#] Scanning area for objects (117 / 2500)
[#] Walking from (52.229948, 20.9923161) to (52.232448, 20.9923161) for approx. 16.00 seconds
[#] Finished walking
[#] (52.232448, 20.9923161, 0)
[#] Scanning area for objects (118 / 2500)
[#] Walking from (52.232448, 20.9923161) to (52.234948, 20.9923161) for approx. 16.00 seconds
[#] Finished walking
[#] (52.234948, 20.9923161, 0)
[#] Scanning area for objects (119 / 2500)
[#] Walking from (52.234948, 20.9923161) to (52.237448, 20.9923161) for approx. 16.00 seconds
[#] Finished walking
[#] (52.237448, 20.9923161, 0)
[#] Scanning area for objects (120 / 2500)
[#] Walking from (52.237448, 20.9923161) to (52.239948, 20.9923161) for approx. 16.00 seconds
[#] Finished walking
[#] (52.239948, 20.9923161, 0)
[#] Scanning area for objects (121 / 2500)
[#] Walking from (52.239948, 20.9923161) to (52.242448, 20.9923161) for approx. 16.00 seconds
[#] Finished walking
[#] (52.242448, 20.9923161, 0)
[#] Scanning area for objects (122 / 2500)
[#] Walking from (52.242448, 20.9923161) to (52.244948, 20.9923161) for approx. 16.00 seconds
[#] Finished walking
[#] (52.244948, 20.9923161, 0)
[#] Scanning area for objects (123 / 2500)
[#] Walking from (52.244948, 20.9923161) to (52.244948, 20.994816099999998) for approx. 10.00 seconds
[#] Finished walking
`

reset instantly helps, and bot starts finding pokemon

**Comment by surfaace** [comment]
error respons is from api and sure, we didnt have the code to handle it. servers are now more stable so we are currenly 'not experiancing it'
