### ISSUE TITLE
implement application like delays to account of animation screens

### ISSUE THREAD

**Issue by duttonw** [PokemonGoF/PokemonGo-Bot#4700]
### Short Description
logs for the game are being joined up into one place, anything that does not look normal from a device in timings is being flagged 
from my normal play through once a pokemon shows up nearby, it takes at least 2-3 seconds before you can throw a pokeball (animation of pokemon appearing) , then it takes at least 3-20 seconds (20ish if its a new pokedex pokemon) to allow you to transfer cancel out of the capture and allow you select another pokemon to capture. 

I don't know where the asset downloads would be occuring, e.g. when you have a new pokemon nearby or when you select it to capture.

### Possible solution
implement default timings for items such as selecting/throwing pokeball after they appear. waiting the min time after a capture for the success screen and maybe the new pokedex entry. if a badge is awarded, wait the min time for the badge to display before selecting/throwing a pokeball etc.

### How it would help others
With more realistic application timings we should be able to stand out as much as the other users of the api.

**Comment by alexyaoyang** [comment]
This is already accomplished with @Quantra's 
`
"catch_simulation": {
            "flee_count": 3,
            "flee_duration": 3,
            "catch_wait_min": 3,
            "catch_wait_max": 6,
            "berry_wait_min": 3,
            "berry_wait_max": 5,
            "changeball_wait_min": 3,
            "changeball_wait_max": 5
          }
`

**Comment by mjmadsen** [comment]
Shouldn't be too hard to add a min/max wait time if we catch a new pokemon. I'll look when I get home, less someone else merges before then.

**Comment by MZorzy** [comment]
Cant radt the code, when bot is in 20sec pause, gps data are sent or are also in pause ?

**Comment by mjmadsen** [comment]
@MZorzy TBH we probably shouldn't use a flat sleep anywhere. Ideally our responses to the server were decoupled from our tasks. But that's a pretty large change.

In the mean time, I'd say a standard sleep is fine (no API updates).

**Comment by duttonw** [comment]
maybe go for a random sleep between min time and a max so that its not as
easy to tell due to exact timings. i've noticed that the tutorial/avatar
setup has exact sleeps which if enough bots user it will show up as humans
never wait exactly 10 seconds before actioning things ;)

**Comment by mjmadsen** [comment]
As I thought about it, our API should be the thing that determines when our calls are made. If it's a request/response sent every X seconds, it should be doing the handling of that. Not quite in the scope of our project.

I'll take a gander at the pokemon_catch_worker and try to get in a PR for the never seen before capture delays.

**Comment by mjmadsen** [comment]
PR up. Give it a go. 

PS some of the formatting in the config files is messed up.

**Comment by mjmadsen** [comment]
Merged.
