### ISSUE TITLE
disable "enable_social" will also disable snipe pokemon from PokemonGoMap

### ISSUE THREAD

**Issue by DragoonZ** [PokemonGoF/PokemonGo-Bot#4704]
if I set "enable_social" to false, it will also stop to snip pokemon from PokemonGoMap

tested on both dev and master branch

**Comment by justprotato** [comment]
i got the same issue

**Comment by sohje** [comment]
Made PR that fixed this issue.

**Comment by sohje** [comment]
I think it fixed after merge.

**Comment by Calcyfer** [comment]
You don't want to use snipe anyway, it will result in a ban, Confirmed with 4 different accounts.
