### ISSUE TITLE
[ERROR] ImportError : Pgoapi.exceptions (Mac OsX) 

### ISSUE THREAD

**Issue by jinkawasaki333** [PokemonGoF/PokemonGo-Bot#4705]
Hello, just compiled and run on my MacOS X and got this error on first run.
How can I fix this?

`./run.sh: line 10: bin/activate: No such file or directory
remote: Counting objects: 127, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 127 (delta 87), reused 74 (delta 74), pack-reused 24
Receiving objects: 100% (127/127), 54.46 KiB | 0 bytes/s, done.
Resolving deltas: 100% (90/90), completed with 38 local objects.
From https://github.com/PokemonGoF/PokemonGo-Bot
   4cc56b9..a529e0e  dev        -> origin/dev
Traceback (most recent call last):
  File "pokecli.py", line 43, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetException
ImportError: No module named pgoapi.exceptions
Thu Aug 25 11:31:12 JST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.`

**Comment by mjmadsen** [comment]
pip install -r requirements.txt --upgrade

But they just put out an update to the app, so I highly recommend not running the bot right now.

**Comment by mjmadsen** [comment]
Oh, and you need to run this too:
source bin/activate

Missed that first part of the error.
