### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by AradeaTechno** [PokemonGoF/PokemonGo-Bot#4706]
===============ISSUE SECTION===============
### Expected Behavior
Bot work fine

### Actual Behavior
Getting error after login procedure

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/7fBJ4zgh

### Output when issue occurred
Getting this error after last pull (master)

Traceback (most recent call last):
  File "pokecli.py", line 705, in <module>
    main()
  File "pokecli.py", line 187, in main
    report_summary(bot)
  File "pokecli.py", line 229, in report_summary
    metrics.num_evolutions(), metrics.num_new_mons(), metrics.uniq_caught()))
  File "/home/aradea/PokemonGo-Bot/pokemongo_bot/metrics.py", line 51, in uniq_caught
    return ', '.join([Pokemons.name_for(pok_id) for pok_id in self.uniq_pokemons_caught]) or ''
TypeError: 'NoneType' object is not iterable

### Steps to Reproduce
- install all requirements after pull
- change latest config

### Other Information
OS: Ubuntu Trusty
Branch: Master
Git Commit:  commit: a529e0e16927b16e79945445d345126efbec501d
Python Version:  Python 2.7.12

**Comment by mjmadsen** [comment]
They updated the app. Probably due to that and our API not updated yet.

**Comment by AradeaTechno** [comment]
Ahh...i see...oke...thx for the great work...appreciate that...

**Comment by mjmadsen** [comment]
My bad, there is a PR in for this #4710

**Comment by mjmadsen** [comment]
Merged it over to dev. Should be resolved now. Please reopen if problem persists.
