### ISSUE TITLE
Looking for help from anyone on right now puh-lease

### ISSUE THREAD

**Issue by roshcamlian** [PokemonGoF/PokemonGo-Bot#4709]
![pikabot](https://cloud.githubusercontent.com/assets/21103035/17956681/34215cc4-6abe-11e6-9270-cbec026472bf.png)
 Halp pretty please? ;-;

**Comment by mjmadsen** [comment]
That is not our bot.

**Comment by roshcamlian** [comment]
@mjmadsen yea but is the error related to your bot? :disappointed:

**Comment by mjmadsen** [comment]
There was an update to the game, but other than that I couldn't tell you. Sorry.
