### ISSUE TITLE
[FollowPath] position_update log frequency

### ISSUE THREAD

**Issue by lntn** [PokemonGoF/PokemonGo-Bot#4719]
position_update log entries for FollowPath appear too often, like every 1.5 seconds, with distance changes from 1 meter to 5 meter depend on the random speed. It's kind of unnecessarily spam the terminal.

An interval of 5 seconds or 10 meter should be more relevant.

**Comment by Gzerox** [comment]
After merge, you can use something like:

```
        "type": "FollowPath",
        "config": {
             ....
             ....
             "log_interval" : 4
        }
```

**Comment by mjmadsen** [comment]
Recent merge fixes this.
