### ISSUE TITLE
curent location not saved under docker

### ISSUE THREAD

**Issue by ntanto** [PokemonGoF/PokemonGo-Bot#4722]
### Expected Behavior
{
        "type": "FollowPath",
        "config": {
          "enabled": true,
          "walker": "StepWalker",
          "path_mode": "loop",
          "path_start_mode": "closest",
          "path_file": "configs/pathfile.gpx",
          "number_lap": 10,
          "timer_restart_min": "01:30:00",
          "timer_restart_max": "02:00:00"
        }
      }

with "path_start_mode": "closest", i expect start from last position and move to closest path

### Actual Behavior
docker images removed after bot shutdowns and not record last position
when its restart will act like "path_start_mode": "first"

### Steps to Reproduce
add this line to docker run command -v $(pwd)/data/:/usr/src/app/data/
and got error message dont have right access database
i change folder security access doesnt change the error

### Other Information
OS: Windows 10 - Docker 1.12.0 Stable Build 5968
Branch: master
Git Commit: ae314b666a1eb71de8872289ef3a298af09e4637
Python Version:  2.7.12

**Comment by MartinTerp** [comment]
if you remove the "--rm" part of the docker run command, it wont "reset" every time, but just stop.
Then if you need to stop: docker stop BOTNAME, or start: docker start BOTNAME

**Comment by k4n30** [comment]
@ntanto does this solve your issue?

**Comment by ntanto** [comment]
i think this solve my problem
thanks a lot and close my case

**Comment by mjmadsen** [comment]
Glad we could help
