### ISSUE TITLE
Dokcker - UpdateWebInventory create json files if dosnt exist

### ISSUE THREAD

**Issue by MartinTerp** [PokemonGoF/PokemonGo-Bot#4729]
### Short Description
UpdateWebInventory dosnt seem to create the json files, that it needs to write to, if i create a empty json file with content: `[]` it registers the inventory, but not player_stats ( i guess it expects the player_stats data to be in the file, so it can append )
Then we cant see lvl/xp on the web gui

### Possible solution
if the inventory.json file dosnt exist, create it with default content

### How it would help others
For us that use the gui, and started a new bot, we can again see the xp/lvl info

**Comment by MartinTerp** [comment]
maybe this is more a bug when i think about it.
recreate as bug or what do you guys say

**Comment by maxprzemo** [comment]
I got the same error https://github.com/PokemonGoF/PokemonGo-Bot/issues/4682#issuecomment-242310674

**Comment by Gobberwart** [comment]
Looks like a bug. Not sure where this file was originally created but appears not to be doing it now. PR to follow.

**Comment by Gobberwart** [comment]
PR #4740 submitted

**Comment by MartinTerp** [comment]
Hi

this dosnt solve the player_stats issue

**Comment by Gobberwart** [comment]
@MartinTerp It sure doesn't. See PR #4757 for this fix.

**Comment by MartinTerp** [comment]
@Gobberwart thanks for clearing this up :)
