### ISSUE TITLE
Double MQTT emit

### ISSUE THREAD

**Issue by Jasperrr91** [PokemonGoF/PokemonGo-Bot#4744]
@solderzzc @BreezeRo @sohje guys, what's up with the double emitting of the found pokemon:

````
self.mqttc.publish("pgomapcatch/all/catchable/"+str(data['pokemon_id']), str(data['latitude'])+","+str(data['longitude'])+","+str(data['encounter_id'])+","+str(data['pokemon_id'])+","+str(data['expiration_timestamp_ms'])+","+str(data['pokemon_name']))
                
json_data = json.dumps(data)
self.mqttc.publish("pgo/all/catchable/"+str(data['pokemon_id']), json_data)
````

The first one is comma seperated and the second one is JSON but it's entirely the same data. So why is it sent twice? 😛

**Comment by Jasperrr91** [comment]
@k4n30 wtf.. Leave this open.

**Comment by k4n30** [comment]
@Jasperrr91 

1. This is not a bot "issue" (and if it were, see point 2)
2. It doesn't follow the issue template

I'll let you decide how you's like to proceed

**Comment by brantje** [comment]
@k4n30 Please leave this open

**Comment by mjmadsen** [comment]
From line 73 of social_handler. 

It looks like we're emitting to two different places, I think? From the comments just before, it looks like the two have different formatting. Either way, I'm not very familiar with this section.

**Comment by Jasperrr91** [comment]
@mjmadsen yea, we're emitting to two different topics on the same MQTT broker. Once with a comma separated data list and once with a JSON object.

@k4n30 it is not an issue with the bot. Therefor the issue template does not apply. It is however an issue with the bot's code and @BreezeRo mentioned on Slack that he'd preferred it if we opened issues here instead of discussing it on slack.

**Comment by mjmadsen** [comment]
@Jasperrr91 I'm told we are emitting to two channels. We can't merge the two channels. But we want to support both, so we send to both.
