### ISSUE TITLE
Better bot movement

### ISSUE THREAD

**Issue by rawgni** [PokemonGoF/PokemonGo-Bot#4751]
### Short Description

Human does not go through building and bot shouldn't too.

Currently, the bot destination is being decided on every `tick()`, ie. the destination can change between `tick`. It will just get the nearest fort and take the shortest route (usually, straight path).

### Possible Solution

Bot should decide which destination to go to, ie which fort to visit next, and stay that way until there is a reason to do so. Once the destination is fixed, we get the direction through Google Direction API. We can then continue using the current algorithm to move through the coordinates returned by  the API. This will make sure we are walking on the road and not through buildings.

**Comment by k4n30** [comment]
@rawgni love the FR, but unless you intend on developing both of these, do you mind splitting them into 2 separate feature requests, because although they are related, they do not need to be achieved together and therefore one could be met independently of the other

**Comment by lntn** [comment]
Google direction API doesn't work for a very short distance, i.e. it will just tell you to walk straight to the destination. Hence when two pokestops are close to each other, direction API won't help.

Altitude algorithm is important though. I too believe that randomizing the altitude is not a good choice because one's altitude should not keep jumping up and down unless you're walking in a mountain jungle. Change in altitude should happen gradually, or once after every few hundred meters.

**Comment by rawgni** [comment]
@lntn I am not sure what you mean by not work. Are you saying that if the pokestop is close to each other , you shouldn't walk straight to it ?

**Comment by lntn** [comment]
@rawgni what I mean is Google maps and its API is not accurate down to every meter, or at least the distance from where you can spin a pokestop. If you do a map search, it will only show you the direction (driving/walking) to the nearest road point, then tell you to walk over to your destination. This walking over part likely to be through building.

Another possible issue is walking direction API only work perfectly for a few country. If there happen to be flyover, bridge, highway, expess way etc... the direction API may mess it up and may tell you to walk/drive a few km for an exit & u-turn.

**Comment by rawgni** [comment]
@lntn If the pokestop happens to be far from road point, then we can't stop it from walking through building. A human would probably need to get off the road to do the same.

I would think direction API will be quite accurate for most location that people bot in. Does it really matter if the bot ask you to drive a few more km for an exit ? 

![screen shot 2016-08-26 at 11 57 33 am](https://cloud.githubusercontent.com/assets/11707733/17994638/b8ffc69e-6b84-11e6-8ffe-26a255dc4475.png)
Check out the screen shot above. The red line is for train tracks, the blue line is for road.
The bot is basically crossing the train track, passing through a couple of houses to get to the other side of the road and back.

**Comment by mjmadsen** [comment]
This can be achieved through using path.json

Applying it to all walkers would be rather difficult. But still a FR regardless. In the mean time, try to setup the dedicated paths.

**Comment by rawgni** [comment]
@mjmadsen yep it's achieveable using path.json but wouldn't be nicer if we could do it without. not everyone wants/knows how to generate a path.json

Initially, i thought why can't we have the bot spawn at a position. look at all the available forts in the area, plans the route it wants to take for the day and execute it.

**Comment by mjmadsen** [comment]
Yeah, that's while I'll leave it open as a FR. Once we can get all these basic elements in, it'll be fun to work on AI elements.

**Comment by alexyaoyang** [comment]
Using google direction api is already implemented with Polyline walker. 
<img width="200" alt="screenshot 2016-08-23 at 6 48 55 pm" src="https://cloud.githubusercontent.com/assets/4772843/18022810/e0706c0c-6ba6-11e6-9c4e-76ff7efbfd4b.png">

**Comment by rawgni** [comment]
@alexyaoyang this FR wants it to not have to depend on followpath. please read my reply to @mjmadsen above

**Comment by alexyaoyang** [comment]
@rawgni Hmm ok, the only other move task which allows you to use polyline walker is move to map pokemon for now. As time goes by, the other move tasks will implement using polyline walker too.

**Comment by th3w4y** [comment]
@lntn 

.get_alt() implements that in the polyline class

>Altitude algorithm is important though. I too believe that randomizing the altitude is not a good choice because one's altitude should not keep jumping up and down unless you're walking in a mountain jungle. Change in altitude should happen gradually, or once after every few hundred meters.

**Comment by th3w4y** [comment]
All the points in this issue are already implemented
