### ISSUE TITLE
inventory-username.json File Is Not Being Updated

### ISSUE THREAD

**Issue by oralunal** [PokemonGoF/PokemonGo-Bot#4752]
### Expected Behavior
Every second it was being updated and I can follow my pokemons via the Web interface. 

### Actual Behavior
It's being updated when bot starts then no updates untill next restarting the bot.

**Comment by lntn** [comment]
I found that it does update, but at a very slow rate or only occasionally. It should be updated after every change in the inventory.

**Comment by mjmadsen** [comment]
What branch, commit, etc. It is difficult as a dev to know where to look without completing the issue template.

**Comment by Gobberwart** [comment]
See latest config example. Add UpdateWebInventory task to make web inventory update every bot tick. Otherwise it will only happen on bot start.

```
      { "type": "UpdateWebInventory",
        "config": {
          "enabled": true
        }
      },
```

**Comment by lntn** [comment]
@Gobberwart dev branch? I setup.sh -u updated the bot but still don't see this in config example

**Comment by Gobberwart** [comment]
In latest dev, it's on line 192 of config.json.example (and in the other examples at different lines)

**Comment by Gobberwart** [comment]
Not in master yet to my knowledge. Master probably still only updates when recycle is run, so... depending on your min_empty_space setting.

**Comment by beltoft** [comment]
I've put 
{ "type": "UpdateWebInventory",
        "config": {
          "enabled": true
        }
      },

in my config but the info button stil don't work.
After i updated to newest dev the info button now just open whatever other windows i had open before. (pokedex, items, whatever)

**Comment by Gobberwart** [comment]
See PR #4757

**Comment by mjmadsen** [comment]
Merged to dev branch. Please give that a go.

**Comment by mjmadsen** [comment]
Closing as it is not fixed in dev branch.

**Comment by Gobberwart** [comment]
@mjmadsen "not" fixed or "now" fixed? Just clarifying whether my PR worked or not.

**Comment by mjmadsen** [comment]
@Gobberwart Oops. I meant "now"
