### ISSUE TITLE
[help needed] explanation on FollowCluster & FollowSpiral

### ISSUE THREAD

**Issue by lntn** [PokemonGoF/PokemonGo-Bot#4755]
We all see example config file for FollowCluster & FollowSpiral but I have no idea what it does. Can someone please help? A simple comment in config file will do.

**Comment by alexyaoyang** [comment]
This is from what I understand by reading the code, so pardon me if there are any errors on my part. I'll be happy to add it to the docs if there aren't any errors.

FollowCluster: Find the biggest cluster of pokestops within `radius`. `lured` specifies if you want to prioritize lured pokestops, if no lured pokestops are found, it will go back to normal behavior of finding the biggest cluster of pokestops.

FollowSpiral: Follows a (strict) spiral path, with the max circle size limited by the `diameter`, walking in step size of `step_size`.

**Comment by mjmadsen** [comment]
@lntn Did you get the answer you were looking for?

**Comment by lntn** [comment]
yup. please close.
Hopefully someone can help to update the documentation for the next person like me.
