### ISSUE TITLE
Noise / Actual location and pathing

### ISSUE THREAD

**Issue by mjmadsen** [PokemonGoF/PokemonGo-Bot#4760]
Currently our pathing is effected by our noise. While it should be effected by human variance (walking side to side), noise should not effect it as it is a device issue. After we apply noise, we're pathing from the noise location rather than the location we're pretending to be at. Basically, noise should only effect API requests and not our internal, "where I want to go from here" bits of goodness.

**Comment by kanemasa1987** [comment]
Aren't the positions changed through api.set_position and retrieved from api.get_position/bot.position (which manipulates actual position)?
The only strange code code I found was in follow_path
https://github.com/PokemonGoF/PokemonGo-Bot/blob/ae314b666a1eb71de8872289ef3a298af09e4637/pokemongo_bot/cell_workers/follow_path.py#L145-L146
which is using noised position for logging. Other parts seem to be using set/get, which should be the actual position.

**Comment by kanemasa1987** [comment]
Oh no! you were right
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/walkers/polyline_walker.py#L29

**Comment by kanemasa1987** [comment]
This is totally unintended, but cached polyline is returning the position you are supposed to be, regardless of this bug, so the behavior itself is correct after all (we are not affected by noise.)

That line in polyline is not used, if we look at it carefully.
I will do some cleanups and add the long waited altitude thingy, after taking some sleep...

**Comment by mjmadsen** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/cell_workers/follow_spiral.py#L70
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/cell_workers/follow_path.py#L102
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/cell_workers/random_alive_pause.py#L141 (this code should be called from somewhere else)
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/cell_workers/pokemon_catch_worker.py#L49
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/api_wrapper.py#L29
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/walkers/polyline_walker.py#L18

**Comment by th3w4y** [comment]
@kanemasa1987  @mjmadsen  let me know if there is a bug in polyline but the instant location returned by .get_pos() should not deviate by more then ~50cm [because of round(pos, 5)] from the calculated position on the Google Directions API polyline.

**Comment by kanemasa1987** [comment]
@th3w4y
Polyline itself is fine, the PolylineWalker is wrong.

**Comment by kanemasa1987** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/cell_workers/follow_spiral.py#L70 <- bug
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/cell_workers/follow_path.py#L102 <- bug
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/cell_workers/random_alive_pause.py#L141 (this code should be called from somewhere else) <- periodically update noised position with thread?
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/cell_workers/pokemon_catch_worker.py#L49 <- bot relogging affects???
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/api_wrapper.py#L29 <- bot relogging affects??? 
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/pokemongo_bot/walkers/polyline_walker.py#L18 <- should be fine.

**Comment by kanemasa1987** [comment]
#4789

**Comment by mjmadsen** [comment]
Nice work @kanemasa1987. We seem good to close this now?

**Comment by kanemasa1987** [comment]
I believe so, we are using actual positions, except spin fort thingy which we should use the noised position (there are cases that actual position is out of radius, while the noised position we are sending is not)

**Comment by mjmadsen** [comment]
Closing, I think we're looking good.
