### ISSUE TITLE
Bot not functioning when bot restarts after `Possibly searching too often` message comes once.

### ISSUE THREAD

**Issue by ravenda900** [PokemonGoF/PokemonGo-Bot#4761]
### Expected Behavior
I run bot once, and it shows `Possibly searching too often`, take a rest. I tried to restart it if it will gone after a couple of mins.

### Actual Behavior
After I restarted the bot is not walking to proper location already(not moving to pokestops, not finding pokemon)

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/k5BiSgGP

### Output when issue occurred

http://pastebin.com/TvJ14pUu

### Steps to Reproduce

1. Run the bot once until the message `Possibly searching too often` comes out.
2. Restart the bot and the out put will appear.

### Other Information
OS: 
Linux
Branch: 
master
Git Commit: 
ae314b666a1eb71de8872289ef3a298af09e4637
Python Version: 
Python 2.7.12
Any other relevant files/configs (eg: path files)

**Comment by mjmadsen** [comment]
@ravenda900 Still having problems?
