### ISSUE TITLE
Bot walking on water?

### ISSUE THREAD

**Issue by razithekillers** [PokemonGoF/PokemonGo-Bot#4763]
### Expected Behavior
Bot walking on water?

### Actual Behavior
![image](https://cloud.githubusercontent.com/assets/20743071/17999424/d02f53e4-6bab-11e6-91ed-cf3debf89569.png)

### Other Information
OS: 
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by r3pek** [comment]
It's not walking... it's on ferry to cross the "river" O:-)

**Comment by kirikay** [comment]
better use FollowPath to avoid walking over water or thru buildings...

**Comment by zeronivram** [comment]
how to used new update?

**Comment by mjmadsen** [comment]
This is related to #4751
