### ISSUE TITLE
Log spammed with useless information (printing object: pokemon)

### ISSUE THREAD

**Issue by hectorcorral** [PokemonGoF/PokemonGo-Bot#4764]
### Expected Behavior
Log should only contain information about what the bot is actually doing when debug=false, not script steps etc...

### Actual Behavior
```print pokemon``` <--- WHY?
The log is spammed because the object 'pokemon' is printed without any logical reason.
Printed in class **MyMQTTClass** in method **mqtt_on_message** in file ```pokemongo_bot/event_handlers/social_handler.py``` at line 24.

#### EDIT
```print data``` <--- This one too
Same file, at line 74

### Output when issue occurred
{u'pokemon_id': 66, u'longitude': 8.628544279491454, u'expiration_timestamp_ms': 1472201662676, u'pokemon_name': u'Machop', u'latitude': 53.046631393331246, u'spawn_point_id': u'47b0d51018d', u'encounter_id': 6457268787903340605}
{u'pokemon_id': 16, u'longitude': 2.2888893782658952, u'expiration_timestamp_ms': 1472202359188, u'pokemon_name': u'Pidgey', u'latitude': 48.86312181304295, u'spawn_point_id': u'47e66fe4b2d', u'encounter_id': 17333531635999326957L}
{u'pokemon_id': 13, u'longitude': -122.40491513304501, u'expiration_timestamp_ms': 1472201766284, u'pokemon_name': u'Weedle', u'latitude': 37.78835965163472, u'spawn_point_id': u'80858088fd3', u'encounter_id': 8940159970307643613}
{u'pokemon_id': 104, u'longitude': -15.431473925529767, u'expiration_timestamp_ms': 1472201755772, u'latitude': 28.124525283969206, u'spawn_point_id': u'0c40950cdef', u'encounter_id': 12858052982978725645L}
{u'pokemon_id': 114, u'longitude': -73.99572046066817, u'expiration_timestamp_ms': 1472201725132, u'pokemon_name': u'Tangela', u'latitude': 40.73478372641785, u'spawn_point_id': u'89c259979db', u'encounter_id': 12273509720898490893L}
{u'pokemon_id': 13, u'longitude': -73.99572046066817, u'expiration_timestamp_ms': 1472202298932, u'pokemon_name': u'Weedle', u'latitude': 40.735169810311724, u'spawn_point_id': u'89c259979a5', u'encounter_id': 3086800281945465853}
{u'pokemon_id': 16, u'longitude': 9.189030093384213, u'expiration_timestamp_ms': 1472202432900, u'pokemon_name': u'Pidgey', u'latitude': 45.464018988614065, u'spawn_point_id': u'4786c6ac221', u'encounter_id': 14183982227785450093L}
{u'pokemon_id': 16, u'longitude': 9.18844264119969, u'expiration_timestamp_ms': 1472202162468, u'pokemon_name': u'Pidgey', u'latitude': 45.46473417889433, u'spawn_point_id': u'4786c6ac371', u'encounter_id': 6949830481900082045}
{u'pokemon_id': 54, u'longitude': 121.50671116466084, u'expiration_timestamp_ms': -1, u'pokemon_name': u'Psyduck', u'latitude': 25.13646168735932, u'spawn_point_id': u'3442ae44c15', u'encounter_id': 18389177561123753357L}
{u'pokemon_id': 22, u'longitude': -122.4107560767055, u'expiration_timestamp_ms': 1472202187020, u'pokemon_name': u'Fearow', u'latitude': 37.75752628440108, u'spawn_point_id': u'808f7e37a53', u'encounter_id': 2317694028186708781}
{u'pokemon_id': 29, u'longitude': -118.49529181876433, u'expiration_timestamp_ms': 1472201795956, u'pokemon_name': u'Nidoran F', u'latitude': 34.01912017582781, u'spawn_point_id': u'80c2a4cf205', u'encounter_id': 12222959468145136285L}
{u'pokemon_id': 16, u'longitude': -73.97634540988807, u'expiration_timestamp_ms': 1472202279508, u'pokemon_name': u'Pidgey', u'latitude': 40.76939459093573, u'spawn_point_id': u'89c258f3e4d', u'encounter_id': 13626634699559755277L}
{u'pokemon_id': 129, u'longitude': -122.47197791419082, u'expiration_timestamp_ms': 1472202335924, u'pokemon_name': u'Magikarp', u'latitude': 37.76958269504357, u'spawn_point_id': u'808587699cd', u'encounter_id': 11044124604299158989L}
{u'pokemon_id': 129, u'longitude': -122.3936748286729, u'expiration_timestamp_ms': 1472202364724, u'pokemon_name': u'Magikarp', u'latitude': 37.79851355995945, u'spawn_point_id': u'80858067655', u'encounter_id': 8752609263233208381}
2016-08-26 10:52:17,969 [  SpinFort] [INFO] [spun_pokestop] Spun pokestop Fresque Europe. Experience awarded: 50. Items awarded: {u'Pokeball': 4}
{u'pokemon_id': 73, u'longitude': -122.39402887232174, u'expiration_timestamp_ms': 1472201983116, u'pokemon_name': u'Tentacruel', u'latitude': 37.79818146193523, u'spawn_point_id': u'80858067693', u'encounter_id': 16907150306228699741L}
{u'pokemon_id': 13, u'longitude': -73.96890707541883, u'expiration_timestamp_ms': 1472202243836, u'pokemon_name': u'Weedle', u'latitude': 40.78963171250092, u'spawn_point_id': u'89c2589cfaf', u'encounter_id': 10453286979810929629L}
{u'pokemon_id': 21, u'longitude': -73.96853974281441, u'expiration_timestamp_ms': 1472202045364, u'pokemon_name': u'Spearow', u'latitude': 40.789810919520576, u'spawn_point_id': u'89c2589cfed', u'encounter_id': 2991479905837631965}
{u'pokemon_id': 19, u'longitude': -73.96872340920417, u'expiration_timestamp_ms': 1472202268260, u'pokemon_name': u'Rattata', u'latitude': 40.7898370222414, u'spawn_point_id': u'89c2589cfc1', u'encounter_id': 13255881439683076781L}
{u'pokemon_id': 129, u'longitude': 4.357653505429834, u'expiration_timestamp_ms': 1472202042236, u'pokemon_name': u'Magikarp', u'latitude': 52.01177252969623, u'spawn_point_id': u'47c5b5c3bc7', u'encounter_id': 13510818261010958429L}
{u'pokemon_id': 16, u'longitude': -87.61805941520565, u'expiration_timestamp_ms': 1472201915244, u'pokemon_name': u'Pidgey', u'latitude': 41.88243041657855, u'spawn_point_id': u'880e2b58863', u'encounter_id': 18053091628417806061L}

### Steps to Reproduce
Simply execute ./run.sh

### Other Information
OS: ArchLinux
Branch: master

### Possible solution
Simply comment it like this:
```# print pokemon```

#### EDIT
And this one too:
```# print data```

**Comment by askovpen** [comment]
update to latest revision or "enable_social": false` in config

**Comment by mjmadsen** [comment]
What @askovpen said.
