### ISSUE TITLE
[FeatureRequest] Evolve pokemon exception

### ISSUE THREAD

**Issue by askovpen** [PokemonGoF/PokemonGo-Bot#4767]
I need evolve pokemons, except some pokemons, eg:

```js
{
  "type": "EvolvePokemon",
  "config": {
    "enabled": true,
    "evolve_all": "all",
    "first_evolve_by": "iv",
    "evolve_above_cp": 500,
    "evolve_above_iv": 0.9,
    "logic": "or",
    "min_evolve_speed": 25,
    "max_evolve_speed": 30,
    "use_lucky_egg": false,
    "except": "Zubat,Rattata"
  }
}

**Comment by nugrahawahyu** [comment]
+1

**Comment by danielmouraa** [comment]
It would be a nice feature, if we could evolve only the first evolution of the pokemon.

Example: 
`  
"type": "EvolvePokemon",
  "config": {
    "enabled": true,
    "evolve_all": "all",
    "first_evolve_by": "iv",
    "evolve_above_cp": 500,
    "evolve_above_iv": 0.9,
    "logic": "or",
    "min_evolve_speed": 25,
    "max_evolve_speed": 30,
    "use_lucky_egg": false,
    "max_evolution_stage": "1"
  }
`

**Comment by mjmadsen** [comment]
You can do it the other way around by adding specific pokemon to evolve_all. Most people set evolve_all to common pokemon (for exp) and save the candy for non common. 

Can I ask why you wouldn't want to evolve zubats and rattatas?

**Comment by askovpen** [comment]
i don't want write my common pokemons, because i write zubata and rattata :-)

**Comment by mjmadsen** [comment]
What?

**Comment by askovpen** [comment]
e.g. i want evolve all pokemons for exp, but i have best Magikarp with 0.7 iv. I don't want waste 400 candy for evolve Magikarp. i want wait Magikarp with more iv to evolve.

**Comment by mjmadsen** [comment]
So that is what I am saying. Don't list magikarp in evolve_all.

> "evolve_all": "zubat, rattata, pidgey, drowzee",

Evolves only zubat, rattata, pidgey and drowzee.

**Comment by askovpen** [comment]
ok. my config:
```
"evolve_all": "Abra,Bellsprout,Bulbasaur,Caterpie,Charmander,Charmeleon,Clefairy,Cubone,Diglett,Doduo,Dragonair,Dratini,Drowzee,Eevee,Ekans,Exeggcute,Gastly,Geodude,Gloom,Goldeen,Graveler,Grimer,Growlithe,Haunter,Horsea,Ivysaur,Jigglypuff,Kabuto,Kadabra,Kakuna,Koffing,Krabby,Machoke,Machop,//Magikarp,Magnemite,Mankey,Meowth,Metapod,Nidoran F,Nidoran M,Nidorina,Nidorino,Oddish,Omanyte,Paras,Pidgeotto,Pidgey,Pikachu,Poliwag,Poliwhirl,Ponyta,Psyduck,Rattata,Rhyhorn,Sandshrew,Seel,Shellder,//Slowpoke,Spearow,Squirtle,Staryu,Tentacool,Venonat,Voltorb,Vulpix,Wartortle,Weedle,Weepinbell,Zubat",
```

**Comment by askovpen** [comment]
more like config:
```
"evolve_all": "all",
"except": "Magikarp,Slowpoke"
```

**Comment by mjmadsen** [comment]
I put a tag for this as a Feature Request. As I said, I realize that isn't exactly how you want to go about it, but I gave you a solution given the current setup. If you want to reduce the config to your latter post, you'll have to wait for the requested feature to get finished.

**Comment by askovpen** [comment]
```
"config": {
  "enabled": true,
  "min_evolve_speed": 25,
  "max_evolve_speed": 30,
  "use_lucky_egg": false,
  "rules": {
    "any": {"evolve_above_cp": 1, "evolve_above_iv": 0.1, "logic": "or"},
   "Magikarp": {"evolve_above_cp": 5000, "avolve_about_iv": 0.95, "logic": "or"}
  }
}
```

**Comment by mjmadsen** [comment]
@askovpen Merged. Check it out!
