### ISSUE TITLE
[DEV] Errors in config.example.json

### ISSUE THREAD

**Issue by Bashin** [PokemonGoF/PokemonGo-Bot#4768]
### Expected Behavior

Start bot with unmodified config.example.json without errors.

### Actual Behavior

1 - Warning on startup.
2 - RandomAlivePause output even though disabled by default.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

Unmodified config.example.json.

### Output when issue occurred

1:
2016-08-26 13:04:57,681 [cli] [WARNING] The daily_catch_limit argument has been moved into the CatchPokemon Task

2:
2016-08-26 13:05:02,305 [RandomAlivePause] [INFO] [next_random_alive_pause] Next random alive pause at 14:32:13, for a duration of 0:08:38

### Steps to Reproduce

Run the bot.

### Other Information

OS: WIN10 64bit
Branch: dev
Git Commit: Fix shelve key error (09403f5)
Python Version: 2.7.12

**Comment by cbogithub** [comment]
run git pull to update bot

**Comment by Bashin** [comment]
I am on the latest commit.. no need to update

**Comment by acurioustale** [comment]
See #4742.

Unfortunately the example configurations haven't been updated accordingly.

Move `"daily_catch_limit": 800,` into the CatchPokemon task.

**Comment by alexyaoyang** [comment]
1 has been fixed. Just did a quick test on 2, seems like the the random alive pause is scheduled, but when the time comes, it does not pause if the task is disabled. Can someone confirm?

**Comment by mjmadsen** [comment]
@Bashin How is it going?
