### ISSUE TITLE
[Query/Issue] Maximum distance from start point based on step size and diameter?

### ISSUE THREAD

**Issue by pranavperfect** [PokemonGoF/PokemonGo-Bot#4770]
### Expected Behavior
The step size in my config file is set at 20 and the diameter is set at 2. I'd expect the bot to stay quiet close to the starting point. 

### Actual Behavior
However, at present instance it is 6.3 miles away from starting location.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
Start location: Santa Monica Pier, Santa Monica
Present location: Rancho Park Golf Course, Los Angeles
Step_size: 20
Diameter: 2

### Output when issue occurred
N/A

### Steps to Reproduce
Just let bot run for long duration.

### Other Information
OS: 
 
Branch: 
Master
Git Commit: 
latest
Python Version: 
2.3.6

**Comment by pranavperfect** [comment]
If there is no maximum distance from start point, can that be made into a feature request?

**Comment by mjmadsen** [comment]
#3580 has a FR for this.
