### ISSUE TITLE
[Query/Feature Request] Reload config from time to time

### ISSUE THREAD

**Issue by pranavperfect** [PokemonGoF/PokemonGo-Bot#4773]
### Short Description
If i make changes to config.json, i shouldn't have to restart the bot to reload the config file

### Possible solution
Reload config file at fixed time intervals (possibly Hourly)

### How it would help others
If i come across an area with excess of one pokemon that is not in my evolution list, i can add it to evolution list and it will get reloaded and then i can have its evolutions soon.

**Comment by maxprzemo** [comment]
It is already added
    "live_config_update": {
      "enabled": false,
      "tasks_only": false
    },

Just turn on

    "live_config_update": {
      "enabled": true,
      "tasks_only": false
    },

**Comment by Gzerox** [comment]
mh, i was starting to write down some code about this.
@maxprzemo on dev i can't find anything about "live_config_update" neither on pull request.
Am i missing something ?

**Comment by maxprzemo** [comment]
Compare your file config.json with config.json.example
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/configs/config.json.example#L14

**Comment by Gzerox** [comment]
You're right.
But, Why if i use "search on repository" the string "live_config_update", does not show anything about it? :\

**Comment by pranavperfect** [comment]
In that case, i will just close the issue and wait for the dev to be merged with master as i'm relying on using the master branch.

Many thanks @maxprzemo

**Comment by maxprzemo** [comment]
It is added only here https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokecli.py#L127
and here https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokecli.py#L625
