### ISSUE TITLE
Bot not trasfering any pokemon even with full bag

### ISSUE THREAD

**Issue by rdeeb** [PokemonGoF/PokemonGo-Bot#4774]
### Expected Behavior
The bot should transfer the pokemon when the amount left in the pokemon bag is less or equal to the ```min_free_slot```config

### Actual Behavior
The bot doesn't start the transfer procedure

### Your FULL config.json 
http://pastebin.com/rxTyrFdV

### Output when issue occurred
```
2016-08-26 09:46:14,597 [PokemonCatchWorker] [INFO] [pokemon_inventory_full] Your Pokemon inventory is full! Could not catch!
```
![screen shot 2016-08-26 at 10 22 30 am](https://cloud.githubusercontent.com/assets/456490/18010760/85f16422-6b77-11e6-8560-701791dce0aa.png)

### Steps to Reproduce
Set the bot to run on a full pokemon bag

### Other Information
OS: 
**Mac OS X 10.11.3**
Branch: 
**dev**
Git Commit: 
**09403f5ff023f98086f97f647beb344b89188ae0**
Python Version: 
**Python 2.7.10**
Any other relevant files/configs (eg: path files) 
**None**

**Comment by danijov88** [comment]
I have the same issue, using linux.

**Comment by mjmadsen** [comment]
@danijov88 were you also using keep best custom?

**Comment by danijov88** [comment]
@mjmadsen sorry for late reply.. I use the default config, no changes.

**Comment by mjmadsen** [comment]
@danijov88 Your bag is fuller than the minimum you have set?

@rdeeb I think there are issues with the keep best custom release tag.

**Comment by mjmadsen** [comment]
#4689
