### ISSUE TITLE
No XP walking to to the next pokestop

### ISSUE THREAD

**Issue by goodmorning1234** [PokemonGoF/PokemonGo-Bot#4775]
It shows that waling to the next pokestop at {XXXX,XXXXX) using realistic ROAD_WALK routes. Gained 0 XP. 
Anyone knows how to resolve this issue?

**Comment by rdeeb** [comment]
Walking don't yield XP, spinning Pokestops or capturing Pokemon does.

**Comment by goodmorning1234** [comment]
@rdeeb But it seems that I haven been in the same place for a very long time. It shows "walking to the next pokestop at {XXXX,XXXXX) using realistic ROAD_WALK routes. Gained 0 XP" thousands of times.

**Comment by mjmadsen** [comment]
Please actually post logs and fill out the issue template.
