### ISSUE TITLE
[Suggestion] Parameter to not transfer if IV is higher than current highest

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [PokemonGoF/PokemonGo-Bot#478]
Currently, we set a hardwritten IV requirement that needs to be met for a pokemon NOT to be transferred. This would mean that if you don't already have the pokemon, if the IV is too low, it wont be kept anyway..

Wouldn't it be more logical to look at the Pokemon you currently have, and then determine which has the highest IV and transfer the lower one(s)?

**Comment by lpalbyrodri** [comment]
This would be great.

**Comment by celinereine** [comment]
Where is the transfer code? I can maybe try writing some simple if comparisons to see if it'll work? Sorry, I'm so new at this.

**Comment by pol0nium** [comment]
@celinereine https://github.com/PokemonGoF/PokemonGo-Bot/blob/17db0f5bf6b8c4650f1e48fb65bce71e673d8a51/pokemongo_bot/cell_workers/pokemon_catch_worker.py#L133

**Comment by celinereine** [comment]
@pol0nium Is this where the "initial transfer" logic is placed? It looks like it's for catching pokemon parameters. Sorry for being such an amateur lol

**Comment by celinereine** [comment]
Do you think that line of code would be better if it were:
if cp < self.config.cp **&&** pokemon_potential < self.config.pokemon_potential:

That way when catching pokemon, if the IV were 100 but it were less than the cp specified, the pokemon would still be kept?

**Comment by pol0nium** [comment]
This [PR](https://github.com/PokemonGoF/PokemonGo-Bot/pull/448) will change the release logic.

**Comment by pol0nium** [comment]
@celinereine [initial transfer logic](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/__init__.py#L212)

**Comment by CapCap** [comment]
exists in current dev
