### ISSUE TITLE
Separate account from base configs

### ISSUE THREAD

**Issue by mjmadsen** [PokemonGoF/PokemonGo-Bot#4781]
We should have an account file with just the following:
`{
    "auth_service": "",
    "username": "",
    "password": "",
    "location": "",
    "gmapkey": "",
    "encrypt_location": "",
    "config_location": ""
}`

Then the config_location is our base settings. We update the configs a whole lot and if you have multiple bots, that can be a lot of editing if you want to change default values. 

Though, I still yearn for allowing us to enter a series of accounts we automatically switch between every so often. Decisions implementing this could make that easier or possibly harder. 

Feedback welcomed.

**Comment by solderzzc** [comment]
yes, very needed. Since the merging of work config and account config, I've done much work on the copy between configuration files.

**Comment by alexyaoyang** [comment]
Agreed, having an account file will make things a lot easier for both new users and old. Your idea of switching between series of bot accounts **might** be easier with the live update code.

**Comment by solderzzc** [comment]
It can't be real! https://github.com/PokemonGoF/PokemonGo-Bot/pull/4793 works as charming

**Comment by mjmadsen** [comment]
Awesome. Thanks you @rawgni
