### ISSUE TITLE
[Issue] Bot gets stuck randomly at any activity

### ISSUE THREAD

**Issue by pranavperfect** [PokemonGoF/PokemonGo-Bot#4785]
### Expected Behavior
Perform activities non stop unless it is taking a break/sleep

### Actual Behavior
It gets stuck at a point for quite some time. If i press any key on the command prompt after it gets stuck, it resumes.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
N/A

### Output when issue occurred
**2016-08-26 15:38:51,344** [PokemonCatchWorker] [INFO] [threw_pokeball] Great throw! Used Pokeball, with chance 37.43 (36 left)
**2016-08-26 15:38:51,713** [PokemonCatchWorker] [INFO] [pokemon_capture_failed] Nidoran M capture failed.. trying again!
2016-08-26 15:39:01,492 [PokemonCatchWorker] [INFO] [threw_pokeball] Nice throw! Used Pokeball, with chance 37.43 (35 left)
2016-08-26 15:39:01,687 [PokemonCatchWorker] [INFO] [pokemon_capture_failed] Nidoran M capture failed.. trying again!
**2016-08-26 15:39:08,133** [PokemonCatchWorker] [INFO] [threw_pokeball] Great throw! Used Pokeball, with chance 37.43 (34 left)
**2016-08-26 15:58:42,814** [PokemonCatchWorker] [INFO] [pokemon_capture_failed] Pokeball thrown to Nidoran M missed.. trying again!
**2016-08-26 15:58:51,307** [PokemonCatchWorker] [INFO] [threw_pokeball] Excellent Curveball throw! Used Pokeball, with chance 37.43 (33 left)
**2016-08-26 15:58:51,529** [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Nidoran M! [CP 357] [NCP 0.42] [Potential 0.8] [6/15/15] [+210 exp]

### Steps to Reproduce
Unknown. Happens randomly. Has happened multiple times in the past though.

### Other Information
OS: Win 10
Branch: 
Master 
Git Commit: 
ae314b666a1eb71de8872289ef3a298af09e4637 
Python Version: 
2.3.6

**Comment by crvfts** [comment]
This was happening to me previously (no longer occurring on current dev). I found that usually when UpdateLiveInventory logged that it would suddenly log everything else that happened in between (never more than a handful of actions).

There were a few times I returned to my computer to find the completely had completely froze, though.

**Comment by mjmadsen** [comment]
@pranavperfect looks like local issues
