### ISSUE TITLE
"Keep_best_custom" preventing from transferring all pokemon selected

### ISSUE THREAD

**Issue by sfbakin** [PokemonGoF/PokemonGo-Bot#4792]
Running latest dev, notice I was pokemon slots full but had free slots set to 200.
After troubleshooting with slack I removed this line

"Magikarp": {"keep_best_custom": "iv, cp, hp_max", "amount":5}
  
And it allowed the bot to then transfer out over 100 karp instead of the five I wanted to keep. 

Win10 latest dev build.

Thanks!

**Comment by doctordo0m** [comment]
I do not really understand your problem, it might be helpful, if you filled out the Issue/Feature request template, that appears when you create a new issue. Keep that in mind for next time at least.

So, what was the expected behaviour, and what happened?

**Comment by mjmadsen** [comment]
#4689 keep_best_custom doesn't work right now.
