### ISSUE TITLE
moving_to_pokemon_through_port instead of teleporting 

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#4799]
### Expected Behavior
The bot should teleport to Pokemon, then teleport back and catch

### Actual Behavior
in two occasions (both Snorlax) it keep moving to it (and of course not reaching it

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/XzFy46Tv

### Output when issue occurred
http://pastebin.com/Zwb4Bi9X

### Other Information
OS: OSX Capita 
Branch: dev
Git Commit: 
aa1c7811737cb3390b9e8d74d342adcae50112f9
Python Version: Python 2.7.12

**Comment by sohje** [comment]
@Gurzeh Seems Snorlax not added to catch option and have no priority like
```js
        "Mew":      1000,
        "Mewtwo":   1000,
        "Moltres":  1000,
        "Tauros":   1000,
        "Zapdos":   1000,
```
Cause you have option
```js
"snipe_high_prio_only": true,
```
Bot just ignore snipping functionality.

**Comment by Gurzeh** [comment]
@sohje thx buddy!

**Comment by sohje** [comment]
@Gurzeh no problem ;}
