### ISSUE TITLE
Removing date/time from bot output

### ISSUE THREAD

**Issue by nirvana7777** [PokemonGoF/PokemonGo-Bot#4800]
### Expected Behavior

Moving towards pokestop Keppel Island Marina - 0.14km

### Actual Behavior

2016-08-27 18:04:19,285 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Keppel Island Marina - 0.14km

### Steps to Reproduce

I have tried looking for the doc where I can fix this issue but can't find it.

### Other Information
OS: Arch 32bit
 
Branch: master
 
Git Commit: 
 
Python Version: python2
 
Any other relevant files/configs (eg: path files)

**Comment by lntn** [comment]
what is the problem?

**Comment by nirvana7777** [comment]
Problem is how to remove "<date> <time> " from bot line outputs. Thank you.

**Comment by nirvana7777** [comment]
remove " (date) (time) " *

**Comment by nirvana7777** [comment]
I want it to be " moving towards pokestop XXX - X.Xkm "

Instead of " (date) (time) moving towards pokestop XXX - X.Xkm "

**Comment by lntn** [comment]
I believe date, time, component's name & action is the standard log output template and there's very little reason we should remove them.

**Comment by mjmadsen** [comment]
We can mark it as a feature request. Some folks might like this!

**Comment by Gurzeh** [comment]
I agree. It should be possible to remove this info - even if I DO find it useful

**Comment by rawgni** [comment]
@nirvana7777 
```python
 62 logging.basicConfig(
 63     level=logging.INFO,
 64     format='%(asctime)s [%(name)10s] [%(levelname)s] %(message)s')
 65 logger = logging.getLogger('cli')
```
change line 64 to `format='%(message)s'`

**Comment by lntn** [comment]
ok I'm not familiar with Python and not much with git, so if someone gonna do this, you may add a new config "simplified_log" with default value false to make it more flexible.

**Comment by nirvana7777** [comment]
@rawgnii Thank you !

**Comment by Gobberwart** [comment]
See PR #4832 for improved version of this

**Comment by mjmadsen** [comment]
Merged to dev!
