### ISSUE TITLE
random() for hit rate is not accurate

### ISSUE THREAD

**Issue by Gurzeh** [PokemonGoF/PokemonGo-Bot#4805]
Expected Behavior
the throw should be 90% ("hit_rate": 0.9)

Actual Behavior
in fact, random() - which is used to code the % 
if random() >= self.catch_throw_parameters_hit_rate
- gives inaccurate results (this is know behavior)
check the log for actual result

Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/XzFy46Tv

Output when issue occurred
http://pastebin.com/d47ZqyjF

Other Information

OS: OSX Capitan
Branch: dev
Git Commit: 
aa1c7811737cb3390b9e8d74d342adcae50112f9
Python Version: Python 2.7.12

**Comment by maxprzemo** [comment]
@Gurzeh
On 13 shots did not hit only 4 ([pokemon_capture_failed] Pokeball thrown to Pikachu missed.. trying again!)
The rest depends on Capture Probability https://docs.google.com/spreadsheets/d/1Jj4_DGoaI-KZsm7vqNv1RVi3tZWrjiFoSPagwO9qfQM/pubhtml#

**Comment by mjmadsen** [comment]
hit_pokemon = 1
            if random() >= self.catch_throw_parameters_hit_rate and not is_vip:
                hit_pokemon = 0

Looks fine to me. random() generates a number between 0 and 1.

**Comment by mjmadsen** [comment]
Check out the reply to this question:
http://stackoverflow.com/questions/2145510/random-is-barely-random-at-all

**Comment by mjmadsen** [comment]
While random might not return that all of random results, we won't do too much better in the python library. Over the long hall, it is sufficient for our needs. We're not sending credit card information or anything.
