### ISSUE TITLE
no moudle named pgoapi

### ISSUE THREAD

**Issue by TheOwl99** [PokemonGoF/PokemonGo-Bot#4812]
Traceback (most recent call last):
  File "pokecli.py", line 43, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetException
ImportError: No module named pgoapi.exceptions

 Something went wrong and the bot needed to be restarted. Please investigate the cause.

i got this error everytime I'm trying to start the program

**Comment by davidspeijer** [comment]
I had it also this morning.

`pip install -r requirements.txt --upgrade`

Solved it for me

**Comment by TheOwl99** [comment]
where do i put it? I am in windows

**Comment by updatesvc** [comment]
run that  code in cmd with this folder "Pokemone-Bot" as the Parent

**Comment by TheOwl99** [comment]
i tried to do this and it gave me this error at the end:
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\endofall\\appdata\\local\\temp\\pip-build-ouaegc\\xxhash\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\endofall\appdata\local\temp\pip-ofpali-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\endofall\appdata\local\temp\pip-build-ouaegc\xxhash\

**Comment by cbogithub** [comment]
install git, pip
run python.exe -m pip install -r requirements.txt
then python.exe -m pip install -r requirements.txt --upgrade

**Comment by mjmadsen** [comment]
@TheOwl99 Still need help?

**Comment by mjmadsen** [comment]
Closing #4812
