### ISSUE TITLE
No Module named telegram

### ISSUE THREAD

**Issue by avneetsb** [PokemonGoF/PokemonGo-Bot#4815]
Traceback (most recent call last):
  File "pokecli.py", line 46, in <module>
    from pokemongo_bot import inventory
  File "/Users/avneet/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 21, in <module>
    import cell_workers
  File "/Users/avneet/Desktop/PokemonGo-Bot/pokemongo_bot/cell_workers/__init__.py", line 26, in <module>
    from telegram_task import TelegramTask
  File "/Users/avneet/Desktop/PokemonGo-Bot/pokemongo_bot/cell_workers/telegram_task.py", line 2, in <module>
    import telegram
ImportError: No module named telegram
Sat Aug 27 22:08:31 IST 2016 Pokebot  Stopped.

**Comment by askovpen** [comment]
pip install --upgrade -r requirements.txt

**Comment by avneetsb** [comment]
Tried that, and still the same...
Full terminal report below : 
Last login: Sat Aug 27 22:07:49 on ttys000
Avneets-MacBook-Air:~ avneet$ cd ~/Desktop/PO
-bash: cd: /Users/avneet/Desktop/PO: No such file or directory
Avneets-MacBook-Air:~ avneet$ cd ~/Desktop/PokemonGo-Bot/
Avneets-MacBook-Air:PokemonGo-Bot avneet$ git pull
Already up-to-date.
Avneets-MacBook-Air:PokemonGo-Bot avneet$ virtualenv .
New python executable in /Users/avneet/Desktop/PokemonGo-Bot/bin/python2.7
Not overwriting existing python script /Users/avneet/Desktop/PokemonGo-Bot/bin/python (you must use /Users/avneet/Desktop/PokemonGo-Bot/bin/python2.7)
Installing setuptools, pip, wheel...done.
Avneets-MacBook-Air:PokemonGo-Bot avneet$ pip install --upgrade -r requirements.txt 
Requirement already up-to-date: numpy==1.11.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: networkx==1.11 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Obtaining pgoapi from git+https://github.com/joelgreen/pgoapi.git/@fa49ada8570b0817c5a73b9315ba010fa7a47874#egg=pgoapi (from -r requirements.txt (line 3))
  Skipping because already up-to-date.
Requirement already up-to-date: geopy==1.11.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: protobuf==3.0.0b4 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: requests==2.10.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: requests-mock==1.0.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: s2sphere==0.2.4 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: gpsoauth==0.3.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already up-to-date: protobuf-to-dict==0.1.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already up-to-date: googlemaps==2.4.4 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 11))
Requirement already up-to-date: colorama==0.3.7 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 12))
Requirement already up-to-date: enum34==1.1.6 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 13))
Requirement already up-to-date: pyyaml==3.11 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 14))
Requirement already up-to-date: haversine==0.4.5 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 15))
Requirement already up-to-date: polyline==1.3.1 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 16))
Requirement already up-to-date: python-socketio==1.4.2 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 17))
Requirement already up-to-date: flask==0.11.1 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 18))
Requirement already up-to-date: socketIO_client==0.7.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 19))
Requirement already up-to-date: eventlet==0.19.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 20))
Requirement already up-to-date: gpxpy==1.1.1 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 21))
Requirement already up-to-date: mock==2.0.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 22))
Requirement already up-to-date: timeout-decorator==0.3.2 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 23))
Requirement already up-to-date: raven==5.23.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 24))
Requirement already up-to-date: demjson==2.2.4 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 25))
Requirement already up-to-date: greenlet==0.4.9 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 26))
Requirement already up-to-date: yoyo-migrations==5.0.3 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 27))
Requirement already up-to-date: paho-mqtt==1.2 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 28))
Requirement already up-to-date: Geohash==1.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 29))
Requirement already up-to-date: python-telegram-bot==5.0.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 30))
Requirement already up-to-date: decorator>=3.4.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from networkx==1.11->-r requirements.txt (line 2))
Requirement already up-to-date: future in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from pgoapi->-r requirements.txt (line 3))
Requirement already up-to-date: six in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from pgoapi->-r requirements.txt (line 3))
Requirement already up-to-date: xxhash in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from pgoapi->-r requirements.txt (line 3))
Requirement already up-to-date: setuptools in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from protobuf==3.0.0b4->-r requirements.txt (line 5))
Requirement already up-to-date: pycryptodomex>=3.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 9))
Requirement already up-to-date: python-engineio>=0.8.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from python-socketio==1.4.2->-r requirements.txt (line 17))
Requirement already up-to-date: click>=2.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 18))
Requirement already up-to-date: Werkzeug>=0.7 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 18))
Requirement already up-to-date: Jinja2>=2.4 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 18))
Requirement already up-to-date: itsdangerous>=0.21 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 18))
Requirement already up-to-date: websocket-client in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from socketIO_client==0.7.0->-r requirements.txt (line 19))
Requirement already up-to-date: funcsigs>=1; python_version < "3.3" in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from mock==2.0.0->-r requirements.txt (line 22))
Requirement already up-to-date: pbr>=0.11 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from mock==2.0.0->-r requirements.txt (line 22))
Requirement already up-to-date: contextlib2 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from raven==5.23.0->-r requirements.txt (line 24))
Requirement already up-to-date: python-slugify in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from yoyo-migrations==5.0.3->-r requirements.txt (line 27))
Requirement already up-to-date: iniherit in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from yoyo-migrations==5.0.3->-r requirements.txt (line 27))
Requirement already up-to-date: docutils>=0.3 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from Geohash==1.0->-r requirements.txt (line 29))
Requirement already up-to-date: urllib3>=1.10 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from python-telegram-bot==5.0.0->-r requirements.txt (line 30))
Requirement already up-to-date: certifi in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from python-telegram-bot==5.0.0->-r requirements.txt (line 30))
Requirement already up-to-date: MarkupSafe in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 18))
Requirement already up-to-date: Unidecode>=0.04.16 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from python-slugify->yoyo-migrations==5.0.3->-r requirements.txt (line 27))
Installing collected packages: pgoapi
  Running setup.py develop for pgoapi
Successfully installed pgoapi-1.1.8
Avneets-MacBook-Air:PokemonGo-Bot avneet$ source bin/activate
(PokemonGo-Bot) Avneets-MacBook-Air:PokemonGo-Bot avneet$ ./run.sh 
Traceback (most recent call last):
  File "pokecli.py", line 46, in <module>
    from pokemongo_bot import inventory
  File "/Users/avneet/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 21, in <module>
    import cell_workers
  File "/Users/avneet/Desktop/PokemonGo-Bot/pokemongo_bot/cell_workers/__init__.py", line 26, in <module>
    from telegram_task import TelegramTask
  File "/Users/avneet/Desktop/PokemonGo-Bot/pokemongo_bot/cell_workers/telegram_task.py", line 2, in <module>
    import telegram
ImportError: No module named telegram
Sat Aug 27 22:48:38 IST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

(PokemonGo-Bot) Avneets-MacBook-Air:PokemonGo-Bot avneet$

**Comment by askovpen** [comment]
```
Requirement already up-to-date: python-telegram-bot==5.0.0 in /Users/avneet/.pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 30))
```
i don't know :-\

**Comment by avneetsb** [comment]
:-\
Perhaps i'll just clone the repo again, but I highly doubt it will work :(
Anyways, thanks for looking into it @askovpen

**Comment by askovpen** [comment]
try `pip install --upgrade -r requirements.txt` after `source bin/activate`

**Comment by Gobberwart** [comment]
I don't use virtualenv, but wondering if this has anything to do with it:

```
New python executable in /Users/avneet/Desktop/PokemonGo-Bot/bin/python2.7
Not overwriting existing python script /Users/avneet/Desktop/PokemonGo-Bot/bin/python (you must use /Users/avneet/Desktop/PokemonGo-Bot/bin/python2.7)
```

Requirements being installed to an incorrect location maybe? Sorry, just guesswork.

**Comment by avneetsb** [comment]
Aha, gold !

Installing collected packages: pgoapi, urllib3, certifi, python-telegram-bot
  Running setup.py develop for pgoapi
Successfully installed certifi-2016.8.8 pgoapi-1.1.8 python-telegram-bot-5.0.0 urllib3-1.16

Danke @askovpen
