### ISSUE TITLE
Permanent Ban notifier [REQUEST]

### ISSUE THREAD

**Issue by updatesvc** [PokemonGoF/PokemonGo-Bot#4818]
### Short Description
I want to know if I am permanently banned..

### Possible solution
At the login procedure...an error like "possibly banned "should popup.

### How it would help others
Would save time for many bot user as they would now start with a fresh account.

**Comment by Gobberwart** [comment]
Once the bot is pretty sure a permaban has occurred, a message reading "Probably permabanned, Game Over !" is displayed.

That's based (as far as I can tell) on whether or not player inventory data can be successfully retrieved from the server.

Not sure if there is currently any other way to tell (even the legit app can't tell you if you're banned).
