### ISSUE TITLE
Bot doesn't login

### ISSUE THREAD

**Issue by phupabegim** [PokemonGoF/PokemonGo-Bot#482]
`pokecli.py -a google -u XXXXX -p XXXXX -c 1`

I get a message about the server being busy. I don't have 2FA enabled on my Google Account so it doesn't require an App password.

**Comment by pol0nium** [comment]
I think it's Niantic servers that are busy. Try to login again.

**Comment by phupabegim** [comment]
No luck yet :-(

**Comment by phupabegim** [comment]
Google was blocking the login as I'd never logged in on my VPS before, solved!
