### ISSUE TITLE
Telegram bot :wrong stats per day

### ISSUE THREAD

**Issue by orchid666** [PokemonGoF/PokemonGo-Bot#4829]
So im using the new telegram feature, and when i do a /info in the telegram app i get the stats of my bot including stats per day. 
Those stats per day sometime decrease for no apparent reason.
Example: At 3:45 PM i had "182 pokemons captured today". Then at 4:07PM i had "175 pokemons captured today". 
Maybe it removes the pokemons released from calculation?

**Comment by askovpen** [comment]
today - in 24 hour, not from start of day.

**Comment by orchid666** [comment]
Then could it be "past 24h" or something like that instead of "today"?. It might be misleading. Sorry if im being picky :)

**Comment by askovpen** [comment]
ok. rename in next patch

**Comment by orchid666** [comment]
Thanks :)
