### ISSUE TITLE
How to unban permanent ban of Pokemon Go Bot

### ISSUE THREAD

**Issue by LeonardoVilarinho** [PokemonGoF/PokemonGo-Bot#4834]
Is there any possibility to unban an account permanently banned Pokemon Go?

I used the bot, but recently was banned, wanted to unban the account to play, now without the bot. Because it is difficult for me to create a new account because I use Windows Phone (with PoGo).

My user banned: _leonardovilarinh_

Sorry for my English.

**Comment by IamCarbonMan** [comment]
You can submit a ban appeal to Niantic, but if they don't accept it you're out of luck: https://support.pokemongo.nianticlabs.com/hc/en-us/articles/225146308-Submit-a-ban-appeal

**Comment by Gobberwart** [comment]
Chances are they're pretty certain you've been botting or they wouldn't have banned you. Good luck, but I reckon you can kiss the account goodbye :(

**Comment by IamCarbonMan** [comment]
Yeah, permabans are pretty end-all. I mean, if their response to a month-old customer service request involving an actual bug in their game that caused a user to lose money, was "r"...

**Comment by Gobberwart** [comment]
"r" - Albert Einstein

**Comment by IamCarbonMan** [comment]
I think that one can stand without a citation. I mean, it's already on its way to becoming an urban legend...

But I'll give it to you anyways https://www.reddit.com/r/pokemongo/comments/4yikec/niantic_responded_to_my_help_ticket_after_35_days/

**Comment by th3w4y** [comment]
@IamCarbonMan thanks!
