### ISSUE TITLE
IncubateEggs task is incubating in breakable "2" (km)  when is configured only for "10" (km)

### ISSUE THREAD

**Issue by alexmuntean** [PokemonGoF/PokemonGo-Bot#4835]
### Expected Behavior

Breakable should incubate only 10 km eggs.
config:
```
{
        "type": "IncubateEggs",
        "config": {
          "enabled": true,
          "longer_eggs_first": true,
          "min_interval": 60,
         "infinite": [2,5,10],
         "breakable": [10]
        }
      },
```

### Actual Behavior

It incubates any eggs. I had only 2 km eggs

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/AYnhUu9p

### Other Information
OS: OSX latest
 
Branch: master
 
Git Commit: ed095936e8fb2bdb7442c9966630664f0cb739ea
 
Python Version: Python 2.7.9
 
Any other relevant files/configs (eg: path files)

**Comment by alexyaoyang** [comment]
Update to latest dev, this is fixed recently.

**Comment by Anakin5** [comment]
It is not, I am running on head right now and it is still incubating 5km egges in breakable:

```Eggs incubating: [4.49/5.0 km, 3.70/5.0 km, 3.34/5.0 km] (Eggs left: 6, Incubating: 3)```


```
		{
			"type": "IncubateEggs",
			"config": {
				"infinite_longer_eggs_first": false,
				"breakable_longer_eggs_first": true,
				"min_interval": 120,
				"infinite": [
					2,
					5,
					10
				],
				"breakable": [
					10
				]
			}
		},
```

**Comment by Anakin5** [comment]
After reading the code,it is quite clear where this bug (and other bugs) are:
- ``temp_ready_incubators```only contains the id of the incubator, and not the "uses_remaining" attributes. This cause breakable incubator to be treated as infinite ones and thus hatching eggs initially configured for the infinite only.
- If only one egg 10 km in the bag, and you have infinite and one free breakable incubator free, we are going to hatch it with a breakable incubator instead of the infinite one. It is not an optimized decision.

**Comment by alexyaoyang** [comment]
Ping @rawgni

**Comment by mjmadsen** [comment]
Merged to dev.
