### ISSUE TITLE
MoveToMapPokemon not working from master

### ISSUE THREAD

**Issue by dummyaja** [PokemonGoF/PokemonGo-Bot#4837]
ISSUE

### Expected Behavior

Snipe / Teleport to  Pokemon position from PokemonGo-Map raw-data

### Actual Behavior

Nothing happen, never saw logs for teleporting to pokemon position in map

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

{
    "auth_service": "ptc",
    "username": "xxx",
    "password": "xxx",
    "location": "xxx, xxx",
    "favorite_locations":[
        {"name": "xxx", "coords": xxx, xxx"}
    ],
    "gmapkey": "xxx",
    "encrypt_location": "",
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": true,
    "live_config_update": {
      "enabled": true,
      "tasks_only": false
    },
    "tasks": [
      {
        "//NOTE: This task MUST be placed on the top of task list": {},
        "type": "RandomAlivePause",
        "config": {
          "enabled": true,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:05:00",
          "max_interval": "01:30:00"
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "RandomPause",
        "config": {
          "enabled": true,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:10:00",
          "max_interval": "02:00:00"
        }
      },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": true,
          "// set a name": "",
          "nickname": "botblaz1"
        }
      },
      {
        "type": "CollectLevelUpReward",
        "config": {
          "collect_reward": true,
          "level_limit": -1
        }
      },
      {
        "type": "IncubateEggs",
        "config": {
          "enabled": true,
          "longer_eggs_first": true,
          "min_interval": 120,
         "infinite": [2,5,10],
         "breakable": [2,5,10]
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": true,
          "min_interval": 23,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "level"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": true,
          "min_interval": 124,
          "show_all_multiple_lines": false,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
        }
      },
      {
        "type": "ShowBestPokemon",
        "config": {
          "enabled": true,
          "min_interval": 65,
          "amount": 5,
          "order_by": "cp",
          "info_to_show": ["cp", "ivcp", "dps", "hp"]
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "enabled": true,
          "min_free_slot": 999,
          "transfer_wait_min": 3,
          "transfer_wait_max": 5
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": true,
          "nickname_above_iv": 0.7,
          "nickname_template": "{name}_{ivcp_pct2}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "enabled": true,
          "evolve_all": "all",
          "first_evolve_by": "cp",
          "evolve_above_cp": 1600,
          "evolve_above_iv": 0.99,
          "logic": "and",
          "min_evolve_speed": 25,
          "max_evolve_speed": 30,
          "use_lucky_egg": true
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":     {"keep": 60},
            "Greatball":    {"keep": 60},
            "Ultraball":    {"keep": 60},
            "Masterball":   {"keep": 60},
            "Potion":       {"keep": 20},
            "Super Potion": {"keep": 20},
            "Hyper Potion": {"keep": 20},
            "Revive":       {"keep": 10},
            "Razz Berry":   {"keep": 40},
            "Bluk Berry":   {"keep": 20},
            "Nanab Berry":  {"keep": 20},
            "Wepar Berry":  {"keep": 20},
            "Pinap Berry":  {"keep": 20}
          },
          "recycle_wait_min": 3,
          "recycle_wait_max": 5,
          "recycle_force": true,
          "recycle_force_min": "00:01:00",
          "recycle_force_max": "00:05:00"
        }
      },
      {
        "type": "CatchPokemon",
        "config": {
          "enabled": true,
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 5,
          "berry_threshold": 0.35,
          "vip_berry_threshold": 0.9,
          "treat_unseen_as_vip": true,
          "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.5,
            "nice_rate": 0.3,
            "normal_rate": 0.1,
            "spin_success_rate" : 0.6,
            "hit_rate": 0.75
          },
          "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 3,
            "catch_wait_max": 6,
            "berry_wait_min": 3,
            "berry_wait_max": 5,
            "changeball_wait_min": 3,
            "changeball_wait_max": 5,
            "newtodex_wait_min": 20,
            "newtodex_wait_max": 30
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "enabled": true,
          "spin_wait_min": 3,
          "spin_wait_max": 5
        }
      },
      { "type": "UpdateWebInventory",
        "config": {
          "enabled": true
        }
      },
      {
       	"type": "MoveToMapPokemon",
        "config": {
          "enabled": true,
          "address": "http://localhost:5000",
          "max_distance": 500,
          "min_ball": 50,
          "prioritize_vips": true,
          "snipe": true,
          "snipe_high_prio_only": true,
          "snipe_high_prio_threshold": 300,
          "update_map": true,
          "mode": "priority",
          "map_path": "raw_data",
          "walker": "StepWalker",
          "max_extra_dist_fort": 10,
          "catch": {
            "==========Legendaries==========": 0,
            "Aerodactyl": 1000,
            "Snorlax": 1000,
            "Articuno": 1000,
            "Zapdos": 1000,
            "Moltres": 1000,
            "Dratini": 1000,
            "Dragonair": 1000,
            "Dragonite": 1000,
            "Mewtwo": 1000,
            "Mew": 1000,

            "==========Region Locked==========": 0,
            "Farfetch'd": 1000,
            "Kangaskhan": 1000,
            "Mr. Mime": 1000,
            "Tauros": 1000,

            "==========Very Rare==========": 0,
            "Lapras": 900,
            "Electabuzz": 900,
            "Magmar": 900,
            "Ditto": 900,

            "==========Starters==========": 0,
            "Bulbasaur": 400,
            "Ivysaur": 600,
            "Venusaur": 1000,

            "Charmander": 400,
            "Charmeleon": 600,
            "Charizard": 1000,

            "Squirtle": 400,
            "Wartortle": 600,
            "Blastoise": 1000,

            "Pikachu": 600,
            "Raichu": 1000,

            "==========Semi Rare==========": 0,
            "Jynx": 200,

            "==========Uncommon==========": 0,

            "Omastar": 500,

            "Dewgong": 500,

            "Muk": 500,

            "Cloyster": 500,

            "Gengar": 1000,

            "Onix": 600,

            "Drowzee": 600,

            "Hypno": 600,

            "Arcanine": 700,

            "Tentacruel": 500,

            "Primeape": 500,

            "Clefable": 500,

            "Wigglytuff": 500,

            "Dugtrio": 500,

            "Golduck": 500,

            "Graveler": 500,
            "Golem": 800,

            "Vaporeon": 800,
            "Jolteon": 800,
            "Flareon": 800,

            "Kabutops": 500,

            "Magikarp": 350,
            "Gyarados": 800,

            "Rapidash": 500,

            "Slowbro": 500,

            "Magneton": 500,

            "Electrode": 500,

            "Exeggcutor": 500,

            "Marowak": 800,

            "Hitmonlee": 400,

            "Hitmonchan": 400,

            "Lickitung": 500,

            "Weezing": 500,

            "Rhydon": 500,

            "Chansey": 800,

            "Seadra": 600,

            "Seaking": 500,

            "==========T2 Evolvers==========": 0,
            "Vileplume": 600,

            "Poliwrath": 800,

            "Abra": 300,
            "Kadabra": 600,
            "Alakazam": 800,

            "Pinsir": 350,

            "Machoke": 400,
            "Machamp": 800
          }
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "enabled": true,
          "lure_attraction": true,
          "lure_max_distance": 2000,
          "walker": "StepWalker"
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "enabled": true,
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "pokemon_bag": {
      "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
      "show_at_start": true,
      "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
      "show_count": true,
      "// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
      "show_candies": true,
      "// 'pokemon_info' parameter define which info to show for each pokemon": {},
      "// the available options are": {},
      "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
      "pokemon_info": ["cp", "iv_pct"]
    },
    "walk_max": 5.16,
    "walk_min": 3.16,
    "alt_min": 500,
    "alt_max": 1000,
    "sleep_schedule": [
      {
        "time": "12:00",
        "duration": "4:30",
        "time_random_offset": "00:30",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      },
      {
        "time": "17:45",
        "duration": "2:00",
        "time_random_offset": "01:00",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      }
    ],
    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": false,
    "replicate_gps_z_noise": false,
    "gps_xy_noise_range": 0.000125,
    "gps_z_noise_range": 12.5,
    "debug": false,
    "test": false,
    "walker_limit_output": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging_color": true,
    "daily_catch_limit": 800,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"keep_best_cp": 1, "keep_best_iv": 1, "logic": "and"},
      "Rattata": {"always_release": true},
      "Pidgey": {"always_release": true},
      "Ekans": {"always_release": true},
      "Zubat": {"always_release": true},
      "Raticate": {"always_release": true},
      "Spearow": {"always_release": true},
      "Doduo": {"always_release": true},
      "Dodrio": {"always_release": true},
      "Staryu": {"always_release": true},
      "Caterpie": {"always_release": true},
      "Butterfree": {"always_release": true},
      "Weedle": {"always_release": true},
      "Metapod": {"always_release": true},
      "Kakuna": {"always_release": true},
      "Pidgeotto": {"always_release": true},
      "Nidoran F": {"always_release": true},
      "Nidoran M": {"always_release": true},
      "Clefairy": {"always_release": true},
      "Paras": {"always_release": true},
      "Meowth": {"always_release": true},
      "Krabby": {"always_release": true},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Keep no more than 3 best IV pokemon for every pokemon type": {},
      "// any": {"keep_best_iv": 3},
      "// Discard all pokemon in bag except 100 pokemon with best CP": {},
      "// all": {"keep_best_cp": 100},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3},
      "// Example of custom order of static criterion": {},
      "// Zubat": {"keep_best_custom": "iv, cp, hp_max", "amount":2}
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}

### Output when issue occurred
none

### Steps to Reproduce
1. ./setup.sh -u
2. ./run.sh
3. start pokemongo MAP

### Other Information
OS:  Ubuntu 16.04
 
Branch: Master
Git Commit: ed095936e8fb2bdb7442c9966630664f0cb739ea
Python Version: Python 2.7.12

**Comment by warxhead1** [comment]
i'm also having this issue on both master and dev branch. it doesn't give the error that it doesn't detect the map when it isn't running either

**Comment by daemonsyn** [comment]
Same here.

**Comment by sohje** [comment]
guys, set this:
```js
"social_enable": false
```

**Comment by dummyaja** [comment]
@sohje thanks, disable social_enable fix snipe problem

**Comment by Jasperrr91** [comment]
Snipe works but your config is broken. You need to change the value in:

`"max_distance": 500"`

To define the sniping range.
