### ISSUE TITLE
when capturing pokemon, adjust capture waits to account for pokemon blocks

### ISSUE THREAD

**Issue by duttonw** [PokemonGoF/PokemonGo-Bot#4840]
### Short Description
Somewhere in the application there must be a setting on how often and for how long a pokemon blocks pokeball throws. This unavailable capture from the application means normal users can't capture it at this time. But our bot may be sending in a threw pokeball capture call at this time and show up as an anomaly . #4114 

### Possible solution
When the bot starts getting into the high levels, capture misses need to go up and delays need to gradually increase unless the master settings file tells us what ratio the native application is triggering on. With low capture pokemon they usually trigger a curveball is required flag to capture as they made the straight pokeballs miss but the rate of this magic curve power is not 100% active unless on really low capture rate pokemon (deep red rings in game)

### How it would help others
With this change, the bot should not show up on the timings where no real player can capture pokemon at certain time intervals. this should reduce what logs they can scan to see if its a bot if they are using capture behaviours to flag for bots.

label: feature request

**Comment by leadboots5** [comment]
I'm going to tentatively say the bot accounts for this. There are plenty of times the bot will throw a nice/great/etc.. ball, but it won't hit. You can feel free to set the miss rate.

I won't close this as I'm not 100% sure I answered your question and maybe I'm missing what you're getting at.

            "hit_rate": 0.75
