### ISSUE TITLE
Info Button (on web) probelm

### ISSUE THREAD

**Issue by ermanherman** [PokemonGoF/PokemonGo-Bot#4846]
Hi there,

I having problem with when i click INFO button on submenu on webpage it should display my status, exp, and etc, but it not work. It will shown last action i do, for example i click on item, it will shown item in my inventory, but when i click on info it also will show item in my inventory.

Here error on my console (firefox)

`TypeError: self.user_data[self.settings.users[user_id]].stats[0] is undefined
main.js:315:13`

And for you info the data not updated, let say latest pokemon catch it not shown in pokemon list, untill i restart bot.

thanks

OS: Windows 8
Branch: master
Git Commit: ab5fb3540ac9312b5320bd0904e7faea170d7824
Python Version:  2.7.12

**Comment by Gobberwart** [comment]
This has all been fixed in dev.
