### ISSUE TITLE
Telegram documentation missing

### ISSUE THREAD

**Issue by takenek** [PokemonGoF/PokemonGo-Bot#4847]
Hello
Like everyday i just do git pull and i see new configuration option: telegram token
What is that? where i get this?
I try find here in readme but i don't see any information.

Best Regards

**Comment by 4IbWNsis3S** [comment]
Because even though the config objects are updated rapidly the config documentation itself stays around 15% completed.. The people who add the config objects do not document them and people who can reverse engineer the scripts to document them are typically too busy..

**Comment by mjmadsen** [comment]
The original request might shed some light on it #4353. Purpose is to remotely check a bot's progress. 

I'm also guilty of not updating all docs. Sorry!

**Comment by 4IbWNsis3S** [comment]
pokecli.py has all the config entries for anyone curious. Look for the series of "add_config" entries and there are some others in "attrs" below that. I don't have time to confirm this is all of them though. I didn't see "PokemonOptimizer", for example.

**Comment by askovpen** [comment]
[Telegram](https://telegram.org/)
[Getting Telegram Token](https://core.telegram.org/bots#6-botfather)

**Comment by mjmadsen** [comment]
@askovpen Could you put a PR in to update configuration_files.md with information about this feature?

**Comment by askovpen** [comment]
yes

**Comment by mjmadsen** [comment]
Thank you! :+1:
