### ISSUE TITLE
Lastest master: ImportError: No module named urllib.request

### ISSUE THREAD

**Issue by MrDibbley** [PokemonGoF/PokemonGo-Bot#4851]
### Expected Behavior
./run.sh executes without error

### Actual Behavior
pulled latest master, ran ./setup.sh -i to install and created the two config files

### Output when issue occurred
[root@centos PokemonGo-Bot]# ./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 46, in <module>
    from pokemongo_bot import inventory
  File "/tmp/PokemonGo-Bot/pokemongo_bot/__init__.py", line 22, in <module>
    import cell_workers
  File "/tmp/PokemonGo-Bot/pokemongo_bot/cell_workers/__init__.py", line 26, in <module>
    from telegram_task import TelegramTask
  File "/tmp/PokemonGo-Bot/pokemongo_bot/cell_workers/telegram_task.py", line 2, in <module>
    import telegram
  File "/tmp/PokemonGo-Bot/lib/python2.7/site-packages/telegram/__init__.py", line 44, in <module>
    from .inputfile import InputFile
  File "/tmp/PokemonGo-Bot/lib/python2.7/site-packages/telegram/inputfile.py", line 34, in <module>
    from future.moves.urllib.request import urlopen
ImportError: No module named urllib.request
Sun 28 Aug 10:11:43 BST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

### Other Information
OS: 
Centos 7
Branch: 
master
Python Version: 
2.7

**Comment by mjmadsen** [comment]
@askovpen is this the same problem as #4852?

**Comment by askovpen** [comment]
```
$ pip install --upgrade -r requirements.txt
```

**Comment by MrDibbley** [comment]
$ pip install --upgrade -r requirements.txt = same result

`[root@centos PokemonGo-Bot]# pip install --upgrade -r requirements.txt
Requirement already up-to-date: numpy==1.11.0 in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: networkx==1.11 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Obtaining pgoapi from git+https://github.com/joelgreen/pgoapi.git/@fa49ada8570b0817c5a73b9315ba010fa7a47874#egg=pgoapi (from -r requirements.txt (line 3))
  Skipping because already up-to-date.
Requirement already up-to-date: geopy==1.11.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: protobuf==3.0.0b4 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: requests==2.10.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: requests-mock==1.0.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: s2sphere==0.2.4 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: gpsoauth==0.3.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already up-to-date: protobuf-to-dict==0.1.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already up-to-date: googlemaps==2.4.4 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 11))
Requirement already up-to-date: colorama==0.3.7 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 12))
Requirement already up-to-date: enum34==1.1.6 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 13))
Requirement already up-to-date: pyyaml==3.11 in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 14))
Requirement already up-to-date: haversine==0.4.5 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 15))
Requirement already up-to-date: polyline==1.3.1 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 16))
Requirement already up-to-date: python-socketio==1.4.2 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 17))
Requirement already up-to-date: flask==0.11.1 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 18))
Requirement already up-to-date: socketIO_client==0.7.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 19))
Requirement already up-to-date: eventlet==0.19.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 20))
Requirement already up-to-date: gpxpy==1.1.1 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 21))
Requirement already up-to-date: mock==2.0.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 22))
Requirement already up-to-date: timeout-decorator==0.3.2 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 23))
Requirement already up-to-date: raven==5.23.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 24))
Requirement already up-to-date: demjson==2.2.4 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 25))
Requirement already up-to-date: greenlet==0.4.9 in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 26))
Requirement already up-to-date: yoyo-migrations==5.0.3 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 27))
Requirement already up-to-date: paho-mqtt==1.2 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 28))
Requirement already up-to-date: Geohash==1.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 29))
Requirement already up-to-date: python-telegram-bot==5.0.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 30))
Requirement already up-to-date: decorator>=3.4.0 in /usr/lib/python2.7/site-packages (from networkx==1.11->-r requirements.txt (line 2))
Requirement already up-to-date: future in /usr/lib/python2.7/site-packages (from pgoapi->-r requirements.txt (line 3))
Requirement already up-to-date: six in /usr/lib/python2.7/site-packages (from pgoapi->-r requirements.txt (line 3))
Requirement already up-to-date: xxhash in /usr/lib64/python2.7/site-packages (from pgoapi->-r requirements.txt (line 3))
Requirement already up-to-date: setuptools in /usr/lib/python2.7/site-packages (from protobuf==3.0.0b4->-r requirements.txt (line 5))
Requirement already up-to-date: pycryptodomex>=3.0 in /usr/lib64/python2.7/site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 9))
Requirement already up-to-date: python-engineio>=0.8.0 in /usr/lib/python2.7/site-packages (from python-socketio==1.4.2->-r requirements.txt (line 17))
Requirement already up-to-date: click>=2.0 in /usr/lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 18))
Requirement already up-to-date: Jinja2>=2.4 in /usr/lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 18))
Requirement already up-to-date: Werkzeug>=0.7 in /usr/lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 18))
Requirement already up-to-date: itsdangerous>=0.21 in /usr/lib/python2.7/site-packages (from flask==0.11.1->-r requirements.txt (line 18))
Requirement already up-to-date: websocket-client in /usr/lib/python2.7/site-packages (from socketIO_client==0.7.0->-r requirements.txt (line 19))
Requirement already up-to-date: funcsigs>=1; python_version < "3.3" in /usr/lib/python2.7/site-packages (from mock==2.0.0->-r requirements.txt (line 22))
Requirement already up-to-date: pbr>=0.11 in /usr/lib/python2.7/site-packages (from mock==2.0.0->-r requirements.txt (line 22))
Requirement already up-to-date: contextlib2 in /usr/lib/python2.7/site-packages (from raven==5.23.0->-r requirements.txt (line 24))
Requirement already up-to-date: python-slugify in /usr/lib/python2.7/site-packages (from yoyo-migrations==5.0.3->-r requirements.txt (line 27))
Requirement already up-to-date: iniherit in /usr/lib/python2.7/site-packages (from yoyo-migrations==5.0.3->-r requirements.txt (line 27))
Requirement already up-to-date: docutils>=0.3 in /usr/lib/python2.7/site-packages (from Geohash==1.0->-r requirements.txt (line 29))
Requirement already up-to-date: urllib3>=1.10 in /usr/lib/python2.7/site-packages (from python-telegram-bot==5.0.0->-r requirements.txt (line 30))
Requirement already up-to-date: certifi in /usr/lib/python2.7/site-packages (from python-telegram-bot==5.0.0->-r requirements.txt (line 30))
Requirement already up-to-date: MarkupSafe in /usr/lib64/python2.7/site-packages (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 18))
Requirement already up-to-date: backports.ssl_match_hostname in /usr/lib/python2.7/site-packages (from websocket-client->socketIO_client==0.7.0->-r requirements.txt (line 19))
Requirement already up-to-date: Unidecode>=0.04.16 in /usr/lib/python2.7/site-packages (from python-slugify->yoyo-migrations==5.0.3->-r requirements.txt (line 27))
Installing collected packages: pgoapi
  Running setup.py develop for pgoapi
Successfully installed pgoapi-1.1.8
[root@centos PokemonGo-Bot]# ./run.sh
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
From https://github.com/PokemonGoF/PokemonGo-Bot
   2832a37..d896a80  dev        -> origin/dev
Traceback (most recent call last):
  File "pokecli.py", line 46, in <module>
    from pokemongo_bot import inventory
  File "/tmp/PokemonGo-Bot/pokemongo_bot/__init__.py", line 22, in <module>
    import cell_workers
  File "/tmp/PokemonGo-Bot/pokemongo_bot/cell_workers/__init__.py", line 26, in <module>
    from telegram_task import TelegramTask
  File "/tmp/PokemonGo-Bot/pokemongo_bot/cell_workers/telegram_task.py", line 2, in <module>
    import telegram
  File "/tmp/PokemonGo-Bot/lib/python2.7/site-packages/telegram/__init__.py", line 44, in <module>
    from .inputfile import InputFile
  File "/tmp/PokemonGo-Bot/lib/python2.7/site-packages/telegram/inputfile.py", line 34, in <module>
    from future.moves.urllib.request import urlopen
ImportError: No module named urllib.request
Sun 28 Aug 11:46:15 BST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
`

**Comment by MrDibbley** [comment]
edited /PokemonGo-Bot/lib/python2.7/site-packages/telegram/inputfile.py line 34 from

from future.moves.urllib.request import urlopen

to

from urllib2 import urlopen

gets the bot running on centos 7 with python 2.7?

**Comment by askovpen** [comment]
try `pip install --upgrade -r requirements.txt` after bin/activate

**Comment by MrDibbley** [comment]
@askovpen same result

**Comment by askovpen** [comment]
show output of `pip install --upgrade python-telegram-bot==5.0.0`

**Comment by MrDibbley** [comment]
(PokemonGo-Bot) [root@centos PokemonGo-Bot]# pip install --upgrade python-telegram-bot==5.0.0
Requirement already up-to-date: python-telegram-bot==5.0.0 in ./lib/python2.7/site-packages
Requirement already up-to-date: future>=0.15.2 in ./lib/python2.7/site-packages (from python-telegram-bot==5.0.0)
Requirement already up-to-date: urllib3>=1.10 in ./lib/python2.7/site-packages (from python-telegram-bot==5.0.0)
Requirement already up-to-date: certifi in ./lib/python2.7/site-packages (from python-telegram-bot==5.0.0)

**Comment by MrDibbley** [comment]
from stackoverflow it maybe a python 2 v python 3 thing:

he urllib and urllib2 packages have been split into urllib.request , urllib.parse and urllib.error packages in Python 3.x. The latter packages do not exist in Python 2.x

hence changing to urllib2 works ?

**Comment by askovpen** [comment]
I create [Issue](https://github.com/python-telegram-bot/python-telegram-bot/issues/398)

**Comment by askovpen** [comment]
do you have `/tmp/PokemonGo-Bot/lib/python2.7/site-packages/future/moves/urllib/request.py` ?

**Comment by MrDibbley** [comment]
@askovpen  under moves there is no urllib folder only:

(PokemonGo-Bot) [root@centos moves]# ls -l
total 4
drwxr-xr-x. 2 root root  69 Aug 17 12:34 dbm
drwxr-xr-x. 2 root root  44 Aug 17 12:34 html
-rw-r--r--. 1 root root 407 Aug 17 12:34 __init__.pyc
drwxr-xr-x. 2 root root  43 Aug 17 12:34 test


Thanks

**Comment by askovpen** [comment]
pip install --force-reinstall future>=0.15.2

**Comment by askovpen** [comment]
pip install --upgrade --ignore-installed python-telegram-bot==5.0.0

**Comment by MrDibbley** [comment]
[root@centos PokemonGo-Bot]# pip install --force-reinstall future>=0.15.2
[root@centos PokemonGo-Bot]# pip install --upgrade --ignore-installed python-telegram-bot==5.0.0
Collecting python-telegram-bot==5.0.0
  Using cached python_telegram_bot-5.0.0-py2.py3-none-any.whl
Collecting future>=0.15.2 (from python-telegram-bot==5.0.0)
Collecting urllib3>=1.10 (from python-telegram-bot==5.0.0)
  Using cached urllib3-1.16-py2.py3-none-any.whl
Collecting certifi (from python-telegram-bot==5.0.0)
  Using cached certifi-2016.8.8-py2.py3-none-any.whl
Installing collected packages: future, urllib3, certifi, python-telegram-bot
Successfully installed certifi-2016.8.8 future-0.15.2 python-telegram-bot-5.0.0 urllib3-1.16
[root@centos PokemonGo-Bot]# ls /tmp/PokemonGo-Bot/lib/python2.7/site-packages/future/moves/
dbm  html  __init__.pyc  test
[root@centos PokemonGo-Bot]#

**Comment by askovpen** [comment]
without bin/activate modules installed in /usr/lib/python2.7/site_packages
try bin/activate before

**Comment by 4IbWNsis3S** [comment]
things like this are never suppose to make it in to master branch. There is no way any test scenario wouldn't catch bugs like this and others that completely break execution. I was getting it with "telegram.py" till I went to dev branch yesterday.. Right before that I had to completely revert bat-installer because a merge completely wrecked it with extremely obvious batch-script path bugs..

**Comment by MrDibbley** [comment]
searching for request.py shows it in the usr site packages?

[root@centos PokemonGo-Bot]# find / -name request.py
/tmp/PokemonGo-Bot/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/request.py
/tmp/PokemonGo-Bot/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/request.py
/tmp/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py
/tmp/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/request.py
/tmp/PokemonGo-Bot/lib/python2.7/site-packages/urllib3/util/request.py
/tmp/PokemonGo-Bot/lib/python2.7/site-packages/telegram/utils/request.py
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/request.py
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/request.py
/usr/lib/python2.7/site-packages/eventlet/green/urllib/request.py
/usr/lib/python2.7/site-packages/requests/packages/urllib3/request.py
/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/request.py
/usr/lib/python2.7/site-packages/future/backports/urllib/request.py
/usr/lib/python2.7/site-packages/future/moves/urllib/request.py
/usr/lib/python2.7/site-packages/urllib3/request.py
/usr/lib/python2.7/site-packages/urllib3/util/request.py
/usr/lib/python2.7/site-packages/telegram/utils/request.py

**Comment by askovpen** [comment]
bin/activate 
before
pip install --upgrade --ignore-installed python-telegram-bot==5.0.0

**Comment by askovpen** [comment]
bin/pip install --upgrade --ignore-installed python-telegram-bot==5.0.0

**Comment by MrDibbley** [comment]
OK, looks like its able to run now, ran setup -u to update master and restore  inputfile.py to source

run now starts with out errors, so one of those commands worked :)

**Comment by askovpen** [comment]
@mjmadsen not bug. if requirements.txt updated - users, who use virtualenv have not updated modules.
