### ISSUE TITLE
Running on Windows Error

### ISSUE THREAD

**Issue by OlafBerens** [PokemonGoF/PokemonGo-Bot#4852]
After today´s update i got this message

Traceback (most recent call last):
  File "pokecli.py", line 46, in <module>
    from pokemongo_bot import inventory
  File "D:\Pokemon\phy\PokemonGo-Bot - olaf.berens.google\pokemongo_bot\__init__
.py", line 22, in <module>
    import cell_workers
  File "D:\Pokemon\phy\PokemonGo-Bot - olaf.berens.google\pokemongo_bot\cell_wor
kers\__init__.py", line 26, in <module>
    from telegram_task import TelegramTask
  File "D:\Pokemon\phy\PokemonGo-Bot - olaf.berens.google\pokemongo_bot\cell_wor
kers\telegram_task.py", line 2, in <module>
    import telegram
ImportError: No module named telegram

The line is "import os" which i do not find somewehere 
(has not been commited ?)

Thanks to clarify

**Comment by LuckyMe4Evers** [comment]
Are you using telegram ? If not change in auth.json "telegram_token": "" let it empty (like it is here)

**Comment by mjmadsen** [comment]
@askovpen Are we missing it in requirements.txt?

**Comment by askovpen** [comment]
```
$ pip install --upgrade -r requirements.txt
```

**Comment by J-Bones** [comment]
Thanks that fixed it

**Comment by J-Bones** [comment]
Potentially related to the updates. Anyone finding the status web server doesn't work anymore? All I get is a blank screen showing the settings.
