### ISSUE TITLE
player_data not in response_dict [dev]

### ISSUE THREAD

**Issue by TianCNCA** [PokemonGoF/PokemonGo-Bot#486]
This is the log:

```
Traceback (most recent call last):
  File "pokecli.py", line 183, in <module>
    main()
  File "pokecli.py", line 169, in main
    bot.start()
  File "D:\New folder\PokemonGo-Bot\pokemongo_bot\__init__.py", line 30, in start
    self._setup_api()
  File "D:\New folder\PokemonGo-Bot\pokemongo_bot\__init__.py", line 166, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'
```
Can someone help me take a look at this please. Thanks!

**Comment by pol0nium** [comment]
Try a `git pull`. I had the same issue with a previous version.

**Comment by TianCNCA** [comment]
My code is latest. Still the same issue.

**Comment by pol0nium** [comment]
Hmm. Are you on master or dev branch ?

**Comment by TianCNCA** [comment]
I'm on dev. Sorry I forgot to add a tag.

**Comment by earthchie** [comment]
your pgoapi is outdated. try
pip install -r requirements.txt

**Comment by TianCNCA** [comment]
It should be pgoapi-1.1.0 right? I'm still having the error.

**Comment by Ecostack** [comment]
Have the same issue. Also have pgoapi-1.1.0.

**Comment by TianCNCA** [comment]
Are you using Windows or OS X?

**Comment by Ecostack** [comment]
```
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
```

**Comment by CapCap** [comment]
Try doing a git clone into a new folder, and redoing pip install
 Or deleting the pgoapi folder.

**Comment by Ecostack** [comment]
Ok, looks like a 
`pip install --upgrade -r requirements.txt` 
did the trick.

**Comment by heihachi** [comment]
http://pastebin.com/aL8duZpj

I am having this issue and pip says all is updated

**Comment by TianCNCA** [comment]
For anyone who have the same problem, delete whole folder and do git pull
