### ISSUE TITLE
[FeatureRequest] Altitude Improvements

### ISSUE THREAD

**Issue by PokemonGoZ** [PokemonGoF/PokemonGo-Bot#4868]
### Short Description
In my logs it shows that it's moving from a high altitude of 923 feet/meters to an altitude of 8 feet/meters... Niantic can EASILY spot that I'm literally skydiving down a hole to Wonderland in the middle of Central Park. This is possibly one way you can get banned.

>2016-08-28 13:55:49,852 [FollowPath] [INFO] [position_update] Walking from (40.753874846728664, -73.96611342797506, **923.2405306212179**) to (40.764726, -73.973134, **8.0**), distance left: (1343.69523416 m) ..

### Possible solution
You could use a Google API to pull the Altitude from the location you're walking to, and the bot could just gradually increase/decrease as it moves towards the location (Instead of using the API to pull the altitude of its current location. This would waste the daily quota of Google API requests).

### How it would help others
It could potentially decrease the likelihood of being banned.

**Comment by avexus** [comment]
well, 923 seems high.
we need a reasonable range. i live in a high rise building, the height is at least 160 feet, or almost 50 meters. when we use phone to log in, this is the data gets sent over (if it gets sent).
and elevation is around 200 meters, i think.
by the way, is the altitude in meters?

**Comment by PokemonGoZ** [comment]
@avexus Not sure. That's just what it said in my logs.

**Comment by acurioustale** [comment]
Altitude is in meters and can be adjusted in config.json:
`    "gps_default_altitude": 8.0,`

The Google Maps Elevation API doesn't allow enough daily requests. We could switch to something like Mapzen with user-generated keys.

**Comment by th3w4y** [comment]
@PokemonGoZ  this is already implemented in .get_alt() of the polyline walker... it gets max 512 elevations for one API call  for a polyline path 

which cell worker are you using?

**Comment by th3w4y** [comment]
For me it looks more like a display bug.... 

at least if you use the polyline walker...

also worth mentioning is that the so called **current_position** is actually the *next destination.. 

```

        self.emit_event(
            'position_update',
            formatted="Walking from {last_position} to {current_position}, distance left: ({distance} {distance_unit}) ..",
            data={
                'last_position': (last_lat, last_lng, last_alt),
                'current_position': (lat, lng, alt),
                'distance': dist,
                'distance_unit': 'm'
            }
        )
```

You are using follow path

**Comment by th3w4y** [comment]
By my estimates if someone has about an average of ~100m between the points (with a speed between 2.5-3ms) then the 2500/day API calls for the Directions and Elevations should/will suffice.

**Comment by th3w4y** [comment]
@PokemonGoZ you are not using the PolylineWalker?

thy seeing walker = PolylineWalker in your config...

i am puzzled where the 923 in your output is coming from...

i instantiated a Polyline object  just to check your from..to case and that returns elevations between 10 and 15 m
```

In [16]: a = Polyline((40.753874846728664, -73.96611342797506), (40.764726, -73.973134), 2.5)

In [17]: a.get_alt()
Out[17]: 10.78

In [18]: a.polyline_elevations[-20:-2]
Out[18]: 
[15.04905605316162,
 15.06498241424561,
 15.0811014175415,
 15.10161113739014,
 15.12298583984375,
 15.14080429077148,
 15.1419506072998,
 15.1506290435791,
 15.16418743133545,
 15.16819667816162,
 15.17319107055664,
 15.17757320404053,
 15.18530178070068,
 15.18915176391602,
 15.19785404205322,
 15.20766353607178,
 15.21686363220215,
 15.23192405700684]

In [19]: 

```

**Comment by faegan** [comment]
@th3w4y: there are two more settings in config.json:
`    "alt_min": 500,
    "alt_max": 1000 `

those are the default values in .example. People should edit that to values corresponding with the location they are botting. Or, use PolylineWalker instead of StepWalker

**Comment by avexus** [comment]
@faegan what does Polylinewalker do again?

**Comment by th3w4y** [comment]
@avexus PolylineWalker is a Walker that uses Google Directions API and Google Elevations API to calculate the position and elevation you should be at according to the speed you set, thus your walking will be natural you will walk on pathways not through buildings...

**Comment by th3w4y** [comment]
@avexus give it a try then look at the bot path.. and you will like it 👍

**Comment by avexus** [comment]
Nice. Should it be in the default config so that if some people don't know about this can use it?

**Comment by th3w4y** [comment]
@avexus thanks.

This is currently supported in below cell_workers:

```
follow_path.py
move_to_fort.py
move_to_map_pokemon.py

```
and NOT in:

```
follow_cluster.py   # we should use walker_factory in this one also
follow_spiral.py -  # this one - it does not even make sense to use PolylineWalker.
```

Thus it cannot be made the default yet

**Comment by avexus** [comment]
I had it run for a while, and I like the result. I changed FollowSpiral to true. And I like the result.
I may enlarge the circle diameter to see how it works out.

I have this in my config:
      { "type": "MoveToFort",
        "config": {
          "enabled": true,
          "lure_attraction": true,
          "lure_max_distance": 800,
          "walker": "PolylineWalker",
          "log_interval": 5
        }
      },
      { "type": "FollowSpiral",
        "config": {
          "enabled": true,
          "diameter": 4,
          "step_size": 70
        }
      }

**Comment by th3w4y** [comment]
@avexus  do not use it with FollowSpiral.... you will consume your API limits very fast..

**Comment by avexus** [comment]
how should i do it? delete the FollowSpiral altogether or set it to
"enabled": false
?

**Comment by th3w4y** [comment]
@avexus if you use moveToFort with polyline should be enough 

the follow_spiral will actually cause some jitter... might not have an impact in the nr. of API requests.. 

not sure.. i don't use the bot :)

**Comment by avexus** [comment]
Don't worry, I will do a lot of testing.

**Comment by th3w4y** [comment]
@PokemonGoZ can we close this... everything is implemented

**Comment by th3w4y** [comment]
This is already implemented
