### ISSUE TITLE
Radius of the bot with wifi

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#4869]
When I logged in on my phone with wifi at home, I noticed that it randomly moves around, but there is always a range where it can go. I guess there is an area of radius that it considers is reasonable.
When we use bot with wifi, it should also have some kind of range, so that it won't be discovered.

**Comment by neohunter** [comment]
there is already gps noise param

**Comment by avexus** [comment]
@neohunter I never used that, should I set both of them to true?
