### ISSUE TITLE
Nickname, best moveset based on dps 

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#4871]
I did a search online, the best moveset are almost always based on dps, not the damage.
so, in nicknane template, 
...
          "good_attack_threshold":  0.8,
          "nickname_template":      "{ivcp_pct}_{attack_code}"

sometimes bad moves get capitalized.
Expected:
capitalization based on dps, not attack itself.
And it's pretty standard which moves are the best for each one. If it is the best, capitalize it. Making a lookup table for the best movesets are better than comparing if "good_attack_threshold": 0.8, is met.

**Comment by avexus** [comment]
Does anybody think this is important? Because I do.
Basically, I want a look up table to tell if the movesets are the best ones.
Everytime I want to see if they are, I will have to go on line to search for it, and very hard to remember for each one. I tried to write them down, but sometimes the notes are not handy.
And these tasks are what bots do best.

So, if possible, I would like a feature like:
"best_moveset_dps":  true,

to override this line:
"good_attack_threshold": 0.8
 or in default of this line.

Thank you very much!

**Comment by avexus** [comment]
Actually, if the best 15 overall can be known is enough.
1	Mewtwo*
2	Dragonite
3	Mew*
4	Articuno*
5	Snorlax
6	Moltres*
7	Zapdos*
8	Lapras
9	Arcanine
10	Blastoise
11	Exeggutor
12	Vaporeon
13	Gyarados
14	Slowbro
15	Venusaur

**Comment by RedViper9** [comment]
Here's another reference for you @avexus 
http://pokemongo.gamepress.gg/

**Comment by davidakachaos** [comment]
We have functionality now to nickname Pokemon, closing this issue. If there are stil things missing, please open a new issue.
