### ISSUE TITLE
Crash when evolving pokemon

### ISSUE THREAD

**Issue by r3pek** [PokemonGoF/PokemonGo-Bot#4873]
### Expected Behavior

Bot to evolve pokemon

### Actual Behavior
Crash with the following call trace while trying to evolve a pokemon:
http://pastebin.com/z3Dj932k

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

Pretty much the default config, just enable evolve pokemons

### Output when issue occurred

http://pastebin.com/z3Dj932k

### Steps to Reproduce

start bot with a pokemon available to evolve

### Other Information
OS: linux
 
Branch: dev
 
Git Commit:  007f02a
 
Python Version: Python 2.7.12
 
Any other relevant files/configs (eg: path files)

**Comment by Gobberwart** [comment]
Did this happen just once or is it a regular/recurring thing?

**Comment by r3pek** [comment]
Since it doesn't even evolve the pokemon, everytime i start the bot, it triggers the evolution, and so it crashes.

**Comment by Gobberwart** [comment]
I changed the title of this issue because "Yet another UTF8 crash" means nothing.

**Comment by mjmadsen** [comment]
Looks related to #4798. @rawgni 

Is this because we have the default value = none. So we try getting the first index and it's none (null).

**Comment by rawgni** [comment]
@r3pek can you post your config file ? just the EvolvePokemon part

**Comment by r3pek** [comment]
@rawgni yes. my bad then? :(

**Comment by mjmadsen** [comment]
Not necessarily, whatever you have evolve_all is the key to figuring this out.

**Comment by mjmadsen** [comment]
@rawgni I looked over what is there, realize it wouldn't get to that line if it was set to none. Side note, we need to change it to something other then evolve_all (it's purposes go well beyond it's initial purpose).

**Comment by r3pek** [comment]
i have `"evolve_all": ""`

**Comment by mjmadsen** [comment]
Ah, set to none if you don't want to have any evolved.

**Comment by r3pek** [comment]
I want the exact opposite... evolve all ;)

**Comment by rawgni** [comment]
`"evolve_all": "all"`

**Comment by r3pek** [comment]
works ;) thx and sorry for the misleading error

**Comment by mjmadsen** [comment]
Maybe change it to evolve_list. Do we indicate the values in the md?

@r3pek No problem, the variable is a bit misleading. Plus helped us realize a few places to make sure we're getting correct data.

**Comment by mjmadsen** [comment]
Several solutions merged to dev. If problems persist, please reopen with new logs.
