### ISSUE TITLE
Error on "Most Perfect Pokemon", pokecli.py line 768

### ISSUE THREAD

**Issue by 19jake68** [PokemonGoF/PokemonGo-Bot#4879]
===============ISSUE SECTION===============

### Expected Behavior
Bot running

### Actual Behavior
Bot crashed when displaying "Most Perfect Pokemon"
Pokecli.py line 768

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/3wH5rdy3

### Output when issue occurred
http://pastebin.com/VqeJeR6G

### Steps to Reproduce
Run the bot in the latest config

### Other Information
Pulled today's updates (August 29, 2016 11:AM UTC+8:00)

**Comment by Gobberwart** [comment]
There's a PR to fix this problem with update_web_inventory. Ignore.
