### ISSUE TITLE
Logging now has no color

### ISSUE THREAD

**Issue by tranquochuy** [PokemonGoF/PokemonGo-Bot#4880]
I have updated the source code to date and found out the logging has no color at all. I did set it on my config at: `"logging_color": true` but it didn't work.

**Comment by rawgni** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md#logging-configuration

should now use 
```
"logging": {
     "color": true
}
```

**Comment by Gobberwart** [comment]
Correct... logging_color is deprecated. Your log should have said something about it, eg...

```
2016-08-29 14:43:19,038 [       cli] [WARNING] The logging_color argument has been moved into the logging config section
```

Pays to pay attention to these messages.
