### ISSUE TITLE
[ISSUE] Error on startup

### ISSUE THREAD

**Issue by Creuqe** [PokemonGoF/PokemonGo-Bot#4890]
Expected Behavior
To start normally

Actual Behavior
gives a trackback error:
Traceback (most recent call last):File "pokecli.py", line 43, in <module>from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetExceptionImportError: No module named pgoapi.exceptions

Your FULL config.json (remove your username, password, gmapkey and any other private info)
{
    "websocket_server": false,
    "heartbeat_threshold": 11,
    "enable_social": true,
    "live_config_update": {
      "enabled": false,
      "tasks_only": false
    },
    "tasks": [
      {
        "type": "TelegramTask",
        "config": {
          "enabled": false,
          "master": null,
          "alert_catch": ["all"]
        }
      },
      {
        "//NOTE: This task MUST be placed on the top of task list": {},
        "type": "RandomAlivePause",
        "config": {
          "enabled": true,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:05:00",
          "max_interval": "01:30:00"
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "RandomPause",
        "config": {
          "enabled": true,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:10:00",
          "max_interval": "02:00:00"
        }
      },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": true,
          "// set a name": "Kaiju9K",
          "nickname": "Kaiju9K"
        }
      },
      {
        "type": "CollectLevelUpReward",
        "config": {
          "collect_reward": true,
          "level_limit": -1
        }
      },
      {
        "type": "IncubateEggs",
        "config": {
          "enabled": true,
          "infinite_longer_eggs_first": false,
          "breakable_longer_eggs_first": true,
          "min_interval": 120,
         "infinite": [2,5,10],
         "breakable": [2,5,10]
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 11,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": false,
          "min_interval": 120,
          "show_all_multiple_lines": false,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
        }
      },
      {
        "type": "ShowBestPokemon",
        "config": {
          "enabled": true,
          "min_interval": 61,
          "amount": 4,
          "order_by": "cp",
          "info_to_show": ["cp", "ivcp", "dps", "hp"]
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "enabled": true,
          "min_free_slot": 6,
          "transfer_wait_min": 4,
          "transfer_wait_max": 6
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_above_iv": 0.9,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "enabled": true,
          "//evolve all except Zubat and Rattata": "",
          "//evolve_all": "-Zubat,-Rattata",
          "evolve_all": "Zubat,Rattata,Pidgey,Paras,Golduck,Doduo",
          "first_evolve_by": "cp",
          "evolve_above_cp": 100,
          "evolve_above_iv": 0.8,
          "logic": "or",
          "min_evolve_speed": 26,
          "max_evolve_speed": 31,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 14,
          "max_balls_keep": 141,
          "max_potions_keep": 53,
          "max_berries_keep": 73,
          "max_revives_keep": 73,
          "item_filter": {
            "Pokeball":       { "keep" : 99 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 21 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          },
          "recycle_wait_min": 3,
          "recycle_wait_max": 6,
          "recycle_force": true,
          "recycle_force_min": "00:01:00",
          "recycle_force_max": "00:05:00"
        }
      },
      {
        "type": "CatchPokemon",
        "config": {
          "enabled": true,
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 6,
          "berry_threshold": 0.34,
          "vip_berry_threshold": 0.9,
          "treat_unseen_as_vip": true,
          "daily_catch_limit": 799,
          "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.3,
            "nice_rate": 0.5,
            "normal_rate": 0.1,
            "spin_success_rate" : 0.6,
            "hit_rate": 0.59
          },
          "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 4,
            "catch_wait_max": 6,
            "berry_wait_min": 3,
            "berry_wait_max": 6,
            "changeball_wait_min": 3,
            "changeball_wait_max": 6,
            "newtodex_wait_min": 20, 
            "newtodex_wait_max": 31
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "enabled": true,
          "spin_wait_min": 3,
          "spin_wait_max": 6
        }
      },
      { "type": "UpdateWebInventory",
        "config": {
          "enabled": true
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "enabled": true,
          "lure_attraction": true,
          "lure_max_distance": 1923,
          "walker": "StepWalker",
          "log_interval": 65
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "enabled": true,
          "diameter": 4,
          "step_size": 69
        }
      }
    ],
    "map_object_cache_time": 6,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 49,
      "cache_recent_forts": true
    },
    "pokemon_bag": {
      "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
      "show_at_start": true,
      "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
      "show_count": false,
      "// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
      "show_candies": false,
      "// 'pokemon_info' parameter define which info to show for each pokemon": {},
      "// the available options are": {},
      "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
      "pokemon_info": ["cp", "iv_pct"]
    },
    "walk_max": 4.10,
    "walk_min": 2.09,
    "alt_min": 498,
    "alt_max": 1091,
    "sleep_schedule": [
      {
        "time": "03:00",
        "duration": "2:30",
        "time_random_offset": "00:21",
        "duration_random_offset": "00:31",
        "wake_up_at_location": ""
      },
      {
        "time": "09:11",
        "duration": "2:59",
        "time_random_offset": "00:21",
        "duration_random_offset": "00:31",
        "wake_up_at_location": ""
      },
      {
        "time": "14:31",
        "duration": "2:50",
        "time_random_offset": "00:21",
        "duration_random_offset": "00:31",
        "wake_up_at_location": ""
      },
      {
        "time": "18:49",
        "duration": "2:41",
        "time_random_offset": "00:21",
        "duration_random_offset": "00:31",
        "wake_up_at_location": ""
      }
    ],
    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": true,
    "replicate_gps_z_noise": true,
    "gps_xy_noise_range": 0.000126,
    "gps_z_noise_range": 10.4,
    "debug": false,
    "test": false,
    "walker_limit_output": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 17,
    "logging": {
      "color": true,
      "show_datetime": true,
      "show_process_name": true,
      "show_log_level": true
    },
    "catch": {
      "any": {"candy_threshold" : 400 ,"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Keep no more than 3 best IV pokemon for every pokemon type": {},
      "// any": {"keep_best_iv": 3},
      "// Discard all pokemon in bag except 100 pokemon with best CP": {},
      "// all": {"keep_best_cp": 100},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3},
      "// Example of custom order of static criterion": {},
      "// Zubat": {"keep_best_custom": "iv, cp, hp_max", "amount":2}
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}

Output when issue occurred
Traceback (most recent call last):
  File "pokecli.py", line 43, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetException
ImportError: No module named pgoapi.exceptions

 Something went wrong and the bot needed to be restarted. Please investigate the cause.

Steps to Reproduce
start the bot via .bat file( i followed the easy windows installation method)

Other Information

OS: win10

Branch: master

Git Commit:

Python Version: 2.7(32bit) tried on both x32 x64

Any other relevant files/configs (eg: path files)
Short Description n/a
Possible solution n/a
How it would help others n/a

**Comment by mjmadsen** [comment]
Traceback (most recent call last):File "pokecli.py", line 43, in from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetExceptionImportError: No module named pgoapi.exceptions

You don't the pgoapi project or at least an updated version.

pip install -r requirements.txt --upgrade

**Comment by plkscmc33** [comment]
How to type the command above?
I am new to the BOT.
Great thanks.
