### ISSUE TITLE
How Do i enable transfer pokemon

### ISSUE THREAD

**Issue by memeshack** [PokemonGoF/PokemonGo-Bot#4892]
Mine just doesnt work on the default config

**Comment by r3pek** [comment]
I was just going to report this :)

Bot don't transfer pokemons :(

**Comment by memeshack** [comment]
Then whats         "type": "TransferPokemon",  for

**Comment by r3pek** [comment]
@memeshack i'm just confirming the bug ;)

**Comment by memeshack** [comment]
ohh okay

**Comment by r3pek** [comment]
@memeshack got it. Search for the "release" section and change the "any" (or any other) line in it. bellow_cp 0 or bellow_iv 0 really doesn't make it work out-of-the-box.

**Comment by memeshack** [comment]
@r3pek Thanks!

**Comment by mjmadsen** [comment]
{
        "type": "TransferPokemon",
        "config": {
          "enabled": true,
          "min_free_slot": 5, <------------- must have this or fewer spots left in your bag to transfer
          "transfer_wait_min": 3,
          "transfer_wait_max": 5
        }
      },

**Comment by r3pek** [comment]
@mjmadsen 
actual problem is:
```
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"}, <--------- this line
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Keep no more than 3 best IV pokemon for every pokemon type": {},
      "// any": {"keep_best_iv": 3},
      "// Discard all pokemon in bag except 100 pokemon with best CP": {},
      "// all": {"keep_best_cp": 100},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3},
      "// Example of custom order of static criterion": {},
      "// Zubat": {"keep_best_custom": "iv, cp, hp_max", "amount":2}
    },
```
the default "any" like make it that it's impossible to release any pokemon, so it never releases even with bag full.

**Comment by memeshack** [comment]
Ah, well I got it to work

**Comment by mjmadsen** [comment]
@memeshack @r3pek Can I close this?
