### ISSUE TITLE
[Feature Request] Add Conditions and Delay to NicknamePokemon for More Realism

### ISSUE THREAD

**Issue by etiennebechara** [PokemonGoF/PokemonGo-Bot#4893]
### Short Description
I would like to suggest 2 features for NicknamePokemon:
1. Add a configurable delay before the action to simulate the time of a human navigating and typing the new name.
2. Add a conditional configuration method of only nicknaming specific pokemon and not all of them. It could be based on the "vips", or based on a separated array configured by the user.

### Possible solution
The config could look like this (vips way):
> {
> 	"type": "NicknamePokemon",
> 	"config": {
> 		"enabled": true,
> 		"nickname_wait_min": 3,
> 		"nickname_wait_max": 6,
> 		"dont_nickname_favorite": false,
> 		"nickname_vips_only": true,
> 		"good_attack_threshold": 0.85,
> 		"nickname_template": "{iv_ads_hex}.{attack_pct2}.{defense_pct2}",
> 		"locale": "en"
> 	}
> },

Or like this (threshold way):
> {
> 	"type": "NicknamePokemon",
> 	"config": {
> 		"enabled": true,
> 		"nickname_wait_min": 3,
> 		"nickname_wait_max": 6,
> 		"dont_nickname_favorite": false,
> 		"good_attack_threshold": 0.85,
> 		"nickname_thresholds": [
> 		{
> 			"type": "iv",
> 			"threshold": 0.9
> 		},
> 		{
> 			"type": "attack_pct",
> 			"threshold": 0.8
> 		},
> 		{
> 			"type": "defense_pct",
> 			"threshold": 0.85
> 		},
> 		]
> 		"nickname_template": "{iv_ads_hex}.{attack_pct2}.{defense_pct2}",
> 		"locale": "en"
> 	}
> },

### How it would help others
It would help everyone as a more realistic way of simulating a person nicknaming pokemon.

**Comment by mjmadsen** [comment]
I would advise not using nickname if you want to look like a human. The nicknames we put in there look very nonhuman. But we should have delays in there, as we do with most tasks.

**Comment by alexyaoyang** [comment]
Addressed, closing.
