### ISSUE TITLE
Disable sleep?

### ISSUE THREAD

**Issue by memeshack** [PokemonGoF/PokemonGo-Bot#4897]
I dont want the bot to sleep, how do I disable it?

**Comment by th3w4y** [comment]
@memeshack can you give more details? when does it sleep and you don't want it to sleep?

**Comment by memeshack** [comment]
it sleeps after a little bit and it does it for a while,  i dont know to describe it

**Comment by th3w4y** [comment]
@memeshack maybe copy&paste your last lines... of output...

**Comment by memeshack** [comment]
It didnt happen yet, i will when it does @th3w4y

**Comment by th3w4y** [comment]
@memeshack in the mean time ☕ (coffee) should help agains sleeping 👍

**Comment by memeshack** [comment]
Good one

**Comment by hobbes3** [comment]
He means there should be a

    "enabled": false

for `sleep_schedule` in `config.json`. I'm up for that.

**Comment by memeshack** [comment]
I just did that and this is the message that pops up in console,

[2016-08-29 17:59:15] [SleepSchedule] [INFO] [bot_sleep] Sleeping for 03:06:49,
wake at 2016-08-29 21:06:04.370000

It finally did it after running for 5 hours lol

**Comment by oralunal** [comment]
Just remove the sleep schedule things from your config file.

**Comment by hobbes3** [comment]
@oralunal The purpose of having a `enabled` option is so you can quickly enable and disable certain portion of the config without re-typing it all. That's why all the other tasks have that feature. You should consider re-opening this :-).

**Comment by oralunal** [comment]
@hobbes3 openning for you :)

**Comment by cmezh** [comment]
Done in #5278
