### ISSUE TITLE
[OffTopic] Nub Question: how can i host it on a server?

### ISSUE THREAD

**Issue by dominikue** [PokemonGoF/PokemonGo-Bot#490]
I want to host the script on a server - it is possible?
Can somebody give me some links to tutorials or to an good hosting sites? Would be nice - coulnd't find something helpfull on google..

**Comment by s1x** [comment]
@dominikue Do you mean host in terms of running the bot on a server rather than your local machine?

**Comment by s1x** [comment]
Its basically out of the scope of the bot, but you might check AWS or DigitalOcean which provide exactly that. You just need to set up a server, there is a bunch of tutorials out there and then follow the readme.

**Comment by dominikue** [comment]
Ty, will try DigitalOcan :)

**Comment by dominikue** [comment]
@s1x it worked with digitalOcean and putty. But when i close putty the script closed too? And how can i start 2 instance with one s

**Comment by dominikue** [comment]
GOT it :D
