### ISSUE TITLE
Bot is "crawling". Moving .3m/min to 1m/min. very slow walk.

### ISSUE THREAD

**Issue by crvfts** [PokemonGoF/PokemonGo-Bot#4902]
JSON validated- Valid JSON

yes, i did search issues, did not find current behavior recently for dev.

Issue occurs for me with current dev. I reverted to e43f8f9 and issue still occurs.
### Expected Behavior

Trainer to walk 3.22km/h to 4.14km/h

### Actual Behavior

Trainer walking only 0.3m/min to 1m/minute, walking VERY slowly.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

{
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": false,
    "live_config_update": {
      "enabled": true,
      "tasks_only": true
    },

    "tasks": [
      {
        "type": "TelegramTask",
        "config": {
          "enabled": true,
          "master": #########,
          "alert_catch": ["all"]
        }
      },
      {
        "//NOTE: This task MUST be placed on the top of task list": {},
        "type": "RandomAlivePause",
        "config": {
          "enabled": true,
          "min_duration": "00:04:13",
          "max_duration": "00:10:28",
          "min_interval": "01:02:37",
          "max_interval": "02:17:14"
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "RandomPause",
        "config": {
          "enabled": true,
          "min_duration": "00:00:39",
          "max_duration": "00:10:14",
          "min_interval": "01:02:37",
          "max_interval": "02:17:14"
        }
      },
      {
        "type": "CollectLevelUpReward",
        "config": {
          "collect_reward": true,
          "level_limit": -1
        }
      },
      {
        "type": "IncubateEggs",
        "config": {
          "enabled": true,
          "infinite_longer_eggs_first": true,
          "breakable_longer_eggs_first": true,
          "min_interval": 600,
         "infinite": [2,5,10],
         "breakable": [10]
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": true,
          "min_interval": 600,
          "stats": ["uptime", "level_stats", "km_walked", "xp_earned", "xp_per_hour", "pokemon_caught", "stops_visited", "stardust_earned"],
          "terminal_log": false,
          "terminal_title": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": true,
          "min_interval": 900,
          "show_all_multiple_lines": true,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "enabled": true,
          "min_free_slot": 999,
          "transfer_wait_min": 9,
          "transfer_wait_max": 13
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "enabled": false,
          "//evolve all except Zubat and Rattata": "",
          "//evolve_all": "-Zubat,-Rattata",
          "evolve_all": "Eevee",
          "first_evolve_by": "iv",
          "evolve_above_cp": 9,
          "evolve_above_iv": 0.9,
          "logic": "and",
          "min_evolve_speed": 31,
          "max_evolve_speed": 36,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 5,
          "max_balls_keep": 280,
          "max_potions_keep": 0,
          "max_berries_keep": 60,
          "max_revives_keep": 0,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Greatball":      { "keep" : 100 },
            "Ultraball":      { "keep" : 80 },
            "Potion":         { "keep" : 0 },
            "Super Potion":   { "keep" : 0 },
            "Hyper Potion":   { "keep" : 0 },
            "Max Potion":     { "keep" : 0 },
            "Revive":         { "keep" : 0 },
            "Max Revive":     { "keep" : 0 },
            "Lucky Egg":      { "keep" : 10},
            "Razz Berry":     { "keep" : 60 }
          },
          "recycle_wait_min": 10,
          "recycle_wait_max": 15,
          "recycle_force": false,
          "recycle_force_min": "00:01:00",
          "recycle_force_max": "00:05:00"
        }
      },
	  {
        "type": "CatchPokemon",
        "config": {
          "enabled": true,
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 9,
          "berry_threshold": 0.35,
          "vip_berry_threshold": 0.9,
          "treat_unseen_as_vip": true,
          "daily_catch_limit": 315,
          "catch_throw_parameters": {
            "excellent_rate": 0.07,
            "great_rate": 0.07,
            "nice_rate": 0.1,
            "normal_rate": 0.76,
            "spin_success_rate" : 0.42,
            "hit_rate": 0.71
          },
          "catch_simulation": {
            "flee_count": 5,
            "flee_duration": 5,
            "catch_wait_min": 5,
            "catch_wait_max": 7,
            "berry_wait_min": 5,
            "berry_wait_max": 7,
            "changeball_wait_min": 5,
            "changeball_wait_max": 7,
            "newtodex_wait_min": 22, 
            "newtodex_wait_max": 31
          }
        }
      },

      {
        "type": "SpinFort",
        "config": {
          "enabled": true,
          "spin_wait_min": 4,
          "spin_wait_max": 8
        }
      },
      { "type": "UpdateWebInventory",
        "config": {
          "enabled": true
        }
      },

      
      
      

      {
        "type": "MoveToFort",
        "config": {
          "enabled": true,
          "lure_attraction": false,
          "lure_max_distance": 400,
          "log_interval": 5,
          "walker": "StepWalker"
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "enabled": true,
          "diameter": 4,
          "step_size": 70
        }
      }
    ],

    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 28,
      "cache_recent_forts": true
    },
    "walk_max": 4.14,
    "walk_min": 3.22,
    "alt_min": 126,
    "alt_max": 138,
    "gps_default_altitude": 132.0,
    "replicate_gps_xy_noise": true,
    "replicate_gps_z_noise": true,
    "gps_xy_noise_range": 0.000075,
    "gps_z_noise_range": 9.5,

    "sleep_schedule": [
      {
        "time": "13:49",
        "duration": "00:18",
        "time_random_offset": "00:05",
        "duration_random_offset": "00:05",
        "wake_up_at_location": ""
      },
      {
        "time": "16:31",
        "duration": "00:26",
        "time_random_offset": "00:05",
        "duration_random_offset": "00:05",
        "wake_up_at_location": "44.666729, -74.998328"
      }
    ],

    "debug": false,
    "test": false,
    "walker_limit_output": true,
    "health_record": false,
    "location_cache": true,
    "distance_unit": "m",
    "reconnecting_timeout": 63,
    "logging": {
      "color": true,
      "show_datetime": true,
      "show_process_name": false,
      "show_log_level": false
    },

    "catch": {
      "any": {"candy_threshold" : 404, "catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"}
    },

    "release": {
      "any": {"keep_best_iv": 2}
    },
    "vips" : {
        "any": {"catch_above_cp": 999, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }

    
}

### Other Information
OS: Windows 8.1
 
Branch: current dev (and e43f8f9 to test as it was working for me last, still same issue)
 
Git Commit: current and e43f8f98985de8d1bc254f0c04b2b4068101c879
 
Python Version: 2.1.12 32bit
 
Any other relevant files/configs (eg: path files) 

It seems that skip ignore is taking a lot of time.... but even when there are not pokemon being ignored the bot still moves very slowly.

**Comment by davidspeijer** [comment]
Same issue here, disable the `TelegramTask` to fix the speed to normal. I expect there is a bug in the Telegram code :).

**Comment by crvfts** [comment]
@davidspeijer thank you very much! disabled TelegramTask and everything is back to normal!

**Comment by davidspeijer** [comment]
Perhaps it should remain open as it appears it is an issue with the telegram task?
