### ISSUE TITLE
[Bug] transfer pokemon has "hidden" value

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#4905]
When I used bot to transfer all the pokemons, I set "release_all": true
when it released/transferred all the pokemons, and opened it on my phone, i saw no pokemon in my bag, but it says "9/250".

I tried with 2 of my accounts, the same situation. And a 3rd new account, with not many inventories. I saw 2 "hidden" pokemons in the bag.

Is it because when transferring, something didn't register?
Does that mean we lost 9 slots?
Could that be an indication that we used this and could be marked?
Can this be related to the favorite we marked then removed favorite mark?

**Comment by mjmadsen** [comment]
How many eggs do you have?

**Comment by avexus** [comment]
@mjmadsen 9. Does that include 9 eggs?
