### ISSUE TITLE
Error on bot start, after login.

### ISSUE THREAD

**Issue by Creuqe** [PokemonGoF/PokemonGo-Bot#4910]
### Expected Behavior
BOT starts normally and goes on

### Actual Behavior
Gives strange error

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

> {
>     "websocket_server": false,
>     "heartbeat_threshold": 11,
>     "enable_social": true,
>     "live_config_update": {
>       "enabled": false,
>       "tasks_only": false
>     },
>     "tasks": [
>       {
>         "type": "TelegramTask",
>         "config": {
>           "enabled": false,
>           "master": null,
>           "alert_catch": ["all"]
>         }
>       },
>       {
>         "//NOTE: This task MUST be placed on the top of task list": {},
>         "type": "RandomAlivePause",
>         "config": {
>           "enabled": true,
>           "min_duration": "00:00:10",
>           "max_duration": "00:10:00",
>           "min_interval": "00:05:00",
>           "max_interval": "01:30:00"
>         }
>       },
>       {
>         "type": "HandleSoftBan"
>       },
>       {
>         "type": "RandomPause",
>         "config": {
>           "enabled": true,
>           "min_duration": "00:00:10",
>           "max_duration": "00:10:00",
>           "min_interval": "00:10:00",
>           "max_interval": "02:00:00"
>         }
>       },
>       {
>         "type": "CompleteTutorial",
>         "config": {
>           "enabled": true,
>           "// set a name": "Kaiju9K",
>           "nickname": "Kaiju9K"
>         }
>       },
>       {
>         "type": "CollectLevelUpReward",
>         "config": {
>           "collect_reward": true,
>           "level_limit": -1
>         }
>       },
>       {
>         "type": "IncubateEggs",
>         "config": {
>           "enabled": true,
>           "infinite_longer_eggs_first": false,
>           "breakable_longer_eggs_first": true,
>           "min_interval": 120,
>          "infinite": [2,5,10],
>          "breakable": [2,5,10]
>         }
>       },
>       {
>         "type": "UpdateLiveStats",
>         "config": {
>           "enabled": false,
>           "min_interval": 11,
>           "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
>           "terminal_log": true,
>           "terminal_title": true
>         }
>       },
>       {
>         "type": "UpdateLiveInventory",
>         "config": {
>           "enabled": false,
>           "min_interval": 120,
>           "show_all_multiple_lines": false,
>           "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
>         }
>       },
>       {
>         "type": "ShowBestPokemon",
>         "config": {
>           "enabled": true,
>           "min_interval": 61,
>           "amount": 4,
>           "order_by": "cp",
>           "info_to_show": ["cp", "ivcp", "dps", "hp"]
>         }
>       },
>       {
>         "type": "TransferPokemon",
>         "config": {
>           "enabled": true,
>           "min_free_slot": 6,
>           "transfer_wait_min": 4,
>           "transfer_wait_max": 6
>         }
>       },
>       {
>         "type": "NicknamePokemon",
>         "config": {
>           "enabled": false,
>           "nickname_above_iv": 0.9,
>           "nickname_template": "{iv_pct}_{iv_ads}"
>         }
>       },
>       {
>         "type": "EvolvePokemon",
>         "config": {
>           "enabled": true,
>           "//evolve all except Zubat and Rattata": "",
>           "//evolve_all": "-Zubat,-Rattata",
>           "evolve_all": "Zubat,Rattata,Pidgey,Paras,Golduck,Doduo",
>           "first_evolve_by": "cp",
>           "evolve_above_cp": 100,
>           "evolve_above_iv": 0.8,
>           "logic": "or",
>           "min_evolve_speed": 26,
>           "max_evolve_speed": 31,
>           "use_lucky_egg": false
>         }
>       },
>       {
>         "type": "RecycleItems",
>         "config": {
>           "enabled": true,
>           "min_empty_space": 15,
>           "max_balls_keep": 150,
>           "max_potions_keep": 50,
>           "max_berries_keep": 70,
>           "max_revives_keep": 70,
>           "item_filter": {
>             "Pokeball":       { "keep" : 100 },
>             "Potion":         { "keep" : 10 },
>             "Super Potion":   { "keep" : 20 },
>             "Hyper Potion":   { "keep" : 30 },
>             "Revive":         { "keep" : 30 },
>             "Razz Berry":     { "keep" : 100 }
>           },
>           "recycle_wait_min": 3,
>           "recycle_wait_max": 5,
>           "recycle_force": true,
>           "recycle_force_min": "00:01:00",
>           "recycle_force_max": "00:05:00"
>         }
>       },
>       {
>         "type": "CatchPokemon",
>         "config": {
>           "enabled": true,
>           "catch_visible_pokemon": true,
>           "catch_lured_pokemon": true,
>           "min_ultraball_to_keep": 5,
>           "berry_threshold": 0.35,
>           "vip_berry_threshold": 0.9,
>           "treat_unseen_as_vip": true,
>           "daily_catch_limit": 800,
>           "catch_throw_parameters": {
>             "excellent_rate": 0.1,
>             "great_rate": 0.5,
>             "nice_rate": 0.3,
>             "normal_rate": 0.1,
>             "spin_success_rate" : 0.6,
>             "hit_rate": 0.75
>           },
>           "catch_simulation": {
>             "flee_count": 3,
>             "flee_duration": 2,
>             "catch_wait_min": 4,
>             "catch_wait_max": 6,
>             "berry_wait_min": 3,
>             "berry_wait_max": 6,
>             "changeball_wait_min": 3,
>             "changeball_wait_max": 6,
>             "newtodex_wait_min": 20, 
>             "newtodex_wait_max": 31
>           }
>         }
>       },
>       {
>         "type": "SpinFort",
>         "config": {
>           "enabled": true,
>           "spin_wait_min": 3,
>           "spin_wait_max": 6
>         }
>       },
>       { "type": "UpdateWebInventory",
>         "config": {
>           "enabled": true
>         }
>       },
>       {
>         "type": "MoveToFort",
>         "config": {
>           "enabled": true,
>           "lure_attraction": true,
>           "lure_max_distance": 1923,
>           "walker": "StepWalker",
>           "log_interval": 65
>         }
>       },
>       {
>         "type": "FollowSpiral",
>         "config": {
>           "enabled": true,
>           "diameter": 4,
>           "step_size": 69
>         }
>       }
>     ],
>     "map_object_cache_time": 6,
>     "forts": {
>       "avoid_circles": true,
>       "max_circle_size": 49,
>       "cache_recent_forts": true
>     },
>     "pokemon_bag": {
>       "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
>       "show_at_start": true,
>       "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
>       "show_count": false,
>       "// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
>       "show_candies": false,
>       "// 'pokemon_info' parameter define which info to show for each pokemon": {},
>       "// the available options are": {},
>       "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
>       "pokemon_info": ["cp", "iv_pct"]
>     },
>     "walk_max": 4.10,
>     "walk_min": 2.09,
>     "alt_min": 498,
>     "alt_max": 1091,
>     "sleep_schedule": [
>       {
>         "time": "03:00",
>         "duration": "2:30",
>         "time_random_offset": "00:21",
>         "duration_random_offset": "00:31",
>         "wake_up_at_location": ""
>       },
>       {
>         "time": "09:11",
>         "duration": "2:59",
>         "time_random_offset": "00:21",
>         "duration_random_offset": "00:31",
>         "wake_up_at_location": ""
>       },
>       {
>         "time": "14:31",
>         "duration": "2:50",
>         "time_random_offset": "00:21",
>         "duration_random_offset": "00:31",
>         "wake_up_at_location": ""
>       },
>       {
>         "time": "18:49",
>         "duration": "2:41",
>         "time_random_offset": "00:21",
>         "duration_random_offset": "00:31",
>         "wake_up_at_location": ""
>       }
>     ],
>     "gps_default_altitude": 8.0,
>     "replicate_gps_xy_noise": true,
>     "replicate_gps_z_noise": true,
>     "gps_xy_noise_range": 0.000126,
>     "gps_z_noise_range": 10.4,
>     "debug": false,
>     "test": false,
>     "walker_limit_output": false,
>     "health_record": true,
>     "location_cache": true,
>     "distance_unit": "km",
>     "reconnecting_timeout": 17,
>     "logging": {
>       "color": true,
>       "show_datetime": true,
>       "show_process_name": true,
>       "show_log_level": true
>     },
>     "catch": {
>       "any": {"candy_threshold" : 400 ,"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
>       "// Example of always catching Rattata:": {},
>       "// Rattata": { "always_catch" : true }
>     },
>     "release": {
>       "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
>       "// Example of always releasing Rattata:": {},
>       "// Rattata": {"always_release": true},
>       "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
>       "// Pidgey": {"keep_best_cp": 3},
>       "// Example of keeping 2 best (based on IV) Zubat:": {},
>       "// Zubat": {"keep_best_iv": 2},
>       "// Keep no more than 3 best IV pokemon for every pokemon type": {},
>       "// any": {"keep_best_iv": 3},
>       "// Discard all pokemon in bag except 100 pokemon with best CP": {},
>       "// all": {"keep_best_cp": 100},
>       "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
>       "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3},
>       "// Example of custom order of static criterion": {},
>       "// Zubat": {"keep_best_custom": "iv, cp, hp_max", "amount":2}
>     },
>     "vips" : {
>         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": {},
>         "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
>         "Lapras": {},
>         "Moltres": {},
>         "Zapdos": {},
>         "Articuno": {},
> 
>         "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
>         "Mewtwo": {},
>         "Dragonite": {},
>         "Snorlax": {},
>         "// Mew evolves to Mewtwo": {},
>         "Mew": {},
>         "Arcanine": {},
>         "Vaporeon": {},
>         "Gyarados": {},
>         "Exeggutor": {},
>         "Muk": {},
>         "Weezing": {},
>         "Flareon": {}
>     }
> }

_AND AUTH.JSON IF NEEDED_
`{
    "auth_service": "google",
    "username": "--private--",
    "password": "--private--",
    "location": "tokyo disneyland",
    "favorite_locations":[
        {"name": "--private--", "coords": "--private--,--private--"}
    ],
    "gmapkey": "--private--",
    "encrypt_location": "",
    "telegram_token": ""
}`

### Output when issue occurred

> 2016-08-29 23:01:09,556 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
> 2016-08-29 23:01:09,572 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
> 2016-08-29 23:01:09,651 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
> [2016-08-29 23:01:10] [SleepSchedule] [INFO] [next_sleep] Next sleep at 2016-08-30 03:09:08.073000
> [2016-08-29 23:01:10] [PokemonGoBot] [INFO] [set_start_location] Setting start location.
> Traceback (most recent call last):
>   File "pokecli.py", line 781, in <module>
>     main()
>   File "pokecli.py", line 217, in main
>     report_summary(bot)
>   File "pokecli.py", line 265, in report_summary
>     metrics.capture_stats()
>   File "C:\Users\Broooooo\Desktop\GoFPokemonGo-Bot\pokemongo_bot\metrics.py", line 109, in capture_stats
>     response_dict = request.call()
>   File "C:\Users\Broooooo\Desktop\GoFPokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 223, in call
>     if not self.can_call():
>   File "C:\Users\Broooooo\Desktop\GoFPokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 124, in can_call
>     raise NoPlayerPositionSetException()
> pgoapi.exceptions.NoPlayerPositionSetException
> [2016-08-29 23:01:11] [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
> Traceback (most recent call last):
>   File "C:\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
>     super(ThreadedHTTPTransport, self).send(data, headers)
>   File "C:\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
>     ca_certs=self.ca_certs,
>   File "C:\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
>     return opener.open(url, data, timeout)
>   File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
>     response = self._open(req, data)
>   File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
>     '_open', req)
>   File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
>     result = func(*args)
>   File "C:\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
>     return self.do_open(ValidHTTPSConnection, req)
>   File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
>     h.request(req.get_method(), req.selector, req.data, headers)
>   File "C:\Python27\lib\httplib.py", line 1057, in request
>     self._send_request(method, url, body, headers)
>   File "C:\Python27\lib\httplib.py", line 1097, in _send_request
>     self.endheaders(body)
>   File "C:\Python27\lib\httplib.py", line 1053, in endheaders
>     self._send_output(message_body)
>   File "C:\Python27\lib\httplib.py", line 895, in _send_output
>     msg += message_body
>   File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
>     return codecs.utf_8_decode(input, errors, True)
> UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
> [2016-08-29 23:01:11] [sentry.errors.uncaught] [ERROR] [u'NoPlayerPositionSetException', u'  File "pokecli.py", line 781, in <module>', u'  File "pokecli.py", line 217, in main', u'  File "pokecli.py", line 265, in report_summary', u'  File "C:\\Users\\Broooooo\\Desktop\\GoFPokemonGo-Bot\\pokemongo_bot\\metrics.py", line 109, in capture_stats', u'  File "C:\\Users\\Broooooo\\Desktop\\GoFPokemonGo-Bot\\pokemongo_bot\\api_wrapper.py", line 223, in call', u'  File "C:\\Users\\Broooooo\\Desktop\\GoFPokemonGo-Bot\\pokemongo_bot\\api_wrapper.py", line 124, in can_call']
> 
>  Something went wrong and the bot needed to be restarted. Please investigate the cause.

### Steps to Reproduce
Just start the bot

### Other Information
OS: win10 
Branch: master 
Git Commit: 5eb9fb2447accd252b1cb95433598116425583d5
Python Version: 2.7.12(32bit)
Any other relevant files/configs (eg: path files) 
I really didn't know how to rename and where to put the encrypt dll/so(the instrucions are poorly organized and not explicit) so i've put all their versions and names in the root directory, i don't think that is the problem tho.

**Comment by azraelppuk** [comment]
Getting similar error. Yesterday I got this error:

2016-08-29 19:34:34,328 [PokemonGoBot] [INFO]
Traceback (most recent call last):
  File "pokecli.py", line 781, in <module>
    main()
  File "pokecli.py", line 217, in main
    report_summary(bot)
  File "pokecli.py", line 265, in report_summary
    metrics.capture_stats()
  File "/home/pi/PokemonGo-Bot-Dev-7/PokemonGo-Bot/pokemongo_bot/metrics.py", line 110, in capture_stats
    refresh_inventory(response_dict)
  File "/home/pi/PokemonGo-Bot-Dev-7/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1345, in refresh_inventory
    _inventory.refresh(data)
AttributeError: 'NoneType' object has no attribute 'refresh'

I did a full reinstall of dev. Error went away. Stopped bot over night. Launched again this morning and yet again the same error.

[2016-08-30 10:35:08]
Traceback (most recent call last):
  File "pokecli.py", line 781, in <module>
    main()
  File "pokecli.py", line 217, in main
    report_summary(bot)
  File "pokecli.py", line 265, in report_summary
    metrics.capture_stats()
  File "/home/pi/PokemonGo-Bot-Dev-29/PokemonGo-Bot/pokemongo_bot/metrics.py", line 110, in capture_stats
    refresh_inventory(response_dict)
  File "/home/pi/PokemonGo-Bot-Dev-29/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1345, in refresh_inventory
    _inventory.refresh(data)
AttributeError: 'NoneType' object has no attribute 'refresh'

Wondering if there's a file being written regaridng the inventory than when read causes the crash but when doesn't exist is ok?

**Comment by Creuqe** [comment]
i really don't know anything about programming, do you use windows? @azraelppuk

**Comment by azraelppuk** [comment]
armv7l GNU/Linux on raspberry pi

**Comment by azraelppuk** [comment]
did a fresh 'git pull' and it now works.

**Comment by ivanli88** [comment]
I have same problem run at ubuntu 15.

**Comment by mjmadsen** [comment]
@ivanli88 Did doing the following help:
git pull
git submodule update --init --recursive
git submodule foreach git pull origin master
source bin/activate (-- do not skip this step --)
pip install -r requirements.txt --upgrade
pip install -r requirements.txt

**Comment by ivanli88** [comment]
@mjmadsen Many thanks for your help,  I got an error. "Too many levels of symbolic links"

root@ubuntu:/PokemonGo-Bot# git pull
Already up-to-date.
root@ubuntu:/PokemonGo-Bot# git submodule update --init --recursive
Submodule path 'web': checked out '6ba5609c6151507b5b832a74e471b6b7b1a182c9'
root@ubuntu:/PokemonGo-Bot# git submodule foreach git pull origin master
Entering 'web'
From https://github.com/OpenPoGo/OpenPoGoWeb
 * branch            master     -> FETCH_HEAD
Updating 6ba5609..607397a
Fast-forward
 README.md                         |   2 ++
 config/userdata.js.example        |   6 ++++++
 css/main.css                      |   3 ++-
 image/forts/img_pokestop_lure.png | Bin 0 -> 4960 bytes
 index.html                        |  18 +++++++++---------
 js/main.js                        |  78 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------
 6 files changed, 89 insertions(+), 18 deletions(-)
 create mode 100644 image/forts/img_pokestop_lure.png
root@ubuntu:/PokemonGo-Bot# source bin/activate
(PokemonGo-Bot) root@ubuntu:/PokemonGo-Bot# pip install -r requirements.txt --upgrade
-bash: /PokemonGo-Bot/bin/pip: /PokemonGo-Bot/bin/python2: bad interpreter: Too many levels of symbolic links

**Comment by Creuqe** [comment]
@mjmadsen ran all those commands, except source activate bin because it doesn't work on windows.
Do anyone know how to renae the encrypt dll to put it in the root dir?

**Comment by ivanli88** [comment]
update from ubuntu 15.04 to 15.10  , it's ok now.

**Comment by Creuqe** [comment]
Currently i'm installing ubuntu 16.04.1 LTS, hope there will go straighter

**Comment by mjmadsen** [comment]
@Creuqe Get it working?

**Comment by Creuqe** [comment]
@mjmadsen This laptop isn't dualbooting ubuntu at all
