### ISSUE TITLE
Add requirement validation before starting

### ISSUE THREAD

**Issue by ITAYC0HEN** [PokemonGoF/PokemonGo-Bot#4912]
### Expected Behavior

executing ./run.sh should work
### Actual Behavior

crashing after login successfuly.
### Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/yTzFeMiG
### Output when issue occurred

http://pastebin.com/tUSaxAYa
### Other Information

OS: 
Debian 4.3.3
Branch: 
master
Git Commit: 
56339fba1ba7f77a0275078ea0cf7a73e60c2ed0
Python Version: 
Python 2.7.12

**Comment by mjmadsen** [comment]
Looks like your API is out of date. Please try:
pip install -r requirements.txt --upgrade

**Comment by Ryuspb** [comment]
I have the same error -___-

**Comment by DBa2016** [comment]
The real error is here:
[2016-08-29 18:08:40] [sentry.errors.uncaught] [ERROR] [u'TypeError: call() takes exactly 1 argument (2 given)', u'  File "pokecli.py", line 768, in <module>', u'  File "pokecli.py", line 207, in main', u'  File "pokecli.py", line 253, in report_summary', u'  File "pokemongo_bot/metrics.py", line 109, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 239, in call', u'  File "pokemongo_bot/api_wrapper.py", line 188, in _call']

Has nothing to do with UTF8

**Comment by sediyama** [comment]
I have the same error only with one of my accounts, I think it is a new response to the "Permaban".

**Comment by Ryuspb** [comment]
> I have the same error only with one of my accounts, I think it is a new response to the "Permaban". 

I have tried other accs, did not help...

**Comment by Ryuspb** [comment]
I solved the problem!
I was updated according to the instructions:

**source bin/activate
pip install -r requirements.txt --upgrade
pip install -r requirements.txt**

You must have "Successfully installed php api-1.1.8"

**Comment by mjmadsen** [comment]
I'm going to leave this up as a a FR because this happens a whole lot.

Can we make a change to the methods in which we start the bot to always ensure we're using the correct versions in our requirements? If not we crash and tell the user to execute our updated.
