### ISSUE TITLE
[Feature request]Implement "powerup" in PokemonOptimizer task.

### ISSUE THREAD

**Issue by DBa2016** [PokemonGoF/PokemonGo-Bot#4913]
### Short Description
There are certain conditions which would normally qualify a pokemon to be powered up, e.g. IV=1.0 and id=Snorlax (or some other set). However, the bot currently does not offer a possibility to auto-powerup the pokemons.

### Possible solution
I think the best place to house this feature would be the PokemonOptimizer task. I tried to search for the implementation possibilities myself, but was not able to find the api call for this. Actually, if someone can point me in the right direction, I would implement it myself...

### How it would help others
With this feature, you can fully automatically grow your pokemons.

**Comment by pranavperfect** [comment]
+1

**Comment by mjmadsen** [comment]
Closing #4913
