### ISSUE TITLE
[BUG] Bot walking speed slowing down when telegram enabled

### ISSUE THREAD

**Issue by davidspeijer** [PokemonGoF/PokemonGo-Bot#4914]
### Actual Behavior

Bot is slowing down when telegram is enabled. 

### Steps to Reproduce

Start the bot with telegram enabled. 

### Other Information
OS: centos
 
Branch: dev
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files) 

[https://github.com/PokemonGoF/PokemonGo-Bot/issues/4902](url)

**Comment by davidspeijer** [comment]
Title of the issue is incomplete but cannot change it.

**Comment by avexus** [comment]
Yes, you can. Look at the right of the title.

**Comment by maradlgl** [comment]
same here, when i set "enable_social": true,
bot slow down and failed to connect to broker.pikabot.org:1883

this is log after checking with proxifier
![image](https://cloud.githubusercontent.com/assets/20656016/18070950/dea662f0-6e7b-11e6-9819-f80fee713a7b.png)

**Comment by mjmadsen** [comment]
Please post your config.

**Comment by askovpen** [comment]
i'll fix

**Comment by davidspeijer** [comment]
Don't know if the bot is multi threaded but I suppose this could be the fix?

**Comment by avexus** [comment]
can someone give me a link to the telegram feature?
thank you!

**Comment by davidspeijer** [comment]
Thank you @askovpen 
What kind of link are you looking for @avexus ?
