### ISSUE TITLE
Can loot pokestops but can't catch pokemon starting at lvl20 above...how can i solve this?someone pls help me.

### ISSUE THREAD

**Issue by Arprime30** [PokemonGoF/PokemonGo-Bot#4915]
Pls help me..can't catch pokemon but can loot at pokestop.

**Comment by sohje** [comment]
softban/ip ban

**Comment by SGColdSun** [comment]
Simply wait it out and you'll be able to again. In the future, set your daily pokemon catch limit to something lower.
