### ISSUE TITLE
Better  "RecycleItems" logic

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#4917]
"RecycleItems" now goes through the keep list until the very end. If we have "min_empty_space" specified, then we want to stop when this criteria is met.

if
"smart_recycle_items": true
then
stop when 
"min_empty_space" is big enough.

**Comment by mjmadsen** [comment]
min_empty_space is primary there to prevent transferring items right after you get them. Set min_empty_spaces to 999 if you want it to happen all the time.

**Comment by avexus** [comment]
I understand what min_empty_space does.
I want the recycle that does not go through all the way till the list. Say if I have 150 Pokeballs, 75 Greatballs, 50 Ultra Balls.
And my configure says keep 100 poke balls, 50 great balls.
 Then if I recycle 50 Poke Balls, the min_empty_space requirement is met, then the recycle should stop, in this case, I can accumulate more Great Balls and more Ultra Balls.
Does this make sense? @mjmadsen

**Comment by mjmadsen** [comment]
If you don't specify how many greatballs and up you want to keep in the config, it'll trim to whatever "max_balls_keep" is set to, first by dropping regular pokeballs, then great and so on. If you do specify limits for each kind of ball, it'll trim them all to that number.
