### ISSUE TITLE
Add button in item webIU

### ISSUE THREAD

**Issue by Jcolomar** [PokemonGoF/PokemonGo-Bot#4927]
### Short Description

Add a "ACTION" button in item window to use/discard item. For the ppl dont use incense for evolve pokemons to gain more exp, we keeping this items in bag and dont have chance to use it when we want or discard it. Same happens with lure modules. I know discard option can be setting in config, but like in pokemon windows, id like the posibility to use/discard

### Possible solution

Same like in pokemon window "ACTION" button: Use/discard. For lure modules maybe "use next pokestop"

**Comment by r3pek** [comment]
can't even use the one on the pokemon list :P
