### ISSUE TITLE
help

### ISSUE THREAD

**Issue by sumanth5526** [PokemonGoF/PokemonGo-Bot#4932]
### Actual Behavior

not able to start the bot
using ./run.sh

### Output when issue occurred

tele@tele-desktop165:~/Desktop/a$ ./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 43, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetException
ImportError: No module named pgoapi.exceptions
Tue Aug 30 17:06:34 IST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

### Other Information
OS: 
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by sohje** [comment]
pip install -r requirements.txt --upgrade
