### ISSUE TITLE
Updating the bot (with setup.sh -r) fails with message "Too many levels of symbolic links"

### ISSUE THREAD

**Issue by castorfou** [PokemonGoF/PokemonGo-Bot#4934]
### Expected Behavior

Bot updated to last version

### Actual Behavior

Error is displayed in terminal.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/g9HZ91QP

### Output when issue occurred

Branch master resetting.
HEAD is now at 56339fb Merge dev to master (#4889)
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/guillaume/Applications/PokemonGo-Bot/bin/python2
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2327, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 924, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 1230, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 40] Too many levels of symbolic links: '/home/guillaume/Applications/PokemonGo-Bot/bin/python2'
Already up-to-date.
Submodule path 'web': checked out '6ba5609c6151507b5b832a74e471b6b7b1a182c9'
Entering 'web'
From https://github.com/OpenPoGo/OpenPoGoWeb
 * branch            master     -> FETCH_HEAD
Updating 6ba5609..607397a
Fast-forward
 README.md                         |   2 ++
 config/userdata.js.example        |   6 +++++
 css/main.css                      |   3 ++-
 image/forts/img_pokestop_lure.png | Bin 0 -> 4960 bytes
 index.html                        |  18 +++++++-------
 js/main.js                        |  78 +++++++++++++++++++++++++++++++++++++++++++++++++++++------
 6 files changed, 89 insertions(+), 18 deletions(-)
 create mode 100644 image/forts/img_pokestop_lure.png
./setup.sh: /home/guillaume/Applications/PokemonGo-Bot/bin/pip: /home/guillaume/Applications/PokemonGo-Bot/bin/python: bad interpreter: Too many levels of symbolic links
./setup.sh: /home/guillaume/Applications/PokemonGo-Bot/bin/pip: /home/guillaume/Applications/PokemonGo-Bot/bin/python: bad interpreter: Too many levels of symbolic links

### Steps to Reproduce

execute ~/Applications/PokemonGo-Bot$ LANG=C ./setup.sh -r

### Other Information
OS: 
ubuntu 16.04
Branch: 
master
Git Commit: 
56339fba1ba7f77a0275078ea0cf7a73e60c2ed0
Python Version: 
 
Python 2.7.12
Any other relevant files/configs (eg: path files)

**Comment by mjmadsen** [comment]
Try this before "source bin/activate":
pip install -r requirements.txt --upgrade

But I'm still curious as to why you're getting such an error.

**Comment by mjmadsen** [comment]
git pull
git submodule update --init --recursive
git submodule foreach git pull origin master
source bin/activate (-- do not skip this step --)
pip install -r requirements.txt --upgrade
pip install -r requirements.txt

**Comment by castorfou** [comment]
pip install -r requirements.txt --upgrade
fails with this message:
(PokemonGo-Bot) guillaume@XPS:~/Applications/PokemonGo-Bot$ pip install -r requirements.txt --upgrade
bash: /home/guillaume/Applications/PokemonGo-Bot/bin/pip: /home/guillaume/Applications/PokemonGo-Bot/bin/python: bad interpreter: Too many levels of symbolic links

but sudo  pip install -r requirements.txt --upgrade
works

the same for  pip install -r requirements.txt

**Comment by mjmadsen** [comment]
Try the upgrade not in virtualenv

**Comment by castorfou** [comment]
Does that mean without executing source bin/activate  ?
