### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by hiiphop** [PokemonGoF/PokemonGo-Bot#4944]
Hello everyone. I have used ubuntu 14.04.05, python 2.7.6 and pip 1.5.4. I exactly did step by step manual installation document. But when i run this script `./run.sh`, The bot didn't run. It said : 

./run.sh: line 16: bin/activate: No such file or directory
Traceback (most recent call last):
  File "pokecli.py", line 43, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetException
ImportError: No module named pgoapi.exceptions
Thứ ba, 30 Tháng tám năm 2016 22:54:17 ICT Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

Somebody help me pls !

**Comment by gungoan** [comment]
install pgopi

**Comment by hiiphop** [comment]
sorry! i don't understand.

**Comment by mjmadsen** [comment]
git pull
git submodule update --init --recursive
git submodule foreach git pull origin master
source bin/activate (-- do not skip this step --)
pip install -r requirements.txt --upgrade
pip install -r requirements.txt

**Comment by hiiphop** [comment]
Thank you! it worked for me.
