### ISSUE TITLE
Bot is not incubating

### ISSUE THREAD

**Issue by farshidhss** [PokemonGoF/PokemonGo-Bot#4947]
### Expected Behavior
On the latest dev branch, it is expected to incubate eggs as long as there is an egg available. 

### Actual Behavior
There is no log of the egg incubation nor any egg is actually incubated. 

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/viSJHTXs

### Other Information
OS: 
Mac OS X 10.11.6
Branch: 
dev
Git Commit: 
28450ce9f98122a81a1162b943b7500d3a0f191c
Python Version: 
2.7
Any other relevant files/configs (eg: path files)

**Comment by mjmadsen** [comment]
Can I see a terminal log?

**Comment by davidakachaos** [comment]
I have this issue too. I can show some logs, but it doesn't even log the incubate eggs when I start the bot.
see: http://pastebin.com/bkhw66Tf

**Comment by farshidhss** [comment]
Sure, please see the logs here: http://pastebin.com/XfEgq0YL

**Comment by db-coder** [comment]
Same with me. Bot isn't incubating eggs.

**Comment by AhiruDuck** [comment]
Same happening here, latest dev branch on OS X. bot is not incubating

**Comment by mmixx** [comment]
Yeah... same as with me... updated mine few hours ago and noticed that it isn't incubating eggs...

**Comment by mmixx** [comment]
Updated my copy just now and it's working...

`[2016-08-31 03:56:28] [IncubateEggs] [INFO] [incubate] Incubating a 2.0 egg.`

**Comment by askovpen** [comment]
#4967 when to master?

**Comment by mmixx** [comment]
After updating to latest dev... I encountered an error when egg finished incubating... I thought it was just a hiccup but I've waited for another egg to finished the incubation and it again triggered this error:

`Traceback (most recent call last):
  File "pokecli.py", line 781, in <module>
    main()
  File "pokecli.py", line 139, in main
    bot.tick()
  File "/home/chris/PokemonGo-Bot/pokemongo_bot/__init__.py", line 658, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/chris/PokemonGo-Bot/pokemongo_bot/cell_workers/incubate_eggs.py", line 45, in work
    self._hatch_eggs()
  File "/home/chris/PokemonGo-Bot/pokemongo_bot/cell_workers/incubate_eggs.py", line 215, in _hatch_eggs
    if not pokemon_ids or pokemon_data[0]['name'] == "error":
IndexError: list index out of range
Wed Aug 31 06:06:39 PHT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.`

**Comment by RedViper9** [comment]
Fixed in #4973

**Comment by db-coder** [comment]
@RedViper9 any ideas how I can see the eggs it hatched while the bot wasn't showing logs for this task? I remember I had 2 10K eggs last time the bot was showing info about eggs but now I don't seem to have those i.e. they must have hatched.

**Comment by mjmadsen** [comment]
@db-coder We currently do not save such information, so it is lost, sorry. I think there is a FR for storing hatched results in a db (might be good for crowdsourcing data).

**Comment by RedViper9** [comment]
@db-coder as per mjmadsen's comment we don't keep those logs. If you have a log of pokemon caught v.s. pokemon evolved v.s. pokemon transfered you should be able to puzzle it out.
