### ISSUE TITLE
WebUI weird issue

### ISSUE THREAD

**Issue by krishven** [PokemonGoF/PokemonGo-Bot#4953]
### Expected Behavior
When I click on Info, it shows info about my level, XP, pokestops visited etc
Also info about Pokemon caught is shown immediatey etc

### Actual Behavior
When I click on Info, it doesn't show info about my level etc its blank
Info about Pokemon caught is old data, newer Pokemon not shown

### Steps to Reproduce
Start python server
load localhost:8000 in browser

### Other Information
OS: 
Ubuntu
Branch: 
dev
Git Commit: 
6ba5609c6151507b5b832a74e471b6b7b1a182c9
Python Version: 
Python 2.7.12

**Comment by oralunal** [comment]
This issue exists for 2-3 days

**Comment by kirikay** [comment]
IMO, it's not an issue... check ur config, Update Live Status should be "True"...

**Comment by krishven** [comment]
@kirikay even then the info about my XP, level is not displayed
it is blank with just a heading that says "Submenu"

**Comment by oralunal** [comment]
Changed the web UI from OpenPoGoWeb to Pokemongo-Web... Not its working.

**Comment by krishven** [comment]
@oralunal Is it working or not?

**Comment by oralunal** [comment]
@krishven I wrote "Not" instead of "Now". It's working now.

**Comment by krishven** [comment]
@oralunal how do I change it?
