### ISSUE TITLE
Release and catch based on NCP

### ISSUE THREAD

**Issue by janjuafarooq** [PokemonGoF/PokemonGo-Bot#4963]
**Short Description**

I would like to be able to catch or release pokemon based on their NCP, instead of just CP.  

**Possible solution**

Add these fields for the transfer_pokemon cell worker

**How it would help others**

This would make it easier than having to find high CP values for each pokemon.

**Comment by mrincredible2017** [comment]
NCP?

**Comment by intuition17** [comment]
Normalized cp (current/max)

**Comment by avexus** [comment]
@intuition17 I saw NCP in the output. Could you enlighten me what this number does? Is it better to have a bigger NCP value?

**Comment by RedViper9** [comment]
NCP is the pokemon level / trainer level. So it's a fraction of how powerful the poke is compared to how powerful it can be (which is limited by current trainer level). CP depends on IV but NCP does not.

**Comment by xivaxy** [comment]
Actually the NCP the bot currently shows does not seem to be pokemon level / trainer level, but rather something close to pokemon level / 39. 
E.g. it shows Jynx (CP 999, NCP 0.58, Level 21.0, IV 0.8), and my trainer level is 21.
