### ISSUE TITLE
Errors logged in output when Eggs hatching.

### ISSUE THREAD

**Issue by JimmyMultani** [PokemonGoF/PokemonGo-Bot#4966]
### Expected Behavior

When egg is hatching, details of Pokemon should appear.

### Actual Behavior

Details appear as:
```Shell
[IncubateEggs] [INFO] [egg_hatched] {'candy': 'error', 'iv': 'error', 'stardust': 'error', 'exp': 'error', 'cp': 'error', 'pokemon': 'error'}
```

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/JbAE8rGC

### Output when issue occurred

```Shell
[IncubateEggs] [INFO] [egg_hatched] {'candy': 'error', 'iv': 'error', 'stardust': 'error', 'exp': 'error', 'cp': 'error', 'pokemon': 'error'}
```

### Steps to Reproduce

Set up Egg Incubation settings, let eggs hatch. Happens inconsistently.

### Other Information
OS: OSX
 
Branch: Master
 
Git Commit: 56339fba1ba7f77a0275078ea0cf7a73e60c2ed0
 
Python Version: 2.7.10
 
Any other relevant files/configs (eg: path files) 

N/A

**Comment by Gobberwart** [comment]
Looking at this now

**Comment by leadboots5** [comment]
Mine actually crashed when it hatched on the latest dev:

```
Traceback (most recent call last):
  File "pokecli.py", line 781, in <module>
    main()
  File "pokecli.py", line 139, in main
    bot.tick()
  File "C:\Users\Josh\Downloads\PokemonGo-Bot\pokemongo_bot\__init__.py", line 658, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "C:\Users\Josh\Downloads\PokemonGo-Bot\pokemongo_bot\cell_workers\incubate_eggs.py", line 45, in work
    self._hatch_eggs()
  File "C:\Users\Josh\Downloads\PokemonGo-Bot\pokemongo_bot\cell_workers\incubate_eggs.py", line 215, in _hatch_eggs
    if not pokemon_ids or pokemon_data[0]['name'] == "error":
IndexError: list index out of range
```

**Comment by mmixx** [comment]
Encountered same errors with mine...

**Comment by Asafffff** [comment]
mine crashed too, but i have another problem - it says it reads from C:\Python while my Python installation is on D:\
http://pastebin.com/dXQTTiBf

**Comment by Jasperrr91** [comment]
Check out this @Asafffff 
http://stackoverflow.com/questions/4583367/how-to-run-multiple-python-version-on-windows

**Comment by Gobberwart** [comment]
OK, I think I've just about got this nailed... PR coming soon I hope.

**Comment by mmixx** [comment]
Updated from last commit... It doesn't produce or crashed the bot, but it also didn't indicate or output the info about the hatched egg...

`[2016-08-31 08:40:30] [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Best Friends - 0.09km`
`[2016-08-31 08:40:36] [IncubateEggs] [INFO] [incubate] Incubating a 5.0 egg.`
`[2016-08-31 08:40:36] [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Best Friends - 0.08km`

**Comment by Gobberwart** [comment]
I think the issue here is that the cached inventory does not properly reflect that an egg has been hatched, so it can't find a match, so it reports garbage. Going to add a call to refresh inventory on egg_hatch before it compares.

**Comment by mmixx** [comment]
Working perfectly now... Thanks @Gobberwart :)

**Comment by Gobberwart** [comment]
Thank @DeXtroTip - he beat me by a few minutes :)

**Comment by mjmadsen** [comment]
Closing #4966
