### ISSUE TITLE
web interface not showing pokedex, items etc.

### ISSUE THREAD

**Issue by vanrzuf** [PokemonGoF/PokemonGo-Bot#497]
Just checked this out and items, pokedex, info, and pokemon gives only [object Object],[object Object],[object Object],[object Object],[object Object]. I'ts on dev.

**Comment by jmeyer2k** [comment]
This is a known issue. We'll be redesigning the web interface in the future. https://github.com/PokemonGoF/PokemonGo-Bot/issues/492

**Comment by vanrzuf** [comment]
kk
