### ISSUE TITLE
Update minor error

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#4972]
does not affect running, but i think you might want to know.
Windows 10, gitBash.
git pull first, then

\PokemonGo-Bot>git submodule update --init --recursive
error: no such remote ref e9322cd8952bcc1bbd70e302d3943d0abe5d3a00
Fetched in submodule path 'web', but it did not contain e9322cd8952bcc1bbd70e302d3943d0abe5d3a00. Direct fetching of that commit failed.

**Comment by Gobberwart** [comment]
Should be ok now
