### ISSUE TITLE
Multiple errors then crash

### ISSUE THREAD

**Issue by theresthatguy** [PokemonGoF/PokemonGo-Bot#4975]
### Expected Behavior

Bot to run. 

### Actual Behavior

Bot crashes after login

### FULL config.json

auth.json: http://pastebin.com/aCdbFitq
config.json: http://pastebin.com/zcXFvF1C

### Output when issue occurred

http://pastebin.com/JTdZU6NT

### Steps to Reproduce

```
git clone https://github.com/PokemonGoF/PokemonGo-Bot
cd PokemonGo-Bot
./setup.sh -i
```
Copy/edit/validate auth/config.json
```
./run.sh
```

### Other Information
OS: Linux Mint 18
 
Branch: master
 
Git Commit: 0e226418
 
Python Version: 2.7.12

**Comment by jrjhealey** [comment]
You would probably be well advised to switch to dev from master, it's generally a few commits ahead at least at any given time.

**Comment by theresthatguy** [comment]
What happened to master being stable?

**Comment by theresthatguy** [comment]
Just did a git pull and install from the Dev branch and I'm getting the exact same errors.

**Comment by Gobberwart** [comment]
You can't possibly be getting the exact same errors. At least one of those has been addressed in a very recent dev update. 

`TypeError: not all arguments converted during string formatting`

Paste your latest error output.

**Comment by jrjhealey** [comment]
Are you using virtualenv? First error I see is that it failed to find bin/activate
