### ISSUE TITLE
Need clarification on which tasks use API calls

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#4976]
I'm guessing "EvolvePokemon", "TransferPokemon", "RecycleItems", etc use API calls, but how about
"UpdateLiveInventory", "UpdateLiveStats" etc? Do these only pull information from client side and don't have to make calls to server?

Maybe a comment on conf file will be nice. And also in documentation.

**Comment by Gobberwart** [comment]
It depends what hour of which day you ask. We're (I'm??) in the process of removing as many api calls as possible, so this is highly variable. 

Don't see any need to document it.

**Comment by Gobberwart** [comment]
This isn't an issue. If knowing which tasks make api calls is important, check the source.

**Comment by avexus** [comment]
i'll do that. What do API calls look like? Give me 1 or 2 examples, so I can get started. Thank you @Gobberwart

**Comment by rawgni** [comment]
@avexus it starts with self.bot.api

**Comment by Gobberwart** [comment]
@avexus Sometimes just self.api, eg.

From __init__.py line 1329
`        self.last_map_object = self.api.get_map_objects(`

From metrics.py line 103
`            request = self.bot.api.create_request()`
