### ISSUE TITLE
Telegram- sending 2 notifications per event and repetitive line in logger

### ISSUE THREAD

**Issue by crvfts** [PokemonGoF/PokemonGo-Bot#4977]
Few things I'm noting with Telegram:

I receive 2 notifications per event.

Get repetitive line in logger: "Connection pool is full, discarding connection: api.telegram.org"

"alert_catch": {
            "all": {"operator": "and", "cp": 9, "iv": 0.9}
          }

but I'm still getting notifications for every single catch. That should only be sending messages for pokemon with at least CP 9 and IV 0.9, correct?

**Comment by Gobberwart** [comment]
I'm getting the same "connection pool is full" error... I believe the fault is on their side, not ours.

**Comment by Gobberwart** [comment]
From what I can tell, we should be able to safely ignore these warnings (see https://github.com/python-telegram-bot/python-telegram-bot/issues/341)

I don't know enough about telegram to say for sure.

**Comment by askovpen** [comment]
which bot commit?

**Comment by davidakachaos** [comment]
This still happens as of now; commit 4cce54823e4209ad0000b5166be7443e5c775194

**Comment by askovpen** [comment]
check on master

**Comment by Gobberwart** [comment]
Issue with "connection pool is full" fixed #5307
