### ISSUE TITLE
docker cant find auth.json and config.json

### ISSUE THREAD

**Issue by ntanto** [PokemonGoF/PokemonGo-Bot#4985]
### Actual Behavior
already try timezone and TIMEZONE

### Output when issue occurred
Step 13 : RUN printf "#!/bin/sh\n\nTIMEZONE=\${TIMEZONE:-Etc/UTC}\n\nln -sfn /usr/share/zoneinfo/\$TIMEZONE /etc/localtime\necho \$TIMEZONE > /etc/timezone\n\npython pokecli.py \$@\n" > /entrypoint.sh     && chmod +x /entrypoint.sh

One or more build-args [TIMEZONE] were not consumed, failing build.

### Other Information
OS: Windows 10
Branch: Master
Git Commit: 0e2264180fb87283df923d618918374e53f396b4
Python Version: 2.7.12

**Comment by ntanto** [comment]
docker can't find auth.json and config.json

problem solved, docker share driv uncheck
restore the shared drive and its back running

timezone still unsolve

**Comment by walkerlee** [comment]
@ntanto docker build --build-arg TIMEZONE is no longer available

You can use -e TIMEZONE=Asia/Taipei to set your container timezone

```
⋊> ~/h/PokemonGo-Bot on dev ⨯ docker run --rm -it -e TIMEZONE=Asia/Taipei pokemongo-bot --help | head -n2
2016-08-31 22:31:58,054 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-31 22:31:58,065 [       cli] [INFO] commit: 42d670a4
⋊> ~/h/PokemonGo-Bot on dev ⨯ docker run --rm -it -e TIMEZONE=Europe/London pokemongo-bot --help | head -n2
2016-08-31 15:32:12,575 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-31 15:32:12,583 [       cli] [INFO] commit: 42d670a4
⋊> ~/h/PokemonGo-Bot on dev ⨯ docker run --rm -it -e TIMEZONE=Africa/Cairo pokemongo-bot --help | head -n2
2016-08-31 16:33:04,085 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-31 16:33:04,094 [       cli] [INFO] commit: 42d670a4
```

**Comment by ntanto** [comment]
@walkerlee thanks a lot
i use -e TZ=Asia/Singapore, its shorter
case closed, problem solved

**Comment by walkerlee** [comment]
@ntanto yes, it's better 👍

**Comment by MrCarlosJr** [comment]
I can use this out of docker?

**Comment by walkerlee** [comment]
@MrCarlosJr yes
```
bash-3.2$ TZ=Asia/Taipei date
Mon Sep  5 18:49:10 CST 2016
bash-3.2$ TZ=Asia/Tokyo date
Mon Sep  5 19:49:15 JST 2016
```
