### ISSUE TITLE
store sleep timers between restarts

### ISSUE THREAD

**Issue by cbogithub** [PokemonGoF/PokemonGo-Bot#4986]
[2016-08-31 12:30:21] [SleepSchedule] [INFO] [bot_sleep] Sleeping for 05:05:47, wake at 2016-08-31 17:36:08.043000

after restart bot :   
[2016-08-31 13:45:29] [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Spearow! [CP 360] [NCP 0.52] [Potential 0.62] [3/13/12] (649/800) [+120 exp]
[2016-08-31 13:45:29] [PokemonCatchWorker] [INFO] [gained_candy] You now have 75 Spearow candy!

bot not resume sleep !!!!

**Comment by mjmadsen** [comment]
Sleep timers reset after each restart. Can I ask why you restarted?

Anyway, we could save the timers, but they are arbitrary in the first place. Unless you have the sleep action to start at a minimum of hours from now, it shouldn't make that much of a difference.

**Comment by avexus** [comment]
I don't see this as a big problem. Every time I change the conf file and save it, the timer restarts.

**Comment by mjmadsen** [comment]
@avexus Indeed, but it can be logged as a FR regardless.

**Comment by cbogithub** [comment]
i think store sleep timers between restarts to avoid  ban accounts, such bot will like humans.. Now timers was stored between we restart bot

Thanks

**Comment by robertpro** [comment]
I do something like @cbogithub , but i manually let the bot sleep, I run this command:

sleep 24000; ./run.sh

Thats it!

**Comment by oralunal** [comment]
I don't think this is an issue. If you're restarting bot that means you want bot to run.
