### ISSUE TITLE
Account is not yet active, please redirect

### ISSUE THREAD

**Issue by rawgni** [PokemonGoF/PokemonGo-Bot#4993]
### Expected Behavior
Logged in

### Actual Behavior
The bot failed to log in. See log for more info.

### Output when issue occurred

2016-08-31 18:29:19,439 [PokemonGoBot] [INFO] [login_started] Login procedure started.
2016-08-31 18:29:20,991 [pgoapi.auth] [ERROR] Could not retrieve token: Account is not yet active, please redirect.
2016-08-31 18:29:20,991 [pgoapi.pgoapi] [ERROR] Login process failed: User login failed!
2016-08-31 18:29:20,992 [PokemonGoBot] [INFO] [login_failed] Login error, server busy. Waiting 10 seconds to try again.

### Steps to Reproduce
Create a NEW PTC account.
Verify email.

Run bot.

### Other Information
OS: MacOSX
Branch: dev
Git Commit: 4cce54823e4209ad0000b5166be7443e5c775194
Python Version: 2.7.10

**Comment by sohje** [comment]
Try to accept TOS on profile page.

**Comment by rawgni** [comment]
![screen shot 2016-08-31 at 6 49 12 pm](https://cloud.githubusercontent.com/assets/11707733/18127601/a5ed37a0-6fab-11e6-8f40-20de795f9135.png)
nope :(

**Comment by sohje** [comment]
Can you try to verify your email again?

**Comment by rawgni** [comment]
yes, i can. and still doesn't work

**Comment by sohje** [comment]
I just created new account. Verified, tos accepted -> login success.

**Comment by sohje** [comment]
Can you try to login via phone or phone emulator?

**Comment by rawgni** [comment]
yes. I can login using my phone. 
I tried it again with the bot after successfully logged in on the phone.
Same error message. Account not yet active.

**Comment by rawgni** [comment]
hm.. even my main account get the same error message.

**Comment by rawgni** [comment]
@sohje my bad. i have multiple login info into multiple config files :( . Ty for the help
