### ISSUE TITLE
What is the risk of ban using the bot ?

### ISSUE THREAD

**Issue by LUCKASSs** [PokemonGoF/PokemonGo-Bot#4994]
Hello,
I would like to using the bot with a second account on my phone, what is the chance that I get banned with the account on my Phone AND in the bot (not connected at the same time and level 11 btw) ? (I'm using Ubuntu Mate on a Raspberry Pi 3)

I have tested an 3rd account this morning without stopping the process, he's now level 8 without ban.

And what is the best walking Speed to not get spotted ?
Last question (yes I'm retarded), how I can configure Walking Speed on Ubuntu using command line ?

Thx !

**Comment by GlennSmeulders** [comment]
You will be banned if you use a bot, simple

**Comment by ntcong** [comment]
close to 100% at level 20.

**Comment by kevinsmendes** [comment]
Very high. You should use the bot for fun only. Play with your account legit, and make a throw away account just to chill out. Please, do not use the bot account in Gyms and future player vs player activities. This would be really a douche move.

**Comment by LUCKASSs** [comment]
Yeah I just use the bot for more level and better pokemon at my Lured Pokestop

**Comment by mjmadsen** [comment]
If you use the bot at all, your chances of being banned are great. @GlennSmeulders isn't wrong.

If you're concerned about being banned, don't bot on an account you don't want to risk losing.
