### ISSUE TITLE
Web map not loading 

### ISSUE THREAD

**Issue by foster82** [PokemonGoF/PokemonGo-Bot#4997]
When trying to use the web interface I keep getting this error and it will not load the map data, however it does load the rest of the data

[31/Aug/2016 14:04:35] "GET /socket.io/?EIO=3&transport=polling&t=LRWwczH HTTP/1.1" 404 -

**Comment by oralunal** [comment]
What map datas isn't loading?

**Comment by foster82** [comment]
Where there should be Google Maps I am just getting a blue back ground

**Comment by crvfts** [comment]
solid blue or Pokemon Go color scheme? if Pokemon colorscheme and you want to see google maps' scheme you'll need to edit /web/js/main.js.  search for mapTypeId: 'roadmap', and then delete inside styles, resulting in- styles: [ ]

**Comment by foster82** [comment]
It's just solid blue,  it's like it's not loading all the data. I get a character and I can see the line as the bot moves. I am still also getting the 404 error.

**Comment by foster82** [comment]
Still having this problem any ideas anyone

**Comment by sskes** [comment]
#5045 

problem solved, i've made two changes
