### ISSUE TITLE
Bot doesn't seem to get PokeBalls

### ISSUE THREAD

**Issue by phupabegim** [PokemonGoF/PokemonGo-Bot#500]
Started using `pokecli.py -a google -u XXXXX -p XXXXX -c 1` the bot is finding lots of Pokemon but not PokeBalls. Do I need to specify additional parameter when I start or not?

**Comment by s1x** [comment]
If you run out of pokeballs the bot will automatically go to pokestops and get pokeballs again. (e.g. working on dev branch)

**Comment by phupabegim** [comment]
What's the default mode if not specified?

**Comment by phupabegim** [comment]
@s1x ?
