### ISSUE TITLE
the console only shows updates every 2 minutes

### ISSUE THREAD

**Issue by palerique** [PokemonGoF/PokemonGo-Bot#5000]
### Expected Behavior
update more often console showing that the bot is working

(If it is not a issue what I can do to solve the problem???)

### Actual Behavior
the console only shows updates every 2 minutes.

As if the bot only do something every 2 minutes

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
`{
  "websocket_server": false,
  "heartbeat_threshold": 10,
  "enable_social": true,
  "live_config_update": {
    "enabled": false,
    "tasks_only": false
  },
  "tasks": [
    {
      "type": "TelegramTask",
      "config": {
        "enabled": false,
        "master": null,
        "min_interval": 120,
        "// old syntax, still supported: alert_catch": [
          "all"
        ],
        "// new syntax:": {},
        "alert_catch": {
          "all": {
            "operator": "and",
            "cp": 1300,
            "iv": 0.95
          },
          "Snorlax": {
            "operator": "or",
            "cp": 900,
            "iv": 0.9
          }
        }
      }
    },
    {
      "//NOTE: This task MUST be placed on the top of task list": {},
      "type": "RandomAlivePause",
      "config": {
        "enabled": false,
        "min_duration": "00:00:10",
        "max_duration": "00:10:00",
        "min_interval": "00:05:00",
        "max_interval": "01:30:00"
      }
    },
    {
      "type": "HandleSoftBan"
    },
    {
      "type": "RandomPause",
      "config": {
        "enabled": false,
        "min_duration": "00:00:10",
        "max_duration": "00:10:00",
        "min_interval": "00:10:00",
        "max_interval": "02:00:00"
      }
    },
    {
      "type": "CompleteTutorial",
      "config": {
        "enabled": false,
        "// set a name": "",
        "nickname": ""
      }
    },
    {
      "type": "CollectLevelUpReward",
      "config": {
        "collect_reward": true,
        "level_limit": -1
      }
    },
    {
      "type": "IncubateEggs",
      "config": {
        "enabled": true,
        "infinite_longer_eggs_first": false,
        "breakable_longer_eggs_first": true,
        "min_interval": 120,
        "infinite": [
          2,
          5,
          10
        ],
        "breakable": [
          2,
          5,
          10
        ]
      }
    },
    {
      "type": "UpdateLiveStats",
      "config": {
        "enabled": true,
        "min_interval": 120,
        "stats": [
          "username",
          "uptime",
          "stardust_earned",
          "xp_earned",
          "xp_per_hour",
          "stops_visited"
        ],
        "terminal_log": true,
        "terminal_title": true
      }
    },
    {
      "type": "UpdateLiveInventory",
      "config": {
        "enabled": true,
        "min_interval": 120,
        "show_all_multiple_lines": false,
        "items": [
          "pokemon_bag",
          "space_info",
          "pokeballs",
          "greatballs",
          "ultraballs",
          "razzberries",
          "luckyegg"
        ]
      }
    },
    {
      "type": "ShowBestPokemon",
      "config": {
        "enabled": true,
        "min_interval": 120,
        "amount": 5,
        "order_by": "cp",
        "info_to_show": [
          "cp",
          "ivcp",
          "dps",
          "hp"
        ]
      }
    },
    {
      "type": "TransferPokemon",
      "config": {
        "enabled": false,
        "min_free_slot": 5,
        "transfer_wait_min": 3,
        "transfer_wait_max": 5
      }
    },
    {
      "type": "NicknamePokemon",
      "config": {
        "enabled": false,
        "nickname_above_iv": 0.9,
        "nickname_template": "{iv_pct}_{iv_ads}"
      }
    },
    {
      "type": "EvolvePokemon",
      "config": {
        "enabled": false,
        "// evolve only pidgey and drowzee": "",
        "// evolve_list": "pidgey, drowzee",
        "// donot_evolve_list": "none",
        "// evolve all but pidgey and drowzee": "",
        "// evolve_list": "all",
        "// donot_evolve_list": "pidgey, drowzee",
        "evolve_list": "all",
        "donot_evolve_list": "none",
        "first_evolve_by": "cp",
        "evolve_above_cp": 500,
        "evolve_above_iv": 0.8,
        "logic": "or",
        "min_evolve_speed": 25,
        "max_evolve_speed": 30,
        "use_lucky_egg": false
      }
    },
    {
      "type": "RecycleItems",
      "config": {
        "enabled": true,
        "min_empty_space": 15,
        "max_balls_keep": 150,
        "max_potions_keep": 50,
        "max_berries_keep": 70,
        "max_revives_keep": 70,
        "item_filter": {
          "Pokeball": {
            "keep": 100
          },
          "Potion": {
            "keep": 10
          },
          "Super Potion": {
            "keep": 20
          },
          "Hyper Potion": {
            "keep": 30
          },
          "Revive": {
            "keep": 30
          },
          "Razz Berry": {
            "keep": 100
          }
        },
        "recycle_wait_min": 3,
        "recycle_wait_max": 5,
        "recycle_force": true,
        "recycle_force_min": "00:01:00",
        "recycle_force_max": "00:05:00"
      }
    },
    {
      "type": "CatchPokemon",
      "config": {
        "enabled": true,
        "catch_visible_pokemon": true,
        "catch_lured_pokemon": true,
        "min_ultraball_to_keep": 5,
        "berry_threshold": 0.35,
        "vip_berry_threshold": 0.9,
        "treat_unseen_as_vip": true,
        "daily_catch_limit": 800,
        "catch_throw_parameters": {
          "excellent_rate": 0.1,
          "great_rate": 0.5,
          "nice_rate": 0.3,
          "normal_rate": 0.1,
          "spin_success_rate": 0.6,
          "hit_rate": 0.75
        },
        "catch_simulation": {
          "flee_count": 3,
          "flee_duration": 2,
          "catch_wait_min": 3,
          "catch_wait_max": 6,
          "berry_wait_min": 3,
          "berry_wait_max": 5,
          "changeball_wait_min": 3,
          "changeball_wait_max": 5,
          "newtodex_wait_min": 20,
          "newtodex_wait_max": 30
        }
      }
    },
    {
      "type": "SpinFort",
      "config": {
        "enabled": true,
        "spin_wait_min": 3,
        "spin_wait_max": 5,
        "daily_spin_limit": 1900
      }
    },
    {
      "type": "UpdateWebInventory",
      "config": {
        "enabled": true
      }
    },
    {
      "type": "MoveToFort",
      "config": {
        "enabled": true,
        "lure_attraction": true,
        "lure_max_distance": 2000,
        "walker": "StepWalker",
        "log_interval": 5
      }
    },
    {
      "type": "FollowSpiral",
      "config": {
        "enabled": true,
        "diameter": 4,
        "step_size": 70
      }
    },
    {
      "type": "PokemonOptimizer",
      "config": {
        "enabled": true,
        "transfer": true,
        "transfer_wait_min": 3,
        "transfer_wait_max": 5,
        "evolve": true,
        "evolve_time": 25,
        "evolve_for_xp": true,
        "evolve_only_with_lucky_egg": false,
        "evolve_count_for_lucky_egg": 80,
        "may_use_lucky_egg": true,
        "groups": {
          "gym": [
            "Dragonite",
            "Snorlax"
          ]
        },
        "keep": [
          {
            "mode": "by_family",
            "top": 1,
            "sort": [
              {
                "iv": 0.9
              }
            ],
            "evolve": true
          },
          {
            "mode": "by_family",
            "top": 1,
            "sort": [
              {
                "ncp": "0.9"
              }
            ],
            "evolve": true
          },
          {
            "mode": "by_family",
            "top": 1,
            "sort": [
              "cp"
            ],
            "evolve": false
          },
          {
            "mode": "by_pokemon",
            "names": [
              "gym"
            ],
            "top": 5,
            "sort": [
              "cp"
            ],
            "evolve": false
          }
        ]
      }
    }
  ],
  "map_object_cache_time": 5,
  "forts": {
    "avoid_circles": true,
    "max_circle_size": 50,
    "cache_recent_forts": true
  },
  "pokemon_bag": {
    "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
    "show_at_start": true,
    "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
    "show_count": false,
    "// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
    "show_candies": false,
    "// 'pokemon_info' parameter define which info to show for each pokemon": {},
    "// the available options are": {},
    "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
    "pokemon_info": [
      "cp",
      "iv_pct"
    ]
  },
  "walk_max": 4.16,
  "walk_min": 2.16,
  "alt_min": 500,
  "alt_max": 1000,
  "sleep_schedule": [
    {
      "time": "12:00",
      "duration": "5:30",
      "time_random_offset": "00:30",
      "duration_random_offset": "00:30",
      "wake_up_at_location": ""
    },
    {
      "time": "17:45",
      "duration": "3:00",
      "time_random_offset": "01:00",
      "duration_random_offset": "00:30",
      "wake_up_at_location": ""
    }
  ],
  "gps_default_altitude": 8.0,
  "replicate_gps_xy_noise": false,
  "replicate_gps_z_noise": false,
  "gps_xy_noise_range": 0.000125,
  "gps_z_noise_range": 12.5,
  "debug": false,
  "test": false,
  "walker_limit_output": false,
  "health_record": true,
  "location_cache": true,
  "distance_unit": "km",
  "reconnecting_timeout": 15,
  "logging": {
    "color": true,
    "show_datetime": true,
    "show_process_name": true,
    "show_log_level": true
  },
  "catch": {
    "any": {
      "candy_threshold": 1000,
      "catch_above_cp": 0,
      "catch_above_iv": 0,
      "logic": "or"
    },
    "// Example of always catching Rattata:": {},
    "// Rattata": {
      "always_catch": true
    }
  },
  "release": {
    "any": {
      "release_below_cp": 0,
      "release_below_iv": 0,
      "logic": "or"
    },
    "// Example of always releasing Rattata:": {},
    "// Rattata": {
      "always_release": true
    },
    "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
    "// Pidgey": {
      "keep_best_cp": 3
    },
    "// Example of keeping 2 best (based on IV) Zubat:": {},
    "// Zubat": {
      "keep_best_iv": 2
    },
    "// Keep no more than 3 best IV pokemon for every pokemon type": {},
    "// any": {
      "keep_best_iv": 3
    },
    "// Discard all pokemon in bag except 100 pokemon with best CP": {},
    "// all": {
      "keep_best_cp": 100
    },
    "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
    "// Zubat": {
      "keep_best_cp": 2,
      "keep_best_iv": 3
    },
    "// Example of custom order of static criterion": {},
    "// Zubat": {
      "keep_best_custom": "iv, cp, hp_max",
      "amount": 2
    }
  },
  "vips": {
    "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": {},
    "any": {
      "catch_above_cp": 1200,
      "catch_above_iv": 0.9,
      "logic": "or"
    },
    "Lapras": {},
    "Moltres": {},
    "Zapdos": {},
    "Articuno": {},
    "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
    "Mewtwo": {},
    "Dragonite": {},
    "Snorlax": {},
    "// Mew evolves to Mewtwo": {},
    "Mew": {},
    "Arcanine": {},
    "Vaporeon": {},
    "Gyarados": {},
    "Exeggutor": {},
    "Muk": {},
    "Weezing": {},
    "Flareon": {}
  }
}
`

### Output when issue occurred
`2016-08-31 11:27:02,000 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-31 11:27:02,044 [       cli] [INFO] commit: 2bafce1e
2016-08-31 11:27:02,048 [       cli] [INFO] Configuration initialized
2016-08-31 11:27:02,048 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-31 11:27:02,049 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-31 11:27:02,078 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
2016-08-31 11:27:02,876 [yoyo.migrations] [INFO] Applying pokemongobot
2016-08-31 11:27:02,876 [yoyo.migrations] [INFO]  - applying step 0
2016-08-31 11:27:02,877 [yoyo.migrations] [INFO] Marking pokemongobot applied
[2016-08-31 11:27:03] [MainThread] [SleepSchedule] [INFO] [next_sleep] Next sleep at 12:22:46, for a duration of 5:31:16
[2016-08-31 11:29:10] [MainThread] [PokemonGoBot] [INFO] [set_start_location] Setting start location.
[2016-08-31 11:31:18] [MainThread] [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
[2016-08-31 11:31:18] [MainThread] [PokemonGoBot] [INFO] [location_found] Location found: -15.8009728,-47.8606519 (-15.8009728, -47.8606519, 8.0)
[2016-08-31 11:33:25] [MainThread] [PokemonGoBot] [INFO] [position_update] Now at (-15.8009728, -47.8606519, 8.0)
[2016-08-31 11:39:47] [MainThread] [PokemonGoBot] [INFO] [login_started] Login procedure started.
`

### Steps to Reproduce
just start the bot with given configuration file

### Other Information
OS: linux
Branch: dev
Git Commit: 2bafce1e
Python Version: 2.7.6

**Comment by kevinsmendes** [comment]
Try setting `"enable_social": true` on your config.json and see if it fix it for you.

**Comment by palerique** [comment]
Yes it works!!!

why????

**Comment by ozi6616** [comment]
5000 m eror
