### ISSUE TITLE
MoveToMapPokemon Snipping doesn't work

### ISSUE THREAD

**Issue by MrCarlosJr** [PokemonGoF/PokemonGo-Bot#5001]
### Expected Behavior

Snipping using data PokemonMap

### Actual Behavior
```
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Pidgey
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Zubat
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Drowzee
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Meowth
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Pidgey
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Poliwag
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Pidgey
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Pidgey
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Voltorb
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Spearow
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Ekans
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Drowzee
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Pidgey
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Caterpie
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Pidgey
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Slowpoke
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Seel
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Pidgey
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Beedrill
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Nidoran M
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Weedle
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Weedle
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Pidgey
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Pidgey
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Pidgey
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Pidgey
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Pidgey
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Squirtle
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Zubat
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Pidgey
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Pidgeotto
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Staryu
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Rattata
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Poliwag
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Horsea
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Rattata
[MainThread] [MoveToMapPokemon] [INFO] [move_to_map_pokemon] Catching Rattata
```

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

```json
{
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": true,
    "live_config_update": {
      "enabled": false,
      "tasks_only": false
    },
    "tasks": [
      {
        "type": "TelegramTask",
        "config": {
          "enabled": true,
          "master": ,
          "min_interval": 120,
          "alert_catch": {
            "all": {"operator": "or", "cp": 500, "iv": 0.80},
            "Snorlax": {"operator": "or", "cp": 900, "iv": 0.9}
          }
        }
      },

      {
        "//NOTE: This task MUST be placed on the top of task list": {},
        "type": "RandomAlivePause",
        "config": {
          "enabled": true,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:05:00",
          "max_interval": "01:30:00"
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": false,
          "// set a name": "",
          "nickname": ""
        }
      },
      {
        "type": "CollectLevelUpReward",
        "config": {
          "collect_reward": true,
          "level_limit": -1
        }
      },
      {
        "type": "IncubateEggs",
        "config": {
          "enabled": true,
          "infinite_longer_eggs_first": false,
          "breakable_longer_eggs_first": true,
          "min_interval": 120
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": true,
          "min_interval": 10,
          "stats": ["username", "level", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": false,
          "terminal_title": true
        }
      },
        {
            "type": "UpdateLiveInventory",
            "config": {
                "enabled": true,
                "min_interval": 120,
                "show_all_multiple_lines": false,
                "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
            }
        },
      {
        "type": "ShowBestPokemon",
        "config": {
          "enabled": true,
          "min_interval": 300,
          "amount": 5,
          "order_by": "iv",
          "info_to_show": ["iv_pct", "cp", "ivcp", "dps", "hp"]
        }
      },
      {
      "type": "PokemonOptimizer",
      "config": {
        "enabled": true,
        "transfer": true,
        "transfer_wait_min": 3,
        "transfer_wait_max": 5,
        "evolve": true,
        "evolve_time": 25,
        "evolve_for_xp": true,
        "evolve_only_with_lucky_egg": false,
        "evolve_count_for_lucky_egg": 80,
        "may_use_lucky_egg": true,
        "upgrade": true,
        "groups": {
          "gym": ["Dragonite", "Snorlax", "Lapras", "Arcanine"]
        },
        "keep": [
          {
            "mode": "by_family",
            "top": 1,
            "sort": [{"iv": 0.9}],
            "evolve": true,
            "upgrade": false
          },
          {
            "mode": "by_family",
            "top": 1,
            "sort": [{"ncp": "0.9"}],
            "evolve": true,
            "upgrade": false
          },
          {
            "mode": "by_family",
            "top": 1,
            "sort": ["cp"],
            "evolve": false,
            "upgrade": false
          },
          {
            "mode": "by_family",
            "names": ["gym"],
            "top": 3,
            "sort": [{"iv": 0.9}, {"ncp": "0.9"}],
            "evolve": true,
            "upgrade": true
          }
        ]
      }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": true,
          "nickname_above_iv": 0.9,
          "nickname_template": "{name:.9} {ivcp_pct2}"
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          },
          "recycle_wait_min": 3,
          "recycle_wait_max": 5,
          "recycle_force": true,
          "recycle_force_min": "00:01:00",
          "recycle_force_max": "00:05:00"
        }
      },
        {
          "type": "CatchPokemon",
          "config": {
            "enabled": true,
            "catch_visible_pokemon": true,
            "catch_lured_pokemon": true,
            "min_ultraball_to_keep": 5,
            "berry_threshold": 0.35,
            "vip_berry_threshold": 0.9,
            "treat_unseen_as_vip": true,
            "daily_catch_limit": 800,
            "catch_throw_parameters": {
              "excellent_rate": 0.1,
              "great_rate": 0.5,
              "nice_rate": 0.3,
              "normal_rate": 0.1,
              "spin_success_rate" : 0.6
            },
            "catch_simulation": {
              "flee_count": 3,
              "flee_duration": 2,
              "catch_wait_min": 3,
              "catch_wait_max": 6,
              "berry_wait_min": 3,
              "berry_wait_max": 5,
              "changeball_wait_min": 3,
              "changeball_wait_max": 5,
              "newtodex_wait_min": 20, 
              "newtodex_wait_max": 30
            }
          }
        },
      {
        "type": "SpinFort",
        "config": {
          "enabled": true,
          "spin_wait_min": 3,
          "spin_wait_max": 5
        }
      },
      { "type": "UpdateWebInventory",
        "config": {
          "enabled": true
        }
      },
      {
        "type": "MoveToMapPokemon",
        "config": {
          "enabled": true,
          "address": "http://localhost:5000",
          "//NOTE: Change the max_sniping_distance to adjust the max sniping range (m)": {},
          "max_sniping_distance": 100000,
          "//NOTE: Change the max_walking_distance to adjust the max walking range when snipe is off (m)": {},
          "max_walking_distance": 5000,
          "min_ball": 50,
          "prioritize_vips": true,
          "snipe": true,
          "snipe_high_prio_only": true,
          "snipe_high_prio_threshold": 400,
          "update_map": true,
          "mode": "priority",
          "map_path": "raw_data",
          "walker": "StepWalker",
          "max_extra_dist_fort": 10,
          "skip_rounds": 5,
          "update_map_min_distance_meters": 500,
          "update_map_min_time_sec": 120,
          "snipe_sleep_sec": 2,
          "snipe_max_in_chain": 2,
          "debug": true,
          "catch": {
            "==========Legendaries==========": 0,
            "Aerodactyl": 1000,
            "Snorlax": 1000,
            "Articuno": 1000,
            "Zapdos": 1000,
            "Moltres": 1000,
            "Dratini": 1000,
            "Dragonair": 1000,
            "Dragonite": 1000,
            "Mewtwo": 1000,
            "Mew": 1000,

            "==========Region Locked==========": 0,
            "Farfetch'd": 1000,
            "Kangaskhan": 1000,
            "Mr. Mime": 1000,
            "Tauros": 1000,

            "==========Very Rare==========": 0,
            "Lapras": 900,
            "Electabuzz": 900,
            "Magmar": 900,
            "Ditto": 900,

            "==========Starters==========": 0,
            "Bulbasaur": 400,
            "Ivysaur": 600,
            "Venusaur": 1000,

            "Charmander": 400,
            "Charmeleon": 600,
            "Charizard": 1000,

            "Squirtle": 400,
            "Wartortle": 600,
            "Blastoise": 1000,

            "Pikachu": 600,
            "Raichu": 1000,

            "==========Semi Rare==========": 0,
            "Porygon": 200,
            "Scyther": 200,
            "Jynx": 200,

            "==========Uncommon==========": 0,

            "Omanyte": 150,
            "Omastar": 500,

            "Seel": 300,
            "Dewgong": 500,

            "Grimer": 200,
            "Muk": 500,

            "Shellder": 200,
            "Cloyster": 500,

            "Gastly": 200,
            "Haunter": 500,
            "Gengar": 1000,

            "Onix": 600,

            "Drowzee": 600,

            "Hypno": 600,

            "Vulpix": 200,
            "Ninetales": 600,

            "Paras": 100,
            "Parasect": 500,

            "Growlithe": 200,
            "Arcanine": 700,

            "Tentacool": 200,
            "Tentacruel": 500,

            "Mankey": 150,
            "Primeape": 500,

            "Clefairy": 150,
            "Clefable": 500,

            "Jigglypuff": 150,
            "Wigglytuff": 500,

            "Venonat": 100,
            "Venomoth": 500,

            "Diglett": 200,
            "Dugtrio": 500,

            "Meowth": 250,
            "Persian": 500,

            "Psyduck": 150,
            "Golduck": 500,

            "Geodude": 100,
            "Graveler": 500,
            "Golem": 800,

            "Eevee": 200,
            "Vaporeon": 800,
            "Jolteon": 800,
            "Flareon": 800,

            "Kabuto": 150,
            "Kabutops": 500,

            "Magikarp": 150,
            "Gyarados": 800,

            "Pinsir": 150,

            "Ponyta": 200,
            "Rapidash": 500,

            "Slowpoke": 200,
            "Slowbro": 500,

            "Magnemite": 250,
            "Magneton": 500,

            "Krabby": 100,
            "Kingler": 500,

            "Voltorb": 200,
            "Electrode": 500,

            "Exeggcute": 250,
            "Exeggcutor": 500,

            "Cubone": 300,
            "Marowak": 800,

            "Hitmonlee": 400,

            "Hitmonchan": 400,

            "Lickitung": 500,

            "Koffing": 200,
            "Weezing": 500,

            "Rhyhorn": 200,
            "Rhydon": 500,

            "Chansey": 800,

            "Tangela": 300,

            "Horsea": 200,
            "Seadra": 600,

            "Goldeen": 150,
            "Seaking": 500,

            "Staryu": 200,
            "Starmie": 800,


            "==========T1 Evolvers==========": 0,
            "Caterpie": 10,
            "Metapod": 10,
            "Butterfree": 500,

            "Weedle": 10,
            "Kakuna": 10,
            "Beedrill": 500,

            "Pidgey": 10,
            "Pidgeotto": 10,
            "Pidgeot": 300,

            "==========T2 Evolvers==========": 0,
            "Nidoran F": 10,
            "Nidorina": 10,
            "Nidoqueen": 10,

            "Nidoran M": 10,
            "Nidorino": 10,
            "Nidoking": 10,

            "Oddish": 100,
            "Gloom": 200,
            "Vileplume": 600,

            "Poliwag": 200,
            "Poliwhirl": 400,
            "Poliwrath": 800,

            "Abra": 300,
            "Kadabra": 600,
            "Alakazam": 800,

            "Machop": 150,
            "Machoke": 400,
            "Machamp": 800,

            "Bellsprout": 100,
            "Weepinbell": 400,
            "Victreebel": 800,

            "==========Trash==========": 0,

            "Rattata": 10,
            "Raticate": 10,

            "Spearow": 10,
            "Fearow": 10,

            "Ekans": 10,
            "Arbok": 10,

            "Sandshrew": 10,
            "Sandslash": 10,

            "Zubat": 10,
            "Golbat": 10,

            "Doduo": 10,
            "Dodrio": 10
          }
        }
      },
      {
        "type": "MoveToFort",
        "config": {
            "enabled": true,
            "lure_attraction": true,
            "lure_max_distance": 2000,
            "log_interval": 5
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "enabled": true,
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "pokemon_bag": {
      "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
      "show_at_start": true,
      "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
      "show_count": false,
      "// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
      "show_candies": false,
      "// 'pokemon_info' parameter define which info to show for each pokemon": {},
      "// the available options are": {},
      "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
      "pokemon_info": ["cp", "iv_pct"]
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "alt_min": 500,
    "alt_max": 1000,
    "sleep_schedule": [
      {
        "time": "12:00",
        "duration": "5:30",
        "time_random_offset": "00:30",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      },
      {
        "time": "17:45",
        "duration": "3:00",
        "time_random_offset": "01:00",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      }
    ],
    "debug": false,
    "test": false,
    "walker_limit_output": false,
    "health_record": true,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging": {
      "color": true,
      "show_datetime": false,
      "show_process_name": true,
      "show_log_level": true
    },
    "catch": {
        "any": {
            "always_catch": true
        }
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    },
    "websocket": {
    "start_embedded_server": true,
    "server_url": "127.0.0.1:4000"
  }
}

```

### Steps to Reproduce

Just use this config in dev branch.

### Other Information
OS: Fedora 24
 
Branch: dev
 
Git Commit: a674b2681ea5eb9d942a2f5a097eca50e43704a1
 
Python Version: Python 2.7.12

**Comment by sohje** [comment]
disable social, if you trying to use PokemonMap

**Comment by kenkclam** [comment]
[MoveToMapPokemon] is also not working for me
I can see from the localhost 5000 that there are pokemon found, but the bot is not walking towards them. The message [MoveToMapPokemon] never show up on my log.
How do I know if the bot is using [MoveToMapPokemon] at all?

    "libencrypt_location": "",
    "enable_social": false,
    "websocket_server": true,
    "heartbeat_threshold": 13,
    "tasks": [
      {
        "//NOTE: This task MUST be placed on the top of task list": {},
        "type": "RandomAlivePause",
        "config": {
          "enabled": true,
          "min_duration": "00:01:10",
          "max_duration": "00:5:00",
          "min_interval": "00:5:00",
          "max_interval": "00:25:00"
        }
      },
      {
        "type": "RandomPause",
        "config": {
          "enabled": true,
          "min_duration": "00:5:10",
          "max_duration": "00:15:00",
          "min_interval": "00:18:00",
          "max_interval": "00:48:00"
        }
      },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": false,
          "// set a name": "",
          "nickname": ""
        }
      },
      {
        "type": "MoveToMapPokemon",
        "config": {
          "address": "http://localhost:5000",
          "max_walking_distance": 500,
          "max_sniping_distance": 9500000,
          "min_time": 10,
          "min_ball": 20,
          "prioritize_vips": true,
          "snipe": true,
          "snipe_high_prio_only": true,
          "snipe_high_prio_threshold": 950,
          "update_map": false,
          "map_path": "raw_data",
          "walker": "StepWalker",
          "mode": "priority",
          "catch": {
            "Poliwag": 10,
            "Nidoran F": 10,
            "Nidoran M": 10,
            "Clefairy": 15,
            "Bellsprout": 10,
            "Slowpoke": 10,
            "Eevee": 20,
            "Oddish": 20,
            "Geodude": 50,
            "Abra": 50,
            "Diglett": 100,
            "Vulpix": 100,
            "Kabuto": 100,
            "Muk": 300,
            "Poliwrath": 200,
            "Golem": 200,
            "Weezing": 300,
            "Electrode": 300,
            "Primeape": 300,
            "Mr-mimi": 1000,
            "Chansey": 1000,
            "Alakazam": 600,
            "Omastar": 500,
            "Kabutops": 500,
            "Raichu": 600,
            "Tauros": 500,
            "Dugtrio": 500,
            "Bulbasaur": 400,
            "Charmander": 500,
            "Charmeleon": 600,
            "Squirtle": 300,
            "Pikachu": 600,
            "Growlithe": 400,
            "Machop": 300,
            "Grimer": 200,
            "Exeggcute": 500,
            "Omanyte": 100,
            "Koffing": 200,
            "Dratini": 600,
            "Lapras": 1000,
            "Electabuzz": 1000,
            "Magmar": 600,
            "Ditto": 900,
            "Arcanine": 980,
            "Machamp": 700,
            "Blastoise": 980,
            "Venusaur": 1100,
            "Charizard": 1100,
            "Slowbro": 300,
            "Nidoqueen": 150,
            "Nidoking": 150,
            "Clefable": 100,
            "Victreebel": 200,
            "Jolteon": 200,
            "Magneton": 100,
            "Gengar": 100,
            "Machoke": 80,
            "Vileplume": 400,
            "Exeggutor": 1200,
            "Aerodactyl": 600,
            "Snorlax": 1200,
            "Articuno": 1200,
            "Zapdos": 1300,
            "Moltres": 1300,
            "Dragonair": 800,
            "Dragonite": 1200,
            "Mewtwo": 1300,
            "Mew": 1300
          }
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": true,
          "min_interval": 1200,
          "show_all_multiple_lines": false,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries"]
        }
      },
      {
       "type": "TransferPokemon",
       "config": {
       "min_free_slot": 5,
       "transfer_wait_min": 1,
       "transfer_wait_max": 4
      }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "enabled": true,
            
            "// evolve only pidgey and drowzee": "",
            "// evolve_list": "pidgey, drowzee",
            "// donot_evolve_list": "none",
            
            "// evolve all but pidgey and drowzee": "",
            "// evolve_list": "all",
            "// donot_evolve_list": "pidgey, drowzee",
            
            "evolve_list": "Magikarp, Psyduck, Poliwag, Poliwhirl, Drowzee, Slowpoke, Staryu, Eevee, Krabby, Goldeen, Pidgeotto, Bellsprout, Gastly, Oddish, Horsea",
            "donot_evolve_list": "none",
            
          "first_evolve_by": "cp",
          "evolve_above_cp": 120,
          "evolve_above_iv": 0.9,
          "logic": "and",
          "min_evolve_speed": 30,
          "max_evolve_speed": 40,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 10,
          "max_balls_keep": 130,
          "max_potions_keep": 160,
          "max_berries_keep": 30,
          "max_revives_keep": 50,
          "item_filter": {
            "Pokeball":       { "keep" : 5 },
            "Potion":         { "keep" : 5 },
            "Super Potion":   { "keep" : 5 },
            "Hyper Potion":   { "keep" : 60 },
            "Max Potion":     { "keep" : 100 },
            "Revive":         { "keep" : 30 },
            "Max Revive":     { "keep" : 40},
	    "Greatball":      { "keep" : 70 },
            "Ultraball":      { "keep" : 100 },
            "Razz Berry":     { "keep" : 30 }
          }
        }
      },
	    {
	      "type": "CatchPokemon",
	      "config": {
	        "catch_visible_pokemon": true,
	        "catch_lured_pokemon": true,
                "daily_catch_limit": 500,
	        "min_ultraball_to_keep": 2,
	        "catch_throw_parameters": {
	          "excellent_rate": 0.1,
	          "great_rate": 0.1,
	          "nice_rate": 0.4,
	          "normal_rate": 0.4,
	          "spin_success_rate" : 0.3
	        },
				  "catch_simulation": {
				    "flee_count": 2,
				    "flee_duration": 2,
				    "catch_wait_min": 1,
				    "catch_wait_max": 3,
				    "berry_wait_min": 2,
				    "berry_wait_max": 3,
				    "changeball_wait_min": 2,
				    "changeball_wait_max": 3
				  }
	      }
	    },
      {
        "type": "SpinFort",
        "config": {
          "spin_wait_min": 2,
          "spin_wait_max": 8
           }
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 1000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 1,
          "step_size": 5
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 10
    },
    "walk_max": 5,
    "walk_min": 1,
    "sleep_schedule": [
      {
        "time": "22:30",
        "duration": "03:00",
        "time_random_offset": "00:10",
        "duration_random_offset": "00:20",
        "wake_up_at_location": ""
      },
      {
        "time": "13:30",
        "duration": "5:00",
        "time_random_offset": "00:20",
        "duration_random_offset": "00:40",
        "wake_up_at_location": ""
      }
    ],
    "alt_min": 30,
    "alt_max": 40,
    "gps_default_altitude": 278.0,
    "replicate_gps_xy_noise": true,
    "replicate_gps_z_noise": true,
    "gps_xy_noise_range": 0.000025,
    "gps_z_noise_range": 4.5,
    "action_wait_min": 1,
    "action_wait_max": 10,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 30,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "Rattata": {"never_catch": true},
      "Caterpie": {"never_catch": true},
      "Weedle": {"never_catch": true},
      "Pidgey": {"never_catch": true},
      "Staryu": {"never_catch": true},
      "Horsea": {"never_catch": true},
      "Venonat": {"never_catch": true},
      "Tentacool": {"never_catch": true},
      "//Shellder": {"never_catch": true},
      "Doduo": {"never_catch": true},
      "//Starmie": {"never_catch": true},
      "Goldeen": {"never_catch": true},
      "Drowzee": {"never_catch": true},
      "Spearow": {"never_catch": true},
      "Zubat": {"never_catch": true},
      "Krabby": {"never_catch": true},
      "//Paras": {"never_catch": true},
      "Psyduck": {"never_catch": true},
      "//Pidgeotto": {"never_catch": true}
    },
    "release": {
      "any": {"release_below_cp": 800, "release_below_iv": 0.80, "logic": "and"},
      "Bulbasaur": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Squirtle": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Nidoran M": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Clefairy": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Rattata": {"keep_best_cp": 1},
      "Pidgey": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Starmie": {"release_below_cp": 900, "release_below_iv": 0.80, "logic": "and"},
      "Raticate": {"release_below_cp": 900, "release_below_iv": 0.85, "logic": "and"},
      "Pidgeotto": {"release_below_cp": 900, "release_below_iv": 0.85, "logic": "and"},
      "Metapod": {"release_below_cp": 350, "release_below_iv": 0.85, "logic": "and"},
      "Kakuna": {"release_below_cp": 400, "release_below_iv": 0.85, "logic": "and"},
      "Zubat": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Caterpie": {"keep_best_cp": 1},
      "Weedle": {"keep_best_cp": 1},
      "Spearow": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Sandshrew": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Nidoran F": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Jigglypuff": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Oddish": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Paras": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Venonat": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Vulpix": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Mankey": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Diglett": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Abra": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Meowth": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Psyduck": {"keep_best_cp": 2, "keep_best_iv": 2},
      "Poliwag": {"keep_best_cp": 1, "keep_best_iv": 3},
      "Poliwhirl": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Geodude": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Ponyta": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Tentacool": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Bellsprout": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Slowpoke": {"keep_best_cp": 1, "keep_best_iv": 3},
      "Seel": {"release_below_cp": 650, "release_below_iv": 0.85, "logic": "and"},
      "Exeggcute": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Magnemite": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Shellder": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Doduo": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Dodrio": {"release_below_cp": 900, "release_below_iv": 0.7, "logic": "and"},
      "Tangela": {"release_below_cp": 800, "release_below_iv": 0.8, "logic": "and"},
      "Scyther": {"release_below_cp": 800, "release_below_iv": 0.8, "logic": "and"},
      "Pinsir": {"release_below_cp": 1600, "release_below_iv": 0.8, "logic": "and"},
      "Gastly": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Drowzee": {"keep_best_cp": 1, "keep_best_iv": 3},
      "Rhyhorn": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Krabby": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Cubone": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Koffing": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Horsea": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Goldeen": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Staryu": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Magikarp": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Dratini": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Eevee": {"keep_best_cp": 2, "keep_best_iv": 3},
      "Ekans": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Growlithe": {"keep_best_cp": 2, "keep_best_iv": 2},
      "Jynx": {"keep_best_cp": 2},
      "Dodrio": {"keep_best_cp": 2}
    },
    "vips" : {
         "//Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

**Comment by MrCarlosJr** [comment]
thanks For help. Junst work now. same json/config
