### ISSUE TITLE
[Feature Request] Wait at fort if lure is on

### ISSUE THREAD

**Issue by ravey-davey** [PokemonGoF/PokemonGo-Bot#5002]
### Short Description
When the bot reaches a fort that has a lure on, I'd like to be able to set the bot to wait at fort for a pre-determined amount of time, and/or until the lure has ended where the bot will continue walking on its 'route'.
While waiting at the fort, the bot will catch the lured pokemon (which is already in the code to do so), and would provide output as to how long it will remain at the lure for.

### How it would help others
This gives the bot a more 'human' feel to it, and would potentially allow for rarer Pokemon to be caught via a lure which has been set. 
An enhancement may be to allow the bot to check for any lures in its inventory (troy disk) and set a lure on specific fort (using GPS location) that it known to produce rare Pokemon.

**Comment by Gobberwart** [comment]
Hanging around a lured fort is definitely very human-like behaviour, and likely to result in better captures. I support this concept.

**Comment by LazGit** [comment]
+1, I think it's a very good idea !

**Comment by Hyperdancer** [comment]
+1

**Comment by javajohnHub** [comment]
Working great for me. Thanks.

**Comment by madzul** [comment]
could our bot do FollowPath, but stays at fort with lure on?

**Comment by Anakin5** [comment]
Do we agree that is done ?

**Comment by Gobberwart** [comment]
Yep, looks good
