### ISSUE TITLE
[BUG] Telegram not processing "pokemon_caught" event

### ISSUE THREAD

**Issue by davidspeijer** [PokemonGoF/PokemonGo-Bot#5003]
### Expected Behavior

Telegram message should be send when pokemon is caught

### Actual Behavior

No message is send. 
When sending /info to bot you get the correct reply.
Added `self.bot.logger.info("TEST TELEGRAM")` at line 117 in PokemonGo-Bot\pokemongo_bot\event_handlers\telegram_handler.py to test if bot would go into "pokemon_caught" event. Never receive a message in the log.
elif event == 'pokemon_caught':
     self.bot.logger.info("TEST TELEGRAM")
     if isinstance(self.pokemons, list):

### Other Information
OS: CentOS
 
Branch: DEV
 
Git Commit: latest
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by askovpen** [comment]
config `TelegramTask`?

**Comment by mmeulstee** [comment]
Same issue not getting an alert on catch.

OS: RaspberryPi (Ubuntu)
Branch: Master
Git: Latest

Config.json:
        "type": "TelegramTask",
        "config": {
          "enabled": true,
          "master": "@mmeul",
          "// old syntax, still supported: alert_catch": ["all"],
          "// new syntax:": {},
          "alert_catch": {
            "all": {"operator": "or", "cp": 300, "iv": 0.95},
            "Snorlax": {"operator": "or", "cp": 900, "iv": 0.9}
          }
        }

**Comment by askovpen** [comment]
master: 123456

**Comment by mmeulstee** [comment]
Which number are you talkin about is it at the start of the telegram_key?

**Comment by askovpen** [comment]
send message to bot and view in pokemongo-bot console userid(number)

**Comment by askovpen** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/configuration_files.md#telegram-task

**Comment by mmeulstee** [comment]
Thank you very much its workin now

**Comment by mmeulstee** [comment]
Maybe give that answer in the telegram configuration

**Comment by Gobberwart** [comment]
Documentation and example configs are correct. Closing.
