### ISSUE TITLE
Possible typo in config.json.map.example

### ISSUE THREAD

**Issue by farshidhss** [PokemonGoF/PokemonGo-Bot#5006]
### Expected Behavior
The lines 192 to 195 of config.json.map.example should be:
          "//NOTE: Change the max_sniping_distance to adjust the max sniping range (m)": {},
          "max_sniping_distance": 10000,
          "//NOTE: Change the max_walking_distance to adjust the max walking range when snipe is off (m)": {},
          "max_walking_distance": 500,

### Actual Behavior
but in the latest commit those lines are: 
          "//NOTE: Change the max_sniping_distance to adjust the max sniping range (m)": {},
          "max_sniping distance": 10000,
          "//NOTE: Change the max_walking_distance to adjust the max walking range when snipe is off (m)": {},
          "max__walking_distance": 500,

using this config file there will be an error when bot communicates with the map. 

### Other Information
OS: 
 
Branch: 
dev 
Git Commit: 
4cce54823e4209ad0000b5166be7443e5c775194
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by BreezeRo** [comment]
Thank you, fixed

https://github.com/PokemonGoF/PokemonGo-Bot/commit/f9875b6cd40afab7d00dc90fa07be158a03da8fe
