### ISSUE TITLE
Download Fort image (.jpg)

### ISSUE THREAD

**Issue by sediyama** [PokemonGoF/PokemonGo-Bot#5007]
### Short Description

At every Fort spin, the phone client request the Fort image is downloaded and displayed at the phone. I couldn't find any download request at the Bot code. 

If I were working at Niantic, I would find all the Bot users, using this. 

### Possible solution

Add the Image download at the Fort Spin.

### How it would help others

It would mimic the Official App much better.

**Comment by mjmadsen** [comment]
Well the server still sends the image. We just don't do anything with it.

**Comment by sediyama** [comment]
Ok! Thank you!
