### ISSUE TITLE
[CollectLevelUpReward] outputting Array instead of clean list of rewards.

### ISSUE THREAD

**Issue by JimmyMultani** [PokemonGoF/PokemonGo-Bot#5008]
### Expected Behavior

When leveling up, it should output a list of items rewarded in a clean manner.

### Actual Behavior

When leveling up, it outputs an Array with the items rewarded.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/RyhMpXrq

### Output when issue occurred

[CollectLevelUpReward] [INFO] [level_up_reward] Received level up reward: [{'item_id': 3, 'name': u'Ultraball', 'item_count': 15}, {'item_id': 103, 'name': u'Hyper Potion', 'item_count': 10}, {'item_id': 201, 'name': u'Revive', 'item_count': 10}, {'item_id': 701, 'name': u'Razz Berry', 'item_count': 10}]

### Steps to Reproduce

1.) Run bot.
2.) Level up your character.

### Other Information
OS: OSX
 
Branch: master
 
Git Commit: 42d670a411b4f8dc9a6206dd10a88cc51744026d
 
Python Version: 2.7.10
 
Any other relevant files/configs (eg: path files)

**Comment by Gobberwart** [comment]
#5016 merged. Closing.
