### ISSUE TITLE
MoveToMapPokemon max_distance with PokemonGo-Map

### ISSUE THREAD

**Issue by crvfts** [PokemonGoF/PokemonGo-Bot#5009]
I'm noting the changes for the MoveToMapPokemon task, and that the parameter "max_distance" is set in km (kilometers).

I personally do not use map-chat, and I set snipe:false which results in a walk-to-snipe action.

For a week now I have been using max_distance: 333. When I have done this I have assumed meters and my walk-to-snipe has NEVER gone over 333m. Works beautifully!

Now I am seeing in the config example that max_distance is supposed to be measured in km.  Naturally I adjusted thinking perhaps this has changed, and therefore changed my max_distance to 0.333 (333meters).

I ran the bot and was within 200meters of pokemon- MoveToMap did not occur. I then used live config (thanks guys!) and changed my max_distance back to 333 (three hundred thirty-three), and immediately my bot started honing in on a pokemon 197meters away.

Is max_distance affected somehow whether we use map-chat or PokemonGo-Map ? Using it with PokemonGo-Map certainly seems to be measuring in meters, not km.  And yes, there are other pokemon >333meters away but they are not engaged until they are <333meters away.

edit: just brought to my attention that distance_unit may be a global setting? i have distance_unit: m (meters). I thought that was only affecting logger, does this also affect max_distance?

**Comment by sohje** [comment]
Seems distance calculated in meters - [distance func](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/utils.py#L50)

**Comment by mjmadsen** [comment]
distance_unit is only for log output. 

We should output a warning, but the MoveToMapPokemon setting max_distance has been split into two:
      "max_walking_distance": 500,
      "max_sniping_distance": 500,
