### ISSUE TITLE
Option -ms does not work correctly

### ISSUE THREAD

**Issue by CheeryMom** [PokemonGoF/PokemonGo-Bot#501]
### Expected Behavior
With different values of -ms, the steps away from the start location should be different

### Actual Behavior
With different values of -ms, the steps away from the start location do not change much

### Steps to Reproduce
used different value of -ms, i.e. 1, 2, 3,4
python pokecli.py -a ptc -u usename -p password -l "37.807270, -122.428268" -w 4 -ms x -c 1
always the same pokestop are show up by using the map to view:
-ms 1: http://www.directupload.net/file/d/4425/i2m6hx4z_png.htm
-ms 2: http://www.directupload.net/file/d/4425/dvtimrs6_png.htm
-ms 3: http://www.directupload.net/file/d/4425/m9go59mf_png.htm
-ms 4: http://www.directupload.net/file/d/4425/74go2of8_png.htm

### Other Information
the steps should be like PokemonGo-Map: https://github.com/AHAAAAAAA/PokemonGo-Map
from the same location as above and with -st 3 (I think it is like -ms 3): http://www.directupload.net/file/d/4425/b7m4gz8f_png.htm

**Comment by surfaace** [comment]
having pokestops shown in map and where you go are two different things
