### ISSUE TITLE
Starting problem

### ISSUE THREAD

**Issue by Anderuimm** [PokemonGoF/PokemonGo-Bot#5010]
### Expected Behavior
Start botting

### Actual Behavior
Crashing

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

{
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": true,
    "live_config_update": {
      "enabled": false,
      "tasks_only": false
    },
    "tasks": [
      {
        "type": "TelegramTask",
        "config": {
          "enabled": false,
          "master": null,
          "// old syntax, still supported: alert_catch": ["all"],
          "// new syntax:": {},
          "alert_catch": {
            "all": {"operator": "and", "cp": 1300, "iv": 0.95},
            "Snorlax": {"operator": "or", "cp": 900, "iv": 0.9}
          }
        }
      },
      {
        "//NOTE: This task MUST be placed on the top of task list": {},
        "type": "RandomAlivePause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:05:00",
          "max_interval": "01:30:00"
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "RandomPause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:10:00",
          "max_interval": "02:00:00"
        }
      },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": false,
          "// set a name": "",
          "nickname": ""
        }
      },
      {
        "type": "CollectLevelUpReward",
        "config": {
          "collect_reward": true,
          "level_limit": -1
        }
      },
      {
        "type": "IncubateEggs",
        "config": {
          "enabled": true,
          "infinite_longer_eggs_first": false,
          "breakable_longer_eggs_first": true,
          "min_interval": 120,
         "infinite": [2,5,10],
         "breakable": [2,5,10]
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": false,
          "min_interval": 120,
          "show_all_multiple_lines": false,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
        }
      },
      {
        "type": "ShowBestPokemon",
        "config": {
          "enabled": true,
          "min_interval": 60,
          "amount": 5,
          "order_by": "cp",
          "info_to_show": ["cp", "ivcp", "dps", "hp"]
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "enabled": true,
          "min_free_slot": 5,
          "transfer_wait_min": 3,
          "transfer_wait_max": 5
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_above_iv": 0.9,
          "nickname_template": "{iv_pct}_{iv_ads}"
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "enabled": false,
            
            "// evolve only pidgey and drowzee": "",
            "// evolve_list": "pidgey, drowzee",
            "// donot_evolve_list": "none",
            
            "// evolve all but pidgey and drowzee": "",
            "// evolve_list": "all",
            "// donot_evolve_list": "pidgey, drowzee",
            
            "evolve_list": "all",
            "donot_evolve_list": "none",
            
          "first_evolve_by": "cp",
          "evolve_above_cp": 500,
          "evolve_above_iv": 0.8,
          "logic": "or",
          "min_evolve_speed": 25,
          "max_evolve_speed": 30,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          },
          "recycle_wait_min": 3,
          "recycle_wait_max": 5,
          "recycle_force": true,
          "recycle_force_min": "00:01:00",
          "recycle_force_max": "00:05:00"
        }
      },
      {
        "type": "CatchPokemon",
        "config": {
          "enabled": true,
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 5,
          "berry_threshold": 0.35,
          "vip_berry_threshold": 0.9,
          "treat_unseen_as_vip": true,
          "daily_catch_limit": 800,
          "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.5,
            "nice_rate": 0.3,
            "normal_rate": 0.1,
            "spin_success_rate" : 0.6,
            "hit_rate": 0.75
          },
          "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 3,
            "catch_wait_max": 6,
            "berry_wait_min": 3,
            "berry_wait_max": 5,
            "changeball_wait_min": 3,
            "changeball_wait_max": 5,
            "newtodex_wait_min": 20, 
            "newtodex_wait_max": 30
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "enabled": true,
          "spin_wait_min": 3,
          "spin_wait_max": 5,
          "daily_spin_limit": 1900
        }
      },
      { "type": "UpdateWebInventory",
        "config": {
          "enabled": true
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "enabled": true,
          "lure_attraction": true,
          "lure_max_distance": 2000,
          "walker": "StepWalker",
          "log_interval": 5
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "enabled": true,
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "pokemon_bag": {
      "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
      "show_at_start": true,
      "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
      "show_count": false,
      "// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
      "show_candies": false,
      "// 'pokemon_info' parameter define which info to show for each pokemon": {},
      "// the available options are": {},
      "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
      "pokemon_info": ["cp", "iv_pct"]
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "alt_min": 500,
    "alt_max": 1000,
    "sleep_schedule": [
      {
        "time": "12:00",
        "duration": "5:30",
        "time_random_offset": "00:30",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      },
      {
        "time": "17:45",
        "duration": "3:00",
        "time_random_offset": "01:00",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      }
    ],
    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": false,
    "replicate_gps_z_noise": false,
    "gps_xy_noise_range": 0.000125,
    "gps_z_noise_range": 12.5,
    "debug": false,
    "test": false,
    "walker_limit_output": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging": {
      "color": true,
      "show_datetime": true,
      "show_process_name": true,
      "show_log_level": true
    },
    "catch": {
      "any": {"candy_threshold" : 400 ,"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Keep no more than 3 best IV pokemon for every pokemon type": {},
      "// any": {"keep_best_iv": 3},
      "// Discard all pokemon in bag except 100 pokemon with best CP": {},
      "// all": {"keep_best_cp": 100},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3},
      "// Example of custom order of static criterion": {},
      "// Zubat": {"keep_best_custom": "iv, cp, hp_max", "amount":2}
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {},
        "Jolteon": {},
        "Vaporeon": {}
    },
	"websocket": {
		"start_embedded_server": true,
		"server_url": "127.0.0.1:4000"
	}
}

### Output when issue occurred

--------------------Starting bot--------------------

2016-08-31 15:30:37,464 [       cli] [INFO] PokemonGO Bot v1.0
2016-08-31 15:30:37,496 [       cli] [INFO] commit: unknown
2016-08-31 15:30:37,496 [       cli] [INFO] No auth argument specified, checking for C:\pogobot\PokemonGo-Bot\pokemongo_bot\..\configs\auth.json
2016-08-31 15:30:37,496 [       cli] [INFO] No config argument specified, checking for C:\pogobot\PokemonGo-Bot\pokemongo_bot\..\configs\config.json
2016-08-31 15:30:37,513 [       cli] [INFO] Configuration initialized
2016-08-31 15:30:37,516 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-08-31 15:30:37,517 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-08-31 15:30:37,528 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(8340) wsgi starting up on http://127.0.0.1:4000
2016-08-31 15:30:37,903 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 127.0.0.1
[2016-08-31 15:30:37] [SleepSchedule] [INFO] [next_sleep] Next sleep at 18:38:55, for a duration of 3:22:12
[2016-08-31 15:30:38] [PokemonGoBot] [INFO] [set_start_location] Setting start location.
Traceback (most recent call last):
  File "pokecli.py", line 781, in <module>
    main()
  File "pokecli.py", line 217, in main
    report_summary(bot)
  File "pokecli.py", line 265, in report_summary
    metrics.capture_stats()
  File "C:\pogobot\PokemonGo-Bot\pokemongo_bot\metrics.py", line 108, in capture_stats
    response_dict = request.call()
  File "C:\pogobot\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 223, in call
    if not self.can_call():
  File "C:\pogobot\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 124, in can_call
    raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException
[2016-08-31 15:30:39] [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 895, in _send_output
    msg += message_body
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
[2016-08-31 15:30:39] [sentry.errors.uncaught] [ERROR] [u'NoPlayerPositionSetException', u'  File "pokecli.py", line 781, in <module>', u'  File "pokecli.py", line 217, in main', u'  File "pokecli.py", line 265, in report_summary', u'  File "C:\\pogobot\\PokemonGo-Bot\\pokemongo_bot\\metrics.py", line 108, in capture_stats', u'  File "C:\\pogobot\\PokemonGo-Bot\\pokemongo_bot\\api_wrapper.py", line 223, in call', u'  File "C:\\pogobot\\PokemonGo-Bot\\pokemongo_bot\\api_wrapper.py", line 124, in can_call']

 Something went wrong and the bot needed to be restarted. Please investigate the cause.

Waiting 55 segundos, press any key to continue ...

### Other Information
OS: 
Windows 10

Branch: 
master

Git Commit: 
42d670a411b4f8dc9a6206dd10a88cc51744026d 

Python Version: 
2.7.12

Any other relevant files/configs (eg: path files) 

auth.json

{
    "auth_service": "google",
    "username": "my_google_username@gmail.com",
    "password": "my_google_password",
    "location": "Porto Alegre RS",
    "favorite_locations":[
        {"name": "Porto Alegre RS", "coords": "-30.0398566,-51.2146972"}
    ],
    "gmapkey": "MY_MAPS_API_KEY",
    "encrypt_location": "",
    "telegram_token": ""
}

**Comment by mjmadsen** [comment]
2016-08-31 15:30:37,496 [ cli] [INFO] No auth argument specified, checking for C:\pogobot\PokemonGo-Bot\pokemongo_bot..\configs\auth.json
2016-08-31 15:30:37,496 [ cli] [INFO] No config argument specified, checking for C:\pogobot\PokemonGo-Bot\pokemongo_bot..\configs\config.json

You don't have configuration files setup.

**Comment by sohje** [comment]
pip install -r requirements.txt --upgrade ?

**Comment by Anderuimm** [comment]
I suposed it must be these:

![image](https://cloud.githubusercontent.com/assets/3143872/18141960/e8d57d9e-6f91-11e6-811d-cded21a4313b.png)

I've copy-paste them on pokemongo_bot , pokemogo_bot/config and root directory, no success.

**Comment by Anderuimm** [comment]
I deleted both files and run PokemonGo-Bot-Configurator.bat as Administrator. When I PokemonGo-Bot-Start.bat the error are differente because config.json are missing. Then I check: auth.json are on the /configs folder but config.json is missing. I renamed config.json.example and try to run PokemonGo-Bot-Start.bat again, the original error returns.

**Comment by mjmadsen** [comment]
Hm. Let me take a gander.

**Comment by mjmadsen** [comment]
Actually, I was incorrect. Sorry. Looks like this is the culprit:
File "C:\pogobot\PokemonGo-Bot\pokemongo_bot\api_wrapper.py", line 124, in can_call
raise NoPlayerPositionSetException()
pgoapi.exceptions.NoPlayerPositionSetException

We've been having more folks crash with this problem. Either we need to figure out how to handle it so we can keep running or at least give better output as to what we think is the cause.

**Comment by Anderuimm** [comment]
It's, I guess, any problem with localization API Key. I'm running other pogoapi based apps in python (maps, basically) and when I try to use my Google Maps API Key on command line without quotes it's broke the console, because it have an "-" (minus signal). Peraphs it's breaking on your scripts to Windows users.

**Comment by mjmadsen** [comment]
Do you know which git branch the other apps are using?

**Comment by Anderuimm** [comment]
This one:

https://github.com/PokemonGoMap/PokemonGo-Map

**Comment by Anderuimm** [comment]
It uses master's POGOAPI as I can see.

**Comment by mjmadsen** [comment]
Guess their own their own branch of the API.

https://github.com/PokemonGoMap/pgoapi.git#egg=pgoapi

**Comment by mjmadsen** [comment]
From what I can tell, there isn't much of a difference dealing with NoPlayerPositionSetException between the fork we use, the PokemonGoMap api for or the currently active pogodevorg/pgoapi.

**Comment by Anderuimm** [comment]
During an fresh install using the batch file inside the project I got this error:

```
Submodule 'web' (https://github.com/PokemonGoF/PokemonGo-Web) registered for pat
h 'web'
Cloning into 'C:/pogobotPokemonGo-Bot/web'...
←[33m  Could not find a tag or branch 'fa49ada8570b0817c5a73b9315ba010fa7a47874', assuming commit.←[0m
```


Seems important...

**Comment by k4n30** [comment]
@Anderuimm no that message is expected
