### ISSUE TITLE
Unbanned?!

### ISSUE THREAD

**Issue by mjmadsen** [PokemonGoF/PokemonGo-Bot#5012]
Trainer,

We have restored access to your Pokémon GO account.  Your may not have realized that an add-on app you were using was impacting our service.  For this reason, we are unbanning your Pokémon GO account as a one-time courtesy.  For more details on this topic, please click here.

Our goal is to provide a fair, fun, and legitimate gameplay experience for all Pokémon GO players.  One aspect of these efforts is maintaining the integrity of the game and the health of our servers by blocking unauthorized access, including blocking bots and data scraping operations.  We may be required to ban accounts of users of third party apps that facilitate these activities as a way to protect our servers.  So please keep in mind that use of third party services which use your account to access Pokémon GO servers is in violation of our Terms of Service and may result in the re-banning of your account.

Say WHAT?!

**Comment by sediyama** [comment]
Did you file a appeal?

**Comment by mjmadsen** [comment]
No, I didn't even both with that. I assumed it was a lost cause.

**Comment by theresthatguy** [comment]
pics or it didn't happen

**Comment by mjmadsen** [comment]
I'm one of the devs here. I have no reason to make stuff up.

https://s22.postimg.org/6il2jgo1d/Untitled.png

**Comment by akatasonov** [comment]
Happened to my recent account as well. At some point today it did got banned.. So.. How to make them harder to detect bot activity? Lets exchange some tips

**Comment by th3w4y** [comment]
happen to me also...

**Comment by th3w4y** [comment]
maybe this unbanned account are still under close monitoring...?

**Comment by theLastLivingGhost** [comment]
Here as well. I'm thinking of rebooting the bot on it as well, I have certain doubts though..

**Comment by siembz** [comment]
I got unbanned to and got the same e-mail from support@nianticlabs.com

**Comment by solderzzc** [comment]
BountySource good ? @mjmadsen

**Comment by hngouveia01** [comment]
How much time between ban and unban?

**Comment by mjmadsen** [comment]
That account was lost shortly after the API update however long ago that was now. I'm definitely not going to bot on it again - it's a pretty damn solid account. 

@solderzzc What?

**Comment by davidspeijer** [comment]
Received the same mail. I did send an appeal. Me so happy 🙂

**Comment by zilions** [comment]
Also got unbanned a few hours ago via the exact same email. Might stay away from the bot from now on though.

**Comment by solderzzc** [comment]
@mjmadsen  we can add crowdfunding for issue solve, initialed by issue opener.

**Comment by avexus** [comment]
I am still banned. So sad.

**Comment by sanik90** [comment]
I have yet to receive any email from Niantic, I did mail email them regarding my login issue, it says can't get data from server something like that

**Comment by cypha88** [comment]
I got an email giving back my main as well. I think people who may have spent some cash on it got their accounts back. I only used it for 26-29 and had leveled it by hand to 26 and 31 after... so needless to say I am STOKED to have this account back. Never again!

**Comment by oralunal** [comment]
Still "Failed to get game data from the server"...

**Comment by kirikay** [comment]
@mjmadsen hello sir, may i ask what level is ur account? 
reading ur post made me really happy! so i immediately checked our accounts... my sisters account was unbanned but mine is still data error from server... I leveled it manually to lvl 24 by driving to the nearby city (30 km from home), from 25 to 29 with bot, i bought some coins too for incubators etc... i wish i'll also get it back and wont bot with that account anymore...

**Comment by avexus** [comment]
I got a different message. it says "Unable to authenticate. Please try again." I think they erased my account.
Anybody has the same message?

**Comment by SiRoCu1976** [comment]
On my banned account I got "Unable to authenticate. Please try again." for today. Then I try to input a wrong password in the game it says "login incorrect! and have 4 times to try" that's mean my account still in database, but can't login to the game. Any idea?

**Comment by kirikay** [comment]
@avexus i think that's the normal response if the account is banned...

@SiRoCu unless you get an email from them, ur account is still banned :(

**Comment by hngouveia01** [comment]
Yesterday I filed an appeal and today I received an e-mail from Niantic saying that my account was banned.
Only this way I knew my account was in that situation.
I've uploaded two screen shots of payments in my appeal.
Let's see if it helps.

**Comment by adiramardiani** [comment]
@mjmadsen @th3w4y @siembz @davidspeijer @cypha88 
Hello all, sorry to disqus this condition in issues area

I banned in 20 August (I didn't send appeal) and today I have email (my account terminated)

- May i ask the banned date and unbanned date, how duration from unbanned ?
- Do you send appeal to niantic ?
- If send appeal, what the content in your appeal to niantic, do you attach some file ? (dont answer if you think this is privacy)

I hope a get the answer, and sorry for my bad english

Thanks

**Comment by avexus** [comment]
@hngouveia01 I filed an appeal yesterday too. Didn't get any reply. Still unable to authenticate. Seems it's still banned. And I doubt it will be unbanned.

**Comment by avexus** [comment]
@SiRoCu1976, i have the same error message. It's for perma ban on google account.

**Comment by theLastLivingGhost** [comment]
@redrodan I had a Google account banned, they didn't ban the PTC one yet (I haven't used it but for pokémon iv gathering though). The former has been the one unbanned some days ago.

**Comment by 1Edman** [comment]
If you have purchased Pokecoins from Apple Store and you were banned, you can request a refund from Apple support! I got refunded for every coin I purchased in that account. I guess Niantic is aware now that Apple will stand with their clients and will refund any banned account, even if Niantic mentioned in their NEW ToU that they won't refund terminated accounts but this conflicts with Apple App store terms. So this is why I'm thinking they have started to UNBAN some users. Money always talks

**Comment by adiramardiani** [comment]
So if have purchased Pokecoins, have a more chance to UNBAN ?

Unfortunately, I haven't some purchase in pogo

**Comment by PlanetoftheMapes** [comment]
I can confirm I am also unbanned. I think Niantic is getting desperate about their user retention numbers and are hoping this will boost their active users.

**Comment by PlanetoftheMapes** [comment]
BTW my unbanned account already was refunded for coin purchases by Apple, so that doesn't seem to be a factor.

**Comment by k4n30** [comment]
:p

**Comment by adiramardiani** [comment]
@PlanetoftheMapes so I still have a chance :)

Thanks to share

**Comment by Gobberwart** [comment]
I had one of each banned. Got an email regarding the ptc account yesterday to confirm that it was terminated due to breaches of T&C. Haven't heard anything about the google account, and I don't really care.

**Comment by adiramardiani** [comment]
My banned account is google account ;)

**Comment by PlanetoftheMapes** [comment]
@adiramardiani My account that was unbanned was also google

**Comment by adiramardiani** [comment]
@PlanetoftheMapes do you remember the distance time between ban (can't login), getting emails ban, until unbanned account?

**Comment by PlanetoftheMapes** [comment]
Yes, ban occurred exactly 21 days ago (first ban wave).

**Comment by adiramardiani** [comment]
Back to bot topic, so if use bot with not aggressive action, the anti cheat can still see as LEGIT PLAYER ?
Or they have a parameter to see the player not play in their device ?

**Comment by Gobberwart** [comment]
This is not an issue. Take it to slack.
