### ISSUE TITLE
Experimental pokemon upgrade issue

### ISSUE THREAD

**Issue by Jcolomar** [PokemonGoF/PokemonGo-Bot#5017]
### Expected Behavior
Add experimental pokemon upgrade (power-up) logic doesnt work.

### Actual Behavior
No evolve, no power up. I have 58 kabuto's candy and one perfect kabuto.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

...
{
        "type": "PokemonOptimizer",
            "config": {
                "enabled": true,
                "transfer": true,
                "transfer_wait_min": 3,
                "transfer_wait_max": 5,
                "evolve": true,
                "evolve_time": 25,
                "evolve_for_xp": false,
                "evolve_only_with_lucky_egg": false,
                "evolve_count_for_lucky_egg": 80,
                "may_use_lucky_egg": false,
                "upgrade": true,
				"keep": [
                    {
                        "mode": "by_family",
                        "top": 1,
                        "sort": [{"iv": 1}],
                        "evolve": true,
                        "upgrade": true
                    },
					{
                        "mode": "by_family",
                        "top": 1,
                        "sort": ["cp"],
                        "evolve": false,
                        "upgrade": false
                    }
				]
        }
...

Link to full config http://pastebin.com/seZvCD6T

### Output when issue occurred
No errors in terminal

### Other Information
OS: 
Windows 10 x64
Branch: 
dev
Git Commit: 
Latest commit a7fb0ed
Python Version: 
Python 2.7.12
Any other relevant files/configs (eg: path files)

**Comment by Anakin5** [comment]
Please read https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/pokemon_optimizer.md

**Comment by Jcolomar** [comment]
I did it few times and i dont know where is the error

**Comment by Anakin5** [comment]
`"1.0"` in your config should be `1`. Also since you need 50 candies to evolve to Kabutops, I don't think the 8 remaining will be enough to power it up.

**Comment by Jcolomar** [comment]
So doc file isnt clear because doesnt say what is priority upgrade or evolve. I understand first try evolve, once done, try upgrade it. Whatever, ill change "1.0" to "1" when i go home and i tell u if it works.

Thank you!

**Comment by Anakin5** [comment]
I will clarify that evolve comes before upgrade if both are available.

**Comment by Jcolomar** [comment]
I changed value "1.0" to "1" and same problem. Edit first post with link to config: WebIU doesnt do any  action neither (release/evolve).

Already 87 kabuto's candy

**Comment by Anakin5** [comment]
It is a numeric value, not a character string:
```
{
    "mode": "by_family",
    "top": 1,
    "sort": [{"iv": 1}],
    "evolve": true,
    "upgrade": true
},
```

**Comment by Jcolomar** [comment]
Changed, but no evolution. Now i got errors when bot launch, but no fatal ones. Bot still running. 

[2016-09-01 12:22:21] [PokemonGoBot] [INFO]
Traceback (most recent call last):
  File "C:\Python27\lib\logging\__init__.py", line 861, in emit
    msg = self.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 734, in format
    return fmt.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 465, in format
    record.message = record.getMessage()
  File "C:\Python27\lib\logging\__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file __init__.py, line 1325

**Comment by Anakin5** [comment]
Let's go through the obvious list since I do not have enough info at all to understand your problem:
- How many empty slots is there left in your bag ?
- What are the detailed stats of this Kabuto: iv, cp, npc, level ?
- How many Kabuto candy do you have ?
- How many stardust do you have ?

Without all answers, I can't be sure there is a problem and/or where it comes from.

**Comment by Jcolomar** [comment]
[2016-09-01 13:01:58] [PokemonOptimizer] [INFO] Evolving 1 Pokemon (the best)
[2016-09-01 13:01:58] [PokemonOptimizer] [INFO] [pokemon_evolved] Evolved Kabuto [IV 1.0] [CP 410] [29 candies] [+500 xp]
[2016-09-01 13:02:21] [PokemonOptimizer] [INFO] Evolving 0 Pokemon (for xp)
[2016-09-01 13:02:21] [PokemonOptimizer] [INFO] Upgrading 0 Pokemon [286841 stardust]

Seems only evolve pokemon when release function is over ?!  Anyway bot doesnt poweup the pokemon

How many Kabuto candy do you have ? 29
How many stardust do you have ? 286841

**Comment by Anakin5** [comment]
You said no evolution but I see the Kabuto beeing evolved in your log. Everything looks fine to me.

**Comment by Jcolomar** [comment]
I said no evolution before release function start. When it finished, bot evolution kabuto to kabutops (i copied the log). Bot should powerup with kabutos candys and stardust

**Comment by k4n30** [comment]
Config issue - take to slack
