### ISSUE TITLE
poly line walker cause a problem, just started, then error.

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#5020]
In poly line walker, it has a problem, won't start.

{
    "websocket_server": false,
    "heartbeat_threshold": 15,
    "enable_social": false,
    "live_config_update": {"enabled": true, "tasks_only": false},
    "tasks": [
      { "type": "RandomAlivePause",  "config": {"enabled": true, "min_duration": "00:00:10", "max_duration": "00:10:00", "min_interval": "00:05:00", "max_interval": "01:30:00"}},
      { "type": "HandleSoftBan"},
      { "type": "RandomPause",      "config": {"enabled": true, "min_duration": "00:01:00", "max_duration": "00:05:00","min_interval": "00:30:00", "max_interval": "02:00:00"}},
      { "type": "CompleteTutorial", "config": {"enabled": false, "nickname": ""}},
      { "type": "CollectLevelUpReward", "config": {"collect_reward": true, "level_limit": -1}},
      { "type": "IncubateEggs",     "config": {"enabled": true, "infinite_longer_eggs_first": false, "breakable_longer_eggs_first": true, "min_interval": 120, "infinite": [2,5,10], "breakable": [5,10]}},
      { "type": "UpdateLiveStats",  "config": {"enabled": true, "min_interval": 500,
        	"stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true, "terminal_title": true}},
      { "type": "UpdateLiveInventory",  "config": {"enabled": true,  "min_interval": 300, "show_all_multiple_lines": false, "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]}},
      { "type": "EvolvePokemon",        "config": {"enabled": true,
        	"evolve_list": "Pidgey, Drowzee, Weedle, Caterpie, Spearow, Rattata",
          "min_evolve_speed": 25, "max_evolve_speed": 30, "use_lucky_egg": false}},
      { "type": "TransferPokemon",      "config": {"enabled": true,  "min_free_slot": 20, "transfer_wait_min": 7, "transfer_wait_max": 12}},
      { "type": "RecycleItems",         "config": {"enabled": true,
          "min_empty_space":    5,
          "max_potions_keep":   0,
          "max_revives_keep":   0,
          "max_balls_keep":   210,
          "max_berries_keep": 100,
          "item_filter": {
            "Potion":         {"keep" :   0 },
            "Super Potion":   {"keep" :   0 },
            "Hyper Potion":   {"keep" :   0 },
            "Revive":         {"keep" :   0 },
            "Pokeball":       {"keep" :  50 },
            "Greatball":      {"keep" :  50 },
            "Razz Berry":     {"keep" : 100 }
          },
          "recycle_wait_min":   3,
          "recycle_wait_max":   5,
          "recycle_force":      true,
          "recycle_force_min":  "00:30:00",
          "recycle_force_max":  "01:00:00"
        }
      },

      { "type": "FollowSpiral", "config": {"enabled": true, "diameter": 12, "step_size": 80}},

      { "type": "CatchPokemon",
        "config": {
          "enabled": true,
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 15,
          "berry_threshold": 0.35,
          "vip_berry_threshold": 0.9,
          "treat_unseen_as_vip": true,
          "daily_catch_limit": 800,
          "catch_throw_parameters": {"excellent_rate": 0.1, "great_rate": 0.5, "nice_rate": 0.3, "normal_rate": 0.1, "spin_success_rate" : 0.6, "hit_rate": 0.75},
          "catch_simulation": {"flee_count": 3, "flee_duration": 2, "catch_wait_min": 3, "catch_wait_max": 6, "berry_wait_min": 3, "berry_wait_max": 5, "changeball_wait_min": 3, "changeball_wait_max": 5, "newtodex_wait_min": 20, "newtodex_wait_max": 30}}},
      { "type": "NicknamePokemon", "config": {"enabled": false, "nickname_above_iv": 0.9,
          "nickname_template": "{iv_pct}%{iv_ads_hex}"}
      },
      { "type": "SpinFort",   "config": {"enabled": true, "spin_wait_min": 3, "spin_wait_max": 5, "daily_spin_limit": 1500}},
      { "type": "MoveToFort", "config": {"enabled": true, "lure_attraction": true, "lure_max_distance": 800, "walker": "PolylineWalker", "log_interval": 20}}
    ],
    "map_object_cache_time": 5,
    "forts": {"avoid_circles": false, "max_circle_size": 50, "cache_recent_forts": true},
    "walk_max": 5,
    "walk_min": 2,
    "alt_min":  30,
    "alt_max":  60,
    "sleep_schedule": [
      {"time": "01:00", "duration": "23:30", "time_random_offset": "00:30", "duration_random_offset": "00:30", "wake_up_at_location": ""},
      {"time": "17:45", "duration": "00:30", "time_random_offset": "01:00", "duration_random_offset": "00:30", "wake_up_at_location": ""}
    ],
    "gps_default_altitude":		22.3418,
    "replicate_gps_xy_noise":	true,
    "replicate_gps_z_noise":	true,
    "gps_xy_noise_range":     0.000125,
    "gps_z_noise_range":      12.5,
    "walker_limit_output":		true,
    "health_record":          false,
    "location_cache":			    true,
    "distance_unit":          "m",
    "reconnecting_timeout":		200,
    "location_cache":         false,
    "logging":	{"color": false, "show_datetime": true, "show_process_name": false, "show_log_level": false},
    "catch":    {"any": {"always_catch" :   true}},
    "release":  {"any": {"always_release":  true}}
}

Result:

 [MainThread] Most Perfect Pokemon: Drowzee [CP: 542] [IV: 15/6/4] Potential: 0.56
Traceback (most recent call last):
  File "pokecli.py", line 781, in <module>
    main()
  File "pokecli.py", line 139, in main
    bot.tick()
  File "E:\GameDownload\PokemonGo-Bot\pokemongo_bot\__init__.py", line 658, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "E:\GameDownload\PokemonGo-Bot\pokemongo_bot\cell_workers\move_to_fort.py", line 92, in work
    if not step_walker.step():
  File "E:\GameDownload\PokemonGo-Bot\pokemongo_bot\walkers\polyline_walker.py", line 30, in step
    (self.destLat, self.destLng), self.speed)
  File "E:\GameDownload\PokemonGo-Bot\pokemongo_bot\walkers\polyline_generator.py", line 42, in cached_polyline
    PolylineObjectHandler._cache = Polyline(origin, destination, speed)
  File "E:\GameDownload\PokemonGo-Bot\pokemongo_bot\walkers\polyline_generator.py", line 73, in __init__
    self.directions_response['routes'][0]['legs'][0]['steps']]
IndexError: list index out of range
(PokemonGo-Bot)

**Comment by BreezeRo** [comment]
What branch are you on? and when you have the time, please try to install a fresh copy of the bot using this config to see if you still get experience this issue

**Comment by th3w4y** [comment]
@avexus i believe i know what can cause it.... @kanemasa1987 added L73 and was preparing to catch that exception in Factory... 

but i believe the exception does not require extra handling...  actually 
I am very curious to know what the destination was and what fort were you at... maybe we should dump that if we raise..

**Comment by th3w4y** [comment]
@avexus if this is urgent for you comment out L73 in pokemongo_bot\walkers\polyline_generator.py and you should be safe... 

will look in creating a PR soon

**Comment by th3w4y** [comment]
@solderzzc @kanemasa1987 

What do you guys think? shall we remove the raise in case of a) and b)

One of you Guys must have added it while back when there was a teleport bug in the polyline..
```
        try:
        # In case of API limit reached we get back we get a status 200 code with an empty routes []
        # {u'error_message': u'You have exceeded your rate-limit for this API.',
        #  u'routes': [],
        #  u'status': u'OVER_QUERY_LIMIT'
        # }

            self.polyline_points = [x['polyline']['points'] for x in
                                    self.directions_response['routes'][0]['legs'][0]['steps']]
        except IndexError:
        # This handles both cases:
        # a) the above API Quota reached self.directions_response['routes'] = []
        # b) ZERO_RESULTS {
        #    "geocoded_waypoints" : [ {}, {} ],
        #    "routes" : [],
        #    "status" : "ZERO_RESULTS"
        # }
            self.polyline_points = self.directions_response['routes']
            raise # catch at factory atm...
```

**Comment by th3w4y** [comment]
The bug was in Polyline.calculate_coord()
If Google API hit one of the 2 exception case a) b) (API limit, ZERO_RESULTS) it was returning destination reached instantly but now that part is fixed since ages:
```

    def calculate_coord(self, percentage, o, d):
        # If this is the destination then returning as such when percentage complete = 1.0
        # Here there was a bug causing this to teleport when API quota was reached!!!
        if self.points[-1] == d and percentage == 1.0 :
            return [d]
        else:
            # intermediary points returned with 5 decimals precision only
            # this ensures ~3-50cm ofset from the geometrical point calculated
            lat = o[0]+ (d[0] -o[0]) * percentage
            lon = o[1]+ (d[1] -o[1]) * percentage
            return [(round(lat, 5), round(lon, 5))]
```

**Comment by kanemasa1987** [comment]
If the bug is fixed, polyline should be semi equivalent with the StepWalker when we reach the API limit (provided that the GPS noise is on.)

I think we can simply remove the raise from the code at this point.

**Comment by th3w4y** [comment]
@kanemasa1987 the noise is done via round(pos, 5) thus it would ensure ~50cm off the geometrical course on each .get_pos()

**Comment by th3w4y** [comment]
i believe this can be closed
