### ISSUE TITLE
Bot staying at one point

### ISSUE THREAD

**Issue by LUCKASSs** [PokemonGoF/PokemonGo-Bot#5024]
Hello 
There is any way that the bot stay at one point and don't move and catch Pokemon ?
I have a good spot with 4 Pokestop Lured 24/24h by high level 

40.764909,-73.972649

Maybe the risk of ban may decrease..?

Thx !

**Comment by dokhed** [comment]
if you want to make the bot stay at one point, set the bot by...
`...
...
{
        "type": "MoveToFort",
        "config": {
          "enabled": false,
          "lure_attraction": true,
          "lure_max_distance": 2000,
          "walker": "StepWalker",
          "log_interval": 5
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "enabled": false,
          "diameter": 4,
          "step_size": 70
        }
      }
...
...`

or   disable all moving tasks

**Comment by MZorzy** [comment]
modded config.json.example with correct altitute data for my location and try as @dokhled wrote
"enable": false in MoveToFort & FollowSpiral. relaunch bot and it go to where are going befor modding.
don't stay at one point

**Comment by LUCKASSs** [comment]
And what I have to modify in order that the bot move only into lured fort ?

**Comment by dokhed** [comment]
As I've checked from your location(40.764909,-73.972649). It's not in the range that you can stay still and be able to spin all 4 forts

the best location should be on the same as a mouse cursor that will be able to spin all 4 forts without moving

![pokmon go map - google chrome_2](https://cloud.githubusercontent.com/assets/21478501/18167386/856fdf12-707a-11e6-981f-3529fc12fbb7.jpg)

**Comment by dokhed** [comment]
another way is...
make the bot follow the path `"FollowPath"`
and set the `"path_mode"` to be `linear` so the bot will turn around at the last waypoint and along the given waypoints in reverse order.
and set the `          "timer_restart_min": "00:05:00",
          "timer_restart_max": "00:07:00"` to make the bot stop every time it finish the lap

![pokmon go map - google chrome_2](https://cloud.githubusercontent.com/assets/21478501/18167781/afc051d2-707c-11e6-9b47-eb8f566c84d0.jpg)

**Comment by nealqu** [comment]
Is there a way to reduce the diameter that the bot walks?

**Comment by k4n30** [comment]
#3580
