### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by bilalkamoon** [PokemonGoF/PokemonGo-Bot#5028]
===============ISSUE SECTION===============

### Expected Behavior
bot running after update

### Actual Behavior
bot stops working, npm install fails

### Output when issue occurred
C:\Users\Win8\node_modules\weak>if not defined npm_config_node_gyp (node "C:\Use
rs\Win8\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_module
s\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the regi
stry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versi
on number. [C:\Users\Win8\node_modules\weak\build\weakref.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [C:\Users\Win8\node_modules\weak\build\weakref.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Win8\AppData\Roaming\npm\nod
e_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Win8\\AppData
\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "re
build"
gyp ERR! cwd C:\Users\Win8\node_modules\weak
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN install:weak@1.0.1 weak@1.0.1 install: `node-gyp rebuild`
npm WARN install:weak@1.0.1 Exit status 1
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Win8\package.j
son'
npm WARN Win8 No description
npm WARN Win8 No repository field.
npm WARN Win8 No README data
npm WARN Win8 No license field.

### Other Information
OS: 
Windows 
Branch: 
master
Python Version: 
2.7

**Comment by Jcolomar** [comment]
As i know, pokemongo-bot no need npm install. Thats is for pokemongo-map
