### ISSUE TITLE
Error everytime pikabot runs for around 1hour

### ISSUE THREAD

**Issue by christopherganda** [PokemonGoF/PokemonGo-Bot#5041]
So,everytime my pikabot runs for around 1 hour,it shows error like this :
![2](https://cloud.githubusercontent.com/assets/14087607/18159103/525dba64-7051-11e6-8420-236aa23740f3.png)
<p>thank you</p>

**Comment by Cptspal** [comment]
According to this thread, your IP address may be banned : https://github.com/PokemonGoF/PokemonGo-Bot/issues/4908

**Comment by christopherganda** [comment]
banned?if my ip has been banned,how can I still use it?

**Comment by sediyama** [comment]
It is banned from Niantic servers, not from the Internet.

**Comment by afro001** [comment]
I had the same issue when there was a problem inside config file. For sure one pokemon name was written in a wrong way but I don't remember another mistake.

**Comment by k4n30** [comment]
Please use issue template
