### ISSUE TITLE
Latest pull not catching Pokemon or seeing any Pokemon

### ISSUE THREAD

**Issue by foster82** [PokemonGoF/PokemonGo-Bot#5046]
Hi guys,  

Latest pull is not seeing any Pokemon, I am using the default config file. Any ideas why.

**Comment by Anakin5** [comment]
Soft ban

**Comment by foster82** [comment]
The app works fine and the issue started last night.

**Comment by dokhed** [comment]
what do you mean not seeing any Pokemons?

**Comment by foster82** [comment]
Nothing is being seen,  it seems it is just walking also as no pokestops are being found.

**Comment by dokhed** [comment]
Could you post the config.json file

**Comment by foster82** [comment]
The config file is just the default one generated by the setup script

**Comment by foster82** [comment]
It seems like the bot is just walking and nothing else
