### ISSUE TITLE
How i can open Web UI in Linux

### ISSUE THREAD

**Issue by shudack** [PokemonGoF/PokemonGo-Bot#5052]
Hi,

How i can open Web UI in Linux? (The Bot works fine, but URL i don't know what's the port)
I test with my MyURL:4000 and MyURL:8000 and don't work.

Best regards,
Shudack

**Comment by mmixx** [comment]
If you didn't run the command `python -m SimpleHTTPServer` when you're inside the `web` directory or haven't setup a local web server on your linux box... you probably won't be able to open the Web UI... If you have, the default port for that is `8000`...

**Comment by shudack** [comment]
Thanks, it works :D

**Comment by mmixx** [comment]
Welcome...
