### ISSUE TITLE
UTF-8 error, but bot still run normally

### ISSUE THREAD

**Issue by kureijir** [PokemonGoF/PokemonGo-Bot#5053]
### Expected Behavior
Bot run normally without any errors.

### Actual Behavior
Sometimes bot throws an UTF-8 error, but still run normally

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/4feZt242

### Output when issue occurred
http://pastebin.com/7cD9CccT

### Steps to Reproduce
Just run the bot

### Other Information
OS: 
Arch Linux ARM
Branch: 
master
Git Commit: 
42d670a411b4f8dc9a6206dd10a88cc51744026d
Python Version: 
Python 2.7.12

**Comment by k4n30** [comment]
@kureijir Which issue is current #5053 or #5054 ? One or the other is a duplicate, please close the issue your experiencing or don't reuse the same output for both issues
