### ISSUE TITLE
Sleep schedule fails to wake up

### ISSUE THREAD

**Issue by kureijir** [PokemonGoF/PokemonGo-Bot#5054]
### Expected Behavior
After a scheduled sleep, bot wake up and continue catching/farming.

### Actual Behavior
Bot does nothing even after the sleep period. If sent a SIGINT, bot throws some error

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/4feZt242

### Output when issue occurred
http://pastebin.com/t6TK5ZJU

### Steps to Reproduce
Set some sleep schedule in config and run the boss.

### Other Information
OS: 
Arch Linux ARM (chrooted from Android)
Branch: 
master
Git Commit: 
42d670a411b4f8dc9a6206dd10a88cc51744026d
Python Version: 
Python 2.7.12

**Comment by k4n30** [comment]
@kureijir Which issue is current #5053 or #5054 ? One or the other is a duplicate, please close the issue your experiencing or don't reuse the same output for both issues

**Comment by kureijir** [comment]
@k4n30 I'm sorry that I've made it confusing, but they're 2 separate issues. #5054 make me unable to play without manually restarting the bot, while #5053 did me no harm so far, just occasional error seen from the terminal output (please look at the timestamp). I don't know why line 2-29 of the output looks similar to #5053's output, but they're not identical anyway. Umm... if you still think they're duplicate I'll close #5053.

**Comment by kureijir** [comment]
I forgot the fact that Android device has "Deep sleep" mode, which tune down CPU to the minimum speed. Will try a wakelock app and give a reply tomorrow.

**Comment by kureijir** [comment]
@k4n30 I tried to keep my phone awake and the bot run normally. Strangely, the errors from #5053 are gone too. Well, I'll close both issues.
