### ISSUE TITLE
[MoveToMapPokemon] No pokemons in list to snipe

### ISSUE THREAD

**Issue by jane0815** [PokemonGoF/PokemonGo-Bot#5056]
### Expected Behavior

Bot snipe pokemons from social map

### Actual Behavior

Bot is not sniping, stopped to work two days ago. 

### Your FULL config.json 

I just tryed with unmodified version of config.json.map.example and still the same problem.

### Output when issue occurred

[MoveToMapPokemon] [INFO] [move_to_map_pokemon] No pokemons in list to snipe

### Steps to Reproduce

Run latest dev with config.json.map.example

### Other Information

OS: Mac OSX
Branch: dev 
Git Commit: d5059ed2 

I have a local map running for my area running on port 9000.
I also use PogoAlerts to send notifications.

**Comment by jane0815** [comment]
It was working for a few minutes after i changed "snipe_high_prio_only": from true to false. 

But when i tryed to verifiy that this really was the problem it stopped to work again. 

Maybe the server is overloaded and not accepting more connections?

**Comment by Asafffff** [comment]
I thought I have a different problem, but I enabled debug and I'm having the same message. #5057

**Comment by pranavperfect** [comment]
Would sniping result in getting banned sooner?

**Comment by Jasperrr91** [comment]
What is your max_sniping_range?

**Comment by jane0815** [comment]
It was fixed for me after i did another git pull after pokemongof fixed something.
