### ISSUE TITLE
release_config.json still releasing

### ISSUE THREAD

**Issue by HeIix** [PokemonGoF/PokemonGo-Bot#506]
### Expected Behavior
Restrict the release of Pokemon to CP < 300 or IV < 0.8
`	"any": {
		"min_cp": 300,
		"min_iv": 0.8,
		"cp_iv_logic": "or"
	},`

### Actual Behavior

> [x] Captured Eevee! [CP 318] [IV 0.78] - exchanging for candy
> [x] Release config for Eevee: CP 300 or IV 0.8
> [#] Eevee has been exchanged for candy!
> [2016-07-23 21:13:37] [#] Something rustles nearby!
> [#] A Wild Diglett appeared! [CP 181] [Potential 0.8]
> [#] IV [Stamina/Attack/Defense] = [13/12/11]
> [x] Using Pokeball...
> [x] Captured Diglett! [CP 181] [IV 0.8] - exchanging for candy
> [x] Release config for Diglett: CP 300 or IV 0.8
> [#] Diglett has been exchanged for candy!

### Steps to Reproduce
Catching pokemon

### Other Information
OS: Debian
Dev branch

**Comment by pol0nium** [comment]
Looks like it works as specified in your example, no?

**Comment by HeIix** [comment]
I may be having a brain fart.  My understanding on setting min_cip to 300 tells me that the 318 Eevee should not have been released.  Same with the Diglett being released, it was 0.8 and my min_iv is set at 0.8.

**Comment by alistairmackenzie** [comment]
I've and similar results, look like the OR is being processed as an AND.

**Comment by pol0nium** [comment]
My understanding is that the config says "release the pokemon if cp < 300  or iv < 0.8". In your example, each time one of the condition was `TRUE`.

**Comment by alistairmackenzie** [comment]
See here for a slightly better example.

`[2016-07-23 22:29:30] [#] Something rustles nearby!
[#] A Wild Clefairy appeared! [CP 323] [Potential 0.67]
[#] IV [Stamina/Attack/Defense] = [4/13/13]
[x] Using Greatball...
[x] Captured Clefairy! [CP 323] [IV 0.67] - exchanging for candy
[x] Release config for Clefairy: CP 400 or IV 0.4
[#] Clefairy has been exchanged for candy`

**Comment by pol0nium** [comment]
323 < 400 -> TRUE
0.67 < 0.4 -> FALSE
release pokemon if TRUE or FALSE

Therefore pokemon is released.
I think this is the correct behaviour.

**Comment by HeIix** [comment]
If that's the case then how do you suppose I set the configuration to keep pokemon that are CP 300+ and IV 0.8+, releasing everything else?  Thanks for your time and feedback.

**Comment by pol0nium** [comment]
I think you should replace `"any": { "min_cp": 300, "min_iv": 0.8, "cp_iv_logic": "or" },` by `"any": { "min_cp": 300, "min_iv": 0.8, "cp_iv_logic": "and" },`

**Comment by Hatsunyan** [comment]
i don't understand, if config is
```js
"any": {
		"min_cp": 400,
		"min_iv": 0.8,
		"cp_iv_logic": "or"
	},
```
thats mean, don`t release pokemon if cp >=400 OR iv >= 0.8.
this correct ?

**Comment by pol0nium** [comment]
That means "realease pokemon if cp <400 or iv < 0.8"

**Comment by timychann** [comment]
I think the logic could be reversed:

` release_results = {
            'cp':               True,
            'iv':               True,
        }

        if release_config.get('min_cp'):
            min_cp = release_config['min_cp']
            if cp > min_cp:
                release_results['cp'] = False

        if release_config.get('min_iv'):
            min_iv = release_config['min_iv']
            if iv > min_iv:
                release_results['iv'] = False`

So it will release unless the Pokemon's CP or IV is over the minimum threshold

**Comment by surfaace** [comment]
release_config and config has been merged, please see if issue remains. if it does open a new issue with reference to this

**Comment by rlllam** [comment]
It's kinda poor design imo
