### ISSUE TITLE
WebUI total items is broken?

### ISSUE THREAD

**Issue by Asafffff** [PokemonGoF/PokemonGo-Bot#5064]
### Expected Behavior
See the numbers of items in total in the headline "X items in Bag"

### Actual Behavior
It shows 13 items for me, while I have much more

### Other Information
OS: 
Chrome
Branch: 
dev
Git Commit: 
6374300108ad5d30abc7a272eabf14617bb96e8a
Python Version: 
2.7.12

**Comment by Gobberwart** [comment]
I see this as well. It seems to be displaying the number of "types" of items rather than the total number of items since the latest update.

**Comment by Gobberwart** [comment]
I've just submitted a fix for this. Not sure how long it will take to be implemented.

**Comment by k4n30** [comment]
@Gobberwart can you link the PR please

**Comment by Gobberwart** [comment]
@k4n30 Can I do that from here? PR is in Pokemongo-Web, not Pokemongo-Bot. It's PR 33.

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Web/pull/34

**Comment by Gobberwart** [comment]
Er, yeah.. 34 is what I meant :)

Thanks for that.

**Comment by oralunal** [comment]
It's fixed now. Thanks Gobbert
