### ISSUE TITLE
Getting softban frequently 

### ISSUE THREAD

**Issue by kolinchang** [PokemonGoF/PokemonGo-Bot#5073]
###_ Expected Behavior
Bot keeps a low profile, running without softban, does not search stops too often.

### Actual Behavior
pokestop_searching_too_often, followed by handle soft ban.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/raw/hwPz74Wh

### Output when issue occurred
http://pastebin.com/raw/wNYy33CR

### Steps to Reproduce
Run bot with provided config, run past 23 mins in the game.

### Other Information
OS: 
Windows 10
Branch: 
dev
Git Commit: 
d5059ed2adb569953a3e627b4141b2275b0b1bc5

Python Version: 
2.7.12
Any other relevant files/configs (eg: path files) 
http://pastebin.com/raw/8ccghA0X (optional: seem to happen with or without)

**Comment by Gobberwart** [comment]
You're not opening the app on your phone while running the bot are you?

**Comment by kolinchang** [comment]
@Gobberwart Good question, but no. I don't log into game while running bot.

**Comment by oralunal** [comment]
Are you running one account only?

**Comment by kolinchang** [comment]
@oralunal Running multiple, tried running just one from same ip for a while, doesn't seem to make a difference.  Do you think it's an IP ban?

**Comment by oralunal** [comment]
It is probably an IP ban. Best botting is one account per IP. You can use maximum two accounts per IP but it is not healthy, too.
Please continue to discuss this on Slack Server.

**Comment by kolinchang** [comment]
Just an update, this doesn't seem to happen anymore after I got latest on dev
