### ISSUE TITLE
[FEATURE REQUEST] Load new config after wake up from sleep schedule

### ISSUE THREAD

**Issue by nugrahawahyu** [PokemonGoF/PokemonGo-Bot#5080]
### Short Description

We will able to set config file for certain hours then switch to other config file for the next hours.
### How it would help others

We will able to set what the bot gonna do in a day like follow path in certain location for 3 hours then wandering around in certain location or snipping pokemon for 2 hours.

**Comment by MZorzy** [comment]
implementing somethin like '-stop-at-time' we must use batch/script to do this
