### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by beltoft** [PokemonGoF/PokemonGo-Bot#5086]
### Expected Behavior
Bot should run for more than a few minutes

### Actual Behavior
Bot start and runs for a couple of minutes and then crashes

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

{
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": true,   
    "live_config_update": {
      "enabled": false,
    
    "tasks_only": false
},   
   
    "tasks": [

   {
        "type": "TransferPokemon",
        "config": {
          "min_free_slot": 5,
          "transfer_wait_min": 1,
          "transfer_wait_max": 4
        }
      },
          {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": true,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
    
    {
      "type": "HandleSoftBan"
    },
  
    { "type": "UpdateWebInventory",
      "config": {
        "enabled": true
      }
    },

       {
        "type": "RandomPause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:10:00",
          "max_interval": "02:00:00"
        }
      },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": true,
          "// set a name": "",
          "nickname": "SugarBison2",
          "team": 2
        }
      },
 
      {
        "type": "CollectLevelUpReward",
        "config": {
          "collect_reward": true,
          "level_limit": -1
        }
      },
      {
        "type": "IncubateEggs",
        "config": {
          "enabled": true,
          "infinite_longer_eggs_first": false,
          "breakable_longer_eggs_first": true,
          "min_interval": 120,
         "infinite": [2,5,10],
         "breakable": [2,5,10]
        }
      },
 
    {
        "type": "RecycleItems",
        "config": {
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          },
          "recycle_wait_min": 1,
          "recycle_wait_max": 4
        }
      },
	    {
	      "type": "CatchPokemon",
	      "config": {
	        "catch_visible_pokemon": true,
	        "catch_lured_pokemon": true,
         "daily_catch_limit": 900,
          "min_ultraball_to_keep": 5,
	        "catch_throw_parameters": {
	          "excellent_rate": 0.1,
	          "great_rate": 0.5,
	          "nice_rate": 0.3,
	          "normal_rate": 0.1,
	          "spin_success_rate" : 0.6
	        },
				  "catch_simulation": {
				    "flee_count": 3,
				    "flee_duration": 2,
				    "catch_wait_min": 2,
				    "catch_wait_max": 6,
				    "berry_wait_min": 2,
				    "berry_wait_max": 3,
				    "changeball_wait_min": 2,
				    "changeball_wait_max": 3
				  }
	      }
	    },
      {
        "type": "SpinFort",
        "config": {
          "enabled": true,
          "spin_wait_min": 1,
          "spin_wait_max": 3,
          "daily_spin_limit": 1900
        }
      },

		{
			"type": "PokemonOptimizer",
			"config": {
				"enabled": true,
				"transfer": true,
				"transfer_wait_min": 3,
				"transfer_wait_max": 5,
				"evolve": true,
				"evolve_time": 20,
				"evolve_for_xp": true,
				"evolve_only_with_lucky_egg": false,
				"evolve_count_for_lucky_egg": 80,
				"may_use_lucky_egg": true,
				"upgrade": true,
				"upgrade_level": 60,
        "min_slots_left": 5,
				"groups": {
					"gym": ["Dragonite", "Snorlax", "Lapras", "Arcanine"]
				},
				"keep": [
					{
						"mode": "by_family",
						"top": 1,
						"sort": [{"iv": 1.0}],
						"evolve": true,
						"upgrade": true
					},
					{
						"mode": "by_family",
						"top": 1,
						"sort": [{"ncp": "0.9"}],
						"evolve": true,
						"upgrade": false
					},
					{
						"mode": "by_family",
						"top": 1,
						"sort": ["cp"],
						"evolve": false,
						"upgrade": false
					},
          {
						"mode": "by_family",
						"names": ["gym"],
						"top": 2,
						"sort": [{"iv": 0.9}],
						"evolve": true,
						"upgrade": true
					}
				]
			}
		},

    {
      "type": "MoveToMapPokemon",
        "config": {
          "address": "http://10.120.36.50:5000",
          "max_sniping_distance": 1000000,
          "max_walking_distance": 500,
          "min_time": 15,
          "min_ball": 20,
          "prioritize_vips": true,
          "snipe": true,
          "snipe_high_prio_only": true,
          "snipe_high_prio_threshold": 400,
          "mode": "priority",
          "walker": "StepWalker",
          "max_extra_dist_fort": 10,
          "skip_rounds": 1,
	        "map_path": "raw_data",
          "update_map": true,
          "update_map_min_distance_meters": 500,
	        "update_map_min_time_sec": 60,
	        "snipe_sleep_sec": 1,
	        "snipe_max_in_chain": 500,
	        "debug": false,        
          
          "catch": {
         
          "==========Legendaries==========": 0,
          "Aerodactyl": 1000,
          "Snorlax": 1000,
          "Dratini": 1000,
          "Dragonair": 1000,
          "Dragonite": 1000,
          
          
          "========Ghosts============": 0,
          "Mewtwo": 2500,
          "Mew": 2500,
          "Articuno": 2500,
          "Zapdos": 2500,
          "Moltres": 2500,
          "Ditto": 2500,
        
          
          "Persian": 500,
          "Arcanine": 500,
          "Golem": 1500,
          "Rapidash": 1500,
          "Hitmonlee": 500,
          "Hitmonchan": 500,
          "Rhydon": 1500,
          "Chansey": 1500,
          "Porygon": 500,
          "Omanyte": 500,
          "Omastar": 1500,
          "Kabutops": 1500,
          

          "==========Region Locked==========": 0,
          "Farfetch'd": 1000,
          "Kangaskhan": 1000,
          "Mr. Mime": 1000,
          "Tauros": 1000,

          "==========Very Rare==========": 0,
          "Lapras": 900,
          "Electabuzz": 900,
          "Magmar": 900,
          

          "==========Starters==========": 0,
          
          "Ivysaur": 600,
          "Venusaur": 1000,

          
          "Charmeleon": 600,
          "Charizard": 1000,

          
          "Wartortle": 600,
          "Blastoise": 1000,

          "Pikachu": 600,
          "Raichu": 1000,

          "==========Semi Rare==========": 0,
          

          "==========Uncommon==========": 0,

          "Omastar": 500,

          "Dewgong": 500,

          "Muk": 500,

          "Cloyster": 500,

          "Haunter": 500,
          "Gengar": 1000,

          "Hypno": 600,

          
          "Ninetales": 600,

          "Wigglytuff": 500,

          "Dugtrio": 500,

          "Vaporeon": 800,
          "Jolteon": 800,
          "Flareon": 800,

          "Kabutops": 500,

          "Gyarados": 800,

          "Rapidash": 500,

          "Slowbro": 500,

          
          "Magneton": 500,

          "Kingler": 500,

          "Electrode": 500,

          "Exeggcutor": 500,

          
          "Lickitung": 500,

          "Weezing": 500,

          "Rhydon": 500,

          "Chansey": 800,

          
          "Seadra": 600,

          "Seaking": 500,

          "Starmie": 800,

          "==========T1 Evolvers==========": 0,
          "Butterfree": 500,

          "Beedrill": 500,

          
          "==========T2 Evolvers==========": 0,
          
          "Vileplume": 600,

          
          "Poliwrath": 800,

          
          "Kadabra": 600,
          "Alakazam": 800,

          
          "Machamp": 800,

          
          "Victreebel": 800
        }
      }
    },
      {
        "type": "MoveToFort",
        "config": {
          "lure_attraction": true,
          "lure_max_distance": 2000,
          "walker": "StepWalker"
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 4,
          "step_size": 70
        }
      }
  ],
   "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
  
  "walk_min": 13,
  "walk_max": 23,
  "sleep_schedule": [
      {
        "time": "22:53",
        "duration": "7:39",
        "time_random_offset": "00:30",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      }
      ],
  "alt_min": 500,
  "alt_max": 1000,
  "gps_default_altitude": 8.0,
  "replicate_gps_xy_noise": false,
  "replicate_gps_z_noise": false,
  "gps_xy_noise_range": 0.000125,
  "gps_z_noise_range": 12.5,
  "action_wait_min": 1,
  "action_wait_max": 5,
  "debug": false,
  "test": false,
  "health_record": false,
  "location_cache": true,
  "distance_unit": "km",
  "reconnecting_timeout": 1,
      "logging": {
      "color": true,
      "show_datetime": true,
      "show_process_name": false,
      "show_log_level": false
    },
  "catch_randomize_reticle_factor": 1.0,
  "catch_randomize_spin_factor": 1.0,
   "catch_throw_parameters": {
      "excellent_rate": 0.7,
      "great_rate": 0.5,
      "nice_rate": 0.3,
      "normal_rate": 0.1,
      "spin_success_rate" : 0.8
    },
  "catch": {
    "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or" },

    "// Pokemons with example": { "always_catch": true },
    "// Gets filtered with release parameters": {},

    "// Legendary pokemons (Goes under S-Tier)": {},
    "Lapras": { "always_catch": true },
    "Moltres": { "always_catch": true },
    "Zapdos": { "always_catch": true },
    "Articuno": { "always_catch": true },

    "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
    "Mewtwo": { "always_catch": true },
    "Dragonite": { "always_catch": true },
    "Snorlax": { "always_catch": true },
    "// Mew evolves to Mewtwo": {},
    "Mew": { "always_catch": true },
    "Arcanine": { "always_catch": true },
    "Vaporeon": { "always_catch": true },
    "Gyarados": { "always_catch": true },
    "Exeggutor": { "always_catch": true },
    "Muk": { "always_catch": true },
    "Weezing": { "always_catch": true },
    "Flareon": { "always_catch": true },

    "// Growlithe evolves to Arcanine": {},
    "Growlithe": { "always_catch": true },
    "// Dragonair evolves to Dragonite": {},
    "Dragonair": { "always_catch": true },
    "// Grimer evolves to Muk": {},
    "Grimer": { "always_catch": true },

    "// Magikarp evolves to Gyarados": {},
    "Magikarp": { "always_catch": true },
    "// Exeggcute evolves to Exeggutor": {},
    "Exeggcute": { "always_catch": true },
    "// Eevee evolves to many versions, like Vaporeon, Flareon": {},
    "Eevee": { "always_catch": true },

    "// A-Tier pokemons": {},
    "Slowbro": { "always_catch": true },
    "Victreebel": { "always_catch": true },
    "Machamp": { "always_catch": true },
    "Poliwrath": { "always_catch": true },
    "Clefable": { "always_catch": true },
    "Nidoking": { "always_catch": true },
    "Venusaur": { "always_catch": true },
    "Charizard": { "always_catch": true },
    "Golduck": { "always_catch": true },
    "Nidoqueen": { "always_catch": true },
    "Vileplume": { "always_catch": true },
    "Blastoise": { "always_catch": true },
    "Omastar":  { "always_catch": true },
    "Aerodactyl": { "always_catch": true },
    "Golem": { "always_catch": true },
    "Wigglytuff": { "always_catch": true },
    "Dewgong": { "always_catch": true },
    "Ninetales": { "always_catch": true },
    "Magmar": { "always_catch": true },
    "Kabutops": { "always_catch": true },
    "Electabuzz": { "always_catch": true },
    "Starmie": { "always_catch": true },
    "Jolteon": { "always_catch": true },
    "Rapidash": { "always_catch": true },
    "Pinsir": { "always_catch": true },
    "Scyther": { "always_catch": true },
    "Tentacruel": { "always_catch": true },
    "Gengar": { "always_catch": true },
    "Hypno": { "always_catch": true },
    "Pidgeot": { "always_catch": true },
    "Rhydon": { "always_catch": true },
    "Seaking": { "always_catch": true },
    "Kangaskhan": { "always_catch": true }
 },
 
 
  "vips" : {
    "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
    "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
    "Lapras": {},
    "Moltres": {},
    "Zapdos": {},
    "Articuno": {},

    "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
    "Mewtwo": {},
    "Dragonite": {},
    "Snorlax": {},
    "// Mew evolves to Mewtwo": {},
    "Mew": {},
    "Arcanine": {},
    "Vaporeon": {},
    "Gyarados": {},
    "Exeggutor": {},
    "Muk": {},
    "Weezing": {},
    "Flareon": {}

 	}
 }
  

### Output when issue occurred
[2016-09-02 09:01:05] [MainThread] [log_stats] SugarBison2 | Uptime : 0:01:35 | Earned 0                                                                                                                   Stardust | +150 XP | 5,672 XP/h | Visited 3 stops
[2016-09-02 09:01:08] [MainThread] [item_discarded] Discarded 1x Pokeball.
[2016-09-02 09:01:12] [MainThread] [item_discarded] Discarded 1x Greatball.
[2016-09-02 09:01:14] [MainThread] [item_discarded] Discarded 1x Potion.
[2016-09-02 09:01:14] [MainThread] [moving_to_fort] Moving towards pokestop 3 Eyed Dog Mural - 0.10km
Traceback (most recent call last):
  File "pokecli.py", line 795, in <module>
  File "pokecli.py", line 231, in main
  File "pokecli.py", line 279, in report_summary
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/metrics.py", line 108, in capture_stats
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 239, in call
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/api_wrapper.py", line 188, in _call
  File "/home/beltoft/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 236, in call
  File "/home/beltoft/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 124, in request
  File "/home/beltoft/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 212, in _build_main_request
OSError: [Errno 24] Too many open files
Fri Sep 2 09:01:18 CEST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

### Steps to Reproduce
Updated the bot to latest dev and got the problem after

### Other Information
OS: 
ubuntu 14.04 LTS
Branch: 
DEV

**Comment by davidspeijer** [comment]
Same problem here.....

> [2016-09-02 09:25:18] [MoveToFort] [moving_to_fort] Moving towards pokestop xxxx - 0.05km
> [2016-09-02 09:25:19] [PokemonGoBot] [api_error] Session stale, re-logging in.
> [2016-09-02 09:25:19] [PokemonGoBot] [login_started] Login procedure started.
> [2016-09-02 09:25:19] [pgoapi.pgoapi] Login process failed: ('Caught ConnectionError: %s', SSLError(SSLError(IOError(24, 'Too many open files'),),))
> [2016-09-02 09:25:19] [PokemonGoBot] [login_failed] Login error, server busy. Waiting 10 seconds to try again.
> [2016-09-02 09:25:29] [pgoapi.pgoapi] Login process failed: ('Caught ConnectionError: %s', SSLError(SSLError(IOError(24, 'Too many open files'),),))
> [2016-09-02 09:25:29] [PokemonGoBot] [login_failed] Login error, server busy. Waiting 10 seconds to try again.
> [2016-09-02 09:25:40] [pgoapi.pgoapi] Login process failed: ('Caught ConnectionError: %s', SSLError(SSLError(IOError(24, 'Too many open files'),),))
> [2016-09-02 09:25:40] [PokemonGoBot] [login_failed] Login error, server busy. Waiting 10 seconds to try again.
> [2016-09-02 09:25:50] [pgoapi.pgoapi] Login process failed: ('Caught ConnectionError: %s', SSLError(SSLError(IOError(24, 'Too many open files'),),))
> [2016-09-02 09:25:50] [PokemonGoBot] [login_failed] Login error, server busy. Waiting 10 seconds to try again.
> [2016-09-02 09:26:00] [pgoapi.pgoapi] Login process failed: ('Caught ConnectionError: %s', SSLError(SSLError(IOError(24, 'Too many open files'),),))
> [2016-09-02 09:26:00] [PokemonGoBot] [login_failed] Login error, server busy. Waiting 10 seconds to try again.
> [2016-09-02 09:26:10] [pgoapi.pgoapi] Login process failed: ('Caught ConnectionError: %s', SSLError(SSLError(IOError(24, 'Too many open files'),),))
> [2016-09-02 09:26:10] [PokemonGoBot] [login_failed] Login error, server busy. Waiting 10 seconds to try again.
> [2016-09-02 09:26:21] [pgoapi.pgoapi] Login process failed: ('Caught ConnectionError: %s', SSLError(SSLError(IOError(24, 'Too many open files'),),))
> [2016-09-02 09:26:21] [PokemonGoBot] [login_failed] Login error, server busy. Waiting 10 seconds to try again.
> [2016-09-02 09:26:31] [pgoapi.pgoapi] Login process failed: ('Caught ConnectionError: %s', SSLError(SSLError(IOError(24, 'Too many open files'),),))
> [2016-09-02 09:26:31] [PokemonGoBot] [login_failed] Login error, server busy. Waiting 10 seconds to try again.
> [2016-09-02 09:26:41] [pgoapi.pgoapi] Login process failed: ('Caught ConnectionError: %s', SSLError(SSLError(IOError(24, 'Too many open files'),),))

**Comment by sohje** [comment]
Try to run
```bash
ulimit -n 2048
```
Temp workaround.
Also, show `pip freeze` output

**Comment by davidspeijer** [comment]
backports.ssl-match-hostname==3.5.0.1
certifi==2016.8.31
click==6.6
colorama==0.3.7
contextlib2==0.5.4
decorator==4.0.10
demjson==2.2.4
docutils==0.12
enum34==1.1.6
eventlet==0.19.0
Flask==0.11.1
funcsigs==1.0.2
future==0.15.2
Geohash==1.0
geopy==1.11.0
googlemaps==2.4.4
gpsoauth==0.3.0
gpxpy==1.1.1
greenlet==0.4.9
haversine==0.4.5
iniherit==0.3.4
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
mock==2.0.0
networkx==1.11
numpy==1.11.0
paho-mqtt==1.2
pbr==1.10.0
-e git+https://github.com/joelgreen/pgoapi.git/@fa49ada8570b0817c5a73b9315ba010fa7a47874#egg=pgoapi
polyline==1.3.1
protobuf==3.0.0b4
protobuf-to-dict==0.1.0
pycryptodomex==3.4.2
python-engineio==1.0.1
python-slugify==1.2.1
python-socketio==1.4.2
python-telegram-bot==5.0.0
PyYAML==3.11
raven==5.23.0
requests==2.10.0
requests-mock==1.0.0
s2sphere==0.2.4
six==1.10.0
socketIO-client==0.7.0
timeout-decorator==0.3.2
Unidecode==0.4.19
urllib3==1.16
websocket-client==0.37.0
Werkzeug==0.11.11
xxhash==0.6.1
yoyo-migrations==5.0.3

**Comment by th3w4y** [comment]
@beltoft is this still an issue for you?

**Comment by beltoft** [comment]
Nope haven't seen it in since I rebooted my machine
