### ISSUE TITLE
bot crashing a lot more often

### ISSUE THREAD

**Issue by philly223** [PokemonGoF/PokemonGo-Bot#5087]
### Expected Behavior
bot to run normally

### Actual Behavior
bot runs good for 5-15 minutes but eventually crashes

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/zSQFaUx5

### Output when issue occurred
http://pastebin.com/AW8xa5En

which was then followed by another crash on diff account -> http://pastebin.com/0SCQyBtd

+ more

-----ImportError: No module named processors
  File "/Users/Phil/PokemonGo/PokemonGo-Bot/lib/python2.7/site-packages/requests/adapters.py", line 467, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.google-analytics.com', port=80): Max retries exceeded with url: /collect (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1116f7b90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

-----  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named EvolvePokemonMessage_pb2

### Steps to Reproduce
git pull
pip install --upgrade

### Other Information
OS X
Python
Latest master pull

**Comment by Gobberwart** [comment]
pip install -r requirements.txt --upgrade
