### ISSUE TITLE
Slack account

### ISSUE THREAD

**Issue by th3w4y** [PokemonGoF/PokemonGo-Bot#5090]
I use to have an account on slack for the PokemonGo-Bot team, but about a month back i deleted it.
(i was not sure what my future involvement in this project will be in the context of the panic arround our accounts being banned)

I would like to be able to use slack again. 

Can one of the Slack admins re-enable my account.

Thanks

**Comment by oralunal** [comment]
What is your username?

**Comment by th3w4y** [comment]
my e-mail address that i commit with... ovidiu@ghinet.ch

**Comment by oralunal** [comment]
it's enabled now

**Comment by th3w4y** [comment]
Thanks!
