### ISSUE TITLE
More than 10000 candies but no Evolve

### ISSUE THREAD

**Issue by as4ajaysoni** [PokemonGoF/PokemonGo-Bot#5093]
### Expected Behavior

I have uploaded the config file. I enable the evolve section but still none of Pokemon got evolve yet.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/P6Q0QTfF

### Output when issue occurred

https://dl2.pushbulletusercontent.com/BwlLivEXn947HkwmKOrsEhtMduvOlMq2/candies.png

### Other Information
OS: 
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by sohje** [comment]
I think cause of this:
```js
"Pidgey": {"always_release": true},
"Weedle": {"always_release": true},
```

**Comment by as4ajaysoni** [comment]
I have also tried keep_best_cp :2 but still didn't see any evolve

**Comment by sohje** [comment]
Did you remove lines a posted before?

**Comment by as4ajaysoni** [comment]
Yes, I have even tried to replace whole release section by http://pastebin.com/WPVgbeYd
but still facing the same problem.

**Comment by as4ajaysoni** [comment]
https://dl2.pushbulletusercontent.com/Y4jaLUuymBUAeW8xsqam8zUVrMEXpKFz/p2.png
No pokemon evolves yet.

**Comment by kirikay** [comment]
why is the minus sign (-) before ur Zubat and Rattata?

**Comment by as4ajaysoni** [comment]
I have removed those (-) sign before Zubat and Rattata. here is my new config http://pastebin.com/DnHeCFub
Still facing the same problem

**Comment by sohje** [comment]
Maybe you can try to disable use_lucky_egg, not sure but you can try.

**Comment by DeXtroTip** [comment]
Try changing:
"evolve_all": "all", 
To
"evolve_list": "all",

**Comment by as4ajaysoni** [comment]
Thanks a lot..... It worked after changing "evolve_all": "all",
To
"evolve_list": "all",
