### ISSUE TITLE
MoveToMapPokemon is not working with latest commit. Help.

### ISSUE THREAD

**Issue by kenkclam** [PokemonGoF/PokemonGo-Bot#5094]
===============ISSUE SECTION===============

### Expected Behaviour
The bot walk or snipe to Pokemon with MoveToMapPokemon. 

### Actual Behaviour
The Pokemon Map is working. I can see that it finds pokemon the bot should walk to via localhost.
The bot is not walking or sniping to any pokemon.
I have updated to the latest version.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
    "libencrypt_location": "",
    "enable_social": false,
    "websocket_server": true,
    "heartbeat_threshold": 13,

    "tasks": [
      {
        "//NOTE: This task MUST be placed on the top of task list": {},
        "type": "RandomAlivePause",
        "config": {
          "enabled": true,
          "min_duration": "00:01:10",
          "max_duration": "00:5:00",
          "min_interval": "00:5:00",
          "max_interval": "00:25:00"
        }
      },
      {
        "type": "RandomPause",
        "config": {
          "enabled": true,
          "min_duration": "00:5:10",
          "max_duration": "00:15:00",
          "min_interval": "00:18:00",
          "max_interval": "00:48:00"
        }
      },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": false,
          "// set a name": "",
          "nickname": ""
        }
      },
      {
        "type": "MoveToMapPokemon",
        "config": {
          "address": "http://localhost:5000",
          "max_walking_distance": 500,
          "max_sniping_distance": 6000000,
          "min_time": 10,
          "min_ball": 20,
          "prioritize_vips": true,
          "snipe": true,
          "snipe_high_prio_only": true,
          "snipe_high_prio_threshold": 1150,
          "update_map": false,
          "map_path": "raw_data",
          "walker": "StepWalker",
          "mode": "priority",
          "catch": {
            "Poliwag": 10,
            "Nidoran F": 10,
            "Nidoran M": 10,
            "Clefairy": 15,
            "Bellsprout": 10,
            "Slowpoke": 10,
            "Eevee": 20,
            "Oddish": 20,
            "Geodude": 50,
            "Abra": 50,
            "Diglett": 100,
            "Vulpix": 100,
            "Kabuto": 100,
            "Muk": 300,
            "Poliwrath": 200,
            "Golem": 200,
            "Weezing": 300,
            "Electrode": 300,
            "Primeape": 300,
            "Mr-mimi": 1000,
            "Chansey": 1000,
            "Alakazam": 600,
            "Omastar": 500,
            "Kabutops": 500,
            "Raichu": 600,
            "Tauros": 500,
            "Dugtrio": 500,
            "Bulbasaur": 400,
            "Charmander": 500,
            "Charmeleon": 600,
            "Squirtle": 300,
            "Pikachu": 600,
            "Growlithe": 400,
            "Machop": 300,
            "Grimer": 200,
            "Exeggcute": 500,
            "Omanyte": 100,
            "Koffing": 200,
            "Dratini": 600,
            "Lapras": 1000,
            "Electabuzz": 1000,
            "Magmar": 600,
            "Ditto": 900,
            "Arcanine": 980,
            "Machamp": 700,
            "Blastoise": 980,
            "Venusaur": 1100,
            "Charizard": 1100,
            "Slowbro": 300,
            "Nidoqueen": 150,
            "Nidoking": 150,
            "Clefable": 100,
            "Victreebel": 200,
            "Jolteon": 200,
            "Magneton": 100,
            "Gengar": 100,
            "Machoke": 80,
            "Vileplume": 400,
            "Exeggutor": 1200,
            "Aerodactyl": 600,
            "Snorlax": 1150,
            "Articuno": 1200,
            "Zapdos": 1300,
            "Moltres": 1300,
            "Dragonair": 800,
            "Dragonite": 1200,
            "Mewtwo": 1300,
            "Mew": 1300
          }
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "CollectLevelUpReward"
      },
      {
        "type": "IncubateEggs",
        "config": {
          "longer_eggs_first": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": true,
          "min_interval": 1200,
          "show_all_multiple_lines": false,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries"]
        }
      },
      {
       "type": "TransferPokemon",
       "config": {
       "min_free_slot": 5,
       "transfer_wait_min": 1,
       "transfer_wait_max": 4
      }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "enabled": true,
            
            "// evolve only pidgey and drowzee": "",
            "// evolve_list": "pidgey, drowzee",
            "// donot_evolve_list": "none",
            
            "// evolve all but pidgey and drowzee": "",
            "// evolve_list": "all",
            "// donot_evolve_list": "pidgey, drowzee",
            
            "evolve_list": "Magikarp, Psyduck, Poliwag, Poliwhirl, Drowzee, Slowpoke, Staryu, Eevee, Krabby, Goldeen, Pidgeotto, Bellsprout, Gastly, Oddish, Horsea",
            "donot_evolve_list": "none",
            
          "first_evolve_by": "cp",
          "evolve_above_cp": 120,
          "evolve_above_iv": 0.9,
          "logic": "and",
          "min_evolve_speed": 30,
          "max_evolve_speed": 40,
          "use_lucky_egg": false
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 10,
          "max_balls_keep": 130,
          "max_potions_keep": 160,
          "max_berries_keep": 30,
          "max_revives_keep": 50,
          "item_filter": {
            "Pokeball":       { "keep" : 5 },
            "Potion":         { "keep" : 5 },
            "Super Potion":   { "keep" : 5 },
            "Hyper Potion":   { "keep" : 60 },
            "Max Potion":     { "keep" : 100 },
            "Revive":         { "keep" : 30 },
            "Max Revive":     { "keep" : 40},
	    "Greatball":      { "keep" : 70 },
            "Ultraball":      { "keep" : 100 },
            "Razz Berry":     { "keep" : 30 }
          }
        }
      },
	    {
	      "type": "CatchPokemon",
	      "config": {
	        "catch_visible_pokemon": true,
	        "catch_lured_pokemon": true,
                "daily_catch_limit": 500,
	        "min_ultraball_to_keep": 2,
	        "catch_throw_parameters": {
	          "excellent_rate": 0.1,
	          "great_rate": 0.1,
	          "nice_rate": 0.4,
	          "normal_rate": 0.4,
	          "spin_success_rate" : 0.3
	        },
				  "catch_simulation": {
				    "flee_count": 2,
				    "flee_duration": 2,
				    "catch_wait_min": 1,
				    "catch_wait_max": 3,
				    "berry_wait_min": 2,
				    "berry_wait_max": 3,
				    "changeball_wait_min": 2,
				    "changeball_wait_max": 3
				  }
	      }
	    },
      {
        "type": "SpinFort",
        "config": {
          "spin_wait_min": 2,
          "spin_wait_max": 8
           }
      },
      {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 1000
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "diameter": 1,
          "step_size": 5
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 10
    },
    "walk_max": 3,
    "walk_min": 1,
    "sleep_schedule": [
      {
        "time": "22:30",
        "duration": "03:00",
        "time_random_offset": "00:10",
        "duration_random_offset": "00:20",
        "wake_up_at_location": ""
      },
      {
        "time": "13:30",
        "duration": "5:00",
        "time_random_offset": "00:20",
        "duration_random_offset": "00:40",
        "wake_up_at_location": ""
      }
    ],
    "alt_min": 30,
    "alt_max": 40,
    "gps_default_altitude": 278.0,
    "replicate_gps_xy_noise": true,
    "replicate_gps_z_noise": true,
    "gps_xy_noise_range": 0.000025,
    "gps_z_noise_range": 4.5,
    "action_wait_min": 1,
    "action_wait_max": 10,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": false,
    "distance_unit": "km",
    "reconnecting_timeout": 30,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1.0,
    "catch_randomize_spin_factor": 1.0,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "Rattata": {"never_catch": true},
      "Caterpie": {"never_catch": true},
      "Weedle": {"never_catch": true},
      "Pidgey": {"never_catch": true},
      "Staryu": {"never_catch": true},
      "Horsea": {"never_catch": true},
      "Venonat": {"never_catch": true},
      "Tentacool": {"never_catch": true},
      "//Shellder": {"never_catch": true},
      "Doduo": {"never_catch": true},
      "//Starmie": {"never_catch": true},
      "Goldeen": {"never_catch": true},
      "Drowzee": {"never_catch": true},
      "Spearow": {"never_catch": true},
      "Zubat": {"never_catch": true},
      "Krabby": {"never_catch": true},
      "//Paras": {"never_catch": true},
      "Psyduck": {"never_catch": true},
      "//Pidgeotto": {"never_catch": true}
    },
    "release": {
      "any": {"release_below_cp": 800, "release_below_iv": 0.80, "logic": "and"},
      "Bulbasaur": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Squirtle": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Nidoran M": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Clefairy": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Rattata": {"keep_best_cp": 1},
      "Pidgey": {"keep_best_cp": 2, "keep_best_iv": 1},
      "Starmie": {"release_below_cp": 900, "release_below_iv": 0.80, "logic": "and"},
      "Raticate": {"release_below_cp": 900, "release_below_iv": 0.85, "logic": "and"},
      "Pidgeotto": {"release_below_cp": 900, "release_below_iv": 0.85, "logic": "and"},
      "Metapod": {"release_below_cp": 350, "release_below_iv": 0.85, "logic": "and"},
      "Kakuna": {"release_below_cp": 400, "release_below_iv": 0.85, "logic": "and"},
      "Zubat": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Caterpie": {"keep_best_cp": 1},
      "Weedle": {"keep_best_cp": 1},
      "Spearow": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Sandshrew": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Nidoran F": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Jigglypuff": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Oddish": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Paras": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Venonat": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Vulpix": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Mankey": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Diglett": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Abra": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Meowth": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Psyduck": {"keep_best_cp": 2, "keep_best_iv": 2},
      "Poliwag": {"keep_best_cp": 1, "keep_best_iv": 3},
      "Poliwhirl": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Geodude": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Ponyta": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Tentacool": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Bellsprout": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Slowpoke": {"keep_best_cp": 1, "keep_best_iv": 3},
      "Seel": {"release_below_cp": 650, "release_below_iv": 0.85, "logic": "and"},
      "Exeggcute": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Magnemite": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Shellder": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Doduo": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Dodrio": {"release_below_cp": 900, "release_below_iv": 0.7, "logic": "and"},
      "Tangela": {"release_below_cp": 800, "release_below_iv": 0.8, "logic": "and"},
      "Scyther": {"release_below_cp": 800, "release_below_iv": 0.8, "logic": "and"},
      "Pinsir": {"release_below_cp": 1600, "release_below_iv": 0.8, "logic": "and"},
      "Gastly": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Drowzee": {"keep_best_cp": 1, "keep_best_iv": 3},
      "Rhyhorn": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Krabby": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Cubone": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Koffing": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Horsea": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Goldeen": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Staryu": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Magikarp": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Dratini": {"keep_best_cp": 1, "keep_best_iv": 2},
      "Eevee": {"keep_best_cp": 2, "keep_best_iv": 3},
      "Ekans": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Growlithe": {"keep_best_cp": 2, "keep_best_iv": 2},
      "Jynx": {"keep_best_cp": 2},
      "Dodrio": {"keep_best_cp": 2}
    },
    "vips" : {
         "//Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}

    }
}

### Output when issue occurred
The log does not show any messages related to MoveToMapPokemon
But it is not a log problem, the bot is just not responding to MoveToMapPokemon

### Other Information
OS: 
Mac
Branch: 
 
Git Commit: 
2016-09-02 11:49:25,539 [       cli] [INFO] commit: e83c7e6b

**Comment by sohje** [comment]
Try to increase "max_walking_distance": 500 or set "update_map": true and check again.

**Comment by kenkclam** [comment]
Thanks for your reply.
I did that. I changed the distance to 1000 and 2000, and update map to true.
I can see Clzfairy etc on localhost:5000, but the bot is still not responding. It does not walk to them.
Sniping also does not work, probably suffers from the same problem.
i also tried to delete Movetofort, that does not help.

**Comment by sohje** [comment]
Can you show some logs with update_map enabled and max_walking_distance: 1000 or 2000

**Comment by kenkclam** [comment]
Like this?

2016-09-02 13:46:21,614 [PokemonCatchWorker] [INFO] [pokemon_appeared] Skip ignored Spearow! [CP 113] [Potential 0.42] [A/D/S 10/8/1]
2016-09-02 13:46:21,622 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Münster Brunnen - 0.06km
2016-09-02 13:46:23,475 [PokemonCatchWorker] [INFO] [pokemon_appeared] Skip ignored Drowzee! [CP 680] [Potential 0.38] [A/D/S 11/4/2]
2016-09-02 13:46:24,811 [PokemonCatchWorker] [INFO] [pokemon_appeared] Skip ignored Drowzee! [CP 680] [Potential 0.38] [A/D/S 11/4/2]
2016-09-02 13:46:24,820 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Münster Brunnen - 0.06km
2016-09-02 13:46:25,730 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Münster Brunnen - 0.05km
2016-09-02 13:46:26,476 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Münster Brunnen - 0.05km
2016-09-02 13:46:27,291 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Münster Brunnen - 0.05km
2016-09-02 13:46:28,317 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Münster Brunnen - 0.05km
2016-09-02 13:46:29,654 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Paras appeared! [CP 557] [NCP 0.61] [Potential 0.4] [A/D/S 9/8/1]
2016-09-02 13:46:36,088 [PokemonCatchWorker] [INFO] [threw_berry] Threw a Razz Berry! Catch rate with Greatball is now: 50.53
2016-09-02 13:46:40,889 [PokemonCatchWorker] [INFO] [threw_pokeball] Great throw! Used Greatball, with chance 50.53 (26 left)
2016-09-02 13:46:41,477 [PokemonCatchWorker] [INFO] [pokemon_caught] Captured Paras! [CP 557] [NCP 0.61] [Potential 0.4] [9/8/1] (59/500) [+150 exp]
2016-09-02 13:46:41,481 [PokemonCatchWorker] [INFO] [gained_candy] You now have 177 Paras candy!
2016-09-02 13:46:48,012 [PokemonCatchWorker] [INFO] [pokemon_appeared] Skip ignored Drowzee! [CP 680] [Potential 0.38] [A/D/S 11/4/2]
2016-09-02 13:46:48,683 [PokemonCatchWorker] [INFO] [pokemon_appeared] Skip ignored Drowzee! [CP 680] [Potential 0.38] [A/D/S 11/4/2]
2016-09-02 13:46:49,357 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Münster Brunnen - 0.05km
2016-09-02 13:46:52,476 [PokemonCatchWorker] [INFO] [pokemon_appeared] Skip ignored Drowzee! [CP 680] [Potential 0.38] [A/D/S 11/4/2]
2016-09-02 13:46:53,937 [PokemonCatchWorker] [INFO] [pokemon_appeared] Skip ignored Drowzee! [CP 680] [Potential 0.38] [A/D/S 11/4/2]
2016-09-02 13:46:53,945 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Münster Brunnen - 0.05km
2016-09-02 13:46:55,457 [PokemonCatchWorker] [INFO] [pokemon_appeared] Skip ignored Drowzee! [CP 680] [Potential 0.38] [A/D/S 11/4/2]
2016-09-02 13:46:56,125 [PokemonCatchWorker] [INFO] [pokemon_appeared] Skip ignored Drowzee! [CP 680] [Potential 0.38] [A/D/S 11/4/2]
2016-09-02 13:46:56,134 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Münster Brunnen - 0.05km
2016-09-02 13:46:57,983 [PokemonCatchWorker] [INFO] [pokemon_appeared] Skip ignored Drowzee! [CP 680] [Potential 0.38] [A/D/S 11/4/2]
2016-09-02 13:46:58,635 [PokemonCatchWorker] [INFO] [pokemon_appeared] Skip ignored Drowzee! [CP 680] [Potential 0.38] [A/D/S 11/4/2]
2016-09-02 13:46:58,643 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Münster Brunnen - 0.05km
2016-09-02 13:46:59,773 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Münster Brunnen - 0.05km
2016-09-02 13:47:00,660 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Münster Brunnen - 0.04km
2016-09-02 13:47:01,872 [MoveToFort] [INFO] [moving_to_fort] Moving towards pokestop Münster Brunnen - 0.04km

**Comment by ttpeter** [comment]
"Drowzee": {"never_catch": true},

You have this config under the CatchPokemon task, will never catch drowzee.. same to alot other pokemons too.

**Comment by kenkclam** [comment]
@ttpeter I know I am not catching Drowzee, I myself put that rules in my config....
But how is that related to the MoveToMapPokemon problem?
I am lost, can you explain more?

I skip catching these 15-19 pokemons:
  "Rattata": {"never_catch": true},
  "Caterpie": {"never_catch": true},
  "Weedle": {"never_catch": true},
  "Pidgey": {"never_catch": true},
  "Staryu": {"never_catch": true},
  "Horsea": {"never_catch": true},
  "Venonat": {"never_catch": true},
  "Tentacool": {"never_catch": true},
  "//Shellder": {"never_catch": true},
  "Doduo": {"never_catch": true},
  "//Starmie": {"never_catch": true},
  "Goldeen": {"never_catch": true},
  "Drowzee": {"never_catch": true},
  "Spearow": {"never_catch": true},
  "Zubat": {"never_catch": true},
  "Krabby": {"never_catch": true},
  "//Paras": {"never_catch": true},
  "Psyduck": {"never_catch": true},
  "//Pidgeotto": {"never_catch": true}

My problem is that the bot is not following the PokemonGoMap to catch pokemons like
        "Poliwag": 10,
        "Nidoran F": 10,
        "Nidoran M": 10,
        "Clefairy": 15,
        "Bellsprout": 10,
        "Slowpoke": 10,
        "Eevee": 20,
        "Oddish": 20,
and more...

Of course, the 15 pokemons on my never catch list are not the one on my MoveToMapPokemon list.

**Comment by kenkclam** [comment]
Now I enable "enable_social": true, the bot can snipe once in a while.
(does social use my MoveToMapPokemon config to decide max distance and what to snip? Please refer me there if there is any documentation on social)

Yet, it still does not replace MoveToMapPokemon, as I want both walking and sniping to Pokemon.
Any suggestions will be welcome, thanks!

**Comment by sohje** [comment]
if social_enabled bot calculate distance to pokemon from data received from social broker and decide to snip this pok or not

**Comment by kenkclam** [comment]
Thanks @sohje 
I guess you mean the bot with social_enabled will make its own calculation, and that is regardless of my max_sniping_distance setting in MoveToMapPokemon?

how does the bot know which pokemon to snipe?
Does it take the  "snipe_high_prio_threshold" and other settings from my MoveToMapPokemon task?

**Comment by sohje** [comment]
It will compare calculated dist with max_sniping_distance, and also check snipe_high_prio_threshold and other options from MoveToMapPokemon task.

**Comment by ttpeter** [comment]
@kenkclam I'm not very sure about this configuration:
"snipe_high_prio_only": true,
"snipe_high_prio_threshold": 1150,

as my understanding, this config only snipe high priority pokemons with threshold above 1150.
Probably this is why it skipping all

"Poliwag": 10,
"Nidoran F": 10,
"Nidoran M": 10,
"Clefairy": 15,
"Bellsprout": 10,
"Slowpoke": 10,
"Eevee": 20,
"Oddish": 20,

As for my config, I set:
          "snipe_high_prio_only": false,
          "snipe_high_prio_threshold": 1,
It snipe everything.

**Comment by kenkclam** [comment]
@ttpeter 
your understanding is right, but it does not explain my situation. 
This config only snipe high priority pokemons with threshold above 1150. For Pokemon with score less than 1150, the bot will walk to them. Yet, my bot is not walking to the clues :( 

My bot neither snipe or walk to any pokemon, although I see that the map upserts pokemons on localhost and the bot is supposed to walk to them.

**Comment by martixingwei** [comment]
I made a pull request to fix this issue. Basically, in the original code, the bot will not try to walk to any pokemon when `snipe=True`, because the sniping code exit the move_to_map_pokemon worker as success no matter there are pokemons snipped or not.
Your problem is when the bot find snipe is on but no pokemons are qualified for sniping, it simply exit the move_to_map_pokemon worker instead of walking to the next pokemon.

**Comment by martixingwei** [comment]
@solderzzc It does not matter if you closed my pull request. Please resolve this problem.

**Comment by kenkclam** [comment]
Thanks @martixingwei for looking into the code!
Basically now walking to pokemon and sniping to pokemon are not compatible with the current code.
It kinda defeat the purpose of the snipe threshold

**Comment by Nik0lashka** [comment]
@kenkclam may be this will help you https://github.com/PokemonGoF/PokemonGo-Bot/issues/5313#issuecomment-246106364

**Comment by kenkclam** [comment]
@Nik0lashka no, mine is a different issue.
But martixingwei explained the problem. Basically the developer decided that walking and sniping to pokemon are mutually exclusive. If I want my bot to walk to the pokemon, I will have to turn off sniping and social. 
Ideally I would like the bot to snipe to a few rare Pokemon (according to the set threshold), but still walk to the less rare, but still desirable pokemon. Now it is either sniping or walking. It is a weird setting I think, but the developers decided not to change it.

**Comment by Nik0lashka** [comment]
@kenkclam yeah, figured out that social flag is essential here - must be disabled while WALKING to pokemons using pokemongo-map data, "map_path" option doesn't matter here. You are right.

**Comment by YvesHenri** [comment]
I'm closing this as it might have already been fixed. If it isn't, please reopen a new one.
