### ISSUE TITLE
Add more configs / config explantation

### ISSUE THREAD

**Issue by alexanderrock** [PokemonGoF/PokemonGo-Bot#510]
Allow to use the bot with different accounts and different configuration files.
Make also clear which settings in config.json are required and which not, so which can be empty/commented/deleted.

Also what needs to be inserted in release_config.json and how to write in this to not release any pokemon.

In the config.json there's an option "cp" which isn't used any more or?

**Comment by surfaace** [comment]
cp option is moved to release_config.json

**Comment by surfaace** [comment]
not to release any pokemons:
        "release_under_cp": 0,
        "release_under_iv": 0,

**Comment by surfaace** [comment]
you can specify specific configs with pokecli.py --cf yourconfig.json
