### ISSUE TITLE
SybtaxError cath_log event

### ISSUE THREAD

**Issue by MrCarlosJr** [PokemonGoF/PokemonGo-Bot#5103]
### Expected Behavior

Works

### Actual Behavior

```
Traceback (most recent call last):
  File "pokecli.py", line 45, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/home/carlos/Documentos/POKEMON/PokemonGo-Bot/pokemongo_bot/__init__.py", line 625
    self.event_manager.register_event('catch_log')
       ^
SyntaxError: invalid syntax

```

### Other Information
OS: Fedora 24 
 
Branch: dev 
 
Git Commit: 838fea4298b79acfac07447d8328a4672b583667 
 
Python Version: 2.7
 
Any other relevant files/configs (eg: path files)

**Comment by avexus** [comment]
Same here. Did a pit pull, then it won't start.

**Comment by tienthanhdhcn** [comment]
It is some minor problem. You can fix it by doing the following steps:

1. In pokemongo_bot/__init__.py line 623 add ")"
self.event_manager.register_event(
            'save_spawn',
            parameters=('pokemon','location')
)

2. In cell_workers/pokemon_catch_worker.py remove from "<<<<<<< HEAD" to "=======" (line 666 to 699) and remove ">>>>>>> e83c7e6b368ea77849c83eb07281b1e30acd8137" ( conflict). And it will work

**Comment by avexus** [comment]
guess it's no testing before commit

**Comment by avexus** [comment]
@tienthanhdhcn, could you change it and commit back to the dev branch? I think more people will have the same problem.

**Comment by tienthanhdhcn** [comment]
@avexus sorry I cannot have permission to commit to the project :)

**Comment by r3pek** [comment]
yep, have the same problem as of commit 838fea4

**Comment by MrCarlosJr** [comment]
Post here You solution @tienthanhdhcn

**Comment by loflol** [comment]
thanks @tienthanhdhcn 
It's work fine ow

**Comment by oralunal** [comment]
Fixed. You need to pull
