### ISSUE TITLE
[Question] install related, space in dir name won't work.

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#5109]
There is no merge of Windows install and Mac install, so I want to move the whole project to Google drive. IN this case, I can use my Windows at home and still do bot when I go to library with my Mac laptop. And I don't have to change auth and config every time.

I installed in Google Drive directory. However, terminal does not recognize the space between "Google Drive".
I used ... instead of my actual dir name.

$ pip install -r requirements.txt --upgrade
-bash: /Users/.../Google Drive/bot/bin/pip: "/Users/.../Google: bad interpreter: No such file or directory
(bot) xxxxx:bot ...$ pip install -r ./requirements.txt --upgrade
-bash: /Users/.../Google Drive/bot/bin/pip: "/Users/.../Google: bad interpreter: No such file or directory

**Comment by oralunal** [comment]
This is not about Pokemon Go Bot... This is about "PIP" command btw python's problem.. Google for this issue. 

Try to change folders name.
