### ISSUE TITLE
ImportError: No module named pgoapi.exceptions

### ISSUE THREAD

**Issue by MTeres** [PokemonGoF/PokemonGo-Bot#5112]
> (PokemonGo-Bot-master)marcus@marcus-K45VM:~/Transferências/PokemonGo-Bot-master$ ./run.sh
Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetException
ImportError: No module named **pgoapi**.exceptions
Sex Set 2 16:37:19 BRT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

to solve:

**git pull - ok
git submodule update --init --recursive - ok
git submodule foreach git pull origin master - ok
source bin/activate - ok
pip install -r requirements.txt --upgrade - e1
pip install -r requirements.txt** - e1

e1:
  File "..../PokemonGo-Bot-master/bin/pip", line 1
SyntaxError: Non-ASCII character '\xc3' in file ..../PokemonGo-Bot-master/bin/pip on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

when i use:

**git pull - ok
git submodule update --init --recursive - ok
git submodule foreach git pull origin master - ok
source bin/activate - ok
sudo pip install -r requirements.txt --upgrade - alert1
sudo pip install -r requirements.txt** - alert1

alert1:

The directory '..../.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/marcus/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

And the error at ./run.sh continue.

Help?

**Comment by Cephis** [comment]
I've had the same error today.
i've done:
virtualenv .
source bin/activate
pip install -r requirements.txt

and the problem was resolved.

**Comment by MTeres** [comment]
When i try:
(PokemonGo-Bot-master)marcus@marcus-K45VM:~..../PokemonGo-Bot-master$ pip install -r requirements.txt
  File ".../PokemonGo-Bot-master/bin/pip", line 1
SyntaxError: Non-ASCII character '\xc3' in file /home/marcus/Transferências/PokemonGo-Bot-master/bin/pip on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by sohje** [comment]
Dont run pip install as sudo.
Show output of this command:
```shell
cat bin/pip
```

**Comment by MTeres** [comment]
# -*- coding: utf-8 -*-
import re
import sys

from pip import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

**Comment by Huanzhang89** [comment]
I'm having the same issue and my `bin/pip` is the same as MTeres

**Comment by YvesHenri** [comment]
I'm closing this as it might have already been fixed (too old). If it isn't, please reopen a new one.
