### ISSUE TITLE
Incense being used when false

### ISSUE THREAD

**Issue by Bilibox** [PokemonGoF/PokemonGo-Bot#5119]
### Expected Behavior
Don't use Incense when set to false in config

### Actual Behavior
Bot using incense when set to false in config

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/YEHMRMiE

### Output when issue occurred
[2016-09-02 15:43:55] [UseIncense] [INFO] [use_incense] Using Ordinary incense. 8 incense remaining

### Steps to Reproduce
Run bot with Incense false in config

### Other Information
OS: Linux
Branch: Dev
Git Commit: 1cc9da7a79c421f11a4b13359f6a6c1abfcd061a
Python Version: 2.7.12
Any other relevant files/configs (eg: path files) 
config.json

**Comment by sohje** [comment]
Should be fixed with latest commit.
