### ISSUE TITLE
[TelegramClass.connect] Invalid token - typo bug in code

### ISSUE THREAD

**Issue by b4p3p** [PokemonGoF/PokemonGo-Bot#5120]
with last commit i have an issue with TelegramTask

**telegram_token** is in self.config, not in self.bot.config.telegram_token

I modified
`self._tbot = telegram.Bot(self.bot.config.telegram_token)`
in
`self._tbot = telegram.Bot(self.config.get('telegram_token'))`

anyway, please add an exception message in function like this:
```
try:
   self.update_id = self._tbot.getUpdates()[0].update_id
except IndexError:
   self.update_id = None
   logger.error("can't create a telegram bot")
```
and a "seat belt"

```
if self.tbot:
   self.tbot.sendMessage(chat_id=master, parse_mode='Markdown', text=msg)
else:
   print "telegram in null?!!?"
```

**Comment by avexus** [comment]
I just downloaded Telegram for my android phone, How can i find the token?
Thank you! first time using this.

**Comment by b4p3p** [comment]
1. Here for create bot and get telegram_token
https://core.telegram.org/bots#6-botfather

2. Add new bot in telegram chat

3. Ask a telegram your chat_id (aka master in config.json)
https://api.telegram.org/bot<token>/getUpdates

4. Set master and token_id in config.json

5. if you wont add a custom methods for bot, add these in telegram_handler.py like this:
```
...
elif event == 'bot_start':
   msg = "ok...stay sitting. I'm going to play"
...
```

good luck friend! :D

**Comment by avexus** [comment]
Just got my token. But I cannot find my chat_id. I tried /getUpdates command.

**Comment by DBa2016** [comment]
you need to set "master" to either a numeric value (-> I don't know how to find out the correct value...), or to "@username" (which starts to send notifications after you sent the initial "/info" to the bot).

If this does not work still, post your config (use pastebin or similar, please) and I will look into this.

**Comment by Gobberwart** [comment]
To get the numeric value, just send a message to the bot and it will write to the log output something like "message received from username (userid): messagetext". 

You can also send a message to @get_id_bot in Telegram and it will tell you your id.

**Comment by brkskn28** [comment]
para çekme işlemi yapacağım ama üyelığımı onaylamam gerekıyormus  canlı destek cevap vermıyor nasıl yapabılırım

**Comment by sameer043** [comment]
Token please

**Comment by mhamadaram270-cell** [comment]
07722135185

**Comment by shivambali911-rgb** [comment]
WhatsApp login code 9149306641

**Comment by amd374068-creator** [comment]
Token please
