### ISSUE TITLE
[guide] setup telegram push notification for bot

### ISSUE THREAD

**Issue by lntn** [PokemonGoF/PokemonGo-Bot#5150]
It took me a while to Google this out so I am going to put it here, hoping it may benefit other people.

If you have not known, currently the bot has already implemented Telegram notification. The reason why you are still not able to receive anything from the `alert_catch` option is you have not told the bot which Telegram account it should send the message to. This is where the "master" option come in.

As the instruction says, you need to enter your chat ID into that `master` option.

In order to find out your chat ID, open Telegram app, find the **@get_id_bot** bot. Once found you can ask `\my_id` and you will get it.

That's it, put the ID into `master` option and cross your finger.

P.S. the bot does inform you on newly hatched pokemons, not only the new catches.

**Comment by avexus** [comment]
Thank you. Now I can talk both ways.

**Comment by Gobberwart** [comment]
Note also that the bot will display a log message like:

`[2016-09-04 06:55:31] [MainThread] [PokemonGoBot] [INFO] message from USERNAME (USERID): MESSAGETEXT`

whenever a message is received. You can just grab your ID from there.

**Comment by oralunal** [comment]
Please make a PR and update configuration file ;)
