### ISSUE TITLE
incense [bug]

### ISSUE THREAD

**Issue by askovpen** [PokemonGoF/PokemonGo-Bot#5151]
now dev-branch only use incense, but not check incense-pokemons on map.
to check incense-pokemons around trainer, need use 'GetIncensePokemonMessage' method.

**Comment by askovpen** [comment]
maybe self.bot.api.get_incense_pokemon

**Comment by askovpen** [comment]
@davidakachaos @sohje

**Comment by askovpen** [comment]
and need check if incense active

**Comment by davidakachaos** [comment]
I'll give it a shot :-)
