### ISSUE TITLE
After installation, do we still need pgoapi source?

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#5159]
I checked my src dir, and found pgoapi is there.
there is also another file: pip-delete-this-directory
which indicate that this directory should be deleted.

**Comment by th3w4y** [comment]
Yes you do need them!

When you do pip install -r requirements

What pip does regarding the `-e git+https://github.com/joelgreen/pgoapi.git/@fa49ada8570b0817c5a73b9315ba010fa7a47874#egg=pgoapi` is to git clone the repo to src/pgoapi and to create a .egg-link file  `lib/python2.7/site-packages/pgoapi.egg-link`  (relative to your python installation) which`s content is  the location of that checkout.

Removing src/pgoapi will break the bot!

**Comment by th3w4y** [comment]
if you wan to have that in some other location... 
play around with pip parameters 
[quick hack i can think is the  '--src' parameter]
