### ISSUE TITLE
Never been banned for now

### ISSUE THREAD

**Issue by LUCKASSs** [PokemonGoF/PokemonGo-Bot#5167]
Hello guys and sorry for my bad English 
I would like to share my experience with the bot, so I installed the bot on my Raspberry Pi 3 with Ubuntu Mate, and I use the bot for three weeks for now on 2 differents account, the first account is my "official" account and I set the coordinate at a short walk of my home, and my second I set the coordinate in central park 
My first account is now lvl 15 and the second is now 25. 
And for now I never been banned. Even with the bot working an entire night. 
(I use the config 6 (pokemon) and I set true on "evolve Pokemon")

**Comment by oralunal** [comment]
Please use slack server.
