### ISSUE TITLE
Bot Is Moving SUPER-FAST

### ISSUE THREAD

**Issue by oralunal** [PokemonGoF/PokemonGo-Bot#5168]
### Expected Behavior
My speed should be between 2-4 km/h

### Actual Behavior
It's like flying, He moved 270 meters in 5 secs :)

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/Y3McgMeg

### Output when issue occurred
http://pastebin.com/XkVLPfv1

### Other Information
OS: Windows 10
Branch: dev
Git Commit: 847c45bca3fa8244e00ab418308495b52b54436f
 
Python Version: Python 2.7.12

**Comment by Anakin5** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/pull/5169

**Comment by th3w4y** [comment]
@oralunal  that is because the StepWalker does not sleep if 

`if (self.dLat == 0 and self.dLng == 0) or self.dist < self.speed:`

i added sleep(1) to that in https://github.com/PokemonGoF/PokemonGo-Bot/pull/5169

**Comment by th3w4y** [comment]
just worth mentioning not only the Polyline walker would have been affected by this... but all tasks.. at the last step....

**Comment by oralunal** [comment]
This is occured in Polyline.. Now I passed to stepwalker and there is problem about speed calculation..

```
[2016-09-04 12:44:31] [MoveToFort] [INFO] Moving towards pokestop Vişnelik Küçük Park - 315.53m
[2016-09-04 12:44:37] [MoveToFort] [INFO] Moving towards pokestop Vişnelik Küçük Park - 300.66m
[2016-09-04 12:44:42] [MoveToFort] [INFO] Moving towards pokestop Vişnelik Küçük Park - 285.04m
[2016-09-04 12:44:48] [MoveToFort] [INFO] Moving towards pokestop Vişnelik Küçük Park - 270.33m
```

With this log my speed is 10 km/h.. But it should be max 4.16 km/h..

**Comment by th3w4y** [comment]
is m/s not km/h

**Comment by macio525** [comment]
4.16km/h= ~1.2m/s

**Comment by th3w4y** [comment]
@macio525: speed is calculated in m/s not km/h

**Comment by oralunal** [comment]
@th3w4y exactly. If you take a look to my config file you'll see this:
```
    "walk_max": 4.16,
    "walk_min": 2.16,
```
So, there is something wrong.

**Comment by macio525** [comment]
4.16m/s in config, right?

**Comment by oralunal** [comment]
No, walk_max and walk_min values are km/h

**Comment by macio525** [comment]
"Set the maximum walking speed (1 is about 1.5km/hr)"

**Comment by th3w4y** [comment]
@oralunal where is this written? that the speed are in km/h? everywhere in the code calculations and all are in m/s

**Comment by oralunal** [comment]
@th3w4y as @macio525 mentioned it's written in configuration https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/configuration_files.md

**Comment by th3w4y** [comment]
@oralunal documentation is incorrect then.. it always has been m/s check even the master code..

**Comment by th3w4y** [comment]
@oralunal 

Nr of steps was distance/speed

`self.steps = (self.dist + 0.0) / (self.speed + 0.0)`

we had steps of one second because of the sleep(1)
```
        sleep(1)  # sleep one second plus a random delta
        # self._work_at_position(
        #     self.initLat, self.initLng,
        #     alt, False)
```

**Comment by th3w4y** [comment]
@oralunal this we have self.dist in meter decided per "self.speed" and step was one second this makes it m/s

**Comment by th3w4y** [comment]
I will update the documentation https://github.com/PokemonGoF/PokemonGo-Bot/commit/3259fb660d19276ef26427435f655f85cc0ed61d

**Comment by mjmadsen** [comment]
Walking speed is an empirical number - not a real world unit.

**Comment by mjmadsen** [comment]
arbitrary is probably a better word.

**Comment by th3w4y** [comment]
@mjmadsen it kinda is a real unit is m/s

the distance variance depending on where in the world is very very small not even worth mentioning... will maybe same more confusion...

**Comment by th3w4y** [comment]
@mjmadsen  or...

do we still waist lot of time in bot.heartbeat()??

**Comment by mjmadsen** [comment]
I'm not sure atm

**Comment by th3w4y** [comment]
@mjmadsen if we do.. then every second spent then make the real speed smaller...

**Comment by th3w4y** [comment]
but if i am to infer from @oralunal comment regarding 10km/h i'd guess we don't spend much time in bot.heartbeat() otherwise we will not see that speed...

**Comment by mjmadsen** [comment]
def heartbeat(self):
        if self.config.health_record:
            current_time = time.time()
            if current_time - self.heartbeat_wait > self.last_heartbeat:
                self.last_heartbeat = current_time
                self.track_url('/heartbeat')

That doesn't do what I expected :smile: I thought we had some timing bits in here.

**Comment by mjmadsen** [comment]
Why are we even calling that from tasks and walkers? Should be in our core loop

**Comment by th3w4y** [comment]
@mjmadsen it has a 10seconds threadsholt at least... thus runs every 10 sec...

**Comment by mjmadsen** [comment]
I assumed since we were calling it in so many files it was a timing element. Guess that's why you shouldn't assume right? :smile:

**Comment by th3w4y** [comment]
@mjmadsen the one you were mentioning is a different heartbeat...
`
health_record.heartbeat()`

**Comment by th3w4y** [comment]
@oralunal @mjmadsen let's get https://github.com/PokemonGoF/PokemonGo-Bot/pull/5169 merge to fix this issues...

**Comment by mjmadsen** [comment]
Oh I see it now. Duh!

**Comment by mjmadsen** [comment]
Merged

**Comment by kureijir** [comment]
I had my max and min speed set to 6 and 5 respectively before and it ran just fine. Updated today and realized that the bot move too fast, so I tuned down max speed to 3 and min speed to 2.5, yet it's still a little faster than before.

**Comment by th3w4y** [comment]
what do you guys think...
shall we  bailout with a message say if average min-max > 4 ?
