### ISSUE TITLE
-if not working properly 

### ISSUE THREAD

**Issue by vanrzuf** [PokemonGoF/PokemonGo-Bot#517]
### Expected Behavior
recycles selected items after spinning pokestop

### Actual Behavior
recycles pokeballs

### Steps to Reproduce
run bot with `-if ["101","102","103","104"]` (potions id)

### Other Information
OS: debian wheezy
Git Commit: 002dd59b75bc1cfb14d1e86d06e635774757203e

**Comment by hawx07** [comment]
did u find the solution

**Comment by jdinh1** [comment]
Can also confirm this. Passed in [\"101\",\"102\",\"103\",\"104\",\"201\"] but bot recycle pokeballs instead.

> 2016-07-23 20:04:28 [+] Loot:
2016-07-23 20:04:28 [+] 50 xp
2016-07-23 20:04:28 [+] 2x Pokeball
2016-07-23 20:04:28 [+] Recycling 2x Pokeball...
2016-07-23 20:04:28 [+] Recycling success
2016-07-23 20:04:28 [+] 1x Greatball
2016-07-23 20:04:28 [+] Recycling 1x Greatball...
2016-07-23 20:04:29 [+] Recycling success

**Comment by budi-khoirudin** [comment]
Please verify my pull request #543 , to fix this issue

**Comment by skydrome** [comment]
@budi-khoirudin its not removing anything now

**Comment by jdinh1** [comment]
@budi-khoirudin Also confirmed not removing any of the items that were passed into the command line

**Comment by skydrome** [comment]
@budi-khoirudin edited my comment above, it seems just to be removing super potion.

**Comment by budi-khoirudin** [comment]
How you use it? you must use like this => -if "101,102,103,104,201" , it's working properly below is the output not only super potion, in here example revive too

> 2016-07-24 08:28:33 [#] Now at Pokestop: mushola al hidayah vip - Spinning...
2016-07-24 08:28:36 [+] Loot:
2016-07-24 08:28:36 [+] 50 xp
2016-07-24 08:28:36 [+] 2x Revive (Total: 4)
2016-07-24 08:28:36 [+] Recycling 2x Revive...
2016-07-24 08:28:37 [+] Recycling success
2016-07-24 08:28:37 [+] 1x Pokeball (Total: 55)
[2016-07-24 08:28:37] [#] PokeStop on cooldown. Time left: 4.95 minutes

**Comment by skydrome** [comment]
@budi-khoirudin ah yes forgot to remove the brackets, its working now, cheers!

**Comment by vanrzuf** [comment]
@budi-khoirudin just copy pasted this from manual. Will try without brackets

**Comment by SpaceBoris** [comment]
python pokecli.py -a google -u user -p pass -l "x.y" -w 4 -if "101,102,103,104,201"
tried this. Still recycling pokeballs.

**Comment by vanrzuf** [comment]
Without brackets works to me.

**Comment by dmateusp** [comment]
I'm the one that added the feature, tested with ["101", "102", "103"] in the config json file, I will now test it on the cmd line and convert "101,102,103" to an array! Sorry about that

**Comment by ayozebarrera** [comment]
Having this issue aswell

**Comment by surfaace** [comment]
will be fixed in #638
