### ISSUE TITLE
Sleep not triggered if bot launched during a scheduled sleep interval

### ISSUE THREAD

**Issue by Matttter** [PokemonGoF/PokemonGo-Bot#5171]
### Expected Behavior

Sleep schedule should be triggered regardless if the bot is launched during a sleep schedule or not.

### Actual Behavior

If I have a sleep schedule configured from 7 to 10 and launch the bot during that timeframe, the sleep doesn't get triggered.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

Not relevant.

### Steps to Reproduce

Configure sleep, do ./run.sh during a sleep timeframe

### Other Information
OS: debian
Branch:  dev
Git Commit: 37a11099ba1b2430febcc1c98570dd638e61b31a
Python Version:  Python 2.7.9

**Comment by rawgni** [comment]
@solderzzc don't think the merge fix the sleep schedule.
```
  "sleep_schedule": [
    {
      "time": "12:00",
      "duration": "5:30",
      "time_random_offset": "00:30",
      "duration_random_offset": "00:30",
      "wake_up_at_location": ""
    },
    {
      "time": "17:00",
      "duration": "12:00",
      "time_random_offset": "00:00",
      "duration_random_offset": "00:00",
      "wake_up_at_location": ""
    }
  ],
```
`[2016-09-05 00:06:52] [MainThread] [SleepSchedule] [INFO] Next sleep at 11:48:19, for a duration of 5:21:24`

The bot should be sleeping now.

**Comment by cmezh** [comment]
@rawgni According to your config it shouldn't sleep at 00:06.

**Comment by cmezh** [comment]
@rawgni Also bot will not sleep if it is less than 10 minutes to sleep time (with random offset applied).

**Comment by rawgni** [comment]
@cmezh i have it set to sleep from 5pm for 12 hours (5pm - 5am). So, shouldn't it be sleeping if it's 12am?

**Comment by mjmadsen** [comment]
This should be something we can enable / disable. Was having the same problem. Was able to force it to skip by setting:
duration": "0:00",
