### ISSUE TITLE
Skip ignored "Pokemon" spamming log.

### ISSUE THREAD

**Issue by maxprzemo** [PokemonGoF/PokemonGo-Bot#5174]
### Actual Behavior
![zrzut ekranu z 2016-09-04 11 13 47](https://cloud.githubusercontent.com/assets/4314537/18230873/f111ba94-72a8-11e6-813b-fb73ec196878.png)

![zrzut ekranu z 2016-09-04 14 56 06](https://cloud.githubusercontent.com/assets/4314537/18231126/2c0985c6-72b0-11e6-90e1-ffd877fa3cb1.png)

Skip ignored "Pokemon" spamming log.
Blocks the movement bots.
Sends too many requests to the server? I am not sure about that.
Softban to pokestop?
![zrzut ekranu z 2016-09-04 14 24 06](https://cloud.githubusercontent.com/assets/4314537/18230958/f48249f8-72aa-11e6-9d6e-c8d2cb5d9a23.png)
![zrzut ekranu z 2016-09-04 14 24 17](https://cloud.githubusercontent.com/assets/4314537/18230959/f7eb0030-72aa-11e6-88cf-893bc57a7977.png)

### Expected Behavior
Ignore pokemon only once.

### config.json
I have very little Pokeballs, That's why I use this restriction:
    },
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "Pidgey": {"catch_above_cp": 300, "catch_above_iv": 0.8, "logic": "or"},
      "Rattata": {"catch_above_cp": 300, "catch_above_iv": 0.8, "logic": "or"},
      "Drowzee": {"catch_above_cp": 300, "catch_above_iv": 0.8, "logic": "or"},
      "Spearow": {"catch_above_cp": 300, "catch_above_iv": 0.8, "logic": "or"},
      "Pidgeotto": {"catch_above_cp": 100, "catch_above_iv": 0.8, "logic": "or"},
      "Zubat": {"catch_above_cp": 300, "catch_above_iv": 0.8, "logic": "or"},
      "Raticate": {"catch_above_cp": 300, "catch_above_iv": 0.8, "logic": "or"},
      "Krabby": {"catch_above_cp": 100, "catch_above_iv": 0.8, "logic": "or"},
      "Gastly": {"catch_above_cp": 100, "catch_above_iv": 0.8, "logic": "or"},
      "Hypno": {"catch_above_cp": 100, "catch_above_iv": 0.8, "logic": "or"},
      "// Rattata": { "always_catch" : true }
    },

### Other Information
OS: 
Debian 8.5 
Branch: 
master

**Comment by kenkclam** [comment]
I also ignore a lot of pokemons with "never_catch" : true.
Indeed, my log is full of the ignore message.
But I was never softbanned. 
I believe the bot tells you that it "see" the pokemon but will ignore it. I doubt if there is any request sent to the server. I guess your softban is bc of something else.
I am fine with my log being jammed with the repeated "ignore" messages. If you are annoyed, maybe you can request for a feature to turn that message off from the log.

**Comment by Gobberwart** [comment]
Looks like it should be an easy fix. Looking at it now.

**Comment by Gobberwart** [comment]
I take that back. Doesn't appear to be any sort of unique identifier for an encountered pokemon, so will need to build some sort of list of attributes to compare. Sorry, don't really have time for that right now.

**Comment by Gobberwart** [comment]
And I take that back too. PR to follow in a minute :)

**Comment by Gobberwart** [comment]
#5197 merged. Closing.
