### ISSUE TITLE
-c not available?

### ISSUE THREAD

**Issue by sarandafl** [PokemonGoF/PokemonGo-Bot#518]
### Expected Behavior
Release all Pokemon with a CP lower than x `-c x`

### Actual Behavior
```
usage: pokecli.py [-h] -a AUTH_SERVICE [-u USERNAME] [-p PASSWORD]
                  [-l LOCATION] [-lc LOCATION_CACHE] [-m MODE] [-w WALK]
                  [-k GMAPKEY] [-ms MAX_STEPS] [-it INITIAL_TRANSFER]
                  [-d DEBUG] [-t TEST] [-du DISTANCE_UNIT] [-if ITEM_FILTER]
pokecli.py: error: unrecognized arguments: -c 200
```

### Steps to Reproduce
Run with -c argument.

**Comment by CasBroad** [comment]
The CP is now set in the release_config.json

**Comment by gerbilsinspace** [comment]
For more information about this, if you look at the root directory of the codebase, you will see release_config.json. Inside the file, you will see min_cp and min_iv. If you want all pokemon that are under 100cp to be traded in? set your minimum to 100. The same goes for min_iv, set that to a decimal between 0 and 1. 

WARNING: There was a bug that ignored your cp. A workaround is to set -iv to 0 in the command line.

**Comment by solderzzc** [comment]
README.me updated. Let's close this topic.
