### ISSUE TITLE
Polylinewalker is still drunk

### ISSUE THREAD

**Issue by orchid666** [PokemonGoF/PokemonGo-Bot#5186]
I noticed a few days ago that , on the DEV branch, the polylinewalker stopped working smoothly.
Even after today's modification, it still has the "drunk" type of walking.
![poly](https://cloud.githubusercontent.com/assets/10350351/18232958/776518ec-72a0-11e6-94cb-5ce4ff9a06ee.jpeg)

Any idea what's going on?

**Comment by maxprzemo** [comment]
In the file config.json remove lines
      {
        "type": "FollowSpiral",
        "config": {
          "enabled": true,
          "diameter": 4,
          "step_size": 70
        }
      }
I use the method "Follow Path" working as it should
![zrzut ekranu z 2016-09-04 21 10 53](https://cloud.githubusercontent.com/assets/4314537/18233298/907141c4-72e3-11e6-9753-2adc02aba406.png)

**Comment by orchid666** [comment]
I removed followspiral and now polyline is working nicely. Aren't they supposed to work well together? It was the case last week.

**Comment by th3w4y** [comment]
@orchid666 no they are not of course...
they give conflicting directions....

**Comment by th3w4y** [comment]
One one task should use the PolylineWalker if you want consistent results..

**Comment by Gobberwart** [comment]
Fixed: Told Polylinewalker to go home and sleep it off :)

**Comment by orchid666** [comment]
Well kind of, it puked all over the couch.

**Comment by mjmadsen** [comment]
@th3w4y maybe we should disable it in the config by default (instead of deleting it).

**Comment by th3w4y** [comment]
@mjmadsen I do believe we are very close to that moment... 

There are still some issues when multiple tasks call step walker..
We have so many follow BaseTask and each call their StepWalwer as they please!

**Comment by th3w4y** [comment]
@orchid666 is this still a problem for you ?

**Comment by orchid666** [comment]
@th3w4y you mean polyline + spiral?

**Comment by th3w4y** [comment]
@orchid666 i mean Polyline without spiral

(In my opinion Spiral should be deprecated!)

**Comment by orchid666** [comment]
Polyline without spiral always worked for me.  Polyline with spiral used to work nicely then it stopped working so i wanted to bring that issue, but apparently it's something planned so i guess thats fine.

**Comment by Gobberwart** [comment]
Currently using MoveToFort with polyline and it looks a lot less wobbly. Guess it sobered up a little.

**Comment by th3w4y** [comment]
@Gobberwart is only with spiral that would be messed up
