### ISSUE TITLE
Pokemon transfer? crashes

### ISSUE THREAD

**Issue by slysamdogs** [PokemonGoF/PokemonGo-Bot#5191]
Expected Behavior

Pokemon to transfer when Pokemon bag is full.

Actual Behavior

Whenever my Pokemon bag gets to 245/250, it will crash after every Pokemon it catches and does not release any.

Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/HyXizCFc

Output when issue occurred

When the bot crashes, everything appears normal until this - http://pastebin.com/V6GRKZje

Steps to Reproduce

Simply restarting the bot recreates this crash, because the Pokemon bag is still full. I have gone into the app and transferred ~20 Pokemon to see if it was just a hiccup where it did not initiate the transfer process, but the same crash happened again.

Other Information

OS: Mac (El Capitan)

Branch: master

Git Commit:

Python Version:

Any other relevant files/configs (eg: path files)

Short Description

Possible solution

How it would help others

**Comment by Anakin5** [comment]
Can you tell me if you have any Eevee or one of its evolution in your bag ?

**Comment by shudack** [comment]
It's happen to me too...

**Comment by slysamdogs** [comment]
Yes, I have three Vaporeon

**Comment by Anakin5** [comment]
I see the issue, will commit something to fix.

**Comment by oralunal** [comment]
Is the issue continue?

**Comment by shudack** [comment]
Yes, the issue continue. When pokemon bag is full, don't transfer any pokemon..

**Comment by Anakin5** [comment]
@shudack The issue was about a crash, not about pokemon not transferring. What is the error you have ?

**Comment by shudack** [comment]
@Anakin5 No erros, only have message Pokemon bag is full, can't catch more pokemons..

**Comment by Anakin5** [comment]
It is a config issue, need to see your config.

**Comment by Tuutti3** [comment]
I have the same problem, bag is full, but bot doesnt transfer any.
Here is the config http://pastebin.com/mszShmbB

**Comment by Anakin5** [comment]
@Tuutti3 Your issue is not related and your config is wrong. Check your release settings...

**Comment by Tuutti3** [comment]
@Anakin5 Whoops, thanks.
