### ISSUE TITLE
[FEATURE REQUEST] Dratini is missing on the list

### ISSUE THREAD

**Issue by thejamespinto** [PokemonGoF/PokemonGo-Bot#5196]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/configs/config.json.pokemon.example#L288

Node "release" contains 150 Pokemon, it includes **Mew** and is missing **Dratini**.

**Dragonite** is such a good pokemon I also recommend including **Dratini** on node "catch".

I would do this myself, but I trust there are people better qualified to choose lines and wording.

I would also like to see a special space under "catch" and "release" saying `"// Personal": {}` so as to encourage people to add their customizations and ultimately improve the example files as well.

Thank you for maintaining this project. ❤️ 

PS. Please also include **Greatball** here. https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/configs/config.json.example#L158

**Comment by thejamespinto** [comment]
@solderzzc @TheSavior what do you guys think?

**Comment by oralunal** [comment]
This is not an issue
