### ISSUE TITLE
Walking speed bugged?

### ISSUE THREAD

**Issue by harsh1412** [PokemonGoF/PokemonGo-Bot#52]
So i set the speed -w 4.40 and got this in console
This is PokeStop
distant is 43.8958391159m
need setup the postion to farming fort
((xxx, xxx, 0.0), xxxxxxxxxxxxxxxxxxxxxxxxxxx')
Walking from (xxx, xxx) to (xxx, xxxx) for approx. 95.0sec

If i am correct speed of walking should be low right?

**Comment by douglascamata** [comment]
Can be faster than 4.40 m/s. I'm using 20 m/s, which is equivalent to a can running 100 km/h and it works.

**Comment by holywend** [comment]
Hahaha but 20m/s wont hatch egg isnt it?

**Comment by crack00r** [comment]
yep, if you want to hatch eggs, you can max go 15km/h wich is 4.16

**Comment by harsh1412** [comment]
@crack00r exactly..! then why it was showing 95 seconds? :3

**Comment by LilDice** [comment]
I cant set the walkk speed at all I am using -w 2.2 and it gives error

**Comment by millejosh** [comment]
@LilDice what is the error?

**Comment by holywend** [comment]
im confused I set the walking speed as 4 m/s but this happen

This is PokeStop
distant is 790.359542282m
need setup the postion to farming fort
((52.630008, -1.142752, 0.0), u'1c4bf55a09c642a295e588895401fe5f.16')
Walking from (52.632314, -1.145138) to (52.630008, -1.142752) for approx. 76.0sec

distant is 790.359 while the approx is 76 sec it doesnt make sense coz
790.359 / 76 = 10.4 m/s

different from what I set (4 m/s)

**Comment by LilDice** [comment]
unrecognized arguments: -w 4.16

**Comment by holywend** [comment]
@LilDice perhaps you can try to redownload the zip.

**Comment by LilDice** [comment]
That worked thankyou!

**Comment by tstumm** [comment]
@holywend Your calculations are correct but the distance estimation by the bot itself is wrong so the displayed distance is wrong. The walk routine uses a different distance estimator which is more precise.
