### ISSUE TITLE
How is the atk/def % determined?

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#5205]
Hi, I have a perfect moveset hitmonchan. When I did a nickname, I got:
99% and 78%.
{attack_pct2} and {defense_pct2}

However, from
http://www.pokemongodb.net/2016/05/hitmonchan.html
I got:
Ideal Moveset for Hitmonchan:			
Move:	Rock Smash	Brick Break			
Category:	Fast	Charge			
DPS:	10.6	18.8			
Rank (DPS):	#57	#65			
DPS (w/ STAB):	13.3	23.4			
Rank (w/ STAB):	#23	#39

**Comment by Anakin5** [comment]
perfect moveset for attack or for defense ?

**Comment by Gobberwart** [comment]
No response in 2 days. Closing as this is a question, not an issue.
