### ISSUE TITLE
How to use web ui ?

### ISSUE THREAD

**Issue by lusherlo** [PokemonGoF/PokemonGo-Bot#5209]
### Other Information
OS: 
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by Darkayer** [comment]
Can you provide a little bit more information according to your question?
What is the problem you're running in to?

**Comment by lusherlo** [comment]
sorry I am a newbie .?
How to start web UI bot in linux

**Comment by KingTheRipper** [comment]
Hi newbie ;P

First you have to install a Simple HTTP server here: 
http://www.tecmint.com/python-simplehttpserver-to-create-webserver-or-serve-files-instantly/

After that setup your config file in a WEB folder > config > userdata.js.example (Clone and remove .example):

```
var userInfo = {
	users: ["YOUR_USER_NAME_HERE"],
	userZoom: true,
	zoom: 16,
	userFollow: true,
	gMapsAPIKey: "YOUR_API_KEY_HERE"
};
```
Open your terminal and send a commad:

```
cd PokemonGo-Bot/web
python -m SimpleHTTPServer
```

Open up your browser to http://localhost:8000/

and Enjoy!

**Comment by avexus** [comment]
@KingTheRipper I am new to this too. After following your instruction, I got this:
code 404, message File not found
"GET /Catchable-xxx.json HTTP/1.1" 404
error. I don't know how to copy the message from my cmd on Windows to here

**Comment by Darkayer** [comment]
Is your bot allready Running?? Normally the bot should make 3 files in your /web directory. location-USERNAME.json, catchable-USERNAME.json and inventory-USERNAME.json. Did you fill in the right username in the userdate.json file?

**Comment by BarrieG14** [comment]
I am getting a similar error:  
Serving HTTP on 0.0.0.0 port 8000 ...
127.0.0.1 - - [05/Sep/2016 20:34:01] "GET /config/userdata.js HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2016 20:43:06] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2016 20:43:06] "GET /config/userdata.js HTTP/1.1" 200 -
127.0.0.1 - - [05/Sep/2016 20:43:22] "GET / HTTP/1.1" 200 -

My userdata.js has:
var userInfo = {
    users: ["MyName"],
    userZoom: true,
    zoom: 16,
    userFollow: true,
    gMapsAPIKey: "mykey"
};

**Comment by Gobberwart** [comment]
@barrieg14 they're not errors. What you're seeing is a request for a file with a 200 (success) result

**Comment by lytesout2376** [comment]
I'm also having problems getting the web ui to work.  I've followed all of the above instructions.  It seems like the localhost server is serving up the page, however I get a white screen with only one button: "Settings".  When I click on settings I see "Pan", "Zoom", "Bot Path" and "Logs".  The first three have toggle sliders and "Logs" has a "Logs" button in blue.  They react to my clicks but nothing happens.   No map and no user menu.  I've had this web ui work in a previous branch before.  I am not sure what is causing this.  Yes userdata.js is filled out including a gmaps key.  I do have catchable, location and inventory (.json).  Any assistance would be appreciated.  Thanks!

**Comment by Gobberwart** [comment]
@lytesout2376 I had this issue after a recent web update and discovered that my userdata.js file was missing (no idea why, it was there before). Make sure you have a file called userdata.js (not userdata.js.example) and that it's correctly filled out.

**Comment by Gobberwart** [comment]
All required information is contained in docs/google_map.md. No need for this "issue" to exist.

**Comment by lusherlo** [comment]
Thanks I will try to do again.

**Comment by lytesout2376** [comment]
I still can't get web ui working.  I have userdata.js properly configured per the google map doc.  I am now wondering if my config.json settings have any effect to my problems. I have the following in my config.son:

	"websocket": {
		"start_embedded_server": true,
		"server_url": "127.0.0.1:4000"
	}

and

    "websocket_server": true,

Here is my userdata.js:

var userInfo = {
 	users: [{
            enable: true,
 	    username: "myPGusername",
 	    socketAddress: "0.0.0.0:4000"
 	},{
            enable: false,
 	    username: "username2",
 	    socketAddress: "0.0.0.0:5000"
 	}],
 	userZoom: false,
 	userPath: true,
 	zoom: 16,
 	userFollow: true,
 	gMapsAPIKey: "myGMAPsKey"
 };

Please help!

**Comment by Gobberwart** [comment]
Try "socketAddress": "127.0.0.1:4000" instead of 0.0.0.0
