### ISSUE TITLE
Make bot compatible with greenlet 0.4.10

### ISSUE THREAD

**Issue by AhiruDuck** [PokemonGoF/PokemonGo-Bot#5213]
### Expected Behavior
bot to run

### Actual Behavior
bot doesn't run on Mac OS X 10.8.5 with greenlet 0.4.9, used to work with 0.4.10 (updating manually after setup.sh / install requirements)
before the last updates, the bot ran just fine.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
N/A

### Output when issue occurred
if installed 0.4.10 - "Some of the required packages are not found / have different version."

if running 0.4.9 - 
Traceback (most recent call last):
  File "pokecli.py", line 45, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/Users/Ahiru/PokemonGo-Bot/pokemongo_bot/__init__.py", line 33, in <module>
    from pokemongo_bot.socketio_server.runner import SocketIoRunner
  File "/Users/Ahiru/PokemonGo-Bot/pokemongo_bot/socketio_server/runner.py", line 5, in <module>
    from eventlet import patcher, wsgi
  File "/Users/Ahiru/PokemonGo-Bot/lib/python2.7/site-packages/eventlet/patcher.py", line 4, in <module>
    from eventlet.support import six
  File "/Users/Ahiru/PokemonGo-Bot/lib/python2.7/site-packages/eventlet/support/__init__.py", line 4, in <module>
    from eventlet.support import greenlets, six
  File "/Users/Ahiru/PokemonGo-Bot/lib/python2.7/site-packages/eventlet/support/greenlets.py", line 3, in <module>
    import greenlet
ImportError: dlopen(/Users/Ahiru/PokemonGo-Bot/lib/python2.7/site-packages/greenlet.so, 2): Symbol not found: __PyTrash_thread_deposit_object
  Referenced from: /Users/Ahiru/PokemonGo-Bot/lib/python2.7/site-packages/greenlet.so
  Expected in: flat namespace
 in /Users/Ahiru/PokemonGo-Bot/lib/python2.7/site-packages/greenlet.so
Seg 5 Set 2016 08:08:31 BRT Pokebot  Stopped.

### Steps to Reproduce
run .setup.sh -u
then run pip install greenlet --update
(to update from 0.4.9 to 0.4.10, otherwise the bot wouldn't run)

### Other Information
OS: OS X 10.8.5

Branch: dev

Git Commit: f60a2ecc564d9728863073a5ead56b9ee2c35a52

Python Version: 2.7.2

Any other relevant files/configs (eg: path files) 
greenlet 0.4.10

**Comment by rawgni** [comment]
Try
```
pip install greenlet --update
python pokecli.py
```

**Comment by AhiruDuck** [comment]
@rawgni thank you! 
was trying via run.sh - gonna edit the script then! thanks again!
