### ISSUE TITLE
How long have you boted? and what lvl should you stop?

### ISSUE THREAD

**Issue by perpysling2** [PokemonGoF/PokemonGo-Bot#5215]
Wonder when i should turn the bot of? when do people get banned?

**Comment by perpysling2** [comment]
soon i reach lvl 30

**Comment by davidspeijer** [comment]
I use several accounts; bot 1 to lvl 20, another to 25, now 1 to 30, hereafter i will bot the 20 to 35 and so on.... If one get banned not all is lost...

**Comment by DBa2016** [comment]
This is not really an "issue", is it? Join Slack, discuss it there...

**Comment by perpysling2** [comment]
do people bot multiple users on the same ip at the same time?

**Comment by sohje** [comment]
Join slack and discuss :octocat:
