### ISSUE TITLE
ImportError: No module named pgoapi.exceptions / pokecli.py

### ISSUE THREAD

**Issue by LeO-Fr** [PokemonGoF/PokemonGo-Bot#5220]
./run.sh: line 16: bin/activate: No such file or directory
Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetException
ImportError: No module named pgoapi.exceptions
Mon Sep 5 16:56:41 UTC 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

Whait I should do? That appens when I launch the bot with ./run.sh , I have do the auto installation correctly. (I'm on raspbian)
Thx for help

**Comment by robertpro** [comment]
On raspbian I always install requirements.txt as root, it is a work around for some problems...

and then I ran python pokecli.py ...

**Comment by LeO-Fr** [comment]
Yeah I just install as root, it's works now, thx
