### ISSUE TITLE
Why does it keep showing connection pool error?

### ISSUE THREAD

**Issue by philzeey** [PokemonGoF/PokemonGo-Bot#5221]
### Expected Behavior
Not giving an error.

### Actual Behavior
The program still works, but it gives me a ton of connection pool errors like shown below, just curious as to why?

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
{
  "auth_service":"google",
  "username":"x",
  "password":"x",
  "location":"x",
  "favorite_locations":[
      {"name": "x",
       "name": "x"}
  ],
  "gmapkey":"x",
  "encrypt_location":"",
  "websocket_server":false,
  "heartbeat_threshold":10,
  "enable_social":true,
  "live_config_update":{
    "enabled":true,
    "tasks_only":false
  },
  "tasks":[
    {
      "//NOTE: This task MUST be placed on the top of task list":{

      },
      "type":"RandomAlivePause",
      "config":{
        "enabled":false,
        "min_duration":"00:00:10",
        "max_duration":"00:10:00",
        "min_interval":"00:05:00",
        "max_interval":"01:30:00"
      }
    },
    {
      "type":"TelegramTask",
      "config":{
        "enabled":true,
        "master":"@Philzeey",
        "alert_catch":{
          "all":{
            "operator":"or",
            "cp":1000,
            "iv":0.9
          },
          "Lapras":{
            "operator":"or",
            "cp":0,
            "iv":0.0
          },
          "Moltres":{
            "operator":"or",
            "cp":0,
            "iv":0.0
          },
          "Zapdos":{
            "operator":"or",
            "cp":0,
            "iv":0.0
          },
          "Articuno":{
            "operator":"or",
            "cp":0,
            "iv":0.0
          },
          "Mewtwo":{
            "operator":"or",
            "cp":0,
            "iv":0.0
          },
          "Dragonite":{
            "operator":"or",
            "cp":0,
            "iv":0.0
          },
          "Mew":{
            "operator":"or",
            "cp":0,
            "iv":0.0
          },
          "Exeggutor":{
            "operator":"or",
            "cp":0,
            "iv":0.0
          },
          "Weezing":{
            "operator":"or",
            "cp":0,
            "iv":0.0
          },
          "Porygon":{
            "operator":"or",
            "cp":0,
            "iv":0.0
          },
          "Kangaskhan":{
            "operator":"or",
            "cp":0,
            "iv":0.0
          },
          "Mr. Mime":{
            "operator":"or",
            "cp":0,
            "iv":0.0
          },
          "Farfetch'd":{
            "operator":"or",
            "cp":0,
            "iv":0.0
          },
          "Ditto":{
            "operator":"or",
            "cp":0,
            "iv":0.0
          }
        }
      }
    },
    {
      "type":"HandleSoftBan"
    },
    {
      "type":"CompleteTutorial",
      "config":{
        "enabled":false,
        "// set a name":"",
        "nickname":""
      }
    },
    {
      "type":"CollectLevelUpReward",
      "config":{
        "collect_reward":true,
        "level_limit":-1
      }
    },
    {
      "type":"IncubateEggs",
      "config":{
        "enabled":true,
        "infinite_longer_eggs_first":true,
        "breakable_longer_eggs_first":true,
        "min_interval":120
      }
    },
    {
      "type":"UpdateLiveStats",
      "config":{
        "enabled":true,
        "min_interval":10,
        "stats":[
          "uptime",
          "stardust_earned",
          "xp_earned",
          "xp_per_hour",
          "stops_visited"
        ],
        "terminal_log":false,
        "terminal_title":true
      }
    },
    {
      "type":"UpdateLiveInventory",
      "config":{
        "enabled":true,
        "min_interval":120,
        "show_all_multiple_lines":true,
        "items":[
          "pokemon_bag",
          "space_info",
          "pokeballs",
          "greatballs",
          "ultraballs",
          "razzberries",
          "luckyegg"
        ]
      }
    },
    {
      "type":"ShowBestPokemon",
      "config":{
        "enabled":true,
        "min_interval":60,
        "amount":5,
        "order_by":"cp",
        "info_to_show":[
          "cp",
          "ivcp",
          "dps",
          "hp"
        ]
      }
    },
    {
      "type":"TransferPokemon",
      "config":{
        "enabled":true,
        "min_free_slot":15,
        "transfer_wait_min":3,
        "transfer_wait_max":5
      }
    },
    {
      "type":"NicknamePokemon",
      "config":{
        "enabled":true,
        "nickname_above_iv":0.9,
        "nickname_template":"{id}_{iv_pct}",
        "nickname_wait_min": 3,
        "nickname_wait_max": 5
      }
    },
    {
      "type":"EvolvePokemon",
      "config":{
        "enabled":true,
        "evolve_list":"Pidgey",
        "first_evolve_by":"cp",
        "evolve_above_cp":0,
        "evolve_above_iv":0.0,
        "logic":"or",
        "min_evolve_speed":25,
        "max_evolve_speed":30,
        "use_lucky_egg":false
      }
    },
    {
      "type":"PokemonOptimizer",
      "config":{
        "enabled":false,
        "transfer":false,
        "transfer_wait_min":3,
        "transfer_wait_max":5,
        "evolve":false,
        "evolve_time":25,
        "evolve_for_xp":false,
        "evolve_only_with_lucky_egg":false,
        "evolve_count_for_lucky_egg":80,
        "may_use_lucky_egg":true,
        "upgrade":false,
        "upgrade_level":60,
        "min_slots_left":14,
        "groups":{
          "final":[
            "Dragonite",
            "Snorlax",
            "Lapras",
            "Arcanine",
            "Poliwrath",
            "Venusaur",
            "Charizard",
            "Blastoise",
            "Butterfree",
            "Beedrill",
            "Pidgeot",
            "Raticate",
            "Fearow",
            "Arbok",
            "Raichu",
            "Sandslash",
            "Nidoqueen",
            "Nidoking",
            "Clefable",
            "Ninetales",
            "Wigglytuff",
            "Golbat",
            "Vileplume",
            "Parasect",
            "Venomoth",
            "Dugtrio",
            "Persian",
            "Golduck",
            "Primeape",
            "Alakazam",
            "Machamp",
            "Victreebel",
            "Tentacruel",
            "Golem",
            "Rapidash",
            "Slowbro",
            "Magneton",
            "Farfetch'd",
            "Dodrio",
            "Dewgong",
            "Muk",
            "Cloyster",
            "Gengar",
            "Onix",
            "Hypno",
            "Kingler",
            "Electrode",
            "Exeggutor",
            "Marowak",
            "Hitmonlee",
            "Hitmonchan",
            "Lickitung",
            "Weezing",
            "Rhydon",
            "Chansey",
            "Tangela",
            "Kangaskhan",
            "Seadra",
            "Seaking",
            "Starmie",
            "Mr. Mime",
            "Scyther",
            "Jynx",
            "Electabuzz",
            "Magmar",
            "Pinsir",
            "Tauros",
            "Gyarados",
            "Ditto",
            "Vaporeon",
            "Jolteon",
            "Flareon",
            "Porygon",
            "Omastar",
            "Kabutops",
            "Aerodactyl",
            "Articuno",
            "Zapdos",
            "Moltres",
            "Mewtwo",
            "Mew"
          ]
        },
        "keep":[
          {
            "mode":"by_family",
            "names":[
              "final"
            ],
            "top":1,
            "sort":[
              {
                "iv":0.9
              }
            ],
            "evolve":false,
            "upgrade":true
          }
        ]
      }
    },
    {
      "type":"RecycleItems",
      "config":{
        "enabled":true,
        "min_empty_space":15,
        "max_balls_keep":280,
        "max_potions_keep":0,
        "max_berries_keep":50,
        "max_revives_keep":0,
        "item_filter":{
          "Pokeball": {
            "keep":170
          },
          "Ultraball":{
            "keep":50
          },
          "Lucky Egg":{
            "keep":5
          },
          "Incense":{
            "keep":1
          },
          "Troy Disk":{
            "keep":5
          },
          "Special Camera":{
            "keep":1
          },
          "Incubator (Unlimited)":{
            "keep":1
          },
          "Incubator":{
            "keep":1
          }
        },
        "recycle_wait_min":1,
        "recycle_wait_max":4,
        "recycle_force":true,
        "recycle_force_min":"00:01:00",
        "recycle_force_max":"00:05:00"
      }
    },
    {
      "type":"CatchPokemon",
      "config":{
        "enabled":true,
        "catch_visible_pokemon":true,
        "catch_lured_pokemon":true,
        "min_ultraball_to_keep":5,
        "berry_threshold":0.35,
        "vip_berry_threshold":0.9,
        "daily_catch_limit":800,
        "catch_throw_parameters":{
          "excellent_rate":0.1,
          "great_rate":0.5,
          "nice_rate":0.3,
          "normal_rate":0.1,
          "spin_success_rate":0.6
        },
        "catch_simulation":{
          "flee_count":3,
          "flee_duration":2,
          "catch_wait_min":2,
          "catch_wait_max":6,
          "berry_wait_min":2,
          "berry_wait_max":3,
          "changeball_wait_min":2,
          "changeball_wait_max":3,
          "newtodex_wait_min":20,
          "newtodex_wait_max":30
        }
      }
    },
    {
      "type":"SpinFort",
      "config":{
        "enabled":true,
        "spin_wait_min":3,
        "spin_wait_max":5
      }
    },
    {
      "type":"UpdateWebInventory",
      "config":{
        "enabled":true
      }
    },
    {
      "type":"MoveToMapPokemon",
      "config":{
        "enabled":true,
        "address":"http://localhost:8000",
        "max_sniping_distance":10000,
        "max_walking_distance":1000,
        "min_ball":25,
        "prioritize_vips":true,
        "snipe":true,
        "snipe_high_prio_only":true,
        "snipe_high_prio_threshold":900,
        "update_map":true,
        "mode":"priority",
        "map_path":"raw_data",
        "walker":"StepWalker",
        "max_extra_dist_fort":10,
        "skip_rounds":5,
        "update_map_min_distance_meters":500,
        "update_map_min_time_sec":120,
        "snipe_sleep_sec":2,
        "snipe_max_in_chain":2,
        "debug":false,
        "catch":{
          "==========Legendaries==========":0,
          "Aerodactyl":1000,
          "Snorlax":1000,
          "Articuno":1000,
          "Zapdos":1000,
          "Moltres":1000,
          "Dratini":1000,
          "Dragonair":1000,
          "Dragonite":1000,
          "Mewtwo":1000,
          "Mew":1000,
          "==========Region Locked==========":0,
          "Farfetch'd":1000,
          "Kangaskhan":1000,
          "Mr. Mime":1000,
          "Tauros":1000,
          "==========Very Rare==========":0,
          "Lapras":900,
          "Electabuzz":900,
          "Magmar":900,
          "Ditto":900,
          "==========Starters==========":0,
          "Bulbasaur":400,
          "Ivysaur":600,
          "Venusaur":1000,
          "Charmander":400,
          "Charmeleon":600,
          "Charizard":1000,
          "Squirtle":400,
          "Wartortle":600,
          "Blastoise":1000,
          "Pikachu":600,
          "Raichu":1000,
          "==========Semi Rare==========":0,
          "Porygon":1000,
          "Scyther":200,
          "Jynx":200,
          "==========Uncommon==========":0,
          "Omanyte":150,
          "Omastar":500,
          "Seel":300,
          "Dewgong":500,
          "Grimer":200,
          "Muk":500,
          "Shellder":200,
          "Cloyster":500,
          "Gastly":200,
          "Haunter":500,
          "Gengar":1000,
          "Onix":600,
          "Drowzee":600,
          "Hypno":600,
          "Vulpix":200,
          "Ninetales":600,
          "Paras":100,
          "Parasect":500,
          "Growlithe":200,
          "Arcanine":700,
          "Tentacool":200,
          "Tentacruel":500,
          "Mankey":150,
          "Primeape":500,
          "Clefairy":150,
          "Clefable":500,
          "Jigglypuff":150,
          "Wigglytuff":500,
          "Venonat":100,
          "Venomoth":500,
          "Diglett":200,
          "Dugtrio":500,
          "Meowth":250,
          "Persian":500,
          "Psyduck":150,
          "Golduck":500,
          "Geodude":100,
          "Graveler":500,
          "Golem":800,
          "Eevee":200,
          "Vaporeon":800,
          "Jolteon":800,
          "Flareon":800,
          "Kabuto":150,
          "Kabutops":500,
          "Magikarp":150,
          "Gyarados":1000,
          "Pinsir":150,
          "Ponyta":200,
          "Rapidash":500,
          "Slowpoke":200,
          "Slowbro":500,
          "Magnemite":250,
          "Magneton":500,
          "Krabby":100,
          "Kingler":500,
          "Voltorb":200,
          "Electrode":500,
          "Exeggcute":250,
          "Exeggcutor":1000,
          "Cubone":300,
          "Marowak":800,
          "Hitmonlee":400,
          "Hitmonchan":400,
          "Lickitung":500,
          "Koffing":200,
          "Weezing":1000,
          "Rhyhorn":200,
          "Rhydon":500,
          "Chansey":800,
          "Tangela":1000,
          "Horsea":200,
          "Seadra":600,
          "Goldeen":150,
          "Seaking":500,
          "Staryu":200,
          "Starmie":800,
          "==========T1 Evolvers==========":0,
          "Caterpie":10,
          "Metapod":10,
          "Butterfree":500,
          "Weedle":10,
          "Kakuna":10,
          "Beedrill":500,
          "Pidgey":10,
          "Pidgeotto":10,
          "Pidgeot":300,
          "==========T2 Evolvers==========":0,
          "Nidoran F":10,
          "Nidorina":10,
          "Nidoqueen":10,
          "Nidoran M":10,
          "Nidorino":10,
          "Nidoking":10,
          "Oddish":100,
          "Gloom":200,
          "Vileplume":1000,
          "Poliwag":200,
          "Poliwhirl":400,
          "Poliwrath":800,
          "Abra":300,
          "Kadabra":600,
          "Alakazam":800,
          "Machop":150,
          "Machoke":400,
          "Machamp":800,
          "Bellsprout":100,
          "Weepinbell":400,
          "Victreebel":100,
          "==========Trash==========":0,
          "Rattata":10,
          "Raticate":10,
          "Spearow":10,
          "Fearow":10,
          "Ekans":10,
          "Arbok":10,
          "Sandshrew":10,
          "Sandslash":10,
          "Zubat":10,
          "Golbat":10,
          "Doduo":10,
          "Dodrio":10
        }
      }
    },
    {
      "type":"MoveToFort",
      "config":{
        "enabled":true,
        "lure_attraction":true,
        "lure_max_distance":2000,
        "log_interval":5
      }
    },
    {
      "type":"FollowSpiral",
      "config":{
        "enabled":true,
        "diameter":4,
        "step_size":70
      }
    }
  ],
  "forts":{
    "avoid_circles":true,
    "max_circle_size":50,
    "cache_recent_forts":true
  },
  "pokemon_bag":{
    "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start":{

    },
    "show_at_start":true,
    "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)":{

    },
    "show_count":false,
    "// if 'show_candies' is true, it will show the amount of candies for each pokemon":{

    },
    "show_candies":true,
    "// 'pokemon_info' parameter define which info to show for each pokemon":{

    },
    "// the available options are":{

    },
    "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']":{

    },
    "pokemon_info":[
      "cp",
      "iv_pct"
    ]
  },
  "walk_max":4.16,
  "walk_min":2.16,
  "alt_min":500,
  "alt_max":1000,
  "sleep_schedule":[
    {
      "time":"12:00",
      "duration":"5:30",
      "time_random_offset":"00:30",
      "duration_random_offset":"00:30",
      "wake_up_at_location":""
    },
    {
      "time":"17:45",
      "duration":"3:00",
      "time_random_offset":"01:00",
      "duration_random_offset":"00:30",
      "wake_up_at_location":""
    }
  ],
  "debug":false,
  "test":false,
  "walker_limit_output":false,
  "health_record":true,
  "location_cache":true,
  "distance_unit":"km",
  "reconnecting_timeout":15,
  "logging":{
    "color":true,
    "show_datetime":true,
    "show_process_name":true,
    "show_log_level":true
  },
  "catch":{
    "any":{
      "catch_above_cp":0,
      "catch_above_iv":0,
      "logic":"or"
    },
    "// Example of always catching Rattata:":{

    },
    "// Rattata":{
      "always_catch":true
    }
  },
  "release":{
    "any":{
      "keep_best_iv":1
    },
    "Pidgey":{
      "keep_best_cp":100
    },
    "// Example of always releasing Rattata:":{

    },
    "// Rattata":{
      "always_release":true
    },
    "// Example of keeping 3 stronger (based on CP) Pidgey:":{

    },
    "// Pidgey":{
      "keep_best_cp":3
    },
    "// Example of keeping 2 stronger (based on IV) Zubat:":{

    },
    "// Zubat":{
      "keep_best_iv":2
    },
    "// Keep no more than 3 best IV pokemon for every pokemon type":{

    },
    "// any":{
      "keep_best_iv":3
    },
    "// Discard all pokemon in bag except 100 pokemon with best CP":{

    },
    "// all":{
      "keep_best_cp":100
    },
    "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:":{

    },
    "// Zubat":{
      "keep_best_cp":2,
      "keep_best_iv":3
    }
  },
  "vips":{
    "any":{
      "catch_above_cp":1200,
      "catch_above_iv":0.9,
      "logic":"or"
    },
    "Lapras":{

    },
    "Moltres":{

    },
    "Zapdos":{

    },
    "Articuno":{

    },
    "Mewtwo":{

    },
    "Dragonite":{

    },
    "Snorlax":{

    },
    "Mew":{

    },
    "Arcanine":{

    },
    "Vaporeon":{

    },
    "Gyarados":{

    },
    "Exeggutor":{

    },
    "Muk":{

    },
    "Weezing":{

    },
    "Flareon":{

    },
    "Porygon":{

    },
    "Chansey":{

    },
    "Aerodactyl":{

    },
    "Kangaskhan":{

    },
    "Mr. Mime":{

    },
    "Farfetch'd":{

    },
    "Ditto":{

    }
  }
}

### Output when issue occurred
[2016-09-05 12:17:43] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:17:44] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:17:46] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:17:47] [MainThread] [PokemonCatchWorker] [INFO] [threw_pokeball] Excellent throw! Used Pokeball, with chance 47.34 (168 left)
[2016-09-05 12:17:47] [MainThread] [PokemonCatchWorker] [INFO] [pokemon_capture_failed] Ekans capture failed.. trying again!
[2016-09-05 12:17:48] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:17:48] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:17:49] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:17:49] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:17:51] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:17:51] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:17:53] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:17:53] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:17:53] [MainThread] [PokemonCatchWorker] [INFO] [threw_pokeball] Great throw! Used Pokeball, with chance 47.34 (167 left)
[2016-09-05 12:17:53] [MainThread] [PokemonCatchWorker] [INFO] [pokemon_capture_failed] Ekans capture failed.. trying again!
[2016-09-05 12:17:55] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:17:55] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:17:57] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:17:57] [MainThread] [PokemonCatchWorker] [INFO] [threw_pokeball] Nice Curveball throw! Used Pokeball, with chance 47.34 (166 left)
[2016-09-05 12:17:58] [MainThread] [PokemonCatchWorker] [INFO] [pokemon_capture_failed] Ekans capture failed.. trying again!
[2016-09-05 12:17:59] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:18:08] [MainThread] [PokemonCatchWorker] [INFO] [threw_pokeball] Nice Curveball throw! Used Pokeball, with chance 47.34 (165 left)
[2016-09-05 12:18:08] [MainThread] [PokemonCatchWorker] [INFO] [pokemon_capture_failed] Ekans capture failed.. trying again!
[2016-09-05 12:18:10] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:18:12] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:18:14] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:18:14] [MainThread] [PokemonCatchWorker] [INFO] [threw_pokeball] Great throw! Used Pokeball, with chance 47.34 (164 left)
[2016-09-05 12:18:15] [MainThread] [PokemonCatchWorker] [INFO] [pokemon_vanished] Ekans vanished!
[2016-09-05 12:18:15] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:18:17] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:18:21] [MainThread] [urllib3.connectionpool] [WARNING] Connection pool is full, discarding connection: api.telegram.org
[2016-09-05 12:18:21] [MainThread] [IncubateEggs] [INFO] [next_egg_incubates] Eggs incubating: [1.23/5.0 km] (Eggs left: 8, Incubating: 1)

### Steps to Reproduce
It only happens when i have the MoveToMapPokemon function in config file.

**Comment by oralunal** [comment]
It's not issue about pogo-bot. It's telegram api log, and it is not problem.. So don't worry about it.
