### ISSUE TITLE
MoveToMapPokemon- snipe_high_prio_threshold not working

### ISSUE THREAD

**Issue by crvfts** [PokemonGoF/PokemonGo-Bot#5224]
"snipe_high_prio_threshold": 799,
.... etc
Eevee: 666,

```
"type": "MoveToMapPokemon",
        "config": {
          "enabled": true,
          "address": "http://localhost:5010",
          "max_sniping_distance": 333,
          "max_walking_distance": 333,
          "min_time": 240,
          "min_ball": 5,
          "prioritize_vips": true,
          "snipe": false,
          "snipe_high_prio_only": true,
          "snipe_high_prio_threshold": 799,
          "mode": "priority",
          "map_path": "raw_data",
          "walker": "StepWalker",
          "max_extra_dist_fort": 10,
          "update_map": false,
          "snipe_max_in_chain": 21,
          "debug": false,
```

I've noticed for awhile now I have to either comment-out a Pokemon or delete them from config completely.  Any ideas?

min_time also appears to have no effect. Sometimes bot will reroute to more desired pokemon when they only have a few seconds of spawn-time left.

**Comment by mjmadsen** [comment]
If you set eevee to 666 with a threshold of 799. you'll only walk towards the eevee, not teleport

**Comment by crvfts** [comment]
I have config set to only walk. Pokemon are sought out in descending order as intended just fine, the only issue is that Pokemon that should be disregarded are still walked to. Am I simply misunderstanding how the task actually works or is it a bug?

**Comment by mjmadsen** [comment]
For walking, all pokemon are hunted - I don't think ignore is applied, maybe wrong.

**Comment by crvfts** [comment]
It worked fine for me previously without this issue. I tested some more this evening and after a couple hours, commented-out pokemon were finally ignored. It actually happened with Eevee and there was nothing else around within the walk range. Weird. Maybe it's an intermittent glitch? It seems when it happens it keeps happening for awhile and then stops for a day or 2. I only play in the exact same area all the time so it's the same pokemon day in and day out.

**Comment by YvesHenri** [comment]
I'm closing this as it might have already been fixed. If it isn't, please reopen a new one.
