### ISSUE TITLE
release_below_ivcp

### ISSUE THREAD

**Issue by javajohnHub** [PokemonGoF/PokemonGo-Bot#5225]
### Short Description

release_below_ivcp functionality. Release pokemon based on ivcp score.

### Possible solution

as a release parameter

### How it would help others

The ivcp calculation is more accurate according to the docs.

**Comment by Gobberwart** [comment]
I'd look at it but... beer

**Comment by Gobberwart** [comment]
Yes.. let me take a look :)

**Comment by Gobberwart** [comment]
Working on it. Adding "keep_best_ivcp" as well.

**Comment by javajohnHub** [comment]
Nice thank you!

**Comment by Gobberwart** [comment]
@javajohnHub Take a look at PR #5465
