### ISSUE TITLE
The project still use the old system python2.6 instead of python2.7 for installing

### ISSUE THREAD

**Issue by SiRoCu1976** [PokemonGoF/PokemonGo-Bot#5229]
CentOS release 6.6
As the topic, I've new install python2.7 into the machine and set /home/.bashrc like these:

alias python=/usr/local/bin/python2.7
alias python2=/usr/local/bin/python2.7

When type "python --version" it get "Python 2.7" on the shell, everything look ok.

But the PokemonGo-Bot setup script still use the old python2.6 and it alway incomplete.

Any idea?

**Comment by Anakin5** [comment]
That is quite a singular way to use another version of python. May I know why you don't add `/usr/local/bin` into your `PATH`, before `/usr/bin` ?
Can you check what is the result once you do ?

**Comment by sohje** [comment]
What about this?
```shell
PYTHONPATH=/usr/local/bin/python2.7 ./setup.sh
```
