### ISSUE TITLE
Issue ([Errno 54] Connection reset by peer) with PokemonOptimizer task

### ISSUE THREAD

**Issue by farshidhss** [PokemonGoF/PokemonGo-Bot#5232]
### Expected Behavior
The evolve process continue without any issue. 

### Actual Behavior
Evolve process returns an Error ([Errno 54] Connection reset by peer) every few evolve. Please see the logs: http://pastebin.com/1HU82FM3
Same thing happens during transfer:
http://pastebin.com/Xmfbb086

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/LjBKMwhC

### Output when issue occurred

http://pastebin.com/1HU82FM3
http://pastebin.com/Xmfbb086

### Steps to Reproduce
Use the task PokemonOptimizer to transfer or evolve.

### Other Information
OS: 
Mac OS X 10.11.6
Branch: 
dev
Git Commit: 
f0df954ee0e79c1dbfd3be76324b73b36988915b
Python Version: 
2.7
Any other relevant files/configs (eg: path files)

**Comment by Anakin5** [comment]
Whether your problem is related or not, I added the heartbeat to those tasks to avoir having zero activity during evolve.
However since you also get issues during transfer, you issue surely comes from something else. Remove all that Telegram, WebSocket etc... crap from your config and check if you still have the issue.

**Comment by sohje** [comment]
Ok, seems i found source of a problem.
This is social_handler.py when client attempting to connect with mqtt_protocol version.

**Comment by MZorzy** [comment]
#5240

**Comment by farshidhss** [comment]
I get error 54 not 104 so I'm not sure of that issue is related to mine. But as your instructions I disables social and will report back to you if that helped. Thanks.

**Comment by Gobberwart** [comment]
This error is completely ignorable. Most likely will be addressed during major social_handler.py overhaul (currently in progress).
