### ISSUE TITLE
Telegram bot /info should return exactly what UpdateLiveStats does - any more ideas

### ISSUE THREAD

**Issue by lntn** [PokemonGoF/PokemonGo-Bot#5236]
I've been using Telegram bot and I'm in love with it. I can totally replace the Web UI for keeping track of what the bot's doing, and where.

Here's my two cent : /info should return more relevant data - the best bet is to be exactly what people have set up for "UpdateLiveStats", instead of the current static set of info. For example, the number of catches over the past 24 hours wouldn't be helpful in any circumstance, with the daily catch limit on.

Like-wise, /inventory (to be added) should works as same as "UpdateLiveInventory";
/show_best would show you your best pokemon

Furthermore, certain commands can be issued to the bot, if possible
- /transfer would trigger transfer pokemon before the threshold is reached
- /return_poly would trigger returning to the start location using polyline walker, ignoring all path & move config.
and much more if it is possible for the Telegram to control other tasks.

In fact, Telegram can even become our own app client with push notification for events, and awaiting for our actions.

**Comment by rawgni** [comment]
yep. the code needs refactoring.

**Comment by MerlionRock** [comment]
I've seen the code. Isn't that straight forward and currently look messy to me...

Haven't been coding for a long time and didn't have the time. Else I might try.

**Comment by DBa2016** [comment]
Parts of this "issue" (it is a feature request, by the way, please update the title) have already been implemented in #5238 (merged into dev already; you can subscribe to whatever events you like, including log_stats) and in #5274 (adds display of top X pokemon, plus some backend preparations for pokemon manipulations).

Yes, I liek the idea of having Telegram as an own kind-of-frontend.

Actually, this all logic should go into a base class, inherited by Telegram, Discord etc etc.

Hell, old-school guys could even use IRC or FidoNet to control the bot...

**Comment by Gobberwart** [comment]
@DBa2016 Yes it should. Maybe I'll look into it tomorrow.

**Comment by lntn** [comment]
Strange, I've just tried to pull from dev 1 hour ago and there's no changes. Maybe it's been updated since yesterday, but I can't see any change in sample config file, and Telegram is not notifying anything now.

**Comment by DBa2016** [comment]
@lntn : #5274 is waiting to be merged yet, so "/top" does not work yet. For notification configuration, please look at the telegramtask.md, you need to subscribe to the events you want notifications about.

**Comment by lntn** [comment]
@DBa2016 thanks for the PR.

by `In order to subscribe to a certain event, e.g. to "no_pokeballs", you simply send the `/sub` command as follows:`, does it mean that we will need to subscribe again every time the bot started? Or do you keep the subscription in some sort files? If subscription is just temporary then I'd suggest to have a config line for that.

**Comment by th3w4y** [comment]
man this will require quite some work...!
>/return_poly would trigger returning to the start location using polyline walker, ignoring all path & move config. and much more if it is possible for the Telegram to control other tasks.

**Comment by javajohnHub** [comment]
With the recent merge can this now be closed?

**Comment by javajohnHub** [comment]
Nevermind the features you asked for havent been implemented.

**Comment by lntn** [comment]
I have not tried it yet, but thanks you.

**Comment by lntn** [comment]
@javajohnHub I've pulled the latest dev branch few hours ago and /info still giving the same old stuff, like number of pokemon caught in the past 24 hours.

**Comment by javajohnHub** [comment]
So even though you can subscribe to that data....you would still like a command to get updatelivestats?
