### ISSUE TITLE
Not evolving Nidoran M/F

### ISSUE THREAD

**Issue by jannickv** [PokemonGoF/PokemonGo-Bot#5239]
All pokemon in my evolve_list are being evolved except for the Nidoran. Guess it has something to do with the space.

```
{
        "type": "EvolvePokemon",
        "config": {
          "enabled": true,

          "evolve_list": "Pidgey, Caterpie, Weedle, Zubat, Rattata, Sandshrew, Drowzee, Nidoran M, Tentacool, Spearow, Psyduck",
          "donot_evolve_list": "none",

          "first_evolve_by": "cp",
          "evolve_above_cp": 0,
          "evolve_above_iv": 0,
          "logic": "or",
          "min_evolve_speed": 22,
          "max_evolve_speed": 30,
          "use_lucky_egg": false
        }
      },

```

**Comment by Anakin5** [comment]
No it is correct with one space. You are missing the female versionthough:
`Nidoran M` `Nidoran F`

**Comment by jannickv** [comment]
I don't want to evolve the female version so thats ok. But i checkend, and even when i added it, it doesn't evolve them.

**Comment by Gobberwart** [comment]
Remove the space, eg. "NidoranM" not "Nidoran M". Even though the pokemon is called "Nidoran M" the bot strips out the space before comparing.

**Comment by Gobberwart** [comment]
Putting through a PR to fix this now.

**Comment by jannickv** [comment]
@Gobberwart thanks for your work!

**Comment by Anakin5** [comment]
Note that PokemonOptimizer accept both !!
