### ISSUE TITLE
Perma ban statistics

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#5246]
There was an old one, but it gets old and no one is reporting anything there.

I have several accounts, all running fine for more than a week. Anybody else have banning issues?
At first, I thought it was the bot that is causing banning problem. But after I tested more, I find it's in the settings. If you do settings right, you should be fine.

**Comment by Anakin5** [comment]
My 2 cents: bans come by waves, and it will come again, dont worry.
All people snipping will get ban because it is easy to detect. Others might have a chance but I would not hope too much because bots are not perfect yet.

**Comment by jrjhealey** [comment]
Yeah I would expect the next big ban wave to come when the Gen2 update hits. I believe thats rumoured to be happening in the next couple of months.

Don't count you're chickens just yet ;)

**Comment by settoger** [comment]
I think I broke the game! For about 1 month I am over Level 20. At this time lvl 29. 
I started with a new ptc account and start only with the bot. At lvl 21 I logged in from my smartphone for the first time. I first had to choose my starter Pokemon (Squirtle CP 545). Then the guy said to me I had to move to a arena (or what ever he said), to choose my team (blue).
I got no avatar and when I want to create one to myself the game crash. 
When I walk around I see no avatar walking, just a tiny round shadow.
I found out last week, after my first arena-fight, that when I am the leader of an arena and you try to fight me, the game crash again. This take affect for every player who wants to fight me.
At this time I am the leader of 13 arenas. The strongest Pokemon is a Venomoth (CP 787).

I use dev (pull every day) with standard config.json (no changes where made)

**Comment by jrjhealey** [comment]
Well that is why the bot instructions do (or did) say you should complete the tutorial first, and why bot activity related to gyms is generally frowned upon...

**Comment by avexus** [comment]
still wait to see the ban wave to come.

**Comment by avexus** [comment]
I could be IP banned. The bot stopped working. I'll try to use the bot in a coffee shop later on. To see if it's IP ban or something else.

**Comment by Gobberwart** [comment]
Nice chat, but not an issue. Take it to slack.
