### ISSUE TITLE
'PokemonGoBot' object has no attribute '_player'

### ISSUE THREAD

**Issue by cbogithub** [PokemonGoF/PokemonGo-Bot#5249]
```
Traceback (most recent call last):
  File "pokecli.py", line 803, in <module>
    main()
  File "pokecli.py", line 239, in main
    report_summary(bot)
  File "pokecli.py", line 287, in report_summary
    metrics.capture_stats()
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\metrics.py", line 105, in capture_stats
    self.dust['latest'] = self.bot.stardust 
  File "P:\pokemon go\PokemonGo-Bot\pokemongo_bot\__init__.py", line 72, in stardust
    return filter(lambda y: y['name'] == 'STARDUST', self._player['currencies'])[0]['amount']
AttributeError: 'PokemonGoBot' object has no attribute '_player'
```

**Comment by alexyaoyang** [comment]
@rawgni

**Comment by avexus** [comment]
same problem, could not start bot.

**Comment by alexyaoyang** [comment]
Follow that PR and add that line should work for now.

**Comment by Gobberwart** [comment]
#5254 has been merged into dev, but not master. You will need to apply the fix yourself until merged to master (refer to the PR for details)

**Comment by rawgni** [comment]
@alexyaoyang actually, the problem exist because the user was not able to login. Thus, bot having no player information. However, our code still wants to print report_summary on exit.

**Comment by mjmadsen** [comment]
@rawgni I completely forgot about that. Thank you!

**Comment by mjmadsen** [comment]
@cbogithub @avexus Was there an API error printed before that traceback? 

This whole damn file needs to be cleaned up.

**Comment by Gobberwart** [comment]
Yes it does, but closing because there's fix in dev.
