### ISSUE TITLE
"pokecli.py", line 42 | Raspberry Pi 2

### ISSUE THREAD

**Issue by SlaYxK** [PokemonGoF/PokemonGo-Bot#5250]
### Expected Behavior
I got a Raspberry Pi 2 with Raspbian  an everything is installed. Virtuelenv won't work and the bot wont start.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

Standart config.json

### Output when issue occurred

```
(PokemonGo-Bot) root@raspberrypi:/usr/share/pokemon/PokemonGo-Bot# python pokecl                                                                                                                                                             i.py
Traceback (most recent call last):
  File "pokecli.py", line 42, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottl                                                                                                                                                             ingException, ServerBusyOrOfflineException, NoPlayerPositionSetException
ImportError: No module named pgoapi.exceptions
```

### Other Information
OS: Raspbian
Branch: dev
Python Version: Python 2.7.9 
Any other relevant files/configs (eg: path files)

**Comment by cbogithub** [comment]
run "pip install requirements.txt"

**Comment by mmeulstee** [comment]
run "sudo pip install requirements.txt" on rpi

**Comment by SlaYxK** [comment]
> run "sudo pip install requirements.txt" on rpi
i did it before
and with "pip install -r requirements.txt"

```
root@raspberrypi:/usr/share/pokemon/PokemonGo-Bot# pip install requirements.txt Downloading/unpacking requirements.txt
  Could not find any downloads that satisfy the requirement requirements.txt
Cleaning up...
No distributions at all found for requirements.txt
Storing debug log for failure in /root/.pip/pip.log

```

**Comment by sohje** [comment]
install -**r** requirements.txt

**Comment by SlaYxK** [comment]
```
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-Qpwnad/protobuf-to-dict
Storing debug log for failure in /root/.pip/pip.log

```
this is the end of "pip install -r requirements.txt"

**Comment by DBa2016** [comment]
And what is in /root/.pip/pip.log ?

**Comment by jannickv** [comment]
have you tried installing python dev and afterwards installing the requirements again?

`sudo apt-get install python-dev`

**Comment by jrjhealey** [comment]
You'll want to run the pip command once you've already set up virtualenv.

Make sure you've got it installed. You can check with `virtualenv --version`

If you get nothing, that's your problem I'd say (at least to start with).

**Comment by foster82** [comment]
I had the same problem at first. You need to add ..

deb http://archive.raspbian.org/raspbian jessie  main contrib non-free

To your source.list file then..

Sudo apt-get update 

Then.. 

Sudo apt-get install -y python-dev.

It should then install. Once done follow the manual install process. I did this and is working fine on my b+. :)

**Comment by Gobberwart** [comment]
Solution provided
