### ISSUE TITLE
 [   Pokemon] [ERROR] Unexpected moveset [Mud Slap, Ancient Power] for #76 Golem, please update info in pokemon.json and create issue/PR

### ISSUE THREAD

**Issue by agetnc313** [PokemonGoF/PokemonGo-Bot#5255]
[   Pokemon] [ERROR] Unexpected moveset [Mud Slap, Ancient Power] for #76 Golem, please update info in pokemon.json and create issue/PR

**Comment by Gobberwart** [comment]
Hmmm, this moveset appears to be in pokemon.json... when did you last update?

**Comment by Gobberwart** [comment]
No response. Closing.
