### ISSUE TITLE
(Feature Request) Campfort to print out distance left when moving towards location

### ISSUE THREAD

**Issue by deception83** [PokemonGoF/PokemonGo-Bot#5259]
I think Campfort should have some sort of a feedback printed out that it is moving rather then just telling me that it found a good location and nothing else although according to my map it is really moving.

**Comment by Anakin5** [comment]
I will add that in next commit on camp fort

**Comment by deception83** [comment]
@Anakin5 
Thanks!

**Comment by Anakin5** [comment]
Done
