### ISSUE TITLE
Virtualenv does not exits

### ISSUE THREAD

**Issue by cedricbousmanne** [PokemonGoF/PokemonGo-Bot#5261]
### Expected Behavior

Running the app

### Actual Behavior

Ask to run `./setup.sh -i` even though I just did it

### Your FULL config.json

https://gist.github.com/cedricbousmanne/17ea044497a8236014d33c62d52655cd

### Output when issue occurred

```
 ./run.sh 
Virtualenv does not exits
Run: ./setup.sh -i

```

### Steps to Reproduce

* Checkout master
* run setup.sh
* run run.sh

### Other Information
OS: Ubuntu 16.04
Branch: both dev and master
Git Commit: 1b8cf13ffa183962df4c0ddfe92e6a9906da236b
Python Version: Python 2.7.12

**Comment by rawgni** [comment]
@cedricbousmanne can you try
```
virtualenv .
source bin/activate 2> /dev/null
echo $?
```

**Comment by cedricbousmanne** [comment]
Did work, thanks
