### ISSUE TITLE
[Debug] suppressed error msg <location.cs-line 86 - index is -1

### ISSUE THREAD

**Issue by Slayer013** [PokemonGoF/PokemonGo-Bot#5272]
### Expected Behavior

initially, character gets items at pokestops and proceed to the next one

### Actual Behavior

after a few hours farming, i got this error message everytime my character goes to a poke stop..

**Comment by Gobberwart** [comment]
This is not the bot you're looking for.

**Comment by Slayer013** [comment]
sorry.. i thought this is for PokemonGo.RocketAPI.Console.exe
