### ISSUE TITLE
Optimizer exchange the only pokemon of a family

### ISSUE THREAD

**Issue by liejuntao001** [PokemonGoF/PokemonGo-Bot#5275]
### Expected Behavior

Using PokemonOptimizer and it should keep the at least one pokemon of a family

### Actual Behavior

It exchange the only one of a family, for a upgraded family.
example: there are many Magnetites and only one Magneton, it exchange the Magneton

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

                {
                        "type": "PokemonOptimizer",
                        "config": {
                                "enabled": true,
                                "transfer": true,
                                "transfer_wait_min": 4,
                                "transfer_wait_max": 6,
                                "evolve": true,
                                "evolve_time": 25,
                                "evolve_for_xp": true,
                                "evolve_only_with_lucky_egg": false,
                                "evolve_count_for_lucky_egg": 72,
                                "may_use_lucky_egg": true,
                                "upgrade": true,
                                "upgrade_level": 60,
                                "min_slots_left": 5,
                                "groups": {
                                        "gym": ["Dragonite", "Snorlax", "Lapras", "Arcanine"],
                                        "my_love": ["Pikachu"],
                                        "vip": ["Exeggutor", "Blastoise", "Vaporeon", "Gyarados", "Flareon", "Venusaur", "Dragonite", "Snorlax", "Lapras", "Arcanine"]
                                },
                                "keep": [
                                        {
                                                "mode": "by_family",
                                                "top": 1,
                                                "sort": [{"iv": 0.9}],
                                                "evolve": true,
                                                "upgrade": false
                                        },
                                        {
                                                "mode": "by_family",
                                                "top": 1,
                                                "sort": [{"ncp": 0.9}],
                                                "evolve": true,
                                                "upgrade": false
                                        },
                                        {
                                                "mode": "by_family",
                                                "top": 1,
                                                "sort": ["cp"],
                                                "evolve": false,
                                                "upgrade": false
                                        },
                                        {
                                                "mode": "by_family",
                                                "names": ["vip"],
                                                "top": 3,
                                                "sort": [{"iv": 0.9}, {"ncp": 0.9}],
                                                "evolve": true,
                                                "upgrade": false
                                        },
                                        {
                                                "mode": "by_family",
                                                "names": ["my_love"]
                                        }
                                ]
                        }
                },
### Output when issue occurred

[2016-09-07 18:47:44] [PokemonOptimizer] [INFO] Exchanged Magnemite [IV 0.67] [CP 179] [57 candies]
[2016-09-07 18:47:48] [PokemonOptimizer] [INFO] Exchanged Magneton [IV 0.64] [CP 551] [58 candies]
[2016-09-07 18:47:54] [PokemonOptimizer] [INFO] Exchanged Magnemite [IV 0.58] [CP 520] [59 candies]
[2016-09-07 18:48:00] [PokemonOptimizer] [INFO] Exchanged Magnemite [IV 0.56] [CP 361] [60 candies]
[2016-09-07 18:48:05] [PokemonOptimizer] [INFO] Exchanged Magnemite [IV 0.53] [CP 197] [61 candies]
[2016-09-07 18:48:10] [PokemonOptimizer] [INFO] Exchanged Magnemite [IV 0.38] [CP 451] [62 candies]

### Steps to Reproduce

NA

### Other Information
OS: 
Linux
Branch: 
master
Git Commit: 
d4addb06c1910384c010e9fb4ee5a367953b8d00
Python Version: 
Python 2.7.6 
Any other relevant files/configs (eg: path files)

**Comment by Anakin5** [comment]
Expected behavior according to your config.
Read https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/pokemon_optimizer.md#keep-mode

**Comment by DaxChen** [comment]
If you want to keep 1 for every pokemon, you should change the "by_family" to "by_pokemon"

**Comment by liejuntao001** [comment]
Thanks, so I didn't understand the meaning of "family". It would be nice to have a glossary to help new guys.

**Comment by deception83** [comment]
For example the family includes all 3 evolution for charmander. So when you config optimizer to evaluate the "by_family" of charmander, the optimizer will evaluate all 3 evolutions. 

If you use "by_pokemon" for charmander, the optimizer will only evaluate the pokemon with the name of charmander only.

**Comment by Anakin5** [comment]
I will add what it means in the doc.

**Comment by Anakin5** [comment]
Done
