### ISSUE TITLE
[Question] How to stay in a place with some diameter (in meters)?

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#5284]
How can we specify for the bot to stay in a specified area?
I noticed they wonder around to the neighboring cities.

**Comment by lntn** [comment]
set a circle path?

**Comment by Anakin5** [comment]
If there is at least one fort in your area, you can use the CampFort task.

**Comment by lytesout2376** [comment]
What I do to achieve this is to remove the MoveToFort task and add the FollowPath task.  In my path config, I only place 1 location (the location I want the bot to stay in).

I do wonder, if we remove MoveToFort AND FollowPath and just add a location in the auth config; this might achieve the same thing.  Devs?

**Comment by avexus** [comment]
I'll try CampFort, so, I should set the time for a very long period, right? @Anakin5

**Comment by Anakin5** [comment]
Depends what you want to do in detail:
- Remove FolloSpiral but keep MoveToFort after CampFort
- Put `moving_time` to zero if you just want to move between clusters in your radius and stay there
- Put `moving_time` to non zero if you want to allow the bot to use the task move to fort for some time. (It might walk out of your defined radius)
- Put `camping_time` to whatever you want. When this time expire, the bot will look for another interesting cluster.
