### ISSUE TITLE
Bot goes to sleep when started

### ISSUE THREAD

**Issue by neogan86** [PokemonGoF/PokemonGo-Bot#5286]
### Expected Behavior
Bot should login when started

### Actual Behavior
Bot goes to sleep cycle of 4.5hrs on day time.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
{
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": true,
    "live_config_update": {
      "enabled": false,
      "tasks_only": false
    },	
    "tasks": [
      {
        "type": "TelegramTask",
        "config": {
          "enabled": false,
          "master": null,
          "// old syntax, still supported: alert_catch": ["all"],
          "// new syntax:": {},
		  "//alert_catch": {"all": {"operator": "and", "cp": 1300, "iv": 0.95},"Snorlax": {"operator": "or", "cp": 900, "iv": 0.9}},
          "alert_catch": ["all"]
	  
        }
      },
      {
        "//NOTE: This task MUST be placed on the top of task list": {},
        "type": "RandomAlivePause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:05:00",
          "max_interval": "01:30:00"
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "RandomPause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:10:00",
          "max_interval": "02:00:00"
        }
      },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": false,
          "// set a name": "",
          "nickname": "",
          "// 0 = No Team, 1 = Blue, 2 = Red, 3 = Yellow": "",
          "team": 0
        }
      },
      {
        "type": "CollectLevelUpReward",
        "config": {
          "collect_reward": true,
          "level_limit": -1
        }
      },
      {
        "type": "IncubateEggs",
        "config": {
          "enabled": true,
          "infinite_longer_eggs_first": false,
          "breakable_longer_eggs_first": true,
          "min_interval": 120,
         "infinite": [2,5,10],
         "breakable": [2,5,10]
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": true,
          "min_interval": 60,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": true,
          "min_interval": 120,
          "show_all_multiple_lines": false,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
        }
      },
      {
        "type": "ShowBestPokemon",
        "config": {
          "enabled": true,
          "min_interval": 60,
          "amount": 5,
          "order_by": "cp",
          "info_to_show": ["cp", "ivcp", "dps", "hp"]
        }
      },
       {
        "type": "TransferPokemon",
        "config": {
          "enabled": true,
          "min_free_slot": 5,
          "transfer_wait_min": 3,
          "transfer_wait_max": 5
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_above_iv": 0.9,
          "nickname_template": "{iv_pct}_{iv_ads}",
          "nickname_wait_min": 3,
          "nickname_wait_max": 5
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "enabled": false,            
          "evolve_list": "all",
          "donot_evolve_list": "none",            
          "first_evolve_by": "cp",
          "evolve_above_cp": 640,
          "evolve_above_iv": 0.8,
          "logic": "or",
          "min_evolve_speed": 25,
          "max_evolve_speed": 30,
          "use_lucky_egg": false
        }
      },
      {
        "type": "UseIncense",
        "config": {
          "use_incense": false,
          "use_order": [
            "ordinary",
            "spicy",
            "cool",
            "floral" 
          ]
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 15,
          "max_balls_keep": 250,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 80 },
			"Greatball":      { "keep" : 80 },
			"Ultraball":      { "keep" : 60 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 10 },
            "Hyper Potion":   { "keep" : 15 },
			"Max Potion":     { "keep" : 15 },
            "Revive":         { "keep" : 10 },
            "Razz Berry":     { "keep" : 55 },
			"Incense":		  { "keep" : 10 },
			"Lucky Egg":	  { "keep" : 10 }			
          },
          "recycle_wait_min": 3,
          "recycle_wait_max": 5,
          "recycle_force": true,
          "recycle_force_min": "00:01:00",
          "recycle_force_max": "00:05:00"
        }
      },
      {
        "type": "CatchPokemon",
        "config": {
          "enabled": true,
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 5,
          "berry_threshold": 0.75,
          "vip_berry_threshold": 0.9,
          "treat_unseen_as_vip": true,
          "daily_catch_limit": 800,
          "vanish_settings": {
            "consecutive_vanish_limit": 10,
            "rest_duration_min": "02:00:00",
            "rest_duration_max": "04:00:00"
          },
          "catch_throw_parameters": {
            "excellent_rate": 0.9,
            "great_rate": 0.9,
            "nice_rate": 0.1,
            "normal_rate": 0.1,
            "spin_success_rate" : 0.9,
            "hit_rate": 0.9
          },
          "catch_simulation": {
            "flee_count": 2,
            "flee_duration": 2,
            "catch_wait_min": 3,
            "catch_wait_max": 6,
            "berry_wait_min": 3,
            "berry_wait_max": 5,
            "changeball_wait_min": 3,
            "changeball_wait_max": 5,
            "newtodex_wait_min": 20, 
            "newtodex_wait_max": 30
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "enabled": true,
          "spin_wait_min": 3,
          "spin_wait_max": 5,
          "daily_spin_limit": 1900
        }
      },
      { "type": "UpdateWebInventory",
        "config": {
          "enabled": true
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "enabled": true,
          "lure_attraction": true,
          "lure_max_distance": 1500,
          "walker": "StepWalker",
          "log_interval": 5
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "enabled": true,
          "diameter": 10,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 10,
      "cache_recent_forts": true
    },
    "pokemon_bag": {
      "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
      "show_at_start": true,
      "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
      "show_count": false,
      "// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
      "show_candies": false,
      "// 'pokemon_info' parameter define which info to show for each pokemon": {},
      "// the available options are": {},
      "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
      "pokemon_info": ["cp", "iv_pct"]
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "alt_min": 500,
    "alt_max": 1000,
    "sleep_schedule": [
      {
        "time": "12:00",
        "duration": "5:30",
        "time_random_offset": "00:30",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      },
      {
        "time": "17:45",
        "duration": "3:00",
        "time_random_offset": "01:00",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      }
    ],
    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": false,
    "replicate_gps_z_noise": false,
    "gps_xy_noise_range": 0.000125,
    "gps_z_noise_range": 12.5,
    "debug": false,
    "test": false,
    "walker_limit_output": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
	"logging": {
		"color": true,
		"show_datetime": true,
		"show_process_name": true,
		"show_log_level": true,
		"show_thread_name": false,
		"clean": false
	},
    "catch": {		
      "//any": {"always_catch": true},
	  "any": {"candy_threshold" : 800 ,"catch_above_cp": 700, "catch_above_iv": 0.9, "logic": "or"},
      "//any": {"candy_threshold" : 800 ,"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "//any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
	  "any": {"keep_best_cp": 2},
      "//any": {"keep_best_cp": 2, "keep_best_iv": 1},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Keep no more than 3 best IV pokemon for every pokemon type": {},
      "// any": {"keep_best_iv": 3},
      "// Discard all pokemon in bag except 100 pokemon with best CP": {},
      "// all": {"keep_best_cp": 100},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3},
      "// Example of custom order of static criterion": {},
      "// Zubat": {"keep_best_custom": "iv, cp, hp_max", "amount":2}
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},
        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    },
	"websocket": {
		"start_embedded_server": true,
		"server_url": "127.0.0.1:4000"
	}
}

### Steps to Reproduce
Start the bot with above config

###Output when started
--------------------Starting bot--------------------

2016-09-08 12:56:07,305 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-08 12:56:07,325 [       cli] [INFO] commit: unknown
2016-09-08 12:56:07,326 [       cli] [INFO] No auth argument specified, checking for C:\Users\neo\Desktop\PoGo\PoGoBot\PokemonGo-Bot\pokemongo_bot\..\configs\auth.json
2016-09-08 12:56:07,331 [       cli] [INFO] No config argument specified, checking for C:\Users\neo\Desktop\PoGo\PoGoBot\PokemonGo-Bot\pokemongo_bot\..\configs\config.json
2016-09-08 12:56:07,335 [       cli] [INFO] Configuration initialized
2016-09-08 12:56:07,336 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-09-08 12:56:07,338 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-09-08 12:56:07,351 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(6548) wsgi starting up on http://127.0.0.1:4000
2016-09-08 12:56:07,599 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): 127.0.0.1
[2016-09-08 12:56:07] [SleepSchedule] [INFO] Sleeping for 03:57:08, wake at 2016-09-08 16:53:15.625000

### Other Information
OS: 
Windows10

Branch: 
latest

Git Commit: 
11123a82cb18c172a262dc9e46e7b2c175666828

Python Version: 
2.7

Am I doing something wrong? It was working fine till I took latest today. Kindly help.

**Comment by rawgni** [comment]
@neogan86 

```
"sleep_schedule": [
  {
    "time": "12:00",
    "duration": "5:30",
    "time_random_offset": "00:30",
    "duration_random_offset": "00:30",
    "wake_up_at_location": ""
  },
```
change the duration or time.

**Comment by neogan86** [comment]
@rawgni 

Doesn't help. Even if I add the schedule, it goes to sleep on start :(

**Comment by rawgni** [comment]
the config above means you are going to sleep at 12pm for around 5 hours and 30 mins. So, it will wake up at around 5:30pm . 

what did you change it to?

**Comment by neogan86** [comment]
I changed it to 10pm. But somehow it still goes to sleep_schedule.

"sleep_schedule": [
  {
    "time": "22:00",
    "duration": "5:30",
    "time_random_offset": "00:30",
    "duration_random_offset": "00:30",
    "wake_up_at_location": ""
  }
]

**Comment by rawgni** [comment]
@neogan86 what's your time now ?
your second sleep is scheduled at 5:45 pm for around 3 hours.
```
  },
  {
    "time": "17:45",
    "duration": "3:00",
    "time_random_offset": "01:00",
    "duration_random_offset": "00:30",
    "wake_up_at_location": ""
  }
],
```

**Comment by neogan86** [comment]
Now the time is 4:45 pm. I removed the second schedule and had only 10pm schedule entry, it works. Don't know why it went to sleep cycle from around 12 pm :(
