### ISSUE TITLE
bot crashes on MoveToMapPokemon  task

### ISSUE THREAD

**Issue by houkop** [PokemonGoF/PokemonGo-Bot#5290]
### Expected Behavior
I want to use move to map without sniping

### Actual Behavior
bot crashes

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/AZKkmqm3

### Output when issue occurred
Traceback (most recent call last):
  File "pokecli.py", line 803, in <module>
    main()
  File "pokecli.py", line 162, in main
    bot.tick()
  File "/home/houkop/dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 685, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/home/houkop/dev/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_map_pokemon.py", line 381, in work
    step_walker = self._move_to_pokemon_througt_fort(nearest_fort, pokemon)
  File "/home/houkop/dev/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_map_pokemon.py", line 521, in _move_to_pokemon_througt_fort
    data= pokemon_throught_fort_event_data
  File "/home/houkop/dev/PokemonGo-Bot/pokemongo_bot/base_task.py", line 43, in emit_event
    data=data
  File "/home/houkop/dev/PokemonGo-Bot/pokemongo_bot/event_manager.py", line 72, in emit
    formatted_msg = formatted.format(**data)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

### Steps to Reproduce
enable MoveToMapPokemon

### Other Information
OS: 
Debian GNU/Linux 8 
Branch: 
last dev
Git Commit: 
6aea15fc0a201d529de8c9d4cb3bf19cebc1cbb4
Python Version: 
Python 2.7.9

**Comment by YvesHenri** [comment]
What are your purposes to use snipping without actually teleporting?
It might be deprecated soon.

**Comment by houkop** [comment]
Fix 5290 works, thanks.

It is good feature, why it might be deprecated?

**Comment by YvesHenri** [comment]
Snipping wont be fully deprecated, just the "walking sniper". There's no point to snipe a target by walk. Mostly all the targets are at least farther than 50 kilometers (and thats a really fair close one), so even if it has 15 mins left (which is very unlikely to be), you can't humanly reach it, so why bother walking to it when you can teleport?

**Comment by houkop** [comment]
May be it was misunderstood, I'm not using snipe at all, I'm using that task to move to rare pokemons near bot. So, I hope it will be  ok :)

**Comment by YvesHenri** [comment]
Sorry, which task are you using exactly (name)?

**Comment by houkop** [comment]
move_to_map_pokemon

**Comment by crvfts** [comment]
I use the walking sniper all the time, there are plenty of Pokemon I want within walking range at some point. Doesn't the game record location where pokemon was caught? If there isn't a spawn near the catch site, wouldn't we want to avoid that?

**Comment by Anakin5** [comment]
Fixed

**Comment by YvesHenri** [comment]
@houkop move_to_map_pokemon is what we can snipping.
@crvfts I can't tell you whether they record the encounter coords and/or the caught coords, but either way snipping is not safe, so isnt botting.
