### ISSUE TITLE
Major issue with heartbeat, random crashes

### ISSUE THREAD

**Issue by Anakin5** [PokemonGoF/PokemonGo-Bot#5299]
There is a major issue with the heartbeat being moved to a separate thread.
It updates inventory, player data and fort timeout concurrently to other tasks. It causes random crashes.

Simple scenario:
````
Main Thread: Transfer Pokemon
Timeout Thread: Refresh Inventory
Main Thread: inventory.remove(pokemon_id) <- exception
```

I have trigger several scenario like that so far. The update of data structures should be moved out of the heartbeat.

**Comment by Gobberwart** [comment]
What's your proposed solution?

**Comment by Anakin5** [comment]
Must be done in main thread to avoid modifying objects that a tasks is currently using. But does the phone application do that anyway ? (requesting inventory, player data etc.. regularly)

**Comment by Gobberwart** [comment]
Not sure if the app does it, but we need to in order to make sure our information is 100% accurate and avoid other silly errors (like trying to discard stuff we don't have, trying to nickname a pokemon that isn't there etc.)

If every single piece of code that does something inventory-related could be guaranteed to always update inventory/stats, wouldn't be an issue, but... I wouldn't make that guarantee :)

**Comment by rawgni** [comment]
#4605 show which api is being requested for any request

**Comment by Gobberwart** [comment]
```
    def add(self, pokemon):
        if pokemon.unique_id <= 0:
            raise ValueError("Can't add a pokemon without id")
        if pokemon.unique_id in self._data:
            raise ValueError("Pokemon already present in the inventory")
        self._data[pokemon.unique_id] = pokemon
```

This now occurs because of heartbeat being moved to thread, HOWEVER... why on earth are we raising an exception/crashing because of this? Should just print a debug message and move on.

**Comment by Gobberwart** [comment]
Ugh, yes this is a major headache. Why did heartbeat get threaded? It's not as if it was significantly holding up bot execution or anything.

**Comment by rawgni** [comment]
@Gobberwart since heartbeat should be sent periodically, and some of the tasks might prevent this to be done. Say, if you are evolving a whole bunch of pokemon, the heartbeat will not be called until all the tasks are done.

**Comment by Gobberwart** [comment]
@rawgni ok cool thank you. So... why does that matter? Trying to replicate the app behaviour?

**Comment by rbusquet** [comment]
I'm having lots of crashes because of this, I believe. 
Mainly pokemon already in inventory and trying to remove an item I don't have. Is this problem related to this issue?

**Comment by Gobberwart** [comment]
Yes. PR coming.

**Comment by Gobberwart** [comment]
#5347 should fix this

**Comment by Gobberwart** [comment]
@Anakin5 does this resolve your issue?

**Comment by Gobberwart** [comment]
I'm going to say yes, and close this. Reopen if not fixed.
