### ISSUE TITLE
issue with CampFort

### ISSUE THREAD

**Issue by liejuntao001** [PokemonGoF/PokemonGo-Bot#5301]
I'm trying to use CampFort and notice 2 problems.
1. If I increase "min_forts_count" to 4, I don't see CampFort kicking in
2. If a cluster was detected and after moved to the place, if the lure has gone, bot is not leaving

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

      {
        "type": "CampFort",
        "config": {
        "enabled": true,
        "max_distance": 2000,
        "min_forts_count": 2,
        "min_lured_forts_count": 1,
        "camping_time": 1800,
        "moving_time": 600
        }
      },
      {
        "type": "MoveToFort",
        "config": {
        "enabled": true,
        "lure_attraction": true,
        "lure_max_distance": 300,
        "walker": "PolylineWalker",
        "log_interval": 5
        }
      }

### Output when issue occurred

[2016-09-08 12:16:54] [  CampFort] [INFO] New destination at 328 meters: 2 forts, 2 lured.
[2016-09-08 12:24:34] [  CampFort] [INFO] Arrived at destination: 2 forts, 0 lured.
...
staying there

Branch: 
master

Git Commit: 
11123a82cb18c172a262dc9e46e7b2c175666828

**Comment by MZorzy** [comment]
have u wait 1800 ?

**Comment by liejuntao001** [comment]
No I didn't wait 1800, why would it wait if no lured forts?

**Comment by MZorzy** [comment]
i think that with 
camping_time": 1800, 
bot will not move until 1800 time expire.

**Comment by Anakin5** [comment]
If `min_forts_count` is 4, you will only go to clusters of 4 forts. Do you have such thing in your area ? If not, the task will not so anything.

The bot will not more away imediately if lures disappear because a player might put back a lure right away.
The next cluster could be far so it will be a waste of time to decide to go 1000 meters away to realize lures are back in our previous location.

However, I am adding a feature that will apply a malus to the time when we see there is no lure. So the bot will leave earlier.

**Comment by liejuntao001** [comment]
I set the bot to a big city with huge amount of forts. (41.8756,-87.6291)
I tried to set min_forts_count to 3 and saw no log about CampFort

**Comment by Anakin5** [comment]
Can you check that it is working with the config you have mentioned in your first post ? It is not 4 or 3 there, it is 2.

**Comment by liejuntao001** [comment]
it's working with 2.

**Comment by Anakin5** [comment]
You may not have any 3+ fort camp in your area.

**Comment by liejuntao001** [comment]
what's the meaning of 3+ fort camp? 3 forts in a range of xxx meters?
basically the area is full of forts, if you search the coordinate.

**Comment by davidakachaos** [comment]
`min_forts_count` is the amount of forts you can reach while standing in 1 spot.
Of those a count of `min_lured_forts_count` must be lured for the task to select is as a camp site.

**Comment by liejuntao001** [comment]
I see, it's quite rare but I did see a place with min_forts_count 3.

[2016-09-09 09:46:19] [  CampFort] [INFO] Arrived at destination: 3 forts, 1 lured.

**Comment by Anakin5** [comment]
Keep it at 2 if you want to make the CampFort your main decision point for moving.
Put it to 3 with a minimum number of lures, if you know you have several spot with 3 forts reachable and only want to go there when it is really worth it.

**Comment by Anakin5** [comment]
Question  answered ?
