### ISSUE TITLE
bot become still after 3 hours of running.

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#5302]
===============ISSUE SECTION===============

Before you create an Issue, please check the following:

1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you [searched our issue tracker](https://github.com/PokemonGoF/PokemonGo-Bot/issues?q=is%3Aissue+sort%3Aupdated-desc) to see if the issue already exists? If so, comment on that issue instead rather than creating a new issue.
3. Are you running on the `master` branch? We work on the `dev` branch and then add that functionality to `master` when it is stable. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.
4. All Issue sections MUST be completed to help us determine the actual problem and find its cause
-->

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
{
	"websocket_server":		false,
	"heartbeat_threshold":	10,
	"enable_social":		false,
	"live_config_update": {"enabled": true, "tasks_only": true},
	"tasks": [
		{"type": "TelegramTask", "config": {"enabled": false, "master": XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX, "alert_catch": {"all": {"operator": "or", "cp": 10, "iv": 0.1}}}},
		{"type": "RandomAlivePause", "config": {"enabled": false, "min_duration": "00:00:10", "max_duration": "00:10:00", "min_interval": "00:05:00", "max_interval": "01:30:00"}},
		{"type": "HandleSoftBan"},
		{"type": "RandomPause", "config": {"enabled": false, "min_duration": "00:00:10", "max_duration": "00:10:00", "min_interval": "00:10:00", "max_interval": "02:00:00"}},
		{"type": "CollectLevelUpReward", "config": {"collect_reward": true, "level_limit": -1}},
		{"type": "IncubateEggs", "config": {"enabled": true, "infinite_longer_eggs_first": false, "breakable_longer_eggs_first": true, "min_interval": 900,"infinite": [2,5,10], "breakable": [10]}},
		{"type": "UpdateLiveStats", "config": {"enabled": true, "min_interval": 8,
			"stats": ["login", "level_stats", "km_walked", "pokemon_encountered", "pokemon_caught", "pokeballs_thrown", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
			"terminal_log": false, "terminal_title": true}},
		{"type": "UpdateLiveInventory", "config": {"enabled": true, "min_interval": 120, "show_all_multiple_lines": false,
			"items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries"]}},
		{"type": "TransferPokemon", "config": {"enabled": true, "min_free_slot": 100, "transfer_wait_min": 7, "transfer_wait_max": 9}},
		{"type": "EvolvePokemon", "config": {"enabled": true,
			"evolve_list": "Pidgey, Weedle, Caterpie",
			"donot_evolve_list": "none", "min_evolve_speed": 25, "max_evolve_speed": 30, "use_lucky_egg": false}},
		{"type": "RecycleItems", "config": {"enabled": true, "min_empty_space":	15,
			"max_potions_keep":	0,
			"max_revives_keep": 0,
			"max_berries_keep":	100,
			"max_balls_keep":	200,
			"item_filter": {
				"Potion":         { "keep" :   0 },
				"Super Potion":   { "keep" :   0 },
				"Hyper Potion":   { "keep" :   0 },
				"Revive":         { "keep" :   0 },
				"Razz Berry":     { "keep" :  100 },
				"Pokeball":       { "keep" :  100 },
				"Greatball":      { "keep" :  100 }
			},
			"recycle_wait_min": 7, "recycle_wait_max": 9, "recycle_force": false, "recycle_force_min": "00:50:00", "recycle_force_max": "01:05:00"}},
		{"type": "CatchPokemon", "config": {"enabled": true, "catch_visible_pokemon": true, "catch_lured_pokemon": true,
			"min_ultraball_to_keep":	5,
			"berry_threshold":			0.55,
			"vip_berry_threshold":		0.5,
			"treat_unseen_as_vip":		true,
			"daily_catch_limit":		1000,
			"catch_throw_parameters": {"excellent_rate": 0.1, "great_rate": 0.5, "nice_rate": 0.3, "normal_rate": 0.1, "spin_success_rate": 0.6,"hit_rate": 0.85},
			"catch_simulation": {"flee_count": 3, "flee_duration": 2, "catch_wait_min": 3, "catch_wait_max": 6, "berry_wait_min": 3, "berry_wait_max": 5, "changeball_wait_min": 3, "changeball_wait_max": 5, "newtodex_wait_min": 20, "newtodex_wait_max": 30}}},
		{"type": "SpinFort", "config": {"enabled": true, "spin_wait_min": 5, "spin_wait_max": 8, "daily_spin_limit": 1500}},

		{
			"type": "CampFort",
			"config": {
				"enabled": true,
				"max_distance": 3000,
				"min_forts_count": 2,
				"min_lured_forts_count": 1,
				"camping_time": 3600,
				"moving_time": 600
			}
		},
		{
			"type": "MoveToFort",
			"config": {
				"enabled": true,
				"lure_attraction": true,
				"lure_max_distance": 300,
				"walker": "PolylineWalker",
				"log_interval": 5
			}
		},

		{"type": "FollowSpiral", "config": {"enabled": true, "diameter": 4, "step_size": 40}}
	],
	"map_object_cache_time": 5,
	"forts": {"avoid_circles": false, "max_circle_size": 40, "cache_recent_forts": true},
	"alt_min":	40,
	"alt_max":	60,
    "sleep_schedule": [
		{"time": "23:45", "duration": "00:20", "time_random_offset": "00:30", "duration_random_offset": "00:30", "wake_up_at_location": ""},
		{"time": "13:05", "duration": "00:20", "time_random_offset": "01:00", "duration_random_offset": "00:30", "wake_up_at_location": ""}
    ],
	"gps_default_altitude":		150.0,
	"replicate_gps_xy_noise":	false,
	"replicate_gps_z_noise":	false,
	"debug":				false,
	"test":					false,
	"walker_limit_output":	true,
	"health_record":		false,
	"location_cache":		false,
	"distance_unit":		"m",
	"reconnecting_timeout":	50,
	"logging": {"color": false, "show_datetime": true, "show_process_name": false, "show_log_level": false, "show_thread_name": false},
	"catch": {"any": {"always_catch" : true}},
	"release": {"any": {"release_below_cp": 0, "release_below_iv": 0.95, "logic": "or"}}
}

### Output when issue occurred
 Pokemon: 127/250 | Items: 314/350 | Pokeballs: 128 | GreatBalls: 57

repeated many times.
### Other Information
OS:  Windows 10
 
Branch: master
Git Commit: 11123a82cb18c172a262dc9e46e7b2c175666828
Python Version: 2.7.12

**Comment by sohje** [comment]
Softbanned?
