### ISSUE TITLE
Bounty source or other crowd source integration

### ISSUE THREAD

**Issue by solderzzc** [PokemonGoF/PokemonGo-Bot#5304]
Although the devs don't contribute for money in this project, but still they've spent much effort. It really help people to understand how to program in python and keep out of the dangerous area.
So if you want to show your support, please use the third part crowd source tools to encourage people here.

BTW, I don't familiar with https://www.bountysource.com or other tools, so please advise.

**Comment by Gobberwart** [comment]
Feel free to send us beer, wine, whisky (single-malt please) or any other goodies you like :)

**Comment by solderzzc** [comment]
This one is also interesting:
https://github.com/tip4commit/tip4commit

**Comment by solderzzc** [comment]
And this one:
https://github.com/WhisperSystems/BitHub

**Comment by TheSavior** [comment]
I really strongly don't want any type of these things hooked up to the project. As soon as money becomes involved at all, the likelihood that any developer who has ever worked on this project is at risk of being liable in a lawsuit goes up. 

I understand that the intention here is to get people to stick around longer, but I don't think this approach is worth the tradeoffs. The risk with this to all people who have ever contributed is too high.

**Comment by mjmadsen** [comment]
I think I like tip4commit most. Seems to be better documented than BitHub. I also like that it's a percentage of currently available funds and not a flat per commit amount. 

With bountysource. we will probably only see donations for certain FR and the like. But not for refactoring, bug solving, etc. 

We could just pull the trigger and try one, if we don't like it switch to something else?

**Comment by Gobberwart** [comment]
Agree with @TheSavior. As nice as it would be to get paid for work, I'm treating it as a training/learning opportunity.

**Comment by mjmadsen** [comment]
And a nice portfolio builder. :smile:

**Comment by solderzzc** [comment]
Before SEO notice, let's hide this issue.
