### ISSUE TITLE
PokemonOptimizer does not handle Eevee with my config

### ISSUE THREAD

**Issue by liejuntao001** [PokemonGoF/PokemonGo-Bot#5315]
### Expected Behavior

PokemonOptimizer leaves all the Eevees untouched with my config
I don't feel it's right.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

        {
            "type": "PokemonOptimizer",
            "config": {
                "enabled": true,
                "transfer": true,
                "transfer_wait_min": 4,
                "transfer_wait_max": 6,
                "evolve": true,
                "evolve_time": 25,
                "evolve_for_xp": true,
                "evolve_only_with_lucky_egg": false,
                "evolve_count_for_lucky_egg": 72,
                "may_use_lucky_egg": true,
                "upgrade": true,
                "upgrade_level": 60,
                "min_slots_left": 5,
                "groups": {
                    "gym": ["Dragonite", "Snorlax", "Lapras", "Arcanine"],
                    "my_love": ["Pikachu"],
                    "vip": ["Exeggutor", "Blastoise", "Vaporeon", "Gyarados", "Flareon", "Venusaur", "Jolteon"]
                },
                "keep": [
                    {
                        "mode": "by_family",
                        "top": 1,
                        "sort": [{"iv": 0.9}],
                        "evolve": true,
                        "upgrade": false
                    },
                    {
                        "mode": "by_family",
                        "top": 1,
                        "sort": [{"ncp": 0.9}],
                        "evolve": true,
                        "upgrade": false
                    },
                    {
                        "mode": "by_family",
                        "top": 1,
                        "sort": ["cp"],
                        "evolve": false,
                        "upgrade": false
                    },
                    {
                        "mode": "by_family",
                        "names": ["gym"],
                        "top": 3,
                        "sort": [{"iv": 0.9}, {"ncp": 0.9}],
                        "evolve": true,
                        "upgrade": true
                    },
                    {
                        "mode": "by_pokemon",
                        "names": ["vip"],
                        "top": 3,
                        "sort": [{"iv": 0.9}, {"ncp": 0.9}],
                        "evolve": true,
                        "upgrade": false
                    },
                    {
                        "mode": "by_family",
                        "names": ["my_love"]
                    }
                ]
            }
        },

### Output when issue occurred

[2016-09-08 19:29:37] [PokemonOptimizer] [INFO] Pokemon Bag: 245/250
[2016-09-08 19:29:37] [PokemonOptimizer] [INFO] Transferring 70 Pokemon
...
[2016-09-08 19:35:52] [PokemonOptimizer] [INFO] Pokemon Bag: 175/250
[2016-09-08 19:35:52] [PokemonOptimizer] [INFO] Waiting for more Pokemon to evolve with lucky egg: 28/72
[2016-09-08 19:35:52] [PokemonOptimizer] [INFO] Upgrading 0 Pokemon [304643 stardust]

I still have many Eevees in bag

[2016-09-08 21:30:22] [PokemonGoBot] [INFO] #133 Eevee[13][87 candies]
[2016-09-08 21:30:22] [PokemonGoBot] [INFO] #134 Vaporeon[1][87 candies]
[2016-09-08 21:30:22] [PokemonGoBot] [INFO] #135 Jolteon[1][87 candies]
[2016-09-08 21:30:22] [PokemonGoBot] [INFO] #136 Flareon[2][87 candies]
 
Branch: 
master
Git Commit: 
11123a82cb18c172a262dc9e46e7b2c175666828

**Comment by Anakin5** [comment]
You can read the part about Eevee in the documentation.
Basically, what is happening is that all the Eevee in your bag are somehow better than one of the Vaporeon, Jolteon or Flareon. (somehow = depending on your rules, for either iv, cp or ncp is better).
 Give me all their iv, cp and ncp Andi can tell you in detail why they are kept.

**Comment by liejuntao001** [comment]
I think you are right. it's truly complex case.
maybe I should drop the (CP 37, IV 0.93) flareon?

[2016-09-09 08:16:45] [PokemonGoBot] [INFO] #133 Eevee[13][87 candies]: (CP 46, IV 0.89) | (CP 14, IV 0.82) | (CP 506, IV 0.69
) | (CP 276, IV 0.4) | (CP 581, IV 0.78) | (CP 458, IV 0.58) | (CP 406, IV 0.69) | (CP 524, IV 0.71) | (CP 298, IV 0.8) | (CP
14, IV 0.67) | (CP 238, IV 0.89) | (CP 379, IV 0.73) | (CP 582, IV 0.29)
[2016-09-09 08:16:45] [PokemonGoBot] [INFO] #134 Vaporeon[1][87 candies]: (CP 996, IV 0.51)
[2016-09-09 08:16:45] [PokemonGoBot] [INFO] #135 Jolteon[1][87 candies]: (CP 222, IV 0.93)
[2016-09-09 08:16:45] [PokemonGoBot] [INFO] #136 Flareon[2][87 candies]: (CP 37, IV 0.93) | (CP 1490, IV 0.91)

**Comment by Anakin5** [comment]
Ok, the iv of your best Vaporeaon is 0.51. So every Eevee with an iv greater than that is a potential candidate to replace hi, as "best iv". There is 12 of your 13 Eevee that have iv better than that.

Then, the 13th Eevee is kept because of its high CP (582). Which makes him both best CP and best NCP if he ever becomes a Jolteon for example.

On the long run, you will have less and less Eevee kept like that but for now, some of the evolutions are weak and a lot of Eevee are better. If you have place in your bag, there is no reason to touch anything, just let it like that.
