### ISSUE TITLE
Now at Pokestop: Unknown - Spinning...

### ISSUE THREAD

**Issue by nvhk** [PokemonGoF/PokemonGo-Bot#532]
### Expected Behavior
When bot is running about 1h is error with unknows pokestops, after restart is ok. 

### Actual Behavior

> 2016-07-24 01:30:06 [#] Now at Pokestop: St Regis Hotel Landmark Plaque  - Spinning...
> 2016-07-24 01:30:09 [+] Loot:
> 2016-07-24 01:30:09 [+] 50 xp
> 2016-07-24 01:30:09 [+] 2x Pokeball
> 2016-07-24 01:30:09 [+] 1x Razz Berry
> [2016-07-24 01:30:09] [#] PokeStop on cooldown. Time left: 5.00 minutes
> [2016-07-24 01:30:11] [#] Found fort 148dbe8cc54b489db4679676997ac327.16 at distance 0.74km
> [2016-07-24 01:30:11] [#] Need to move closer to Pokestop
> [2016-07-24 01:30:11] [#] Walking from (40.761425, -73.974639) to (40.76058, -73.982849) for approx. 28.00 seconds
> [2016-07-24 01:31:00] [#] Finished walking
> [2016-07-24 01:31:00] [#] Arrived at Pokestop
> 2016-07-24 01:31:03 [#] Now at Pokestop: Unknown - Spinning...
> [2016-07-24 01:31:16] [#] Found fort 3cd2573b8bde4a5dae645c75041e0bd3.16 at distance 0.58km
> [2016-07-24 01:31:16] [#] Need to move closer to Pokestop
> [2016-07-24 01:31:16] [#] Walking from (40.76058, -73.982849) to (40.762054, -73.982709) for approx. 7.00 seconds
> [2016-07-24 01:31:25] [#] Finished walking
> [2016-07-24 01:31:25] [#] Arrived at Pokestop
> 2016-07-24 01:31:28 [#] Now at Pokestop: Unknown - Spinning...
> [2016-07-24 01:31:40] [#] Found fort 3d56f4fe8213411b80c09dc043d894ff.16 at distance 0.62km
> [2016-07-24 01:31:40] [#] Need to move closer to Pokestop
> [2016-07-24 01:31:40] [#] Walking from (40.762054, -73.982709) to (40.761361, -73.981574) for approx. 5.00 seconds
> [2016-07-24 01:31:44] [#] Finished walking
> [2016-07-24 01:31:44] [#] Arrived at Pokestop
> 2016-07-24 01:31:48 [#] Now at Pokestop: Unknown - Spinning...
> [2016-07-24 01:31:58] [#] Found fort 40d8febaf79e4a558b012b76836ebdd7.16 at distance 0.70km
> [2016-07-24 01:31:58] [#] Need to move closer to Pokestop
> [2016-07-24 01:31:58] [#] Walking from (40.761361, -73.981574) to (40.760417, -73.98023) for approx. 7.00 seconds
> [2016-07-24 01:32:05] [#] Finished walking
> [2016-07-24 01:32:06] [#] Arrived at Pokestop
> 2016-07-24 01:32:08 [#] Now at Pokestop: Unknown - Spinning...
> [2016-07-24 01:32:20] [#] Found fort 5af685cdc2284317a4387ca739fe35e5.12 at distance 0.76km
> [2016-07-24 01:32:20] [#] Need to move closer to Pokestop
> [2016-07-24 01:32:20] [#] Walking from (40.760417, -73.98023) to (40.75991, -73.980227) for approx. 3.00 seconds
> [2016-07-24 01:32:25] [#] Finished walking
> [2016-07-24 01:32:25] [#] Arrived at Pokestop
> 2016-07-24 01:32:26 [#] Now at Pokestop: Unknown - Spinning...
> [2016-07-24 01:32:34] [#] Found fort 615de11d28584c7198c72af1fe90f207.16 at distance 0.58km
> [2016-07-24 01:32:34] [#] Need to move closer to Pokestop
> [2016-07-24 01:32:34] [#] Walking from (40.75991, -73.980227) to (40.761638, -73.981273) for approx. 9.00 seconds
> [2016-07-24 01:32:46] [#] Finished walking
> [2016-07-24 01:32:46] [#] Arrived at Pokestop
> 2016-07-24 01:32:49 [#] Now at Pokestop: Unknown - Spinning...
> [2016-07-24 01:33:03] [#] Found fort 83dfd3d072804185996bb62dee3c40a5.12 at distance 0.61km
> [2016-07-24 01:33:03] [#] Need to move closer to Pokestop
> [2016-07-24 01:33:03] [#] Walking from (40.761638, -73.981273) to (40.76132, -73.980469) for approx. 4.00 seconds
> [2016-07-24 01:33:07] [#] Finished walking
> [2016-07-24 01:33:07] [#] Arrived at Pokestop
> 2016-07-24 01:33:08 [#] Now at Pokestop: Unknown - Spinning...
> [2016-07-24 01:33:20] [#] Found fort 97d9f7b7ea9745268313605593b54def.16 at distance 0.65km
> [2016-07-24 01:33:20] [#] Need to move closer to Pokestop
> [2016-07-24 01:33:20] [#] Walking from (40.76132, -73.980469) to (40.761009, -73.981328) for approx. 4.00 seconds
> [2016-07-24 01:33:25] [#] Finished walking
> [2016-07-24 01:33:25] [#] Arrived at Pokestop
> 2016-07-24 01:33:27 [#] Now at Pokestop: Unknown - Spinning...
> [2016-07-24 01:33:41] [#] Found fort c3aa5f44cb1d439795649f55f14490fb.16 at distance 0.74km
> [2016-07-24 01:33:41] [#] Need to move closer to Pokestop
> [2016-07-24 01:33:41] [#] Walking from (40.761009, -73.981328) to (40.760348, -73.982169) for approx. 5.00 seconds
> [2016-07-24 01:33:48] [#] Finished walking
> [2016-07-24 01:33:48] [#] Arrived at Pokestop
> 2016-07-24 01:33:49 [#] Now at Pokestop: Unknown - Spinning...
> [2016-07-24 01:33:56] [#] Found fort c470931fb9684f37a53b203fe81ffee6.16 at distance 0.58km
> [2016-07-24 01:33:56] [#] Need to move closer to Pokestop
> [2016-07-24 01:33:56] [#] Walking from (40.760348, -73.982169) to (40.761851, -73.982214) for approx. 7.00 seconds
> [2016-07-24 01:34:05] [#] Finished walking
> [2016-07-24 01:34:05] [#] Arrived at Pokestop
> 2016-07-24 01:34:07 [#] Now at Pokestop: Unknown - Spinning...
> [2016-07-24 01:34:16] [#] Found fort e155687f70904feab9bc4df61f87b467.16 at distance 0.65km
> [2016-07-24 01:34:16] [#] Need to move closer to Pokestop
> [2016-07-24 01:34:16] [#] Walking from (40.761851, -73.982214) to (40.761379, -73.982853) for approx. 4.00 seconds
> [2016-07-24 01:34:20] [#] Finished walking
> [2016-07-24 01:34:20] [#] Arrived at Pokestop
> 2016-07-24 01:34:23 [#] Now at Pokestop: Unknown - Spinning...
> [2016-07-24 01:34:32] [#] Found fort 09ca7bad34964cf7b25e4c699c8af81d.16 at distance 0.84km
> [2016-07-24 01:34:32] [#] Need to move closer to Pokestop
> [2016-07-24 01:34:32] [#] Walking from (40.761379, -73.982853) to (40.760353, -73.974188) for approx. 30.00 seconds
> ^C2016-07-24 01:34:36 [x] Exiting PokemonGo Bot

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by sinistance** [comment]
`Unknown` mean there is an API issue while getting the pokestop name. in that way you can still continue instead of stopped by crash 😄

**Comment by zx900930** [comment]
Same problem here,  once it get the first `Pokestop: Unknown`, it will be an infinite loop(no pokemon capture during the loop) .
I think the bot should stop and rescan when it get the first `Pokestop: Unknown`.

**Comment by vtuan10** [comment]
+1

**Comment by StahlJonas** [comment]
i have the same problem

**Comment by fuzha** [comment]
same problem here

**Comment by surfaace** [comment]
please provide git commit

Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by TSM-EVO** [comment]
I get the same issue, usually after 30 minutes of running the bot, it seems. I'll keep an eye on this and post updates here.

**Comment by TSM-EVO** [comment]
`[2016-07-25 12:47:22] [#] Need to move closer to Pokestop
[2016-07-25 12:47:22] [#] Walking from (-33.865762, 151.190796) to (-33.864821, 151.192112) for approx. 39.00 seconds
[2016-07-25 12:48:32] [#] Finished walking
[2016-07-25 12:48:32] [#] Arrived at Pokestop
[2016-07-25 12:48:34] [#] Now at Pokestop: Unknown - Spinning...
[2016-07-25 12:48:41] [#] Found fort 67d0a962795d4a4781ca55e7e64da8d6.16 at distance 0.91km
[2016-07-25 12:48:41] [#] Need to move closer to Pokestop
[2016-07-25 12:48:41] [#] Walking from (-33.864821, 151.192112) to (-33.864525, 151.191362) for approx. 19.00 seconds
[2016-07-25 12:49:13] [#] Finished walking
[2016-07-25 12:49:13] [#] Arrived at Pokestop
[2016-07-25 12:49:15] [#] Now at Pokestop: Unknown - Spinning...
[2016-07-25 12:49:23] [#] Found fort 207421ae35e84b91a7533b558583c0d4.16 at distance 0.73km
[2016-07-25 12:49:23] [#] Need to move closer to Pokestop
[2016-07-25 12:49:23] [#] Walking from (-33.864525, 151.191362) to (-33.877896, 151.194615) for approx. 6.08 minutes
`

I get the same thing

git log -n 1 --pretty=format:6bc4b168c26d876d9981f01f3a1bdd3b80fc3e16

**Comment by lvieirajr** [comment]
+ 1
335a0aa9a6e57fef17d0865b2f404e0ca785124b

**Comment by surfaace** [comment]
#643
