### ISSUE TITLE
[Feature Request] Check nearby pokemon list - if VIP present, try to find it

### ISSUE THREAD

**Issue by ravey-davey** [PokemonGoF/PokemonGo-Bot#5325]
Using the nearby Pokemon list (which must exist somewhere), if a pokemon on you VIP list is present, attempt to find it using walking in circles

### Possible solution
The assumption here is that the nearby pokemon list is accessible. If so, in theory it should be possible to modify the walking parameters to walk in a 200 metre circumference to attempt to find it.

### How it would help others
Allows finding VIP (could be a specific Pokemon you're looking for, or something you're not captured yet) that maybe nearby that otherwise could be missed due to the bot's walking pattern.

**Comment by Anakin5** [comment]
Actually we have a location point for nearby pokemons. That is not an exact point but it gives the direction.
I have created a task to move to nearby pokemons, will test it and see how it goes.

**Comment by muffettsman** [comment]
or how about have it just read from the Pokemon-Go Map database -- take into consideration the despawn timer and calculate if you can get to that location in time (or better 'stick to roads' and get there at driving speeds :D lol

**Comment by davidakachaos** [comment]
That's different because some people (like me) don't use the map feature at all. And this is more human-like behaviour; when you see a Pokemon we want you will start searching for it :smiley: We just get lucky with the direction of where to search.

**Comment by ravey-davey** [comment]
Might be worth adding that upon finding it you could choose to set the action as snipe or walk_to in order to try to catch pokemon..

**Comment by Anakin5** [comment]
You cannot snipe as you do not have a precise location

**Comment by amal** [comment]
There was a pull request for the nearby scanning, but it wasn't merged.
See: #2453  Add simple nearby pokemon hunter cellworker (+ radar output feature)

**Comment by Anakin5** [comment]
Thabk Amal. Well I did not see that so I rewrote everything. Testing now and will commit a PR soon.
