### ISSUE TITLE
Starting bot error

### ISSUE THREAD

**Issue by zZzWhoAmIzZz** [PokemonGoF/PokemonGo-Bot#5328]
Install By: ./setup.sh -i
Run By: ./run.sh
OS: Ubuntu 14.04.4 LTS
Branch: master
Python Version: Python 2.7.12
![ss](https://cloud.githubusercontent.com/assets/21981334/18385958/384515c0-76c6-11e6-8f56-e7b02fca9a05.png)

**Comment by alephmelo** [comment]
I'm having this issue as well. 

`commit: 7a6a5f09`
