### ISSUE TITLE
Bot would not keep Greatball

### ISSUE THREAD

**Issue by xSkav** [PokemonGoF/PokemonGo-Bot#5331]
### Expected Behavior

Having my item filter to keep greatball at an amount . 

### Actual Behavior

Bot not keeping any Greatball 

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/5ucCQY5N

### Output when issue occurred

[2016-09-09 14:41:06] [MainThread] [UpdateLiveInventory] [INFO] Pokemon: 244/250 | Items: 314/350 | Pokeballs: 134 | GreatBalls: 0 | UltraBalls: 122 | RazzBerries: 14 | LuckyEgg: 6

### Other Information
OS: Windows 10 64 bit
 
Branch: dev
 
Git Commit: 
 
Python Version: Python 2.7.12
 
Any other relevant files/configs (eg: path files)

**Comment by Anakin5** [comment]
There is no parameter that exist today to keep a minimum number of items. The parameter define a maximum number of items.

**Comment by kureijir** [comment]
Set `"max_balls_keep"` to, for example 200, then remove everything in `"item_filter"`, and it will keep best 200 balls.

      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 13,
          "max_balls_keep": 200,
          "max_potions_keep": 20,
          "max_berries_keep": 50,
          "max_revives_keep": 20,
          "item_filter": {},
          "recycle_wait_min": 3,
          "recycle_wait_max": 5,
          "recycle_force": true,
          "recycle_force_min": "00:01:00",
          "recycle_force_max": "00:05:00"
        }
      },

**Comment by mmixx** [comment]
Or like what I'm using...
```
      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 15,
          "max_balls_keep": 120,
          "max_potions_keep": 50,
          "max_berries_keep": 50,
          "max_revives_keep": 50,
          "item_filter": {
            "Pokeball":       { "keep" : 50 },
            "Greatball":      { "keep" : 50 },
            "Ultraball":      { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 50 }
          },
          "recycle_wait_min": 3,
          "recycle_wait_max": 5,
          "recycle_force": true,
          "recycle_force_min": "00:01:00",
          "recycle_force_max": "00:05:00"
        }
      },
```

**Comment by xSkav** [comment]
mmixx . i actually only put 20 pokeball to keep . but its still doesnt keep any greatball . so i run out of pokeballs to catch . so i switch it back to higer pokeball amount

**Comment by alexyaoyang** [comment]
@xSkav Like @Anakin5 said, the `keep` value in `item_filter` means the # of that item to keep when Recycling Items, not the minimum # of that item the bot will save for you.

Unfortunately, this is an expected pattern as your account level levels up (higher level account encounters higher level pokemon). 

However, this brings up a good point, I just checked my logs and it seems like our bot is using ultraballs on VIP pokemons only. I'll open a separate issue and ask for verifications.
