### ISSUE TITLE
Polyline Walker moves in zigzag

### ISSUE THREAD

**Issue by kureijir** [PokemonGoF/PokemonGo-Bot#5333]
### Expected Behavior
Move path should look like this: (screenshot taken with commit ca94424f688bc8080db055d1b9443c3c8d8212fb)
http://imgur.com/rqfxWVu

### Actual Behavior
After updating to commit 11123a82cb18c172a262dc9e46e7b2c175666828 it looks like this:
http://imgur.com/xcYokPc
It slows down overall movement speed of the bot a bit and it looks annoying.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/RP104P55

### Other Information
OS: 
Arch Linux ARM
Branch: 
master
Git Commit: 
11123a82cb18c172a262dc9e46e7b2c175666828
Python Version: 
2.7.12

**Comment by crvfts** [comment]
try "enable_social": false, and remove the entire FollowSpiral task. Doing this solved this issue for me.

**Comment by Anakin5** [comment]
Yes, it is your FollowSpiral that creates these pattern. Remove that tasks, you don't need it.

**Comment by kureijir** [comment]
Thanks, just wonder why it's been working fine until I updated. And what's that task for anyway?

**Comment by Anakin5** [comment]
It is for moving in zigzag and getting people to open issue tickets. It is pretty good at it ;)
