### ISSUE TITLE
Your Pokemon inventory is full! Could not catch!

### ISSUE THREAD

**Issue by shudack** [PokemonGoF/PokemonGo-Bot#5335]
When pokemon bag is full, don't transfer any pokemon..

No erros, only have the message : 
[PokemonCatchWorker] [pokemon_inventory_full] Your Pokemon inventory is full! Could not catch!

My config:
http://pastebin.com/VbZNt3Gw

**Comment by bjchristenson** [comment]
Check the **release** in the config. Your ANY will not match any Pokemon. You may want to do something like the following to save the best 2 with highest CP and best 2 with highest IV:

"any": {"keep_best_cp": 2, "keep_best_iv": 2},

**Comment by crvfts** [comment]
Your release criteria is only ""any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},".

**Comment by shudack** [comment]
Thanks!

Who's the best config?

**Comment by shudack** [comment]
It's possible?

"release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Keep no more than 3 best IV pokemon for every pokemon type": {},
      "// any": {"keep_best_iv": 3},
      "// Discard all pokemon in bag except 100 pokemon with best CP": {},
      "all": {"keep_best_cp": 100},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "Zubat": {"keep_best_cp": 2, "keep_best_iv": 3},
      "// Example of custom order of static criterion": {},
      "// Zubat": {"keep_best_custom": "iv, cp, hp_max", "amount":2}
    },

**Comment by crvfts** [comment]
"release": {
"all": {"keep_best_cp": 100},
"Pidgey": {"keep_best_cp": 3},
"Zubat": {"keep_best_cp": 2, "keep_best_iv": 3}
},

Will work OK

**Comment by shudack** [comment]
Thanks for help!

**Comment by shudack** [comment]
I will test config.json.pokemon.example...
