### ISSUE TITLE
[BUG] Bot should be keeping a 0.91 iv Magikarp, but transfers it instead with the correct rules.

### ISSUE THREAD

**Issue by crazy4ever** [PokemonGoF/PokemonGo-Bot#534]
### Expected Behavior

Keep the magikarp

### Actual Behavior

Trashing the Magikarp

### Steps to Reproduce

use the latest commit as of posting this.

### Other Information

[x] Captured Magikarp! [CP 26] [IV 0.91] - Checking Release Config
[x] Release config for Magikarp: CP 800 or IV 0.8
[#] Magikarp has been exchanged for candy!

{
    "any": {
        "min_cp": 800,
        "min_iv": 0.8,
        "cp_iv_logic": "or"
    },

**Comment by DanielHeckrath** [comment]
If you want to keep a high IV pokemon with low CP you have to use cp_iv_logic = and.
For your config the magickarp would have been kept if it also had >800 cp.

With cp_iv_logic = or the pokemon is released if one of the conditions is met, so in your case the magikarps cp was below 800.

**Comment by crazy4ever** [comment]
Hmm, 

from looking at it I thought "cp_iv_logic": "or" would mean either of them. 

So it would keep the pokemon if it was either higher then 800 cp **OR** higher then 0.8 iv, 1 of the 2.

**Comment by pol0nium** [comment]
Nope, it's a release logic, not keeping logic. @DanielHeckrath is right.

**Comment by crazy4ever** [comment]
Alright, Thanks for the clarity, will change it. Close the Issue if you want. :)

**Comment by boriss579** [comment]
So if I write -
"release_under_cp": 2500,
        "release_under_iv": 0.95,
        "cp_iv_logic": "and"

It will keep only high IV Pokémon and release all others no matter their CP right?
(unless I manage to find a Pokémon with 2500+ CP yes :P)
