### ISSUE TITLE
Investigate usage of FakeBot and  mock all the methods it should mock

### ISSUE THREAD

**Issue by th3w4y** [PokemonGoF/PokemonGo-Bot#5344]
While investigating travis build speed issue I noticed https://github.com/PokemonGoF/PokemonGo-Bot/issues/5339 Investigation revealed sleep_schedule_test was using FakeBot(0 as a mocker but that class currently does not mock properly the event manager

Fix https://github.com/PokemonGoF/PokemonGo-Bot/pull/5343

**Comment by th3w4y** [comment]
There is not much usage of FakeBot() everywhere we use MagicMock() except:
```

pokemongo_bot/test/log_interval_test.py:from tests import FakeBot
pokemongo_bot/test/log_interval_test.py:        self.bot = FakeBot()
pokemongo_bot/test/sleep_schedule_test.py:from tests import FakeBot
tests/location_parser_test.py:from tests import FakeBot
tests/location_parser_test.py:        self.bot = FakeBot()
tests/update_live_stats_test.py:from tests import FakeBot
tests/update_live_stats_test.py:        self.bot = FakeBot()
```

**Comment by th3w4y** [comment]
Marked as a bug due to potential issues of the mock of the above mentioned..

Will go through them and inspect

**Comment by k4n30** [comment]
@th3w4y update?

**Comment by th3w4y** [comment]
@k4n30  i will close.... my investigation revealed no issues... FakeBot() was not that used...
