### ISSUE TITLE
-it Flag: "expected one argument"

### ISSUE THREAD

**Issue by IcicleTF** [PokemonGoF/PokemonGo-Bot#535]
### Expected Behavior
Initial transfer - all pokemon with cp lower than highest are transfered.

### Actual Behavior
pokecli.py error: argument -it/--initial_transfer: expected one argument.
(Seems to be expecting an integer)

### Steps to Reproduce
Using "-it" or "--initial_transfer" in command line.

### Other Information
OS: Windows 10

**Comment by lpc921** [comment]
That integer is CP

**Comment by IcicleTF** [comment]
Huh, alright. In that case, after some more looking, it will automatically do a initial transfer even without the flag, it seems.

**Comment by surfaace** [comment]
-it requires CP input
