### ISSUE TITLE
Unsuccessful in setting VIP status based on CP and IV

### ISSUE THREAD

**Issue by mli1990** [PokemonGoF/PokemonGo-Bot#5357]
### Expected Behavior
Set VIP status to pokemon that meet CP and IV criteria

### Actual Behavior
Not setting VIP status to those pokemon

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
    "vips" : {
      "Any pokemon put here directly force to use Berry & Best Ball to capture": {},
      "Caterpie": { "catch_above_cp": 35, "catch_above_iv": 0.1, "logic": "and" },
      "Weedle": { "catch_above_cp": 35, "catch_above_iv": 0.1, "logic": "and" },
      "Pidgey": { "catch_above_cp": 53, "catch_above_iv": 0.1, "logic": "and" },
      "Rattata": { "catch_above_cp": 46, "catch_above_iv": 0.1, "logic": "and" },
      "Metapod": { "catch_above_cp": 37, "catch_above_iv": 0.1, "logic": "and" },
      "Kakuna": { "catch_above_cp": 38, "catch_above_iv": 0.1, "logic": "and" },
      "Pidgeotto": { "catch_above_cp": 96, "catch_above_iv": 0.1, "logic": "and" },
      "Butterfree": { "catch_above_cp": 114, "catch_above_iv": 0.1, "logic": "and" },
      "Beedrill": { "catch_above_cp": 113, "catch_above_iv": 0.1, "logic": "and" },
      "Pidgeot": { "catch_above_cp": 164, "catch_above_iv": 0.1, "logic": "and" },
      "Raticate": { "catch_above_cp": 113, "catch_above_iv": 0.1, "logic": "and" },
      "Articuno": { },
      "Zapdos": { },
      "Moltres": { },
      "Mewtwo": { },
      "Mew": { }
    },

### Output when issue occurred
![image](https://cloud.githubusercontent.com/assets/22008624/18408130/0ad4e7ea-76f4-11e6-8a9b-a769a4422aca.png)

### Steps to Reproduce
Set VIP status based on CP and IV with the 'and' operator, and go find that pokemon

### Other Information
OS: Windows
Git Commit:

**Comment by RedViper9** [comment]
Are you still having this issue? Please fill out the full issue template.
Which commit are you on?
