### ISSUE TITLE
Telegram bot not working with fresh dev branch

### ISSUE THREAD

**Issue by javajohnHub** [PokemonGoF/PokemonGo-Bot#5358]
No password nor master configured in TelegramTask section, bot will not accept any commands

I have my master set and my key set.

**Comment by ShiLingStar** [comment]
I got the same with log:
> [2016-09-09 22:29:22] [PokemonGoBot] [INFO] Telegram message from "USERNAME" (XXXXXXXX): /info
[2016-09-09 22:29:22] [PokemonGoBot] [ERROR] Telegram message received from unknown sender. Please either make sure your username or ID is in TelegramTask/master, or a password is set in TelegramTask section and /login is issued

Does not seems to have any documentation about adding password in the TelegramTask at the moment,

**Comment by lntn** [comment]
I also received this

> [2016-09-10 16:04:42] [PokemonGoBot] Telegram bot not running. Starting

**Comment by lntn** [comment]
It's weird. I sent /info command, nothing appears in the log.
Then I stop & start the bot again, the command appears as
```
[PokemonGoBot] Telegram message from  (....): /info
```

right after being started

**Comment by javajohnHub** [comment]
It's looking for a password in the config. I don't remember getting a telegram password and there is no password option in the config.

**Comment by javajohnHub** [comment]
if self.config.get('password', None) == None and (not hasattr(self, "master") or not self.master): # no auth provided in config
                        self.sendMessage(chat_id=update.message.chat_id, parse_mode='Markdown', text="No password nor master configured in TelegramTask section, bot will not accept any commands")
                        continue

**Comment by DBa2016** [comment]
I suggest you guys look into the docs/telegramtask.md file. It tells explicitly about authentication options.

If you configured authentication but it does not work, please provide your conf file(s), stripped of sensitive information (keys).

**Comment by javajohnHub** [comment]
The docs say 2 possible ways. This way works on master branch. This is my config for TelegramTask:

"tasks": [
      {
        "type": "TelegramTask",
        "config": {
          "enabled": true,
          "master": *******,
          "// old syntax, still supported: alert_catch": ["all"],
          "// new syntax:": {},
          "alert_catch": {
            "all": {"operator": "or", "cp": 0, "iv": 0.95}
          }
        }
      },

and auth:
{
    "auth_service": "ptc",
    "username": "**********",
    "password": "*******",
    "location": "42.3295, -83.0396",
    "favorite_locations":[
        {"name": "Milan", "coords": "45.472849,9.177567"}
    ],
    "gmapkey": "************",
    "encrypt_location": "",
    "telegram_token": "**************",
    "discord_token": ""
}

**Comment by javajohnHub** [comment]
@lntn I also have that happening.
[PokemonGoBot] Telegram message from  (1234567): /info

 It shows the request came from my master id. But telegram gives this error:
**No password nor master configured in TelegramTask section, bot will not accept any commands**

**Comment by javajohnHub** [comment]
How do you obtain a password....i dont see the option anywhere

**Comment by javajohnHub** [comment]
Ok so Problem solved. 
You just set the pw manually in the config.

"tasks": [
      {
        "type": "TelegramTask",
        "config": {
          "enabled": true,
          "password": "*******",
          "alert_catch": {
            "all": {"operator": "or", "cp": 0, "iv": 0.95}
          }
        }
      },

and the /login <password>

**Comment by lntn** [comment]
@javajohnHub no it's not right.
The MD file says there are 2 ways to authenticate, either by MASTER (userid) or PASSWORD (manual login). I have had the master set, but it's not working.
It was working with the master ID alone previously.
