### ISSUE TITLE
Log spam with candy threshold messages

### ISSUE THREAD

**Issue by lntn** [PokemonGoF/PokemonGo-Bot#5361]
### Expected Behavior
Not sure

### Actual Behavior
Got spammed with messages about candy amount over threshold every second, without knowing what to do.
```
Amount of candies for Kakuna is 1994, greater than threshold 400
```
But then what? what am I supposed to do?

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/qWRy6i4e

### Output when issue occurred
http://pastebin.com/CYUCR1D8

### Other Information
OS: 
Mac
Branch: 
dev
Git Commit: 
f02ce439aa4e6f6c14c9a2aafb8fea848ac6a6ca

**Comment by Anakin5** [comment]
It is in your config: `"any": {"candy_threshold" : 400, "catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"}`

**Comment by lntn** [comment]
@Anakin5 indeed

**Comment by lntn** [comment]
@Anakin5 sorry but why closing this? the problem is with that log message appearing every second.

**Comment by Anakin5** [comment]
Ok

**Comment by Gobberwart** [comment]
Wow, this is definitely an issue. Why on earth are we displaying this event????

**Comment by Gobberwart** [comment]
#5604 fixes this.
