### ISSUE TITLE
Proposal for ConcurentWalking "Rickshaw" sharing between the tasks that have to walk

### ISSUE THREAD

**Issue by th3w4y** [PokemonGoF/PokemonGo-Bot#5367]
**Below proposal is related to all tasks that are changing bot.position [via StepWalker]**

Currently we achieve already a great deal (almost everywhere) to standardise the bot.position changes to only use the StepWalker.step() [be it the PolylineWalker(StepWalker)]

**Assumptions:**
- 90% of users don't deviate much from the documented config.json.example
- We expect all the walking Tasks to befriend each other!
- Tasks have a .work() they calculate distances and do stuff here,  they create a step_walker = StepWalker() object and when they call step_walker.step() they expect True if bot has reached  the requested destination of False if walk is in progress...
- We don't want to spend time explaining the users what are valid walking task combinations and what not! or to explain them in what order the tasks should be configured....
- Things should just work!

**Identified Issues:**
- Different Tasks Concurrently request different Destinations [Classic example FollowSpiral conflicting with MoveToFort (_well actually conflicting with anything_)]
- Certain tasks want the bot.position to not change [loitering for example] and others want it to change.
- Tasks that use PolylineWalker are conflicting with task that don't use it

**Reason for the proposal against a refactoring alternative:**
- To much refactoring would be needed to solve above mentions points, in too many Tasks...,  Walkers... and so on... and so on...
- If i fuck up something the revert is to just undecorate the step() method in StepWalker

**Comment by th3w4y** [comment]
```
import inspect

class ConcurrentWalking(object):
    """
    Proposal for decorator that stores all tasks destinations and returns them to the Task call only in certain cases
    Assumming bot.position (0,0)

    Will check:


    - When two tasks are requesting different destinations Task1(0,0), (5, 5)):   Task2((0,0), (6, 6))
        We identify that the cost of reaching dest (5,5) is small than reaching dest (6, 6)
        cost(Task1) < cost(Task2)
        Thus:
            a) When Task2.work() calls walker.step()  step() will NOT be executed but will return False immediately
            b) When Task1.work() calls walker.step() step() will be executed and method will return whateve is needed

    - When two task have same destination Will check if one of them is a PolylineWalker and if that is the case
        will execute the .step() of the identified PolylineWalker object also for the Task that requested StepWalker!!!

    - Other things to check

        - Possibly check the priority based on the order of the tasks in config.json !!!


    """
    _WALKER_CONTAINER = data # [] pr {} - to be defined!!!

    def _step(foo):
        def magic(self):
            caller_stack = inspect.stack()[1][0]
            if 'self' in caller_stack.f_locals.keys():
                # We identified the callerTask
                callerTask = caller_stack.f_locals['self'].__class__.__name__
                print(caller)
                # Here we lookup the existing walker in the _WALKER_CONTAINER
                # and we'd identify their costs

                if cost(callerTask) = smallestCost:
                    foo(self)
                else:
                    return False
            else:
                # This is a pure new StepWalker().step() thus we return unmodified!
                foo(self)
        return magic
    @_step
    def step(self):
        print('True')
    _step = staticmethod(_step)


class StepWalker(object):
    """
    To mimic current StepWalker
    """
    ...

    # The only change in StepWalker will be decorating the step() function!!!!
    @ConcurrentWalking._step
    def step(self, speed=1):
    ...

```

**Comment by th3w4y** [comment]
And this would activate the cost calculations explained above  for every tasks... [the only change to existing code]

```

class StepWalker(object):
    """
    To mimic current StepWalker
    """
    ...

    # The only change in StepWalker will be decorating the step() function!!!!
    @ConcurrentWalking._step
    def step(self, speed=1):
    ...
```

**Comment by th3w4y** [comment]
I would want you input if i should start implement this proposal (Should be quite simple to do..) and what I should take into consideration in the cost functions:

For the moment i will make two big assumptions:
- Cost of staying put is 0
- Cost of teleporting   is -float("inf")
       - for the move to map for example [StepWalker().step(speed=float"inf")]

**Comment by sohje** [comment]
Just sleepy thoughts: why not just implement some sort of priority queue with some kind of limit over Walker; on step() method we will extract and calculate less cost position and move to that coords, etc?

**Comment by th3w4y** [comment]
@sohje I am afraid  that might not fix everything... [that will not allow to pass objects around...and replace one object type with another (PolylineWalker <==>StepWalker...)]

**Comment by mjmadsen** [comment]
I've been thinking about if our destination picking tasks (movetofort, catchpokemon, etc) help build a list of possible destinations (from all read cells). We then run an algorithm where we map out our next and future destinations - updating our path as we pick up new stops, new pokemon, etc. Maybe use a+ plus some priority bits based on config settings (rarer pokemon, etc), estimated exp gain by heading towards a larger group of lured stops, etc. Then our fort spinner and pokemon catching tasks don't call our stepper - instead only do those things and our walker task is the only thing directly using stepwalker. 

As an added bit, we could have our map show your planned route. To go a step further, we could use our starting position and a new config setting for max distance from the starting position - anything, except for VIP pokemon, outside of that range is ignored. That would solve a very old FR. 

I know this isn't quite what you're looking for as far as input, but I hope it can be helpful!

**Comment by th3w4y** [comment]
@mjmadsen yes i think i can solve all this with my above proposal... 
The decorator i am proposing can act like TrafficController

**Comment by th3w4y** [comment]
I don't have a fixation on decorator [some may be scared only when they read this word] approach but i see advantage:
- code readability
- separation of concerns
- being able to have 2 behaviours for same class decorated/undecorated

**Comment by sohje** [comment]
If i understand you correctly, we can make a singlton class and every task will get the same object.

**Comment by th3w4y** [comment]
@sohje every task will get "an" object the coordinated by logic one... in order to precompute paths and so on...

**Comment by th3w4y** [comment]
To simplify a bit currently:

**Phase 0**: # current implementation
- We have different mover Tasks  - they currently each call StepWalker.step()
- StepWalker handles next_point calculation bot.position setting and returns True or False.
- workers do 3 things...
 - identify destinations
 - wait for the destination to be reached
 - do their work

**Phase 1**:
Without refactoring all workers:
- we keep the StepWalker as is
- workers still expect a True or False from the .step() method but that is only to tell them if they reached a destination (and do their work accordingly...)
- We add a new coordinating class for walking directions to handle what the bot should do with the conflicting destinations requests or to generate the best path between the workers destinations requests. (if that would decorates .step() then would mean less refactoring...)
- use of inspect module in that coordinating class.. ensure we know everything about that Task we can identify  the caller and thus we can create a distance/task  based queuing/coordinating logic `{'MoveToFort':<StepWalker(12.3,12,4) _q36d74_>, 'FollowPath':<StepWalker(12.4,12,4) _au4g5_>}
`

**Phase 2**:
- we modify the workers to not send only one destination to StepWalker, but to possibly instantiate their step_walker differently:
`step_walker = StepWalker([(12.2, 12.2),(12.3, 12.2),(12.3, 12.3),(12.3, 12.4),(12.4, 12.4),(12.5, 12.5)])`
- workers do 3 things...
 - identify destinations and send the in a list of tuples to StepWalker
 - wait for ~~the~~ **"a"** destination to be reached (this will be the closest destination that was reached)
 - do their work
- coordinating class fetches those destinations and creates the walking route based on all the combined destination requests. 
- Computed path could be displayed on the web GUI!

**Comment by Anakin5** [comment]
> Identified Issues:

> - Different Tasks Concurrently request different Destinations [Classic example FollowSpiral conflicting with MoveToFort (well actually conflicting with anything)]
> - Certain tasks want the bot.position to not change [loitering for example] and others want it to change.
> - Tasks that use PolylineWalker are conflicting with task that don't use it

I don't understand this "conflict" issue. There is bug in MoveToFort line 112, it is returning SUCCESS instead of RUNNING. You change that single line and all the issues you mention above are gone.
Also my comments on each point:
- This is only true if one of the moving tasks wrongly return SUCCESS instead of RUNNING. If this condition is true, there is no two tasks giving different positions.
- Again, it is related to SUCCESS and RUNNING status.
- I do not have that issue, I use Polyline on one of my task and StepWalker in another and they go well with each other. What is the scenario ?

**Comment by th3w4y** [comment]
This is an example of conflicting direction https://github.com/PokemonGoF/PokemonGo-Bot/issues/5186#issue-174961761

**Comment by Anakin5** [comment]
> Are you saying we don't need such a Traffic Controller?

Yes, maybe we just make sure 2 tasks cannot drive the position in same time. I proposed something simple as a comment in my PR:

in MoveToFort

if self.bot.move_lock is not None and self.bot.move_lock != "MoveToFort":
    return

self.bot.move_lock == "MoveToFort"
<do my logic here>
in FollowPath

if self.bot.move_lock is not None and self.bot.move_lock != "FollowPath":
    return

self.bot.move_lock == "FollowPath"
<do my logic here>

You can do that with decorator as well

**Comment by th3w4y** [comment]
@Anakin5 what about conflicting destination how do you solve that? because you just locked the first one you received!

**Comment by Anakin5** [comment]
There is only one task giving destination, all others are silent. Priority is handled with order in the task list, just like for other tasks.

**Comment by th3w4y** [comment]
@Anakin5  we collaborated in few PRs and issues before and I believe we're both quick to contradict each other at times.
But i tend to believe we still **did**  generally found value in each other's comments. 
(Once we get to make our point understood by the other person...)

Please take the time to also check if there is a **positive** value in this proposal not only contradict.

**Comment by mjmadsen** [comment]
I will say I think you guys work well together after you both get on the same page. The walker updates you guys put in are great. Keep up the great work! We should try to use our chat more often (including private chats) so establish our thoughts. We all have the same goal of making an awesome bot. You're both very good programmers and have a great deal of insight. :+1:

**Comment by th3w4y** [comment]
@Anakin5 how does MoveToFort play together with FollowPath? imagine them in whatever order you want and think what results... you'd get even with lock
- do you still follow the point in FollowPath?
- do you still move to forts along the Path?

**Comment by th3w4y** [comment]
I have to mention that I like  that @Anakin5  is usually able to come up with a simpler solution...

**Comment by Anakin5** [comment]
I guess people use FollowPath because they want the bot to stick to a route. FollowPath is also spinning Forts, so there is no need to especially move to a fort.

Let's say you still want to mix them to achieve something. There is a of issues in front. 
What forts are you allowed to visit while following the path ? Is it a distance from the path ? How do you compute distance from the path with a Polyline anyway ?

We are only moving to spin fort and hatch eggs. It does not matter much whether you were able to find the shortest way to spin the 250 forts of your area.
Even if you imagine that you know in advance the location  of the Pokemon, you will just find a way to catch all the ones you are interested in and disregard the forts.

I am just feeling this is going to take a very long time to get something working. And then another very long time to fix bugs. And then everything is going to be more complicated to implement.

But I mean, you asked for thoughts :), I am OK if you do something and it works as well. I just don't feel that work is going to be used much.

**Comment by th3w4y** [comment]
@Anakin5 Thanks! feedback appreciated...

one of the side advantage to my proposal would be that we could possibly show the computed path in the web GUI, that would be a candy future to have...

**Comment by th3w4y** [comment]
I plan to do some changes but not push yet to upstream branches yer that would modify the Polyline object to support base line segments operations... https://github.com/PokemonGoF/PokemonGo-Bot/issues/5374 https://github.com/PokemonGoF/PokemonGo-Bot/issues/5379
>How do you compute distance from the path with a Polyline anyway ?

**Comment by th3w4y** [comment]
lets just also add  that i would consume less API calls if i know more destinations in advance... 
I can send up to 10 waypoints to google and google will return best path (then i would create either one with best route... or 10 small polylines out of one(1) API call)
