### ISSUE TITLE
make the web interface more interactive

### ISSUE THREAD

**Issue by phekphek** [PokemonGoF/PokemonGo-Bot#5368]
### Short Description

currently the web interface is showing some basic information about the player and collected pokemons. Currently it's impossible to do some basic operations like manually transferring a pokemon or manually evolving a pokemon. There is no evolve/transfer option from the web interface. The moveset of the pokemons are also not shown. 

### Possible solution

Add evolve/transfer buttons for each pokemon that is shown in the pokemon list. Also add moveset information for each pokemon in this list.

### How it would help others

If the user does not want automatic transfer or evolve, with this enhancement the user can decide on his own which pokemon to evolve or to release without running the original game client.

Displaying the moveset is important to delete pokemons with bad movesets.

**Comment by poid0010** [comment]
I have
![image](https://cloud.githubusercontent.com/assets/20973618/18410919/b976b2ea-7796-11e6-893b-01e250fc8da4.png)

**Comment by phekphek** [comment]
This is exactly the feature that i am looking for. But it's not part of the latest web interface yet. Is it ??

**Comment by shudack** [comment]
How i can get the actions menu?

**Comment by TridentNooch** [comment]
Ironically I see the release button, but it doesn't do anything at this point

**Comment by mmixx** [comment]
Yep... It doesn't do anything yet... It was removed on the latest commit... I also working on a way to make that feature work...

**Comment by shudack** [comment]
Me like this! How do you get looks like your stats?

![capturar](https://cloud.githubusercontent.com/assets/17851196/18418744/e80aa910-7843-11e6-86c2-dd2f4b7ff26c.PNG)
