### ISSUE TITLE
[FR] FollowPath should get a log_interval setting

### ISSUE THREAD

**Issue by thejamespinto** [PokemonGoF/PokemonGo-Bot#5373]
Hey guys,

![image](https://cloud.githubusercontent.com/assets/335238/18411370/8eb31390-774c-11e6-8200-6b60051b2c9b.png)

How often do you guys use `FollowPath`?
`MoveToFort` has a `log_interval` setting.
Would be really nice to have the same setting on `FollowPath`
so as to reduce the log overload

What do you guys think?

**Comment by maxprzemo** [comment]
"walker_limit_output": true,
Add to config.json

**Comment by thejamespinto** [comment]
@maxprzemo I stopped using that one because it was removing lines from my log, instead of not inputting them :(
