### ISSUE TITLE
Adding reverse/ addition/substration operations to the Polyline class

### ISSUE THREAD

**Issue by th3w4y** [PokemonGoF/PokemonGo-Bot#5374]
**Details:**

```
Polyline(A,E) + Polyline(E,M) = Polyline(A,M)
reversed(Polyline(M,A) = Polyline(A,M)
Polyline(A,M) - Polyline(A,E) = Polyline(E,M)
# point I is the intersection point between Polyline(A,E) and Polyline(X,Y)
Polyline.intersects(Polyline(A,E), Polyline(X,Y)) = True, (Polyline(A,I), Polyline(I,E), Polyline(I,X), Polyline(I,Y)]
# no intersection point 
Polyline.intersects(Polyline(A,E), Polyline(X,Y)) = False, ((ClosestPointOnPolyline1,ClosestPointOnPolyline2 ), distance)
Polyline.intersects(Polyline(A,E), Polyline(X,Y), fetch=True) =  Polyline(A, Z).. and the other possible polylines....# via missing link between  ClosestPointOnPolyline1 and ClosestPointOnPolyline2  fetched from the API
```

**Comment by mjmadsen** [comment]
I suppose if a task wanted to force a particular destination, it could send only that one - those that want to let the walker decides will send multiple requests

**Comment by th3w4y** [comment]
To add a bit of context to @mjmadsen comment.

We had a chat on gitter.im and the driving force behind the purpose of this change is so that we can prioritise cell_worker tasks an precompute a walking route...

 For this to work the best I would need to modify the Polyline class to support the operations mentioned above in order to be able to re-use Polyline objects as line segments that we can put together or split as we'd want.
