### ISSUE TITLE
Logging in with wrong password in auth.json doesn't stop the bot

### ISSUE THREAD

**Issue by Shentang** [PokemonGoF/PokemonGo-Bot#5376]
Currently, the behaviour of the bot is, that if the password is wrong, it will try 5 times before locking you out from your account.

I don't really see sense in this, since if the password was wrong on the first try, how would it be correct on th 2nd, 3rd, 4th and 5th? Bot should just stop running instead of retrying login. I barely made it to use "crtl+c" to stop the bot while it was trying for the 5th time...

**Comment by Gobberwart** [comment]
Fixed
