### ISSUE TITLE
Bot goes back and forth between normal and lured forts

### ISSUE THREAD

**Issue by kureijir** [PokemonGoF/PokemonGo-Bot#5384]
### Expected Behavior
Bot moves normally between forts.

### Actual Behavior
It goes back and forth between a normal and a lured fort.
http://imgur.com/WZSOEbR

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/gUUT6fiA

### Output when issue occurred

> [2016-09-11 10:10:05] [MoveToFort] [INFO] Moving towards pokestop Roman Boy Holding Paper - 0.07km
> [2016-09-11 10:10:27] [MoveToFort] [INFO] Moving towards pokestop Roman Boy Holding Paper - 0.08km
> [2016-09-11 10:10:49] [MoveToFort] [INFO] Moving towards pokestop Памятник перед муниципальным о - 0.07km (attraction of
>  lure 0.07km)
> [2016-09-11 10:10:53] [IncubateEggs] [INFO] Eggs incubating: [4.23/5.0 km] (Eggs left: 8, Incubating: 1)
> [2016-09-11 10:11:09] [MoveToFort] [INFO] Moving towards pokestop Памятник перед муниципальным о - 0.07km (attraction of
>  lure 0.07km)
> [2016-09-11 10:11:30] [MoveToFort] [INFO] Moving towards pokestop Roman Boy Holding Paper - 0.08km
> [2016-09-11 10:11:51] [MoveToFort] [INFO] Moving towards pokestop Памятник перед муниципальным о - 0.07km (attraction of
>  lure 0.07km)
> [2016-09-11 10:12:13] [MoveToFort] [INFO] Moving towards pokestop Roman Boy Holding Paper - 0.07km
> [2016-09-11 10:12:34] [MoveToFort] [INFO] Moving towards pokestop Roman Boy Holding Paper - 0.06km
> [2016-09-11 10:12:55] [IncubateEggs] [INFO] Eggs incubating: [4.23/5.0 km] (Eggs left: 8, Incubating: 1)
> [2016-09-11 10:12:55] [MoveToFort] [INFO] Moving towards pokestop Памятник перед муниципальным о - 0.07km (attraction of
>  lure 0.07km)
> [2016-09-11 10:13:19] [MoveToFort] [INFO] Moving towards pokestop Памятник перед муниципальным о - 0.07km (attraction of
>  lure 0.07km)
> [2016-09-11 10:13:40] [MoveToFort] [INFO] Moving towards pokestop Памятник перед муниципальным о - 0.07km (attraction of
>  lure 0.07km)
> [2016-09-11 10:14:01] [MoveToFort] [INFO] Moving towards pokestop Roman Boy Holding Paper - 0.08km

### Other Information
OS: 
Arch Linux ARM
Branch: 
master
Git Commit: 
11123a82cb18c172a262dc9e46e7b2c175666828
Python Version: 
2.7.12

**Comment by Anakin5** [comment]
Put `log_interval` in MoveToFort to `0` and generate a log for us again. Your issue is that you are not Spinning these forts, but not sure why yet.

**Comment by kureijir** [comment]
Well the lure worn out so I can't reproduce it right now. The problem is it never went near the forts enough to spin them.
http://imgur.com/6n3cTgD
Pink is the lured fort, cyan is the normal one, red is my position and orange is the road path.

**Comment by Anakin5** [comment]
Without log I can't see why you are never getting close enough to spin.

**Comment by kureijir** [comment]
Well then, I'll reopen when I can reproduce this.
