### ISSUE TITLE
How does FollowPath work?

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#5385]
I have these, (Just added FollowPath in my conf)
```
{
	"type": "CatchPokemon",
	"config": {
		"enabled": true,
		"catch_visible_pokemon": true,
		"catch_lured_pokemon": true,
		"min_ultraball_to_keep": 15,
		"berry_threshold": 0.5,
		"vip_berry_threshold": 0.1,
		"treat_unseen_as_vip": true,
		"daily_catch_limit": 800,
		"catch_throw_parameters": {
			"excellent_rate": 0.1,
			"great_rate": 0.5,
			"nice_rate": 0.3,
			"normal_rate": 0.1,
			"spin_success_rate": 0.6,
			"hit_rate": 0.85
		},
		"catch_simulation": {
			"flee_count": 3,
			"flee_duration": 2,
			"catch_wait_min": 3,
			"catch_wait_max": 6,
			"berry_wait_min": 3,
			"berry_wait_max": 5,
			"changeball_wait_min": 3,
			"changeball_wait_max": 5,
			"newtodex_wait_min": 20,
			"newtodex_wait_max": 30
		}
	}
},
{
	"type": "NicknamePokemon",
	"config": {
		"enabled": true,
		"nickname_template": "{ivcp_pct2}",
		"dont_nickname_favorite": true,
		"nickname_above_iv": 0.95,
		"nickname_wait_min": 3,
		"nickname_wait_max": 5
	}
},
{
	"type": "FollowPath",
	"config": {
		"path_mode": "linear",
		"path_start_mode": "first",
		"path_file": "configs/path.json"
	}
},
{
	"type": "SpinFort",
	"config": {
		"enabled": true,
		"spin_wait_min": 5,
		"spin_wait_max": 8,
		"daily_spin_limit": 1500
	}
},
{
	"type": "MoveToFort",
	"config": {
		"enabled": true,
		"lure_attraction": true,
		"lure_max_distance": 300,
		"walker": "StepWalker",
		"log_interval": 5
	}
},
{
	"type": "FollowSpiral",
	"config": {
		"enabled": false,
		"diameter": 4,
		"step_size": 40
	}
}
```
And the bot is always try to move to the next stop.
```
] [MainThread] [FollowPath] [INFO] Walking from (...) to (...), distance left: (32.47 m) ..
```
If it encounters a pokemon, it will catch it, then move to the next stop.

These stops are just some coordinates, no pokestops.

**Comment by Anakin5** [comment]
What do you want to know exactly ?

**Comment by avexus** [comment]
I would like the bot to move alone a busy street, a lot of poke stops along the way.
When I added in "FollowPath", the bot only moves from one point to the another. And does NOT spin the poke stops.
It does catch pokemons if it sees them.

I want the bot to move along the street. IF there is a poke stop, then move to the poke stop and spin it, then move to the next point in the path file.

**Comment by jmarenas** [comment]
I removed the "MoveToFort" task and the "FollowPath" task is at the end of the task list.
So the bot will walk from point to point and if it sees a pokestop, it will spin it, and if spawn a pokemon it will catch it.
I have that configuration and it work for me.

Additional info: with that configuration, the bot will not walk to a poke-stop, but when it walk from point to point, if a poke-stop is in the range it will spin the poke-stop. If you want that the bot walk to a poke-stop, you must add a loiter field in the json file that contain the points (more info at [https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/configuration_files.md#followpath-settings](url))

**Comment by Anakin5** [comment]
@avexus 
You do not provide enough information. If you have a problem with the follow path, the essential thing that you should give us is your file of points.
Second thing is that if your points are not placed properly, you might never be in range for a fort and thus never spin it. For now, there is nothing in the information you gave that confirm that there is indeed a pokestop on your path.

**Comment by ntanto** [comment]
try this config

{
    "type": "CatchPokemon",
    "config": {
        "enabled": true,
        "catch_visible_pokemon": true,
        "catch_lured_pokemon": true,
        "min_ultraball_to_keep": 15,
        "berry_threshold": 0.5,
        "vip_berry_threshold": 0.1,
        "treat_unseen_as_vip": true,
        "daily_catch_limit": 800,
        "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.5,
            "nice_rate": 0.3,
            "normal_rate": 0.1,
            "spin_success_rate": 0.6,
            "hit_rate": 0.85
        },
        "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 3,
            "catch_wait_max": 6,
            "berry_wait_min": 3,
            "berry_wait_max": 5,
            "changeball_wait_min": 3,
            "changeball_wait_max": 5,
            "newtodex_wait_min": 20,
            "newtodex_wait_max": 30
        }
    }
},
{
    "type": "NicknamePokemon",
    "config": {
        "enabled": true,
        "nickname_template": "{ivcp_pct2}",
        "dont_nickname_favorite": true,
        "nickname_above_iv": 0.95,
        "nickname_wait_min": 3,
        "nickname_wait_max": 5
    }
},
{
    "type": "SpinFort",
    "config": {
        "enabled": true,
        "spin_wait_min": 5,
        "spin_wait_max": 8,
        "daily_spin_limit": 1500
    }
},
{
    "type": "FollowPath",
    "config": {
        "path_mode": "linear",
        "path_start_mode": "first",
        "path_file": "configs/path.json"
    }
}

**Comment by Gobberwart** [comment]
Read the documentation. No issue. Closed.
