### ISSUE TITLE
[minor error] ambiguous if condition

### ISSUE THREAD

**Issue by LuyiTian** [PokemonGoF/PokemonGo-Bot#539]
### Expected Behavior
do not transfer any Pidgey when I set this to json
```
	"Pidgey": {
		"min_cp": 0,
		"min_iv": 0,
		"cp_iv_logic": "or"
	}
```
### Actual Behavior
UnboundLocalError: local variable 'min_cp' referenced before assignment

### Other Information

I believe this is caused by the ambiguous `if` condition: `if release_config.get('min_cp'):`, which should be replaced with `if release_config.get('min_cp') != None:`  because `if 0` and `if None` will all returns false but they are different.

**Comment by douglascamata** [comment]
Code merged a few minutes ago solves this issue.

**Comment by douglascamata** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/commit/5cd992f7677e9e2c6f2a67c773d752d8469f54ad
