### ISSUE TITLE
New User auth.json problem

### ISSUE THREAD

**Issue by jh0s3ph** [PokemonGoF/PokemonGo-Bot#5393]
2016-09-11 13:03:43,347 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-11 13:03:43,373 [       cli] [INFO] commit: cb9ebb39
2016-09-11 13:03:43,376 [       cli] [INFO] No auth argument specified, checking for /usr/src/app/pokemongo_bot/../configs/auth.json
/usr/src/app/pokemongo_bot/../configs/auth.json:12:0: Error: Object literal (dictionary) is not terminated
   |  At line 12, column 0, offset 331 (AT-END)
   |    near text: True
   |  Object started at line 1, column 0, offset 0 (AT-START)
/usr/src/app/pokemongo_bot/../configs/auth.json: has errors
2016-09-11 13:03:43,391 [       cli] [CRITICAL] Error with configuration file

auth.json file as follow:

{
  "auth_service": "google",
  "username": "xxxxx@gmail.com",
  "password": "xxxxxxx",
  "location": "14.58466625,120.9803305",
  "favorite_locations": [
    {"name": "Luneta","coords": "14.58466625,120.9803305"}
  ],
  "gmapkey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "encrypt_location": "",
  "telegram_token": ""
}

**Comment by askovpen** [comment]
it's valid json. maybe you copy paste not all?
you can validate json [here](http://jsonlint.com/) or [here](http://codebeautify.org/jsonvalidator)

**Comment by oralunal** [comment]
Check the file encoding.

**Comment by th3w4y** [comment]
@jh0s3ph do you know how to reset you Gmap API key???

**Comment by jh0s3ph** [comment]
Its a free api key but i regenerate key anyway. thanks. didn't know that gmap api key is important to keep private as well as username and password. 

I copy-pasted the code in the link askovpen gave and validated it. it says valid jason. i then copied the code in the site to the auth.json and now it works. thanks guys
