### ISSUE TITLE
Transfer Pokemon lower CP .. example I have 2 Exeggutor cp2345 and 2344  once I open bot .. the cp2344 will transfer to professor. I have save transfer list and set max duplicate Pokemon

### ISSUE THREAD

**Issue by mbtrading88** [PokemonGoF/PokemonGo-Bot#5399]
### Other Information
OS: 
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by mbtrading88** [comment]
Still the same.. once I save than I return to the transfer list it become back the same..

**Comment by oralunal** [comment]
Please follow the issue template.
