### ISSUE TITLE
Fix Refresh rate object on map (catch more pokemon)

### ISSUE THREAD

**Issue by b4p3p** [PokemonGoF/PokemonGo-Bot#5409]
Hello, 

i were suggesting that refresh is set on one sec. but niantic's set on ten secs (info on web)
if refresh is under ten secs, niantic maybe return empty array

my fix is:

this on PokemonGoBot constructor
```Python
def __init__(self, db, config):
   ...
   self.last_update_cell = time.time()
```

and this in PokemonGoBot.get_meta_cell method

```Python
def get_meta_cell(self):
   if self.cell and time.time() - self.last_update_cell < 10:
      # print "too early"
      return self.cell
   # print "update cells"
   self.last_update_cell = time.time()
   ...
```

after fix, i started to catch more pokemon ^^

**Comment by b4p3p** [comment]
sorry,  :no_good: 

can i edit this value?

 map_object_cache_time = 10

**Comment by Anakin5** [comment]
Yes you can

**Comment by Gobberwart** [comment]
Closed
