### ISSUE TITLE
[Suggestion] Improve output log

### ISSUE THREAD

**Issue by ayozebarrera** [PokemonGoF/PokemonGo-Bot#541]
* **Add datetime to each line:** Could be useful. Sometimes when user is walking to pokemon you dont know how many time has passed
* **Add colors to important messages:** Maybe green when captured and red when they flee...

Good work btw

**Comment by Tekill** [comment]
Use dev branch
<img width="940" alt="wut" src="https://cloud.githubusercontent.com/assets/965890/17083317/027662e6-51a5-11e6-900a-055f2fead110.png">

**Comment by ayozebarrera** [comment]
Lol... nice and sorry :)
