### ISSUE TITLE
FollowPath json input

### ISSUE THREAD

**Issue by ukos-git** [PokemonGoF/PokemonGo-Bot#5413]
I'm having issues with a path file. the file was acquired using http://www.gpsies.com as recommended in the help-file.
That site is returning float point values with no trailing zeroes like
`[{"location": "49.78837,9.93,191"]`

therefore the location is not recognized anymore by the regex pattern in `pokemongo_bot/__init__.py` line 1220ff
this fixed it for me:
`                "[-]?\d{1,3}[.]\d{2,7}", location_name`

don't know why the digits after the floating point have to be in that specific format. one digit after the "." should also be ok.

digging in the blame history, aabeace9 by @Calcyfer was the initial author of the regex.

I had to format the *.js file to match the correct syntax of "location": "x,y,z" but that's another story.

**Comment by mmixx** [comment]
Is this location `[{"location": "49.78837,9.93,191"]` the one you put on your path config? It's missing a closing curly bracket...

**Comment by ukos-git** [comment]
I extraced the line that caused the issue to boil down the problem. 
Forgot to post the closing braket. Just put the line in a path.json file. It will throw the error.

**Comment by mmixx** [comment]
I'm currently using `FollowPath` and it's working for me... Try to remove the 3rd set of numbers... The `,191`...

**Comment by ukos-git** [comment]
The altitude is an optionsl return value. 
As I said: the regex is not right. I will post a fix.

**Comment by alexyaoyang** [comment]
@ukos-git Good catch. I think `[-]?\d{1,3}[.]?\d+` should do the trick. The front part before decimal should only have 1-3 digits (if I'm not mistaken latitude is [-80,80] and longitude is [-180,180]) while the # of significant digits can be [0,as precise as user wants]?

**Comment by ukos-git** [comment]
if you write it like that, a number like 0, 1, 2 etc. would not be recognized because you made the "." optional but still want to have at least one digit after that "." with the "+"

**Comment by alexyaoyang** [comment]
Yes my bad. `[-]?\d{1,3}([.]\d+)?` or yours should work then 👍

**Comment by Shrihan-P** [comment]
Anyone, please help. I'm not able to install this on windows.  I have all the files ready, but having trouble putting them in place.? :(

**Comment by Gobberwart** [comment]
@Shrihan-P This is not the correct place to post a general "I can't install the bot" question. Read the docs or visit pokemongo-bot.slack.com

**Comment by alexyaoyang** [comment]
PR merged, closing issue
