### ISSUE TITLE
loitering

### ISSUE THREAD

**Issue by ukos-git** [PokemonGoF/PokemonGo-Bot#5416]
hi there.
i have an understanding issue. read the docs and tried a lot but I don't get it.
I have a point-path file with loitering points. So far everything works. The bot walks to the points and loiters at some stops for 0s and at some for 500s (as specified in the file). So far so good.

my  initial standard tasks are set like in the standard config and are all beeing executed when in loitering mode. But I can not get the MovetoFort-Task after the FollowPath-Task to Work.
`tasks: ... --> spinFort --> FollowPath --> FollowSpiral --> MovetoFort`

can someone post a working task-list for me, please?

**Comment by alexyaoyang** [comment]
Remove the FollowSpiral task, and it should work.

**Comment by ukos-git** [comment]
I removed the Spiral. still no walking around when loitering.
Maybe I missed sth else in the config or path file. so here it is:

http://paste2.org/yFjcd4W0
http://paste2.org/DB1xepZ1

**Comment by Anakin5** [comment]
> still no walking around when loitering

Isn't it the point ?

**Comment by ukos-git** [comment]
Ah. Ok. That was my understanding issue. 
I was in the impression, i could do other walking tasks when loitering at a point. 
I want the bot to wander a bit around at certain points of the city. Then after this return to the next waypoint.

**Comment by alexyaoyang** [comment]
What do you mean by walking 'around'? If you are asking will it execute the MoveToFort task while loitering, yes it will.

**Comment by Anakin5** [comment]
I never used it but according to the code, it should not run the MoveToFort while loitering:
```
if self.status == STATUS_LOITERING and time.time() < self.loiter_end_time:
            return WorkerResult.RUNNING
```

**Comment by ukos-git** [comment]
@alexyaoyang maybe you are on master. In current dev it is changed. sorry. should have added the branch.
@Anakin5 I took a quick look in the `cell_workers.py` (line 144). Why is the task returning a running status when loitering (imho) should not be a running task at all? I dig into the blame here and saw that you changed it in 3c1b0f51

**Comment by Anakin5** [comment]
I understood loitering means stay there according to another discussion in another issue. Now if we agree it means to potenrially handover movement to another task, we have to return Success.

**Comment by alexyaoyang** [comment]
@ukos-git I have a few bots running, some on latest dev and some on old dev.

@Anakin5 Ah I see that you've submitted a PR and changed it a couple of days ago. Sorry I didn't saw that PR before. Let me correct myself that the code right now doesn't allow you to move while loiter.

However the intended behavior of loiter is tasks that are placed under FollowPath will be executed. This was the behavior prior to the change in my logs, also quote @janpascal from his PR #4660 

```
[2016-09-09 15:29:19] Loitering for 60 seconds...
[2016-09-09 15:29:19] Moving towards pokestop The Big Strike - 150.78m
[2016-09-09 15:29:23] Moving towards pokestop The Big Strike - 145.83m
[2016-09-09 15:29:27] Moving towards pokestop The Big Strike - 131.08m
```

> 'loiter' in the json file will cause the bot pause following the path for a while, and instead execute the next task. E.g. if a MoveToFort task is next, the bot will chase pokestops for the indicated number of seconds, and the resume the path

What's your opinion on this?

**Comment by ukos-git** [comment]
@alexyaoyang maybe we should add an option like `allow_walk_while_loitering` in the config so everyone is happy

**Comment by reigelgallarde** [comment]
@ukos-git, I get your point but won't make sense if you enabled some task that needs the bot to walk but then you will not allow the bot to walk 😄

**Comment by ukos-git** [comment]
what a mess. now the new posts from yesterday are also gone. feeling like sisiphos.
@reigelgallarde you're right.

the line is already reverted in [current dev](https://github.com/PokemonGoF/PokemonGo-Bot/blob/11123a82cb18c172a262dc9e46e7b2c175666828/pokemongo_bot/cell_workers/follow_path.py#L144)

As the term "LOITER" is fairly uncommon to non-naitive speakers it would also be great to change the constant to WANDER to avoid subsequent misunderstandings.

**Comment by janpascal** [comment]
Unfortunately, reverting `return WorkerResult.RUNNING` to `return WorkerResult.SUCCESS` seems to have missed the update to `master`. Could someone please fix it?

**Comment by Gobberwart** [comment]
Nothing's missed anything. Pull to master will happen in due course.

**Comment by Gobberwart** [comment]
What a disaster this issue is. If you want to wait at a pokestop, set loiter. If not, don't. You can't have both.

**Comment by janpascal** [comment]
It's not in the `dev` branch either. And I agree with @ukos-git that we should change to name to `wander`, since `loiter` creates too many misunderstandings. My bad since I came up with the term.

**Comment by ukos-git** [comment]
@Gobberwart you missed the point:

> If you want to wait at a pokestop, set loiter. If not, don't. You can't have both.

It is sure that you can not stand still and walk at the same time. That's not the issue.
I have some POI in the path of my city and I want to allow doing other tasks like camping or spinning pokestops when near to those POIs. 
Setting a time limit for doing other tasks along the way was a great idea. The only thing that is a mess is the misunderstandings it caused along some devs but everything should be clear now. 
@janpascal If we all agree then let's change the name of the constant. I would be happy.

**Comment by reigelgallarde** [comment]
I missed this this "loiter" thing.. when can we have "wander" then?

**Comment by reigelgallarde** [comment]
why I want this back? is mainly because in my scenario, the spawn area has only one pokestop. I need to have a combination of both FollowPath and MoveToFort... FollowPath will scan the spawn area... and after scanning, do MoveToFort to get some pokeballs..

Is there any config that can do this without loiter?
