### ISSUE TITLE
PR #5415 may be buggy?

### ISSUE THREAD

**Issue by RedViper9** [PokemonGoF/PokemonGo-Bot#5418]
### Expected Behavior
Bot Runs

### Actual Behavior
Bot crashes when triggering the evolve cycle of pokemon_optimizer.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/VFJvuNkj

### Output when issue occurred
http://pastebin.com/mQygXXTQ

### Steps to Reproduce
Run above config with dev bot at 02390dce72ddac2a60ba14a786906485ffa61f96

### Other Information
OS: Linux Mint 18
Branch: dev
Git Commit: 02390dce72ddac2a60ba14a786906485ffa61f96
Python Version: Python 2.7.12

### Seems Fixed by:
Revert 0ee559bcab9dfbaf6f871d731324065b683202f9

Haven't traced the error any further than that.

**Comment by Anakin5** [comment]
Fixed #5420

**Comment by Anakin5** [comment]
what is it doing that is not matching your configuration ?
