### ISSUE TITLE
Buddy System

### ISSUE THREAD

**Issue by kevinlife** [PokemonGoF/PokemonGo-Bot#5419]
Is there any plan to implement the buddy system?

**Comment by DeXtroTip** [comment]
I've been working on this, already made a new task, need to test it. But the api calls for that are not up yet, I guess.

**Comment by joelgreen** [comment]
@DeXtroTip New api calls will be updated in this PR https://github.com/PokemonGoF/PokemonGo-Bot/pull/5421

**Comment by DeXtroTip** [comment]
I've the task ready, just need to add documentation. Also, can't make PR since there is a bug in the api with the SetBuddyPokemon api call which needs to be fixed first.

**Comment by dogeatdog** [comment]
It would be naive to think that just adding a buddy in the app first and then just start running the bot will cause the candies for your buddy to be added automatically ? Just wondering :)

**Comment by davidakachaos** [comment]
I have set a buddy, when I login to the game via the app I see the distance is registered for the buddy :smile: so that seems to work.

**Comment by rumytaulu** [comment]
Manually adding a pokemon buddy with Pokemon App (Android PokemonGo App in my case) and then running the bot did the trick, it start collecting candies.

**Comment by DeXtroTip** [comment]
Adding the buddy in the app and the running the bot should work but may only get you the candies after use the app again since the bot doesn't make that api call yet. That's my guess. 
Do you know if there is any daily limit for the candies received? I was running some tests yeaterday and after some time with the same buddy I started getting errors receiving the candy, the api call was successfull but there were no candies.

**Comment by dogeatdog** [comment]
Not sure, just tested it, stopped the bot and started the app. Pikachu had found +4 Candies :) Will have it run for some time now and see after an hour or 2. It should say +10 or something after that.

**Comment by DeXtroTip** [comment]
Yeah, you get +4 because the bot does not make any api call so the candies that you should earn at each km (depending on pokemon) you receive them all at once when opening the app.

**Comment by ukos-git** [comment]
@DeXtroTip is this also the reason why the bot says

> 0 NN candys earned. You now have XX candy! (Candy Limit 0/100) Probably reached candy daily limit

when collecting the candy reward?

**Comment by DeXtroTip** [comment]
I couldn'5 test it too much because had no way to run the bot so much time in a day. But it did happen to me 2 times and I guess it was around 42 or 44 km, so it might be the limit and that's when you get 0 candies.

**Comment by YvesHenri** [comment]
@DeXtroTip please help closing these
