### ISSUE TITLE
error on requirements.txt

### ISSUE THREAD

**Issue by devilreaper** [PokemonGoF/PokemonGo-Bot#5422]
hello, i searched all over the issues page and over the whole internet, and nothing seems to fix it for me.
when i try ti run requirements.txt i get the folowing output:
http://pastebin.com/izdXiCNP

 im using the manual instalation method.
i tryed the automatic instalation with the ./setup.sh and same erro ocurred, im not very good with linux but im trying hard to learn.
tryed uinstall and instaling again requirements.txt 

raspberry pi2 =>PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
                                  NAME="Raspbian GNU/Linux"
                                   VERSION_ID="8"
                                   VERSION="8 (jessie)"
                                   ID=raspbian
                                   ID_LIKE=debian
                                   HOME_URL="http://www.raspbian.org/"
                                   SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
                                    BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

dev branch of bot
git version 2.1.4
Python Version: 
Python 2.7.9
Python 3.5.2

**Comment by rawgni** [comment]
@devilreaper what's the output ?

**Comment by devilreaper** [comment]
just updated

**Comment by DBa2016** [comment]
are you behind a firewall/proxy?

**Comment by Bilibox** [comment]
for me the setup.sh has to be run w/ sudo beforehand or else I get similar errors.
