### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by javajohnHub** [PokemonGoF/PokemonGo-Bot#5427]
### Expected Behavior

Bot starts and runs

### Actual Behavior

Critical Error

### Output when issue occurred

2016-09-13 13:27:00,854 [       cli] [CRITICAL] Error with configuration file
Tue Sep 13 13:27:00 EDT 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
  2016-09-13 13:27:21,685 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-13 13:27:21,691 [       cli] [INFO] commit: c9c5332f
./configs/config.json:146:12: Warning: Object contains duplicate key: u'// evolve_list'
   |  At line 146, column 12, offset 4126
   |  Object started at line 138, column 18, offset 3848
./configs/config.json:147:12: Warning: Object contains duplicate key: u'// donot_evolve_list'
   |  At line 147, column 12, offset 4164
   |  Object started at line 138, column 18, offset 3848
./configs/config.json:271:4: Warning: Strict JSON does not allow a final comma in an array (list) literal
   |  At line 271, column 4, offset 7729
   |  Array started at line 9, column 13, offset 197
./configs/config.json:356:6: Warning: Object contains duplicate key: u'// Zubat'
   |  At line 356, column 6, offset 10790
   |  Object started at line 343, column 15, offset 10061
./configs/config.json:358:6: Warning: Object contains duplicate key: u'// Zubat'
   |  At line 358, column 6, offset 10910
   |  Object started at line 343, column 15, offset 10061
./configs/config.json: ok, with warnings
2016-09-13 13:27:21,798 [       cli] [CRITICAL] Error with configuration file
Tue Sep 13 13:27:21 EDT 2016 Pokebot  Stopped.

### Steps to Reproduce

fresh dev install

### Other Information
OS: 
Mac
 
Branch: 
Dev
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files) 

I will change the values and submit a pull

**Comment by kirikay** [comment]
where is your config file?

check it here : http://jsonlint.com
