### ISSUE TITLE
Cannot start bot new api install error

### ISSUE THREAD

**Issue by javajohnHub** [PokemonGoF/PokemonGo-Bot#5429]
### Expected Behavior

Upgrade to new api

### Actual Behavior

package not found

### Output when issue occurred

Installing collected packages: pgoapi
  Running setup.py develop for pgoapi
Successfully installed pgoapi-1.1.6
Johns-iMac:PokemonGo-Bot john$ ./run.sh
Some of the required packages are not found / have different version.
Run: ./setup.sh -u

### Other Information
OS: 
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by javajohnHub** [comment]
Same result after running ./setup.sh -u

**Comment by mmixx** [comment]
Yeah... Same result after I updated my copy...
```
Some of the required packages are not found / have different version.
Run: ./setup.sh -u
```

**Comment by LgiMatBrd** [comment]
I solve this with: "./setup.sh -i".

**Comment by ukos-git** [comment]
same here. requirements not met due to pogo version missmatch.
in a630689bfbd4e1cf09bfb3c7969fe5a557268c8b @joelgreen changed the entry in the `requirements.txt` saying

> updated to latest pgoapi from master branch

maybe he has some ideas.

**Comment by joelgreen** [comment]
`sudo pip install -r requirements.txt --upgrade`
If you're having trouble updating requirements try removing the -e in `requirements.txt`
`-e git+https://github.com/pogodevorg/pgoapi.git/@5e550f656b318227f021801c796b8a80ad917b93#egg=pgoapi`
to
`git+https://github.com/pogodevorg/pgoapi.git/@5e550f656b318227f021801c796b8a80ad917b93#egg=pgoapi`

You will also have to confirm to switch, and you may need to run it twice since pip has some issues with the repo cloning.

**Comment by ukos-git** [comment]
still not working for me. it installs correctly but before install gives a warning for the commit
```

Cloning https://github.com/pogodevorg/pgoapi.git/ (to 5e550f656b318227f021801c796b8a80ad917b93) to /tmp/pip-build-J1AbYL/pgoapi
  Could not find a tag or branch '5e550f656b318227f021801c796b8a80ad917b93', assuming commit.

```
afterwards it installs.

```
Installing collected packages: pgoapi
  Found existing installation: pgoapi 1.1.6
    Uninstalling pgoapi-1.1.6:
      Successfully uninstalled pgoapi-1.1.6
  Running setup.py install for pgoapi ... done
Successfully installed pgoapi-1.1.6

```
is the commit 5e550f656b318227f021801c796b8a80ad917b93 right?

as a work-around I skipped the exit 1 in the `run.sh` bash script for once.

**Comment by javajohnHub** [comment]
Installed this time but now I get this error when trying to start bot:
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
[2016-09-13 15:21:56] [sentry.errors.uncaught] [ERROR] [u'ConfigException: No worker named DiscordTask defined', u'  File "pokecli.py", line 802, in <module>', u'  File "pokecli.py", line 149, in main', u'  File "pokecli.py", line 109, in start_bot', u'  File "pokecli.py", line 93, in initialize_task', u'  File "pokemongo_bot/tree_config_builder.py", line 59, in build', u'  File "pokemongo_bot/tree_config_builder.py", line 21, in _get_worker_by_name']

**Comment by tienthanhdhcn** [comment]
To fix this problem, in run.sh you have to change pgoapi==1.1.8 to pgoapi==1.1.6
