### ISSUE TITLE
WebSocket Port

### ISSUE THREAD

**Issue by LUCKASSs** [PokemonGoF/PokemonGo-Bot#5431]
Hello guys
Any tips to open the `WebSocketPort` on `14251` for use the bot with this UI : https://github.com/GediminasMasaitis/PokeEase ?

btw I'm using actually this UI : https://github.com/ChiarilloMassimo/PokemonGo-Farm
But I can't link the bot to the UI.. Any tips to do that ?

Thx !

**Comment by ukos-git** [comment]
Maybe you better comment in the @ChiarilloMassimo - Repository for questions regarding his app. and in @GediminasMasaitis repo for questions regarding him. Also I'm not sure how you use the app if you were not able to link the bot...

Nevertheless:
I think `app.dir` is the key to where to place the app. Look at where it gets set:
`$app['app.dir'] = $this->getAppDir();`
```
    protected function getAppDir()
    {
        return realpath(sprintf('%s/../app/', __DIR__));
    }
```
and finally in `src/Process/PokemonGoBotProcess.php` you find the process that calls the bot:
```

                '(cd %s/../PokemonGo-Bot %s) &',
                SilexApp::getInstance()['app.dir'],
                $command
```

little bit confusing code but in the end it looks like you would have to clone your PokemonGo-Bot to the root directory of the UI-app. Not sure if this is good git standard but you could add the bot-repo to the ignore list of the UI-repo.

**Comment by HelloTroy** [comment]
@ukos-git or anyone else because this involves web socket.  Can someone explain this bit of code for me...?

`},
"websocket": {
    "start_embedded_server": true,
    "server_url": "127.0.0.1:4000"
}`

**Comment by ukos-git** [comment]
seems like other apps can remote control the bot through that server. Never tried it.
Maybe ask @rawgni or @douglascamata to write something to the docs.

**Comment by LUCKASSs** [comment]
Any other tips ?

**Comment by Gobberwart** [comment]
Closed op not relevant to pokemongo-bot
