### ISSUE TITLE
Pokemon Optimizer fails to transfer Poke's

### ISSUE THREAD

**Issue by RedViper9** [PokemonGoF/PokemonGo-Bot#5439]
### Expected Behavior
pokemon_optimizer does:
```
by family; top 2 by ivcp = evolve
    else transfer
per pokemon; top 2 by attack perfection w/ ivcp>0.8 = upgrade
per pokemon; top 2 by defense perfection w/ ivcp>0.8 = upgrade
```
### Actual Behavior
Nothing is exchanged or evolved, pokemon bag is full.
Attempt to transfer doesn't seem to respect delay timers.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/7hh1K9nm

Also tried for PokemonOptimizer using only
```
 "rules": [
                    {
                        "mode": "by_family",
                        "top": 2,
                        "sort": ["ivcp"],
                        "evolve": true,
                        "upgrade": {"ivcp": 0.8}
                    }
             ]
```

### Output when issue occurred
http://pastebin.com/hckyRJK3

### Steps to Reproduce
Use config above with 815abd739905504ccbfa4e3a5687fe47f6c24123

### Other Information
OS: Linux Mint 18
Branch: Dev
Git Commit: 815abd739905504ccbfa4e3a5687fe47f6c24123
Python Version: 2.7.12

### Attempted Solutions
Reverted pokemon_optimizer.py to 9a00253e92e3880fbfb2a19a300fd2a6f847271a
This optimizer was working for me as of last night.
Today, pokemon can not be transferred. Assuming that this is due to API change.

EvolvePokemon and TransferPokemon tasks work fine.

**Comment by solderzzc** [comment]
wired. never saw that happen. you also need `pip install --upgrade -r requirement.txt` after a fresh clone.

**Comment by RedViper9** [comment]
@solderzzc yep, that runs as well. Says everything is up to date. I use this short bash script
```
cd ~/PokemonGo-Bot
git fetch --all
git reset --hard origin/dev
git pull origin dev
source bin/activate
pip install -U -r requirements.txt
git submodule init
git submodule update
```

**Comment by Anakin5** [comment]
There is issues in your config in rule 2 and 3
```
"sort" : ["attack_perfection", {"ivcp": 0.8}]
```
should be changed to something else. It depends what you want to do with that rule.

**Comment by Anakin5** [comment]
+ the output that you show has been produced with `enabled: false`, that is why timer is not respected, it is only a dry run.
