### ISSUE TITLE
No module named UpdateLiveInventory

### ISSUE THREAD

**Issue by javajohnHub** [PokemonGoF/PokemonGo-Bot#5441]
### Expected Behavior

Submit pull request

### Actual Behavior

Getting this error....although I did not touch anything to do with UpdateLiveInventory

### Steps to Reproduce

Submit a pull request and travis will fail?

### Other Information
OS: 
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by Bilibox** [comment]
No errors here on latest dev commit

**Comment by javajohnHub** [comment]
Did you submit a pull request and pass travis ci?

**Comment by javajohnHub** [comment]
could #5406 have caused my error?

**Comment by javajohnHub** [comment]
#5426 possibly?
