### ISSUE TITLE
Bot doesnt work anymore

### ISSUE THREAD

**Issue by xSkav** [PokemonGoF/PokemonGo-Bot#5448]
### Actual Behavior

The bot was working fine yesterday . But after i pull the latest images today . it doesnt work anymore

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/1XvWN9Jg

### Output when issue occurred

2016-09-15 07:04:18,902 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-15 07:04:18,907 [       cli] [INFO] commit: 11123a82
2016-09-15 07:04:18,908 [       cli] [INFO] Error: No /configs/auth.json
2016-09-15 07:04:18,908 [       cli] [INFO] Error: No /configs/config.json
usage: pokecli.py [-h] [-cf CONFIG] [-af AUTH] -a AUTH_SERVICE [-u USERNAME]
                  [-ws WEBSOCKET.SERVER_URL]
                  [-wss WEBSOCKET.START_EMBEDDED_SERVER]
                  [-wsr WEBSOCKET.REMOTE_CONTROL] [-p PASSWORD] [-l LOCATION]
                  [-lc LOCATION_CACHE] [--forts.spin FORTS.SPIN]
                  [-wmax WALK_MAX] [-wmin WALK_MIN] [-k GMAPKEY]
                  [-e SHOW_EVENTS] [-d DEBUG] [-t TEST] [-du DISTANCE_UNIT]
                  [-rt RECONNECTING_TIMEOUT] [-hr HEALTH_RECORD]
                  [-ac FORTS.AVOID_CIRCLES] [-mcs FORTS.MAX_CIRCLE_SIZE]
                  [-crf FORTS.CACHE_RECENT_FORTS]
                  [--map_object_cache_time MAP_OBJECT_CACHE_TIME]
                  [--logging.color LOGGING.COLOR]
                  [--logging.clean LOGGING.CLEAN]
                  [--heartbeat_threshold HEARTBEAT_THRESHOLD]
                  [--pokemon_bag.show_at_start POKEMON_BAG.SHOW_AT_START]
                  [--pokemon_bag.show_count POKEMON_BAG.SHOW_COUNT]
                  [--pokemon_bag.show_candies POKEMON_BAG.SHOW_CANDIES]
                  [--pokemon_bag.pokemon_info POKEMON_BAG.POKEMON_INFO]
                  [--alt_min ALT_MIN] [--alt_max ALT_MAX]
                  [--replicate_gps_xy_noise REPLICATE_GPS_XY_NOISE]
                  [--replicate_gps_z_noise REPLICATE_GPS_Z_NOISE]
                  [--gps_xy_noise_range GPS_XY_NOISE_RANGE]
                  [--gps_z_noise_range GPS_Z_NOISE_RANGE]
                  [--gps_default_altitude GPS_DEFAULT_ALTITUDE]
                  [--enable_social ENABLE_SOCIAL]
                  [--walker_limit_output WALKER_LIMIT_OUTPUT]
pokecli.py: error: argument -a/--auth_service is required

### Steps to Reproduce

I try pulling the new docker images . after that the problem persist

### Other Information
OS: Windows 10 64-bit
 
Branch: dev
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files) 

I am using Docker to pull . and command i use docker pull svlentink/pokemongo-bot

**Comment by rumytaulu** [comment]
Try re-recreate your config

./setup.sh -c

**Comment by roadfox** [comment]
on ptc account the walker stopped working here too , while google account still works
the only difference is see is that with the ptc account i see an id in the logs and not the name:
[PokemonGoBot] [INFO] --- iGckw7CYHObCu6 ---
spinning still works, it just does not start to walk

**Comment by xSkav** [comment]
AFter recreating new config . the problem still persist

**Comment by Gobberwart** [comment]
Come on dude, really? 

```
2016-09-15 07:04:18,908 [ cli] [INFO] Error: No /configs/auth.json
2016-09-15 07:04:18,908 [ cli] [INFO] Error: No /configs/config.json
```

This error is self-explanitory. Not an issue with the bot. Closing.
