### ISSUE TITLE
Intermittent error [Bad request syntax]

### ISSUE THREAD

**Issue by Edzelopez** [PokemonGoF/PokemonGo-Bot#5449]
Hi,

I keep getting this long error message every now and again. I'm running the bot normally with most of the default settings in config.json. The bot continues as usual, but this error keeps popping up. It doesn't affect functionality, but just thought you guys would like to know.

code 400, message Bad request syntax ('\x81\xf0\x1b\xe8\xdbC/\xda\x80ay\x87\xafyy\x9a\xb4"\x7f\x8b\xba0o\xca\xf7c`\xca\xba x\x87\xae-o\xca\xe1c9\xad\xbf9~\x84\xb43~\x92\xf9o;\xca\xbf"o\x89\xf9y;\x93\xf9.h\x8f\xf9y;\xca\x97,|\x81\xb5ch\x9d\xb8 ~\x9b\xa8%n\x84\xf5af\xc4\xfba~\x9e\xbe-o\xca\xe1c9\x84\xb4$r\x86\x840n\x8b\xb8&h\x9b\xbd6w\xca\xa6\x1e\x81\xfe\x00\xd3\xa0\x8d8\r\x94\xbfc/\xc2\xe2L7\xc2\xffWl\xc4\xeeY~\xd4\xaf\x14-\xdb\xafYn\xc3\xe2Mc\xd4\xaf\x02-\x82\xc8\\w\xc5\xe1W}\xc5\xf7\x1a!\x80\xaf\\l\xd4\xec\x1a7\x80\xf6\x1a`\xd3\xea\x1a7\x80\xaf}j\xc7\xfe\x18d\xce\xeeMo\xc1\xf9Qc\xc7\xb7\x18V\x90\xa3\x00=\x8f\xb8\x16=\x80\xe6UP\x80\xa5}j\xc7\xfe\x18a\xc5\xebL7\x80\xb5\x14-\xe9\xe3[x\xc2\xecLd\xce\xea\x02-\x91\xa4\x1a!\x80\xaf]j\xc7\xfe\x1a7\x80\xaf\x08#\x98\xbd\x178\x8e\xbd\x18f\xcd\xaf\x14-\x82\xe8_j\xd3\xd2Th\xc6\xf9\x1a7\x80\xb5\x14-\x82\xe8_j\xd3\xd2Qc\xc3\xaf\x02-\x91\xf0\x14-\x82\xe8Nh\xce\xf9\x1a7\x80\xafVh\xd8\xf9gh\xc7\xeagd\xce\xeeMo\xc1\xf9]~\x82\xf0e\x81\xfe\x046\xf8\x0b\xf4\xd7\xcc9\xaf\xf5\x9ad\x80\xed\x9ay\x9b\xb6\x9ch\x95\xa4\x8c)\xd8\xf7\x83)\x95\xb4\x9bd\x81\xb9\x8c)\xce\xf7\xdaN\x90\xad\x9dg\x9b\xa7\x9dq\xd6\xfb\xd8)\x90\xb6\x8cj\xd6\xed\xd8p\xd6\xba\x8bl\xd6\xed\xd8)\xb1\xb3\x8bn\x98\xb8\x88n\x8e\xf7\x84+\xa1\xa7\x8cb\x99\xb2\xd81\xd4\xe6\xc29\xc4\xed\xcd3\xd4\xab\xd8N\x95\xa5\x96n\x90\xf7\xca\'\xc2\xe1\xc0+\xa7\xa3\x99y\x90\xa2\x8b\x7f\xd4\xab\xd8 \xc1\xfb\xca=\xc4\xf7\xa0[\xd4\xab\xd88\xd8\xef\xc13\xd4\x8f\xa8$\x9c\xf7\x84+\xa2\xbe\x8bb\x80\xb2\x9c+\xc6\xe6\xd8x\x80\xb8\x88x\xd6\xfb\xd8)\x87\xa3\x99\x7f\x87\xf5\xc2+\xd6\x92\x9cx\x91\xbb\x97{\x91\xad\xd8w\xd4\x82\x88\x7f\x9d\xba\x9d+\xce\xf7\xc91\xc6\xe7\xc2>\xcc\xf7\x84+\xb1\xb6\x8ae\x91\xb3\xd89\xd8\xe1\xce3\xd4\x84\x8cj\x86\xb3\x8dx\x80\xf7\x84+\xdf\xe2\xd49\xc2\xe7\xd8S\xa4\xf7\x84+\xc7\xfb\xc02\xcc\xf7\xa0[\xdb\xbf\xd8w\xd4\x81\x91x\x9d\xa3\x9do\xd4\xe5\xc9+\x87\xa3\x97{\x87\xf5\xd4+\xd6\xa4\x8cj\x80\xa4\xa7y\x95\xa0\xda1\xd4\xac\xda{\x9b\xbc\x9df\x9b\xb9\xa7n\x82\xb8\x94}\x91\xb3\xda1\xd4\xe7\xd4+\xd6\xaf\x88T\x84\xb2\x8aT\x9c\xb8\x8dy\xd6\xed\xd88\xcc\xee\xcf%\xcd\xe4\xcd>\xc7\xee\xcc3\xcd\xe0\xc1:\xc2\xfb\xd8)\x87\xa3\x97{\x87\x88\x8eb\x87\xbe\x8cn\x90\xf5\xc2+\xc6\xe6\xd4+\xd6\xa4\x8cj\x86\xb3\x8dx\x80\x88\x9dj\x86\xb9\x9do\xd6\xed\xd89\xc2\xe1\xc0\'\xd4\xf5\x80{\xab\xb2\x99y\x9a\xb2\x9c)\xce\xf7\xcd9\xc2\xe7\xd4+\xd6\xa7\x97`\x91\xba\x97e\xab\xb2\x96h\x9b\xa2\x96\x7f\x91\xa5\x9do\xd6\xed\xd89\xc0\xfb\xd8)\x81\xa7\x8cb\x99\xb2\xda1\xd4\xf5\xc91\xc6\xe7\xc2>\xcc\xf5\xd4+\xd6\xb4\x8dy\x86\xb2\x96\x7f\xab\xbb\x9d}\x91\xbb\xa7s\x84\xf5\xc2+\xc5\xe7\xc8;\xc4\xe7\xd4+\xd6\xa7\x97`\x91\xba\x97e\xab\xb4\x99~\x93\xbf\x8c)\xce\xf7\xc9<\xd8\xf7\xdag\x9b\xb4\x99\x7f\x9d\xb8\x96)\xce\xf7\xa3?\xc4\xf9\xc13\xc5\xe6\xcd:\xc2\xe3\xcf;\xc6\xe5\xc98\xd8\xf7\xca3\xda\xef\xce:\xc2\xe7\xcc9\xc2\xe4\xc8;\xc2\xe4\xc1>\xa9\xfb\xd8)\x9c\xbe\x9fc\x91\xa4\x8cT\x97\xa7\xa7{\x9b\xbc\x9df\x9b\xb9\xda1\xd4\xf5\xbfd\x98\xb5\x99\x7f\xd4\x8c\xbb[\xce\xf7\xc9;\xc2\xe5\xa5+\xaf\x9e\xae1\xd4\xe6\xcc$\xc5\xe6\xd7:\xc4\x8a\xd8[\x9b\xa3\x9de\x80\xbe\x99g\xce\xf7\xc8%\xc3\xef\xd8)\xd8\xf7\xda{\x9b\xbc\x9df\x9b\xb9\xa7y\x91\xbb\x9dj\x87\xb2\x9c)\xce\xf7\xc8\'\xd4\xf5\x8dx\x91\xa5\x96j\x99\xb2\xda1\xd4\xf5\xbdo\x87\xb2\x94d\x84\xb2\x82)\xd8\xf7\xda{\x9b\xbc\x9di\x95\xbb\x94x\xab\xa3\x90y\x9b\xa0\x96)\xce\xf7\xcb3\xd8\xf7\xda|\x9c\xb8\x94n\xab\xbb\x9d}\x91\xbb\xa7s\x84\xf5\xc2+\xc5\xe7\xc8;\xc4\xe7\xd4+\xd6\xbf\x99\x7f\x97\xbf\x9do\xab\xb2\x9fl\x87\xf5\xc2+\xc5\xfb\xd8)\x9f\xba\xa7|\x95\xbb\x93n\x90\xf5\xc2+\xc0\xf9\xc88\xc2\xef\xca<\xc4\xef\xcf?\xc4\xe5\xcb?\xc0\xfb\xd8)\x98\xb2\x8en\x98\xf5\xc2+\xc6\xe5\xd4+\xd6\xb9\x9ds\x80\x88\x9dl\x93\x88\x90j\x80\xb4\x90b\x9a\xb0\xda1\xd4\xe3\xd69\xc4\xe7\xca8\xc7\xe3\xcd2\xc0\xe0\xca=\xc1\xe1\xd4+\xd6\xb2\x80{\x91\xa5\x91n\x9a\xb4\x9d)\xce\xf7\xcc9\xcc\xe3\xc8;\xd8\xf7\xdag\x91\xa1\x9dg\xab\xb4\x97f\x84\xbb\x9d\x7f\x9d\xb8\x96T\x84\xb2\x8ah\x91\xb9\x8cj\x93\xb2\xda1\xd4\xee\xcb\'\xd4\xf5\x9bj\x84\xa3\x8dy\x91\xa4\xa7{\x91\xa5\xa7c\x9b\xa2\x8a)\xce\xf7\xc99\xda\xe2\xc1<\xcc\xee\xc8>\xc5\xe4\xc03\xc0\xe5\xc18\xd8\xf7\xdag\x9b\xb0\x91e\xd6\xed\xd8)\xb1\xb3\x82n\x98\xb8\x88n\x8e\xf5\xd4+\xd6\xa7\x97`\x91\xba\x97e\xab\xa2\x96x\x91\xb2\x96)\xce\xf7\xca\'\xd4\xf5\x95d\x87\xa3\xa7{\x91\xa5\x9en\x97\xa3\xa7{\x9b\xbc\x9df\x9b\xb9\xda1\xd4\xf5\xb3j\x9a\xb0\x99x\x9f\xbf\x99e\xd4\x8c\xbb[\xce\xf7\xcc?\xc7\x8a\xd8P\xbd\x81\xc2+\xc5\xe6\xd7:\xc6\xf8\xc98\xa9\xf7\xa8d\x80\xb2\x96\x7f\x9d\xb6\x941\xd4\xe7\xd63\xd4\xf5\x85v\xd8\xf7\xdan\x82\xb2\x96\x7f\xd6\xed\xd8)\x98\xb8\x9fT\x87\xa3\x99\x7f\x87\xf5\x85V\x81\xfe\x02\x82Y\xcb\x0c\xd9m\xf9W\xfb;\xa4x\xe3;\xb9c\xb8=\xa8m\xaa-\xe9 \xf9"\xe9m\xba:\xa4y\xb7-\xe96\xf9{\x8eh\xa3<\xa7c\xa9<\xb1.\xf5y\xe9h\xb8-\xaa.\xe3y\xb0.\xb4*\xac.\xe3y\xe9W\x948\xaca\xb8+\xe7,\x9a\t\xeb=\xe8m\xff \xf9\x10\x9dO\x89y\xfb"\xe1`\xe7,\x9d\t\x98,\xe8k\xe5=\xefu\xebD\x89y\xf3<\xf6a\xfbQ\xf9%\xebW\x8b1\xb2h\xb67\xe7,\x9a\t\xeb=\xe9n\xfd \xf9\x10\x9dO\x89y\xfb"\xe0k\xe7,\x9d\t\x98,\xe8j\xe54\xe0u\xebD\x89y\xfa>\xebv\xfa>\xeb\x04\xebp\xf9\x02\x8cc\xb5;\xaax\xf5y\x88\\\xf9h\xfb:\xebu\xebE\x8f\x1a\x9b,\xe9w\xf3=\xf5y\x8f\\\x8ay\xfa=\xf7i\xfa \xf9\x11\x9b,\xe0l\xe45\xec\x04\xebp\xf9\x02\x98m\xb7=\xb8`\xb8*\xa3 \xf9\x1a\x9b,\xe8i\xfe<\xf5y\x82Z\x9a\t\xeb<\xf7l\xfe \xf9\x1d\x9b_\xf9h\xfd"\xebj\xe7,\x91\t\xeb=\xe9i\xe4=\xe9i\x96,\xa5y\x90^\xb1 \xafc\xb7u\xebO\x89y\xfa<\xedi\xe7,\x90\x0f\x88\\\xf9i\xe5;\xf5y\x8f\\\x8ay\xfa?\xf7o\xf8 \xf9\x11\x9b,\xe8k\xf9#\xe8k\xf9Q\xfbu\xeb.\xa96\xa0i\xb46\xa5\x7f\xfbc\xeb.\x82\x14\xaak\xb48\xb9 \xf9\x1a\x9b,\xe8h\xff8\xf5y\x82Z\x9a\t\xeb<\xf7a\xf2 \xf9\x1d\x9b_\xf9h\xf9"\xe8o\xe7,\x91\t\xeb4\xe9v\xf3<\x84y\xb7,\x82\x0b\xa3u\xbd6\xa5 \xf9\x1a\x9b,\xe8i\xfc:\xf5y\x82Z\x9a\t\xeb<\xf7`\xf9 \xf9\x1d\x9b_\xf9h\xf8"\xe1`\xe7,\x91\t\xeb=\xebk\xe4=\xebk\x96,\xa5y\x90K\xb65\xa9m\xadu\xebO\x89y\xfa<\xefk\xe7,\x90\x0f\x88\\\xf9i\xe54\xe8u\xebH\x89')
Traceback (most recent call last):
  File "/home/edsel/git/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/greenpool.py", line 82, in _spawn_n_impl
    func(*args, **kwargs)
  File "/home/edsel/git/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 719, in process_request
    proto.__init__(sock, address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 342, in handle
    self.handle_one_request()
  File "/home/edsel/git/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/wsgi.py", line 351, in handle_one_request
    if not self.parse_request():
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 458, in log_message
    format%args))
  File "/home/edsel/git/PokemonGo-Bot/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
  File "/home/edsel/git/PokemonGo-Bot/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 38: invalid start byte

**Comment by Anakin5** [comment]
Those are not valid utf-8 encoded strings. somebody somewhere forgot to encode the string before sending it.
