### ISSUE TITLE
Reaching daily spin limit is causing multiple teleport

### ISSUE THREAD

**Issue by lntn** [PokemonGoF/PokemonGo-Bot#5462]
This is not a bug, rather an unexpected behaviour.

Reaching daily spin limit is now causing the bot to stop, but then it will auto start again after 20 seconds, at the original location, and voila, a teleport.

Then if you're not around, it will keep looping until a new day.

As we all know, teleporting is the most likely reason to get banned, so everyone should disable the daily catch/spin limit for now, or turn on location cache (hopefully this will work).

**Comment by avexus** [comment]
does that mean sniping is dangerous?

**Comment by lntn** [comment]
@avexus I believe so. There are people who used GPS tools to snipe & got ban, nothing to do with botting. It's the most obvious though.

**Comment by Gobberwart** [comment]
There's a PR open to change the way daily_spin_limit works. Once done, you can set 'exit_on_limit_reached' and the bot will just stop when you reach your limit. See #5550
