### ISSUE TITLE
pokemon_optimizer crash when Pokemon Bag is full

### ISSUE THREAD

**Issue by MerlionRock** [PokemonGoF/PokemonGo-Bot#5468]
### Expected Behavior

pokemon_optimizer triggered when TransferPokemon min_free_slot condition met.

### Actual Behavior

When pokemon bag is full, errors and bot crash

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/mtVPUnYw

### Output when issue occurred
http://pastebin.com/tjrakAC7

### Steps to Reproduce
It's always triggered when bag is full, in my case 245/250.
Never happened in stable version when using the same Pokemon Optimizer config

### Other Information
OS: 
Windows 10
Branch: 
Dev
Git Commit: 
 
b51bca679056fad9b2e45f3410cff1f8d8569271

**Comment by Anakin5** [comment]
You need to update your configuration, there is errors. See https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/pokemon_optimizer.md.
