### ISSUE TITLE
Pokemon_Optimizer ISSUE

### ISSUE THREAD

**Issue by Jcolomar** [PokemonGoF/PokemonGo-Bot#5483]
### Expected Behavior
Only evolve and upgrade with rules

### Actual Behavior
Bot evolve pokemon not following rules

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
{
        "type": "PokemonOptimizer",
            "config": {
                "enabled": true,
                "min_slots_left": 5,
                "transfer": true,
                "transfer_wait_min": 6,
                "transfer_wait_max": 9,
                "evolve": true,
                "evolve_time": 25,
                "evolve_for_xp": true,
                "evolve_only_with_lucky_egg": true,
                "evolve_count_for_lucky_egg": 1,
                "may_use_lucky_egg": true,
                "upgrade": true,
                "upgrade_level": 60,
                "rules": [
                    {
                        "mode": "by_pokemon",
                        "top": 2,
                        "sort": ["iv", "dps_attack"], 
                        "upgrade": {"iv": 1},
                        "evolve": {"iv": 1}
                    },
                    {
                        "mode": "by_pokemon",
                        "top": 1,
			"names": ["Magikarp"],
                        "sort": ["iv"],
                        "upgrade": false,
                        "evolve": false
                    },
                    {
                        "mode": "by_pokemon",
                        "names": ["Eevee"],
                        "top": 3,
                        "sort": ["iv"],
                        "upgrade": false,
                        "evolve": false
                    }
                ]
        }
      },
### Output when issue occurred
[2016-09-16 13:11:49] [MainThread] [PokemonOptimizer] [INFO] Evolved Voltorb [IV 0.87] [CP 276] [1256 candies] [+1000 xp]
[2016-09-16 13:12:16] [MainThread] [PokemonOptimizer] [INFO] Evolved Voltorb [IV 0.76] [CP 250] [1207 candies] [+1000 xp]
[2016-09-16 13:12:43] [MainThread] [PokemonOptimizer] [INFO] Evolved Voltorb [IV 0.73] [CP 609] [1158 candies] [+1000 xp]
[2016-09-16 13:13:10] [MainThread] [PokemonOptimizer] [INFO] Evolved Voltorb [IV 0.62] [CP 603] [1109 candies] [+1000 xp]

### Other Information
OS:  W10 x64
Branch: 
Master
Git Commit: 
Latest commit a8ee312
Python Version: 
Python 2.7.12

**Comment by Anakin5** [comment]
`"evolve_for_xp": true,`

**Comment by Jcolomar** [comment]
I´ll change "evolve_for_xp": true, to "false" and wait if works.

**Comment by Jcolomar** [comment]
By the moment goes good. Ty
