### ISSUE TITLE
Loitering does not seem to work properly

### ISSUE THREAD

**Issue by jmarenas** [PokemonGoF/PokemonGo-Bot#5488]
### Expected Behavior

Run the bot, go to the next point as in my path file, then, while loitering, move to forts, spin the pokestop and catch pokemons.

### Actual Behavior

only while is following a path spin the pokestops, while is loitering it does nothing.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

http://pastebin.com/HDWecKDg

### Output when issue occurred

http://pastebin.com/2fY2XXBC
in the line 40 and 426 start to loiter.

### Steps to Reproduce

./run.sh

### Other Information
OS: Ubuntu 16.04
 
Branch: master
 
Git Commit: a8ee31256d412413b107cce81b62059634e8c802
 
Python Version: Python 2.7.12
 
Any other relevant files/configs (eg: path files) 

path file
[
	{"location": "40.7814675, -73.9741015, 33", "loiter": 300},
  {"location": "40.7795502, -73.9632225, 46", "loiter": 300},
  {"location": "40.7739931, -73.9665484, 23", "loiter": 300},
  {"location": "40.7741881, -73.9707756, 25", "loiter": 300},
  {"location": "40.7757805, -73.9717841, 26", "loiter": 300},
  {"location": "40.7772429, -73.9712047, 29", "loiter": 300},
  {"location": "40.7678016, -73.9717411, 18", "loiter": 300},
  {"location": "40.7663878, -73.9732003, 21", "loiter": 300},
  {"location": "40.7647626, -73.9732003, 32", "loiter": 300},
  {"location": "40.7653802, -73.9750671, 26", "loiter": 300},
  {"location": "40.7665015, -73.9748954, 14", "loiter": 300},
  {"location": "40.7762842, -73.9740157, 32", "loiter": 300}
]

**Comment by alexyaoyang** [comment]
#5416

**Comment by Gobberwart** [comment]
You want to loiter but also walk around? Makes no sense.

**Comment by jmarenas** [comment]
@Gobberwart The actual behavior, happens after the update from 11123a82cb18c172a262dc9e46e7b2c175666828 to a8ee31256d412413b107cce81b62059634e8c802.
As is documented [here](https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/configuration_files.md#followpath-settings) the loiter field indicates the number of seconds that the bot loiter after reaching a point, during that time, the next Task -in the task list- is executed. The next task, in my configuration file, is MoveToFort, and, as expected, when loitering the bot should move to forts and catch pokemons, as it happens in 11123a82cb18c172a262dc9e46e7b2c175666828.
