### ISSUE TITLE
Is there any change to the spinFort task?

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#5496]
I did a clean install of the dev branch on Windows 10. Now the bot stuck with

 [MoveToFort] [INFO] Arrived at fort.

I have the following
		{"type": "NicknamePokemon",	"config": {"enabled": true,		"nickname_above_iv": 0.5, "nickname_template": "{ivcp_pct2}{iv_ads_hex}", "dont_nickname_favorite": true, "nickname_wait_min": 3, "nickname_wait_max": 5}},
		{"type": "MoveToFort",		"config": {"enabled": true,		"lure_attraction": false, "lure_max_distance": 300, "walker": "StepWalker", "log_interval": 5}},
		{"type": "SpinFort",		"config": {"enabled": true,		"spin_wait_min": 5, "spin_wait_max": 8, "daily_spin_limit": 1500}},
		{"type": "FollowPath",		"config": {"enabled": false,	"walker": "StepWalker", "path_mode": "loop", "path_start_mode": "first", "path_file": "configs/path.json", "number_lap": 10, "timer_restart_min": "00:10:00", "timer_restart_max": "00:20:00"}},
 		{"type": "FollowSpiral",	"config": {"enabled": true,	"diameter": 3, "step_size": 30}}

**Comment by javajohnHub** [comment]
Under nickname template try putting a - between the two values

**Comment by avexus** [comment]
@javajohnHub I tried that, it didn't work. Just stayed at [MoveToFort] [INFO] Arrived at fort.
over and over and won't move on.

This conf file was from before the update. I added '_', but still the same. Kinda weird.

**Comment by javajohnHub** [comment]
It has to be a -  i could be wrong..but almost positive

**Comment by avexus** [comment]
Nope, still doesn't work.

**Comment by avexus** [comment]
Anyhow, I copied from somebody who's conf worked, and changed some values. So it works now.
But it's really strange. My conf works fine. Until this afternoon.
