### ISSUE TITLE
RandomAlivePause RandomPause runs even disabled

### ISSUE THREAD

**Issue by liejuntao001** [PokemonGoF/PokemonGo-Bot#5501]
I notice these run even disabled in config
RandomAlivePause
RandomPause

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

     {
        "//NOTE: This task MUST be placed on the top of task list": {},
        "type": "RandomAlivePause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:05:00",
          "max_interval": "01:30:00"
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "RandomPause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:10:00",
          "max_interval": "02:00:00"
        }
      },

### Output when issue occurred

[2016-09-16 21:09:07] [RandomAlivePause] [INFO] Next random alive pause at 21:24:19, for a duration of 0:06:03
[2016-09-16 21:09:07] [RandomPause] [INFO] Next random pause at 22:01:19, for a duration of 0:08:44

### Steps to Reproduce

start bot

### Other Information

Branch: 
master
Git Commit: 
a8ee31256d412413b107cce81b62059634e8c802

**Comment by kureijir** [comment]
Unless I'm mistaken, that's only an output at start of the bot, it won't actually pause at the specified time.

**Comment by cmezh** [comment]
@kureijir You're right, but it should be fixed anyway.

**Comment by Gobberwart** [comment]
#5591 is a blanket approach which will not be approved as-is. Suggest fixing the individual randompause and randomalivepause tasks instead.

**Comment by cmezh** [comment]
@Gobberwart It is not a issue, just a messages of scheduling functions called from init.

**Comment by cmezh** [comment]
#5591 merged.
