### ISSUE TITLE
Transfer Pokemon not working

### ISSUE THREAD

**Issue by jury89** [PokemonGoF/PokemonGo-Bot#5507]
Hi,

It looks like that automatically transfer Pokemons after every catch is not working correctly (or perhaps i'm missing something).
this is my config.json
```
    {
        "type": "TransferPokemon",
        "config": {
          "enabled": true,
          "min_free_slot": 9999,
          "// transfer_wait_min": 1,
          "// transfer_wait_max": 100
        }
      }
```
but after the bot succesfuly catch the Pokemon, it doesn't get transferred.

Any help?

**Comment by 0rgan1c** [comment]
Make sure you review this section: https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md#release-configuration

> Default configuration will not release any Pokémon.
`"release": {"any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"}}`

If you never changed it, and it looks like that you will never release anything ever.

What I did is change the config.json to:
```
"release": {
      "any": {"keep_best_cp": 4},
      "//any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
```
This will keep 4 of the same type of pokemon with the best CP, you can change this to however many you want. 

Alternatively, you can just comment (//) or uncomment any of of the examples in your config.json in the "RELEASE" section.

**Comment by jury89** [comment]
I thought that the "release" section was to ignore some kind of Pokemon, not to transfer it after the Pokemon is caught. 
Btw your configuration works perfectly, thank for the hint.
