### ISSUE TITLE
Telegram Task does not react, I think i broke it with wrong commands

### ISSUE THREAD

**Issue by crepes11** [PokemonGoF/PokemonGo-Bot#5508]
### Actual Behavior

In my telegram app: Just the normal output of my subscriptions. The output I was expecting because of typing for example '/info' did not appear.

terminal output window:
`Traceback (most recent call last):
  File "/home/crepes/pgo/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/poll.py", line 115, in wait
    listener.cb(fileno)

  File "/home/crepes/pgo/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/thread.py", line 41, in __thread_body
    func(*args, **kwargs)

  File "/home/crepes/pgo/PokemonGo-Bot/pokemongo_bot/event_handlers/telegram_handler.py", line 382, in run
    self.display_events(update)

  File "/home/crepes/pgo/PokemonGo-Bot/pokemongo_bot/event_handlers/telegram_handler.py", line 265, in display_events
    events.remove('vanish_log')

ValueError: list.remove(x): x not in list

Removing descriptor: 9
`
But the Bot is still running...

(Restarting of PokemonGo-bot does not help. (I opened a new terminal as well, because I thought there might be some cache.))

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
    {
        "type": "TelegramTask",
        "config": {
          "enabled": true,
          "master": MY ID,	
          "// old syntax, still supported: alert_catch": ["all"],
          "// new syntax:": {},
          "alert_catch": {
            "all": {"operator": "or", "cp": 999, "iv": 0.98},
            "Dratini": {"operator": "or", "cp": 10, "iv": 0.01},
            "Dragonair": {"operator": "or", "cp": 10, "iv": 0.001},
            "Dragonite": {"operator": "or", "cp": 10, "iv": 0.01},
            "Snorlax": {"operator": "or", "cp": 10, "iv": 0.01},
            "Lapras": {"operator": "or", "cp": 10, "iv": 0.01}
          }
        }
      }

### Steps to Reproduce

-sending to my telegram bot while my pokemonGo-Bot was offline: /info
-starting my pokemonGo-Bot in terminal
-typing '/events pokemon' in telegram app (I tried to filter the output of '/events')
-typing '/events egg' in telegram app

### possible solution

maybe clearing some cache?

### Other Information
OS:  ubuntu 14.04
Branch:  master
Git Commit: fef76945022210f4663c091b55750c57684026ec
Python Version:  Python 2.7.6

EDIT: Rebooting the computer and deleting 'PokemonGo-Bot' folder and reinstalling does not fix the issue. So i guess I need to create a new telegram bot. But i am going to wait a little. Maybe there is a better soluton.

**Comment by javajohnHub** [comment]
Can you confirm this is still happening?

**Comment by javajohnHub** [comment]
When you reinstalled the repo... did you /login pw again 
And /sub all. ?

**Comment by Gobberwart** [comment]
Fixed in latest dev branch
