### ISSUE TITLE
protobuf

### ISSUE THREAD

**Issue by ukos-git** [PokemonGoF/PokemonGo-Bot#5509]
repost of https://github.com/PokemonGoF/PokemonGo-Bot-Backup/issues/15

Seems like `protobuf-to-dict` depends on `six>=1.9.0` but in their repo's requirements it is only refered to six 1.8.0
An issue is already active at the developer's repo (#https://github.com/benhodgson/protobuf-to-dict/issues/12) but the repo seems to be stale.
I recommend adding the six dependency to our requirements.txt (right before `protobuf-to-dict`) because it raised strange errors on debian8 having six 1.8.0 installed. updating six to 1.10.0 fixed the issue for me.

**Comment by Gobberwart** [comment]
Fair enough. I already had six 1.10.0 so no issue but I can see how it might impact someone. Fixed in PR #5601

**Comment by ukos-git** [comment]
@Gobberwart thank you.
