### ISSUE TITLE
MoveToMapPokemon working or not ?

### ISSUE THREAD

**Issue by ikariya69** [PokemonGoF/PokemonGo-Bot#5512]
config.json -> original MoveToMapPokemon

on previous version if this task was on and the Pokemon-Map server was not on there was an error message, asking iof the server was running.

no message actually on the last version. i turned off pokemon-map and it changes nothing on the running bot. turn it on and i see no sniping.

is it normal ?

**Comment by cowst** [comment]
yesterday evening it was working, right now apparently not, or i am the only one botting and there are no detections around to snipe :)

**Comment by YvesHenri** [comment]
Please follow the "rules" when posting issues. Post your config file, branch and commit version.

**Comment by Gobberwart** [comment]
Refer to issue #5512 for known issues with MoveToMap

Seems to work ok with enable_social but not with Pokemongo-Map

**Comment by cowst** [comment]
@Gobberwart you referred to this own issue :)

**Comment by Gobberwart** [comment]
Hahah, sorry I meant #5523
