### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by 0x2400** [PokemonGoF/PokemonGo-Bot#5517]
File "/Users/test/PokemonGo-Bot/pokemongo_bot/event_handlers/telegram_handler.py", line 156, in get_pokestop
    "*" + str(x[0] + "*"),
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

**Comment by Gobberwart** [comment]
Likely caused by a pokestop with unusual characters in its name. Can you please provide more information, eg. log lines before this occurred etc.

**Comment by Anakin5** [comment]
Looks like telegramhandler is manipulating pokestop names but does not have the `from __future__ import unicode_literals`
