### ISSUE TITLE
Mqtt connection refused - not authorised

### ISSUE THREAD

**Issue by cowst** [PokemonGoF/PokemonGo-Bot#5518]
### Expected Behavior
With social enabled, I expect to receive a list of pokemon to snipe.

### Actual Behavior
I receive empty list every time.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
[config](http://pastebin.com/v1DpQ3Hy)

### Output when issue occurred
when enabling mqtt debug:

> 
> rc: 0
> rc: 5
> on_disconnect
> Unexpected disconnection.
> rc: 0
> rc: 5
> on_disconnect
> Unexpected disconnection.

### Steps to Reproduce
Run dev branch with above config.

### Other Information
OS: 
Linux Mint 18
Branch: 
dev 
Git Commit: 
b2eb347847bfd23b7e4089f53729b8287b3ddbbc 
Python Version: 
Python 2.7.12
Any other relevant files/configs (eg: path files) 
It was working until yesterday, and it worked once this afternoon in between non-working runs.
Other functions work fine, only mqtt list of pokemon returns empty.

**Comment by gengstah** [comment]
I second this issue. Since someone trolled the mqtt broker (sent false pokemon spawns), @solderzzc implemented some kind of way to throttle the mqtt broker connections. However, I experienced the same error as stated by @cowst.

**Comment by YvesHenri** [comment]
@cowst Could you please push this https://github.com/PokemonGoF/PokemonGo-Bot/pull/5522 and let me know what happens?

**Comment by solderzzc** [comment]
@gengstah  current version should not trigger this event. I'll develop a auth based user management some time later.

**Comment by cowst** [comment]
@YvesHenri I used it yesterday evening, with no success (at least concerning the mqtt throttling).
1 - used bot dev - I could snipe
2 - tweaked a bit the config to filter out some pokemon and ran again dev - still working
3 - did it again - not working anymore
4 - moved to snipe 2.1 - still not working with social
5 - changed to urls - working
So your pull request did not solve the issue on mqtt, but if it is really throttling, there is nothing that can be done on this side until @solderzzc introduces some sort of auth. And even with that, if the problem is trolls, they might keep trying to annoy us :)

**Comment by gengstah** [comment]
Now, I get this error:

```
[2016-09-21 22:03:52] [PokemonGoBot] [INFO] Login procedure started.
Traceback (most recent call last):
  File "/root/PokemonGo/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/hubs/poll.py", line 115, in wait
    listener.cb(fileno)
  File "/root/PokemonGo/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/thread.py", line 41, in __thread_body
    func(*args, **kwargs)
  File "/root/PokemonGo/PokemonGo-Bot/pokemongo_bot/event_handlers/social_handler.py", line 86, in run
    self._mqttc.connect("broker.pikabot.org", 1883, 20)
  File "/root/PokemonGo/PokemonGo-Bot/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 686, in connect
    return self.reconnect()
  File "/root/PokemonGo/PokemonGo-Bot/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 808, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/root/PokemonGo/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/green/socket.py", line 63, in create_connection
    raise err
error: [Errno 111] ECONNREFUSED
Removing descriptor: 14
```

Somebody welp!

**Comment by JSchwerberg** [comment]
That node should be up. o.o  Let me see why it wouldn't be responding.

**Comment by Gobberwart** [comment]
Any news @JSchwerberg?

**Comment by JSchwerberg** [comment]
Node should be up now...for some reason, after a maintenance reboot, my docker daemon launched an old version of the MQTT broker.  I fixed it minutes after posting here.  Forgot to report back.

**Comment by Gobberwart** [comment]
Thanks mate. Closing this.
