### ISSUE TITLE
Can't override location cache

### ISSUE THREAD

**Issue by doctor-ew** [PokemonGoF/PokemonGo-Bot#552]
I changed location property in json
added location_cache and then passed along -lc false and then --location_false

6-07-23 21:42:37 [x] PokemonGO Bot v1.0
2016-07-23 21:42:37 [x] Configuration initialized
[2016-07-23 21:42:37]
[2016-07-23 21:42:37] [x] Last location flag used. Overriding passed in location

### Other Information
OS: osx yosemite
Git Commit: 5cd992f7677e9e2c6f2a67c773d752d8469f54ad

**Comment by fmdcarvalho** [comment]
Can confirm that location flag is being ignored even in the config.json
