### ISSUE TITLE
All Pokemons are treated as VIPs

### ISSUE THREAD

**Issue by Ciribomflax** [PokemonGoF/PokemonGo-Bot#5525]
### Expected Behavior

Just the Pokemons on the VIP list should be treated as such.

### Actual Behavior

All encountered Pokemons are treated as VIPs

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

{
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": true,
    "live_config_update": {
      "enabled": false,
      "tasks_only": false
    },
    "tasks": [
      {
        "//NOTE: This task MUST be placed on the top of task list": {},
        "type": "RandomAlivePause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:05:00",
          "max_interval": "01:30:00"
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "RandomPause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:10:00",
          "max_interval": "02:00:00"
        }
      },
      {
        "type": "CollectLevelUpReward",
        "config": {
          "collect_reward": true,
          "level_limit": -1
        }
      },
      {
        "type": "IncubateEggs",
        "config": {
          "enabled": true,
          "infinite_longer_eggs_first": false,
          "breakable_longer_eggs_first": true,
          "min_interval": 120,
         "infinite": [2,5,10],
         "breakable": [2,5,10]
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": false,
          "min_interval": 120,
          "show_all_multiple_lines": false,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
        }
      },
      {
        "type": "ShowBestPokemon",
        "config": {
          "enabled": true,
          "min_interval": 60,
          "amount": 5,
          "order_by": "cp",
          "info_to_show": ["cp", "ivcp", "dps", "hp"]
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": true,
          "nickname_above_iv": 0.8,
          "nickname_template": "{iv_pct}_{iv_ads}",
          "nickname_wait_min": 3,
          "nickname_wait_max": 5
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "enabled": true,
            
            
            "evolve_list": "all",
            "donot_evolve_list": "Bulbasaur, Charmander, Squirtle, Metapod, Kakuna, Pidgeotto,  Eevee, Nidoran M, Nidoran F, Bellsprout, Geodude",
            
          "first_evolve_by": "cp",
          "evolve_above_cp": 10,
          "evolve_above_iv": 0.1,
          "logic": "or",
          "min_evolve_speed": 25,
          "max_evolve_speed": 30,
          "use_lucky_egg": false
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "enabled": true,
          "min_free_slot": 300,
          "transfer_wait_min": 3,
          "transfer_wait_max": 5
        }
      },
      {
        "type": "UseIncense",
        "config": {
          "use_incense": false,
          "use_order": [
            "ordinary",
            "spicy",
            "cool",
            "floral" 
          ]
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          },
          "recycle_wait_min": 3,
          "recycle_wait_max": 5,
          "recycle_force": true,
          "recycle_force_min": "00:01:00",
          "recycle_force_max": "00:05:00"
        }
      },
      {
        "type": "CatchPokemon",
        "config": {
          "enabled": true,
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "min_ultraball_to_keep": 5,
          "berry_threshold": 0.35,
          "vip_berry_threshold": 0.9,
          "treat_unseen_as_vip": true,
          "daily_catch_limit": 800,
          "vanish_settings": {
            "consecutive_vanish_limit": 10,
            "rest_duration_min": "02:00:00",
            "rest_duration_max": "04:00:00"
          },
          "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.5,
            "nice_rate": 0.3,
            "normal_rate": 0.1,
            "spin_success_rate" : 0.6,
            "hit_rate": 0.75
          },
          "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 3,
            "catch_wait_max": 6,
            "berry_wait_min": 3,
            "berry_wait_max": 5,
            "changeball_wait_min": 3,
            "changeball_wait_max": 5,
            "newtodex_wait_min": 20, 
            "newtodex_wait_max": 30
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "enabled": true,
          "spin_wait_min": 3,
          "spin_wait_max": 5,
          "daily_spin_limit": 1900
        }
      },
      { "type": "UpdateWebInventory",
        "config": {
          "enabled": true
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "enabled": true,
          "lure_attraction": true,
          "lure_max_distance": 2000,
          "walker": "StepWalker",
          "log_interval": 5
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "enabled": false,
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "pokemon_bag": {
      "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
      "show_at_start": true,
      "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
      "show_count": false,
      "// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
      "show_candies": false,
      "// 'pokemon_info' parameter define which info to show for each pokemon": {},
      "// the available options are": {},
      "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
      "pokemon_info": ["cp", "iv_pct"]
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "alt_min": 500,
    "alt_max": 1000,
    "sleep_schedule": [
      {
        "time": "12:00",
        "duration": "1:00",
        "time_random_offset": "00:30",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      },
      {
        "time": "17:00",
        "duration": "1:00",
        "time_random_offset": "01:00",
        "duration_random_offset": "00:30",
        "wake_up_at_location": ""
      }
    ],
    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": false,
    "replicate_gps_z_noise": false,
    "gps_xy_noise_range": 0.000125,
    "gps_z_noise_range": 12.5,
    "debug": false,
    "test": false,
    "walker_limit_output": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging": {
      "color": true,
      "show_datetime": true,
      "show_process_name": true,
      "show_log_level": true,
      "show_thread_name": false
    },
    "catch": {
      "any": {"candy_threshold" : 400 ,"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      "Bulbasaur": {"keep_best_cp": 1},
      "Charmander": {"keep_best_cp": 1},
      "Squirtle": {"keep_best_cp": 1},
      "Caterpie": {"keep_best_cp": 1},
      "Metapod": {"keep_best_cp": 1},
      "Butterfree": {"keep_best_cp": 5},
      "Weedle": {"keep_best_cp": 1},
      "Kakuna": {"keep_best_cp": 1},
      "Beedrill": {"keep_best_cp": 5},
      "Pidgey": {"keep_best_cp": 1},
      "Pidgeotto": {"keep_best_cp": 1},
      "Pidgeot": {"keep_best_cp": 5},
      "Rattata": {"keep_best_cp": 1},
      "Raticate": {"keep_best_cp": 3},
      "Spearow": {"keep_best_cp": 1},
      "Fearow": {"keep_best_cp": 3},
      "Sandshrew": {"keep_best_cp": 1},
      "Sandlash": {"keep_best_cp": 3},
      "Nidoran F": {"keep_best_cp": 1},
      "Nidoran M": {"keep_best_cp": 1},
      "Ekans": {"keep_best_cp": 1},
      "Arbok": {"keep_best_cp": 3},
      "Vulpix": {"keep_best_cp": 1},
      "Jigglypuff": {"keep_best_cp": 1},
      "Zubat": {"keep_best_cp": 1},
      "Golbat": {"keep_best_cp": 2},
      "Oddish": {"keep_best_cp": 1},
      "Paras": {"keep_best_cp": 1},
      "Parasect": {"keep_best_cp": 3},
      "Venonat": {"keep_best_cp": 1},
      "Diglett": {"keep_best_cp": 1},
      "Meowth": {"keep_best_cp": 1},
      "Psyduck": {"keep_best_cp": 1},
      "Golduck": {"keep_best_cp": 5},
      "Mankey": {"keep_best_cp": 1},
      "Growlithe": {"keep_best_cp": 3},
      "Poliwag": {"keep_best_cp": 1},
      "Poliwhirl": {"keep_best_cp": 1},
      "Abra": {"keep_best_cp": 1},
      "Bellsprout": {"keep_best_cp": 1},
      "Weepinbell": {"keep_best_cp": 1},
      "Tentacool": {"keep_best_cp": 1},
      "Geodude": {"keep_best_cp": 1},
      "Graveler": {"keep_best_cp": 1},
      "Ponyta": {"keep_best_cp": 1},
      "Slowpoke": {"keep_best_cp": 1},
      "Magnemite": {"keep_best_cp": 1},
      "Doduo": {"keep_best_cp": 1},
      "Seel": {"keep_best_cp": 1},
      "Shellder": {"keep_best_cp": 1},
      "Gastly": {"keep_best_cp": 1},
      "Haunter": {"keep_best_cp": 1},
      "Drowzee": {"keep_best_cp": 1},
      "Hypno": {"keep_best_cp": 3},
      "Krabby": {"keep_best_cp": 1},
      "Voltorb": {"keep_best_cp": 1},
      "Exeggcute": {"keep_best_cp": 1},
      "Cubone": {"keep_best_cp": 1},
      "Koffing": {"keep_best_cp": 1},
      "Rhyhorn": {"keep_best_cp": 1},
      "Horsea": {"keep_best_cp": 1},
      "Goldeen": {"keep_best_cp": 1},
      "Seaking": {"keep_best_cp": 5},
      "Staryu": {"keep_best_cp": 1},
      "Starmie": {"keep_best_cp": 5},
      "Jynx": {"keep_best_cp": 5},
      "Magikarp": {"keep_best_cp": 1, "keep_best_iv": 1},
      "Omanyte": {"keep_best_cp": 1},
      "Kabuto": {"keep_best_cp": 1},
      "Dratini": {"keep_best_cp": 1}
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    },
  "websocket": {
    "start_embedded_server": true,
    "server_url": "127.0.0.1:4000"
  }
}

### Output when issue occurred

[2016-09-18 10:22:21] [PokemonCatchWorker] [INFO] *A wild Pidgey appeared!* (CP: 55) (NCP: 0.08) (Potential 0.27) (A/D/S 0/12/0)
[2016-09-18 10:22:24] [PokemonCatchWorker] [INFO] This is a VIP pokemon. Catch!!!
[2016-09-18 10:22:27] [PokemonCatchWorker] [INFO] Threw a Razz Berry! Catch rate with Pokeball is now: 117.32
[2016-09-18 10:22:30] [PokemonCatchWorker] [INFO] Great throw! Used Pokeball, with chance 117.32 (99 left)
[2016-09-18 10:22:30] [PokemonCatchWorker] [INFO] Captured Pidgey! [CP 55] [NCP 0.08] [Potential 0.27] [0/12/0] (51/800) [+150 exp] [+100 stardust]
[2016-09-18 10:22:30] [PokemonCatchWorker] [INFO] You now have 11 Pidgey candy!
[2016-09-18 10:22:36] [TransferPokemon] [INFO] Keeping best 1 Pidgey, based on cp
[2016-09-18 10:22:36] [TransferPokemon] [INFO] Kept Pidgey (CP: 186, IV: 0.33, IVCP: 0.241025251356)
[2016-09-18 10:22:36] [TransferPokemon] [INFO] Released Pidgey (CP: 55, IV: 0.27, IVCP: 0.190352115246) You now have 12 Pidgey candies

### Other Information
OS: Xubuntu 16.04
 
Branch: master
 
Git Commit: fef76945022210f4663c091b55750c57684026ec
 
Python Version: Python 2.7.12
 
Any other relevant files/configs (eg: path files)

**Comment by arjanvanham** [comment]
See comments in this commit: https://github.com/PokemonGoF/PokemonGo-Bot/commit/a45943e061e4936b56f21f71f6ff39398e24af52

**Comment by Ciribomflax** [comment]
Thanks, that worked like a charm!
