### ISSUE TITLE
Pokemon Master won't install 

### ISSUE THREAD

**Issue by fluxpiada** [PokemonGoF/PokemonGo-Bot#5531]
3. Are you running on the `master` branch? We work on the `dev` branch and then add that functionality to `master` when it is stable. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.
4. All Issue sections MUST be completed to help us determine the actual problem and find its cause
-->
### Actual Behavior
`**SyntaxError: Missing parentheses in call to 'print'
zo 18 sep 2016 21:33:54 CEST Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
    File "pokecli.py", line 68
    print "Run following command to get latest update: `pip install -r requirements.txt --upgrade`"**`

### Steps to Reproduce
bash run.sh

### Other Information
OS: 
mac osx 10.11.6
Branch: 
master  
Git Commit: 
`commit fef76945022210f4663c091b55750c57684026ec
Merge: a8ee312 5d3148e
Author: Stuart Travers <Gobberwart@users.noreply.github.com>
Date:   Sat Sep 17 08:34:23 2016 +1000

    Merge pull request #5493 from Gobberwart/dev_release_ivcp`
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by VBQL** [comment]
Have you upgraded the components needed with pip according to a newly created file called "requirements.txt"?

**Comment by ukos-git** [comment]
A good guess is that you are using python3. The print statement has to be with parenthesis there.
Could you check first your python version.
Check for the running virtualenv and pip and afterwards also the ./bin/* Directory inside your app dir for correct python interpreter.

**Comment by VBQL** [comment]
If you are running python3, do sudo apt-get remove python3 && sudo apt-get install python

**Comment by ukos-git** [comment]
@VBQL would be better do do that it in virtualenv via pip like I was already saying.
Also on MacOS I don't think there is apt installed :-)

**Comment by fluxpiada** [comment]
Ahem, yes the python upgrade was the issue, indeed 3.7. I assumed wrongly, that it would still be compatible...Had fun downgrading. Thanks for the help. As for apt MacOS has homebrew (not installed by default)

**Comment by ukos-git** [comment]
Wonderful. 
Indeed python3 is not fully compatible to python2. There exists of cours also a package to load the deprivated print statement to python3. 
Glad to help. 
#closed
