### ISSUE TITLE
More descriptive error messages for catch error 1 and catch error 2

### ISSUE THREAD

**Issue by javajohnHub** [PokemonGoF/PokemonGo-Bot#5533]
### Expected Behavior

You are out of razzberries. ??
or a descriptive error message

### Actual Behavior

catch error 2

### Steps to Reproduce

I think it happens when I am out of berries.

### Other Information
OS: 
Mac
 
Branch: 
Dev
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by Gobberwart** [comment]
Despite your lack of detail, I believe I have identified this as an issue with chat_handler.py, so tagging @javajohnHub

**Comment by javajohnHub** [comment]
Im no longer a member. so tagging @Gobberwart

**Comment by Gobberwart** [comment]
Catch error 1 / 2... Sounds like something I had in my code while I was testing it. Occasionally the catch message would fail due to inability to match against your list of pokemons. Possibly because telegram is running in a separate thread, so the inventory may not be up-to-date.

**Comment by Gobberwart** [comment]
Fixed
