### ISSUE TITLE
Telegram task send almost all log to chat

### ISSUE THREAD

**Issue by lntn** [PokemonGoF/PokemonGo-Bot#5535]
### Expected Behavior
Telegram task should only send chat based on subscription

### Actual Behavior
Sends everything, almost all log lines.
even after /unsub everything
/showsubs shows nothing

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
Just basic Telegram config

### Output when issue occurred
Nothing special from log

### Steps to Reproduce
Turn on Telegram & set a master ID in config
Start bot

### Other Information
Branch: 
dev
Git Commit: 
19639712f9a72ce056bedd5b0664d5e717e02db1
Python Version: 
2.7.10

**Comment by Gobberwart** [comment]
What is an instagram task?

**Comment by Gobberwart** [comment]
If you mean telegram, this should be fixed in latest dev.

**Comment by lntn** [comment]
@Gobberwart haha I mean telegram. I must be crazy while writing Instagram...

**Comment by Gobberwart** [comment]
LOL no worries, in which case, fixed by #5537

**Comment by Gobberwart** [comment]
If you still have that issue, you might want to try "/showsubs" to see what you're subscribed to and remove something (eg. "/unsub all")

**Comment by lntn** [comment]
Noted, will try dev branch again later.
I had to switch back to master because of this bug.

**Comment by Gobberwart** [comment]
Worst case scenario - stop bot, delete database file (data/username.db) and start bot again. db will get recreated cleanly.
