### ISSUE TITLE
Issue - Missing Modules and Requirements Failures

### ISSUE THREAD

**Issue by StudioNoctis** [PokemonGoF/PokemonGo-Bot#5552]
===============ISSUE SECTION===============

Before you create an Issue, please check the following:

1. Have you validated that your config.json is valid JSON? Yes
2. Have you [searched our issue tracker](https://github.com/PokemonGoF/PokemonGo-Bot/issues?q=is%3Aissue+sort%3Aupdated-desc) to see if the issue already exists? Yes
3. Are you running on the `master` branch? Yes
4. All Issue sections MUST be completed to help us determine the actual problem and find its cause
-->
### Expected Behavior

Running the bot without an error on launch, with all modules installed.

### Actual Behavior

When attempting to run python pokecli.py, I get an error about missing module SignalAgglomUpdates_pb2

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
Not really relevant, as the code isn't even getting that far

### Output when issue occurred
Davids-Mac-mini:PokemonGo-Bot Dominus$ python pokecli.py 
Traceback (most recent call last):
  File "pokecli.py", line 46, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetException
  File "/Users/Dominus/Desktop/Pokemon Go/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/Users/Dominus/Desktop/Pokemon Go/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/Users/Dominus/Desktop/Pokemon Go/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 53, in <module>
    from POGOProtos.Networking.Envelopes.SignalAgglomUpdates_pb2 import SignalAgglomUpdates
ImportError: No module named SignalAgglomUpdates_pb2

### Steps to Reproduce

I've uninstalled the api and attempted reinstalling the requirements, but I get the following error;

Davids-Mac-mini:PokemonGo-Bot Dominus$ sudo pip install --ignore-installed six -r requirements.txt
The directory '/Users/Dominus/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/Dominus/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting six
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting numpy==1.11.0 (from -r requirements.txt (line 1))
  Downloading numpy-1.11.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.9MB)
    100% |████████████████████████████████| 3.9MB 328kB/s 
Collecting networkx==1.11 (from -r requirements.txt (line 2))
  Downloading networkx-1.11-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 940kB/s 
Obtaining pgoapi from git+https://github.com/pogodevorg/pgoapi.git/@5e550f656b318227f021801c796b8a80ad917b93#egg=pgoapi (from -r requirements.txt (line 3))
  Cloning https://github.com/pogodevorg/pgoapi.git/ (to 5e550f656b318227f021801c796b8a80ad917b93) to ./src/pgoapi
  Could not find a tag or branch '5e550f656b318227f021801c796b8a80ad917b93', assuming commit.
Collecting geopy==1.11.0 (from -r requirements.txt (line 4))
  Downloading geopy-1.11.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 8.3MB/s 
Collecting geographiclib==1.46.3 (from -r requirements.txt (line 5))
Collecting protobuf==3.0.0b4 (from -r requirements.txt (line 6))
  Downloading protobuf-3.0.0b4-py2.py3-none-any.whl (342kB)
    100% |████████████████████████████████| 348kB 2.8MB/s 
Collecting requests==2.10.0 (from -r requirements.txt (line 7))
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 2.2MB/s 
Collecting requests-mock==1.0.0 (from -r requirements.txt (line 8))
  Downloading requests_mock-1.0.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 9))
  Downloading s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 10))
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 11))
Collecting googlemaps==2.4.4 (from -r requirements.txt (line 12))
  Downloading googlemaps-2.4.4-py2-none-any.whl
Collecting colorama==0.3.7 (from -r requirements.txt (line 13))
  Downloading colorama-0.3.7-py2.py3-none-any.whl
Collecting enum34==1.1.6 (from -r requirements.txt (line 14))
  Downloading enum34-1.1.6-py2-none-any.whl
Collecting pyyaml==3.11 (from -r requirements.txt (line 15))
Collecting haversine==0.4.5 (from -r requirements.txt (line 16))
Collecting polyline==1.3.1 (from -r requirements.txt (line 17))
  Downloading polyline-1.3.1-py2.py3-none-any.whl
Collecting python-socketio==1.4.2 (from -r requirements.txt (line 18))
Collecting flask==0.11.1 (from -r requirements.txt (line 19))
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB)
    100% |████████████████████████████████| 81kB 6.5MB/s 
Collecting socketIO_client==0.7.0 (from -r requirements.txt (line 20))
Collecting eventlet==0.19.0 (from -r requirements.txt (line 21))
  Downloading eventlet-0.19.0-py2.py3-none-any.whl (138kB)
    100% |████████████████████████████████| 143kB 5.8MB/s 
Collecting gpxpy==1.1.1 (from -r requirements.txt (line 22))
Collecting mock==2.0.0 (from -r requirements.txt (line 23))
  Downloading mock-2.0.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 8.6MB/s 
Collecting timeout-decorator==0.3.2 (from -r requirements.txt (line 24))
Collecting raven==5.23.0 (from -r requirements.txt (line 25))
  Downloading raven-5.23.0-py2.py3-none-any.whl (268kB)
    100% |████████████████████████████████| 276kB 3.3MB/s 
Collecting demjson==2.2.4 (from -r requirements.txt (line 26))
Collecting greenlet==0.4.9 (from -r requirements.txt (line 27))
Collecting yoyo-migrations==5.0.3 (from -r requirements.txt (line 28))
Collecting paho-mqtt==1.2 (from -r requirements.txt (line 29))
Collecting Geohash==1.0 (from -r requirements.txt (line 30))
Collecting python-telegram-bot==5.0.0 (from -r requirements.txt (line 31))
  Downloading python_telegram_bot-5.0.0-py2.py3-none-any.whl (130kB)
    100% |████████████████████████████████| 133kB 5.9MB/s 
Collecting discord_simple==0.0.1.15 (from -r requirements.txt (line 32))
Collecting decorator>=3.4.0 (from networkx==1.11->-r requirements.txt (line 2))
  Downloading decorator-4.0.10-py2.py3-none-any.whl
Collecting future (from pgoapi->-r requirements.txt (line 3))
Collecting xxhash (from pgoapi->-r requirements.txt (line 3))
Collecting setuptools (from protobuf==3.0.0b4->-r requirements.txt (line 6))
  Downloading setuptools-27.2.0-py2.py3-none-any.whl (465kB)
    100% |████████████████████████████████| 471kB 2.2MB/s 
Collecting pycryptodomex>=3.0 (from gpsoauth==0.3.0->-r requirements.txt (line 10))
Collecting python-engineio>=0.8.0 (from python-socketio==1.4.2->-r requirements.txt (line 18))
Collecting itsdangerous>=0.21 (from flask==0.11.1->-r requirements.txt (line 19))
Collecting click>=2.0 (from flask==0.11.1->-r requirements.txt (line 19))
Collecting Werkzeug>=0.7 (from flask==0.11.1->-r requirements.txt (line 19))
  Downloading Werkzeug-0.11.11-py2.py3-none-any.whl (306kB)
    100% |████████████████████████████████| 307kB 3.1MB/s 
Collecting Jinja2>=2.4 (from flask==0.11.1->-r requirements.txt (line 19))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |████████████████████████████████| 266kB 4.5MB/s 
Collecting websocket-client (from socketIO_client==0.7.0->-r requirements.txt (line 20))
Collecting funcsigs>=1; python_version < "3.3" (from mock==2.0.0->-r requirements.txt (line 23))
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock==2.0.0->-r requirements.txt (line 23))
  Downloading pbr-1.10.0-py2.py3-none-any.whl (96kB)
    100% |████████████████████████████████| 102kB 5.9MB/s 
Collecting contextlib2 (from raven==5.23.0->-r requirements.txt (line 25))
  Downloading contextlib2-0.5.4-py2.py3-none-any.whl
Collecting iniherit (from yoyo-migrations==5.0.3->-r requirements.txt (line 28))
Collecting python-slugify (from yoyo-migrations==5.0.3->-r requirements.txt (line 28))
Collecting docutils>=0.3 (from Geohash==1.0->-r requirements.txt (line 30))
  Downloading docutils-0.12.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 714kB/s 
Collecting urllib3>=1.10 (from python-telegram-bot==5.0.0->-r requirements.txt (line 31))
  Downloading urllib3-1.17-py2.py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 7.0MB/s 
Collecting certifi (from python-telegram-bot==5.0.0->-r requirements.txt (line 31))
  Downloading certifi-2016.8.31-py2.py3-none-any.whl (379kB)
    100% |████████████████████████████████| 389kB 2.8MB/s 
Collecting MarkupSafe (from Jinja2>=2.4->flask==0.11.1->-r requirements.txt (line 19))
Collecting Unidecode>=0.04.16 (from python-slugify->yoyo-migrations==5.0.3->-r requirements.txt (line 28))
Installing collected packages: six, numpy, decorator, networkx, geopy, setuptools, protobuf, requests, future, s2sphere, pycryptodomex, gpsoauth, xxhash, pgoapi, geographiclib, requests-mock, protobuf-to-dict, googlemaps, colorama, enum34, pyyaml, haversine, polyline, python-engineio, python-socketio, itsdangerous, click, Werkzeug, MarkupSafe, Jinja2, flask, websocket-client, socketIO-client, greenlet, eventlet, gpxpy, funcsigs, pbr, mock, timeout-decorator, contextlib2, raven, demjson, iniherit, Unidecode, python-slugify, yoyo-migrations, paho-mqtt, docutils, Geohash, urllib3, certifi, python-telegram-bot, discord-simple
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/wheel.py", line 378, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/share'
Davids-Mac-mini:PokemonGo-Bot Dominus$ python pokecli.py 

### Other Information
OS: 
Mac OSX 10.11.16
Branch: 
Master
Git Commit: 
fef76945022210f4663c091b55750c57684026ec
Python Version: 
Python 2.7.12
Any other relevant files/configs (eg: path files) 
This was all running fine until recently, probably around Wednesday last week? Ever since I've been unable to run due to this error.

**Comment by ashdude1120** [comment]
This is a shot in the dark, but perhaps try 
`sudo chown -R $(whoami) /Users/Dominus/Desktop/Pokemon\ Go/Pokemon-Go-Bot`
to give yourself permission to the folder? I had a similar issue after upgrading to MacOS Sierra.

**Comment by StudioNoctis** [comment]
@ashdude1120 Attempted changing the owner successfully, but the same response on the requirements. Looks like there's something that's not permitted, but I'm not sure what's triggering it, or what it needs in requirements. 

Thanks though!

**Comment by Gobberwart** [comment]
@StudioNoctis I don't know much about MacOS but perhaps there's something here that might help you with this error: http://stackoverflow.com/questions/31900008/oserror-errno-1-operation-not-permitted-when-installing-scrapy-in-osx-10-11

**Comment by StudioNoctis** [comment]
@Gobberwart Didn't help, but a little more searching and I found the solution, appending --user python to the requirements, so;


sudo pip install -r requirements.txt --user python

**Comment by StudioNoctis** [comment]
Actually, that solved the requirements issue, but I'm still missing the module when running Pokecli.py;

ImportError: No module named SignalAgglomUpdates_pb2

Did the API get updated or something? Seems like it's missing something

**Comment by dayzdayz** [comment]
Can you post the solution if you found one?
I am getting the same error, ImportError: No module named SignalAgglomUpdates_pb2
I installed with pip.exe install git+https://github.com/pogodevorg/pgoapi.git
Windows, Python 3.5
