### ISSUE TITLE
threshold not working in new sniper task

### ISSUE THREAD

**Issue by beltoft** [PokemonGoF/PokemonGo-Bot#5560]
### Expected Behavior
bot should snipe using the catch list

### Actual Behavior
bot crashes when threshold is set in the "order" in the config as explained in the docs.

order - The order on which you want to snipe. This can be one or multiple of the following values (default: [missing, vip, threshold]):

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
 {
		"type": "Sniper",
		"config": {
			"enabled": true,
			"mode": "social",
			"bullets": 3,
			"homing_shots": true,
			"special_iv": 100,
			"order": ["missing", "threshold"],
			"sources": [
            {
                "url": "http://pokesnipers.com/api/v1/pokemon.json",
                "key": "results",
                "mappings": {
                    "iv": { "param": "iv" },
                    "name": { "param": "name" },
                    "latitude": { "param": "coords" },
                    "longitude": { "param": "coords" },
                    "expiration": { "param": "until", "format": "utc" }
                }
            }
        ],
	"catch": {
	 "Mewtwo": 2500,
         "Mew": 2500,
         "Articuno": 2500,
         "Zapdos": 2500,
         "Moltres": 2500,
         "Ditto": 2500,
	 "Pidgey": 2300
				
			}
		}
   },

### Output when issue occurred
Traceback (most recent call last):
  File "pokecli.py", line 843, in <module>
    main()
  File "pokecli.py", line 191, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 146, in start_bot
    initialize_task(bot, config)
  File "pokecli.py", line 98, in initialize_task
    tree = TreeConfigBuilder(bot, config.raw_tasks).build()
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/tree_config_builder.py", line 80, in build
    instance = worker(self.bot, task_config)
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/cell_workers/sniper.py", line 190, in __init__
    super(Sniper, self).__init__(bot, config)
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/base_task.py", line 23, in __init__
    self.initialize()
  File "/home/beltoft/PokemonGo-Bot/pokemongo_bot/cell_workers/sniper.py", line 212, in initialize
    raise ValueError("Unrecognized ordering: '{}'".format(ordering))
ValueError: Unrecognized ordering: 'threshold'
Tue Sep 20 09:27:41 CEST 2016 Pokebot  Stopped.

### Steps to Reproduce

"order": ["missing", "threshold"],

### Other Information
OS: 
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by YvesHenri** [comment]
Please use "priority" instead of "threshold" and it will work. Docs is outdated and there's a PR pending approval.

**Comment by Gobberwart** [comment]
@YvesHenri If you put those vips back I'll approve it :)
