### ISSUE TITLE
Bot Google login error: AttributeError: AuthGoogle instance has no attribute '_proxy'

### ISSUE THREAD

**Issue by lntn** [PokemonGoF/PokemonGo-Bot#5561]
### Expected Behavior
Bot to start normally

### Actual Behavior
Unable to start after updating latest dev & master

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/PUBmNvnV

### Output when issue occurred
http://pastebin.com/uKLC7vQt

### Steps to Reproduce
./setup.sh -u
then start

### Other Information
OS: 
Branch: 
both
Git Commit: 
master: fef76945022210f4663c091b55750c57684026ec
dev: d1e983f45f4687580c2a305591dd9178477be444
Python Version: 
2.7.10

**Comment by ikariya69** [comment]
same here

**Comment by farshidhss** [comment]
same here too

**Comment by krkmastav** [comment]
same here.
i can login with my ptc accounts and the google api key but not login with my google accounts.

**Comment by DeXtroTip** [comment]
There's been a PR in the pgoapi repo fixing this.

**Comment by farshidhss** [comment]
I updated but doesn't seem to fix it

**Comment by youyi1314** [comment]
same here, updated but still same problem

**Comment by victormx** [comment]
Same problem here, all up to date but same error.

**Comment by DeXtroTip** [comment]
The fix hasn't been added to the api yet, only after that we can update the api in the bot.

**Comment by crvfts** [comment]
may I please have link to the api repo? I am unsure which one it is, thanks.

**Comment by DeXtroTip** [comment]
[`pgoapi`](https://github.com/pogodevorg/pgoapi/tree/master/pgoapi)

**Comment by mmixx** [comment]
The fix that they have there still give error... What I've seen was, these two lines:
```
        user_login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID, proxy=self._proxy)
```
```
            token_data = perform_oauth(None, self._refresh_token, self.GOOGLE_LOGIN_ANDROID_ID, self.GOOGLE_LOGIN_SERVICE, self.GOOGLE_LOGIN_APP,
                self.GOOGLE_LOGIN_CLIENT_SIG, proxy=self._proxy)
```

They've added the `proxy=self._proxy` on one of the parameters of `perform_master_login` and `perform_oauth` which is not accepted on the said functions from `lib/python2.7/site-packages/gpsoauth/__init__.py`... Below are the defined functions and their allowed arguments:
```
def perform_master_login(email, password, android_id,
                         service='ac2dm', device_country='us', operatorCountry='us',
                         lang='en', sdk_version=17):
```
```
def perform_oauth(email, master_token, android_id, service, app, client_sig,
                  device_country='us', operatorCountry='us', lang='en', sdk_version=17):
```

When I removed the added argument which is `proxy=self._proxy` from both functions, I didn't get the error and the bot runs smoothly...


PS. With the mentioned fix from their (pgoapi) repository, here is the error I get when I used it:
```
    user_login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID, proxy=self._proxy)
TypeError: perform_master_login() got an unexpected keyword argument 'proxy'
```

**Comment by halsafar** [comment]
Same here.

**Comment by DeXtroTip** [comment]
@mmixx They updated the version needed of gpsoauth in the requirements.txt. Did you upgrade it when testing the mentioned fix?

**Comment by mmixx** [comment]
Yep... I run `./setup.sh -u` first before executing `./run.sh` to make sure my copy is updated...

**Comment by mmixx** [comment]
@DeXtroTip I just found out that there is an updated gpsoauth version **0.4.0**... the one that is on our `requirements.txt` is **0.3.0**...

**Comment by halsafar** [comment]
The bot was working fine until I pip install... 

Then I started getting this error.

**Comment by DeXtroTip** [comment]
@mmixx Yeah, that was the one I was saying. Oh, I thought that it would update anyway since the api needs the **0.4.0** Have you tried the fix now?

**Comment by mmixx** [comment]
Yep... I changed the gpsoauth version on `requirements.txt`, run `./setup.sh`, and then applied the fix posted on `pgoapi` and it works...

**Comment by farshidhss** [comment]
this is really frustrating! The only solution for me was to manually delete the proxy=self._proxy from this file: src/pgoapi/pgoapi/auth_google.py

**Comment by claudioferrari** [comment]
How to fix:
src/pgoapi/pgoapi/auth_google.py lines 58 and 91, remove proxy=self._proxy

**Comment by lntn** [comment]
@claudioferrari removeing those causes other errors
```
Traceback (most recent call last):
  File "pokecli.py", line 47, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetException
  File "/Users/namle/Downloads/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/Users/namle/Downloads/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 36, in <module>
    from pgoapi.auth_google import AuthGoogle
  File "/Users/namle/Downloads/PokemonGo-Bot/src/pgoapi/pgoapi/auth_google.py", line 61
    try:
    ^
IndentationError: unexpected indent
```

**Comment by claudioferrari** [comment]
No, if you use the old api (gpsoauth-0.3.0 pgoapi-1.1.6)

**Comment by cowst** [comment]
check indentation of the code after removing that parameter.
python does not tolerate bad indentation.

**Comment by crvfts** [comment]
What finally worked for me was:
-fresh clone of dev
-cd PokemonGo-Bot
-virtualenv .
-source bin/activate
-pip uninstall -r requirements.txt (takes about 5 minutes or so)
-edit requirements.txt, changed gpsoauth==0.3.0 to 0.4.0
-pip install -r requirements.txt
-edit src/pgoapi/pgoapi/auth_google.py manually with fix from https://github.com/pogodevorg/pgoapi/pull/136/files

**Comment by IAmThePat** [comment]
Thanks @crvfts, that worked for me!

**Comment by Gobberwart** [comment]
@crvfts So... should we be updating requirements.txt from `gpsoauth==0.3.0` to `gpsoauth==0.4.0`

**Comment by lntn** [comment]
Can someone please make a pull request to apply this fix for a new installation process? I'd do if I can...

**Comment by crvfts** [comment]
@Gobberwart I would think not yet because users will still have to manually edit auth_google.py.

I also need to credit @killerherts as they held my hand through the process.

**Comment by Killerherts** [comment]
@crvfts have u submitted this to pogoapi the should be able to merg that part ether way requirements should be changed to 0.4.0

**Comment by lntn** [comment]
I don't understand. How could other people still using the bot normally while we are having this problem? They're still committing new codes, fixing other issues & more pull requests, releases.

**Comment by ukos-git** [comment]
@dogeatdog https://github.com/pogodevorg/pgoapi/pull/136/files was finally merged to master.
Is someone willing to add PR with an updated `requirements.txt`?

**Comment by WayneUong** [comment]
+1

**Comment by Gobberwart** [comment]
I just put in a PR. Anyone want to approve? #5645

**Comment by Pjumpod** [comment]
I have this issue as well in 90b35ea0

**Comment by ukos-git** [comment]
@Pjumpod it was merged to dev 6h ago by @Gobberwart. You are using the master branch. Go get the dev branch and the issue should be fixed. If not, it's something different.
@Gobberwart thank you
