### ISSUE TITLE
Not transferring pokemon

### ISSUE THREAD

**Issue by jannickv** [PokemonGoF/PokemonGo-Bot#5562]
### Expected Behavior
Should be transferring pokemon. For example: i've got a 210 CP / 0.32 IV Ratatta in my inventory... that one should be transferred.

### Actual Behavior
[2016-09-20 11:05:17] Your Pokemon inventory is full! Could not catch!

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/FyT7MViA

### Other Information
OS: Mac OSx
Branch: DEV
Git Commit: d1e983f45f4687580c2a305591dd9178477be444
Python Version: Python 2.7.12

**Comment by davidspeijer** [comment]
Same problem here...

**Comment by Ryuspb** [comment]
I have same problem too ....

**Comment by Cephis** [comment]
same problem too

**Comment by arkachat** [comment]
ame problem here .. Mac os x  El Capitan 10.11.6

**Comment by jannickv** [comment]
so we're all waiting on @sohje to check the pull request^^

**Comment by Gobberwart** [comment]
Gave up waiting. Fixed in #5575

**Comment by jannickv** [comment]
@Gobberwart MVP! Thanks a million!
