### ISSUE TITLE
[FR] Snipe Pokemons not in Pokedex

### ISSUE THREAD

**Issue by davidakachaos** [PokemonGoF/PokemonGo-Bot#5566]
### Short Description
Okay, so the PokemonHunter task has a great option: hunt_pokedex
This will hunt pokemons that we don't have in our Pokedex. Can we have this in the MoveToMapPokemon and/or Sniper tasks as well? 

### Possible solution
I think there is a method "get_worth_pokemons" in PokemonHunter that maybe can be re-used in the sniper?

### How it would help others
This will help filling the Pokedex even faster :smile:

**Comment by YvesHenri** [comment]
MoveToMapPokemon  and Sniper should not be used together for safety. Instead, I'd recommend you to use Sniper.
If you want to snipe missing pokemons with the Sniper task, just change your "order" value to ["missing"]. You can also use multiple orderings, such as ["missing", "vip", "priority"]. This will order by the 'missing' flag, then 'vip' flag and finally by the priority you have set in the catch list.

**Comment by davidakachaos** [comment]
@YvesHenri agreed, but what about catching the previous evolutions?
So you would get something like:
```
Vileplume is not in the pokedex, therefore Gloom is a valid target
```
Or do we teleport too often then?
