### ISSUE TITLE
[REQUEST] Initialize Transfer with iv and cp

### ISSUE THREAD

**Issue by ReqMid** [PokemonGoF/PokemonGo-Bot#558]
### Expected Behavior

"initial_transfer": 100 and 0.7,

### Actual Behavior

"initial_transfer": 100,

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by clavat** [comment]
Better solution is: Initial transfer should use the "release_config.json" rules !

**Comment by surfaace** [comment]
@dmateusp maybe something for you?

**Comment by ReqMid** [comment]
@clavat agree (y)

**Comment by dmateusp** [comment]
I will give it a look :)
