### ISSUE TITLE
All Pokemon treated as VIP

### ISSUE THREAD

**Issue by RaikHS** [PokemonGoF/PokemonGo-Bot#5582]
### Expected Behavior
Bot only treats Pokemon as VIP if they meet the requirements in config.

### Actual Behavior
All Pokemon are treated as VIP regardless of CP or IV.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)

[config.json.txt](https://github.com/PokemonGoF/PokemonGo-Bot/files/483820/config.json.txt)

### Other Information
OS: macOS Sierra
Branch: dev
Git Commit: fef76945022210f4663c091b55750c57684026ec
Python Version: Python 2.7.12

**Comment by Gobberwart** [comment]
Nope. This was fixed days ago.

**Comment by Gobberwart** [comment]
If you disagree, please explain exactly what you're seeing, because this error has definitely been eliminated in current dev.

**Comment by Pjumpod** [comment]
@Gobberwart I try "git pull" but bot already returned my BOT is up-to-date.
Is this change merged to main branch yet?

**Comment by Gobberwart** [comment]
@Pjumpod It is in the current dev branch and tested working correctly. Not sure if in master.

**Comment by dornelas** [comment]
Only in DEV.

**Comment by Gobberwart** [comment]
PR #5494 if you're interested
