### ISSUE TITLE
[Enhancement] Check timestamp before teleporting back to previous location after sniping.

### ISSUE THREAD

**Issue by abhinavagrawal1995** [PokemonGoF/PokemonGo-Bot#5593]
### Short Description

After the bot finds a pokemon worth teleporting to, it teleports back to the player's current location immdiately afterwards. I faced a connection error (due to my internet) AFTER it teleported to the pokemon, but BEFORE the bot was able to go back to its initial location. Naturally, when my connection was restored it resumed and teleported back to the location. 
The downtime gave the pokemon servers enough time to record my player's location and two huge jumps 15 minutes apart earned me a soft ban.

### Possible solution
Record the timestamp before teleporting to a location.
Before the bot teleports back to its initial location, check that timestamp. If its more than some predetermined time interval, either pause the bot to prevent soft ban or take some other prevention measures.

**Comment by YvesHenri** [comment]
There are 2 sniping tasks, which one are you talking about?

**Comment by Gobberwart** [comment]
Are you positive that's what caused the softban? I wouldn't think so, otherwise we'd all be getting banned every time we teleported.

**Comment by YvesHenri** [comment]
@abhinavagrawal1995 Teleporting (read CHANGING positions ONLY) does not cause bans, at least I NEVER heard of it. You can freely move around (change locations) for as long as you do NOTHING else (no catches, no spins, NOTHING). You've been banned very much probably of something else.
