### ISSUE TITLE
  pip install -r requirements.txt --> Could not open requirements file: [Errno 2] No such file or directory: './requirements.txt'  Please help me!

### ISSUE THREAD

**Issue by General-258** [PokemonGoF/PokemonGo-Bot#5600]
### Other Information
OS: 
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by General-258** [comment]
This problem is how to solve the problem can not be detailed to me, . Because I have encountered this problem. Thanks

**Comment by Gobberwart** [comment]
You need to run that command from the same directory where the bot is stored.
