### ISSUE TITLE
Catch Pokemons under "Catch" rules if no pokemon to hunt for PokemonHunter

### ISSUE THREAD

**Issue by MerlionRock** [PokemonGoF/PokemonGo-Bot#5608]
### Short Description

Currently, Pokemon Hunter hunt down specifically what you have requested in config when you set hunt_vip to true. If there are no Pokemon found, it will continue towards fort. It will ignore any other Pokemon encounter along the way.

### Possible solution

If will be good if there's no specific Pokemon to catch,  if it encounter a Pokemon when it's walking towards fort and the Pokemon is valid under "catch", instead of ignoring it, it will catch it. Perhaps a new entry in PokemonHunter call "ProceedToCatch_If_NothingToHunt" : true

Someone might have to think of a better name if this is to be taken into consideration....

### How it would help others

Example: Sometime, one might still want to catch Magikarp, but do not want to specifically hunting for it. So while say hunting for Lapras, and it's not found in sighting, it should catch any other Pokemons specified in the "catch" rules if it encounter one while moving towards the next fort.

**Comment by iruy** [comment]
What's the purpose of PokemonHunther then? If you just don't use it, it would behave like you want.. The advantage of using the Hunter, is that you walk longer distance at the same speed looking for particular pokemon, thus increasing your possibilities of finding it...if the bot stops trying to catch common pokemon, then PokemonHunter is completely useless.
It would be maybe better adding priority to pokemon in `catch` config

**Comment by Anakin5** [comment]
@MerlionRock
If I understand correctly what you are asking, then it is already like you want it. The PokemonHunter does not do anything when there is no Pokemon to hunt. It is not moving to forts (that is your MoveToFort task doing that), and it is not catching Pokemon on the way to fort (that is your CatchPokemon task doing that).
So as long as you have your catch Pokemon task in your config, Pokemon will be caught when encountered, whether they are vip or not.

**Comment by MerlionRock** [comment]
@Anakin5 Hmm.... doesn't seem happening to me. 

One of the output:
[2016-09-22 20:21:15] [MoveToFort] [INFO] Moving towards pokestop Abstract Figure Bust  - 0.06km
[2016-09-22 20:21:22] [MoveToFort] [INFO] Moving towards pokestop Abstract Figure Bust  - 0.05km
[2016-09-22 20:21:29] [PokemonCatchWorker] [INFO] Skip ignored Magikarp! (CP 159) (Potential 0.58) (A/D/S 14/7/5)
[2016-09-22 20:21:29] [MoveToFort] [INFO] Moving towards pokestop Abstract Figure Bust  - 0.04km
[2016-09-22 20:21:33] [  SpinFort] [INFO] Spun pokestop Abstract Figure Bust . Experience awarded: 50. Items awarded: 2x Potion, 1x Pokeball

My Catch config:
    "catch": {
      "any": {"candy_threshold" : 9999 ,"catch_above_cp": 1200, "catch_above_iv": 0.8, "logic": "and"},
      "// Example of always catching Rattata:": {},
	  "Bulbasaur": {},
	  "Charmander": {},
	  "Squirtle": {},
	  "Pikachu": {},
	  "Vulpix": {},
	  "Growlithe": {},
	  "Mankey": {},
	  "Abra": {},
	  "Machop": {},
	  "Geodude": {},
	  "Ponyta": {},
	  "Drowzee": {},
	  "Rhyhorn": {},
	  "Magikarp": {},
	  "Dratini": {},
	  "Exeggcute": {},
	  "Tangela": {"candy_threshold" : 9999 ,"catch_above_cp": 1000, "catch_above_iv": 0.8, "logic": "or"},
	  "Onix": {"candy_threshold" : 9999 ,"catch_above_cp": 1000, "catch_above_iv": 0.8, "logic": "or"},
	  "Hitmonlee": {"candy_threshold" : 9999 ,"catch_above_cp": 1000, "catch_above_iv": 0.8, "logic": "or"},
	  "Hitmonchan": {"candy_threshold" : 9999 ,"catch_above_cp": 1000, "catch_above_iv": 0.8, "logic": "or"},
	  "Lickitung": {"candy_threshold" : 9999 ,"catch_above_cp": 1200, "catch_above_iv": 0.8, "logic": "or"},
	  "Scyther": {"candy_threshold" : 9999 ,"catch_above_cp": 1200, "catch_above_iv": 0.8, "logic": "or"},
	  "Jynx": {"candy_threshold" : 9999 ,"catch_above_cp": 1200, "catch_above_iv": 0.8, "logic": "or"},
	  "Electabuzz": {"candy_threshold" : 9999 ,"catch_above_cp": 1200, "catch_above_iv": 0.8, "logic": "and"},
      "Diglett": { "candy_threshold": 9999, "catch_below_cp": 11, "catch_above_iv": 0, "logic": "and", "fast_attack": ["Scratch", "Mud Slap"] },
      "Horsea": { "candy_threshold": 9999, "catch_below_cp": 11, "catch_above_iv": 0, "logic": "and", "fast_attack": ["Bubble"] }
    },

Magikarp has been set to always catch, but it's ignored when bot run.... hmmm.... did I miss something?

**Comment by Anakin5** [comment]
Not sure what empty catch config means anymore with recent changes. The Pokemon hunter does not read that config and does not catch Pokemon, it just drive movements

**Comment by MerlionRock** [comment]
@Anakin5 I think I figured out. Empty config does not do anything...

In order for it to work, there must be at least one argument in it. This is different from what the comment say.

Is this a bug or intented?

**Comment by Anakin5** [comment]
@Gobberwart might be able to answer this question

**Comment by Anakin5** [comment]
I confirm it with not catch of config empty. You must have always_catch at True inside.
