### ISSUE TITLE
Nothing works....

### ISSUE THREAD

**Issue by PeshBG** [PokemonGoF/PokemonGo-Bot#5614]
I tried installing the docker no luck, i tried with the easy install bats nope.. i tried with the ./setup.sh nope... is there a step by step guide that really works or every guide is a mess?

**Comment by kureijir** [comment]
What operating system are you using?

**Comment by DBa2016** [comment]
At the very least, provide some log output and your configuration files. Without it, no help is possible - "nothing works" is not a valid error description.
