### ISSUE TITLE
Optimizer Error: Not upgrading

### ISSUE THREAD

**Issue by sebamenabar** [PokemonGoF/PokemonGo-Bot#5623]
### Expected Behavior
Pokemon should be upgraded

### Actual Behavior
Upgrade never happens

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/NVMV4Y2M

### Output when issue occurred
http://pastebin.com/nYffTwkd

### Steps to Reproduce
The problem does not go away when I restart the bot

### Other Information
OS: 
Mac OS
Branch: 
dev
Git Commit: 
fcc2a3f2b42a6249d83509d2ecacbecc77adc009
Python Version: 
Python 2.7.12
Any other relevant files/configs (eg: path files) 

### Correction
I'm sorry the exchange problem was because I was using the dratini as buddy

**Comment by Anakin5** [comment]
Can you reproduce or did it just happen one time ?

**Comment by sebamenabar** [comment]
The upgrade problem does not go away when I restart the bot

**Comment by Anakin5** [comment]
Did you verify that the Pokemon you want to upgrade are matching your configuration ?
For example, what Pokemon would you expect to upgrade ?

**Comment by sebamenabar** [comment]
I have a Flareon and a Jolteon that should be upgraded

**Comment by Anakin5** [comment]
Looks like the upgrade fail for one of them. Is one of them in a gym or something ?

**Comment by sebamenabar** [comment]
Nope, none in gyms an also the upgrade that appears in the log never happens
