### ISSUE TITLE
After update no more logs

### ISSUE THREAD

**Issue by marioacarvalho** [PokemonGoF/PokemonGo-Bot#5633]
After update this week this is the only thing I got. After 2 hours I only get 1000XP, nothing compared with last week. Any idea?

<img width="1438" alt="screen shot 2016-09-23 at 12 35 03" src="https://cloud.githubusercontent.com/assets/1671532/18784492/4fdc8d16-818a-11e6-8893-99283df84991.png">

**Comment by javajohnHub** [comment]
Closing due to not enough info.

**Comment by Gobberwart** [comment]
@marioacarvalho Please use the issue template in future, and provide your config so we can have a chance to help you.
