### ISSUE TITLE
Releasing pokemon feature - Keep Favourites

### ISSUE THREAD

**Issue by Paradoxum** [PokemonGoF/PokemonGo-Bot#5638]
### Short Description
Releasing pokemon feature

### Possible solution
    "release": {
      "any": {"keep_best_iv": 1, **"keep_favourite_pokemon": 1}**,

(1 = never release a pokemon with Favoured status, regardless of IV or CP)

### How it would help others
I've got EG; 3 porygon I want to keep, but I have 7 of them, if I do keep_best_iv=3, it will keep the 3 I favourited, but it will also keep every other pokemon with the best IV, including rattattas etc, unless I manually create an entry for every single pokemon.

**Comment by PokemonGoZ** [comment]
Favorite Pokemon can't be released, so the bot skips over them. Also, you can do the following:

`
"release": {
  "any": {"keep_best_iv": 1},
  "Porygon": {"keep_best_iv": 3}
                 },
`

This would keep the best 1 IV Pokemon, but have an exception to keep the best 3 IV Porygons. To make it easier, just go into the app with location services off, and favorite the pokemon you want to keep. It will then skip over those.

**Comment by Paradoxum** [comment]
tell that to my kangaskhans the bot released which were all favourited...
