### ISSUE TITLE
Errors after last update

### ISSUE THREAD

**Issue by shudack** [PokemonGoF/PokemonGo-Bot#5646]
Hi,

After last update i had this errors:
http://pastebin.com/T0qVdDuH

Can you help me please?

Best regards,
Shduack

**Comment by boyw165** [comment]
Me too.

**Comment by thuram1770** [comment]
Me too

**Comment by Gobberwart** [comment]
pip install -r requirements.txt --upgrade

Does that help?

**Comment by hvk3** [comment]
^ Didn't work. The last merge messed something up in the login process.

**Comment by Gobberwart** [comment]
No it really didn't. It's working fine.

**Comment by Gobberwart** [comment]
Fixed
