### ISSUE TITLE
Starting Bot with TOR now won't work

### ISSUE THREAD

**Issue by supergithubo** [PokemonGoF/PokemonGo-Bot#5649]
I've been using TOR (torify) for the earlier releases and everything works fine. I'm running my bot on an AWS instance and since most IP address of AWS are banned, torify is a perfect workaround. The problem occured with the latest release (buddy pokemon batch). 

### Expected Behavior
Bot should start normally using TOR (torify)

### Actual Behavior
Bot not starting after the latest update

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/tLdtbZey

### Output when issue occurred

after running `torify ./run.sh`:

`
2016-09-24 05:01:01,298 [       cli] [INFO] PokemonGO Bot v1.0
2016-09-24 05:01:01,314 [       cli] [INFO] commit: fd495448
2016-09-24 05:01:01,317 [       cli] [INFO] Configuration initialized
[2016-09-24 05:01:01] [PokemonGoBot] [INFO] Setting start location.
05:01:01 libtorsocks(6656): connect: Connection is to a local address (127.0.0.1), may be a TCP DNS request to a local DNS server so have to reject to be safe. Please report a bug to http://code.google.com/p/torsocks/issues/entry if this is preventing a program from working properly with torsocks.
`

### Steps to Reproduce
`torify ./run.sh`

### Other Information
OS: 
Ubuntu 14.04.5 LTS

Branch: 
master

Git Commit: 
fd49544

Python Version: 
2.7.6

**Comment by ultrafunkamsterdam** [comment]
Uncomment following lines in /etc/tor/torrc:

ControlPort 9051
CookieAuthentication 1
and set:
CookieAuthentication 0

sudo /etc/init.d/tor restart 

. torsocks on >/dev/null 2>&1

torify curl whatismyip.akamai.com/

**Comment by supergithubo** [comment]
@ultrafunkamsterdam I'll give it a try. I've been using torify since start and my account is level 27. There are some instances that the ip gets banned but I modified the bot to execute 'tor restart | reload' when the bot encountered IP ban error.

**Comment by supergithubo** [comment]
@ultrafunkamsterdam still not working. I guess the issue is not with tor configs since I can use the PokemonGo Map using torify perfectly. I think the issue is caused by the latest bot release.

**Comment by ultrafunkamsterdam** [comment]
I installed it based on your OP. Do you use maps from PokemonGoMap? Does it perform well (fast enough?)

**Comment by supergithubo** [comment]
@ultrafunkamsterdam yes if performs well. Are you still using torify on the latest bot release?

**Comment by Gobberwart** [comment]
Issue is tor related. Not bot. Closing.
