### ISSUE TITLE
Could not fetch data from PokemonGo-Map instance using Sniper

### ISSUE THREAD

**Issue by acurioustale** [PokemonGoF/PokemonGo-Bot#5652]
### Expected Behavior
The bot fetches data from a local PokemonGo-Map instance and snipes Pokémon accordingly.

### Actual Behavior
The bot displays an error message and doesn't snipe Pokémon.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
[chemnitz.json](http://pastebin.com/b2G6sKej)

### Output when issue occurred
> [2016-09-24 10:40:52] [    Sniper] [INFO] Could not fetch data from 'http://localhost:5000/raw_data'. Details: 'NoneType' object has no attribute 'replace'. Skipping...

### Steps to Reproduce
1. Run PokemonGo-Map
2. Run PokemonGo-Bot

### Other Information
OS:  macOS 10.12 
Branch: dev
Git Commit: e262b95eb15f144c89c1f17ffe434cecb4b3e9e6
Python Version: Python 2.7.12
Any other relevant files/configs (eg: path files) [path1.gpx](http://pastebin.com/QMPPbbDw)

**Comment by acurioustale** [comment]
I added the following to [sniper.py](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/sniper.py) to account for Nidoran F and Nidoran M as suggested [here](https://github.com/PokemonGoF/PokemonGo-Bot/commit/3b52047d0b3099ce89d4f571bcdc9300747dcc47):

```
name = name.replace("Nidoran\u2642","nidoran m")
name = name.replace("Nidoran\u2640","nidoran f")```

I also tried removing the name mapping, but the error still appears:

```"name": {
	"param": "pokemon_name"
},```

Same for a clean install of e262b95eb15f144c89c1f17ffe434cecb4b3e9e6.

**Comment by Gobberwart** [comment]
Try adding `if name:` to the top of fixname, see if that helps. If so, we might need to put that in.

**Comment by acurioustale** [comment]
That seems to have worked.

Thanks!

**Comment by Gobberwart** [comment]
OK I'll put in a PR for it

**Comment by Gobberwart** [comment]
#5661 should fix this for all
