### ISSUE TITLE
Nickname does not work for 2 conditions

### ISSUE THREAD

**Issue by abhinavagrawal1995** [PokemonGoF/PokemonGo-Bot#5654]
### Expected Behavior

          "nickname_above_iv": 0.8,
          "nickname_above_cp": 1500,
Expecting all pokemon above 1500 cp OR above 0.8 iv to be nicknamed

### Actual Behavior

Only pokemon above 0.8 iv nicknamed. Regardless of CP. (below 1500 also nicknamed if iv>0.8

{
        "type": "NicknamePokemon",
        "config": {
          "enabled": true,
          "nickname_above_iv": 0.8,
          "nickname_above_cp": 1500,
          "nickname_template": "{iv_pct}-{attack_code}-{name}",
          "nickname_wait_min": 3,
          "nickname_wait_max": 5
        }
      },

**Comment by Gobberwart** [comment]
nickname_above_cp is not supported by NicknamePokemon task.

**Comment by abhinavagrawal1995** [comment]
In that case, this please reopen as feature request

**Comment by Gobberwart** [comment]
Please resubmit as feature request.
