### ISSUE TITLE
Conditions to enable Sniper

### ISSUE THREAD

**Issue by abhinavagrawal1995** [PokemonGoF/PokemonGo-Bot#5655]
### Short Description
Add a set of conditions similar to MoveToMapPokemon in Sniper
like: 

"max_sniping distance": 10000,
      "max__walking_distance": 500,
      "min_time": 60,
      "min_ball": 50,
      "prioritize_vips": true,

Also, add a minimum great ball and minimum ultra ball condition to both sniping tasks.
### How it would help others
Sniping with only a few pokeballs and no greatballs to catch a dragonite would end up with the player having no balls if the pokemon doesn't vanish in time.

**Comment by Gobberwart** [comment]
And nobody likes a player with no balls, amirite?

**Comment by Gobberwart** [comment]
One of the designer's intentions for Sniper was to keep config to a minimum which has both positive and negative impacts. MoveToMapPokemon is highly configurable, but also unwieldy and leads to confusion, so I'm not sure this is a great idea. @YvesHenri your thoughts?

**Comment by abhinavagrawal1995** [comment]
At bare minimum, at least a condition for checking number of great balls?

**Comment by Gobberwart** [comment]
I'm in the process of putting together some code that will automatically disable ALL catching tasks when a ball-threshold is reached, for a user-configurable time period.  Something like:

```
{
  "type": "CatchPokemonLimiter",
  "config": {
    "enabled": true,
    "min_balls": 20,
    "duration": 15
  }
}
```

Would basically turn off ALL catch tasks (sniper, mtmp, regular catching) for a period of 15 minutes if less than 20 balls on hand. Would automatically resume after 15 minutes... assuming more than 20 balls, which there should be after 15 minutes of looting, but you could increase that to 30 minutes, change the ball threshold etc.

Would that work for you?

**Comment by abhinavagrawal1995** [comment]
That would work even better than what I had in mind.
