### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#5664]
I reinstalled Windows 10 system. After install python and run the bot, i got this error, the last line.

Fetching origin
HEAD is now at fd49544 Merge pull request #5645 from PokemonGoF/dev
From https://github.com/PokemonGoF/PokemonGo-Bot
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Requirement already up-to-date: numpy==1.11.0 in e:\master\lib\site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: networkx==1.11 in e:\master\lib\site-packages (from -r requirements.txt (line 2))
Obtaining pgoapi from git+https://github.com/pogodevorg/pgoapi.git/@3a02e7416f6924b1bbcbcdde60c10bd247ba8e11#egg=pgoapi (from -r requirements.txt (line 3))
  Skipping because already up-to-date.
    Complete output from command python setup.py egg_info:
    d:\p\python27\Lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
      warnings.warn(msg)
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: invalid command 'egg_info'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in e:\master\src\pgoapi\

**Comment by avexus** [comment]
Actually, this error comes from the command:

>pip install -r requirements.txt --upgrade

**Comment by Gobberwart** [comment]
From Windows 10 manual install instructions:

```
cd C:\Python27\
pip2 install --upgrade pip
pip2 install --upgrade virtualenv
pip2 install --upgrade protobuf==3.0.0b4
git clone --recursive -b dev https://github.com/PokemonGoF/PokemonGo-Bot
pip2 install --upgrade -r C:/Python27/PokemonGo-Bot/requirements.txt
```

Try that and see how you go.

**Comment by Gobberwart** [comment]
Also make sure you've installed the requirements:

```
- [Python 2.7.x](http://docs.python-guide.org/en/latest/starting/installation/) *Be sure to tick "Add python.exe to Path" during install*
- [git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
- [Microsoft Visual C++ Compiler for Python 2.7](http://www.microsoft.com/en-us/download/details.aspx?id=44266)
```

**Comment by avexus** [comment]
@Gobberwart I did a clean install of the bot and it works. However, there is a line contains a bit error, but I guess it doesn't matter. The last line.

Obtaining pgoapi from git+https://github.com/pogodevorg/pgoapi.git/@3a02e7416f6924b1bbcbcdde60c10bd247ba8e11#egg=pgoapi (from -r requirements.txt (line 3))
  Cloning https://github.com/pogodevorg/pgoapi.git/ (to 3a02e7416f6924b1bbcbcdde60c10bd247ba8e11) to e:\others\master\src\pgoapi
  Could not find a tag or branch '3a02e7416f6924b1bbcbcdde60c10bd247ba8e11', assuming commit.
