### ISSUE TITLE
CatchLimiter

### ISSUE THREAD

**Issue by mmeulstee** [PokemonGoF/PokemonGo-Bot#5666]
### Short Description

I love the new function "CatchLimiter".
      {
        "type": "CatchLimiter",
        "config": {
          "enabled": true,
          "min_balls": 20,
          "duration": 15
        }
      },
### Possible solution

Wouldn't be nicer to have the choice on which Pokeballs you wanna have on 20.
      {
        "type": "CatchLimiter",
        "config": {
          "enabled": true,
 -       "min_balls": 20,
+       "pokeball": 15,
+       "greatball": 20,
+       "ultraball": 10,
          "duration": 15
        }
      },

**Comment by Gobberwart** [comment]
I considered that, but wanted to get it at least started without making it too complex. Pending feedback from others, this is an option to consider.

**Comment by acurioustale** [comment]
If this is added, we probably should remove `min_ultraball_to_keep` from `CatchPokemon`.

**Comment by mmeulstee** [comment]
indeed to not have any conflicts

**Comment by Gobberwart** [comment]
@acurioustale No need to remove that. Even if we implement this, it will work differently.
