### ISSUE TITLE
Too many potions discarded

### ISSUE THREAD

**Issue by abhinavagrawal1995** [PokemonGoF/PokemonGo-Bot#5668]
### Expected Behavior
Expecting my player to have a lot of potions after running the bot for around 72 hours, and never battling a single gym.

### Actual Behavior
[2016-09-25 17:29:23] [RecycleItems] [INFO] Forcing item recycle based on schedule
[2016-09-25 17:29:23] [RecycleItems] [INFO] Next forced item recycle at 17:32:17
[2016-09-25 17:29:27] [ItemRecycler] [INFO] Discarded 4x Potion.
[2016-09-25 17:29:32] [ItemRecycler] [INFO] Discarded 1x Super Potion.
[2016-09-25 17:29:37] [ItemRecycler] [INFO] Discarded 1x Hyper Potion.
[2016-09-25 17:29:42] [ItemRecycler] [INFO] Discarded 1x Max Potion.

 [UpdateLiveInventory] [INFO] Pokemon Bag: 248/250
 [UpdateLiveInventory] [INFO] Items: 183/350
[UpdateLiveInventory] [INFO] Potion: 2 | SuperPotion: 1 | HyperPotion: 0 | MaxPotion: 50

The bot keeps discarding hyper potions and super potions randomly even though I clearly have a lack of these.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
{
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 15,
          "max_balls_keep": 200,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 20,
          "item_filter": {
            "Pokeball":       { "keep" : 40 },
            "Potion":         { "keep" : 30 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          },
          "recycle_wait_min": 3,
          "recycle_wait_max": 5,
          "recycle_force": true,
          "recycle_force_min": "00:01:00",
          "recycle_force_max": "00:05:00"
        }
      }

Also, doe the "item_filter" accept "GreatBalls" and "UltraBalls" as parameters ?

**Comment by db-coder** [comment]
Remove: "max_potions_keep": 50,
or increase the value

**Comment by abhinavagrawal1995** [comment]
Removing that would make the player run out of inventory spaces very soon right?
"max_potions_keep": 50
is this applicable only on "Potions" or the sum of all types of potions?

**Comment by db-coder** [comment]
It's applicable to the sum of all types of potions. So either increase the value or just remove it. Other parameters (n item_filter) will take care of the inventory space.

**Comment by elexiel** [comment]
dude if u keep alrdy  200 balls and u have only 350 slots in total, where should it keep the rest?!

**Comment by abhinavagrawal1995** [comment]
@elexiel I don't have 200 pokeballs. That's the max limit I've set.

**Comment by abhinavagrawal1995** [comment]
@db-coder does the config for RecycleItems recognise the parameter "Max Potion" ?
