### ISSUE TITLE
Encryption file location, does it work if I put it into another dir?

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#5670]
I have several instances of bots. If I put the encryption file to each bot's root dir, they all work. But that involves copying multiple times.
If I put them into a separate location and want the bot to use it, I got the following error.

in auth.json, I have the following (the double \ becomes single \ after I hit 'comment'):
   "encrypt_location": "E:\\GoogleDrive\\Game\\encrypt_64.dll",

After running, I have:

[] [PokemonGoBot] encrypt_64.dll is not found! Please place it in the bots root directory or set encrypt_location in config.
[] [PokemonGoBot] Platform: win32 encrypt_64.dll directory: E:\GoogleDrive\Game\encrypt_64.dll

E:\GameDownload\master>dir  E:\GoogleDrive\Game\encrypt_64.dll
 Volume in drive E is Data
 Volume Serial Number is A216-E9EC

 Directory of E:\GoogleDrive\Game

08/07/2016  09:19 AM           347,952 encrypt_64.dll
               1 File(s)        347,952 bytes
               0 Dir(s)  208,713,916,416 bytes free

**Comment by crvfts** [comment]
"encrypt_location": "E:/GoogleDrive/Game",

**Comment by avexus** [comment]
@crvfts thank you. it worked.
