### ISSUE TITLE
telegram token

### ISSUE THREAD

**Issue by ukos-git** [PokemonGoF/PokemonGo-Bot#5692]
Hello.
I can not activate the telegram task.
I created a new bot in telegram and i got a token back:

> Done! Congratulations on your new bot. You will find it at telegram.me/pokemon_main_bot. You can now add a description, about section and profile picture for your bot, see /help for a list of commands. By the way, when you've finished creating your cool bot, ping our Bot Support if you want a better username for it. Just make sure the bot is fully operational before you do this.
> 
> Use this token to access the HTTP API:
> 1234:CENSSORED
> 
> For a description of the Bot API, see this page: https://core.telegram.org/bots/api

I created a standard config but the telegram task raises an InvalidToken error.
Can someone explain how I should create my config file for it. Currently it is like that:

```
{
    "type": "TelegramTask",
    "config": {
        "enabled": true,
        "master": "myUserNameFromTelegram",
        "telegram_token": "1234:CENSSORED",
        "alert_catch": {
          "all": {"operator": "and", "cp": 1300, "iv": 0.95},
          "Snorlax": {"operator": "or", "cp": 900, "iv": 0.9}
        }
    }
}
```

**Comment by javajohnHub** [comment]
That is pretty wrong.
try this:
in auth.json

{
    "auth_service": "ptc",
    "username": "******",
    "password": "******",
    "location": "37.80793, -122.475",
    "favorite_locations":[
        {"name": "Detroit", "coords": "42.3293, -83.0398"},
        {"name": "SF", "coords": "37.8075, -122.4732"}
    ],
    "gmapkey": "*****************",
    "encrypt_location": "",
    "telegram_token": "1234:CENSSORED"
}

and in config.json:

{
        "type": "TelegramTask",
        "config": {
          "enabled": true,
          "password": "ANY PASSWORD YOU WANT",
          "// old syntax, still supported: alert_catch": ["all"],
          "// new syntax:": {},
          "alert_catch": {
            "all": {"operator": "and", "cp": 0, "iv": 0.01}
          }
        }
      },

**Comment by ukos-git** [comment]
ah ... thank you.
I missed the `telegram_token` entry in the auth.json file.
what about the `master` entry?

**Comment by javajohnHub** [comment]
Please close this issue if everything is working now.  Master is not needed
