### ISSUE TITLE
datetime

### ISSUE THREAD

**Issue by ukos-git** [PokemonGoF/PokemonGo-Bot#5693]
The last merged commit seems to be broken in my place here. Could someone confirm this? I commented on the line

https://github.com/PokemonGoF/PokemonGo-Bot/commit/c53a57e9a2fc43844e62c6492883b5346042e5c3

**Comment by iruy** [comment]
Same here

**Comment by ukos-git** [comment]
ok.
can someone revert the last commit and mark it as bugged?
I checked out HEAD~1 and everything is fine there.

**Comment by alexyaoyang** [comment]
Fixed, closing
