### ISSUE TITLE
Bot stops capturing pokemons once the server gets laggy

### ISSUE THREAD

**Issue by dmateusp** [PokemonGoF/PokemonGo-Bot#57]
Testing the bot right now, a time when the Server must be busy,

The bot finds pokemons and a message like
"A Wild Spearow appeared! [CPXXX]"
is printed out. But instead of being followed by either :
"Attempted to capture Spearow - failed.. trying again" **OR** "Captured Spearow!"
It is followed by another Pokemon encounter 

"A Wild Spearow appeared! [CPXXX]"
"A Wild Weedle appeared! [CPXXX]"

My wild guess is that it is the "freezing pokeball" phenomenon that happens on the app as well..

I'm new to the code so I'm not sure about what's happening here but I guess in that situation we should stay on the same spot until the pokemon is captured or goes away instead of moving on with the pokemon still there ?

Also I think those messages should all be logged with a time and I would love to do it :)

**Comment by millejosh** [comment]
@dmateusp are you out of normal Pokeballs by chance?

**Comment by dmateusp** [comment]
No I'm not, and as I described, during the same run of the app if the server becomes stable again the bot will catch pokemons again
