### ISSUE TITLE
PokemonOptimizer Buddy/Family Bug

### ISSUE THREAD

**Issue by RedViper9** [PokemonGoF/PokemonGo-Bot#5702]
### Expected Behavior
Log shows correct family for pokemon.

### Actual Behavior
PokemonOptimizer seems to think that dragonair is in the mew family.

### Your FULL config.json 
I use the BuddyPokemon task and do not define a buddy in PokemonOptimizer.
http://pastebin.com/JNVpNQ6s

### Output when issue occurred
[2016-09-26 15:33:18] 1 Dratini candy earned. You now have 49 candy!
[2016-09-26 15:33:19] Buddy Dragonair rewards Mew candies [+0 candies] [0 candies]
[2016-09-26 15:33:24] Buddy Dragonair rewards Mew candies [+0 candies] [0 candies]

### Steps to Reproduce
Walk a dragonair.

### Other Information
OS: Mint 18
Branch: Dev
Git Commit: c53a57e9a2fc43844e62c6492883b5346042e5c3
Python Version: 2.7.12

**Comment by Anakin5** [comment]
It is because of the other buddy task getting the candy first.
