### ISSUE TITLE
[Feature Request] Use candy to Power UP.

### ISSUE THREAD

**Issue by takenek** [PokemonGoF/PokemonGo-Bot#5709]
Hello
I just see on webpage there is "Use Candy" Features complete - how i can use this?
I want to use Candy to Power UP my Pokemons with the best iv.
So if i got 5 pokemons with iv:
0.7
0.4
0.6
0.8
0.9
I want to use my Candys and Dusts to"Power UP" Pokemons in this order: 0.9 > 0.8 > 0.7 >0.6 >0.4

Best Regards
TaKeN

**Comment by beltoft** [comment]
use optimizer task

**Comment by takenek** [comment]
What Your mean? How to use this?

**Comment by beltoft** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/pokemon_optimizer.md
