### ISSUE TITLE
Session stale, re-logging in

### ISSUE THREAD

**Issue by gise88** [PokemonGoF/PokemonGo-Bot#5712]
### Expected Behavior
The bot remains logged in

### Actual Behavior
`Session stale, re-logging in.` A lot of times

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
http://pastebin.com/marNFBVM

### Output when issue occurred
http://pastebin.com/RyfmP1fm

### Other Information
OS: 
Arch Linux 4.7.4-1-ARCH #1 SMP PREEMPT Thu Sep 15 15:24:29 CEST 2016 x86_64 GNU/Linux

Branch: 
dev

Git Commit: 
4c380f29a5f195a07815c7eef9c2ca863939120d

Python Version: 
Working with the original docker-compose

**Comment by gise88** [comment]
I've just tried.. Happens the same with master branch!

**Comment by Gobberwart** [comment]
Sounds like some sort of issue with your pokemongo account expiring sessions too quickly. Are you using google or ptc account?

**Comment by gise88** [comment]
Ptc account. But it is weird! Trying it on another pc it works correctly... Could it be a docker problem?

**Comment by Gobberwart** [comment]
Hmm, I didn't realise it worked with the same account on another PC.

Looking at the code, I'm wondering if it might be a timezone issue:

```
            remaining_time = \
                self.api._auth_provider._ticket_expire / 1000 - time.time()

            if remaining_time < 60:
                 <generate log message and re-login>
```

SO it gets ticket expiry from the api, and compares it with your local time, and thinks remaining_time is < 60 seconds... pretty much every time.

**Comment by gise88** [comment]
Fu*k! 😅 It is my old pc and I did not realize that the time was wrong. 
`timedatectl set-ntp true` fix this!
Thanks for your time and sorry for this issue

**Comment by Gobberwart** [comment]
No worries, happy to help.
