### ISSUE TITLE
Program Error on my VPS:

### ISSUE THREAD

**Issue by Kelviniano** [PokemonGoF/PokemonGo-Bot#5733]
Hello, I have a problem in "PokemonGo-Bot" on my VPS, on my computer but it works correctly in my VPS is experiencing an error; Here is a screenshot of the error I'm having: http://prntscr.com/cnswrw

My operating system: Windows 7 Professional
Python Version: 2.7.10

How can I fix this error?

Thanks for reading

**Comment by ukos-git** [comment]
that is way to few information.

**Comment by Kelviniano** [comment]
what else is needed?
I have no experience whatsoever with it.

**Comment by ukos-git** [comment]
What works and what not? Your semantic structure in the explaination you gave is not logical. Try to put it in better english.
Can you start the bot normally via the bash script ./run.sh and output the full error message (as text). 
Please don't use any other language than english in the compiler-output. I also think that your error messages you posted as a screen shot are not complete.
which branch/commit are you?
Did the bot run before and what did you do that it doesn't run anymore.
also: please give me a hint, what VPS should mean. I'm no expert in windows shells but I think you ran it in some virtual environment?
What have you tried so far, can you nail down the problem in a certain direction ...

**Comment by rawgni** [comment]
different bot
