### ISSUE TITLE
Feature request : Notification when a pokemon is kicked out of a gym.

### ISSUE THREAD

**Issue by dogeatdog** [PokemonGoF/PokemonGo-Bot#5742]
### Short Description

A warning if a pokemon which has been placed in a gym has been kicked out in the logs.

### Possible solution

Read the pokemon status of every pokemon in your bag, in particular the health and placement in a gym. Store this. Read it again after a minute (or a recheck_interval in the config) and compare it to the last statuses. Then update it again. Keep repeating this.

If the status changes from "in_gym" to "not_in_gym" (obviously I don't know the real attributes..) then put out a warning : 'Pokemon Electrabuzz was kicked out of gym (gym_id/name), health is now "health"'. 

This would also be very helpful if it was outputted via a Telegram/Discord message.

### How it would help others

Although we don't use the bot to fight battles for us, it might be useful to get a warning if a pokemon we placed in a gym is kicked out, so we can quit the bot and go outside to the gym and fight again.

**Comment by YvesHenri** [comment]
We do not, and will not, support gym features.

**Comment by dogeatdog** [comment]
Ok, sorry I asked. I knew you did not support fighting in a gym. Didn't know that just logging stuff would also violate that 'We don't code for gym stuff'-policy. My bad.
