### ISSUE TITLE
QUERY: CatchPokemon vs Catch tasks

### ISSUE THREAD

**Issue by ravey-davey** [PokemonGoF/PokemonGo-Bot#5743]
### Expected Behaviour
I have both the CatchPokemon and Catch tasks configured as per below.

Unless I'm doing something wrong (which I fully concede I may be), I would expect the CatchPokemon task to reference the Catch task, skipping the Pidgey (and a bunch of other 'junk' Pokemon I have way too many of). Instead it appears to ignore it completely, catching pretty much every Pokemon..

### Actual Behaviour
Instead, it's catching all of the Pokemon I've set for it to not catch..

[2016-09-30 12:19:20] [MainThread] [PokemonCatchWorker] [INFO] A wild Pidgey appeared! (CP: 123 IV: 0.31 A/D/S 3/1/10 NCP: 0.18)
[2016-09-30 12:19:28] [MainThread] [PokemonCatchWorker] [INFO] OK throw! Used Pokeball, with chance 53.30 (19 left)
[2016-09-30 12:19:28] [MainThread] [PokemonCatchWorker] [INFO] Captured Pidgey! (CP: 123 IV: 0.31 3/1/10 NCP: 0.18) Catch Limit: (168/500) +100 exp +100 stardust
[2016-09-30 12:19:28] [MainThread] [PokemonCatchWorker] [INFO] You now have 572 Pidgey candy!

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
{
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": true,
    "live_config_update": {
      "enabled": false,
      "tasks_only": false
    },
    "tasks": [
      {
	"type": "TelegramTask",
	"config": {
	  "enabled": false,
	  "master": null,
	  "password": null,
	  "alert_catch": {
	    "all": {"operator": "and", "cp": 1300, "iv": 0.95},
	    "Snorlax": {"operator": "or", "cp": 900, "iv": 0.9}
	  }
	}
      },
      {
	"type": "DiscordTask",
	"config": {
	  "enabled": false,
	  "master": null,
          "alert_catch": {
            "all": {"operator": "and", "cp": 1300, "iv": 0.95},
            "Snorlax": {"operator": "or", "cp": 900, "iv": 0.9}
          }
	}
      },
      {
	"type": "RandomAlivePause",
	"config": {
	  "enabled": false,
	  "min_duration": "00:00:10",
	  "max_duration": "00:10:00",
	  "min_interval": "00:05:00",
	  "max_interval": "01:00:00"
	}
      }, 
      {
        "type": "HandleSoftBan"
      },
      {
	"type": "RandomPause",
	"config": {
	  "enabled": true,
	  "min_duration": "00:00:10",
	  "max_duration": "00:02:00",
	  "min_interval": "00:02:00",
	  "max_interval": "00:10:00"
	}
      },
      {
	"type": "CompleteTutorial",
	"config": {
	  "enabled": false,
	  "nickname": "",
	  "// 0 = No Team, 1 = Blue, 2 = Red, 3 = Yellow": "",
	  "team": 1
	}
      },
      {
        "type": "CollectLevelUpReward",
	"config": {
	  "collect_reward": true,
	  "level_limit": -1
	}
      },
      {
	"type": "BuddyPokemon",
	"config": {
	  "enabled": true,
	  "buddy_list": "vulpix",
	  "best_in_family": true,
	  "candy_limit": 0,
	  "force_first_change": false,
	  "buddy_change_wait_min": 3,
	  "buddy_change_wait_max": 5,
	  "min_interval": 120
	}
      },
      {
	"type": "IncubateEggs",
	"config": {
	  "enabled": true,
	  "infinite_longer_eggs_first" : false, 
	  "breakable_longer_eggs_first": true,
	  "min_interval" :      120,
	  "infinite" :          [2,5,10],
	  "breakable" :         [2,5,10]
	}
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": true,
          "min_interval": 25,
          "stats": ["uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
	"type": "UpdateLiveInventory",
	"config": {
	  "enabled": true,
	  "min_interval": 120,
	  "show_all_multiple_lines": false,
	  "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
	}
      },
      {
	"type": "ShowBestPokemon",
	"config": {
	  "enabled": true,
	  "min_interval": 60,
	  "amount": 5,
	  "order_by": "cp",
	  "info_to_show": ["cp", "ivcp", "dps", "hp"]
	}
      },
      {
        "type": "TransferPokemon",
	"config": {
	  "enabled": true,
	  "min_free_slot": 50,
	  "transfer_wait_min": 3,
	  "transfer_wait_max": 5
	}
      },
      {
	"type": "NicknamePokemon",
	"config": {
	  "enabled": false,
	  "nickname_above_iv": 0.9,
	  "nickname_template": "{name:.6}_{iv_pct}",
	  "nickname_wait_min": 3,
	  "nickname_wait_max": 5
	}
      },
      {
        "type": "EvolvePokemon",
        "config": {
	    "enabled": false,
	    "evolve_list": "all",
	    "donot_evolve_list": "Abra, Bellsprout, Bulbasaur, Charmander, Charmeleon, Clefairy, Eevee, Gastly, Geodude, Gloom, Growlithe, Ivysaur, Machop, Magikarp, Nidoran F, Nidoran M, Nidoina, Nidorino, Oddish, Paras, Pidgey, Pikachu, Poliwag, Squirtle, Staryu, Tentacool, Venonat, Vulpix, Wartortle, Weepinbell",
            "first_evolve_by": "cp",
	    "evolve_above_cp": 500,
            "evolve_above_iv": 0.8,
            "logic": "or",
            "min_evolve_speed": 25,
	    "max_evolve_speed": 35,
	    "min_pokemon_to_be_evolved": 1,
            "use_lucky_egg": false
        }
      },
      {
	"type": "UseIncense",
	"config": {
	  "use_incense": false,
	  "use_order": [
	    "ordinary",
	    "spicy",
	    "cool",
	    "floral"
	  ]
	}
      },
      {
        "type": "RecycleItems",
        "config": {
	  "enabled": true,
          "min_empty_space": 15,
          "item_filter": {
            "Pokeball":       { "keep" : 65 },
	    "Greatball":      { "keep" : 60 },
	    "Ultraball":      { "keep" : 50 },
            "Potion":         { "keep" : 15 },
	    "Super Potion":   { "keep" : 15 },
	    "Hyper Potion":   { "keep" : 20 },
	    "Max Potion":     { "keep" : 25 },
            "Revive":         { "keep" : 10 },
            "Razz Berry":     { "keep" : 50 }
          },
	  "recycle_wait_min": 3,
	  "recycle_wait_max": 5,
	  "recycle_force": true,
	  "recycle_force_min": "00:01:00",
	  "recycle_force_max": "00:05:00"
        }
      },
      {
	"type": "CatchLimiter",
	"config": {
	  "enabled": true,
	  "min_balls": 20,
	  "duration": 15
	}
      },
      {
	"type": "Sniper",
	"config": {
	  "enabled": false,
	  "mode": "social",
	  "bullets": 1,
	  "homing_shots": true,
	  "special_iv": 100,
	  "order": ["missing", "vip", "priority"],
	  "sources": [
	      {
		"enabled": false,
		"url": "http://localhost:5000/raw_data",
		"timeout": 3,
		"key": "pokemons",
		"mappings": {
		  "id": { "param": "pokemon_id" },
		  "name": { "param": "pokemon_name" },
		  "latitude": { "param": "latitude" },
		  "longitude": { "param": "longitude" },
		  "expiration": { "param": "dissapear_time", "format": "milliseconds" }
		}
	      },
	      {
		"enabled": false,
		"url": "https://pokewatchers.com/grab/",
		"timeout": 10,
		"mappings": {
		  "iv": { "param": "iv" },
		  "id": { "param": "pid" },
		  "name": { "param": "pokemon" },
		  "latitude": { "param": "cords" },
		  "longitude": { "param": "cords" },
		  "expiration": { "param": "timeend", "format": "milliseconds" }
		}
	      },
	      {
		"enabled": false,
		"url": "http://pokesnipers.com/api/v1/pokemon.json",
		"timeout": 10,
		"key": "results",
		"mappings": {
		  "iv": { "param": "iv" },
		  "name": { "param": "name" },
		  "latitude": { "param": "coords" },
		  "longitude": { "param": "coords" },
		  "expiration": { "param": "until", "format": "utc" }
		}
	      }
	    ],
	    "catch": {
		"Blastoise": 10,
		"Charizard": 10,
		"Dragonair": 10,
		"Dragonite": 10,
		"Exeggutor": 10,
		"Electabuzz": 10,
		"Gyarados": 10,
		"Ivysaur": 10,
		"Kabutops": 10,
		"Laprass": 10,
		"Machamp": 10,
		"Magmar": 10,
		"Magneton": 10,
		"Marowak": 10,
		"Muk": 10,
		"Ninetales": 10,
		"Omastar": 10,
		"Pikachu": 10,
		"Porygon": 10,
		"Raichu": 10,
		"Snorlax": 10,
		"Tangela": 10,
		"Venosaur": 10,
		"Weezing": 10,
		"Wigglytuff": 10 
	    }
	  }
      },
      {
        "type": "CatchPokemon",
	"config": {
	  "enabled": true,
	  "catch_visible_pokemon": true,
	  "catch_lured_pokemon": true,
	  "catch_incensed_pokemon": true,
	  "min_ultraball_to_keep": 5,
	  "berry_threshold": 0.25,
	  "vip_berry_threshold": 0.9,
	  "treat_unseen_as_vip": true,
	  "daily_catch_limit": 500,
	  "vanish_settings": {
	    "consequtive_vanish_limit": 5,
	    "rest_duration_min": "02:00:00",
	    "rest_duration_max": "04:00:00"
	  },
	  "catch_throw_parameters": {
	    "excellent_rate": 0.2,
	    "great_rate": 0.5,
	    "nice_rate": 0.3,
	    "normal_rate": 0.2,
	    "spin_success_rate": 0.9,
	    "hit_rate": 0.75
	  },
	  "catch_simulation": {
	    "flee_count": 3,
	    "flee_duration": 2,
	    "catch_wait_min": 3,
	    "catch_wait_max": 6,
	    "berry_wait_min": 3,
	    "berry_wait_max": 5,
	    "changeball_wait_min": 3,
	    "changeball_wait_max": 5,
	    "newtodex_wait_min": 20,
	    "newtodex_wait_max": 30
	  }
	}
      },
      {
        "type": "SpinFort",
	"config": {
	    "enabled": true,
	    "spin_wait_min": 2,
	    "spin_wait_max": 5,
	    "daily_spin_limit": 450
	}
      },
      {
	"type": "UpdateWebInventory",
	"config": {"enabled": true }
      },
      {
	"type": "CampFort",
	"config": {
	  "enabled": true,
	  "min_distance": 2000,
	  "min_forts_count": 1,
	  "min_lured_forts_count": 1,
	  "camping_time": 1800,
	  "moving_time": 600
	}
      },
      {
	"type": "PokemonHunter",
	"config": {
	  "enabled": true,
	  "max_distance": 1500,
	  "hunt_all": false,
	  "hunt_vip": true,
	  "hunt_pokedex": true
	}
      },
      {
        "type": "MoveToFort",
        "config": {
	    "enabled": true,
            "lure_attraction": true,
            "lure_max_distance": 2000,
	    "walker": "StepWalker",
	    "log_interval": 5
        }
      },
      {
	"type":"FollowSpiral",
        "config": {
	  "enabled": true,
          "diameter": 7,
          "step_size": 70
	}
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "pokemon_bag": {
	"show_at_start": true,
	"show_count": true,
	"show_candies": true,
	"pokemon_info": ["cp", "iv_ads", "iv_pct", "ncp", "moveset"]
	},
    "walk_max": 3.16,
    "walk_min": 2.66,
    "alt_min": 500,
    "alt_max": 1000,

    "sleep_schedule": {
      "enabled": true,
      "enable_reminder": true,
      "reminder_interval": 600,
      "entries": [
        {
	  "time": "12:30",
	  "duration": "1:23",
	  "time_random_offset": "00:27",
	  "duration_random_offset": "00:18",
	  "wake_up_at_location": ""
        },
        {
	  "time": "17:00",
	  "duration": "03:00",
	  "time_random_offset": "00:15",
	  "duration_random_offset": "00:30",
	  "wake_up_at_location": ""
        },
        {
	  "time": "23:34",
	  "duration": "10:00",
	  "time_random_offset": "00:22",
	  "duration_random_offset": "00:22",
	  "wake_up_at_location": ""
        }
      ]
    },

    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": true,
    "replicate_gps_z_noise": true,
    "gps_xy_noise_range": 0.000125,
    "gps_z_noise_range": 12.5,
    "debug": false,
    "test": false,
    "walker_limit_timeout": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging": {
      "color": true,
      "show_datetime": true,
      "show_process_name": true,
      "show_log_level": true,
      "show_thread_name": true
    },
    "catch": {
      "// any": {"candy_threshold": 300, "catch_above_cp": 1200, "catch_above_iv": 8.0, "logic": "and"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true },
      "Abra":           { "always_catch" : true },
      "Bellsprout":     { "always_catch" : false },
      "Beedrill":       { "catch_above_cp" : 1000 },
      "Butterfry":	{ "always_catch" : false },
      "Caterpie":       { "always_catch" : false },
      "Clefable":	{ "catch_above_cp" : 1000},
      "Clefairy":       { "always_catch" : false },
      "Cubone":         { "always_catch" : true },
      "Dewgong":	{ "catch_above_cp" : 1000 },
      "Doduo":		{ "always_catch" : false },
      "Diglett":        { "always_catch" : true },
      "Drowzee":        { "always_catch" : false },
      "Eevee":          { "always_catch" : true },
      "Ekans":          { "always_catch" : true },
      "Electrode":	{ "always_catch" : true },
      "Fearow":         { "always_catch" : false },
      "Gastly":         { "always_catch" : false },
      "Geodude":	{ "always_catch" : false },
      "Gloom":		{ "always_catch" : false },
      "Golbat":         { "always_catch" : false },
      "Goldeen":        { "always_catch" : false },
      "Graveler":	{ "always_catch" : true },
      "Grimer":		{ "always_catch" : true },
      "Growlithe":	{ "always_catch" : true },
      "Horsea":         { "always_catch" : false },
      "Hypno":          { "always_catch" : false },
      "Jynx":           { "always_catch" : true },
      "Jigglypuff":     { "always_catch" : true },
      "Kabuto":		{ "always_catch" : true },
      "Kadabra":	{ "always_catch" : true },
      "Kakuna":         { "always_catch" : false },
      "Kingler":        { "always_catch" : false },
      "Koffing":        { "always_catch" : true },
      "Krabby":         { "always_catch" : false },
      "Lickitung":	{ "always_catch" : true },
      "Machoke":	{ "catch_above_cp" : 800 },
      "Machop":         { "always_catch" : true },
      "Magikarp":       { "always_catch" : true },
      "Magnemite":	{ "always_catch" : true },
      "Mankey":         { "always_catch" : true },
      "Meowth":         { "always_catch" : false },
      "Metapod":        { "always_catch" : false },
      "Mr. Mime":       { "always_catch" : true },
      "Nidoran F":      { "always_catch" : false },
      "Nidoran M":      { "always_catch" : false },
      "Nidorina":       { "always_catch" : false },
      "Nidorino":       { "always_catch" : false },
      "Oddish":         { "always_catch" : false },
      "Onyx":           { "always_catch" : true },
      "Paras":          { "always_catch" : false },
      "Parasect":	{ "catch_above_cp" : 1000 },
      "Persian":	{ "always_catch" : true },
      "Pidgeot":	{ "catch_above_cp" : 1000 },
      "Pidgeotto":      { "always_catch" : false },
      "Pidgey":         { "always_catch" : false },
      "Poliwag":        { "always_catch" : false },
      "Polywhirl":	{ "always_catch" : false },
      "Ponyta":         { "always_catch" : true },
      "Psyduck":        { "always_catch" : false },
      "Raticate":       { "always_catch" : false },
      "Rattata":        { "always_catch" : false },
      "Rhydon":		{ "always_catch" : true },
      "Rhyhorn":        { "always_catch" : true },
      "Sandshrew":      { "always_catch" : true },
      "Scyther":	{ "catch_above_cp" : 1000 },
      "Seadra":		{ "always_catch" : false },
      "Seaking":        { "always_catch" : false },
      "Seel":           { "always_catch" : false },
      "Shellder":       { "always_catch" : false },
      "Slowbro":	{ "always_catch" : true },
      "Slowpoke":       { "catch_above_cp" : 500 },
      "Spearow":        { "always_catch" : false },
      "Starmie":	{ "always_catch" : true },
      "Staryu":         { "always_catch" : false },
      "Tentacool":      { "catch_above_cp" : 500 },
      "Venonat":        { "always_catch" : false },
      "Venomoth":	{ "always_catch" : false },
      "Voltorb":        { "always_catch" : true },
      "Vulpix":		{ "always_catch" : true },
      "Weedle":         { "always_catch" : false },
      "Weepinbell":	{ "always_catch" : false },
      "Zubat":          { "always_catch" : false }
    },
    "release": {
      "Abra": 		{"keep_best_iv": 1, "keep_best_cp": 1},
      "Bellsprout": 	{"keep_best_iv": 2},
      "Beedrill": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Caterpie": 	{"keep_best_iv": 2},
      "Clefairy": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Cubone": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Diglett": 	{"keep_best_iv": 2},
      "Drowzee": 	{"keep_best_iv": 2},
      "Eevee": 		{"keep_best_iv": 6},
      "Ekans": 		{"keep_best_iv": 2},
      "Electabuzz": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Fearow": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Gastly": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Golbat": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Goldeen": 	{"keep_best_iv": 2},
      "Horsea": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Hypno": 		{"keep_best_iv": 1, "keep_best_cp": 1},
      "Jynx": 		{"keep_best_iv": 1, "keep_best_cp": 1},
      "Jigglypuff": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Kakuna": 	{"keep_best_iv": 2},
      "Kingler": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Koffing": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Krabby": 	{"keep_best_iv": 2},
      "Machop": 	{"keep_best_iv": 1},
      "Magikarp": 	{"keep_best_iv": 2},
      "Mankey": 	{"keep_best_iv": 2},
      "Meowth": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Metapod": 	{"keep_best_iv": 1},
      "Mr. Mime": 	{"keep_best_iv": 2, "keep_best_cp": 1},
      "Nidoran F": 	{"keep_best_iv": 1},
      "Nidoran M": 	{"keep_best_iv": 1},
      "Nidorina": 	{"keep_best_iv": 1},
      "Nidorino": 	{"keep_best_iv": 1},
      "Oddish": 	{"keep_best_iv": 2},
      "Onyx": 		{"keep_best_iv": 1, "keep_best_cp": 1},
      "Paras": 		{"keep_best_iv": 2},
      "Parasect": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Pidgeot": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Pidgeotto": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Pidgey": 	{"keep_best_iv": 2},
      "Poliwag": 	{"keep_best_iv": 2},
      "Ponyta": 	{"keep_best_iv": 2, "keep_best_cp": 1},
      "Psyduck": 	{"keep_best_iv": 2},
      "Raticate": 	{"keep_best_iv": 2},
      "Rattata": 	{"keep_best_iv": 2},
      "Rhyhorn": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Sandshrew": 	{"keep_best_iv": 2},
      "Seaking": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Seel": 		{"keep_best_iv": 1, "keep_best_cp": 1},
      "Shellder": 	{"keep_best_iv": 2},
      "Slowpoke": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Spearow": 	{"keep_best_iv": 2},
      "Staryu": 	{"keep_best_iv": 2},
      "Squirtle": 	{"keep_best_iv": 2, "keep_best_cp": 1},
      "Tentacool": 	{"keep_best_iv": 2, "keep_best_cp": 1},
      "Venonat": 	{"keep_best_iv": 2},
      "Voltorb": 	{"keep_best_iv": 1, "keep_best_cp": 1},
      "Weedle": 	{"keep_best_iv": 2},
      "Zubat": 		{"keep_best_iv": 2}
    },
    "vips" : {
         "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},
	"Aerodactyl": {},
	"Alakazam": {},
	"Arbok": {},
        "Arcanine": {},
	"Blastoise": {},
        "Bulbasaur": {},
	"Chansey": {},
	"Charizard": {},
        "Charmander": {},
	"Charmeleon": {},
	"Cloyster": {},
	"Dragonair": {},
	"Dragonite": {},
	"Dratini": {},
	"Dugtrio": {},
	"Electabuzz": {},
	"Exeggcute": {},
        "Exeggutor": {},
	"Golem": {},
        "Gyarados": {},
	"Hitmonchan": {},
	"Hitmonlee": {},
	"Ivysaur": {},
	"Kabutops": {},
	"Laprass": {},
	"Machamp": {},
	"Magmar": {},
	"Magneton": {},
	"Marowak": {},
        "Muk": {},
	"Ninetales": {},
	"Omanyte": {},
	"Omastar": {},
        "Pikachu": {},
	"Polywrath": {},
	"Porygon": {},
	"Primeape": {},
	"Raichu": {},
	"Sandslash": {},
	"Slowbro": {},
        "Snorlax": {},
        "Squirtle": {},
        "Tangela": {},
	"Tentacruel": {},
	"Venosaur": {},
	"Victreebel": {},
	"Vileplume": {},
	"Wartortle": {},
        "Weezing": {},
	"Wigglytuff": {}
    }
}

### Output when issue occurred
See above

### Steps to Reproduce
See above

### Other Information
OS: OSX 10.11.6 (El Capitan)
Branch: dev
Git Commit: f65b063762384d97c5195a55db1b8257ba6cddee
Python Version: Python 2.7.10
Any other relevant files/configs: None

**Comment by Gobberwart** [comment]
"always_catch": false is not the same thing as "never_catch": true.

As per documentation: "For example: `"Pidgey": {"never_catch": true}` will stop catching Pidgey entirely.
