### ISSUE TITLE
[Doubt] Snipe Pokemon Task

### ISSUE THREAD

**Issue by pranavperfect** [PokemonGoF/PokemonGo-Bot#5758]
Will snipe pokemon jump across continents to capture pokemon? Or it can be limited to a specific distance beyond which it will not jump?

**Comment by Gobberwart** [comment]
Yes, it will go wherever your data sources say there are pokemon to catch. No, it cannot be limited. Does it matter? Probably not. If Niantic decides to crack down on sniping, then it will notice a jump of 10km as much as it will notice 10,000km. Probably.
