### ISSUE TITLE
web UI is not loading bot

### ISSUE THREAD

**Issue by beltoft** [PokemonGoF/PokemonGo-Bot#5761]
### Expected Behavior
I can see bot when going to web UI

### Actual Behavior
Bot is not loaded by web UI

I can see the files catchable-XXX inventory-XXX and location-XXX and they are all being updated by the bot 

username in userdata.js is also the same as in my auth file

**Comment by ChaosMarc** [comment]
Please close this issue and reopen it at http://github.com/PokemonGoF/PokemonGo-Web as it is clearly web related.
