### ISSUE TITLE
[Bug Fix] zh_tw translation

### ISSUE THREAD

**Issue by kevinlife** [PokemonGoF/PokemonGo-Bot#5764]
[zh_tw.json.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/510572/zh_tw.json.zip)

1.Fix the translation of "Lapras"
2.Fix the key "Nidoran F"
3.Fix the key "Nidoran M"

**Comment by k4n30** [comment]
Please create a PR request - https://github.com/PokemonGoF/PokemonGo-Bot/pulls
