### ISSUE TITLE
Got Error: "Possibly searching too often, take a rest". Restarted the bot. The bot got stuck after restart

### ISSUE THREAD

**Issue by thermoblasto** [PokemonGoF/PokemonGo-Bot#5767]
The bot was running fine since last week. Today I got 
**

> [2016-10-05 20:54:23] [MainThread] [  SpinFort] [INFO] Possibly searching too often, take a rest.

**

After which I restarted.
After restart the bot get stuck after Evolved notification. Please find the log below. It does not move after  **[MainThread] [EvolvePokemon] [INFO] Evolvable: 0/1 notification.**

> 
> [2016-10-05 21:00:57] [MainThread] [ShowBestPokemon] [INFO] *Best Pokemons* (Pinsir, CP 1322, IVCP 0.42, DPS 13.49, HP 94/94) | (Pinsir, CP 1304, IVCP 0.35, DPS 11.51, HP 94/94) | (Pinsir, CP 1236, IVCP 0.28, DPS 11.51, HP 88/88) | (Scyther, CP 1222, IVCP 0.61, DPS 11.24, HP 93/93) | (Starmie, CP 1151, IVCP 0.51, DPS 15.36, HP 75/75)
> **[2016-10-05 21:00:57] [MainThread] [EvolvePokemon] [INFO] Evolvable: 0/1
> ^C[2016-10-05 21:01:20] [MainThread] [PokemonGoBot] [INFO] Bot caught SIGINT. Shutting down.**
> [2016-10-05 21:01:20] [MainThread] [       cli] [INFO] 
> [2016-10-05 21:01:20] [MainThread] [       cli] [INFO] Ran for 0:00:29
> [2016-10-05 21:01:20] [MainThread] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
> [2016-10-05 21:01:20] [MainThread] [       cli] [INFO] Travelled 0.00km
> [2016-10-05 21:01:20] [MainThread] [       cli] [INFO] Visited 0 stops
> [2016-10-05 21:01:20] [MainThread] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
> [2016-10-05 21:01:20] [MainThread] [       cli] [INFO] Threw 0 pokeballs
> [2016-10-05 21:01:20] [MainThread] [       cli] [INFO] Earned 0 Stardust
> [2016-10-05 21:01:20] [MainThread] [       cli] [INFO] Hatched eggs 0
> [2016-10-05 21:01:20] [MainThread] [       cli] [INFO] Next egg hatches in 0.95 km
> [2016-10-05 21:01:

[config.txt](https://github.com/PokemonGoF/PokemonGo-Bot/files/512042/config.txt)

**Comment by thermoblasto** [comment]
commit: ff7eae5c

**Comment by DragoonJC** [comment]
Niantic just added an image captcha to Pokemon GO requiring you to select the images containing a specific thing.

I was able to log into Pokemon GO on my phone, solve the captcha then run the bot again.

**Comment by ainz0u** [comment]
Just had that issue too. But my bot is in another continent right now, can't log in to solve the captcha... Does it mean that my account will be banned if I don't do the captcha asap? :s:s

**Comment by houkop** [comment]
safetyNet olso updated... can't log in with root((

**Comment by thermoblasto** [comment]
Mine was roaming in Sydney. I just waited 2 hours and open the app on one of the spare devices and solved the captcha.
Not sure if I will sent the bot back. :)

**Comment by ainz0u** [comment]
Mine was in Sydney too! Is it enough to wait 2 hours to open? Sydney is kind of very, very faaaar! I'm in Europe at the moment...
