### ISSUE TITLE
[NEWS] Please read this before running your bot.

### ISSUE THREAD

**Issue by PokemonGoZ** [PokemonGoF/PokemonGo-Bot#5773]
## You probably want to quit using the bot...

With all of the SafetyNet, the Captcha, and the new API the bot is basically a hot pink sports car speeding down a road with police on it.
The official PokemonGo App uses the 0.39 API. The PokemonGoF bot (or any other bot/map/scanner) uses the 0.35 API. If you have the official PokemonGo App on 0.35, then it tells you, you can't log in unless you update. This flags all accounts running the 0.35 API.
0.39 is basically Unknown6 all over again. Some have decompiled it, and the structure is mostly the same, but they would have to FULLY re-crack the API. There aren't as many devs as there were working on 0.35 Unknown6 now, so it is unlikely that we'll see a crack soon.
Captcha is enabled in the 0.39 app. The bot can't bypass the Captcha, therefore if we even crack the 0.39 API, PokemonGo would know who is using an un-authorized client and who's not.
## But you don't have to quit!

If you use PokemonGoF on a spare account, go ahead! We encourage you to your own advantage! This isn't the end of PokemonGoF, and we'll be here pushing updates for you guys.

**Comment by reigelgallarde** [comment]
it's too early to give up...

**Comment by prusswan** [comment]
Thanks for putting up the notice for the benefit of community

**Comment by tihiniko** [comment]
Thank you for the update! Do you think it would be possible to add 2captcha support in the future? or is this still unknown for now?

**Comment by rbusquet** [comment]
In my opinion, who bots for primary account should be worried since the beginning. Botting for fun/science will always be possible (unless Nia does something really crazy about their API 🤔 hehe)

**Comment by PratikBodawala** [comment]
[https://www.youtube.com/watch?v=8iMU9HbJ7Wo](url)

**Comment by DarthKeizer** [comment]
Here is why it doesnt work:
![50cb26bb-a679-4d2a-b913-833391fc343b](https://cloud.githubusercontent.com/assets/15630050/19211434/62af326e-8d3c-11e6-8170-f8f209ed8d46.jpg)

**Comment by ProZer0** [comment]
Now the bot is not working at all, nothing happens after the bot starts o_O

**Comment by DarthKeizer** [comment]
@ProZer0 read my previous comment why it does not work. Someone needs to crack the API
![62af326e-8d3c-11e6-8170-f8f209ed8d46](https://cloud.githubusercontent.com/assets/15630050/19212435/6063a44e-8d51-11e6-8daf-99a2f7d84de6.jpg)

**Comment by camnomis** [comment]
On the plus side, those only using the bot to sort and release are still able to lol

**Comment by kenkclam** [comment]
yea, that's right. It is funny that releasing pokemon still works, but nothing else does.

I read your warning too late, I ran the bot, got flagged. And now I am constantly getting this stupid warning (when I start the game on ipohone) that they caught me and advise me not to use third party app anymore, otherwise I will be banned.

**Comment by ProZer0** [comment]
Only 5% of the 0.39 api was cracked, to follow up on the progress join https://discord.pogodev.org

**Comment by jacy** [comment]
Captcha is required when the first time login to pokemon server, it might be difficult to break it, but it would be still easy if pokemonGoF just simply forward the Captcha images to users and let them choose the answer.

**Comment by MerlionRock** [comment]
@jacy good idea. Forward to telegram! 

But let's get a working 0.39 API first

**Comment by bsjpark** [comment]
Wow. All activities seems to have screeching halt. No Commit. No Conversation. No Update.
I guess the API update really killed us off so far. Fingers crossed for API update.

**Comment by db-coder** [comment]
@WayneUong where did you get this info from?

**Comment by camnomis** [comment]
https://m.reddit.com/r/pokemongodev/comments/58onby/re_has_cracked_the_api_fpm_to_go_live_around/

**Comment by WayneUong** [comment]
https://twitter.com/FastPokeMapCom
We still need to wait for them to release it to the public. Then we gotta update the api python library. Then I guess everything will be back to normal.

**Comment by PokemonGoZ** [comment]
Bot should be fixed.
