### ISSUE TITLE
Can't find pokestops but does not seem baned 

### ISSUE THREAD

**Issue by Flikzy** [PokemonGoF/PokemonGo-Bot#5782]

**Comment by Flikzy** [comment]
Hi everyone,

I searched everywhere but I haven't seen any solution. The bot keeps telling me it can't find pokestops in a range of ..., but I can log in without problems. I can still catch pokemons and pokestops on my iPhone when I turn on the app, however the bot still doesn't work. I used to have CAPTCHA (asking if I'm a robot) and a warning message, but I don't see that anymore for a few weeks. So I do not understand what's happening.
I tried proxies, vpm, change IP, nothing worked for me.
May be someone has a solution. It would be great.
Thanks by advance !

**Comment by mmixx** [comment]
@Flikzy the bot is still not working as of now... The pogodevs are currently working on getting the pgoapi done... Please refer to #5781, #5773 and #5768 for further information about this matter... Thanks...

**Comment by Flikzy** [comment]
Alright thank you very much for answering !

**Comment by Flikzy** [comment]
Alright thank you very much for answering !
