### ISSUE TITLE
Wrong ELF class

### ISSUE THREAD

**Issue by azraelppuk** [PokemonGoF/PokemonGo-Bot#5786]
got error:
[2016-11-07 21:14:37] [ERROR] [u'OSError: /home/pi/PokemonGo-Bot-Dev-29/PokemonGo-Bot//src/pgoapi/pgoapi/lib/libencrypt-linux-x86-64.so: wrong ELF class: ELFCLASS64'

investigated and local/pokemongo_bot/__init__.py contained 

if _platform.lower() == "linux" or _platform.lower() == "linux2":
            file_name = 'src/pgoapi/pgoapi/lib/libencrypt-linux-x86-64.so'

changed to

if _platform.lower() == "linux" or _platform.lower() == "linux2":
            file_name = 'src/pgoapi/pgoapi/lib/libencrypt-linux-arm-32.so'

then then proceeded for _me_. This isn't the fix, needs to properly check platform.

**Comment by solderzzc** [comment]
So you are running on RespBerry PI ?

**Comment by azraelppuk** [comment]
yes

**Comment by breakawayt** [comment]
@azraelppuk Got the same error as yours (i'm running this on Pi too), would you be kind enough to point me to download the file "libencrypt-linux-arm-32.so" and "libniantichash-linux-arm-32.so"?

Also, to get pi working, is there a better way to "pip install -r requirements.txt" (or something like that)?

Thanks.

**Comment by azraelppuk** [comment]
https://github.com/pogodevorg/pgoapi/pull/148

**Comment by beltoft** [comment]
Had the same problem on a minix neo 7 running ubuntu 14.04 ARM

This solved it

**Comment by azraelppuk** [comment]
yeah also need to change 

if _platform.lower() == "linux" or _platform.lower() == "linux2":
            file_name = 'src/pgoapi/pgoapi/lib/libniantichash-linux-x86-64.so'

to 

if _platform.lower() == "linux" or _platform.lower() == "linux2":
            file_name = 'src/pgoapi/pgoapi/lib/libniantichash-linux-arm-32.so'

**Comment by breakawayt** [comment]
Thanks a lot @azraelppuk , it's working now. All up and running in Rasbian.

**Comment by solderzzc** [comment]
let me close this issue
