### ISSUE TITLE
[ERROR] Could not find darwin hashing library libniantichash-osx-64.so on MacOS

### ISSUE THREAD

**Issue by bobbyc** [PokemonGoF/PokemonGo-Bot#5807]
The run.sh could not find libniantichash-osx-64.so. But when I rename libniantichash-macosx-64.dylib as libniantichash-osx-64.so. Everything works fine.

### Expected Behavior
libniantichash-osx-64.so should be exist in src/pgoapi/pgoapi/lib folder

### Actual Behavior
libniantichash-osx-64.so doesn't exist in src/pgoapi/pgoapi/lib folder. But libniantichash-macosx-64.dylib does exist.

### Output when issue occurred
2016-11-12 00:18:27,500 [pgoapi.utilities] [ERROR] Could not find darwin hashing library ...../PokemonGo-Bot/src/pgoapi/pgoapi/lib/libniantichash-osx-64.so
_inventory was not initialized
_inventory was not initialized

### Steps to Reproduce
Everytime execute ./run.sh

### Other Information
OS: 
MacOS
Branch: 
master

**Comment by ashdude1120** [comment]
I second this. Bot is currently unusable.

**Comment by claudioferrari** [comment]
cd /src/pgoapi/pgoapi/lib/
ln -s libniantichash-macos-64.dylib libniantichash-osx-64.so

**Comment by moquette** [comment]
@claudioferrari Than you so much!!!!! You have no idea how long I've searched for an answer!  I can confirm it works!!!!

MacOS 10.12.2

**Comment by MerlionRock** [comment]
Moving forward, extension for mac should be .dylib instead of .so

Should make the changes in init.py, get_hash_lib function

**Comment by AWSadmin** [comment]
Having similar issue with docker version of the bot:
Error relocating /usr/src/app/src/pgoapi/pgoapi/lib/libniahash-linux-x86-64.so: __memcpy_chk: symbol not found.

**Comment by bobbyc** [comment]
Fixed
