### ISSUE TITLE
libencrypt and libniantichash missing for raspberry pi and linux-32

### ISSUE THREAD

**Issue by pepeverde9** [PokemonGoF/PokemonGo-Bot#5808]
### Expected Behavior

to be able to run the bot

### Actual Behavior

After getting the bot with git clone and running setup.sh -i, it complains about missing libencrypt.
In fact, this lib exist, but in the install directory instead of being in src/pgoapi/pgoapi/lib, and the name is also different.
After copying this lib, the bot can still not being run, complaining about missing libniantichash.
There are several libniantichash files in src/pgoapi/pgoapi/lib, but none for linux-32 or arm-32.

### Other Information
OS:
ubuntu 14.4 32 bit on intel CPU
raspbian jessie on raspberry pi 3 
 
Branch: 
 
both of them
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by azraelppuk** [comment]
See https://github.com/PokemonGoF/PokemonGo-Bot/issues/5786

**Comment by pepeverde9** [comment]
after the last update, the missing libraries are present on both linux-x86-32 and linux-arm-32.
