### ISSUE TITLE
0.45 API Update - Fix

### ISSUE THREAD

**Issue by ElliotRobot1** [PokemonGoF/PokemonGo-Bot#5809]
Can someone update the project with the latest API posted?

**Comment by ElliotRobot1** [comment]
https://github.com/pogodevorg/pgoapi/pull/155

**Comment by MerlionRock** [comment]
They haven't merge yet. Just wait ba.

I got it working but I only change for my Mac os only....

Who ever updating the project for Mac under get_hash_lib(self) use .dylib extension instead of .so

Also note no changes for encrypt

**Comment by ElliotRobot1** [comment]
which file did you update the extensions in? going to manually modify to get working on Win

**Comment by MerlionRock** [comment]
The extension changes is only for Mac.

My guess is overwrite your existing DLL with the updated 0.45 should get you working on the new API.

**Comment by ElliotRobot1** [comment]
get errors when starting bot after updating files and changes from 0.45. 
I assume you updated your src/pogoapi folder with the new changes (commit by Noctem) and it worked?

**Comment by MerlionRock** [comment]
@ElliotRobot1  I make changes to rpc_api.py & utilities.py too

https://github.com/pogodevorg/pgoapi/pull/155/commits/ceb8dd58039cb406a013c4d572df12c782df261b

**Comment by ElliotRobot1** [comment]
I did as well.

**Comment by ElliotRobot1** [comment]
Got it working with new 0.45 API! 
PM me for the details.

**Comment by Dr8g0n** [comment]
@ElliotRobot1 Got error pulling new changes from pogodevorg/pgoapi@ceb8dd5

Can't contact you on github. Could you give some details here?

Thanks!

**Comment by claudioferrari** [comment]
same here, did you solved it?

**Comment by db-coder** [comment]
Can someone post some detailed steps please?

**Comment by ElliotRobot1** [comment]
Actually not working. Getting the same error, didn't realize running pip install was overriding my changes. need to wait for commit.

**Comment by ElliotRobot1** [comment]
Instructions Below:

https://github.com/Noctem/pokecrypt-pgoapi/tree/a9a36903277fc0f0fa31827eff8f166b127417ff
grab libniantichash-windows-x86-64.dll rename to niantichash64.dll replace file in \src\pgoapi\pgoapi\lib
grab libpcrypt-windows-x86-64.dll rename to encrypt64.dll replace file in \src\pgoapi\pgoapi\lib
Also update all other encrypt.dll locations (windows_bat).
update rpc_api.py by
(Change value may be different) sig.field25 = 10038237239822475814  
(To) sig.field25 = 16892874496697272497  
update utilities.py by
(Change)HASH_SEED = 0x61247FBF  # static hash seed from app  
(To)HASH_SEED = 0x46E945F8  # static hash seed from app  

Should work at this point. Cant confirm if it actually using the new API 0.45

**Comment by Dr8g0n** [comment]
@ElliotRobot1 changes in rpc_api.py and utilities.py are already there if you pull down from https://github.com/Noctem/pgoapi.git@ceb8dd58039cb406a013c4d572df12c782df261b

I downloaded new files from https://github.com/Noctem/pokecrypt-pgoapi/tree/a9a36903277fc0f0fa31827eff8f166b127417ff
But same error :-(

**Comment by ElliotRobot1** [comment]
you cant pull down the rpc_api and utilities files because they do not include the encrypt path hashs, so you need to use the old 0.43.3 file and simply modify them manually as per above.

**Comment by ElliotRobot1** [comment]
[pgoapi.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/587284/pgoapi.zip)

**Comment by enginebai** [comment]
From 0.43 -> 0.45, the encryption does not changed, but only hash.

**Comment by ElliotRobot1** [comment]
on Discord, devs has to update some paths in the crypto files, code didn't change (from what I understand)

**Comment by MerlionRock** [comment]
@ElliotRobot1 Yes, when I say "make changes to rpc_api.py & utilities.py", I mean edit the old files and replace the hash in the files. Encrypt, from what I last heard, no change.

**Comment by tunayuyar** [comment]
So for linux what needs to be done?

**Comment by ElliotRobot1** [comment]
@tunayuyar 
update the utilities.py has and encrypt paths for the Linux section. Use Norcem's .so files.

**Comment by tunayuyar** [comment]
@ElliotRobot1 so i suppose when it offers to update it at first run I should say no right?

**Comment by MerlionRock** [comment]
@tunayuyar If you have updated, follow @ElliotRobot1 instructions. Make sure you have both the encrypt and the hash files in \src\pgoapi\pgoapi\lib

The hash files download from Noctem's repo https://github.com/Noctem/pokecrypt-pgoapi/tree/a9a36903277fc0f0fa31827eff8f166b127417ff

The files name might also have change, in that case, you'll need to search /pokemongo_bot/_init_.py and replace the old file names with new ones, or simply make sure you edit new files to old file names, which ever is easier for you.

**Comment by Dr8g0n** [comment]
@ElliotRobot1 , thx!

updating the OLD files and using the new dylib worked!
if it complains about missing file, just go to \src\pgoapi\pgoapi\lib and create the symlink for the file it asks or just rename the file

**Comment by ElliotRobot1** [comment]
You got it! Once they commit, someone can create a PR with the changes here to get the repo updated, in the interim happy boting!

**Comment by tunayuyar** [comment]
@MerlionRock @ElliotRobot1 thanks. It was working when I asked not to update(since it overrides the changes I did)

So far it is working.

**Comment by tunayuyar** [comment]
Also please note guys:

update rpc_api.py by
(Change value may be different) sig.field25 = 10038237239822475814
(To) sig.field25 = 16892874496697272497

I did have "-" infront of my sig.field25 value it needs to removed.

**Comment by houkop** [comment]
there are no libs for centos now, right?

**Comment by tunayuyar** [comment]
@houkop unless you have specific reason to use centos, you can use virtualbox > ubuntu, thats what im doing on windows.

**Comment by MerlionRock** [comment]
Guys! It should be working soon~

They have committed the files in https://github.com/pogodevorg/pgoapi/tree/master/pgoapi

**Comment by joltir** [comment]
update (setup -u) gave this:
Obtaining pgoapi from git+https://github.com/sebastienvercammen/pgoapi.git#egg=pgoapi (from -r requirements.txt (line 3))
  git clone in ./src/pgoapi exists with URL https://github.com/pogodevorg/pgoapi.git/
  The plan is to install the git repository https://github.com/sebastienvercammen/pgoapi.git
What to do?  (s)witch, (i)gnore, (w)ipe, (b)ackup s
  Switching clone ./src/pgoapi to https://github.com/sebastienvercammen/pgoapi.git


Is this ok? Do i have api 0.45 now? Or did i hace to select an other option as s?

**Comment by solderzzc** [comment]
Latest commit updated to the new API.
