### ISSUE TITLE
[FEATURE REQUEST] Telegram subscribe list save to config?

### ISSUE THREAD

**Issue by guoyida** [PokemonGoF/PokemonGo-Bot#5814]
I subscribe some events to my telegram. 

------
buddy_candy_earned ->  
{}level_up ->  
{}pokemon_caught -> operator:or cp:1800 iv:0.80
{}pokemon_caught -> pokemon:Lapras
{}pokemon_vip_caught ->  
-------------

Once I restart my script, this list is gone. I have to subscribe them one by one again. Is it possible to save the list to the config file so that I don't need to do it again.

**Comment by guoyida** [comment]
Tested again, this time the list was saved. Somebody else please test this? if this is already a feature, please close this issue.

**Comment by solderzzc** [comment]
It was saved to DB. let me close this issue.
