### ISSUE TITLE
How to run bot with mutliple users ?

### ISSUE THREAD

**Issue by jamiekuo** [PokemonGoF/PokemonGo-Bot#5816]
Hello,

I install "Bot" and "Web UI" both and then they work pretty good now. Because I saw the top right corner of the design of [my web page](http://imgur.com/UhKua95) showing "Bots", I wonder if we can run more bots and display on the same page?

**Comment by reigelgallarde** [comment]
if you're on linux, try [this](https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/configuration_files.md#usage)

**Comment by jamiekuo** [comment]
> if you're on linux, try this

I have done this before and my bot and web work very well. However, my problem is how to add more than one user into the same pokebot and then the web can display users more than one account. This seems no such feature now... Thank you.

**Comment by paganoll** [comment]
Edit web/config/userdata.js and add another users:
 	    enable: **true,**
 	    username: "**username2**",
 	    socketAddress: "127.0.0.1:5000",
 	    enableSocket: false

Run a task for each user as @reigelgallarde link:
'./run.sh ./configs/config.json ./configs/**authname**.json
