### ISSUE TITLE
[FEATURE REQUEST] Kill Switch - API Version Validation

### ISSUE THREAD

**Issue by eRobot1** [PokemonGoF/PokemonGo-Bot#5825]
### Short Description

Requesting a KillSwitch to validate API version.
### Possible solution

Check https://pgorelease.nianticlabs.com/plfe/version
If > bot version, force exit and prevents sign in.

**Comment by tiagoAnon** [comment]
+1

**Comment by houkop** [comment]
+1

**Comment by ElliotRobot1** [comment]
This should be an easy enhancement, anyone up for the challenge?

**Comment by ElliotRobot1** [comment]
@YvesHenri  @solderzzc  Can we make this an official Feature Request?

**Comment by Jcolomar** [comment]
Since last 0.43.x, seems a lot of devs are missed

**Comment by moquette** [comment]
+1

**Comment by ElliotRobot1** [comment]
I created a PR with the changes, so will see.

**Comment by tiagoAnon** [comment]
Niantic just changed the minimum API to 0.47.0. Not safe to bot again.

**Comment by joltir** [comment]
But we still need an update of the bot to use it? Right?

**Comment by ProZer0** [comment]
Yes! and there is no PR yet!

**Comment by MZorzy** [comment]
@ProZer0 #5826

**Comment by dogeatdog** [comment]
Would be awesome if the mainpage would be updated. Especially the part about the bot working (a warning not to use it would be cool as well :) )

**Comment by PokemonGoZ** [comment]
Sounds great! +1

**Comment by nachi9211** [comment]
Why is this implementation a compulsion? How can I turn this off, I was happily moderating on the previous version and runnin bot, now I update hoping for a patch, but instead can't run bot anymore. 
Please help me disable this check, thank you.

**Comment by nachi9211** [comment]
Roll back to get your double experience and candies.
Watch app on device closely to remove captcha magnemite.
