### ISSUE TITLE
Give IV to nickname

### ISSUE THREAD

**Issue by alawing** [PokemonGoF/PokemonGo-Bot#583]
Is that possible give IV to nicknames so after running we could manually by client to make decisions for the pokemons.

**Comment by alawing** [comment]
also could we have an option to close the evolve if we dont want any evolve?

**Comment by earthchie** [comment]
right now we can't. we aren't figure out how to make nickname api work yet. 

However we can favorite it.

**Comment by Esummoner** [comment]
Not very smart to add iv to nicknames, think that makes it a lot easier for them to catch botters.

**Comment by sakulstra** [comment]
Giving IV to nickname doesn't sound like a good idea, but one could have a command like `--list` to just list all the pokemons in the inventory with their cp and iv value.

**Comment by alawing** [comment]
yes I think we need a command just like --list

**Comment by GreWull** [comment]
See this open issue as well:

https://github.com/PokemonGoF/PokemonGo-Bot/issues/452
