### ISSUE TITLE
virtualenv not installed (Arch)

### ISSUE THREAD

**Issue by thisischrys** [PokemonGoF/PokemonGo-Bot#5838]
virtualenv is not installed as part of setup.sh

**Comment by thisischrys** [comment]
eh, guess it's dead again anyway :p

**Comment by Denis-Em** [comment]
Do you mean when launching run.sh it tell "virtualenv does not exist" ?

**Comment by thisischrys** [comment]
yes

**Comment by thisischrys** [comment]
setup.sh also has some errors like easy_install not being a valid command
also it should be virtualenv2 on arch anyway, it defaults to python3
