### ISSUE TITLE
ISSUE: ValueError: Attack 242 not found in FastAttacks (Ditto Related?!)

### ISSUE THREAD

**Issue by camnomis** [PokemonGoF/PokemonGo-Bot#5840]
Looks like this is related to the release of a Ditto, on an account with a Ditto I get the error message, on an account without a Ditto it runs fine.

(Sorry for not giving the full break down of error log/config.json but I am on my mobile at the moment RDP'ing back to my server, will post the full break down later if needs be, but hopefully this might be enough to kick of a bit of investigation)

**Comment by camnomis** [comment]
Edit just seen this is a duplicate of #5833

**Comment by ozi66** [comment]
bot nerde bot bot yokmu

**Comment by dcsim** [comment]
@ozi66 yeni API'den bot calismiyor. herkes artık bekliyor.
