### ISSUE TITLE
Current API version no longer supported

### ISSUE THREAD

**Issue by igoldny** [PokemonGoF/PokemonGo-Bot#5841]
Hey,

i get this message: 'We have detected a Pokemon API Change. The current API version 0.45.0 is no longer supported. Exiting...'

i did all the updates (./setup.sh -r)
and then ./run
but still the same, what am i missing?

**Comment by joltir** [comment]
It is the kill switch. see #5826

Pokemon go is on api 0.47.1 The bot still on 0.45. To avoid detection the bot will not run.

**Comment by igoldny** [comment]
@joltir thnx.
so bot currently not working for most of the ppl with the new version?

**Comment by joltir** [comment]
Yep, but you can overrule it by editting the config.sjon file and chage the check to false:
"check_niantic_api": false

But it is safer to wait till the new api is supported, the accounts which use the bot are detected easy.
