### ISSUE TITLE
We have detected a Pokemon API Change. The current API version 0.45.0 is no longer supported. Exiting...

### ISSUE THREAD

**Issue by lukasz138** [PokemonGoF/PokemonGo-Bot#5844]

**Comment by SGColdSun** [comment]
And? This isn't a bug or an issue.

The bot does not currently support the latest API.

**Comment by lukasz138** [comment]
So, when will be working ?

**Comment by SGColdSun** [comment]
When the new API has been reverse engineered and made available. There is no time frame.

**Comment by Jcolomar** [comment]
Come on guys.. READ what happend with bot BEFORE try start to use it.

**Comment by mcferson** [comment]
during monthes we waited for update and now it's released, it's already... out ?
the last time they spoke about a captcha protection system. I NEVER seen that with google account NOR Hunters Club.

**Comment by mcferson** [comment]
however, where is the last release ? i can't find it. i can't find the exe.

**Comment by SGColdSun** [comment]
Its a python script. Of course there isn't an exe in this repository.

**Comment by mcferson** [comment]
> Its a python script. Of course there isn't an exe in this repository.
It's not obvious. You can make an exe with python language and a python IDE like Boa Constrictor.

**Comment by VBQL** [comment]
First of all, these scripts are mostly running on Linux servers or the Raspberry pi. If you really want an exe just grab all the python packages and make it yourself. Also, learn to read the sentence "The current API version 0.45.0 is no longer supported". It is not supported so please don't mark this as an error. Take some time to learn how Python works I guess.

**Comment by reigelgallarde** [comment]
haha!

**Comment by yuvarajpuru** [comment]
Is there a python script update that is needed to get around this error? Or are we waiting on a code fix?

**Comment by dcsim** [comment]
> Is there a python script update that is needed to get around this error? Or are we waiting on a code fix?

@yuvarajpuru It isn't an error, it is expected behavior. The available API isn't the minimum supported API and so login is prevented. If you want to, you could cut this safety check out of the code, but there are good reasons to not use an unsupported API version, which is why the check was added...

**Comment by acurioustale** [comment]
See #5826.

If you want to use the old API, adjust your config.json: `"check_niantic_api": false,`

**Comment by MerlionRock** [comment]
You can allow it to run by adjusting your config file to "check_niantic_api": false

There's a good reason why this is there. Do it at your own risk.

Just in case if anyone wonder what's the risk: BAN

**Comment by pogarek** [comment]
I don't think that this issue not longer valid. Closing.
