### ISSUE TITLE
incompatible version of websocket websocket-client from fresh install

### ISSUE THREAD

**Issue by johnscancella** [PokemonGoF/PokemonGo-Bot#5845]
### Expected Behavior
After a fresh install it starts when running `./run.sh`

### Actual Behavior
I get the following output
```
An incompatible websocket library is conflicting with the one we need.
You can remove the incompatible library and install the correct one
by running the following commands:

yes | pip uninstall websocket websocket-client
pip install -U websocket-client
Fri Dec 2 19:49:39 EST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
```

### config.json 
```
{
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": false,
    "check_niantic_api": true,
    "live_config_update": {
      "enabled": false,
      "tasks_only": false
    },
    "tasks": [
      {
        "type": "TelegramTask",
        "config": {
          "enabled": false,
          "master": null,
          "password": null,
          "// old syntax, still supported: alert_catch": ["all"],
          "// new syntax:": {},
          "alert_catch": {
            "all": {"operator": "and", "cp": 1300, "iv": 0.95},
            "Snorlax": {"operator": "or", "cp": 900, "iv": 0.9}
          }
        }
      },
      {
        "type": "DiscordTask",
        "config": {
          "enabled": false,
          "master": null,
          "// old syntax, still supported: alert_catch": ["all"],
          "// new syntax:": {},
          "alert_catch": {
            "all": {"operator": "and", "cp": 1300, "iv": 0.95},
            "Snorlax": {"operator": "or", "cp": 900, "iv": 0.9}
          }
        }
      },
      {
        "//NOTE: This task MUST be placed on the top of task list": {},
        "type": "RandomAlivePause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:05:00",
          "max_interval": "01:30:00"
        }
      },
      {
        "type": "HandleSoftBan"
      },
      {
        "type": "RandomPause",
        "config": {
          "enabled": false,
          "min_duration": "00:00:10",
          "max_duration": "00:10:00",
          "min_interval": "00:10:00",
          "max_interval": "02:00:00"
        }
      },
      {
        "type": "CompleteTutorial",
        "config": {
          "enabled": false,
          "// set a name": "",
          "nickname": "",
          "// 0 = No Team, 1 = Blue, 2 = Red, 3 = Yellow": "",
          "team": 0
        }
      },
      {
        "type": "CollectLevelUpReward",
        "config": {
          "collect_reward": true,
          "level_limit": -1
        }
      },
      {
        "type": "BuddyPokemon",
        "config": {
          "enabled": true,
          "buddy_list": "dratini, magikarp",
          "best_in_family": true,
          "// candy_limit = 0 means no limit, so it will never change current buddy": {},
          "candy_limit": 0,
          "candy_limit_absolute":0,
          "// force_first_change = true will always change buddy at start removing current one": {},
          "force_first_change": false,
          "buddy_change_wait_min": 3,
          "buddy_change_wait_max": 5,
          "min_interval": 120
        }
      },
      {
        "type": "IncubateEggs",
        "config": {
          "enabled": true,
          "infinite_longer_eggs_first": false,
          "breakable_longer_eggs_first": true,
          "min_interval": 120,
         "infinite": [2,5,10],
         "breakable": [2,5,10]
        }
      },
      {
        "type": "UpdateLiveStats",
        "config": {
          "enabled": false,
          "min_interval": 10,
          "stats": ["username", "uptime", "stardust_earned", "xp_earned", "xp_per_hour", "stops_visited"],
          "terminal_log": true,
          "terminal_title": true
        }
      },
      {
        "type": "UpdateLiveInventory",
        "config": {
          "enabled": false,
          "min_interval": 120,
          "show_all_multiple_lines": false,
          "items": ["pokemon_bag", "space_info", "pokeballs", "greatballs", "ultraballs", "razzberries", "luckyegg"]
        }
      },
      {
        "type": "ShowBestPokemon",
        "config": {
          "enabled": true,
          "min_interval": 60,
          "amount": 5,
          "order_by": "cp",
          "info_to_show": ["cp", "ivcp", "dps", "hp"]
        }
      },
      {
        "type": "TransferPokemon",
        "config": {
          "enabled": true,
          "min_free_slot": 5,
          "transfer_wait_min": 3,
          "transfer_wait_max": 5
        }
      },
      {
        "type": "NicknamePokemon",
        "config": {
          "enabled": false,
          "nickname_above_iv": 0.9,
          "nickname_template": "{iv_pct}-{iv_ads}",
          "nickname_wait_min": 3,
          "nickname_wait_max": 5
        }
      },
      {
        "type": "EvolvePokemon",
        "config": {
          "enabled": false,
          "log_interval": 120,

            "// evolve only pidgey and drowzee": "",
            "// evolve_list": "pidgey, drowzee",
            "// donot_evolve_list": "none",

            "// evolve all but pidgey and drowzee": "",
            "// evolve_list": "all",
            "// donot_evolve_list": "pidgey, drowzee",

            "evolve_list": "all",
            "donot_evolve_list": "none",

          "first_evolve_by": "cp",
          "evolve_above_cp": 500,
          "evolve_above_iv": 0.8,
          "logic": "or",
          "min_evolve_speed": 25,
          "max_evolve_speed": 30,
          "min_pokemon_to_be_evolved": 1,
          "use_lucky_egg": false
        }
      },
      {
        "type": "UseIncense",
        "config": {
          "use_incense": false,
          "use_order": [
            "ordinary",
            "spicy",
            "cool",
            "floral"
          ]
        }
      },
      {
        "type": "RecycleItems",
        "config": {
          "enabled": true,
          "min_empty_space": 15,
          "max_balls_keep": 150,
          "max_potions_keep": 50,
          "max_berries_keep": 70,
          "max_revives_keep": 70,
          "item_filter": {
            "Pokeball":       { "keep" : 100 },
            "Potion":         { "keep" : 10 },
            "Super Potion":   { "keep" : 20 },
            "Hyper Potion":   { "keep" : 30 },
            "Revive":         { "keep" : 30 },
            "Razz Berry":     { "keep" : 100 }
          },
          "recycle_wait_min": 3,
          "recycle_wait_max": 5,
          "recycle_force": true,
          "recycle_force_min": "00:01:00",
          "recycle_force_max": "00:05:00"
        }
      },
      {
        "type": "CatchLimiter",
        "config": {
          "enabled": false,
          "min_balls": 20,
          "duration": 15
        }
      },
      {
		"type": "Sniper",
		"config": {
			"enabled": false,
			"mode": "social",
			"bullets": 1,
			"homing_shots": true,
			"special_iv": 100,
			"order": ["missing", "vip", "priority"],
			"sources": [
				{
				    "enabled": false,
					"url": "http://localhost:5000/raw_data",
					"timeout": 3,
					"key": "pokemons",
					"mappings": {
						"id": { "param": "pokemon_id" },
						"name": { "param": "pokemon_name" },
						"latitude": { "param": "latitude" },
						"longitude": { "param": "longitude" },
						"expiration": { "param": "disappear_time", "format": "milliseconds" }
					}
				},
				{
				    "enabled": false,
					"url": "https://pokewatchers.com/grab/",
					"timeout": 10,
					"mappings": {
						"iv": { "param": "iv" },
						"id": { "param": "pid" },
						"name": { "param": "pokemon" },
						"latitude": { "param": "cords" },
						"longitude": { "param": "cords" },
						"expiration": { "param": "timeend", "format": "seconds" }
					}
				},
				{
				    "enabled": false,
					"url": "http://pokesnipers.com/api/v1/pokemon.json",
					"timeout": 10,
					"key": "results",
					"mappings": {
						"iv": { "param": "iv" },
						"name": { "param": "name" },
						"latitude": { "param": "coords" },
						"longitude": { "param": "coords" },
						"expiration": { "param": "until", "format": "utc" }
					}
				}
			],
			"catch": {
				"Snorlax": 1000,
				"Dragonite": 1000,
				"Growlithe": 600,
				"Clefairy": 500,
				"Kabuto": 500,
				"Dratini": 500,
				"Dragonair": 500,
				"Mr. Mime": 500,
				"Magmar": 500,
				"Electabuzz": 500,
				"Tangela": 500,
				"Tauros": 500,
				"Primeape": 500,
				"Chansey": 500,
				"Pidgey": 100,
				"Caterpie": 100,
				"Weedle": 100
			}
		}
      },
      {
        "type": "CatchPokemon",
        "config": {
          "enabled": true,
          "catch_visible_pokemon": true,
          "catch_lured_pokemon": true,
          "catch_incensed_pokemon": true,
          "min_ultraball_to_keep": 5,
          "berry_threshold": 0.35,
          "vip_berry_threshold": 0.9,
          "treat_unseen_as_vip": true,
          "daily_catch_limit": 800,
          "vanish_settings": {
            "consecutive_vanish_limit": 10,
            "rest_duration_min": "02:00:00",
            "rest_duration_max": "04:00:00"
          },
          "catch_throw_parameters": {
            "excellent_rate": 0.1,
            "great_rate": 0.5,
            "nice_rate": 0.3,
            "normal_rate": 0.1,
            "spin_success_rate" : 0.6,
            "hit_rate": 0.75
          },
          "catch_simulation": {
            "flee_count": 3,
            "flee_duration": 2,
            "catch_wait_min": 3,
            "catch_wait_max": 6,
            "berry_wait_min": 3,
            "berry_wait_max": 5,
            "changeball_wait_min": 3,
            "changeball_wait_max": 5,
            "newtodex_wait_min": 20,
            "newtodex_wait_max": 30
          }
        }
      },
      {
        "type": "SpinFort",
        "config": {
          "enabled": true,
          "spin_wait_min": 3,
          "spin_wait_max": 5,
          "daily_spin_limit": 1900
        }
      },
      { "type": "UpdateWebInventory",
        "config": {
          "enabled": true
        }
      },
      {
        "type": "MoveToFort",
        "config": {
          "enabled": true,
          "lure_attraction": true,
          "lure_max_distance": 2000,
          "walker": "StepWalker",
          "log_interval": 5
        }
      },
      {
        "type": "FollowSpiral",
        "config": {
          "enabled": true,
          "diameter": 4,
          "step_size": 70
        }
      }
    ],
    "map_object_cache_time": 5,
    "forts": {
      "avoid_circles": true,
      "max_circle_size": 50,
      "cache_recent_forts": true
    },
    "pokemon_bag": {
      "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
      "show_at_start": true,
      "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
      "show_count": false,
      "// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
      "show_candies": false,
      "// 'pokemon_info' parameter define which info to show for each pokemon": {},
      "// the available options are": {},
      "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
      "pokemon_info": ["cp", "iv_pct"]
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "alt_min": 500,
    "alt_max": 1000,

    "sleep_schedule": {
      "enabled": true,
      "enable_reminder": false,
      "reminder_interval": 600,
      "entries": [
        {
          "enabled": true,
          "time": "12:00",
          "duration": "5:30",
          "time_random_offset": "00:30",
          "duration_random_offset": "00:30",
          "wake_up_at_location": ""
        },
        {
          "enabled": true,
          "time": "17:45",
          "duration": "3:00",
          "time_random_offset": "01:00",
          "duration_random_offset": "00:30",
          "wake_up_at_location": ""
        }
      ]
    },

    "gps_default_altitude": 8.0,
    "replicate_gps_xy_noise": false,
    "replicate_gps_z_noise": false,
    "gps_xy_noise_range": 0.000125,
    "gps_z_noise_range": 12.5,
    "debug": false,
    "test": false,
    "walker_limit_output": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging": {
      "color": true,
      "show_datetime": true,
      "show_process_name": true,
      "show_log_level": true,
      "show_thread_name": false
    },
    "catch": {
      "any": {"candy_threshold" : 400 ,"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "// Example of always catching Rattata:": {},
      "// Rattata": { "always_catch" : true },
      "// Example of catching only Diglett and Horsea needed for Bubblestrat; you might want to also configure sniping (MoveToMap - helps you get hold of neede pokemons faster) and disable SpinFort (or you will advance past level 2 which will make it impossible to catch level-1 pokemons)": {},
      "Diglett": { "candy_threshold": 1, "catch_below_cp": 11, "catch_above_iv": 0, "logic": "and", "fast_attack": ["Scratch", "Mud Slap"] },
      "Horsea": { "candy_threshold": 1, "catch_below_cp": 11, "catch_above_iv": 0, "logic": "and", "fast_attack": ["Bubble"] },
      "// Example of catching Vaporeon only with Water Gun and Hydro Pump": {},
      "Vaporeon": { "catch_above_iv": 0.99, "charged_attack": ["Hydro Pump"], "fast_attack": ["Water Gun"]}
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "release_below_ivcp": 0, "logic": "or"},
      "// Example of always releasing Rattata:": {},
      "// Rattata": {"always_release": true},
      "// Example of keeping 3 stronger (based on CP) Pidgey:": {},
      "// Pidgey": {"keep_best_cp": 3},
      "// Example of keeping 2 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_iv": 2},
      "// Keep no more than 3 best IV pokemon for every pokemon type": {},
      "// any": {"keep_best_iv": 3},
      "// Keep no more than 3 best IVCP pokemon for every pokemon type": {},
      "// any": {"keep_best_ivcp": 3},
      "// Discard all pokemon in bag except 100 pokemon with best CP": {},
      "// all": {"keep_best_cp": 100},
      "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
      "// Zubat": {"keep_best_cp": 2, "keep_best_iv": 3},
      "// Example of custom order of static criterion": {},
      "// Zubat": {"keep_best_custom": "iv, cp, hp_max", "amount":2}
    },
    "vips" : {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": {},
        "any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},

        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    },
	"websocket": {
		"start_embedded_server": true,
		"server_url": "127.0.0.1:4000"
	}
}
```

### Output when issue occurred
```
[jscancella@johns-air python-bot (master)]$ ./run.sh
An incompatible websocket library is conflicting with the one we need.
You can remove the incompatible library and install the correct one
by running the following commands:

yes | pip uninstall websocket websocket-client
pip install -U websocket-client
Fri Dec 2 19:49:39 EST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
```

### Steps to Reproduce

run the `./setup.sh` script then run `./run.sh`

### Other Information
OS: Mac
Branch: master
Git Commit: 6416d10b3c38122f4d00aed2958efcdf9f6c340f
Python Version: python2.7

**Comment by SGColdSun** [comment]
Did you follow the directions in the provided output?

**Comment by johnscancella** [comment]
yes, but it doesn't fix the problem

**Comment by xiatianyu** [comment]
Same here

**Comment by crvfts** [comment]
remove

`"websocket": {
		"start_embedded_server": true,
		"server_url": "127.0.0.1:4000"
	}`

you won't be able to view toasts as a result but this should allow the bot to run OK.

**Comment by xiatianyu** [comment]
> remove
> 
> "websocket": { "start_embedded_server": true, "server_url": "127.0.0.1:4000" }
> 
> you won't be able to view toasts as a result but this should allow the bot to run OK.

The problem persists despite the removal of the `"websocket"` property.

**Comment by yuvarajpuru** [comment]
Problem still persists after removal of the property... confirmed

**Comment by b4rtt** [comment]
Same problem here. On mac and linux too

**Comment by yuvarajpuru** [comment]
Now i am getting this error...

We have detected a Pokemon API Change. The current API version 0.45.0 is no longer supported. Exiting...

**Comment by SGColdSun** [comment]
THat isn't an error. The current API isn't supported by the bot and therefore closes. Wait until the pogodevs release support for the new API and then try again.

**Comment by camnomis** [comment]
@yuvarajpuru is you change the line

`    "check_niantic_api": true,`

to 

  `  "check_niantic_api": false,`

The app will run without checking the API version, you will need to be very careful to keep logged into a device to do the capture but the bot will work, for how long I don't know but I do an hour a day max and I haven't been banned.

As for the original issue, I have tried with websocket-client==0.37.0 and websocket-client==0.39.0 neither work, any suggestions?

**Comment by b4rtt** [comment]
After this all solutions I see this problem. `2016-12-06 08:57:27,044 [       cli] [INFO] PokemonGO Bot v1.0
2016-12-06 08:57:27,065 [       cli] [INFO] commit: 2f8ae4b9
2016-12-06 08:57:27,071 [       cli] [INFO] Configuration initialized
2016-12-06 08:57:27,071 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:
2016-12-06 08:57:27,071 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics
2016-12-06 08:57:27,091 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com
(62845) wsgi starting up on http://127.0.0.1:4000
[2016-12-06 08:57:27] [SleepSchedule] [INFO] Next sleep at 12:26:14, for a duration of 05:52:16
[2016-12-06 08:57:27] [PokemonGoBot] [INFO] Setting start location.
[2016-12-06 08:57:27] [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.
[2016-12-06 08:57:27] [PokemonGoBot] [INFO] Location found: 40.741895,-73.989308 (40.741895, -73.989308, 8.0)
[2016-12-06 08:57:27] [PokemonGoBot] [INFO] Now at (40.741895, -73.989308, 8.0)
[2016-12-06 08:57:27] [PokemonGoBot] [INFO] Login procedure started.
[2016-12-06 08:57:28] [PokemonGoBot] [INFO] Login successful.
[2016-12-06 08:57:28] [PokemonGoBot] [INFO] 
[2016-12-06 08:57:29] [PokemonGoBot] [INFO] [x] Error while opening cached forts: [Errno 2] No such file or directory: u'/Users/Roman/Desktop/PokemonGo-Bot/pokemongo_bot/../data/recent-forts-hxmeo11.json'
_inventory was not initialized
_inventory was not initialized
[2016-12-06 08:57:30] [       cli] [INFO] 
[2016-12-06 08:57:30] [       cli] [INFO] Ran for 0:00:04
[2016-12-06 08:57:30] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h
[2016-12-06 08:57:30] [       cli] [INFO] Travelled 0.00km
[2016-12-06 08:57:30] [       cli] [INFO] Visited 0 stops
[2016-12-06 08:57:30] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()
[2016-12-06 08:57:30] [       cli] [INFO] Threw 0 pokeballs
[2016-12-06 08:57:30] [       cli] [INFO] Earned 0 Stardust
[2016-12-06 08:57:30] [       cli] [INFO] Hatched eggs 0
[2016-12-06 08:57:30] [       cli] [INFO] 
[2016-12-06 08:57:30] [       cli] [INFO] Highest CP Pokemon: 
[2016-12-06 08:57:30] [       cli] [INFO] Most Perfect Pokemon: 
Traceback (most recent call last):
  File "pokecli.py", line 856, in <module>
    main()
  File "pokecli.py", line 195, in main
    bot = start_bot(bot, config)
  File "pokecli.py", line 147, in start_bot
    bot.start()
  File "/Users/Roman/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 149, in start
    init_inventory(self)
  File "/Users/Roman/Desktop/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1416, in init_inventory
    _inventory = Inventory(bot)
  File "/Users/Roman/Desktop/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1260, in __init__
    self.refresh()
  File "/Users/Roman/Desktop/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1270, in refresh
    i.refresh(inventory)
  File "/Users/Roman/Desktop/PokemonGo-Bot/pokemongo_bot/inventory.py", line 75, in refresh
    self._data = self.retrieve_data(inventory)
  File "/Users/Roman/Desktop/PokemonGo-Bot/pokemongo_bot/inventory.py", line 71, in retrieve_data
    ret[key] = self.parse(item)
  File "/Users/Roman/Desktop/PokemonGo-Bot/pokemongo_bot/inventory.py", line 490, in parse
    return Pokemon(item)
  File "/Users/Roman/Desktop/PokemonGo-Bot/pokemongo_bot/inventory.py", line 991, in __init__
    assert max(int(self.cp_exact), 10) == self.cp
AssertionError
[2016-12-06 08:57:30] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128) (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "/Users/Roman/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/Users/Roman/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/Users/Roman/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/Roman/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/Users/Roman/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/Users/Roman/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/Users/Roman/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/Users/Roman/Desktop/PokemonGo-Bot/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 895, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2016-12-06 08:57:30] [sentry.errors.uncaught] [ERROR] [u'AssertionError', u'  File "pokecli.py", line 856, in <module>', u'  File "pokecli.py", line 195, in main', u'  File "pokecli.py", line 147, in start_bot', u'  File "pokemongo_bot/__init__.py", line 149, in start', u'  File "pokemongo_bot/inventory.py", line 1416, in init_inventory', u'  File "pokemongo_bot/inventory.py", line 1260, in __init__', u'  File "pokemongo_bot/inventory.py", line 1270, in refresh', u'  File "pokemongo_bot/inventory.py", line 75, in refresh', u'  File "pokemongo_bot/inventory.py", line 71, in retrieve_data', u'  File "pokemongo_bot/inventory.py", line 490, in parse', u'  File "pokemongo_bot/inventory.py", line 991, in __init__']
út 6. prosince 2016 08:57:30 CET Pokebot  Stopped.
Press any button or wait 20 seconds to continue.`

**Comment by b4rtt** [comment]
![snimek obrazovky 2016-12-06 v 9 01 06](https://cloud.githubusercontent.com/assets/4247839/20917592/aebef994-bb92-11e6-9dbc-536c89d367bb.png)
![snimek obrazovky 2016-12-06 v 9 01 21](https://cloud.githubusercontent.com/assets/4247839/20917594/b0ac64a8-bb92-11e6-8ff6-3bb6a268d26f.png)
![snimek obrazovky 2016-12-06 v 9 01 42](https://cloud.githubusercontent.com/assets/4247839/20917598/b337930a-bb92-11e6-8576-250596fc9182.png)

**Comment by camnomis** [comment]
Is there a solution to this? I have tried various different websocket-client versions but none work

**Comment by Killerrat93** [comment]
Hi,Any updates on this issue? i keep getting the same output despite all your solutions.:


An incompatible websocket library is conflicting with the one we need.
You can remove the incompatible library and install the correct one
by running the following commands:

yes | pip uninstall websocket websocket-client
pip install -U websocket-client
Wed Dec 7 10:13:35 PST 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.


i tried "yes | pip uninstall websocket websocket-client",but came out this output:

Cannot uninstall requirement websocket, not installed 

pip install -U websocket-client

replaces websocket-client==0.37.0 with websocket-client==0.39.0.

still doesn't works

same output as before.

**Comment by camnomis** [comment]
Doesn't work with latest version (0.40.0) I have tried uninstalling websocket-client completely (pip freeze confirms its not there) and we are still getting the error message.

I am struggling with my level of ability to debug this, I know most of the dev's will be waiting for the API to be updated before continuing, but hopefully someone is still looking

**Comment by bebek-air** [comment]
@knightcraw: confirm, i do as description, and the bot running again.  ubuntu 14.04

**Comment by camnomis** [comment]
@bebek-air Still not working on OSX

**Comment by camnomis** [comment]
@bebek-air is that a question or a statement.

Are you asking if you do that will it run again, or are you confirming you have done that and it is working again?

**Comment by bebek-air** [comment]
ups sorry (english not my native lang) :), I'm confirmed it's work for me. As added information, my bot run using virtualenv.

**Comment by camnomis** [comment]
Spun up a VM with fresh install of Ubuntu on and again still not working, tried with 16.04 and 14.04.

Guess with the Gen2 releases that are slowly coming out there is going to be more and more issue similar to after Ditto was released so will have to hope an update sorts it out.

**Comment by knightcraw** [comment]
@camnomis:  add `websocket-client==0.37.0` into your requirements.txt file above python-socketio and the setup script will handle it.
[requirements.txt](https://github.com/PokemonGoF/PokemonGo-Bot/files/650883/requirements.txt)

**Comment by OscarCid** [comment]
@knightcraw work! but now appears this

We have detected a Pokemon API Change. The current API version 0.45.0 is no longer supported. Exiting...

**Comment by bebek-air** [comment]
@OscarCid see @camnomis above, disable API Check **do at your own risk!**

**Comment by camnomis** [comment]
@knightcraw cheers mate!

**Comment by ChaosMarc** [comment]
@knightcraw (or someone else) could you please create a pull request with the additional requirement?
