### ISSUE TITLE
Error when run pokecli.py

### ISSUE THREAD

**Issue by xDyN** [PokemonGoF/PokemonGo-Bot#5847]
$ python pokecli.py
  File "pokecli.py", line 70
    print "Run following command to get latest update: `pip install -r requirements.txt --upgrade`"
                                                                                                  ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by brunifrancesco** [comment]
Seem you're using Python 3 executable while code you posted has a Python 2 syntax.

**Comment by BreezeRo** [comment]
closing
