### ISSUE TITLE
An incompatible websocket library is conflicting with the one we need

### ISSUE THREAD

**Issue by perpysling2** [PokemonGoF/PokemonGo-Bot#5852]
root@pokemongobot:/pokemon/PokemonGo-Bot# ./run.sh
An incompatible websocket library is conflicting with the one we need.
You can remove the incompatible library and install the correct one
by running the following commands:

yes | pip uninstall websocket websocket-client
pip install -U websocket-client
on. 28. des. 16:11:46 +0100 2016 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by perpysling2** [comment]
what can i do here?

**Comment by camnomis** [comment]
You can learn to search for a start!

#5845

**Comment by perpysling2** [comment]
After reading this post i still have same problem.

**Comment by pogarek** [comment]
copy your configs (of bot and web ui), delete the folder with bot, clone master or dev branch again and check if you , still, have the error.
