### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by pogarek** [PokemonGoF/PokemonGo-Bot#5855]
Hi
0.51 is enforced. PR with fixes for it awaits merge.. 
I also think that Sniper task on URL doesn't work any longer....

**Comment by pogarek** [comment]
adding @YvesHenri .
I've spend a few hours today on investigation and it seems that api response to after teleporting back and starting encounter is not what script expect.
Unfortunatelly my python and pokeapi knowledge are too low to fix it.. 
Might be pgoapi issue - no idea.

**Comment by vilalupus** [comment]
I am using your fork. Its great! Tks.

**Comment by MerlionRock** [comment]
@pogarek Just wondering, if original developers for this project are not supporting anymore, can others continue the project with your fork?

**Comment by pogarek** [comment]
Sure
