### ISSUE TITLE
Automatic Installation

### ISSUE THREAD

**Issue by mcferson** [PokemonGoF/PokemonGo-Bot#5859]
I don't understand why this is called "automatic" installation while we need to search and find and download ourselves some UNFOUNDABLE DLLs (encrypt.so and encrypt.dll or encrypt_64.dll) for whom you cannot give us links.

**Comment by breakawayt** [comment]
> I don't understand why this is called "automatic" installation while we need to search and find and download ourselves some UNFOUNDABLE DLLs (encrypt.so and encrypt.dll or encrypt_64.dll) for whom you cannot give us links.

@mcferson Oh sorry, what's your contribution towards this project again? Tsk tsk tsk.. zero contribution, plenty of complaint.

**Comment by mcferson** [comment]
oh yeah well, so continue to give incomplete information. good idea.
bye bye.

**Comment by breakawayt** [comment]
Dear admins, feel free to close this irrelevant "issue". 

And most importantly, this doesn't reflect the general opinion of what you guys have achieved so far. Keep up the good work.

**Comment by MerlionRock** [comment]
@mcferson All 3 files are included with pogo api.

Please do a clean installation using pogarek's fork with this command: 
git clone -b dev https://github.com/pogarek/PokemonGo-Bot

**Comment by mcferson** [comment]
however, efforts are wasted by the newly monthly paying API key. for that, thanks to pogodev...

**Comment by MerlionRock** [comment]
@mcferson

Check this https://www.atlassian.com/git/tutorials/install-git/mac-os-x under the window install instructions
