### ISSUE TITLE
Sniper.py is not able to verify the pokemon

### ISSUE THREAD

**Issue by pogarek** [PokemonGoF/PokemonGo-Bot#5863]
If json data is missing EcounterID and SpawnpointID, then sniper.py do a verification of pokemon. 
However it always fails for me - from my investigation it seems, like results are empty ( get_meta_cell => find_close_cells => get_map_objects  : catchable pokemons)... 

It seems like get_map_object returns forts only. 

Unfortunatelly I have no idea how to fix it.

**Comment by MerlionRock** [comment]
It's me. Replied you in Discord :) Documenting it for future developers to take note.

After version 0.45, Niantic implemented a delay for Pokemon spawns after a teleport (both to and back) Once Niantic's server detected a jump in position all Pokemons will not be shown on map for a few mins (up to even 5mins). But once in a while, if you're lucky, it's just a few secs (which explain why sometimes you can snipe without Encounter ID & Spawn Point ID).

You can try this with Pokemon Go and a spoofing app to verify the above information.

For my new features, I've increased the MIN_SECONDS_ALLOWED_FOR_CELL_CHECK to 180 secs. 

If i'm not wrong, Sniper.py will bypass the check if there's  EncounterID and SpawnpointID. So this increase in timing is only for my Telegram Snipe and Url that doesn't provide EncounterID and SpawnpointID.

**Comment by MerlionRock** [comment]
Ok...

Update: Just today, it doesn't work anymore even after 300 secs of delay.

**Comment by MerlionRock** [comment]
Found out what happened with sniper.py
Fixed. Will be doing a PR.

**Comment by pogarek** [comment]
fixed by #5877
