### ISSUE TITLE
pgoapi  code change is in conflict with bot and virtuaenv

### ISSUE THREAD

**Issue by pogarek** [PokemonGoF/PokemonGo-Bot#5868]
This issue affects the combination of bot+virtualenv+latets pogoapi from dev. 
I've have checked PokemonGo-Map with latest pogoapi (I've changed their requirementst.txt) and with virtualenv and map works.

In this commit https://github.com/pogodevorg/pgoapi/commit/d5f846aaee84b10dd43c184fd191c3fc02244bed, they changed support for protobuf3-to-dict:
*  They require version higher or equal to >=0.1.4  and they did some code change, 
*  They have removed protobuf_to_dict.py file and switched to the one from requirements
*  They have changed rpc_api.py from: 
```
[auth_ticket['expire_timestamp_ms'], base64.standard_b64decode(auth_ticket['start']), base64.standard_b64decode(auth_ticket['end'])])  
```
to:
```
[auth_ticket['expire_timestamp_ms'], auth_ticket['start'], auth_ticket['end']]) 
```
This breaks the bot ability to login while running under virtualenv. 

However I don't know how to fix it.

**Comment by pogarek** [comment]
Waiting for someone from @PokemonGoF/pokemongo-bot-team to check this.

**Comment by Jcolomar** [comment]
New update in develop branch [https://github.com/pogodevorg/pgoapi/pull/178](url)

**Comment by pogarek** [comment]
Ok, so basing on PokemonGo-Map I tested the approach and it worked (for me, in virtualenv). However it requires some **manual actions** before upgrade and I'm not sure how to do the commit/PR, to make users aware /implement the changes for them.

Steps to be done : (first make sure that you have updated your repo by using 'git pull' . At the moment of writing this comment, master branch is the most updated)
```
pip uninstall pgoapi
pip uninstall protobuf_to_dict
pip uninstall protobuf3-to-dict
```

then edit requirements.txt (in root of the bot) and:
1. remove the line with: protobuf==3.0.0b4
2. remove the line with: protobuf-to-dict==0.1.0
3. change line with pogoapi to: 
>git+https://github.com/pogodevorg/pgoapi.git@develop#egg=pgoapi
4. run:
>pip2 install --upgrade -r requirements.txt

then start the bot., So far, so good. And bots uses the latest pogoapi now.
