### ISSUE TITLE
Out of pokeball

### ISSUE THREAD

**Issue by hklcf** [PokemonGoF/PokemonGo-Bot#587]
### Expected Behavior
farm pokeshop

### Actual Behavior
[#] Walking from (40.773632899999996, -73.97418739999999) to (40.77404382503233, -73.97322318103993) for approx. 38.0 seconds
[#] Finished walking to (40.77404382503233, -73.97322318103993)
[x] Walked to Pokemon
[#] A Wild Pidgey appeared! [CP75]
[x] Out of pokeballs...
[x] Farming pokeballs...
[x] Found pokemon at distance 362.660273526m
[#] Walking from (40.77404382503233, -73.97322318103993) to (40.774392713676995, -73.97404965831205) for approx. 32.0 seconds
[#] Finished walking to (40.774392713676995, -73.97404965831205)
[x] Walked to Pokemon
[x] Found pokemon at distance 333.708773072m
[#] Walking from (40.774392713676995, -73.97404965831205) to (40.77404382503233, -73.97322318103993) for approx. 32.0 seconds
[#] Finished walking to (40.77404382503233, -73.97322318103993)
[x] Walked to Pokemon
[#] A Wild Pidgey appeared! [CP75]
[x] Out of pokeballs...
[x] Farming pokeballs...
certain [x] Found pokemon at distance 362.660273526m
[#] Walking from (40.77404382503233, -73.97322318103993) to (40.774392713676995, -73.97404965831205) for approx. 32.0 seconds

### Other Information
OS: Debian 8
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by surfaace** [comment]
please provide the git commit format

**Comment by petercunha** [comment]
Run `git pull` so you have the latest version. Then in _config.json_ edit line 8 to say `"mod":
"farm",`.

**Comment by hklcf** [comment]
Git Commit: ab604452c2a0a72e13fa6d940fa55902d3b01466

Im using the latest version :(

**Comment by surfaace** [comment]
@hklcf this was committed 8 hours ago

**Comment by hklcf** [comment]
@petercunha where can i find the config.json?
I just see config.json.example in the folder.

**Comment by surfaace** [comment]
rename .example to config.json

**Comment by hklcf** [comment]
@surfaace ah...
when i run `git pull` it return up-to-date

**Comment by surfaace** [comment]
what branch? git branch

**Comment by hklcf** [comment]
oh sorry!
im using master branch :-1:
