### ISSUE TITLE
"Mode" not working

### ISSUE THREAD

**Issue by hklcf** [PokemonGoF/PokemonGo-Bot#588]
pokecli.py [-h] -a AUTH_SERVICE -u USERNAME -p PASSWORD -l LOCATION [-m] [-w] [--distance_unit] [--initial-transfer] [--maxsteps] [-iv] [-d] [-t]

optional arguments:
  -m MODE, --mode MODE                          Set farming Mode for the bot ('all', 'poke', 'farm')

**Comment by petercunha** [comment]
Open up `config.json` and on line 8 change it to `"mode": "<WHATEVER YOU WANT>",`

**Comment by petercunha** [comment]
Oh, and I forgot to mention. Make sure to run `git pull` first to make sure you have the latest version.
