### ISSUE TITLE
Error with the config file

### ISSUE THREAD

**Issue by Ubed** [PokemonGoF/PokemonGo-Bot#5885]
I bought the HASHKEY but when i try to run the bot said me that the config file is not ok, WHY?

2017-01-23 10:12:54,222 [       cli] [INFO] PokemonGO Bot v1.0
2017-01-23 10:12:54,230 [       cli] [INFO] commit: ce549716
./configs/auth.json: ok
2017-01-23 10:12:54,240 [       cli] [CRITICAL] Error with configuration file
lun ene 23 10:12:54 CET 2017 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

**Comment by dogeatdog** [comment]
Probably a typo ? Kinda hard to tell for us without looking at the auth.json

**Comment by Ubed** [comment]
Auth.json? the auth.json said me that is ok, the trouble are un config.auth bu im generating with the setup.sh -c

**Comment by MerlionRock** [comment]
It might be typo in config.

Show us your config file

**Comment by davidakachaos** [comment]
@Ubed do you still have this problem? If so, please show us your config file, or use a site like jsonlint.com to validate the JSON file.

**Comment by pogarek** [comment]
Closing because there is no answer
