### ISSUE TITLE
how to get encrypt.so and encrypt.dll or encrypt_64.dll ?

### ISSUE THREAD

**Issue by mike1223** [PokemonGoF/PokemonGo-Bot#5894]
pretty new at this and trying to set it up i instaled the desktop version and its giveing a python error? can anyone help

**Comment by pogarek** [comment]
read the docs. post more details and troubleshooting steps done

**Comment by MerlionRock** [comment]
If you are referring to the desktop version, please ask your question there: https://github.com/PokemonGoF/PokemonGo-Bot-Desktop/issues

However, judging from the PRs there, most likely that project has been halted.

**Comment by pogarek** [comment]
PokemonGo-Bot handles these DLLs for you. For PokemonGo-Desktop you would need to ask their authors.

Please check our setup script and docs and comeback with more details in a new issue.
