### ISSUE TITLE
Can't run without embedded server

### ISSUE THREAD

**Issue by jagauthier** [PokemonGoF/PokemonGo-Bot#5898]
When changing config.json, and setting "start_embedded_server" to false, the application doesn't seem to do anything.

This is the last line logged:
2017-01-31 20:12:35,453 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com

When it is enabled, it sails right through.

[edit]
Removing the section entirely seems to work!

**Comment by pogarek** [comment]
So I assume that I can close it :) Comment here If I'm wrong . :-)
