### ISSUE TITLE
API v0.55.0 - API check fail

### ISSUE THREAD

**Issue by camnomis** [PokemonGoF/PokemonGo-Bot#5900]
Ran a fresh install of the bot (master branch, commit 7c2722d7) on a brand new VM (ubuntu 16.4.0 LTS) after trying Pogarek's for a while, bought a brand new hash key (and according to buddyauth it's gone from "UNUSED / INACTIVE" to "ACTIVE" so that bit is OK), tried to follow @pogarek's adivce in #5882 and ran 

`pip2 install --upgrade -r requirements.txt`

But am still getting the API check fail, is this expected behaviour, is there something in the bot that will need to be updated to work with 0.55.0?

**Comment by MerlionRock** [comment]
in Config, set "check_niantic_api": false

Don't worry, if you have done the upgrade, it should be on API 0.55

Also, you can do a ./setup.sh -u to do the upgrade.

I do have a updated version for checking niantic api, however, whenever there's a version change, changes have to be done on github, which is not dynamic.

**Comment by camnomis** [comment]
Will spin up a dummy account and see if it comes up with the captcha warnings

**Comment by pogarek** [comment]
My repo should be quite close to master repo. Make sure to run 'git pull' from time to time.
Or  backup config files , delete data and take te main repo/

**Comment by MerlionRock** [comment]
Do a ./setup.sh -u

API check updated

**Comment by pogarek** [comment]
closing because pgoapi is on 0.57 now. Reopen if this still happens
