### ISSUE TITLE
[SUGGESTION] Update method for releasing pokemons based on config

### ISSUE THREAD

**Issue by surfaace** [PokemonGoF/PokemonGo-Bot#591]
### Expected Behavior
Currently when you catch a pokemon and any of the two conditions fails with 'or' statement you transfer the pokemon, suggestion is to have two value if statement. Then if either cp or iv is above configured limit it will keep the pokemon

if condition is 'or':
if cp > min_cp and iv < iv_min: keep
if cp < min_cp and iv > iv_min: keep
else: transfer
else if condition is 'and':
if cp > min_cp and iv > iv_min: keep
else: transfer

### Actual Behavior
What it does now is that if either CP or IV is below the configured threashold it will transfer the pokemon away. Therefore i suggest to have two value if statement to correct this

### Other Information
OS: 
Git Commit: 154971c2a5a87738825381e74281ea89943bfd75

**Comment by petercunha** [comment]
You can change `or` to `and` in the config file. If you want really advanced logic you're going to have to code it yourself.

**Comment by surfaace** [comment]
if you use 'AND' both conditions needs to be true. with this suggestion it will keep the pokemon if CP 'or' IV is matched

**Comment by surfaace** [comment]
explained in issue #534 , its releaselogic, not keep logic.

Code is ok
