### ISSUE TITLE
ImportError: No module named packaging.version

### ISSUE THREAD

**Issue by azraelppuk** [PokemonGoF/PokemonGo-Bot#5912]
Just did a fresh install and now getting following error when running:

Traceback (most recent call last):
  File "pokecli.py", line 48, in <module>
    from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetException
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/pgoapi/__init__.py", line 30, in <module>
    import pkg_resources
  File "/home/pi/PokemonGo-Bot/PokemonGo-Bot/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 70, in <module>
    import packaging.version
ImportError: No module named packaging.version
Wed 15 Feb 23:27:45 GMT 2017 Pokebot  Stopped.
Press any button or wait 20 seconds to continue.

Any ideas?

**Comment by pogarek** [comment]
Reinstall the bot, clean directory. Looks like issue with python libraries.

**Comment by DeepJeep** [comment]
Look for errors during install caused by missing permissions, I had the same problems couple of days ago. Did a fresh install running 'sudo setup.sh' afterwards, followed by recursively 'chown'ing everything in the bot directory to the user who is supposed to run the bot.

**Comment by pogarek** [comment]
or this might about virtualenv and missing packages. Reopen if this still affects you
