### ISSUE TITLE
Bot stopped working

### ISSUE THREAD

**Issue by roxane11** [PokemonGoF/PokemonGo-Bot#5916]
Even after Gen 2 Pokemon, though i was getting error "Unexpected moveset [Rock Throw, Rock Slide]" , Bot was still working. But now bot stopped working ( a couple of hours back i would say ) and now getting this error. Any idea what would have caused this ?

> pi@raspberrypi:~/PokemonGo-Bot $ ./run.sh                                                                                                       
> 2017-02-17 21:50:31,608 [       cli] [INFO] PokemonGO Bot v1.0                                                                                  
> 2017-02-17 21:50:31,629 [       cli] [INFO] commit: 26117e6e                                                                                    
> 2017-02-17 21:50:31,648 [       cli] [INFO] Configuration initialized                                                                           
> 2017-02-17 21:50:31,649 [pokemongo_bot.health_record.bot_event] [INFO] Health check is enabled. For more information:                           
> 2017-02-17 21:50:31,650 [pokemongo_bot.health_record.bot_event] [INFO] https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev#analytics           
> 2017-02-17 21:50:31,671 [requests.packages.urllib3.connectionpool] [INFO] Starting new HTTP connection (1): www.google-analytics.com            
> (4594) wsgi starting up on http://127.0.0.1:4000                                                                                                
> [2017-02-17 21:50:31] [SleepSchedule] [INFO] Next sleep at 12:01:35, for a duration of 05:03:53                                                 
> [2017-02-17 21:50:31] [PokemonGoBot] [INFO] Setting start location.                                                                             
> [2017-02-17 21:50:31] [PokemonGoBot] [INFO] [x] Coordinates found in passed in location, not geocoding.                                         
> [2017-02-17 21:50:31] [PokemonGoBot] [INFO] Location found: 40.765727, -73.976226 (40.765727, -73.976226, 8)                                    
> [2017-02-17 21:50:31] [PokemonGoBot] [INFO] Now at (40.765727, -73.976226, 8)                                                                   
> [2017-02-17 21:50:31] [PokemonGoBot] [INFO] Login procedure started.                                                                            
> [2017-02-17 21:50:38] [PokemonGoBot] [INFO] Login successful.                                                                                   
> [2017-02-17 21:50:38] [PokemonGoBot] [INFO] Captcha Check Passed                                                                                
> [2017-02-17 21:50:38] [PokemonGoBot] [INFO]                                                                                                     
> [2017-02-17 21:50:40] [PokemonGoBot] [INFO] [x] Error while opening cached forts: [Errno 2] No such file or directory: u'/home/pi/PokemonGo-Bot/
> pokemongo_bot/../data/recent-forts-roxane_13.json'                                                                                              
> [2017-02-17 21:50:41] [   Pokemon] [ERROR] Unexpected moveset [Rock Throw, Rock Slide] for #218 Slugma, please update info in pokemon.json and c
> reate issue/PR                                                                                                                                  
> [2017-02-17 21:50:41] [   Pokemon] [ERROR] Unexpected moveset [Cut, Seed Bomb] for #191 Sunkern, please update info in pokemon.json and create i
> ssue/PR                                                                                                                                         
> [2017-02-17 21:50:41] [   Pokemon] [ERROR] Unexpected moveset [Rock Smash, Brick Break] for #66 Machop, please update info in pokemon.json and c
> reate issue/PR                                                                                                                                  
> [2017-02-17 21:50:41] [   Pokemon] [ERROR] Unexpected moveset [Scratch, Aerial Ace] for #190 Aipom, please update info in pokemon.json and creat
> e issue/PR                                                                                                                                      
> [2017-02-17 21:50:41] [   Pokemon] [ERROR] Unexpected moveset [Tackle, Aerial Ace] for #165 Ledyba, please update info in pokemon.json and creat
> e issue/PR                                                                                                                                      
> [2017-02-17 21:50:41] [   Pokemon] [ERROR] Unexpected moveset [Bite, Dazzling Gleam] for #209 Snubbull, please update info in pokemon.json and c
> reate issue/PR                                                                                                                                  
> _inventory was not initialized                                                                                                                  
> _inventory was not initialized                                                                                                                  
> [2017-02-17 21:50:41] [       cli] [INFO]                                                                                                       
> [2017-02-17 21:50:41] [       cli] [INFO] Ran for 0:00:09                                                                                       
> [2017-02-17 21:50:41] [       cli] [INFO] Total XP Earned: 0  Average: 0.00/h                                                                   
> [2017-02-17 21:50:41] [       cli] [INFO] Travelled 0.00km                                                                                      
> [2017-02-17 21:50:41] [       cli] [INFO] Visited 0 stops                                                                                       
> [2017-02-17 21:50:41] [       cli] [INFO] Encountered 0 pokemon, 0 caught, 0 released, 0 evolved, 0 never seen before ()                        
> [2017-02-17 21:50:41] [       cli] [INFO] Threw 0 pokeballs                                                                                     
> [2017-02-17 21:50:41] [       cli] [INFO] Earned 0 Stardust                                                                                     
> [2017-02-17 21:50:41] [       cli] [INFO] Hatched eggs 0                                                                                        
> [2017-02-17 21:50:41] [       cli] [INFO]                                                                                                       
> [2017-02-17 21:50:41] [       cli] [INFO] Highest CP Pokemon:                                                                                   
> [2017-02-17 21:50:41] [       cli] [INFO] Most Perfect Pokemon:                                                                                 
> Traceback (most recent call last):                                                                                                              
>   File "pokecli.py", line 865, in <module>                                                                                                      
>     main()                                                                                                                                      
>   File "pokecli.py", line 195, in main                                                                                                          
>     bot = start_bot(bot, config)                                                                                                                
>   File "pokecli.py", line 147, in start_bot                                                                                                     
>     bot.start()                                                                                                                                 
>   File "/home/pi/PokemonGo-Bot/pokemongo_bot/__init__.py", line 155, in start                                                                   
>     init_inventory(self)                                                                                                                        
>   File "/home/pi/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1422, in init_inventory                                                        
>     _inventory = Inventory(bot)                                                                                                                 
>   File "/home/pi/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1266, in __init__                                                              
>     self.refresh()                                                                                                                              
>   File "/home/pi/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1276, in refresh                                                               
>     i.refresh(inventory)                                                                                                                        
>   File "/home/pi/PokemonGo-Bot/pokemongo_bot/inventory.py", line 75, in refresh                                                                 
>     self._data = self.retrieve_data(inventory)                                                                                                  
>   File "/home/pi/PokemonGo-Bot/pokemongo_bot/inventory.py", line 71, in retrieve_data                                                           
>     ret[key] = self.parse(item)                                                                                                                 
>   File "/home/pi/PokemonGo-Bot/pokemongo_bot/inventory.py", line 493, in parse                                                                  
>     return Pokemon(item)                                                                                                                        
>   File "/home/pi/PokemonGo-Bot/pokemongo_bot/inventory.py", line 982, in __init__                                                               
>     self.charged_attack = ChargedAttacks.data_for(data['move_2'])  # type: ChargedAttack                                                        
>   File "/home/pi/PokemonGo-Bot/pokemongo_bot/inventory.py", line 652, in data_for                                                               
>     attack_id, cls.__name__))                                                                                                                   
> ValueError: Attack 251 not found in ChargedAttacks                                                                                              
> [2017-02-17 21:50:41] [sentry.errors] [ERROR] Sentry responded with an error: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in
>  range(128) (url: https://app.getsentry.com/api/90254/store/)                                                                                   
> Traceback (most recent call last):                                                                                                              
>   File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync                           
>     super(ThreadedHTTPTransport, self).send(data, headers)                                                                                      
>   File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send                                     
>     ca_certs=self.ca_certs,                                                                                                                     
>   File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen                                      
>     return opener.open(url, data, timeout)                                                                                                      
>   File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open                         
>     response = self._open(req, data)                                                                                                            
>   File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open                        
>     '_open', req)                                                                                                                               
>   File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain                  
>     result = func(*args)                                                                                                                        
>   File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open                                   
>     return self.do_open(ValidHTTPSConnection, req)                                                                                              
>   File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open                     
>     h.request(req.get_method(), req.selector, req.data, headers)                                                                                
>   File "/usr/lib/python2.7/httplib.py", line 1039, in request                                                                                   
>     self._send_request(method, url, body, headers)                                                                                              
>   File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request                                                                             
>     self.endheaders(body)                                                                                                                       
>   File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders                                                                                
>     self._send_output(message_body)                                                                                                             
>   File "/usr/lib/python2.7/httplib.py", line 877, in _send_output                                                                               
>     msg += message_body                                                                                                                         
> UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)                                               
> [2017-02-17 21:50:41] [sentry.errors.uncaught] [ERROR] [u'ValueError: Attack 251 not found in ChargedAttacks', u'  File "pokecli.py", line 865, 
> in <module>', u'  File "pokecli.py", line 195, in main', u'  File "pokecli.py", line 147, in start_bot', u'  File "pokemongo_bot/__init__.py", l
> ine 155, in start', u'  File "pokemongo_bot/inventory.py", line 1422, in init_inventory', u'  File "pokemongo_bot/inventory.py", line 1266, in _
> _init__', u'  File "pokemongo_bot/inventory.py", line 1276, in refresh', u'  File "pokemongo_bot/inventory.py", line 75, in refresh', u'  File "
> pokemongo_bot/inventory.py", line 71, in retrieve_data', u'  File "pokemongo_bot/inventory.py", line 493, in parse', u'  File "pokemongo_bot/inv
> entory.py", line 982, in __init__', u'  File "pokemongo_bot/inventory.py", line 652, in data_for']                                              
> Fri 17 Feb 21:50:41 UTC 2017 Pokebot  Stopped.                                                                                                  
> Press any button or wait 20 seconds to continue.                                                                                                
>   ^CTraceback (most recent call last):
>   File "pokecli.py", line 48, in <module>                                                                                                       
>     from pgoapi.exceptions import NotLoggedInException, ServerSideRequestThrottlingException, ServerBusyOrOfflineException, NoPlayerPositionSetE
> xception                                                                                                                                        
>   File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/pgoapi/__init__.py", line 50, in <module>                                      
>     from pgoapi.pgoapi import PGoApi                                                                                                            
>   File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/pgoapi/pgoapi.py", line 35, in <module>                                        
>     from pgoapi.rpc_api import RpcApi                                                                                                           
>   File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/pgoapi/rpc_api.py", line 45, in <module>                                       
>     from pgoapi.utilities import to_camel_case, get_time, get_format_time_diff, Rand48, long_to_bytes, f2i                                      
>   File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/pgoapi/utilities.py", line 34, in <module>                                     
>     from geopy.geocoders import GoogleV3                                                                                                        
>   File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/geopy/__init__.py", line 13, in <module>                                       
>     from geopy.geocoders import * # pylint: disable=W0401                                                                                       
>   File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/geopy/geocoders/__init__.py", line 113, in <module>                            
>     from geopy.geocoders.ignfrance import IGNFrance                                                                                             
>   File "/home/pi/PokemonGo-Bot/local/lib/python2.7/site-packages/geopy/geocoders/ignfrance.py", line 5, in <module>                             
>     import xml.etree.ElementTree as ET                                                                                                          
>   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 127, in <module>                                                                     
>     from . import ElementPath                                                                                                                   
>   File "/usr/lib/python2.7/xml/etree/ElementPath.py", line 62, in <module>                                                                      
>     "("                                                                                                                                         
>   File "/home/pi/PokemonGo-Bot/lib/python2.7/re.py", line 194, in compile                                                                       
>     return _compile(pattern, flags)                                                                                                             
>   File "/home/pi/PokemonGo-Bot/lib/python2.7/re.py", line 249, in _compile                                                                      
>     p = sre_compile.compile(pattern, flags)                                                                                                     
>   File "/home/pi/PokemonGo-Bot/lib/python2.7/sre_compile.py", line 572, in compile                                                              
>     p = sre_parse.parse(p, flags)                                                                                                               
>   File "/home/pi/PokemonGo-Bot/lib/python2.7/sre_parse.py", line 696, in parse                                                                  
>     p = _parse_sub(source, pattern, 0)                                                                                                          
>   File "/home/pi/PokemonGo-Bot/lib/python2.7/sre_parse.py", line 317, in _parse_sub                                                             
>     itemsappend(_parse(source, state))                                                                                                          
>   File "/home/pi/PokemonGo-Bot/lib/python2.7/sre_parse.py", line 656, in _parse                                                                 
>     p = _parse_sub(source, state)                                                                                                               
>   File "/home/pi/PokemonGo-Bot/lib/python2.7/sre_parse.py", line 317, in _parse_sub                                                             
>     itemsappend(_parse(source, state))                                                                                                          
>   File "/home/pi/PokemonGo-Bot/lib/python2.7/sre_parse.py", line 522, in _parse                                                                 
>     item = subpattern[-1:]                                                                                                                      
>   File "/home/pi/PokemonGo-Bot/lib/python2.7/sre_parse.py", line 141, in __getitem__                                                            
>     return SubPattern(self.pattern, self.data[index])                                                                                           
>   File "/home/pi/PokemonGo-Bot/lib/python2.7/sre_parse.py", line 90, in __init__                                                                
>     def __init__(self, pattern, data=None):                                                                                                     
> KeyboardInterrupt                                                                                                                               
> Fri 17 Feb 21:51:03 UTC 2017 Pokebot  Stopped.                                                                                                  
> Press any button or wait 20 seconds to continue.

**Comment by rubyShell** [comment]
I've seen this too. Are you getting picture captcha? I usually connect from my phone on the same lat lon as the bot and at times, the phone pops up the captcha. I've seen this exact error when that happens. You can usually control-c out of it and start it up again. Just make sure you clear the captcha if that is occurring. Bot is still running for me with the same move errors but still hunting :)

**Comment by MerlionRock** [comment]
Attack 251, wild charge. New moves.

Download my fast moves and charge moves json files and replace yours in data folder.

I have the files, look for the link in the gen 2 issue thread.

**Comment by roxane11** [comment]
Worked. However still getting "Unexpected moveset" error but bot works

**Comment by MerlionRock** [comment]
Unexpected moveset is due to information not updated in pokemon.json

If you have the time, you can try to help us. Refer to #5917
