### ISSUE TITLE
Help Needed with pokemon.json

### ISSUE THREAD

**Issue by MerlionRock** [PokemonGoF/PokemonGo-Bot#5917]
#Other than asking if there's a updated pokemon.json, if anyone is reading this, if you have the time, please help us. I have check and done up to pokemon: 018, download the file below and load it into http://www.jsoneditoronline.org/ use the arrow key to load the file to editor and edit from there. 

**_Link Removed_**

Compare data with https://thesilphroad.com/catalog and make the changes. Take note especially to fast moves and special attacks, the base attack, defense and stamina, the candies need for evolution for new pokemons. If stones are needed for upgrade, don't add in first, bot cant handle yet.

Any changes to moves, please do an INSERT instead of changing the values.

Thank you. If you can't finish it, save it to your own dropbox/iCloud/or any sharing services and leave  the link here and ask next person to continue. Or you can leave a comment here telling people you will be doing from which pokemon to which. Someone else can do a different set so that there will be no overlapping of work.

Once we are sure the file is good to go and all agreed it's good, I'll do a PR for it.

Thank you so much for helping. Any errors, we can amend it later. 

If you need the updated moves and item list, download below:
**_Link Removed_**

**Update:** with the help of @rubyShell and @zyrix the Pokemon.json is ready.i will do a PR with some changes to some function of the bot together with these new files later. For now, you can download it here:

**Update 2:** Realised Gen 1 old moves are removed. Download link has been removed until I fix it again.

**Update 3:** Finally, here's the updated pokemon.json Will need to have some more changes. But for now, it should solve most of the error message about missing moves. Use together with 3 other files posted above.

**_Link Removed_**

**Update 4: ** PR Merged. All links will be removed to prevent people from downloading old files.

**Comment by rubyShell** [comment]
I can try to help. Going to jump on #19 but I see it's fairly updated already. I'll put a note on how far I get by comparing the catalog

**Comment by MerlionRock** [comment]
@rubyShell Thank you. The changes will start mostly from gen 2. But gen 1 will also have some slight changes. Just make sure you add in new moves and not edit the old ones.

**Comment by rubyShell** [comment]
@MerlionRock You got it. Going to go as far as I can confirming the Gen1 pokemon and then trying to start with Gen2.

**Comment by rubyShell** [comment]
Up to #026. Sorry for the lag. Kids driving me crazy at home lol

**Comment by rubyShell** [comment]
https://www.dropbox.com/s/ovalxjqrf9govzu/pokemon.json.updated_026?dl=0

**Comment by Zyrix** [comment]
I can help you by adding the new moves from Gen2.

**Comment by rubyShell** [comment]
@Zyrix Thanks! I'm on #64 for Gen1

**Comment by rubyShell** [comment]
#92 for now. Going to charge my laptop and finish up in about an hour. I should have Gen1 done soon enough. @Zyrix is working on Gen2. Thanks

**Comment by pogarek** [comment]
If we consider https://thesilphroad.com/catalog as trustworthy, later today (my day just started) I will write a tool which will update the Pokémon.json and create a new one (it will have two modes). 

Also it will be nice to have a web source for just moves and items, as it has been described here : 
https://github.com/PokemonGoF/PokemonGo-Bot/issues/5914#issuecomment-280611681

**Comment by rubyShell** [comment]
@pogarek excellent. I'm almost done with Gen1 and I think @Zyrix is handling Gen2. Definitely will be good to look for mistakes we made manually (if any).

**Comment by pogarek** [comment]
Damn . https://thesilphroad.com/catalog Is missing evolution data.. So I will need to fetch this from another website.. Anyway - we will see what we will have in a few hours .

**Comment by MerlionRock** [comment]
@rubyshell @zyrix @pogarek thank-you guys. Understand there might be some overlapping of work especially when scripting can do this quite efficiently. 

I went ahead with manual as I can't find one trustworthy source with all information in. Once again thaNk you guys.

**Comment by rubyShell** [comment]
Welcome! 
Gen1 pokemon.json is completed. 
Here is the link 
https://www.dropbox.com/s/tzaizjw29xk5mpj/pokemon.json.gen1?dl=0
I'm going to bed. I'm in California so it's getting late for me. :)

**Comment by rubyShell** [comment]
Ok. Gen1 done. Here's the link. I ran it and caught a few typos but cleaned them up. 
https://www.dropbox.com/s/byi11vipcz00kda/pokemon.json.gen1?dl=0

Hope this helps!

**Comment by MerlionRock** [comment]
@rubyshell, thank-you so much.

@pogark the evolution should be there? Or not available for Gen 2? 

Possible to use two sources? 

@zyrix let us know your progress so we'll know how to progress from here. Script should be able to fill in existing missing info.

**Comment by pogarek** [comment]
Yeah, I will need to combine at least two sources.

**Comment by Zyrix** [comment]
I'm finished with Gen2

**Comment by MerlionRock** [comment]
@zyrix thank you so much. Did you run the bot with it? Any errors?

Post the link. I'm currently running a live production, can't do any thing. @pogarek you want to combine them?

**Comment by Zyrix** [comment]
I ran a semi automatic script and checked manually for errors.

https://www.dropbox.com/s/4hdvyu9iywq1o6o/pokemon.json?dl=0

**Comment by pogarek** [comment]
My script will take any pokemon.json (in structure for bot), then it will create a new one an updated one , based on sliproad and another website (for data missing on sliphroad). Then you can compare new files with these one , than you done manually , so we will know how to proceed from there 

Get Outlook for iOS




On Sat, Feb 18, 2017 at 10:24 AM +0100, "Philipp Brandl" <notifications@github.com> wrote:












I ran a semi automatic script and checked manually for errors.


https://www.dropbox.com/s/4hdvyu9iywq1o6o/pokemon.json?dl=0

**Comment by MerlionRock** [comment]
Okay. Wait for you.

**Comment by pogarek** [comment]
Starting to code now. I'll be back when I'll done / have something to share.

**Comment by pogarek** [comment]
ok, so it seems that https://thesilphroad.com/catalog has a lot of data already in the code : it has pokemondata variable , in json, as script value. 

Attaching a file with these json data. I'll use it for further parsing, but this is a good start.

**Comment by camnomis** [comment]
This is the pokemon.json I am using at the moment

https://dl.dropboxusercontent.com/u/9125175/pokemon.json

No errors so far!

**Comment by MerlionRock** [comment]
@camnomis I just did the PR with the changes we did :)

**Comment by camnomis** [comment]
@MerlionRock No worries, I run my bot on a VM so can roll back any changes when a new build is out :)

**Comment by pogarek** [comment]
Golbat is missing next evolution data: https://fevgames.net/pokedex/042-golbat/ 
Requirements are not added there, I'll assume 100.

**Comment by andrenagusch** [comment]
Is there anything else to do than to replace the pokemon.json?  Bot isn't working.

With the default pokemon.json, the bot is working. Only some errors while bot is running:
`[ERROR] Unexpected moveset`

Example:
`KeyError: 'Unknown fast attack: "Hex"'`

**Comment by pogarek** [comment]
try the attached file (rename it to pokemon.json) and let me know. we still testing 
[pokemon-appended.txt](https://github.com/PokemonGoF/PokemonGo-Bot/files/785335/pokemon-appended.txt)

**Comment by andrenagusch** [comment]
```
Traceback (most recent call last):
  File "pokecli.py", line 51, in <module>
    from pokemongo_bot import PokemonGoBot, TreeConfigBuilder
  File "/Users/andre/dev/PokemonGo-Bot/pokemongo_bot/__init__.py", line 23, in <module>
    from . import cell_workers
  File "/Users/andre/dev/PokemonGo-Bot/pokemongo_bot/cell_workers/__init__.py", line 4, in <module>
    from .evolve_pokemon import EvolvePokemon
  File "/Users/andre/dev/PokemonGo-Bot/pokemongo_bot/cell_workers/evolve_pokemon.py", line 2, in <module>
    from pokemongo_bot import inventory
  File "/Users/andre/dev/PokemonGo-Bot/pokemongo_bot/inventory.py", line 1405, in <module>
    Pokemons()  # init Pokemons
  File "/Users/andre/dev/PokemonGo-Bot/pokemongo_bot/inventory.py", line 55, in __init__
    super(_BaseInventoryComponent, self).__init__()
  File "/Users/andre/dev/PokemonGo-Bot/pokemongo_bot/inventory.py", line 34, in __init__
    self.init_static_data()
  File "/Users/andre/dev/PokemonGo-Bot/pokemongo_bot/inventory.py", line 40, in init_static_data
    json.load(open(cls.STATIC_DATA_FILE)))
  File "/Users/andre/dev/PokemonGo-Bot/pokemongo_bot/inventory.py", line 406, in process_static_data
    data = [PokemonInfo(d) for d in data]
  File "/Users/andre/dev/PokemonGo-Bot/pokemongo_bot/inventory.py", line 794, in __init__
    self.fast_attacks = self._process_attacks()
  File "/Users/andre/dev/PokemonGo-Bot/pokemongo_bot/inventory.py", line 924, in _process_attacks
    'charged' if charged else 'fast', name))
KeyError: 'Unknown fast attack: "Fire Spin"'
Sa 18 Feb 2017 22:21:48 CET Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
```

**Comment by pogarek** [comment]
ok, it seems that haven't updated another files. Replace all .json files (you can make a copy if you wish) by these ones from commit: https://github.com/PokemonGoF/PokemonGo-Bot/pull/5918/files

**Comment by andrenagusch** [comment]
Now I've some other errors! I'm trying to find it myself

**Comment by roxane11** [comment]
Two corrections 

Unexpected moveset [Scratch, **Sand Tomb**] for #27 **Sandshrew**, please update info in pokemon.json and create issue/PR
[2017-02-18 21:51:59] [   Pokemon] [ERROR] Unexpected moveset [Tackle, **Flamethrower**] for #156 **Quilava**, please upd

**Comment by pogarek** [comment]
Guys, PR has been made. Get files from https://github.com/PokemonGoF/PokemonGo-Bot/pull/5918/files and check again .

**Comment by andrenagusch** [comment]
@pogarek In my case I get this error:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
[2017-02-18 23:26:08] [sentry.errors.uncaught] [ERROR] [u"KeyError: u'captcha_url'", u'  File "pokecli.py", line 865, in <module>', u'  File "pokecli.py", line 195, in main', u'  File "pokecli.py", line 147, in start_bot', u'  File "pokemongo_bot/__init__.py", line 153, in start', u'  File "pokemongo_bot/__init__.py", line 1076, in _setup_api', u'  File "pokemongo_bot/__init__.py", line 996, in login', u'  File "pokemongo_bot/event_manager.py", line 73, in emit']
Sa 18 Feb 2017 23:26:08 CET Pokebot  Stopped.
```

Couldn't figure out why.

**Comment by pogarek** [comment]
looks like config error..Not related to this issue.

**Comment by svaj** [comment]
Applying the changes in this PR worked for me!

**Comment by MerlionRock** [comment]
@svaj there will still be changes. Some moves are still incorrect

**Comment by rubyShell** [comment]
@MerlionRock how we looking? Just debugging moveset errors? Just wondering how else I can help here. I have a few hours to spare at the moment :)

**Comment by pogarek** [comment]
@rubyShell : let me summarize:
- pokemon.json is, done. (attaching the latest one, 
[pokemon.json.txt](https://github.com/PokemonGoF/PokemonGo-Bot/files/785709/pokemon.json.txt) ; done with https://github.com/pogarek/PokemonDataImporter )
- fast_moves.json and charged_moves.json are updated, but might be incorrect : energy is/was negative in some cases, which causes tests to fail. However negative value in some move make evolve in pokemonOptimizer failed, for one of my tests bots..

So I would say, that test it out. I could generate moves automatically (like it has been done for pokemon.json) , if someone help me with #5921

**Comment by rubyShell** [comment]
@pogarek I'll test it out and see what I can do about #5921 Let me give it a try :)

**Comment by snorlax100** [comment]
Have been running for a few hours one a single account with latest pokemon.json from pogarek. No moveset errors, but did get several times "Possibly searching too often, take a rest",  and once "Server is throttling"

**Comment by ais1406** [comment]
[2017-02-20 13:52:31] [   Pokemon] [ERROR] Unexpected moveset [Scratch, Aqua Jet] for #158 Totodile, please update info in pokemon.json and create issue/PR
[2017-02-20 13:52:31] [   Pokemon] [ERROR] Unexpected moveset [Peck, Drill Peck] for #198 Murkrow, please update info in pokemon.json and create issue/PR

how can i fix?

i already  git pull & ./setup.sh -r 
and git status is master branch

**Comment by Zyrix** [comment]
I think there is an error in the automatically generated pokemon.json
For generation II every pokemon has tackle as fast attack and struggle as charged attack.
IIRC these were just placeholders.

**Comment by MerlionRock** [comment]
@ais1406 That's because when you did that, the PR wasn't merged. Try again with ./setup -u

**Comment by MerlionRock** [comment]
Issue closed as PR merged.
