### ISSUE TITLE
Energy in moves - how to calculate?

### ISSUE THREAD

**Issue by pogarek** [PokemonGoF/PokemonGo-Bot#5921]
In fast_moves.json and charged_moves.json we have Energy property.

Doesn anyone know how to calculate it ? From example from data like here:

```
            {
                "move_id": "214",
                "name": "VINE WHIP",
                "type": "grass",
                "power": "8",
                "duration": "1100",
                "damage_window": "250",
                "crit_percentage": "0%",
                "base_dps": 7.3,
                "has_stab": 1,
                "stab_dps": 9.1,
                "background_hex": "2ecc71",
                "percent": 50,
                "count": 50
            }
```
This is needed to make sure, that we have moves up to date and correct.

**Comment by davidakachaos** [comment]
A quick search around and I think energy for the moves is mainly used in Gym battles? So you can know when a certain move is available for use during a fight?

I don't think we can calculate the energy a move costs, these seems to be static per move... Or am I missing something (can very well be)

**Comment by pogarek** [comment]
Thnx. Actually this will be closed now - the info is in GameMaster :)
