### ISSUE TITLE
Maintaining our own PGoAPI Repo

### ISSUE THREAD

**Issue by MerlionRock** [PokemonGoF/PokemonGo-Bot#5932]
Currently, we are using PGoAPI at https://github.com/pogodevorg/pgoapi 

Question: Do we want to fork it and use it instead of using pogodevorg's.

Currently I have fork of their api, it has minor changes but it serves our purpose. Easy to update Hash server endpoint, Unknown25. Most importantly, it returns what Api version the hashing server is using which can allows us to make simple changes to our bot to correctly inform user if a new api is available.

Any thoughts on this?

**Comment by venney** [comment]
Sine it is only one line in requirments.txt, right?
We could keep pogodevorg to be working as the first priority.
Then maintain another PGoAPI for fun ...

**Comment by ashleykleynhans** [comment]
Sounds like unnecessary admin overhead, why don't you just PR to PGoAPI instead of having to maintain a fork?
