### ISSUE TITLE
'WSAECONNREFUSED' all the time 

### ISSUE THREAD

**Issue by pogarek** [PokemonGoF/PokemonGo-Bot#5934]
It seems that broker.pikabot.org doesn't listen on port 1883.

If this kill your bot, find a line with:
```
handlers.append(SocialHandler(self))
```
 in _init_.py and comment it out.

If the above service will be down for a longer time, we will fix the code .

**Comment by MerlionRock** [comment]
I have a question.

Who maintain pikabot?

**Comment by pogarek** [comment]
@YvesHenri do you have any idea ?

**Comment by friscoMad** [comment]
This still pops every time the bot is started, even with enable_social to false, it is just one time error but I don't see why it does start it if social is disabled.
