### ISSUE TITLE
Info needed - How does Sniping work ?

### ISSUE THREAD

**Issue by roxane11** [PokemonGoF/PokemonGo-Bot#5939]
Wondering how sniping work without even getting soft banned ?

**Comment by davidakachaos** [comment]
Use sniping for real rare Pokemon. The sniper will teleport you around the globe hunting Pokemons. So when you have a lot of Pokemon missing for example (new account or no gen 2 Pokemons yet) the bot will bounce around a lot. That might get noticed sooner then later.

But if you only snipe rare Pokemons, it will not bounce around the globe as much, keeping you more save. But sniping is always the main way people get caught! Remember that.

**Comment by pogarek** [comment]
I snipe since august... no problem or ban so far..  I snipe only 100% IV.
You need to have is a source of coordinates. 
I use [](https://github.com/pogarek/PSSnipeFeeder )( with Discord Module).

**Comment by roxane11** [comment]
I am sniping like anything since a long time, no ban so far ( maybe I am lucky ). Just wondering how teleport works? Like I use bot to play in Ney York area, the moment I log in my Phone in Chicago I get soft banned and then I have to spin a pokestop for 40 times. However, i see no issue with teleporting. Interesting !

**Comment by pogarek** [comment]
Bot teleports and gets pokemon info, then is going back to original location. Taken data are used to catch pokemon from original location

**Comment by saliapin** [comment]
@roxane11 @pogarek @davidakachaos 
{
    "type": "Sniper",
    "config": {
        "enabled": true,
        "mode": "url",
        "bullets": 1,
        "homing_shots": true,
        "special_iv": 100,
        "order": ["missing", "iv", "priority", "vip"],
        "sources": [
            {
                "url": "http://pokesnipers.com/api/v1/pokemon.json",
                "enabled": true,
                "timeout": 15,
                "key": "results",
                "mappings": {
                    "iv": { "param": "iv" },
                    "name": { "param": "name" },
                    "latitude": { "param": "coords" },
                    "longitude": { "param": "coords" },
                    "expiration": { "param": "until", "format": "utc" }
                }
            },
Is this still the format you use?
Besides a local map, do you know of a working alternative to "http://pokesnipers.com/api/v1/pokemon.json" for "url"?
Thanks in advance?

**Comment by pogarek** [comment]
Format is ok. As I said before , you need to find a source for Pokemon.json ... Like my tool, for example

**Comment by saliapin** [comment]
Thanks @pogarek. I gave it a quick try but wasn't able to make the SnipeFeeder work. Probably it's an issue with the Discord account. I'll try it again and let you know. Cheers!

**Comment by MerlionRock** [comment]
@roxane11 I believe Niantic knows you are snipping.

The reason they didn't do the ban is because spoofers are also doing the exact same thing....

And they don't want to ban spoofers.... Or maybe, not yet want to ban them totally....

**Comment by Freeman19** [comment]
in example config 

{
"url": "http://pokesnipers.com/api/v1/pokemon.json",
"enabled": true,
"timeout": 15,
"key": "results",
"mappings": {
"iv": { "param": "iv" },
"name": { "param": "name" },
"latitude": { "param": "coords" },
"longitude": { "param": "coords" },
"expiration": { "param": "until", "format": "utc" }
}

please show example file format ==> pokemon,json
for test snipping....

**Comment by roxane11** [comment]
@pogarek  - Which tool of yours you are referring to ? Can we get download link?

**Comment by pogarek** [comment]
sure. [https://github.com/pogarek/PSSnipeFeeder]

**Comment by pogarek** [comment]
closing. reopen if needed
