### ISSUE TITLE
python Web server not showing map?

### ISSUE THREAD

**Issue by surfaace** [PokemonGoF/PokemonGo-Bot#595]
### Expected Behavior
To see your self moving around at on a google map

### Actual Behavior
no google map is showing, pokemons cant be shown, same for pokedex.
Playerstats and items is showing/updating

(it has been working)

### Steps to Reproduce
D:\Pokemon stuff\PokemonGo-Bot\web>python -m SimpleHTTPServer 8080
Serving HTTP on 0.0.0.0 port 8080 ...
127.0.0.1 - - [24/Jul/2016 08:40:58] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Jul/2016 08:40:58] "GET /main.css HTTP/1.1" 200 -
127.0.0.1 - - [24/Jul/2016 08:40:58] "GET /userdata.js HTTP/1.1" 200 -
127.0.0.1 - - [24/Jul/2016 08:40:58] "GET /main.js HTTP/1.1" 200 -

### Other Information
OS: Win10 x64
Git Commit: 154971c2a5a87738825381e74281ea89943bfd75

**Comment by kaise123** [comment]
Have you renamed 'userdata.js.example' to 'userdata.js' and filled in your username?

**Comment by surfaace** [comment]
yes, also noticed now that it doesnt have pan or zoom on by default, even if specified in userdata.js

// MUST CONFIGURE THE USER ARRAY.
var users = ["myuser"];
var userZoom = true;
var userFollow = true;
var imageExt = ".png";

**Comment by wandering7man** [comment]
js?key=cftodxuvpvdqyksm&callback=initMap:35 Google Maps API error: InvalidKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error

**Comment by wandering7man** [comment]
change google API KEY to urs in index.html 97 line

**Comment by surfaace** [comment]
After keychange in index file it now shows a map
