### ISSUE TITLE
Unexpected moveset [Mud Shot, Mud Bomb] for #50 Diglett

### ISSUE THREAD

**Issue by Kijax** [PokemonGoF/PokemonGo-Bot#5966]
### Expected Behavior
Trivial - no info about unexpexted moveset for Diglett.

### Actual Behavior
Every 10 seccond bot displays info: [   Pokemon] [ERROR] Unexpected moveset [Mud Shot, Mud Bomb] for #50 Diglett, please update info in pokemon.json and create issue/PR

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
Does not matter.

### Output when issue occurred
[   Pokemon] [ERROR] Unexpected moveset [Mud Shot, Mud Bomb] for #50 Diglett, please update info in pokemon.json and create issue/PR

### Steps to Reproduce
1. Need to have Diglett caught before attacks changes made by Niantic in last year.
2. Run the bot...

### Other Information
OS: 
Debian Jessie 8.7
Branch: 
master
Git Commit: 
commit 7e17370be430666d72d0d1420e52074d2f33fcca
Merge: 10b8895 74058c2
Author: pogarek <tregorek@gmail.com>
Date:   Wed Mar 15 06:45:51 2017 +0100
Python Version: 
Python 2.7.9

**Comment by pogarek** [comment]
currently for Diglett we have:
 "Fast Attack(s)": [
      "Mud Slap",
      "Scratch"
    ],

  "Special Attack(s)": [
      "Dig",
      "Mud Bomb",
      "Rock Tomb"
    ],

(in data\pokemon.json for Diglett) 
Adjust the file according to data about your pokemon on phone, then test the bot.
If it will work.  please let me know which attack we should add and to which attack types (fast/special). Thanks

**Comment by Kijax** [comment]
I added Mud Shot fast attack to Diglett info before you suggested that and test this change - it is OK, no more info about unexpected moveset. Then i tried to do pull request ;) but i see that you did that quicker ;)

Changes i made:
"Fast Attack(s)": [
"Mud Slap",
"Mud Shot",
 "Scratch"
],
