### ISSUE TITLE
Shiny magikarp request

### ISSUE THREAD

**Issue by pedroelmoucho** [PokemonGoF/PokemonGo-Bot#5975]
Hello everybody,
Since I've looking for some discord, i've see that some shiny magikarp appears sometimes.
So I want to know if someone can add a variable "shiny" for example to the magikarp, then we can filter our magikarp and release all except shiny magikarp.
I am actually searching if Niantic difference shiny to not shiny with a variable or anything else, but I don't know where to search. So if someone can help me it could be great 
Thanks a lot

Pedroelmoucho

**Comment by MerlionRock** [comment]
I don't have time to code it in. Anyone free please do so. 

It's already in API

```
package POGOProtos.Data;

import "POGOProtos/Enums/Costume.proto";
import "POGOProtos/Enums/Form.proto";
import "POGOProtos/Enums/Gender.proto";

message PokemonDisplay {
	.POGOProtos.Enums.Costume costume = 1;
	.POGOProtos.Enums.Gender gender = 2;
	bool shiny = 3;
	.POGOProtos.Enums.Form form = 4;
}
```

**Comment by davidakachaos** [comment]
I am yet to catch a Shiny Pokemon, but I've added the variable now.

**Comment by pogarek** [comment]
closing
