### ISSUE TITLE
please guide for download the program

### ISSUE THREAD

**Issue by lefteris7** [PokemonGoF/PokemonGo-Bot#5978]
### Other Information
OS: 
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by lefteris7** [comment]
please help to download the program i download the zip but there is no luncher to start the program

**Comment by VBQL** [comment]
Read.
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/docs/installation.md

**Comment by pogarek** [comment]
closing. for "helpdesk" issues step by to discord.
