### ISSUE TITLE
Evolve not properly working?

### ISSUE THREAD

**Issue by rubyShell** [PokemonGoF/PokemonGo-Bot#5983]
Can someone point out a good working configuration for evolving pokemon? 

I want to farm all pokemon, have them evolve, and then transfer the evolved ones out. Just to get mass xp gains. I set specific ones in evolve_list and the evolved ones that I want released in the release config.

The transfer/release stuff is working fine but I can't seem to get the evolve portion right. Am I missing something or did I configure something wrong in my evolve section?

Bot is running and working but Evolvable never updates even though I've caught several pokemon in my evolve_list. Thanks!

{
    "websocket_server": false,
    "heartbeat_threshold": 10,
    "enable_social": false,
    "check_niantic_api": false,
    "live_config_update": {
        "enabled": false,
        "tasks_only": false
    },
    "tasks": [
        {
            "type": "TelegramTask",
            "config": {
                "enabled": false,
                "master": null,
                "password": null,
                "// old syntax, still supported: alert_catch": [
                    "all"
                ],
                "// new syntax:": {},
                "alert_catch": {
                    "all": {
                        "operator": "and",
                        "cp": 1300,
                        "iv": 0.95
                    },
                    "Snorlax": {
                        "operator": "or",
                        "cp": 900,
                        "iv": 0.9
                    }
                }
            }
        },
        {
            "type": "DiscordTask",
            "config": {
                "enabled": false,
                "master": null,
                "// old syntax, still supported: alert_catch": [
                    "all"
                ],
                "// new syntax:": {},
                "alert_catch": {
                    "all": {
                        "operator": "and",
                        "cp": 1300,
                        "iv": 0.95
                    },
                    "Snorlax": {
                        "operator": "or",
                        "cp": 900,
                        "iv": 0.9
                    }
                }
            }
        },
        {
            "//NOTE: This task MUST be placed on the top of task list": {},
            "type": "RandomAlivePause",
            "config": {
                "enabled": false,
                "min_duration": "00:00:10",
                "max_duration": "00:10:00",
                "min_interval": "00:05:00",
                "max_interval": "01:30:00"
            }
        },
        {
            "type": "HandleSoftBan"
        },
        {
            "type": "RandomPause",
            "config": {
                "enabled": false,
                "min_duration": "00:00:10",
                "max_duration": "00:10:00",
                "min_interval": "00:10:00",
                "max_interval": "02:00:00"
            }
        },
        {
            "type": "CompleteTutorial",
            "config": {
                "enabled": false,
                "// set a name": "",
                "nickname": "",
                "// 0 = No Team, 1 = Blue, 2 = Red, 3 = Yellow": "",
                "team": 0
            }
        },
        {
            "type": "CollectLevelUpReward",
            "config": {
                "collect_reward": true,
                "level_limit": -1
            }
        },
        {
            "type": "BuddyPokemon",
            "config": {
                "enabled": true,
                "buddy_list": "dratini, magikarp",
                "best_in_family": true,
                "// candy_limit = 0 means no limit, so it will never change current buddy": {},
                "candy_limit": 0,
                "candy_limit_absolute": 0,
                "// force_first_change = true will always change buddy at start removing current one": {},
                "force_first_change": false,
                "buddy_change_wait_min": 3,
                "buddy_change_wait_max": 5,
                "min_interval": 120
            }
        },
        {
            "type": "IncubateEggs",
            "config": {
                "enabled": true,
                "infinite_longer_eggs_first": false,
                "breakable_longer_eggs_first": true,
                "min_interval": 120,
                "infinite": [
                    2,
                    5,
                    10
                ],
                "breakable": [
                    2,
                    5,
                    10
                ]
            }
        },
        {
            "type": "UpdateLiveStats",
            "config": {
                "enabled": true,
                "min_interval": 30,
                "stats": [
                    "username",
                    "uptime",
                    "stardust_earned",
                    "xp_earned",
                    "xp_per_hour",
                    "stops_visited",
                    "total_stardust"
                ],
                "terminal_log": true,
                "terminal_title": true
            }
        },
        {
            "type": "UpdateLiveInventory",
            "config": {
                "enabled": true,
                "min_interval": 30,
                "show_all_multiple_lines": false,
                "items": [
                    "pokemon_bag",
                    "space_info",
                    "pokeballs",
                    "greatballs",
                    "ultraballs",
                    "razzberries",
                    "luckyegg"
                ]
            }
        },
        {
            "type": "ShowBestPokemon",
            "config": {
                "enabled": true,
                "min_interval": 30,
                "amount": 20,
                "order_by": "cp",
                "info_to_show": [
                    "cp",
                    "ivcp",
                    "dps",
                    "hp"
                ]
            }
        },
        {
            "type": "TransferPokemon",
            "config": {
                "enabled": true,
                "min_free_slot": 9999,
                "transfer_wait_min": 3,
                "transfer_wait_max": 5
            }
        },
        {
            "type": "NicknamePokemon",
            "config": {
                "enabled": false,
                "nickname_above_iv": 0.9,
                "nickname_template": "{iv_pct}-{iv_ads}",
                "nickname_wait_min": 3,
                "nickname_wait_max": 5
            }
        },
        {
            "type": "EvolvePokemon",
            "config": {
                "enabled": true,
                "log_interval": 30,
                "evolve_list": "mankey, psyduck, sandshrew, marill, slugma, cyndaquil, doduo, krabby, cubone, pidgey, rattata, natu, ekans, meowth, wooper, venonat, geodude",
		"donot_evolve_list": "none",
		"min_evolve_speed": 25,
		"max_evolve_speed": 30,
		"use_lucky_egg": false,
		"min_pokemon_to_be_evolved": 1
            }
        },
        {
            "type": "UseIncense",
            "config": {
                "use_incense": false,
                "use_order": [
                    "ordinary",
                    "spicy",
                    "cool",
                    "floral"
                ]
            }
        },
        {
            "type": "RecycleItems",
            "config": {
                "enabled": true,
                "min_empty_space": 15,
                "max_balls_keep": 200,
                "max_potions_keep": 200,
                "max_berries_keep": 77,
                "max_revives_keep": 200,
                "item_filter": {
                    "Pokeball": {
                        "keep": 200
                    },
                    "Potion": {
                        "keep": 5
                    },
                    "Super Potion": {
                        "keep": 5
                    },
                    "Hyper Potion": {
                        "keep": 100
                    },
                    "Revive": {
                        "keep": 100
                    },
                    "Razz Berry": {
                        "keep": 5
                    }
                },
                "recycle_wait_min": 3,
                "recycle_wait_max": 5,
                "recycle_force": true,
                "recycle_force_min": "00:01:00",
                "recycle_force_max": "00:05:00"
            }
        },
        {
            "type": "CatchLimiter",
            "config": {
                "enabled": false,
                "min_balls": 20,
                "duration": 15
            }
        },
        {
            "type": "Sniper",
            "config": {
                "enabled": false,
                "mode": "social",
                "bullets": 1,
                "homing_shots": true,
                "special_iv": 100,
                "order": [
                    "missing",
                    "vip",
                    "priority"
                ],
                "sources": [
                    {
                        "enabled": false,
                        "url": "http://localhost:5000/raw_data",
                        "timeout": 3,
                        "key": "pokemons",
                        "mappings": {
                            "id": {
                                "param": "pokemon_id"
                            },
                            "name": {
                                "param": "pokemon_name"
                            },
                            "latitude": {
                                "param": "latitude"
                            },
                            "longitude": {
                                "param": "longitude"
                            },
                            "expiration": {
                                "param": "disappear_time",
                                "format": "milliseconds"
                            }
                        }
                    },
                    {
                        "enabled": false,
                        "url": "https://pokewatchers.com/grab/",
                        "timeout": 10,
                        "mappings": {
                            "iv": {
                                "param": "iv"
                            },
                            "id": {
                                "param": "pid"
                            },
                            "name": {
                                "param": "pokemon"
                            },
                            "latitude": {
                                "param": "cords"
                            },
                            "longitude": {
                                "param": "cords"
                            },
                            "expiration": {
                                "param": "timeend",
                                "format": "seconds"
                            }
                        }
                    },
                    {
                        "enabled": false,
                        "url": "http://pokesnipers.com/api/v1/pokemon.json",
                        "timeout": 10,
                        "key": "results",
                        "mappings": {
                            "iv": {
                                "param": "iv"
                            },
                            "name": {
                                "param": "name"
                            },
                            "latitude": {
                                "param": "coords"
                            },
                            "longitude": {
                                "param": "coords"
                            },
                            "expiration": {
                                "param": "until",
                                "format": "utc"
                            }
                        }
                    }
                ],
                "catch": {
                    "Snorlax": 1000,
                    "Dragonite": 1000,
                    "Growlithe": 600,
                    "Clefairy": 500,
                    "Kabuto": 500,
                    "Dratini": 500,
                    "Dragonair": 500,
                    "Mr. Mime": 500,
                    "Magmar": 500,
                    "Electabuzz": 500,
                    "Tangela": 500,
                    "Tauros": 500,
                    "Primeape": 500,
                    "Chansey": 500,
                    "Pidgey": 100,
                    "Caterpie": 100,
                    "Weedle": 100
                }
            }
        },
        {
            "type": "CatchPokemon",
            "config": {
                "enabled": true,
                "catch_visible_pokemon": true,
                "catch_lured_pokemon": true,
                "catch_incensed_pokemon": true,
                "min_ultraball_to_keep": 5,
                "berry_threshold": 0.35,
                "vip_berry_threshold": 0.9,
                "treat_unseen_as_vip": true,
                "daily_catch_limit": 10000,
                "vanish_settings": {
                    "consecutive_vanish_limit": 10,
                    "rest_duration_min": "02:00:00",
                    "rest_duration_max": "04:00:00"
                },
                "catch_throw_parameters": {
                    "excellent_rate": 0.1,
                    "great_rate": 0.5,
                    "nice_rate": 0.3,
                    "normal_rate": 0.1,
                    "spin_success_rate": 0.6,
                    "hit_rate": 0.75
                },
                "catch_simulation": {
                    "flee_count": 3,
                    "flee_duration": 2,
                    "catch_wait_min": 3,
                    "catch_wait_max": 6,
                    "berry_wait_min": 3,
                    "berry_wait_max": 5,
                    "changeball_wait_min": 3,
                    "changeball_wait_max": 5,
                    "newtodex_wait_min": 20,
                    "newtodex_wait_max": 30
                }
            }
        },
        {
            "type": "SpinFort",
            "config": {
                "enabled": true,
                "spin_wait_min": 3,
                "spin_wait_max": 5,
                "daily_spin_limit": 1900
            }
        },
        {
            "type": "UpdateWebInventory",
            "config": {
                "enabled": true
            }
        },
        {
            "type": "MoveToFort",
            "config": {
                "enabled": true,
                "lure_attraction": true,
                "lure_max_distance": 2000,
                "walker": "StepWalker",
                "log_interval": 5
            }
        },
        {
            "type": "FollowSpiral",
            "config": {
                "enabled": true,
                "diameter": 4,
                "step_size": 70
            }
        }
    ],
    "map_object_cache_time": 5,
    "forts": {
        "avoid_circles": true,
        "max_circle_size": 50,
        "cache_recent_forts": true
    },
    "pokemon_bag": {
        "// if 'show_at_start' is true, it will log all the pokemons in the bag (not eggs) at bot start": {},
        "show_at_start": true,
        "// if 'show_count' is true, it will show the amount of each pokemon (minimum 1)": {},
        "show_count": false,
        "// if 'show_candies' is true, it will show the amount of candies for each pokemon": {},
        "show_candies": false,
        "// 'pokemon_info' parameter define which info to show for each pokemon": {},
        "// the available options are": {},
        "// ['cp', 'iv_ads', 'iv_pct', 'ivcp', 'ncp', 'level', 'hp', 'moveset', 'dps']": {},
        "pokemon_info": [
            "cp",
            "iv_pct"
        ]
    },
    "walk_max": 4.16,
    "walk_min": 2.16,
    "alt_min": 500,
    "alt_max": 1000,
    "sleep_schedule": {
        "enabled": false,
        "enable_reminder": false,
        "reminder_interval": 600,
        "entries": [
            {
                "enabled": true,
                "time": "12:00",
                "duration": "5:30",
                "time_random_offset": "00:30",
                "duration_random_offset": "00:30",
                "wake_up_at_location": ""
            },
            {
                "enabled": true,
                "time": "17:45",
                "duration": "3:00",
                "time_random_offset": "01:00",
                "duration_random_offset": "00:30",
                "wake_up_at_location": ""
            }
        ]
    },
    "gps_default_altitude": 8,
    "replicate_gps_xy_noise": false,
    "replicate_gps_z_noise": false,
    "gps_xy_noise_range": 1.25E-4,
    "gps_z_noise_range": 12.5,
    "debug": false,
    "test": false,
    "walker_limit_output": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "logging": {
        "color": true,
        "show_datetime": true,
        "show_process_name": true,
        "show_log_level": true,
        "show_thread_name": false
    },
    "catch": {
        "any": {
            "candy_threshold": 10000,
            "catch_above_cp": 0,
            "catch_above_iv": 0,
            "logic": "or"
        },
        "// Example of always catching Rattata:": {},
        "// Rattata": {
            "always_catch": true
        },
        "// Example of catching only Diglett and Horsea needed for Bubblestrat; you might want to also configure sniping (MoveToMap - helps you get hold of neede pokemons faster) and disable SpinFort (or you will advance past level 2 which will make it impossible to catch level-1 pokemons)": {},
        "Diglett": {
            "candy_threshold": 1,
            "catch_below_cp": 11,
            "catch_above_iv": 0,
            "logic": "and",
            "fast_attack": [
                "Scratch",
                "Mud Slap"
            ]
        },
        "Horsea": {
            "candy_threshold": 1,
            "catch_below_cp": 11,
            "catch_above_iv": 0,
            "logic": "and",
            "fast_attack": [
                "Bubble"
            ]
        },
        "// Example of catching Vaporeon only with Water Gun and Hydro Pump": {},
        "Vaporeon": {
            "catch_above_iv": 0.99,
            "charged_attack": [
                "Hydro Pump"
            ],
            "fast_attack": [
                "Water Gun"
            ]
        }
    },
    "release": {
        "any": {
            "release_below_cp": 0,
            "release_below_iv": 0,
            "release_below_ivcp": 0,
            "logic": "or"
        },
        "Venomoth": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Sentret": {
            "release_below_cp": 10000,
            "release_below_iv": 1.0,
            "logic": "or"
        },
        "Paras": {
            "release_below_cp": 10000,
            "release_below_iv": 1.0,
            "logic": "or"
        },
        "Aipom": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Natu": {
            "release_below_cp": 10000,
            "release_below_iv": 1.0,
            "logic": "or"
        },
        "Azumarill": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Marowak": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Spearow": {
            "release_below_cp": 10000,
            "release_below_iv": 1.0,
            "logic": "or"
        },
        "Quilava": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Sandslash": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Pidgeot": {
            "release_below_cp": 10000,
            "release_below_iv": 1.0,
            "logic": "or"
        },
        "Pidgeotto": {
            "release_below_cp": 10000,
            "release_below_iv": 1.0,
            "logic": "or"
        },
        "Raticate": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Arbok": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Dodrio": {
            "release_below_cp": 0,
            "release_below_iv": 1.0,
            "logic": "or"
        },
        "Persian": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Xatu": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Quagsire": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Magikarp": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Magcargo": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Murkrow": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Snubbull": {
            "release_below_cp": 0,
            "release_below_iv": 1.0,
            "logic": "or"
        },
        "Seel": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Zubat": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Tentacool": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Growlithe": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Golduck": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Omanyte": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Abra": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Slowpoke": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Chinchou": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Remoraid": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Totodile": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Staryu": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Spinarak": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Dunsparce": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Goldeen": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Furret": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Poliwag": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Houndour": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Hoothoot": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Primeape": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Eevee": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Qwilfish": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Squirtle": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Graveler": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Slowbro": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Weedle": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Mantine": {
            "release_below_cp": 0,
            "release_below_iv": 0.9,
            "logic": "or"
        },
        "Voltorb": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Machop": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Granbull": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Kingler": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Shellder": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Kabuto": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "Magnemite": {
            "release_below_cp": 0,
            "release_below_iv": 0.95,
            "logic": "or"
        },
        "// Example of keeping 2 best (based on IV) Zubat:": {},
        "// Zubat": [
            {
                "keep_best_iv": 2
            },
            {
                "keep_best_cp": 2,
                "keep_best_iv": 3
            },
            {
                "keep_best_custom": "iv, cp, hp_max",
                "amount": 2
            }
        ],
        "// Keep no more than 3 best IV pokemon for every pokemon type": {},
        "// any": [
            {
                "keep_best_iv": 3
            },
            {
                "keep_best_ivcp": 3
            }
        ],
        "// Keep no more than 3 best IVCP pokemon for every pokemon type": {},
        "// Discard all pokemon in bag except 100 pokemon with best CP": {},
        "// all": {
            "keep_best_cp": 100
        },
        "// Example of keeping the 2 strongest (based on CP) and 3 best (based on IV) Zubat:": {},
        "// Example of custom order of static criterion": {}
    },
    "vips": {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate": {},
        "any": {
            "catch_above_cp": 1200,
            "catch_above_iv": 0.9,
            "logic": "or"
        },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},
        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    },
    "websocket": {
        "start_embedded_server": true,
        "server_url": "127.0.0.1:4000"
    }
}

**Comment by Jcolomar** [comment]
did u read docs about evolve?

**The evolve all mechanism evolves only higher IV/CP Pokémon. It works by sorting the high CP Pokémon (default: 300 CP or higher) based on their IV values. After evolving all high CP Pokémon, the mechanism will move on to evolving lower CP Pokémon only based on their CP (if it can). It will also automatically transfer the evolved Pokémon based on the release configuration.**

**Comment by rubyShell** [comment]
@Jcolomar Let me try it out. I totally kept skipping over that section like an idiot. My bad.

**Comment by rubyShell** [comment]
Okay, I added evolve_cp_min = 1 but nothing is working now. 

Does this stanza look right?

       {
            "type": "EvolvePokemon",
            "config": {
                "enabled": true,
                "log_interval": 30,
                "evolve_list": ["mankey, psyduck, sandshrew, marill, slugma, cyndaquil, doduo, krabby, cubone, pidgey, rattata, natu, ekans, meowth, wooper, venonat, geodude, paras, spearow", "all" ],
                "min_evolve_speed": 25,
                "max_evolve_speed": 30,
                "use_lucky_egg": false,
                "evolve_cp_min": 1,
                "min_pokemon_to_be_evolved": 1
            }
        },

Transfer pokemon is enabled and my release configuration is solid. 

I keep seeing this...

[2017-03-30 08:40:46] [EvolvePokemon] [INFO] Evolvable: 0/1

Even though I have plenty of pokemon to evolve :/

**Comment by rubyShell** [comment]
I had the evolve list in brackets which I updated at some point thinking it didn't like my list. I have removed it and it appears to be working now. Just want to ensure the transfer is still working and I'll close this out. 
Thanks @Jcolomar

**Comment by Jcolomar** [comment]
today i started to test evolvepokemon and i have this setup:

{
            "type": "EvolvePokemon",
            "config": {
                "enabled": true,
                "log_interval": 360,
                "evolve_list": "all",
                "donot_evolve_list": "none",
                "first_evolve_by": "iv",
                "evolve_above_cp": 9,
                "evolve_above_iv": 0.99,
                "logic": "and",
                "min_evolve_speed": 25,
                "max_evolve_speed": 30,
                "min_pokemon_to_be_evolved": 2,
                "use_lucky_egg": false
            }
        },

**Comment by rubyShell** [comment]
It only evolved a few so I added some more parameters based on your configuration.

            "type": "EvolvePokemon",
            "config": {
                "enabled": true,
                "log_interval": 30,
                "evolve_list": "mankey, psyduck, sandshrew, marill, slugma, cyndaquil, doduo, krabby, cubone, pidgey, rattata, natu, ekans, meowth, wooper, venonat, geodude, paras, spearow",
                "min_evolve_speed": 25,
                "max_evolve_speed": 30,
                "use_lucky_egg": false,
                "evolve_cp_min": 1,
                "evolve_iv_min": 0,
                "evolve_above_cp": 1,
                "evolve_above_iv": 0,
                "logic": "and",
                "donot_evolve_list": "none",
                "min_pokemon_to_be_evolved": 1
            }

**Comment by Jcolomar** [comment]
i hope it works now

**Comment by rubyShell** [comment]
This final configuration worked. I'll make a PR to update the documentation as they aren't too clear.

**Comment by Jcolomar** [comment]
great
