### ISSUE TITLE
[Feature Request] pinap on low lvl mons

### ISSUE THREAD

**Issue by WayneUong** [PokemonGoF/PokemonGo-Bot#5986]
Can we have `pinap_on_level_below` or `pinap_on_cp_below` options?

**Comment by MerlionRock** [comment]
My hash key expired.

Once I have a vaild hash key, I'll work on it. That's not hard.

**Comment by MerlionRock** [comment]
This option is for use_pinap_on_vip right?

Doesn't make sense if anyone want to use on any other pokemon that's not VIP....

**Comment by davidakachaos** [comment]
I disagree Merlion, Maybe someone wants to use a pinap on a Pokemon when they can almost evolve that Pokemon in a missing or better combat Pokemon.

I vote for a ```pinap_on_candy_needed``` kind of config.

**Comment by MerlionRock** [comment]
I've added 3 new configuration, they are: 

```
"pinap_on_level_below": 0,
"pinap_operator": "or",
"pinap_ignore_threshold": false,
```

set "pinap_on_level_below" to 0 if you don't want to use it at all
"pinap_operator" -> or | and to be used together with "use_pinap_on_vip"
"pinap_ignore_threshold" to ignore threshold if set to true

Any more request before I sumbit a PR?

**Comment by MerlionRock** [comment]
PR added #5990

**Comment by MerlionRock** [comment]
Merged therefore Close
