### ISSUE TITLE
Config has no split attribute for Item_filter

### ISSUE THREAD

**Issue by surfaace** [PokemonGoF/PokemonGo-Bot#599]
### Expected Behavior
Split and read the string to array?

### Actual Behavior
D:\Pokemon stuff\PokemonGo-Bot>pokecli.py
Traceback (most recent call last):
  File "D:\Pokemon stuff\PokemonGo-Bot\pokecli.py", line 219, in <module>
    main()
  File "D:\Pokemon stuff\PokemonGo-Bot\pokecli.py", line 196, in main
    config = init_config()
  File "D:\Pokemon stuff\PokemonGo-Bot\pokecli.py", line 168, in init_config
    config.item_filter = [str(item_id) for item_id in config.item_filter.split(',')]
AttributeError: 'list' object has no attribute 'split'

### Steps to Reproduce
Have up-to-date config.json

### Other Information
OS:  Win10 pro x64
Git Commit: a634b5529fe0a230bf5cb87e5158ab1844cca6b5

**Comment by fsegouin** [comment]
Same error here.

**Comment by Balauue** [comment]
Had the same issue, because the notation has changed. Now I use ``"101,102,103"`` as opposed to ``["101","102","103"]``, which worked 12 hours ago

**Comment by surfaace** [comment]
Seems to be working

**Comment by dmateusp** [comment]
Please don't mark it as working! the logic hasn't be changed by the person that "fixed" the problem, a list should be used because I use "101" in list, I'm working on making both "101,102,103" and ["101","102","103"] work but it will drop everything at the moment !

**Comment by surfaace** [comment]
@dmadisetti assign the issue to yourself then please :)
