### ISSUE TITLE
Bulk transfer crashes the bot

### ISSUE THREAD

**Issue by pogarek** [PokemonGoF/PokemonGo-Bot#5992]
@walaoaaa1234 check comments in #5988 .
If this won't get fixed we will need to figure out how to remove/rollback #5988 and #5987 from dev branch....

**Comment by walaoaaa1234** [comment]
maybe limit it to 50 pokemons at a time

**Comment by pogarek** [comment]
how ? can you code to have the bulk transfer optional and the classic one as default ? 
We cannot merge dev to master till it will be resolved..

@Jcolomar would it help for you ? (the limit to 50)

**Comment by pogarek** [comment]
@walaoaaa1234 will you be able to fix it or should I revert https://github.com/PokemonGoF/PokemonGo-Bot/commit/437c2bd65c551a686058d07ddc6ce3ccee1b9963#diff-40e7f769ac13a8c2681747b100bfa53c and https://github.com/PokemonGoF/PokemonGo-Bot/commit/70df5464f4c0e9ce79d55adde8c615ab6793d673#diff-40e7f769ac13a8c2681747b100bfa53c ?

**Comment by walaoaaa1234** [comment]
i am working on it

**Comment by pogarek** [comment]
great , thnx

**Comment by Jcolomar** [comment]
@pogarek didnt work to me. No transfer. 

![image](https://cloud.githubusercontent.com/assets/21227457/24621580/45dc45f4-18a2-11e7-8f96-221a9ba20f20.png)

**Comment by MerlionRock** [comment]
@walaoaaa1234 See comments I have for your latest PR

**Comment by MerlionRock** [comment]
@pogarek say he can't get it working.

Anyone else facing same issue. I would love to merge all changes to Master soon.

**Comment by Jcolomar** [comment]
Fixed #5998
