### ISSUE TITLE
Get rid of the evolved pokemons after XP evolve (#5876)

### ISSUE THREAD

**Issue by Jcolomar** [PokemonGoF/PokemonGo-Bot#5999]
This has issues. The bot release all pokemons evolved in same round, trash and good ones:

[2017-04-05 21:07:19] [PokemonOptimizer] [INFO] Evolving 3 Pokemon (the best)
[2017-04-05 21:07:19] [PokemonOptimizer] [INFO] Evolved Geodude [IV 1.0] [CP 682] [2205 candies] [+500 xp]
[2017-04-05 21:07:45] [PokemonOptimizer] [INFO] Evolved Graveler [IV 1.0] [CP 1037] [2106 candies] [+500 xp]
[2017-04-05 21:08:11] [PokemonOptimizer] [INFO] Evolved Magnemite [IV 1.0] [CP 929] [9804 candies] [+500 xp]
[2017-04-05 21:08:38] [PokemonOptimizer] [INFO] Transferring 2 Pokemon
[2017-04-05 21:08:41] [PokemonOptimizer] [INFO] Exchanged Magneton [IV 1.0] [CP 1917] [9805 candies]
[2017-04-05 21:08:41] [PokemonOptimizer] [INFO] Exchanged Golem [IV 1.0] [CP 1666] [2107 candies]

**Comment by MerlionRock** [comment]
@Jcolomar 
I just went through the codings.

Can't find anything wrong with it. It simply just run the checking 2 times. Post your Optimizer config again, I try to see what go wrong.

**Comment by Jcolomar** [comment]
"rules": [
                    {
                        "mode": "overall",
                        "top": 1,
                        "sort": [
                            "-candy",
                            "iv"
                        ],
                        "evolve": false,
                        "buddy": true
                    },
                    {
                        "mode": "by_pokemon",
                        "names": [
                            "gym_attack"
                        ],
                        "top": 2,
                        "sort": [
                            "moveset.attack_perfection",
                            "dps_attack",
                            "npc"
                        ]
                    },
                    {
                        "mode": "by_pokemon",
                        "names": [
                            "gym_def"
                        ],
                        "top": 3,
                        "sort": [
                            "moveset.defense_perfection",
                            "dps_defense",
                            "npc"
                        ]
                    },
                    {
                        "mode": "by_family",
                        "top": 1,
                        "sort": [
                            "moveset.attack_perfection",
                            "iv",
                            "dps_attack",
                            "npc"
                        ],
                        "evolve": {
                            "iv": 1.0
                        }
                    }
                ]

**Comment by guenterneust** [comment]
I had almost the same issue a few days ago. After evolving (the best) 7 pokemons, the bot threw away 5 pokemons, from those just evolved, including pokemons which were the best in their family from any possible point of view. I was using the stock config.json.optimizer on raspbian.

**Comment by Jcolomar** [comment]
Tyvm david. Time to test,

Optimizer fix #6006
