### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by crack00r** [PokemonGoF/PokemonGo-Bot#6]
Hi, pp?

**Comment by PokemonGoF** [comment]
wow... let me setup a bitcoin account?

**Comment by crack00r** [comment]
only have PP, no bitcoins

**Comment by PokemonGoF** [comment]
will this work?
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=WQUXDC54W6EVY

**Comment by crack00r** [comment]
yep, send you have some money for a beer, or something

**Comment by PokemonGoF** [comment]
Lol, thanks a lot :)
