### ISSUE TITLE
[Feature Request]  Keep_to_evolve Pokemon

### ISSUE THREAD

**Issue by ronaldobr72** [PokemonGoF/PokemonGo-Bot#6000]
### Short Description

I've create a "keep_to_evolve" = true parameter on my code, I'm trying to make sure it's working.

Ex: config.json
"release":
     {
         "Pidgey": {"keep_to_evolve": true},
     }

It will keep enough pidgey to evolve according to the number of candies, ex. if I have 30 candies and 5 Pidgey it will release 3 Pidgey and keep 2.

I'm just getting to use Python, so maybe  there is a better way to do it.

### Possible solution

change in transfer_pokemon.py

    def keep_to_evolve(self, pokemon):
        
        release_config = self._get_release_config_for(pokemon.name)
           
        if release_config.get('keep_to_evolve', False):
          
           bag = inventory.pokemons().all()
           pokemon_list = [filter(lambda x: x.pokemon_id == pokemon.pokemon_id, bag)]
           if pokemon.evolution_cost > 0:
              pokemons_to_evolve = pokemon.candy_quantity / pokemon.evolution_cost
              if pokemons_to_evolve == 0:
                 pokemons_to_evolve = 1
                 
              total_pokemons = len(pokemon_list[0])
              if pokemons_to_evolve < total_pokemons:
                  self.emit_event(
                     'future_pokemon_release',
                     data={
                          'pokemon': pokemon.name,
                          'iv': pokemon.iv,
                          'cp': pokemon.cp,
                          'ivcp': pokemon.ivcp
                          },
                          formatted="do not Keep to evolve {} (CP: {}, IV: {}, IVCP: {} shiny: {} Candies {} for {} of {} Evolutions )".format(pokemon.name, pokemon.cp, pokemon.iv, pokemon.ivcp, pokemon.shiny, pokemon.candy_quantity, total_pokemons, pokemons_to_evolve, ),
                  )
                  return False
              else:
                  self.emit_event(
                     'future_pokemon_release',
                     data={
                          'pokemon': pokemon.name,
                          'iv': pokemon.iv,
                          'cp': pokemon.cp,
                          'ivcp': pokemon.ivcp
                          },
                          formatted="Keep to evolve {} (CP: {}, IV: {}, IVCP: {} shiny: {} Candies {} for {} of {} Evolutions )".format(pokemon.name, pokemon.cp, pokemon.iv, pokemon.ivcp, pokemon.shiny, pokemon.candy_quantity, total_pokemons, pokemons_to_evolve, ),
                  )                 
                  return True
           else:
              return False
        else:
            return False

.
.
.
    def should_release_pokemon(self, pokemon, keep_best_mode=False):
        release_config = self._get_release_config_for(pokemon.name)

     
        if release_config.get('keep_to_evolve', False):
            keep_to_evolve = self.keep_to_evolve(pokemon)
            if keep_to_evolve:
               return False
            else:
               return True

also include this code to keep my shiny pokemons:

        never_release_shiny = release_config.get('never_release_shiny', 0)
        if pokemon.shiny and never_release_shiny:
           self.emit_event(
               'future_pokemon_release',
               data={
                   'pokemon': pokemon.name,
                   'iv': pokemon.iv,
                   'cp': pokemon.cp,
                   'ivcp': pokemon.ivcp,
               },
               formatted="Kept {} (CP: {}, IV: {}, IVCP: {} shiny: {})".format(pokemon.name, pokemon.cp, pokemon.iv, pokemon.ivcp, pokemon.shiny),
           )
           return False

### How it would help others

When you want to get a lot of Pokemons to evolve and get to the next level, you will have only the exactly number of Pokemons that you need.

**Comment by MerlionRock** [comment]
There's already such option under Pokemon Optimizer: evolve_for_xp
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/pokemon_optimizer.md

**Comment by ronaldobr72** [comment]
@MerlionRock thank you very much fro your answer. I'll start using it.
