### ISSUE TITLE
Bot crash after update to latest 0.61 API

### ISSUE THREAD

**Issue by MerlionRock** [PokemonGoF/PokemonGo-Bot#6001]
Solution: in _init_.py, comment or delete line 1039.

Let me think of better solotion before doing a PR for this. But for now, use the above mentioned to run your bot.

**Comment by TraggerHippy** [comment]
Thanks got me up and running. Before had to restart the bot constantly due to server busy or offline, without much success.

👍

**Comment by MerlionRock** [comment]
Closing, issued solved
