### ISSUE TITLE
can not start unrecognized arugments

### ISSUE THREAD

**Issue by ahangchen** [PokemonGoF/PokemonGo-Bot#602]
### Expected Behavior
```
/home/cwh/.conda/envs/pokemon/bin/python pokecli.py -a google -u cwh -p 1234 --location "New York, Washington Square"
```

### Actual Behavior
```
/home/cwh/.conda/envs/pokemon/bin/python pokecli.py -a google -u cwh -p 1234 --location "New York, Washington Square"
usage: pokecli.py [-h] [-cf CONFIG]
pokecli.py: error: unrecognized arguments: -a google -u cwhgooglezero -p 1234 --location New York, Washington Square
```

### Steps to Reproduce
as above

### Other Information
OS: ubuntu 14.04 lts 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by julienkessels** [comment]
yea readme is totaly not uptodate, needs update, im getting confused too, took me 30 minutes to work it out on my own

**Comment by hklcf** [comment]
rename and config `release_config.json.example` to `release_config.json`
rename and config `config.json.example` to `config.json`

python pokecli.py

**Comment by julienkessels** [comment]
where do i get a gmapkey from ?

**Comment by hklcf** [comment]
@julienkessels [https://console.developers.google.com/flows/enableapi?apiid=maps_backend,geocoding_backend,directions_backend,distance_matrix_backend,elevation_backend,places_backend&keyType=CLIENT_SIDE&reusekey=true](url)

**Comment by ahangchen** [comment]
OK, thanks.
