### ISSUE TITLE
Modified client software warning 

### ISSUE THREAD

**Issue by camnomis** [PokemonGoF/PokemonGo-Bot#6025]
As a heads up I was presented with the warning when I logged in, I have the API check in the config so only run with the latest API but still got the warning, not sure if Niantic are getting smarter or I have been careless but thought I'd warn every one else to be careful!

**Comment by TraggerHippy** [comment]
Same here on all of my bot accounts.

**Comment by MerlionRock** [comment]
Happens to all that run bots. Any bot....

Think Niantic is now laughing seeing this message...

Niantic: 1 Bots: 0

**Comment by DeepJeep** [comment]
Got the warning as well.

Did anyone get banned yet?

**Comment by TraggerHippy** [comment]
No bans yet for me. Are some of you still running the bot ? The message is more or less a final warning i asume, or does it mean you are nominated for a new banwave to come ?

**Comment by davidakachaos** [comment]
Remember that the bot uses a iPhone as device, so if you login from a
android, this warning is more likely to be displayed. I had this warning on
one account, but haven't been banned.

Op 22 apr. 2017 12:44 schreef "TraggerHippy" <notifications@github.com>:

**Comment by davidakachaos** [comment]
Never mind, in the recent iOS version I get the warning also.

**Comment by MerlionRock** [comment]
It's has to be something that trigger it. All bots are hit.

**Comment by MerlionRock** [comment]
@TraggerHippy I assume if you have that message, it means you are nominated for next ban wave... But doesn't mean you will get banned. Depend if they still detect if you are using 3rd party.

**Comment by TraggerHippy** [comment]
Is it wise to stop until the message is no longer presented ? Perhaps set a strict limiter with random alive pauses ? It's strange all bots are hit, find that a bit tricky...

**Comment by camnomis** [comment]
Not used the bot since I got the message, today it dropped off, will use another account of mine to see if/when it comes back

**Comment by TraggerHippy** [comment]
I did use the bot on 1 account, which had the message. The message was lifted for that account as well.

**Comment by TraggerHippy** [comment]
On 1 account the message has returned. Not on all of them this time.

**Comment by davidakachaos** [comment]
Closing old issue, if you think this is an error let me know or open a new issue. Thank you.
