### ISSUE TITLE
Pause FollowPath if Hunter is locked

### ISSUE THREAD

**Issue by hotbit007** [PokemonGoF/PokemonGo-Bot#6030]
### Short Description

The time given for wander is not sufficient to reach the target of the PokemonHunter if a target was locked. It would be great to pause the FollowPath task to allow the Hunter to finish.
In the current setup the FollowPath would break the Hunter.

### Possible solution

Give an option to FollowPath and/or Hunter to take precedent over FollowPath. If given resume FollowPath at cool down.

### How it would help others

Should be important to everybody using followPath and Hunter.

**Comment by davidakachaos** [comment]
Sorry it took a while, but the PR is done 😉

**Comment by Jcolomar** [comment]
#6031
