### ISSUE TITLE
Trading recommendation

### ISSUE THREAD

**Issue by taigrr** [PokemonGoF/PokemonGo-Bot#604]
I think there should be a way to only trade pokemon you don't already own, and if you get one that's lower than the specified CP but higher than the highest of its type, it should keep the collected one and drop the lower of the two.

**Comment by hahnrobert** [comment]
Totally agree. 
Add a flag to only transfer pokemons which you already own, and always transfer the lower of them.

**Comment by hahnrobert** [comment]
Working on a PR to make this happen.

**Comment by hahnrobert** [comment]
Here is the corresponding pull request #668

**Comment by surfaace** [comment]
please resolve issues with latest DEV branch with that PR #668 and create new PR
