### ISSUE TITLE
Proposal: New Snipe Mode

### ISSUE THREAD

**Issue by MerlionRock** [PokemonGoF/PokemonGo-Bot#6046]
Since sniping does not work anymore, here a proposal:

Local Sniping with Hunter.

Use a local map source. While hunter is checking for eligible Pokemon, it will also check sniping source. If a pokemon is within x-km of current location and expired time of more than x-mins, it will close session and wait for x mins before login to new location and capture. 

After which I'm not sure if it should continue doing it's task at new location or logout and wait for x mins before going back to old location. (If use follow path, it should teleport back and wait out)

Currently thinking that x should be 15. But should be configurable by user.

This model of snipping would work very well in locations where it is small but has a wide range of Pokemons. Example, Singapore is 50km from west to east, a snipping range of 15 radius would cover almost the whole of Singapore, this will greatly increase snipping of rare monster.

If user wants snipping for specific common pokemons for specific uses, then they should be using follow path at nest.

Any thought?

**Comment by Jcolomar** [comment]
Singanpore is a perfect location for this, short distances to snipe :). Can this proposal export to any city?

**Comment by MerlionRock** [comment]
As long as there's a source. Any city should be fine.

The tested formula for unSoftban is 1km/min.

For a distance of 15km, that will be 15mins.

**Comment by Jcolomar** [comment]
Max softban time is 2 hours

**Comment by MerlionRock** [comment]
#6151
