### ISSUE TITLE
API check failed with new key (but not really?)

### ISSUE THREAD

**Issue by crvfts** [PokemonGoF/PokemonGo-Bot#6053]
Using fresh clone of master and new key purchased today, I received this error on all ptc and google account:

`[2017-05-31 16:29:09] Login procedure started.
[2017-05-31 16:29:17] Login successful.
[2017-05-31 16:29:17] Niantic Official API Version: 0.63.1
[2017-05-31 16:29:17] Latest Bossland Hashing API Version: 0.63.1
[2017-05-31 16:29:17] We have detected a Pokemon API Change. Latest Niantic Version is: 0.63.1. Program Exiting...`

If I tun off api check in config the bot runs fine and I do not appear to be shadowbanned. All captcha checks passed as well.

OS: Windows 8.1

**Comment by MerlionRock** [comment]
Do me a favor, at line 1064 add the following
```
print(format(officialAPI_int))
print(format(hashingAPI_int))
```
Let me know what are their values and are they different

**Comment by crvfts** [comment]
`[2017-06-01 11:16:39] Login successful.
[2017-06-01 11:16:40] Niantic Official API Version: 0.63.1
[2017-06-01 11:16:41] Latest Bossland Hashing API Version: 0.63.1
631
610
[2017-06-01 11:16:41] We have detected a Pokemon API Change. Latest Niantic Version is: 0.63.1. Program Exiting...`

**Comment by MerlionRock** [comment]
610?????!

You are using 0.61.0 Hashing.... in your requirement.txt, do you have this line?
git+https://github.com/pogodevorg/pgoapi.git@develop#egg=pgoapi

**Comment by MerlionRock** [comment]
I would advise that you stop your bots until you are sure you are using latest hashing instead of old one. I have no idea why are you using 0.61.0 Hash

**Comment by crvfts** [comment]
I cloned fresh, but I double-checked requirements and it's exactly as it appears on the current commit.

**Comment by crvfts** [comment]
question- do we need to clone recursively or something? when i clone i do:

git clone -b master https://github.com/PokemonGoF/PokemonGo-Bot

then do: pip install -r requirements

but that should have nothing to do with the install correct? api is on bossland's end, right?

**Comment by MerlionRock** [comment]
We are using API from https://github.com/pogodevorg/pgoapi/tree/develop

What is werid is that you are using a old api. There have to be something that went wrong or your pervious installation of pogo API wasn't overwrite by new one. @pogarek You able to give suggestion?

**Comment by MerlionRock** [comment]
Have you tried running PokemonGo-Bot-Updater.bat?

**Comment by crvfts** [comment]
I tried that but it seems to hang will installing the web submodule.

**Comment by crvfts** [comment]
OK I see what's happening- somehow the pip install is install to my Python3.5 installation!

**Comment by MerlionRock** [comment]
So problem solved? :) Can this issue be closed? :)

**Comment by crvfts** [comment]
Uninstalled 3.5 and removed from PATH, reboot, FIXED!

**Comment by MerlionRock** [comment]
:)
