### ISSUE TITLE
[Solved - Please Close] Need help with a second bot in my Web UI (propably not a bug, but my fault in a config)

### ISSUE THREAD

**Issue by thelemonenergy** [PokemonGoF/PokemonGo-Bot#6055]
I have 2 Bots running on 2 Servers

What I want to do is to have both bots showing in the Web UI of Server1
What is working in this config is that both accounts are shown on the right under "bots",
but only account1@gmail.com is showing a route and any informations about Info or Pokemon.
The Log Popups in the bottom left show information from both bots.

I opened ports 4000 and 5000 on both servers. Am I missing a port?

The webserver is nginx, but with the python webserver it did exactly the same.
I changed the Web UI to port 80 far before i added the second bot.

The Userdata.js on the Server1 with the active Web UI

    users: [{
    enable: true,
    username: "account1@gmail.com",
    socketAddress: "externalIP-Server1:4000",
    enableSocket: true
    },{
    enable: true,
    username: "account2@gmail.com",
    socketAddress: "externalIP-Server2:5000",
    enableSocket: true

Config on Server1

    {
    "websocket_server": true,
    ...
    "websocket": {
    "start_embedded_server": true,
    "server_url": "externalIP-Server1:4000"
    }
    }

Config on Server2

    {
    "websocket_server": true,
    ...
    "websocket": {
    "start_embedded_server": true,
    "server_url": "externalIP-Server2:5000"
    }
    }

Can anybody help me?
I cant find a full documetation about running multiple bots in one Web UI, is there one?

**Comment by walaoaaa1234** [comment]
```
enable: true,
username: "account2@gmail.com",
socketAddress: "externalIP-Server2:5000",
enableSocket: true
```
``What I want to do is to have both bots showing in the Web UI of Server1``
try ``socketAddress: "externalIP-Server1:5000",`` and ``"server_url": "externalIP-Server1:5000"``

**Comment by thelemonenergy** [comment]
This is what the bot in Server2 sais whenever I change the "server_url" to anything other than its own IP:

> [2017-06-02 22:12:29] [       cli] [INFO] Config changed! Applying new config.
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/admin/PokemonGo-Bot/pokemongo_bot/socketio_server/runner.py", line 34, in _start_listening_blocking
    listener = eventlet.listen((self.host, self.port))
  File "/home/admin/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/convenience.py", line 43, in listen
    sock.bind(addr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address

**Comment by thelemonenergy** [comment]
This can be closed.

The improvements to the webUI fixed it.

**Comment by nbq** [comment]
Closed as requested @thelemonenergy
