### ISSUE TITLE
API Change?

### ISSUE THREAD

**Issue by camnomis** [PokemonGoF/PokemonGo-Bot#6060]
[2017-06-24 16:10:44] [PokemonGoBot] [INFO] Niantic Official API Version: 0.67.1
[2017-06-24 16:10:44] [PokemonGoBot] [INFO] Latest Bossland Hashing API Version: 0.67.1
[2017-06-24 16:10:44] [PokemonGoBot] [INFO] We have detected a Pokemon API Change. Latest Niantic Version is: 0.67.1. Program Exiting...

I thought when bossland changed "we" had a fix where as the API version being checked against wasn't hardcoded?

**Comment by walaoaaa1234** [comment]
pgoapi not yet updated, hashing server does updated the algorithm. just wait more couple day, and the request flow changed.

**Comment by MerlionRock** [comment]
We check against what API we are using. Bossland is already providing latest hashing but Python API not ready. They want to be sure no trap set by Niantic before releasing it.

We will wait for them.

 (I know what need to be done to implement the API change, but I'm not going to do it)

**Comment by Socratemus** [comment]
Any news on this api change?

**Comment by walaoaaa1234** [comment]
pgoapi is updated, the bot haven't update the request flow.
you may run the bot now, but your account may **flagged/BANNED/slash pokemon.**
If you persist, run `pip install -r requirements.txt -U`
If you don't know what it is, **DO NOT RUN THE BOT**

**Comment by davidakachaos** [comment]
Sniping is the main issue for getting flagged Pokemon I think...

**Comment by pogarek** [comment]
ok, we got some PRs about new api, but I don't think is enough. We need to remember about Get_Inbox in requests. 

RocketMap got updated: https://github.com/RocketMap/RocketMap/commit/a125ebdc1c76730c59368d60e2c64ffeecfbd637

but we have some problems here
1. some say, that get_inbox should on every request and some says, that only on few
2. in bot sometimes we use functions from api_wrapper, and sometime we call api directly. For example check .py files for get_buddy_walked
3. In POgoLib (C#) the api handles default requests https://github.com/AeonLucid/POGOLib/blob/7357c56279f964e25e660e42367fbd140dd1f9fd/POGOLib.Official/Net/RpcClient.cs#L323 , so every request there is CheckChallenge , GetHatchedEggs, GetInventory , CheckAwardedBadges,DownloadSettings . Getinbox will be added there as well , probably
4. so we shoudl have ALL request handled by one code in bot or in api. 
5. let's take check_awarded_badges now. In bot we call it only in heartbeat (init.py). 

to much unknowns here for me.. plus my low python experience excludes me from fixing the bot..

**Comment by walaoaaa1234** [comment]
maybe we can use sLoPPydrive MrMime.
https://github.com/sLoPPydrive/MrMime/
but is everyone using the correct request flow?

**Comment by davidakachaos** [comment]
@MerlionRock has fixed the checking of the API and I have implemented GetInbox in heartbeat, I don't know if it's enough though...

**Comment by goedzo** [comment]
Please close issue. Is fixed now.

**Comment by davidakachaos** [comment]
Closing this issue, if you think this is an error please let us know! Thank you!
