### ISSUE TITLE
fast movesets

### ISSUE THREAD

**Issue by Jcolomar** [PokemonGoF/PokemonGo-Bot#6069]
Id like to understand the diferences between movesets in the bot. 

In Optimicer u can choose between this ones:

dps	--------------->raw dps based on the moves of the pokemon
dps1	--------->raw dps of the fast attack
dps2	--------->raw dps of the charge attack
dps_attack	---->estimated average dps when attacking
attack_perfection ->ratio dps_attack / best_dps_attack. Return same order as dps_attack

If i want optimicer DONT release dragonite with DRAGON TAIL / OUTRAGE what of those one pointing to fast attack should i choose. 

I had this config in Optimicer:
"moveset.attack_perfection", "dps1", "dps2", "iv", "cp"

Is i understand, dps1 isnt work like i spected coz im only keeping dragonites with Steel Wing [ 11 ] in fast attack, and proper one is Dragon Tail.

Same occurs with Snorlax, best fast attack is LICK, and bot only keeping Zen Headbutt [ 12 ]

On the other hand, "dps2" is working good as i knew, keeping best damage moveset

I hope someone can help.

Thx

**Comment by davidakachaos** [comment]
Maybe we should check the file under data -> fast_moves.json
I think some balancing things have not been adjusted. Do we have a good source for the stats on these moves?

**Comment by Jcolomar** [comment]
https://pokemongo.gamepress.gg/

But i think is wrong in my config. Set "dps1" force to keep best damage move, not best moveset

**Comment by davidakachaos** [comment]
You're right, DPS, DPS Attack/Defense and Attack/Defense perfection are calculated from the moveset, but the dps1 (fast attack) and dps2 (charge attack) should come straight from the respective json files under data...
So if the data in those files are off....

**Comment by Jcolomar** [comment]
Closed #6078
