### ISSUE TITLE
Server seems to be busy or offline - only for Google login

### ISSUE THREAD

**Issue by krishven** [PokemonGoF/PokemonGo-Bot#6070]
===============ISSUE SECTION===============

### Expected Behavior
Bot should work normally for all kinds of login

### Actual Behavior
Bot says "Server seems to be busy or offline" for Google login, but works for ptc login.
Also I can login using the google account from my phone.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
Same for both logins, doesn't matter here

### Output when issue occurred
Login procedure started.
Server seems to be busy or offline, retrying in 905 seconds

### Steps to Reproduce
Start bot with google login

### Other Information
OS: 
MacOS
Branch: 
dev
Git Commit: 
1df94d9a655d904fdd903d0952c97a2ae5146e5c
Python Version: 
2.7.10
Any other relevant files/configs (eg: path files) 
NA

**Comment by fatalerrortan** [comment]
Bot has just detected,Niantic Official API has been updated to 0.67.2. Latest Bossland Hashing API is still Version: 0.67.1    
Nevertheless, I can still login using google account.

**Comment by kranzrm** [comment]
Running into same error.  Unable to login using non-google auth.

**Comment by Jcolomar** [comment]
Server hashing has a lot of issues

**Comment by goedzo** [comment]
I fixed the server hashing issues by adding a fixed ip into my dns. Some of the hashing servers are down, but a lot of others are working ok.

**Comment by hankmoody801** [comment]
Any update on this, I can't get the hash I purchased today to work... It doesn't work using a google account or a pokemon account.

**Comment by davidakachaos** [comment]
@hankmoody801 I think the issues with the hashing service have (almost) been resolved. Have you updated the bot with setup.sh -u ? 
If you still have issues after that, what is the message you get? Server offline? Or do you get a notification that your hash key is rejected?

**Comment by hankmoody801** [comment]
[2017-07-10 08:28:22] [MainThread] [PokemonGoBot] [INFO] Login successful.
[2017-07-10 08:28:22] [MainThread] [PokemonGoBot] [INFO] Checking for captcha challenge.
[2017-07-10 08:28:22] [MainThread] [CaptchaHandler] [INFO] Captcha Check Passed
[2017-07-10 08:28:22] [MainThread] [PokemonGoBot] [INFO] Niantic Official API Version: 0.67.2
[2017-07-10 08:28:23] [MainThread] [PokemonGoBot] [INFO] Latest Bossland Hashing API Version: 0.67.1
[2017-07-10 08:28:23] [MainThread] [PokemonGoBot] [INFO] We have detected a Pokemon API Change. Latest Niantic Version is: 0.67.2. Program Exiting...

**Comment by hankmoody801** [comment]
@davidakachaos Yes, I updated the bot with setup.sh -u. It updated fine.  I also tried to connect via ptc and google accounts with no luck.  I put my terminal response in my previous message.

**Comment by davidakachaos** [comment]
I see the problem; the Bossland API still says it's 0.67.1 and if you have 
```json
"check_niantic_api": true
```
in your config, the bot will short out because it's risky to run.

So if your account is really dear to your heart, don't bot it. But if you want to try it out, change the config to
```json
"check_niantic_api": false
```

**Comment by hankmoody801** [comment]
@davidakachaos Whaalaa! David you're a genius! Thanks buddy! I added that bool to my config and everything is now working perfect! Much appreciated!

**Comment by MerlionRock** [comment]
@hankmoody801 We have fixed this issue. Please re-enable "check_niantic_api" back to true if you want some protection.
