### ISSUE TITLE
CAN NOT Set GEO Location

### ISSUE THREAD

**Issue by ShiFangJuMie** [PokemonGoF/PokemonGo-Bot#609]
### Expected Behavior
Go to the exact latitude and longitude

### Actual Behavior
Nearby place,But I can't get what I want.

For example: There are many Dratini in "-34.916767 138.595291", but “Memorial Drive Tennis Club War Memorial Dr Adelaide SA 5006” did not, Although the distance is not far.

### Steps to Reproduce
```
$ python pokecli.py -a google -u **** -p **** -l "-34.916767 138.595291"
2016-07-24 15:05:38 [x] PokemonGO Bot v1.0
2016-07-24 15:05:38 [x] Configuration initialized
[2016-07-24 15:05:40] 
[2016-07-24 15:05:40] [x] Address found: Memorial Drive Tennis Club War Memorial Dr Adelaide SA 5006
[2016-07-24 15:05:40] [x] Position in-game set as: (-34.9150856, 138.5994554, 0.0)
```

I have also tried these lists are not what I want
```
-l "-34.916767,138.595291"
-l "138.595291,-34.916767"
-l "138.595291 -34.916767"
```
AndI also deleted the location line in config.json

### Other Information
OS: OSX 10.11.5
Git Commit: stable form download zip

**Comment by reddivision** [comment]
I'm noticing this as well too recently. I think the issue is coord truncation. will look into it.

**Comment by ShiFangJuMie** [comment]
Maybe it's because config.json
I have now re installed the project, did not enable config.json, it seems to be right.

**Comment by surfaace** [comment]
location is set in config.json
