### ISSUE TITLE
[Cant install]

### ISSUE THREAD

**Issue by gagas3113** [PokemonGoF/PokemonGo-Bot#611]
I already finished install requirements.txt but cmd show pokecli.py: error: unrecognized arguments

**Comment by Aiyubi** [comment]
did you create and edit the config file?

**Comment by eggins** [comment]
@gagas3113 the readme is currently incorrect

**Comment by gagas3113** [comment]
readme only show [-h] and [-cf] no another command like -it -w

**Comment by gagas3113** [comment]
i think its cause protobuf doesn't install correctly, i only put protobuf to bot folder. any help ?

**Comment by reddivision** [comment]
currently, you have to use a config file _ONLY_, no other arguments are allowed (that's why you're getting `unrecognized arguments`). make a copy of `config.json.example` named `config.json`, fill it out with your information, and try running just `python pokecli.py`
