### ISSUE TITLE
[GymPokemon} Bot waits too long when waiting for deployment lockout

### ISSUE THREAD

**Issue by goedzo** [PokemonGoF/PokemonGo-Bot#6115]
Bot is waiting more then 30 minutes for this lockout ends:

[2017-07-23 17:17:15] [GymPokemon] [INFO] Arrived at Gym Metra LaSalle Street Station.
[2017-07-23 17:17:16] [GymPokemon] [INFO] Expecting team: 2 it is: 2
[2017-07-23 17:17:16] [GymPokemon] [INFO] Waiting for 00:05:04 deployment lockout to end...

Code to wait must be updated instead of freezing the bot for way too long.

**Comment by MerlionRock** [comment]
You want to code a simple workaround? Example in config add "max_lockout_min", if lockout more than specified, quit GymPokemon?

@davidakachaos any suggestion?

**Comment by davidakachaos** [comment]
Hmmm, strange, I believe I had a max of 10 minutes in place.... But I agree that part needs some more thinking a better way to handle it would be to just skip the wait if it's more than two minutes (it will drop off a certain list in the worker when the raid ends)
But more than 30 minutes?? Wow....

**Comment by goedzo** [comment]
I suspect the wait was caused by docker hanging, so closing issue for now.
