### ISSUE TITLE
Non stop asking to update pogo api to latest version

### ISSUE THREAD

**Issue by MerlionRock** [PokemonGoF/PokemonGo-Bot#6120]
This concern those on master Branch. Forked API updated to 1.2.1, please wait for master merge if you encounter error. #6119 

Else you can change pokecli.py line 69 from 1.2.0 to 1.2.1

**Comment by TheCannings** [comment]
You also need to change run.sh line 25

required=(`cat requirements.txt | sed -e 's/.*pgoapi$/pgoapi==1.2.0/' -e 's/[-_]//g' -e 's/==\(.*\)/:\1/' | awk '{print tolower($0)}'`)

to

required=(`cat requirements.txt | sed -e 's/.*pgoapi$/pgoapi==1.2.1/' -e 's/[-_]//g' -e 's/==\(.*\)/:\1/' | awk '{print tolower($0)}'`)

**Comment by MerlionRock** [comment]
@TheCannings Done, #6121

**Comment by Jcolomar** [comment]
Can we close this?

**Comment by MerlionRock** [comment]
Wait for it to be merge into master

**Comment by MerlionRock** [comment]
Merged. Closing.
