### ISSUE TITLE
Map is blank in the Stable branch

### ISSUE THREAD

**Issue by harsh1412** [PokemonGoF/PokemonGo-Bot#613]
### Expected Behavior

Show me the map :3
### Actual Behavior
The map doesn't load.. Its just blank with option bar and player info bar but nothing else..
I already configured the userdata.js and started http server.
Do i need to install anything else?
It was working before in the dev branch like a day or two before..

**Comment by reddivision** [comment]
make sure you have your google maps api key in config.json (see the `"gmapkey"` in `config.json.example`)

**Comment by harsh1412** [comment]
@reddivision so after filling up the config.json i can run the project without giving arguments?

**Comment by reddivision** [comment]
@harsh1412 that's correct. just run `python pokecli.py`

**Comment by harsh1412** [comment]
Thanks :)
