### ISSUE TITLE
[Suggestion] Use StreetView for live-maps

### ISSUE THREAD

**Issue by Balauue** [PokemonGoF/PokemonGo-Bot#614]
### Suggested Behavior

The map view provided in ``/web`` could have a switch to go into Street View mode, if available. In the best case, you would see the actual place the bot is currently wandering around. It should reflect the bots movements in real time. Might be especially interesting for landmarks such as the Central Park, Santa Monica Pier etc.

### Actual Behavior

The map view shows the map or satellite areal view.

**Comment by boriss579** [comment]
So.. not only you want the bot to walk for you, you also want to see the real places "he" is going :)
Interesting twist to the game :D

**Comment by surfaace** [comment]
web folder is now a seperate repo https://github.com/OpenPoGo/OpenPoGoWeb
