### ISSUE TITLE
Catch limiter makes bot stop moving

### ISSUE THREAD

**Issue by ChiefM3** [PokemonGoF/PokemonGo-Bot#6157]
### Expected Behavior
- When Catch limiter is initiated by `balls_on_hand < min_balls`, the bot should only stop catching and move around to collect balls.

### Actual Behavior
- Bot stops moving, so the bot cannot collect balls. This makes the bot fall in an infinite loop of 'Stop because you have no balls, because you have stopped no more balls'.

### Output when issue occurred
- `All catch tasks disabled until balls on hand (15) > threshold.` is output over and over again.

### Steps to Reproduce
- Set a high `min_balls` value for `CatchLimiter`

**Comment by MerlionRock** [comment]
Which Branch are you at right now? Dev or Master?

**Comment by davidakachaos** [comment]
This is very strange behavior. Can you share your config please? Maybe I can see something there.
I have set mine to 20 and do not experience this. "works for me"

**Comment by MerlionRock** [comment]
It works for me too. Weird....

**Comment by ChiefM3** [comment]
I am on dev branch. I will investigate further and report back. Thanks for the feedback!

**Comment by ChiefM3** [comment]
This is weird. I reset the bot location and the bot works fine. Closing.
