### ISSUE TITLE
all pokestop in range was already visited

### ISSUE THREAD

**Issue by dannickdannn** [PokemonGoF/PokemonGo-Bot#6163]
![capture](https://user-images.githubusercontent.com/30559660/28749154-24de38da-748c-11e7-91e2-006765d0471d.PNG)

**Comment by dannickdannn** [comment]
help me

**Comment by VoIP** [comment]
Appears your using RocketMaps. Have you tried waiting 4 minutes for it to reset the pokestops?

**Comment by dannickdannn** [comment]
is not that

**Comment by Jcolomar** [comment]
seems not be pokemongo-bot

**Comment by dannickdannn** [comment]
what do you mean ?it's pokemongo bot

**Comment by Jcolomar** [comment]
console is not the same, i see something about pokemaster?Rocketapi? What fork are u using?

**Comment by MerlionRock** [comment]
Wrong bot. Definitely wrong one. TO use our bot, please down see documentation: https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/installation.md or https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/manual_installation.md also visit us in discord if you need help with the bot
