### ISSUE TITLE
Update Usage in readme.md

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [PokemonGoF/PokemonGo-Bot#617]
Usage says we need to give parameters to pokecli.py, but that's not even possible anymore

**Comment by IcicleTF** [comment]
It seems that none of the flags are working anymore? Or is it just me?

**Comment by CtrlAltDefeat94** [comment]
Because you have to use a config file, and it doesnt seem to be documented anywhere how it works

**Comment by IcicleTF** [comment]
Alright, I see now.  Just have to delete the "example" off the end of the release_config.json and config.json.

**Comment by julienkessels** [comment]
yea should be updated.. and some functions are not added to the config file (like evolve etC) how do i still evolve in this case?

**Comment by surfaace** [comment]
should be updated now
