### ISSUE TITLE
Future Request - New badges data in inventory

### ISSUE THREAD

**Issue by Kijax** [PokemonGoF/PokemonGo-Bot#6188]
### Description
I did PR https://github.com/PokemonGoF/PokemonGo-Web/pull/130 which adds new badges. Now we need info for this badges in player inventory. Badges data that we need to add to inventory:
1) Kanto - now this is summary of all unique pokemons in pokedex. Should be only for Kanto region pokemons. Can be done by Kanto=Kanto-Johto.
2) Johto
3) Gym Leader
4) Berry Master
5) Champion
6) Legendary Pokemon
7) Unown - i'm not sure if this data is already in inventory.

**Comment by Jcolomar** [comment]
https://github.com/PokemonGoF/PokemonGo-Web/pull/130

Closed
