### ISSUE TITLE
 I can not install or I may not be. Want to help someone teach or install by teamviewer? Thank you very much.

### ISSUE THREAD

**Issue by mindgamemy** [PokemonGoF/PokemonGo-Bot#6189]
### Other Information
OS: 
 
Branch: 
 
Git Commit: 
 
Python Version: 
 
Any other relevant files/configs (eg: path files)

**Comment by Jcolomar** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/installation.md
or
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/manual_installation.md

also u can join our discord server ---> https://discord.gg/n3g5puF
