### ISSUE TITLE
Timezone issue - with requirements

### ISSUE THREAD

**Issue by goedzo** [PokemonGoF/PokemonGo-Bot#6196]
Got this error when trying to user timezones. After disabling try catch, the following error was shown:

ImportError: pytz must be installed in order to locate timezones.  Install with `pip install geopy -e ".[timezone]"`.

So we need to have this installed in requirements??

**Comment by goedzo** [comment]
Also I have no idea how to install this on windows:

G:\Setups\Pokemon Go\Bot\Pikabot\_git\PokemonGo-Bot\goedzo_windows>pip install geopy -e ".[timezone]"
Directory '.' is not installable. File 'setup.py' not found.

G:\Setups\Pokemon Go\Bot\Pikabot\_git\PokemonGo-Bot\goedzo_windows>pip install geopy
Requirement already satisfied: geopy in c:\python27\lib\site-packages

G:\Setups\Pokemon Go\Bot\Pikabot\_git\PokemonGo-Bot\goedzo_windows>pip install geopy -e "[timezone]"
[timezone] should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+

???

**Comment by goedzo** [comment]
Bingo!

pip install pytz

So we need to add pytz to requirements.txt

**Comment by goedzo** [comment]
I only have no clue what to add in requirements.txt :)

**Comment by MerlionRock** [comment]
Oh so sorry! I forgot to add that in!

Can help me? 

In requirements.txt add pytz==2017.2

**Comment by Jcolomar** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/pull/6197

**Comment by MerlionRock** [comment]
@jcolomar @goedzo thanks~

**Comment by MerlionRock** [comment]
Closing.

**Comment by Jcolomar** [comment]
u are welcome
