### ISSUE TITLE
How to watch Bot

### ISSUE THREAD

**Issue by lufthansa747** [PokemonGoF/PokemonGo-Bot#62]
> **My pokemon are not showing up in my Pokedex?**
> 
> Finish the tutorial on a smartphone. This will then allow everything to be visible.

The above is taken from the README. Is it possible to watch the bot operate?

**Comment by Boren** [comment]
Only by reading the output generated.

**Comment by CtrlAltDefeat94** [comment]
I just installed BlueStacks to watch whatever is going on
![eaeodrq 1](https://cloud.githubusercontent.com/assets/5640470/17036307/0d54a508-4f8c-11e6-8af1-a9927d6a1e98.png)

**Comment by dominikue** [comment]
You can login at your mobile Device and then look at your diary/stats. But i would deactivated the gps to avoid softbans - still on your on risk.

**Comment by dominikue** [comment]
@CtrlAltDefeat94 I got the same problem, that much Pokemons run away..

**Comment by CtrlAltDefeat94** [comment]
@dominikue apparently that's a bug that happens when pokestops are enabled. See #67
