### ISSUE TITLE
Optimizer is transferring (almost) everything!

### ISSUE THREAD

**Issue by camnomis** [PokemonGoF/PokemonGo-Bot#6202]
Spun up a new account to try out the [https://github.com/goedzo/pgoapi/tree/Test-AntiBan-2]Test-AntiBan-2(url), so also taking the opportunity to try and get to grips with Optimzer on an account I don't give a damn about.

This is my config:

` {
         "type":"PokemonOptimizer",
         "config":{
            "enabled":true,
            "bulktransfer_enabled":true,
            "max_bulktransfer":20,
            "min_slots_left":25,
            "action_wait_min":3,
            "action_wait_max":5,
            "transfer":true,
            "evolve":true,
            "debug":false,
            "evolve_to_final":true,
            "evolve_time":25,
            "evolve_for_xp":true,
            "evolve_only_with_lucky_egg":false,
            "evolve_count_for_lucky_egg":80,
            "may_use_lucky_egg":true,
            "may_evolve_favorites":true,
            "may_upgrade_favorites":true,
            "may_unfavor_pokemon":false,
            "upgrade":true,
            "upgrade_level":30,
            "groups":{
               "gym":[
                  "Dragonite",
                  "Snorlax",
                  "Lapras",
                  "Tyranitar",
                  "Rhydon",
                  "Gyarados",
                  "Golem"
               ],
    "my_love": [
         "Pichu",
         "Pikachu",
         "Raichu",
         "Lugia",
         "Articuno",
         "Zapdos",
         "Moltres",
         "Unown"
               ],
    "trash": [
        "!gym",
        "!my_love"
    ]
            },
            "rules":[
               {
                  "// Of all Pokemon with less than 124 candies, buddy the Pokemon having the highest maximum cp":{

                  },
                  "mode":"overall",
                  "top":1,
                  "sort":[
                     "max_cp",
                     "cp"
                  ],
                  "keep":{
                     "candy":-124
                  },
                  "evolve":true,
                  "buddy":true
               },
               {
                  "// Buddy the Pokemon having the less candies. In case no Pokemon match first rule":{

                  },
                  "mode":"overall",
                  "top":1,
                  "sort":[
                     "-candy",
                     "max_cp",
                     "cp"
                  ],
                  "evolve":false,
                  "buddy":true
               },
               {
               "// Keep All Gym & My_Love, evolve or update if iv is greater than 0.9":{

                  },
                  
                       "mode":"by_pokemon",
                  "names":[
                     "gym",
                     "my_love"
                  ],
                  "keep":true,
                  "evolve":{
                     "iv":0.9,
                     "ncp":0.9
                  },
                  "upgrade":{
                     "iv":0.9,
                     "ncp":0.9
                  }
               },
               {
                  "// Keep two best iv of each type and evolve it if its iv is greater than 0.9":{

                  },
                  "mode":"by_pokemon",
                  "names":[
                     "trash"
                  ],
                  "top":2,
                  "sort":[
                     "iv"
                  ],
                  "evolve":{
                     "iv":0.9
                  }
               },
               {
                  "// Keep best cp of each type but do not evolve it":{

                  },
                  "mode":"by_pokemon",
                  "names":[
                     "trash"
                  ],
                  "top":1,
                  "sort":[
                     "cp"
                  ],
                  "evolve":false
               },
               {
                  "// For Pokemon of final evolution and with iv greater than 0.9, keep the best two dps_attack":{

                  },
                  "mode":"by_pokemon",
                  "names":[
                     "!with_next_evolution"
                  ],
                  "top":2,
                  "sort":[
                     "dps_attack",
                     "iv"
                  ],
                  "keep":{
                     "iv":0.9
                  }
               }
            ]
         }
      },`

However pretty much everything is being transferred, I am assuming it's a problem with the config rather than a bug, but I just can't seem to get my head around the logic, I have turned on debugging and this is the log file

https://dl.dropboxusercontent.com/u/9125175/pokemon-optimizer.log

**Comment by Jcolomar** [comment]
Seems all good, but for sure the problem is in "trash" rule, remove it

**Comment by camnomis** [comment]
@Jcolomar yep that seems to have worked, not sure what i was trying to do with the trash group.

Evolve and transfer seems good, don't think I have got anything that meets the rules for upgrading yet (using it on my new test account rather than anything with anything actually good) so will keep an eye on that going forward
