### ISSUE TITLE
--initial-transfer doesn't work any more

### ISSUE THREAD

**Issue by tastypear** [PokemonGoF/PokemonGo-Bot#622]
`pokecli.py: error: unrecognized arguments: --initial-transfer`
Git Commit: ab604452c2a0a72e13fa6d940fa55902d3b01466

**Comment by surfaace** [comment]
you need to specify a minumum CP level with --initial-transfer

**Comment by reddivision** [comment]
the argument processing has been redone. you need to specify your initial transfer inside `config.json` now (see `config.json.example` for... an example). no arguments other than `-h` and `-cf` are currently supported on the command-line.

**Comment by tastypear** [comment]
so what does the argument `initial_transfer=0` mean? zero means False or CP limit?

**Comment by Naramsim** [comment]
It means CP limit as of now
@tastypear
