### ISSUE TITLE
Problem to run runMultiBot.sh

### ISSUE THREAD

**Issue by tokar86a** [PokemonGoF/PokemonGo-Bot#6235]
### Actual Behavior

https://pastebin.com/8iQHawN4

It dont help that i run ./setup.sh -u It still say the same thing.

### Output when issue occurred

https://pastebin.com/8iQHawN4

### Other Information
OS: Ubuntu
 
Branch: dev
 
Git Commit: 
 
Python Version: 2.7.13
 
Any other relevant files/configs (eg: path files)

**Comment by MerlionRock** [comment]
PR done for this issue #6237
