### ISSUE TITLE
Castform moves in pokemon.json

### ISSUE THREAD

**Issue by nemchik** [PokemonGoF/PokemonGo-Bot#6267]
### Expected Behavior

No errors when running the bot

### Actual Behavior

There bot displays errors that Castform moves after unrecognized. [Hex, Hurricane], [Hex, Energy Ball], and [Tackle, Hurricane].

### Steps to Reproduce

Just ran the bot for the first time ever today. I think I have multiple Castform and apparently the included pokemon.json doesn't have the moves listed. I added them myself and the error went away.

### Other Information
OS: Ubuntu server 17.10
 
Branch: Master
 
Git Commit: ccdcc5afd5f4b6d8f59f588ad8512c66a080ec46
 
Python Version: Python 2.7.14
 
Any other relevant files/configs (eg: path files)

**Comment by sleepypikachu** [comment]
This issue should be closed.
