### ISSUE TITLE
Webserver serves blank page

### ISSUE THREAD

**Issue by obi343** [PokemonGoF/PokemonGo-Bot#627]
Greetings,
after i set up script and webserver, i've reloaded nginx with 'nginx -s reload' and i can access localhost, but only thing there is blank space with options and trainer submenus. After clicking INFO box with 'Submenu' is showing up.

OS: Debian Sid
Git Commit: Sun Jul 24 01:15:16 2016

**Comment by surfaace** [comment]
you need to configure googleAPI key https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by obi343** [comment]
I've already did it, sir.

**Comment by surfaace** [comment]
if defining the key in config doesnt resolve it, change google API KEY to ours in index.html 97 line

**Comment by obi343** [comment]
Defined key in index.html and still all i have is: [http://i.imgur.com/n3bP2fQ.png](url)

**Comment by dotaxis** [comment]
Same issue here

**Comment by aditardy** [comment]
same problem  with nginx or SimpleHTTPServer ...

**Comment by dotaxis** [comment]
Make sure to edit userdata.js and add your username/email to it.

**Comment by obi343** [comment]
Changed username, still no result.

**Comment by yoyellow** [comment]
it should be ["user@email.com"]

**Comment by obi343** [comment]
Thank you kindly, Sir!
