### ISSUE TITLE
[Question] What is gmapkey for ?

### ISSUE THREAD

**Issue by YourATowel** [PokemonGoF/PokemonGo-Bot#628]
Sorry if wrong place.
What is gmapkey for? What does it do ?

I have not been using it and couldn't find what its purpose is.

**Comment by hahnrobert** [comment]
It's used when making use of the web interface which is available in dev branch. The idea is to not use one API key which will exceed its limits quite fast but instead every users uses their own one.

**Comment by YourATowel** [comment]
Thanks.
So is it just used for seeing your where your character is on the map ?

**Comment by eggins** [comment]
Only used for the webmap so that you can map where they are.
