### ISSUE TITLE
The bot is dead

### ISSUE THREAD

**Issue by Nesonica** [PokemonGoF/PokemonGo-Bot#6281]
I just read in your Discord that the bot is not working anymore. It is a pity that I had to find out this way, as I just bought hash keys for it.

**Comment by vish01** [comment]
@Nesonica  That sucks, sorry to hear that. I was about to get hash keys, but glad I read messages on Discord first. Are there any other bots that are working?

**Comment by Nesonica** [comment]
Sorry, I have no clue but I think rather not. Did Niantic not just lately close 500.000 accounts that hack?
