### ISSUE TITLE
[Pokemon Description] Map of location where the pokemon was captured is not displayed

### ISSUE THREAD

**Issue by apsdehal** [PokemonGoF/PokemonGo-Bot#630]
### Expected Behavior
Map of the location where pokemon was captured should be there in Pokemon's Description menu

### Actual Behavior
White image. (This may be used to catch botters)

### Steps to Reproduce
- Catch a pokemon through bot
- Go to pokemon menu
- Select the latest catched pokemon which open up the description menu.
- Scroll down and check out the capture map location for the pokemon.

### Other Information
OS: Ubuntu 14.04.4 GNOME
Git Commit: 7009a4a4e643d42df39125d1262a7715bb3501a1

**Comment by vtuan10** [comment]
this is because of the "3 steps bug" and has nothing to do with the bot.

**Comment by apsdehal** [comment]
Thanks, confirmed. Closing.
