### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by loqento** [PokemonGoF/PokemonGo-Bot#6302]
I’d like to make a request for a feature to auto complete rocket battles when passing by a go rocket stop. This would make for way easier auto farming/stardust farming and allow users to use that stardust to power up their costly Pokemon. I hope you choose to integrate it into your project if possible. Thanks if you read through.

**Comment by ohrip** [comment]
Is this thing actually working?

**Comment by Jasperrr91** [comment]
> Is this thing actually working?

No it's not, this project hasn't been maintained for almost 5 years now.
