### ISSUE TITLE
How to make pokemon bot

### ISSUE THREAD

**Issue by Subroop** [PokemonGoF/PokemonGo-Bot#6312]
Hi

**Comment by Rdallen1** [comment]
Hello

**Comment by Rdallen1** [comment]
??

**Comment by Rdallen1** [comment]
I do apologize for the tardiness.

**Comment by oralunal** [comment]
This project has been abandoned.

**Comment by Jasperrr91** [comment]
Indeed, we haven't had any activity for almost 5 years as Niantic had securely patched their servers, shutting down our entry points.

As far as I know, the only available options are applications that run on rooted mobile devices so they can directly interact with the official Pokemon Go application..
