### ISSUE TITLE
Scanning area and walking hook

### ISSUE THREAD

**Issue by ayozebarrera** [PokemonGoF/PokemonGo-Bot#636]
Hi.. after few minutes, I only see how the bot scan area for objects and walking hooks. No pokemons found... no pokemons appears... am I doing any wrong?

**Comment by reddivision** [comment]
plug your coordinates into google maps, look up the location on pokevision.com, and see if there are even any pokemon where your bot is. it's not uncommon to not see any pokemon depending on where you are at.

**Comment by surfaace** [comment]
please do as @reddivision mentioned and if you see that there infact is pokemons in the area, printscreen and open a new ticket
