### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by sevano** [PokemonGoF/PokemonGo-Bot#640]
I cloned the latest PokemonGO-bot 
Installed the requirements and virtualenv 
I changed release_config.json and config.json 
When i run i get this error

```
File "pokecli.py", line 219, in <module>
    main()
  File "pokecli.py", line 196, in main
    config = init_config()
  File "pokecli.py", line 168, in init_config
    config.item_filter = [str(item_id) for item_id in config.item_filter.split(',')]
AttributeError: 'list' object has no attribute 'split'

```

**Comment by reddivision** [comment]
Make sure that in `config.json` your `item_filter` key just has a string value of integers separated by commas. 

Example: `"item_filter":"101,102,103,104"`

**Comment by sevano** [comment]
Thanks Solved
