### ISSUE TITLE
[Suggestion] Command for changing region

### ISSUE THREAD

**Issue by GanbaruTobi** [PokemonGoF/PokemonGo-Bot#645]
As people will want to get region based Pokemon, it would be nice to provide a way to change the region. There probably needs to be an off time in game, which could be handled with a timer. Further i don't know if a proxy for the Internet connection will be needed. This could be mentioned in the Console.
When the times are known as same for every region, changing it could be done by:
-mv "NA"
When they are different:
-mv "EU" -to "NA"
        or
-mv "EU" "NA"

Here two links to region based Pokemon:
[http://www.ew.com/article/2016/07/18/pokemon-go-continents-exclusive](http://www.ew.com/article/2016/07/18/pokemon-go-continents-exclusive)
[http://www.eurogamer.net/articles/2016-07-22-pokemon-go-region-exclusive-pokemon-locations-how-and-where-to-catch-tauros-kangaskhan-mr-mime-and-farfetchd](http://www.eurogamer.net/articles/2016-07-22-pokemon-go-region-exclusive-pokemon-locations-how-and-where-to-catch-tauros-kangaskhan-mr-mime-and-farfetchd)

**Comment by fonix232** [comment]
Just set a position, and you're good to go. Of course wait the usual 30min-1hr cooldown between large position jumps (this definitely counts as large!), unless you want to get softbanned.

**Comment by surfaace** [comment]
if you 'teleport' to aisa you will be on their servers? ofc depending on time since servers had your last location you can get softbanned
