### ISSUE TITLE
Error when start: ImportError: No module named smbus

### ISSUE THREAD

**Issue by gmkbenjamin** [PokemonGoF/PokemonGo-Bot#647]
### Actual Behavior
Traceback (most recent call last):
  File "pokecli.py", line 46, in <module>
    from pokemongo_bot import lcd
  File "C:\Users\user\Desktop\PokemonGo-Bot\pokemongo_bot\lcd.py", line 14, in <module>
    import smbus
ImportError: No module named smbus

### Steps to Reproduce
Run python pokecli.py

### Other Information
OS: Widnows 10 64bit
Git Commit: 4aea4b278181d71b6e22feaa038f568fe2b211df

**Comment by zx900930** [comment]
Same problem here and because smbus is build for linux, we cant install it with `pip install smbus-cffi` on windows.

**Comment by r3fl0g** [comment]
I2C support broke the current build. In Linux based systems install the i2c-tools package and it should be fixed.

**Comment by pol0nium** [comment]
The package doesn't exist in homebrew. This dependency is an issue for OSX users.

**Comment by Tekill** [comment]
Fixed by https://github.com/PokemonGoF/PokemonGo-Bot/commit/1624e5ee3669edd665e76718eef2b30a6b7ab21b
