### ISSUE TITLE
Pokemons ran away

### ISSUE THREAD

**Issue by ulou** [PokemonGoF/PokemonGo-Bot#65]
Hello, only I have problem, that all pokemons ran away? (I can see this in Journal in app)

**Comment by Imbos** [comment]
Are you still able to collect items from pokestops?
maybe its a temporary ban.

**Comment by ulou** [comment]
Yeah, Its looks that I got ban soft-ban for 1h (I have been using -s). Now ban expired and again after 5 pokestops on -s cant use it anymore and all pokemons ran away.

**Comment by Imbos** [comment]
hmm. maybe adding a delay after collecting from a stop will help with that?

**Comment by ulou** [comment]
Yeah, I guess there is a delay in PokeGo, something like "You can use max 5 pokestops in 30s", if you use more you getting ban.

**Comment by Imbos** [comment]
i just downloaded the latest version and its not catching anything even without -s

checked and not soft banned. 
can you stil catch pokemon without -s?

**Comment by ulou** [comment]
If all pokemons ran away (even without bot) and spining pokestops doesnt give you items, you are soft-banned.

**Comment by Imbos** [comment]
yeah but i do get items from pokestops

**Comment by s1x** [comment]
@lmbos If you have still any issues please open a new one. However it really seems like you are softbanned.
