### ISSUE TITLE
[BUG] Bot neither uses greatballs when out of pokeballs nor switches to farm mode

### ISSUE THREAD

**Issue by ckrmml** [PokemonGoF/PokemonGo-Bot#660]
### Expected Behavior

No more pokeballs but more than ten greatballs, bot should use greatballs

### Actual Behavior

2016-07-24 13:51:10] [#] A Wild Voltorb appeared! [CP 223] [Potential 0.42]
[2016-07-24 13:51:10] [#] IV [Stamina/Attack/Defense] = [14/2/3]
[2016-07-24 13:51:13] [x] Using Pokeball (chance: 45.14%)... (-1 left!)

### Steps to Reproduce

just run the bot

### Other Information
OS: OSX
Git Commit: ee730249167e4d6d28191e4c36c819fe29652dad

**Comment by earthchie** [comment]
will fix in this PR
https://github.com/PokemonGoF/PokemonGo-Bot/pull/655

**Comment by xskeeperx** [comment]
same bug here.
need to merge that PR!

**Comment by solderzzc** [comment]
Commented on #655. We was on CI situation yesterday, now CI and PullApproval works.
