### ISSUE TITLE
Evolve all not working

### ISSUE THREAD

**Issue by Foxy1990** [PokemonGoF/PokemonGo-Bot#663]
### Expected Behavior
	"evolve_all": true 

should evolve all pokemons on startup

### Actual Behavior
doesnt evolve anything :/

### Steps to Reproduce
use "evolve_all": true in config

### Other Information
OS: win10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Witzbold** [comment]
Same problem here. Seems like the value "evolve_all" isn't even red by the program.

OS: ubuntu

**Comment by surfaace** [comment]
please test with latest dev branch, also paste in git commit if issue persist

**Comment by hoangnn89** [comment]
> commit 149a357347276e3910d023732d4fb492397438db

 > "evolve_all": "Pidgey,Weedle,Caterpie,Rattata"

nothing happen...

**Comment by Witzbold** [comment]
for me the all function worked
