### ISSUE TITLE
Release_config not work at all

### ISSUE THREAD

**Issue by crusardri** [PokemonGoF/PokemonGo-Bot#664]
### Expected Behavior

Transfer pokemons with CP lower than X and IV lower than Y

### Actual Behavior
Console:
[2016-07-24 14:09:43] [x] Captured Primeape! [CP 950] [IV 0.58]
[2016-07-24 14:09:43] [x] Captured Primeape! [CP 950]
release_config.json
"Primeape": { "release_under_cp": 900, "release_under_iv": 1, "cp_iv_logic": "and" },
In-game
![image](https://cloud.githubusercontent.com/assets/4596106/17083724/14bdedda-51a9-11e6-979a-fe41a261deac.png)
### Steps to Reproduce
Start the bot lol
### Other Information
OS: Windows 10
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Last dev downloaded a few minutes ago. (Seriously, i don't know how i can use git command)

**Comment by Witzbold** [comment]
You chose the option AND which means:

 [CP 950] [IV 0.58]
if(CP<900 AND IV<1):
     release
since CP>900 the result will be false

**Comment by surfaace** [comment]
No issue, your config specifes that both CP and IV pokemon values needs to be true in order to transfer it

[2016-07-24 14:09:43] [x] Captured Primeape! [CP 950] [IV 0.58]
[2016-07-24 14:09:43] [x] Captured Primeape! [CP 950]
release_config.json
"Primeape": { "release_under_cp": 900, "release_under_iv": 1, "cp_iv_logic": "**and**" },

**Comment by earthchie** [comment]
but still, kinda confuse.

He want to hunt CP 900+ Primeape with IV potential = 1
How to config then?

We should improve this logic

**Comment by crusardri** [comment]
in my config say
Don't transfer a primeape with 900 or more AND IV 1 or more, and the bot don't transfer a primeape 950 (OK) with IV 0.58 (not OK)

**Comment by surfaace** [comment]
i see that you are right, do 0.99 until its fixed :)

**Comment by crusardri** [comment]
still not working with AND and IV 0.99, but work fine with OR

**Comment by douglascamata** [comment]
```
[2016-07-24 14:09:43] [x] Captured Primeape! [CP 950] [IV 0.58]
[2016-07-24 14:09:43] [x] Captured Primeape! [CP 950]
release_config.json
"Primeape": { "release_under_cp": 900, "release_under_iv": 1, "cp_iv_logic": "and" },```

This means: `if cp < 900 AND iv < 1 THEN release`

**Comment by crusardri** [comment]
In that case, the release config is broken, the primeape is 950, OK but the IV is lower than 1

**Comment by mehdi-S** [comment]
for me it seems that _release_config.json_ is never used with the new `-cf config.json` logic

**Comment by douglascamata** [comment]
@crusardri dude... it's a logic AND. It's working as expected. `if cp < 900 AND iv < 1 `. CP is less than 900? False. IV is less than 1? True. `False AND True = False`,  so it won't release. Nothing is broken, it's boolean math.

**Comment by crusardri** [comment]
Math logic:
OR
0 0 = 0
0 1 = 1
1 0 = 1
1 1 = 1

AND
0 0 = 0
0 1 =0
1 0 = 0
1 1 = 1

Pokemon used: Primeape PC 950 (>900) IV 0.58 (<1)
[2016-07-24 14:09:43] [x] Captured Primeape! [CP 950] [IV 0.58]
My config
"Primeape": { "release_under_cp": 900, "release_under_iv": 1, "cp_iv_logic": "**and**" },
Expected Behavior
if primeape is PC >900 AND IV >1, keep
Actual Behavior
if primeape is PC >900 OR IV >1, keep

**Comment by douglascamata** [comment]
@crusardri: 

1. IV condition is `False` and CP condition is `True`, right? Agree on this?
2. `False AND True` is `False`
3. Returning `False` means it SHOULD NOT transfer.

**Comment by douglascamata** [comment]
With this configuration you're only keeping in your Pokemon list whatever has CP higher than 900 and IV 1 (IV 1 is almost impossible to find).

**Comment by douglascamata** [comment]
Just check the code, it's clear:

```
if 'release_under_cp' in release_config:
                min_cp = release_config['release_under_cp']
                if cp < min_cp:
                    release_results['cp'] = True
```

Transforming into text: if pokemon cp is lower than `'release_under_cp'`, it should be released based on that criteria. Same happens to IV. 

Your pokemon CP = 950 and IV = 0.58, config is CP 900 and IV 1.

950 < 900 = FALSE
0.58  < 0.1 = TRUE

`False AND True` = False = not release.

**Comment by crusardri** [comment]
ahhh, ok, i understand now, but it don't have any sense.
Why the config is for transfer instead of keep it?

**Comment by douglascamata** [comment]
The file is named **release**_config.json and the name of the key is **release**_under_cp...

**Comment by douglascamata** [comment]
IMHO, it's pretty clear what it means.

**Comment by mehdi-S** [comment]
@douglascamata and how did you manage to use release_config file with the config_file logic ?

**Comment by crusardri** [comment]
Ok, it's my fault, close the issue if you want.
@mehdi-S 
release when the pokemon have PC lower than X and IV lower than Y, or release when the pokemon have PC lower than X or IV lower than Y

PC is 950 and IV is 0.58
the config says PC 900 and IV 1
950 > 900 = false
0,58 < 1 = true
OR = X + Y
AND = X * Y

OR: false + true = true, release it
AND: flase * true = false, keep it

**Comment by douglascamata** [comment]
@mehdi-S I don't know about config_file logic + release_config.json file. I implemented the release_config.json logic before the config_file one. I just woke up a few minutes ago and saw it there, so...
