### ISSUE TITLE
[Bug] Initial Transfer is transfer all my Pkmn regardless of CP

### ISSUE THREAD

**Issue by earthchie** [PokemonGoF/PokemonGo-Bot#666]
### Expected Behavior
Keep Pokemon with CP > config.

### Actual Behavior
![image](https://cloud.githubusercontent.com/assets/7013039/17083842/aaa77ffa-51d6-11e6-9fcb-bc55ea62ee8b.png)

### Steps to Reproduce
Run bot until pokemon bag is full

**Comment by ulou** [comment]
Can you paste what you write in console? (delete username and password)

**Comment by earthchie** [comment]
It has something to do with this line

https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/initial_transfer_worker.py#L33

self.config.initial_transfer is False
because I set it to False, but this method called because my bag full.

We have 2 choices:
1. not trigger initial_transfer if self.config.initial_transfer is False
https://github.com/earthchie/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/pokemon_catch_worker.py#L37

2. trigger but set self.config.initial_transfer to True before initial_transfer

**Comment by ethervoid** [comment]
It seemm like you have more than one Charmaleon and with that option you keep the Charmaleon with highest CP.

**Comment by earthchie** [comment]
@ethervoid that's not the problem. 

Will NOT transfer anything above CP 0?

BAM! Transferring Charmeleon with CP 701

I went to check the code and it really a bug. I already made PR to fix this too.
