### ISSUE TITLE
[BUG] Bot evolves pokemon, then releases them

### ISSUE THREAD

**Issue by ckrmml** [PokemonGoF/PokemonGo-Bot#669]
### Expected Behavior

Release pokemon not matching release_config and evolve only pokemon beeing kept

### Actual Behavior

[2016-07-24 15:02:19] [#] Spearow has been evolved!
[2016-07-24 15:02:19] [x] Release config for Spearow: CP 500 or IV 0.8
[2016-07-24 15:02:19] [#] Spearow has been exchanged for candy!

### Steps to Reproduce

run the bot with "evolve_captured": true in config.json
### Other Information
OS: OSX
Git Commit: ee730249167e4d6d28191e4c36c819fe29652dad

**Comment by Aiyubi** [comment]
I don'T see where the error is:
You catch Spearow
You have evolve captured enabled so it gets evolved
its values are too low so it gets released

**Comment by ckrmml** [comment]
Which would make sense if the pokemon would be kept, not if it gets released. 
1) capture
2) check release config
3) release or keep
4) evolve if kept
is the way this would make any sense.

**Comment by dmateusp** [comment]
@ckrmml no, the behavior is as described by @Aiyubi . The logic here is to use evolve to gain XP, so if you have enough candy even weak pokemons get evolved so you earn XP and then they get released
