### ISSUE TITLE
-s bugged?

### ISSUE THREAD

**Issue by crack00r** [PokemonGoF/PokemonGo-Bot#67]
It seams, even on walking  (-w 4.16) and -s for spinning bot get banned...
without -s it catches pokemons en mass, but as soon i add -s the bot only spins, and no pokemons anymore

**Comment by Apoloser** [comment]
THats true, with -s bot doesnot catch pokemons, only spins pokestops

**Comment by douglascamata** [comment]
I was using using `-s` and it caught some pokemons. I started using today, used for a few hours and not banned yet.

**Comment by Apoloser** [comment]
It was working fine, until some update.

**Comment by vincesmits** [comment]
can confirm this issue

**Comment by ulou** [comment]
confirm

**Comment by CapCap** [comment]
Can confirm as well. I believe problem is caused by the fort loop in bot.py, will try to work on it if I have time (on vacay right now)

**Comment by crack00r** [comment]
Any news?

**Comment by douglascamata** [comment]
Does it still happen? Some code was pushed today to master to fix this.

**Comment by crack00r** [comment]
Yep, latest Master still no pokemons on - s

**Comment by s1x** [comment]
@crack00r Please reopen an issue if this error still occurs with either the master or dev branch!
Thank you!
