### ISSUE TITLE
[Feature request] Prioritize rare pokemon

### ISSUE THREAD

**Issue by JohanJu** [PokemonGoF/PokemonGo-Bot#672]
Include a list of rare pokémon that will be pursued with highest priority if in range.

In the future maybe a hunter-catcher setup where the main account catches pokémon and secondary accounts jumps in a grid pattern to find rare pokémon.

**Comment by ththompson** [comment]
An extension (or base setting) could be to prioritise uncaught Pokemon.

**Comment by surfaace** [comment]
define what you mean with 'pursued'

**Comment by JohanJu** [comment]
@surfaace Say that there are a mew, 5 pokestops and 5 other pokémon visible. Then the bot should raise speed to maximum without ban (40m/s?) and try to catch that mew before trying to catch other pokémon or spin pokestops.

**Comment by CapCap** [comment]
mostly exists in current dev
