### ISSUE TITLE
[QUESTION] IV and CP?

### ISSUE THREAD

**Issue by Roydeking52** [PokemonGoF/PokemonGo-Bot#685]
How do i capture pokemon i want, it always trade them for candy.
Can somebody explaine to me how the release_config file work.

I wanted new pokemon but because theye are to "low" the bot is trading them for candy.

Is there a way to not look at IV only at the CP level?

**Comment by Aiyubi** [comment]
Explanation in pseudocode:
```
If pokeIV < configIV KEYWORD pokeCP < configCP:
    release
else:
    not release
```

So if you just want to look at CP and ignore IV: Set all IV values to 0.0

**Comment by Roydeking52** [comment]
Thank you its working :)
