### ISSUE TITLE
Fix the submodule url to not use SSH

### ISSUE THREAD

**Issue by Diskmaster** [PokemonGoF/PokemonGo-Bot#690]
### Expected Behavior
git submodule to sync the web repository without issue. (Not everyone has SSH or an account)

### Actual Behavior
It fails, specifically about a lack of pubkey, but that would require forking and setting up your own repo variant, which isn't ideal for submodules.

### Steps to Reproduce
git submodule init
git submodule sync
watch as it complains about a missing pubkey if you don't have one

### Other Information
OS: Win7 64bit
Git Commit: bc70cdc3b

Suggested fix, probably not ideal as my experience with this feature isn't in depth.
git rm web
git submodule add https://github.com/OpenPoGo/OpenPoGoWeb.git web

**Comment by surfaace** [comment]
fixed in merge #708

**Comment by Diskmaster** [comment]
Thanks.
