### ISSUE TITLE
WebServer Map 

### ISSUE THREAD

**Issue by ltotsas** [PokemonGoF/PokemonGo-Bot#691]
Trying to setup the webserver but every time the username is wrong and i get

127.0.0.1 - - [24/Jul/2016 19:30:46] code 404, message File not found
127.0.0.1 - - [24/Jul/2016 19:30:46] "GET /location-larrougos.json HTTP/1.1" 404 -
127.0.0.1 - - [24/Jul/2016 19:30:46] code 404, message File not found
127.0.0.1 - - [24/Jul/2016 19:30:46] "GET /catchable-larrougos.json HTTP/1.1" 404 -

The username in Bot config is the same!

**Comment by Aiyubi** [comment]
so look at the folder what the filenames are - thats what you need to put in as username

**Comment by ltotsas** [comment]
inside the folders of the bot the username for example is "tarto", if i use the same username inside the web folder of the map config it does not work

**Comment by Aiyubi** [comment]
can you show the python output and userdata.js ?

**Comment by nvhk** [comment]
Yes, the same problem. my config is correct.

 [24/Jul/2016 23:06:33] code 404, message File not found
 [24/Jul/2016 23:06:33] "GET /location-xqsdvhk1.json HTTP/1.1" 404 -
 [24/Jul/2016 23:06:33] code 404, message File not found
 [24/Jul/2016 23:06:33] "GET /catchable-xqsdvhk1.json HTTP/1.1" 404 -

**Comment by Aiyubi** [comment]
if you want help I will need:
* "ls" in the directory to see what files
* the userdata.js to see what username is written in there
* the console output to see what filename it is failing on

If you want to check yourself - it should always be the same.

As for the last report here it should be:
* a file named "location-xqsdvhk1.json" in the web directory
* the user "xqsdvhk1" in the userdata.js
* the request for [24/Jul/2016 23:06:33] "GET /catchable-xqsdvhk1.json HTTP/1.1" in the terminal window

**Comment by nvhk** [comment]
Ok, problem solved.
If i use gmail account, i need put in userdata.js my whole email adress name@gmail.com

**Comment by ltotsas** [comment]
well, as i have played with the username the following results appear.
for start i had the same username as inside the bot folder aka "larrougos@gmail.com"
var users = ["larrougos@gmail.com"];
the errors i got was : 
127.0.0.1 - - [24/Jul/2016 19:30:46] code 404, message File not found
127.0.0.1 - - [24/Jul/2016 19:30:46] "GET /location-larrougos.json HTTP/1.1" 404 -
after that i tried to remove the array and use it as a simple variable
var users = "larrougos@gmail.com";
the erros i got was the same as the other guy said : 
[24/Jul/2016 23:06:33] code 404, message File not found
[24/Jul/2016 23:06:33] "GET /location-xqsdvhk1.json HTTP/1.1" 404 -
[24/Jul/2016 23:06:33] code 404, message File not found
[24/Jul/2016 23:06:33] "GET /catchable-xqsdvhk1.json HTTP/1.1" 404 -
in the end i simple just used the same as in the first place and it worked nothing more nothing less

**Comment by kilabyte** [comment]
Ive tried all the options above. Ive put my gmail email into the array and i still get... 
![screen shot 2016-07-24 at 3 13 48 pm](https://cloud.githubusercontent.com/assets/487948/17086843/3cd8f910-51b1-11e6-953a-3957e7ca1a13.png)

I can't see to find any file that has the location-XXXX or the catchable-XXXX. Am i suppose to have debug mode ON on the bot?

**Comment by Devsome** [comment]
I got the same problem as @kilabyte . I can't find any of location-NAME or catchable-NAME in the folder.

**Comment by kilabyte** [comment]
@Devsome are they just empty files with that naming convention?

**Comment by Leondoingstuff** [comment]
nope they constantly update

**Comment by Leondoingstuff** [comment]
although should probably automatically write those files if they're not already there

**Comment by Doc5az** [comment]
same here,its not automatically generate in web folder.

**Comment by brumie** [comment]
inventory-USER.json and catchable-USER.json are generated
only location-USER.json is not generated

master

**Comment by Doc5az** [comment]
@brumie
true but,if you create manually the location-USER.json file is work again.
when i'm trying to another name config file its didnt work even try to create manually the files.

**Comment by Mordana** [comment]
Same behaviour for `data/last-location-%s.json` 
Will not be auto-generated, but will update as soon as you create it manually

**Comment by surfaace** [comment]
web folder is not included by this code. its a seperate git repo (https://github.com/OpenPoGo/OpenPoGoWeb by default)

**Comment by jaerak** [comment]
@surfaace 
Thanks!
Can updated instructions be pushed to the readme?
