### ISSUE TITLE
travis cant pull submodules

### ISSUE THREAD

**Issue by mercuriete** [PokemonGoF/PokemonGo-Bot#695]
Something happen when travis is trying to pull a submodule (clone --recursive)
this probably happen because you are using ssh key instead of https or http autentication

### Expected Behavior
pull request ok

### Actual Behavior
travis is saying all pull  request are bad

### Steps to Reproduce
1) do a pull request
2) your pull request is rejected by travis

### Other Information

See this example: https://travis-ci.org/PokemonGoF/PokemonGo-Bot/builds/147009614

**Comment by mercuriete** [comment]
Sorry, duplicate of this bug:

https://github.com/PokemonGoF/PokemonGo-Bot/issues/690

**Comment by surfaace** [comment]
fixed in merge #708
