### ISSUE TITLE
Help me install somebody I did everything except I couldn't understand how to get to install protobuf 

### ISSUE THREAD

**Issue by ssm34** [PokemonGoF/PokemonGo-Bot#696]
What exactly did they mean by "PATH" on the Readme in the protobuf section for Windows

**Comment by mercuriete** [comment]
windows path environmental variable:
http://www.computerhope.com/issues/ch000549.htm

google is your friend :)

enjoy the bot :smile:

**Comment by ssm34** [comment]
Thanks for the help. I put the .exe in the PATH folder and still nothing. Could you walk me through the whole process if possible?

**Comment by zx900930** [comment]
@ssm34  

1. You need to unzip the protoc-3.0.0-beta-4-win32.zip and add the folder path (for example: `C:\protoc-3.0.0-beta-4-win32\bin` , make sure the protoc.exe is in the bin folder )to the windows PATH environmental variable. 
 
2. Reopen Command prompt window and done.

**Comment by gmkbenjamin** [comment]
Weird. It was working fine before even without protobuf installed now it complains I don't have it installed even though I do and I have it in PATH. I can even execute it directly from command prompt.

Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "C:\Users\user\Desktop\pg\PokemonGo-Bot\pokemongo_bot\__init__.py", line 14, in <module>
    from pgoapi import PGoApi
  File "c:\users\user\desktop\pg\pokemongo-bot\src\pgoapi\pgoapi\__init__.py", line 17, in <module>
    raise PleaseInstallProtobufVersion3()
pgoapi.exceptions.PleaseInstallProtobufVersion3

OS: Windows 10 64bit
Commit: 6bc4b168c26d876d9981f01f3a1bdd3b80fc3e16

**Comment by ssm34** [comment]
Okay so I just decided to dump google and use my Ubuntu installation instead. So now I'm set up, I configured my PTC account. But what location does it take? Lat and Long right? And how to execute it? $python pokecly.py ?
