### ISSUE TITLE
Feature request: Logging to a file

### ISSUE THREAD

**Issue by BartKoppelmans** [PokemonGoF/PokemonGo-Bot#698]
_Not an issue, just a quick question/feature request:_

Is it, or could it be, possible to log the log to a file. Right now it has a limited log on the command prompt, but I would like to leave it running for a night or so. Then, in the morning, I would like to see what it has done or found.

Cheers,
Bart

**Comment by d0t1q** [comment]
If you're just running it via linux just redirect the output

./app.py [options(using -v] | egrep  '(Walking|Found|appeared|vanished|Caught)' > output.log

easy walk around until we get actual log output
