### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by crack00r** [PokemonGoF/PokemonGo-Bot#7]
Incubate eggs - free Pokemons
Human walking logic -  for eggs
Use Stardust for level Pokemons
Use Candy on 50+ for level pokemons

**Comment by necrozis** [comment]
put all huge "json" prints to debug
print catched pockemon name ( can use [https://github.com/AHAAAAAAA/PokemonGo-Map/tree/master/locales](url)?) with CP

**Comment by surfaace** [comment]
Human walking logic - Done

**Comment by surfaace** [comment]
All suggestions has been added in 'TODO' on readme.md file
