### ISSUE TITLE
[Suggestion] show Player info on key press combination

### ISSUE THREAD

**Issue by diordache** [PokemonGoF/PokemonGo-Bot#70]
1. Every step the number of pokemons in inventory(maybe their type and CP) could be listed, also the items and count.
2. The CP of the pokemons discarded could be computed every step, so that pokemons are tranfered just to make room for new ones. (suggestion: discard 20 pokemons if free space in inventory is lower than 10)

**Comment by diordache** [comment]
#78

**Comment by diordache** [comment]
Created a pull request for (1) #78

**Comment by surfaace** [comment]
is this still viable? taking in account if something like #55 is added, you can 'interrupt' or some other key combination to show your stats /inventory status

**Comment by dmateusp** [comment]
Printing that much information at each step would be flooding, as in the current version most of the information is given when it changes ( when a pokeball is thrown) when something is recycled etc..

My opinion is having a key combination to print startup information

**Comment by surfaace** [comment]
key combo should definitly be the way to go

**Comment by gregtampa** [comment]
Use the web/map feature to check or send killsig 6
