### ISSUE TITLE
[Feature Request] Restart bot after X minutes,

### ISSUE THREAD

**Issue by koper89** [PokemonGoF/PokemonGo-Bot#703]
Having a possiblitiy in settings to restart the bot every X minutes would be really nice. Or after Xminutes after last catched pokemon.

**Comment by MikeDX** [comment]
Why would you want to do that?

**Comment by koper89** [comment]
To mitigate crashing risk.

**Comment by MikeDX** [comment]
If the script crashes, it has crashed and the process is ended, so it cannot restart itself.

**Comment by jessebinken** [comment]
I think what he means is to mitigate the "Unknown Pokestop" loop with this feature request.

**Comment by MikeDX** [comment]
I think so too, but that would be an awful way of achieving the fix if so.

**Comment by LostDGod** [comment]
Ideally every bug would be solved but unpredictable crashes can still happen anytime (so far it hasn't happened to me).
To solve this you could easily make an autohotkey script that checks for the process every X minutes and if the process doesn't exist, it starts it anew.

**Comment by phupabegim** [comment]
Use `crontab`. 

`*/5 * * * * timeout 5m python /home/user/bot/pokecli.py`

**Comment by Fak3Tales** [comment]
i have mine in a service in ubuntu and then restart the service every hour via cron.

**Comment by koper89** [comment]
Yep I think I'll make cron to handle those. I think this issue can be deleted.

Regards,
koper89

**Comment by Fak3Tales** [comment]
@koper89 i think you can mark this as closed.

**Comment by inerba** [comment]
This command restart the bot every 1 hour, after a pause of 10 secs

`while true; do timeout -k 1h -s SIGINT 1h python /home/user/bot/pokecli.py; sleep 10; done`

**Comment by dominikue** [comment]
@phupabegim @inerba 
How i use crontab with screen to run 2 bots with an ubuntu server?

thats what i got, but i think it didnt work:

`0 */2 * * * /usr/bin/screen -dmS catchthemall7fun /home/Pokemon-Go-Bot/ python pokecli.py -a ptc -u USER -p PASS --location "New York, Central Park" -m all`

How can close the other screen session  and let it wait 5 min to the next restart ?
I didnt use the latest dev.
