### ISSUE TITLE
[BUG] Cannot change to pokeball farm mode

### ISSUE THREAD

**Issue by bimahp** [PokemonGoF/PokemonGo-Bot#711]
> [#] A Wild Zubat appeared! [CP85]
[x] Out of pokeballs...
[x] Farming pokeballs...
[x] Found pokemon at distance 350.525627638m
[#] Walking from (-33.86571104319641, 151.20992542865255) to (-33.86571104319641, 151.20992542865255) for approx. 0.0 seconds
[#] Finished walking to (-33.86571104319641, 151.20992542865255)
[x] Walked to Pokemon
[#] A Wild Zubat appeared! [CP85]
[x] Out of pokeballs...
[x] Farming pokeballs...
[#] Walking from (-33.86571104319641, 151.20992542865255) to (-33.866319700000005, 151.2117955) for approx. 75.0 seconds

Somehow it skips pokeball farming so when my pokeball is running out, it can't catch anything anymore.
Is this related with #693?

**Comment by phupabegim** [comment]
To speed it up switch to `farm` mode, that helped in my case. Once I had built up balls then I switched back to `all` mode and now it does both weirdly.

**Comment by sebyx07** [comment]
there is no farm mode on the master branch
i have problems when i try to run from the dev branch, the params parsing is not working

**Comment by bimahp** [comment]
yeah param parsing not working on my mac too but runs well on windows, dunno what happened.
there is no farm mode on master, but i think farm is working fine on dev branch now

**Comment by skydrome** [comment]
you can try this to speed up switching back to capturing, instead of waiting for a full inventory it waits for at least 40 pokeballs then continues
https://github.com/skydrome/PokemonGo-Bot/commit/9a2b4c1a47818ee298258d9c9f60d09659f4a78c

**Comment by surfaace** [comment]
PR #655, issue #660
