### ISSUE TITLE
[ENHANCEMENT] Make client<>server token refresh so session doesnt timeout

### ISSUE THREAD

**Issue by phupabegim** [PokemonGoF/PokemonGo-Bot#713]
When I start the bot at my location it is good for about 1 hour, going to PokeStops catching releasing Pokémon but then once that hour or so elapses it just walks round for hours on end (currently 7 hours) doing nothing.

**Comment by MikeDX** [comment]
The session token expires after about an hour (sometimes less, sometimes more). After that it needs to re-login to continue. Your only option at the moment is to restart it.

**Comment by phupabegim** [comment]
Oh, I assumed that it was still running due to the walking notices. Is that not the case then?

**Comment by MikeDX** [comment]
It's still moving around, but it cant perform any tasks as the session is expired (but isnt aware of it)

**Comment by gpires** [comment]
@MikeDX Its possible to check if the season is expired?
Then just needs to refresh the session.

**Comment by phupabegim** [comment]
Or just renew it every hour anyway.

**Comment by MikeDX** [comment]
@gpires yes, since the PokemonGo-Map repo does exactly this, it gets the session token lifetime at login.

@phupabegim no that is just a dirty hack way of doing it.

**Comment by tonz134** [comment]
This is my biggest issue right now :<

**Comment by MikeDX** [comment]
Currently working on a fix for this as it is driving me insane :)

**Comment by MikeDX** [comment]
Submitted Pull request #735

**Comment by dmateusp** [comment]
This is the fix probably https://github.com/PokemonGoF/PokemonGo-Bot/pull/735
