### ISSUE TITLE
[suggestion] Don't catch pokemon lower then X% IV

### ISSUE THREAD

**Issue by boriss579** [PokemonGoF/PokemonGo-Bot#715]
### Expected Behavior
Config the bot to ignore and not catch a Pokémon with a lower IV then specified in settings.
Catch only if IV>0.85 - the bot will try to catch only Pokémon with that parameter and ignore all others.
Useful for player who don't want to waste pokeballs and rake extreme amount of candy 

### Actual Behavior
The bot try to catch every Pokémon (if not on the ignore list) and keep/exchange it using the release parameters.

**Comment by jle3** [comment]
You can already do this with release_config.json

{
	"any": {
		"min_cp": 9,
		"min_iv": 0.85,
		"cp_iv_logic": "or"
	},
	"My Pokemon": {
		"min_cp": 0,
		"min_iv": 0,
		"cp_iv_logic": "or"
	}
}

**Comment by boriss579** [comment]
But the bot will still catch the Pokémon first no?

**Comment by dmateusp** [comment]
maybe something like a config file catch_pokemon looking like this "catch : { "min_cp": 1000, "min_iv": 0.8, "cp_iv_logic": "or"} ?

**Comment by surfaace** [comment]
function implemented in 33a0ad6c6645415e7491b1d76fe664f40376fb16
