### ISSUE TITLE
Map behavior when different bots are active

### ISSUE THREAD

**Issue by alexanderrock** [PokemonGoF/PokemonGo-Bot#716]
I've started 4 bots and started the map.
All 4 are displayed but i have to manually zoom to them, under the Trainer" section it should defineable which one to follow and also in the config of the "web" define a start/default trainer to follow

**Comment by MikeDX** [comment]
This is the wrong repo to report this in (probably) as the Web interface is now in a different repo.

**Comment by tstumm** [comment]
I agree with @MikeDX 
Please submit your issue here https://github.com/OpenPoGo/OpenPoGoWeb
