### ISSUE TITLE
Add test if user has the pokémon

### ISSUE THREAD

**Issue by LeaklessGfy** [PokemonGoF/PokemonGo-Bot#731]
### Expected Behavior
The user can specified if he want to keep the pokemon (whatever CP or IV ) if this one isn't in his hand

### Actual Behavior
Transfer pokémon if he is under CP or IV specified, same if the user don't have this one

What do you think ?

**Comment by surfaace** [comment]
so multiuser option for transfer filter?

**Comment by ironbishop** [comment]
duplicate of #604

**Comment by TheGoldenXY** [comment]
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/604

/closed
