### ISSUE TITLE
[Question] How to enter in our own Google Maps API key ?

### ISSUE THREAD

**Issue by jtara1** [PokemonGoF/PokemonGo-Bot#736]
### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by leadboots5** [comment]
Depends on what version you are running.
Maybe -k
Maybe config
or changing the code

**Comment by jtdroste** [comment]
Please fill out all the required information (such as version of the bot you are running).
