### ISSUE TITLE
[Question] Releasing pokemons is really slow

### ISSUE THREAD

**Issue by fsegouin** [PokemonGoF/PokemonGo-Bot#74]
It looks like releasing pokemons with a higher cp that what you set as the -c flag takes ages. It was fine in the earlier versions and now it takes at least 10 or 20s to release a pokemon. Servers are not overloaded right now (UK) so I'm not sure what this issue is. Is anyone experiencing the same issue? Cheers!

**Comment by douglascamata** [comment]
There is an intentional delay when releasing pokemons after capturing. I think it's set to 5 seconds or something like this.

**Comment by fsegouin** [comment]
@douglascamata It's actually way more than that - I've seen the bot wait for almost 20 seconds. It must be something else.

**Comment by douglascamata** [comment]
@fsegouin I realised the code looks through all your inventory stuff (pokemon go seems to store inventory and pokemon data together) to see if it finds any pokemon to release using the current minimum CP config, not the just captured one.

You have a lot of items and/or pokemons, I suppose. Am I right?

**Comment by fsegouin** [comment]
Uh nice find, that might be it. Yeah, I'm almost full of items/pokemons. Wouldn't be faster to only release the pokemon we just captured if it doesnt meet the minimum CP requirements?

**Comment by douglascamata** [comment]
@fsegouin of course. But I think we need to find some special id used to store the pokemon in your pokemon list, so the loop seems necessary. I'll dig into this after I finish some refactoring.

**Comment by fsegouin** [comment]
@douglascamata much better since 583b967 thanks!

**Comment by PokemonGoF** [comment]
We can do the release when counter > 10 or 20, to avoid get full list every time.
