### ISSUE TITLE
[ENHANCEMENT] - Use Razz Berries. 

### ISSUE THREAD

**Issue by TSM-EVO** [PokemonGoF/PokemonGo-Bot#743]
### Expected Behavior
Bot encounters a pokemon
(possibly uses logic to determine catch chance)

Checks inventory for RazzBerry
(possibly include logic to check that the number of razzberries that'll remain is above a certain amount)
(ie, keep 5 razberries in case people want to use them manually at some stage)

Uses RazzBerry
Catches pokemon

This would have the benefit of giving a higher catch chance, as well as using razzberries (at last check I had over 200 in my bag)

**Comment by Nihisil** [comment]
There is a pull-request that implement this feature

https://github.com/PokemonGoF/PokemonGo-Bot/pull/655

I have merged it to my local repository and it is working like a charm. I hope it will be merged to the dev soon, when author will resolve merge conflicts.

**Comment by TSM-EVO** [comment]
should be in dev now :) https://github.com/PokemonGoF/PokemonGo-Bot/commit/335a0aa9a6e57fef17d0865b2f404e0ca785124b
