### ISSUE TITLE
[suggestion] pokestop farming

### ISSUE THREAD

**Issue by doomrider666** [PokemonGoF/PokemonGo-Bot#744]
anyway to use the code for just pokestop farming? i know --spinstop will do the pokestop, but im only really interested in farming the stops, not the pokemon itself.

**Comment by MikeDX** [comment]
In your config.json, set "mode": "all" to "mode": "farm"

**Comment by doomrider666** [comment]
just tried this with sort of success, it still tries to catch pokemon between each pokestop.
