### ISSUE TITLE
[TUTORIAL] How to run multiple accounts at the same time

### ISSUE THREAD

**Issue by skyl1ne94** [PokemonGoF/PokemonGo-Bot#745]
* Needs to be added to the README.md

## How to run multiple accounts at the same time
    Before u start with this, make sure you create a copy of the config file for a second account by typing 
    "cp config.json.example config_acc1" in the Terminal. Fill in your details in the file "config_acc1"
    
    To actually make PokemonGo-Bot run multiple accounts, you can follow this tutorial:
    
    Linux:
    1. Download the template for Linux [here](https://onedrive.live.com/download?cid=8A1EC0D384061BB1&resid=8A1EC0D384061BB1%2116640&authkey=AEZ6QGJ8xIACQ6U)
    2. Place the template in the root folder of the PokemonGo-Bot.
    3. Copy the template and give it your own identity "cp startlinux_acc1_example startlinux_acc1".
    4. Open the file with notepad and edit the following parts:
       - LOCATION OF PokemonGo-Bot FOLDER (e.g. /root/PokemonGo-Bot);
       - git pull origin to "dev" or "master" (e.g. git pull origin dev);
       - config.json to the config file of the other account (e.g. config_acc1.json).
    5. You can run the bot now by opening a terminal and filling in "./startbotacc1".
    6. To run multiple accounts at the same time:
       - Create a copy of "config_acc1" to "config_acc2"
       - Create a copy of "startwin_acc1" to "startwin_acc2"
    7. Now use the command "screen" to create a screen for each bot to seperate the bots from each other. For a manual of the command    "screen" use "man screen" in the Terminal.

    
    Windows
    1. Download the template for Windows [here](https://onedrive.live.com/download?cid=8A1EC0D384061BB1&resid=8A1EC0D384061BB1%2116639&authkey=AH04lpHZWP6ISWg)
    2. Place the template in the root folder of the PokemonGo-Bot.
    3. Copy the template and give it your own identity "cp startwin_acc1_example startwin_acc1".
    4. Open the file with notepad and edit the following parts:
       - LOCATION OF PokemonGo-Bot FOLDER (e.g. C:\Program Files\PokemonGo-Bot);
       - git pull origin to "dev" or "master" (e.g. git pull origin dev);
       - config.json to the config file of the other account (e.g. config_acc1.json).
    5. You can run the bot by opening "startwin_acc1"
    6. To run multiple accounts at the same time:
       - Create a copy of "config_acc1" to "config_acc2"
       - Create a copy of "startwin_acc1" to "startwin_acc2"
    7. Change the values in these files to the credentials and details of the second account and you are good to go a second bot!

**Comment by julienkessels** [comment]
mac?

**Comment by solderzzc** [comment]
many thanks.
merged:
https://github.com/PokemonGoF/PokemonGo-Bot/commit/debbe1d4d6d390c5e6615b4e3c58b7936dd10162
