### ISSUE TITLE
[Suggestion]Just keep the best one in bag, transfer others

### ISSUE THREAD

**Issue by tastypear** [PokemonGoF/PokemonGo-Bot#753]
Need a feature to keep the best pokemon and ignore CP limit.
High CP limit always release my new PM. So if current catched PM's CP is higher, keep it and release the weak one at the same time.
Then the bag will never be full.

**Comment by Anyrainel** [comment]
Maybe keep a pokemon of currently highest IV would also make sense. This check list should also be able to be strict to a specific set of strong species. I would probably look into the code and see if I can add this feature myself :D (unfortunately I just got this project successfully running on my PC...)

**Comment by MikeDX** [comment]
I would like to keep the best N or have it configurable. I might want to keep two or more vaporeon, but I don't want to keep more than one pidgey or zulbat

**Comment by Saturate** [comment]
Seems like a nice feature :)

**Comment by dezayner** [comment]
Like feature "smart" cp

**Comment by CapCap** [comment]
feature exists now
