### ISSUE TITLE
[Suggestion] Drop Items when the bag is full with priorities for farming

### ISSUE THREAD

**Issue by dominikue** [PokemonGoF/PokemonGo-Bot#76]
I think it would be nice for farming, when the bot drops items with priorities. This means
Potion < Revive < Razz Berry < Poké Ball < Super Ball < Ultra Ball 
But first the bots need to handle with @[suggestion] Use great balls when encounter higher CP pokemons and maybe with Razz Berry.

**Comment by surfaace** [comment]
@dominikue could you assist here since you are already working on item filtering?
