### ISSUE TITLE
Unable to get player_data

### ISSUE THREAD

**Issue by ilarimakela** [PokemonGoF/PokemonGo-Bot#763]
When I start the bot my output looks like this:
[2016-07-25 06:11:18] [x] PokemonGO Bot v1.0
[2016-07-25 06:11:18] [x] Configuration initialized
[2016-07-25 06:11:18]
[2016-07-25 06:11:18] [x] Address found: Tyynenmerenkatu 11 Helsinki
[2016-07-25 06:11:18] [x] Position in-game set as: (60.15638089999999, 24.9209373, 0.0)
[2016-07-25 06:11:18]
Traceback (most recent call last):
  File "pokecli.py", line 225, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.start()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 33, in start
    self._setup_api()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 215, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'

Yesterday everything was fine but this morning I don't get the player data.

I pprinted the response_dict and it looks like this:
{'auth_ticket': {'end': '*******',
                 'expire_timestamp_ms': '*******',
                 'start': '*******',
 'direction': 1,
 'responses': {'GET_PLAYER': {'profile': {'avatar': {'unknown2': 1,
                                                     'unknown3': 4,
                                                     'unknown9': 3},
                                          'creation_time': 1468906693625L,
                                          'currency': [{'type': u'POKECOIN'},
                                                       {'amount': 10574,
                                                        'type': u'STARDUST'}],
                                          'daily_bonus': {},
                                          'item_storage': 350,
                                          'poke_storage': 250,
                                          'team': 1,
                                          'tutorial': 'AAEDBAc=\n',
                                          'unknown12': '',
                                          'unknown13': '',
                                          'username': u'143154946'},
                              'unknown1': 1}},
 'unknown2': 8145806132888207460L}

I don't know what 'auth_ticket' contains so I ***** it...

Anyone knows what's wrong? I use updated version of dev branch.

**Comment by LasseSkogland** [comment]
Delete and reclone repo fixes this issue.

**Comment by ilarimakela** [comment]
Easy fix :D and it actually fixed my problem. Thanks Lasse!

**Comment by tdurieux** [comment]
Reclone the repo does not fix the issue for me.
Do you have an other fix?

**Comment by LasseSkogland** [comment]
It depends what error you get.
But you should not ask questions on closed issues, create a new one instead.
