### ISSUE TITLE
PokeStop out of range everytime & seems teleporting among PokeStops

### ISSUE THREAD

**Issue by Anyrainel** [PokemonGoF/PokemonGo-Bot#765]
### Expected Behavior
Yields items from PokeStops and walk with designated speed.

### Actual Behavior
After login, the bot starts to walk through lots of PokeStops. It arrives too soon and each spin got "out of range"
Is this softbanned? Every run has same result.

### Other Information
OS: Windows 10
Git Commit: 
![image](https://cloud.githubusercontent.com/assets/3783449/17092668/16ffc226-5212-11e6-8215-283a6825d2d5.png)

**Comment by MikeDX** [comment]
Are you logged in on another device at the same time?

**Comment by Anyrainel** [comment]
No, I didn't. I guess it is somehow like driving: you passed the pokestop while u are spinning because of fast speed.
Could yours work as normal?

**Comment by TSM-EVO** [comment]
This is also occurring for me and others in dev

@SteffanLong has suggested using master

**Comment by SteffanLong** [comment]
Please switch to master branch. This is a known issue on dev currently.

**Comment by xavor92** [comment]
Same Issue, but working on Master.
Master seems to work without Problems.

**Comment by 3mph4515** [comment]
Faced with the same issue on dev branch

**Comment by TheOssi** [comment]
Got the same Issue

**Comment by dotaxis** [comment]
Same problem. Knew I shouldn't have updated :/

**Comment by TheOssi** [comment]
@dotaxis just revert your pull

**Comment by dotaxis** [comment]
@TheOssi I messed up my fork and just made a new one from the most recent commit and added a few things. Can't really do that.

**Comment by 03t02** [comment]
Same problem, it told me that I'm probably softbanned

**Comment by dmateusp** [comment]
see https://github.com/PokemonGoF/PokemonGo-Bot/pull/775

**Comment by dotaxis** [comment]
This still isn't fixed for me.

**Comment by 03t02** [comment]
It fixed for me, but bot don't catch any pokemon anymore, just spin pokestop. In my config file mode is all...

**Comment by dmateusp** [comment]
using dev branch ?

**Comment by 03t02** [comment]
Yes I'm using dev branch.

**Comment by dotaxis** [comment]
PokeStops are actually working now but it's not catching Pokkemon anymore.

**Comment by dmateusp** [comment]
@dotaxis I think it is an issue for everyone on the dev branch at the moment

**Comment by TSM-EVO** [comment]
I have the same behaviour @dotaxis has described, the bot catches one poke then loses all interest in catching another

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed

**Comment by thelemonenergy** [comment]
I have exactly this issue right now. Bot was running for hours and then this happend suddenly. Cant spin anything. 
Is this an annually bug?

**Comment by MerlionRock** [comment]
Did you set a spin limit? How long did you run the bot?

There is a spin limit. I think it's 1.5k for 3 days. Once you hit it, limit will be reduced. To prevent hitting limit, do not run the bot 24hr, reduce walking speed and use sleep schedule.

**Comment by thelemonenergy** [comment]
I had my limit on 1900 per day (default in config example).
Set it to 500 now and will wait a day. 
Is exceeding the limit a known ban/flag reason?
