### ISSUE TITLE
[Feature Request] Remote Control

### ISSUE THREAD

**Issue by c0rrre** [PokemonGoF/PokemonGo-Bot#770]
Hi,

First of all, nice project.

But wouldn`t it be nice to have to possibility to control the bot remotely?

For example with a Telegram Bot like in this project 
https://github.com/Ar1i/PokemonGo-Bot

So we could get some Informations or Start/Stop the bot without ssh Access

Greetz

**Comment by douglascamata** [comment]
@c0rrre we're in the process of a big refactoring that will enable plugins and asynchronous 3rd party apps communication through a websocket server. So it will be very easy for users to develop such things.
