### ISSUE TITLE
I can't run the script on the second run. Worked fine the first time!

### ISSUE THREAD

**Issue by ssm34** [PokemonGoF/PokemonGo-Bot#772]
Was working fine on the first run. I closed it (pressed x close button on terminal). Next time I run it, it gives me the error attached.

### Other Information
OS: Ubuntu 16.04 LTS x64
![selection_002](https://cloud.githubusercontent.com/assets/19939177/17094160/26de012c-526b-11e6-8cca-ee39a2de6792.png)

**Comment by Aiyubi** [comment]
did you do the virtualenv version before? If so you have to do it every time before starting the bot

**Comment by ssm34** [comment]
Can't believe I missed that - multiple times! Thanks.
