### ISSUE TITLE
Give random delay time between catch and exchanged for candy

### ISSUE THREAD

**Issue by ariefbayu** [PokemonGoF/PokemonGo-Bot#774]
Should have random time (and configured in seconds) between catch and exchange for candy. This is to mimic normal playing behaviour (also to prevent from being sniffed by anti bot mechanism (if any:D).

**Comment by DanielVolz** [comment]
I agree. I think there should be a random time period added to every action the bot makes, to mimic a more human like behaviour. 

Also every action should take as long as it take a human to to it on the phone + random seconds.

**Comment by SpaceWhale** [comment]
I've submitted a pull request for this feature. We may eventually want to enable/disable this behavior in the config.

**Comment by shermj** [comment]
Can this be extended to delay before recycling items as well? :)
