### ISSUE TITLE
ENORMOUS Amount of ram used after starting the script

### ISSUE THREAD

**Issue by fr1tzz** [PokemonGoF/PokemonGo-Bot#777]
My laptop is running Debain 8.5 with 4Gb of ram and 8Gb of swap. It idles at around 300-400 Mb of ram usage doing nothing. I started the script and It immediately started using all my ram and 2Gb of swap. It didn't seem to be doing this before. I'm I doing something wrong or is this a bug?

**Comment by xavor92** [comment]
On Master, Uses <30Mb of RAM.

**Comment by dmateusp** [comment]
What are you starting ? the script only ? the web server ? also, can you add a screenshot of the usage live ?

**Comment by fr1tzz** [comment]
Here are before and after when I run the script.
BEFORE: http://imgur.com/dS0J9lR
AFTER: http://imgur.com/4a6NUoE

**Comment by dmateusp** [comment]
Maybe someone with more experience with your OS could help you, I'm  a filthy Windows user and the RAM usage is fine on my setup

**Comment by douglascamata** [comment]
Trying to reproduce on OS X

**Comment by douglascamata** [comment]
Please, show me your `config.json` and keep `htop` window on the bot process so I can see better how it's behaving.

**Comment by douglascamata** [comment]
Have been running for almost 10 minutes and memory usage is stable at 0.3% of my RAM.

**Comment by douglascamata** [comment]
btw, I'm running the last commit from `dev` branch, as always. Still my RAM usage is at 0.3%.

**Comment by douglascamata** [comment]
Still at 0.3% RAM usage .... I can't confirm your leak in my OS.

**Comment by linanqiu** [comment]
I had this problem too. Deleted the `web` folder and it was fine. Turns out the `index.html` grew to something like 4GB. Had no idea why.

**Comment by surfaace** [comment]
not related to core code
