### ISSUE TITLE
location of exiting the bot and log in from the app

### ISSUE THREAD

**Issue by yidongw** [PokemonGoF/PokemonGo-Bot#779]
Awesome project.

I used location spoofing changed to another place, but in a reasonable time, so I can avoid soft ban.

If I turn on the bot and let it run for 20 hours. Will it be a big move from the initial location?
It will be better if I can monitor my account and set my location there before I log in to my account.  I thought I can use web folder to monitor but I couldn't figure how to make it work. Better explanation will be appreciated.

: )

**Comment by dmateusp** [comment]
You can limit the steps around your start location, default is 100 see config.json :     "max_steps": 100

**Comment by yidongw** [comment]
The default is 5. You mean it will be a 5 steps circle from the initial point?

What does Web do tho?

**Comment by dmateusp** [comment]
please use Slack as the Q&A https://pokemongo-bot.slack.com/messages/general/ , web is a way to visualize your bot, read the README file as well
