### ISSUE TITLE
inventory is full

### ISSUE THREAD

**Issue by mehdi-S** [PokemonGoF/PokemonGo-Bot#781]
### Expected Behavior
getting item from pokestop

### Actual Behavior
inventory is full, going into catch mode ("poke" mode)
but in poke mode, it cannot catch anything without pokeball, so going into "farm" mode etc

### Steps to Reproduce
get item from pokestop,after a while your inventory will be full but
1) full of what ?
2) how to unfull-ize it ?

### Other Information
OS: Debian x64_86
Git Commit: fb2cca3b1f701653d58424f49a2ba7fae5cd97e9

**Comment by dmateusp** [comment]
Full of any item, pokeballs, potions or any other item counts as ONE. 

You can manually drop the items you don't want using the phone app and then use the parameter "item_filter":["101","102","103","104"] to recycle the items you don't want when you get them from a Pokestop

**Comment by mehdi-S** [comment]
@dmateusp i am aware of that, but i have no information about the item i need to drop, and it will be a nice enhancement to drop automatically item since i cannot login on my phone without getting a soft ban (i'm farming around the world to get special poke)

**Comment by dmateusp** [comment]
You can drop any item, every item counts as one. Dropping automatically is a known enhancement to work on
