### ISSUE TITLE
Problem with auth_service

### ISSUE THREAD

**Issue by Mentaa** [PokemonGoF/PokemonGo-Bot#784]
Hello,

The bot works perfectly when i use pokecli.py -a ptc -u ... 
but now when i put my config on config.json when i try to launch i have this error:

> 
~/Desktop/PokemonGo-Bot-dev# python pokecli.py -cf config.json
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-p PASSWORD] [-l LOCATION] [-lc LOCATION_CACHE] [-m MODE]
                  [-w WALK] [-k GMAPKEY] [-ms MAX_STEPS]
                  [-it INITIAL_TRANSFER] [-d DEBUG] [-t TEST]
                  [-du DISTANCE_UNIT] [-if ITEM_FILTER] [-ev EVOLVE_ALL]
                  [-ec EVOLVE_CAPTURED]
pokecli.py: error: argument -a/--auth_service is required
> 

My config.json:

> {
    "auth_service": "ptc",
    "username": "xx",
    "password": "xx",
    "location": "Canada, Montreal",
    "gmapkey": "AGMAPAPIKEY",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104",
    "evolve_all": "NONE",
    "use_lucky_egg": false
}

> 

Someone have same problem and know how to fix ? thanks in advance.

**Comment by sirkz** [comment]
i have the same issue please help !!!!!!!!
this is what i get after launching the command : 
usage: pokecli.py [-h] [-cf CONFIG] -a AUTH_SERVICE [-u USERNAME]
                  [-p PASSWORD] [-l LOCATION] [-lc LOCATION_CACHE] [-m MODE]
                  [-w WALK] [-k GMAPKEY] [-ms MAX_STEPS]
                  [-it INITIAL_TRANSFER] [-d DEBUG] [-t TEST]
                  [-du DISTANCE_UNIT] [-if ITEM_FILTER] [-ev EVOLVE_ALL]
                  [-ec EVOLVE_CAPTURED]
pokecli.py: error: argument -a/--auth_service is required

**Comment by maestroi** [comment]
Works now, Copy config.json.example to config.json and edit that then it works.
