### ISSUE TITLE
New catch version is pretty long

### ISSUE THREAD

**Issue by LeaklessGfy** [PokemonGoF/PokemonGo-Bot#787]
### Expected Behavior
Can catch pokemon and find apropriate path

### Actual Behavior
Makes long minutes before actually seeing a pokemon

Why yesterday behaviour has change ?

**Comment by surfaace** [comment]
what commit are you running? i dont see any issues on b8606bc509ca89902441b213f5ee7996cca29137

[2016-07-25 13:36:24] [#] A Wild Pidgey appeared! [CP 125] [Potential 0.42]
[2016-07-25 13:36:24] [#] IV [Stamina/Attack/Defense] = [6/2/11]
[2016-07-25 13:36:26] [x] Using Pokeball (chance: 53.30%)... (87 left!)
[2016-07-25 13:36:27] [x] Captured Pidgey! [CP 125] [6/2/11]
[2016-07-25 13:36:27] [#] Pidgey has been exchanged for candy!

**Comment by tstumm** [comment]
There is an issue regarding SpiralNavigator. @douglascamata is already working on a fix.

**Comment by LeaklessGfy** [comment]
I'm on 'dev' to be as close as possible on the latest version and try to give some work on it. 

@tstumm Thanks ! Waiting for this fix :)

**Comment by douglascamata** [comment]
I'm having trouble with the fix. Any help is appreciated. Please setup the maps integration to have a better picture of how (bad) it's walking. lol

**Comment by LeaklessGfy** [comment]
@douglascamata I will try to see that tonight (I'm at work for now). The former method wasn't enough great ? Because yesterday it was actually pretty efficient.

**Comment by douglascamata** [comment]
@LeaklessGfy we're refactoring towards implementing a Behaviour Tree and this broke the SpiralNavigator. It's not calculating next points to walk to correctly, I guess. :/

**Comment by LeaklessGfy** [comment]
@douglascamata Alright thanks for this informations and can you tell me more about the problem you encounter ? What's actually happening with that function on map ? Google map direction make the process buggy ? Another thing ?

**Comment by douglascamata** [comment]
@LeaklessGfy basically the bot is walking like a drunk cockroach. I think next step is not being calculated correctly by SpiralNavigator.

**Comment by LeaklessGfy** [comment]
Alright the big problem here is that the master branch is actually at the same point of dev ... I think that's a terrible thing because here we are stuck until we don't find the solution of this problem and I can't get a eye on it for now ... On slack we should warn every dev on this issue.

**Comment by LeaklessGfy** [comment]
@tstumm Seem to fix it ? (on slack he told some things about that, need to test in order to see if it works)

**Comment by crazy4ever** [comment]
Just updated to #813 the latest commit in dev and it's not fixed, still won't find anything.

**Comment by tstumm** [comment]
Fixed

**Comment by tstumm** [comment]
Wait @crazy4ever can you post a log?

**Comment by tstumm** [comment]
Normally log gets kinda long since its printing a walk msg on every tick. For me it catches pokemon now and then. Of course its not doing this on every tick because the distance travelled is normally low.

**Comment by crazy4ever** [comment]
@tstumm Set debug to true and do i just have to copy everything in it or does it safe the info somewhere?

**Comment by crazy4ever** [comment]
Alright, reinstalled everything, and now "catch" isn't working like before, but when using "all" it actually catches pokemons.

It's just "catch" that isn't working.

**Comment by surfaace** [comment]
modes are: all, farm, poke
