### ISSUE TITLE
web directory no longer in DEV branch

### ISSUE THREAD

**Issue by xorinzor** [PokemonGoF/PokemonGo-Bot#788]
I did an `git pull` to update to the latest changes from the dev branch, but it ended up deleting the entire `web` directory.

I'm not sure if this is intended, because from what I've seen it works fine.

**Comment by LasseSkogland** [comment]
Do this inside your Pokemon Go Bot GIT Dir:
git submodule init
git submodule update

**Comment by xorinzor** [comment]
Well I reverted to the old version because there seem to be some issues with the current revision, but if that solves it then I'll close this issue :)
