### ISSUE TITLE
DEV - Failed to start since new upate

### ISSUE THREAD

**Issue by tpmodding** [PokemonGoF/PokemonGo-Bot#791]
### Actual Behavior
after updating nothing works..
configs are in configs-dir

and for what is the "source bin/activate" command? it doesnt work on windows...

C:\Users\User\Desktop\PokemonGo-Bot>python pokecli.py
[2016-07-25 12:50:38] [x] No config argument specified, checking for /configs/config.json
Traceback (most recent call last):
  File "pokecli.py", line 228, in <module>
    main()
  File "pokecli.py", line 205, in main
    config = init_config()
  File "pokecli.py", line 65, in init_config
    load.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 17 column 2 (char 467)
### Other Information
OS: windows 10 x64
Git Commit: b8606bc509ca89902441b213f5ee7996cca29137

**Comment by dmateusp** [comment]
Can you copy paste your config.json file (take our your username and password)?

**Comment by tpmodding** [comment]
sure

{
    "auth_service": "google",
    "username": "@googlemail.com",
    "password": " ",
    "location": "Schloss Johannisburg 63739 Aschaffenburg",
    "gmapkey": "",
    "max_steps": 7,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "101,102,103,104",
    "evolve_all": "NONE",
    "use_lucky_egg": false
}

**Comment by dmateusp** [comment]
Devs, information on the bug here : http://stackoverflow.com/q/28223242/4884034 (I can't code at the moment).

For your question about source/bin/activate it is used to have a separate virtual environment, you can read about it here https://virtualenv.pypa.io/en/stable/

**Comment by TheHaliax** [comment]
okay so i was having a similar problem on line 16.
this is my solution
 {
    "auth_service": "google",
    "username": "YOUR_USERNAME",
    "password": "YOUR_PASSWORD",
    "location": "SOME_LOCATION",
    "gmapkey": "GOOGLE_MAPS_API_KEY",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": [""],
    "evolve_all": "NONE",
    "use_lucky_egg": false,
    "evolve_captured": false,
    "catch": {
		"any": {"catch_above_cp": "0", "catch_above_iv": "0"},
		"logic": "or"
    },
    "release": {
		"any": {"release_under_cp": "0", "release_under_iv": "0"},
		"logic": "or"
    }
}
