### ISSUE TITLE
[REQUEST] Multiple locations in config, and switch in commandline

### ISSUE THREAD

**Issue by ariefbayu** [PokemonGoF/PokemonGo-Bot#792]
It would be great if I don't have to edit `config.json` just so that I can start bot from different location.

**Comment by surfaace** [comment]
we had that earlier, until it was moved to config because it's 'easier'.
location randomizer was opened as a request which will be an improvement #793

**Comment by ariefbayu** [comment]
It's different than location randomizer. Consider this: there are 3-4 favorite location in town and I would like to run bot in that place while I also sit there to occasionally login and battle the gym... If my location and bot location is too far apart, it would trigger anti bot because I "jumped". Hope you get the point :)

**Comment by surfaace** [comment]
i would suggest to use multiple locations in config, then have a switch indicator to specify which one to use. then location cache needs to be used in order not to teleport

**Comment by ariefbayu** [comment]
That's fine by me, as I don't travel to far to often... Thank you for the consideration :)

**Comment by surfaace** [comment]
been added to dev branch, use -cf <config> or --config <config>
