### ISSUE TITLE
web/location-%s.json and data/last-location-%s.json not auto-generated when non-existing

### ISSUE THREAD

**Issue by Mordana** [PokemonGoF/PokemonGo-Bot#795]
### Expected Behavior
"web/location-myuser.json" and "data/last-location-mysuser.json" will be created if the files do not exist.

### Actual Behavior
"web/location-myuser.json" and "data/last-location-mysuser.json" aren't created automatically.

### Steps to Reproduce
remove said files and start both bot and webserver.

### Other Information
OS: Win7/Win10

### Additional Comments
The files are being updated as soon as you manually create the files.

Similar to #691

**Comment by surfaace** [comment]
web folder is not included by this code. its a seperate git repo (https://github.com/OpenPoGo/OpenPoGoWeb by default)

**Comment by Mordana** [comment]
but data/last-location-%s.json is :P

**Comment by surfaace** [comment]
duplicate of #778
