### ISSUE TITLE
[Suggestion] Predefined routes?

### ISSUE THREAD

**Issue by Teodor-Dobrev** [PokemonGoF/PokemonGo-Bot#799]
It would be nice if there were predefined routes that travel all around the world. Like for example: seaMap, which contains the best places for catching water type pokemon and you visit them with believable time laps. Or you just choose mountainMap, which has the best mountains...

The user just has to choose the type of pokemon he/she wants, and the bot will start "mining" in the perfect places.

**Comment by dmateusp** [comment]
I believe it would be a good amount of work and other things should be prioritized over this.

But this would be a very cool feature to be implemented in the future

**Comment by thomaswelton** [comment]
This tool will convert a google maps route to a GPX file for spoofing location on an iOS device using xcode. A GPX file contains coordinates as well as timestamps for moving along the route.

https://mapstogpx.com/pokemon.php

**Comment by Teodor-Dobrev** [comment]
You don't need exactly a route to do this, all you need are close coordinates of dots, of places, since that bot goes around a certain place, all you need is a list of close spots on the same type of terrain... and the distance/time teleportation issue could be resolved with just adding the right amount of time between two places: 1km = 2 min, 2km = 4 min.

**Comment by rguedes** [comment]
A good feature would be have a option to define 2 points, start point (when bot starts) and finish point and bot goes between this 2 points.

**Comment by TheSavior** [comment]
This will be very possible once we get to behavior trees: https://github.com/PokemonGoF/PokemonGo-Bot/issues/142
