### ISSUE TITLE
Switch to catch mode failed

### ISSUE THREAD

**Issue by seadog007** [PokemonGoF/PokemonGo-Bot#801]
### Expected Behavior
Switch to catch mode

### Actual Behavior
Keep finding Pokestops

### Steps to Reproduce
Make the Inventory full, and start the script.

### Other Information
OS: Ubuntu 14.04
Git Commit: 844ae697407c505a9405c775e8a235179749e62f

<img width="645" alt="screen shot 2016-07-25 at 8 24 38 pm" src="https://cloud.githubusercontent.com/assets/5138409/17101207/d647217c-52a5-11e6-9e24-feb5f6e7fdaf.png">

**Comment by HoaxKey** [comment]
I pulled 15 mins ago, and now it seems to only farm pokestops and not catch anything, which i think may be a related bug.

**Comment by chiefcll** [comment]
Reverted back to 586a0dc - seems to work fine - I think its with the new google stepper logic

**Comment by ththompson** [comment]
Confirming. Also bot seeks stops when set to 'poke' in config.

**Comment by LeaklessGfy** [comment]
Related to :
https://github.com/PokemonGoF/PokemonGo-Bot/issues/787

We haved warn a lot of dev on this issues, don't know when it will be fix

**Comment by surfaace** [comment]
#377 #382 #804
