### ISSUE TITLE
[REQUEST] Timer & Schedule

### ISSUE THREAD

**Issue by Naramsim** [PokemonGoF/PokemonGo-Bot#805]
### Desired Behavior
Implement a timer option. The bot should stop after a specific amount of time. So we can let the bot running all night without caring of it. 

OR: (more complicated) implement a sort of a schedule. Thanks @Saturate 

### Actual Behavior
No timer implemented

### Steps to Reproduce
No one

**Comment by Saturate** [comment]
Seems like a nice idea. Maybe a extended version should be a schedule on when to run?

**Comment by Naramsim** [comment]
Whoa! That's nicer!

**Comment by surfaace** [comment]
use cronjob if you are running linux, or task scheduler in windows. there is alot of ways to make this possible
