### ISSUE TITLE
Consider transforming PokemonGoF into organisation

### ISSUE THREAD

**Issue by douglascamata** [PokemonGoF/PokemonGo-Bot#81]
Makes it easier for contributions and enables we to become an official "team" 😄

**Comment by PokemonGoF** [comment]
+1  :)

**Comment by PokemonGoF** [comment]
Haven't seen any transforming settings in github, we can keep use the link since it was announced?

**Comment by douglascamata** [comment]
Let me check.

**Comment by douglascamata** [comment]
@PokemonGoF https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by PokemonGoF** [comment]
hmm, maybe we can keep it as it for now.

Warning: Before converting a user into an organization, keep these points in mind:

You will no longer be able to sign into the converted user account.
You will no longer be able to create or modify gists owned by the converted user account.
An organization cannot be converted back to a user.
The SSH keys, OAuth tokens, job profile, and associated user information, will not be transferred to the organization. This is only true for the user account that's being converted, not any of the user account's collaborators.
Any commits made with the converted user account will no longer be linked to that account. The commits themselves will remain intact.

**Comment by douglascamata** [comment]
@PokemonGoF yes, you would need a new user to be the admin of the organisation. Or you can create a organisation under your user and transfer the repository ownership to the organisation.
