### ISSUE TITLE
Resume from last known position / safe-guard for teleporting

### ISSUE THREAD

**Issue by Saturate** [PokemonGoF/PokemonGo-Bot#810]
### New Behavior

1. When running the bot and exiting, we want to save the current location for the user..
2. When we start up the bot from again, we want to make sure the start location is not making us teleport.

    1. If the time is considered too shot to have travled back to starting position, we should either:
       - Walk to start location from last known position
       - Wait to start the bot until enough time has passed. This will make it more likely that we did not teleport.
      - Spawn in-between the starting location and last known location. This should be calculated so it's a possible location.  

3. If we change the starting location, we want to check we are not teleporting. If it's around the globe we want the user to confirm this choice.

The methods explained here in point 2. can all co-exist, and even be picked by the user or randomly to avoid bot detection on a even better scale.

### Current Behavior

It just teleports, and that's really bad for bot detection. Let's not get banned! It seems like it start from the last known position, but that's still a bit too strange.

**Comment by bstpierr** [comment]
FYI: The last location is currently logged to data/last-location-username.json, but that information is only used during the running of the bot. If you want to resume from that location, you can copy-paste the lat-long to your config.json.

This is more of a workaround, but still useful to know about :)

**Comment by Skeyelab** [comment]
my location is not being written to data/last-location-username.json in the master fork.  Is this the case for everyone?  Or do i need to create this file?

**Comment by bstpierr** [comment]
I'm on the master fork at 32cefeed4760d6b5d2b3eb76d783d0f13d068e83 and my last location is updated nearly ever second while running.

**Comment by Skeyelab** [comment]
[http://cloud.skeyelab.com/0L1f123t0q1g](url)

**Comment by Skeyelab** [comment]
I had to do `touch data/last-location-username.json`, then it worked

**Comment by Calcyfer** [comment]
In a previous commit 2 days ago (approximately) this is how it worked. I'll check when and why it was removed.
