### ISSUE TITLE
Initial_tranfer

### ISSUE THREAD

**Issue by NielsvanDijk** [PokemonGoF/PokemonGo-Bot#814]
Is there a way to remove certain pokemon?

### Expected Behavior

"initial_transfer": "0,Raticate"

### Actual Behavior

Does not remove raticade i got 40

**Comment by CtrlAltDefeat94** [comment]
doesnt 0 mean disabled? not sure if only transferring specific pokemon is even supported though

**Comment by eggins** [comment]
Just set the CP level - and it will delete all but 1 - leaving the highest CP/IV
