### ISSUE TITLE
web submodule dissapeared in dev branch

### ISSUE THREAD

**Issue by alvarogzp** [PokemonGoF/PokemonGo-Bot#817]
It is not there anymore: https://github.com/PokemonGoF/PokemonGo-Bot/tree/dev

Is it a bug or a feature? I had to clone the [OpenPoGoWeb](https://github.com/OpenPoGo/OpenPoGoWeb) manually.

**Comment by bool-** [comment]
It is a git submodule now.
Command "git submodule update --init --recursive" will clone it.

**Comment by alvarogzp** [comment]
@bool- yes, I can see it as a submodule in master branch here: https://github.com/PokemonGoF/PokemonGo-Bot/tree/master

But in dev it is not present.

**Comment by leadboots5** [comment]
@alvarogzp I see it in dev.

**Comment by alvarogzp** [comment]
it looks like they have re-added it: https://github.com/PokemonGoF/PokemonGo-Bot/commit/71f9f685a9de1c768b950b44522b1f6751e7f09f

closing issue...
