### ISSUE TITLE
Config default path

### ISSUE THREAD

**Issue by alexanderrock** [PokemonGoF/PokemonGo-Bot#819]
### Expected Behavior
python pokecli.py -cf config.json

### Actual Behavior
python pokecli.py -cf configs/config.json

### Steps to Reproduce
try to start bot without the subdirectory configs/*

default lookup for configs should be in the configs folder and the config subdirectory should not needed to be passed

**Comment by Mello-Yello** [comment]
Just do: python pokecli.py
It's already searching in the configs folder
```
python pokecli.py
[19:26:31] PokemonGO Bot v1.0
[19:26:31] No config argument specified, checking for /configs/config.json
[19:26:31] Configuration initialized
```

**Comment by surfaace** [comment]
always good to specify configs path, but i see your point

**Comment by koter84** [comment]
i think i'ts quite common to specify the path relative to your current location, so for me as a daily Linux user, the expected behavior is ./pokecli.py -cf configs/config.json
