### ISSUE TITLE
Evolving Pokemon

### ISSUE THREAD

**Issue by tellomichmich** [PokemonGoF/PokemonGo-Bot#82]
working.py :`

    def _transfer_low_cp_pokemon(api,value,pokemon):
        if 'cp' in pokemon and pokemon['cp'] < value:
                #print('need release this pokemon({}): {}'.format(value,pokemon))
                api.evolve_pokemon(pokemon_id=pokemon['id'])
                response_dict = api.call()
                #print('Response dictionary: \n\r{}'.format(json.dumps(response_dict, indent=2)))
                status = response_dict['responses']['EVOLVE_POKEMON']['result']
                if status == 1:
                        print('Evolved succesfuly !')
                else:
                        print('Evolve failed... Exchange !')
                        api.release_pokemon(pokemon_id=pokemon['id'])
                        response_dict = api.call()
                        #print('Response dictionary: \n\r{}'.format(json.dumps(response_dict, indent=2)))
                        print('Exchanged successfuly!')
`

pgoapi/protos/RpcSub.proto :`
    
    message EvolvePokemonRequest {
      optional fixed64 pokemon_id = 1;
    }

    message EvolvePokemonResponse {
      optional Result result = 1;
    
      enum Result {
        UNSET = 0;
        SUCCESS = 1;
        POKEMON_DEPLOYED = 2;
        FAILED = 3;
        ERROR_POKEMON_IS_EGG = 4;
      }
    }
`

Need to compile protobuf:
>protoc --proto_path=pgoapi/protos/ --python_out=pgoapi/protos/ pgoapi/protos/RpcSub.proto

Working :)

LOG :

> Walking from (XXX) to (XXX) for approx. 10.0sec
> Finished walking
> (XXX)
> Something rustles nearby!
> A Wild Pidgey appeared! [CP92]
> Captured Pidgey! [CP92] - exchanging for candy
> Evolved succesfuly !
> looping: step 7 of 100
> steplimit: 100 x: -1 y: -1 pos: 1 dx: 0 dy -1
> Walking from (XXX) to (XXX) for approx. 10.0sec
> Finished walking
> (XXX)
> Something rustles nearby!
> A Wild Rattata appeared! [CP81]
> Captured Rattata! [CP81] - exchanging for candy
> Evolve failed... Exchange !
> Exchanged successfuly!
> A Wild Staryu appeared! [CP134]
> Captured Staryu! [CP134]
> A Wild Spearow appeared! [CP66]
> Captured Spearow! [CP66] - exchanging for candy
> Evolve failed... Exchange !
> Exchanged successfuly!

Edit: sorry I'm too lazy to Pull Request...

**Comment by surfaace** [comment]
function added
