### ISSUE TITLE
release_config.json clarification.

### ISSUE THREAD

**Issue by jplusc** [PokemonGoF/PokemonGo-Bot#820]
### Expected Behavior

The "My Pokemon" configured section of release_config.json is honored during config.json.initial_transfer

### Actual Behavior
config.json.initial_transfer only honors the CP value given

### Other Information

Is there an option I am missing?  I know --initial_transfer was added well before the IV logic, so I really didn't expect to to work,  but is the "My Pokemon" section of release_config.json used by anything in the current bot?  Thanks.

(using dev branch)

**Comment by surfaace** [comment]
check release_config.json.example, but "my pokemon" is a pokemon name, such as "dog" or "cat"

**Comment by jplusc** [comment]
are you thinking of the exceptions list?

example "My Pokemon" section:
"My Pokemon": {
		"release_under_cp": 0,
		"release_under_iv": 0.5,
		"cp_iv_logic": "or"

**Comment by surfaace** [comment]
release_config and config is merged, new examples added. please check them and open new issue if you still have a problem
