### ISSUE TITLE
Just a suggest

### ISSUE THREAD

**Issue by BeginnerSlob** [PokemonGoF/PokemonGo-Bot#824]
I found this can show IVs when encountering wilds.
so I think this may can show Pokemons who i already have. This can help me filter Pokemons.
My English is poor.xD

**Comment by Saturate** [comment]
So what's the suggestion? :)

**Comment by eggins** [comment]
lmao

**Comment by BeginnerSlob** [comment]
add a function to show Pokemons IVs

**Comment by widnyana** [comment]
@BeginnerSlob @Saturate how about adding an option to choose which one to keep and transfer the other?

I'm thinking about an ability to compare IV from the newly captured Pokemon with the one we already have and automatically choose between them. 

I didnt really know what those number mean btw, the idea just pop up in my mind when reading this thread.

**Comment by surfaace** [comment]
This function has been added, please check config.json.examples from dev branch

**Comment by BeginnerSlob** [comment]
I'm sorry about that i can't find the option which can let me know my Pokemons' IVs
