### ISSUE TITLE
Hangs after walking to XXXXX until Ctrl + C is pressed to resume

### ISSUE THREAD

**Issue by iggut** [PokemonGoF/PokemonGo-Bot#827]
### Expected Behavior
Going to the next PokeStop and catching pokemon on the go

### Actual Behavior
Bot hangs at Walking to XXXXXXXXX until I press Ctrl + C then it immediately starts encountering and catching pokemon and resumes running fine. It then hangs again after a couple minutes of running perfectly. Same way to kick it back into action.

### Steps to Reproduce
Just let the bot run for 10 min to an hour and it hangs at a Walking to XXXXX until Ctrl + C is presset to resume for some reason.

### Other Information
OS:  Win 10 64bit
Running Dev version

**Comment by iggut** [comment]
I have not tried pressing anything else on the keyboard. Just though that it was the ctrl +c that woke it up, but might just be any keyboard activity. Will post update when it hangs again

**Comment by afro001** [comment]
CTRL+Z is also working and more safe, because sometimes when nothing was happening for a long time I pressed CTRL+C and accidentally stopped the script. With CTRL+Z there is no such problem. If there is a freeze - it starts the script. If everything is ok - nothing happens.
How to get rid of these freezes? Windows 10, 64 bit here.

**Comment by iggut** [comment]
I can't figure out what causes it. Since right now I did nothing special and the bot has been running since it froze up when I finally posted this issue.

**Comment by Reaver01** [comment]
http://stackoverflow.com/questions/33883530/why-is-my-command-prompt-freezing-on-windows-10

As solution here

**Comment by surfaace** [comment]
not related to code, related to how cmd works by default in win10

**Comment by bsjpark** [comment]
I am not sure if this will reopen this.
I am seeing exact same behavior on OSX El Capitan V10.11.5 Console as well.
Does anyone else see this?
