### ISSUE TITLE
Doesn't catch any pokemon

### ISSUE THREAD

**Issue by chimeno** [PokemonGoF/PokemonGo-Bot#83]
Using last commit in master branch.
````python pokecli.py -a google -u xx@gmail.com -p xx --location "xxx" -c 100````
All the loops have the same final:
`Something rustles nearby!
A Wild Sandshrew appeared! [CP92]`

**Comment by Bonfire** [comment]
You ran out of pokeballs. Spin pokestops to obtain more.

**Comment by Roydeking52** [comment]
i have the same problem i have 52x poke balls

**Comment by chimeno** [comment]
I have 111x poke balls, but still have the problem :(

**Comment by Bonfire** [comment]
I say just wait until the refactor and see if the issue persists.

**Comment by Boren** [comment]
You're probably softbanned. Try playing from your phone and see what happens.

**Comment by MERR0N** [comment]
I have same problem. All pokemons run out

**Comment by Roydeking52** [comment]
i can still play, i see pokemons on the map but theye are not in range

**Comment by chimeno** [comment]
I would say i'm softbanned, I've tried two with my phone and they also run away.
Note: I run the script first time for a minute and it catched 5 pokemon and released them.
Be careful!

**Comment by douglascamata** [comment]
@chimeno you're probably soft banned. The script will release ALL pokemons you have which are under the configured CP, even the ones you already captured and are with you, so be careful. I'll try to fix this behaviour asap, because it's a bit dangerous.

**Comment by chimeno** [comment]
@douglascamata Yep, after tried catching 6 pokemons, all of them run away playing on the phone. So yes, soft banned.
- That would be a great idea, the default values are quite dangerous.

**Comment by whiterabbit00** [comment]
Probably softban, you set gps location different from original location, you are softbanned for 15 min up to 2 hour, TO DO: remains at current location and wait as long as you are unbanned
This is my experience

**Comment by dragonalvaro** [comment]
it's the "-s" command broken? How can I set the bot to catch pokemons and spin forts?

**Comment by maddo7** [comment]
I think currently that's not possible. For me I didn't see the bot catching pokemon while -s was set.
If not the bot does capture pokemon but it doesn't seem to work properly. I often see outputs like

> [x] Found pokemon at distance 436.160820117m
> [#] Walking from (48.763101249641515, 9.166192318864447) to (48.763101249641515, 9.166192318864447) for approx. 0.0 seconds
> [#] Finished walking to (48.763101249641515, 9.166192318864447)
> [x] Walked to Pokemon
> [#] Walking from (48.763101249641515, 9.166192318864447) to (48.761009999999985, 9.167200000000001) for approx. 15.0 seconds
> walking hook  13 [#] Finished walking to (48.761009999999985, 9.167200000000001)
> (48.761009999999985, 9.167200000000001, 0)
> [#] Scanning area for objects (18 / 25)

It seems it sometimes walks to a pokemon without catching it.

**Comment by CapCap** [comment]
I'm having similar:

```
[x] Walked to Pokemon
steplimit: 25 x: 2 y: 2 pos: 1 dx: 0 dy 1
[#] Walking from (21.270442070738707, -157.81958036254952) to (21.270914899999998, -157.8169262) for approx. 97.0 seconds
walking hook  95 [#] Finished walking to (21.270914899999998, -157.8169262)
(21.270914899999998, -157.8169262, 0)
[#] Scanning area for objects (14 / 25)
map_cells are 21
steplimit: 25 x: 1 y: 2 pos: 1 dx: -1 dy 0
[#] Walking from (21.270914899999998, -157.8169262) to (21.2684149, -157.8169262) for approx. 96.0 seconds
walking hook  94 [#] Finished walking to (21.2684149, -157.8169262)
(21.2684149, -157.8169262, 0)
[#] Scanning area for objects (15 / 25)
steplimit: 25 x: 0 y: 2 pos: 1 dx: -1 dy 0
[#] Walking from (21.2684149, -157.8169262) to (21.2659149, -157.8169262) for approx. 96.0 seconds
walking hook  94 [#] Finished walking to (21.2659149, -157.8169262)
(21.2659149, -157.8169262, 0)
[#] Scanning area for objects (16 / 25)
steplimit: 25 x: -1 y: 2 pos: 1 dx: -1 dy 0
[#] Walking from (21.2659149, -157.8169262) to (21.263414899999997, -157.8169262) for approx. 96.0 seconds
walking hook  94 [#] Finished walking to (21.263414899999997, -157.8169262)
(21.263414899999997, -157.8169262, 0)
[#] Scanning area for objects (17 / 25)
steplimit: 25 x: -2 y: 2 pos: 1 dx: -1 dy 0
[#] Walking from (21.263414899999997, -157.8169262) to (21.2609149, -157.8169262) for approx. 96.0 seconds
walking hook  94 [#] Finished walking to (21.2609149, -157.8169262)
(21.2609149, -157.8169262, 0)
[#] Scanning area for objects (18 / 25)
steplimit: 25 x: -2 y: 1 pos: 1 dx: 0 dy -1
[#] Walking from (21.2609149, -157.8169262) to (21.2609149, -157.8194262) for approx. 90.0 seconds
walking hook  88 [#] Finished walking to (21.2609149, -157.8194262)
(21.2609149, -157.8194262, 0)
[#] Scanning area for objects (19 / 25)
steplimit: 25 x: -2 y: 0 pos: 1 dx: 0 dy -1
[#] Walking from (21.2609149, -157.8194262) to (21.2609149, -157.8219262) for approx. 90.0 seconds
walking hook  88 [#] Finished walking to (21.2609149, -157.8219262)
(21.2609149, -157.8219262, 0)
[#] Scanning area for objects (20 / 25)
steplimit: 25 x: -2 y: -1 pos: 1 dx: 0 dy -1
[#] Walking from (21.2609149, -157.8219262) to (21.2609149, -157.8244262) for approx. 90.0 seconds
walking hook  88 [#] Finished walking to (21.2609149, -157.8244262)
(21.2609149, -157.8244262, 0)
[#] Scanning area for objects (21 / 25)
steplimit: 25 x: -2 y: -2 pos: 1 dx: 0 dy -1
[#] Walking from (21.2609149, -157.8244262) to (21.2609149, -157.8269262) for approx. 90.0 seconds

```

**Comment by s1x** [comment]
The issue of @chimeno should be solved (softbanned). @CapCap if you continue having this issue please feel free to open a issue with a detailed description so we can help you.
