### ISSUE TITLE
Bot goes to distant forts before closer ones

### ISSUE THREAD

**Issue by ugurbor** [PokemonGoF/PokemonGo-Bot#830]
### Expected Behavior
Bot should go nearest available fort in farming area.

### Actual Behavior
Bot tries to go distant pokestops before very close ones when in "farming" mode. I believe there is something wrong with this decision algorithm. I will try to get a reproducable input.

### Steps to Reproduce
None.

### Other Information
OS: Debian 7 32bit

**Comment by ugurbor** [comment]
This two screenshots will give a clue about the issue I guess. There are very close pokestops where player is but takes almost the longest pokestop.

http://imgur.com/0jQxNDW
http://imgur.com/9xg0zBL

**Comment by bstpierr** [comment]
I also had this happen on the master branch.

<img width="495" alt="screen shot 2016-07-25 at 3 19 47 pm" src="https://cloud.githubusercontent.com/assets/464763/17114066/5a653dca-527b-11e6-9b1c-e12c7e9cf1f0.png">

**Comment by EvilSupahFly** [comment]
Even when `maxsteps 1` is used, it still does it.

**Comment by bstpierr** [comment]
I think the root cause might be that the bot only looks at stops that are within the current cell. If the nearest stop was actually in a neighboring cell, it's ignored (This might happen when you're close to the edge of a cell).
