### ISSUE TITLE
AttributeError: 'PokemonGoBot' object has no attribute 'position'

### ISSUE THREAD

**Issue by Orrielel** [PokemonGoF/PokemonGo-Bot#834]
### Expected Behavior
Normal startup procedure

### Actual Behavior
Crashes because `'PokemonGoBot' object has no attribute 'position'`
Somehow the position in config.json is ignored or can't be found

### Steps to Reproduce
Run bot using only config.json and no command line parameters

### Other Information
OS: Windows 7
Log:
> [18:16:16] PokemonGO Bot v1.0
> [18:16:16] No config argument specified, checking for /configs/config.json
> [18:16:16] Configuration initialized
> [18:16:17] [x] The location given using -l could not be parsed. Checking for a cached location.
> [18:16:17] Attempting login to Pokemon Go.
> Traceback (most recent call last):
>   File "pokecli.py", line 228, in <module>
>     main()
>   File "pokecli.py", line 214, in main
>     bot.start()
>   File "C:\Video Games\Pokemon Go\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 33, in start
>     self._setup_api()
>   File "C:\Video Games\Pokemon Go\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 269, in _setup_api
>     self.login()
>   File "C:\Video Games\Pokemon Go\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 240, in login
>     lat, lng = self.position[0:2]
> AttributeError: 'PokemonGoBot' object has no attribute 'position'

**Comment by Sekhmet** [comment]
Can you show your config.json with censored user data? And how are you starting bot?

**Comment by Orrielel** [comment]
Starting it with `python pokecli.py` in cmd.

> {
>     "auth_service": "google",
>     "username": "MAIL@gmail.com",
>     "password": "PW",
>     "location": "59.744329 10.204808",
>     "gmapkey": "GMAPKEY",
>     "maxsteps": 5,
>     "mode": "all",
>     "walk": 14.32,
>     "debug": false,
>     "test": false,
>     "initial_transfer": 0,
>     "location_cache": false,
>     "distance_unit": "km",
>     "item_filter": "101,102",
>     "evolve_all": "NONE",
>     "use_lucky_egg": false
> }

**Comment by Sekhmet** [comment]
Location has to be comma separated like this
`59.744329,10.204808`

**Comment by Orrielel** [comment]
Interesting, I've used space until now, but I should've guessed that.
Thanks though!
