### ISSUE TITLE
[Request] fancy progressbar when walking to Pokestop

### ISSUE THREAD

**Issue by dominikue** [PokemonGoF/PokemonGo-Bot#838]
I would like a fancy progressbar when the bot is walking to a Pokestop, so the user can see the walking progress.

 Maybe something like this 
![apt-progress](https://cloud.githubusercontent.com/assets/17249002/17109658/34792234-5299-11e6-8ab8-8d94948d4c10.png)

**Comment by ironbishop** [comment]
coming soon in #970

**Comment by dominikue** [comment]
nice :)
