### ISSUE TITLE
Documentation needed for parameters.

### ISSUE THREAD

**Issue by antfry** [PokemonGoF/PokemonGo-Bot#844]
Documentation needed for parameters.

**Comment by surfaace** [comment]
no parameters, use config.json.example found in configs

**Comment by antfry** [comment]
Their isn't example much info in the example file.

**Comment by antfry** [comment]
"max_steps": 5, , What this?
    "mode": "all", What modes?
    "walk": 4, , What's the fastest walking speed without being detected. 
    "initial_transfer": 0, ??

All things, I think need to be documented.

**Comment by surfaace** [comment]
please check #868
