### ISSUE TITLE
Indexerror: tuple index out of range after relogin

### ISSUE THREAD

**Issue by hklcf** [PokemonGoF/PokemonGo-Bot#846]
![image](https://cloud.githubusercontent.com/assets/410302/17112378/6b0eed1c-52d8-11e6-805e-f6a34668a53c.png)

5b74e198dd8ebde220eed966ae0aded1bc5b220e

**Comment by vanrzuf** [comment]
Get this too while ago, i was going to write new issue but saw this :D
![securecrt_2016-07-25_20-39-33](https://cloud.githubusercontent.com/assets/18649425/17112969/aaf25dd6-52a8-11e6-8eb2-bcd0cb534a5f.png)

**Comment by surfaace** [comment]
issue is tracked in #864
