### ISSUE TITLE
[Suggestion] Add a second account to scan the area

### ISSUE THREAD

**Issue by crusardri** [PokemonGoF/PokemonGo-Bot#861]
Like pokemon Go Map, a second account to scan the area and spot all pokemons, lured pokemons and pokestops, to say to the bot where search

**Comment by surfaace** [comment]
Are you talking about web now?

**Comment by Reaver01** [comment]
Think he means something to scout ahead. Seems unnecessary for a bot.

**Comment by MikeDX** [comment]
This would actually make a lot of sense, since you could have a second account that could "look" anywhere without the risk of being banned, which populates a database for the bot to read to farm the area. 

The best way of doing this would probably be to run PokemonGo-Map and have that populate a db, and have PokemonGo-Bot have the option to read this database to view the area without the risk of teleporting to scan and being banned.

**Comment by JulioMansilla** [comment]
A scout account would be a great way to avoid the main account getting banned for teleport/scan.

**Comment by crusardri** [comment]
@surfaace yes and no, the second account will show all pokemons in the action area of the bot in the web map and telling the bot the location of all pokemons

**Comment by jahkuba** [comment]
#1043 
Looks like these two are connected. This is might be a "killer feature".
Scan area with PockemonGo-Map and populate DB, then bot can quiery DB for name and location, teleport, wait for possible softban delay and catch poke. All you need is a populate "wanted list" and scan "nice spots".

**Comment by MikeDX** [comment]
Ok now here is an interesting find:

I have had a bot running on a dummy account, and the same account being used to populate a map. Interestingly the map scanner is in a different country to the bot worker (map in uk, bot in new york).

Not experienced any soft banning at all in the past 24 hours. 

I'm wondering whether the bans only take place if you try to spin / fight / catch in two different areas at once - or even on the same login token.

Saying that, PTC accounts are very easy to come by, so not that relevant.

**Comment by ewold** [comment]
Good idea, also include an option to get first the more rare pokemons in the neighbourhood and which should last long enough to get there ( walk speed ). Some calculations should be made here but it's not impossible.
