### ISSUE TITLE
[Suggestion] User specified maximum limit for specific items in inventory

### ISSUE THREAD

**Issue by chauhan-rahul** [PokemonGoF/PokemonGo-Bot#865]
### Expected Behavior
user can set limits for each item such that only specific amounts of certain stuff are kept like if we set 5 as maximum for potions then only 5 potions are kept rest will be deleted and if new arrive by pokestops they will be released too.
So the provided space is optimally used and redundant objects are released.

### Other Information
Status: In Progress
Git Commit: https://github.com/PokemonGoF/PokemonGo-Bot/commit/60af1a7f6907e37e7f84144facff84c6efd3d18c

**Comment by leadboots5** [comment]
you can set it to discard new items which can help keep potions in check assuming you don't want new ones. Not quite what you're asking for, but assuming you have some free space will take you a long time to fill up.

**Comment by chauhan-rahul** [comment]
what i have in mind is like i just want to keep 20 revive, 40 hyper potions i.e. less amount of less effective items like potions... since the bot keeps visiting pokestops then the best stuff should be kept more.

I got this request from quite some people.. so ive merged the initial changes to dev branch , where you can defined the maximum items for each item..

**Comment by sgitkene** [comment]
looks like this is available now in dev branch.

**Comment by chauhan-rahul** [comment]
Available in dev, closing!
