### ISSUE TITLE
Map GET location failed 404

### ISSUE THREAD

**Issue by bimahp** [PokemonGoF/PokemonGo-Bot#867]
### Expected Behavior
Map can show objects and track bot

### Actual Behavior
Only show image of pokemon that appeared next to bot

### Other Information
127.0.0.1 - - [26/Jul/2016 03:21:24] "GET /location-user@gmail.com.json HTTP/1.1" 404 -
127.0.0.1 - - [26/Jul/2016 03:21:24] "GET /catchable-user@gmail.com.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2016 03:21:25] code 404, message File not found
127.0.0.1 - - [26/Jul/2016 03:21:25] "GET /location-user@gmail.com.json HTTP/1.1" 404 -
127.0.0.1 - - [26/Jul/2016 03:21:25] "GET /catchable-user@gmail.com.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2016 03:21:26] code 404, message File not found
127.0.0.1 - - [26/Jul/2016 03:21:26] "GET /location-user@gmail.com.json HTTP/1.1" 404 -
127.0.0.1 - - [26/Jul/2016 03:21:26] "GET /catchable-user@gmail.com.json HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2016 03:21:27] code 404, message File not found
127.0.0.1 - - [26/Jul/2016 03:21:27] "GET /location-usere@gmail.com.json HTTP/1.1" 404 -
127.0.0.1 - - [26/Jul/2016 03:21:27] "GET /catchable-user@gmail.com.json HTTP/1.1" 200 -

OS: Win10
Branch: master
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by surfaace** [comment]
web site not related to our repo. have a look at https://github.com/PokemonGoF/PokemonGo-Bot/issues/867
