### ISSUE TITLE
teleport error

### ISSUE THREAD

**Issue by bebef1987** [PokemonGoF/PokemonGo-Bot#87]
Teleport is not working as it should

We are getting an error: "Need to move closer to Pokestop"

> 

Arrived at Pokestop
Now at Pokestop: Monumento Antimafia Falcone/Borsellino - Spinning...
- Loot: 
- 0 xp
- Nothing found.
may search too often, lets have a rest
need a rest
Found fort 0fef8a0f102d46c6bbea2e49d115cd18.16 at distance 190.755393617m
Need to move closer to Pokestop
Arrived at Pokestop
Now at Pokestop: Pontificio Santuario - Spinning...
- Loot: 
- 0 xp
- Nothing found.
may search too often, lets have a rest
need a rest
Something rustles nearby!
A Wild Pidgey appeared! [CP106]
Found fort 04793def3b0f4a8fb19817e7cf443465.16 at distance 94.7994370462m
Need to move closer to Pokestop
Arrived at Pokestop
Now at Pokestop: Monumento Alla Madonna Del Vesuvio - Spinning...
- Loot: 
- 0 xp
- Nothing found.
may search too often, lets have a rest
need a rest
Found fort b0b1ea3e64074ba99505fadd5a0cfca0.16 at distance 548.34068954m
Need to move closer to Pokestop
Arrived at Pokestop
Now at Pokestop: Ulivo Rotary Club - Spinning...
- Loot: 
- 0 xp
- Nothing found.
may search too often, lets have a rest
need a 

> rest

**Comment by douglascamata** [comment]
@bebef1987 you mind giving me the coordinates that lead to this pokestop?

**Comment by bebef1987** [comment]
"40.748957, 14.500514"

**Comment by douglascamata** [comment]
@bebef1987 seems like the spin_details dict is coming just with the result key. I'm debugging.

**Comment by fvorez** [comment]
Was having this same problem as well

**Comment by douglascamata** [comment]
These are the only things the server is sending after we send code to spin: 

```
{'unknown2': 8145806132888207460L, 'direction': 1, 'auth_ticket': {'expire_timestamp_ms': 1469140259345L, 'start': '4PADcRQyA+mWUaG7Yps0UsNOyoGtL1oALqQ4E29iQNkIvQ9az0rwXBXkAXhWgPQSi5mJk9sXzjIC\nW0kbn2QRKA==\n', 'end': 'wPEhiwxSKyCmuZ4UgtUDFw==\n'}, 'responses': {'FORT_SEARCH': {'result': 1}}}```

There's no information about exp or items o.o

**Comment by fvorez** [comment]
Seems like the bot just constantly looping, and spinning the same pokestops and getting that message back when the spot is on cooldown...if that made sense..

**Comment by douglascamata** [comment]
@fvorez maybe you're right. But the bot is supposed to walk. Even in the logs @bebef1987 provided it's walking from pokestop to pokestop.

**Comment by douglascamata** [comment]
btw, I just found the problem. Indeed the Pokestop is on cool down, but cool down detection code is not correct.

**Comment by douglascamata** [comment]
I can confirm teleporting also doesn't work here. The response for trying to spin the pokestop doesn't have any information about anything.

**Comment by douglascamata** [comment]
Crap, I think I got softbanned. HAHAHAHAHAH

**Comment by fvorez** [comment]
Hard to say, servers are being really shitty right now.

**Comment by s1x** [comment]
@bebef1987 This should be fixed with the servers up.
Please feel free the open a new issue when necessary!
