### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by nullrndtx** [PokemonGoF/PokemonGo-Bot#874]
Traceback (most recent call last):
  File "./pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/home/rndtx/PokemonGo-Bot/pokemongo_bot/__init__.py", line 85
    gyms = [gym for gym in cell['forts'] if 'gym_points' in gym]
                                                               ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by leadboots5** [comment]
I'm guessing you manually edited a file a did a poor job so indentations aren't correct.

**Comment by surfaace** [comment]
use template to report issue

**Comment by yqrashawn** [comment]
Use python 2.7. I change to 2.7 from 3.0. Solved this.
