### ISSUE TITLE
Erro trying to install the requirements

### ISSUE THREAD

**Issue by Wheaties466** [PokemonGoF/PokemonGo-Bot#876]
### Expected Behavior

it should install everything in the requirements file.

### Actual Behavior
   Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/root/PokemonGo-Bot/src/pgoapi/setup.py", line 9, in <module>

    install_reqs = parse_requirements(path_req, session=False)

TypeError: parse_requirements() got an unexpected keyword argument 'session'

this happens when trying to install the pgoapi requirments.

### Steps to Reproduce
clone the repo, pip install -r requirements.txt

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

debian VPS

**Comment by surfaace** [comment]
add git commit please

**Comment by Wheaties466** [comment]
git commit
# On branch dev
nothing to commit (working directory clean)

**Comment by surfaace** [comment]
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by Wheaties466** [comment]
This doesn't look right but here it is.

git log -n 1 --pretty=format:"%H"
9c89414ebf8c02ff0b712d4a05d3d83380e95a8f

**Comment by ritashugisha** [comment]
This was an issue with old versions of pip. Try updating.

```bash
sudo pip install --upgrade pip
```
