### ISSUE TITLE
[suggestions] Ideas to avoid getting detected

### ISSUE THREAD

**Issue by berend** [PokemonGoF/PokemonGo-Bot#88]
I have some ideas to avoid getting detected

* making sleep a bit variable (replacing all `sleep(x)`with `sleep_around(x)` with not sleeping x, but sleeping a rnd value between x-10% and x+10%
* doing different heartbeats (as of now, heartbeat does always the same, make this more fuzzy)
* do not walk straight lines from A to B
* be variable in speed (like sleep, move within x and x-10%, do not go above x, to keep within the speed limit for egg breading)

I would like to start, one by one, after refactoring is more or less done. (see https://github.com/PokemonGoF/PokemonGo-Bot/pull/84 and https://github.com/PokemonGoF/PokemonGo-Bot/pull/86)

**Comment by douglascamata** [comment]
@berend we can create our own wrapper of sleep to including a random factor. 

About walking in straight line though, it can be hard to calculate the size of the "walkable area" of the street to not jump outside it... I think this is tough to implement, although a very good idea.

Variable speed is also great! I would add even a chance to stop for `x (seconds) - random_factor` seconds.

**Comment by bebef1987** [comment]
maybe use gmaps to plot a route on know streets or something. Walking strait to the poi can be strange

**Comment by aconite33** [comment]
I've noticed just adding 15 second sleep greatly reduces chances of softbans.

**Comment by douglascamata** [comment]
@aconite33 15 seconds sleep at which party? Between each step?

**Comment by aconite33** [comment]
I put it right after "need a rest" in bot.py, line 46.

**Comment by douglascamata** [comment]
@aconite33 you mind creating a separate issue for this for better tracking? It's pretty easy to implement and I'll add it pretty soon with a configurable rest time through the command-line.

**Comment by berend** [comment]
more tomorrow.
yes, we should think about behaving more randomly. Being variable in speed also should include stops.

**Comment by msdrahcir** [comment]
Not sure if Niantec stores this information, but another thought is less consistent pokeball throwing.

**Comment by surfaace** [comment]
@aconite33 could you follow up on this, or confirm if it has been implemented please?
