### ISSUE TITLE
[request] Parrameter cp with Evolve mode

### ISSUE THREAD

**Issue by paledrewnem** [PokemonGoF/PokemonGo-Bot#884]
### Expected Behavior

To catch pokemons with evolve behaviour. If I have 60 pidgey candies then keep at least 5 pidgeys(with highest cp or VI) to evolve all at once in future. If should work along with the current release_config.  

In best situation you will have about 50 pidgeys, 30 rattatas ready to evolve and 5 drowzee and other pokemons with full filled bag.

### Actual Behavior

Pokemons are released when are too low.

Give a sign what do you think about. I can try to add it to current branch.

**Comment by Bramzor** [comment]
To know which pokemon to evolve/release, you should consider both CP and VI . Possibly by doing ordering them on CP x VI

**Comment by DrSardjoe** [comment]
This is a feature I desperately need. What we have to do now is set it so it won't release any pidgeys, rattatas etc. to only end up with either too few pokemon for the candy or the other way around.
