### ISSUE TITLE
Provide Sane Defaults

### ISSUE THREAD

**Issue by atomaka** [PokemonGoF/PokemonGo-Bot#891]
Perhaps the initial config files would be more useful if they provided some sane defaults for users.  It doesn't seem the case right now.

**Comment by Skeyelab** [comment]
Perhaps you should describe why they are not "sane" and suggest a solution.

**Comment by atomaka** [comment]
Hah. It's cool.

**Comment by Skeyelab** [comment]
I was serious.  It would be helpful to hear what you think would improve the project.
