### ISSUE TITLE
The Readme or Get started not really clear

### ISSUE THREAD

**Issue by kimdotnet** [PokemonGoF/PokemonGo-Bot#895]
I already complete installation steps, but know I don't know how to use the Bot.
Can someone explain to me, how to use the bot?

### Other Information
OS: 
WINDOWS 10 64 BIT

**Comment by Fyreek** [comment]
As the Readme tells you, you should edit the config.json with your credentials. 
After that start pokecli.py

**Comment by Fyreek** [comment]
What os are you using, don't know how to do it for windows, but for everything else it is 
"python pokecly.py"

**Comment by kimdotnet** [comment]
Wow great it works, thanks buddy.
And I have another question what is the funtion of the map in the web folder?
and how to use the map?

**Comment by abscondite** [comment]
You can see that [here](https://github.com/OpenPoGo/OpenPoGoWeb/tree/dc742c598a2636337bd358dae8a558ef02159e8e)

**Comment by kimdotnet** [comment]
Thank you for the answer, but after I deployed web server and trying to open the map. I got 404 in almost every request.

I already fill userdata.js
```
var users = ["myemail@gmail.com"]
var userZoom = true;
var userFollow = true;
var imageExt = ".png";
var gMapsAPIKey = "Some Random Alphabetical";
```

Is my usersdata.js correct?

**Comment by maestroi** [comment]
@kimdotnet 
@endeavor7 
please do the following steps:

1. Navigate to the web folder.
2. Open a file and put in `{}`.
3. Save the file as `catchable-YOUREMAIL@gmail.com.json`.
4. Restart webservice.

Repeat steps for location.json:

1. Navigate to the web folder.
2. Open a file and put in `{}`.
3. Save the file as `location-YOUREMAIL@gmail.com.json`.
4. Restart webservice.

**Comment by Teodor-Dobrev** [comment]
Do you know how can I change the huge time consuming movement between the Pokestops to become faster? That:"Need to move closer to Pokestop" is taking 5 minutes. Is there anything I can do about it?

**Comment by abscondite** [comment]
@Teodor-Dobrev you can change parameter `walk` in `config.json`
`"walk": 4.16`
4.16 set as default because it is maximum for keep incubators working.
But do you really want to do it? i think it can lead to ban.

**Comment by Fyreek** [comment]
I don't think you will get Banned for that, because walking faster is just like driving a car. As long as you dont Teleport around, it should be fine.

**Comment by TheGoldenXY** [comment]
Please use the Wiki. Closing this for now.

/closed
