### ISSUE TITLE
[Loop] Inventory is full, switching to catch mode...

### ISSUE THREAD

**Issue by hklcf** [PokemonGoF/PokemonGo-Bot#899]
![image](https://cloud.githubusercontent.com/assets/410302/17124750/f6e667c4-531f-11e6-8593-14258a74612b.png)

ff665d625c028d490fe9d2fd4e6b0b8c10a2d9c9

**Comment by TCB13** [comment]
In my case after 2 or 3 erros like that it really changes to catch mode.

**Comment by giarmul** [comment]
Have same issue, have tried more than 5 times, still trying to spin

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
