### ISSUE TITLE
Issue: catch-ignore.yml not working on dev

### ISSUE THREAD

**Issue by TCB13** [PokemonGoF/PokemonGo-Bot#900]
### Expected Behavior

Adding a the file `data/catch-ignore.yml` with a list of pokemons would cause the bot to ignore then and not try to catch it.

### Actual Behavior

Bot still catches them.

### Steps to Reproduce

Create the file `data/catch-ignore.yml` and run the bot. 

### Other Information
OS: Debian / OSX
Git Commit: ff665d625c028d490fe9d2fd4e6b0b8c10a2d9c9

**Comment by SteffanLong** [comment]
This file has been removed. Please use the "catch" block in your config.json to configure what will be captured. Instructions in the readme.

**Comment by TCB13** [comment]
@SteffanLong thanks. Documentation should be updated accordingly.

**Comment by TheGoldenXY** [comment]
This issue has been resolved.

/closed
