### ISSUE TITLE
server busy

### ISSUE THREAD

**Issue by screamolic** [PokemonGoF/PokemonGo-Bot#901]
i got server busy on terminal.

**Comment by abscondite** [comment]
Which type of authentication do you use, PTC or Google?

**Comment by screamolic** [comment]
google

**Comment by abscondite** [comment]
I was experienced the same problem when trying to use Google account to sign in. Do you use two-factor authentication in your Google account?

**Comment by screamolic** [comment]
nope.

**Comment by abscondite** [comment]
I've just checked, in my case disabling the two-factor authentication helps. Did you try to use PTC to sign in?

**Comment by hklcf** [comment]
setup app password to bypass two-factor authentication

**Comment by abscondite** [comment]
@hklcf maybe we need to add correct error messages when using Google account?

**Comment by screamolic** [comment]
yeah. its blocked by authentication

**Comment by abscondite** [comment]
@screamolic [solution](https://github.com/PokemonGoF/PokemonGo-Bot#google-login-issues-login-error-server-busy)

**Comment by hklcf** [comment]
https://support.google.com/accounts/answer/185833?hl=en

**Comment by screamolic** [comment]
@hklcf link error. and i cant find the aapps on my list.

**Comment by TheGoldenXY** [comment]
Tutorial on how to fix this issue here: https://github.com/PokemonGoF/PokemonGo-Bot#google-login-issues-login-error-server-busy

Closing this for now.

/closed
