### ISSUE TITLE
stay in 1 location

### ISSUE THREAD

**Issue by nadarehime** [PokemonGoF/PokemonGo-Bot#902]
can make stay in 1 location?

**Comment by dmdque** [comment]
Would be very useful since there are some known locations with frequent good spawns. This feature would require the ability to spin pokestops and engage pokemon from a distance.

**Comment by linanqiu** [comment]
Yeah I'm thinking of coding an algo to generate a cycle optimal for around 5+min so that you can just travel in circles around the same area. Is anyone doing this @pokemongo-dev

**Comment by nadarehime** [comment]
actually there's nothing do anything for walk random

i hope can stay in 1 location
in scan circle have 3 or 4 pokestop for farming poke

**Comment by ironbishop** [comment]
similar to existing #95 and #830 , oh, and  #334

**Comment by linanqiu** [comment]
close this
