### ISSUE TITLE
Do not create a location-username.json file

### ISSUE THREAD

**Issue by Gustik** [PokemonGoF/PokemonGo-Bot#905]
### Expected Behavior
It must show the location on the map

### Actual Behavior
Do not create a location-username.json file

### Steps to Reproduce
run python -m SimpleHTTPServer 5000 and open browser

### Other Information
OS: Ubuntu 14.04.4 LTS
Git Commit: dc742c598a2636337bd358dae8a558ef02159e8e

**Comment by Gustik** [comment]
fixed manually create an empty file location-username.json

**Comment by Blogshot** [comment]
That is more than a workaround instead of a fix.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
