### ISSUE TITLE
Missing info on -c option

### ISSUE THREAD

**Issue by TCB13** [PokemonGoF/PokemonGo-Bot#907]
Hello, first of all many thanks for the great work.

I was used to pass the option `-c 130` to the bot in order to discard all pokemon with CP < 130 if the storage was full.

Right now on the latest `dev` how are we supposed to set this parameter?

Thank you.

**Comment by MonsieurClavet** [comment]
the dev uses the config file located under configs/
you can check example here https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/configs/config.json.example

**Comment by SteffanLong** [comment]
Initial transfer is being removed. Please use a "release" block in your config.json. Instructions are in the readme and example files.

**Comment by TCB13** [comment]
@SteffanLong I'm sure if I understand the logic of the `release` block.

The documentation doesn't explain that much what happens when used. Take this example of my `config.json`:

```
"catch": {
      "any": {
      		"catch_above_cp": 0, 
      		"catch_above_iv": 0,
      		"logic": "or"
      	}
    },
    "release": {
      "any": {
      		"release_below_cp": 1000, 
      		"release_below_iv": 0.7,
      		"logic": "and"
      	}
    }
```

My objective is to:

Catch any Pokemon (to gain XP);
Transfer to the professor every Pokemon with CP < 1000 and IV < 0.7 right after the capture.

How can I make sure once my Pokemon storage I can get rid of all Pokemon with, for instance, a CP < 1100 without the initial transfer?

Thank you.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
