### ISSUE TITLE
Raspberry Pi Syntax Error

### ISSUE THREAD

**Issue by muhammetkucuk** [PokemonGoF/PokemonGo-Bot#919]
Hello, I followed steps from documentation actually python is chinese for me . 
I'm calling script with command: pytgon pokecli.py

##Terminal Output:
pi@raspberrypi:~/PokemonGo-Bot $ python pokecli.py 
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/home/pi/PokemonGo-Bot/pokemongo_bot/__init__.py", line 13, in <module>
    from pgoapi import PGoApi
  File "/home/pi/PokemonGo-Bot/src/pgoapi/pgoapi/__init__.py", line 19, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/home/pi/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/home/pi/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 40, in <module>
    from POGOProtos.Networking.Envelopes_pb2 import RequestEnvelope
  File "/home/pi/PokemonGo-Bot/src/pgoapi/pgoapi/protos/POGOProtos/Networking/Envelopes_pb2.py", line 16, in <module>
    from POGOProtos.Networking import Requests_pb2 as POGOProtos_dot_Networking_dot_Requests__pb2
  File "/home/pi/PokemonGo-Bot/src/pgoapi/pgoapi/protos/POGOProtos/Networking/Requests_pb2.py", line 23, in <module>
    ENCOUNTER\x10\x91\x01\x12!\n\x1c\x43OLLECT_DAILY_DEFENDER_BONUS\x10\x92\x01\x12\x14\n\x0fUPGRADE_POKEMON\x10\x93\x01\x12\x19\n\x14SET_FAVORITE_POKEMON\x10\x94\x01\x12\x15\n\x10NICKNAME_POKEMON\x10\x95\x01\x12\x10\n\x0b\x45QUIP_BADGE\x10\x96\x01\x12\x19\n\x14SET_CONTACT_SETTINGS\x10\x97\x01\x12\x15\n\x10GET_ASSET_DIGEST\x10\xac\x02\x12\x16\n\x11GET_DOWNLOAD_URLS\x10\xad\x02\x12\x1c\n\x17GET_SUGGESTED_CODENAMES\x10\x91\x03\x12\x1d\n\x18\x43HECK_CODENAME_AVAILABLE\x10\x92\x03\x12\x13\n\x0e\x43LAIM_CODENAME\x10\x93\x03\x12\x0f\n\nSET_AVATAR\x10\x94\x03\x12\x14\n\x0fSET_PLAYER_TEAM\x10\x95\x03\x12\x1b\n\x16MARK_TUTORIAL_COMPLETE\x10\x96\x03\x12\x16\n\x11LOAD_SPAWN_POINTS\x10\xf4\x03\x12\t\n\x04\x45\x43HO\x10\x9a\x05\x12\x1b\n\x16\x44\x45\x42UG_UPDATE_INVENTORY\x10\xbc\x05\x12\x18\n\x13\x44\x45\x42UG_DELETE_PLAYER\x10\xbd\x05\x12\x17\n\x12SFIDA_REGISTRATION\x10\xa0\x06\x12\x15\n\x10SFIDA_ACTION_LOG\x10\xa1\x06\x12\x18\n\x13SFIDA_CERTIFICATION\x10\xa2\x06\x12\x11\n\x0cSFIDA_UPDATE\x10\xa3\x06\x12\x11\n\x0cSFIDA_ACTION\x10\xa4\x06\x12\x11\n\x0cSFIDA_DOWSER\x10\xa5\x06\x12\x12\n\rSFIDA_CAPTURE\x10\xa6\x06\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'

### Other Information
OS: Raspbian Jessie
Python version:: 2.7.12
Latest pip installed
virtualenv installed
protobuf installed
Master branch used

**Comment by heihachi** [comment]
sudo apt-get install protobuf-compiler and then run pip inside a virtualenv and should work

**Comment by muhammetkucuk** [comment]
Thank you I'll check it after I got home.

**Comment by tpmodding** [comment]
@heihachi i tried it, doesnt work :( im inside the virtualenv but i get this error:

Installed /tmp/pip-build-WRZGZh/protobuf-to-dict/nose-1.3.7-py2.7.egg
    Searching for protobuf>=2.3.0
    Reading https://pypi.python.org/simple/protobuf/
    Best match: protobuf 3.0.0b4
    Downloading https://pypi.python.org/packages/8b/fa/2a4f48c3579a5d88bfe4e8408227cb12731efcb30da4ba423cf115a1d320/protobuf-3.0.0b4-py2.7.egg#md5=e29a69cb89fff0bc39f099e705e4e93e
    Processing protobuf-3.0.0b4-py2.7.egg
    creating /tmp/pip-build-WRZGZh/protobuf-to-dict/protobuf-3.0.0b4-py2.7.egg
    Extracting protobuf-3.0.0b4-py2.7.egg to /tmp/pip-build-WRZGZh/protobuf-to-dict
    
    Installed /tmp/pip-build-WRZGZh/protobuf-to-dict/protobuf-3.0.0b4-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-WRZGZh/protobuf-to-dict/setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 262, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 287, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 631, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 867, in best_match
        dist = working_set.find(req)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 509, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (six 1.8.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.9'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-WRZGZh/protobuf-to-dict/
(PokemonGo-Bot) pi@raspberrypi:~/PokemonGo-Bot $

**Comment by heihachi** [comment]
pip install --update six

it has a older version of six installed

**Comment by bloigge** [comment]
It's pip install six --upgrade

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
