### ISSUE TITLE
[Request] Adopt same configuration for both initial_transfer and release

### ISSUE THREAD

**Issue by Anyrainel** [PokemonGoF/PokemonGo-Bot#921]
### Motivation
Right now the initial transfer is not much configurable. However, organizing the inventory is always a headache. I'm also afraid to set the single CP threshold too high so that I lose some rare pokemons. So a better bot behavior could be really helpful.
Since the standard for "keep" should be similar for initially owned or newly caught pokemon, I think it is reasonable to reuse the configuration for "release".
Also I have a question, could manually renaming pokemon prevent the bot from transferring it? I'm not sure of the current matching pattern, but I think this way to protect some certain pokemons could be helpful.
I have a strong sense that this could be very helpful for users play both on phone and bot.
### Summary
1. use the "release" configuration for "initial_transfer" (and turn the old CP threshold to a bool switch).
2. (ignore if already exists) prevent renamed pokemon from being transferred

**Comment by SteffanLong** [comment]
We actually have this coded and it will be in dev branch very soon.

**Comment by Anyrainel** [comment]
Thanks!
