### ISSUE TITLE
Error starting dev bot

### ISSUE THREAD

**Issue by alexanderrock** [PokemonGoF/PokemonGo-Bot#928]
Commit: b93db8f5f5cb785bec0c362037755b751c7b47a2

Error:
```
./pokecli.py -cf configs/config_ptc.json
[08:17:22] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "./pokecli.py", line 232, in <module>
    main()
  File "./pokecli.py", line 211, in main
    config = init_config()
  File "./pokecli.py", line 56, in init_config
    load.update(json.load(data))
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 22 column 5 (char 637)
```

Config File:
`{
    "auth_service": "ptc",
    "username": "xxxx",
    "password": "xxxx",
    "location": "Buchhornplatz, Friedrichshafen, DE",
    "gmapkey": "xxxx",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": ["101","102","103","104","201","701"],
    "evolve_all": "NONE",
    "cp_min": 300,
    "use_lucky_egg": false,
    "evolve_captured": false,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
    }
}
`

**Comment by Foxy1990** [comment]
your json is wrong

`{
	"auth_service": "ptc",
	"username": "xxxx",
	"password": "xxxx",
	"location": "Buchhornplatz, Friedrichshafen, DE",
	"gmapkey": "xxxx",
	"max_steps": 5,
	"mode": "all",
	"walk": 4.16,
	"debug": false,
	"test": false,
	"initial_transfer": 0,
	"location_cache": true,
	"distance_unit": "km",
	"item_filter": ["101", "102", "103", "104", "201", "701"],
	"evolve_all": "NONE",
	"cp_min": 300,
	"use_lucky_egg": false,
	"evolve_captured": false,
	"catch": {
		"any": {
			"catch_above_cp": 0,
			"catch_above_iv": 0,
			"logic": "or"
		}
	},
	"release": {
		"any": {
			"release_below_cp": 0,
			"release_below_iv": 0,
			"logic": "or"
		}
	}
}`

**Comment by anhkhoi** [comment]
Same error with me

**Comment by anhkhoi** [comment]
My error
`Traceback (most recent call last):
  File "pokecli.py", line 232, in <module>
    main()
  File "pokecli.py", line 223, in main
    bot.take_step()
  File "/Users/macmini02/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 40, in take_step
    self.work_on_cell(cell, location)
  File "/Users/macmini02/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 211, in work_on_cell
    hack_chain = worker.work()
  File "/Users/macmini02/Desktop/PokemonGo-Bot/pokemongo_bot/cell_workers/seen_fort_worker.py", line 107, in work
    raise RuntimeError(message)
RuntimeError: Stopped at Pokestop and did not find experience, items or information about the stop cooldown. You are probably softbanned. Try to play on your phone, if pokemons always ran away and you find nothing in PokeStops you are indeed softbanned. Please try again in a few hours.`

**Comment by tstumm** [comment]
@anhkhoi You are softbanned try again later.

@alexanderrock Your JSON has a faulty syntax as @Foxy1990 said.

**Comment by AndyBean** [comment]
I see this error frequently without the nice softban messages. Part of the confusion in the error is that it implies that something is wrong in other files that have not been touched. It seems we could replace the messaging with a note stating that either:
1. a person's config is syntactically incorrect
2. they have been soft banned
3. their login credentials are invalid ?

It seems we know when they have been soft banned so it can be streamlined even further.
