### ISSUE TITLE
Change name on catching pokemon

### ISSUE THREAD

**Issue by demirb** [PokemonGoF/PokemonGo-Bot#930]
### Expected Behavior
When the pokemon is caught and not transferred it should change the name of the pokemon if it has a high IV rating. If the pokemon has ex: IV 0.92 stamina: 12, attack:15, def: 11 then this should be displayed in the pokemons name as 0.92 s12,a15,d11

### Actual Behavior
Pokemons name doesnt change

### Other Information
If you guys can make a change name function, I can do the rest.
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
