### ISSUE TITLE
Do not transfer name changed pokemons

### ISSUE THREAD

**Issue by demirb** [PokemonGoF/PokemonGo-Bot#932]
### Expected Behavior
When the transfer function runs, it should leave alone the pokemons whos names have been changed. 

### Actual Behavior
When the transfer function runs, it releases all duplicate pokemons. I had 2 flareons named Pyro and it transfered the lower cp one. I needed & wanted to keep that one. 

### Steps to Reproduce
Have 3 dragonites in your bag. Fill out your pokemon capacity, watch as 2 of your dragonites gets transfered.

### Other Information
This will be a lot stronger function when [this issue](https://github.com/PokemonGoF/PokemonGo-Bot/issues/930) is made.

**Comment by TCB13** [comment]
Check "Transfer limit" as #871. It might be enough for you in a near future!

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
