### ISSUE TITLE
IndexError after re-logging in

### ISSUE THREAD

**Issue by Anyrainel** [PokemonGoF/PokemonGo-Bot#933]
### Expected Behavior
Bot works as before.

### Actual Behavior
![image](https://cloud.githubusercontent.com/assets/3783449/17128452/c21a3254-52da-11e6-96a4-d3a7bb839641.png)

Actually I'm also curious about why this "slate" happens, it often occurs to me after running bot for hours.

### Steps to Reproduce
Run bot after like an hour or two

### Other Information
OS: Windows 10

**Comment by hklcf** [comment]
#864

**Comment by tstumm** [comment]
Already fixed
