### ISSUE TITLE
Not catching any pokemons?

### ISSUE THREAD

**Issue by phillipj123123** [PokemonGoF/PokemonGo-Bot#94]
When i log back in it hasnt catched anything. Am i using it wrong? 
Usage: pokecli.py -a ptc -u username -p password -l current  -d -t -s -c 1 

I just want it to stand at my current position and catch pokemons. I know for a fact that theres is some since they are there everytime i log in

**Comment by douglascamata** [comment]
"current" is not a supported location string, if I recall correctly. You may want to get you GPS coordinates and use them like this: `-l "lat, long"`. Also you're using the `-t` flag, which is for testing purposes. And by using `-s` it will only search for PokeStops.

**Comment by tkien212** [comment]
so if we use -s, it will only go for PokeStops
if no -s, then only pokemon?

**Comment by s1x** [comment]
@phillipj123123 
Please feel free the open a new issue if you still have problems. You can use the -lc flag for the last position or as @douglascamata mentioned the -l flag.
