### ISSUE TITLE
Do not starting - ./run.sh or pokecli.py

### ISSUE THREAD

**Issue by msm2k11** [PokemonGoF/PokemonGo-Bot#940]
### Actual Behavior
I have checked both repositories - master and dev. Here now the "dev" problem. Installation without any errors - all ok. but if i run the ./run.sh or manual over pokecli.py --config ......, not working. See message below:
```
root@glftpd:/var/www/PokemonGo-Bot# ./run.sh
[09:53:24] PokemonGO Bot v1.0
Traceback (most recent call last):
  File "pokecli.py", line 236, in <module>
    main()
  File "pokecli.py", line 215, in main
    config = init_config()
  File "pokecli.py", line 56, in init_config
    load.update(json.load(data))
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 22 column 7 (char 587)
```

### Steps to Reproduce
Install like your Install-Guide for Linux/Dev Repository without optional packages.
No errors while installation.

### Other Information
OS: Debian GNU/Linux 8.5 (jessie) x64
Git Commit: 8c540c9c9cd09a4e7b7c29cc0aac5f53181ed39b

**Comment by hklcf** [comment]
please check ypur config.json file

**Comment by msm2k11** [comment]
here my config.json
username, password and gmapkey edited below. password have a "!" inside.

`{
    "auth_service": "google",
    "username": "my.username",
    "password": "my!Passw0rd!321",
    "location": "49.792464,9.940243",
    "gmapkey": "AIzaSsAamye3omVuT3jhCdP.....7028fEF2d8U",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "",
    "evolve_all": "NONE",
    "cp_min": 300,
    "use_lucky_egg": false,
    "evolve_captured": false,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      // "Rattata": { "always_catch" : true }
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"},
      // "Rattata": { "always_release" : true }
    }
}
`

**Comment by rwrwrwrwrw** [comment]
If you're **not** using the Pokemon-specific catch/release options, delete the commas at the end of lines 21 & 25 in your config.json

**Comment by msm2k11** [comment]
@rwrwrwrwrw
done, but same output-message as in first post

**Comment by hklcf** [comment]
`{
    "auth_service": "google",
    "username": "YOUR_USERNAME",
    "password": "YOUR_PASSWORD",
    "location": "SOME_LOCATION",
    "gmapkey": "GOOGLE_MAPS_API_KEY",
    "max_steps": 5,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "",
    "evolve_all": "NONE",
    "cp_min": 300,
    "use_lucky_egg": false,
    "evolve_captured": false,
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"}
    },
    "release": {
      "any": {"release_below_cp": 0, "release_below_iv": 0, "logic": "or"}
    }
}`

**Comment by rwrwrwrwrw** [comment]
woops yeah you'll need to delete the "// Rattata" lines too

**Comment by msm2k11** [comment]
good work @rwrwrwrwrw :) working now.

got now "Login Error, server busy" .... possible because i have a "!" in password?

**Comment by rwrwrwrwrw** [comment]
Maybe? I have a "!" in my password as well and it works but I'm using PTC instead of Google for auth

**Comment by Aelirik** [comment]
Setup an app password under your google account and it will work just fine

**Comment by msm2k11** [comment]
ok nice, working now :) thanks a lot guys!
