### ISSUE TITLE
No catching pokemons and jump

### ISSUE THREAD

**Issue by StarForser** [PokemonGoF/PokemonGo-Bot#942]
### Actual Behavior

![3](https://cloud.githubusercontent.com/assets/17098307/17130877/6d6ce726-5323-11e6-9927-09735646f87a.jpg)

### Steps to Reproduce

**Config** 

{
    "auth_service": "google",
    "username": "",
    "password": "",
    "gmapkey": "",
    "max_steps": 10,
    "mode": "all",
    "walk": 4.16,
    "debug": false,
    "test": false,
    "initial_transfer": 0,
    "location_cache": true,
    "distance_unit": "km",
    "item_filter": "201",
    "evolve_all": "NONE",
    "cp_min": 300,
    "use_lucky_egg": false,
    "evolve_captured": false,
	"catch": {
      "any": {"catch_above_cp": 10, "catch_above_iv": 0.1, "logic": "or"}
    },
    "release": {
      "any": {"release_below_cp": 1000, "release_below_iv": 0.8, "logic": "or"},
      "Rattata": { "always_release" : false },
	  "Pidgey": { "always_release" : false },
	  "Weedle": { "always_release" : false }
    }
}

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by qfdk** [comment]
I confirm this bug,  walk around and  catch noting.

**Comment by tstumm** [comment]
The Bot is NOT jumping around (look at the destinations). The log messages are a bit confusing. Switch to newest `dev` which fixes those messages. The fact that the bot is not catching pokemon while farming is known and the bugfix is already in the works.

**Comment by bstpierr** [comment]
Not catching any Pokemon bug: https://github.com/PokemonGoF/PokemonGo-Bot/issues/821

**Comment by H4xXx0r** [comment]
Clean up your old clone.

**Comment by s1x** [comment]
As mentioned by @bstpierr this is a duplicate.
