### ISSUE TITLE
Stop the bot from walking on water

### ISSUE THREAD

**Issue by Saturate** [PokemonGoF/PokemonGo-Bot#944]
### Expected Behavior

It's not really expected to walk on water, I'm a pokémon trainer not Jesus.

### Actual Behavior

Does not care about water at all, just walks on it.

![jesus-man-bot](https://cloud.githubusercontent.com/assets/453018/17132563/9e26e246-5322-11e6-99b8-f2fe3b69a849.PNG)

**Comment by bloodhawk** [comment]
Why does it matter? You could be using a boat.

**Comment by Saturate** [comment]
I seem too looooove boats then, and I have a lot of them!

It matters as it's pretty easy to detect this is a bot, and we should try to avoid that. It's not the most important thing right now, but it's good to know for the future - and maybe someone with nothing to do can look into how you detect water with the Google Maps API :-)

**Comment by kaise123** [comment]
I feel like this could be a useful addition too, as when near water it does tend to cross it often, which could look odd to a bot-detection system.

However, I think simply setting the start location somewhere away from water is a fairly viable solution for now.

**Comment by Saturate** [comment]
@kaise123 That is a solution for now, but I think that there are other ways that are easier to detect so for now it's not so important.

**Comment by MeGaPk** [comment]
Maybe just get path by google api (from current point to next point) and walk by this path?

**Comment by Saturate** [comment]
Yes, that seems like a good way to do it, and would seem pretty human as well for bot detection.

**Comment by MeGaPk** [comment]
@Saturate and simulate not accurate gps signal :) Its very hard for detect more bots, maybe.

**Comment by mehdi-S** [comment]
i suggest to change the issue with an IMPROVEMENT tag

**Comment by TCB13** [comment]
Guys, really some people may care about this feature, other don't. If this gets implemented can you make it optional in a config like "traverses_everything". I really don't mind this behavior... Thanks!

**Comment by mehdi-S** [comment]
@Saturate question offtopic, how did you make your bot put a red dot on his path

**Comment by Saturate** [comment]
@mehdi-S Update the web submodule and it's a setting
