### ISSUE TITLE
Bot crashes after a few hours of uptime

### ISSUE THREAD

**Issue by TheGoldenXY** [PokemonGoF/PokemonGo-Bot#948]
### Expected Behavior
The bot shouldn't crash at all. It should be stable and run 24/7 without crashes.

### Actual Behavior
The bot crashes after a few hours uptime. It's crashing at different times. Sometimes 30 mins, 2 hours, etc etc.

http://m.imgur.com/rZ0Z2D5

### Steps to Reproduce
Use the latest version and run the bot.

### Other Information
OS: Ubuntu 14.04
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
3aca6d798f8a3e173dce0beb7b13c9505cc5b251

**Comment by MeGaPk** [comment]
+1
I have same exception:
```
Traceback (most recent call last):
  File "./pokecli.py", line 220, in <module>
    main()
  File "./pokecli.py", line 211, in main
    bot.take_step()
  File "/home/server/PokemonGo-Bot/pokemongo_bot/__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "/home/server/PokemonGo-Bot/pokemongo_bot/stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "/home/server/PokemonGo-Bot/pokemongo_bot/stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "/home/server/PokemonGo-Bot/pokemongo_bot/__init__.py", line 93, in work_on_cell
    worker.work()
  File "/home/server/PokemonGo-Bot/pokemongo_bot/cell_workers/move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "/home/server/PokemonGo-Bot/pokemongo_bot/stepper.py", line 88, in _walk_to
    alt, False)
  File "/home/server/PokemonGo-Bot/pokemongo_bot/stepper.py", line 102, in _work_at_position
    response_dict = self.api.call()
  File "/home/server/PokemonGo-Bot/src/pgoapi/pgoapi/pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "/home/server/PokemonGo-Bot/src/pgoapi/pgoapi/rpc_api.py", line 98, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException
```

**Comment by tb87** [comment]
+1
Same here as well

[2016-07-26 21:02:40] [x] Using Pokeball (chance: 47.34%)... (55 left!)
[2016-07-26 21:02:42] [x] Captured Pidgey! [CP 155] [IV 0.29]
[2016-07-26 21:02:44] [#] Pidgey has been exchanged for candy!
Traceback (most recent call last):
  File "pokecli.py", line 220, in <module>
    main()
  File "pokecli.py", line 211, in main
    bot.take_step()
  File "C:\Python27\Download\PokemonGo-Bot\pokemongo_bot\__init__.py", line 36, in take_step
    self.stepper.take_step()
  File "C:\Python27\Download\PokemonGo-Bot\pokemongo_bot\stepper.py", line 62, in take_step
    self._work_at_position(position[0], position[1], position[2], True)
  File "C:\Python27\Download\PokemonGo-Bot\pokemongo_bot\stepper.py", line 139, in _work_at_position
    self.bot.work_on_cell(cell, position, pokemon_only)
  File "C:\Python27\Download\PokemonGo-Bot\pokemongo_bot\__init__.py", line 93, in work_on_cell
    worker.work()
  File "C:\Python27\Download\PokemonGo-Bot\pokemongo_bot\cell_workers\move_to_fort_worker.py", line 30, in work
    self.stepper._walk_to(self.config.walk, *position)
  File "C:\Python27\Download\PokemonGo-Bot\pokemongo_bot\stepper.py", line 88, in _walk_to
    alt, False)
  File "C:\Python27\Download\PokemonGo-Bot\pokemongo_bot\stepper.py", line 102, in _work_at_position
    response_dict = self.api.call()
  File "c:\python27\download\pokemongo-bot\src\pgoapi\pgoapi\pgoapi.py", line 81, in call
    response = request.request(api_endpoint, self._req_method_list, player_position)
  File "c:\python27\download\pokemongo-bot\src\pgoapi\pgoapi\rpc_api.py", line 98, in request
    raise NotLoggedInException()
pgoapi.exceptions.NotLoggedInException

**Comment by MeGaPk** [comment]
Temp fix:
Just make bash script (if windows or mac):
```#!/bin/bash
while true
do
  ./pokecli.py
  echo ">pokecli exited... restarting...";
  sleep 5;
done```

And fixed :D

**Comment by xiejiachen** [comment]
Excuse me, what bash script?

Just input that in terminal every time before running, right?

**Comment by MeGaPk** [comment]
create file "start.sh"
put this
and in terminal
chmod u+x start.sh
./start.sh

**Comment by xiejiachen** [comment]
Should I type 
'''
chmod u+x start.sh
./start.sh
'''
Every time before I run it?

**Comment by leovarmak** [comment]
Same issue. What to do ?

**Comment by ReqMid** [comment]
same here :") what should i do in win10 ?

**Comment by MeGaPk** [comment]
So...
Because pokecli.py have exception and he dropped. I recommend use "auto restart" script, for now.

So, for linux or mac you need create file in folder, where you have pokecli.py, for example start.sh with this data:
```
#!/bin/bash
while true
do
  ./pokecli.py
  echo ">pokecli exited... restarting...";
  sleep 5;
done
```
Okay, now need give permission for this file from terminal / console:
```
chmod u+x start.sh
```
And next time, you need start only 
```
./start.sh
```



For windows, you need create file in folder where "pokecli.py" with name, for example start.bat with this data:
```
@echo off
:begin
python2 pokecli.py
goto begin
```

and start, your file "start.bat".

**Comment by ironbishop** [comment]
duplicate of #906

**Comment by TheGoldenXY** [comment]
Syntax error line 6 "done"
I am using Ubuntu, Linux. Please fix the syntax error
26. jul. 2016 12:24 skrev Ivan Gaydamakin <notifications@github.com>:So...
Because pokecli.py have exception and he dropped. I recommend use "auto restart" script, for now.

So, for linux or mac you need create file in folder, where you have pokecli.py, for example start.sh with this data:

#!/bin/bash
while true
do
  ./pokecli.py
  echo ">pokecli exited... restarting...";
  sleep 5;
done


Okay, now need give permission for this file from terminal / console:

chmod u+x start.sh


And next time, you need start only 

./start.sh


For windows, you need create file in folder where "pokecli.py" with name, for example start.bat with this data:

@echo off
:begin
python2 pokecli.py
goto begin


and start, your file "start.bat".

**Comment by Spycomb** [comment]
how about running the commandon supervisord?

**Comment by leovarmak** [comment]
@MeGaPk I get this error on LInux `-bash: ./start.sh: /bin/bash^M: bad interpreter: No such file or directory`

**Comment by MeGaPk** [comment]
@leovarmak 
You have unknown symbols in first line your file. Try delete and write manually this line, or:
install dos2unix program and 
dos2unix start.sh

**Comment by leovarmak** [comment]
@MeGaPk will try and let you know

**Comment by castiliad** [comment]
@MeGaPk The bot runs just fine when started with `python pokecli.py` or `./pokecli.py` but only when using the shell script to run the application do I get an import error saying there's no module named google maps. Any idea why this would be happening?

**Comment by MeGaPk** [comment]
@castiliad strange... can you show here your script?

**Comment by castiliad** [comment]
@MeGaPk 

`#!/bin/bash
while true
do
    python pokecli.py
    echo ">Bot crashed. Restarting...";
    sleep 5;
done
`

I've tried using `./pokecli.py` instead of `python pokecli.py` as well

**Comment by MeGaPk** [comment]
@castiliad strange, no have idea... 
Maybe you write to  my skype: ivan6335523, i can help from team viewer or etc?

**Comment by castiliad** [comment]
@MeGaPk I had multiple terminal windows opened and I just tested the script in a different terminal session and it worked just fine now. I'm not sure what happened or why it would do that. Thanks for your help though.

**Comment by dorbenshimol** [comment]
Pokecli.py seems to crash every hour or so, I use Windows 10
I will be greatful if anyone can help me.

**Comment by MeGaPk** [comment]
@dorbenshimol  read my comments in this topic. I have for windows solution too.

**Comment by leovarmak** [comment]
@dorbenshimol yea, the bot crashes a lot on Windows. However as @MeGaPk  saidyou can create a .bat file which will restart the program if the bot fails.

Just create a `start.bat` in the `PokemonGo-Bot` with this content
`@echo off
:begin
python2 pokecli.py
goto begin`
 Now go to CMD and run this by using `start.bat`
This should help

**Comment by TheGoldenXY** [comment]
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/906

/closed

**Comment by Messingaroung2323** [comment]
When I put a start.sh file in the pokebot folder where pokecli.py the bot can no longer run, but I can run the start.sh perfectly in a seperate terminal window. Any ideas what i'm doing wrong?

**Comment by Messingaroung2323** [comment]
I followed these instructions and have the script working to restart correctly, but it is crashing every few minutes checking stops that still have a cool down time left and then crashing now. 
![image](https://cloud.githubusercontent.com/assets/20694819/17266254/cf5f35d6-55aa-11e6-8b43-e61972fa66db.png)

Any ideas?

**Comment by leovarmak** [comment]
@Messingaroung2323 Try pulling the latest master and try it

**Comment by dorbenshimol** [comment]
http://prntscr.com/bzj5uz

2016-07-28 5:38 GMT+03:00 Karthik Varma <notifications@github.com>:

**Comment by leovarmak** [comment]
@dorbenshimol In your script replace the `python2` with `python` . It should work

**Comment by dorbenshimol** [comment]
Thank you soooooo much

2016-07-30 21:46 GMT+03:00 Karthik Varma <notifications@github.com>:

**Comment by tobiashaas** [comment]
Does this also work with an Docker Image ?
`docker run --name=pokego-bot2 --rm -it -v $(pwd)/configs/config-account-user1.json:/usr/src/app/configs/config.json pokemongo-bot1`

Thanks ;-)
