### ISSUE TITLE
[Error] ImportError: No module named pgoapi

### ISSUE THREAD

**Issue by pararang** [PokemonGoF/PokemonGo-Bot#951]
### Expected Behavior
Bot running as usual

### Actual Behavior
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/opt/PokemonGo-Bot/pokemongo_bot/__init__.py", line 13, in <module>
    from pgoapi import PGoApi
ImportError: No module named pgoapi

### Steps to Reproduce
ubuntu@prrng:/opt/PokemonGo-Bot$ python pokecli.py --config config_Bulba.json 
ubuntu@prrng:/opt/PokemonGo-Bot$ python pokecli.py

### Other Information
I have config.json for default account and config_Bulba.json for my other account.
OS: Ubuntu 14.04
Git Commit: 55adefeeb580ed8bb51d097e56a506e2973377c9

**Comment by Calcyfer** [comment]
Is the src folder present? If not, you'll have to reinstall using `pip install -r requirements.txt`

If it is, try `pip install --upgrade -r requirements.txt`

**Comment by pararang** [comment]
@Calcyfer thanks, it works
