### ISSUE TITLE
not spinning forts with non ascii char in names

### ISSUE THREAD

**Issue by wcrwcr** [PokemonGoF/PokemonGo-Bot#96]
or smthing like that. 

Raising UnicodeEncodeError here
File "D:\pokemonbot\cell_workers\seen_fort_worker.py", line 38, in work
  print('Now at Pokestop: ' + fort_details['name'] + ' - Spinning...')

works fine when `fort_details['name']` removed

**Comment by douglascamata** [comment]
@wcrwcr acknowledge. Should be easy to fix, but I gotta sleep now. Tomorrow I check it.
