### ISSUE TITLE
Option to change pokemon to candy, if higher level already

### ISSUE THREAD

**Issue by silelmot** [PokemonGoF/PokemonGo-Bot#960]
hello,
no problem, just a question or a request.
is it already possible, that the bot doesnt carry 2 or more of the same kind but trades the lower ones?
if not... would be great!

**Comment by TheGoldenXY** [comment]
This feature is already implemented.

Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

Closing this for now.

/closed
