### ISSUE TITLE
switch fail on startup

### ISSUE THREAD

**Issue by hklcf** [PokemonGoF/PokemonGo-Bot#962]
![image](https://cloud.githubusercontent.com/assets/410302/17133999/f84d5f74-535a-11e6-9400-aadb0467382c.png)

aa47f667196cad02ad2d566ccbe5be5cc1be8827

**Comment by slonce** [comment]
And? Your inventory bag and pokemon full what bot can do?)

**Comment by mehdi-S** [comment]
@slonce normally, switch to catch mode, not crash

**Comment by Zgrkaralar** [comment]
@mehdi-S not possible this condition because pokemon bag and inventory is full

@hklcf clean your pokemon bag

**Comment by ironbishop** [comment]
The bot could run a recycle/transfer/evolve cycle on the bags, in order to free space, so this could become a feature request.

But it does already recycle every time you collect something recyclable, and transfer every time you catch something transferable, so we are running out of options here :)
