### ISSUE TITLE
No Module Named Requests

### ISSUE THREAD

**Issue by sohamdodia** [PokemonGoF/PokemonGo-Bot#963]
Traceback (most recent call last):
  File "pokecli.py", line 38, in <module>
    import requests
ImportError: No module named requests

Getting this error while i try to run python pokecli.py from terminal.

**Comment by MeGaPk** [comment]
pip install requests

**Comment by ariefbayu** [comment]
or, in my case (after closing terminal window), `source bin/activate`, before `python pokecli.py`

**Comment by sohamdodia** [comment]
I have tried pip install and it says requests are already installed. But still I am getting this error.

**Comment by veynor** [comment]
if you're like me you forgot that your pip is python2 and python -> python3. Try python2 pokecli.py
Ignore if not on linux/mac

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
