### ISSUE TITLE
Develop Build Error

### ISSUE THREAD

**Issue by TheGoGlider** [PokemonGoF/PokemonGo-Bot#964]
### Expected Behavior
I expected it to work properly, I had a stable/master version I guess and it kept showing an error which says "Unkown Spinning". that error comes after 15 mins of uptime and was frustrating. I tried the develop build and I followed basically everything in the wiki guide, except the `source venu/bin/activate` wasn't working. It says there is no internal or external command known as source. When I try to run the develop build with `python pokecli.py` it gives me a random error and doesn't even start the bot.

### Actual Behavior
Here is the link to the error: [Error](http://imgur.com/a/FdI8B)
Another problem is there is no file in /configs named `release_config.json.example`, but [this.
](http://imgur.com/a/v9zDc) I don't know if its supposed to be like that or no.
### Steps to Reproduce
I tried to do all the steps again mentioned in wiki and even reinstalled the develop build but it didn't fix the isssue

### Other Information
OS: Windows 10
Git Commit: (c4c34875c7af8d8ffdcc18e76b0ea0f0146c2422)

**Comment by bimahp** [comment]
have you already configure config.json file on the 'configs' folder?

**Comment by TheGoGlider** [comment]
Yeah, I have edited both the files in fact.

**Comment by tpmodding** [comment]
i hat the same issues with the source command, just use the windows command tool for all commands except the source-command, for this use the git-bash (right click in the folder then "git bash here" then it works :)

but i get then an nother error...
[12:48:18]
[12:48:18] Attempting login to Pokemon Go.
[12:48:19] Login to Pokemon Go successful.
Traceback (most recent call last):
  File "pokecli.py", line 250, in <module>
    main()
  File "pokecli.py", line 236, in main
    bot.start()
  File "C:\Users\User\Desktop\pokemon\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 31, in start
    self._setup_api()
  File "C:\Users\User\Desktop\pokemon\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 275, in _setup_api
    self._print_character_info()
  File "C:\Users\User\Desktop\pokemon\PokemonGo-Bot-dev\pokemongo_bot\__init__.py", line 295, in _print_character_info
    player = response_dict['responses']['GET_PLAYER']['player_data']
TypeError: 'bool' object has no attribute '__getitem__'

C:\Users\User\Desktop\pokemon\PokemonGo-Bot-dev>

i used git pull to update, made my config.json but it doesn't work...should i load the whole dev as new zip or is git pull enough?

**Comment by TheGoGlider** [comment]
tried doing the source thing in git bash but here is the [result](http://imgur.com/a/wXDZf)

**Comment by tpmodding** [comment]
i said ONLY the source thing in git bash...as you can read the command above didnt work...open your eyes dude x)

**Comment by TheGoGlider** [comment]
Dude xD check again, it says no file or directory

**Comment by tpmodding** [comment]
i checked it, because your command virtualenv didnt workt...as you can see "DOES NOT EXIST" with this your source command doestn work...why dont you only do what i say :D all commands with windows command tool and ONLY the source command in git bash

**Comment by TheGoGlider** [comment]
FFS, I have done all the commands in windows command prompt but only the source command in git bash, it still has that error. Do you understand?????

**Comment by tpmodding** [comment]
yeah then you showed us the wrong screenshot, cool down ;)

**Comment by TheGoGlider** [comment]
No I just wanted to show the source command, but thought why not show the other in git bash as well...

**Comment by tpmodding** [comment]
<img width="750" alt="bildschirmfoto 2016-07-26 um 13 30 45" src="https://cloud.githubusercontent.com/assets/17259976/17136401/60d633ca-5335-11e6-80f8-f6855e8b8f73.png">
hm...was the cmd in the pokemongo bot dir?

**Comment by TheGoGlider** [comment]
yeah

**Comment by TheGoGlider** [comment]
YUPPPPPP THE SOURCE AND VENU COMMAND WORKED but still the same error I got in the starting while doing pokecli.py

**Comment by tpmodding** [comment]
may the same problem like us?
https://github.com/PokemonGoF/PokemonGo-Bot/issues/966

**Comment by TheGoGlider** [comment]
yup, I tried to do that. Now I got another error

**Comment by TheGoGlider** [comment]
http://imgur.com/VlPb8ge new error after downloading the current latest version!!! BEST

**Comment by Ph4i1ur3** [comment]
What's your config.json look like?

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
