### ISSUE TITLE
IndentationError: unexpected indent

### ISSUE THREAD

**Issue by BScreen** [PokemonGoF/PokemonGo-Bot#965]
### Expected Behavior
Bot should start up as usual

### Actual Behavior
After running the bot earlier today I tested some of the PRs, but reverted back to the original master branch. Now I keep getting the same error and can't fix it myself, since I'm only slowly getting the hang of python.
After doing
```
python pokecli.py
```

I get the following message:
```
Traceback (most recent call last):
  File "pokecli.py", line 39, in <module>
    from pokemongo_bot import logger
  File "/Users/***/Desktop/PokemonGo-Bot/pokemongo_bot/__init__.py", line 89
    forts.sort(key=lambda x: distance(self.position[
    ^
IndentationError: unexpected indent
```

I hope you guys can help me.

### Steps to Reproduce
```
$ git clone -b master https://github.com/PokemonGoF/PokemonGo-Bot  
$ cd PokemonGo-Bot  
$ virtualenv .  
$ source bin/activate  
$ pip install -r requirements.txt
$ git submodule init
$ git submodule update
```

### Other Information
OS: OS X El Capitan 10.11.6
Git Commit: 32cefeed4760d6b5d2b3eb76d783d0f13d068e83

**Comment by Godsend72** [comment]
Delete the space in line 90. Line 89 should look like this:
89: forts.sort(key=lambda x: distance([0], self.position[1], x['latitude'], x['longitude']))

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
