### ISSUE TITLE
i open git and can't run pip

### ISSUE THREAD

**Issue by howldy** [PokemonGoF/PokemonGo-Bot#975]
it said "bash: pip: command not found"
how to fix it , sry im newbie

**Comment by hklcf** [comment]
install pip

**Comment by pararang** [comment]
@howldy install it with `python get-pip.py` on your command line or terminal.

**Comment by howldy** [comment]
@pararang it said "Requirement already up-to-date: pip in c:\python27\lib\site-packages"
show me the way please, ty for being generous.

**Comment by TheGoldenXY** [comment]
Please upgrade to the latest `dev` branch by running this command:
```
git reset --hard
git pull -f
```

Then run this command:
`pip install --upgrade -r requirements.txt`

If issue persists, open a new issue.

/closed
