### ISSUE TITLE
bot crash : IndexError: list index out of range

### ISSUE THREAD

**Issue by mehdi-S** [PokemonGoF/PokemonGo-Bot#976]
### Expected Behavior
do what a bot do normally

### Actual Behavior
bot work for few seconds, catch pokemon, then fall into

```
[08:01:50] Scanning area for objects....
[08:01:50] Walking from (48.893666, 2.390437) to [48.893666, 2.390437] 0.00km
[08:01:52] Attempting to evolve all pokemons ...
[08:01:53] Scanning area for objects....
[08:01:53] Walking from (48.893666, 2.390437) to [48.893666, 2.390437] 0.00km
```
```
Traceback (most recent call last):
  File "pokecli.py", line 250, in <module>
    main()
  File "pokecli.py", line 241, in main
    bot.take_step()
  File "/root/PokemonGo-Bot-pokemonbot94/pokemongo_bot/__init__.py", line 36, in take_step
    location = self.navigator.take_step()
  File "/root/PokemonGo-Bot-pokemonbot94/pokemongo_bot/spiral_navigator.py", line 49, in take_step
    point = self.points[self.ptr]
IndexError: list index out of range
```
### Steps to Reproduce
git clone latest build on dev branch
doing initial step
configuration that might be usefull for testing :
```
...
"location": "48.893666,2.390437"
...
"max_steps": 1
...
"walk": 4.16
...
"location_cache": true
"distance_unit": "km"
...
```
launch

### Other Information
OS: Debian x64_86
Git Commit: 4555466ed1801f401e99670b17a9c98f4cb4ebb9

**Comment by mehdi-S** [comment]
**update

in 27fa1d53760aa1a0068cedbf799c361c264de72f
change where made to solve the problem, but now the bot cannot parse a location of type 
`"location": "48.893666,2.390437"`

what format should i use ?

**Comment by tstumm** [comment]
@mehdi-S I tried the same coordinates and for me it's working. Do you really have the newest commit?

**Comment by mehdi-S** [comment]
##update

now on : 6a9e74c91b9f5234f74c0cb09ec2568f1f37f01f

after your merge @tstumm **_parse location_** error gone away
but `IndexError: list index out of range` error is still here

**Comment by tstumm** [comment]
increase `max_steps` in configuration

**Comment by mehdi-S** [comment]
## solution : 

in config.json file put a max_steps of 2 or more to work

i suggest to improve the readme accordingly

**Comment by pickerflicker** [comment]
I think even better than a readme would be an appropriate error message. Requiring this field to be >=2 seems arbitrary and most people will gloss over it. I set max_steps to 1 to try to "camp out" more in an area.

**Comment by mehdi-S** [comment]
yes but it seems to not work fine when the maxstep is at 1
