### ISSUE TITLE
Incorrect number of Pokemon post use

### ISSUE THREAD

**Issue by decix** [PokemonGoF/PokemonGo-Bot#98]
After using the bot and stopping the program using SIGINT and logging in the pokemon displayed vs. the number of pokemon I supposedly have are different.

![image](https://cloud.githubusercontent.com/assets/6101512/17042324/8431e058-4f61-11e6-8843-ec86a4a1484f.png)

**Comment by eggins** [comment]
Complete the setup tutorial - pick your starter
Log out and back in afterward

**Comment by Bashin** [comment]
Just to clarify: eggs use a pokemon inventory slot
So 1 Paras + 3 eggs = 4 / 250
Nothing to do with the bot

**Comment by decix** [comment]
Ah, didn't realize the eggs took spots. Thanks.
