### ISSUE TITLE
Detectability: Heartbeat interval should match app

### ISSUE THREAD

**Issue by bstpierr** [PokemonGoF/PokemonGo-Bot#981]
Currently, the bot performs a heartbeat whenever work_on_cell is complete, which is unlikely to be the same interval as the retail app.

**Comment by tstumm** [comment]
So whats the interval of the retail app?

**Comment by bstpierr** [comment]
When standing still, it only seems to update when a Pokemon expires or after you've interacted with something (caught a Pokemon, spun a stop, tapped on a gym). When moving around, it appears as though it's part of the get_map_objects call (probably to batch the calls).

More investigation is needed though, since this is mostly just me watching for when the spinner happens and noticing when my egg hatch notification comes up (which is part of the heartbeat in the app).

This issue should track using the MITM proxy on the app to observe exactly what the app does and its implementation. It's also possible that someone on /r/pokemongodev or /r/pokemongobotting has done this research already.

**Comment by TheGoldenXY** [comment]
PR are welcome. Closing this for now.

/closed
