### ISSUE TITLE
Detectability: Bot stands perfectly still while catching Pokemon

### ISSUE THREAD

**Issue by bstpierr** [PokemonGoF/PokemonGo-Bot#983]
In the app, you can move around while catching Pokemon and the app continues to update the location with the server.

Not only does standing perfectly still during catching look fishy, it's also a waste of time. The bot could continue moving towards its next target (as a human would).

**Comment by JohnnyOmm** [comment]
So just close your damn app and leave the bot running

**Comment by mehdi-S** [comment]
@JohnnyOmm  ??

suggest to be an improvement

**Comment by VictorChen** [comment]
I don't think it looks fishy, I know tons of people who would stop to catch a pokemon (especially with AR on)

**Comment by bstpierr** [comment]
I'm certain it looks strange to anyone looking at the server logs. When catching Pokemon, the app sends up periodic changes in location. Even just a few inches to a feet in difference.

Without these location updates, it would be pretty easy to detect a botting account.

**Comment by Eilyre** [comment]
Most people I've seen do stop to catch a pokemon, to properly get the throw off. I'm not sure how the bot's logic works though, does it still update the server with location periodically while catching or not.

**Comment by TheGoldenXY** [comment]
PR are welcome. Closing this for now.

/closed
