### ISSUE TITLE
Detectability: Bot traverses water/buildings/impassable terrain

### ISSUE THREAD

**Issue by bstpierr** [PokemonGoF/PokemonGo-Bot#984]
If a human were to look at the path taken by the bot, it would be obvious that location spoofing is being used.

We should consider using the gmaps Waypoint API https://developers.google.com/maps/documentation/directions/intro#Waypoints possibly using Polyline encoding (https://developers.google.com/maps/documentation/utilities/polylinealgorithm) to enable pathing of multiple targets.

**Comment by mehdi-S** [comment]
duplicate of issue https://github.com/PokemonGoF/PokemonGo-Bot/issues/944

**Comment by bstpierr** [comment]
I think this is more of a superset bug than #944 since I'm also concerned with walking through walls and off cliffs.

**Comment by tstumm** [comment]
We already have the polyline algorithm down, it just needs implementation

**Comment by douglascamata** [comment]
Please, guys, search a little before creating more issues, take a look at pull requests.... we already have the issue tracked WAY TOO SPAMMED. Help us to be able to read all the issues by not duplicating.

**Comment by TheGoldenXY** [comment]
Duplicate of https://github.com/PokemonGoF/PokemonGo-Bot/issues/944

/closed
