### ISSUE TITLE
web module not downloading after submodule update

### ISSUE THREAD

**Issue by ayiire** [PokemonGoF/PokemonGo-Bot#985]
### Expected Behavior
Web folder should populate with files

### Actual Behavior
Web folder is created but nothing is downloaded to it

### Steps to Reproduce
$ git submodule update
error: no such remote ref 12007bea09011fb9fbb93624728b994a60fc9c78
Fetched in submodule path 'web', but it did not contain 12007bea09011fb9fbb93624728b994a60fc9c78. Direct fetching of that commit failed.

### Other Information
Dev Branch
OS: Win10
Git Commit: commit 6a9e74c91b9f5234f74c0cb09ec2568f1f37f01f

**Comment by bstpierr** [comment]
I'm also getting this in a new setup of the dev branch.

**Comment by hklcf** [comment]
run `git clone https://github.com/OpenPoGo/OpenPoGoWeb.git web` inside your bot folder

**Comment by AlixBa** [comment]
can you try this one? https://github.com/PokemonGoF/PokemonGo-Bot/pull/987

**Comment by surfaace** [comment]
merged pr
