### ISSUE TITLE
The bot catch all pokemons but don't release anyone - Solved

### ISSUE THREAD

**Issue by crusardri** [PokemonGoF/PokemonGo-Bot#993]
### Expected Behavior

Catch all pokemons and release all pokemons with some conditions

### Actual Behavior

Catch all and don't release nothing

### Steps to Reproduce

config
"catch": {"any": {"catch_above_cp": 1, "catch_above_iv": 0.1, "logic": "and"}},
"release": {
    "Any": {"release_under_cp": 300, "release_under_iv": 0.8, "cp_iv_logic": "or" },
    "Machop": { "release_under_cp": 381, "release_under_iv": 0.8, "cp_iv_logic": "or" },
    "Sandshrew": { "release_under_cp": 400, "release_under_iv": 0.99, "cp_iv_logic": "or" }
}

### Other Information
OS: Windows 10
Last dev
Console LOG
[15:23:56] A Wild Machop appeared! [CP 400] [Potential 0.67]
[15:23:56] IV [Stamina/Attack/Defense] = [8/7/15]
[15:23:59] Using Pokeball (chance: 40.01%)... (123 left!)
[15:24:05] Captured Machop! [CP 400] [8/7/15]
[15:24:11] A Wild Sandshrew appeared! [CP 383] [Potential 0.4]
[15:24:11] IV [Stamina/Attack/Defense] = [3/14/1]
[15:24:14] Using Greatball (chance: 46.80%)... (19 left!)
[15:24:14] Captured Sandshrew! [CP 383] [3/14/1]
![image](https://cloud.githubusercontent.com/assets/4596106/17139597/71fd9b6a-5345-11e6-9e15-9705b9d71391.png)

**Comment by TCB13** [comment]
I'm running ff665d625c028d490fe9d2fd4e6b0b8c10a2d9c9 (2 or 3 commits ago) and this issue doesn't seem to exist.

**Comment by mizhgan** [comment]
Replace `release_under` with `release_below`

**Comment by crusardri** [comment]
@mizhgan Ok, al right. Thanks mate

**Comment by hklcf** [comment]
@mizhgan whats diff between `release_under` and `release_below` :question:

**Comment by TCB13** [comment]
@hklcf the latest version of the bot uses `release_below` instead of `release_under`.

**Comment by hklcf** [comment]
@TCB13 :ok: thanks
why no one update the sample config file :smiley:

**Comment by TCB13** [comment]
@hklcf It is up to date... https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/configs/config.json.example maybe you just copied your old version while updating?

**Comment by hklcf** [comment]
@TCB13 haha, because im using this one
https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/configs/config.json.pokemons.example

**Comment by TCB13** [comment]
@hklcf #980 seems to fix this.
